### ISSUE TITLE
Option to use iTunes Store API to retrieve artwork and/or metadata

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#1]
I would love the option to download the artwork and/or show artwork from the iTunes store instead / as well as The TVDB. I will look in to writing a patch for this.

For reference see http://www.apple.com/itunes/affiliates/resources/documentation/itunes-store-web-service-search-api.html and as an example https://itunes.apple.com/search?term=Breaking+Bad&attribute=tvSeasonTerm&entity=tvEpisode

**Comment by viearical** [comment]
Does anybody know how or what Subler (https://bitbucket.org/galad87/subler) uses to pull meta data from the iTunes store?  That app seems to bee pretty reliably querying all the meta data and full size art work for shows and movies.
