### ISSUE TITLE
Title Metadata Request

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1000]
Would it be possible to add a option to make the title metadata of the mp4 file the same as the renamed file name? 

Or even a setting to wipe all metadata except the audio video track data.

As of now I have been having to do it manually with this bat: 

```
mkdir output

for %%a in (*.mp4) do ffmpeg -i "%%a" -map 0:v -map 0:a? -map 0:s? -map_metadata:g -1 -c copy -metadata title="%%~na" "output\%%~a"
```

Then rerunning the automator.

I understand you can disable plex metadata as a bandaid fix.

**Comment by mdhiggins** [comment]
Not a planned feature, title is set based on TVDB / TMDB
You could write a post processing script and tie into mutagen if you wanted to adjust tagging behavior though including whip and custom sources
See the tvdb_mp4 / tmdb_mp4 files for how a tagging script can work
