### ISSUE TITLE
.webm files "is not in the correct format"

### ISSUE THREAD

**Issue by tjesp** [mdhiggins/sickbeard_mp4_automator#1003]
Is this only supposed to work with mkv?

I have tried to convert a .webm video file and this is what I get:

File Eco-friendly traveling - TheTravelBook.webm is not in the correct format

ffprobe correctly identifies it. It also plays fine in video players.

This is on a Mac, but I have seen similar on Ubuntu.

**Comment by mdhiggins** [comment]
You can open extensions.py and modify what is supported in this way, but webm isn’t a tested format though in theory should work

From: tjesp
Sent: Wednesday, April 24, 2019 3:56 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] .webm files "is not in thecorrect format" (#1003)

Is this only supposed to work with mkv?
I have tried to convert a .webm video file and this is what I get:
File Eco-friendly traveling - TheTravelBook.webm is not in the correct format
ffprobe correctly identifies it. It also plays fine in video players.
This is on a Mac, but I have seen similar on Ubuntu.

**Comment by tjesp** [comment]
Your suggestionb seemed to work.
