### ISSUE TITLE
deluge post process not converting all files in folder

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1004]
I currently have a batch script configured to unrar all files and then to call the delugePostprocess.py script. Some downloaded files included a sample if the root of the torrent files list and a bunch of archives. The only file that gets processed for conversion is only what was in the original torrent list regardless files that now exist after extraction.

I would like to request assistance with getting the delugePostprocess.py file to instead target the root folder itself which I believe would solve my problem.

Batch file being called by deluge is:

> #!/bin/sh
> 
> torrentid=$1
> torrentname=$2
> torrentpath=$3
> 
> /opt/deluge/unrarall/unrarall -q "$torrentpath"/"$torrentname"
> wait $!
> python /opt/mp4automator/delugePostProcess.py $torrentid $torrentname $torrentpath
> 
> exit

Sample from deluge log file where the sample file is the only thing converted:

> 2019-04-24 06:30:59 - delugePostProcess - INFO - Deluge post processing started.
> 2019-04-24 06:30:59 - readSettings - INFO - /usr/bin/python
> 2019-04-24 06:30:59 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2019-04-24 06:30:59 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
> 2019-04-24 06:30:59 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
> 2019-04-24 06:30:59 - delugePostProcess - INFO - Successfully connected to Deluge
> 2019-04-24 06:30:59 - delugePostProcess - INFO - Converting file /dwnldr/tor/comp/movie/MOVIE_NAME/Sample/MOVIE_NAME.sample.mkv at location /dwnldr/tor/comp/movie/MOVIE_NAME-convert.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Reading video stream.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Video codec detected: h264.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Profile: High.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Reading audio streams.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to > default
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Reading subtitle streams.
> 2019-04-24 06:31:00 - mkvtomp4 - INFO - Starting conversion.
> 2019-04-24 06:31:03 - mkvtomp4 - INFO - /dwnldr/tor/comp/movie/MOVIE_NAME-convert/MOVIE_NAME.sample.mp4 created.
> 2019-04-24 06:31:04 - delugePostProcess - INFO - Passing /dwnldr/tor/comp/movie/MOVIE_NAME-convert directory to Radarr.
> 2019-04-24 06:31:04 - autoprocess.radarr - INFO - Radarr notifier started.
> 2019-04-24 06:31:04 - autoprocess.radarr - INFO - Requesting Radarr to scan directory '/dwnldr/tor/comp/movie/MOVIE_NAME-convert'.
> 2019-04-24 06:31:04 - autoprocess.radarr - INFO - Radarr response: queued.
> 2019-04-24 06:31:04 - delugePostProcess - ERROR - Unable to delete temporary directory.
> Traceback (most recent call last):
>   File "/opt/mp4automator/delugePostProcess.py", line 142, in <module>
>     os.rmdir(delete_dir)
> OSError: [Errno 39] Directory not empty: '/dwnldr/tor/comp/movie/MOVIE_NAME-convert'

**Comment by mdhiggins** [comment]
delugePostProcess works by tying directly into the file list provided by deluge so if you're using scripts to unRar before hand that list will be incomplete. Suggest using completed download handling and having the conversion just be down by the postSonarr/postRadarr/etc scripts
