### ISSUE TITLE
Videotoolbox support

### ISSUE THREAD

**Issue by tjesp** [mdhiggins/sickbeard_mp4_automator#1006]
Is it possible you can add Videotoolbox support for hardware acceleration for Mac users:

https://forum.videohelp.com/threads/386398-ffmpeg-videotoolbox-options

?

**Comment by D1ag0nall3y** [comment]
let me know if anyone figures this out

**Comment by mdhiggins** [comment]
Added

Set your codec to `h264_videotoolbox`
Make sure you still include h264 in your codec list so you don't end up re-transcoding existing H264 files though

**Comment by AnilDaoud** [comment]
could you add the same for hevc_videotoolbox?

`% ffmpeg -hide_banner -h encoder=hevc_videotoolbox`
> Encoder hevc_videotoolbox [VideoToolbox H.265 Encoder]:
>     General capabilities: delay hardware 
>     Threading capabilities: none
>     Supported pixel formats: videotoolbox_vld nv12 yuv420p p010le
> hevc_videotoolbox AVOptions:
>   -profile           <int>        E..V...... Profile (from 0 to 3) (default 0)
>      main            1            E..V...... Main Profile
>      main10          2            E..V...... Main10 Profile
>   -allow_sw          <boolean>    E..V...... Allow software encoding (default false)
>   -require_sw        <boolean>    E..V...... Require software encoding (default false)
>   -realtime          <boolean>    E..V...... Hint that encoding should happen in real-time if not faster (e.g. capturing from camera). (default false)
>   -frames_before     <boolean>    E..V...... Other frames will come before the frames in this session. This helps smooth concatenation issues. (default false)
>   -frames_after      <boolean>    E..V...... Other frames will come after the frames in this session. This helps smooth concatenation issues. (default false)
