### ISSUE TITLE
Bit Depth

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1007]
I've come across files that are 10 bit and are not directly streamable due to the automator not having an option to force 10 bit videos down to 8 Bit.

Any way to implement that?

**Comment by mdhiggins** [comment]
I believe this is all handled by the pixfmt which the script already supports as a configurable option
https://askubuntu.com/questions/997507/ffmpeg-how-do-i-convert-x265-10bit-to-x265-8bit
