### ISSUE TITLE
Does manual.py check to see if conversion is needed before converting

### ISSUE THREAD

**Issue by ckought** [mdhiggins/sickbeard_mp4_automator#1008]
I'm using Sonarr & SABnzbd.  I have sickbeard_mp4_automator running, and everything goes well 99%+ of the time.  But, sometimes it looks like sickbeard_mp4_automator dies part way through a conversion (it leaves a QTFS file that's somewhat smaller than the mp4 that it was doing the atom moov on).

I'd like to be able to run manual.py at the top of my TV folders and have it propagate through the folders and convert any that need conversion.  The thing is, I don't want it to try and re-convert ones that don't need it - only convert ones that the need it (ones that the moov atom isn't at the front).

Does it check to see if an mp4 file NEEDS conversion before it starts the conversion process on it?  Re-converting 12K+ files when only a couple dozen actually need conversion wouldn't be a productive way of doing things.

**Comment by Geordon** [comment]
I've been using the script for a couple of years, and unless you use -cmp4 to force re-conversion of the file, it doesn’t convert files that have already been converted.  

It also checks to see if the moov atom is at the front of the file, and if it is, the script notes that it's already there and skips it.

I actually use the manual script to process gobs of files in a given directory structure (tag -cmp4 -i ./Processing/ -a) frequently.  The -cmp4 flag forces the script to do a full conversion on the file even if it's already all set.  Leaving it out (tag -i ./Processing/ -a) allows the script to check the file, note if it's already got the moov atom at the start of the file, and skip the file if it's there.

**Comment by mdhiggins** [comment]
Pushed an update that adds an additional conversion check that will bypass conversion is all codecs are determined to be 'copy' appropriate for files that have the same input and output extension
Now if you scan an mp4 that has all streams in the correct codec it should catch this and bypass an unneeded conversion

**Comment by uchagani** [comment]
@mdhiggins can we have an option to copy unconverted movies to the final `output_directory` if a file doesn't need conversion.  I'm batch converting a ton of file and moving the converted files to a "completed" directory.  This causes the files that don't need conversion to remain in the source directory and converted files moved to the `output_directory`.  Would be nice to have a complete set in the `output_directory`
