### ISSUE TITLE
Official Docker support

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1012]
So after the very [first question about Docker](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/412) in this git, is there already anything official? Docker is mature now and it's the first time I'm trying it. I have Sonarr, Radarr, Plex, and NZBGet in their own containers and I still don't know how to integrate this automator :(

**Comment by kevindd992002** [comment]
@mdhiggins 

Sorry, I just noticed that you already provided Sonarr and Radarr docker with your automator built-in. Is there any disadvantage to having the media managers handle the conversion as opposed to having the downloaders do it? 

In Windows, I've had SAB handle the conversion before it notifies Sonarr/Radaar to complete the download and I just let the media managers notify Plex to do a library scan. Now that I'm using Debian/Docker, I'm very new to this and would want to incorporate your automator into the mix.

I hope you can help me out here.

**Comment by kevindd992002** [comment]
Also, would both your containers be maintained to always reflect them using the latest image from LSIO?

**Comment by mdhiggins** [comment]
Containers are maintained and automatically updated, or at least they should be based on how I have the docker containers configured

The notification system having SAB trigger the scan is more or less a relic from the way things were done before Sonarr/Radarr and is included for legacy support. Completed download handling is more reliable and offers other nice advantages such as progress monitoring and better handling of failed downloads.

The one advantage of the old method is that you could convert the files before they were passed back potentially in a different location than your final media destination. All my files are on the same RAID array so it doesn't matter for my setup, but some people may do the conversion on a different drive or computer before passing the files back to Sonarr/Radarr. When using completed download handling you don't get that option

**Comment by kevindd992002** [comment]
Ok. That advantage would be beneficial to my setup because I process everything on an SSD then have NZBGet transfer the file to a mergerFS disk pool. With Sonarr/Radare doing the conversion, the conversion happens when the files are already in their final destinations. 

Sonarr/Radarr does the conversion one at a time, right? Because if not, that will be a problem when the script notifies Plex of a library rescan while one or more files are still being converted.

Also, I miss how SAB includes the logs of the post-process script in the notification emails I receive for the jobs. Is there a way to do this in Sonarr/Radarr with your docker containers?

**Comment by kevindd992002** [comment]
Also, everytime there's a new feature/parameter available in the autoProcess.ini, how would my ini be updated with it? Is this automatic?

Why is it that in your docker compose yml file, you specified the "ro" tag for autoProcess.ini when it should be writable?

**Comment by mdhiggins** [comment]
Should be writable, fixed that in later versions
Script automatically creates the option in the default setting

**Comment by kevindd992002** [comment]
I see.

How about my other questions?

Sonarr/Radarr does the conversion one at a time, right? Because if not, that will be a problem when the script notifies Plex of a library rescan while one or more files are still being converted.

Also, I miss how SAB includes the logs of the post-process script in the notification emails I receive for the jobs. Is there a way to do this in Sonarr/Radarr with your docker containers?
