### ISSUE TITLE
Docker Sonarr taking a long time converting/creating mp4

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1014]
Here's my autoProcess.ini contents: https://pastebin.com/Mn6Mib89

The first file that was converted took less than 1 minute to finish. The second file is still running until now (after 30+ minutes) and it's just a 1.35GB.

Logs for the 1st conversion: https://pastebin.com/QvwhGxri
Logs for the 2nd conversion: https://pastebin.com/ddSrcwP1 (Updated logs: https://pastebin.com/2J9q0dcj)

Is this because I have subtitle embedding enabled? If so, then the 1st file conversion should've taken very long too, right?

**Comment by mdhiggins** [comment]
It probably has to do with how many streams are being encoded vs copied
From the logs its tough to see but the video stream will have the most impact and could account for the time difference you're reporting

**Comment by kevindd992002** [comment]
Right but why would it copy the video stream if it already detects it as h264?

**Comment by mdhiggins** [comment]
There are a number of reasons the video stream could be converted even if the codec is correct

Bitrate or size limitations (dimensions), pixmap profiles not matching; it all depends on your autoProcess.ini settings

I'm also not sure if your video stream was copied or not from these logs you've posted, it may be just the audio encoding that slowed things down especially if you're running on more modest hardware

**Comment by kevindd992002** [comment]
Could it be because I have my video profile set to High and h264 level to 4.1?

If it was the audio stream causing it, then I would have the same long conversion problem with the other, won't I?

**Comment by mdhiggins** [comment]
It could
If you enable debug level logging (this can be done via logging.ini, uses standard python logging) and check those logs you'll get way more detail about why copying isn't happening

```
        self.log.info("Profile: %s." % info.video.profile)
        if self.video_profile and info.video.profile.lower().replace(" ", "") not in self.video_profile:
            self.log.debug("Video profile is not supported. Video stream can no longer be copied.")
            vcodec = self.video_codec[0]
            vprofile = self.video_profile[0]
            if self.pix_fmt:
                pix_fmt = self.pix_fmt[0]
        else:
            vprofile = None
```

That's the relevant code for video profile
If you're curious as to how all this is handled, review the mkvtomp4.py file

**Comment by mdhiggins** [comment]
Actually looking at your 1st and 2nd logs, 1st was 'high' and second was 'main'

That's probably why you're converting video
You can either leave that blank if you don't care about profile or you can add other profiles as acceptable variants
video-profile = high, main

**Comment by kevindd992002** [comment]
Oh ok. Got it. If you leave a parameter in the ini blank, what are the defaults? Some parameters in the readme don't have their defaults stated.

**Comment by mdhiggins** [comment]
It simply won't be specified or evaluated against

**Comment by kevindd992002** [comment]
In Linux, how do I know if it's using the full potential of my hardware when ffmpeg/your script is converting the media file? My CPU is the Intel Pentium J5005 which has Intel Quicksync. Does it automatically use that to convert the video?

Also, since my hardware is relatively new and the current Debian Stretch Backport Kernel still doesn't recognize the GuC/HuC firmwares for this, does that have any effect in the whole conversion process?
