### ISSUE TITLE
Can manual.py be told to automatically skip tagging? 

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1015]
I have a bunch of personal video clips that I want to manually process with manual.py but they are not of anything that would be in one of the databases.  Is there a way to tell manual.py to automatically skip trying to tag the files?

**Comment by mdhiggins** [comment]
-nt, --notag          Overrides and disables tagging when using the
                        automated option


From: Geordon VanTassle
Sent: Monday, June 3, 2019 2:26 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Can manual.py be told toautomatically skip tagging? (#1015)

I have a bunch of personal video clips that I want to manually process with manual.py but they are not of anything that would be in one of the databases. Is there a way to tell manual.py to automatically skip trying to tag the files?

**Comment by Geordon** [comment]
Thank you so much!  I didn't recall seeing it under the manual.py instructions or in the --help.

Thank you!
