### ISSUE TITLE
Force Eng as default stream??

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#1016]
I've a movie which has following:

    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(fre): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(fre): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:4(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s

As you can see the default is French audio and sub.
How can I make sickbeard automator make the language audio and substitles English by default??

**Comment by mdhiggins** [comment]
Pushed an update to the way defaults are handled, now it will set the first occurrence of the audio-default-language and subtitle-default-language as the default track

**Comment by kevindd992002** [comment]
If I use the Docker containers, I guess I won't do anything other than update the container to get this updated, correct?

**Comment by mdhiggins** [comment]
Rebuilding the docker hub images as we speak

**Comment by kevindd992002** [comment]
Right, yes, I use Watchtower to auto-rebuild my images if there's a newer version and this is checked daily at 6:00AM my time. So all good.
