### ISSUE TITLE
preopts and postopts converted to lowercase 

### ISSUE THREAD

**Issue by mergwyn** [mdhiggins/sickbeard_mp4_automator#1017]
Both of these settings are converted to lower case after they are read. Normally this is not an issue, but caught me out when trying to set probesize to 2048M .

Is there a specific reason why this conversion takes place? I kind of get why it might help for other options, but I suspect that it might be better to pass these two options as is.

I’m happy to prepare a pull request if you think this is sensible.

**Comment by mdhiggins** [comment]
No particular reason other than I didn't realize there was any case sensitive options and that was part of my usual sanitation process. 
Updated to remove this
