### ISSUE TITLE
 MANUAL - INFO - Ignoring {subtitle file}.srt

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1018]
So I decided to convert all my existing mp4 files so that they all have the uniform settings of my autoProcess.ini. Most of my media files have external english srt files with them and when they are converted I always see the "MANUAL - INFO - Ignoring {subtitle file}.srt" message. I have eng set as my default language. What does this message exactly mean?

**Comment by mdhiggins** [comment]
Needs to include the language for external files or they won't be imported
`The.Matrix.1999.eng.srt`
