### ISSUE TITLE
Missing audio track in MP4

### ISSUE THREAD

**Issue by ryangrush** [mdhiggins/sickbeard_mp4_automator#1019]
I'm trying to convert my MVKs to MP4s but the MP4s are always missing the audio track so I'm trying to figure out what I'm doing wrong. I'm doing this on my Synology DSM (Linux) btw.

**autoProcess.ini**
```
[MP4]
ffmpeg = /bin/ffmpeg
ffprobe = /bin/ffprobe
threads = 0
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts =
preopts =
```
I originally had it triggering `postSonarr.py` to do the conversion but for debugging this issue I've been running - 

`python /scripts/sickbeard_mp4_automator/manual.py -i "my_video.mkv" -tv 12345 -s 1 -e 1`

Here is the output -

```
ash-4.3# python /scripts/sickbeard_mp4_automator/manual.py -i "my_video.mkv" -tv 12345 -s 13 -e 1
Manual processor started.
/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
Audio detected for stream #1: eac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: subrip [eng].
Creating subtitle stream 0 from source stream 2.
No valid subtitle language specified, cannot download subtitles.
Subtitle language array is empty.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {
        "0": {
            "map": 2,
            "codec": "mov_text",
            "disposition": "none",
            "language": "eng",
            "encoding": null
        }
    },
    "format": "mp4",
    "postopts": [
        "-threads",
        "0"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": null,
        "codec": "copy",
        "bitrate": 8688.4663,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "ac3",
            "disposition": "none",
            "bitrate": 1536,
            "filter": null
        }
    }
}
Starting conversion.
[########  ] 87%/volume1/Downloads/my_video.mp4 created.
Tagging file: /volume1/Downloads/my_video.mp4.
There was an error tagging the file
track has no audio data
Relocating MOOV atom to start of file.
```

**Comment by mdhiggins** [comment]
Looks like the options are generated correctly, not sure why the audio tracks aren’t being generated like they’re supposed to. Does it do this for all files? If you turn on debugging logs and try to run the command manually does it work? Does the debug log show anything? (logging.ini to change to debug)

From: Ryan Grush
Sent: Friday, June 7, 2019 11:46 AM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Missing audio track in MP4(#1019)

I'm trying to convert my MVKs to MP4s but the MP4s are always missing the audio track so I'm trying to figure out what I'm doing wrong. I'm doing this on my Synology DSM (Linux) btw.
autoProcess.ini
[MP4]
ffmpeg = /bin/ffmpeg
ffprobe = /bin/ffprobe
threads = 0
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts =
preopts =
I originally had it triggering postSonarr.py to do the conversion but for debugging this issue I've been running -
python /scripts/sickbeard_mp4_automator/manual.py -i "my_video.mkv" -tv 12345 -s 1 -e 1
Here is the output -
ash-4.3# python /scripts/sickbeard_mp4_automator/manual.py -i "my_video.mkv" -tv 12345 -s 13 -e 1
Manual processor started.
/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
Audio detected for stream #1: eac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: subrip [eng].
Creating subtitle stream 0 from source stream 2.
No valid subtitle language specified, cannot download subtitles.
Subtitle language array is empty.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {
        "0": {
            "map": 2,
            "codec": "mov_text",
            "disposition": "none",
            "language": "eng",
            "encoding": null
        }
    },
    "format": "mp4",
    "postopts": [
        "-threads",
        "0"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": null,
        "codec": "copy",
        "bitrate": 8688.4663,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "ac3",
            "disposition": "none",
            "bitrate": 1536,
            "filter": null
        }
    }
}
Starting conversion.
[########  ] 87%/volume1/Downloads/my_video.mp4 created.
Tagging file: /volume1/Downloads/my_video.mp4.
There was an error tagging the file
track has no audio data
Relocating MOOV atom to start of file.

**Comment by ryangrush** [comment]
I just downloaded a sample MKV file from [here](http://techslides.com/sample-files-for-development), ran it through the process and it worked with audio so it must be the MKV I was using. I will say I extracted it from a series of RAR files so I'm not sure if that might've caused the problem.

Here is an ffprobe of the problem MKV file - 

```
ash-4.3# ffprobe -i 8dbc025b43a44bf5b865f2972071e821.mkv
ffprobe version 3.2-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-3) 20161019
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libebur128 --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, matroska,webm, from '8dbc025b43a44bf5b865f2972071e821.mkv':
  Metadata:
    encoder         : libebml v1.3.6 + libmatroska v1.4.9
    creation_time   : 2018-09-15T03:51:56.000000Z
  Duration: 00:21:43.30, start: 0.000000, bitrate: 9785 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 9143518
      DURATION-eng    : 00:21:43.302000000
      NUMBER_OF_FRAMES-eng: 31248
      NUMBER_OF_BYTES-eng: 1489595705
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-09-15 03:51:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      title           : English
      BPS-eng         : 640000
      DURATION-eng    : 00:21:43.296000000
      NUMBER_OF_FRAMES-eng: 40728
      NUMBER_OF_BYTES-eng: 104263680
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-09-15 03:51:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS-eng         : 144
      DURATION-eng    : 00:21:41.300000000
      NUMBER_OF_FRAMES-eng: 588
      NUMBER_OF_BYTES-eng: 23504
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-09-15 03:51:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by ryangrush** [comment]
@mdhiggins it looks like my issue was that I was running the binary of ffmpeg (version 2.7.1) in my Synology's /bin folder and not the updated one I downloaded via "package center" like I thought I was.
