### ISSUE TITLE
Will this work work in this situation?

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#1020]
I would like to use this to auto convert any video that has eac3 audio to ac3 but leave the video if eac3 is not detected. Will this work in that situation? Thanks.

**Comment by mdhiggins** [comment]
Yeah, just setup your autoProcess.ini file accordingly

**Comment by Deihmos** [comment]
I have been experimenting but it does not work. 
[MP4]
ffmpeg = C:\Users\\Downloads\mp4_automator\ffmpeg\ffmpeg.exe
ffprobe = C:\Users\\Downloads\mp4_automator\ffmpeg\ffprobe.exe
threads = 
output_directory = 
copy_to = 
move_to = 
output_extension = mkv
output_format = mkv
delete_original = True
relocate_moov = False
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3,dts,aac
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts =

**Comment by mdhiggins** [comment]
What happens?

**Comment by Deihmos** [comment]
Nevermind I got it working. Great tool. Thanks.
