### ISSUE TITLE
Embedding subs sometimes fail error Application provided duration: XXX is invalid

### ISSUE THREAD

**Issue by izeen** [mdhiggins/sickbeard_mp4_automator#1023]
Hello!

Im having some troubles with embedding subs, it is happening on multiple files and alot of them. When i disable the option to embed subtitles everything works as excpected. In the log output i have this:

Application provided duration: 14399999000 is invalid
av_interleaved_write_frame(): Invalid argument

As soon as i disable the embed-subs options the files that failed works as excpected.

`cur_dts is invalid (this is harmless if it occurs once at the start per stream)
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
[mp4 @ 0x56455a5813c0] Application provided duration: 14399999000 is invalid
av_interleaved_write_frame(): Invalid argument
No more output streams to write to, finishing.
[mp4 @ 0x56455a5813c0] Application provided duration: 14399999000 is invalid
Error writing trailer of /media/dl/XXXXXXXXXXXX.mp4: Invalid argument`

Any ideas? I would like to keep embedded subs on if possible, this is not happening on everyfile but on many/multiple files a day.

**Comment by mdhiggins** [comment]
I haven't been able to find a reliable fix for this. Its FFMPEG limited. The fix_sub_duration option is supposed to address this but appears to be broken
