### ISSUE TITLE
More than an hour to just convert audio

### ISSUE THREAD

**Issue by A-Alhashem** [mdhiggins/sickbeard_mp4_automator#1024]
I'm using windows 10 OS, before using the script I used a .bat file ffmpeg to convert/remux all my mkv into mp4 (with relocate moov atoms to start for web optimized) and changing the default audio to aac stereo if it has more than 2 channels.

When I stumbled on this script, I wanted to use it to only remux mkv to mp4, with web optimized (moov atoms) and only changing/converting audio to AAC stereo (whether the source was ac3, DTS etc..)

normally, this wouldn't take more than 2-7mins max (using bat file before), with mp4 automator, i'm waiting for 50-70mins just to change mkv to mp4 with the audio stated. I'm not converting my video, leaving it as it is. these are my mp4 settings:

[MP4]
ffmpeg = C:\FFMPEG\bin\ffmpeg.exe
ffprobe = C:\FFMPEG\bin\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = True
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 2
audio-codec = aac
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = srt
subtitle-language = 
subtitle-default-language =
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

I've tried different setups, including having ioa-audio to false.

my dedicated pc's CPU (intel NUC) is 6th Generation Intel Core i7-6770HQ 

EDIT: Just wanted to add that I only want to take the first audio (whether its ac3, DTS etc..) and convert it into AAC Stereo, and delete any additional audio tracks (including documentary and other languages)

so the mp4 container would only have 1 video and 1 audio track

**Comment by mdhiggins** [comment]
Post some logs of the process running to see why your conversion is taking so long. It entirely depends on your video source.

**Comment by A-Alhashem** [comment]
where can I find the logs of the script? is it inside sickbeard_mp4_automator directory or my download client directory (SABnzbd) ?

**Comment by mdhiggins** [comment]
Both

**Comment by A-Alhashem** [comment]
I've found the index.log for the mp4 script, I've tried 2 media files, and the 2nd media I've did it several times, including terminating the task while it was performing the conversion as it took a very long time.

[index.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/3316796/index.log)

I'm not sure what exactly I need to look for, if I leave my file converting to the end (which takes around 1hour), it doesn't really say anything in the log..

but if I terminate it in the middle of the conversion, it does show the progress of the conversion (just at the end of the log)

**Comment by A-Alhashem** [comment]
Just wanted to add that with .bat file using FFMPEG manually, i've successfully converted the media to the end result that I wanted the script to perform.

with my bat file (windows 10) all i've done was this:

for %%a in ("*.mkv") do ffmpeg -i "%%a" -movflags faststart -map 0:0 -map 0:1 -map 0:1 -c:v copy -c:a:0 aac -b:a:0 192k -ac 2 -c:a:1 copy "%%~na.CONV.mp4"
pause

how would I edit the autoProcess.ini to achieve the same thing?

**Comment by A-Alhashem** [comment]
Just wanted to add that once the conversion is done, it calls radarr for it to import it to my plex folder, but once imported, i'm seeing 2 types of the same media file .. one is mp4, while the other is mp4.QTFS that is running.

Now I know that its relocating moov atoms, but I thought SAB script already does that, dunno why its re-doing it again on radarr's side as well.

**Comment by A-Alhashem** [comment]
This has been fixed for me, thanks! Now its converting my audio in less than 3mins!

**Comment by kevindd992002** [comment]
How was it fixed?

**Comment by A-Alhashem** [comment]
> How was it fixed?

The fault was on my side. Using windows 10.

Apparently there was a new windows update that caused some CPU issues and drivers. Not to mention it  did a reset to my power plan.
Long story short, using ffmpeg as a bat file command line directly would not see any problem, but running any script (like python) my cpu throttles. Took me a while to figure it out.

Reverted my windows 10 update, updated drivers,

I'm embarrassed to say the main cause of everything was actually from my power plan reset after windows update. It was so obvious and I'm pretty sure it was the main cause as my power plan changed to power saving instead of balance or performance.

It's always the simple things that we overlook and look for complicated problems.
