### ISSUE TITLE
convert_mp4 + ios-audio = duplicate stereo AAC

### ISSUE THREAD

**Issue by GodsVictory** [mdhiggins/sickbeard_mp4_automator#1025]
Is there anyway around this? I know it specifically mentions this would be the result of using both of those options, but not all MP4s have a stereo AAC stream, however, those that do have it are duplicated.

**Comment by uchagani** [comment]
No there isn't.  In the readme and other issues @mdhiggins states that there is no way to know if the existing stream is a stereo version of another.
