### ISSUE TITLE
File permissions are not being set for downloaded/extracted subtitles

### ISSUE THREAD

**Issue by uchagani** [mdhiggins/sickbeard_mp4_automator#1029]
File permissions are set for the converted video file but not the extracted subtitle.  

```
-rw-------  1 admin admin     1MB Jul 10 23:19 'Some.Movie-(2011).en.srt'
-rwxrwxrwx  1 admin admin 15838MB Jul 10 23:27 'Some.Movie-(2011).mp4'
```

**Comment by notorius28** [comment]
Happening also to me, and in my case the resulting srt files are 0kb... its a little bit annoying, I've to extract manually the subs with another app. Many thanks.

>`2019-07-18 16:07:31 - mkvtomp4 - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 588, in generateOptions
    os.chmod(outputfile, self.permissions)  # Set permissions of newly created file
OSError: [Errno 2] No such file or directory: '/mnt/unionfs/tv/vo/The Office (US)/Season 6/the.office.s06e08.1080p.bluray.x264-wavey.eng.srt'`

**Comment by mdhiggins** [comment]
Ripped subs should have always had permissions set but this was missing from downloaded subs
The code for ripped subs and downloaded subs has been overhauled though. Subliminal has been updated to v2 and permissions should now be set. Reopen if this is not working as intended
