### ISSUE TITLE
subliminal v2 upgrade?

### ISSUE THREAD

**Issue by uchagani** [mdhiggins/sickbeard_mp4_automator#1030]
Wondering if you know what it would take to upgrade to subliminal v2?  I'm willing to help out where I can.

**Comment by mdhiggins** [comment]
Would need to update guessit as well, I'm open to a PR request just haven't had time to get to it

**Comment by mdhiggins** [comment]
Just updated to both guessit and subliminal latest versions

**Comment by uchagani** [comment]
Awesome. Thank you!
