### ISSUE TITLE
Allow use of "audio-first-track-of-language" when "audio-language" unset

### ISSUE THREAD

**Issue by TwoLeaves** [mdhiggins/sickbeard_mp4_automator#1031]
Hi. When transcoding a video, I would ideally like to include just the normal audio track in the intended language and nothing else (i.e. no dubs, no commentaries). The only way I can see the automator making this possible is to determine what the spoken language of a film is via IMDB lookup and map that to the available languages. I imagine this is a dicey proposition. So far I have been content just to include all languages.

Second best is to remove any commentary tracks by using the "audio-first-track-of-language" option (copy only "the first occurance of a specific language"). However this option only works for languages I've specified in "audio_language". I don't want to specify any languages in audio_language because I want to copy all languages (seeing as any language audio could be the original language of the film). Can "audio-first-track-of-language" be made to work even if "audio-language" is unset? Am I missing something that prevents this functionality?

I could set audio_language to every language code. But that's a bit of a hack and wouldn't it also then configure the automator to not copy over untagged audio tracks?

Thanks.

**Comment by mdhiggins** [comment]
Late response but `audio-first-track-of-language` should work now without a language whitelist
