### ISSUE TITLE
Extract subtitles only without changing video or audio?

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#1034]
Hi guys, firstly thanks for the great script and support!!

So, my library is quite large and now I need to extract all subtitles from video files and make them srts external. 
All sources are mp4 and only subtitles are mov_text and i wish to rip them to external srt, WITHOUT changing anything in video or audio and also as fast as possible.

Also some tv episodes do not have any subtitles included, so I want to SKIP those as nothing to be changed in it.

How is this possible?

**Comment by uchagani** [comment]
there are probably other tools more suitable for this

**Comment by mdhiggins** [comment]
Yeah this really isn't the purpose of this script. You can reference the code in mkvtomp4.py to see how I rip the subtitles or just use a batch file with ffmpeg to do it
