### ISSUE TITLE
SBMA copies or converts then immediately deletes the files

### ISSUE THREAD

**Issue by BigWebstas** [mdhiggins/sickbeard_mp4_automator#1035]
it looks like everything is working, the downloaded files are there the script copies them to a new folder then something deletes them both the original folder and the copy 
<<Log>>
019-07-26 19:07:37 - delugePostProcess - INFO - Deluge post processing started.
2019-07-26 19:07:37 - readSettings - INFO - /usr/bin/python
2019-07-26 19:07:37 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-07-26 19:07:37 - delugePostProcess - INFO - Successfully connected to Deluge
2019-07-26 19:07:37 - delugePostProcess - INFO - Copying file /mnt/nas10k/media_files/DONE/SHOW to /mnt/nas10k/media_files/DONE/Show19:07:40 - delugePostProcess - INFO - Copying file /mnt/nas10k/media_files/DONE/Show Downloaded from theplace .txt to /mnt/nas10k/media_files/DONE/SHOW 19:07:40 - delugePostProcess - INFO - Passing /mnt/nas10k/media_files/DONE/SHOW-copy directory to Sonarr.
2019-07-26 19:07:40 - autoprocess.sonarr - INFO - Sonarr notifier started.
2019-07-26 19:07:40 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/mnt/nas10k/media_files/DONE/SHOW-copy'.
2019-07-26 19:07:40 - autoprocess.sonarr - INFO - Sonarr response: queued.

![image](https://user-images.githubusercontent.com/2896329/61975814-5f9c7880-afa7-11e9-9c33-88668f64777c.png)
 

my autoProcess.ini
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = 10.2.0.54
port = 8989
web_root = 
ssl = False
apikey = xxxx

[Radarr]
host = 10.2.0.54
port = 7878
web_root = 
ssl = False
apikey = xxxx

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = 8
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 5.1
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = True
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = eng 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[Deluge]
host = 10.2.0.182
username = xxx
convert = False
password = xxx
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = True
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = 10.2.0.70
port = 32400
refresh = True
token = xxxx

**Comment by BigWebstas** [comment]
this is my first time setting it up, so i might just be missing something

**Comment by mdhiggins** [comment]
Reopen if ongoing
