### ISSUE TITLE
Post process radarr stuck on ~partial all of a sudden

### ISSUE THREAD

**Issue by infamouswb** [mdhiggins/sickbeard_mp4_automator#1037]
I don't know what happened, but this was working great, and it still does on the Sonarr end. However with the movies on Radarr, it starts to copy partial mkv to the end destination and creates a ~partial mkv and then doesnt do anything and then retries the ~partial....i don't know whats going on. Everything is local mounted.

I didn't change anything recently.

Using Ubuntu 16.04, latest updates.

**Comment by mdhiggins** [comment]
Turn off completed downloading handling probably
