### ISSUE TITLE
What can i change in my autoProcess.ini for just Remuxing? 

### ISSUE THREAD

**Issue by foizashik** [mdhiggins/sickbeard_mp4_automator#1039]
**I would like it to only change containers without any conversion for Plex direct play. It takes awhile now but is there anything i can change to make this go even faster? I just want to Remux it** 
Thanks

[MP4]
ffmpeg = C:\Program Files (x86)\ffmpeg-20190711-2601eef-win64-static\bin\ffmpeg.exe
ffprobe = C:\Program Files (x86)\ffmpeg-20190711-2601eef-win64-static\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,h265,x265,hevc
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = True
enable_dxva2_gpu_decode = True
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = aac, aa3, DTS, MP3
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = true
audio-first-track-of-language = true
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = false
fullpathguess = True
convert-mp4 = False
tagfile = false
tag-language = eng
download-artwork = Poster
download-subs = false
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts =

**Comment by mdhiggins** [comment]
As long as all the codecs for all the input streams are listed it will remux
