### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1043]
Got this error starting today.  Had not run the manual script since 8-7-2019 and it ran fine at that time.  I was out of town on vacation so no changes to my machine that I am aware of anyway.  Tried it from a second machine with the same results.  Downloaded the latest version and am getting the same results.

Any ideas?

K:\xbmc\iPad>C:\Python27\python C:\Users\user\Documents\sickbeard_mp4_automator-master\manual.py -i "Movie.m4v" -a
Manual processor started.
C:\Python27\python.exe
Audio bitrate was invalid, defaulting to 256 per channel.
32bit Python.
No JSON object could be decoded

**Comment by mdhiggins** [comment]
Not able to produce this

**Comment by samcro1967** [comment]
Working now.  Weird
