### ISSUE TITLE
Subtitles are huge on plex after remuxing. 

### ISSUE THREAD

**Issue by foizashik** [mdhiggins/sickbeard_mp4_automator#1044]
Not a big issue but i turn off embedding subs and make a external srt file instead. But it seems like the subtitles are HUGE after conversion. I uploaded an example, this is on plex web player and subtitles are on  "Normal" Even setting it to Tiny makes it look huge. 
![Capture](https://user-images.githubusercontent.com/34486426/62989708-25d8c800-be17-11e9-8651-f47ecfa7e27e.PNG)

**Comment by mdhiggins** [comment]
Script has nothing to do with subtitle size

From: foizashik
Sent: Tuesday, August 13, 2019 10:10 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Subtitles are huge on plex afterremuxing. (#1044)

Not a bit issue but i turn off embedding subs and make a external srt file instead. But it seems like the subtitles are HUGE after conversion. I uploaded an example, this is on plex web player and subtitles are on "Normal" Even setting it to Tiny makes it look huge.

**Comment by mdhiggins** [comment]
Quick google search

https://forums.plex.tv/t/huge-subtitles-on-ps3/69426/9

From: foizashik
Sent: Tuesday, August 13, 2019 10:10 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Subtitles are huge on plex afterremuxing. (#1044)

Not a bit issue but i turn off embedding subs and make a external srt file instead. But it seems like the subtitles are HUGE after conversion. I uploaded an example, this is on plex web player and subtitles are on "Normal" Even setting it to Tiny makes it look huge.
