### ISSUE TITLE
Plex is not refreshed on Upgrade

### ISSUE THREAD

**Issue by promo76** [mdhiggins/sickbeard_mp4_automator#1050]
Once sabnzbd downloads the movie and converts it, Radarr will refresh Plex only on new downloads. If Radarr finds an better version, after sabnzbd converts it to mp4, it sends it back to Radarr and for some reason it fails to refresh Plex. I looked at all the settings and I cannot figure out why on a new download Plex is refreshed, and on an upgrade it is not. 

Thank you for your help!

**Comment by mdhiggins** [comment]
Are you trigger your plex refreshes through radarr or through the script?
Script refreshes should be triggered any time the script runs and isn't aware of whether its an upgrade or not, so if you're using radarr to trigger refreshes consider using the scripts integrated plex notification instead.

**Comment by promo76** [comment]
I am using the postrdarr.py script. 

Thank you

**Comment by promo76** [comment]
OMG...lollllll.....mdhiggins, my apologies! I am using both the sabportprocess.py and postradarr.py, they probably do the same thing. Being that I do not have the prereqs installed in the Radarr container the process fails and it never refreshes Plex. I disabled the postradarr.py script. Let's see if that solves the problem.

**Comment by mdhiggins** [comment]
sabpostprocess doesn't trigger plex refresh, but postradarr will (as sabpostprocess isn't intended to be the final step)

**Comment by promo76** [comment]
Then for some reason is not working. I cannot figure out why.

**Comment by mdhiggins** [comment]
Check the logs, post your plex config settings, make sure you're not getting refresh from Radarr's built in plex refresher

**Comment by promo76** [comment]
I disabled the Radarr Plex refresher. Maybe that was it. Thank you! I will keep you posted.

**Comment by mdhiggins** [comment]
Good chance the radarr one was the one that was working before, you'll need to make sure you have your plex settings correct in autoProcess.ini

**Comment by promo76** [comment]
Hello mdhiggins,

Here are the errors I am getting in the Radarr logs:


  | Component | Message | Time
-- | -- | -- | --
  | postRadarr.py | ImportError: No module named babelfish | 9:04pm
  | postRadarr.py | from babelfish import Language | 9:04pm
  | postRadarr.py | File "/mp4automator/readSettings.py", line 11, in <module> | 9:04pm
  | postRadarr.py | from readSettings import ReadSettings | 9:04pm
  | postRadarr.py | File "/mp4automator/postRadarr.py", line 6, in <module> | 9:04pm
  | postRadarr.py | Traceback (most recent call last):

**Comment by promo76** [comment]
I checked the container and it has the module installed:
Requirement already satisfied: babelfish in /usr/local/lib/python2.7/dist-packag                                  es (0.5.5)

**Comment by promo76** [comment]
Correction: The sabnzbd container has the module installed, however the radarr conatiner does not. 
Do I need to use the postradarr.py script at all if I am converting in sabnzbd? Can I use the radarr built in Plex refesh?

**Comment by mdhiggins** [comment]
Sounds like the bigger issue is that postRadarr is being called with the wrong python environment and you actually have 2. Make sure you're pointing to the correct python executable/environment when you're calling this post script and things shoulder work.

This is how mine is configured, I use a virtual environment python setup
![image](https://user-images.githubusercontent.com/3608298/63430776-66be7700-c3eb-11e9-85b5-29de3e98f634.png)

The SAB script is actually only an intermediate script and only has some features because its a 'dumb' script because SAB passes no information about the media file other than its location. The postRadarr script is the one that handles tagging and all the additional copy/post processing options so ideally not a script to ignore.

That being said, you probably can use the plex notifier built in to Radarr, just need to add the 'on upgrade' event. I actually use this instead of the built in notifier for my needs.

**Comment by promo76** [comment]
I don't have python 3 installed. The radarr and sonarr containers from Linuxserver.io have python 2.7. I will try to point it to that and see if it changes anything. I'll post my results.

**Comment by mdhiggins** [comment]
You do not need python 3, that's just what I'm using, it was provided as an example. Just point it to the python install where you have installed things

Also, I have docker containers for sonarr/radarr if you're interested that include the script setup stuff
https://cloud.docker.com/u/mdhiggins/repository/docker/mdhiggins/sonarr-sma
https://cloud.docker.com/u/mdhiggins/repository/docker/mdhiggins/radarr-sma

**Comment by promo76** [comment]
Hello mdhiggins,

My Please refresh issues are still there. I downloaded you radarr container and set it up. Here are the screen shots:

![image](https://user-images.githubusercontent.com/53126190/63629967-270eaf80-c5e4-11e9-9a28-c55fa8fa0476.png)

![image](https://user-images.githubusercontent.com/53126190/63629993-51606d00-c5e4-11e9-95f3-36f608376872.png)

Thanks!

**Comment by mdhiggins** [comment]
What are you autoProcess.ini settings for plex?

**Comment by promo76** [comment]
Hello mdhiggins,

There are screen shots attached to that post. But here they are in text format:

[Plex]
host = IP for my Synology NAS(Plex is using the host network)
port = 32400
refresh = True
token = I got the Plex token from GET INFO(movie) -> View XML

After I started using your radarr container I am also getting these errors:


python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/bin/ffmpeg | Yesterday
-- | -- | --
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/mp4automator/converter/ffmpeg.py", line 364, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/mp4automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile) | Yesterday
  | python3 | File "/mp4automator/mkvtomp4.py", line 308, in generateOptions | Yesterday
  | python3 | options = self.generateOptions(inputfile, original=original) | Yesterday
  | python3 | File "/mp4automator/mkvtomp4.py", line 192, in process | Yesterday
  | python3 | output = converter.process(inputfile, original=original) | Yesterday
  | python3 | File "/mp4automator/postRadarr.py", line 51, in <module> | Yesterday
  | python3 | Traceback (most recent call last): | Yesterday
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/bin/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/mp4automator/converter/ffmpeg.py", line 364, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/mp4automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile) | Yesterday
  | python3 | File "/mp4automator/mkvtomp4.py", line 308, in generateOptions | Yesterday
  | python3 | options = self.generateOptions(inputfile, original=original) | Yesterday
  | python3 | File "/mp4automator/mkvtomp4.py", line 192, in process | Yesterday
  | python3 | output = converter.process(inputfile, original=original) | Yesterday
  | python3 | File "/mp4automator/postRadarr.py", line 51, in <module> | Yesterday
  | python3 | Traceback (most recent call last):

Thanks!

**Comment by promo76** [comment]
Here are my sabnzbd settings:

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = tv series
radarr-category = uhd movies
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory =

**Comment by promo76** [comment]
Hello mdhiggins,

This issue is resolved. I unchecked the following settings in Plex and it seems it resolved the issue:

![image](https://user-images.githubusercontent.com/53126190/64867203-f03c2000-d60a-11e9-81da-d57653097242.png)

Thank you!

**Comment by Muckoma** [comment]
@promo76 - I had a similar issue so followed this thread a bit and fixed it.  Please close the issue if it's working for you.
