### ISSUE TITLE
Deluge integration issues

### ISSUE THREAD

**Issue by trippinshrumes** [mdhiggins/sickbeard_mp4_automator#1051]
Ubuntu 18.04

When Deluge finishes downloading, the execute script is set to run the delugePostProcess.py, when that is triggered I am only seeing Deluge post processing started in the log, and then nothing further happens. 

Usenet works wonderfully with your mp4 conversion tool, I would love to get torrents working with this as well. Please let me know what steps I can take next to get this resolved, thank you. 

![image](https://user-images.githubusercontent.com/13083581/63287657-7c635d80-c280-11e9-9d55-ac8ffcb00fe0.png)

**Comment by mdhiggins** [comment]
Check the logs and see if there's an error in the deluge post process
And as always check your autoProcess.ini deluge settings and make sure everything is configured appropriately as the script needs to be able to talk to deluge to run. Also make sure you're using deluge daemon and not just the standard deluge client

**Comment by trippinshrumes** [comment]
I do believe I found the issue, and it is in the deluged log. It is stating that a username is not available

this is where mp4 automator is starting and suddenly stopping. 

Would this be referencing the deluged username/password at `/var/lib/deluge/.config/deluge/auth`? 

As this script works fine for sonarr and radarr through nzbget, I wouldn't imagine that it's having issues connecting to sonarr/radarr. 

Thanks for any additional help you can provide. 

![image](https://user-images.githubusercontent.com/13083581/63351745-68256c00-c325-11e9-8a2c-92f726835587.png)

**Comment by mdhiggins** [comment]
Yes I believe that is referring to the username and password you’ve configured in /var/lib/deluge/.config/deluge

You need to provide that username and password in that config file and additionally you need to have that information match what you’ve specified in your autoProcess.ini under the [Deluge] settings

Most of this is outlined in the readme
https://github.com/mdhiggins/sickbeard_mp4_automator#deluge-daemon

**Comment by trippinshrumes** [comment]
This was solved by having the correct username and password corresponding in the autoProcess.ini for Deluge, as well as the auth file located at ~/.config/deluge/auth for the user I have running deluge. I had been editing the auth file in the other location which is the same location I found referenced on the web. Thank you for your assistance.

**Comment by mdhiggins** [comment]
Great, glad its working
