### ISSUE TITLE
Exception while retrieving poster Invalid URL 'None': No schema supplied. Perhaps you meant http://None?.

### ISSUE THREAD

**Issue by daphatty** [mdhiggins/sickbeard_mp4_automator#1052]
This is a continuation of [Issue # 944](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/944) originally reported by Jeff47.

When I first encountered this problem, it was during the use of manual.py against some .mp4 files to relocate the MOOV bit and add missing metadata and posters. The initial error ...
```
Exception while retrieving poster "NoneType" object has no attribute 'strip'
```
...changed to...
```
Exception while retrieving poster Invalid URL 'None': No schema supplied. Perhaps you meant http://None?.
```
...after updating my mp4 automator suite to the latest version. This issue seems to happen on video files downloaded from pbskids.org via youtube.dl using the default settings (youtube-dl "<URL>" --ignore-confg). So far, the manual.py method has successfully added metadata to only one of my files downloaded using the aforementioned method.  Manually tagging other files is otherwise working in my environment. 

Command being used to process files - manual/py -i <source directory/file> -a

**Comment by daphatty** [comment]
Update - I may have just solved my own problem. I cross referenced my affected files with the TVDB website and found that no episode posters existed for all of my "failed" files. If I am correct, this should be easy to recreate. Example shows are Daniel Tiger's Neighborhood and Ready Jet Go!.

It might be useful to modify the manual tagging process such that the error output reflects the actual situation (i.e. No Poster Available)?

**Comment by mdhiggins** [comment]
No longer TVDB so no longer relevant
