### ISSUE TITLE
Trancode audio Twice possible?

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#1053]
Sample video file audio is ac3 stereo.

I want to convert that ac3 audio stream into aac stereo (which is easy) AND I want to transcode that same ac3 stream into aac 5.1 (which is also easy) But how can transcode once and put both streams on same output file?

How could I achieve this???

**Comment by uchagani** [comment]
you could probably do it with pre/post options.

**Comment by Zeusy123** [comment]
Hi Uchagani, could you explain how this would be possible using pre/post pls?

**Comment by mdhiggins** [comment]
Just use the iOS audio option, it does exactly this
