### ISSUE TITLE
Extracting PGS subs like SRT subs

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1054]
FFMPEG support saving HDMV_PGS subs already so i am wondering how hard it would be to implement this?

`ffmpeg -i test.mkv -map 0:3 -c:s copy "test.eng.sup"`

But i don't think there is any way for me to make use of this with pre or post ops arguments. 

It would be nice to get these to extract for later OCR.

**Comment by JySzE** [comment]
bump

**Comment by mdhiggins** [comment]
Can you send me a link to a sample file that has the subs

**Comment by JySzE** [comment]
https://www.mediafire.com/file/2i28imuh183ao7o/Test.mkv/file

**Comment by JySzE** [comment]
https://www.mediafire.com/file/fm8tnk5ha85gfmm/test.mkv/file

**Comment by mdhiggins** [comment]
Alright I think I got pgs extraction working
use `pgs` as your subtitle codec with `embed-subs=False`

**Comment by JySzE** [comment]
Okay, so this works but the issue is if i run the subtitle codec as pgs,srt it makes a blank srt file if there is no srt file present in the mkv. I have to have both since if this already has a srt in the file id like it to pick that up also.

**Comment by JySzE** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/25883052/69214833-e0feb480-0b1c-11ea-8580-4eecb25989b4.png)

**Comment by mdhiggins** [comment]
Just pushed a fix for this
Because there's no good way to know which subtitle format will correctly match without storing a large databank of related subtitle crossovers I instead opted to have it try to convert and fail but added in file cleanup options this time around so you shouldn't have left over srt/sup files, give it a try

**Comment by JySzE** [comment]
Works great!
