### ISSUE TITLE
Recent qbittorent PR breaks manual run

### ISSUE THREAD

**Issue by AlexanderNZ** [mdhiggins/sickbeard_mp4_automator#1055]
Hi Folks,

I think I've found a bug introduced by #1033 that causes manual.py to fail.

**Reproduction:**
run `python manual.py -i some.mkv`
This outputs:

```
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "manual.py", line 45, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "/home/alex/sickbeard_mp4_automator/readSettings.py", line 583, in __init__
    self.qBittorrent['radarr'] = config.get(section, "radarr-label").lower()
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'radarr-label' in section: 'qBittorrent'
```

Expected behaviour is for manual processing to begin successfully.

I feel that #1033 contains the code that causes this, as reverting to the last commit before qbittorent support was added causes `python manual.py -i some.mkv` to begin processing successfully.

**i.e. to fix:**
`git checkout 55e5948ff0042eef5190b3d613f247e6d8074d6d`
then re-run `python manual.py -i some.mkv` successfully begins the file processor.

Cheers

Alex

**Comment by mdhiggins** [comment]
Just pushed an update that should address/fix this. Give it a try

**Comment by AlexanderNZ** [comment]
Thanks! Will give it a go in the next few days.

**Comment by AlexanderNZ** [comment]
Just confirming it works now as expected.
