### ISSUE TITLE
Converting Before Handing to Plex Directory

### ISSUE THREAD

**Issue by CoderKiwi** [mdhiggins/sickbeard_mp4_automator#1062]
I have `sonarr-sma` set up and working great. However, at the moment, after `SABnzbd` downloads an episode, `sonarr-sma` moves it to my Plex folder (on a separate NAS, mounted via cifs), Plex finds the file, and THEN `mp4-automator` starts converting. 

This means a Plex user could play the unoptimized file while it's being optimized, then the file could be deleted and replaced by the optimized mp4 and disrupt playback. Also now that [Plex supports On Deck notifications](https://www.plex.tv/blog/plex-knows-notifications/) it means users are sometimes notified twice that a new episode is available because both the unoptimized and optimized shows are being found by Plex at two different times. 

I know [the README](https://github.com/mdhiggins/sickbeard_mp4_automator#sonarr-setup) says that in order to optimize the file before it's handed to Plex I need to turn off 'Completed Download Handling'. When I turn that off nothing happens. The `postSonarr` script isn't called, `sonarr-sma` doesn't even output any logs that anything was downloaded. 

**Sonarr logs:**
```
...
[Info] NzbSearchService: Searching 5 indexers for [TV SHOW] 
[Info] DownloadDecisionMaker: Processing 25 releases 
[Info] Sabnzbd: Adding report [TV SHOW] to the queue. 
[Info] DownloadService: Report sent to SABnzbd. TV SHOW
... and then nothing...
```

`index.log` stored in the container under `var/log/sickbeard-mp4-automator` shows nothing. 

**postSonarr config:**
<img width="461" alt="Screen Shot 2019-09-21 at 11 05 56 PM" src="https://user-images.githubusercontent.com/33564041/65372439-65bb8680-dcc4-11e9-84f3-c38e723b5a7a.png">

Is there another way to optimize the file before moving it to a Plex-monitored directory? Or perhaps I'm doing something wrong here? I had a working setup before turning off 'Completed Download Handling'.

**Comment by CoderKiwi** [comment]
Anybody?

**Comment by mdhiggins** [comment]
The docker containers are not set up to work without completed download handling, you'll need to implement your own solution (you need to use the post downloader scripts for SAB, NZBGet, etc to hand the file over if you turn off completed download handling, it wont magically work).

Alternatively, just turn off automatic plex scanning and configure the plex refresh features in either sonarr/radarr or the script

**Comment by CoderKiwi** [comment]
Okay, I'll try out those ways, thank you @mdhiggins.
