### ISSUE TITLE
Sickbeard_mp4_Automator with Plex, uTorrent, Sonarr, and Radarr not working

### ISSUE THREAD

**Issue by rnsimmons** [mdhiggins/sickbeard_mp4_automator#1063]
I need some help with my SMA setup.  I apologize if this has already been covered elsewhere.

I'm running Plex 1.16.6.1592, uTorrent (Ad-free) 3.5.5, Sonarr 2.0.0.5338, and Radarr 0.2.0.1358.  My downloads are not converting, nor moving to the correct directories.

My autoProcess.ini file:

****************************************************************************************************
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = localhost
port = 8989
web_root = 
ssl = False
apikey = XXXXXXXXXXXXXXXXXXXXXXXXXXXX

[Radarr]
host = localhost
port = 7878
web_root = 
ssl = False
apikey = XXXXXXXXXXXXXXXXXXXXXX

[MP4]
ffmpeg = C:\Program Files (x86)\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\Program Files (x86)\ffmpeg\bin\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = True
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = rnsimmons
password = XXXXXXXXXXXXXXXX
output_directory = 
radarr-label = radarr

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = false
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token = XXXXXXXXXXXXXXXXXXXXXXXX

![Radarr Custom Script Setup](https://user-images.githubusercontent.com/27501490/65446128-54c06180-ddf9-11e9-87ad-94c179461597.png)

![Sonarr Custom Script Setup](https://user-images.githubusercontent.com/27501490/65449596-ed0e1480-de00-11e9-92ee-3dc1977fe7a2.png)

****************************************************************************************************
Does my configuration look correct?  If so, is there someplace I can go to see logs in order to figure this out?

I appreciate any help.

**Comment by rnsimmons** [comment]
I was taking another quick look and was wondering of the uTorrent Run Program option needs to include the path to my uTorrentPostProcess.py?

I'm going to give it a try and will report any success.  (BTW, I'd still like to know the location of any logging files.)

**Comment by SnarkyCanuck** [comment]
@rnsimmons , did you have any success in getting this to work?  I'm running into the same problem on a Windows 7 machine.

**Comment by rnsimmons** [comment]
No, I haven’t.  I even started uTorrent with logging and can’t tell whether it even tries to start the process.  I’ve even fully qualified the python executable and the Sick beard uTorrent script to no avail.  I opened a ticket with SMA on GitHub and haven’t heard back from the author.

 

Let me know if you make any progress.

 

Russell N. Simmons, Network+
Principal


940.293.5113 Cell | 940.398.4021 Fax

 

 <mailto:Russell.simmons@arnessco.com> Russell.simmons@arnessco.com

**Comment by ratt2581** [comment]
Sorry I don't use uTorrent but a few things that might help you:

- There should be a "index.log" file in the root directory of sickbeard_mp4_automator
- Update your ffmpeg paths to escape the backslashes C:\\Program Files (x86)\\ffmpeg\\bin\\ffmpeg.exe
- Does "Test" work on your Sonarr/Radarr setups?
- Have you tried running manual.py?
