### ISSUE TITLE
Sonarr/Radarr-sma not recognizing/finding ffmpeg.exe

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1066]
Sonarr/Radarr-sma seems to be grabbing the download from the Sabnzdb folder and moving it to the destination folder, but it fails to convert and rename.  I believe it is not finding ffmpeg which does not appear to be in the container.  Here is what I have done so far:

1. "Completed Download Handling" is enabled
2.  Path mounted on my host to ffmpeg as a volume to the container at /ffmpeg/
3.  Updated autoprocess.ini with the path for both ffmpeg and ffprobe to /ffmpeg/bin/ffmpeg.exe & /ffmpeg/bin/ffprobe.exe
4. Updated postSonarr/Radarr connect tab Path and Arguments to:
    -/usr/local/bin/sma/env/bin/python3
    -/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr/Radarr.py respectively
5. Verified ffmpeg is at the location Sonarr/Radarr-sma says it is looking for it from withing the container and that it has read and write permissions

![image](https://user-images.githubusercontent.com/2319445/66269857-31db7780-e813-11e9-83ce-2f28c09fbd97.png)

![image](https://user-images.githubusercontent.com/2319445/66269916-ea092000-e813-11e9-8c12-47200e466fd8.png)

**Comment by mdhiggins** [comment]
It’s a unix based system, never use .exe that’s exclusively a windows extension for executables (executables in Linux no extension)

On Linux executables are located in the bin folders, specifically

/usr/local/bin/ffmpeg/ffmpeg
/usr/local/bin/ffmpeg/ffprobe


```
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
```

From: samcro1967
Sent: Sunday, October 6, 2019 9:35 AM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Sonarr-sma notrecognizing/finding ffmpeg.exe (#1066)

Sonarr-sma seems to be grabbing the download from the Sabnzdb folder and moving it to the destination folder, but it fails to convert and rename. I believe it is not finding ffmpegh whioch does not appear to be in the container. Here is what I have done so far:
1. "Completed Download Handling" is enabled
2. Path mounted on my host to ffmpeg as a volume to the container at /ffmpeg/
3. Updated autoprocess.ini with the path for both ffmpeg and ffprobe to /ffmpeg/bin/ffmpeg.exe & /ffmpeg/bin/ffprobe.exe
4. Verified ffmpeg is at the location Sonarr-sma says it is looking for it from withing the container and that it has read and write permissions

**Comment by mdhiggins** [comment]
And just to clarify the executables are automatically downloaded as part of the container

**Comment by samcro1967** [comment]
Removed the mount to external source for ffmpeg and updated autorpcoess.ini to
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe

Sabnzbd downloads still but sma never seems to do anything else.  Verified connect postSonnar is still setup with correct  Path and Arguments and that Completed Download Handling is still enabled.  Cannot seem to locate a separate log (index.log) for sonarr-sma anywhere to see where the breakdown is between sonarr, sma, and sabnzbd.

Sabnzbd and Sonarr logs are below, but neither has any errors
SABnabd log - https://pastebin.com/FkBAi7m0
Sonarr Log - https://pastebin.com/CMW5cmx9

**Comment by samcro1967** [comment]
Not sure why, but everything seems to be working fine now.  The only additional change I made was to expose the logs externally tot he container for easier viewing.

-v C:\Users\username\Documents\Docker\sma\radarr-sma.log:/var/log/sickbeard_mp4_automator/index.log

-v C:\Users\username\Documents\Docker\sma\sonarr-sma.log:/var/log/sickbeard_mp4_automator/index.log
