### ISSUE TITLE
sonarr-sma: Processed files are corrupted

### ISSUE THREAD

**Issue by trolley** [mdhiggins/sickbeard_mp4_automator#1067]
Note: I'm using your `sonarr-sma` Docker config for this.

I'm having a problem where Sonarr downloads an episode and runs the postSonarr task, but the output file is corrupt and won't play. The file is processed with no errors according to the SMA log:

```
2019-10-06 20:35:55 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2019-10-06 20:35:55 - readSettings - INFO - /usr/local/bin/sma/env/bin/python3
2019-10-06 20:35:56 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-10-06 20:35:56 - SonarrPostConversion - INFO - Processing /shared/TV/South Park/Season 23/South Park - S23E01 - Mexican Joker.mkv.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading video stream.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Video codec detected: h264.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Profile: High.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading audio streams.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Audio detected for stream #1: aac [eng].
2019-10-06 20:36:01 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading subtitle streams.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2019-10-06 20:36:01 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Starting conversion.
2019-10-06 20:39:14 - mkvtomp4 - INFO - /shared/TV/South Park/Season 23/South Park - S23E01 - Mexican Joker.mp4 created.
```
The output file is unplayable. VLC log:

```
avcodec debug: trying url: /Users/trolley/South Park - S23E01 - Mexican Joker.mp4
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: detected format: mov,mp4,m4a,3gp,3g2,mj2
avcodec debug: Trying to seek too far : EOF?
avcodec debug: Trying to seek too far : EOF?
avcodec error: Could not open /Users/trolley/South Park - S23E01 - Mexican Joker.mp4: Unknown error
ps warning: this does not look like an MPEG PS stream, continuing anyway
```

**autoProcess.ini**
```
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = XXX
port = 8989
web_root = 
ssl = False
apikey = XXX

[Radarr]
host = XXX
port = 7878
web_root = 
ssl = False
apikey = XXX

[MP4]
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[qBittorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
action_before = pause
action_after = resume
host = http://localhost:8080/
username = 
password = 
output_directory = 

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = false
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = XXX
port = 32400
refresh = True
token = XXX
```

**Comment by mdhiggins** [comment]
Very strange

Does the source episode also cause playback issues?
If you disable tagging does the issue persist?

It seems the script isn’t even encoding the video stream so unless there is an issue with the container this would be a strange bug

Are you seeing this problem with every file?

From: Mark Trolley
Sent: Sunday, October 6, 2019 8:51 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] sonarr-sma: Processed files arecorrupted (#1067)

I'm having a problem where Sonarr downloads an episode and runs the postSonarr task, but the output file is corrupt and won't play. The file is processed with no errors according to the SMA log:
2019-10-06 20:35:55 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2019-10-06 20:35:55 - readSettings - INFO - /usr/local/bin/sma/env/bin/python3
2019-10-06 20:35:56 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-10-06 20:35:56 - SonarrPostConversion - INFO - Processing /shared/TV/South Park/Season 23/South Park - S23E01 - Mexican Joker.mkv.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading video stream.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Video codec detected: h264.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Profile: High.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading audio streams.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Audio detected for stream #1: aac [eng].
2019-10-06 20:36:01 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Reading subtitle streams.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2019-10-06 20:36:01 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2019-10-06 20:36:01 - mkvtomp4 - INFO - Starting conversion.
2019-10-06 20:39:14 - mkvtomp4 - INFO - /shared/TV/South Park/Season 23/South Park - S23E01 - Mexican Joker.mp4 created.
The output file is unplayable. VLC log:
avcodec debug: trying url: /Users/trolley/South Park - S23E01 - Mexican Joker.mp4
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: detected format: mov,mp4,m4a,3gp,3g2,mj2
avcodec debug: Trying to seek too far : EOF?
avcodec debug: Trying to seek too far : EOF?
avcodec error: Could not open /Users/trolley/South Park - S23E01 - Mexican Joker.mp4: Unknown error
ps warning: this does not look like an MPEG PS stream, continuing anyway
autoProcess.ini
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = XXX
port = 8989
web_root = 
ssl = False
apikey = XXX

[Radarr]
host = XXX
port = 7878
web_root = 
ssl = False
apikey = XXX

[MP4]
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[qBittorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
action_before = pause
action_after = resume
host = http://localhost:8080/
username = 
password = 
output_directory = 

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = false
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = XXX
port = 32400
refresh = True
token = XXX

**Comment by trolley** [comment]
Every file, yes. This is a new setup and I haven't had it successfully convert an episode in the Docker container. The source files play fine.

**Comment by trolley** [comment]
I'm recreating the container and I'll try again.

Is there a way I can manually trigger this process from Sonarr or do I need to just get it to download another episode to get the log again?

**Comment by trolley** [comment]
I recreated the container and while looking though my Sonarr settings I found that somehow I'd left "Completed Download Handling" on, so I turned that off as the instructions say to but now nothing happens in Sonarr after the download finishes in Transmission, and postSonarr doesn't get run.

**Comment by trolley** [comment]
I did some reading and see that the file won't get imported to Sonarr if "Completed Download Handling" isn't enabled, so I don't know whether that should be on or not. Without it postSonarr doesn't get executed.

**Comment by trolley** [comment]
I found another issue where you said the Docker containers should use completed download handling after all so I turned it back on: https://github.com/mdhiggins/sickbeard_mp4_automator/issues/951

**Comment by trolley** [comment]
I've experimented a bit more and the problem only happens when the file is processed by `postSonarr.py`. If I open a shell in the container and process it with `manual.py` it works fine.

**Comment by mdhiggins** [comment]
Was this ever resolved?

**Comment by trolley** [comment]
I haven't tried it again recently. I'll update my docker compose config when I get home and try it again.

**Comment by trolley** [comment]
@mdhiggins Sorry I didn't get back to trying this until last night and it works now, thank you.
