### ISSUE TITLE
File not being imported

### ISSUE THREAD

**Issue by 1stian** [mdhiggins/sickbeard_mp4_automator#1069]
Hello,
I closed my previous post, because I solved that one...

So now..!

Whenever a file is done converting and ends up in my "output directory". It stays there and nothing more happens with the file. In the index.log file. There is this:

2019-10-09 20:00:11 - mkvtomp4 - INFO - D:\Media\ferdigmedia\Dark.Phoenix.2019.1080p.BluRay.DTS.X264-CMRG[EtHD].mp4 created.
2019-10-09 20:00:11 - uTorrentPostProcess - INFO - Passing D:\Media\ferdigmedia directory to Radarr.
2019-10-09 20:00:11 - autoprocess.radarr - INFO - Radarr notifier started.
2019-10-09 20:00:11 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'D:\Media\ferdigmedia'.
2019-10-09 20:00:11 - autoprocess.radarr - INFO - Radarr response: queued.

But then I look at "Radarr response: queued." So it sends the request to radarr to look into my output directory... But it says queued. Does that mean it is going to run? In my case, it does nothing... How can I solve this?

**Comment by mdhiggins** [comment]
Sounds like Sonarr was either having permission issues or having trouble parsing the naming scheme of your directory. Ultimately a sonarr problem but always good to share how you fixed it

**Comment by 1stian** [comment]
> Sounds like Sonarr was either having permission issues or having trouble parsing the naming scheme of your directory. Ultimately a sonarr problem but always good to share how you fixed it

Ohh hello :) Well I just switched to qBitTorrent and it just started working.. So I don't know what was up when I used uTorrent. I can try to experminate a bit more with it.. To see if I get it working :) And I will lett you know.

**Comment by mdhiggins** [comment]
If you can find the same line for parser in the debug lines for uTorrent it would be interesting to see if it passes the path in a different manner
