### ISSUE TITLE
Small documentation suggestions

### ISSUE THREAD

**Issue by fortiko** [mdhiggins/sickbeard_mp4_automator#1070]
1. README.md talks about "subtitle-language-default", but I believe that the actual name is "subtitle-default-language" (default first, then language), similar to "audio-default-language"
2. Also a quote from README.md:
subtitle-language = same as audio-language but for subtitles. Set to nil to disable copying of subtitles.
I think we should clarify that if left blank, only the existing ones are copied from the source, but of course no additional subtitles can be downloaded, because the script doesn't know in what languages, which in turn leads to the warning "Subtitle language array is empty."

**Comment by mdhiggins** [comment]
Done
