### ISSUE TITLE
[Question] Adding 'mp4' to extensions.py

### ISSUE THREAD

**Issue by tjesp** [mdhiggins/sickbeard_mp4_automator#1072]
I have a few 'mp4' files that are in 4k. My autoprocess.ini is set up to 1920 resolution.

However according to extensions.py 'mp4' is not processed.

If I add 'mp4' to extensions.py will that give problems since that is my destination format? Will it reprocess mp4 files again and again? (I have set it to H264 and AAC according to plex documentation. Will that be enough?)

**Comment by mdhiggins** [comment]
Just turn on the convert-mp4 option

**Comment by tjesp** [comment]
Of course! I didn't know there were an option.
