### ISSUE TITLE
PostSonarr Issue

### ISSUE THREAD

**Issue by Muckoma** [mdhiggins/sickbeard_mp4_automator#1073]
Hi, 
I'm trying to run the postProcess script on Synology and getting a few errors. I tried using manaul.py and it works fine so I know my issue isn't with the libs required. I am running Sonarr through a synology package provided by Synocommunity so I believe it's an older version of Sonarr. Here are the errors I'm getting. I apologize in advance if this has been asked or addressed 
`19-10-21 22:10:18.7|Error|postSonarr.py|Traceback (most recent call last):
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/volume1/vpnInfo/SickBeard/postSonarr.py", line 5, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    import requests
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from urllib3.contrib import pyopenssl
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    import OpenSSL.SSL
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from OpenSSL import crypto, SSL
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from cryptography import x509
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from cryptography.x509.base import (
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from cryptography.x509.extensions import Extension, ExtensionType
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 14, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from asn1crypto.keys import PublicKeyInfo
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from ._elliptic_curve import (
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from ._int import inverse_mod
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    from ._perf._big_num_ctypes import libcrypto
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
19-10-21 22:10:18.8|Error|postSonarr.py|    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
19-10-21 22:10:18.8|Error|postSonarr.py|  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
19-10-21 22:10:18.8|Error|postSonarr.py|    raise RuntimeError("can not find library %s" % name)
19-10-21 22:10:18.8|Error|postSonarr.py|RuntimeError: can not find library crypto
19-10-21 22:10:19.6|Error|postSonarr.py|Traceback (most recent call last):
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/volume1/vpnInfo/SickBeard/postSonarr.py", line 5, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    import requests
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from urllib3.contrib import pyopenssl
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    import OpenSSL.SSL
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from OpenSSL import crypto, SSL
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from cryptography import x509
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from cryptography.x509.base import (
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from cryptography.x509.extensions import Extension, ExtensionType
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 14, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from asn1crypto.keys import PublicKeyInfo
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from ._elliptic_curve import (
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from ._int import inverse_mod
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    from ._perf._big_num_ctypes import libcrypto
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
19-10-21 22:10:19.6|Error|postSonarr.py|    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
19-10-21 22:10:19.6|Error|postSonarr.py|  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
19-10-21 22:10:19.6|Error|postSonarr.py|    raise RuntimeError("can not find library %s" % name)
19-10-21 22:10:19.6|Error|postSonarr.py|RuntimeError: can not find library crypto
19-10-21 22:10:20.7|Error|postSonarr.py|Traceback (most recent call last):
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/volume1/vpnInfo/SickBeard/postSonarr.py", line 5, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    import requests
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from urllib3.contrib import pyopenssl
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    import OpenSSL.SSL
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from OpenSSL import crypto, SSL
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from cryptography import x509
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from cryptography.x509.base import (
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from cryptography.x509.extensions import Extension, ExtensionType
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 14, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from asn1crypto.keys import PublicKeyInfo
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from ._elliptic_curve import (
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from ._int import inverse_mod
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    from ._perf._big_num_ctypes import libcrypto
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
19-10-21 22:10:20.7|Error|postSonarr.py|    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
19-10-21 22:10:20.7|Error|postSonarr.py|  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
19-10-21 22:10:20.7|Error|postSonarr.py|    raise RuntimeError("can not find library %s" % name)
19-10-21 22:10:20.7|Error|postSonarr.py|RuntimeError: can not find library crypto
19-10-21 22:10:26.9|Error|postSonarr.py|Traceback (most recent call last):
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/volume1/vpnInfo/SickBeard/postSonarr.py", line 5, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    import requests
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from urllib3.contrib import pyopenssl
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    import OpenSSL.SSL
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from OpenSSL import crypto, SSL
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from cryptography import x509
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from cryptography.x509.base import (
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from cryptography.x509.extensions import Extension, ExtensionType
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 14, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from asn1crypto.keys import PublicKeyInfo
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from ._elliptic_curve import (
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from ._int import inverse_mod
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    from ._perf._big_num_ctypes import libcrypto
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
19-10-21 22:10:26.9|Error|postSonarr.py|    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
19-10-21 22:10:26.9|Error|postSonarr.py|  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
19-10-21 22:10:26.9|Error|postSonarr.py|    raise RuntimeError("can not find library %s" % name)
19-10-21 22:10:26.9|Error|postSonarr.py|RuntimeError: can not find library crypto
1`

Sonarr version is 2.0.0.5301

**Comment by malhal** [comment]
Hi I'm also running Sonarr and SabNZB Synology community packages and interested in using sickbeard_mp4_automator, is there a tutorial available?

**Comment by mdhiggins** [comment]
It does look like you're missing some libs. Manual.py doesn't make use of all of them so you might be able to run that without errors while not being able to run others

From the errors my quick guess is you're missing the requests security package
`pip install requests[security]`

**Comment by Muckoma** [comment]
@mdhiggins - I'm closing this issue because I just ended up using your docker builds with Sonarr and Radarr built into them which worked fine besides a minor security issue that I've been able to resolve. :)

I might write a guide soon for people to get everything set up so I'd love your feedback when Im' done.
