### ISSUE TITLE
set speed of the encode

### ISSUE THREAD

**Issue by hoyane** [mdhiggins/sickbeard_mp4_automator#1079]
I am trying to figure out how to speed up my conversions. Is there a second option to adjust the speed of the crf factor set. Like in handbrake you can set the rf but then you can adjust the preset from ultrafast to placebo. Is this what the option video profile is for? if so what are the options for that? If not is there another way to accomplish this?

Thanks

**Comment by mdhiggins** [comment]
video-bitrate and video-crf are pretty much the only options, changing the profile might result in faster encodes but not directly equivalent. You may also use preopts / postopts to add in more specific options to ffmpeg to try to reduce times
