### ISSUE TITLE
Some Processed Movie Files Just Show Tagged Poster On Screen

### ISSUE THREAD

**Issue by drewid79** [mdhiggins/sickbeard_mp4_automator#1080]
Hello! As the title says, when playing some processed movie files the video doesn't show on screen. I just see the movie poster. Seems random and I only find them occasionally. Audio tracks play fine. I can share info about the files and the config file, but was wondering if you've seen this before? Thanks for help!

**Comment by mdhiggins** [comment]
That's usually only when there's a problem with the video stream either being corrupt to absent

**Comment by drewid79** [comment]
Hmmm, I don't think that was the case here. It turns out this happened to
about 200 movies. Most of them I know for sure played just fine before
conversion. I've re-downloaded them all now, but thanks for your reply.

**Comment by mdhiggins** [comment]
Feel free to post some actual info on a file that's failing otherwise its all speculation

`ffprobe file.mp4 -show_streams` and post that whole dump of info
