### ISSUE TITLE
Feature Request: Option to burn-in forced subtitles

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1083]
Right now, forced subs are added but not marked as forced because mp4 containers do not support it. Outputting them to SRT does solve this, but it would be nice to have an option of burning them into the video for compatibility instead of having to use srt.

**Comment by LandMineHare** [comment]
I second this. Some movies with forced subtitles like "A Quiet Place" don't work without them being burned in.

**Comment by mdhiggins** [comment]
Just pushed some updates to try to support this

- `burn-subtitles` = Burns subtitles onto video stream. Valid parameters are `true` / `any`, `false`, `default`, `forced`, `default, forced`. If a valid subtitle for burning is found this will force the video stream to be encoded (cannot copy). Internal subtitles are prioritized over external subtitles. This feature does not support image based subtitle formats

Use the new sorting features added to further sub-select which subtitle gets burned beyond the forced/default limiters the option supports
