### ISSUE TITLE
postSonarr.py Error

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1086]
19-11-12 22:33:55.6|Info|OwinHostController|Listening on the following URLs:
19-11-12 22:33:55.6|Info|OwinHostController|  http://*:8989/
19-11-12 22:33:55.7|Info|NancyBootstrapper|Starting Web Server
19-11-12 22:33:56.4|Warn|MonoDebugCheck|Mono is not running with --debug switch
19-11-12 22:34:26.3|Info|RssSyncService|Starting RSS Sync
19-11-12 22:34:31.8|Info|DownloadDecisionMaker|Processing 472 releases
19-11-12 22:34:32.6|Info|RssSyncService|RSS Sync Completed. Reports found: 472, Reports grabbed: 0
19-11-12 22:38:25.6|Info|SceneMappingService|Updating Scene mappings
19-11-12 22:38:26.8|Info|RefreshSeriesService|Updating Info for SpongeBob SquarePants
19-11-12 22:38:27.2|Info|RefreshEpisodeService|Starting episode info refresh for: [75886][SpongeBob SquarePants]
19-11-12 22:38:27.5|Info|RefreshEpisodeService|Finished episode refresh for series: [75886][SpongeBob SquarePants].
19-11-12 22:38:27.5|Info|DiskScanService|Scanning disk for SpongeBob SquarePants
19-11-12 22:38:29.0|Info|DiskScanService|Completed scanning disk for SpongeBob SquarePants
19-11-12 22:38:29.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
19-11-12 22:38:29.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
19-11-12 22:38:29.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
19-11-12 22:38:29.2|Info|ExistingExtraFileService|Found 0 extra files
19-11-12 22:38:32.8|Info|NzbSearchService|Searching 5 indexers for [SpongeBob SquarePants : S02]
19-11-12 22:38:35.7|Info|DownloadDecisionMaker|Processing 79 releases
19-11-12 22:38:36.9|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E18b.Artist.Unknown.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:36.9|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E18b.Artist.Unknown.DVDRip.x264-TiMEGOD
19-11-12 22:38:37.1|Error|python|Traceback (most recent call last):
19-11-12 22:38:37.1|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:37.1|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:37.1|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:38.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E02b.Bossy.Boots.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:38.7|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E02b.Bossy.Boots.DVDRip.x264-TiMEGOD
19-11-12 22:38:38.9|Error|python|Traceback (most recent call last):
19-11-12 22:38:38.9|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:38.9|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:38.9|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:40.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E03b.Bubble.Buddy.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:40.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E03b.Bubble.Buddy.DVDRip.x264-TiMEGOD
19-11-12 22:38:41.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:41.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:41.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:41.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:42.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E04b.Imitation.Krabs.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:42.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E04b.Imitation.Krabs.DVDRip.x264-TiMEGOD
19-11-12 22:38:43.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:43.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:43.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:43.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:44.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E05b.Patty.Hype.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:44.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E05b.Patty.Hype.DVDRip.x264-TiMEGOD
19-11-12 22:38:45.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:45.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:45.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:45.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:46.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E06b.Squidville.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:46.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E06b.Squidville.DVDRip.x264-TiMEGOD
19-11-12 22:38:47.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:47.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:47.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:47.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:48.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E07b.Life.of.Crime.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:48.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E07b.Life.of.Crime.DVDRip.x264-TiMEGOD
19-11-12 22:38:49.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:49.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:49.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:49.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:50.9|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E08.Christmas.Who.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:50.9|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E08.Christmas.Who.DVDRip.x264-TiMEGOD
19-11-12 22:38:51.1|Error|python|Traceback (most recent call last):
19-11-12 22:38:51.1|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:51.1|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:51.1|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:52.8|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E09b.Dumped.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:52.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E09b.Dumped.DVDRip.x264-TiMEGOD
19-11-12 22:38:53.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:53.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:53.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:53.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:54.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E10a.No.Free.Rides.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:54.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E10a.No.Free.Rides.DVDRip.x264-TiMEGOD
19-11-12 22:38:55.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:55.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:55.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:55.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:57.4|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E11b.Squirrel.Jokes.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:57.5|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E11b.Squirrel.Jokes.DVDRip.x264-TiMEGOD
19-11-12 22:38:57.7|Error|python|Traceback (most recent call last):
19-11-12 22:38:57.7|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:57.7|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:57.7|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:38:58.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E12b.The.Smoking.Peanut.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:38:58.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E12b.The.Smoking.Peanut.DVDRip.x264-TiMEGOD
19-11-12 22:38:59.0|Error|python|Traceback (most recent call last):
19-11-12 22:38:59.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:38:59.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:38:59.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:00.9|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E13a.Shanghaied.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:00.9|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E13a.Shanghaied.DVDRip.x264-TiMEGOD
19-11-12 22:39:01.2|Error|python|Traceback (most recent call last):
19-11-12 22:39:01.2|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:01.2|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:01.2|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:02.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E14b.Frankendoodle.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:02.7|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E14b.Frankendoodle.DVDRip.x264-TiMEGOD
19-11-12 22:39:03.0|Error|python|Traceback (most recent call last):
19-11-12 22:39:03.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:03.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:03.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:04.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E15b.Band.Geeks.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:04.9|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E15b.Band.Geeks.DVDRip.x264-TiMEGOD
19-11-12 22:39:05.1|Error|python|Traceback (most recent call last):
19-11-12 22:39:05.1|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:05.1|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:05.1|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:06.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E16b.Krusty.Love.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:06.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E16b.Krusty.Love.DVDRip.x264-TiMEGOD
19-11-12 22:39:07.0|Error|python|Traceback (most recent call last):
19-11-12 22:39:07.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:07.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:07.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:08.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E17b.Im.With.Stupid.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:08.8|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E17b.Im.With.Stupid.DVDRip.x264-TiMEGOD
19-11-12 22:39:09.0|Error|python|Traceback (most recent call last):
19-11-12 22:39:09.0|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:09.0|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:09.0|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:10.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E18a.Sailor.Mouth.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:10.7|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E18a.Sailor.Mouth.DVDRip.x264-TiMEGOD
19-11-12 22:39:10.9|Error|python|Traceback (most recent call last):
19-11-12 22:39:10.9|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:10.9|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:10.9|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:12.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E19b.The.Fry.Cook.Games.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:12.7|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E19b.The.Fry.Cook.Games.DVDRip.x264-TiMEGOD
19-11-12 22:39:12.9|Error|python|Traceback (most recent call last):
19-11-12 22:39:12.9|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:12.9|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:12.9|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:14.7|Info|Sabnzbd|Adding report [SpongeBob.SquarePants.S02E20b.Squid.on.Strike.DVDRip.x264-TiMEGOD] to the queue.
19-11-12 22:39:14.7|Info|DownloadService|Report sent to sab. SpongeBob.SquarePants.S02E20b.Squid.on.Strike.DVDRip.x264-TiMEGOD
19-11-12 22:39:14.9|Error|python|Traceback (most recent call last):
19-11-12 22:39:14.9|Error|python|  File "/home/(removed)/Desktop/Convert/postSonarr.py", line 39, in <module>
19-11-12 22:39:14.9|Error|python|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-11-12 22:39:14.9|Error|python|TypeError: int() argument must be a string or a number, not 'NoneType'
19-11-12 22:39:14.9|Info|SeasonSearchService|Season search completed. 20 reports downloaded.
19-11-12 22:39:15.0|Info|DiskScanService|Scanning disk for SpongeBob SquarePants
19-11-12 22:39:15.1|Info|DiskScanService|Completed scanning disk for SpongeBob SquarePants
19-11-12 22:39:15.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
19-11-12 22:39:15.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
19-11-12 22:39:15.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
19-11-12 22:39:15.3|Info|ExistingExtraFileService|Found 0 extra files

**Comment by mdhiggins** [comment]
Where are these log files coming from? It looks like Sonarr didn’t set any of its post processing environment variables which would suggest maybe its being executed from somewhere else. Log files kind of look like SAB logs

**Comment by mdhiggins** [comment]
Related to the other error you posted, you're probably getting this cyclical issue because the script is trying to requeue sonarr when it fails. Question is why are none of your sonarr environment variables being passed to the script

**Comment by JySzE** [comment]
This is from sonarr.txt: https://pastebin.com/HmYMexjc

**Comment by JySzE** [comment]
And my ini file : https://pastebin.com/5kWLxMF9

**Comment by JySzE** [comment]
#1085 This might be related?

**Comment by cdorrington** [comment]
yes - related.

**Comment by mdhiggins** [comment]
Related but also a bandaid fix
This change essentially suppresses errors when the script isn't executing with environment variables like its supposed to by wrapping them in trys

Could you post your sonarr config settings for the script? (from inside sonarr's options)

**Comment by mdhiggins** [comment]
Nevermind saw that you did that

Are you running this inside docker or just a regular linux install?

**Comment by JySzE** [comment]
Yep regular Linux install 

![image](https://user-images.githubusercontent.com/25883052/68796989-9e167b80-0608-11ea-8d2d-3ce70a3be4ac.png)

**Comment by mdhiggins** [comment]
Try adding
`log.info(str(os.environ))`
to your postSonarr script after line 39 to see what environment variables you actually have

**Comment by JySzE** [comment]
@mdhiggins https://pastebin.com/vtjWyDX5

**Comment by JySzE** [comment]
let me know if you need anymore info.

**Comment by mdhiggins** [comment]
So yeah there's a problem with Sonarr where you're missing all the sonarr-injected environment variables though why that is I'm not sure. 
One thing to try might be to have sonarr call postSonarr.py directly instead of your python executable with the script as an argument, though I use that setup without issues but see if that makes any change. I haven't been able to find any documentation of anyone else with this issue but its really more of a sonarr problem
Do you use radarr and is radarr also having this problem?

**Comment by mdhiggins** [comment]
Sonarr handles the custom scripts here
https://github.com/Sonarr/Sonarr/blob/f2efebf7d94cf707e0594dabcbb5a6394e32622c/src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs

Which then passes off to the process provider class here:
https://github.com/Sonarr/Sonarr/blob/7503ce62af1f1d4796d92ad70a0cbaa52bd95fbf/src/NzbDrone.Common/Processes/ProcessProvider.cs

The process provider class injects the environment variables at this stage. Looking through their code there is some error logging that should take place if there's a problem doing that though you may need to adjust your logging settings to see it (not sure)

**Comment by JySzE** [comment]
yeah radarr is also having issues, different error tho I will post it later and can you post an example on how I should set it up how you described ? 

> One thing to try might be to have sonarr call postSonarr.py directly instead of your python executable with the script as an argument

**Comment by JySzE** [comment]
Error from radarr also:
![image](https://user-images.githubusercontent.com/25883052/68912851-3d716680-070e-11ea-8688-dd4b124103aa.png)

**Comment by mdhiggins** [comment]
Looks like maybe the final portion of that error is cropped off cause I see the stack trace but not the actual error in that screenshot

**Comment by cdorrington** [comment]
> Related but also a bandaid fix
> This change essentially suppresses errors when the script isn't executing with environment variables like its supposed to by wrapping them in trys
> 

Correct, but wouldn't you want the script to execute successfully regardless of whether these environment variables are passed? These external dependencies should be optional and the script should proceed whenever missing or invalid - Sonarr can pick them up regardless.

I encountered the same issue as this thread which is why I'm proposing #1085;  similar issues were also reported on issues #899, #974 & #1021.

**Comment by JySzE** [comment]
Should i contact sonarr support to find out why sonarr is missing all environment variables?

**Comment by mdhiggins** [comment]
May not be a bad idea because I'm at a loss. Did you try changing to executing the python script directly as above?

**Comment by JySzE** [comment]
@mdhiggins no how would i set it up to do so? can i get a picture example?

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/69245272-84c77f00-0b74-11ea-9506-089270dbfc8f.png)
Just delete what you have in the path field and move what you have in the argument field into the path field, then leave argument blank

**Comment by JySzE** [comment]
sonarr Dev responded back and said sonarr env variables were not the issue?

**Comment by mdhiggins** [comment]
I mean you have none of the environment variables so I would disagree

**Comment by mdhiggins** [comment]
Feel free to link me to the issue

**Comment by JySzE** [comment]
@mdhiggins yeah I put a link to the issue here on the issue on the on sonarr, which would link them back to here.

**Comment by mdhiggins** [comment]
Yeah can I get a link to the sonarr issue to see what they said

**Comment by mdhiggins** [comment]
NeverMind I see it. I would open a post on their forums as suggested

**Comment by JySzE** [comment]
oh yeah sorry it said up a few messages ago I mentioned this issue there I guess you can't see it?

https://github.com/Sonarr/Sonarr/issues/3413

**Comment by mdhiggins** [comment]
Did you try calling the script directly as above yet?

**Comment by JySzE** [comment]
will do when i get home later tonight

**Comment by JySzE** [comment]
tried it to no avail 
![image](https://user-images.githubusercontent.com/25883052/69470023-c27d0100-0d48-11ea-9fb5-b159aa3b0c37.png)

**Comment by mdhiggins** [comment]
I did some reading and it looks like python can be executed in an isolation mode (usually with a command line argument) though I’m wondering if maybe your python install has something weird configured that’s forcing that mode

**Comment by JySzE** [comment]
@mdhiggins il make another linux vm and test a fresh setup.

**Comment by JySzE** [comment]
Brand new fresh linux install with everything back up and running and same error, I'm completely stumped.

**Comment by cdorrington** [comment]
for fun could you test my fork and report back?  Maybe we're the only two people running fresh installs.

**Comment by JySzE** [comment]
@cdorrington : https://pastebin.com/qRQyvmKd

**Comment by mdhiggins** [comment]
I mean the docker containers work fine which are essentially fresh installs / VMs
@cdorrington I'm sure your fork doesn't crash but it also has none of the sonarr metadata to do its processing, its just bypassing anything dependent on that data
There's a problem with your environment that's causing the sonarr populated environment variables to be lost
You could try creating a python virtual env (which is how the docker contain I'm using works)

**Comment by JySzE** [comment]
i made a forum post on sonarr, but we will see if I get any help or not. 

https://forums.sonarr.tv/t/mp4-automator-and-sonar-env-variables-issues/24041

**Comment by JySzE** [comment]
I ended up just adding -movsflag faststart to my the ini file and had sonarr do all the handling with no post sonarr since im not doing any tagging. I got some help from someone on their discord that basically told me postsonarr.py isnt needed.

**Comment by mdhiggins** [comment]
While I'm glad you got a solution that works for you this is again missing the point of an underlying issue with your setup that's causing the environment variables to fail

I think trying to set up a python virtualenv might be a good solution if you want to get everything working entirely but it all depends on the effort you want to expend to troubleshoot this further

**Comment by JySzE** [comment]
@mdhiggins this is incredibly embarrassing, I fixed the issue.

Setting up the connection to the custom script in sonar was my issue. 

All i had to do was go from this: 
![69470023-c27d0100-0d48-11ea-9fb5-b159aa3b0c37](https://user-images.githubusercontent.com/25883052/70384621-5ef0f700-1936-11ea-9eab-68bfb42ff389.png)

to this:
![image](https://user-images.githubusercontent.com/25883052/70384626-69ab8c00-1936-11ea-9ac0-c66285396780.png)


You even have it perfectly spelt out in the sonarr setup.... sorry for wasting your time!
