### ISSUE TITLE
after deluge has finished seeding.

### ISSUE THREAD

**Issue by jaime2k190** [mdhiggins/sickbeard_mp4_automator#1088]
i had 15 torrents in queue downloading. and 6 had finished around the same times. and for some reason it was converting them all. is there a way to be able to queue them up, so it would just 1 or 2 at a time. then do the others. because every time 1 finishes download. it auto start converting and the other day i ended up with nearly 8 converting at same time. could some help me out with this please?

**Comment by mdhiggins** [comment]
No good way to solve this other than using completed download handling which will queue the conversions at the sonarr/radarr level
Deluge itself does not have a queuing system and will execute the scripts whenever they finish
