### ISSUE TITLE
Force-Convert Error manual.py

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1091]
Force convert does not work via manual.py

![Screenshot_4](https://user-images.githubusercontent.com/25883052/69222786-04caf600-0b2f-11ea-8336-9290387427bd.png)

**Comment by mdhiggins** [comment]
It does it just doesn't have its own command line parameter, though I just added that in a new build
use `-fc` or `--forceconvert`
