### ISSUE TITLE
Process completion

### ISSUE THREAD

**Issue by 1stian** [mdhiggins/sickbeard_mp4_automator#1094]
Hello, I am unable to get the % completed.. The last message is "Starting conversion". I am not getting  the progress.

I've changed "reportProgrss" to true in the mkvtomp4.py. But that didn't help. The script is being run by SABnzbd.. 

Anyway to enable it??

**Comment by T0rm3nt** [comment]
Would be great if it gave feedback into SABnzbd and showed the percentage when it was converting... 
I also tried adding a progress bar script from github using the postopt/preopt variables but couldn't seem to get it to work, perhaps I was adding it wrong? (ffmpeg-progressbar-cli)

**Comment by mdhiggins** [comment]
This is a limit to SAB logging it doesn't have an api that allows you to report progress and it doesn't support the method used to write to the console by the script for the progress
