### ISSUE TITLE
Manual.py encoding not carrying over correct scan type 

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1095]
Im running manual.py to encode a few old scrub dvd's and the remuxes are interlaced but after running it with manual.py its changing the scan type to progressive and now nothing can de interlace it properly due to wrong reported scan type. 

Media info for dvd remux: https://pastebin.com/vRgJdGDA

Media info from the manual.py encode: https://pastebin.com/Hq1EGDqk

**Comment by JySzE** [comment]
update: i think this is a ffmpeg issue where its assuming its progressive for some reason:

https://github.com/voc/voctomix/issues/137#issue-246605154

i have to manually add -field_order 2 for it to work properly.

**Comment by JySzE** [comment]
Small update, 

FFprobe can detect interlaced fields either top field or bottom field.

Maybe a way to address this would be if FFprobe detects either Top or Bottom send this argument `-field_order 2` to ffmpeg?

**Comment by JySzE** [comment]
Bump

**Comment by mdhiggins** [comment]
Can you post an ffprobe -show_streams output from a file that's giving you problems? This should be doable

**Comment by JySzE** [comment]
https://pastebin.com/ADXtR3MV

**Comment by mdhiggins** [comment]
08deefb2a78ca7f74ce1bf150affda9808286f63

See if that does the trick

**Comment by mdhiggins** [comment]
Should  be fixed now, closing
