### ISSUE TITLE
Qbittorrent

### ISSUE THREAD

**Issue by TinTin192** [mdhiggins/sickbeard_mp4_automator#1098]
Sorry if this has been addressed already but i haven't found anything around that helps me out.
Just installed Qbittorrent as it's now supported etc.

Linked to Sonarr/Radarr. Both download's work. 
Sonarr - Download file through Qbittorrent.
File stay's in download location. No convert. No move. (Seeding)

Radarr - Download file through Qbittorrent
File stay's in download location. No convert. No move. (Seeding)

My Command in Qbittorrent -
"/home/folder/folder/qBittorrentPostProcess.py" "%L" "%T" "%R" "%F" "%N" "%I"

Have also tried 

"/usr/bin/python" "/home/folder/folder/qBittorrentPostProcess.py" "%L" "%T" "%D" "%K" "%F" "%I" "%N"

Settings for Qbit - 

[qBittorrent]
convert = True
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = tv-sonarr
bypass-label = bypass
sickrage-label = sickrage
action_before = stop
action_after = deletedata
host = http://IPADDRESS:8086/
username = USER
password = PASSWORD
output_directory = 
radarr-label = radarr

**Comment by TinTin192** [comment]
(N) 2019-12-09T03:08:43 - Successfully moved torrent: fuller.house.s05e01.web.x264-strife[eztv].mkv. New path: /home/Downloads/qbittorrent/completed/
(N) 2019-12-09T03:08:43 - Torrent: fuller.house.s05e01.web.x264-strife[eztv].mkv, running external program, command: &quot;/home/vodflix/.scripts/qBittorrentPostProcess.py&quot; &quot;tv-sonarr&quot; &quot;udp://tracker.openbittorrent.com:80&quot; &quot;/home/Downloads/qbittorrent/completed/fuller.house.s05e01.web.x264-strife[eztv].mkv&quot; &quot;/home/Downloads/qbittorrent/completed/fuller.house.s05e01.web.x264-strife[eztv].mkv&quot; &quot;fuller.house.s05e01.web.x264-strife[eztv].mkv&quot; &quot;f76fdd1e01e60a8642b4fbe2916f01b9b6001f23&quot;

Qbittorent log or part of it anyway to assist

**Comment by mdhiggins** [comment]
Is the script actually executing? There should be log files for SMA either in the script directory or in /var/log/sickbeard_mp4_automator

If the script isn't being called or is having an error things will just sit there. The fact that no conversion is happening means something is failing pretty early

Does manual.py run and work without issues?

**Comment by drikqlis** [comment]
I had similar problem, when running qBittorentPostProcess manually i got:
```
2019-12-11 19:39:20 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2019-12-11 19:39:20 - readSettings - INFO - /usr/bin/python
2019-12-11 19:39:20 - readSettings - WARNING - Force-convert is true, so convert-mp4 is being overridden to true as well
Traceback (most recent call last):
  File "/opt/mp4auto/qBittorrentPostProcess.py", line 75, in <module>
    qb = Client(settings.qBittorrent['host'])
  File "/home/user/.local/lib/python2.7/site-packages/qbittorrent/client.py", line 30, in __init__
    """)
RuntimeError: 
                This wrapper only supports qBittorrent applications
                 with version higher than 3.1.x.
                 Please use the latest qBittorrent release.
```
My qBittorrent was on version 4.2.0 and it looks like there is new API and python-qbittorrent is not yet updated. I downgraded qbittorrent to 4.0.3 and it is working.

**Comment by drikqlis** [comment]
python-qbittorrent was updated to work with the new API and it looks like it works with newest qBittorrent version now after `pip install --upgrade python-qbittorrent`
