### ISSUE TITLE
Feature Request: Opus audio support

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1099]
Add the ability to encode audio into Opus audio format. (libopus)

ffmpeg options: https://www.ffmpeg.org/ffmpeg-codecs.html#libopus-1

**Comment by mdhiggins** [comment]
```
class Opus(AudioCodec):
    """
    Opus audio codec
    """
    codec_name = 'opus'
    ffmpeg_codec_name = 'libopus
```

Added, please give it a try

**Comment by RandomNinjaAtk** [comment]
Gave it an attempt and got the following error:

```
[mp4 @ 0x558e7929af40] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
```

**Comment by RandomNinjaAtk** [comment]
Follow up, after adding:
```
postopts= -strict, -2
```
It processed normally.

**Comment by mdhiggins** [comment]
Updated the codec to include this so its not needed in postopts

**Comment by RandomNinjaAtk** [comment]
Quick question...

Is it possible to just set a overall bitrate for audio codec?

The problem is with no bitrate specified, it ballons because it gives it 256 per channel. In according to guidence online, ie: https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings&mobileaction=toggle_view_desktop

The overall bitrate only needs to be within this range: 128 - 450

I would like to be able set it statically to say 256, regardless of how many channels

**Comment by mdhiggins** [comment]
No it can only be set on a per channel basis

**Comment by RandomNinjaAtk** [comment]
Hmm, I guess setting the bitrate to 64K is about as close as you can get to the recommended spec.
