### ISSUE TITLE
Default audio-filter normalization

### ISSUE THREAD

**Issue by stevemk14ebr** [mdhiggins/sickbeard_mp4_automator#1104]
I suggest setting dynaudnorm as the default value for audio-filter and ios-audio-filter in autoProcess.ini. It's performance is excellent, and it really doesn't produce any artifacts or clipping in the output in my experience. Relates to #219 #930 and #206 (which sets custom pan settings). I also advocate for the removal of those custom pan settings and replacing with this. 

This filter uses this library: https://github.com/lordmulder/DynamicAudioNormalizer. If you read their readme i think you will be impressed with its features and the considerations it takes. It was merged to ffmpeg with the patch here: https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2015-July/175331.html

**Comment by stevemk14ebr** [comment]
Additionally i have a question, i added that filter like i said and this was my output: 

> "audio": {
>         "0": {
>             "map": 1,
>             "codec": "aac",
>             "channels": 2,
>             "bitrate": 256,
>             "filter": null,
>             "language": "eng",
>             "disposition": "default"
>         },
>         "1": {
>             "map": 1,
>             "codec": "ac3",
>             "channels": 6,
>             "bitrate": 1536,
>             "filter": "dynaudnorm",
>             "language": "eng",
>             "disposition": "none"
>         }

why was the filter null on the two channel track?

**Comment by mdhiggins** [comment]
Think its benefits are worthwhile enough that it should be the default option as opposed to no filter currently?
Also I don't believe any custom pan settings were ever merged into the master branch, though correct me if I'm wrong there its been a while

**Comment by stevemk14ebr** [comment]
In my opinion yes it's worth it. I posted a wave form as the last comment on #219 . I think I made a mistake saying pan settings were merged. This filter normalizes the files sound against the file itself. This makes it so that individual files have different Db levels, but that each file is relatively within its own range. So you could run a pass after the fact that was just a simple gain +/- on the whole file and your entire library would be consistently at the correct volume
