### ISSUE TITLE
What does the ignore-trudhd parameter in autoProcess.ini do?

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1107]
Like the title says, I see an `ignore-trudhd = true` parameter in the sample autoProcess.ini file but I don't see any documentation about it. I also don't see anyone even remotely mentioning this parameter anywhere so what does it do?

**Comment by mdhiggins** [comment]
It ignores trueHD audio streams
Lots of releases include trueHD audio streams in addition to the exact same AC3 stream. MP4 files don't support trueHD, so the script previously would convert trueHD and copy the AC3 stream, then people end up with duplicate audio streams of similar quality and waste encoding time

See here
https://github.com/mdhiggins/sickbeard_mp4_automator/pull/816

And here
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1027

**Comment by kevindd992002** [comment]
Ok. Is the trudhd part a typo that you plan on fixing?

**Comment by mdhiggins** [comment]
Didn’t even notice. Yeah I’ll fix that

**Comment by kevindd992002** [comment]
Great, thanks!

**Comment by mdhiggins** [comment]
76c82279455aae284e67c0daa5696158c79ab1a7
Fixed

**Comment by kevindd992002** [comment]
@mdhiggins If i want lossless trueHD streams to be part of my media files, do I need to keep the files in mkv format? What's the advantage of converting everything to mp4 anyway? Is mp4 only preferable if you have Apple devices streaming off of your Plex server?

**Comment by mdhiggins** [comment]
Correct, mp4 does not support trueHD
MP4 files tend to have more compatibility for direct playback on lots of devices, not just apple devices (steam sticks, phones, etc)

**Comment by kevindd992002** [comment]
Ok. AAC doesn't support TrueHD too, right? If so, what other sma parameters do I need to set to make sure that TrueHD is copied, set as the 1st track, and an AAC track set as the 2nd?

**Comment by mdhiggins** [comment]
You can’t have true HD in mp4

**Comment by kevindd992002** [comment]
> You can’t have true HD in mp4

Yes, but given that I don't convert to mp4 and just leave it at mkv. This is possible with your script, isn't it?
