### ISSUE TITLE
PostProcess for NZB Drone

### ISSUE THREAD

**Issue by Mirabis** [mdhiggins/sickbeard_mp4_automator#111]
I'd like to convert my TV-Shows to mp4 like sickbeard does but duo the nature of NZBDrone being different this never worked before.

Then I found a page on their wiki, last updated 20 days ago: https://github.com/NzbDrone/NzbDrone/wiki/Disable-Drone-Factory-Folder-Scanning

We can disable the Drone Factory scan and send a command to their API to scan the folder. 

Would it be possible to implement, if not i'd like to donate for a custom script :+1: 

Workflow

Sab downloads into .../downloads/nzbDrone, runs the script which converts and moves the file to .../downloads/DroneFactory and then sends a command to scan the Drone Factory.

Using two folders, because it might pickup an unconverted file while processing a just finished download.. causing it to move the unprocessed file as well.

**Comment by zybeon** [comment]
Can we close this issue out with the nzbToSonarrMP4.py update?

**Comment by mdhiggins** [comment]
All looks good. Gonna close out the issue
