### ISSUE TITLE
Running ./manual.py results in error message

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1110]
Hi,

I noticed that the Automator was updated a few days ago and decided to download it and replace the old version I had. When I run the ``./manual.py`` I now get an error message I never saw before. 

I'm not really sure how to solve this myself since I've never experienced this issue before.

I appreciate any help! Thank you!

//Morgan

See below;

```$ ./manual.py
Traceback (most recent call last):
  File "./manual.py", line 13, in <module>
    from tvdb_mp4 import Tvdb_mp4
  File "/path/automator_test/tvdb_mp4.py", line 11, in <module>
    import tmdbsimple as tmdb 
ImportError: No module named tmdbsimple

**Comment by JySzE** [comment]
`pip install tmdbsimple`

**Comment by mdhiggins** [comment]
APIs were updated and changed and the prereqs have also changed to reflect this, JzSzE's response is correct

**Comment by morganzero** [comment]
Thank you very much @JySzE and @mdhiggins.
