### ISSUE TITLE
Plex autoscan integration does not work

### ISSUE THREAD

**Issue by hacktek** [mdhiggins/sickbeard_mp4_automator#1112]
Hi there.

I can't get Plex_Autoscan to work when using the included python post processing script. With regular Plex_Autoscan the request included the .mkv file (which I am not keeping) so Plex_Autoscan never actually found that file so it never actually scan the path as expected.

I'm running radarr and sonarr with SMA integrated from these docker containers: 

https://hub.docker.com/r/mdhiggins/radarr-sma
https://hub.docker.com/r/mdhiggins/sonarr-sma

I went into each of the containers and modified the /usr/local/bin/sma/sickbeard_mp4_automator/post_process/plex_autoscan.py file to include my URL:

```
root@daa096dd95b3:/# cat /usr/local/bin/sma/sickbeard_mp4_automator/post_process/plex_autoscan.py 
#!/usr/bin/python
import os
import json
import requests

def main():
        print("Plex Autoscan Post Script")
        url = "http://domain.com:3467/111112rdlkhfkdjhfjkdsh"

        files = json.loads(os.environ.get('MH_FILES'))
        if not (files):
        print("Error - Did not find environment variables.")
...
```
I then configured Plex_Autoscan and SMA as per the notes here: https://github.com/Cloudbox/Cloudbox/wiki/Extra%3A-Sickbeard-MP4-Automator

Is that all that's needed? Do I need to manually call this script? If so, with which settings?

With the way it's currently configured my understanding was that SMA would take care of calling Plex_Autoscan with the path including the mp4 as a manual request but I don't see that request when I look at the autoscan logs.

Thanks!

**Comment by notorius28** [comment]
Check this post [here](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/856#issuecomment-406683600), it worked for me

**Comment by mdhiggins** [comment]
Updated
