### ISSUE TITLE
All of a sudden when trying to run the script I get a random error

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1113]
Been running the script fine for months with no issues but all of a sudden I get this
Traceback (most recent call last):
  File "C:\Converter\manual.py", line 13, in <module>
    from tvdb_mp4 import Tvdb_mp4
  File "C:\Converter\tvdb_mp4.py", line 11, in <module>
    import tmdbsimple as tmdb
ModuleNotFoundError: No module named 'tmdbsimple'

**Comment by JySzE** [comment]
`pip install tmdbsimple`

**Comment by morpheus2n2** [comment]
Yep, seems when my PC did windows update last night something messed with the python install, just ran through all the pre-requirements again and about 3 things reinstalled themselves as if they where not already there lol
