### ISSUE TITLE
include nvenc capabile ffmpeg in docker containers

### ISSUE THREAD

**Issue by kmr2319** [mdhiggins/sickbeard_mp4_automator#1120]
Looking to migrate to your dockers which are super convenient. But being able to redirect a GPU to the dockers and use HW encoding for ffmpeg would awesome also...

The problem:
I haven't found any solid static builds of ffmpeg with nvenc support enabled.

[LSIO has a docker](https://github.com/linuxserver/docker-ffmpeg) which is nice, but I can't seem to find where the ffmpeg build itself is coming from... :confused: :confounded: 

I also tried out [this gist](https://gist.github.com/Brainiarc7/3f7695ac2a0905b05c5b) within your docker - it takes a long time and ultimately fails. So even if it was successful, anytime the image is created would take a long time if ffmpeg had to be rebuilt. Might be better to have a build -- or at least an option for the user to build -- that includes nvenc support.

If you've got any other thoughts, I could test, report back and/or submit PRs accordingly...

Thanks!

**Comment by mdhiggins** [comment]
I think this might be how they are getting FFMPEG

https://github.com/linuxserver/ffmpeg-builder/blob/master/Dockerfile

**Comment by kmr2319** [comment]
Good find! I'm embarrassed that I didn't find it considering how long I was poking around. I'm going to blame reduced mental capacity due to being sick for the last week.

Still on the mend and didn't look into it that long so far, but I don't see where they are storing artifacts at all. I poked around their Jenkins instance ([docker pipeline example](https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-ffmpeg/detail/master/34/pipeline)) as well...

Are you interested in something like this? I'd be willing to contact the LSIO team via their [forum](https://discourse.linuxserver.io/) to see if they post artifacts publicly at all...

**Comment by mdhiggins** [comment]
My be able to just include the `FROM lsiobase/ffmpeg:bin as binstage` in my dockerfile in lieu of the current implementation, it appears to store things in `/usr/local/bin/ffmpeg` and then point autoProcess.ini to that

**Comment by mdhiggins** [comment]
Won't be able to test it for a couple days but if you wanted to give it a shot I think that's where I would start

**Comment by kmr2319** [comment]
Sounds like a plan. I'll see if I can muck with it and report back/PR if I can.

**Comment by mdhiggins** [comment]
```
FROM linuxserver/sonarr
FROM lsiobase/ffmpeg:bin as binstage
MAINTAINER mdhiggins <mdhiggins23@gmail.com>

# get python3 and git, and install python libraries
RUN \
  apt-get update && \
  apt-get install -y \
    git \
    wget \
    python3 \
    python3-pip && \

# install pip, venv, and set up a virtual self contained python environment
  python3 -m pip install --user --upgrade pip && \
  python3 -m pip install --user virtualenv && \
  mkdir /usr/local/bin/sma && \
  python3 -m virtualenv /usr/local/bin/sma/env && \
  /usr/local/bin/sma/env/bin/pip install requests \
    requests[security] \
    requests-cache \
    babelfish \
    tmdbsimple \
    'guessit<2' \
    'subliminal<2' \
    'stevedore==1.19.1' \
    python-dateutil \
    qtfaststart && \

# download repo
  git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git /usr/local/bin/sma/sickbeard_mp4_automator && \

# create logging directory
  mkdir /var/log/sickbeard_mp4_automator && \
  touch /var/log/sickbeard_mp4_automator/index.log && \
  chgrp -R users /var/log/sickbeard_mp4_automator && \
  chmod -R g+w /var/log/sickbeard_mp4_automator && \

# ffmpeg
  chmod g+x /usr/local/bin/ffmpeg && \
  chmod g+x /usr/local/bin/ffprobe && \

# cleanup
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
```

Just a rough guess to help guide you

**Comment by mdhiggins** [comment]
Not sure if you've been following along but I think this is solved now

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1059#issuecomment-587059654
