### ISSUE TITLE
Only convert one file at a time?

### ISSUE THREAD

**Issue by djs4000** [mdhiggins/sickbeard_mp4_automator#1121]
Hello,
I have the script configured to run from Radarr and Sonarr and it works pretty great, but the issue is i run a pretty low end intel NUC server and if multiple downloads finish together, then each file gets sent to transcode all at once. Is it possible to queue transcodes? My system can get bog down to the point of unusability with 3 or 4 simultaneous transcodes.

**Comment by mdhiggins** [comment]
Not really. The script isn't really 'self aware' of other instances as it functions mainly as addons to other more persistent pieces of software. This would actually be a feature more cleanly implemented at the level of Sonarr/Radarr. 

One potential solution if you only use one downloading program (SAB/NZBGet) is to have the conversion handled by those programs which will automatically queue and transcode one at a time.
