### ISSUE TITLE
Keep all original audio tracks

### ISSUE THREAD

**Issue by Dead-Rekon** [mdhiggins/sickbeard_mp4_automator#1122]
I recently set my entire collection of dual-language media to convert thinking I had proper settings, only to come back to all of my 5.1 English audio tracks removed. Do I have incorrect settings, or does audio-copy-original only copy the default original audio track and not all original audio tracks? Previous setup was 5.1 Japanese (default) and 5.1 English. The result was 2.0 AAC English (default), 2.0 AAC Japanese, and 5.1 Japanese. I'm using this exclusively for manually converting media on a Windows 10 PC.

Desired setup was to be 2.0 AAC English (default), 2.0 AAC Japanese, 5.1 English/Japanese. Thanks in advance!

[MP4]
ffmpeg = C:\FFMPEG\bin\ffmpeg.exe
ffprobe = C:\FFMPEG\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 2
audio-codec = aac
ignore-truehd = false
audio-language = eng,jpn
audio-default-language = eng
audio-channel-bitrate = 0
audio-filter = 
audio-copy-original = True
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
bad-internal-subtitle-sources = pgssub, hdmv_pgs_subtitle, s_hdmv/pgs, dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
bad-external-subtitle-sources = dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
fullpathguess = True
convert-mp4 = False
force-convert = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
temp_extension = 
preopts =

**Comment by mdhiggins** [comment]
Can you post an ffprobe -show_streams of your source and output files as well as the logs for the session for those files

**Comment by Dead-Rekon** [comment]
The original media in question is gone now, but I had another dual audio DTS file. This time, the English DTS was kept but the Japanese DTS  was deleted and Japanese was set as the default audio.

[Log File.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4156973/Log.File.txt)
[Output FFPROBE.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4156974/Output.FFPROBE.txt)
[Source FFPROBE.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4156975/Source.FFPROBE.txt)

**Comment by mdhiggins** [comment]
Think I found out why its not working, just pushed an update if you want to give it another try

**Comment by mdhiggins** [comment]
7b47ac8174d747951bbe7fad49631c7099b2e800

**Comment by Dead-Rekon** [comment]
Closes immediately after selecting path and options with the previous original .mkv

2020-02-04 21:34:55 - MANUAL - INFO - Manual processor started.
2020-02-04 21:34:55 - MANUAL - INFO - C:\Python27\python.exe
2020-02-04 21:35:00 - MANUAL - INFO - Reading video stream.
2020-02-04 21:35:00 - MANUAL - INFO - Video codec detected: h264.
2020-02-04 21:35:00 - MANUAL - INFO - Pix Fmt: yuv420p.
2020-02-04 21:35:00 - MANUAL - INFO - Profile: High.
2020-02-04 21:35:00 - MANUAL - INFO - Reading audio streams.
2020-02-04 21:35:00 - MANUAL - INFO - Audio detected for stream #1: dts [jpn].
2020-02-04 21:35:00 - MANUAL - INFO - Creating audio stream 0 from source stream 1.

**Comment by Dead-Rekon** [comment]
Update: I was initially using update 76c8227. I have tested every update since then up to the 7b47ac8 update and received the previous crash (starting with eb17455).

**Comment by mdhiggins** [comment]
Hmm not able to reproduce this, can you post the exception?

**Comment by mdhiggins** [comment]
I pushed out some additional updates with more debugging information last night; not specific to this issue but probably worth updating to the latest version before more testing

**Comment by Dead-Rekon** [comment]
After updating to the most recent version it converts fine again and preserves both original language tracks. It does however set Japanese  as the first two audio tracks and English as the third with the default tag. This unfortunately gets ignored in my player, as it defaults to the first audio stream regardless. Thanks again for the quick and useful responses.

[Log.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4162637/Log.txt)

**Comment by mdhiggins** [comment]
The order of the tracks is set based on the order of the input file which is probably why they are out of order. What player are you using that's ignoring the default flag?

**Comment by Dead-Rekon** [comment]
Scratch that, I didn't have the default language selection checked in Plex. It's properly selecting English as the default language now. Thanks for all of your help!

**Comment by mdhiggins** [comment]
Your original issue gave me an idea and I just added `sort-tracks-by-language` as an option. It will take your language options and put the tracks in the same order
So if audio-language=eng,jpn then tracks will be reordered to have english first and japanese second. Subtitles work the same way

**Comment by Dead-Rekon** [comment]
I look forward to checking it out. It seems I've encountered another issue. Some seasons of a show are converting and some are being immediately skipped with not much info in the log.

2020-02-05 21:38:27 - MANUAL - INFO - Manual processor started.
2020-02-05 21:38:27 - MANUAL - INFO - C:\Python27\python.exe
2020-02-05 21:38:39 - MANUAL - INFO - Input Data

It ends each skipped file with the last line and nothing else. In the command line I'm seeing "An unexpected error occurred, processing of this file has failed 'language'" I included stream info for one of the failed season files.

[Source FFPROBE.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4162974/Source.FFPROBE.txt)

**Comment by mdhiggins** [comment]
Hm looks like it's a bug with one of the new changes if language isn't defined
Just pushed an update to handle this and prevent it from skipping the file
Also improved the output of that error you were having above so if it persists instead of just saying 'language' it should give you more useful debugging info
