### ISSUE TITLE
[Feature Request]:  Ability to choose 6 channel audio for the ios-audio

### ISSUE THREAD

**Issue by edrikk** [mdhiggins/sickbeard_mp4_automator#1125]
As the title states, most ios devices now support 5.1 channel.  This includes everything from Phones, to iPads, to AppleTV.   

I would like to be able to convert a given input audio format to both X.1 AC3, as well as X.1 AAC.
There are two options here I would think:
- Introduce a new parameter to define the value of X instead of the current hardcoded value in mkvtomp4.py
- Update the hardcoded values to set the channels to 6.

Thanks in advance!

**Comment by mdhiggins** [comment]
Are there any devices that support multi channel AAC and not AC3 or vice versa? Not sure there's demand to have both AAC and AC3 6 channel audio tracks per language. The name iOS audio is sort of old but its more of an option create an additional stereo audio track for devices that don't need more than 2 channels
That being said it wouldn't be hard to add an option. Only reason I haven't renamed the setting is to prevent disrupting people's exist setups
