### ISSUE TITLE
Unable to determine iOS audio bitrate from source stream

### ISSUE THREAD

**Issue by sbcrumb** [mdhiggins/sickbeard_mp4_automator#1128]
Recently updated to the latest code and getting the following errors.

`Manual processor started.
/usr/bin/python
64bit Python.
Enter path to file:
#: /mnt/local/Media/TV/tv
Processing file /mnt/local/Media/TV/tv/The Simpsons (1987)/Season 30/The Simpsons (1987) - S30E04 - Treehouse of Horror XXIX [ WEBDL-720p h264 EAC3 5.1]-CIELOS.mkv
Matched TV episode as The Simpsons (TMDB ID:456) S30E04
Proceed using guessed identification from filename?
# [y/n]: y
Processing The Simpsons Season 30 Episode 04 - Treehouse of Horror XXIX
Input Data
{
    "audio": [
        {
            "index": 1, 
            "language": "fre", 
            "default": true, 
            "channels": 6, 
            "codec": "eac3", 
            "type": "audio"
        }, 
        {
            "index": 2, 
            "language": "eng", 
            "default": false, 
            "channels": 6, 
            "codec": "eac3", 
            "type": "audio"
        }
    ], 
    "subtitle": [
        {
            "index": 3, 
            "language": "fre", 
            "forced": true, 
            "default": true, 
            "codec": "subrip", 
            "type": "subtitle"
        }, 
        {
            "index": 4, 
            "language": "fre", 
            "forced": false, 
            "default": false, 
            "codec": "subrip", 
            "type": "subtitle"
        }, 
        {
            "index": 5, 
            "language": "eng", 
            "forced": false, 
            "default": false, 
            "codec": "subrip", 
            "type": "subtitle"
        }
    ], 
    "format-fullname": "Matroska / WebM", 
    "video": {
        "pix_fmt": "yuv420p", 
        "index": 0, 
        "codec": "h264", 
        "type": "video", 
        "profile": "High"
    }, 
    "format": "matroska,webm"
}
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
Audio detected for stream 1 - eac3 fre 6 channel.
Audio detected for stream 2 - eac3 eng 6 channel.
Unable to determine iOS audio bitrate from source stream 2, defaulting to 256 per channel.
Traceback (most recent call last):
  File "./manual.py", line 404, in <module>
    main()
  File "./manual.py", line 370, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "./manual.py", line 268, in walkDir
    processFile(filepath, tagdata, converter, info=info, relativePath=relative)
  File "./manual.py", line 223, in processFile
    output = converter.process(inputfile, True)
  File "/opt/scripts/mp4_automatorNEW/mkvtomp4.py", line 221, in process
    options, preopts, postopts, ripsubopts = self.generateOptions(inputfile, info=info, original=original)
  File "/opt/scripts/mp4_automatorNEW/mkvtomp4.py", line 525, in generateOptions
    iOSbitrate = audio_channels * 256
UnboundLocalError: local variable 'audio_channels' referenced before assignment`

link to .ini
https://hatebin.com/ytthleqkbd

**Comment by mdhiggins** [comment]
Looks like this bug was introduced in 62cc5f4e27a82785e31bef8e86d55728473f9ef3

Should be fixed now, please try latest version

**Comment by sbcrumb** [comment]
So this bug is said to have been fixed 6 days ago. I git a git pull this morning. I see the lines in my file that are changed. Could it be something else?

**Comment by mdhiggins** [comment]
Now as in I fixed it this morning, but was introduced 16 days ago
Here is the fix
e9edd516705df968032be92808269dd352b856a4

**Comment by sbcrumb** [comment]
Sorry my bad Ok did a pull. New Error

`Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (eac3 (native) -> aac (native))
  Stream #0:2 -> #0:2 (eac3 (native) -> ac3 (native))
  Stream #0:5 -> #0:3 (subrip (srt) -> subrip (srt))
Press [q] to stop, [?] for help
[mp4 @ 0x5590d6dce6c0] Could not find tag for codec subrip in stream #3, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 -- 
[aac @ 0x5590d6dc8180] Qavg: -nan
[aac @ 0x5590d6dc8180] 1 frames left in the queue on closing
Conversion failed!

/home/plex/temp/The Simpsons (1987) - S30E04 - Treehouse of Horror XXIX [ WEBDL-720p h264 EAC3 5.1]-CIELOS.mp4 deleted.
Traceback (most recent call last):
  File "./manual.py", line 404, in <module>
    main()
  File "./manual.py", line 370, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "./manual.py", line 268, in walkDir
    processFile(filepath, tagdata, converter, info=info, relativePath=relative)
  File "./manual.py", line 223, in processFile
    output = converter.process(inputfile, True)
  File "/opt/scripts/mp4_automatorNEW/mkvtomp4.py", line 241, in process
    outputfile, inputfile = self.convert(inputfile, options, preopts, postopts, reportProgress)
  File "/opt/scripts/mp4_automatorNEW/mkvtomp4.py", line 1108, in convert
    raise Exception("FFMpegConvertError")
Exception: FFMpegConvertError`

**Comment by mdhiggins** [comment]
You're trying to use SRT for your subtitle codec - MP4 doesn't support SRT
Use mov_text

**Comment by sbcrumb** [comment]
well dont' I feel dumb I learned that once before but forgot. Thanks it is running now.

**Comment by mdhiggins** [comment]
It's all good. Part of the recent updates was expanding compatibility for other formats and removing hard-coded blocks, one of those blocks was probably filtering SRT before and saving your from yourself

Gonna close this for now since it seems to be fixed
