### ISSUE TITLE
AttributeError: 'MkvtoMp4' object has no attribute 'logs'

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1130]
Hello,

The script seems to now be trying to process non-video files like .nfo and aborting the converstion so it wont pass the files to sonarr/radarr and plex?

[index.log](https://pastebin.com/raw/vWgYyrXN)
[[MP4]](https://pastebin.com/raw/tTTbDUXB)

**Comment by mdhiggins** [comment]
So recently migrated from filtering out by extensions to trying to use FFPROBE output but apparently if the filename resembles an MP4 even if its just a text file or NFO file FFPROBE puts out some limited information and is causing this check to fail.

Just pushed an update that addresses this by verifying the info more strictly

Also logs was supposed to be log so that typo was fixed as well. Let me know

**Comment by Smalfinn** [comment]
Got a new error now: 
`AttributeError: 'MkvtoMp4' object has no attribute 'output_dir'`

[SABnzbd log](https://pastebin.com/raw/nq5RachJ)
[[SABNZBD]](https://pastebin.com/raw/dNJYW9pf)

**Comment by mdhiggins** [comment]
Good catch. The post download scripts were still referring to the now deprecated output_dir reference in MkvToMp4 class which is now handled by ReadSettings
Just pushed an update to fix this
Appreciate the feedback. I was worried I'd miss something like this when migrating the code base over and thought I had caught all the outliers but missed this one.

**Comment by Smalfinn** [comment]
No worries; love the script so happy to help.
New error from sonarr this time
`converter.ConverterError: Can't get information about source file`

[Sonarr log](https://pastebin.com/raw/HxeahwKP)

**Comment by mdhiggins** [comment]
Do you have the full log for that conversion with some of the preceding information? This error is a tougher one not sure why its being called

**Comment by mdhiggins** [comment]
Actually I think I know what's happening. If this is a situation where the original file is being renamed it wasn't keeping track of that updated source path when passing to the converter
This should be fixed now try updating and see if its better

**Comment by mdhiggins** [comment]
Is this by chance a situation where the inputfile and outputfile had the same extension? (MKV to MKV or MP4 to MP4)

**Comment by Smalfinn** [comment]
No, MKV to MP4

**Comment by Smalfinn** [comment]
I think it's "process-same-extensions = True" causing the script to re-transcode the file after moving it

**Comment by mdhiggins** [comment]
Ah yeah that option will do that. I would turn that off if you’re converting from SAB or deluge because it will cause the conversion to just run again. 
That being said the change I just added should fix your crash so let me know.

**Comment by Smalfinn** [comment]
Ah okay, I'll change that to False.

I updated, changed process-same-extensions to false, and seems to run the script and eventually plex refreshed and its there thank you!

Only thing is when its moved by sonarr the script runs tagging again slowing everything down.
Could final tagging be done before sonarr moves the file?

**Comment by mdhiggins** [comment]
Could you try it one more time with the process same extension set to true? Just for testing purposes to make sure that error was addressed (having it false will avoid the error and not test the fix that was just submitted)

Tagging should be relatively fast. Unfortunately sonarr does it’s post processing after moving so you can’t do it before and the data needed to do the tagging isn’t available from the downloaders like SAB or Deluge so it can’t be done there. 

I have automatic refresh on plex turned off and have sonarr / Radarr trigger the plex refresh which is done after the post processing is complete

The script can also refresh plex on its own as an alternative too.

**Comment by Smalfinn** [comment]
Sorry, of course.

Went through without a hitch; downloaded, converted, moved, converted, tagged then added to plex.
[index.log](https://pastebin.com/raw/gx5YWFvv)

That's SABnzbd all fixed but now deluge is just creating the -convert folder and nothing else?
`2020-02-14 16:02:11 - DelugePostProcess - INFO - Deluge post processing started.`
`2020-02-14 16:02:15 - DelugePostProcess - INFO - Successfully connected to Deluge`

**Comment by mdhiggins** [comment]
The files aren't handed back to Sonarr? The folder remaining afterward does occasionally happen

Is there any more log information?

Could you maybe set your logging level to debug in logging.ini to get more information if there isn't more available

Change the fileHandler below:
```
[handler_fileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=simpleFormatter
args=('%(logfilename)s', 10000, 1)
```

**Comment by mdhiggins** [comment]
I updated delugePostProcess to include some catches to hopefully at least get the error logged so we can sort out if something is happened, if you want to update and try again and post back if its more helpful

**Comment by Smalfinn** [comment]
Ran it again with the updated delugePostProcess:
[index.log](https://pastebin.com/raw/iNFZ86WN)

Sorry didn't see the update to debug level; I'll do this next

**Comment by Smalfinn** [comment]
level=DEBUG
[index.log](https://pastebin.com/raw/RDe5CLNq)

**Comment by mdhiggins** [comment]
Excellent very helpful I’ll have a fix up shortly

**Comment by mdhiggins** [comment]
Alright fix uploaded, give it a shot and see if deluge is working again

**Comment by mdhiggins** [comment]
And I appreciate your feedback on this, I don't have a good deluge test environment set up at the moment so your help has been very valuable

**Comment by Smalfinn** [comment]
Looking good!
Working fine now: [index.log](https://pastebin.com/raw/5kKFgNtK)
Thanks for all you quick responses today

**Comment by mdhiggins** [comment]
Thanks for the feedback. Glad it’s all working now.
