### ISSUE TITLE
NzbGet postprocess

### ISSUE THREAD

**Issue by j-burton** [mdhiggins/sickbeard_mp4_automator#1131]
Hi,
I've done a fresh install of the OS (Synology) using python 3.5. the manual.py works fine, however in nzbget, i get the following:

INFO | Sat Feb 15 2020 00:28:19 | Collection Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre removed from history
-- | -- | --
INFO | Sat Feb 15 2020 00:28:19 | Deleting file /volume1/downloads/nzb/Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre.nzb.queued
INFO | Sat Feb 15 2020 00:28:19 | Deleting Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre from history
INFO | Sat Feb 15 2020 00:28:11 | Collection Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre added to history
ERROR | Sat Feb 15 2020 00:28:11 | Post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre failed (terminated with unknown status)
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: KeyError: 'formatters'
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: raise KeyError(key)
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/configparser.py", line 956, in __getitem__
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: flist = cp["formatters"]["keys"]
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 109, in _create_formatters
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: formatters = _create_formatters(cp)
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 76, in fileConfig
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: fileConfig(configPath, defaults={'logfilename': logPath})
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: File "/volume1/@appstore/sickbeard_mp4_automator/log.py", line 19, in getLogger
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: log = getLogger("NZBGetPostProcess")
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: File "/volume1/@appstore/nzbget/share/nzbget/scripts/NZBGetPostProcess.py", line 83, in <module>
INFO | Sat Feb 15 2020 00:28:11 | NZBGetPostProcess: Traceback (most recent call last):
INFO | Sat Feb 15 2020 00:28:11 | Executing post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre

Any help would be greatly appreciated...

**Comment by mdhiggins** [comment]
Found the issue. Should be fixed in the latest update. Please update and try again. (log.py needs update as well as nzbgetpostprocess.py)

**Comment by mdhiggins** [comment]
c5722f834b3d4b4744ac0049cd0922741edbb623

**Comment by j-burton** [comment]
Seems to have the same problem unfortunately


ERROR | Sat Feb 15 2020 13:46:08 | Post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre failed (terminated with unknown status)
-- | -- | --
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: KeyError: 'formatters'
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: raise KeyError(key)
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/configparser.py", line 956, in __getitem__
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: flist = cp["formatters"]["keys"]
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 109, in _create_formatters
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: formatters = _create_formatters(cp)
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 76, in fileConfig
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: fileConfig(configPath, defaults={'logfilename': logPath})
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: File "/volume1/@appstore/sickbeard_mp4_automator/log.py", line 19, in getLogger
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: log = getLogger("NZBGetPostProcess")
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: File "/volume1/@appstore/nzbget/share/nzbget/scripts/NZBGetPostProcess.py", line 83, in <module>
INFO | Sat Feb 15 2020 13:46:08 | NZBGetPostProcess: Traceback (most recent call last):
INFO | Sat Feb 15 2020 13:46:04 | Executing post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre

**Comment by j-burton** [comment]
Forgot to move nzbgetprostprocess..... but same result



ERROR | Sat Feb 15 2020 14:17:25 | Post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre failed (terminated with unknown status)
-- | -- | --
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: KeyError: 'formatters'
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: raise KeyError(key)
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/configparser.py", line 956, in __getitem__
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: flist = cp["formatters"]["keys"]
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 109, in _create_formatters
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: formatters = _create_formatters(cp)
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 76, in fileConfig
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: fileConfig(configPath, defaults={'logfilename': logPath})
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: File "/volume1/@appstore/sickbeard_mp4_automator/log.py", line 19, in getLogger
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: log = getLogger("NZBGetPostProcess", MP4folder)
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: File "/volume1/@appstore/nzbget/share/nzbget/scripts/NZBGetPostProcess.py", line 83, in <module>
INFO | Sat Feb 15 2020 14:17:25 | NZBGetPostProcess: Traceback (most recent call last):
INFO | Sat Feb 15 2020 14:17:22 | Executing post-process-script NZBGetPostProcess.py for Chopper.2000.iNTERNAL.DVDRip.x264-PFa-Pre

**Comment by mdhiggins** [comment]
Just to clarify because I’ve made this mistake a few times. Did you remember to update NZBGetPostProcess.py separately? Because it resides in its own folder outside the script’s main folder that can be overlooked. You’ll also need to shutdown NZBGet before hand and clear out any .pyc files before restarting it

**Comment by j-burton** [comment]
The first reply was without updating NZBGetPostProcess.py but the second was after copying the new file. Where are the pyc files?

**Comment by mdhiggins** [comment]
Nah don’t worry about that I didn’t see the first reply. The update worked I can see the changes. Can you post a pic of your NZBGetPostProcees settings?

**Comment by mdhiggins** [comment]
Actually wait, I just realized I missed something in that last update, just pushed another update see if that fixes things

**Comment by j-burton** [comment]
While im doing that, i wasnt able to make a symlink of manual.py... any thoughts? (actually i made the symlink, but it didnt work)

**Comment by j-burton** [comment]
Conversion worked perfectly! thanks again.
Two side issues; the symlink seemed to not use the original paths, and the filename wasnt renamed, is that a radarr, nzbget, or autoprocess issue?

**Comment by mdhiggins** [comment]
Not sure about the symlink, why are you trying to symlink manual.py?

And NZBGet isn't supposed to rename, that's handled by Radarr/Sonarr/CP/SB/SR after the file gets passed back. NZBGetPostProcess will do the conversion and then send a notice to Radarr/Sonarr/CP/SB/SR to trigger them to scan the file and then initiate their renaming/moving process.

**Comment by j-burton** [comment]
manual.py wasnt in my path file, and the only other way i know is to have it in there, amongst a few other programs, so what i thought was a better solution was to make one directory in my patt, then add a bunch of symlinks in it.

The renaming issue i solved in radarr

**Comment by mdhiggins** [comment]
Gotcha so you just want to be able to call manual.py from the console without specifying the directory?

I would think symlink would work fine for that, was it giving you an error of some kind?

Alternatively you could add your script folder to your PATH variable if that didn't work

**Comment by j-burton** [comment]
I originally had it in the path, but it seemed messy because i had to add a bunch of other folders there.
this is what i get from the symlink


Traceback (most recent call last):
  File "/volume1/@appstore/exec/manual.py", line 26, in <module>
    log = getLogger("MANUAL")
  File "/volume1/@appstore/sickbeard_mp4_automator/log.py", line 19, in getLogger
    fileConfig(configPath, defaults={'logfilename': logPath})
  File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/volume1/@appstore/python3/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by mdhiggins** [comment]
Ah I see. I think I can solve that actually it has to do with the way it looks for the logging.ini file, if I resolve to os.path.realpath in the right locations I should be able to fix that
Just pushed an update, see if that fixes symlink

Also, with that update I had to rework some of the changes I made to fix NZBGetPostProcess for your original issue so if you could make sure that's still working that would be appreciated

**Comment by j-burton** [comment]
After a git pull, this was the result

Traceback (most recent call last):
  File "/volume1/@appstore/exec/manual.py", line 26, in <module>
    log = getLogger("MANUAL")
  File "/volume1/@appstore/sickbeard_mp4_automator/log.py", line 29, in getLogger
    fileConfig(configPath, defaults={'logfilename': logPath})
  File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/volume1/@appstore/python3/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/volume1/@appstore/python3/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by mdhiggins** [comment]
Alright I spun up a linux docker container and did some actual testing since testing on windows creates other issues and think I've got it all working now. My test making a symlink works; give it one more update and try again and please make sure NZBGet still works too but from my end I think I got it solved
