### ISSUE TITLE
Convert only if eac3 audio is detected.

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#1134]
I sometimes get mkv and mp4 files but I want mp4 automator to only convert if an eac3 audio stream is detected and leave untouched if not detected. The problem is the output extension. If I set it to mp4 it will repack everything into mp4. If I set it to mkv I sometimes have playback issues. 

Is there any way to get it to leave untouched if no eac3 stream is detected in either an mp4 or mkv file extension? Thanks.

[MP4]
ffmpeg = /home/server/.config/automator/ffmpeg
ffprobe = /home/server/.config/automator/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mkv	
output_format = mp4
delete_original = True
relocate_moov = False
video-codec = h264,x264,h265,hevc,x265
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3,dts,dtshd,aac
ignore-truehd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
bad-internal-subtitle-sources = pgssub, hdmv_pgs_subtitle, s_hdmv/pgs, dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
bad-external-subtitle-sources = dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
fullpathguess = True
convert-mp4 = False
force-convert = False
tagfile = False
tag-language = 
download-artwork = False
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
temp_extension = 
preopts =

**Comment by mdhiggins** [comment]
I don't believe there currently exists a way to achieve what you want with any specific set of options

You could potentially have 2 autoProcess.ini files one for mkv and one for mp4 and run it through a small script that divides up the extensions up to each respective autoProcess.ini file

If the script doesn't detect any codecs that needs transcoding and you don't have force-convert turned on then it wouldn't do anything to those files

**Comment by Deihmos** [comment]
Interesting but unfortunately I have no scripting experience and wouldn’t know what to do. Thanks.

**Comment by mdhiggins** [comment]
Quick sample (haven't tested but should get you started). It's a wrapped for manual.py that changes the config file depending on the extension

```
import os
import sys

path = sys.argv[1]
filename, file_extension = os.path.splitext(path)
path_to_manual = "python C:\\sickbeard_mp4_automator\\manual.py"
if file_extension.lower() in [".mkv"]:
    os.system("%s --config %s " % (path_to_manual, "C:\\sickbeard_mp4_automator\\autoProcessMKV.ini"))
elif file_extension.lower() in ["mp4", "m4v"]:
    os.system("%s --config %s " % (path_to_manual, "C:\\sickbeard_mp4_automator\\autoProcessMP4.ini"))
```
