### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by player666au** [mdhiggins/sickbeard_mp4_automator#1135]
Hi, in the latest docker version gives an FFmpeg  'height not divisible by 2' error when 'video-max-width' is set and the video resizes to an odd height value.

log:
[sma-error.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4212089/sma-error.txt)

**Comment by mdhiggins** [comment]
Just put out an update to address this and rebuilt the docker containers

**Comment by player666au** [comment]
Works great.
Thank you for all your time and effort.
