### ISSUE TITLE
NzbgetPostProcess Fails

### ISSUE THREAD

**Issue by sbcrumb** [mdhiggins/sickbeard_mp4_automator#1138]
`Mon Feb 17 16:16:50 2020        INFO    Executing post-process-script mp4_automator/NZBGetPostProcess.py for 90.Day.Fiance.S07E14.Tell.All.Part.1.1080p.WEB-DL AAC2 0 x264
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess: Traceback (most recent call last):
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/scripts/mp4_automator/NZBGetPostProcess.py", line 73, in <module>
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess:     from autoprocess import autoProcessMovie, autoProcessTV, autoProcessTVSR, sonarr, radarr
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/scripts/mp4_automator/autoprocess/autoProcessMovie.py", line 11, in <module>
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess:     import requests
Mon Feb 17 16:16:50 2020        INFO    mp4_automator/NZBGetPostProcess: ModuleNotFoundError: No module named 'requests'
Mon Feb 17 16:16:50 2020        ERROR   mp4_automator/NZBGetPostProcess: Wrong path to sickbeard_mp4_automator: /scripts/mp4_automator/
Mon Feb 17 16:16:50 2020        ERROR   mp4_automator/NZBGetPostProcess: None`

**Comment by mdhiggins** [comment]
Seems like you need to install requests

**Comment by sbcrumb** [comment]
I thought the same but
`root@nzbget:/# pip install requests
The directory '/config/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/config/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests)
root@nzbget:/# `

**Comment by mdhiggins** [comment]
Seems like perhaps NZBGet is using a different version of python, perhaps you have more than one python environment?

**Comment by sbcrumb** [comment]
Yo might be right looks like I have 3 and 2.. 2 is the preferred yes?

**Comment by sbcrumb** [comment]
Seems the docker image I am using is installing python3 for some reason.. Need to chase that down.

**Comment by mdhiggins** [comment]
3 is preferred these days but you just need to have the dependencies installed under the right one

**Comment by sbcrumb** [comment]
ok got further now I have a logging error
`Mon Feb 17 19:57:29 2020        INFO    Executing post-process-script mp4_automator/NZBGetPostProcess.py for Murdoch.Mysteries.S13E16.720p.WEBRip.x264-CookieMonster
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess: Traceback (most recent call last):
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/scripts/mp4_automator/NZBGetPostProcess.py", line 83, in <module>
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/scripts/mp4_automator/log.py", line 28, in getLogger
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     handlers = _install_handlers(cp, formatters)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/config.py", line 148, in _install_handlers
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     h = klass(*args)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     StreamHandler.__init__(self, self._open())
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:   File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess:     return open(self.baseFilename, self.mode, encoding=self.encoding)
Mon Feb 17 19:57:30 2020        INFO    mp4_automator/NZBGetPostProcess: PermissionError: [Errno 13] Permission denied: '/var/log/sickbeard_mp4_automator/index.log'`

**Comment by mdhiggins** [comment]
```
PermissionError: [Errno 13] Permission denied: '/var/log/sickbeard_mp4_automator/index.log'
```
Looks like you need to make sure the log file has write permissions for whatever user NZBGet is running under

**Comment by sbcrumb** [comment]
thanks cause it is a docker image and I can't specify the log location in the newer version I had to symlink it to some place that user had access to..
Think I got it all working now. Love docker image updates lol.

**Comment by mdhiggins** [comment]
Gonna close this for now
