### ISSUE TITLE
manual.py -a error: AttributeError: 'module' object has no attribute 'guessit'

### ISSUE THREAD

**Issue by petrichor8** [mdhiggins/sickbeard_mp4_automator#1139]
Here is the output if I attempt to run the manual.py using the -a flag on a movie.

`Manual processor started.`
`/usr/bin/python`
`Python 64-bit 2.7.16 (default, Oct  9 2019, 14:10:52)`
`GCC 4.8.4].`
`Guessit version: 1.0.3.`
`Traceback (most recent call last):`
`  File "{mypath}/sickbeard_mp4_automator/manual.py", line 395, in <module>`
`    main()`
`  File "{mypath}/sickbeard_mp4_automator/manual.py", line 386, in main`
`    tagdata = getinfo(path, silent=silent, tvdbid=tvdbid)`
`  File "{mypath}/sickbeard_mp4_automator/manual.py", line 91, in getinfo`
`    tagdata = guessInfo(fileName, tvdbid)`
`  File "{mypath}/sickbeard_mp4_automator/manual.py", line 129, in guessInfo`
`    guess = guessit.guessit(fileName)`
`AttributeError: 'module' object has no attribute 'guessit'`

Environment:
 Linux Mint 17.2 Rafaela x86_64 (ubuntu 14.04 trusty)

`$>python -V`
`Python 2.7.16`

`$>/usr/bin/env python -V`
`Python 2.7.16`

`$>pip --version`
`pip 20.0.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7) `

`$>guessit --version`
`+-------------------------------------------------------+`
`+                   GuessIt 1.0.3                       +`
`+-------------------------------------------------------+`
`|      Please report any bug or feature request at      |`
`|       https://github.com/wackou/guessit/issues.       |`
`+-------------------------------------------------------+`

I tried upgrading to guessit 2, but then subliminal wouldn't run/errored out, so went back to guessit 1.0.3

If I use manual.py with the -imdb flag, it runs ok, so it's just in the usage of guessit, it seems.  Any ideas as to what the fix might be?

**Comment by mdhiggins** [comment]
This is fixed, you need to use latest version of all of these things, guess it and subliminal

See the readme, all the packages supported should all be the latest versions (this was all updated a few weeks ago)

**Comment by petrichor8** [comment]
Thanks, that's the direction I needed to get this working again!

For anyone else who finds this, upgrading subliminal to 2.0 (which upgraded guessit to 3.1.0) fixed the module & dependency errors.

`$>pip install subliminal==2.0.0`

`$>subliminal --version`
`subliminal, version 2.0.0`

note: `$>guessit --version` is still displaying 1.0.3, but when used or in showing `pip freeze`, it's displaying as 3.1.0, and working.
