### ISSUE TITLE
subs error

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sickbeard_mp4_automator#1140]
Hi,

I just got the following error processing a file:

  | Component | Message | Time
-- | -- | -- | --
  | python3 | TypeError: argument of type 'NoneType' is not iterable | 12:48pm
  | python3 | valid_external_subs.sort(key=lambda x: swl.index(x.subtitle[0].metadata['language']) if x.subtitle[0].metadata['language'] in swl else 999) | 12:48pm
  | python3 | File "/usr/local/sma/mkvtomp4.py", line 798, in <lambda> | 12:48pm
  | python3 | valid_external_subs.sort(key=lambda x: swl.index(x.subtitle[0].metadata['language']) if x.subtitle[0].metadata['language'] in swl else 999) | 12:48pm
  | python3 | File "/usr/local/sma/mkvtomp4.py", line 798, in scanForExternalSubs | 12:48pm
  | python3 | valid_external_subs = self.scanForExternalSubs(inputfile, swl) | 12:48pm
  | python3 | File "/usr/local/sma/mkvtomp4.py", line 544, in generateOptions | 12:48pm
  | python3 | options, preopts, postopts, ripsubopts = self.generateOptions(inputfile, info=info, original=original) | 12:48pm
  | python3 | File "/usr/local/sma/mkvtomp4.py", line 44, in process | 12:48pm
  | python3 | output = converter.process(inputfile, original=original, info=info) | 12:48pm
  | python3 | File "/usr/local/sma/postSonarr.py", line 41, in <module> | 12:48pm
  | python3 | Traceback (most recent call last): | 12:48pm

Let me know if you need something else.

**Comment by mdhiggins** [comment]
c82e80ecbabb0210bb82df91710ff8f10859af87

Should be fixed with this update

Curious, did you have any subtitle languages specified when this error occurred?

**Comment by powerdude** [comment]
no, i don't believe i did but can you tell me where i should check?

**Comment by mdhiggins** [comment]
You can just post your autoProcess.ini file if you want
But try the update and see if that resolves your issue

**Comment by powerdude** [comment]
I'm using docker, can i just update the container or should i edit the file myself.  I've attached my autoProcess.ini file and it seems like some random stuff was added to it.  can i delete the "sonarr_*" keys

[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4221819/autoProcess.ini.txt)

**Comment by mdhiggins** [comment]
I'll update my docker containers but that'll take some time so you're free to just change the file or open the docker container and do `git pull origin master` from inside the directory

**Comment by mdhiggins** [comment]
And yeah you can remove that stuff from your environment variables, there was a bug for like a day that accidentally added those variables that has since been fixed so you can remove anything under [DEFAULT]

Pushed the updates to docker hub now, give it like an hour to finish building and refresh and then update

**Comment by powerdude** [comment]
i did the `git pull origin master` and things seem to be ok.  

Thanks!!

**Comment by mdhiggins** [comment]
Sweet, I'll close this out and update the containers
