### ISSUE TITLE
Audio Channel Bitrate

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1141]
I saw that the standard rate of the script is 256k, is it possible to leave it with 128k of audio bitrate?

**Comment by mdhiggins** [comment]
`audio-channel-bitrate` = set the bitrate for each audio channel. Default is 256. Setting this value to 0 will attempt to mirror the bitrate of the audio source, but this can be unreliable as bitrates vary between different codecs

Does that option not work?

**Comment by andrerxavier** [comment]
Even setting audio-channel-bitrate = 128, at the end of the process it is 256.

**Comment by mdhiggins** [comment]
It’s channel bitrate though so if your audio is stereo then it’s 128*2. 

If you want 128 for stereo set it to 64

**Comment by andrerxavier** [comment]
I will take the test now and thank you for your help and work. Congratulations
