### ISSUE TITLE
sonarr-sma/radarr-sma log location

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1142]
The docker containers no longer seem to be writing SMA log info to /var/log/sickbeard_mp4_automator/index.log.  Not sure if there is an issue on my end or if the logging was changed recently.  The last log entry I have is on 2-11/2020.

Can anyone confirm the log location is correct?

**Comment by mdhiggins** [comment]
There was a bug with logging permissions that should be fixed as of last night. Just update your containers

**Comment by samcro1967** [comment]
It is working now after updating the containers.
