### ISSUE TITLE
Is there some way to log manual tagging?

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1144]
I have reason to suspect that manual tagging might be crashing and causing my Mac to go down in flames.  The problem has been happening for a few days, and I'm trying to confirm if it's the tagging that's crashing the computer or something else.

I don't have it running on an automated basis because I'm not running an automated download process.

**Comment by mdhiggins** [comment]
Everything is logged. What errors are you getting? Going down in flames isn’t very specific and tagging is wrapped in a try/catch so it shouldn’t cause any failures. 

Tagging has been working fine on my end.

**Comment by Geordon** [comment]
When I mean that the computer is going down in flames, I mean that I will
start the manual tagging on a directory that has a bunch of files that need
conversion and tagging and I walk away.  When I come back, my computer is
completely shut down. I have not enabled any sort of automatic shutdown or
power off functions.

Where would I look to find the log file?
—
Geordon VanTassle

On February 22, 2020 at 6:00:42 PM, Michael Higgins (
notifications@github.com) wrote:

Everything is logged. What errors are you getting? Going down in flames
isn’t very specific and tagging is wrapped in a try/catch so it shouldn’t
cause any failures.

Tagging has been working fine on my end.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1144?email_source=notifications&email_token=ABK7RCCIJEA3RAQ2JFMZ5SDREG4CTA5CNFSM4KZVTSR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMVNSCI#issuecomment-590010633>,
or unsubscribe

**Comment by mdhiggins** [comment]
I would say that’s reeeally unlikely to have anything to do with the script

If you’re doing more than tagging and FFMPEG is heating up your cpu on a laptop it might be thermal shutdown 

On macOS logs should be in /var/log/sickbeard_mp4_automator/index.log but no crashes in python should cause the OS to do anything

**Comment by mdhiggins** [comment]
Closing this for now until there's some evidence that the script had anything to do with your computer turning off, happy to revisit if you find anything
