### ISSUE TITLE
manual.py starts but does nothing with the file

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1145]
Hello,

Running manual.py starts, gathers all the info about the file but then does nothing with it?

[index.log](https://pastebin.com/raw/2T3sRc8L)
[[MP4]](https://pastebin.com/raw/uGkm0A3m)

**Comment by mdhiggins** [comment]
Doesn’t look like anything is happening. What command are you executing? That log isn’t helpful. Are you processing a file? A directory? Does it do this for every file? If you run without any command line options does it do anything?

**Comment by Smalfinn** [comment]
Apologies, I'm an idiot
I had a .bat script running manual.py with -oo
