### ISSUE TITLE
mkv files not being tagged

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1146]
Hello,

mkv files aren't being tagged with metadata; is this intentional?

[Original media info](https://pastebin.com/raw/fX3WBX5F)
[[MP4]](https://pastebin.com/raw/TZYnkBJx)
[index.log](https://pastebin.com/raw/G472PvWb)
[Output media info](https://pastebin.com/raw/hFSyPExf)

**Comment by mdhiggins** [comment]
Tagging is MP4 only

**Comment by Smalfinn** [comment]
Is tagging MP4 only because of limitations of the mkv container or because the script is setup with only MP4 in mind?

**Comment by mdhiggins** [comment]
It's a little of both. The MKV container does not support as much metadata parameters or atoms as the MP4 container and the library used to do the tagging (mutagen) does not provide any MKV support. 

As far as I know there is no python library that provides metadata writing for MKVs
