### ISSUE TITLE
qBittorrentPostProcess.py - import log seems invalid

### ISSUE THREAD

**Issue by jameseck** [mdhiggins/sickbeard_mp4_automator#1147]
The qBittorrentPostProcess.py has:
```
from log import logger
```
which results in the error:
```
ImportError: cannot import name 'logger' from 'log' (/sba/log.py)
```

I'm using the code from the master branch (freshly pulled).  Is this a bug?  It looks like the other processing scripts use getLogger from log.py.  Maybe an oversight on qBittorrentPostProcess.py?

**Comment by mdhiggins** [comment]
Yeah, this was an oversight

Should be fixed now

6ac60250c867600724cb522286651c18170e4fd5

**Comment by mdhiggins** [comment]
Reopen if you encounter any issues with the fix
