### ISSUE TITLE
Transcode by torrent client

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1148]
Does the sickbeard_mp4_automator script also start transcoding the content, downloaded directly by qBittorrent or Deluge?

**Comment by mdhiggins** [comment]
It can but not until downloads are complete but the delugePostProcess and qBitTorrentPostProcess include everything needed for conversion. They don’t do tagging due to lack of metadata. This should be outlined in the readme.
