### ISSUE TITLE
Kubernetes compatibility

### ISSUE THREAD

**Issue by jameseck** [mdhiggins/sickbeard_mp4_automator#1149]
Hi,
I'm currently building out my platform using Kubernetes.
I have Sonarr, Radarr, Nzbget, qBittorrent etc configured to run as k8s pods and am trying to integrate sickbeard_mp4_automator.

I've written a wrapper program that will spin up a k8s job for each file to be converted/processed.  This uses a docker image that is still a work in progress (https://github.com/jameseck/docker-sba).

The problem I'm facing is the way that sickbeard_mp4_automator handles the autoProcess.ini file.

I want to use the same autoProcess.ini file for all integrations so I want that to be mounted from a shared directory (I'd prefer to be able to mount it from a k8s configMap but since sickbeard_mp4_automator seems to want to write to this file that doesn't seem possible as configMap mounts are read-only).

I have a shared directory called downloads which is mounted in all the above pods and I'd like to keep the autoProcess.ini in this directory.

If I use manual.py I can specify where the autoProcess.ini file is, but using the qbittorrentpostprocess.py it only looks for the autoProcess.ini in the directory the py script lives.

I'd like to be able to specify an environment variable (something like AUTOPROCESS_INI=/path/to/autoProcess.ini) that could be used by whatever python scripts need to find it.
I know I could put the sickbeard_mp4_automator code in the same shared directory but I'd prefer to separate the code from the config.

So out of all this I think there are two points for discussion:
1. Can we have the ability to specify where the autoProcess.ini file is found?
2. Can we allow the autoProcess.ini file to be read-only?

Thanks
J

**Comment by mdhiggins** [comment]
Config file being read only shouldn't be a problem and I've tested this scenario. This was fixed maybe a month ago. You'll get can error message that writing failed but the script should proceed without issues (it will only attempt to write if you're missing options that have been added in recent patches so updating your autoProcess.ini should eliminate this error too)

As for specifying where autoProcess.ini is located, I pushed an update just now to override the default path using an environment variable named `SMACONFIG`

Set this to the full path to an ini file, not just a directory, and the file needs to exist ahead of time for the override to work but should override in all scenarios

94c26635a8aa6481d00e34473450cc0b8d32ece9

Let me know if this works for you and feel free to close the issue. I'll update the readme once you confirm.

**Comment by mdhiggins** [comment]
Made some subtle tweaks
324cbc716b43b954d5ca92ea03c8d4bc9aca07e0

Relaxed some of the above restrictions, test this version instead

**Comment by jameseck** [comment]
Thanks in advance for indulging my use case so quickly!
I'm seeing an error when I try using the latest code:

```
sba/mkvtomp4.py:381: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.settings.abitrate is 0:
/sba/mkvtomp4.py:435: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.settings.abitrate is 0:
/sba/mkvtomp4.py:813: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(lang) is 2:
2020-02-28 09:42:02 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-02-28 09:42:03 - qBittorrentPostProcess - INFO - Performing conversion
Traceback (most recent call last):
  File "/sba/qBittorrentPostProcess.py", line 119, in <module>
    path = converter.output_dir
AttributeError: 'MkvtoMp4' object has no attribute 'output_dir'
```

The SyntaxWarning errors I've been seeing for quite a while and ignoring as they don't seem to affect anything, but the AttributeError is new.
I thought maybe my autoProcess.ini was missing something and because of the read-only mount it was failing to add missing entries, but I get the same error when the autoProcess.ini is read-write.

**Comment by mdhiggins** [comment]
Nah this was a bug that was missed from an update a month ago (qBT doesn't see a lot of use I don't think)
Just pushed 2 updates, one to address the error you're seeing an another to fix that syntax warning
6ce4a95940d2f97372e4a351e8fdc2170a6c078b
709f6db40827eb3a37eac9801dd2ffb5bfccc79f

Let me know if that fixes things

**Comment by jameseck** [comment]
Thanks dude.  Everything is working great now with the env variable.
I've been using Deluge for years but thought I'd give qbt a try.

One pesky SyntaxWarning remains.
```
/sba/mkvtomp4.py:815: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(lang) is 2:
```

**Comment by mdhiggins** [comment]
That last syntax warning should be fixed now
ec025c2835e04e7a552020dcbee190fa60497059

Thanks! Gonna close this

**Comment by mdhiggins** [comment]
Just a quick note, I modified the environment variables to be uniform and the config variable was changed to `SMA_CONFIG` instead of `SMACONFIG`
