### ISSUE TITLE
Filters not applied on copy

### ISSUE THREAD

**Issue by stevemk14ebr** [mdhiggins/sickbeard_mp4_automator#1150]
When using the script in automatic mode ffmpeg is sometmes invoked with the command line options to copy the audio or video sources. Unfortunately the copy option bypasses the filter application pipeline causing filters to _silently_ not be applied. I suggest changing the default behavior to always re-encode if and only if one or more audio/video filters are applied. Ex autprocess.ini:

```
# will not always be applied.
audio-filter = dynaudnorm
```

The correct command line arguments to apply this filter regardless of the source encoding would be:
`ffmpeg -i <file.mp4> -af "dynaudnorm" <out.mp4>`

**Comment by mdhiggins** [comment]
Added this feature
df0d597b2e55bd8807ffec5d58988fa0a6777f73
