### ISSUE TITLE
How to exclude input extensions (e.g., AVI) from being converted and how to download hearing-impaired subs now?

### ISSUE THREAD

**Issue by strafer** [mdhiggins/sickbeard_mp4_automator#1151]
With the recent changes, I can no longer exclude certain extensions such as AVI or MOV from being auto-converted by mp4_automator. I used to be able to edit the extensions.py file but no longer.

What is the correct method now of including/excluding video codec extensions?

Also, the autoProcess.ini no longer has an option for downloading hearing-impaired subs. How do I enable that?

**Comment by mdhiggins** [comment]
I guess by increasing the support of the script to dynamically handle more formats this specific trick was lost

2289b9b4e8933821f1de701081a1238d855dcd7b

Added an option to autoProcess.ini to ignore certain extensions `ignored-extensions`

**Comment by strafer** [comment]
Thanks for adding that option. Much appreciated. I don't bother transcoding AVIs because it pins the CPU on my old Mac Mini media server at 100% for too long.

Also, the autoProcess.ini no longer has an option for downloading hearing-impaired subs. How do I enable that?

**Comment by mdhiggins** [comment]
The hearing impaired option hasn't been touched and should still exist

**Comment by strafer** [comment]
> The hearing impaired option hasn't been touched and should still exist

![autoprocess_diff](https://user-images.githubusercontent.com/4935512/75642575-d6aa8700-5bf0-11ea-923e-1606c9697729.png)

The left is the old autoprocess.ini from January and the right is the newest.

**Comment by mdhiggins** [comment]
Option is still there, check your config file, running any aspect of the script should add the option if its missing too
All the code for reading the option is still in place and I even tried deleting the option from my config and then opening manual.py and the option was recreated

**Comment by strafer** [comment]
Okay, you're right. It did update once I ran it. I didn't realize that the script would or could make additions to the .ini file. 

Thanks.

**Comment by mdhiggins** [comment]
Yeah it never deletes things but if new features are added or options are removed by the user that it expects it restores them to the default value

I think what happened here was that it was missing from the sample file, it has now been added
