### ISSUE TITLE
Manual progress counter now does new line?

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1152]
I'm not sure what changed, but after a reboot, now manual tagging is printing each percentage of completion multiple times with a newline.

I've tried this with a completely empty .bash_profile and the same thing happens.  I'm kind of guessing that it's something local, but I sure would appreciate some suggesions on what to look into in order to get it back to working as expected.

`| => tag -i Tagging/Nikita/ -a
Manual processor started.
Python 64-bit 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 16:07:15)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)].
Guessit version: 3.1.0.
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Loading config file /Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/autoProcess.ini.
Processing file Tagging/Nikita/Nikita - S02e07 - Clawback - GR.mkv
Matched TV episode as Nikita (TMDB ID: 32868) S02E07
Processing Nikita Season 02 Episode 07 - Clawback
Input Data
{
    "subtitle": [],
    "format-fullname": "Matroska / WebM",
    "format": "matroska,webm",
    "video": {
        "pix_fmt": "yuv420p",
        "index": 0,
        "codec": "hevc",
        "type": "video",
        "profile": "Main"
    },
    "attachment": [],
    "audio": [
        {
            "index": 1,
            "language": "eng",
            "default": true,
            "channels": 2,
            "codec": "aac",
            "type": "audio"
        }
    ]
}
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p.
Profile: Main.
Reading audio streams.
Audio detected for stream 1 - aac eng 2 channel.
Unable to determine audio bitrate from source stream 1, defaulting to 256 per channel.
Creating copy audio stream from source stream 1.
Default audio stream set to eng copy 2 channel stream [prefer-more-channels: True].
Reading subtitle streams.
Scanned for external subtitles and found 0 results in your approved languages.
Output Data
{
    "subtitle": [],
    "format": "mp4",
    "source": [
        "Tagging/Nikita/Nikita - S02e07 - Clawback - GR.mkv"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "bufsize": null,
        "pix_fmt": null,
        "field_order": "unknown",
        "level": null,
        "bitrate": null,
        "width": null,
        "codec": "h264",
        "crf": null,
        "debug": "base",
        "maxrate": null
    },
    "attachment": [],
    "audio": [
        {
            "channels": 2,
            "map": 1,
            "codec": "copy",
            "disposition": "+default",
            "language": "eng",
            "debug": "base.ios-audio",
            "bsf": null,
            "bitrate": 512,
            "filter": null
        }
    ]
}
Preopts
[]
Postopts
[
    "-threads",
    "0"
]
Starting conversion.
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3`

**Comment by mdhiggins** [comment]
This looks like an error caused by python 2 and a recent update
Just pushed an update that should fix it

I do minimal compatibility testing on python 2 these days and will probably drop support at some point if there's ever major roadblocks just because its EOL but I'll attempt to keep things working if possible

28f1d76b62d672b3f02ce464797c3d4758546f67

**Comment by Geordon** [comment]
Much appreciated.  I don't have any pressing reason to stick with python 2, so I'd be more than happy to  transition to 3 if you can tell me how.

**Comment by mdhiggins** [comment]
Can just download the installer from pythons website. Good practice is to use virtual environments though but that’s a whole different discussion. Did that update fix python 2?

https://www.python.org/downloads/mac-osx/

**Comment by Geordon** [comment]
Yes, that update worked like a charm, thank you!

—
Geordon VanTassle

From: Michael Higgins <notifications@github.com> <notifications@github.com>
Reply: mdhiggins/sickbeard_mp4_automator
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 3, 2020 at 6:54:00 PM
To: mdhiggins/sickbeard_mp4_automator
<sickbeard_mp4_automator@noreply.github.com>
<sickbeard_mp4_automator@noreply.github.com>
CC: Geordon VanTassle <gvantass@gmail.com> <gvantass@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [mdhiggins/sickbeard_mp4_automator] Manual progress counter
now does new line? (#1152)

Can just download the installer from pythons website. Good practice is to
