### ISSUE TITLE
Automator giving mp4 container wrong framerate meta

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1155]
**Here is the original file meta:**

`Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS`

https://pastebin.com/6Ct8Cark

**Here is the raw H.264 stream meta:**

`Frame rate                               : 23.976 (24000/1001) FPS`

https://pastebin.com/ZgdADFWa

**Here is the output file from MP4 Automator:**

https://pastebin.com/H76Y9cqU

`Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.810 FPS
Maximum frame rate                       : 24.390 FPS`

**Here is my ini file:**

https://pastebin.com/EzM7Nn5h

**Comment by JySzE** [comment]
Apparently this isnt the fault of the automator but is a serious issue in using mp4:

https://trac.ffmpeg.org/ticket/7927

I noticed that the play back on plex is forced to 29.976 because of the VFR tag and that can cause visual issues since this is 23.976 material.

Making the processed mp4 from the automator back to mkv changes the framerate back to the correct value, Is there a way to set the automator to mux the mp4 files back to mkv and merge the srt or (sup) pgs subs?

**Comment by mdhiggins** [comment]
Can't seem to find a work around

Tried setting all `vsync` parameters (0, 1, 2, -1), tried specifying the `-r:v` option to match the source both in float variables and the raw fraction and tried various combinations of the two

I will say that setting the `-r:v` parameter does seem to change the average framerate so maybe there's something there but still produces a variable file

I also tried explicitly setting the inputfile's FPS and the above variables which produced no difference

You can try the fps setting branch here
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/fps

Its the only variant that produced any difference in the output file, see how that plays back and let me know

Muxing mp4's back to MKV files is very easy and can be done currently
Just change your output extension and format to mkv, include all the codecs you want for the various stream times (particularly subtitle image based subtitles) and turn on embed-subs. Make sure you have audio-copy-original and iOS-audio turned off as these might result in duplicated streams (if you already used them to make the MP4s)

**Comment by JySzE** [comment]
Still no change, but I welcome the retention of fps meta none the less. 

Funny enough 25fps material is the only one that doesn't seem to be effected by this mp4 issue.

23.976, 29.976 both have this issue and come out with a variable fps 

Here is a example of 29.976 material acting weird also, which I did not expect. 

**Original 29.976:**

https://pastebin.com/8bGU2ue1

**Raw H.264 Stream 29.976:**

https://pastebin.com/bAxkfHqc

**After automator 29.976:**

https://pastebin.com/C6WWPbq6

I think the only answer is to output everything as mkv at this point.

Which is unfortunate because of the loss of the moov atom and tagging for those who use tagging.

I did find this:

https://forum.doom9.org/showthread.php?t=170781 -

Apparently mp4 supports timecodes also, so maybe if we can extract the timecode from the source file and then merge it with the resulting mp4 file this could be solved.

**Comment by mdhiggins** [comment]
Adding timecode didn't seem to matter

```
        if 'timecode' in safe:
            optlist.extend(['-timecode', safe['timecode']])
        if 'fps' in safe:
            optlist.extend(['-r:v', str(safe['fps'])])
            optlist.extend(['-copyts'])
            optlist.extend(['-vsync', '0'])
            optlist.extend(['-copytb', '0'])
            optlist.extend(['-enc_time_base:v', '-1'])
```

Tried all of those options and many variants of the same with no change

**Comment by mdhiggins** [comment]
If I force those same options but don't 'copy' the stream then it works and produces a constant framerate that matches the source
I suspect this has to do with FFMPEG ignoring most of these parameters when copying

**Comment by mdhiggins** [comment]
I've also read in a few places that the frame timings are the same despite MediaInfo reading it as variable
Are you still having playback issues? And what playback issues are you having? Maybe some sample files for me to play with would be helpful here since comparing the numbers may not be the best approach

https://stackoverflow.com/questions/52214177/ffmpeg-changes-bitrate-to-variable-when-remuxing

If I use FFMPEG to count the result frames and timing the results for both streams is exactly the same

```
mkv
frame=31488 fps=0.0 q=-1.0 Lsize=N/A time=00:21:53.23
```

```
mp4
frame=31488 fps=0.0 q=-1.0 Lsize=N/A time=00:21:53.23
```

**Comment by JySzE** [comment]
So did some more testing and the playback issues I was originally having was plex was detecting any file with the variable fps flag and making it 29.976 even if it said : 

`Frame rate mode : Variable Frame rate : 23.976 (24000/1001) FPS Minimum frame rate : 23.810 FPS Maximum frame rate : 24.390 FPS`

And so i was getting choppy panning shots. 

I just retested it after updating and the same file now that was giving me issues now shows up as 23.976??? 

**Actual Metadata using mediainfo:**

https://pastebin.com/pRCkwVYJ

**Original reported meta from plex:** 

https://pastebin.com/AyyP9gqA

**Reported meta from plex after update:**

https://pastebin.com/ZDvSWRh1

Also would like to note that when playing the file in mpc the fps does show that it fluctuates up and down past what its meant to but i dont see any choppy-ness in the panning shots so idk what to make of that :

**Fps difference recording:** https://www.mediafire.com/file/998dx1x8nowdhsn/owtQh9YtP3.mp4/file

**Sample File:** https://www.mediafire.com/file/1cgcn374aiu39sv/Sample.mkv/file

**Comment by mdhiggins** [comment]
Now that its showing up as 23.976 do you still see the playback issues? Was that change after the fps update or just the same original file?

Any chance plex is transcoding during any of this or is it all direct play?

**Comment by JySzE** [comment]
>Now that its showing up as 23.976 do you still see the playback issues? Was that change after the fps update or just the same original file?

That change in reported Frame rate was from a plex update it was not from the update you made. 

But playback in MPC is still effected. After your update. 

>Any chance plex is transcoding during any of this or is it all direct play?

No its direct playing.

**Comment by JySzE** [comment]
Here is my .ini file if you want to try and replicate the fps issue im getting in mpc:

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4288647/autoProcess.txt)

**Comment by mdhiggins** [comment]
Using the sample file you provided the main branch of the script (before any of the fps changes) I get consistent results between the two files in media player classic 23.96-23.98 fps

**Comment by JySzE** [comment]
Well now I'm even more confused.  😔 

I guess I will close this now and try to fix whatever is happening on my end because it seems to be only me experiencing it. 

Thanks for helping me troubleshoot.  I will reopen if anything changes.

**Comment by mdhiggins** [comment]
Had to leave for work but I’ll do some testing using your autoProcess.ini tonight and see if that makes a difference

**Comment by mdhiggins** [comment]
Tested with your autoProcess.ini file and had the same result, consistent framerate in MPC

Not sure if this has anything to do with it but have you tried installing the LAV filters on windows? I've had this resolve weird playback issues before

https://github.com/Nevcairiel/LAVFilters/releases
