### ISSUE TITLE
[Feature Request] Add pcm_s24le

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1157]
Add pcm_* (all pcm formats) for copying and pcm_s24le to the supported audio-codec=

**Comment by JySzE** [comment]
Ive never worked with python before but i got this to work by adding this to the avcodecs.py file:

```
class Pcm(AudioCodec):
    """
    PCM Codec
    """
    codec_name = 'pcm'
    ffmpeg_codec_name = 'pcm_s24le'
```

```
audio_codec_list = [
    AudioNullCodec, AudioCopyCodec, VorbisCodec, AacCodec, Mp3Codec, Mp2Codec,
    FdkAacCodec, FAacCodec, EAc3Codec, Ac3Codec, DtsCodec, FlacCodec, Opus, Pcm
]
```

I have no idea how to get it to allow all pcm types besides the one i put 'pcm_s24le'

**Comment by mdhiggins** [comment]
0bd46773a8cb2e5b0c3e5bdca68a0433b095a953

**Comment by JySzE** [comment]
Thank you!!
