### ISSUE TITLE
[Feature Request] Seperation of Image based and text based subs

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1158]
Allow the ability to set SRT subs to be embeded but pgs and image based subs to be always dumped so that they can later be OCR'd.
 ^ to avoid transcoding with image based subs

**Comment by JySzE** [comment]
It would also need to be able to copy external srt files and embed them and leave any image based subs if it was grabbed or imported that way.

**Comment by mdhiggins** [comment]
2891bf79703646c95203767409f19ad715014eca

Should be working, new separate `embed-image-subs` option. Both embed options are still dependent on some codec being specified

**Comment by JySzE** [comment]
So this is working now, but It is no longer embedding external srt files

Here is an example of what im trying to do :

![image](https://user-images.githubusercontent.com/25883052/76005310-ae0be100-5ebf-11ea-9e08-fbd28590b4ba.png)

Mux the MP4 and srt and leave the image based subs, i want to make sure if i receive files that have been split apart they can be muxed back together leaving the image based subs.

**Comment by JySzE** [comment]
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4294167/autoProcess.txt)

**Comment by JySzE** [comment]
nvm this works fine, it was messing up because its case sensitive apparently and ENG > eng fixed it.

Sometimes i see people listing subs as .en.srt and .ENG.srt so maybe making it detect that would be helpful if those moments come along.

**Comment by mdhiggins** [comment]
It already handles 2 character language codes, though the case sensitivity thing wasn't intended
91a2872bac31edfc1fce4f3375cd59984f3aca0d
Should be fixed that that patch

**Comment by JySzE** [comment]
Excellent, Great work! Myself and others who use this greatly appreciate your hard work.
