### ISSUE TITLE
Mutagen MP4 not importing

### ISSUE THREAD

**Issue by stevemk14ebr** [mdhiggins/sickbeard_mp4_automator#1159]
```
λ python3 manual.py -i "D:\shows" -a
Traceback (most recent call last):
  File "manual.py", line 15, in <module>
    from metadata import Metadata, MediaType
  File "C:\Users\steve\source\sickbeard_mp4_automator\metadata.py", line 13, in <module>
    from mutagen.mp4 import MP4, MP4Cover, MP4StreamInfoError
ImportError: cannot import name 'MP4' from 'mutagen.mp4' (unknown location)
```

**Comment by mdhiggins** [comment]
Did you install mutagen?

**Comment by stevemk14ebr** [comment]
Yes I did pip3 install mutagen

**Comment by mdhiggins** [comment]
Make sure you don’t have a left over mutagen directory in your script folder that’s causing issues

**Comment by stevemk14ebr** [comment]
oh my bad, i had that + just did a node.js install which uses chocolatey to install deps and that installed a new version of python that messed with my environment variables. So my pip3 and python3 commands were operating on different directories. Got it fixed now, my bad.
