### ISSUE TITLE
[REQ] Simultanious Post Processing

### ISSUE THREAD

**Issue by Mirabis** [mdhiggins/sickbeard_mp4_automator#116]
This is an extra request that could serve as alternative to the thread option, as multi threaded ffmpeg is slower then running 3-4 instances on 1 core.

Could u make it run the processing on background ? 

So sab thinks post processing is done and starts with the next one, while after the processing is done the script still pings couchpotato/nzbdrone/sickbeard so they get moved automatically.

The point of this is when you are downloading with 20MB/s + the post processing queue gets huge and this could greatly speed up the efficiency.

The script would have to queue up to 4 ( or changable  number ) conversions, but once 4 are already running make it wait. 

So < 4, Post process on background else wait ... 

Well I can imagine this might be hard to implement or not something u want to add, in that case would it be possible to get a custom script for some kind of donation?

**Comment by cod3fr3ak** [comment]
I've been thinking on this myself. I actually I'd prefer not to do this, but rather have the script pass a 0 if the conversion was completed correctly. Logs would be good. There are many concurrency programs that can spawn jobs to run this script. If I have time I will try an write up something.

**Comment by mdhiggins** [comment]
This isn't so much an issue with my script as it is a limitation of the way
SAB handles its processing. There's nothing stopping you from creating
multiple simultaneous instances of the script using, for example, manual.py.

Check here for possible solutions:
https://www.sabnzbd.org/viewtopic.php?f=2&t=4365
