### ISSUE TITLE
ReadSettings / autoProcess reformat

### ISSUE THREAD

**Issue by mdhiggins** [mdhiggins/sickbeard_mp4_automator#1162]
The options in the MP4 section have gotten rather long and cumbersome, would like to break that apart into more sections (video, audio, subtitle, etc)

Would also like to overhaul readSettings.py to include more dedicated standardized parsing methods

Ideally would do this in a way that would migrate old configs over to not break anyone's setup

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/settings

This branch contains the settings overhaul, appreciate any testing

**Comment by mdhiggins** [comment]
@RandomNinjaAtk @stevemk14ebr @JySzE

Name dropping a few of the recently active people on here to see if I can get some testers before I merge this back to the main branch. If you can, make sure it migrates all your settings appropriately

**Comment by mdhiggins** [comment]
Pulled the trigger as my prelim tests looked good, closing for now

**Comment by JySzE** [comment]
Okay so a few things I noticed:

Some values I had set to nothing were then changed to a value of "0" and one was changed to 0 when it was actually "5.1"

**Original:**

"video-bitrate = "
"video-max-width = "
"h264-max-level = 5.1"
"max-audio-channels = "
"ignore-truehd = False"
"convert-mp4 = True" < this is completely missing from the reformatting version.

**Reformatted:**

"bitrate = 0"
"max-width = 0"
"max-level = 0"
"max-channels = 0"
"ignore-truehd = " < no value on reformat when original was "False"

You can see if I missed anymore issues here:

Here is my original INI file:  [original.autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4304081/original.autoProcess.txt)

Here is the reformatted INI file: [reformatted.autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4304083/reformatted.autoProcess.txt)

Side note:

Also another thought so every time you run the script it doesn't check the ENTIRE ini file for formatting is to do versioning of the ini file so lets say this INI file would be labeled somehow as "Version 1".

If the script reads that its Version 1 and that matches the current commits version, it wont attempt to reformat the entire thing every time it runs, and next commit if you change or add something to the ini file you just change the version numbering and it will check versioning. (if this is an issue at all).

**Comment by JySzE** [comment]
Dang closed 13 seconds before I posted.  I was too slow 😆

**Comment by mdhiggins** [comment]
I appreciate you getting back to me still!

I rewrote how all the options are parsed because the old method was kind of sloppy and all over the place and I really wanted to clean that up but in a way that wouldn't screw up people's confgs

For some of the settings now 0 is treated like None and I'm using stricter variable types so that's why you're seeing the 0 in lots of stuff. Behavior should still be the same its just the script filling in things

I fixed the level not migrating correctly, had to do with me tagging it as an int instead of float

It only does the migration if it detects the old version of the file so should only run once. It doesn't actually read the entire file it just looks to see if the old "MP4' section is present indicated the old format. I thought about versioning but with versioning I would still need to have all the old code to interpret the other format which wasn't the goal.

the ignore-truehd setting also was reworking. Instead of being a boolean value like before its not an array of extensions. So you could still ignore-truehd for say, MP4 files without having to ignore it for other formats. More flexible this way. If it was set to false before having it blank is the same equivalent

078c7eb47481ca7e05613e3cb9a535f865cddc7f

**Comment by JySzE** [comment]
Excellent news, tested again and everything seems to be working great. 

We appreciate all the hard work.
