### ISSUE TITLE
autoProcess.ini not converting after new ver installed

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1166]
I'm seeing that there were some rather significant changes in the past day or two.  When I pulled the current master branch origin, I am now getting failures when trying to manually process files.

I saw that the file should still be reading the old location, but it doesn't seem to be.

Here's the error:

`tag -i Tagging/Appleseed\ Ex\ Machina\ 2007\ 1080p\ BluRay\ x264\ AAC\ -\ Ozlem/ -a -cmp4
Manual processor started.
Python 64-bit 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 16:07:15)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)].
Guessit version: 3.1.0.
Traceback (most recent call last):
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/manual.py", line 383, in <module>
    main()
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/manual.py", line 359, in main
    walkDir(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), preserveRelative=args['preserverelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
AttributeError: 'NoneType' object has no attribute 'tagfile'`

**Comment by mdhiggins** [comment]
Hm weird that settings would be None. Are you passing custom settings file to manual.py? What’s the full command it looks like it’s cut off

**Comment by Geordon** [comment]
I have an alias "tag" set to point to ~/Documents/GitHub/sickbeard_mp4_automator/manual.py
The full command is shown, there are no custom settings being sent to manual.py.  

So, it's. basically:
manual.py -i [directory with a single mp4 file] -a -cmp4

Automatically guess based on file name and reprocess the MP4 file.

That's where I got the error.

However, I just tried to run a different file (mkv this time), and manual.py upgraded my autoProcess.ini, but now I got this:

`tag -i Tagging/Black\ Magic\ M-66\,\ Appleseed\,\ Dominion\ Tank\ Police\,\ NEW\ D.T.P\,\ etc\ -\ 480p\ DUAL\ AUDIO\ x264/a.\ Black\ Magic\ M-66\ \(1987\ -\ DUAL\ Audio\)/Black\ Magic\ M-66\ 1987.mkv
Manual processor started.
Python 64-bit 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 16:07:15)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)].
Guessit version: 3.1.0.
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Loading config file /Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/autoProcess.ini.
Traceback (most recent call last):
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/manual.py", line 383, in <module>
    main()
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/manual.py", line 317, in main
    settings = ReadSettings(logger=log)
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/resources/readsettings.py", line 518, in __init__
    self.readConfig(config)
  File "/Users/gvantass/Documents/GitHub/sickbeard_mp4_automator/resources/readsettings.py", line 556, in readConfig
    self.permissions['uid'] = config.getint(section, 'uid', vars=os.environ)
TypeError: getint() got an unexpected keyword argument 'vars'`

**Comment by Geordon** [comment]
Side-note:  I had to manually change the permissions on manual.py to execute.

**Comment by mdhiggins** [comment]
Looks like this is an issue with python 2. I haven't been testing against python 2 for a while since most of the dependencies have also dropped support but apparently getint didn't have the vars argument

6cea396820c33551259dd26f1d95bb5711265cad

That should fix that error, though I would consider upgrading to python 3 as I don't know if you'll have issues with some of the libraries the script depends on going forward

**Comment by mdhiggins** [comment]
Also, the -cmp4 option has been renamed as the script is moving towards supporting any format
its now -pse for process-same-extensions

**Comment by mdhiggins** [comment]
Permissions assigned
7c90867a630cfede174624008abccb66337274e0

**Comment by Geordon** [comment]
Ah, understood.  

Alright, just installing the macOS installer of Python 3 did not over-ride the pathing to make python 3 primary on the command line. So, I ripped out the Python 3 installation and installed python3  (actually package python@3.8) and manually linked /usr/local/bin/python and /usr/local/bin/pip to the python@3.8 executable.  That might be something to mention for Mac users.

Ran manual with the new command line switches and WOW is it faster than the old version!   

Should the conversion of autoProcess.ini move the file to the new config location?

**Comment by mdhiggins** [comment]
I didn't include the option to move it previously but that's a good idea. Technically you can override and have autoProcess.ini anywhere but if it detects the old default location and the new default location does not have the file it will now move it, and if that move fails for any reason (docker containers, permissions etc) it will just use it in the old location

0a207bf8859cfb4a101cce46959c56153172f9d8
