### ISSUE TITLE
qBittorrent post processing started but it didn't

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1167]
Hello,
I've setup the script with sonarr and qbittorrent but all that happens is:
`2020-03-10 11:15:01 - qBittorrentPostProcess - INFO - qBittorrent post processing started.`

Then nothing happens, have I set something up wrong?

[autoProcess.ini](https://pastebin.com/raw/9wnERBEG)

**Comment by Smalfinn** [comment]
Changed the logging level to DEBUG and I get:
`2020-03-10 12:12:31 - qBittorrentPostProcess - INFO - qBittorrent post processing started.`
`2020-03-10 12:12:31 - qBittorrentPostProcess - DEBUG - Root Path: C:\FREEFLIX\complete\sonarr\[HorribleSubs] Vinland Saga - 01 [1080p].mkv.`
`2020-03-10 12:12:31 - qBittorrentPostProcess - DEBUG - Label: sonarr.`
`2020-03-10 12:12:31 - qBittorrentPostProcess - DEBUG - Categories: ['couchpotato', 'sickbeard', 'sonarr', 'radarr', 'sickrage', 'bypass'].`
`2020-03-10 12:12:31 - qBittorrentPostProcess - DEBUG - Torrent hash: 73b38e731ba5f0cffbcfc906460217a4067b166e.`
`2020-03-10 12:12:31 - qBittorrentPostProcess - DEBUG - Torrent name: [HorribleSubs] Vinland Saga - 01 [1080p].mkv.`

**Comment by mdhiggins** [comment]
Something is causing a crash. I’ll have an update when I get home (in like 8 hours) that will hopefully catch that and help debug it. 
If you wanted to wrap everything after the logging stops in a try/except block and add
log.exception(“exception occurred”) to the exception section that will tell you why it’s failing

**Comment by Smalfinn** [comment]
Okay, I only got back myself.

I'll wait for the update

**Comment by mdhiggins** [comment]
Alright I found the problem, looks like it was a an issue with a capital letter for actionBefore and actionAfter

That being said I pushed an update that should catch these errors for ALL downloaders scripts and report them in logging and should also fix that issue. Let me know with the latest update if things are any better

**Comment by Smalfinn** [comment]
Looks like we're good to go again!

Thank you 💯

**Comment by mdhiggins** [comment]
As always, appreciate the detailed feedback, makes fixing things easier!
