### ISSUE TITLE
Double universal-audio

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1169]
The Universal Audio option is creating a second acc audio track even after the presence of a "copy" track

[index.log](https://pastebin.com/raw/h1XUneq6)
[autoProcess.ini](https://pastebin.com/raw/BgT0VN4U)

**Comment by mdhiggins** [comment]
That all looks like expected behavior and how that feature is intended to work

**Comment by mdhiggins** [comment]
Actually I see what maybe you're referring to. The audio-first-stream-of-language option?

The current behavior was that it wouldn't be applied if no audio languages were set; no real reason for that so I went ahead and changed that

1280b0ea7c2852a7ef080b05dbc8a09826b498cd
