### ISSUE TITLE
[Feature]On sonarr/radarr upgrades, add option to set file date to original file date.

### ISSUE THREAD

**Issue by uchagani** [mdhiggins/sickbeard_mp4_automator#1171]
Upgraded files cause media servers to show the new file as a new movie/show.  It would be nice if we had an option for sonarr/radarr that, on upgrades, would set the date of the converted file to the original file's date.

We could use the following attributes from sonarr for this:

* `sonarr_isupgrade`
* `sonarr_episodefile_path`
* `sonarr_deletedpaths`

**Comment by mdhiggins** [comment]
Looks like getting and modifying creation times in python across different operating systems is kind of challenging and messy

https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python

Would you want to be changing the creation time or the modified time or both? Creation time will probably be challenging

**Comment by uchagani** [comment]
I think Jellyfin uses file creation date.  But digging into sonarr's code I don't think there is a way to get the file metadata right now anyways.

**Comment by mdhiggins** [comment]
Yeah if the file still existed I could read the data from the original file but I think by the time upgrade is called the original file is deleted. Additionally setting the creation date on a file isn't easy and usually involves some nasty hacks where the system time is temporarily change and the file created but that's probably not something I'd want to implement
Setting the modified time would be achievable if the old file was still around but without Sonarr passing that metadata I don't think there's a way to do this

**Comment by mdhiggins** [comment]
Gonna close this but would revisit if radarr/sonarr add this metadata and if its desired for date modified
