### ISSUE TITLE
NZBGet Postprocess failure with unknown status

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1174]
After the latest updates to mp4automator that were pulled from my nightly git pull cronjob, nzbget post process if failing with errors like below for everything.

I have installed python3 and modified nzbget to to use python3 when executing any *py3 files (NZBGetPostProcess.py was copied to NZBGetPostProcess.py3). All setup requirements were installed as well.

If there is anything else at all that I can provide that would please let me know, and thank you.

> Thu Mar 12 17:16:14 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for Beverly.Hills.Cop.1984.1080p.BluRay.X264-AMIABLE failed (terminated with unknown status)
Thu Mar 12 17:25:47 2020        INFO    Executing post-process-script NZBGetPostProcess.py3 for Beverly.Hills.Cop.1984.1080p.BRRip.x264.DTS-HD.5.1-decatora27
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py3", line 81, in <module>
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:   File "/opt/mp4automator/resources/log.py", line 28, in getLogger
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 76, in fileConfig
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:     formatters = _create_formatters(cp)
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 109, in _create_formatters
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:     flist = cp["formatters"]["keys"]
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess:     raise KeyError(key)
Thu Mar 12 17:25:48 2020        INFO    NZBGetPostProcess: KeyError: 'formatters'
Thu Mar 12 17:25:48 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for Beverly.Hills.Cop.1984.1080p.BRRip.x264.DTS-HD.5.1-decatora27 failed (terminated with unknown status)
Thu Mar 12 19:14:43 2020        INFO    Executing post-process-script NZBGetPostProcess.py3 for True.Lies.1994.1080p.AMZN.WEB-DL.DDP5.1.H.264-ABM
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py3", line 81, in <module>
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:   File "/opt/mp4automator/resources/log.py", line 28, in getLogger
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 76, in fileConfig
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:     formatters = _create_formatters(cp)
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 109, in _create_formatters
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:     flist = cp["formatters"]["keys"]
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess:     raise KeyError(key)
Thu Mar 12 19:14:45 2020        INFO    NZBGetPostProcess: KeyError: 'formatters'
Thu Mar 12 19:14:45 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for True.Lies.1994.1080p.AMZN.WEB-DL.DDP5.1.H.264-ABM failed (terminated with unknown status)
Thu Mar 12 19:42:46 2020        INFO    Executing post-process-script NZBGetPostProcess.py3 for Lethal.Weapon.1987.REMASTERED.RERiP.1080p.BluRay.x264-iLLUSiON
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py3", line 81, in <module>
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:   File "/opt/mp4automator/resources/log.py", line 28, in getLogger
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 76, in fileConfig
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:     formatters = _create_formatters(cp)
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 109, in _create_formatters
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:     flist = cp["formatters"]["keys"]
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess:     raise KeyError(key)
Thu Mar 12 19:42:47 2020        INFO    NZBGetPostProcess: KeyError: 'formatters'
Thu Mar 12 19:42:47 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for Lethal.Weapon.1987.REMASTERED.RERiP.1080p.BluRay.x264-iLLUSiON failed (terminated with unknown status)
Thu Mar 12 20:01:56 2020        INFO    Executing post-process-script NZBGetPostProcess.py3 for Bolt 2008.1080p BluRay x264 Molpol&amp;amp;quot; &amp;amp;amp; &amp;amp;quot;bolt 2008.1080p BluRay Dts x264-SHITSONY
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py3", line 81, in <module>
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess:   File "/opt/mp4automator/resources/log.py", line 28, in getLogger
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Thu Mar 12 20:01:57 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 76, in fileConfig
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess:     formatters = _create_formatters(cp)
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 109, in _create_formatters
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess:     flist = cp["formatters"]["keys"]
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess:     raise KeyError(key)
Thu Mar 12 20:01:58 2020        INFO    NZBGetPostProcess: KeyError: 'formatters'
Thu Mar 12 20:01:58 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for Bolt 2008.1080p BluRay x264 Molpol&amp;amp;quot; &amp;amp;amp; &amp;amp;quot;bolt 2008.1080p BluRay Dts x264-SHITSONY failed (terminated with unknown status)
Thu Mar 12 20:20:08 2020        INFO    Executing post-process-script NZBGetPostProcess.py3 for Ice.Age.Continental.Drift.2012.1080p.BluRay.x264-DAA
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py3", line 81, in <module>
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:     log = getLogger("NZBGetPostProcess", MP4folder)
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:   File "/opt/mp4automator/resources/log.py", line 28, in getLogger
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:     fileConfig(configPath, defaults={'logfilename': logPath})
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 76, in fileConfig
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:     formatters = _create_formatters(cp)
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/logging/config.py", line 109, in _create_formatters
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:     flist = cp["formatters"]["keys"]
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess:     raise KeyError(key)
Thu Mar 12 20:20:09 2020        INFO    NZBGetPostProcess: KeyError: 'formatters'
Thu Mar 12 20:20:09 2020        ERROR   Post-process-script NZBGetPostProcess.py3 for Ice.Age.Continental.Drift.2012.1080p.BluRay.x264-DAA failed (terminated with unknown status)

**Comment by mdhiggins** [comment]
Looks like I forgot to account for the new subdirectory with NZBGet
56386f96e00271258361b4f7b3c8101f4126be1a

NZBGet needs special treatment because it exists outside the usual script location and I had forgotten to account for this change. Should be fixed now please let me know if that fixes your issue

**Comment by johnwchambers** [comment]
Looking better! But now I get the following:

![image](https://user-images.githubusercontent.com/752262/76527368-7221de80-64b2-11ea-9a15-429bdd986d8c.png)

**Comment by mdhiggins** [comment]
That's what I get for trying to fix things before coffee
I forgot a `)` with that change from this morning

Fix that now 4f01e9773c72ca1298bbe313f592bf6c9d9b0072

**Comment by johnwchambers** [comment]
Looks like it's back to the text log output from earlier.

![image](https://user-images.githubusercontent.com/752262/76529117-2fadd100-64b5-11ea-9b5f-0b568919b923.png)

**Comment by mdhiggins** [comment]
1d4270395cda58cd30a56b338684e289857da5e2
Third time's the charm hopefully

**Comment by johnwchambers** [comment]
I manually created the log file mentioned in the error below and gave the appropriate permissions. File was converted successfully:

![image](https://user-images.githubusercontent.com/752262/76537438-1f9bee80-64c1-11ea-89d4-7f9d18d1042b.png)

But then fails saying my sonarr API key is blank:

![image](https://user-images.githubusercontent.com/752262/76537745-933dfb80-64c1-11ea-8b7c-aaa259a2dc95.png)

And here is a snippet of the autoProcess.ini file showing the API key is there:

![image](https://user-images.githubusercontent.com/752262/76537851-b5d01480-64c1-11ea-817e-7527754fd19d.png)

**Comment by johnwchambers** [comment]
Looks like it was looking for the autoProcess.ini file in the main directory instead and created a blank one. I created a symlink pointing /opt/mp4automator/autoProcess.ini to /opt/mp4automator/config/autoProcess.ini and the full post-processing of the file completed successfully.

Glimpse of blank autoProcess.ini getting created:

![image](https://user-images.githubusercontent.com/752262/76539019-8a4e2980-64c3-11ea-9f9d-8f45789ae947.png)

After the symlink everything working:

![image](https://user-images.githubusercontent.com/752262/76539104-a782f800-64c3-11ea-90ff-72e039aebf57.png)

**Comment by mdhiggins** [comment]
Looks like there was logic issue with readsettings as well cause of the same issues with NZBGet and it probably created a blank file in the old location.
Pushed another update to address this as well, delete that default config file that's probably in your script root directory and try the latest fix, sorry about this

**Comment by johnwchambers** [comment]
I'll nuke out the symlink and do a pull and let you know. Thanks again btw for all the help!

**Comment by johnwchambers** [comment]
Your latest update fixed it after I removed the symlink. Thanks again for everything!

Also, is /var/log/sma.log only created because of the NZBGetPostProcess.py? The log file path was /var/log/sickbeard_mp4_automator/index.log before and I just noticed it's not written to anymore on my other two systems either, but neither have complained about the sma.log file not existing.
