### ISSUE TITLE
Max resolution issue

### ISSUE THREAD

**Issue by mbc0** [mdhiggins/sickbeard_mp4_automator#1176]
Hi,

I am using the script with Random-Ninjas sonarr-sma docker to encode downloads to 1280x720 hevc and all is working great except it tries to encode low res files (640x352) to 1280x720. I have specified 1280 in the script thinking/hoping it would only encode files with 1280 as a maximum width and anything larger would be reduced to 1280.
in this instance the source was a low res xvid which although is not in the requested codec list and should not increase the dimensions of the files as the max-width is 1280

"max-width | int |   | Maximum video width, videos larger will be down sized"

[Video]
codec = h265, x265, hevc
bitrate = 0
crf = 24
crf-profiles =
max-width = 1280
profile =
max-level = 0.0
pix-fmt =

![image](https://user-images.githubusercontent.com/19304467/76580622-7bb64100-64c8-11ea-8613-76d3d4ad3bbb.png)

**Comment by mdhiggins** [comment]
Hm yeah that's not the intended behavior, looks like it was a bug for small videos

a9fcd4e9b5bb4fbf9bfba24f0d73415753b3ea62

Should be fixed with that update, though you'll need to wait until the container is rebuilt (though I'll trigger a rebuild tonight which should trigger ninjas)

**Comment by mbc0** [comment]
That's great! thanks for the quick response! :-)

**Comment by mdhiggins** [comment]
Starting the docker builds now, if you see them refresh on docker hub you should be good to update and hopefully the issue will be fixed
Feel to close this issue once you've confirmed things are working

**Comment by mbc0** [comment]
Hi,

Just to update that everything is now working great, thank you!

**Comment by mdhiggins** [comment]
Appreciate the follow up, glad its fixed
