### ISSUE TITLE
Naming subtitle files

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1178]
I thought that the previous version of manual.py used en rather than eng as the English subtitle language.  I could be behind the times, but has that changed?  A bunch of subtitle files that I have are "en" and not "eng" so is there some way to get either of those to embed?  

Is it as simple as changing my subtitle language to "eng, en" ?

**Comment by mdhiggins** [comment]
Everything is standardized around the 3 character language codes and for external subs it will detect 2 and convert to 3 using babelfish. Just set your subtitle language to eng but you shouldn't need to rename your files

**Comment by mdhiggins** [comment]
And to clarify you can name subtitles 2 or 3, but for your autoProcess settings use 3

**Comment by Geordon** [comment]
Thanks!
