### ISSUE TITLE
manual.py does not embed .vtt format subtitles

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1179]
Not sure if this is a but or SWAD, but I am trying to embed .vtt subtitles into an MP4 video file and it doesn't seem to be working.

**Comment by mdhiggins** [comment]
Works fine for me, there's no distinction between extensions anymore so no reason vtt shouldn't work

That being said I did just push an update that makes things more reliable picking up things with weird or no language parameters

47729bb571e42277685c9eb9d7c6725ab771064e

Perhaps your filename didn't have a language parameter before? Either way that update should allow for undefined languages and will set them to the subtitle-default-language if specified

**Comment by Geordon** [comment]
It's working as I expect after the latest update.  Thank you!

—
Geordon VanTassle

On March 14, 2020 at 4:44:04 AM, Michael Higgins (notifications@github.com)
wrote:

Works fine for me, there's no distinction between extensions anymore so no
reason vtt shouldn't work

That being said I did just push an update that makes things more reliable
picking up things with weird or no language parameters

47729bb
<https://github.com/mdhiggins/sickbeard_mp4_automator/commit/47729bb571e42277685c9eb9d7c6725ab771064e>

Perhaps your filename didn't have a language parameter before? Either way
that update should allow for undefined languages and will set them to the
subtitle-default-language if specified

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1179#issuecomment-599034013>,
or unsubscribe
