### ISSUE TITLE
Feature Request: Maximum Audio Bitrate Limit

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1185]
One neat feature the current script has is dynamic bitrates cacluated based on channel count. However, in a lot of cases I find, if you wanted to convert a file with a 5.1+ track to AAC for compatibility reasons, its impossible to control the bitrate from exceeding the input bitrate by quite a lot, especially when using the default setting.

Preferably, it would be great if you could set a maximum cutoff for this reason. So that way for stereo tracks, I could have the limit technically be 128 x 2 (256k) but for 5.1 or greater, it could not exceed say 640k. Because many instances ac3 is only 640k bitrate, but converting to aac means you end up with a file that is encoded at 768k when set at 128 per channel, which is a higher bitrate than the source. 

I've tried using the "0" option, but that doesn't seem to help solve this.

**Comment by mdhiggins** [comment]
I would think the 0 option should prevent this
```
                # Bitrate calculations/overrides
                if self.settings.abitrate == 0:
                    self.log.debug("Attempting to set bitrate based on source stream bitrate.")
                    try:
                        abitrate = ((a.bitrate / 1000) / a.audio_channels) * audio_channels
                    except:
                        self.log.warning("Unable to determine audio bitrate from source stream %s, defaulting to %d per channel." % (a.index, self.default_channel_bitrate))
                        abitrate = audio_channels * self.default_channel_bitrate
```

If the source bitrate was 640 and you were using 6 channels in and out it should come out to the same value

That being said it wouldn't be hard to include a max-bitrate similar to video.

**Comment by mdhiggins** [comment]
ebea08b99d7883581d9551d88150be37f45e2637

max-bitrate setting added
