### ISSUE TITLE
qBittorrent 4.2.X issue

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1187]
Hello,

Cannot run the qBittorrentPostProcess.py
I may have to downgrade back to 4.1.X qBittorrent or wait for [v1k45/python-qBittorrent](https://github.com/v1k45/python-qBittorrent) module to be updated.

[sma.log](https://pastebin.com/raw/HBhD8LuV)

**Comment by mdhiggins** [comment]
Looks like this should be fixed?
https://github.com/v1k45/python-qBittorrent/issues/34
But yeah not really an SMA issue

**Comment by mdhiggins** [comment]
``
        session = requests.Session()
        prefs_url = self.url + 'app/preferences'
        check_prefs = session.get(prefs_url, verify=self.verify)
        if check_prefs.status_code == 200:
            self._is_authenticated = True
            self.session = session

        elif check_prefs.status_code == 404:
            self._is_authenticated = False
            raise RuntimeError("""
                This wrapper only supports qBittorrent applications
                 with version higher than 4.1.x.
                 Please use the latest qBittorrent release.
                """)

        else:
            self._is_authenticated = Fals
``
Kind of looks like that error is generic and if its returning 404 or authen fails you'll get that error too so I would double check your qbt settings and make sure its not an authentication problem (404 will create that error)

**Comment by Smalfinn** [comment]
Typo on my qBittorrent port!
I'll retest now

**Comment by Smalfinn** [comment]
My bad - works fine now
