### ISSUE TITLE
OnDownload error

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sickbeard_mp4_automator#1188]
Hey,

I recently updated my containers, and now get the following logged in Sonarr

`Unable to send OnDownload notification to: postSonarr: ApplicationName='/usr/local/sma/env/bin/python3', CommandLine='/usr/local/sma/postSonarr.py', CurrentDirectory='', Native error= Cannot find the specified file`

What do i need to do to address this?

**Comment by mdhiggins** [comment]
I few things got shuffled around and in preparation for sonarr v3 which is dumping the args section you should now just point to `/usr/local/sma/postSonarr.sh` without args

**Comment by powerdude** [comment]
that did it, thanks!
