### ISSUE TITLE
Feature Request to encode same resolution

### ISSUE THREAD

**Issue by mbc0** [mdhiggins/sickbeard_mp4_automator#1191]
Hi,  

Love this script, thank you for that! 
for years now I have encoded my 720p/1080p X264 tv downloads to 720p X265 but cannot find a way to make the script encode a video if it is 720p?  I use max-width = 1280 so if I download a 1080p video it encodes nicely to 720p but if I download a 720p video it copies it without encoding to x265.  is it possible to have the script force an encode for the same resolution?

Many Thanks

**Comment by mdhiggins** [comment]
Just don’t include whatever codec it’s in on your video codec list. Assuming it’s h264 just leave that off your whitelist

**Comment by mbc0** [comment]
Wow, thanks for the lightning reply! The only reason h264 is on the whitelist is that I don't want anything below 1280 encoded as it generally looks terrible encoding SD videos to x265

**Comment by mdhiggins** [comment]
Gotcha so then yeah there’s really no way. But h265 should still be fine for standard definition I would try looking at the crf-profiles option and see if maybe using that you can just adjust your quality profiles accordingly to your source bitrate and then take h264 off the list. 

But there’s gotta be some component to avoid copying based on the criteria you set

**Comment by mbc0** [comment]
maybe I should up my crf profile then? I currently have crf 24 as this gives really good results on the latest media, I will do some more testing to see if I can get an acceptable encode for SD.  I have found if I increase the crf too much the sd files are larger in x265 than the original x264 which is why I wanted to ignore anything below 720p

**Comment by mdhiggins** [comment]
Yeah the crf-profiles let’s you set various crf and maxrate/bufsize values depending on the source so it may be perfect for what you’re trying to do
