### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by TinTin192** [mdhiggins/sickbeard_mp4_automator#1192]
Just wondering if we're able to setup multiple instances as i've tried and failed.

Installations - 
Radarr - Port 7878
Radarr (4k) - port 7877

Sabnzbd - 8080

All scripts in place etc etc.

Within the scripts. Can we add 2 instances of radarr within the autoProcess.ini. E.g

[Radarr]
webroot = 
host = 1.1.1.1
apikey = APIKEY
port = 7878
ssl = False

[Radarr]
webroot =
host = 1.1.1.1
apikey = APIKEY
port = 7877
ssl = False

AND if we can do such a thing. Can sab pull the seperate category labels in each radarr.

[SABNZBD]
convert = True
sickbeard-category = sickbeard
**radarr-category = movies, 4k**
sonarr-category = tv
output-directory = 
bypass-category = bypass
couchpotato-category = couchpotato
sickrage-category = sickrage

Any assistance would be greatfuly appreciated.

**Comment by mdhiggins** [comment]
Short answer is no, not supported

You're best bet would be to have two instances of the script installed and direct whichever version of radarr to use whichever instance of the script you want and probably just bypass the SAB script all together and use completed download handling

You can also probably achieve this with only one instance of radarr using the filter movie tags parameter

**Comment by TinTin192** [comment]
Awesome. Thank you very much for the response. 
Had a feeling it wasn't possible. But maybe later down the line ;)

**Comment by mdhiggins** [comment]
Another possible option if you don't want to maintain 2 instances of the script is that you can set an environment variable before launching to override your config file path

The environment variable is `SMA_CONFIG`

If you write a small wrapper around launching your scripts you can set that value to override config files for an alternate set of options

for SAB for example
```
#!/usr/bin/env bash
if [ "$5" == "4k" ]
then
$SMA_CONFIG = "/path/to/autoProcess4k.ini"
fi
python /path/to/SABPostProcess.py "$1" "$2" "$3" "$4" "$5" "$6" "$7"
```

**Comment by mdhiggins** [comment]
Batch file

```
IF "%5"=="4k" SET SMA_CONFIG=/path/to/autoProcess4k.ini
python /path/to/SABPostProcess.py "%1" "%2" "%3" "%4" "%5" "%6" "%7"
```

**Comment by mdhiggins** [comment]
Happy to assist further but will close for now

**Comment by mdhiggins** [comment]
And just in case you unsubbed from this after my previous answer, gonna tag you @TinTin192 
Cheers
