### ISSUE TITLE
Is there some way to only process for relocating the MOOV atom?

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#1194]
I know that it's possible to manually process the files for format conversion and subtitles, but is there some way to process files to only process the moov atom?

**Comment by mdhiggins** [comment]
Not sure what you mean. If they’re already MP4 files it won’t convert and will do the pass for tagging and the moov atom. Just have process-same-extension turned off. If you don’t want tagging you can turn that off too.

**Comment by Geordon** [comment]
Ok, so I have files that are previously in MP4, tagged externally, but not
have the moov atom in the correct position.

If I run manual.py -nt with no pse, it will just pass for the moov, correct?

—
Geordon VanTassle

On March 19, 2020 at 6:59:39 PM, Michael Higgins (notifications@github.com)
wrote:

Not sure what you mean. If they’re already MP4 files it won’t convert and
will do the pass for tagging and the moov atom. Just have
process-same-extension turned off. If you don’t want tagging you can turn
that off too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1194#issuecomment-601469922>,
or unsubscribe

**Comment by mdhiggins** [comment]
Correct

**Comment by Geordon** [comment]
Excellent, thank you!
