### ISSUE TITLE
Idea... use local sonarr/radarr metadata for tagging

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1196]
Instead of pulling the information from online, use the data that is already in sonarr/radarr. Both have api's and should be able to produce json files, that you can use to extract the data.

I would think this would speed up the metadata process, by not requiring it to grab the data from online sources, and would also reduce the load of those online resources.

**Comment by mdhiggins** [comment]
Not sure if you'd be able to get parity of data but would be open to a pull request if parity could be achieved
