### ISSUE TITLE
sabnzbd error

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1197]
hello mate. loving the script. been using it sometime now. just downloaded your new files. and now am getting this error on sabnzbd, i have installed the requirements.txt just in case mate.  but i keep getting this error.

```Traceback (most recent call last):
File "/opt/appdata/sickbeard_mp4/SABPostProcess.py", line 5, in <module>
from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
File "/opt/appdata/sickbeard_mp4/autoprocess/autoProcessMovie.py", line 11, in <module>
import requests
File "/usr/local/lib/python3.6/dist-packages/requests/__init__.py", line 113, in <module>
from . import packages
File "/usr/local/lib/python3.6/dist-packages/requests/packages.py", line 7, in <module>
locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'```

**Comment by mdhiggins** [comment]
Did you check and make sure idna is installed? That should be included as part of requests but that's why its failing so try installed that manually and see if it works for you
And make sure you're using the correct python environment through SAB

**Comment by pazport** [comment]
pip install idna
Requirement already satisfied: idna in /usr/local/lib/python3.6/dist-packages (2.9)

that is what i get when i try to install it mate. and sabnzbd is using python3.6 i looked mate

**Comment by mdhiggins** [comment]
Something with IDNA is messed up then, its not a package I import its something requests is importing so I'd try removing and reinstalling or maybe do some debugging on the requests package

**Comment by pazport** [comment]
just an update mate. i found a few of your python scripts have ``#!/usr/bin/env python3`` on them. so i have to change them to ``#!/usr/binpython3.6`` and testing now.

**Comment by pazport** [comment]
@mdhiggins  just an update mate. sabs won't work. i and i don't get log file to see either. so i ran manual.py and i keep getting this. 
``/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Manual processor started.
Python 64-bit 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0].
Guessit version: 3.1.0.
/usr/bin/python3
Loading config file /opt/appdata/sickbeard_mp4/config/autoProcess.ini.``

but when i change it to ``#!/usr/bin python3`` i get ``-bash: ./manual.py: /usr/bin: bad interpreter: Permission denied`` for some reason. this has never happened before.

**Comment by mdhiggins** [comment]
Something definitely going on with your python environment
You shouldn't have to change the shebang. You could also just point to your python executable you want to use followed by the script as a shell script to ensure the environment is correct

**Comment by pazport** [comment]
defo something going of mate. in sabs all i get is ``Exit(-1) Cannot run script /opt/appdata/sickbeard_mp4/SABPostProcess.py`` i even changed it back to ``#!/usr/bin/env python3``
still don't work. but manual.py will work lol. it was all working fine until i grab the new files.

**Comment by mdhiggins** [comment]
Its probably the transition to python 3 that's creating issues somewhere. The logs won't show anything if it crashes before it does its imports and its clearly crashing during importing. The new shebang is probably causing things to execute in some other python environment you have installed that's missing or has a corrupt dependency.  Unfortunately these environment errors you kind of have to debug on your own since it specific to your machine but that's what's happening

**Comment by pazport** [comment]
well your older files are working fine. but your new/updated files on python3 just won't work on sabs. al stick with your older files for time being. i am no good at debugin stuff mate.

**Comment by mdhiggins** [comment]
I gave you one avenue, make a quick shell script and point it to the correct python executable instead of relying on sab to execute the script directly. You're free to use an older version but eventually the libraries this script depends on are gonna start to break python2, lots of them have dropped official support already
