### ISSUE TITLE
Post Processing not working for NZBGet, Sonarr or Radarr, but works manually.

### ISSUE THREAD

**Issue by jennec** [mdhiggins/sickbeard_mp4_automator#1198]
I upgraded to the current version yesterday (23rd March 2020).  Since then NZBGet, Sonarr and Radarr are unable to use any of the postproces scripts.

NZBGet give me "failed (terminated with unknown status)"
Sonarr and Radarr just does nothing, has nothing in the logs and does not convert the file.  But put 
the file in the right place.  

But a manuall conversion works fine.  No errors.  

I am running:
Python 3.6
Sonarr: 2.0.0.5344
Radarr: 0.2.0.1480
Mono: 5.20.1.19
NZBGet: 21.1-testing-r2311
and all current version of modules listed in setup/requirements.txt

None of the above have changed since before the upgrade of the script.

I setup NZBGet with a customised NZBPostPorcess.ini file per category, pointing to two different AutoProcess.ini files (one for 720p conversion for TV shows, and one for 1080p for Movies).
But, even if I just use the original file the same issues happens.  (all files are copied to the NZBGet/Scripts folder.  

Any help at all would be most appreciated.

**Comment by jennec** [comment]
hmm.  I spoke too soon:  the manually process also gives out errors:

Seems like an issue with mutagen and paths with spaces (maybe)?

/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4 created.
Unable to set new file permissions.
Traceback (most recent call last):
  File "/mnt/mpathn/jennec/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1006, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"
Tagging file: /mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4.
There was an error tagging the file
Traceback (most recent call last):
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 235, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manual.py", line 232, in processFile
    tagdata.writeTags(output['output'], settings.artwork, settings.thumbnail, width=output['x'], height=output['y'])
  File "/mnt/mpathn/jennec/sickbeard_mp4_automator/resources/metadata.py", line 149, in writeTags
    video = MP4(path)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 139, in wrapper
    writable, create) as h:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 256, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"

**Comment by hoyane** [comment]
Interesting! I am in the middle of troubleshooting this also. https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1172

I'll be keeping an eye on this one also.

**Comment by mdhiggins** [comment]
Looks like for some reason the file isn't existing in the directory it expects, can you confirm the file is ever there?

**Comment by mdhiggins** [comment]
A full output of the logs for one file start to finish will be helpful here

**Comment by jennec** [comment]
I can't find any log entries for any conversions that were triggered by NZBGetPostProcess.py. or Sonarr or Radarr in the logs.  I can only see the manual convesions.  I wil run a few test after clearing the log to create from NZBGet and Sonarr/Radarr when my current batch of manual conversions have finished. 

Additionally, I noticed now that the script does not rename the original files as xxx.original when converting.  Is this on purpose?  Could it be added back in?  I exclude the *.original file exention from some scripts that move data around on a schedule and it would handy if it did not move an MKV file whilst its being converted.  

The log entry for the manual conversion of Supernatural which ended up failing and removing the file (looks like it could be issue setting permissions):

```
2020-03-24 14:09:38 - MANUAL - INFO - Manual processor started.
2020-03-24 14:09:38 - MANUAL - INFO - /usr/lib/python-exec/python3.6/python3
2020-03-24 14:09:38 - MANUAL - INFO - Loading config file /home/jennec/sickbeard_mp4_automator/config/autoProcess720.ini.
2020-03-24 14:09:38 - MANUAL - INFO - Processing file /home/jennec/media/local/TV/Supergirl/Season 05/Supergirl - S05E16 - Alex in Wonderland.mkv
2020-03-24 14:09:39 - MANUAL - INFO - Matched TV episode as Supergirl (TMDB ID: 62688) S05E16
2020-03-24 14:09:39 - MANUAL - INFO - Processing Supergirl Season 05 Episode 16 - Alex in Wonderland
2020-03-24 14:09:39 - MANUAL - INFO - Input Data
2020-03-24 14:09:39 - MANUAL - INFO - {
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "pix_fmt": "yuv420p",
        "profile": "high",
        "fps": 23.976023976023978,
        "level": 4.0,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "eac3",
            "channels": 6,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default"
        }
    ],
    "subtitle": [
        {
            "index": 2,
            "codec": "subrip",
            "disposition": null,
            "language": "eng"
        },
        {
            "index": 3,
            "codec": "subrip",
            "disposition": null,
            "language": "eng"
        }
    ],
    "attachment": []
}
2020-03-24 14:09:39 - MANUAL - INFO - Reading video stream.
2020-03-24 14:09:39 - MANUAL - INFO - Video codec detected: h264.
2020-03-24 14:09:39 - MANUAL - INFO - Pix Fmt: yuv420p.
2020-03-24 14:09:39 - MANUAL - INFO - Profile: high.
2020-03-24 14:09:39 - MANUAL - INFO - Reading audio streams.
2020-03-24 14:09:39 - MANUAL - INFO - Audio detected for stream 1 - eac3 eng 6 channel.
2020-03-24 14:09:39 - MANUAL - INFO - Creating ac3 audio stream from source stream 1.
2020-03-24 14:09:39 - MANUAL - INFO - Default audio stream set to eng ac3 6 channel stream [default-more-channels: True].
2020-03-24 14:09:39 - MANUAL - INFO - Reading subtitle streams.
2020-03-24 14:09:40 - MANUAL - INFO - Text-based subtitle detected for stream 2 - subrip eng.
2020-03-24 14:09:40 - MANUAL - INFO - Creating mov_text subtitle stream from source stream 2.
2020-03-24 14:09:41 - MANUAL - INFO - Text-based subtitle detected for stream 3 - subrip eng.
2020-03-24 14:09:41 - MANUAL - INFO - Creating mov_text subtitle stream from source stream 3.
2020-03-24 14:09:41 - MANUAL - INFO - Attempting to download subtitles.
2020-03-24 14:09:42 - MANUAL - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2020-03-24 14:09:42 - MANUAL - INFO - Output Data
2020-03-24 14:09:42 - MANUAL - INFO - {
    "source": [
        "/home/jennec/media/local/TV/Supergirl/Season 05/Supergirl - S05E16 - Alex in Wonderland.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264",
        "map": 0,
        "bitrate": 3400,
        "crf": 21,
        "maxrate": null,
        "bufsize": null,
        "level": 4.0,
        "profile": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": 1280,
        "debug": "video.bitrate.max-width"
    },
    "audio": [
        {
            "map": 1,
            "codec": "ac3",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        }
    ],
    "subtitle": [
        {
            "map": 2,
            "codec": "mov_text",
            "language": "eng",
            "encoding": "",
            "disposition": "+default",
            "debug": "subtitle.embed-subs"
        },
        {
            "map": 3,
            "codec": "mov_text",
            "language": "eng",
            "encoding": "",
            "disposition": null,
            "debug": "subtitle.embed-subs"
        }
    ],
    "attachment": []
}
2020-03-24 14:09:42 - MANUAL - INFO - Preopts
2020-03-24 14:09:42 - MANUAL - INFO - [
    "-fix_sub_duration"
]
2020-03-24 14:09:42 - MANUAL - INFO - Postopts
2020-03-24 14:09:42 - MANUAL - INFO - [
    "-threads",
    "4",
    "-metadata:g",
    "encoding_tool=SMA",
    "-movflags",
    "+faststart",
    "-preset",
    "slow",
    "-max_muxing_queue_size",
    "9999"
]
2020-03-24 14:09:42 - MANUAL - INFO - Starting conversion.
2020-03-24 14:24:05 - MANUAL - INFO - /mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4 created.
2020-03-24 14:24:05 - MANUAL - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/mnt/mpathn/jennec/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1006, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"
2020-03-24 14:24:05 - MANUAL - INFO - Tagging file: /mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4.
2020-03-24 14:24:05 - MANUAL - ERROR - There was an error tagging the file
Traceback (most recent call last):
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 235, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manual.py", line 232, in processFile
    tagdata.writeTags(output['output'], settings.artwork, settings.thumbnail, width=output['x'], height=output['y'])
  File "/mnt/mpathn/jennec/sickbeard_mp4_automator/resources/metadata.py", line 149, in writeTags
    video = MP4(path)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 139, in wrapper
    writable, create) as h:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jennec/.local/lib64/python3.6/site-packages/mutagen/_util.py", line 256, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: "/mnt/mpathn/jennec/media/local/TV/Supernatural/Season 15/Supernatural - S15E13 - Destiny's Child.mp4"
```


My autoProcess.ini file:

```
[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 4
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
force-convert = False
post-process = False
preopts = 
postopts = -movflags,+faststart,-preset,slow

[Permissions]
chmod = 0755
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = false
preserve-source-disposition = True

[Video]
codec = h264, x264
bitrate = 3400
crf = 22
crf-profiles = 
max-width = 1920
profile = high
max-level = 4.0
pix-fmt = yuv420p

[Audio]
codec = ac3
languages = eng
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 6
prefer-more-channels = True
default-more-channels = True
filter = 
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v

[Universal Audio]
codec = 
channel-bitrate = 128
first-stream-only = False
move-after = True
filter = 

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
download-subs = True
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
ignore-embedded-subs = False
attachment-codec = 

[Sonarr]
host = xxxxxxxxxxxxxxxx
port = 26148
web_root = 
ssl = False
apikey = xxxxxxxxxxxxxxxxxxxxxxxxx
webroot = 

[Radarr]
host = xxxxxxxxxxxxxxxxxxx
port = 16503
web_root = 
ssl = False
apikey = xxxxxxxxxxxxxxxxxxx
webroot = 

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = tv-sonarr
radarr-label = movies-radarr
bypass-label = bypass
convert = True
host = localhost
port = 29756
username =xxxxxxx
password = xxxxxxxxxxxxxxxxxx
output-directory = 
remove = False

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 

[Plex]
host = xxxxxxxxxxxxxxxxxxxxxxx.plex.direct
port = 13712
refresh = True
token = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by mdhiggins** [comment]
So there's been no changes to the .original behavior
This is very strange as it looks like the file is created and everything works then the file is deleted by the time it goes to do anything including setting permissions
Only thing I can think of is that maybe there's some other program or process that's moving or deleting the files for some reason? I literally creates the file then it disappears when the next steps occur

Can you turn on debug level logging? (inside logging.ini) in your config folder. This is very strange and I'm not sure why the file would just disappear. If you watch the file while its being created does it just disappear?

**Comment by wjbeckett** [comment]
I have noticed the same thing. 
I have found that Radarr and Sonarr aren't importing and starting the postprocessing script. 
If I manually run the import via Sonarr/Radarr the post processing script kicks off and works as expected.

**Comment by jennec** [comment]
OK.  So I ran some tests just now.  I am concentrating on NZBGet as this is the where my work flow starts.  I avoid Sonarr and Radarr running SMA because it can run too many at the same time I am limited on CPU resource.  NZBGets ability to process one at a time saves me here.  

I also have different autoProcess.ini files depending on if its a movie or a tv download.  Movies get converted to 1080p (autoprocess1080.ini) and TV episodes to 720p (autoProcess720.ini).  But for the purposes of these tests I am using the standard autoProcess.ini set to 1080p on a movie download in NZBGet. I just want to get the basics working and then figure out how to reference the different ini files later.  

FYI:  I am running this on a shared linux Gentoo server.  All application run as the same user and cannot be run as root or any other user.  (using Whatbox if that helps at all).  

So Re-running Post Processing on NZBGet with all the following settings:

MP4_Folder: /home/jennec/sickbeard_mp4_automator/
SHOULDCONVERT: True
RADARR_CAT: movies (matches NZBGet Category)
SONARR_CAT: tv (matches NZBGet Categroy)

NZBGet Category: movies set to use NZBGetPostPorcess.py

I get the following outpout from NZBGet:

```
Wed Mar 25 2020 11:33:56	INFO	Post-processing again Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES
Wed Mar 25 2020 11:33:56	INFO	Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES returned from history back to download queue
Wed Mar 25 2020 11:33:56	INFO	Queueing Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES for post-processing
Wed Mar 25 2020 11:33:56	INFO	Executing post-process-script NZBGetPostProcess.py for Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).
Wed Mar 25 2020 11:33:57	DEBUG	NZBGetPostProcess: Path: /home/jennec/downloads/completed/movies/Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES
Wed Mar 25 2020 11:33:57	DEBUG	NZBGetPostProcess: NZB: Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.nzb
Wed Mar 25 2020 11:33:57	DEBUG	NZBGetPostProcess: Category: movies
Wed Mar 25 2020 11:33:57	DEBUG	NZBGetPostProcess: Categories: ['sickbeard', 'couchpotato', 'tv', 'movies', 'sickrage', 'bypass']
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess: 2020-03-25 11:33:57 - resources.readsettings - INFO - /usr/lib/python-exec/python3.6/python3
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess: 2020-03-25 11:33:57 - resources.readsettings - INFO - Loading config file /mnt/mpathn/jennec/sickbeard_mp4_automator/config/autoProcess.ini.
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess: Traceback (most recent call last):
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/mnt/mpathn/jennec/nzbget/scripts/NZBGetPostProcess.py", line 177, in <module>
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     settings = ReadSettings(MP4folder)
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/home/jennec/sickbeard_mp4_automator/resources/readsettings.py", line 539, in __init__
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     self.readConfig(config)
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/home/jennec/sickbeard_mp4_automator/resources/readsettings.py", line 686, in readConfig
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     self.Sonarr['port'] = config.getint(section, "port")
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/home/jennec/sickbeard_mp4_automator/resources/readsettings.py", line 71, in getint
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     return super(SMAConfigParser, self).getint(section, option, vars=vars)
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 819, in getint
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     fallback=fallback, **kwargs)
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 809, in _get_conv
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     **kwargs)
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:   File "/usr/lib64/python3.6/configparser.py", line 803, in _get
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess:     return conv(self.get(section, option, **kwargs))
Wed Mar 25 2020 11:33:57	INFO	NZBGetPostProcess: ValueError: invalid literal for int() with base 10: ''
Wed Mar 25 2020 11:33:57	ERROR	Post-process-script NZBGetPostProcess.py for Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES failed (terminated with unknown status)
Wed Mar 25 2020 11:33:57	INFO	Collection Birds.of.Prey.and.the.Fantabulous.Emancipation.of.One.Harley.Quinn.2020.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES added to history
```
I get very little in the SMA Log file:

```
2020-03-25 11:33:57 - NZBGetPostProcess - INFO - Script triggered from NZBGet (11.0 or later).
2020-03-25 11:33:57 - resources.readsettings - INFO - /usr/lib/python-exec/python3.6/python3
2020-03-25 11:33:57 - resources.readsettings - INFO - Loading config file /mnt/mpathn/jennec/sickbeard_mp4_automator/config/autoProcess.ini.
```

attached are my config files used during the test

[Setting files.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4380614/Setting.files.zip)

**Comment by mdhiggins** [comment]
@jennec looks likes its crashing while trying to read the **Sonarr > port** option of the config file. Do you by chance have a bad value in there? It needs to be some kind of integer. Python's config parser reads the whole file and if a value is set to the wrong type it will generate that kind of error

**Comment by jennec** [comment]
I removed all the settings I did have in there so that they are blank, for Sonarr, Radarr and Deluge.  I just put the default values in there and those errors went away.  But it still did not work until I put the UUID of my running user ID in autoProcess.ini, then it started working  and logging as expected.  I am not sure why this would make a difference as NZBGet is running as the same UUID.  But if it works then I am happy.  

Ive also made two copies of the NZBGetPostProcess.py and changed line 177 to be as follows:

NZBGetPostProcess1080.py:
`settings = ReadSettings("/mnt/mpathn/jennec/sickbeard_mp4_automator/config/autoProcess1080.ini")`

NZBGetPostProcess720.py:
`settings = ReadSettings("/mnt/mpathn/jennec/sickbeard_mp4_automator/config/autoProcess720.ini")`

Is this the right syntax or should I be using something different?  in previous versions I used 
`settings = ReadSettings(MP4folder, 'autoProcess1080.ini')`
But this kept failing in the latest version.

**Comment by mdhiggins** [comment]
Yeah the ReadSettings init function uses a single parameter now. Additionally in an effort to try and support multiple configs more officially, I added the option to just set an environment variables prior to launching the script

So now if you write a small shell script you can adjust your config file without needing to modify the python files by setting the environment variable `SMA_CONFIG`

Here's a sample

```
#!/usr/bin/env bash

if [ "$NZBPP_CATEGORY" == "radarr-1080p" ]
then
$SMA_CONFIG = "/path/to/autoProcess1080.ini"
fi
python /path/to/NZBGetPostProcess.py
```

**Comment by jennec** [comment]
Ah, that makes sense.

I did try to run a nash (.sh) script from NZBGet but it did not pickit up.  would this need to be a python script extension for NZBGet to see it?

**Comment by mdhiggins** [comment]
Nah it can be at .sh script but it needs some extra headers
See here
https://nzbget.net/extension-scripts

**Comment by jennec** [comment]
Great.  Hadn't thought of looking there.  I'll knock a script a script up and test it out.

Thank you for your help,.
