### ISSUE TITLE
Separate Log Files

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1199]
It looks like in this last release the logs were moved into the config folder to a file called sma.log.  I have one config folder I use for both sonarr-sma and radarr-sma so now the logs for both apps are written to the same file.

Can these be separated back out into 2 files in the config folder sonarr-sma.log and radarr-sma.log?  I guess I could create 2 separate sma config folders, but then the same update in the future would need to be made on both directories.  It would seem cleaner to keep things in one folder and separate out the logs for easier reading when troubleshooting issues.

**Comment by mdhiggins** [comment]
Just have 2 instances of logging.ini and mount one of each for each container.
You can then edit that to point to whatever log file path and name you want

**Comment by samcro1967** [comment]
I think there may be an issues with logging in the sonarr-sma container.

I copied logging.ini to radarr-logging.ini and changed the following line:
args = ('/usr/local/sma/config/radarr-sma.log', 10000, 1)

I copied radarr-logging.ini to sonarr-logging.ini and changed the following line:
args = ('/usr/local/sma/config/sonarr-sma.log', 10000, 1)

I removed both containers and added them both back mounting them using their respective logging.ini file as follows:
-v C:\Users\user\Documents\Docker\sma\radarr-logging.ini:/usr/local/sma/config/logging.ini
-v C:\Users\user\Documents\Docker\sma\sonarr-logging.ini:/usr/local/sma/config/logging.ini

I now get a radarr-sma.log in C:\Users\user\Documents\Docker\sma, but I am not getting a sonarr-sma.log file.

**Comment by mdhiggins** [comment]
Are there any errors if you try to run the script? They both pull the exact same build of SMA so there shouldn't be any differences between the two containers

**Comment by samcro1967** [comment]
You do mean try to run "python3 manual.py -i movie_name.mkv" from inside the container correct?

**Comment by mdhiggins** [comment]
Correct

**Comment by samcro1967** [comment]
I do get an error when I run it from within the container.

python3 /usr/local/sma/manual.py -i E4JYH0def0JRtp1sEk7FePV.mkv
Traceback (most recent call last):
  File "/usr/local/sma/manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'

**Comment by mdhiggins** [comment]
Make sure you're running it using the python3 binary inside the venv directory

`/usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py -nd -i E4JYH0def0JRtp1sEk7FePV.mkv`

**Comment by samcro1967** [comment]
It did create the sonarr-sma.log file when I ran it manually.  So it seems like it picked up the correct logging.ini file when ran manually.  I guess that validates that the file mount for logging.ini is correct?  Not sure though where that means the problem lies.

**Comment by mdhiggins** [comment]
It might mean everything is working fine,  the .log files aren't created until the script runs so maybe it just hadn't run in the sonarr instance?

**Comment by samcro1967** [comment]
It had finished because i had a converted and tagged MP4 file.  I tried restarting Docker and that did not help.  I am copying a large file over the network at the moment.  Once that finishes in a few hours, I will reboot the host to see if that has any impact.

**Comment by samcro1967** [comment]
A host reboot did not resolve it either.  I am geeting en error in Sonarr that I am not seeing in Radarr.  SABNZBD and Sonarr logs are attached.

Error I am seeing is "20-3-24 17:45:25.5|Warn|NzbDroneErrorPipeline|API Error"  Not sure if it has any relevance or not.

[Logs.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4378422/Logs.zip)

**Comment by samcro1967** [comment]
It started working overnight.  I think I was looking at a preexisting job in the queue after the reboot which did not generate the log.  I removed it and more ran over night.  I now have a log file.  Seem,s the host reboot did resolve somethign in Docker that a Docker restart did not.

As always, thanks for the help!

**Comment by mdhiggins** [comment]
Good stuff thanks for following up
