### ISSUE TITLE
Feature Request, Maximum Video Bitrate (same as max video width and max audito bitrate)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1206]
The problem:

Incoming file is does not match the correct codec and requires a conversion to the specified codec. The incoming file is low quality, ie xvid or some other low bitrate. If your currently using the Video bitrate setting as a limiter, anything low bitrate will be encoded using the maximum bitrate set.

Meaning a incoming file that is 4 Mbps for video bitrate would be re-encoded to 12 Mbps, if that was the configured video bitrate. Ideally you'd want to use the 0 option to have it match, but that would mean its not possible to re-encode high bitrate files to lower bitrate.

Solution:
Add a maximum video bitrate option, to match the settings for maximum video width and audio with to allow you to size down files with higher bitrate then max, but allow dynamic set bitrate for anything lower.

Hope this wasn't confusing...

**Comment by mdhiggins** [comment]
Currently it sort of already works like a max
```
        vbr = self.estimateVideoBitrate(info)
        vbitrate = self.settings.vbitrate or vbr
        if self.settings.vbitrate and vbr > self.settings.vbitrate:
            self.log.debug("Overriding video bitrate. Codec cannot be copied because video bitrate is too high [video-bitrate].")
            vdebug = vdebug + ".bitrate"
            vcodec = self.settings.vcodec[0]
```

Would switching to this perhaps fix things?
```
        vbitrate = self.estimateVideoBitrate(info)
        if self.settings.vbitrate and vbitrate > self.settings.vbitrate:
            self.log.debug("Overriding video bitrate. Codec cannot be copied because video bitrate is too high [video-bitrate].")
            vdebug = vdebug + ".bitrate"
            vcodec = self.settings.vcodec[0]
            vbitrate = self.settings.vbitrate
```

This way if estimated rate is higher than the max, it goes down to the max; if its less than the max it will use the estimated source bitrate

**Comment by RandomNinjaAtk** [comment]
> 
> 
> Currently it sort of already works like a max
> 
> ```
>         vbr = self.estimateVideoBitrate(info)
>         vbitrate = self.settings.vbitrate or vbr
>         if self.settings.vbitrate and vbr > self.settings.vbitrate:
>             self.log.debug("Overriding video bitrate. Codec cannot be copied because video bitrate is too high [video-bitrate].")
>             vdebug = vdebug + ".bitrate"
>             vcodec = self.settings.vcodec[0]
> ```
> 
> Would switching to this perhaps fix things?
> 
> ```
>         vbitrate = self.estimateVideoBitrate(info)
>         if self.settings.vbitrate and vbitrate > self.settings.vbitrate:
>             self.log.debug("Overriding video bitrate. Codec cannot be copied because video bitrate is too high [video-bitrate].")
>             vdebug = vdebug + ".bitrate"
>             vcodec = self.settings.vcodec[0]
>             vbitrate = self.settings.vbitrate
> ```
> 
> This way if estimated rate is higher than the max, it goes down to the max; if its less than the max it will use the estimated source bitrate

That is exactly what I was hoping for with this request

**Comment by mdhiggins** [comment]
7c495f59fa16fcf200f51383d46ae7c58295f9b4

That should do the trick. Took this change opportunity to rename bitrate to max-bitrate for consistency across options
