### ISSUE TITLE
Medusa daocker build stop being able to execute script

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#1207]
I built a Medusa Docker image with sickbeard_mp4_automator and up until recently it was working great. Now the script does not run.

I get the following error
Extra script /usr/bin/python3 /app/sickbeard_mp4_automator/postSickbeard.py is not a file

My Medusa Docker build
https://hub.docker.com/repository/docker/raydiasdockerhub/medusa_ffmpeg_mp4_automator

**Comment by mdhiggins** [comment]
No idea, is the file actually there? Seems more like an issue with your docker container

**Comment by rrd911** [comment]
yes it's there. I can go into the container and run
/usr/bin/python3 /app/sickbeard_mp4_automator/postSickbeard.py

Of course it errors our since I have no files referenced.

root@medusa-anime-mp4:/# /usr/bin/python3 /app/sickbeard_mp4_automator/postSickbeard.py
2020-03-30 22:53:56 - SickbeardPostProcess - INFO - Sickbeard extra script post processing started.
2020-03-30 22:53:56 - resources.readsettings - INFO - /usr/bin/python3
2020-03-30 22:53:56 - resources.readsettings - INFO - Loading config file /app/sickbeard_mp4_automator/config/autoProcess.ini.
2020-03-30 22:53:56 - SickbeardPostProcess - ERROR - Not enough command line arguments present 1.
2020-03-30 22:53:56 - SickbeardPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/app/sickbeard_mp4_automator/postSickbeard.py", line 51, in <module>
    sys.exit(1)
SystemExit: 1

**Comment by rrd911** [comment]
I am going to see if I role back to a Medusa build from linuxserver/medusa in my docker build from 19 days ago to see if it's an issue with Medusa changes.

**Comment by mdhiggins** [comment]
Couple ideas

Make sure that the account running medusa has access to the script file

Try to make a wrapper script. You can look at my docker containers for radarr/sonarr for example. I include a postRadarr.sh / postSonarr.sh file that links the python path and script and execute that instead of trying to pass the python exe and a parameter directly to the program. Just make sure you pass your command line parameters if you do that

**Comment by rrd911** [comment]
thanks will try that next. Odd that up until recently it was working fine.

**Comment by rrd911** [comment]
ok on a fluke I removed the /usr/bin/python3 and left the /app/sickbeard_mp4_automator/postSickbeard.py in the post processing script field.

It executed the script, but did not convert the video. Probably something in the autoProcess.ini

format has changed in the autoProcess.ini but at least it executed the  /app/sickbeard_mp4_automator/postSickbeard.py

**Comment by mdhiggins** [comment]
It might fail because it uses the wrong python environment if you’re not specifying the correct one. The new config shouldn’t cause issues and it should migrate your old config to the new format.

**Comment by rrd911** [comment]
now I have it so it converts but it deletes the original and the converted file.

**Comment by mdhiggins** [comment]
No logic in the script that should do that. I can’t help you unless you post some log files.

**Comment by rrd911** [comment]
digging into it further

**Comment by mdhiggins** [comment]
Gonna close this for now since its not really a script issue but happy to help if you post some logs
