### ISSUE TITLE
Not really an issue, just a question...

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#1209]
Wanted to write some gratitude as well, this project has been a lifesaver.

Really appreciate the work you put into it.

I just saw the new settings for the video quality, was wondering if I could get a better breakdown or maybe another resource on the "crf-profiles", I'm struggling with understanding how to get it to work, and how it can benefit me vs the crf property.

I saw the wiki page on it, but I'm still not fully understanding it. Any additional info on I could get?

Thanks.

**Comment by mdhiggins** [comment]
I appreciate the kind words

The `crf-profiles` option arose from this issue
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/724

Its just an option that allows you to set different CRF values along with maxrate and bufsize parameters depending on the quality of the input file. You can sort of read through the issue to see why people were requesting it. Hopefully that helps but feel free to ask more questions if its not clear
