### ISSUE TITLE
NZBGetPostProcess: Wrong path to sickbeard_mp4_automator

### ISSUE THREAD

**Issue by chazsm1** [mdhiggins/sickbeard_mp4_automator#1211]
- manual.py works perfectly. 
- The path is set correctly, the script starts so I think its an import error
- seems similar to what was happening [here](https://www.reddit.com/r/PleX/comments/3rts18/mp4_automator_script_suite/cwualc6/?context=8&depth=9)
- I added  print(sys.path)   and    print(sys.executable)   to NZBGetPostProcess.py  to help troubleshoot
- This is on a fresh install of Ubuntu 18.04 on a Proxmox VM. It's been years since I setup mp4automator on 16.04, which has run without issue since. I decided to do a fresh install of everything on 18.04 and the only thing I can't get working is the NZBGetPostProcessing
- I do have python, python3, pip, and pip3 installed

- NZBGet Logs:

```
error | Wed Apr 01 2020 12:35:29 | Post-process-script  NZBGetPostProcess.py for video failed (terminated  with unknown status)

error | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess: None

error | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess: Wrong path to sickbeard_mp4_automator: /home/vls2020/apps/mp4automator/

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess: /usr/bin/python3

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:  ['/home/vls2020/apps/nzbget/scripts', '/usr/lib/python36.zip',  '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess: ModuleNotFoundError: No module named 'tmdbsimple'

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:     import tmdbsimple as tmdb

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:   File "/home/vls2020/apps/mp4automator/resources/metadata.py", line 12, in <module>

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:     from resources.metadata import Metadata

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:   File "/home/vls2020/apps/mp4automator/resources/mediaprocessor.py", line 12, in <module>

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:     from resources.mediaprocessor import MediaProcessor

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess:   File "/home/vls2020/apps/nzbget/scripts/NZBGetPostProcess.py", line 75, in <module>

info | Wed Apr 01 2020 12:35:29 | NZBGetPostProcess: Traceback (most recent call last):

info | Wed Apr 01 2020 12:35:29 | Executing post-process-script NZBGetPostProcess.py for video
```

- I have all of the dependencies installed
`vls2020@vls2020:~/apps/mp4automator$ pip list
appdirs (1.4.3)
asn1crypto (0.24.0)
babelfish (0.5.5)
backports.functools-lru-cache (1.6.1)
beautifulsoup4 (4.8.2)
certifi (2019.11.28)
cffi (1.14.0)
chardet (3.0.4)
click (7.1.1)
cryptography (2.8)
decorator (4.4.2)
dogpile.cache (0.9.0)
enum34 (1.1.10)
enzyme (0.4.1)
futures (3.3.0)
guessit (3.1.0)
idna (2.9)
ipaddress (1.0.23)
keyring (10.6.0)
keyrings.alt (3.0)
mutagen (1.43.0)
pbr (5.4.4)
pip (9.0.1)
pycparser (2.20)
pycrypto (2.6.1)
pygobject (3.26.1)
pyOpenSSL (19.1.0)
pysrt (1.1.2)
python-dateutil (2.8.1)
pytz (2019.3)
pyxdg (0.25)
qtfaststart (1.8)
rarfile (3.1)
rebulk (2.0.0)
requests (2.23.0)
requests-cache (0.5.2)
SecretStorage (2.3.1)
setuptools (44.1.0)
six (1.14.0)
soupsieve (1.9.5)
stevedore (1.32.0)
subliminal (2.0.5)
tmdbsimple (2.2.0)
urllib3 (1.25.8)
wheel (0.30.0)`

- Also installed pip3 dependencies just in case
`vls2020@vls2020:~/apps/mp4automator$ pip list
appdirs (1.4.3)
asn1crypto (0.24.0)
babelfish (0.5.5)
backports.functools-lru-cache (1.6.1)
beautifulsoup4 (4.8.2)
certifi (2019.11.28)
cffi (1.14.0)
chardet (3.0.4)
click (7.1.1)
cryptography (2.8)
decorator (4.4.2)
dogpile.cache (0.9.0)
enum34 (1.1.10)
enzyme (0.4.1)
futures (3.3.0)
guessit (3.1.0)
idna (2.9)
ipaddress (1.0.23)
keyring (10.6.0)
keyrings.alt (3.0)
mutagen (1.43.0)
pbr (5.4.4)
pip (9.0.1)
pycparser (2.20)
pycrypto (2.6.1)
pygobject (3.26.1)
pyOpenSSL (19.1.0)
pysrt (1.1.2)
python-dateutil (2.8.1)
pytz (2019.3)
pyxdg (0.25)
qtfaststart (1.8)
rarfile (3.1)
rebulk (2.0.0)
requests (2.23.0)
requests-cache (0.5.2)
SecretStorage (2.3.1)
setuptools (44.1.0)
six (1.14.0)
soupsieve (1.9.5)
stevedore (1.32.0)
subliminal (2.0.5)
tmdbsimple (2.2.0)
urllib3 (1.25.8)
wheel (0.30.0)`

**Comment by mdhiggins** [comment]
Does the python path match what manual.py shows?

Either way, the fix is to point NZBGet to the correct executable using 
![image](https://user-images.githubusercontent.com/3608298/78187916-52406380-743d-11ea-978b-605e59d54833.png)

**Comment by chazsm1** [comment]
Thanks for the fast response! I probably did something simple wrong when setting it up, I'm a beginner with linux.

I added .py=/usr/bin/python3 to the ShellOverride field, but it still failed.

manual.py is the same except for one thing: '/home/vls2020/.local/lib/python3.6/site-packages'

```
vls2020@vls2020:~/apps/mp4automator$ python3 manual.py
['/home/vls2020/apps/mp4automator', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/vls2020/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
/usr/bin/python3
Manual processor started.
Python 64-bit 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0].
Guessit version: 3.1.0.
/usr/bin/python3
Loading config file /home/vls2020/apps/mp4automator/config/autoProcess.ini.
```

**Comment by mdhiggins** [comment]
Not sure why tmdbsimple won’t import then. Very strange. Does manual.py actually recognize files and tag? Seems like things should be working and it’s clearly reading the correct script folder. 

Sometimes removing and reinstalling that specific dependency helps.

**Comment by mdhiggins** [comment]
https://stackoverflow.com/questions/31384639/what-is-pythons-site-packages-directory

Maybe its installed on a per user basis and not globally?

I'm a little stumped but the missing site-packages is where tmdbsimple would be installed

**Comment by mdhiggins** [comment]
Cleaner option might be to just install everything under a virtualenv for python and point to that, that'll probably be most reliable

**Comment by chazsm1** [comment]
Yes, manual.py recognizes and tags the files perfectly.

I just tried removing and reinstalling the tmdbsimple, no luck.

Yes, tmdb is in /home/vls2020/.local/lib/python3.6/site-packages so that would would make sense.

**Comment by mdhiggins** [comment]
Seems like we know why things aren't working, its an environmental issue. Gonna close this but happy to keep helping if you haven't found a solution
