### ISSUE TITLE
Consistent tagging issue

### ISSUE THREAD

**Issue by Squ1gg1E** [mdhiggins/sickbeard_mp4_automator#1212]
There was an error tagging the file
Traceback (most recent call last):
  File "./manual.py", line 232, in processFile
    tagdata.writeTags(output['output'], settings.artwork, settings.thumbnail, width=output['x'], height=output['y'])
  File "/root/sickbeard_mp4_automator/resources/metadata.py", line 181, in writeTags
    if self.HD:
AttributeError: 'Metadata' object has no attribute 'HD'
Relocating MOOV atom to start of file.

**Comment by mdhiggins** [comment]
e9017a3f0c6d6b6bbffc4bd2043d61d29e20b0f2

That should fix it

**Comment by Squ1gg1E** [comment]
Thanks!

**Comment by Squ1gg1E** [comment]
This fixed it.  Thanks again.
