### ISSUE TITLE
CRF Profiles cause Max-Width to be NULL

### ISSUE THREAD

**Issue by jennec** [mdhiggins/sickbeard_mp4_automator#1213]
When I add a CRF Profile to my autoProcess.ini file the Max-Width passed to FFMPEG is passed as NULL instead of the value configured.  Is correct?

AutoProcess.ini excertp:

```
[Video]
codec = h264, x264
bitrate = 0
crf = -1
crf-profiles = 3400:23:3.4M:8M
max-width = 1280
profile = high
max-level = 4.0
pix-fmt = yuv420p
```
NZBPostProcess.log:
[Max-Width is Null.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4422062/Max-Width.is.Null.log)

**Comment by mdhiggins** [comment]
Max width is only passed if the video exceeds the max width. Otherwise it should be null

**Comment by RandomNinjaAtk** [comment]
> Max width is only passed if the video exceeds the max width. Otherwise it should be null

The only issue, I see  is that it looks like the original video should be 1920 width, based on the file/folder name. So, it should have triggered the max width also?

**Comment by mdhiggins** [comment]
crf profiles have no impact on video width. Best guess here is ffprobe is reporting a width lower than the max width. Post your ffprobe -show_streams data for this file so we can see what FFMPEG is reporting

**Comment by mdhiggins** [comment]
Additionally, I found that release and downloaded that exact file `Underwater.2020.1080p.Bluray.DTS-HD.MA.7.1.X264-EVO.mkv`

Copied your settings exactly as well

```
        "video": {
            "codec": "h264",
            "map": 1,
            "bitrate": 20670.432,
            "crf": 23,
            "maxrate": "3.4m",
            "bufsize": "8m",
            "level": 4.0,
            "profile": null,
            "pix_fmt": null,
            "field_order": "progressive",
            "width": 1280,
            "debug": "video.max-width.max-level"
```

**Comment by jennec** [comment]
If it’s supposed to be Null When the source matches the value set in the ini file then that’s fine.  I wasn’t sure if null was supposed to be the right value passed.  Thanks for clearing that up. 

I wanted the source to stay at 1920 anyway

The log file was using max-width of 1920 but I had typed out the wrong value in my post earlier. Apologies for the confusion.
