### ISSUE TITLE
Guessit Error when running manually

### ISSUE THREAD

**Issue by abzkebabs** [mdhiggins/sickbeard_mp4_automator#1214]
First of I would like to say thanks for you putting so much time and effort into this and when I get it working it's going to be a lifesaver. 

I have just set everything up but when I try a manual run I get the following error: 

>  File "C:\Mp4_Automater\manual.py", line 155, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: 'module' object has no attribute 'guessit'

What could I have done wrong because I followed the setup exactly but just cannot get it to work !

**Comment by mdhiggins** [comment]
You just need to update to the latest version of guessit
