### ISSUE TITLE
SABnzbd don't support Python3

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1215]
Hi, in order for the script to work with SABnzbd I have to change the shebang to `#!/usr/bin/env python`.

Reason is because Sabs don't support Python3. Source: https://sabnzbd.org/wiki/faq#toc4

Could be good if you could add that in the description under SABnzbd configuration page :)

**Comment by mdhiggins** [comment]
SAB should still respect the shebang and even though SAB needs python 2.7 to run the post scripts it executes can be python3. By changing the shebang you're forcing the script to run on python 2 which isn't ideal.

See here https://forums.sabnzbd.org/viewtopic.php?f=2&t=24563

**Comment by morganzero** [comment]
Thank you!
When I change the shebang in `SABPostProcess.py` back to `#!/usr/bin/env python3` I get `error code is 127`in SABnzbd. And when looking further, it shows the below:
```
Script: Exit(127) /usr/bin/env: ‘python3’: No such file or directory
```
The manual.py works as intended;
```
Manual processor started.
Python 64-bit 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0].
Guessit version: 3.1.0.
/usr/bin/python3
Loading config file /opt/mp4manual/config/autoProcess.ini.
Enter path to file:
```

**Comment by mdhiggins** [comment]
Must be missing from your environment under SAB. You could try pointing the shebang to /usr/bin/python3 since that's what it resolves to. You could also just make a shell script that points to your python executable and the script (see that forum post) which is always the safest way

**Comment by morganzero** [comment]
I change the shebang in `SABPostProcess.py` to `/usr/bin/python3` instead. And that gave me a different error code in SAB; `error code is -1`;
```
Script
Exit(-1) Cannot run script /mp4automator/SABPostProcess.py
```

**Comment by mdhiggins** [comment]
I’m not sure what to make of that error but I would just do the shell script then

**Comment by morganzero** [comment]
Hmm. This is so odd.
Pointing the catagories to the `.sh` instead of the `.py` should've forced it I reckon. But I still get the same 127 error.
```
Script: Exit(127) /usr/bin/env: ‘python3’: No such file or directory
```

**Comment by mdhiggins** [comment]
Post the code of your files. Were you getting that same error originally?

**Comment by morganzero** [comment]
I haven't seen that error before until a few days ago and yesterday when I wanted to try out your updated SMA-script.

For the Shell script it's this:
```bash
#!/bin/bash
python3 /opt/mp4automator/SABPostProcess.py "$@"
```
After making it executable I point my catagories in SAB to my shell script `SABPostProcess.sh`.
Let me know if there was some other file you were thinking about.

**Comment by mdhiggins** [comment]
Does typing python3 in your console work?

I would try putting the full path to python3 in your shell script (or consider using virtual python environments). Its not recognizing your python3 command so both the shebang and the shell script seem to be failing since they are pointing to the same thing

Do you have python 3 installed?

Does typing `which python3` result in anything on the command line?

**Comment by morganzero** [comment]
Sorry for my ignorance, how do I put the full path to python3 in the shell script? Noobie here :)

When typing it in terminal I get this:
```
user@morganzero ~ # python3 /opt/mp4automator/SABPostProcess.py
2020-04-06 17:31:29 - SABPostProcess - INFO - SAB post processing started.
2020-04-06 17:31:29 - SABPostProcess - ERROR - Not enough command line parameters specified. Is this being called from SAB?
```

Typing `which python3`;
```
/usr/bin/python3
```
Typing `python -V`;
```
Python 3.6.9
```

**Comment by mdhiggins** [comment]
```
#!/bin/bash
/usr/bin/python3 /opt/mp4automator/SABPostProcess.py "$@"
```

**Comment by morganzero** [comment]
Thank you. I did that. No change in error.
![image](https://user-images.githubusercontent.com/57449785/78641510-a3bf7700-78b1-11ea-812c-62a46fc7022e.png)

I even setup a Virtual Python Environment as suggested - following [this guide](https://linuxize.com/post/how-to-create-python-virtual-environments-on-ubuntu-18-04/).

The error in SAB changed to `Exit(-1) Cannot run script /opt/mp4automator/SABPostProcess.py` instead.

I also found [this article](https://github.com/linuxserver/docker-sabnzbd/issues/67#issuecomment-570704820) interesting.

I do not understand why SAB works with running the script in python2 but not in python3.

I'm completely astray.

**Comment by mdhiggins** [comment]
It almost looks like SAB is still trying to execute the .py script and not the .sh script
You did change the script in SAB correct?

**Comment by morganzero** [comment]
Yes I pointed the catagories to SABPostProcess.**sh** instead of **.py**

And the shell itself is currently written like this:
```
#!/bin/bash
usr/bin/python3 /opt/mp4automator/SABPostProcess.py "$@"
```

I tried using NZBGet instead. I got a `PP-Failure`. Nothing works with me haha 😄

**Comment by mdhiggins** [comment]
I see one problem if your shell script
You forgot your initial '/' in your path which will screw everything up

It should read 
```
#!/bin/bash
/usr/bin/python3 /opt/mp4automator/SABPostProcess.py "$@"
```


Yeah this is a tough one. In NZBGet you have the option of using shell override where you can force it to execute with different python instances

![image](https://user-images.githubusercontent.com/3608298/79045117-70455b00-7bd7-11ea-8966-b1a5a0abd7c9.png)

That might be an option to force NZBGet to work. If both are failing then I'd say you probably just have something messed up in your python installation that's causing both to go down.

**Comment by morganzero** [comment]
After some research with a friend, we finally figured out how to install the requirements with pip3 in the SAB container so it would run the Python3 script.

If anyone ever encounter the same issue as I did, this is what I had to do to get it working:

Firstly, bash in to your SAB:
```
sudo docker exec -it sabnzbd /bin/bash
```
Then run:
```
apt-get update
apt-get install git par2 unrar python3-setuptools python3-pip
apt-get install libffi-dev libssl-dev

git clone https://github.com/sabnzbd/sabnzbd.git 
cd sabnzbd/

pip3 install -r requirements.txt -U
tools/make_mo.py 
./SABnzbd.py -b0
```
Then run:
```
pip3 install requests requests[security] requests-cache babelfish tmdbsimple mutagen guessit subliminal python-dateutil stevedore qtfaststart
```
And lastly restart your SAB:
```
sudo docker restart sabnzbd
```
And yo should be good to go.

Just a reminder if you would update the SAB container or re-deploy it, you will have to redo the process again.

Thank you for being patient and helping me out @mdhiggins.
