### ISSUE TITLE
can i use the same autoprocess.ini ?

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#1217]
I just updated and notice there are many changes. The autoprocess.ini file has a completely different layout. Can I continue using the same ini or do I need to migrate to the new one?

**Comment by mdhiggins** [comment]
It should migrate your old ini to the new format

**Comment by Deihmos** [comment]
Sorry I did not realize that happened automatically. Thank you for this program.

**Comment by mdhiggins** [comment]
No problem, it should all happen on your first run
