### ISSUE TITLE
postSonarr.sh

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1222]
I don't have much experience with shell script, I wanted to know how to create postSonarr.sh, since I use Sonarr V3?
Thank you!

**Comment by mdhiggins** [comment]
No problem. I include a shell script in the docker container that you can reference

https://github.com/mdhiggins/sonarr-sma/blob/master/extras/postSonarr.sh

Just update the paths to reflect where your files are

Here's an example that doesn't use environment variables just to reduce confusion
```
#!/usr/bin/env bash

/path/to/python3 /path/to/postSonarr.py
```
