### ISSUE TITLE
updated the files

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1223]
Hello mate, i have grabbed the updated files. and got sabsnzbd to work with python3. i have noticed that manual.py is a lot faster now. but the sabnzbdprocess.py is still ain't any faster. It couldn't be that SAB interferes with the script to make it slow right?

**Comment by mdhiggins** [comment]
The more recent updates and transition to python 3 aren't gonna make a big impact on speed. Speed is entirely determined by what sort of conversion operations are being performed. Remuxing everything? Then your HD speed is the limiting factor. Encoding? Then its your CPU. Using hardware acceleration? Then your GPU. If you're encoding just audio it will be faster than doing video too. If you're encoding 5 streams it will take longer than 1.

All in all you shouldn't see any major differences between the various scripts if processing the exact same files, they all just funnel everything into mediaprocessor.py, though some scripts have additional steps (manual.py for example will tag and then do a QTFS sweep that SAB won't attempt) that will add time
