### ISSUE TITLE
sonarr-sma docker cpu performance

### ISSUE THREAD

**Issue by twistedatoms** [mdhiggins/sickbeard_mp4_automator#1224]
I have set up the sonarr-sma docker you provide on an unraid server. the docker is working but the performance is suffering hard because the docker, when doing the SMA conversions, will only use one core of my server at a time. If I look at TOP in the docker it just has the CPU at 100% and if I look at unraid it shows 1 core of the 16 maxed out. I tried forcing FFmpeg to do more threads but it almost seems like the docker itself doesn't allow more. I'm not doing any limitation or CPU pinning.

**Comment by mdhiggins** [comment]
Probably not a docker limitation. More likely that that FFMPEG doesn’t have a multi threaded encoder for whatever format you’re using. It has very few.

**Comment by twistedatoms** [comment]
We don't have to reopen the issue but my transcoding performance was far better on barbones than it is now in the docker.. :(

**Comment by mdhiggins** [comment]
Happy to keep the discussion going but I stand by my original statement. There's always gonna be some performance hit for virtualization / docker but it should be pretty minimal. Docker doesn't impose any single core utilization limitations as far as I know. I'm happy to look at some data if you want to provide it but my performance has been stable. Transcoding time has a lot to do with what encoders are required and whether those encoders are multithreaded or efficient. The only real way to see if there's a different would be be comparing two transcodes of the same video writing to the same destination drive (ideally from the same destination drive too) and see if there's a performance difference. If you wanna give that a shot and post some logs and times to see if there's a problem with your setup I'm happy to take a look.
