### ISSUE TITLE
question about autoprocess.ini ?

### ISSUE THREAD

**Issue by Cyb3rGh05t** [mdhiggins/sickbeard_mp4_automator#1226]
hi,

i am new to this project, and not familiar with python! i want to know if it is possible to use the autoprocess to just convert the files into MP4 as is without touching the FORCED SRT's or SRT's files staying in the source folder?
Just converting the MKV files as it is into MP4 without touching at all the subtitles files (different extensions).

Thank you

**Comment by mdhiggins** [comment]
Yep
If you have the `embed-subs` and `embed-image-subs` turned off it won't touch SRT files

**Comment by Cyb3rGh05t** [comment]
thanks
