### ISSUE TITLE
Feature: Backup origional file to set location before doing anything

### ISSUE THREAD

**Issue by ck3mp** [mdhiggins/sickbeard_mp4_automator#1229]
Just come across this set of scripts after a lot of searching and they’re brilliant.

One thing I would like to do is backup the file before any processing is done, just in case something goes wrong. The scripts I made that I used to use (before discovering SMA which all blew them away) would move files to a folder and remove any files older than 30 days as a sort of buffering area to allow me to catch any messed up encodes with no real maintained.

I know I can leave the original file in place but would this mess with Sabnzbd etc?

Is this possible or would it be a feature request?

**Comment by mdhiggins** [comment]
If you turn off delete original it shouldn’t touch the original file at all, and in situations where conversion fails or there are problems there’s multiple checks that should abort deleting the source file even with that option enabled.
