### ISSUE TITLE
Deleted file after upload

### ISSUE THREAD

**Issue by LecoBaliza** [mdhiggins/sickbeard_mp4_automator#1231]
Hello,
I'm using Windows 10 with Rclone with Google Drive, and I use qBittorrent to download the files. It happens as follows, Sonarr sends the file to qBittorrent, after downloading it starts the conversion process, it sends the file to the right folder, but after that it deletes the uploaded file.

Log https://justpaste.it/26qwm
Config https://justpaste.it/2e45z
Google drive https://prnt.sc/s3e126

Thanks

**Comment by mdhiggins** [comment]
Think you need to check your Sonarr logs cause everything looks like it’s working as intended from the script. Is Sonarr deleting the file for some reason or do you have other software that might be moving or deleting the file?

**Comment by LecoBaliza** [comment]
> Think you need to check your Sonarr logs cause everything looks like it’s working as intended from the script. Is Sonarr deleting the file for some reason or do you have other software that might be moving or deleting the file?

The disc is being mounted by rclone, there is no other program that touches the files

For some reason Sonarr checked the files after 3 uploads, the last file sent was deleted, but the other 2 were not deleted. Episode 8 has been deleted, but 6 and 7 have been checked correctly. Could this error be caused by something related to the rclone cache?

Log Sonarr https://justpaste.it/41csu

**Comment by LecoBaliza** [comment]
Problem solved, apparently he moved the original file to Google Drive and made a second copy on the local disk. And since the `delete-original` was active, it deleted the file from the drive.
