### ISSUE TITLE
[Question] regarding docker image tags and updates

### ISSUE THREAD

**Issue by kimpenhaus** [mdhiggins/sickbeard_mp4_automator#1234]
Hi,

First of all - this is not an issue but two questions on information I can't find and maybe knowledge about docker images I don't have 😃 

I am currently using the [linuxserver-sonarr:preview](https://hub.docker.com/r/linuxserver/sonarr) and [linuxserver-radarr:latest](https://hub.docker.com/r/linuxserver/radarr). I saw that your docker images are depending on those from linuxserver (which makes migration quite easy :+1:) 

These are the two questions I have:

1. Are your tags equivalent to those from linuxsever. E.g. if I want to use the preview image of sonarr do I have to choose the preview tag? (I think so - but just to clarify)

2. If any of the underlying linuxsever image is updated - is there any policy that yours will be updated too? (And I guess yours will be updated more often also containing the updates from your repo?)

Thanks!

**Comment by mdhiggins** [comment]
1. Yes
2. Yes*

* docker hub automatically triggers a build if the parent container is updated. It does not trigger a build everytime I update this repo, only the sonarr-sma/radarr-sma repos. I do manually build after any major changes and usually any minor changes too. There's the option to enable SMA_UPDATE to force the script to do a git pull on restart to ensure the script is the most up to date without needing a container rebuild. Its in the readme.

**Comment by kimpenhaus** [comment]
Excellent - thank's a lot! 👋
