### ISSUE TITLE
Skipping certain audio format like mp3/mp2 not to be converted to aac.

### ISSUE THREAD

**Issue by jahmac23** [mdhiggins/sickbeard_mp4_automator#1235]
Hello, I would like to skip mp3 and mp2 audio file not to be converted to aac. Basically any other audio format I want converted to aac. Any option I can put to skip mp3/mp2 audio. Like while doing batch of files in a directory I want to copy mp3/mp2 audio without being converted and only convert ac3,eac,dts or any other format other than aac to aac.

**Comment by mdhiggins** [comment]
Just add those codecs to your codec list

**Comment by jahmac23** [comment]
I added those mp3, in audio codec. "audio-codec = acc, mp3, mp2". but still its doing conversion as audio 0 as aac and audio 1 as copy. i tried with true and false both setup to "audio-copy-original = False/True"
Video codec detected: mpeg4.
Pix Fmt: yuv420p.
Profile: Advanced Simple Profile.
Reading audio streams.
Audio detected for stream #1: mp3 [und].
Creating audio stream 0 from source stream 1.
Adding copy of original audio track in format mp3
Reading subtitle streams.
Subtitle stream array is empty.
{
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 943.53145,
        "level": null,
        "profile": null,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "eng",
            "disposition": "default"
        },
        "1": {
            "map": 1,
            "codec": "copy",
            "language": "eng",
            "disposition": "none"
        }
    },
    "subtitle": {},
    "preopts": [],
    "postopts": [
        "-threads",
        "0"
    ]
}
Starting conversion.
65

**Comment by mdhiggins** [comment]
Are you on and old version or something? that output looks dated

**Comment by mdhiggins** [comment]
Gonna close this again since it definitely looks like an old version and may no longer be relevant. Other things that will cause remuxing to fail would be having a max channel or bitrate that's set below your source material. Feel free to update and see if that fixes things and if not post your config settings and a full conversion output
