### ISSUE TITLE
 ModuleNotFoundError: No module named 'resources.readsettings'

### ISSUE THREAD

**Issue by Callumro** [mdhiggins/sickbeard_mp4_automator#1238]
Hey there,

Despite my best efforts of google fu and git hub fu I am unable to sort this one out on my own and I fear that means I am missing something simple.

Running sma on a rpi4 with NZBGet, Sonarr and Radarr. I have python, pip, python3 and pip3 installed. I have used pip3 to install all dependencies from requirements.txt

1. Installed ffmpeg using apt-get install ffmpeg
2. Renamed the autoprocess.ini file in the config directory
3. Set the configuration options
4. Successfully ran manual.py and converted file
5. Configured direct integration with NZBGet and Radarr and here is where I run into issues...

My _nzblog.txt file:
```INFO    2020-05-04 21:26:02     Collection The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated added to history
INFO    2020-05-04 21:43:28     Post-processing again The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated
INFO    2020-05-04 21:43:28     The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated returned from history back to download queue
INFO    2020-05-04 21:43:28     Queueing The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated for post-processing
INFO    2020-05-04 21:43:28     Executing post-process-script NZBGetPostProcess.py for The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated
INFO    2020-05-04 21:43:28     NZBGetPostProcess: Traceback (most recent call last):
INFO    2020-05-04 21:43:28     NZBGetPostProcess:   File "/mnt/ssd/dietpi_userdata/nzbget/scripts/NZBGetPostProcess.py", line 71, in <module>
INFO    2020-05-04 21:43:28     NZBGetPostProcess:     from resources.readsettings import ReadSettings
INFO    2020-05-04 21:43:28     NZBGetPostProcess: ModuleNotFoundError: No module named 'resources.readsettings'
ERROR   2020-05-04 21:43:28     NZBGetPostProcess: Wrong path to sickbeard_mp4_automator: /mnt/ssd/Git/sickbeard_mp4_automator/
ERROR   2020-05-04 21:43:28     NZBGetPostProcess: None
ERROR   2020-05-04 21:43:29     Post-process-script NZBGetPostProcess.py for The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated failed (terminated with$
INFO    2020-05-04 21:43:29     Executing post-process-script Logger.py for The.Hunger.Games.2012.1080p.BluRay.DTS.H.265.HEVC-BUYMORE-Obfuscated
```

Screenshot of my NZBGETPOSTPROCESS settings page:
![image](https://user-images.githubusercontent.com/31681632/81035978-15a7c380-8e52-11ea-9cb6-0f4af01da904.png)

Any help would be appreciated!

**Comment by mdhiggins** [comment]
Your settings all look like they are entered correctly.

Because NZBGet scripts reside in a remote location, the script takes your MP4_FOLDER and adds it to your path variable and then tries to do its local import

```
sys.path.append(MP4folder)
try:
    from resources.readsettings import ReadSettings
    from resources.mediaprocessor import MediaProcessor
    from resources.log import getLogger
    from autoprocess import autoProcessMovie, autoProcessTV, autoProcessTVSR, sonarr, radarr
except ImportError:
    print("[ERROR] Wrong path to sickbeard_mp4_automator: " + os.environ['NZBPO_MP4_FOLDER'])
    print("[ERROR] %s" % traceback.print_exc())
    sys.exit(1)
```

That's where you're getting stuck

If you can, please verify that
`/mnt/ssd/Git/sickbeard_mp4_automator/resources/readsettings.py` exists since that's the import that's failing. It probably does assuming you installed everything correctly but just in case there's a subdirectory or something, for example, this will not work

`/mnt/ssd/Git/sickbeard_mp4_automator/sma/resources/readsettings.py`

If that all checks out, next step would be to verify permissions. Often the user/group running these background programs like NZBGet won't have permission to access `/mnt/ssd/Git/sickbeard_mp4_automator/` and you'll need to grant that with chmod/chown

**Comment by Callumro** [comment]
I appreciate the assistance with this!

> Because NZBGet scripts reside in a remote location

The scripts are on an attached SSD, would it be simpler if I moved them to the SD card of the pi?

> If you can, please verify that
> /mnt/ssd/Git/sickbeard_mp4_automator/resources/readsettings.py exists since that's the import that's failing.

Got that here:
![image](https://user-images.githubusercontent.com/31681632/81132605-e3ef3500-8f03-11ea-9d75-d74b7b6f5bbd.png)

> If that all checks out, next step would be to verify permissions.

I will admit, I still consider linux permissions an area I struggle. Let me know what you think, nzbget runs with a user "nzbget" and a member of the group "dietpi"
Demonstrated here:
![image](https://user-images.githubusercontent.com/31681632/81135642-e22a6f00-8f0d-11ea-8e79-68838ea00f5a.png)
and the sma folder permissions here:
![image](https://user-images.githubusercontent.com/31681632/81135703-1e5dcf80-8f0e-11ea-9350-6eb29cf1f9c4.png)

**Comment by mdhiggins** [comment]
Your permissions and file structure look correct so I guess that's not the issue. The group being the same especially with the relaxed permissions you have there shouldn't be a problem. 

Are you running any of these programs in a sandbox/docker style setup?

I would think it shouldn't matter where the script resides but it may be worthwhile to try to move the script to the SSD and see if that helps.

**Comment by Callumro** [comment]
Everything is running native in the raspbian OS. 

Although i agree it would be strange, tonight I will attempt starting from a fresh git clone on the SD card instead of the SSD and report back.

**Comment by Callumro** [comment]
Hey Michael,

Took a few steps tonight

1. Removed the existing folder "/mnt/ssd/Git/sickbeard_mp4_automator/"
2. Downloaded a fresh git clone
3. Copied autoProcess.ini to the config folder, re-configured ffmpeg paths.
4. Tested with manual.py successfully
5. Updated the path to the sma folder in NZBGet, Radarr and Sonarr and ran post-processessing again with the same error.

![image](https://user-images.githubusercontent.com/31681632/81251241-a3f98200-8fd7-11ea-91fc-82c7670dbb69.png)

Any thoughts on what else we could try?
Would it be possible to install this module using pip3 instead of relying on the resources folder?

Let me know if I can pull any additional information that might help us troubleshoot

**Comment by Callumro** [comment]
Hey looks like I got it!

Did my research and learned a bit about sys.path in this process. As I understand, the array in sys.path runs in order and if 'resources' were to exist in any other path it would search that directory for readsettings and if it is not found error out instead of continuing. [[source]](https://stackoverflow.com/questions/48885445/import-python-module-using-sys-path-append)

So I added some logging to rule out any problem related to sys.path:
![image](https://user-images.githubusercontent.com/31681632/81256680-0a859c80-8fe6-11ea-8d87-6c6794bebb7d.png)

From there I checked each path and found that a directory called 'resources' existed in one of my other paths. It appears at one time I must have done a `pip3 install resources`. Honestly probably while trying to resolve that error before I posted.

a quick `pip3 uninstall resources` an im off to the races

**Comment by mdhiggins** [comment]
Great solution and thanks for sharing! Didn't realize that was how python behaved but that's good to know

Given that, I pushed a small update that has the script add the MP4folder to the beginning of the sys.path array

f9c0bc3cc4207568870d61dd9e268005d7d95049

Hopefully that will help people in the future with the same issue
