### ISSUE TITLE
postSonarr.py

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1245]
I have this error when connecting the script, the radarr is running normal, but the sonarr is showing this error, I already installed the pip install requests and the error remains.
  | Component | Message | Time |  
-- | -- | -- | -- | --
  | SonarrErrorPipeline | Invalid request Validation failed: -- : Script exited with code: 1 | 11:18pm |  
  | postSonarr.sh | ImportError: No module named 'requests' | 11:18pm |  
  | postSonarr.sh | import requests | 11:18pm |  
  | postSonarr.sh | File "/media/sdc1/k2xx/mp4_automator-master/postSonarr.py", line 4, in <module> | 11:18pm |  
  | postSonarr.sh | Traceback (most recent call last): | 11:18pm

**Comment by mdhiggins** [comment]
You have multiple python environments if your installation of requests isn't being seen and Sonarr is probably using the wrong one
I would point to the specific python executable you intend to execute if you aren't doing that.
Issues like this have been opened multiple times so you can reference those for other solutions

Here is another example
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1237
