### ISSUE TITLE
Sudden error with Manual.py

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1246]
Suddenly getting a error when running Manual.py
Says something about line 10 import enum then closes out

**Comment by mdhiggins** [comment]
Had to face palm at this one a little bit

Run manual.py using command prompt so that the window doesn't close and please post the full error

**Comment by morpheus2n2** [comment]
Fixed it, it seems it didn't like me having both python 2 and 3 installed (cos not everything support 3 lol).
What I ended up doing was changing the file name for both python installs to python2 & python3 and then ran requirements script again use both version and it now seems to work :D

**Comment by mdhiggins** [comment]
What was the error? Manual.py should work just fine with python2 or python3 so I'm curious what you were seeing

**Comment by morpheus2n2** [comment]
think it was just a missing dependency install, not 100% which though sorry. All I remember was it did a traceback and said about a error at line 10 import enum and it couldn't find enum.
