### ISSUE TITLE
Noticed a problem with the readme

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1247]
On the readme under Deluge it says to use either the .py or .bat but there is not mention on how to make said .bat nor is it included in the script :D

**Comment by mdhiggins** [comment]
Batch files are a basic functionality included with windows and the script is designed with some basic knowledge assumed.

Additionally the batch file needs to be custom tailored to your file paths so including one wouldn't work as a universal solution anyway

An example

```
C:\python\python3.exe C:\SMA\delugePostProcess.py %1 %2 %3
```
