### ISSUE TITLE
Since moving over to Python3 build this is what I get a lot

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1248]
Up until yesterday I have been using the script on python 2, last time I downloaded the script was in December. 
Since I pull the newest build and updated everything this is what I get 9 times out of 10 now when I run the manual script.

This has never been a problem before and doesn't seem to happen if its called via SABnzbd to post process why is this suddenly happening?

```
Input #0, matroska,webm, from 'c:\converter\new folder\Young.Justice.S03.1080p.BluRay.x264-W4F[rartv]\Young.Justice.S03E26.1080p.BluRay.x264-W4F.mkv':

  Metadata:

    encoder         : libebml v1.3.9 + libmatroska v1.5.2

    creation_time   : 2019-11-30T05:40:41.000000Z

  Duration: 00:23:55.94, start: 0.000000, bitrate: 8664 kb/s

    Chapter #0:0: start 0.000000, end 162.037000

    Metadata:

      title           : Chapter 01

    Chapter #0:1: start 162.037000, end 680.221000

    Metadata:

      title           : Chapter 02

    Chapter #0:2: start 680.221000, end 1378.335000

    Metadata:

      title           : Chapter 03

    Chapter #0:3: start 1378.335000, end 1435.935000

    Metadata:

      title           : Chapter 04

    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

    Metadata:

      BPS-eng         : 7152727

      DURATION-eng    : 00:23:55.935000000

      NUMBER_OF_FRAMES-eng: 34428

      NUMBER_OF_BYTES-eng: 1283856490

      _STATISTICS_WRITING_APP-eng: mkvmerge v37.0.0 ('Leave It') 64-bit

      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-30 05:40:41

      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)

    Metadata:

      BPS-eng         : 1508999

      DURATION-eng    : 00:23:55.926000000

      NUMBER_OF_FRAMES-eng: 134618

      NUMBER_OF_BYTES-eng: 270851416

      _STATISTICS_WRITING_APP-eng: mkvmerge v37.0.0 ('Leave It') 64-bit

      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-30 05:40:41

      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

[AVHWDeviceContext @ 000002397d528240] Failed to create Direct3D device

Device creation failed: -1313558101.

[h264 @ 000002397cc2e580] No device available for decoder: device type dxva2 needed for codec h264.

Stream mapping:

  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))

  Stream #0:1 -> #0:1 (dts (dca) -> aac (native))

  Stream #0:1 -> #0:2 (dts (dca) -> aac (native))

Device setup failed for decoder on input stream #0:0 : Unknown error occurred


2020-05-17 03:23:06 - MANUAL - ERROR - c:\converter\new folder\Young.Justice.S03.1080p.BluRay.x264-W4F[rartv]\Young.Justice.S03E26.1080p.BluRay.x264-W4F.mp4 deleted.
2020-05-17 03:23:06 - MANUAL - ERROR - There was an error processing file c:\converter\new folder\Young.Justice.S03.1080p.BluRay.x264-W4F[rartv]\Young.Justice.S03E26.1080p.BluRay.x264-W4F.mkv, no output data received
```

**Comment by mdhiggins** [comment]
This has nothing to do with python 2, its an FFMPEG error
You didn't actually post the command or options that were generated so I have to speculate a little bit but since its a direct3d decoder that's failing I'm thinking you need to turn that feature off in autoProcess.ini

By default now the script reads which encoders/decoders your build of FFMPEG has available and compares that against the allowed encoders/decoders in your autoProcess.ini file as an effort to enable hardware

To turn this feature off just remove all the options for `hwaccels` and `hwaccel-decoders`

These are the defaults
```
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
```

Change to 
```
hwaccels =
hwaccel-decoders =
```

If you haven't updated in a while the python3 conversion was a very small change (everything was python3 compatible for years) but there has been a complete rewrite of many core features to add new options and increase customization so don't assume the python version change is the culprit

**Comment by morpheus2n2** [comment]
That's what I thought and why I couldn't make since of it as it was never a issues before, must be the current static build of ffmpg that's an issues as the older version of that was working fine lol

**Comment by mdhiggins** [comment]
Current build must just support it so its passing through but your hardware must not, so just remove it from the list and you should be good to go

**Comment by morpheus2n2** [comment]
Will, do it works fine on my other devices its just the laptop I having sitting in the cupboard processing my library that had this issues pmsl, thanks for the help :D

**Comment by morpheus2n2** [comment]
@mdhiggins Done a bit more playing around seems I can get it to use hardware decoding/encoding on its first use but when it then moves on to the next file it kicks out that error 100% of the time, so I have a feeling that ffmpeg is not releasing the GPU in time for the next use grrr, oh well will just have to use the super slow CPU decoding lmao

**Comment by mdhiggins** [comment]
I can’t say I’ve seen that issue. Try a different build of FFMPEG and see if that helps.
