### ISSUE TITLE
Audio setup

### ISSUE THREAD

**Issue by Zachar2** [mdhiggins/sickbeard_mp4_automator#1249]
With all the recent changes in mind, what are the proper settings to have just one audio stream? Let's say I just want to keep Universal Audio (2 channels, aac) and leave out the rest.

**Comment by mdhiggins** [comment]
Universal audio always aims to create an extra stream so that’s probably not ideal. Just use the general audio options but set codec and max channels.

**Comment by Zachar2** [comment]
Is it possible to disable Universal Audio then? I couldn't find a way to do it so far.

**Comment by mdhiggins** [comment]
Yep. Just don’t put any codecs

**Comment by Zachar2** [comment]
Thank you. Have a nice evening :)
