### ISSUE TITLE
4k slow processing and how to view status of current automated MP4 conversions happening on the backend

### ISSUE THREAD

**Issue by infamouswb** [mdhiggins/sickbeard_mp4_automator#1250]
I am running Ubuntu 16.04 and have automation running fine and working normally expect to when it comes to content higher then 1080P.

Is there any command I can run to see whats happening on the back end for the automator?

Anything I can do that could speed up processing on 4k content?

Thanks for this amazing code!

**Comment by mdhiggins** [comment]
The biggest thing you can do to improve speeds is to do whatever you can to remux the video track. Any video encoding is going to substantially increase the time things take and 4K will be the longest. Transcoding is very CPU intensive and will take a very long time regardless of your CPU. Most FFMPEG encoders don’t use multi core threads very efficiently so you probably won’t see anywhere near 100% usage. 

Quality will also add time. Audio tracks add time. Hard drive speeds matter too. It’s all cumulative. 

If you need to encode though you need to encode. 

You can potentially use hardware acceleration if you have a CPU or GPU that supports it. Read up on FFMPEG hardware acceleration and set your first video codec to one of the hardware enabled 
Codecs. 

As far as monitoring progress, that depends on what’s executing things but you usually have to look at those programs logging

**Comment by infamouswb** [comment]
> The biggest thing you can do to improve speeds is to do whatever you can to remux the video track. Any video encoding is going to substantially increase the time things take and 4K will be the longest. Transcoding is very CPU intensive and will take a very long time regardless of your CPU. Most FFMPEG encoders don’t use multi core threads very efficiently so you probably won’t see anywhere near 100% usage.
> 
> Quality will also add time. Audio tracks add time. Hard drive speeds matter too. It’s all cumulative.
> 
> If you need to encode though you need to encode.
> 
> You can potentially use hardware acceleration if you have a CPU or GPU that supports it. Read up on FFMPEG hardware acceleration and set your first video codec to one of the hardware enabled
> Codecs.
> 
> As far as monitoring progress, that depends on what’s executing things but you usually have to look at those programs logging

Thank you! I will take a look, at the hardware acceleration. As far as monitoring, I was hoping there could be a dashboard (nothing crazy) for sickbeard_mp4_automator where you can view the current progresses of all ongoing conversions by file name and % complete and whats pending, that would be really cool! I don't code, so I can do is dream :)

**Comment by mdhiggins** [comment]
No such thing exists. It’s a collection of extensions scripts that integrate with other software and has no persistence or front end. Not something that is planned for development as it would be a substantial about of work and the script set is designed for integration into other software that already has front ends.
