### ISSUE TITLE
Xvids not encoding 

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1253]
hello. this used to encode Xvids at 1 point. but the past few days i have noticed it asn't been. here is a pastebin of some of the log. 
if you need more info. let me know please.

https://pastebin.com/T0zMm3fk

**Comment by mdhiggins** [comment]
Log is incomplete and doesn't include the actual FFMPEG error

But it appears to be a decoder error. Turn off the hardware decoders and see if this fixes things by setting your `hwaccels` and `hwaccels-decoders` to blank

Looks like its trying to use CUVID

```
hwaccels =
hwaccel-decoders =
```

**Comment by pazport** [comment]
ye i deleted all that was in 

``hwaccels =``
``hwaccel-decoders =`` 

and it started to work. will this be because my server is an intel. and probably doesn't have HW on it

**Comment by mdhiggins** [comment]
Yeah probably
