### ISSUE TITLE
TrueHD + mp4 conversion

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#1254]
As I see in the wiki, and on numerous threads, MP4 doesn't support TrueHD. I also get that releases will  usually have a TrueHD audio stream, followed by the AC3 copy. But I have a few releases that don't have that present, and only have the TrueHD. Is it possible we could force conversion of the TrueHD if "ignore-truehd" is set to "false" or "convert", or just left blank?

As it currently stands, if I make that option blank, and it is set to convert to mp4, it will error out.

> 2020-05-25 20:06:27 - resources.mediaprocessor - INFO - Audio detected for stream 1 - truehd eng 6 channel.
> 2020-05-25 20:06:27 - resources.mediaprocessor - ERROR - Unable to generate options, unexpected exception occurred.
> Traceback (most recent call last):
>   File "D:\sickbeard_mp4_automator\resources\mediaprocessor.py", line 103, in process
>     options, preopts, postopts, ripsubopts, downloaded_subs = self.generateOptions(inputfile, info=info, original=original)
>   File "D:\sickbeard_mp4_automator\resources\mediaprocessor.py", line 503, in generateOptions
>     if a.codec == 'truehd' and self.settings.output_extension in self.settings.ignore_truehd:
> TypeError: argument of type 'NoneType' is not iterable
> 2020-05-25 20:06:27 - RadarrPostProcess - INFO - Processing returned False.
> 2020-05-25 20:06:27 - RadarrPostProcess - ERROR - Error processing file
> Traceback (most recent call last):
>   File "D:\sickbeard_mp4_automator\postRadarr.py", line 153, in <module>
>     sys.exit(1)
> SystemExit: 1

This causes Radarr to immediately import the original mkv into the library, something I'm not wanting. Any help on this would be awesome. Thanks!

**Comment by mdhiggins** [comment]
The ignore-truehd option should be set to a list of extensions for which to ignore any truehd tracks (like mp4 which doesn't support that codec). There was a bug where you could get that error if it was set to '' (blank) which was causing your issue here which I just pushed an update to fix

c3accc90aa3055b93e71c4f60e792e212996301a

TrueHD is otherwise treated like any other audio track so it will encode if its not on your codec list and ignore is not enabled. The ignore option also includes a check to make sure that TrueHD is not the only audio track, so in theory it should prevent the situation you're having above.

The update I linked should fix the error though. If you could media info for the file that was giving you trouble (either ffprobe -show_streams or manual.py -oo) that would be helpful for debugging

**Comment by DatsiK96** [comment]
Here's the media info. I updated the mp4_automator to the latest, and indeed the error has gone away, and it is now encoding. I do not know what it's doing with the audio stream that was TrueHD yet.

```
General
Complete name                            : \\Path\Movie.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 21.8 GiB
Duration                                 : 1 h 43 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 30.3 Mb/s
Encoded date                             : UTC 2013-12-29 21:58:04
Writing application                      : mkvmerge v6.5.0 ('Isn't she lovely') built on Oct 20 2013 12:50:05
Writing library                          : libebml v1.3.0 + libmatroska v1.4.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 43 min
Bit rate mode                            : Variable
Maximum bit rate                         : 36.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Duration_Source                          : General_Duration

Audio #1
ID                                       : 2
Format                                   : MLP FBA
Format/Info                              : Meridian Lossless Packing FBA
Commercial name                          : Dolby TrueHD
Codec ID                                 : A_TRUEHD
Duration                                 : 1 h 43 min
Bit rate mode                            : Variable
Maximum bit rate                         : 5 841 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Compression mode                         : Lossless
Language                                 : English
Default                                  : Yes
Forced                                   : No
Duration_Source                          : General_Duration

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 43 min
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 165 MiB (1%)
Title                                    : English Actor Commentary
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Duration_Source                          : General_Duration
```

It currently shows 3 audio streams in the conversion log. One is a universal audio, but looks like it didn't choose the commentary for that stream, so that's good.

```
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "samplerate": null,
            "filter": null,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo",
            "debug": "universal-audio"
        },
        {
            "map": 1,
            "codec": "aac",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        },
        {
            "map": 2,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "-default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo (Commentary)",
            "debug": "universal-audio"
        }
```

I'll let you know the final results when it's done. Thanks for the quick turn around on this! :)

**Comment by mdhiggins** [comment]
It looks like based on that file the reason the usual TrueHD audio check was failing was because there was that extra commentary track. I pushed a small update that makes the TrueHD replacement check more rigorous; isn't of just checking for any other audio track if looks for a track of similar language and channels as the backup.

1953e4f7ffaaf4459adb47c3f36c20c76787cc9b

**Comment by DatsiK96** [comment]
Well, that update seems to have fixed it, or atleast in terms of what I was looking for... With that option left blank, it looks to have converted it to a stereo copy(not intended on my part, but it's cool either way), while also leaving the 6.1 channel version in there. Not sure if it converted it to aac or whatnot. But it's working with it as blank for me.

Awesome work man, really appreciate everything you've done!

**Comment by mdhiggins** [comment]
The stereo track is due to the universal audio option enabled (and the other one is the commentary track). That can be disabled if you don't want the extra stereo track by not setting a codec in the universal audio section of the config
