### ISSUE TITLE
Forced track flag not carried over

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1255]
Hello,

I'm converting files that have forced subtitle tracks but the converted files never have that flag carried over?

[sma.log](https://pastebin.com/raw/hSnsNbuB)
[autoProcess.ini](https://pastebin.com/raw/5umYRzD0)

**Comment by mdhiggins** [comment]
Looks like its carried over

```
    "subtitle": [
        {
            "map": 3,
            "codec": "copy",
            "language": "eng",
            "encoding": "",
            "disposition": "+default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired",
            "title": "Forced",
            "debug": "subtitle.embed-subs"
        },
```

Its there in the output settings generated

**Comment by Smalfinn** [comment]
I know it appears to handle it but looking at the media info for the before and after it didn't change the flag, just changes the tracks name...

[Orginal](https://prnt.sc/so6lic) and [Output](https://prnt.sc/so6n5o)

**Comment by mdhiggins** [comment]
Looks like this was in fact a bug where the commands were generated but due to a variable name error weren't getting passed to FFMPEG at the last step. Should be fixed now

f8238d761f7ddb42155905a66ea167271ba16bab
