### ISSUE TITLE
Feat request: Keeping the title of embedded subs, or add one similar to how Audio is tagged.

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1258]
The automatic embedded titling seems to work very well for Audio tracks, but subtitles are not currently treated in the same manor.

Example, before:

![image](https://user-images.githubusercontent.com/8386416/83459165-dad58300-a431-11ea-851f-010442ffb5cc.png)

After:

![image](https://user-images.githubusercontent.com/8386416/83459275-0b1d2180-a432-11ea-9fa8-c4212997ac29.png)

As you can see, you cannot tell the difference in the second image between the two subtitle tracks. These images are using MKV as the output, but same would apply to MP4

**Comment by RandomNinjaAtk** [comment]
This could also be useful for MP4, if your not burning in forced subs, you could title the track as Forced English or something to that effect, and tag it as the default. That way players like VLC, will show it correctly on the subtitle selection menu  and possibly enable it automatically because its set to the default track.

Just a thought...

**Comment by mdhiggins** [comment]
This is already implemented
```
    def subtitleStreamTitle(self, disposition):
        output = ""
        if disposition.get("forced"):
            output += "Forced "
        if disposition.get("hearing_impaired"):
            output += "Hearing Impaired "
        if disposition.get("comment"):
            output += "Commentary "
        if disposition.get("visual_impaired"):
            output += "Visual Impaired "
        if disposition.get("dub"):
            output += "Dub "
        return output.strip()
```

**Comment by mdhiggins** [comment]
It uses the disposition flags of the source file

Additionally if disposition flags are not set in the source file it will attempt to guess them based on an included title if present
