### ISSUE TITLE
ffmpeg preset configuration option

### ISSUE THREAD

**Issue by automator0** [mdhiggins/sickbeard_mp4_automator#1260]
Maybe i missed it, but is there an option to configure presets in the script? As indicated below

https://trac.ffmpeg.org/wiki/Encode/H.264

ultrafast
superfast
veryfast
faster
fast
medium – default preset
slow
slower
veryslow
placebo

I assume that it will use the medium preset by default if it is not flagged in the ffmpeg command?

**Comment by mdhiggins** [comment]
There's not a dedicated option for this but you can use the preopts (or postops, forget exactly where FFMPEG likes the preset to be defined, I think preopts) to inject additional options. Just ensure you comma separate them
`preopts = -preset, ultrafast`

**Comment by mdhiggins** [comment]
Actually found some examples its probably `postopts` that you should use
