### ISSUE TITLE
Issue tagging file

### ISSUE THREAD

**Issue by djs4000** [mdhiggins/sickbeard_mp4_automator#1261]
Hi, i just upgraded from the old version and I can't get the file tagging to work. Everything else is working flawlessly.

Trying to write tags.
There was an error writing the tags.
Traceback (most recent call last):
  File "/opt/mp4_automator/resources/metadata.py", line 206, in writeTags
    video.save()
  File "/opt/mp4_automator/mutagen/_file.py", line 111, in save
    return self.tags.save(filename, **kwargs)
  File "/opt/mp4_automator/mutagen/mp4/__init__.py", line 360, in save
    values.append(render_func(self, key, value))
  File "/opt/mp4_automator/mutagen/mp4/__init__.py", line 578, in __render_freeform
    data += v.encode('UTF-8')
AttributeError: 'bytes' object has no attribute 'encode'
Relocating MOOV atom to start of file.

**Comment by RandomNinjaAtk** [comment]
Did you make sure all of your pip packages are up-to-date? If you did not upgrade them, you should try that first.

**Comment by mdhiggins** [comment]
Looks like you actually have the old mutagen directory. You should delete that (and probably wipe the whole directory minus your config and do a clean install in case there are other left overs) and install the mutagen package via PIP

**Comment by djs4000** [comment]
> Looks like you actually have the old mutagen directory. You should delete that (and probably wipe the whole directory minus your config and do a clean install in case there are other left overs) and install the mutagen package via PIP

Ah, thanks, That was the issue. Installed in the same location but didnt clear the folders and the mutagen dir was still there.
