### ISSUE TITLE
Script with GPU on Linux

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1262]
I'm looking to use the script on a dedicated GPU (GeForce GT 710 1 GB), but my question before signing a dedicated one is whether the script uses the GPU and CPU in a Linux environment?

**Comment by mdhiggins** [comment]
Full FFMPEG hardware acceleration is supported for both encoding and decoding. See the hwaccels and hwaccel-decoders settings in addition to the various types of accelerated codecs that can be found in the avcodecs.py file

**Comment by andrerxavier** [comment]
Thank you!

**Comment by mdhiggins** [comment]
No prob, there's a couple good 'issues' that have been closed that may be helpful if you have any questions on github; otherwise if you run into errors or something just post

Make sure your build of FFMPEG is compiled with hardware acceleration support whenever you do get started
