### ISSUE TITLE
Reading subtitle streams performance

### ISSUE THREAD

**Issue by dingho** [mdhiggins/sickbeard_mp4_automator#1264]
I recently updated to python 3.8 and the latest master version of SMA, I was previously running on python 2.7 (and I don't know what the previous version was, but I still have the files so could find out if instructed).

The reading of the subtitle streams is taking much longer, even though I have only ENG, in the autoprocess.ini.

Previously: 
`2020-06-03 12:27:20 - MANUAL - INFO - Subtitle detected for stream #7: subrip [ger].
2020-06-03 12:27:20 - MANUAL - INFO - Subtitle detected for stream #8: subrip [gre].
2020-06-03 12:27:20 - MANUAL - INFO - Subtitle detected for stream #9: subrip [spa].
2020-06-03 12:27:20 - MANUAL - INFO - Subtitle detected for stream #10: subrip [spa].
2020-06-03 12:27:20 - MANUAL - INFO - Subtitle detected for stream #11: subrip [fin].`

And now, around 3 minutes each:
`2020-06-11 09:52:04 - MANUAL - INFO - Text-based subtitle detected for stream 5 - subrip fra.
2020-06-11 09:54:58 - MANUAL - INFO - Text-based subtitle detected for stream 6 - subrip heb.
2020-06-11 09:58:23 - MANUAL - INFO - Text-based subtitle detected for stream 7 - subrip por.
2020-06-11 10:01:08 - MANUAL - INFO - Text-based subtitle detected for stream 8 - subrip spa.`

My subtitle section for reference:
`[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = True
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec =`
Any ideas what I may be doing wrong?  Thank you.

**Comment by mdhiggins** [comment]
3 minutes each sounds excessive. The analysis of subtitles does take a bit longer and has nothing to do with python versions. Because the script now supports image based subtitles in a dynamic way for each stream it does a small FFMPEG task to determine if its image based or note, this is probably why its taking longer. Are you running on very slow hardware? One option might be to try to update your version of FFMPEG and see if that helps

On my desktop on test files with 20 subtitle tracks it still only takes a minute total to get through them all

But that's probably where the new performance hit is coming from

**Comment by mdhiggins** [comment]
007b6be0b97cdd6ede69e194fccc063e1cb97ef6

I tried limiting that task to a 00:00:01 second length (not transcode time but stream length). See if that has any performance impact by updating and retesting

**Comment by SudoUser-Sam** [comment]
I can also reproduce this extremely slow processing with large amount of subtitles, But only on linux windows 10 it had no delay what so ever same python version, same hardware.

I will test the most recent commit and get back to you.

**Comment by mdhiggins** [comment]
I run my server on linux and do all my development and testing on windows and haven't noticed this in either environment but hopefully that commit will help improve performance

**Comment by dingho** [comment]
Thank you.  That seems to have done it.  I tested it on 2 different files successfully.

`2020-06-12 08:17:23 - MANUAL - INFO - Text-based subtitle detected for stream 5 - subrip fra.
2020-06-12 08:17:23 - MANUAL - INFO - Text-based subtitle detected for stream 6 - subrip heb.
2020-06-12 08:17:23 - MANUAL - INFO - Text-based subtitle detected for stream 7 - subrip por.
2020-06-12 08:17:23 - MANUAL - INFO - Text-based subtitle detected for stream 8 - subrip spa.`

**Comment by mdhiggins** [comment]
Sweet, thanks for following up and glad that improved performance
