### ISSUE TITLE
Manual Input/Auto parameters not working after updating

### ISSUE THREAD

**Issue by lovemonkeyz** [mdhiggins/sickbeard_mp4_automator#1266]
Hadn't pulled a new build of the mp4 automator in a year, figured it was time to grab a new one, and also update to Python 3+ instead of 2.7 that I'd been running, and noticed that when running manual.py with input and auto parameters, it's still asking for path and confirmation for guessit to tag the file.

I tried uninstalling python entirely (all versions), cleaned up their folders, deleted the mp4 automator folder and reinstalled everything, but that didn't help. Anyone who can help me figure out what's wrong? 

```
Manual.py -i .\Downloads -a
Manual processor started.
Python 64-bit 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)].
Guessit version: 3.1.1.
C:\Python38\python.exe
Loading config file C:\sickbeard_mp4_automator\config\autoProcess.ini.

> Enter path to file:
#: .\Downloads
Processing file .\Downloads\Funny.People.2009.mp4
Matched movie title as: Funny People 2009-07-31 (TMDB ID: 20829)
> Proceed using guessed identification from filename?
# [y/n]: y
```

**Comment by mdhiggins** [comment]
It actually looks like no python arguments are being passed (notice the input failed too). I suspect this is a python problem that happens with windows sometimes.

https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t

Check and see if any of those solutions fix things

**Comment by lovemonkeyz** [comment]
Thanks mdhiggins, had to add %* to HKEY_CLASSES_ROOT\Applications\python.exe\shell\open\command and it started working.
