### ISSUE TITLE
Subtitle issue

### ISSUE THREAD

**Issue by SudoUser-Sam** [mdhiggins/sickbeard_mp4_automator#1267]
On windows image based subs are being identified as SRT but are still copied properly, on linux they are being forced to SRT and stall.

Both are on the most recent commit, both using the same python version and same ffmpeg version and both have the same autoprocess.ini except the ffmpeg and ffprobe location.

Linux config: https://pastebin.com/tCeXR4QH

Windows config: https://pastebin.com/4YK4bL0R

Here is a video of them both side by side using the same file, windows is instant where linux takes insanely long i have no idea how long it actually takes because i usually cancel it like in the video.

edit: idk why the streamable video looked so horrible here is a updated direct download link to it

https://www.mediafire.com/file/el2z4gtugt9afgx/sc8MvY8s0u.mp4/file

**Comment by SudoUser-Sam** [comment]
Sample of the file used in the video: https://www.mediafire.com/file/urq1sl2cniajnrs/Speed_Racer-001.mkv/file

**Comment by mdhiggins** [comment]
So I don't actually think its getting stuck scanning the internal subs, its getting stuck on the next step which is scanning for external subs. I think that may be because it recursively looks in all subdirectories too and depending on which folder you scan that may be a huge list.

Additionally, that debug line regarding what subtitle its creating is wrong

760a11cf08950206a014857923d24e8ee707946e

Try this update, I removed the recursive nature of the directory scan which really didn't need to be there anyway. I fixed the debugging printing as well.

**Comment by SudoUser-Sam** [comment]
i saw your recent commit and i think dvd vob subs are identified as 'dvd_subtitles' not 'dvdsub' unless this is some other completely other codec. 

![image](https://user-images.githubusercontent.com/25883052/84580309-a3989780-ad8a-11ea-88af-049ba91a5403.png)

![image](https://user-images.githubusercontent.com/25883052/84580393-71d40080-ad8b-11ea-9eff-e7f413d76939.png)


But with the most recent commit it is working flawlessly for that test file I appreciate the fix.

**Comment by mdhiggins** [comment]
What FFMPEG reports and what it uses for its encoder name are often (and frustratingly) not the same
In this case the encoder for dvd subtitles is `dvdsub`

```
 S..... dvdsub               DVD subtitles (codec dvd_subtitle)
```

**Comment by SudoUser-Sam** [comment]
gotcha, thanks again!

**Comment by SudoUser-Sam** [comment]
wait, so in the ini file do i put dvdsub or dvd_subtitles? 

I think it would probably be a good idea to list a set of supported subtitle codec and their proper name so people dont get confused like i easily did.

**Comment by mdhiggins** [comment]
0542bc716421e61cfa769fcddb9e75ecdae0ddfe
8596e80139d60b83f9208d7d5ae69fbfeea3585b

Made a couple tweaks to the previous change to have alt classes inherit from each other

Having alt classes allows you to use either

Make sure I didn't break anything

Most important thing is that if you want things to 'copy' you need to include whatever ffprobe reads the stream as, and sometimes that's different than your encoding codec. For example, with hardware encoders you might use h264qsv but still want h264 to copy, so it would be

`codec = h264qsv, h264`

All the supported codecs can be found in avcodecs.py

**Comment by mdhiggins** [comment]
Added an option to manual.py that prints all the supported codecs and what FFMPEG encoders they resolve to

64cb83daf9fde88e8254b2482d4ea5f075f67248
