### ISSUE TITLE
Not an issue just wondering :D

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1268]
Just wondering if there is a way to have it force a bit rate, I have noticed that if any thing is under my set bitrate it will keep the lower rate which is a pain if I have to convert a low bitrate x265 to x264

**Comment by mdhiggins** [comment]
In those situations you're much better off using CRF or CRF-Profiles instead of a coded bitrate as its tough to predicate and know an equivalent bitrate exchange

**Comment by morpheus2n2** [comment]
Ahh ok cool thank you :D
