### ISSUE TITLE
api calls to sonarr and radarr

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1269]
hello. i did a recent pull of your update mate. and since yesterday, it fails sometimes to send a signal to sonarr. but then sometimes it works. before this update of yours. i had no problems with the ARR'S. only since i updated yesterday. i have posted screen shots too mate.
<img width="464" alt="Untitled" src="https://user-images.githubusercontent.com/46929183/85207112-8762a080-b31e-11ea-9eb2-bebe7add1644.png">
<img width="589" alt="Untitled2" src="https://user-images.githubusercontent.com/46929183/85207115-8893cd80-b31e-11ea-9572-c3969557f142.png">

**Comment by mdhiggins** [comment]
Not really enough information to debug this in any effective manner
If Sonarr's API isn't responding intermittently that would potentially cause this but that's more of a Sonarr issue. Is there any info in Sonarr's logs when these calls fail to suggest why? 

There haven't been any changes to this part of the script in a while, would need to know when you updated for that to be relevant, only a few setting/filepath adjustments which wouldn't impact this, the last change to the API call was in 2018

**Comment by mdhiggins** [comment]
Additionally if you can set your logging level to DEBUG in logging.ini you can probably get more logging information that might help

I also pushed another debug log call of rstate that would help debug this further

130690767e1bf8a8423f2007d9ba20493328c617

**Comment by pazport** [comment]
all i can see in DEBUG for sonarr is 
```20-6-20 22:06:26.2|Debug|QualityParser|Trying to parse quality for Sing.Yesterday.For.Me.E12.1080p.WEB.H264-URANiME
20-6-20 22:06:26.2|Debug|Parser|Quality parsed: WEBDL-1080p v1
20-6-20 22:06:26.2|Debug|Parser|Release Group parsed: URANiME
20-6-20 22:06:26.2|Debug|ParsingService|Using Scene to TVDB Mapping for: SING "YESTERDAY" FOR ME - Scene: 1x12 - TVDB: 1x12
20-6-20 22:06:26.5|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-6-20 22:06:26.5|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-6-20 22:06:26.6|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-6-20 22:06:26.7|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
20-6-20 22:07:26.1|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-6-20 22:07:26.3|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
20-6-20 22:07:56.0|Debug|SabnzbdProxy|Url: http://sabnzbdtv:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
20-6-20 22:07:56.0|Debug|SabnzbdProxy|Url: http://sabnzbdtv:8080/api?mode=history&start=0&limit=30&category=tv&apikey=(removed)&output=json``

and for mp4automator. i checked logs. and it just says that the api is wrong. to check sonarr and make sure it is working. i have changed the api in sonarr. and restarted. it as only started since. i pulled your new update mate.

**Comment by mdhiggins** [comment]
Yeah that error comes when Sonarr doesn't respond to its API query. Try the update and rerun and if it fails post the sonarr log and the sma.log entry with debugging enabled. Otherwise its probably a sonarr issues cause its just a standard API call so maybe sonarr is frozen and its API isn't responding

**Comment by pazport** [comment]
ye it was a sonarr problem mate. i had to kill sonarr and restart it a few times. my bad mate. sorry for this mat :)
