### ISSUE TITLE
manual.py fails with 32 bit python

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#127]
Great script...works great for all of the files under 2gb but gives the following error when the file is larger:

Trying to write tags
An unexpected error occurred, processing of this file has failed
cannot fit 'long' into an index-sized integer

I understand that a fix would be to update python to 64bit but since i'm running this from my armv71 NAS, I cannot run any higher than 32 bit...could there be another fix to it?

**Comment by mdhiggins** [comment]
As of commit 8375e799c53cfa9a0d87d62cccf747072875ee97 a workaround for this issue has been found and tagging should work on 32 bit systems regardless of file size
