### ISSUE TITLE
No guessit.transformer extensions found

### ISSUE THREAD

**Issue by laryan61** [mdhiggins/sickbeard_mp4_automator#1271]
Fresh install of script. After installing requirement and running for the first time I get this error.

Traceback (most recent call last):
  File "./manual.py", line 5, in <module>
    import guessit
  File "/usr/lib/python3/dist-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/lib/python3/dist-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/lib/python3/dist-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/lib/python3/dist-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/lib/python3/dist-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/lib/python3/dist-packages/stevedore/extension.py", line 261, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found

I've tried the fix found at https://github.com/mdhiggins/sickbeard_mp4_automator/issues/643, but still getting same error.

**Comment by mdhiggins** [comment]
What version of stevedore and guessit do you have installed?

**Comment by mdhiggins** [comment]
Also wondering if you got that this fixed on your own since you had the error with tmdbsimple (https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1272) which is an import a few lines down

**Comment by laryan61** [comment]
Thanks for the quick response. I had just commented out tmdbsimple to get "around" that error and test the other requirements.

I'm building a dedicated box to encode a large number of video files. I've been using my own (crude) script, yours is MUCH MORE elegant. Part of this project is building ffmpeg with nvenc support, but discovered the build script I was using was limited to Mint 19.1. My system was 19.3 and it wasn't working, so I've wiped drive and started over with 19.1.

So I can't provide version number at the moment. Or if the new build might "fixed" the errors, but I'll be able to retry your script later today.

**Comment by mdhiggins** [comment]
This error is probably from an old version of guessit so just reopen if updating to the latest doesn’t resolve it.

**Comment by laryan61** [comment]
I've gotten my new Linux Mint 19.1 box built. Working on getting your script installed for me to us. After installing the requirements. I'm still getting the same error above "stevedore.exception.NoMatches: No guessit.transformer extensions found" I have the following versions installed.

stevedore-1.32.0
GuessIt 3.1.2.dev0 

Thanks for any assistance you could provide.

**Comment by mdhiggins** [comment]
Those versions should be ok. I'm betting you have multiple python environments and the one that's actually being executed is using an older version or either guessit or stevedore. The versions you've listed should be compatible (though admittedly I've only tested up to guessit 3.1.1 I doubt a small dev release would cause this). The biggest clue here is that you also weren't able to import tmdbsimple which I assume if you went through all the requirements you installed. 

My guess is whatever environment the pip command you're using to install the dependencies isn't the same environment that's being used to execute your script. 

If you're using the operating system's installation of python that can get tricky as some operating systems use multiple versions and have multiple environments preinstalled. The safest and recommended way to do things these days is to have everything installed in its own python virtual environment

**Comment by laryan61** [comment]
I've gotten the errors related to guessit and tmdbsimple resolved.

I have another issue. ModuleNotFoundError: No module named 'mutagen'

Suggestions to resolving this one?

**Comment by mdhiggins** [comment]
Gotta install mutagen

Any time you have a 'ModuleNotFoundError' the answer is always to install that module in the environment you're operating in

**Comment by laryan61** [comment]
Yep. Sorry. I wasn't typing it in correctly. Right after I sent by last reply, I tried again, this time spelling everything correctly and it found and installed the module. The manual.py script is now executing without errors. At least up to the point its asking for a filename.

**Comment by laryan61** [comment]
I've gotten your manual.py script to run without errors. Previously when I used my own hacked together script I used the ffmpeg option "-af volume=5dB" to increase the  audio stream during conversion. Which when watching the stream via Plex, Roku, phones, tablets, etc. The extra volume is much appreciated. When I tried to add this to autoProcess.ini

postopts = -af:volume=5dB

I got the following error message.
Filtergraph 'volume=5db' was defined for audio output stream 0:1 but codec copy was selected.
Filtering and streamcopy cannot be used together.

Maybe as a feature request, the option to adjust the volume?

**Comment by mdhiggins** [comment]
This is already supported. What you're doing is injecting an audio filter which can be done using the `filter` option which is available for audio, universal audio, and video. If you want to prevent copying in streams that otherwise meet copy criteria set the `force-filter` option to true to universally apply that filter, though you will lose the efficiency of remuxing as a result
