### ISSUE TITLE
Missing module tmdbsimple

### ISSUE THREAD

**Issue by laryan61** [mdhiggins/sickbeard_mp4_automator#1272]
When running manual.py, I get the following error message.

File "./manual.py", line 12, in <module>
    import tmdbsimple as tmdb
ModuleNotFoundError: No module named 'tmdbsimple'

**Comment by mdhiggins** [comment]
Feel like I shouldn't have to ask this but did you install tmdbsimple?
This is a basic python error when you haven't installed the module

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1237
