### ISSUE TITLE
Feature Request: Enable TrueHD audio support for MP4

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1277]
ffmpeg 4.3 introduced TrueHD audio support for MP4 container

Relevant changelog info: https://fossies.org/linux/ffmpeg/Changelog

Relevant ffmpeg ticket for change: https://trac.ffmpeg.org/ticket/8051

**Comment by mdhiggins** [comment]
Fortunately I prepared for this and ignoring true HD isn't hard coded anymore, to include just remove the blocked extensions
`ignore-truehd = mp4, m4v`

**Comment by RandomNinjaAtk** [comment]
I believe I tried removing it and it did not work, still transcoded to eac3, even When configured with truehd. Because I wanted to test that first. But I’ll have try and look at it again when I have some more free time.

**Comment by mdhiggins** [comment]
Works fine on my end
Make sure you include truehd on your codec list and make sure you don't have a max channel that's causing it to convert

**Comment by RandomNinjaAtk** [comment]
Ah, max channel was probably it. Maybe a bug fix
Is needed with that in regards to eac3... eac3 only supports 6 channel. If you don’t set a max, it will fail to transcode because it will try for more channels then is allowed. Which is not an issue, for ac3 I believe.

**Comment by mdhiggins** [comment]
EAC3 should support up to 8 channels and there is logic built into the script to lower channels down if they exceed the max
```
class EAc3Codec(AudioCodec):
    """
    Dolby Digital Plus/EAC3 audio codec.
    """
    codec_name = 'eac3'
    ffmpeg_codec_name = 'eac3'

    def parse_options(self, opt, stream=0):
        if 'channels' in opt:
            c = opt['channels']
            if c > 8:
                opt['channels'] = 8
        if 'bitrate' in opt:
            br = opt['bitrate']
            if br > 640:
                opt['bitrate'] = 640
        return super(EAc3Codec, self).parse_options(opt, stream)
```

Nearly all of the audio codecs have a similar max channel check

**Comment by RandomNinjaAtk** [comment]
ffmpeg is only capable of encoding eac3 as 6 channel.

Here is the open ticket requesting to enable greater than 6 channel support.

https://trac.ffmpeg.org/ticket/3595

If you set it to anything greater then 6 ffmpeg will error out. That’s why a hard coded limitation is needed. AC3 doesn’t error out the same way...

**Comment by mdhiggins** [comment]
9c480a9921c215d6f243896d18bf6f33913f294a

**Comment by RandomNinjaAtk** [comment]
@mdhiggins Why did you increase the max channel count for AC3? Fairly certain AC3 can only encode up to a maximum of 6 channels also.

**Comment by mdhiggins** [comment]
e0a92b65fc38bef952ae88f8eb62628bfe78010d
Misinterpreted max channel

Is that for truehd copying you still need the strict flag?

**Comment by RandomNinjaAtk** [comment]
Yes you need the strict flag for copying into mp4. It did work after adding that to the postopts, I’ve only completed one test so far.

**Comment by mdhiggins** [comment]
fcfdea4b932f8f26d361f5d306cc7b530786a6c2

See how that works
Was a little tricky because usually the experimental flag is handled by the codec's class but since it's copy I had to get a little creative

**Comment by RandomNinjaAtk** [comment]
Looks like the change worked, thanks...
