### ISSUE TITLE
Sonarr response: queued.

### ISSUE THREAD

**Issue by vtyr** [mdhiggins/sickbeard_mp4_automator#1278]
Hi, I've come across an issue which seems to have happened in the past from reading around. Sonarr sits in a state of 'queued' within the Sabnzbd history. Files do get downloaded, processed with ffmepg and then moved correctly, yet they sit in a 'queued' state in Sab. Any ideas? I'm fairly sure it's preventing Plex from rescanning with the use of the autoprocess script.

SABNZBD logs:
`2020-07-04 20:02:19 - resources.mediaprocessor - INFO - Starting conversion.
2020-07-04 20:02:46 - resources.mediaprocessor - INFO - C:\Users\Administrator\Downloads\complete\The.Big.Bang.Theory.S05E14.720p.HDTV.X264.1-DIMENSION-Obfuscated\cb708099423b4c72b118727c87a58bb8.mp4 created.
2020-07-04 20:02:46 - SABPostProcess - INFO - Successfully processed C:\Users\Administrator\Downloads\complete\The.Big.Bang.Theory.S05E14.720p.HDTV.X264.1-DIMENSION-Obfuscated\cb708099423b4c72b118727c87a58bb8.mkv.
2020-07-04 20:02:46 - SABPostProcess - INFO - Passing C:\Users\Administrator\Downloads\complete\The.Big.Bang.Theory.S05E14.720p.HDTV.X264.1-DIMENSION-Obfuscated directory to Sonarr.
2020-07-04 20:02:46 - autoprocess.sonarr - INFO - Sonarr notifier started.
2020-07-04 20:02:46 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'C:\Users\Administrator\Downloads\complete\The.Big.Bang.Theory.S05E14.720p.HDTV.X264.1-DIMENSION-Obfuscated'.
2020-07-04 20:02:46 - autoprocess.sonarr - INFO - Sonarr response: queued.`

Sonarr logs:
`20-7-4 20:01:34.6|Info|DownloadService|Report sent to Sab. The.Big.Bang.Theory.S05E14.720p.HDTV.X264.1-DIMENSION-Obfuscated
20-7-4 20:01:34.6|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded.
20-7-4 20:02:21.1|Info|DiskScanService|Scanning The Big Bang Theory
20-7-4 20:02:21.2|Info|DiskScanService|Completed scanning disk for The Big Bang Theory
20-7-4 20:02:21.2|Warn|VideoFileInfoReader|Unable to open media info from file: D:\The Big Bang Theory\Season 11\The Big Bang Theory - S11E04 - The Explosion Implosion HDTV-720p.mkv
20-7-4 20:02:21.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-7-4 20:02:21.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-7-4 20:02:21.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-7-4 20:02:21.3|Info|ExistingExtraFileService|Found 0 extra files`

**Comment by mdhiggins** [comment]
No idea, not enough info here to debug

SAB has no bearing on Plex and does not call anything related to plex, that script only exists to convert and notify Sonarr. Sonarr will notify plex after it moves and renames and runs postSonarr.py

Do you have completed download handling turned off?
Post your postSonarr.py logs and configuration too

**Comment by vtyr** [comment]
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4874771/sma.log)

Attached, thank you
[postSonarr.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4874775/postSonarr.zip)

**Comment by mdhiggins** [comment]
Do you have completed download handling turned off?
Post a screenshot of your postSonarr configuration too from inside Sonarr

**Comment by vtyr** [comment]
![image](https://user-images.githubusercontent.com/32479561/86535479-8dd54880-bed8-11ea-8ced-74b22aba5f00.png)

**Comment by mdhiggins** [comment]
Hm everything looks good and no errors on the script end

I'm not 100% clear on what issue you're having it seems like everything from the scripts end is working as intended so if you're having an issue it might be a SAB problem

What is the issue exactly? The SABPostProcess script seems to be handing the files off appropriately and trigger Sonarr and running postSonarr.py with good results and no errors

**Comment by mdhiggins** [comment]
Just to clarify 'queued' is the last thing you're supposed to see in the SAB history, that's the end for SAB's part of the process

**Comment by vtyr** [comment]
Ah good. I'm seeing when there's a lot of downloads and ffmepg is backed up processing them, Sonarr sometimes 'forgets' a couple (say 2 in 10-15) and doesn't process them.

**Comment by mdhiggins** [comment]
Well I would say everything looks good from what you've posted and seems to be working as intended

If you have log excerpts from a file that didn't process feel free to post

You could also using completed download handling and not using SABPostProcess and see if that produces better results
