### ISSUE TITLE
SMA Environment Variables

### ISSUE THREAD

**Issue by laryan61** [mdhiggins/sickbeard_mp4_automator#1279]
After testing manual.py for a couple of weeks, I'm working on moving to automation between SABnzbd, Sonarr 3, Plex, Kodi and SMA. I have a .sh script that looped through the folders/files, doing some house cleaning, naming files, if needed, deleting extra files, creating backup of original file and then calling manual.py. It worked well.

Since I'm using Sonarr v3, I need to call your postSonarr.py script via a .sh script. I'd like to incorporate the some of the same house cleaning chores into this script.

Do you have a list of the available SMA Environment Variables that I might be able to utilize in my script?

**Comment by mdhiggins** [comment]
There aren't very many environment variables, just one for config overrides
https://github.com/mdhiggins/sickbeard_mp4_automator#override-configuration-path

And the ones that get generated specifically for the post-process features
https://github.com/mdhiggins/sickbeard_mp4_automator#post-process-scripts

Other than that there aren't environment variables used globally
