### ISSUE TITLE
how to skip hevc h265 files

### ISSUE THREAD

**Issue by astlaurent** [mdhiggins/sickbeard_mp4_automator#1283]
hi

I am wondering how i can pass  h265 hevc file into the scripts but have it just skip them. My system completely crumbles trying to process these so if i choose to download one i wouldn't want the script to do much of anything to it other than maybe tagging.

**Comment by RandomNinjaAtk** [comment]
Add the following the the video codec: h265, x265, hevc

The script will then copy h265/hevc. So it will skip video conversion. However, it may still convert audio or do other functions if you have it setup for that.

**Comment by astlaurent** [comment]
awesome. thanks you. i will give that a go and see if it helps. I don't have too much else configured so it should work in most cases i think
