### ISSUE TITLE
Feat Request: Add Title metadata to Video track, similar to Audio/Subtitle

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1284]
Right now, the script carries over the embedded title data for video tracks. I think it would nice if possible to re-write the video title metadata in the same manor as audio and subtitle tracks.

Sometimes the carried over title is not very clean, may contain undesired info. It would be nice if the title was generated to match the Video info, to include the following info:

Codec (hevc/h265, h264) + Resolution (4k, 1080p, 720p) + HDR (If applicable)

Just a thought...

**Comment by mdhiggins** [comment]
a85cdccfdc06381ee4ef2a6743804efde1e97983

Opted not to include codec since that's not standard for any other stream but resolution and HDR included
