### ISSUE TITLE
tagging error after conversion / plex refresh error

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sickbeard_mp4_automator#1286]
Hello,

I'm seeing the following in the error log:

```
2020-07-25 20:22:13 - resources.mediaprocessor - INFO - Starting conversion.
2020-07-25 20:22:24 - resources.mediaprocessor - INFO - /anime/Plunderer/Season 01/Plunderer - S01E18 - Birth of Alcia.mp4 created.
2020-07-25 20:22:25 - resources.mediaprocessor - INFO - Tagging /anime/Plunderer/Season 01/Plunderer - S01E18 - Birth of Alcia.mkv with TMDB ID 93149.
2020-07-25 20:22:25 - resources.mediaprocessor - ERROR - Unable to tag file
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 52, in fullprocess
    tag.writeTags(output['output'], self.converter, self.settings.artwork, self.settings.thumbnail, output['x'], output['y'], self.converter)
TypeError: writeTags() takes from 3 to 7 positional arguments but 8 were given
2020-07-25 20:22:25 - resources.mediaprocessor - INFO - Relocating MOOV atom to start of file.
```

also, seeing this:

```
2020-07-25 20:22:36 - resources.mediaprocessor - ERROR - https://localhost:32400/library/sections/%s/refresh?X-Plex-Token=<token>
2020-07-25 20:22:36 - resources.mediaprocessor - ERROR - https://localhost:32400/library/sections?X-Plex-Token=<token>
2020-07-25 20:22:36 - resources.mediaprocessor - ERROR - Unable to refresh plex https, check your settings.
```

Does this have to be https if using localhost?

**Comment by mdhiggins** [comment]
It tries http first then falls back to https if that fails. Check your token or plex settings. You might need to relax your plex security if you're using local host and identify what's coming from the local network.

**Comment by mdhiggins** [comment]
e2d22ebf65ebf5756eeceb3a7310961defe7e845

That should fix the first error

**Comment by powerdude** [comment]
thanks for the first fix.  

for the second issue, does it log when it tries `http`.  I've tried it myself in a browser by replacing `localhost` with the ip address of the server  and it works.  this used to work and i already had security changed to preferred in plex.

Also, why is `%s` showing in the first statement?  shouldn't it be a number?

finally, it may be an issue on my side, but is it possible to ignore the port value if not there?  I use traefik and if it must use `https`, i get success with `https://plex.mydomain.com/...`, but not `https://plex.mydomain.com:32400`.

**Comment by powerdude** [comment]
sorry, one more thing, is it possible to limit the size of `sma.log` and/or make backup versions?

**Comment by powerdude** [comment]
the only thing i've been able to get working is to use my Synology address.  Maybe i used to have this set before, but i don't recall.  It seems like all of the following should work:
- `http://localhost:32400/`
- `http://<local-ip>:32400/`
- `http://<container-name>:32400/`
- `https://plex.mydomain.com/`
- `http://plex.mydomain.com/`
- `https://me.synology.me:32400/`

**Comment by mdhiggins** [comment]
If you have secure connections enabled in Plex, you need to set up these settings in Plex

![image](https://user-images.githubusercontent.com/3608298/88485860-66a5f000-cf47-11ea-8612-c5bee9943315.png)

And maybe this too though probably just the first option

![image](https://user-images.githubusercontent.com/3608298/88485871-83422800-cf47-11ea-90fd-591ffb619b69.png)

**Comment by powerdude** [comment]
i do:

![image](https://user-images.githubusercontent.com/780882/88487380-8262c380-cf52-11ea-81af-76d8c28fb8e0.png)

and

![image](https://user-images.githubusercontent.com/780882/88487389-9ad2de00-cf52-11ea-872e-d587d013265e.png)

![image](https://user-images.githubusercontent.com/780882/88487396-aa522700-cf52-11ea-86aa-3af18f998a4c.png)

the 10.0.90.0 is my docker network and 10.0.0.0 is my local network.  the ip of the docker server is 10.0.0.8.

**Comment by mdhiggins** [comment]
Well it's a simple URL call so you'll need to do some debugging and see why it's not working. It's probably something specific to your setup. Obviously verify your token. The plex.py file is very brief so you can see what it's doing easily. Try calling the URL and maybe try calling it from inside a docker container and see where it's failing.
