### ISSUE TITLE
Feature request - Use tag language based on Radarr profile language

### ISSUE THREAD

**Issue by steve1977** [mdhiggins/sickbeard_mp4_automator#1288]
Just learnt about this automator. Looks like quite some magic. Cool and very well done!

I don't plan to use the converter, but would love to use the tagger. Heard it now also support MKV. Ultimate objective is to become independent from Plex for meta data management and instead have all tags included in my MKV files.

I'd have one feature request, which would be great if you can consider: It seems the script gives me a binary choice what language I'd like to use for tagging. Would it be possible to instead use the language of the radarr movie profile (every movie in radarr has a profile, in which I can give it a language).

Would highly appreciate for you to consider. Thanks a lot in advance!

**Comment by mdhiggins** [comment]
While there's not a specific / embedded way to do exactly what you want, for situations like this where you want to vary your configuration slightly depending on *narr profiles the best option is to take advantage of the environment variable that lets you use different configurations

https://github.com/mdhiggins/sickbeard_mp4_automator#override-configuration-path

You can then use this setting within *narr to run slight variations of the script
![image](https://user-images.githubusercontent.com/3608298/88485901-e16f0b00-cf47-11ea-9181-216f014d5658.png)

Then when you create your shell wrapper just set that environment variable to a config file with the language options you would like before executing your post process script and you're good to go

**Comment by steve1977** [comment]
Thanks for your immediate reply. I am excited to see there may already be a solution to accomplish what I have in mind.

I've read your reply several times, but I am not clear on the "how to":

I couldn't find the radarr setting you are referring to. I am not sure I'd tag movies within radarr (by movie quality profile?).

Are you suggesting I create several autoProcess.ini files (autoProcess-1.ini, autoProcess-2.ini, etc.) and then start different version of the ini file depending on the radarr tag?

On separate note, do you have experience whether Plex will read embedded MKV tags (for movie name, description and poster).

Thanks again for all your are doing!

**Comment by mdhiggins** [comment]
Just add a tag for which language you want, then you'll have 2 post process entries in your settings that apply to each tag but not the other

Then have a small shell wrapper that sets the config before launching the script (autoProcess.eng.ini vs autoProcess.spa.ini) by setting that environment variable previously mentioned

You can probably mess around in the 'Agents' setting inside Plex to set where the data comes from

**Comment by steve1977** [comment]
Thanks for your message. Let me apologize, but you seem to over-estimate my capabilities. Will need to ask for a more step-by-step instruction. Let me respond on below.

> Just add a tag for which language you want

Are you referring to setting "tags" within Radarr? If so, within the "movie view", I'd select "movie editor" and then I select the movies that I'd like to "tag". And then click "set tag" to add a language tag (e.g., "French").

> then you'll have 2 post process entries in your settings that apply to each tag but not the other

So, I'd have autoprocess.ini for untagged movies and create a separate one autoprocess-french.ini for movies with the French tag. I'd need to configure them not to do any conversion, but only do MKV tagging. They'd look identical except the language tag would be EN for one and FR for the other.

> Then have a small shell wrapper that sets the config before launching the script (autoProcess.eng.ini vs autoProcess.spa.ini) by 
> setting that environment variable previously mentioned

Can you elaborate what a shell wrapper is and how to set the environmental variable?

**Comment by mdhiggins** [comment]
1. Yes
2. This method is just to create an alternate autoProcess.ini to do whatever you want that varies from your standard processing methods. If you want to tag in a different language this can be done using the tag-language setting, just copy the config and change that one setting. Its up to you to set up the config with the variations of what you want the script to do. Then in your 
3. Depends on your operating system but here's linux/bash example. Look up batch file for Windows but principle is exactly the same just different syntax

Then just filter based on tag in your custom script settings in *narr and point each tag to the respective script

#!/usr/bin/env bash

SMA_CONFIG=/path/to/alternate/autoProcess.ini

/path/to/python /path/to/postRadarr.py
```

**Comment by steve1977** [comment]
Ah, I think I now got it. And it seems I can just try it first just tagging French movies (and then later look into German and English ones). Once I have this, I can expand it to the options.

The wiki says "/usr/local/sma/postRadarr.sh" as script path (https://github.com/mdhiggins/radarr-sma). Should this actually say .py instead?

The above linux/bash script would have the ending *.bash and would be what I'd execute from the radarr custom script.

Now, I just need to familiarize with all the autoprocess configurations ;-)

Thanks!!!

**Comment by mdhiggins** [comment]
Not a typo, the docker containers include premade bash scripts that include the appropriate paths for the python binary/venv and script which would otherwise need to be made

**Comment by steve1977** [comment]
Ah... I am starting to learn how scripts work :-) Maybe I can write my own one day...

Is python included in the radarr-sma container and do I link to the python folder or the actual file?

**Comment by steve1977** [comment]
And a related question - how can I get Radarr to trigger the script for existing / already renamed movies?

**Comment by mdhiggins** [comment]
You can use manual import under the wanted section

**Comment by steve1977** [comment]
Thanks for your quick reply.  Manual import would require me to import everything again? Do you think this will run flawless when importing 1,000+ movies? Assume, this will also do the renaming for those that can be renamed?

Any thoughts whether python is bundled with radarr-sma and whether to link to folder or file?

**Comment by mdhiggins** [comment]
I think manual import is the way to go if you want radarr to process everything, though doing it in small batches just until you ensure things are working is probably safe.

And its docker, everything is included - python (in a venv), all the dependencies, FFMPEG, shell script, and the latest pull from github are all included

**Comment by steve1977** [comment]
Thanks for your continued help. I am making some progress. Few more questions though:

1) I still don't understand what to put for "/path/to/python /path/to/postRadarr.py" as I don't know where python can be found within the docker and whether to link to folder or actual file. I'd assume "/path/to/postRadarr.py" should be "/usr/local/sma/postRadarr.py"

2) I realized two complications of what I thought would work quite easily: (i) Is there a way to run the script on untagged movies (e.g., tag "FR" executes script x, no tag executes script y); (ii) There doesn't seem to be an easy to autotag (based on quality profile)

3) If I execute the script twice, is the movie converted twice (second time without any changes) or does the script see that the file is already same as desired and makes no change?

**Comment by steve1977** [comment]
> Not a typo, the docker containers include premade bash scripts that include the appropriate paths for the python binary/venv and script which would otherwise need to be made

I am using the "radarr-sma" docker for Unraid. I checked, but couldn't find the /usr/local/sma/postRadarr.sh file. At least not in the /usr/local/sma folder. Only see a .py file, but this file seems missing?

**Comment by mdhiggins** [comment]
1. Always link to an executable otherwise you won't execute anything. You can use `$SMA_PATH/venv/bin/python3 $SMA_PATH/postRadarr.py` as your path to python and your path to postRadarr.py  $SMA_PATH is defined as /usr/local/sma inside the docker container. Standard python virtual environment paths are used for the python executable

2. Probably not using Radarr. You could probably look at custom solutions to redirect things based on something like file name. Here are some examples
https://www.reddit.com/r/radarr/comments/8isrn4/custom_script_in_some_cases_only_possible/
By doing this you could avoid tagging all together and instead just look to the release name for something like a language code and then set a custom autoProcess.ini config

3. Depends
```
    def canBypassConvert(self, inputfile, info):
        # Process same extensions
        if self.settings.output_extension == self.parseFile(inputfile)[2]:
            if not self.settings.force_convert and not self.settings.process_same_extensions:
                self.log.info("Input and output extensions are the same so passing back the original file [process-same-extensions: %s]." % self.settings.process_same_extensions)
                return True
            elif info.format.metadata.get('encoder', '').startswith('sma') and not self.settings.force_convert:
                self.log.info("Input and output extensions match and the file appears to have already been processed by SMA, enable force-convert to override [force-convert: %s]." % self.settings.force_convert)
                return True
        return False
```
That's how the script looks to bypass conversion
It will depend on your `force-convert` and `process-same-extension` settings. Tagging always takes place though regardless of these two settings so if you wanted to just tag without potentially converting any streams just turn off both settings

**Comment by mdhiggins** [comment]
https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts

You can reference this to see what environment variables are available from Radarr to potentially help you determine the language

**Comment by mdhiggins** [comment]
Closing this since its not really an issue but feel free to keep posting

**Comment by steve1977** [comment]
Thanks a lot. Let me look into this!

**Comment by steve1977** [comment]
> 3. Depends
> 
> ```
>     def canBypassConvert(self, inputfile, info):
>         # Process same extensions
>         if self.settings.output_extension == self.parseFile(inputfile)[2]:
>             if not self.settings.force_convert and not self.settings.process_same_extensions:
>                 self.log.info("Input and output extensions are the same so passing back the original file [process-same-extensions: %s]." % self.settings.process_same_extensions)
>                 return True
>             elif info.format.metadata.get('encoder', '').startswith('sma') and not self.settings.force_convert:
>                 self.log.info("Input and output extensions match and the file appears to have already been processed by SMA, enable force-convert to override [force-convert: %s]." % self.settings.force_convert)
>                 return True
>         return False
> ```
> 
> That's how the script looks to bypass conversion
> It will depend on your `force-convert` and `process-same-extension` settings. Tagging always takes place though regardless of these two settings so if you wanted to just tag without potentially converting any streams just turn off both settings


I have force-convert and process-same-extension. If I had already processed the file with the script and I run the script again on the already converted it, will it still convert it again? If so, would I need to set forceconvert to "false"?

**Comment by mdhiggins** [comment]
Yep
That being said even if it converted it again it would essentially just be remuxing assuming you aren't doing any generation of extra audio tracks so it wouldn't be a big deal

**Comment by steve1977** [comment]
Got it, thanks. It seems I have it working now and newly added movies are being converted (and tagged). Still without the "language tag" though.

I realized though that I have one much larger issue than the "language tag". I don't know how I can convert & tag movies that are already in my library. I'd need to manually run the script on all movies in my library. Is there an easy way to do this? Maybe something you could help me with creating sich bash script?

**Comment by mdhiggins** [comment]
I still think manual import through Radarr is the best way but if you object to that then using manual.py is probably fine. You can literally pass manual.py a directory and it will walk through and process everything it finds and if specified won't ask you to confirm the ID of the file. See the readme or help documentation included in manual.py (--help)

**Comment by steve1977** [comment]
Thanks for your help.

I should trust the expert ;-) So, help me understand again how I could manually import. My movies are already imported. I could start with a fresh radarr and import them from scratch. However, this will require me to match all of them again, which may turn into a week-long exercise. Is there a way to import them without going through the manual matching process again?

If I were to use manual.py, it would likely work for conversions. There may be two issues with it though. (1) I also have trailer files, which I don't need to have converted (that's the lesser issue though); (2) I don't think it would tag correctly as the script wouldn't have access to the info from radarr to pass on the tmdb ID. I'd assume this would require somehow access to the radarr API or whatever magic you do with the custom script.

I looked through the wiki page and didn't find an answer to this.

Thanks again for all your sharing here!
