### ISSUE TITLE
Skipping H265 completely

### ISSUE THREAD

**Issue by joeblack2k** [mdhiggins/sickbeard_mp4_automator#1290]
i know it has been asked before in the closed issues, but i can't figure out how to skip H265 i've added them to codec under video:

`[Video]
max-width = 0
max-level = 0.0
profile =
crf = 21
pix-fmt =
max-bitrate = 0
codec = h264, x264, h265, x265
crf-profiles =
filter =
force-filter = False`

But it still wants to process, probably because i want audio to be aac, except for H265,HEVC etc.. just skip them

how can i just skip files as soon as the script feels it's H265

**Comment by RandomNinjaAtk** [comment]
You want to set your codec to this:

```
codec = h264, x264, h265, x265, hevc
```

Also your CRF setting could possibly be causing it to still convert the video. If you set the setting to what I gave you, it should copy the video stream for h265/hevc, but if you for example had a max width of 1280, thats where you could still have a conversion triggered. So I'm not sure if your CRF would possibly cause a conversion, but it might....

**Comment by mdhiggins** [comment]
CRF should never force conversion, this is definitely because hevc was missing
