### ISSUE TITLE
qBittorrent

### ISSUE THREAD

**Issue by PadelzZ** [mdhiggins/sickbeard_mp4_automator#1291]
**My qBittorrent Settings:**
![image](https://user-images.githubusercontent.com/19844314/88921535-ff51ae00-d26e-11ea-9def-2504be45d365.png)

**Autoprocess.ini:**
_
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = username
password =  password
output-directory = _

I'm having a problem at the moment to have qBittorrent to start using the python script when a download is complete. In NZBGet I don't have any problems, files get processed and converted all the way to the end. But in qBittorrent I don't see anything happen.

When a download is complete, its keeps seeding but in the log of qBittorrent, I see the following happen:
_(N) 2020-07-30T14:01:36 - 'Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]' added to download list.
(N) 2020-07-30T14:03:16 - Successfully moved torrent: Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]. New path: D:\Downloads
(N) 2020-07-30T14:03:16 - Torrent: Batwoman.S01E01.HDTV.x264-PHOENiX[TGx], running external program, command: D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py ''sonarr'' ''udp://tracker.leechers-paradise.org:6969/announce'' ''D:\Downloads\Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''D:\Downloads\Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''11fc63b8964c919485876e390ce79e5b2b2fb2f9''_

I'm using qBittorrent v4.25 (64-bit).

In the sma.log there is no trace of what is happening, when qBittorrent runs the external program.

Is their a way, you could help me out with fixing this?

**Comment by mdhiggins** [comment]
Run that command from your command line and see if you get any errors
```
D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py ''sonarr'' ''udp://tracker.leechers-paradise.org:6969/announce'' ''D:\Downloads\Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''D:\Downloads\Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''Batwoman.S01E01.HDTV.x264-PHOENiX[TGx]'' ''11fc63b8964c919485876e390ce79e5b2b2fb2f9''
```

If you're crashing on something like an import error very early in the script no log files will be generated

**Comment by PadelzZ** [comment]
You mean like this?

![image](https://user-images.githubusercontent.com/19844314/88922250-265caf80-d270-11ea-8840-265361b4bb6c.png)

**Comment by mdhiggins** [comment]
Alright so your python script isn't getting your command line parameters which is why its probably failing

This is usually an installation problem with python and windows that is fixed by updating some registry keys

https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t

NZBGet doesn't use command line parameters to pass data, it uses environment variables so it would not be impacted by this problem

**Comment by PadelzZ** [comment]
I'm able to run the command manually, it converts and put in the right folder. But in the end has the following problem to delete the  folder:

_2020-07-30 14:44:04 - qBittorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 197, in <module>
    os.rmdir(delete_dir)_

Now i tried downloading different episode, but still nothing happening when qBittorrent runs the external program.

**Comment by mdhiggins** [comment]
Its normal to not be able to delete the directory for torrents since you're often still seeding

Did you have to make the above changes to run it manually?

What is your log in qBittorrent showing?

Is anything showing up in the sma.log file now?

**Comment by PadelzZ** [comment]
I changed something to the register, then I was able to run it manually.

qBittorrent:
_(N) 2020-07-30T14:45:22 - 'Batwoman.S01E02.HDTV.x264-SVA[ettv]' added to download list.
(N) 2020-07-30T14:46:15 - Successfully moved torrent: Batwoman.S01E02.HDTV.x264-SVA[ettv]. New path: D:\
(N) 2020-07-30T14:46:15 - Torrent: Batwoman.S01E02.HDTV.x264-SVA[ettv], running external program, command: D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py ''sonarr'' ''udp://tracker.internetwarriors.net:1337/announce'' ''D:\Batwoman.S01E02.HDTV.x264-SVA[ettv]'' ''D:\Batwoman.S01E02.HDTV.x264-SVA[ettv]'' ''Batwoman.S01E02.HDTV.x264-SVA[ettv]'' ''c88433debbd6d46af4dde4a877dd12fc9bd35a96''
_

**Comment by mdhiggins** [comment]
Sometimes on windows you need to wrap these kind of things in a batch file or it has trouble executing

Try
```
D:\path\to\python.exe D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py %*
```

Obviously updating your path to python executable there. Then point qBittorrent to that instead of the python script directly

**Comment by PadelzZ** [comment]
Still have to put the following arguments in qbitTorrent - ''%L'' ''%T'' ''%R'' ''%F'' ''%N'' ''%I'' ?

**Comment by mdhiggins** [comment]
Yes

**Comment by PadelzZ** [comment]
Seem to get the following problem now in the sma.log

qBittorrent -> D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrent.bat ''%L'' ''%T'' ''%R'' ''%F'' ''%N'' ''%I''

bat.file: C:\Users\Marco\AppData\Local\Programs\Python\Python38\python.exe D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py %*

**Comment by mdhiggins** [comment]
Looks like its not getting your command line parameters
%* is supposed to be a wildcard that includes all parameters

You could alternatively try
```
C:\Users\Marco\AppData\Local\Programs\Python\Python38\python.exe D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py %1 %2 %3 %4 %5 %6
```

**Comment by PadelzZ** [comment]
it's making process:

_2020-07-30 15:37:43 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-07-30 15:37:43 - resources.readsettings - INFO - C:\Users\Marco\AppData\Local\Programs\Python\Python38\python.exe
2020-07-30 15:37:43 - resources.readsettings - INFO - Loading config file D:\sickbeard_mp4\sickbeard_mp4_automator-master\config\autoProcess.ini.
2020-07-30 15:37:43 - qBittorrentPostProcess - ERROR - No valid label detected.
2020-07-30 15:37:43 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 48, in <module>
    sys.exit(1)
SystemExit: 1_

**Comment by mdhiggins** [comment]
Yeah sonarr should be the first command line parameter
Do you have autoProcess.ini set up with sonarr as a category in the qbittorrent section of your config?

You'll also probably get a lot more useful info if you turn on DEBUG level logging which can be done in the logging.ini file 

```
[handler_fileHandler]
class = handlers.RotatingFileHandler
level = INFO
formatter = simpleFormatter
args = ('%(logfilename)s', 10000, 1)
```

change from `INFO` to `DEBUG`

And your config section should have sonarr
```
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
...
```

**Comment by PadelzZ** [comment]
2020-07-30 16:33:28 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-07-30 16:33:28 - resources.readsettings - INFO - C:\Users\Marco\AppData\Local\Programs\Python\Python38\python.exe
2020-07-30 16:33:28 - resources.readsettings - DEBUG - Loading default config file.
2020-07-30 16:33:28 - resources.readsettings - INFO - Loading config file D:\sickbeard_mp4\sickbeard_mp4_automator-master\config\autoProcess.ini.
2020-07-30 16:33:28 - qBittorrentPostProcess - DEBUG - Root Path: ''D:\Batwoman.S01E02.HDTV.x264-SVA[ettv]''.
2020-07-30 16:33:28 - qBittorrentPostProcess - DEBUG - Label: ''sonarr''.
2020-07-30 16:33:28 - qBittorrentPostProcess - DEBUG - Categories: ['couchpotato', 'sickbeard', 'sonarr', 'radarr', 'sickrage', 'bypass'].
2020-07-30 16:33:28 - qBittorrentPostProcess - DEBUG - Torrent hash: ''c88433debbd6d46af4dde4a877dd12fc9bd35a96''.
2020-07-30 16:33:28 - qBittorrentPostProcess - DEBUG - Torrent name: ''Batwoman.S01E02.HDTV.x264-SVA[ettv]''.
2020-07-30 16:33:28 - qBittorrentPostProcess - ERROR - No valid label detected.
2020-07-30 16:33:28 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "D:\sickbeard_mp4\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 48, in <module>
    sys.exit(1)
SystemExit: 1

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password =  
output-directory =

**Comment by mdhiggins** [comment]
It would appear the quotes are actually being included in the string. If your batch file has quotes around the variables ("%1" etc) remove them. If it doesn't then remove the quotes from qBittorrent as they appear to be getting included (possible because of the batch file layer).

**Comment by PadelzZ** [comment]
Yes! That was it, it's finally working! You made my day 👍 
Thanks for your awesome help

**Comment by mdhiggins** [comment]
👍

**Comment by morpheus2n2** [comment]
@PadelzZ HI wondering if you could help me with how you have it set up on yours, I have been having no end of problems with Deluge so trying to switch over to qBittorrent but just can't seem to get this to trigger at all
