### ISSUE TITLE
max-bitrate not set but still used in ffmpeg call

### ISSUE THREAD

**Issue by eikowagenknecht** [mdhiggins/sickbeard_mp4_automator#1292]
I'm currently converting many x265 files (10bit) to h264 (8bit), because the LG Plex app only supports 8bit video.

In doing so I noticed that the quality of the resulting files gets quite bad. Investigating further, I see that the original file has a bitrate (total) of "2364" and your script calls ffmpeg with the argument -maxrate:v 2363k, which is quite close to this.

I suspect this is to make sure the resulting file is smaller that the input? But of course h264 needs a higher bitrate for the same quality so the quality is effectively worse. I do not care much about disk space and would like to disable this max rate.

Is this possible? Or what other settings could I use to achieve what I want?

Video settings are:

```
[Video]
profile = 
crf-profiles = 
codec = h264vaapi, h265vaapi, h264, x264, hevc, x265
crf = 23
max-width = 0
max-bitrate = 0
pix-fmt = yuv420p
max-level = 0.0
filter = 
force-filter = False
```

With crf set to -1 instead there is a "variable bitrate" of 2363 passed into ffmpeg which is not better.
Setting max-bitrate to something high (like 100000) also has no effect.

```
Processing file /tv/zzzzzz.mkv
Input Data
{
    "format": "matroska,webm",
    "format-fullname": "unknown",
    "video": {
        "index": 0,
        "codec": "hevc",
        "pix_fmt": "yuv420p10le",
        "profile": "2",
        "fps": 23.976023976023978,
        "level": 12.0,
        "field_order": "unknown"
    },
    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "channels": 2,
            "samplerate": 44100,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        }
    ],
    "subtitle": [
        {
            "index": 2,
            "codec": "ass",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "language": "eng"
        },
        {
            "index": 3,
            "codec": "ass",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "language": "enm"
        }
    ],
    "attachment": [
        {
            "index": 4,
            "codec": "ttf"
        },
        {
            "index": 5,
            "codec": "otf"
        },
        {
            "index": 6,
            "codec": "otf"
        },
        {
            "index": 7,
            "codec": "otf"
        },
        {
            "index": 8,
            "codec": "otf"
        },
        {
            "index": 9,
            "codec": "otf"
        },
        {
            "index": 10,
            "codec": "ttf"
        }
    ]
}
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p10le.
Profile: 2.
Creating h264vaapi video stream from source stream 0.
Reading audio streams.
Audio detected for stream 1 - aac eng 2 channel.
Creating copy audio stream from source stream 1.
Default audio stream set to eng copy 2 channel stream [default-more-channels: True].
Reading subtitle streams.
Text-based subtitle detected for stream 2 - ass eng.
Creating mov_text subtitle stream from source stream 2.
Text-based subtitle detected for stream 3 - ass enm.
Attempting to download subtitles.
Scanned for external subtitles and found 0 results in your approved languages.
vaapi hwaccel is supported by this ffmpeg build and will be used [hwaccels].
Output Data
{
    "source": [
        "/tv/xxxxxx.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264vaapi",
        "map": 0,
        "bitrate": 2363.735,
        "crf": 23,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "pix_fmt": "yuv420p",
        "field_order": "unknown",
        "width": null,
        "filter": null,
        "title": "FHD",
        "debug": "video.pix_fmt"
    },
    "audio": [
        {
            "map": 1,
            "codec": "copy",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo",
            "debug": "universal-audio"
        }
    ],
    "subtitle": [
        {
            "map": 2,
            "codec": "mov_text",
            "language": "eng",
            "encoding": "",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "",
            "debug": "subtitle.embed-subs"
        }
    ],
    "attachment": []
}
Preopts
[
    "-fix_sub_duration",
    "-hwaccel",
    "vaapi"
]
Postopts
[
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]

```

**Comment by mdhiggins** [comment]
Use the CRF profiles option if you want to fine tune these kinds of things otherwise the script is kind of stuck guessing based on the source bitrate.

**Comment by eikowagenknecht** [comment]
Thanks for the lightening fast response!

But I still don't get it. I have set CRF to 23 and max-bitrate to 0 (=disable). Why is it still passed into ffmpeg? Can this not just be omitted?

**Comment by mdhiggins** [comment]
Correct. You aren't providing a max bitrate so the script is guessing one based on the source material. Not specifying a max bitrate creates problems. This was sort of a legacy solution before the crf-profiles existed

I removed that parameter
c838edbd94fca01aa6c1afa166dd6110b800945e

But you really should set up the profiles and specify some value as you're likely to have some playback issues related to no max rate being set.

Using CRF profiles you can specify this value. Specifying a single profile would be enough.

**Comment by eikowagenknecht** [comment]
Thanks. If anyone else using VAAPI stumbles upon this:

I just found out that  ([crf is not supported at all with VAAPI](https://trac.ffmpeg.org/wiki/Hardware/VAAPI)):

> No CRF-like mode is currently supported. The only constant-quality mode is CQP (constant quantisation parameter), which has no adaptivity to scene content. It does, however, allow different quality settings for different frame types, to improve compression by spending fewer bits on unreferenced B-frames - see the (i|b)_q(factor|offset) options. CQP mode cannot be combined with a maximum bitrate or buffer size.
> 
> CBR and VBR modes are supported, though the output of them varies significantly by driver and device (default is VBR, set -maxrate equal to -b:v for CBR). HRD buffering options (rc_max_rate, rc_buffer_size) are functional, and the encoder will generate buffering_period and pic_timing SEI when appropriate.
> 
> There is no complete analogue of the -preset option. The -compression_level option controls the local speed/quality tradeoff in the encoder (that is, the amount of effort expended on trying to get the best results from local choices like motion estimation and mode decision), using a nebulous per-device scale. The argument is a small integer, from 1 up to some limit dependent on the device (not more than 7) - higher values are faster / lower stream quality. Separately, some hardware (Intel gen9) supports a low-power mode with more restricted features. It is accessible via the -low_power option.
> 
> Neither two-pass encoding nor lookahead are supported at all - only local rate control is possible. VBR mode should do a reasonably good job at getting close to an overall bitrate target, but quality will vary significantly through a stream if the complexity varies.

So when using h264vaapi or h265vaapi, just ignore crf and go with max-bitrate or variable bitrate, I guess.

I'm now using the crf profiles and the crf parameter is still passed in without error, but according to the official documentation above should be completely without effect. So max-bitrate can now be set by crf parameter without actually having crf. It's a bit confusing but seems to work ;-)
