### ISSUE TITLE
radarr issue 

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1298]
hey mate. since radarr did a maintenance update the other day. i have been getting this error on the script.

`2020-08-09 14:23:49 - autoprocess.radarr - INFO - Radarr notifier started.
2020-08-09 14:23:49 - autoprocess.radarr - INFO - Requesting Radarr to scan directory '/mnt/downloads/sabnzbd/movies/Deathstroke.Knights.and.Dragons.2020.1080p.WEBRip.DD5.1.x264-CM-xpost'.
2020-08-09 14:23:49 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/opt/mp4automator/autoprocess/radarr.py", line 61, in processMovie
log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
KeyError: 'state'`

**Comment by mdhiggins** [comment]
Radarr isn't responding, check your setup and API key

**Comment by pazport** [comment]
i have re-checked it mate. sometimes it sends. sometimes it don't mate. i even uninstalled radarr and re-installed. and added new api. i have posted a screen shot here 
![Untitled](https://user-images.githubusercontent.com/46929183/89765798-f1155480-daee-11ea-9b40-d9667783463e.png)

**Comment by mdhiggins** [comment]
The fact that its working intermittently like that means that you have periods of time where the Radarr API isn't responding. Good news is that means the script is configured correctly and everything is working from SMA's perspective. This isn't a script problem but likely a problem with Radarr. Is Radarr crashing or frequently restarting by chance? I've seen people who have problems with Radarr or docker that cause Radarr to constantly restart and the API only responds if the timing works out that it isn't during a launch window

**Comment by mdhiggins** [comment]
In fact you appear to have opened this same issue before and it was a Sonarr problem at that time

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1269

**Comment by pazport** [comment]
yes lol. sonarr did an update that fixed the API calling. 

radarr was working perfect until they did a maintinence update. i have spoken to them. but they think it's your script that isn't up todate with there API or something along them lines mate. 

i hav also uninstalled sabnzbd and re-installed no luck. and also grabbed fresh files for mp4automator. still no luck.

**Comment by mdhiggins** [comment]
Got a link that discussion? Anything about restarting in your Radarr logs? Its not something I've gonna be able to fix I could write code all day but if an API doesn't respond there's not much I can do

**Comment by mdhiggins** [comment]
You could opt to switch to a completed download handling setup to avoid this step all together

**Comment by pazport** [comment]
am using radarr v3/preview lol. when i tell it to use radarrscript on mp4automator it fails every time. that's why i use sabs lol. i could never get nzbget to get it working. due to it being a docker.

**Comment by mdhiggins** [comment]
Radarr v3 should be working lots of people use it. Not sure what Radarrscript is though. Not sure what you mean by it being a docker. NZBGet doesn't have to be a docker but any of these programs can be a docker

**Comment by mdhiggins** [comment]
Gonna close this as I believe its a problem with your radarr setup as I haven't had issues with anyone else on v3 and my tests on V3 are working, but feel free to continue discussion if you get more debugging info (should try turning on debug logging and post those logs)
