### ISSUE TITLE
Not an issue, can't work out best settings lmao

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1299]
This is not an issues however cos there's nothing I can see in the read me I wanted to ask.
I know that H265 is supported and I am going to start moving my library over to it as H264 its taking to much space lmao.
What do I need to change in my autoprocess.ini for the best results at a smaller file size?

Heres my current .ini

```
[Converter]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = 0
output-directory = 
copy-to = 
move-to = \\Plex\To Sort
output-extension = mp4
output-format = mp4
delete-original = True
post-process = False
postopts = 
preopts = 
temp-extension = 
force-convert = True
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
minimum-size = 0
ignored-extensions = nfo, ds_store
sort-streams = True
process-same-extensions = True

[Metadata]
relocate-moov = True
full-path-guess = True
tag = false
tag-language = en
download-artwork = Poster
sanitize-disposition = 

[Video]
codec = h264, x264
max-bitrate = 2500
max-width = 1920
max-level = 5.1
pix-fmt = 
crf = -1
profile = 
crf-profiles = 
filter = 
force-filter = False

[Universal Audio]
codec = aac
first-stream-only = False
filter = 
move-after = False
channel-bitrate = 128
force-filter = False

[Audio]
max-channels = 6
codec = aac,ac3
languages = Jpn,eng
default-language = eng
channel-bitrate = 128
filter = 
aac-adtstoasc = False
copy-original = False
first-stream-of-language = False
allow-language-relax = True
max-bitrate = 0
prefer-more-channels = True
default-more-channels = True
sample-rates = 
ignore-truehd = mp4, m4v
force-filter = False

[Subtitle]
codec = mov_text
languages = eng
default-language = eng
encoding = 
download-subs = False
embed-subs = True
download-providers = addic7ed,podnapisi,thesubdb,opensubtitles
embed-only-internal-subs = False
codec-image-based = 
first-stream-of-language = False
burn-subtitles = False
burn-dispositions = 
download-hearing-impaired-subs = False
embed-image-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec = 
```

**Comment by pazport** [comment]
> 
> 
> This is not an issues however cos there's nothing I can see in the read me I wanted to ask.
> I know that H265 is supported and I am going to start moving my library over to it as H264 its taking to much space lmao.
> What do I need to change in my autoprocess.ini for the best results at a smaller file size?
> 
> Heres my current .ini
> 
> ```
> [Converter]
> ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
> ffprobe = C:\ffmpeg\bin\ffprobe.exe
> threads = 0
> output-directory = 
> copy-to = 
> move-to = \\Plex\To Sort
> output-extension = mp4
> output-format = mp4
> delete-original = True
> post-process = False
> postopts = 
> preopts = 
> temp-extension = 
> force-convert = True
> hwaccels = dxva2, cuvid, qsv, d3d11va
> hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
> minimum-size = 0
> ignored-extensions = nfo, ds_store
> sort-streams = True
> process-same-extensions = True
> 
> [Metadata]
> relocate-moov = True
> full-path-guess = True
> tag = false
> tag-language = en
> download-artwork = Poster
> sanitize-disposition = 
> 
> [Video]
> codec = h264, x264
> max-bitrate = 2500
> max-width = 1920
> max-level = 5.1
> pix-fmt = 
> crf = -1
> profile = 
> crf-profiles = 
> filter = 
> force-filter = False
> 
> [Universal Audio]
> codec = aac
> first-stream-only = False
> filter = 
> move-after = False
> channel-bitrate = 128
> force-filter = False
> 
> [Audio]
> max-channels = 6
> codec = aac,ac3
> languages = Jpn,eng
> default-language = eng
> channel-bitrate = 128
> filter = 
> aac-adtstoasc = False
> copy-original = False
> first-stream-of-language = False
> allow-language-relax = True
> max-bitrate = 0
> prefer-more-channels = True
> default-more-channels = True
> sample-rates = 
> ignore-truehd = mp4, m4v
> force-filter = False
> 
> [Subtitle]
> codec = mov_text
> languages = eng
> default-language = eng
> encoding = 
> download-subs = False
> embed-subs = True
> download-providers = addic7ed,podnapisi,thesubdb,opensubtitles
> embed-only-internal-subs = False
> codec-image-based = 
> first-stream-of-language = False
> burn-subtitles = False
> burn-dispositions = 
> download-hearing-impaired-subs = False
> embed-image-subs = False
> filename-dispositions = forced
> ignore-embedded-subs = False
> attachment-codec = 
> ```

change the (video) codec mate E.G

`codec = h264, x264` to something like this `codec = h265, x265, h.265, x.265, H265, X265, H.265, X.265`

**Comment by mdhiggins** [comment]
The video codec is key here
`codec = h264, x264` will copy anything that meets those 2 criteria and will convert everything else to h264

If you want to convert your old library, I would use
`codec = h265, hevc`

If you want to just add h265 to your whitelist and still keep h264 then just combine
`codec = h265, hevc, h264, x264`

I will say your best bet is to download source material that is already h265 than trying to convert all incoming meida; you lose quality with every conversion and minimizing quality loss always comes at the cost of increased transcoding time and CPU usage.

Additionally if you're going to be converting make sure you have good quality settings. I recommend using `crf` or `crf-profiles` which you can read about on the readme and FFmpeg documentation to achieve best dynamic quality options

@pazport 
Just an FYI `x.265, H.265, X.265, h.265` are not valid codecs and that style of naming isn't used by FFmpeg or FFprobe. It won't hurt anything having them in the option list but you can delete them since they don't do anything. Also all codecs are converted to lower case so you don't need to have two sets of upper and lower

**Comment by morpheus2n2** [comment]
> The video codec is key here
> `codec = h264, x264` will copy anything that meets those 2 criteria and will convert everything else to h264
> 
> If you want to convert your old library, I would use
> `codec = h265, hevc`
> 
> If you want to just add h265 to your whitelist and still keep h264 then just combine
> `codec = h265, hevc, h264, x264`
> 
> I will say your best bet is to download source material that is already h265 than trying to convert all incoming meida; you lose quality with every conversion and minimizing quality loss always comes at the cost of increased transcoding time and CPU usage.
> 
> Additionally if you're going to be converting make sure you have good quality settings. I recommend using `crf` or `crf-profiles` which you can read about on the readme and FFmpeg documentation to achieve best dynamic quality options
> 
> @pazport
> Just an FYI `x.265, H.265, X.265, h.265` are not valid codecs and that style of naming isn't used by FFmpeg or FFprobe. It won't hurt anything having them in the option list but you can delete them since they don't do anything. Also all codecs are converted to lower case so you don't need to have two sets of upper and lower

Sweet thank you, I had a feeling it was just the codec part but wanted to check there wasn't another settings I needed to change i.e hwaccels

**Comment by mdhiggins** [comment]
If you're going to be doing a lot of converting and have a system that supports hardware acceleration that may offer a huge performance boost but requires more research and fine tuned control and often special builds of FFMPEG.

https://trac.ffmpeg.org/wiki/HWAccelIntro

That's a good starting reference

**Comment by morpheus2n2** [comment]
That was a good starting point thank you, running some test encodes now so far it seems to be working perfect with hardware decoding/encoding using my GPU just waiting to see the end result. So will update for others reference :D

**Comment by mdhiggins** [comment]
Unless you have changed your codec, you're probably only using GPU decoding

For nvidia for example you'd need to set your codecs to `h265_nvenc, h265, hevc`

If you did that already please disregard

**Comment by morpheus2n2** [comment]
Ok for anyone that want to use as reference here is what I changed it to 

`[Converter]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = 0
output-directory = 
copy-to = 
move-to = \\Plex\To Sort
output-extension = mp4
output-format = mp4
delete-original = True
post-process = False
postopts = 
preopts = 
temp-extension = 
force-convert = True
hwaccels = dxva2, cuvid, qsv, d3d11va, hevc_nvenc, h264_nvenc
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, h264_nvenc, hevc_nvenc
minimum-size = 0
ignored-extensions = nfo, ds_store
sort-streams = True
process-same-extensions = True
detailed-progress = False

[Metadata]
relocate-moov = True
full-path-guess = True
tag = false
tag-language = en
download-artwork = Poster
sanitize-disposition = 

[Video]
codec = h265_nvenc, h265, hevc
max-bitrate = 1500
max-width = 1920
max-level = 5.1
pix-fmt = 
crf = -1
profile = 
crf-profiles = 
filter = 
force-filter = False
codec-parameters = 

[Universal Audio]
codec = aac
first-stream-only = False
filter = 
move-after = False
channel-bitrate = 128
force-filter = False

[Audio]
max-channels = 6
codec = aac,ac3
languages = Jpn,eng
default-language = eng
channel-bitrate = 128
filter = 
aac-adtstoasc = False
copy-original = False
first-stream-of-language = False
allow-language-relax = True
max-bitrate = 0
prefer-more-channels = True
default-more-channels = True
sample-rates = 
ignore-truehd = mp4, m4v
force-filter = False
ignored-dispositions = 
unique-dispositions = False

[Subtitle]
codec = mov_text
languages = eng
default-language = eng
encoding = 
download-subs = False
embed-subs = True
download-providers = addic7ed,podnapisi,thesubdb,opensubtitles
embed-only-internal-subs = False
codec-image-based = 
first-stream-of-language = False
burn-subtitles = False
burn-dispositions = 
download-hearing-impaired-subs = False
embed-image-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec = 
ignored-dispositions = 
unique-dispositions = False`

I'm using a Ryzen 5 3600  and have a Nvidia 1080 GTX, I have set it to use hardware Decoding/Encoding and have manged to do a number of files as a test. Yes while the bit rate seems low, the whole point of HEVC is that lower bitrates can look just the same as high AVC bitrate files :D
I had it do a blu-ray ripped file of 6GB and got it down to 500mb with NO visible lose in quality, it also only took 10 mins, this was the best bit as when I was doing H264 it would take about 30 min!!
