### ISSUE TITLE
Trouble running manual.py

### ISSUE THREAD

**Issue by the0nlyace** [mdhiggins/sickbeard_mp4_automator#1302]
```
Enter path to file:
#: "G:\My Drive\TV\American Dad!\Season 16\American Dad S16E21 Downtown (1080p AMZN Webrip x265 10bit EAC3 5.1 - Goki)[TAoE].mkv"
isValidSource unexpectedly threw an exception, returning None
Traceback (most recent call last):
  File "C:\MP4 Automator\resources\mediaprocessor.py", line 266, in isValidSource
    info = self.converter.probe(inputfile)
  File "C:\MP4 Automator\converter\__init__.py", line 316, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "C:\MP4 Automator\converter\ffmpeg.py", line 551, in probe
    stdout_data = self._get_stdout([
  File "C:\MP4 Automator\converter\ffmpeg.py", line 515, in _get_stdout
    p = self._spawn(cmds)
  File "C:\MP4 Automator\converter\ffmpeg.py", line 508, in _spawn
    return Popen(cmds, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE,
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied
File G:\My Drive\TV\American Dad!\Season 16\American Dad S16E21 Downtown (1080p AMZN Webrip x265 10bit EAC3 5.1 - Goki)[TAoE].mkv is not in a valid format
```

**Comment by mdhiggins** [comment]
PermissionError: [WinError 5] Access is denied

You've got a permission problem either with ffprobe/ffmpeg or with the file you're trying to read

**Comment by the0nlyace** [comment]
Any Idea what can cause this? Unsure why I'd be getting a permission error

**Comment by mdhiggins** [comment]
... a permission error causes this

Make sure ffmpeg/ffprobe have execute permissions, make sure the user you're running the command from have permissions to access those two executable files and had read/write access to the directory you're working in (in this case american dad)

**Comment by the0nlyace** [comment]
I have execute permission on ffmpeg/ffprobe and full read/write access to the working directory

**Comment by the0nlyace** [comment]
What flags should be in the .ini file regarding permissions?

**Comment by mdhiggins** [comment]
I'd say based on the error is seems like ffprobe probably isn't able to execute

Do you have ffprobe stored somewhere that needs admin access and you're trying to run it through a non-admin command prompt?

I don't' think the ini permissions are the problem (those are for the output files) and it hasn't gotten that far

Start posting some specifics like what user you're executing from, where you ffmpeg/ffprobe binaries are stored, and some screenshots of your permission settings

**Comment by the0nlyace** [comment]
I found an error in my \setup\autoprocess.ini - regarding full path to ffmpeg and ffprobe executables, Fixed that, now running into another error

```
Enter path to file:
#: C:\Users\Jarrad\Desktop\Smallville.S05E15.720p.WEB-DL.AAC2.0.H.264-BTN.mkv
Traceback (most recent call last):
  File "C:\MP4 Automator\manual.py", line 410, in <module>
    main()
  File "C:\MP4 Automator\manual.py", line 398, in main
    tagdata = getInfo(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), season=args.get('season'), episode=args.get('episode'))
  File "C:\MP4 Automator\manual.py", line 113, in getInfo
    tagdata = guessInfo(fileName, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode)
  File "C:\MP4 Automator\manual.py", line 158, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: module 'guessit' has no attribute 'guessit'
```

I have guessit installed

**Comment by the0nlyace** [comment]
Updated guessit - can disregard this thread - all working.
