### ISSUE TITLE
Select audio output format based on audio input format properties

### ISSUE THREAD

**Issue by TwoLeaves** [mdhiggins/sickbeard_mp4_automator#1304]
I'm looking to configure this script such that it selects a different audio output format depending on the whether the audio input format is lossy or lossless. Specifically I'd like it to convert all problematic audio formats to AC3, unless they are lossless (TrueHD, DTS-HD MA) in which case I'd like them repackaged as FLAC (avoiding an unnecessary transcoding). Though in this particular case the lack of such a feature is not too punishing (a transparent lossless to lossy transcode that saves disk space is not the worst outcome) I could see it being useful in other cases (for example selecting different audio output formats depending on the number of channels in the source audio track, e.g. going with a simple audio format like AC3 unless the source audio has too many channels in which case select a more complicated codec). Thanks.

**Comment by mdhiggins** [comment]
Currently this is not supported. The major design function of the script is to convert everything to the same format so there's no logic or configuration option that would do specifically what you're looking to do. To add this would be quite a large undertaking and require overhauling many core components of the script. Happy to look at a pull request but not something that's planned from a development standpoint.

In the past when people have had situations where they wanted essentially two configurations depending on the input file I've recommended using a wrapper script that switches the configuration file depending on the input. You can modify the environment variable `SMA_CONFIG` before launching the script to redirect to an alternative config.

For your case you would have two copies of autoProcess.ini, one for simple audio that converts to AC3 and one for lossless and redirect accordingly.
