### ISSUE TITLE
sonarr-sma & radarr-sma not working for me

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#1308]
I'm not an expert at all so I may be missing something here...

I recently setup a new server with the following in docker: nzbget, sonarr-sma, radarr-sma. I followed your instructions on radarr-sma and sonarr-sma but can't get nzbget to do anything after the download. What am I missing for nzbget to get it to post process?

I also tried to do a manual.py against the downloaded mkv from within the sonarr-sma docker but got an error that its missing guessit...

**Comment by hroman73** [comment]
with my setup i have sonarr, radarr, nzbget and nzbhydra...when i performed a search on either *arr i wouldn't see it in the nzbhydra logs. I then started to check that they could talk to each other and i think that was the problem. with ubuntu 20.04 i had to disable its internal dns and force it to use the network dns configured from network manager, the following article explained the steps:
https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

its now downloading a content and showing status on the *arr's as well as performing the mp4_automation :) 

Thank you very much for the help!

**Comment by mdhiggins** [comment]
Good stuff thanks for sharing the solution
