### ISSUE TITLE
Moving over to qBittorrent having trouble getting SMA to trigger

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1309]
I'm moving over to qBittorrent as I have found its about 80% faster than deluge 😱 .
I have installed the python package as required and filled in all details etc however when a torrent finish's nothing seems to happen, there's nothing in the log either so its like its not being called.

With Deluge I had to use a bat file cos calling the .py direct didn't work, would that help here aswell?

**Comment by mdhiggins** [comment]
Sounds like you need to update your deluge configuration cause there is no reason it should be 80% faster, but whatever you're free to use qBittorrent.

You might need a bat file its entirely dependent on how your registry is configured to handle .py files and your python environment setup but can't hurt to use one if its not executing which would suggest directly executing .py files isn't working

See this closed issue
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1291

**Comment by morpheus2n2** [comment]
Gave up on that idea, just couldn't get it to work, but did find a plug in for deluge that fix my slowness seems its a backend design ☹️  lmao
