### ISSUE TITLE
qBittorrent problems

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1312]
Ok after much playing around I have manged to get qBittorrtent to start triggering the script only this is what I get
```
C:\Users\morph>C:\Users\morph\AppData\Local\Programs\Python\Python38-32\python.exe C:\Converter\qBittorrentPostProcess.py sonarr udp://tracker.coppersurfer.tk:6969/announce D:\Downloads\To Convert\Counting.On.S11E08.The.Best.Duggar.Christmas.Pageant.Ever.1080p.WEB.H264-TXB[rarbg] D:\Downloads\To Convert\Counting.On.S11E08.The.Best.Duggar.Christmas.Pageant.Ever.1080p.WEB.H264-TXB[rarbg]
2020-08-26 22:26:06 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-08-26 22:26:06 - resources.readsettings - INFO - C:\Users\morph\AppData\Local\Programs\Python\Python38-32\python.exe
2020-08-26 22:26:06 - resources.readsettings - INFO - Loading config file C:\Converter\config\autoProcess.ini.
2020-08-26 22:26:06 - resources.readsettings - WARNING - Force-convert is true, so process-same-extensions is being overridden to true as well
2020-08-26 22:26:06 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\morph\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:
```

as per your advice in #1291 this is when I manually trigger it (from qBT the CMD will poop show this then shut really quick so I copied the string from the QBT log and tried to do a manual trigger)

**Comment by mdhiggins** [comment]
Doesn't look like you have enough command line arguments and the only reason its not yelling at you is because you also have spaces in earlier command line arguments so those are getting broken up to inappropriately fill in arguments

Arguments should be
```
Category, Tracker, RootPath, ContentPath , TorrentName, InfoHash
```

And as for any Windows command argument being executed from a command line if there are spaces it an argument it should be in quotes or it will be broken up into 2 arguments

**Comment by mdhiggins** [comment]
And of course verify your qBittorrent settings in autoProcess.ini, having any of those wrong will cause things to fail when it tries to communicate with qBittorrent

**Comment by morpheus2n2** [comment]
Interesting, cos [these](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1291#issuecomment-681100256) (link to other post) are how my QT look are they not quite right?

**Comment by mdhiggins** [comment]
I believe in that situation there was double quotes happening (""sonarr"") due to it being added at 2 levels

**Comment by morpheus2n2** [comment]
> I believe in that situation there was double quotes happening (""sonarr"") due to it being added at 2 levels

umm wonder why thats happening lol

**Comment by mdhiggins** [comment]
It's not happening for you, it happened for that other user (likely because qBittorrent adds the quotes and he also was adding the quotes in the batch file). 

Your problem is that you have no quotes. I can see your test command, you posted it.

```
C:\Users\morph>C:\Users\morph\AppData\Local\Programs\Python\Python38-32\python.exe C:\Converter\qBittorrentPostProcess.py sonarr udp://tracker.coppersurfer.tk:6969/announce D:\Downloads\To Convert\Counting.On.S11E08.The.Best.Duggar.Christmas.Pageant.Ever.1080p.WEB.H264-TXB[rarbg] D:\Downloads\To Convert\Counting.On.S11E08.The.Best.Duggar.Christmas.Pageant.Ever.1080p.WEB.H264-TXB[rarbg]
```

That's the one that's not correct
You only have 4 actual arguments there, but the last 2 paths have a space so you're getting 6 pseudo arguments which happens to be enough to fool the python script cause 6 extra parameters is technically what you're supposed to have, otherwise it would have stopped you from running it because you were missing the last 2 parameters (the torrent name and hash).

Its no surprise given the torrent hash is what's used to talk to qBittorrent via the API and form its url's. So instead of the hash which you did not provide it received `Convert\Counting.On.S11E08.The.Best.Duggar.Christmas.Pageant.Ever.1080p.WEB.H264-TXB[rarbg]` which is not correct

**Comment by morpheus2n2** [comment]
ahh ok so doing the direct copy of the execute command line form qBittorents log was not the best way to check what was going on

**Comment by morpheus2n2** [comment]
Ok this is a new one, going to turn debug on for the next as it failed again even after I made the chance you suggested, its still double quoting which make no sense as it seem to be auto adding them between picking up the Tag and then running the bat file

`(N) 2020-08-26T23:28:44 - Successfully moved torrent: Paw.Patrol.S01.1080p.NF.WEBRip.DDP5.1.x264-LAZY[rartv]. New path: D:\Downloads\To Convert
(N) 2020-08-26T23:28:44 - Torrent: Paw.Patrol.S01.1080p.NF.WEBRip.DDP5.1.x264-LAZY[rartv], running external program, command: C:\Converter\qBittorrentPostProcess.bat "sonarr" "" "D:\Downloads\To Convert\Paw.Patrol.S01.1080p.NF.WEBRip.DDP5.1.x264-LAZY[rartv]" "D:\Downloads\To Convert\Paw.Patrol.S01.1080p.NF.WEBRip.DDP5.1.x264-LAZY[rartv]" "Paw.Patrol.S01.1080p.NF.WEBRip.DDP5.1.x264-LAZY[rartv]" "e67fb8c85d8ee5bd87d6e0663706d12512a3f545"
(N) 2020-08-26T23:29:13 - Options were saved successfully.`

**Comment by mdhiggins** [comment]
Please post the logs and I'll take a look

Also please include these 3 items in your next post
1. qBittorrent settings in autoProcess
2. screenshot of your qBittorrent execute setting (similar to [this](https://user-images.githubusercontent.com/14253602/91353156-c6abe280-e7e2-11ea-9df1-fd4605d1cdaa.png))
3. your batch file

**Comment by morpheus2n2** [comment]
> Please post the logs and I'll take a look
> 
> Also please include these 3 items in your next post
> 
> 1. qBittorrent settings in autoProcess
> 2. screenshot of your qBittorrent execute setting (similar to [this](https://user-images.githubusercontent.com/14253602/91353156-c6abe280-e7e2-11ea-9df1-fd4605d1cdaa.png))
> 3. your batch file

Will do, just going to set a torrent off, have debug turned on as well in SMA.
Really do apricate all the help you give me recently with various things :D

**Comment by morpheus2n2** [comment]
Ok here's the Extract from qBittorrent Log

```
(N) 2020-08-26T23:52:50 - Successfully moved torrent: Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]. New path: D:\Downloads\To Convert
(N) 2020-08-26T23:52:50 - Torrent: Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg], running external program, command: C:\Converter\qBittorrentPostProcess.bat "sonarr" "http://tracker4.itzmx.com:2710/announce" "D:\Downloads\To Convert\Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "D:\Downloads\To Convert\Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "6da5d146a96187b9060c74914162d7d52d953bb8"
(N) 2020-08-26T23:52:53 - Successfully moved torrent: Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG. New path: D:\Downloads\To Convert
(N) 2020-08-26T23:52:53 - Torrent: Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG, running external program, command: C:\Converter\qBittorrentPostProcess.bat "" "" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "4271ce42b1cc742cc42fc31a33d2cc02c6c999f1"
```

SMA didn't trigger at all so no log file was even created :(

That screenshot to link is mine and hasn't changed same with the pic of the batch file from the same post pmsl
however here they are again :D 
![2020-08-26 (2)](https://user-images.githubusercontent.com/14253602/91365051-206ad780-e7f8-11ea-8337-c72e79e6e7e5.png)
![2020-08-26 (3)](https://user-images.githubusercontent.com/14253602/91365058-2496f500-e7f8-11ea-868e-e53724e878b4.png)

```
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = 192.168.1.2
port = 58846
ssl = False
username = morpheus2n2
password = *******
output-directory = 
```

**Comment by mdhiggins** [comment]
If you run that command manually

```
C:\Converter\qBittorrentPostProcess.bat "" "" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "4271ce42b1cc742cc42fc31a33d2cc02c6c999f1"
```

what do you see in command line? Also, it looks like you didn't set a category for that torrent so it won't actually process but the script should have started and complained about the lack of category

You could fake the category with this command for testing
```
C:\Converter\qBittorrentPostProcess.bat "radarr" "" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "D:\Downloads\To Convert\Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "Tales.from.the.Darkside.The.Movie.1990.1080p.BluRay.x265-RARBG" "4271ce42b1cc742cc42fc31a33d2cc02c6c999f1"
```

**Comment by morpheus2n2** [comment]
Ahh no that second on i didn't as it was already in h265 :D its the sonarr stuff thats not working at mo

**Comment by mdhiggins** [comment]
Well without a label/category the script will abort

Though you should see
"qBittorrent post processing started."

Followed by 
"No valid label detected."

**Comment by morpheus2n2** [comment]
Aye and that was the intention on that torrent however this one
```
(N) 2020-08-26T23:52:50 - Successfully moved torrent: Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]. New path: D:\Downloads\To Convert
(N) 2020-08-26T23:52:50 - Torrent: Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg], running external program, command: C:\Converter\qBittorrentPostProcess.bat "sonarr" "http://tracker4.itzmx.com:2710/announce" "D:\Downloads\To Convert\Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "D:\Downloads\To Convert\Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "Deadliest.Catch.S16E19.Rogue.Wave.Juggernaut.1080p.DISC.WEBRip.AAC2.0.x264-BOOP[rarbg]" "6da5d146a96187b9060c74914162d7d52d953bb8"  It was meant to run and didn't do anything lol
```

**Comment by mdhiggins** [comment]
What happens when you run that command manually?

**Comment by morpheus2n2** [comment]
Got that one to log woohoo lol
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5133146/sma.log)

**Comment by mdhiggins** [comment]
Alright so everything from the script side is working its just not able to connect to qBittorrent

Are you sure 58846 is the correct port? Looking at qBittorrent but the default port is 8080 so unless you specifically changed that, that's probably part of the failure

**Comment by morpheus2n2** [comment]
Holly shit that was it I think, its working with a manual trigger so I am guessing if that works the auto trigger will work, I stupidly copied the default Deluge port for it 🤦 

Can't thank you enough for all you do with this script and putting up with my stupidity lmao

**Comment by mdhiggins** [comment]
All good, just close this out if that fixed things

**Comment by morpheus2n2** [comment]
Yep working perfect thank you :)
