### ISSUE TITLE
New issues with Torrents, Script will still kick in even when no label/category is set (sorry)

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1313]
Rally sorry honestly I am.
Now I have it all working I have run it to a possible problem.

I was under the impression that if there was no label or category set for a download then the script would just error out and ignore it, however I have found that it will still kick in and convert things as normal.
It used to do it with Deluge as well but I just assumed it was a deluge bug.

**Comment by mdhiggins** [comment]
Looks like when I migrated from labels being exact to being prefixes there was a bug that allowed blank labels to sneak through since a blank label is technically a prefix for anything

7cb79556a4ff51d6dc6d2c61a01169678ca805c7

That should fix it

**Comment by mdhiggins** [comment]
e10c9b8d8bfee28d7cd18b16c451731f1c3391db

Actually that should fix it, shouldn't commit before coffee

**Comment by morpheus2n2** [comment]
> [e10c9b8](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/e10c9b8d8bfee28d7cd18b16c451731f1c3391db)
> 
> Actually that should fix it, shouldn't commit before coffee

Pmsl love it :D Will test once home

**Comment by morpheus2n2** [comment]
Yep working again 👍
