### ISSUE TITLE
Show disambiguator still asks for show's TVDB ID even though TVDB is not supported

### ISSUE THREAD

**Issue by trolley** [mdhiggins/sickbeard_mp4_automator#1315]
When trying to manually tag a TV series that can't be automatically identified a disambiguator is shown that asks for a series ID from one of several sources, including TVDB. It looks like TVDB support was removed though, so if you enter that ID the manual process just fails out.

Searching the source shows TVDB referenced in a few of the post-processing scripts: https://github.com/mdhiggins/sickbeard_mp4_automator/search?q=tvdb&unscoped_q=tvdb

**Comment by mdhiggins** [comment]
This is working as intended

The API for TVDB has been removed but TMDB supports referencing and searching for shows by the TVDB ID which is what that feature is for. This is confirmed to be working and is the primary way that Sonarr/SB variants provide identifiers for shows for processing

Same is true for the IMDB ID
