### ISSUE TITLE
Encoding 4k File has wrong bitrate

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1317]
When I convert a 4k file it drops the bit rate right down to 426kbps this is far lower than what I have set or that will work.
Or is 4k now supported and this is what's doing it?

**Comment by mdhiggins** [comment]
Depends on many many factors

**Comment by morpheus2n2** [comment]
lol, figured.
I Think I pinned it down to HW encoding/decoding as when I ran it again with it disabled it come out right I just had the Bitrate to low this time myself
