### ISSUE TITLE
AttributeError: module 'guessit' has no attribute 'guessit'

### ISSUE THREAD

**Issue by Rhainland** [mdhiggins/sickbeard_mp4_automator#1321]
Upon running manual.py on a test file, i get this message;
AttributeError: module 'guessit' has no attribute 'guessit'

Im using python3, the system is running the "old" version of sickbeard_mp4_automator through nzbget on the same system perfectly fine.

Both the new and old, are using the same python 3 binary.

guessit v 1.0.3 is installed.

The wiki doesnt state if guessit 2, is required. Is this the case?

**Comment by mdhiggins** [comment]
Yes the script requires the latest version of guess it now
