### ISSUE TITLE
are .ass Subs supported if so how

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1322]
I have some Anime that use .ass subs (the ones that get places in various locations on the screen)
Can these be added if so what do I need to make sure is set properly in my autoprocess, Cos I would love for these to get just embed if possible and for other formats to be converted if there needed

**Comment by mdhiggins** [comment]
Nothing special the only limitations are what FFMPEG can do. ASS subtitles I believe are only supported by MKVs for embedding but you'd have to double check the FFMPEG and MKV specifications. The whole script handles subtitle formats dynamically now there's no specific limitations to formats beyond FFMPEG and the container you want but you'll need to look this up in FFMPEG docs

**Comment by morpheus2n2** [comment]
No worries, I'm happy to leave them floating in the folder :D

**Comment by mdhiggins** [comment]
That being said if they're in the folder and not image based then the script should pick them up and embed them and convert to mov_text (assuming you're using mp4). Image based subs are mkv only. Just keep them the same name as the file with the language code (name.eng.ass) and it should detect them. No extension limitations anymore

**Comment by morpheus2n2** [comment]
Yeah thats what I am trying to avoid as mov_text places the sabs in just the one location (bottom of screen normally) where as the .ass files will place English translated text all over the screen for things like translating Jap txt on signs in the street or etc :D
