### ISSUE TITLE
can't get vaapi to work...

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#1323]
i think i followed all the requirements but i still can't get it to use vaapi...

**docker-compose:**
devices:
  - /dev/dri:/dev/dri

**autoProcess.ini:**
codec = h265vaapi

when i try a manual.py on an mkv file i get the following error:
Device creation failed: -12.
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Cannot allocate memory
Error parsing global options: Cannot allocate memory

**Comment by mdhiggins** [comment]
Could you post your full docker-compose settings for that container?

**Comment by hroman73** [comment]
sonarr:
        hostname: sonarr
        image: mdhiggins/sonarr-sma
        container_name: sonarr
        depends_on:
            - nzbget
        volumes:
            - /opt/sonarr/config:/config
            - /opt/sma:/usr/local/sma/config
            - /home/hroman/Downloads:/downloads
            - /home/hroman/Videos/TV:/tv
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
            - HOST=10.0.0.3
            - SMA_PATH=/usr/local/sma
            - SMA_UPDATE=true
            - UMASK_SET=022
        ports:
            - 8989:8989
        restart: unless-stopped
        devices:
            - /dev/dri:/dev/dri

**Comment by mdhiggins** [comment]
You'll need to use the VAAPI version of the container, the base build doesn't include it, the readme includes an excerpt that shows how you set this up

```
services:
  sonarr:
    container_name: sonarr
    build:
      context: https://github.com/mdhiggins/sonarr-sma.git#build
      args:
        - ffmpeg_tag=vaapi
```

Remove the `image: mdhiggins/sonarr-sma` line too

Also, verify that you actually have the device `/dev/dri/renderD128` in your `/dev/dri` directory cause it might be failing cause that doesn't exist (in which case you may not have hardware support for VAAPI, or your device is named differently for some reason).

**Comment by hroman73** [comment]
i knew i was missing something...let me try that and get back to you....thank you for your prompt response!!!

**Comment by hroman73** [comment]
different error this time but i think it may be the actual file i'm converting?

[hevc_vaapi @ 0x55ade9c36480] No usable encoding profile found.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by mdhiggins** [comment]
Yep looks like the options are working now and the conversion is starting, now you just need to tweak your FFMPEG settings

Feel free to post your options or logs from that failed conversion and I can  take a look and see if anything obvious would be causing that failure

**Comment by hroman73** [comment]
i'm a novice at this so is there any reference somewhere for the settings? i basically want to take files and all import to h265...

**Comment by mdhiggins** [comment]
Just post your autoProcess settings and I'll take a look and make suggestions

**Comment by hroman73** [comment]
thank you so much...

[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va, vaapi
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = vaapi:/dev/dri/renderD128
output-directory =
output-format = mp4
output-extension = mp4
temp-extension =
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
detailed-progress = False
preopts =
postopts =
hwaccel-output-format = vaapi:vaapi

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = thumb
sanitize-disposition =

[Video]
codec = h265vaapi
max-bitrate = 0
crf = -1
crf-profiles =
codec-parameters =
max-width = 0
profile =
max-level = 0.0
pix-fmt =
filter =
force-filter = False
preset =
dynamic-parameters = False

[HDR]
space = bt2020nc
transfer = smpte2084
primaries = bt2020
codec-parameters =
filter =
force-filter = False
pix-fmt =
preset =

[Audio]
codec = ac3
languages = eng
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 192
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter =
force-filter = False
sample-rates =
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions =
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 192
first-stream-only = False
move-after = False
filter =
force-filter = False

[Subtitle]
codec = mov_text
codec-image-based =
languages = eng
default-language = eng
first-stream-of-language = False
encoding =
burn-subtitles = False
burn-dispositions =
download-subs = True
download-hearing-impaired-subs = False
download-providers = addic7ed, podnapisi, thesubdb, opensubtitles
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions =
unique-dispositions = False
attachment-codec =

[Sonarr]
host = 10.xxx
port = 8989
apikey = a;lsdjf;lasdjf[poa
ssl = False
webroot =

[Radarr]
host = 10.xxx
port = 7878
apikey = 1ja;sldkjf;lasdjkf
ssl = False
webroot =

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey =
webroot =
username =
password =

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey =
webroot =
username =
password =

[CouchPotato]
host = localhost
port = 5050
username =
password =
apikey =
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot =

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory =

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username =
password =
output-directory =
remove = False

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before =
action-after =
host = localhost
port = 8080
ssl = False
username =
password =
output-directory =

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before =
action-after =
host = localhost
ssl = False
port = 8080
username =
password =
output-directory =

[Plex]
host = 10...
port = 32400
refresh = True
token = ;alskdjfaoierua;sdf

**Comment by mdhiggins** [comment]
Hm pretty minimal stuff there

Could you also post the logs from that failed conversion? I'll see if I can find the issue

**Comment by mdhiggins** [comment]
```
[Video]
codec = h265vaapi, h265, hevc
crf = 18
```

You can try adding a crf to set some level of quality preservation though I don't think that has anything to do with your error

I also added h265/hevc to your video codec list so that if something is in the correct format that they can be remuxed and save cpu time and preserve quality (though for testing purposes don't add this until everything is working)

I would also move the vaapi decoders to the front of of the priority list so that you're not potentially using a conflicting decoder/encoder
```
hwaccels = vaapi, dxva2, cuvid, qsv, d3d11va
```

**Comment by hroman73** [comment]
as requested, here is a copy of the log of the file i'm trying to test convert. My goal is to eventually convert my entire library and all incoming shows to h265 using your scripts and adding the vaapi to speed up the process

2020-09-12 23:29:46 - MANUAL - INFO - Manual processor started.
2020-09-12 23:29:46 - MANUAL - INFO - /usr/local/sma/venv/bin/python3
2020-09-12 23:29:46 - MANUAL - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2020-09-12 23:29:47 - MANUAL - INFO - Matched TV episode as The Strain (TMDB ID: 47640) S04E03
2020-09-12 23:29:47 - MANUAL - INFO - Processing The Strain Season 04 Episode 03 - One Shot
2020-09-12 23:29:47 - MANUAL - INFO - Input Data
2020-09-12 23:29:47 - MANUAL - INFO - {
    "format": "matroska,webm",
    "format-fullname": "unknown",
    "video": {
        "index": 0,
        "codec": "h264",
        "pix_fmt": "yuv420p",
        "profile": "100",
        "fps": 25.0,
        "dimensions": "1280x720",
        "level": 3.1,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "channels": 2,
            "samplerate": 48000,
            "language": "fra",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        },
        {
            "index": 2,
            "codec": "aac",
            "channels": 2,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        }
    ],
    "subtitle": [
        {
            "index": 3,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "language": "fra"
        }
    ],
    "attachment": []
}
2020-09-12 23:29:47 - MANUAL - INFO - Reading video stream.
2020-09-12 23:29:47 - MANUAL - INFO - Video codec detected: h264.
2020-09-12 23:29:47 - MANUAL - INFO - Pix Fmt: yuv420p.
2020-09-12 23:29:47 - MANUAL - INFO - Profile: 100.
2020-09-12 23:29:47 - MANUAL - INFO - Video codec parameters None.
2020-09-12 23:29:47 - MANUAL - INFO - Creating h265vaapi video stream from source stream 0.
2020-09-12 23:29:47 - MANUAL - INFO - Reading audio streams.
2020-09-12 23:29:47 - MANUAL - INFO - Audio detected for stream 2 - aac eng 2 channel.
2020-09-12 23:29:47 - MANUAL - INFO - Creating copy audio stream from source stream 2.
2020-09-12 23:29:47 - MANUAL - INFO - Audio detected for stream 1 - aac fra 2 channel.
2020-09-12 23:29:47 - MANUAL - INFO - Default audio stream set to eng copy 2 channel stream [default-more-channels: True].
2020-09-12 23:29:47 - MANUAL - INFO - Reading subtitle streams.
2020-09-12 23:29:47 - MANUAL - INFO - Text-based subtitle detected for stream 3 - subrip fra.
2020-09-12 23:29:47 - MANUAL - INFO - Attempting to download subtitles.
2020-09-12 23:29:47 - MANUAL - ERROR - Unable to download subtitles.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1233, in downloadSubtitles
    subtitles = subliminal.download_best_subtitles([video], languages, hearing_impaired=self.settings.hearing_impaired, providers=self.settings.subproviders)
  File "/usr/local/sma/venv/lib/python3.6/site-packages/subliminal/core.py", line 651, in download_best_subtitles
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
  File "/usr/local/sma/venv/lib/python3.6/site-packages/subliminal/core.py", line 139, in list_subtitles
    provider_subtitles = self.list_subtitles_provider(name, video, languages)
  File "/usr/local/sma/venv/lib/python3.6/site-packages/subliminal/core.py", line 102, in list_subtitles_provider
    if not provider_manager[provider].plugin.check(video):
  File "/usr/local/sma/venv/lib/python3.6/site-packages/stevedore/extension.py", line 356, in __getitem__
    return self._extensions_by_name[name]
KeyError: 'addic7ed'
2020-09-12 23:29:47 - MANUAL - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2020-09-12 23:29:47 - MANUAL - INFO - vaapi hwaccel is supported by this ffmpeg build and will be used [hwaccels].
2020-09-12 23:29:47 - MANUAL - INFO - Output Data
2020-09-12 23:29:47 - MANUAL - INFO - {
    "source": [
        "/tv/The Strain/Season 04/The Strain - S04E03.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "h265vaapi",
        "map": 0,
        "bitrate": 3567.59,
        "crf": 18,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "title": "HD",
        "debug": "video",
        "device": "sma"
    },
    "audio": [
        {
            "map": 2,
            "codec": "copy",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo",
            "debug": "universal-audio"
        }
    ],
    "subtitle": [],
    "attachment": []
}
2020-09-12 23:29:47 - MANUAL - INFO - Preopts
2020-09-12 23:29:47 - MANUAL - INFO - [
    "-init_hw_device",
    "vaapi=sma:/dev/dri/renderD128",
    "-hwaccel_device",
    "sma",
    "-hwaccel",
    "vaapi",
    "-hwaccel_output_format",
    "vaapi"
]
2020-09-12 23:29:47 - MANUAL - INFO - Postopts
2020-09-12 23:29:47 - MANUAL - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2020-09-12 23:29:47 - MANUAL - INFO - Downloaded Subtitles
2020-09-12 23:29:47 - MANUAL - INFO - []
2020-09-12 23:29:47 - MANUAL - INFO - Starting conversion.
2020-09-12 23:29:48 - MANUAL - INFO - FFmpeg command:
2020-09-12 23:29:48 - MANUAL - INFO - ======================
2020-09-12 23:29:48 - MANUAL - INFO - /usr/local/bin/ffmpeg -init_hw_device vaapi=sma:/dev/dri/renderD128 -hwaccel_device sma -hwaccel vaapi -hwaccel_output_format vaapi -i /tv/The Strain/Season 04/The Strain - S04E03.mkv -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=HD -tag:v hvc1 -qp 18 -filter_hw_device sma -vf format=nv12|vaapi,hwupload -c:a:0 copy -map 0:2 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /tv/The Strain/Season 04/The Strain - S04E03.mp4
2020-09-12 23:29:48 - MANUAL - INFO - ======================
2020-09-12 23:29:48 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1485, in convert
    for timecode, debug in conv:
  File "/usr/local/sma/converter/__init__.py", line 305, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/usr/local/sma/converter/ffmpeg.py", line 707, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2020-09-12 23:29:48 - MANUAL - ERROR - /usr/local/bin/ffmpeg -init_hw_device vaapi=sma:/dev/dri/renderD128 -hwaccel_device sma -hwaccel vaapi -hwaccel_output_format vaapi -i /tv/The Strain/Season 04/The Strain - S04E03.mkv -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=HD -tag:v hvc1 -qp 18 -filter_hw_device sma -vf format=nv12|vaapi,hwupload -c:a:0 copy -map 0:2 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /tv/The Strain/Season 04/The Strain - S04E03.mp4
2020-09-12 23:29:48 - MANUAL - ERROR - ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, matroska,webm, from '/tv/The Strain/Season 04/The Strain - S04E03.mkv':
  Metadata:
    encoder         : libebml v1.3.9 + libmatroska v1.5.2
    creation_time   : 2019-11-12T15:38:51.000000Z
  Duration: 00:40:11.01, start: 0.000000, bitrate: 3567 kb/s
    Stream #0:0(fre): Video: h264, yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      title           : The Strain S04E03
      BPS-eng         : 3308401
      DURATION-eng    : 00:40:10.960000000
      NUMBER_OF_FRAMES-eng: 60274
      NUMBER_OF_BYTES-eng: 997052874
      _STATISTICS_WRITING_APP-eng: mkvmerge v38.0.0 ('The Silent Type') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-12 15:38:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(fre): Audio: aac, 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Français AAC 2.0
      BPS-eng         : 128000
      DURATION-eng    : 00:40:11.008000000
      NUMBER_OF_FRAMES-eng: 113016
      NUMBER_OF_BYTES-eng: 38576252
      _STATISTICS_WRITING_APP-eng: mkvmerge v38.0.0 ('The Silent Type') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-12 15:38:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: aac, 48000 Hz, stereo, fltp
    Metadata:
      title           : Anglais AAC 2.0
      BPS-eng         : 128000
      DURATION-eng    : 00:40:11.008000000
      NUMBER_OF_FRAMES-eng: 113016
      NUMBER_OF_BYTES-eng: 38576305
      _STATISTICS_WRITING_APP-eng: mkvmerge v38.0.0 ('The Silent Type') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-12 15:38:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(fre): Subtitle: subrip
    Metadata:
      title           : Français
      BPS-eng         : 45
      DURATION-eng    : 00:39:59.080000000
      NUMBER_OF_FRAMES-eng: 449
      NUMBER_OF_BYTES-eng: 13586
      _STATISTICS_WRITING_APP-eng: mkvmerge v38.0.0 ('The Silent Type') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-12 15:38:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_vaapi))
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hevc_vaapi @ 0x5620c9ec5d00] No usable encoding profile found.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

2020-09-12 23:29:48 - MANUAL - ERROR - /tv/The Strain/Season 04/The Strain - S04E03.mp4 deleted.
2020-09-12 23:29:48 - MANUAL - ERROR - There was an error processing file /tv/The Strain/Season 04/The Strain - S04E03.mkv, no output data received
root@sonarr:/usr/local/sma/config#

**Comment by hroman73** [comment]
i also updated my autoProcess.ini file as per your recommendations except to adding the other codecs since i'm trying to get the h265vaapi working...

**Comment by mdhiggins** [comment]
Looks like you need your profile set maybe

Try "main"

**Comment by hroman73** [comment]
after more investigating it turns out my gpu supports h265 decoding only...thanks for the help though...
