### ISSUE TITLE
Feature Request: Web Frontend

### ISSUE THREAD

**Issue by thecyberdevl** [mdhiggins/sickbeard_mp4_automator#1324]
Something like the one in this project: https://github.com/Josh5/unmanic

**Comment by mdhiggins** [comment]
Definitely no plans to do this, not in the spirit of the project; its designed to integrate with other programs not be standalone

**Comment by sbergwall** [comment]
@thecyberdevl You might want to look at https://github.com/HaveAGitGat/Tdarr also.
