### ISSUE TITLE
Can you skip HW encoding for certain media

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1327]
This one I actually don't think is possible but there's no harm is asking.
After we spent all that time getting [HDR](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1285) to work (and it dose wonderfully thank you so much)

I wasted to try and not have to use a separate copy of the script just for 4K HDR content.

So is possible at all for it to use HW encoding for everything expect if it received a file with HDR or in 4K  (as 99% of HDR content is 4K anyways)

What I am hoping is that it will do my 1080p stuff just fine and happily via HW, but when the random 4K HDR file is picked up it uses software only basically automatically removing the HW options.

I know this is probably not likely nor easy to achieve.

I can't thank you enough for this script and the effort you put into it.

**Comment by mdhiggins** [comment]
Nah not really possible and hopefully not needed whenever FFMPEG fixes that bug

Probably not worth the development time since the main purpose stems from trying to combat a bug in FFMPEG that should really just be fixed

**Comment by morpheus2n2** [comment]
Thought as much, its cool I only have my very fav shows/films in 4k on Plex so running a separate script just to remux them is no big deal :)
Thank you for looking into it though really apricated

**Comment by Weezzel** [comment]
Very good question, I was trying to find this out myself. Without making several folders like: HDR folder and NON-HDR folders with 2 different scripts running HW and Non-HW, But wasn't able to. I just settled on 2 Folders and 2 scripts to run on the associated folders. Since my library is so large I need the speed of HW to get through it all before next year..lol
