### ISSUE TITLE
Question? Is it possible to HWaccel with a VAAPI-based encoder and still get a hevc_nvenc formated movie\ tv show

### ISSUE THREAD

**Issue by Weezzel** [mdhiggins/sickbeard_mp4_automator#1329]
taken from:
[Nvidia Dev](https://forums.developer.nvidia.com/t/encoding-hevc-hdr-bt2020-lost/47137)

At the present, HDR signalling is implemented in FFmpeg, as shown in the example below using a filter and a VAAPI-based encoder for reference.

For instance, with VAAPI, you’ll find support for features such as OpenCL-based tone map filters, allowing for HDR(HDR10/HLG) to SDR conversion with tone-mapping, with the example shown below, using a hardware device derived from the VAAPI initialization sequence:

ffmpeg -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device \
opencl=ocl@va -hwaccel vaapi -hwaccel_device va -hwaccel_output_format \
vaapi -i INPUT -filter_hw_device ocl -filter_complex \
'[0:v]hwmap,tonemap_opencl=t=bt2020:tonemap=linear:format=p010[x1]; \
[x1]hwmap=derive_device=vaapi:reverse=1' -c:v hevc_vaapi -profile 2 OUTPUT
The same filter chain can also be derived from an existing OpenCL device on the platform, say, with an NVIDIA GPU, as shown below, which assumes that the NVIDIA GPU is the first OCL device on the first platform (modify as needed):

ffmpeg -init_hw_device opencl=opencl:1.0  \
-hwaccel nvdec  \
-i INPUT -filter_hw_device opencl -filter_complex \
'[0:v]hwmap,tonemap_opencl=t=bt2020:tonemap=linear:format=p010[x1]; \
[x1]hwmap=derive_device=opencl' -c:v hevc_nvenc -preset:v slow 2 OUTPUT

**Comment by mdhiggins** [comment]
Honestly I don't see any way to automate this in any sort of reliable fashion

Definitely not possible with the current logic but I'm open to a pull request or proposal as to how this should function in a dynamic sense

**Comment by mdhiggins** [comment]
That being said if you wanted to apply this globally and statically you could probably get it in through preopts and postopts

**Comment by Weezzel** [comment]
very good I will look into more. Closing Question for now.
