### ISSUE TITLE
NZBGet Logging Level

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1330]
If I wanted to remove lines like below from my sma.log file, what's an appropriate value for logging level in the logging.ini file in the nzbget section?

> 2020-09-24 15:22:00 - NZBGetPostProcess - INFO - 1
2020-09-24 15:22:00 - NZBGetPostProcess - INFO - 1
2020-09-24 15:22:01 - NZBGetPostProcess - INFO - 2
2020-09-24 15:22:01 - NZBGetPostProcess - INFO - 3
2020-09-24 15:22:02 - NZBGetPostProcess - INFO - 3
2020-09-24 15:22:02 - NZBGetPostProcess - INFO - 4
2020-09-24 15:22:03 - NZBGetPostProcess - INFO - 4 

Logging.ini file below

	[loggers]
	keys = root, manual, nzbget

	[handlers]
	keys = consoleHandler, nzbgetHandler, fileHandler, manualHandler

	[formatters]
	keys = simpleFormatter, minimalFormatter, nzbgetFormatter

	[logger_root]
	level = DEBUG
	handlers = consoleHandler, fileHandler

	[logger_nzbget]
	level = INFO
	handlers = nzbgetHandler, fileHandler
	propagate = 0
	qualname = NZBGetPostProcess

	[logger_manual]
	level = DEBUG
	handlers = manualHandler, fileHandler
	propagate = 0
	qualname = MANUAL

	[handler_consoleHandler]
	class = StreamHandler
	level = INFO
	formatter = simpleFormatter
	args = (sys.stdout,)

	[handler_nzbgetHandler]
	class = StreamHandler
	level = INFO
	formatter = nzbgetFormatter
	args = (sys.stdout,)

	[handler_manualHandler]
	class = StreamHandler
	level = INFO
	formatter = minimalFormatter
	args = (sys.stdout,)

	[handler_fileHandler]
	class = handlers.RotatingFileHandler
	level = DEBUG
	formatter = simpleFormatter
	args = ('%(logfilename)s', 'a', 10485760, 7)

	[formatter_simpleFormatter]
	format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
	datefmt = %Y-%m-%d %H:%M:%S

	[formatter_minimalFormatter]
	format = %(message)s
	datefmt =

	[formatter_nzbgetFormatter]
	format = [%(levelname)s] %(message)s
	datefmt =

**Comment by mdhiggins** [comment]
No way to do this through options though this feature was requested so people could see progress

You can just comment out this line in NZBGetPostProcess.py to knock it out though

```
def progressOutput(timecode, debug):
    # log.info(timecode)
    log.debug(debug)
```

**Comment by mdhiggins** [comment]
Actually, if you wanted to test something, does changing that line to 

```
def progressOutput(timecode, debug):
    print("%d%%" % timecode)
    log.debug(debug)
```

allow you to still see the progress in NZBGet without clogging things up in the logs?

**Comment by johnwchambers** [comment]
change made, i'll check on the logs in a couple hours and see if the lines are still omitted.

**Comment by johnwchambers** [comment]
So it looks like on the download tab of nzbget it shows like the screenshot from above. But when I look on the messages tab, it's printing the percentages just fine there. Log file is still clean as I stated before as well. Just figured I'd post additional information is all.

![image](https://user-images.githubusercontent.com/752262/94878054-3e7ec400-0497-11eb-8d21-9e5d2bec62b5.png)

**Comment by mdhiggins** [comment]
Thanks for the follow up, I guess that's better than nothing until they open up a progress API
