### ISSUE TITLE
Issue with Unknown Audio streams?

### ISSUE THREAD

**Issue by dramirvf** [mdhiggins/sickbeard_mp4_automator#1333]
Hi,

I am using MP4 Automator in Radarr to tag my downloaded media. My "output-format" and "output-extension" in **autoProcess.ini** is set to "mp4".

As it is very common, many of the downloaded MP4 and MKV files have "Unknown" audio streams. In order to fix the issue and change "Unknown" audio streams to "English", I have set the "default-language" to "eng" in the Audio section of **autoProcess.ini**, as below:

[Audio]
codec = AC3, DTS, EAC3, AAC
languages = 
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 0
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False

The issue is that only "Unknown" audio streams in the file formats which undergo processing will have their "Unknown" audio streams changed to "English". Therefore all "Unknown" audio streams in MKV files are corrected, since MKV files will finally convert to MP4 and therefore they are all processed. However, MP4 files still contain "Unknown" audio streams, since input and output format is the same.

In order to resolve the issue, I set "process-same-extensions" to **True**, so MP4 files should also get processed. Now, the  MP4 files which will be processed **"in the future"** will have no issues.

But what about the already downloaded and tagged MP4 files! In order to solve the issue, I tried to process them manually, through running **manual.py**, but I got the following message:

**"Input and output extensions match and the file appears to have already been processed by SMA, enable force-convert to override [force-convert: False]."**

Initially I tried to remove the full TMDB tag from the already tagged MP4. But it did not resolve the issue and it looks like "MP4 Automator" has a cache somewhere which recognizes that this particular MP4 file has already been processed by SMA. To my surprise, even renaming the MP4 file itself did not resolve the issue and it still recognizes that this file has already been processed by SMA (although with another filename).

I had no choice but to set the "force-convert" to "True". After running **manual.py**, the file was processed and the issue with "Unknown" audio stream was resolved. But here I have changed a setting (force-convert), which might affect some other scenarios as well, and I think it might not be wise to keep "force-convert" to "True" forever.

I am now facing with hundreds of already downloaded and tagged MP4 files which needs adjustment for "Unknown" audio streams. Is there any simpler way to resolve the issue with already tagged files with "Unknown" audio streams?

Thanks

**Comment by mdhiggins** [comment]
You did everything right and that's pretty much the exact scenario that force-convert was added for. 

Biggest thing to be cautious of is the use of universal-audio or any options such as copy-original that could result in stream duplication when processing already converted content

**Comment by dramirvf** [comment]
> You did everything right and that's pretty much the exact scenario that force-convert was added for.
> 
> Biggest thing to be cautious of is the use of universal-audio or any options such as copy-original that could result in stream duplication when processing already converted content

Is there a way to bulk process MP4 files again through Radarr so I make sure that the correct TMDB IDs are passed to SMA?
I have tried to bulk process through running **manual.py**, but some TMDB IDs are being guessed incorrectly.

**Comment by mdhiggins** [comment]
The workflow I've used for bulk processing is that I've moved the files to a temp directory and then I ran everything through 'manual import' in radarr which does trigger a reprocess and passes the metadata again

**Comment by dramirvf** [comment]
> The workflow I've used for bulk processing is that I've moved the files to a temp directory and then I ran everything through 'manual import' in radarr which does trigger a reprocess and passes the metadata again

Excellent!

**Comment by mdhiggins** [comment]
The manual process will also restore them to their final location.

You may loose some information about the release quality (WebDL etc) so a way to avoid that is to include that in your filename before you redo the manual import which can be configured in Radarr. Ideally just include as much information as possible in the filename and then you can always do a batch rename in Radarr afterward if you don't want that long term
