### ISSUE TITLE
qBittorrentPostProcess.py error NameError: name 'path' is not defined

### ISSUE THREAD

**Issue by yekul** [mdhiggins/sickbeard_mp4_automator#1335]
> 2020-10-04 00:12:50 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-10-04 00:12:50 - resources.readsettings - INFO - C:\Python\python.exe
2020-10-04 00:12:50 - resources.readsettings - INFO - Loading config file C:\Users\WTFLU\Downloads\sickbeard_mp4_automator-master\config\autoProcess.ini.
2020-10-04 00:12:50 - qBittorrentPostProcess - INFO - Single File Torrent
2020-10-04 00:12:50 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "C:\Users\WTFLU\Downloads\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 139, in <module>
    newpath = os.path.join(path, ("%s-%s" % (name, suffix)))
NameError: name 'path' is not defined

Trying to get the qBittorrentPostProcess working inside a virtual machine on the same PC running Sonarr/SAB (in native windows). Only way I could see it possible to get it to work is do a full install of SMA, Python, FFmpeg and also run it on the VM. So i'm using SMA on native windows for SAB, and another SMA inside virtual machine for qbittorrent. So did all that and i'm testing the run external program which keeps falling over. When I manually run it I run into the issue above. 

Problem is I have so many variables i'm not sure exactly what it's referencing when it's talking about the path so not too sure where to start troubleshooting.

**Comment by mdhiggins** [comment]
b3f35022b99d0c3a527b6893314dd85a05e90245

See if that fixes it

**Comment by yekul** [comment]
It fixes the line 139 issue, now jumping down to 145: 

> 2020-10-04 01:17:31 - qBittorrentPostProcess - ERROR - Unexpected exception.
> Traceback (most recent call last):
>   File "C:\Users\WTFLU\Downloads\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 145, in <module>
>     os.mkdir(newpath)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\WTFLU\\Downloads\\Transfer to server\\temp\\testfile.mkv\\testfile.mkv-copy'

**Comment by mdhiggins** [comment]
16de6c434a73a392a9031c4a3371de5224960ea1

Alright this should do it

**Comment by yekul** [comment]
So very very close, delete folder bugs out, but there's also a 'bonus' issue to follow: 

> 2020-10-04 03:19:36 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-10-04 03:19:36 - resources.readsettings - INFO - C:\Python\python.exe
2020-10-04 03:19:36 - resources.readsettings - INFO - Loading config file C:\Users\WTFLU\Downloads\sickbeard_mp4_automator-master\config\autoProcess.ini.
2020-10-04 03:19:36 - qBittorrentPostProcess - INFO - Single File Torrent
2020-10-04 03:19:36 - qBittorrentPostProcess - INFO - Passing C:\Users\WTFLU\Downloads\Transfer to server\temp\testfile-copy directory to Sonarr.
2020-10-04 03:19:36 - autoprocess.sonarr - INFO - Sonarr notifier started.
2020-10-04 03:19:36 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'C:\Users\WTFLU\Downloads\Transfer to server\temp\testfile-copy'.
2020-10-04 03:19:36 - autoprocess.sonarr - INFO - Sonarr response: queued.
2020-10-04 03:19:36 - qBittorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "C:\Users\WTFLU\Downloads\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 199, in <module>
    os.rmdir(delete_dir)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\WTFLU\\Downloads\\Transfer to server\\temp\\testfile-copy'

The bonus issue is that it seems to communicate with the native windows Sonarr install just fine (huzzah), but it topples over on the import scan giving this: 
Folder/File specified for import scan [C:\Users\WTFLU\Downloads\Transfer to server\temp\testfile-copy] doesn't exist.

The mapping is done in Sonarr. I can manually import it just fine by using the mapped location. I'm really not sure why it is working fine manually but toppling over the with script when it's essentially asking it to do the same thing?

**Comment by mdhiggins** [comment]
The delete error is ok and not unexpected and shouldn't create any problems

Is that the correct directory that its telling it to scan? Does it exist? And that directory that its passing to, does it correspond to the directory  as Sonarr sees it? When using virtual environments you'll need parity between the directories or the API call won't work

**Comment by yekul** [comment]
Yeah I thought perhaps the deletion was failing because the import was also failing. 

It's the correct directory, and it definitely exists. However I think Sonarr is not taking into account the Remote Path Mapping options; in which case it wouldn't be able to find it. If I do a manual import to the remote mapped location via Sonarr interface it has no problems finding and importing. But I suspect it's not triggering with the script and is blindly looking for a location that simply doesn't exist. 

I'm not really sure how to work around this.

**Comment by yekul** [comment]
Found a thread from a year or so ago which noted that if using the API to request an import the remote path mappings won't be applied. I guess that's what's happening here. Bummer.

**Comment by mdhiggins** [comment]
Unfortunately that's something handled at the Sonarr API level so I don't have much control over that

You might be able to solve this with simlinks at the operating system level

What do your relative paths look like?

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by mdhiggins** [comment]
Closing this for now since script issue is fixed but feel free to continue discussion.

**Comment by yekul** [comment]
Was just having a shower thinking about this and was headed down the same path (symbolic links). 

I could in theory map a network drive location so they could match on both systems but I run into a few issues. qbittorrent will not let me set a network map drive (for example z:\shared\) as a default save path, it will only allow \\host\shared style. Problem is the share is to allow full speed between Windows and the VM, and the share in the form \\host\shared doesn't actually exist on the native Windows. Which i'm not sure if symbolic links will work for, i'll have a read as i've only used them for basic things before like tricking OneDrive. I might try Deluge and see if it lets me set a G:\shared type input where qbittorrent does not. I could use the IP address which would resolve that issue, but also make a much bigger one (transferring files between VM and windows destroys the CPU unless it's a designated share folder, and cripples transfer speeds). 

I had been a more basic structure in some of the above tests as I didn't want to add another layer of issues to the mix, but the relative paths currently are: 
remote path: \\vmware-host\Shared Folders\shared
local path: C:\Users\server\Downloads\shared\

And yes no problem this is definitely resolved just trying to find a round about way to get where I want to be. Appreciate your help, at least I know where the limitation is now and can begin trying to work it out.

**Comment by mdhiggins** [comment]
Try this

mklink /D C:\Users\server\Downloads\shared \\vmware-host\Shared Folders\shared

**Comment by yekul** [comment]
Unfortunately no joy, gives me a system cannot find the specified path error. Going to try Deluge and see if it lets me use a network map to save locations to.

**Comment by mdhiggins** [comment]
Where you seeing that error? From OS level it should be the same

Could try a hard linke

```
mklink /D /H C:\Users\server\Downloads\shared \\vmware-host\Shared Folders\shared
```

**Comment by yekul** [comment]
Well tried a whole heap of variations on the symbolic linking and nothing worked, either on the OS level or VM level. On the OS level it cannot even see \\vmware-host because it only exists inside the VM. There's a lot of limitations surrounding it with NTFS volume requirements, local volumes, etc. Because of how the VM treats the shares, the storage drives become HGFS volumes it seems. I dunno, i've tried every way I can think of right now. I will try set up Deluge tomorrow and see if it can bypass my mapped network drive issues which should in theory make everything work right off the bat, but I remember I tried to use Deluge in the past and it was a bit difficult with the compiling and stuff so we shall see! 

Appreciate all the help, this sorta thing really drives me nuts till I can figure it out so will post a result if I come up with one just for completions sake heh.

**Comment by mdhiggins** [comment]
What error does the sim link give you? It would have to be inside the VM that it'd be created

**Comment by yekul** [comment]
'Local NTFS volumes are required to complete the operation.' 
C: drive is local NTFS, but i'm guessing the issue is with the \\vmware-host\ because when I check the drive it's listed as a HGFS file system (Host Guest File System upon googling). Assuming to protect OS from VM guest. Symblinks not working with VMware seems to be long documented and not something they plan to address; upon googling.

**Comment by yekul** [comment]
Curiously, would it be possible to address this in the script itself if I could somehow force it to always pass the folder structure Sonarr needs to see? Like some lines of code that would do a replacement text for before the command that is sent to Sonarr API? Or would this break everything else? 
(just asking before I waste time trying to figure it out, feel free to give up on this pipe dream as I know it's probably a hassle at this point!)

**Comment by mdhiggins** [comment]
Working on a solution currently, stand by

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/path-mapping

Alright so here's a branch with a possible solution to this

I added a new `path-mapping` option to the downloaders that should allow for translation of directories for your purposes. The option exists for SAB, NZBGet, uTorrent, qBittorrent, and Deluge

The syntax for the option is `=` for pairs, `,` for separators

Sample using your setup would be

```
[qBittorrent]
path-mapping = \\vmware-host\Shared Folders\shared=C:\Users\server\Downloads\shared
```

Can specify multiple replacements separated by comma if needed

This should result in

- Internal VM path = `\\vmware-host\Shared Folders\shared\moviename`
- Path passed to the API = `C:\Users\server\Downloads\shared\moviename`

If this works and you don't encounter any errors let me know and I'll merge it into the master branch but testing on my end seems to be working so far

**Comment by yekul** [comment]
Well i'm blown away. Does straight transfers perfectly, and just now running a convert file and it also seems to be working perfectly. Will take a while to confirm encoding success, as I need to bump the VM up from 4 cores now. Probably take a few hours but all looks good so far! Couldn't get it to convert at first and took me a few minutes of trials and following error logs to notice the convert = false tag under qbittorrent heading in autoprocess.ini *feels stupid*. 

This is fantastic!! I browsed through and you had to edit so many files to make this work... Very much appreciate your time and effort.

**Comment by yekul** [comment]
One final question, there's no way to differentiate based on codec with the script method is there, so for example x264 files convert and x265 simply get passed over? I remember reading something about there being no mediainfo at some point but just wanted to make sure. 

That's no biggie anyways, mostly just curious to make sure I have my autoprocess.ini set up properly. It only does an audio remux anyway when it 'processes' them it seems (700FPS says that's the case hah).

**Comment by mdhiggins** [comment]
Script analyzes all the streams in a very detailed fashion (way more detail than just mediainfo) and won't encode if its already in desired format and will instead just remux. Just put hevc on your video-codec list (this is what FFProbe reports h265 as) if you don't want to convert h265

**Comment by yekul** [comment]
Oh very nice. Well fantastic, thank you so much again!

**Comment by yekul** [comment]
Yeah I think it's an issue I have in my audio settings. So it's definitely not encoding (if only my CPU could do 700FPS), but is remuxing the audio still and adjusting it to match settings I have in the autoprocess.ini file. Think I need to add AAC to my audio list as I only have AC3 listed and it seems a lot of content is using AAC. So i'll figure that out and be good to go. Thanks a bunch :D

**Comment by mdhiggins** [comment]
For any of the codec options anything that's on that list will be remuxed, but if its not on that list it will be converted to the first option so just include anything you'd like to keep.

Other options can also prevent remuxing (bittrate, channels, etc) but that should be indicated in the logs if one of those options is triggering encoding

Also, I merged the branch into master since its working!
