### ISSUE TITLE
sonarr_series_imdbid

### ISSUE THREAD

**Issue by MatYRicS** [mdhiggins/sickbeard_mp4_automator#1338]
After this commit d9f831f16850c290b2752fb8542d98fd8ff9be06 I keep getting errors when Sonarr is executing `postSonarr.py`:

```
20-10-4 22:19:41.5|Error|postSonarr.py|Traceback (most recent call last):
20-10-4 22:19:41.5|Error|postSonarr.py|  File "/scripts/sickbeard_mp4_automator/postSonarr.py", line 97, in <module>
20-10-4 22:19:41.5|Error|postSonarr.py|    imdb_id = int(os.environ.get('sonarr_series_imdbid'))
20-10-4 22:19:41.5|Error|postSonarr.py|ValueError: invalid literal for int() with base 10: 'tt1086761'
```

I have tested with different episodes and different series and nothing works now.

**Comment by mdhiggins** [comment]
733570cccf27f8bc25a28f52969b530733c3d23c

That should fix it, my mistake thought it reported imdb id as a number not a string

**Comment by MatYRicS** [comment]
> [733570c](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/733570cccf27f8bc25a28f52969b530733c3d23c)
> 
> That should fix it, my mistake thought it reported imdb id as a number not a string

Tested and everything works again :)

**Comment by mdhiggins** [comment]
Sweet thanks, good catch
