### ISSUE TITLE
Deluged Execute .bat file CMD window blank

### ISSUE THREAD

**Issue by Rediculocity** [mdhiggins/sickbeard_mp4_automator#1339]
> First I would like to thank mdhiggins, this project is absolutely amazing, and I cannot count the number of hours that this has saved me. Also to anyone of the other 56 contributors thanks for all of your hard work.
> 
> I don't generally post on things so apologize for any faux pas.

I am not sure if this is the intended behavior, or if this is just a quirk of my configuration, or some other issue.

When deluged executes the delugePostProcess.py via a batchfile at torrent complete, the cmd window that opens is always blank. The script runs just fine and things are logged, just nothing is displayed. When I run the manual.py -i -a things are displayed as I would expect. Is it possible for the cmd window launched from the torrent complete bat file to show the progress? 

I had issues with the deluged not launching/running the py file so I wrapped it in a bat file containing the following. 

`C:\Users\myname\AppData\Local\Programs\Python\Python38\python.exe "C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py" %1 %2 %3`

I am not sure what information would be helpful about my configuration so here is brief summary, and I am happy to post any other information that would be helpful:
Windows 10, sonarr, radarr, deluged, plex, and your script
all updated to the most recent as of 10/4/2020
rechecked my setup vs configuration on your readme and wiki pages with no issues.

**Comment by HomeGrownCoder** [comment]
check out the switches for cmd... I think adding one of those to your calling process would take care of the blank cmd window.

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd

cmd /k and turning off echo in the batch may help

**Comment by Rediculocity** [comment]
I know very little about .bat files. I got the syntax for what i'm using from one of the other issues posted here forever ago. I have tried a few versions of editing the .bat script based on your comments and everything ends up with the same blank window. Can you help me with how I should add the switches, and or echo?

here are a few examples of what I tried:

`CMD /k C:\Users\Redic\AppData\Local\Programs\Python\Python38\python.exe C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py %1 %2 %3
echo off`

`CMD /k C:\Users\Redic\AppData\Local\Programs\Python\Python38\python.exe C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py %1 %2 %3`

`C:\Users\Redic\AppData\Local\Programs\Python\Python38\python.exe C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py %1 %2 %3 /k`

`C:\Users\Redic\AppData\Local\Programs\Python\Python38\python.exe C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py %1 %2 %3 /k
echo off`

`@echo off
C:\Users\Redic\AppData\Local\Programs\Python\Python38\python.exe C:\Scripts\sickbeard_mp4_automator-master\delugePostProcess.py %1 %2 %3`

**Comment by mdhiggins** [comment]
You can try pointing it to pythonw.exe instead of python.exe but I think this is just a weird quirk with deluge that there really isn't a solution to

**Comment by Rediculocity** [comment]
So i played around with it a bunch more with no success. So I just made the switch to qbittorrent program and it is all working great now. Thanks for the help.
