### ISSUE TITLE
nzbget support for this script?

### ISSUE THREAD

**Issue by amlucent** [mdhiggins/sickbeard_mp4_automator#134]
Any plans to add nzbget support for this script?

I believe it would require little effort.  Here are the details on how to add support. I would be interested in helping accomplish this if needed.  I am only scared you would laugh at my skillz...

 http://nzbget.net/Post-processing_scripts

**Comment by ktonini** [comment]
Any update on this? Would be really awesome. Looking at the script I thought it was already implemented, and maybe the reason my Sonarr install wasn't triggering it was because it needs credentials which aren't supported yet, but NZBget actually doesn't even recognize the script when put into the correct folder.

**Comment by mdhiggins** [comment]
No updates on my end. Since I don't use NZBGet and don't have a good testing environment to do this its not high on my priority list. If anyone actively uses NZBget and wants to adapt the script I'd be happy to include it

**Comment by zybeon** [comment]
I use NZBGet and Sonarr and would love to see it implemented. I also happen to have a dedicated server not currently in use that you could use for a test bed.

**Comment by mdhiggins** [comment]
Hm if you wanna send me a private message and we can talk about getting some access there perhaps we can get the ball rolling on this

**Comment by zybeon** [comment]
Sent you an email.

**Comment by zybeon** [comment]
NZBGet to Sonarr/NZBDrone support has been added from the recent merge. Please test it out and respond how it is working.

You will need to move the newly added "nzbtoSonarrMP4.py" to your NZBGet scripts folder. Also check the new autoProcess.ini.sample for the required settings

**Comment by mdhiggins** [comment]
Thanks again for all the hard work, testing, and doing pretty much all the code. Its greatly appreciated.

**Comment by ktonini** [comment]
Wow that was fast, thanks so much guys!  Any chance you could support username/password protection for Sonarr?

**Comment by zybeon** [comment]
There is no need. It uses the API key. It makes a single call to Sonarr (http://localhost:8989/api/command) The api is passed in the header information.

If you are concerned use SSL.

**Comment by mdhiggins** [comment]
So I reviewed the code and I can't see any reason why subliminal wouldn't be working. If anyone else can confirm if they're having issues keep me posted. I know subliminal isn't 100% reliably so you're not gonna get subtitles 100% of the time. Its very dependent on the release.

**Comment by zybeon** [comment]
Over looked a mistake in the sample ini. Under Sonarr api_key should be apikey. Noticed when I did a fresh install. Made a pull for the tiny but crippling error.

**Comment by mdhiggins** [comment]
NZBGet is now supported
