### ISSUE TITLE
Does this work on ARM devices, such as Raspberry pi?

### ISSUE THREAD

**Issue by oregonpillow** [mdhiggins/sickbeard_mp4_automator#1341]
I've used my pi plenty of times with FFMPEG to container convert mkv to mp4 which is does no problem. Wondering if this docker container will run on ARM?

Cheers!

**Comment by mdhiggins** [comment]
The docker containers that I maintain do not support ARM but the script itself should. There may be unofficial containers that do support ARM though but I can’t say for sure. 

The docker file I use is based on the Linuxserver.Io images so you may be able to adjust your base image and FFmpeg source to fit your needs as I do believe there are tags within the base image for ARM
