### ISSUE TITLE
readsettings.py : AttributeError: 'list' object has no attribute 'copy

### ISSUE THREAD

**Issue by oregonpillow** [mdhiggins/sickbeard_mp4_automator#1343]
In readsettings.py:
line [25](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/cd452e51d0a9ff583e020954d74335aecc7c2db2/resources/readsettings.py#L25): `return default.copy()`

causes python2 and python3 to throw an error:
`AttributeError: 'list' object has no attribute 'copy'`

Is there a particular reason you're using copy here? 
I tried changing to `return default` and it seems to be running ok now...?

**Comment by oregonpillow** [comment]
Plagued by more errors now:

```
Input and output extensions are the same so passing back the original file [process-same-extensions: False].
Bypassing conversion and setting outputfile to inputfile.
Relocating MOOV atom to start of file.
Traceback (most recent call last):
  File "manual.py", line 410, in <module>
    main()
  File "manual.py", line 386, in main
    walkDir(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), preserveRelative=args['preserverelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "manual.py", line 276, in walkDir
    processFile(filepath, None, mp, info=info, relativePath=relative)
  File "manual.py", line 239, in processFile
    mp.QTFS(output['output'])
  File "/home/pi/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1582, in QTFS
    processor.process(inputfile, outputfile)
  File "/home/pi/.local/lib/python2.7/site-packages/qtfaststart/processor.py", line 197, in process
    moov = _patch_moov(datastream, moov_atom, offset)
  File "/home/pi/.local/lib/python2.7/site-packages/qtfaststart/processor.py", line 263, in _patch_moov
    moov.write(struct.pack(struct_fmt, *offset_entries))
struct.error: integer out of range for 'L' format code
```

Thanks for any suggestions.

**Comment by mdhiggins** [comment]
https://www.programiz.com/python-programming/methods/list/copy

That sort of explains why it was done, weird variables were transferring over because the default value was being modified (it manifested in parts of the hwaccel settings getting blended together).

Unfortunately it looks like list.copy() was only added in python3.3 so that's not backwards compatible for python2

Confirmation that it is in python3 documentation though so not sure why you say python3 doesn't work
https://docs.python.org/3/tutorial/datastructures.html

This should be a python2 compatible solution
6ba662170e2da759d24d9b3d6ee3e35bdf8e65e9


For your second error, that appears to be an error with qtfaststart and it's not one I've ever seen before. I can't seem to find any documentation on it but its specifically with that package. Is it an error with every file? Sometimes you see out of range errors are large files using 32 bit versions of python which may be the case here. If it's a persistent error you can offload the moov atom relocation to FFMPEG and disable qtfaststart in autoProcess.ini potentially

**Comment by mdhiggins** [comment]
```
[Converter]
postopts = -movflags, faststart

[Metadata]
relocate-moov = False
```

The reason this isn't the default solution and the python-based moov atom relocation is performed is that there was some errors with tagging that were seen (although very rare) when applying the tag metadata after the moov atom had already been moved

**Comment by DatsiK96** [comment]
I downloaded the latest commit probably an hour ago from the time of making this post and I'm also getting this error as well.

I've looked at the code in question, and it looks like it's trying to convert an array into a string possibly, and may not be able to if the array only has one item in the split (no array)...

But not like I know anything about Python. Just what I gleamed from it...

Here's the error in question.

```
20-10-10 10:43:18.7|Debug|CustomScript|Executing external script: D:\Python3\python.exe
20-10-10 10:43:18.7|Debug|python.exe|Starting D:\Python3\python.exe D:\sickbeard_mp4_automator\postRadarr.py
20-10-10 10:43:19.9|Debug|python.exe|2020-10-10 10:43:19 - RadarrPostProcess - INFO - Radarr extra script post processing started.
20-10-10 10:43:19.9|Debug|python.exe|2020-10-10 10:43:19 - resources.readsettings - INFO - D:\Python3\python.exe
20-10-10 10:43:20.0|Debug|python.exe|2020-10-10 10:43:19 - resources.readsettings - INFO - Loading config file D:\sickbeard_mp4_automator\config\autoProcess.ini.
20-10-10 10:43:19.9|Error|python.exe|Traceback (most recent call last):
20-10-10 10:43:20.0|Error|python.exe|  File "D:\sickbeard_mp4_automator\postRadarr.py", line 86, in <module>
20-10-10 10:43:20.0|Error|python.exe|    settings = ReadSettings()
20-10-10 10:43:20.0|Error|python.exe|  File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 585, in __init__
20-10-10 10:43:20.0|Error|python.exe|    self.readConfig(config)
20-10-10 10:43:20.0|Error|python.exe|  File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 595, in readConfig
20-10-10 10:43:20.0|Error|python.exe|    self.hwdevices = config.getdict(section, "hwdevices", lower=False, replace=[])
20-10-10 10:43:20.1|Error|python.exe|  File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 43, in getdict
20-10-10 10:43:20.1|Error|python.exe|    output[split[0]] = split[1]
20-10-10 10:43:20.1|Error|python.exe|TypeError: list indices must be integers or slices, not str
20-10-10 10:43:20.1|Debug|CustomScript|Executed external script: D:\Python3\python.exe - Status: 1
20-10-10 10:43:20.1|Debug|CustomScript|Script Output: 
10/10/2020 5:43:19 PM - Standard - 2020-10-10 10:43:19 - RadarrPostProcess - INFO - Radarr extra script post processing started.
10/10/2020 5:43:20 PM - Standard - 2020-10-10 10:43:19 - resources.readsettings - INFO - D:\Python3\python.exe
10/10/2020 5:43:20 PM - Standard - 2020-10-10 10:43:19 - resources.readsettings - INFO - Loading config file D:\sickbeard_mp4_automator\config\autoProcess.ini.
10/10/2020 5:43:20 PM - Error - Traceback (most recent call last):
10/10/2020 5:43:20 PM - Error -   File "D:\sickbeard_mp4_automator\postRadarr.py", line 86, in <module>
10/10/2020 5:43:20 PM - Error -     settings = ReadSettings()
10/10/2020 5:43:20 PM - Error -   File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 585, in __init__
10/10/2020 5:43:20 PM - Error -     self.readConfig(config)
10/10/2020 5:43:20 PM - Error -   File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 595, in readConfig
10/10/2020 5:43:20 PM - Error -     self.hwdevices = config.getdict(section, "hwdevices", lower=False, replace=[])
10/10/2020 5:43:20 PM - Error -   File "D:\sickbeard_mp4_automator\resources\readsettings.py", line 43, in getdict
10/10/2020 5:43:20 PM - Error -     output[split[0]] = split[1]
10/10/2020 5:43:20 PM - Error - TypeError: list indices must be integers or slices, not str
20-10-10 10:43:23.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
20-10-10 10:44:41.0|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
```

Radarr is calling PostRadarr, but the movie is just moved, not encoded.

**Comment by mdhiggins** [comment]
Whoops looks like I introduced a type error

ff28285100ac9666a47c6b8c9ea881284e840bc1

That update should fix it sorry about that

**Comment by oregonpillow** [comment]
Hi @mdhiggins ,
Good idea! And thanks for your quick reply!
So I want to try offloading MOOV atom to FFmpeg like you suggested.
I disabled [relocate-moov = True](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/ff28285100ac9666a47c6b8c9ea881284e840bc1/setup/autoProcess.ini.sample#L33) in my config file.
So now I assume I need to pass post-processing options `-movflags faststart` to FFmpeg. Where's the best place to add these? [Here](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/504b4ca4a866e0bf0fba655a82a2bdc35524fa18/resources/mediaprocessor.py#L907)?

**Comment by mdhiggins** [comment]
I included that in the sample above, use postopts

**Comment by oregonpillow** [comment]
also, am I right in saying that telling FFmpeg to relocate moov will essentially cause it process everything again? So processing will take significantly longer? (not a problem, just curious)

**Comment by oregonpillow** [comment]
> I included that in the sample above, use postopts

Yes, but I'm an idiot and somehow missed that comment! haha. Thanks! =)

**Comment by mdhiggins** [comment]
Doing it through FFMPEG I believe is relatively fast, faster than qtfaststart which I believe is limited by your HD write speed.
