### ISSUE TITLE
Unexpected Video Output

### ISSUE THREAD

**Issue by Dead-Rekon** [mdhiggins/sickbeard_mp4_automator#1347]
I've moved on to converting a lot of my older files to mkv and encountered an odd issue with about 3/4 of these files. The resulting files are around 100 mb and unplayable. MediaInfo doesn't seem to match up with the log info.

[File Info.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5382291/File.Info.txt)
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5382292/sma.log)
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5382303/autoProcess.txt)

**Comment by mdhiggins** [comment]
You could try disabling hardware acceleration and see if that makes a difference. You also should probably set a CRF value since the the small size might be a bitrate issue and you essentially have no quality settings specified.

**Comment by Dead-Rekon** [comment]
Gives me an excuse to finally upgrade everything. Thanks again.
