### ISSUE TITLE
How do i keep ​ASS (Advanced Substation Alpha)  subtitle 

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1348]
I have an anime show with ass subtitle that replaces/overlayer Japanese signs to English words.
i cant seem to keep it after converting to mp4. i tried adding ass ssa into subtitle codec field.

**Comment by mdhiggins** [comment]
MP4 only supports the mov_text subtitle coded. You can use MKV if you want to use ASS or use external subtitle files.

**Comment by Whereamnow** [comment]
Thanks for that information. Is there a way to detect and burn in ASS into the script?

i know i can manually do it

ffmpeg -i "aa.mkv" -vf subtitles="aa.mkv" -acodec copy "a.mkv"
then convert to mp4

**Comment by mdhiggins** [comment]
There is a burn-subtitle option you can reference

burn-subtitles = False
burn-dispositions =
