### ISSUE TITLE
Linux setup, but space in folder name

### ISSUE THREAD

**Issue by henryjb99** [mdhiggins/sickbeard_mp4_automator#1353]
Lately, some downloads have been having a space in their folder name. for instance:
/shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io].mkv and an autocreated folder called /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]-convert.

Folder contents from Linux
```
/shared/Downloaded/sonarr# ll
drwxrwxrwx 2 root root      4096 Oct 24 07:51 'Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]-convert'/

-rwxrwxrwx 1 root root 612122417 Oct 24 07:53 'Love.After.Lockup.S03E15.Cuffing.Season.1080p.HEVC.x265-MeGusta[eztv.io].mkv'*
```

I run a linux setup, and even though the folder exists, the postSonarr.py instance cannot access it because of this space. Any suggestions?

Here is what I get from the sonarr logs:
20-10-24 07:59:50.4|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
20-10-24 08:01:20.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder

AutoProcess.ini
```
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = localhost
port = 8989
web_root = 
ssl = False
apikey = XXXXXXXXXXXXXX

[Radarr]
host = localhost
port = 7878
web_root = 
ssl = False
apikey = XXXXXXXXXXXXXX

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = 0
output_directory =
copy_to = 
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 3000
video-crf = 
video-max-width = 1280
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 128
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[qBittorrent]
convert = True
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
action_before = pause
action_after = resume
host = http://localhost:8080/
username = XXXXXXXXXXXXXX
password = XXXXXXXXXXXXXX
output_directory = 
radarr-label = radarr

[Deluge]
host = localhost
username = XXXXXXXXXXXXXXX
convert = True
password = XXXXXXXXXXXXXX
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory =
remove = False
radarr-label = radarr

[SABNZBD]
convert = False
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token = XXXXXXXXXXXXXXXXXX
```

**Comment by mdhiggins** [comment]
That error is coming directly from Sonarr, has nothing to do with the script

Also a space shouldn't matter at all, none of the scripts code handles spaces differently and I use linux for my personal setup and it handles spaces without issue

I do notice that the path you linked from your `ls -l` command is different than the one from the error

```
/shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]
vs
/shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]-convert
```

What download client are you using and how is that download client notifying Sonarr?

**Comment by henryjb99** [comment]
Yes, I noticed that also.

I am using the latest qbittorrent docker and sonarr images from linuxserver.io.

My run external command is:
`/usr/bin/python "/opt/sickbeard/qBittorrentPostProcess.py" "%L" "%T" "%R" "%F" "%N" "%I"`

Odd. It seems to me that only the downloads that have a space in them are failing. Sonarr realizes that the download completes, but when I click the icon to manually import them, it finds no files.

A working conversion:
Qbittorrent log:
`(N) 2020-10-24T14:26:47 - Enqueued to move "The Goldbergs 2013 S08E01 720p HDTV x264-SYNCOPY[rarbg]" from "/shared/Downloading/" to "/shared/Downloaded/sonarr".
(N) 2020-10-24T14:26:47 - Moving "The Goldbergs 2013 S08E01 720p HDTV x264-SYNCOPY[rarbg]" to "/shared/Downloaded/sonarr"...
(N) 2020-10-24T14:26:48 - "The Goldbergs 2013 S08E01 720p HDTV x264-SYNCOPY[rarbg]" is successfully moved to "/shared/Downloaded/sonarr".
(N) 2020-10-24T14:26:48 - Torrent: The Goldbergs 2013 S08E01 720p HDTV x264-SYNCOPY[rarbg], running external program, command: /usr/bin/python "/opt/sickbeard/qBittorrentPostProcess.py" "sonarr" "udp://tracker.tiny-vps.com:6969/announce" "/shared/Downloaded/sonarr/The.Goldbergs.2013.S08E01.720p.HDTV.x264-SYNCOPY[rarbg]" "/shared/Downloaded/sonarr/The.Goldbergs.2013.S08E01.720p.HDTV.x264-SYNCOPY[rarbg]" "The Goldbergs 2013 S08E01 720p HDTV x264-SYNCOPY[rarbg]" "eb3413e4fdc182d452af527cbbcdf1187ec27d06"
"`


Failed conversion:
Qbittorrent log:
`Torrent: Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io], running external program, command: /usr/bin/python "/opt/sickbeard/qBittorrentPostProcess.py" "sonarr" "udp://retracker.lanta-net.ru:2710/announce" "/shared/Downloaded/sonarr/Love.After.Lockup.S03E15.Cuffing.Season.720p.HDTV.x264-CRiMSON[eztv.io].mkv" "/shared/Downloaded/sonarr/Love.After.Lockup.S03E15.Cuffing.Season.720p.HDTV.x264-CRiMSON[eztv.io].mkv" "Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]" "292dc0122e7356c31cc00c030cda4c50d3fd814d"`

Sonarr log:
```
20-10-24 14:03:27.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
20-10-24 14:04:57.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
20-10-24 14:06:27.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
20-10-24 14:07:57.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
20-10-24 14:09:27.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /shared/Downloaded/sonarr/Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
```

Folder /shared/Downloaded/sonarr:
```
drwxrwxrwx 2 root root      4096 Oct 24 07:51 'Love After Lockup S03E15 Cuffing Season 1080p HEVC x265-MeGusta[eztv io]-convert'
drwxrwxrwx 2 root root      4096 Oct 24 08:23 'Love After Lockup S03E15 Cuffing Season 720p HDTV x264-CRiMSON[eztv io]-convert'
-rwxrwxrwx 1 root root 928028356 Oct 24 13:59 'Love.After.Lockup.S03E15.Cuffing.Season.720p.HDTV.x264-CRiMSON[eztv.io].mkv'
```

**Comment by mdhiggins** [comment]
What's triggering the import?

**Comment by henryjb99** [comment]
In Sonarr, I have a Connections setup called Post Sonarr. it is triggered On Import and On Upgrade with an executable of /opt/sickbeard/postSonarr.py

**Comment by mdhiggins** [comment]
Yeah but that happens after the import (after Sonarr is notified). How is Sonarr being notified a download is complete? Are you using completed download handling in Sonarr or is it the qBittorrentPostProcess that's doing it

**Comment by mdhiggins** [comment]
Based on everything you've posted postSonarr.py has never actually been launched, it hasn't gotten that far because Sonarr is failing

**Comment by henryjb99** [comment]
Ok odd, I just killed, rebuilt and resetup my docker containers. Now it is working.
