### ISSUE TITLE
Sonarr - Subtitle backup files leftover or "backed" up multiple times

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1354]
This has something to do with #1344 I believe. Two TV shows that were recently added to my setup have multiple *.srt files ending with ".backup" or with ".backup.backup.backup.etc.etc.etc".  Screenshots are below.

Checking my movies directory for anything ending with "*.backup" didn't return any results, so I'm assuming Radarr is just fine as-is. If you need anything else at all please let me know.

![Screen Shot 2020-10-28 at 1 38 31 PM](https://user-images.githubusercontent.com/752262/97392032-09de1b00-1924-11eb-9541-84009cb5d781.png)

![Screen Shot 2020-10-28 at 1 40 11 PM](https://user-images.githubusercontent.com/752262/97392039-0f3b6580-1924-11eb-8662-78b8984d5d50.png)

**Comment by mdhiggins** [comment]
97f3527507b4d79691de12c3674e32bd8f5b1014

See if that resolves things, looks like a stupid mistake on my part for TV shows not accounting for that fact that subs for other episodes will exist in the same folder

**Comment by mdhiggins** [comment]
You will need to manually delete any existing backups

**Comment by johnwchambers** [comment]
will report back as soon as I can, files have been updated. thanks!

**Comment by johnwchambers** [comment]
Getting this error after checking logs today. I'm assuming this is just a typo? The backup and rename operations seem to be working fine so far and the content still showed up on my server even though this error was encountered. 

![Screen Shot 2020-10-29 at 4 05 16 PM](https://user-images.githubusercontent.com/752262/97536527-a544be00-1a00-11eb-804e-b5ce6f4ae573.png)

**Comment by mdhiggins** [comment]
ff0cd26f9be8443b775a532465cd9cac3307d575

Yeah that was a typo, try now. I suspect the backup and renaming was not running because of this typo

**Comment by johnwchambers** [comment]
everything looks good to go now, thanks!
