### ISSUE TITLE
resources.mediaprocessor - ERROR - Unable to tag file

### ISSUE THREAD

**Issue by hoyane** [mdhiggins/sickbeard_mp4_automator#1357]
Hi, I was hoping you could help me understand if this is user error!? I find it odd that it references a tmdbThis is right after the mp4 is successfully created. This is running in the sonarr-sma docker. SMA_UPDATE=true so it is running the newest commit. This is first two shows i added so its not like this was working before.

The error:
https://pastebin.com/raw/F2nX4uKk

Slightly different error on a different show:
https://pastebin.com/raw/dTjh8Czv

My config:
https://pastebin.com/raw/8Yfmjw7W

**Comment by mdhiggins** [comment]
https://www.themoviedb.org/tv/78458-butlers/seasons

Looks like the show you're trying to pull metadata for doesn't have a season 0 on TMDB which is where the metadata comes from so its failing

Season 0 is often 'specials' and may not exist on these libraries

I don't see any Season 0 entries on TVDB either (though this API isn't used)

https://www.thetvdb.com/series/341439-show

The logs are truncated so I can't see what specific episode number you're trying to pull data for but that's the issue

**Comment by mdhiggins** [comment]
I see you edited the original comment but in this case for the 2nd show its not even able to find a TMDB entry for this show. Without know what show and episode its hard to debug this as well but you need to verify there are TMDB entries for these shows and episodes and if they aren't present then the tagging won't work

**Comment by hoyane** [comment]
Sorry about that. 
This was the first error:
https://www.themoviedb.org/tv/78663-bbq-with-franklin?language=en-US

This was the second:
https://www.themoviedb.org/movie/93560-batman-and-robin?language=en-US

**Comment by hoyane** [comment]
So yeah it looks like bbq one is in fact season 0 according to sonarr but tmdb has only season 1. The batman one is a serial and is added to sonarr but the tmdb has it in the movies section. I will try with a more common show.

**Comment by mdhiggins** [comment]
There's been a few shows where I've had issues like this and I've just added the entries to TMDB myself. It's an open database so you can contribute what's missing if it's more obscure.

**Comment by hoyane** [comment]
I tried to do that but both of the shows when you go to edit the seasons it says the show has ended and is locked. On one of the items i reported the issue but dont know when if ever they will make the change. Is there something im missing that I can in fact do that myself?

**Comment by mdhiggins** [comment]
Can't say I've encountered that issue before so I can't speak to how long it takes for them to respond
