### ISSUE TITLE
[FEATURE] Auto Force Tagging during Post Proccessing

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1367]
I wish to have an option in the autoProcess.ini to force tag a video during post processing. The tag would re-tag e.g: an EVO release to the filename instead, due to Plex not matching correctly otherwise. See two examples in the attached picture.

![Screenshot_2020-11-28 Plex](https://user-images.githubusercontent.com/57449785/100499350-2494f100-3169-11eb-9e30-cb2e4216f5ec.png)

Best regards,
M.Z.

**Comment by mdhiggins** [comment]
I don't know what you're asking

**Comment by morganzero** [comment]
I was asking if it’s possible for you to implement an option in the script to force file name tagging during the post process. If the file is already tagged e.g: “EVO”. It would re-tag it to filename instead.

If and when you have time, is this possible ?

**Comment by mdhiggins** [comment]
I'm still not 100% sure what you're looking for here. The tagging you see in Plex is independent of the metadata written to the file itself. The script also doesn't use Plex's metadata when it does its tagging.

The script also does not do file renaming and there's no plans to add that feature, as this is better handled by the media managers the script is intended to integrate with. I admit I still don't fully understand what you want here but I think its outside of anything that has to do with the script. Feel free to provide more concrete examples if I'm misunderstanding still.
