### ISSUE TITLE
Radarr v3 - postRadarr

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1376]
For Radarr v3, to add postRadarr.py. (This worked for me since Radarr auto updated me to v3)

Instead of:

Path - Full path to your python executable
Arguments - Full path to postRadarr.py

Put:

Path - Full path to postRadarr.py

**Comment by mdhiggins** [comment]
This has been covered in other issues before

Just make a bash / sh / bat file depending on your operating system that includes the path to python and the path to the script and then point radarr to that

```
#!/usr/bin/env bash

/path/to/python3 /path/to/postRadarr.py
```

Sample for bash

**Comment by Whereamnow** [comment]
For windows, which is where I installed it on. Creating a bat file to point to Python isn’t needed. Simply putting Full path to postRadarr.py in the “Path” space worked.

**Comment by mdhiggins** [comment]
Depends on how many python installations and if python is part of your environment path, in your case it must but and only one, but just for others that stumble upon this, the 100% effective way is to include the python path as being able to directly call .py files or use the generic `python` command all depends on your python installation and environment PATH configuration
