### ISSUE TITLE
Problem processing avi file

### ISSUE THREAD

**Issue by tabouzeid** [mdhiggins/sickbeard_mp4_automator#1380]
I keep getting the error below when i deal with avi file and i can't seem to figure out what i'm missing. any insight into what's going on?

[AVHWDeviceContext @ 0x5599facb8080] Could not dynamically load CUDA
[mpeg4_cuvid @ 0x5599facb5da0] Error creating a CUDA device
cuvid hwaccel requested for input stream #0:0, but cannot be initialized.
[mpeg4_cuvid @ 0x5599facb5da0] ff_get_format failed: -1
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (mpeg4_cuvid) -> h264 (libx264))
  Stream #0:1 -> #0:1 (mp3 (native) -> aac (native))
Error while opening decoder for input stream #0:0 : Operation not permitted

**Comment by mdhiggins** [comment]
It's an FFMpeg error because you're trying to use hardware acceleration. If you're not intending to use it feel feee to remove those options from hwaccels and hwaccel-decoders (just leave those blank)

If you're intending to use hwaccel then you gotta debug your hardware configuration.
