### ISSUE TITLE
SMA does not resume conversions after restart

### ISSUE THREAD

**Issue by LordChunk** [mdhiggins/sickbeard_mp4_automator#1383]
SMA currently does not resume file conversions after it has been restarted. It leaves a partially converted file in the video folder instead.

Current behaviour:
- SMA starts the conversion of a video file
- SMA is restarted
- SMA abandons partially converted files.
Expected behaviour: 
- SMA starts the conversion of a video file
- SMA is restarted
- SMA continues conversion of unfinished files.

Steps to reproduce:
- Run the docker containers listed below with their default configurations
- Add qBitTorrent to Radarr
- Download a movie with a non-MP4 file format
- Wait for the download to finish
- Let SMA start the conversation process
- Restart the radarr-sma docker container
Your video folder should now contain the original video file and an incomplete MP4 version.

Environment:
Docker using the following image: ``randomninjaatk/radarr-sma``
Download client: ``qBitTorrent``

I'm fairly sure this should also be reproducible with the official docker containers, but this setup makes it faster to reproduce.

**Comment by mdhiggins** [comment]
No chance of adding this.

Its simply not consistent with the SMA workflow and would be something that would need to be implemented at the level of the software that calls SMA (Radarr, Sonarr, QBT, whichever). Additionally picking up an FFMPEG conversion in progress that was abruptly ended from a container restart would be very challenging. Not sure if this can even be done. The script is essentially an FFMPEG wrapper so FFMPEG would need to support this as well. There's also no persistently running instance of the script. Its not a background process or service, its just a python script that's spun up as part of post process routines. It doesn't have a database or backend that keeps track of jobs in progress and all the media management is handled by external programs which is where something like this would need to be implemented.

Best practice would be to not restart your containers with a job in progress

Open to look at a pull request if you think this is doable but I would highly doubt it without massive rewrites and functionality expansions beyond the scope of this project
