### ISSUE TITLE
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device'

### ISSUE THREAD

**Issue by LandMineHare** [mdhiggins/sickbeard_mp4_automator#1384]
I'm running on a headless FreeBSD jail, and the script worked fine until i decided to update everything. After some issues with pkg not wanting to work, I got python3 and pip and all the dependencies installed, but for some reason when I run a ./manual.py to test settings before letting the script run loose, I get this error.

`[                    ] 0% Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/Data/Downloads/scripts/resources/mediaprocessor.py", line 1525, in convert
    for timecode, debug in conv:
  File "/Data/Downloads/scripts/converter/__init__.py", line 309, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/Data/Downloads/scripts/converter/ffmpeg.py", line 707, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
/usr/local/bin/ffmpeg -init_hw_device vaapi=sma:/dev/dri/renderD128 -hwaccel_device sma -hwaccel vaapi -hwaccel_output_format vaapi -i (File and Switches)
ffmpeg version 4.0.3 Copyright (c) 2000-2018 the FFmpeg developers
  built with FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --enable-shared --enable-pic --enable-gpl --enable-postproc --enable-avfilter --enable-avresample --enable-pthreads --cc=cc --disable-alsa --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libaom --disable-libass --disable-libbs2b --disable-libcaca --disable-libcdio --disable-libcelt --disable-chromaprint --disable-libcodec2 --disable-libdc1394 --disable-debug --enable-htmlpages --disable-libdrm --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --disable-libfribidi --disable-gcrypt --disable-libgme --enable-gmp --enable-gnutls --enable-version3 --disable-libgsm --enable-iconv --disable-libilbc --disable-libjack --disable-libkvazaar --disable-ladspa --disable-libmp3lame --disable-libbluray --disable-librsvg --disable-librtmp --disable-libxml2 --disable-lv2 --enable-mmx --disable-libmodplug --disable-libmysofa --disable-nonfree --disable-openal --disable-opencl --enable-libopencv --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --disable-openssl --enable-optimizations --enable-libopus --disable-libpulse --enable-runtime-cpudetect --disable-librubberband --disable-sdl2 --disable-libsmbclient --disable-libsnappy --disable-sndio --disable-libsoxr --disable-libspeex --disable-libsrt --enable-sse --disable-libssh --disable-libtesseract --enable-libtheora --disable-libtwolame --enable-libv4l2 --enable-vaapi --enable-vdpau --disable-libvidstab --enable-libvorbis --disable-libvo-amrwbenc --enable-libvpx --disable-libwavpack --disable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --disable-outdev=xv --disable-libzimg --disable-libzmq --disable-libzvbi
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[AVHWDeviceContext @ 0x80ce1b1c0] No VA display found for device: /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument`

I've racked my brain, browsed everywhere I can but I can't seem to find anything that works. Perhaps my GoogleFu is not that good?

**Comment by mdhiggins** [comment]
Set hwaccels to

`hwaccels = `

**Comment by LandMineHare** [comment]
So that worked, but now it is going extremely slow. Anyway to get hwaccel working on a headless freebsd jail with an intel xeon? :D

**Comment by mdhiggins** [comment]
You can restore those options and put the correct path to your hardware acceleration device. 

You didn't indicate anywhere that you were trying to use hardware acceleration in your post so I assumed you just didn't bother to check the default settings. 

'VA display found for device: /dev/dri/renderD128'

That's your main error. You need to make sure that path to your render device is correct and adjust accordingly. Read up on VAAPI and FFMPEG documentation for starters. 

If you're using some kind of container or virtualization you'll need to ensure that it has access to that device and that permissions are correct.

**Comment by LandMineHare** [comment]
Oh, ok. Thanks for the quick responses.
