### ISSUE TITLE
Request: Add Version number to script to enable better troubleshooting.

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1386]
Add a version number to the script. This will help identify what version of the script a user is using.

Example would be if a user finds an error, but there version is 1.5. But according to github, the latest is version available is 1.7.

You could then easily inform the user to update and retest before anyone takes the time to troubleshoot further when it could have been something that may have already been resolved.

Just a thought...

**Comment by mdhiggins** [comment]
That's what the commit hash tags are for

Not really interested in doing this
