### ISSUE TITLE
Embed watermark

### ISSUE THREAD

**Issue by herbi3** [mdhiggins/sickbeard_mp4_automator#1390]
Apologies, not sure how to add a feature request.

Would be great to have this automatically embed a watermark into the video during conversion.

I've tried using pre and post opts, but no luck with the filter_complex option etc.

Using the direct FFmpeg command it worked well, but couldn't get it to work via the automatic script.

ffmpeg -hwaccel auto -i video-in.mkv -i logo-117x117.png -filter_complex "[0:v][1:v]overlay=W-w-20:H-h-40:enable=between(t\,0\,30)" -c:v hevc_nvenc -crf 20 -preset fast -c:a copy video-out.mp4

**Comment by mdhiggins** [comment]
While on the surface this seems simple this actually would require lots of work as it would need to play nice with all the other automated options that use filter which gets even more complex when you get into hardware acceleration and specialized filters as well. I'll see if I can come up with something but no promises

**Comment by mdhiggins** [comment]
The effort required to get this to work in a dynamic fashion that wouldn't break other filters and input orders especially as some of the hardware accelerated encoders have very complex filters for things like scaling I don't think is worth it for a relatively niche feature. I'm open to looking at a pull request or reconsidering if this is something more people want but gonna say for now not going to add this
