### ISSUE TITLE
Dead links for sonarr/radarr docker images

### ISSUE THREAD

**Issue by Chuckame** [mdhiggins/sickbeard_mp4_automator#1392]
Hi there,

You have dead links into the readme.
New links:
- Sonarr: https://hub.docker.com/r/mdhiggins/sonarr-sma
- Radarr: https://hub.docker.com/r/mdhiggins/radarr-sma

**Comment by mdhiggins** [comment]
00fca854687a92f6070836f2a0f1b9d9cf621c68

Fixed, good catch
