### ISSUE TITLE
No valid files for processing

### ISSUE THREAD

**Issue by Rhainland** [mdhiggins/sickbeard_mp4_automator#1394]
Hi,
Im having an issue on ubuntu 18.04, with nzbget setup where the script claims no valid files are available for processing.

I have verified, that nzbget moves the .mkv file to the directory defined under nzbget CATAGORY settings, SMA afterwards fails and says it cant find any valid files, and nzbget then cleans up the directory and removes the files.

The only log output for SMA, is as follows;

2021-01-06 16:13:50 - NZBGetPostProcess - INFO - Script triggered from NZBGet (11.0 or later).
2021-01-06 16:13:50 - NZBGetPostProcess - ERROR - Neither par2-files found, _brokenlog.txt doesn't exist, considering download successful.
2021-01-06 16:13:50 - resources.readsettings - INFO - /usr/bin/python3
2021-01-06 16:13:50 - resources.readsettings - INFO - Loading config file /opt/postprocess/smaNZBget/config/autoProcess.ini.
2021-01-06 16:13:51 - NZBGetPostProcess - ERROR - No valid files for processing found, aborting.

**Comment by mdhiggins** [comment]
Its possible your build of ffprobe isn't working, see if you can probe a file and ensure it has execute permissions for the same user/group that's calling NZBGet

Try manual.py and see if its able to pick up files

Turn on debug level logging and try to process again and see if this provides more information

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by Rhainland** [comment]
> Its possible your build of ffprobe isn't working, see if you can probe a file and ensure it has execute permissions for the same user/group that's calling NZBGet
> 
> Try manual.py and see if its able to pick up files
> 
> Turn on debug level logging and try to process again and see if this provides more information
> 
> https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

Thanks for your response, debugging helped.

What i initially thought, was that is there something in sma that can block extensions, and i did look in the ini, but i couldnt actually find anything.

This is what debug logging revealed;
NZBGetPostProcess - DEBUG - Invalid source, extension is blacklisted [ignored-extensions].

This is a .mkv file.

What could cause this? Where can i re-configure it?

**Comment by mdhiggins** [comment]
Post the whole log
There's a good chance your download has a .nfo file with it and that's all that specific line is referring to

**Comment by Rhainland** [comment]
> Post the whole log
> There's a good chance your download has a .nfo file with it and that's all that specific line is referring to

That is not the case, all 3 files(1 of them being valid) all throw the same error;

2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Invalid source, extension is blacklisted [ignored-extensions].
2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Ignoring file /opt/appdata/nzbget/downloads/completed/Sonarr/Battlebots.Bounty.Hunters.S01E02.1080p.WEB.H264-WHOSNEXT/battlebots.bounty.hunters.s01e02.1080p.web.h264-whosnext.nfo.
2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Invalid source, no data returned.
2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Ignoring file /opt/appdata/nzbget/downloads/completed/Sonarr/Battlebots.Bounty.Hunters.S01E02.1080p.WEB.H264-WHOSNEXT/battlebots.bounty.hunters.s01e02.1080p.web.h264-whosnext.mkv.
2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Invalid source, extension is blacklisted [ignored-extensions].
2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Ignoring file /opt/appdata/nzbget/downloads/completed/Sonarr/Battlebots.Bounty.Hunters.S01E02.1080p.WEB.H264-WHOSNEXT/battlebots.bounty.hunters.s01e02.1080p.web.h264-whosnext.duplicate1.nfo.
2021-01-06 19:12:08 - NZBGetPostProcess - ERROR - No valid files for processing found, aborting.

**Comment by mdhiggins** [comment]
`2021-01-06 19:12:08 - NZBGetPostProcess - DEBUG - Invalid source, no data returned.`

Yeah I'm guessing this is an ffprobe issue, try running ffprobe on that file, does it work?
ffprobe -show_streams /opt/appdata/nzbget/downloads/completed/Sonarr/Battlebots.Bounty.Hunters.S01E02.1080p.WEB.H264-WHOSNEXT/battlebots.bounty.hunters.s01e02.1080p.web.h264-whosnext.mkv

**Comment by mdhiggins** [comment]
Also just looking at your file structure I'm guessing you're using some kind of docker?

Make sure ffprobe can be executed and that the user/group that's running NZBGet has permission to do so (same for FFMPEG)

**Comment by Rhainland** [comment]
> Also just looking at your file structure I'm guessing you're using some kind of docker?
> 
> Make sure ffprobe can be executed and that the user/group that's running NZBGet has permission to do so (same for FFMPEG)

Im doing it a little unordinary, but nothing that should have serious impact.

1. nzbget is outside docker, i execute sma via nzbget
2. Sonarr is inside docker(your sma image, but only handles moving the files)

I ran your ffprobe command, and it returned file data, heres a little snippet;

Input #0, matroska,webm, from '/opt/appdata/nzbget/downloads/completed/Sonarr/Battlebots.Bounty.Hunters.S01E02.1080p.WEB.H264-WHOSNEXT/battlebots.bounty.hunters.s01e02.1080p.web.h264-whosnext.mkv':
  Metadata:
    encoder         : libebml v1.4.0 + libmatroska v1.6.1
  Duration: 00:46:22.91, start: 0.000000, bitrate: 5051 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, Closed Captions, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
    Stream #0:1(eng): Audio: aac (HE-AAC), 48000 Hz, stereo, fltp (default)
    Stream #0:2(eng): Subtitle: subrip

So it doesnt seem like ffprobe is at fault here?

**Comment by mdhiggins** [comment]
What are your permissions on ffprobe?

**Comment by mdhiggins** [comment]
and you need to run it with the -show_streams argument as that's the main one the script uses, if that's broken for reason it may still be ffprobe.

Try running it through manual.py

**Comment by Rhainland** [comment]
> and you need to run it with the -show_streams argument as that's the main one the script uses, if that's broken for reason it may still be ffprobe.
> 
> Try running it through manual.py

I ran the command you provided, so with --show_streams.

manual.py reports "is not a valid format" on the file.

ffprobe is 0755, owner is root. I executed ffprobe as root via cli and it returned data. NZBget runs as root as well, and should have no issue executing ffprobe.

**Comment by mdhiggins** [comment]
Alright so as long as its outputting the stream data then that's ok and looks like ffprobe should be working
There's only 2 situations where `None` gets returned resulting in your specific error

```
        if not os.path.exists(fname):
            return None

        info = MediaInfo(posters_as_video)
        info.path = fname

        stdout_data = self._get_stdout([
            self.ffprobe_path, '-show_format', '-show_streams', fname])
        info.parse_ffprobe(stdout_data)

        if not info.format.format and len(info.streams) == 0:
            return None
```
If the file does not exist or the file is missing format data and has no streams. FFProbe problems can falsely return no format data or streams

Post the full ffprobe -show_streams output so I can take a look

Is it doing this for every file?

**Comment by Rhainland** [comment]
Looks like everything works now, ill be honest - This was a retarded configuration error on my part.

I am very sorry for having wasted your time.

The path to ffprobe location was wrong.. If i can donate somewhere for my stupidity, please let me know. Thank you for taking your time to respond.

**Comment by mdhiggins** [comment]
lol all good, closing this
