### ISSUE TITLE
Mediaprocessor error

### ISSUE THREAD

**Issue by LandMineHare** [mdhiggins/sickbeard_mp4_automator#1395]
So, I'm getting an error that shows up in sabnzbd, doesn't appear to affect the processing of the file, granted I haven't really been able to check everything downloaded. However it doesn't show up in sma.log.

`resources.mediaprocessor - ERROR - Pymediainfo exception
Traceback (most recent call last):
File "/Data/Downloads/scripts/resources/mediaprocessor.py", line 283, in isValidSource
media_info = MediaInfo.parse(inputfile)
File "/usr/local/lib/python3.7/site-packages/pymediainfo/__init__.py", line 421, in parse
lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
File "/usr/local/lib/python3.7/site-packages/pymediainfo/__init__.py", line 323, in _get_library
raise OSError("Failed to load library")
OSError: Failed to load library`

I checked the pymediainfo GitHub, and they say something about copying a DLL to the scripts folder, but I have no idea what they're talking about.

**Comment by mdhiggins** [comment]
That's a pymediainfo error so I would follow whatever instructions they give. Its an optional library that shouldn't impact things if it doesn't load though

That being said it looks like you're not on windows so a DLL is not the answer
You probably just need to install the mediainfo application as the python library is just a wrapper for that

https://mediaarea.net/en/MediaInfo
