### ISSUE TITLE
best option to save disk space

### ISSUE THREAD

**Issue by belrpr** [mdhiggins/sickbeard_mp4_automator#1399]
Hi,

what would be the best option to save disk space but keep "normal" quality.
In my testing both the nvenc & quicksync give bigger file sizes compares to cpu.

**Comment by mdhiggins** [comment]
The encoder you're choosing probably has very little to do with the size, the quality parameters including bitrate (or CRF), duration of the content, resolution, and chosen codec are all what will determine the size. Number of additional streams inside the file (audio, and subtitles to a lesser degree) will also increase file size. NVEnc and Quicksync might be defaulting (by way of FFMPEG defaults) to higher quality encodes. The hardware based encoders should offer better performance and encoding speeds but in general should be comparable as long as all other variables remain consistent across encoding jobs

H265 will give you the best file sizes but will be less compatible with older hardware
H264 is sort the old standard with the most compatibility but larger sizes compared to the newer H265

Everything else comes down to your quality settings

I suggest you start by reading through these two entries

https://trac.ffmpeg.org/wiki/Encode/H.264
https://trac.ffmpeg.org/wiki/Encode/H.265
