### ISSUE TITLE
Sonarr - Post Conversion Folder & File Cleanup

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1400]
Sonarr-sma is not removing working directories and files after a conversion is complete.  I still have the _UNPACK and raw folder and file.  The final folder and file are all created properly.  Radarr-sma works.  I am only seeing this in Sonarr-sma.  I am guessing I have something configured incorrectly somewhere, but I am not seeing it.

Here are the logs for one that failed for an episode called "Lim".
[Logs](https://pastebin.com/r0eUjXvL)

**Sonarr container config**
```
docker create --name=sonarr-sma -e TZ=America/Chicago -p 8079:8989 -e PUID=0 -e PGID=0 -v C:\Users\user\Documents\Docker\sonarr:/config -v C:\Users\user\Downloads\:/downloads -v C:\Users\user\Documents\Docker\sma:/usr/local/sma/config -v C:\Users\user\Documents\Docker\sma\sonarr-logging.ini:/usr/local/sma/config/logging.ini -v xbmctv:/tv mdhiggins/sonarr-sma:preview
```

```
docker create --name=radarr-sma -e TZ=America/Chicago -p 8095:7878 -e PUID=0 -e PGID=0 -v C:\Users\user\Documents\Docker\radarr:/config -v C:\Users\user\Downloads\complete:/downloads -v C:\Users\user\Documents\Docker\sma:/usr/local/sma/config -v C:\Users\user\Documents\Docker\sma\radarr-logging.ini:/usr/local/sma/config/logging.ini -v xbmcmovies:/movies mdhiggins/radarr-sma:nightly
```

**Comment by mdhiggins** [comment]
So this is probably an issue with your Sonarr configuration or an issue with the upstream container. SMA really has nothing to do with this. The _UNPACK folder is probably something made by your downloader (SAB or NZBGet) and for the docker containers the postSonarr script isn't called until the file is already moved to its final destination and renamed. It has no involvement or knowledge of the original download folder.

I would check your Sonarr settings or ask on the upstream container if there is an issue (Linuxserver/sonarr)
