### ISSUE TITLE
Processing issue - manual works fine, docker containers fail

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sickbeard_mp4_automator#1401]
Using the docker containers (radarr-sma/sonarr-sma, preview on both), almost all my conversions are failing. Here is the conversion tag from the docker container:

`2021-01-28 02:30:22 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -i /gmedia/English Movies/xyz/xyz.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /gmedia/English Movies/xyz/xyz.mp4`

and here it is using an older autoProcess.ini, manually, outside the docker container in a local env:

`2021-01-28 15:08:51 - MANUAL - INFO - /usr/bin/ffmpeg -i "/mnt/media/English Movies/xyz/xyz.mkv" -vcodec copy -map 0:0 -metadata:s:v title="FHD" -metadata:s:v handler_name="FHD" -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title="Stereo" -metadata:s:a:0 handler_n
ame="Stereo" -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 title="5.1 Channel" -metadata:s:a:1 handler_name="5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyri
cs-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/mnt/media/English Movies/xyz/xyz.mp4"`

When converting the first, the error I received at the end of the conversion process was:

`
2021-01-28 02:52:10 - resources.mediaprocessor - ERROR - /usr/local/bin/ffmpeg -i /gmedia/English Movies/xyz/xyz.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /gmedia/English Movies/xyz/xyz.mp4
2021-01-28 02:52:10 - resources.mediaprocessor - ERROR - ffmpeg version N-54441-gaa5e49e46d-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 60.100 / 56. 60.100
  libavcodec     58.108.100 / 58.108.100
  libavformat    58. 59.100 / 58. 59.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, matroska,webm, from '/gmedia/English Movies/xyz/xyz.mkv':
  Metadata:
    CREATION_TIME   : 2018-12-14T22:26:07Z
    ENCODER         : Lavf57.7.2
  Duration: 01:45:56.39, start: 0.000000, bitrate: 6204 kb/s
    Chapter #0:0: start 0.000000, end 394.019000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 394.019000, end 736.110000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 736.110000, end 1157.490000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1157.490000, end 1663.120000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1663.120000, end 1942.899000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1942.899000, end 2373.746000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 2373.746000, end 2806.178000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 2806.178000, end 3191.397000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 3191.397000, end 3509.798000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 3509.798000, end 3809.431000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 3809.431000, end 4207.829000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 4207.829000, end 4759.964000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 4759.964000, end 5215.836000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 5215.836000, end 5424.628000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 5424.628000, end 5860.772000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 5860.772000, end 6356.350000
    Metadata:
      title           : Chapter 16
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 5754488
      DURATION-eng    : 01:45:56.392000000
      NUMBER_OF_FRAMES-eng: 152401
      NUMBER_OF_BYTES-eng: 4572222872
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      title           : Surround
      BPS-eng         : 448000
      DURATION-eng    : 01:45:56.384000000
      NUMBER_OF_FRAMES-eng: 198637
      NUMBER_OF_BYTES-eng: 355957504
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      BPS-eng         : 31
      DURATION-eng    : 01:38:00.040000000
      NUMBER_OF_FRAMES-eng: 769
      NUMBER_OF_BYTES-eng: 22997
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x6d5f9c0] track 2: codec frame size is not set
Output #0, mp4, to '/gmedia/English Movies/xyz/xyz.mp4':
  Metadata:
    encoding_tool   : SMA
    encoder         : Lavf58.59.100
    Chapter #0:0: start 0.000000, end 394.019000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 394.019000, end 736.110000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 736.110000, end 1157.490000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1157.490000, end 1663.120000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1663.120000, end 1942.899000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1942.899000, end 2373.746000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 2373.746000, end 2806.178000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 2806.178000, end 3191.397000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 3191.397000, end 3509.798000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 3509.798000, end 3809.431000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 3809.431000, end 4207.829000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 4207.829000, end 4759.964000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 4759.964000, end 5215.836000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 5215.836000, end 5424.628000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 5424.628000, end 5860.772000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 5860.772000, end 6356.350000
    Metadata:
      title           : Chapter 16
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 16k tbn, 1k tbc (default)
    Metadata:
      BPS-eng         : 5754488
      DURATION-eng    : 01:45:56.392000000
      NUMBER_OF_FRAMES-eng: 152401
      NUMBER_OF_BYTES-eng: 4572222872
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      title           : FHD
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      title           : Stereo
      BPS-eng         : 256000
      BPS             : 256000
      DURATION-eng    : 01:45:56.384000000
      NUMBER_OF_FRAMES-eng: 198637
      NUMBER_OF_BYTES-eng: 355957504
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc58.108.100 aac
    Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      title           : 5.1 Channel
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS-eng         : 448000
      DURATION-eng    : 01:45:56.384000000
      NUMBER_OF_FRAMES-eng: 198637
      NUMBER_OF_BYTES-eng: 355957504
      _STATISTICS_WRITING_APP-eng: mkvmerge v28.0.0 ('Voice In My Head') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-15 23:00:12
frame=  121 fps=0.0 q=-1.0 size=    2560kB time=00:00:05.15 bitrate=4071.2kbits/s speed= 9.8x    ^Mframe=  169 fps=160 q=-1.0 size=    4608kB time=00:00:07.04 bitrate=5362.5kbits/s speed=6.68x    ^Mframe=  225 fps=142 q=-1.0 size=    7936kB time=00:00:09.34 bitrate=6958.0kbits/s speed=5.88x    ^Mframe=  295 fps=141 q=-1.0 size=   10752kB time=00:00:12.48 bitrate=7058.0kbits/s speed=5.95x    ^Mframe=  383 fps=147 q=-1.0 size=   12800kB time=00:00:16.09 bitrate=6514.7kbits/s speed=6.17x    ^Mframe=  535 fps=171 q=-1.0 size=   15360kB time=00:00:22.49 bitrate=5593.6kbits/s speed=7.19x    ^Mfra
...
frame=152223 fps=117 q=-1.0 size= 5004800kB time=01:45:49.18 bitrate=6457.4kbits/s speed=4.88x    ^Mframe=152341 fps=117 q
=-1.0 size= 5007872kB time=01:45:54.04 bitrate=6456.4kbits/s speed=4.88x
2021-01-28 02:52:12 - resources.mediaprocessor - ERROR - /gmedia/English Movies/xyz/xyz.mp4 deleted.
2021-01-28 02:52:12 - RadarrPostProcess - INFO - Processing returned False.
2021-01-28 02:52:12 - RadarrPostProcess - ERROR - Error processing file
Traceback (most recent call last):
  File "/usr/local/sma/postRadarr.py", line 175, in <module>
    sys.exit(1)
SystemExit: 1
`

Where would I start troubleshooting this?

**Comment by mdhiggins** [comment]
It looks like you cut off the log of the failed conversion before the error. Could you post the full error message?

**Comment by abhishekjain14** [comment]
Edited the message to add the very end of the error message. The output data of this movie is below:

`2021-01-28 02:30:22 - resources.mediaprocessor - INFO - Output Data
2021-01-28 02:30:22 - resources.mediaprocessor - INFO - {
    "source": [
        "/gmedia/English Movies/xyz/xyz.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 5468.5590999999995,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "title": "FHD",
        "debug": "video"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "samplerate": null,
            "filter": null,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo",
            "debug": "universal-audio"
        },
        {
            "map": 1,
            "codec": "copy",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        }
    ],
    "subtitle": [],
    "attachment": []
}
2021-01-28 02:30:22 - resources.mediaprocessor - INFO - Preopts
2021-01-28 02:30:22 - resources.mediaprocessor - INFO - []
2021-01-28 02:30:22 - resources.mediaprocessor - INFO - Postopts
2021-01-28 02:30:22 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]`

By contrast...here is a movie that actually got successfully converted:

`
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - Output Data
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - {
    "source": [
        "/gmedia/English Movies/abc/abc.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 6423.597,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "title": "FHD",
        "debug": "video"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "samplerate": null,
            "filter": null,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo",
            "debug": "universal-audio"
        },
        {
            "map": 1,
            "codec": "ac3",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        }
    ],
    "subtitle": [],
    "attachment": []
}
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - Preopts
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - []
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - Postopts
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - Subtitle Extracts
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - []
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - Starting conversion.
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - FFmpeg command:
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - ======================
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -i /gmedia/English Movies/abc/abc.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 768k -metadata:s:a:1 BPS=768000 -metadata:s:a:1 BPS-eng=768000 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /gmedia/English Movies/abc/abc.mp4
2021-01-28 02:52:20 - resources.mediaprocessor - INFO - ======================

`

**Comment by mdhiggins** [comment]
So it looks like an FFMpeg error that's not getting captured well by the logs. Can you try to run the generated FFMpeg command manually inside the container and post the error that is produced? You may need to put some quotes around the track titles with spaces (this is an artifact from how the command is printed in python but not a problem)

**Comment by abhishekjain14** [comment]
Absolutely. I will recreate this and update the thread as soon as I am able to get another failing file

**Comment by mdhiggins** [comment]
Also at some point recently I added some logic that accounts for the missing quotes in the command to make it more copy/paste friendly, if you update container it should get you that change

**Comment by abhishekjain14** [comment]
So it turns out to have been a segmentation fault...do you know how I might get ffmpeg_g into the container to run gdb? or is there a simpler solution?

also, recreating/updating the containers does not seem to have given me the missing quotes....to verify, docker-compose stop/rm/pull/up should give me the newest code right?

**Comment by mdhiggins** [comment]
Hm what was the seg fault? You shouldn't have to compile anything for the standard container tags, they just pull down precompiled binaries. There is a build tag you can use that uses another FFMPEG container (https://hub.docker.com/r/jrottenberg/ffmpeg/) to build from source and that would be the way to approach that. I'm not sure what ffmpeg_g is. Are you running this on some specialized hardware?

**Comment by mdhiggins** [comment]
With regards to the quotes, it should be in there I checked the repo and its included. I did a manual update of the container builds to make sure they're on the latest so you could try the update again but its been in there for a while so I'd be surprised if that hasn't made it in for the last few builds

**Comment by abhishekjain14** [comment]
ffmpeg_g is what I see here to get a core dump: https://ffmpeg.org/bugreports.html..."If you encounter a crash bug, please provide the gdb output, backtrace and disassembly, and if possible the valgrind output, using the the ffmpeg_g debug binary". If there's a simpler way to do it, do let me know and I will try it out.

The command itself gives me this message:

```Segmentation fault (core dumped) 5696000kB time=01:07:14.32 bitrate=11566.2kbits/s speed=8.12x```

Here is the message I get in the logs when running the command with a -report:

```cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
frame=  560 fps=0.0 q=-1.0 size=    2816kB time=00:00:23.38 bitrate= 986.8kbits/s speed=46.7x    ^Mframe=  767 fps=754 q=-1.0 size=    8960kB time=00:00:32.10 bitrate=2286.2kbits/s speed=31.6x    ^Mframe=  867 fps=571 q=-1.0 size=   15360kB time=00:00:36.11 bitrate=3484.0kbits/s speed=23.8x    ^Mframe=  977 fps=484 q=-1.0 size=   22016kB time=00:00:40.85 bitrate=4414.8kbits/s speed=20.2x    ^Mframe= 1073 fps=424 q=-1.0 size=   28672kB time=00:00:44.82 bitrate=5240.5kbits/s speed=17.7x    ^Mframe= 1135 fps=375 q=-1.0 size=   33024kB time=00:00:47.27 bitrate=5722.6kbits/s speed=15.6x    ^Mframe= 1237 fps=349 q=-1.0 size=   39680kB time=00:00:51.79 bitrate=6275.7kbits/s speed=14.6x    ^Mframe= 1341 fps=331 q=-1.0 size=   46336kB time=00:00:56.04 bitrate=6773.2kbits/s speed=13.8x    ^Mframe= 1458 fps=319 q=-1.0 size=   53248kB time=00:01:00.77 bitrate=7177.0kbits/s speed=13.3x    ^Mframe= 1540 fps=303 q=-1.0 size=   58112kB time=00:01:04.27 bitrate=7406.3kbits/s speed=12.7x    ^Mframe= 1662 fps=298 q=-1.0 size=   64256kB time=00:01:09.26 bitrate=7599.2kbits/s speed=12.4x    ^Mframe= 1776 fps=292 q=-1.0 size=   70912kB time=00:01:14.38 bitrate=7809.1kbits/s speed=12.2x    ^Mframe= 1900 fps=288 q=-1.0 size=   77568kB time=00:01:19.44 bitrate=7998.5kbits/s speed=  12x    ^Mframe= 1996 fps=281 q=-1.0 size=   82432kB time=00:01:23.30 bitrate=8106.0kbits/s speed=11.7x    ^Mframe= 2085 fps=274 q=-1.0 size=   87552kB time=00:01:27.12 bitrate=8232.2kbits/s speed=11.4x    ^Mframe= 2201 fps=271 q=-1.0 size=   93952kB time=00:01:31.92 bitrate=8372.6kbits/s speed=11.3x    ^Mframe= 2314 fps=268 q=-1.0 size=   99840kB time=00:01:36.59 bitrate=8467.0kbits/s speed=11.2x    ^Mframe= 2450 fps=268 q=-1.0 size=  106496kB time=00:01:42.22 bitrate=8533.9kbits/s speed=11.2x    ^Mframe= 2531 fps=261 q=-1.0 size=  110592kB time=00:01:45.68 bitrate=8572.4kbits/s speed=10.9x    ^Mframe= 2644 fps=259 q=-1.0 size=  116992kB time=00:01:50.35 bitrate=8684.5kbits/s speed=10.8x    ^Mframe= 2745 fps=256 q=-1.0 size=  123392kB time=00:01:54.51 bitrate=8826.9kbits/s speed=10.7x    ^Mframe= 2840 fps=253 q=-1.0 size=  130048kB time=00:01:58.48 bitrate=8991.5kbits/s speed=10.6x    ^Mframe=
....
 ^M[out_0_1 @ 0x5a9bbc0] EOF on sink link out_0_1:default.
No more output streams to write to, finishing.
Not writing 'clli' atom. No content light level info.
Not writing 'mdcv' atom. Missing mastering metadata.
```

Since the issue is occurring with a new test file, here is the command I am running, generated by SMA:

```
 /usr/local/bin/ffmpeg -i "/gmedia/English Movies/Killer's Kiss (1955)/Killer's Kiss (1955).mkv" -vcodec copy -map 0:0 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 1 -b:a:0 128k -metadata:s:a:0 BPS=128000 -metadata:s:a:0 BPS-eng=128000 -metadata:s:a:0 title=Mono -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/gmedia/English Movies/Killer's Kiss (1955)/Killer's Kiss (1955).mp4" -report
```

**Comment by mdhiggins** [comment]
Is it doing this with every file or just this specific file? Almost seems like a bad MKV

If you wanted to send me a copy I would take a look and see

**Comment by abhishekjain14** [comment]
I am testing another file, and will report back to you if it's the same behavior in the container...but it's doing this with most files, more often than not. I will be happy to send you a copy, but the files are generally 4-6 GB in size. If I can see the same behavior with a TV episode, say, which would be a smaller file, I can send you that, or try shrinking one of the files down.

Just in case there's a version issue... here is the version of ffmpeg in my container:

```
 /usr/local/bin/ffmpeg -version
ffmpeg version N-54441-gaa5e49e46d-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
libavutil      56. 60.100 / 56. 60.100
libavcodec     58.108.100 / 58.108.100
libavformat    58. 59.100 / 58. 59.100
libavdevice    58. 11.102 / 58. 11.102
libavfilter     7. 87.100 /  7. 87.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100
```

and here is my local version of ffmpeg:

```
 ffmpeg -version
ffmpeg version 4.3-2~18.04.york0 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr --extra-version='2~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Comment by abhishekjain14** [comment]
Curiouser....I tried another test....converting the file locally with the same autoProcess.ini, the only change being the paths to ffmpeg, and it worked. This suggests that it's an ffmpeg version issue...however I would love to see your luck with these files as well. I will try to shorten the file and reproduce the issue.

**Comment by mdhiggins** [comment]
Hm yeah maybe a recent FFMPEG build had a bug, I'll rebuild the containers and see if maybe they updated the stable branch

**Comment by abhishekjain14** [comment]
Just FYI...I am on the preview branch of your containers to get radarrv3 and sonarrv3.

**Comment by mdhiggins** [comment]
Preview/Nightly branches and latest branches should be the same as far as SMA/FFMPEG goes, that tag only impacts the parent Sonarr/Radarr containers

**Comment by mdhiggins** [comment]
Any news on this? Gonna close for inactivity soon

**Comment by abhishekjain14** [comment]
Looks like an ffmpeg version issue. Any possible workarounds for this?

**Comment by mdhiggins** [comment]
Updating the container should fix it unless it continues to be broken on latest builds. You could also use the build tag on the containers to compile FFMpeg from source of various versions. See the read me for details

**Comment by mdhiggins** [comment]
Closing but feel free to continue discussion if there's persistent issues
