### ISSUE TITLE
Remux files(truehd, AVC, dolby) fails conversion

### ISSUE THREAD

**Issue by Rhainland** [mdhiggins/sickbeard_mp4_automator#1403]
Hi,
Im having some issues where it seems remux files fails conversion, with errors such as;
`Error initializing output stream 0:2 -- Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height`

Without knowing the exact reason, im thinking its probably got something to do with the audio tracks, despite default settings in SMA that should ignore things like truehd.

My question is;
Which settings should be set in order for these kind of files to pass through? I tried changing output to mkv, but it doesnt process it due to;

_Bypassing conversion and setting outputfile to inputfile._

I have read the documentation on the above, and it says to use it with caution as it may create duplicate streams, so im not too sure if i should enable this, and use mkv to process remux files?

Appreciate any advice

**Comment by mdhiggins** [comment]
`stream #0:2` is probably an audio stream

**Post the logs** of your conversion if you want me to take a look. It looks like you aren't remuxing stream 2 and the encoder is failing, its probably a bad bitrate setting or something but without more info I can't help

Full passthrough needs the input and output formats to be the same, plus all streams being copy, plus a specific combination of settings, but at that point the file is not touched and its kind of moot

Duplicate streams result if you're using the universal audio option or sometimes the copy-original options and processing the file multiple times

**Comment by Rhainland** [comment]
I dont have the logs for this one anymore, ill try and see if i can replicate this with another move and post some logs.

Ill close the issue by tomorrow if im unable to replicate it
