### ISSUE TITLE
Multiple AutoProcess.ini (Windows)

### ISSUE THREAD

**Issue by lukasmd1989** [mdhiggins/sickbeard_mp4_automator#1404]
Hi, 

i am trying to set up two AutoProcess.ini for two different transcoding settings (1. higher bit rate for movies, 2. lower bit rate for tv shows).

I saw a few example on how to set in up on Linux, but I cannot find a solution for Windows.

This was my first attempt:
`IF "%5" == "tv" SET SMA_CONFIG = "C:\path\to\autoProcessTV.ini"
python "C:\path\to\SABPostProcess.py" "%1" "%2" "%3" "%4" "%5" "%6" "%7"`

This is the sabnzbd output:
`C:\Program Files\SABnzbd>IF "tv" == "tv" SET SMA_CONFIG="C:\path\to\autoProcessTV.ini"

C:\Program Files\SABnzbd>python "C:\path\to\SABPostProcess.py" "E:\Downloads\complete\series\Anthony.Bourdain.No.Reservations.S07E09.Cuba.REAL.720p.HDTV.x264-MOMENTUM.2" "Anthony.Bourdain.No.Reservations.S07E09.Cuba.REAL.720p.HDTV.x264-MOMENTUM.nzb" "Anthony.Bourdain.No.Reservations.S07E09.Cuba.REAL.720p.HDTV.x264-MOMENTUM" """" "tv" "alt.binaries.teevee" "0"
2021-01-30 19:06:23 - SABPostProcess - INFO - SAB post processing started.
2021-01-30 19:06:23 - resources.readsettings - INFO - C:\path\to\python.exe
2021-01-30 19:06:23 - resources.readsettings - INFO - Loading config file C:\path\to\autoProcess.ini.`

So, even though I try to load the **autoProcessTV.ini** using the SMA_CONFIG parameter if the category is TV, it still loads the regular **autoProcess.ini**.

I also tried to run it without the "IF"-Statement, but with the same result. What am I missing?

_Specs:_
Windows 10 (64 bit)
Python 3.8
Latest version of MP4 Automator
Sonarr v2

**Comment by mdhiggins** [comment]
Is it perhaps just an issue with your IF statement?
If you set the SMA_CONFIG without the IF statement does it properly change the path to the config file?

```
SET SMA_CONFIG="C:\path\to\autoProcessTV.ini"
python "C:\path\to\SABPostProcess.py" "%1" "%2" "%3" "%4" "%5" "%6" "%7"
```

**Comment by mdhiggins** [comment]
Is python for some reason not inheriting your environment variables from the batch file?

**Comment by mdhiggins** [comment]
Can do a quick test with a python file and a batch file

Python
```
import os
print(os.environ["SMA_CONFIG"])
```

Batch
```
SET SMA_CONFIG="TEST"
python test.py
```

**Comment by lukasmd1989** [comment]
Hi mdhiggins,

thank you for you fast reply. I tested the provided script and was surprised the the output was **"TEST"** instead of **TEST**, which made me think if maybe the quotation marks are the culprit.

I run the same SMA_CONFIG script now without the extra quotation marks:
`SET SMA_CONFIG=C:\path\to\autoProcessTV.ini
python "C:\path\to\SABPostProcess.py" "%1" "%2" "%3" "%4" "%5" "%6" "%7"`

This change did the trick and the **autoProcessTV.ini** setting was used. I kept trying different settings additionally, e.g. this one also works:
`SET "SMA_CONFIG=C:\path\to\autoProcessTV.ini"
python "C:\path\to\SABPostProcess.py" "%1" "%2" "%3" "%4" "%5" "%6" "%7"`

And now with the IF statement:
`IF "%5" == "tv" SET "SMA_CONFIG=C:\path\to\autoProcessTV.ini"
python "C:\path\to\SABPostProcess.py" "%1" "%2" "%3" "%4" "%5" "%6" "%7"`

Thank you for your help!
