### ISSUE TITLE
how to type comma into .ini settings

### ISSUE THREAD

**Issue by mezzovide** [mdhiggins/sickbeard_mp4_automator#1405]
for example:
postopts = -force_key_frames,expr:gte(t,n_forced*2)
always translated to ffmpeg commands :
-force_key_frames expr:gte(t n_forced*2)

**Comment by mdhiggins** [comment]
37b72b6218c1fb092720918de92e62116b3af068

There you go

Adds a new option called `opts-separator` where you can define what character will be used by the preopts/postopts values as the separator. Just change it to something other than a comma. Wiki updated
