### ISSUE TITLE
feature request : audio (and video) filter profile

### ISSUE THREAD

**Issue by mezzovide** [mdhiggins/sickbeard_mp4_automator#1406]
right now theres no way to set filter for different specific source afaik.
Just like crf had crf-profiles, would be great if we can have profile for audio / video filter too. 

example:

if source audio = 5.1 and max-channels = 2 use this as a filter `pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE`

if source audio = stereo and max-channels = 2 do not use filter at all

**Comment by mdhiggins** [comment]
So the filter system would discriminate based on number of desired channels and number of source channels?

```
Assuming this setting:
pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

Source: 5
max-channels: 5
No filter applied

Source: 5
max-channels: 2
Filter applied

Source: 2
max-channels: 2
No filter applied
```

Is that essentially how the flow should work?
If source channels < output channels, apply, but you'd need to specific filters for each combination of input channels and output channels

That would also mean you would need to include something in the key value about source channels and target channels

`6>2:pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE`

So something like `inputchannels>outputchannels` as the key?

**Comment by mdhiggins** [comment]
Think I have a pretty solid concept working here

https://github.com/mdhiggins/sickbeard_mp4_automator/tree/fancyfilters

This adds a new section to the config that looks like this

```
[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE
```

The key `6-2` indicates that input channel count and the output channel count separated by a `-` and anything after the first `=` is the filter that will be applied

You could define plenty of other combinations as well, an example would be 8 channel input to stereo as `8-2`

This should work in combination with other audio filters that are set in the `[Audio]` section of the config

**Comment by mezzovide** [comment]
Okay will test asap. Thanks!

**Comment by mdhiggins** [comment]
Merged into master, please reopen if there is issues
