### ISSUE TITLE
Need some help with HDR processing

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#1407]
I'm trying to convert an HDR video. Mainly, I want to convert it like I do every video. So that the video can be used for streaming.

I'm getting errors when I attempt to do this, and then the video just gets passed to radarr/sonarr and nothing is converted.

Here's all the info I could think of getting for you.

config: https://pastebin.com/UvNeQLSH
sma.log: https://pastebin.com/jGqVv1Ki
Media Info: https://pastebin.com/TY4b19WJ

Any help?

**Comment by mdhiggins** [comment]
x264 [error]: high profile doesn't support a bit depth of 10
 
[libx264 @ 0000020c64893540] Error setting profile high.
 
[libx264 @ 0000020c64893540] Possible profiles: baseline main high high10 high422 high444

Try using high10 for your profile

**Comment by DatsiK96** [comment]
Wouldn't that make all encodes high10 though? Is it possible to get that to only be used with HDR encoding?

**Comment by mdhiggins** [comment]
You could potentially just leave the profile setting blank and let it maintain the same profile as the source

**Comment by mdhiggins** [comment]
The other option that might allow you to leave high as your profile is to leave high and set a different pix-fmt so FFMPEG knows how to convert like yuv420p

**Comment by DatsiK96** [comment]
I apologize, I'm a bit ignorant on all this stuff. I'm trying to maintain the HDR in the original video. But I want to convert it to the quality standards I have so that it's not as large as the original, also not in MKV. How can I accomplish this?

**Comment by mdhiggins** [comment]
You'll probably want to read up on HDR encoding if you're doing that as its way more complicated and you'll likely need to preserve and set HDR metadata. But some simple HDR encodes you just need to stop forcing your HDR content into a non HDR profile. Just remove the `high` option from your profile settings to let FFMPEG default to something it can work with

**Comment by DatsiK96** [comment]
I'm still confused, I'm researching and many sources are saying that x264 can/can't support HDR, but all the videos that I have that are HDR are x265. If I remove the profile, would I have to change the codec as well?

For maximum support across the devices that everyone uses it needs to be x264 at the moment. Do you know if I can achieve HDR with x264 or has someone else achieved it?

**Comment by mdhiggins** [comment]
H264 can do up to 10 bit HDR

And no, you can remove the profile. I also added some additional options to have a different profile for HDR content (see the latest update)

efaebc9a69fc7ef8f1db07715e93f1d653c82c68

But this getting off hand and these are more general codec / FFMPEG questions so you might need to redirect these questions to a different channel. I am far from an FFMPEG expert
