### ISSUE TITLE
Conversion fails

### ISSUE THREAD

**Issue by hoyane** [mdhiggins/sickbeard_mp4_automator#1408]
Hi, hoping you can help with this. I am running your radarr-sma docker on two different servers. On one it works fine on the same exact file that fails on the other. I have compared and matched every single setting and permission i can see to no avail. It fails right before the qtfs stage. The logs mention a dts warning but there is no dts track in the file. 

Any help appreciated!

Here is the sma.log https://pastebin.com/raw/mmGMHGyw
My config file https://pastebin.com/raw/F1ucHVmr

**Comment by mdhiggins** [comment]
This is an FFMpeg error, if it's working on one and not the other it might be a transient bad FFMpeg build try updating the container. 

A quick google search says this may also be a problem with your source file and adding the following to your post-opts in settings might help

-vsync, drop

**Comment by hoyane** [comment]
Thanks! The vsync did not help but the update docker suggestion did. I use portainer and I always have this box checked that is supposed to pull the latest image but i noticed the ffmpeg version was older which made me notice the image was actually old also. Apparently it doesnt pull and thus i was on older version. Started fresh with the terminal command to pull and now it works.

Thanks

**Comment by mdhiggins** [comment]
Good stuff
