### ISSUE TITLE
Reducing Video Bitrate

### ISSUE THREAD

**Issue by sowie2016** [mdhiggins/sickbeard_mp4_automator#1409]
I've just moved to a new system and brought my old configuration with me. Updated Distro Ubuntu 20.04

The Video Bitrate of files converted doesn't seem to be getting reduced by the script. The FFmpeg process completes as expected. I have run manually and below is the ffmpeg command used for the autoprocess.ini.

`/root/bin/ffmpeg -fix_sub_duration -i "File/Location" -vcodec copy -map 0:0 -metadata:s:v title="FHD" -metadata:s:v handler_name="FHD" -c:a:0 libfdk_aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title="Stereo" -metadata:s:a:0 handler_name="Stereo" -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:3 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "File/Location"
`

Attached autoProcess.ini

[Converter]
ffmpeg = /root/bin/ffmpeg
ffprobe = /root/bin/ffprobe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
force-convert = True
post-process = False
preopts = 
postopts = 
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
minimum-size = 0
bypass-if-copying-all = False
wait-post-process = False
detailed-progress = False
opts-separator = ,

[Permissions]
chmod = 0755
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = False
preserve-source-disposition = False
sanitize-disposition = 

[Video]
codec = h264
bitrate = 3000
crf = -1
crf-profiles = 
max-width = 
profile = main
max-level = 4.0
pix-fmt = 
max-bitrate = 0
bitrate-ratio = 
preset = 
codec-parameters = 
dynamic-parameters = False
filter = 
force-filter = False

[Audio]
codec = libfdk_aac
languages = eng
default-language = eng
first-stream-of-language = True
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 2
prefer-more-channels = True
default-more-channels = True
filter = 
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = 
force-filter = False
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = libfdk_aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Subtitle]
codec = mov_text
codec-image-based = mov_text
languages = English, eng
default-language = English, eng
first-stream-of-language = True
encoding = 
burn-subtitles = False
download-subs = True
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
ignore-embedded-subs = False
attachment-codec = 
burn-dispositions = 
filename-dispositions = forced
ignored-dispositions = 
unique-dispositions = False

**Comment by sowie2016** [comment]
Noticed there's now a new autoProcess.ini.sample with some new options. Transferred existing config to that and now working as expected.

Thank You for a great tool

**Comment by mdhiggins** [comment]
Thanks for the follow up!
