### ISSUE TITLE
hevc_qsv complains about encoding parameters unsupported when using -level x.y insted of -level xy

### ISSUE THREAD

**Issue by Dark4Codrutz** [mdhiggins/sickbeard_mp4_automator#1411]
Example command :
`ffmpeg.exe -hwaccel qsv -vcodec hevc_qsv -init_hw_device qsv=hw -filter_hw_device hw -i input.mkv -vcodec hevc_qsv -load_plugin hevc_hw -level 4.0 -vb 5M -y output.mkv`

Gives output error: on hevc_qsv 
```
Using input frames context (format qsv) with hevc_qsv encoder.
Using the average variable bitrate (AVBR) ratecontrol method
Selected ratecontrol mode is unsupported
some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

While changing to -level 40 (the issue being the dot notation):
`ffmpeg.exe -hwaccel qsv -vcodec hevc_qsv -init_hw_device qsv=hw -filter_hw_device hw -i input.mkv -vcodec hevc_qsv -load_plugin hevc_hw -level 40 -vb 5M -y output.mkv`
There is no error outputted by hevc_qsv:
```
Using input frames context (format qsv) with hevc_qsv encoder.
Using the average variable bitrate (AVBR) ratecontrol method
 profile: main10; level: 40
```
And the conversion starts normally.

This issue could be solved from both SAM's side and qsvenc library side (which [doesn't do any checks)](https://github.com/FFmpeg/FFmpeg/blob/c0d0b1c4f6f804796488adf3e552be88c0cee1a4/libavcodec/qsvenc.c#L433) ... but I'm kindly asking if you can manage this notation conversion in your python code.
I'll try and work on a solution myself if time gives.

**Comment by Dark4Codrutz** [comment]
For now, based on how things are, my only workaround is to set max-level to 40.
This will make the conversion work but SAM will never decide to convert video stream based on level criteria again.

**Comment by mdhiggins** [comment]
Is this specific to the QSV HEVC encoder or is this an issue with all HEVC encoders?

**Comment by Dark4Codrutz** [comment]
> Is this specific to the QSV HEVC encoder or is this an issue with all HEVC encoders?

Haven't checked anything other than hevc_qsv so far.
I will check later other encoders but my guess is that it's only qsvenc.c having troubles with dot notation seen that it is the one complaining.

**Comment by mdhiggins** [comment]
I would think so but you never know

7c4d0999c76491d29f4925427fedaca5473c229f

That should fix it for you. Continue to the dot notation like the rest of the script but before it passes the command to FFMPEG it will convert it to the *10 version

**Comment by Dark4Codrutz** [comment]
Oh , I see. Thank you for the prompt fix.

I will test the other encoders tonight.
I'm expecting to see the error on other qsv encoders specifically.
The code line I mentioned in OP is not hevc specific, it's at the root of
ffmpeg's qsv implementation (in qsvenc.c)

**Comment by mdhiggins** [comment]
Got it

a28f3ce7ad7ececd8c350f57b8b87765237861dc

That adds it to the h264 qsv parameters as well

**Comment by Dark4Codrutz** [comment]
> Got it
> 
> [a28f3ce](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/a28f3ce7ad7ececd8c350f57b8b87765237861dc)
> 
> That adds it to the h264 qsv parameters as well

Sorry for the late reply.
I've manually tested  h264_qsv with -level 4.0 and -level 40 , they both work.
This means that only hevc_qsv is having issues with -level 4.0 notation.
You can safely revert a28f3ce

**Comment by mdhiggins** [comment]
I think I'll leave it just so the 2 QSV based codecs are consistent since it looks like it accepts either variant

Closing this out
