### ISSUE TITLE
Quotations Appearing in Metadata

### ISSUE THREAD

**Issue by niallobr** [mdhiggins/sickbeard_mp4_automator#1412]
I'm seeing the below quotation marks appearing around strings in the metadata of converted mp4 files

![Screenshot 2021-02-15 at 16 46 48](https://user-images.githubusercontent.com/204252/107973753-86693800-6fad-11eb-8edb-5f7c42908dea.jpg)

My postopts section in autoProcess.ini looks like this, just in case it could be interfering with the default tagging behaviour

`postopts = -map_metadata,-1,-max_muxing_queue_size,9999`

Could one of the recent commits to mediaprocessor.py have caused it?

https://github.com/mdhiggins/sickbeard_mp4_automator/commits/594def7f737e2996f2a81e90c7c6b5a665f606f8/resources/mediaprocessor.py

**Comment by mdhiggins** [comment]
7ba3a3c7e95c1163c221038762281d792595f9e1

See if that fixes it

Despite FFMPEG docs indicating the quotes should come after the metadata `=` sign it looks like when it comes from python they're getting evaluated literally and included in the string. That update should fix that

**Comment by niallobr** [comment]
Working great now thanks @mdhiggins 🥇(just tested this with 2 conversions) 

Closing
