### ISSUE TITLE
ffprobe HEVC reported levels are weird, be aware ! 

### ISSUE THREAD

**Issue by Dark4Codrutz** [mdhiggins/sickbeard_mp4_automator#1415]
Not really an issue as I haven't came across any problematic scenarios (at least not yet).

As listed in [h265_profile_level.c#L22](https://github.com/FFmpeg/FFmpeg/blob/7ac41e0db2a03f749f43b69f370461bc6bfee38f/libavcodec/h265_profile_level.c#L22) from ffmpeg github you have a list of the usual levels (**names**) in dot notation form next to **level_idc** values, which is what ffprobe actually outputs.

![image](https://user-images.githubusercontent.com/18706363/108422669-25549500-7237-11eb-9fed-2afdbf7f4eb1.png)

The formula for converting dot notation to level_idc is a moltiplicative by 30, where X represents units and Y represents subunits:
`X.Y = X * 30 + Y * 3` so for eg. `level 4.1 = 4 * 30 + 1 * 3 = 123 level_idc` (or just multiply 4,1 * 30)
To convert backwards, from level_idc to dot notation you simply need to divide by 30:
from my previous example `126 / 30 = 4,1` which is level 4.1

Don't go crazy over it, but some special checks for HEVC in case of _video level restriction_ might be needed.

**Comment by Dark4Codrutz** [comment]
Examples in code that I managed to find:
https://github.com/mdhiggins/sickbeard_mp4_automator/blob/ac0130e01b1a10b17b30a40ca2991cb55e65846f/converter/ffmpeg.py#L164-L166 as well as https://github.com/mdhiggins/sickbeard_mp4_automator/blob/a62e5a3041bad312cb660e5c1c2364c69954c662/resources/mediaprocessor.py#L515-L516 you divide by 10 already but you should check if hevc and divide by 30.

ffmpeg should handle the multiplication when given dot notation form as input , except for hevc_qsv which you previously fixed (also it exempts from the rule)

**Comment by mdhiggins** [comment]
Nice deep dive there

Check this change
7f9828ee215ff78b24ddc2157cbdedb05a515e66

Instead of just universally dividing by 10 I included some static methods in the codec classes for adjusting the ffprobe reported value and handle that adjustment during the ffprobe phase

**Comment by Dark4Codrutz** [comment]
I keep getting this error right now, can't test.
https://github.com/mdhiggins/sickbeard_mp4_automator/blob/b2f9528b1d741127a03878ab8f322a1c70b3c0ca/manual.py#L419

I'm a bit stuck.

**Comment by Dark4Codrutz** [comment]
nvm, I think I know why. 
I was using an video-only 10bit mkv file which I use for ffmpeg testing. Never used it with SMA.

**Comment by mdhiggins** [comment]
Yeah it will reject files without at least 1 audio track

**Comment by mdhiggins** [comment]
Did using a different file allow you to test?

**Comment by Dark4Codrutz** [comment]
> Did using a different file allow you to test?

yes, as long as there is an audio track.

**Comment by mdhiggins** [comment]
Alright gonna close this then, looks like on my end its reporting the proper dot notation level

**Comment by Dark4Codrutz** [comment]
yeah, sorry I forgot to say that It works as intended !

**Comment by mdhiggins** [comment]
I figured as much but thanks for following up
