### ISSUE TITLE
Error in SABnzbd

### ISSUE THREAD

**Issue by redvision10** [mdhiggins/sickbeard_mp4_automator#1417]
Hi

I am running Ubuntu 18.04 on linux.

I am getting this issue when SABnzbd tries to run the converter script:

Traceback (most recent call last):
File "/sickbeard_mp4_automator-master/SABPostProcess.py", line 5, in <module>
from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
File "/sickbeard_mp4_automator-master/autoprocess/autoProcessMovie.py", line 11, in <module>
import requests
ImportError: No module named requests

Anyone know how to fix this issue? 

Thanks

**Comment by mdhiggins** [comment]
You need to install the requests module, its pretty straight forward

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Dependencies

If you're done this, then SAB is probably executing scripts from a different python environment and you'll need to address the fact that you have 2 environments and direct the script to be executed in the one where you installed your dependencies

https://github.com/mdhiggins/sickbeard_mp4_automator/issues?q=label%3A%22multiple+environments%22

Many people have had this issue
