### ISSUE TITLE
replace invalid character for windows directory naming

### ISSUE THREAD

**Issue by mezzovide** [mdhiggins/sickbeard_mp4_automator#1418]
Some torrents name using what considered invalid to be used when making directory under windows. `e.g :` making post processing stopped working. it should be replaced/substituted.
```
qBittorrentPostProcess - ERROR - Unable to make output directory E:\Transcode\The Hobbit: The Desolation of Smaug (2013) Extended.
Traceback (most recent call last):
  File "C:\sma\qBittorrentPostProcess.py", line 91, in <module>
    os.makedirs(settings.output_dir)
NotADirectoryError: [WinError 267] The directory name is invalid: 'E:\\Transcode\\The Hobbit: The Desolation of Smaug (2013) Extended'
```

**Comment by mdhiggins** [comment]
9479b2b06e896f7599dcd2119803ff072b0718e6

See if that does the trick for you, applied the change across deluge/qBT/uTorrent which should be the only situation where its pulling torrent names as a directory name

**Comment by mezzovide** [comment]
yeah i think its a little too aggresive, because it also remove these allowed characters `e.g ( )[ ]`. But hey it works. no complains here. thanks!

**Comment by mdhiggins** [comment]
Yeah that's intended, its the most cross-os compatible safe way to handle this from other articles I read and it should only impact those folder names so not a big deal, gonna close this glad its working
