### ISSUE TITLE
sonarr keeps redownloading the same episodes over and over

### ISSUE THREAD

**Issue by Emmer123** [mdhiggins/sickbeard_mp4_automator#1423]
Hi, 

Sorry to bother you, and i'm sure it's something i did wrong, but i hope you can help me with an issue. 
I'm using the docker image which has worked just fine for a week or so. what it usually did was download>import>convert>rename
however the episodes that are downloaded over and over lack that rename stage, but i'm unsure if that's the cause of the problem.
I just found it was a difference between the episodes that are redownloaded constantly. 

I have recently turned off the schedule for series update, because i never ever delete anything and my library is quite large it took litterally days to complete with quite a high load on the storage. 

I'm hoping somebody can assist me in pointing out the correct log files to check why it does this. it does update series on import and they do show in sonarr that they are available. But it does keep downloading them. I've ever tried disabling propers etc. but that doesn't seem to solve it. 

thank you very much for reading.

**Comment by mdhiggins** [comment]
Not enough information here to really tell you anything specifically but it sounds like you aren't passing your downloaded files back to Sonarr. Without know what container and downloader you're using I can't give specifics but you probably need to turn on completed download handling or configure one of the downloader scripts to notify sonarr that the download has finished

Post logs, specific information about your configuration and what containers you're suing, screenshots of the relevant settings within the apps, etc if you want some more assistance. At this point I'm not sure this even has anything to do with SMA and might just be you didn't set up Sonarr correctly

**Comment by Emmer123** [comment]
Ah yes sorry for the lack of information, i've followed the steps on this github to set up the docker, so i've added the connect custom script postsonarr.sh and enabled completed download handling. using sabnzbd (or deluge, but i don't think it matters that much since both worked perfectly before). docker image is mdhiggins/sonarr-sma 

I do agree that it may well be sonarr that's messing up, however the only things i've really changed is add sma, and from the sma logs i can't really tell the steps it's taking, apart from the actual encoding. 
what i noticed was that it renamed it after transfer to the completed folders which was different than bare sonarr. 
I'll try with some other log level of sonarr to see why it thinks it needs to redownload, i've already disabled propers and the cutoff is just 1080 which is met. 

Again, sorry to take up your time by reading this, i just need a little nudge in the right direction to investigate it. 
Thank you very much

**Comment by mdhiggins** [comment]
The renaming side of things is all sonarr, SMA doesn't impact that at all or do any renaming of its own. You don't have sabnzbd or deluge set up to also run post processing scripts on top of completed download handling do you (SABNZBPostProcess.py / DelugePostProcess.py)?

postSonarr.py does do some API notifications as part of its routine that potentially might be causing issues so take a look at the SMA logs as well and see if there's some issue with the API updates (sma.log)

**Comment by Emmer123** [comment]
i think there was a strange bug in the version of sonarr at the time, it stopped now, in case anybody wonders it was a bug in the decision making using the preferred words... thank you very much anyway for the tips, 
and thank you for the awesome dockers, eac3 was making my life a living hell, but now everything is perfect aac :)

**Comment by mdhiggins** [comment]
Glad you got it sorted out
