### ISSUE TITLE
Unable to use manual.py in Sonarr/Radarr without manual pip install

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [mdhiggins/sickbeard_mp4_automator#1424]
I've setup both your Sonarr and Radarr docker containers, however when I try to run manual.py on either image, to hit pre-existing files, I get the following:

```root@d7e3058ba8ae:/usr/local/sma# python3 manual.py -i /data/Videos/Movies/ -a
Traceback (most recent call last):
  File "manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'```

This is the using either the `preview` tag on Sonarr, or `latest` on Radar. There's no requirements file, so I've been trying to manually add it.

I had to manually install `guessit`, `tmdbsimple`, `mutagen`, and `qtfaststart` to get it working. So far at least.

**Comment by mdhiggins** [comment]
All the requirements are installed in a virtual python environment within the container so as to not interfere with any existing python requirements at the operating system level

`$SMA_PATH/venv/bin/python3 $SMA_PATH/manual.py` will get you what you need

And there is a requirements.txt file in `$SMA_PATH/setup/requirements.txt` for future reference which is used during the container setup and can be seen in the Dockerfile
