### ISSUE TITLE
Error while using manual.py

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1425]
Hello,
The script errors out on a specific anime file for some reason, any ideas?
[sma.log](https://pastebin.com/raw/CRneWQsd)
[autoProcess.ini](https://pastebin.com/raw/Bj3VTvTK)

**Comment by mdhiggins** [comment]
Does disabling the `strip-metadata` option have any impact?

**Comment by mdhiggins** [comment]
Also feel free to send the file my way so I can take a look

**Comment by mdhiggins** [comment]
So I found the issue, looks like certain pieces of metadata are required for font attachments that were being stripped away by the strip-metadata option
Added an extra line of code that includes this metadata even with strip-metadata enabled, should be fixed now

a8cea834b0610a60e999b6ec4aee86c3fa51b141

**Comment by mdhiggins** [comment]
b3cfce6c754bd7349dde9e576d88571b9ca188d4

Made a slight change to the approach rather than copying all metadata for attachments I just included the relevant pieces (mimetype and filename)

**Comment by Smalfinn** [comment]
Working perfectly again, thank you very much for the speedy patch!
