### ISSUE TITLE
subtitle credentials

### ISSUE THREAD

**Issue by Petterooe** [mdhiggins/sickbeard_mp4_automator#1427]
Hi! Thanks! for your good work.
In readsettings.py row 816. I had to add keys 'username' and  'password'  for download to work with opensubtitles.
-   self.subproviders_auth[key.strip()] = {credentials[0]: credentials[1]}
+  self.subproviders_auth[key.strip()] = {'username': credentials[0], 'password': credentials[1]}

I tried to search subliminal why that is, with no luck??

**Comment by mdhiggins** [comment]
Yeah looks like this is actually the correct syntax as referenced here

https://github.com/Diaoul/subliminal/issues/848

8c72971c790b074121115b677a0762414be28195

That should fix it
