### ISSUE TITLE
Cannot run ./manual.py from within the docker container.

### ISSUE THREAD

**Issue by belrpr** [mdhiggins/sickbeard_mp4_automator#1428]
Hi,

I've created the docker container on my synology nas:
`docker run -d \
  --name=radarr \
  -e PUID=1029 \
  -e PGID=100 \
  -e TZ="Europe/Brussels" \
  -p 7878:7878\
  -v /volume1/docker/radarr:/config \
  -v /volume1/docker/sma:/usr/local/sma/config \
  -v /volume2/media/movies:/movies \
  -v /volume3/downloads:/downloads \
  --restart unless-stopped \
  mdhiggins/radarr-sma`

Then I ssh into the container:
`docker exec -it 39003bbcabf7 bash`

Then I copied the autoprocess.ini.sample from the /usr/local/sma/setup to /usr/local/sma/config directory.
Then I tried to run ./manual.py

but keeps getting:
`
root@39003bbcabf7:/usr/local/sma# ./manual.py
Traceback (most recent call last):
  File "./manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'`

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/radarr-sma/issues/11
