### ISSUE TITLE
Radarr/Sonarr Instructions Update

### ISSUE THREAD

**Issue by bakerboy448** [mdhiggins/sickbeard_mp4_automator#1429]
neither Sonarr nor Radarr support drone factory anymore.
 it sounds like the instructions are for v0.2 and v2, both are EOL. V3 of both applications is out and stable 

you may also want to clarify that either the download client needs to call the script (completed download handling is off)  (I also assume that script then triggers a manual import into Sonarr?)  or completed download handling stays enabled (likely the preferred/recommended? Route) and the script gets called with on download (and if they want on upgrade) (which is triggered once imported)

**Comment by mdhiggins** [comment]
I feel like this is covered in the readme already and the script has never used the drone factory folder specifically

https://github.com/mdhiggins/sickbeard_mp4_automator#sonarr-setup

I even bolded the more relevant part for emphasis

**You must use either a download script or enabled Completed Download Handling. If neither are used the file will never be passed back**

**Comment by bakerboy448** [comment]
If users are following it step-by-step they're going to be extremely confused

>Set the Drone Factory Interval' to 0 to disable it,

This no longer exists.s

> disable 'Completed Download Handling' in Sonarr settings. 

This is ill-advised and results in a persistent healthcheck.

I'd suggest moving step 4 to step 3 and then changing step 4 (fka step 3) to start with

Alternatively, if you wish to process downloads prior to {ARRNAME} importing the media into your library then you'll need to disable Completed Download Handling and configure your download client to call the script..........[continued]

**Comment by mdhiggins** [comment]
e433e09b21248df679310425cac59833c4edcb27
