### ISSUE TITLE
Guide to install the mp4_automator

### ISSUE THREAD

**Issue by movibeast** [mdhiggins/sickbeard_mp4_automator#1430]
Hi,

I use the 
- ubuntu 18.04 
- Sonarr
- Deluge
- rClone

**Sonarr Info**
Version : 3.0.5.1144
Package Version : 3.0.5 by Team Sonarr
Mono Version : 6.12.0.122
AppData directory : /home/appbox/.config/Sonarr
Startup directory : /usr/lib/sonarr/bin

So I have set the download directory to my google drive.

I tried to install the mp4_automator but I failed. It 
https://prnt.sc/10q1803
It says above error, I am not sure what wrong I did. I tried to do exactly given in the wiki.
Please help, I am newbie so please forgive me for my stupid question.

Thanks

**Comment by mdhiggins** [comment]
Well the error changed slightly, first error before the edit looked like a permission error with lack of execute permissions but I guess you fixed that

The follow error is vague and isn't too helpful. The sonarr logs should show you more details about why the error occurred but its probably crashing due a missing dependency or something

Check the sonarr logs after the crash and post the full error

Another good idea would be to make sure that you can open manual.py from the command line without any errors, that's a good way to ensure your config is setup correctly and you're not missing any dependencies

If you find the errors, please post them back here

**Comment by movibeast** [comment]
Yes, you are right. I was able to fix the first error. it was easy but for second it is getting hard.
I will check the sonarr log and post it here today.

Thank you for quicky reply :)

**Comment by mdhiggins** [comment]
Gonna close this due to inactivity but feel free to continue discussion
