### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1431]
Hi sir,

How would the variables in "Run external program on completion" look like in qBit if I wanted to extract RARs before I convert them?

Referring to:
https://github.com/mdhiggins/sickbeard_mp4_automator#qbittorrent-setup

I currently have it set like this:
`"/usr/bin/unrar" x -ibck -inul "%F/*.r*" "%F/" && "/usr/bin/python3 /opt/scripts/sma-qbit/qBittorrentPostProcess.py" "%L" "%T" "%R" "%F" "%N" "%I"`

I can't get it to work. Any ideas?

**Comment by mdhiggins** [comment]
This isn't directly supported, you're probably better off writing a small script to handle extraction if you're downloading torrents that are compressed (relatively rare) and then having that pass the data to either qBT or manual.py

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1181

Here is an example

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/qBittorrent-Unrar-Script
