### ISSUE TITLE
Script removes square brackets from folder and file names

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1433]
Hello,

I've just noticed that the script replaces square brackets [] within a folder or file name with underscores_
So qBittorrent downloads "2.Broke.Girls.S01.1080p.WEB-DL.DD5.1.H264-NOGRP[rartv]" but when SMA triggers it is renamed to "2.Broke.Girls.S01.1080p.WEB-DL.DD5.1.H264-NOGRP_rartv_-convert"

Doing so while downloading confuses sonarr, especially with anime releases, into not importing said files because the square brackets are used to define the release group at the beginning of the name

Was this intentional?

**Comment by mdhiggins** [comment]
a747400ee28cc56332d03dcbecbd24c9dbbc0a64

There you go

The regex replace string is now an option so you can choose which chars you want to keep or discard

`regex-directory-replace`

**Comment by mdhiggins** [comment]
Updated wiki

**Comment by Smalfinn** [comment]
Awesome, thank you!
