### ISSUE TITLE
Commands not being passed to sonarr/radarr suddenly from QBT

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1435]
Not sure if this is a script issue, but for some reason in the last 2 days when a transcode is finished from qbittorent its not being passed to sonarr/radarr for pick up yet with sabnzbd its still works fine, I have also noticed that anything that's transcoded from qbt is not appearing in the log file so I have no clue as to what's going on.

The Transcodes are still executing perfectly its just the post processing that's not lol.

**Comment by mdhiggins** [comment]
Something must be wrong with your QBT post processing script, if its not going into logs but still converting makes me think you have maybe a second version of the script or python environment or something.

Need more info if you want help. All the scripts use the same notify code so if one works and the other doesn't its probably just not reaching the final step from QBT but if you're getting so far as to have the file actually converted you should definitely have something in the log files. Turn on debug logging and take a look.

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by morpheus2n2** [comment]
Just tested it on 2 files and still not producing a log yet is converting them just fine

**Comment by mdhiggins** [comment]
Something is messed up with your setup then or you have another installation somewhere, or I guess maybe a permission issue with the log files themselves though I would think that would cause and early crash

**Comment by morpheus2n2** [comment]
Not sure why, cos sabnzbd works 100% and its all using the same script and same drives, how odd

**Comment by mdhiggins** [comment]
That leads back to maybe a permissions issue then

**Comment by morpheus2n2** [comment]
hmmm, with QBT or the script? (Windows 10)

**Comment by morpheus2n2** [comment]
> That leads back to maybe a permissions issue then

Ok I have deleted and redownloaded the script and also changed the "Security" on the folder to everyone, all's working with Sab I am going to uninstall QBT and redo that to see if that works, cos if still didn't

**Comment by morpheus2n2** [comment]
Yep all out of ideas, I have changed the permissions, I cant work out why one client works and the other only half works.
It all converts perfect just dosn't get moved nor dose it appear in the logs at all.

Both the script and also QBT have been removed and reinstalled, the only thing that has changed since this all started was a new build of QBT was released otherwise its the same marching and setup I have been using fine months with not a single issue

**Comment by mdhiggins** [comment]
Does rolling back to the old version of QBT fix it?

Post some pics of your QBT configuration

**Comment by morpheus2n2** [comment]
Ok rolling back has not fixed it so not sure if that was what broke it.
<img width="1920" alt="2021-04-23 (1)" src="https://user-images.githubusercontent.com/14253602/115804107-31e19f00-a3da-11eb-8828-6c473fd27fb7.png">
<img width="1920" alt="2021-04-23 (2)" src="https://user-images.githubusercontent.com/14253602/115804111-3312cc00-a3da-11eb-82ef-2e14f2206494.png">
<img width="1920" alt="2021-04-23 (3)" src="https://user-images.githubusercontent.com/14253602/115804112-3312cc00-a3da-11eb-9171-111f63ea72a4.png">
<img width="1920" alt="2021-04-23 (4)" src="https://user-images.githubusercontent.com/14253602/115804113-3312cc00-a3da-11eb-9f1c-f6bc2af10856.png">
<img width="1920" alt="2021-04-23" src="https://user-images.githubusercontent.com/14253602/115804115-33ab6280-a3da-11eb-847b-3580d315329f.png">

**Comment by mdhiggins** [comment]
Also what's the .bat file look like you're using, just want to confirm everything

And logs are you looking at

**Comment by morpheus2n2** [comment]
<img width="1920" alt="2021-04-23 (5)" src="https://user-images.githubusercontent.com/14253602/115838862-01b5f280-a412-11eb-859e-eea09faa1342.png">
And the log file is the SMA.txt under Config (I delete it before each test to see whats going on)

**Comment by mdhiggins** [comment]
But the log files are recreated each time? That means it's running. Does anything show up or is it empty

**Comment by morpheus2n2** [comment]
thats the thing its not recreated when anything from QBT triggers, Sab and Manual recreate fine QBT dosn't but will convert the file

**Comment by morpheus2n2** [comment]
Its also worth nothing that if I point QBT to the raw .py file it never at all triggers I can reproduce this on 3 machines but if I use that bat file it will trigger the encoding just fine (Just not the moving or the log file pmsl)

**Comment by mdhiggins** [comment]
Does manually running the bat file with some fake command line parameters to mimic QBT show any errors? Open command prompt so you can see what the output is and send a screenshot

**Comment by morpheus2n2** [comment]
How would I do fake commands? cos I can get this out of it if I just run it via CMD
<img width="1920" alt="2021-04-23 (6)" src="https://user-images.githubusercontent.com/14253602/115926536-eb904c80-a47a-11eb-9859-c77dbbadeef0.png">

**Comment by mdhiggins** [comment]
Your own screenshot shows what each of the parameters need to be
https://user-images.githubusercontent.com/14253602/115804115-33ab6280-a3da-11eb-847b-3580d315329f.png

`qBittorrentPostProcess.bat "faketorrent" "faketracker" "C:\fakepath\root" "C\fakepath\root\" "torrentname" "fakehash"`

You can probably make up nonsense for most of these just have some text in there so the number of arguments is correct and just make sure the two paths point somewhere that exists (can use one of your existing torrent folders)

**Comment by morpheus2n2** [comment]
🤦‍♂️ Here you go, did it on a real one and it runs fine.
<img width="1920" alt="2021-04-24 (1)" src="https://user-images.githubusercontent.com/14253602/115941914-6d926c80-a49f-11eb-884b-dfcea013a217.png">
<img width="1920" alt="2021-04-24" src="https://user-images.githubusercontent.com/14253602/115941915-6e2b0300-a49f-11eb-99eb-ce0425fb39fc.png">

Or you want me to make up a fake one

**Comment by mdhiggins** [comment]
Can you post the full debug logs from that job? A real one is preferred

**Comment by morpheus2n2** [comment]
Still not showing in logs but I get this
<img width="1920" alt="2021-04-24 (2)" src="https://user-images.githubusercontent.com/14253602/115942068-37a1b800-a4a0-11eb-817d-1b5ed38bd738.png">

**Comment by morpheus2n2** [comment]
Just looking, Why would QBT have API problems with Sonarr yet Sab doesn't when using the exact same autoprocess file?

**Comment by mdhiggins** [comment]
I would need to see some logs from SAB to confirm that's true as well

And just to be clear, SMAdir/config/sma.log is the file you're looking at correct? I can't imagine why you wouldn't get logs
Also can you copy and paste the full text from the command prompt and post it?

**Comment by mdhiggins** [comment]
And post one from SAB too for comparison

**Comment by morpheus2n2** [comment]
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6368767/sma.log)

Yep

This is what I put into the CMD 
A:\PlexBackend\Converter\config>cd a:\plexbackend\converter

a:\PlexBackend\Converter>qbittorent.bat "Sonarr" "udp://9.rarbg.me:2820" "D:\Downalods\To Convert\Sydney.to.the.Max.S03E06.My.Own.First.Enemies.720p.HULU.WEBRip.AAC2.0.H264-LAZY[rarbg]" D:\Downloads\To Convert\Sydney.to.the.Max.S03E06.My.Own.First.Enemies.720p.HULU.WEBRip.AAC2.0.H264-LAZY[rarbg]" "684fa958e4c25357540de89a2c9751db1d24f9a7"

**Comment by mdhiggins** [comment]
Found the problem

You have the script installed on 2 different drives, A and C
Your bat file is calling C and sonarr is using A

Told you that you had 2 installs

**Comment by morpheus2n2** [comment]
> And post one from SAB too for comparison

Sorry didn't see that replay, a sab manual trigger? or the log file from above

**Comment by morpheus2n2** [comment]
> Found the problem
> 
> You have the script installed on 2 different drives, A and C
> Your bat file is calling C and sonarr is using A
> 
> Told you that you had 2 installs

Oh wait that will be when I moved it from C: to A: I must have forgotten to change the bat 🤦‍♂️ Now I just feel stupid sorry about all this lol
