### ISSUE TITLE
Auto add videos to Sonarr/Radarr

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1436]
Just curious since you already have the Sonarr and Radarr API stuff setup and you are already looking up movies in TMDB and TV Shows with TVDB. What are the chances you could just auto add new movies to Radarr and auto add new TV shows to Sonarr? It would be nice to throw stuff at qBittorrent or call from a post processing script from JDownloader 2 to have it auto added and imported in to Radarr and Sonarr. It would in essence add back in the black hole stuff they removed. So you could just pass the video to your script and it would toss correctly to Raddar or Sonarr and let them handle it from there.

I also am thinking about how this would be useful for when you rip your own videos it would further automated things. Specifically I have been using ARM (Automatic Ripping Machine) to easily rip my music and movies.

JDownloader 2
https://jdownloader.org/jdownloader2
https://hub.docker.com/r/jlesage/jdownloader-2

ARM (Automatic Ripping Machine)
https://github.com/automatic-ripping-machine/automatic-ripping-machine
https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/362 (Docker info)

**Comment by mdhiggins** [comment]
Not something I would look to do but accessing the Radarr API isn't something that requires any magic. You're sort of going in the opposite direction of what this script does; it makes no assumptions about content identification but instead uses identifiers passed from Radarr/Sonarr for accuracy purposes.

You might be able to do something with a combination of manual.py and a custom post-process script 
https://github.com/mdhiggins/sickbeard_mp4_automator#post-process-scripts
