### ISSUE TITLE
SMA-MOD NZBGet invalid magic upon deployment

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1441]
Hi there,

I just gave GET a go with sma-mod, had a little tinker with it but got it working pretty fast. Which I haven't been able to in the past. So kudos to SMA-MOD and your work. Appreciated!

However, it fails upon deployment when trying to install dependencies I think. I was given PP-FAILURE every time even though the path to SMA was accurate. See logs from the container below.
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying mdhiggins/sma-mod:latest files to container
tar: invalid magic
tar: short read
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
```
I had to bash in to container and pip install the requirements, after a docker restart it post-processed without issues.

After I rebuilt the container, to make sure it was the dependencies, I got PP-FAILURE again. So it looks like it might be dependencies that fails installing upon deployment.

Just a heads up!

**Comment by mdhiggins** [comment]
I think this might still be a failure related to them trying to get docker-mods working because this stage of execution is before any of my code gets executed

**Comment by morganzero** [comment]
> I think this might still be a failure related to them trying to get docker-mods working because this stage of execution is before any of my code gets executed

Oh yeah, totally forgot about that. We can only hope they get it sorted soon enough. Is your deluge working though?

**Comment by mdhiggins** [comment]
No not yet, they haven't updated the deluge container yet (26 days since the last update)

**Comment by mdhiggins** [comment]
Just to confirm, I pulled the latest docker-mods installation script and replaced the one included currently and it installs fine, so I think we're just waiting for those changes to propagate down to their containers

**Comment by morganzero** [comment]
Awesome! Fingers crossed 🤞

**Comment by mdhiggins** [comment]
Looks like deluge got updated today and is working

**Comment by morganzero** [comment]
Woohoo :)
