### ISSUE TITLE
opensubtitles not downloading

### ISSUE THREAD

**Issue by SharedHelp** [mdhiggins/sickbeard_mp4_automator#1443]
Hello,

I swear I'm not going mad, i've previously had no issues downloading subtitles, added in the necessary username and password but now whenever SMA runs it just always returns no results, I even went to the trouble of matching the file name exactly to the sub one on it and still nothing.

I ran the request using subliminal CLI and it connected and pulled the matching sub from opensubtitles fine.

The only difference is I'm now using ubuntu 20 from ubuntu 18.

Any help appreciated and thanks for the continued great work.

**Comment by mdhiggins** [comment]
Turn on debug level logging and see if subliminal is throwing some errors. Post some logs of it failing and your config settings or I can't help

**Comment by SharedHelp** [comment]
any more help with this?

thanks in advance

**Comment by mdhiggins** [comment]
Sorry this issue had randomly disappeared for a while then came back I guess

I think the reason that subliminal isn't trying here is that your source file has a subtitle stream in the appropriate language, it is however failing to rip that subtitle track and I'm not sure why. Could you send me a copy of this file? I'm having a hard time finding a sample DVDSUB file to test against

**Comment by mdhiggins** [comment]
Are you deleting this issue for some reason after you update it? It keeps appearing briefly then 404’ing From: SharedHelpSent: Wednesday, May 26, 2021 9:17 PMTo: mdhiggins/sickbeard_mp4_automatorCc: Michael Higgins; CommentSubject: Re: [mdhiggins/sickbeard_mp4_automator] opensubtitles not downloading (#1443) any more help with this?thanks in advance—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SharedHelp** [comment]
Hi, Sorry for it constantly disappearing. Github kept marking my account as spammy when I replied here but they have told me they have fixed it now.

What is the best way to send you the file? I did also trying removing dvdsub as a valid codec but it still wouldn't download and I need the sub format in .srt

**Comment by mdhiggins** [comment]
It also looks like FFMPEG isn't able to extract dvdsub tracks

**Comment by mdhiggins** [comment]
Any info on this? Going to close due to inactivity if I don't hear from you
