### ISSUE TITLE
Radarr suddenly not working

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1447]
Not sure if Radarr changed something but the last 2 weeks this is all I get from SMA when it calls on Radarr to do its job lol.

2021-06-05 16:18:59 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "A:\PlexBackend\Converter\autoprocess\radarr.py", line 71, in processMovie
log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
KeyError: 'state'

I have verified the Address and API key and have also changed the API just to see but this sis all I ever get, I can't see anthing in the Radarr logs to say its received a command from SMA

**Comment by mdhiggins** [comment]
Can you access your API using any manual commands?
What version of Radarr?
They wouldn't just modify the API the API to the point where they break all connections so unless you're running nightly build and there's a problem that's breaking the API I would say its something on your own setup

**Comment by mdhiggins** [comment]
https://radarr.video/docs/api/

You should be able to plug in your server settings on the radarr api website and test commands

**Comment by morpheus2n2** [comment]
Not via the script no, but other apps that use the api like Petio etc all communicate and connect just fine, I even copied the API key and ip from the autoconfig to see if may be i was getting it down work and it worked fine.

V4.
Thats what I though cos SMA is the only thing that spits out a error yet all the settings are correct and have been tested on other apps for clarification its very odd lol

**Comment by mdhiggins** [comment]
Wasn't aware V4 even launched, that might be the issue, looks like its only a few days old. Does reverting to V3 fix things?

**Comment by mdhiggins** [comment]
You might need to post some sample API returns for V4 as it looks like its not documented yet

**Comment by morpheus2n2** [comment]
umm good point, I will try and downgrade and let you know

**Comment by morpheus2n2** [comment]
Ok have just spotted this.
4.0.0.5077
—
31 May 2021 nightly Previously Installed
New - Remove Legacy API

**Comment by mdhiggins** [comment]
94d081404748fe7c7ab7fb8dd5eac370b3cba921

Try that update and see if it helps

**Comment by morpheus2n2** [comment]
Ok will test have just asked on discord and the response was
Same as V3
Musta been using a legacy endpoint
if that means anything to you :D

**Comment by mdhiggins** [comment]
Yeah the update I just posted changes to V3 and removes that one last legacy endpoint

**Comment by morpheus2n2** [comment]
ahh ok cool

**Comment by morpheus2n2** [comment]
Yep all fixed thank you :D
