### ISSUE TITLE
[Request] Multiple Extensions?

### ISSUE THREAD

**Issue by blastbeng** [mdhiggins/sickbeard_mp4_automator#1452]
Hello,
is it possibile to have SMA converts mkv to mkv and mp4 to mp4?
I don't want my library to convert all mkvs to mp4, i just want to convert everything that is not in correct extension to mp4 except mkvs

Thanks

**Comment by blastbeng** [comment]
Hello,
is it possibile to have SMA converts mkv to mkv and mp4 to mp4?
I don't want my library to convert all mkvs to mp4, i just want to convert everything that is not in correct extension to mp4 except mkvs

Thanks

**Comment by mdhiggins** [comment]
Only kind of

If you're just looking to convert your old library and don't want to touch the MKV files, you can add mkv to your `ignored-extensions` option

If you did want to process MKV files but wanted a different set of rules for those files (like keeping them MKVs), just make another autoProcess.ini config and write a small wrapper that calls manual.py using whichever version of the config you want to apply based on your own criteria

**Comment by blastbeng** [comment]
Nice solution, however for now i'm using this script

`#!/usr/bin/env bash

extension="${sonarr_episodefile_relativepath##*.}"


if [[ "$extension" == "mkv" ]]; then
        sed -i 's/output-format = mp4/output-format = mkv/' /config/sma/autoProcess.ini
        sed -i 's/output-extension = mp4/output-extension = mkv/' /config/sma/autoProcess.ini
else
        sed -i 's/output-format = mkv/output-format = mp4/' /config/sma/autoProcess.ini
        sed -i 's/output-extension = mkv/output-extension = mp4/' /config/sma/autoProcess.ini
fi


$SMA_PATH/venv/bin/python3 $SMA_PATH/postSonarr.py`

For mkv i keep mkv conversion. For everything else i transcode to mp4. Not an elegant solution, maybe I can call postRadarr.py with a different autoProcess.ini ? Is that possible?

**Comment by mdhiggins** [comment]
There's a global environment variable `SMA_CONFIG` that can be set before you call the script that will override which config file it uses, that should work with your bash script nicely, just set that in your IF statement and keep 2 version of an autoProcess.ini for each scenario

**Comment by blastbeng** [comment]
Ok so that should work:

```
#!/usr/bin/env bash

extension="${sonarr_episodefile_relativepath##*.}"


if [[ "$extension" == "mkv" ]]; then
        SMA_CONFIG="/config/sma/autoProcessMkv.ini"
else
        SMA_CONFIG="/config/sma/autoProcessMp4.ini"
fi


$SMA_PATH/venv/bin/python3 $SMA_PATH/postSonarr.py
```

**Comment by mdhiggins** [comment]
Yeah that should do the trick

You can probably also check for the sonarr vs radarr environment variables that get added and direct to postRadarr.py or postSonarr.py accordingly then have a universal *arr bash script for both of those

https://wiki.servarr.com/Radarr_Tips_and_Tricks#On_Download.2FOn_Upgrade

https://wiki.servarr.com/Sonarr_Tips_and_Tricks#On_Download.2FOn_Upgrade
