### ISSUE TITLE
Radarr Setup

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1454]
Is this correct for Radarr setup V3?

![bild](https://user-images.githubusercontent.com/57449785/124124314-92dfc000-da78-11eb-8b7c-ca455f3a3a43.png)

![bild](https://user-images.githubusercontent.com/57449785/124124345-9a9f6480-da78-11eb-9e19-4d6035583ef8.png)

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/124169363-2a8edf80-da74-11eb-948a-27ab480f5cda.png)

Yeah they changed the language around a little, I'll update the readme
Attached my settings for reference

**Comment by morganzero** [comment]
Awesomeness! Thanks!

**Comment by mdhiggins** [comment]
0738d706361ae87b3ec2986f846c518117b5fe25
