### ISSUE TITLE
logrotate exception

### ISSUE THREAD

**Issue by Petterooe** [mdhiggins/sickbeard_mp4_automator#1458]
When use multiple instances of manual.py script I got a nasty logrotate exception on every update of processbar (file in use).
I've made an addition at the end of log.py for bypass.
Used this for some months now and not noticed any errors.
##### changed this
        return logging.getLogger(name)
##### to this
        log = logging.getLogger(name)
        [rotatehandler] = [x for x in log.handlers if type(x).__name__=='RotatingFileHandler']  or [None]
        if rotatehandler: 
              rotatehandler.rotator = rotator
        return log
    import shutil
    def rotator(source, dest):## logging.RotatingFileHandler rotate override
        try:
            shutil.copyfile(source, dest)## copy logfile  to new file
            open(source, 'w').close()## clears sma.log content
        except Exception as ex: print("Fail when rotate logfiles: %s" % (ex))

**Comment by mdhiggins** [comment]
Could you post the exception you're seeing?

**Comment by Petterooe** [comment]
Good you asked so I must try to reproduce with current code. This time I did not get exception when progressbar update with level info log, only with debug enabled. With log level info it only appears on every log.info command. It's the first started script that lock the logfile and can rename it, the following script can't.

[                    ] 1% --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
    self.doRollover()
  File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] Unable to access file because it
used by another process: 'C:\\Users\\Pao\\sickbeard\\sickbeard_mp4_automator\\config\\sma.log' -> 'C:\\Users\\Pao\\sickbeard\\sickbeard_mp4_automator\\config\\sma.log.1'
Call stack:
  File "C:\Users\Pao\sickbeard\sickbeard_mp4_automator\resources\mediaprocessor.py", line 170, in process
    outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress, progressOutput)
  File "C:\Users\Pao\sickbeard\sickbeard_mp4_automator\resources\mediaprocessor.py", line 1677, in convert
    self.log.debug(debug)
Message: 'frame= 1766 fps= 55 q=33.0 size=   18176kB time=00:01:13.98 bitrate=2012.6kbits/s speed=2.32x'
Arguments: ()

**Comment by mdhiggins** [comment]
4e8477ed5b2b4e68a5eada01c1ff9d07cde9d602

Take a look at this solution and see what you think

Did a couple things here

First I removed writing the debug lines to the log file, this probably just eats up a ton of space for no value

I then based a method off your solution but included the default os.rename method first since this is what python does when it rotates files and just use the shutil solution as a fallback

**Comment by Petterooe** [comment]
All I can say it looks like a work of art. 
The problem should also appear  when downloads finishes at the same time and stack up, not only when use manual.py. 
I only use deluge, and as there are no tagging there I send them instead to manual.py where all my crazy addons are and a gui. A waiting method are made in def process where they wait for ffmpeg to exit to continue.
Have spotted one small thing in your code, in readsettings.py there are two os.path.makedirs hiding behind Try,Except for a long time apperantly os.path.makedirs does not exist only os.makedirs does.

**Comment by mdhiggins** [comment]
Good catch, fixed that

acf5e12f8b85e6bb8ebc2254cc50d6dadfb473a5
