### ISSUE TITLE
Radarr 

### ISSUE THREAD

**Issue by hstorey219** [mdhiggins/sickbeard_mp4_automator#1460]
Hello there, 
I believe that I am following instructions correctly Running Radarr 3.2.2.5080 
When I try to create new Connect using postRadarr.py
I get this error message 
[log.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6835588/log.txt)

**Comment by mdhiggins** [comment]
Seems like you may not have python installed or do not have your operating system configured to execute python files

**Comment by hstorey219** [comment]
> Seems like you may not have python installed or do not have your operating system configured to execute python files

Hi There,
On the same machine, for Sonarr, the post script runs fine inside Sonarr. Sorry, if I am missing something here

**Comment by mdhiggins** [comment]
Post a screenshot of your connect configuration for me preferably for both Radarr and Sonarr

**Comment by hstorey219** [comment]
> Post a screenshot of your connect configuration for me preferably for both Radarr and Sonarr

![image](https://user-images.githubusercontent.com/14917850/126082251-f94d2016-710b-4178-88c8-14fab4734742.png)

This is the Bat file

![image](https://user-images.githubusercontent.com/14917850/126082258-e299c2d2-e648-4129-a827-48f78662f823.png)
Sonarr Connect
![image](https://user-images.githubusercontent.com/14917850/126082268-6ec71ca4-f866-4fad-9d4f-b68772d1d184.png)
Radarr Connect

**Comment by mdhiggins** [comment]
Your bat file is bad, you're executing FFMPEG and providing the script as an argument

You need to either just run the .py file or point to the python file and use that as an argument

I'm guessing your Sonarr one looks different

**Comment by hstorey219** [comment]
> Your bat file is bad, you're executing FFMPEG and providing the script as an argument
> 
> You need to either just run the .py file or point to the python exe and use the script as the argument
> 
> I'm guessing your Sonarr one looks different and has the correct exe
> 
> Your current bat is just passing a python file to ffmpeg which makes no sense

Ok, sorry I got confuse with this statement lol Thank you for helping me! 
For Sonarr V3 you'll need to make a .sh or .bat file to combine your path to python and script
