### ISSUE TITLE
Question - Rolling Logs with custom name

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1462]
I have created separate logging.ini files for radarr and sonarr which are mounted to the docker containers.  I changed the line below so that I have separate logs files.  Here is the example for sonarr:

```
args = ('%(logfilename)s', 10000, 1)  --> args = ('/usr/local/sma/config/sonarr-sma.log', 10000, 1)
```
I end up with separate log files, but the logs are not rotating.  I have one sonarr log file which currently has 300K+ lines and similarly for radarr.

I made this change quite a while ago, so I can't remember what all variations I tired at this point.  Is what I am trying to do achievable and what is the proper syntax for separate logging with rotation?

**Comment by mdhiggins** [comment]
`('%(logfilename)s', 'a', 1000000, 3, 'utf-8')` is the current default

**Comment by mdhiggins** [comment]
And just to clarify the parameters

1. Filename
2. Mode (a is default for auto)
3. Size
4. Number of backups

Looks like your current iteration will fail for 2 reasons, you're missing the 'a' parameters so all your subsequent parameters are in the wrong position
You only have 1 backup setup per your final argument of 1

**Comment by samcro1967** [comment]
If I am interpreting the syntax correctly, the below should get me what I am looking for?
args =  ('%(/usr/local/sma/config/radarr-sma.log)s', 'a', 10000, 3, 'utf-8')

**Comment by mdhiggins** [comment]
Not quite, the %()s syntax is for variables, if you're manually specifying the path just do a normal string

`('/usr/local/sma/config/radarr-sma.log', 'a', 10000, 3, 'utf-8')`
