### ISSUE TITLE
Couchpotato postprocessing - help?

### ISSUE THREAD

**Issue by herbi3** [mdhiggins/sickbeard_mp4_automator#1466]
anyone having success with CouchPotato post processing?

CP is still using py2 and development seems to have stopped. Any work arounds so far?

**Comment by mdhiggins** [comment]
CP is essentially abandoned at this point. You can roll back to older versions of SMA but would recommend just migrating to Radarr which is still being actively updated.

If there's a specific error you're getting I can take a look but many of the libraries this script depends on require python 3 now so my efforts to maintain backwards compatibility don't matter much

**Comment by herbi3** [comment]
Thanks @mdhiggins, I think I might have to do that, CP seems to be done with. Thanks!

**Comment by mdhiggins** [comment]
05d8fde5adf2910eb51d3c2adc9f83a728d24fc3

Going to deprecate CouchPotato support since it doesn't work anyway, I don't think many people use it cause no one has mentioned it doesn't work and likely hasn't for some time. Highly recommend Radarr as an alternative
