### ISSUE TITLE
Ability to change fps

### ISSUE THREAD

**Issue by lowski** [mdhiggins/sickbeard_mp4_automator#1467]
Hey!
Thank you for this tool, it's awesome!

I have quick question: is it possible to change number of frames per second of the movie? I believe ffmpeg has support for `fps` option which allows for that.

**Comment by mdhiggins** [comment]
You can probably use `post-opts` for this, just add your desired change with a comma to separate

`post opts = -fps, 30` for example

**Comment by lowski** [comment]
Awesome, thank you!
