### ISSUE TITLE
Trying to Run ffmpeg after building sonarr-sma getting error with ffmpeg_tag:4.1-nvidia

### ISSUE THREAD

**Issue by coolvicky2** [mdhiggins/sickbeard_mp4_automator#1470]
when i'm trying to run ffmpeg inside dockers container i'm getting this following errror

ffmpeg: error while loading shared libraries: libnppig.so.10: cannot open shared object file: No such file or directory

so then i'm running this command to fix the issue

apt update && apt upgrade -y && apt install -y \
      libnppig10 \
     libnppicc10 \
     libnppidei10
     
  it's giving me this error below
  
apt update && apt upgrade -y && apt install -y  libnppig10  libnppicc10   libnppidei10
  
Hit:1 http://download.mono-project.com/repo/ubuntu bionic/snapshots/5.20 InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                       
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                               
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease          
Hit:5 https://mediaarea.net/repo/deb/ubuntu bionic InRelease
Reading package lists... Done                     
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Conflicting distribution: http://download.mono-project.com/repo/ubuntu bionic/snapshots/5.20 InRelease (expected bionic/snapshots/5.20 but got bionic)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libnppig10
E: Unable to locate package libnppicc10
E: Unable to locate package libnppidei10

in sonarr i'm unable to locate these packages for some reason , not sure it's permisson issue or where im going wrong with it

and sma.log , in /usr/local/bin folder giving me following error

2021-08-10 00:30:57 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2021-08-10 00:30:57 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2021-08-10 00:30:57 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2021-08-10 00:30:57 - resources.mediaprocessor - INFO - File /home/Broken But Beautiful/Season 3/Broken.but.Beautiful.S03E01.720p.WEB-DL.AAC2.0.x265.mkv is not valid
2021-08-10 00:30:57 - SonarrPostProcess - INFO - Processing returned False.
2021-08-10 00:30:57 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 307, in <module>
    sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
Your base image is using bionic which doesn't contain these packages
The develop branch of the base linuxserver sonarr image has been migrated to focal which includes these packages (radarr is already on focal so its not an issue). Set your `sonarr-tag` to develop and the packages should be available

Make sure you're using the same version of Linux to build your FFMpeg binaries as well (in this case using the `nvidia2004` tag). It might actually eliminate the need to install these packages at all
