### ISSUE TITLE
Error Initializing Output Stream

### ISSUE THREAD

**Issue by Dead-Rekon** [mdhiggins/sickbeard_mp4_automator#1474]
I just updated for the first time in quite a while. I have the same settings as my previous install (copy original audio, including TrueHD, add aac 2.0, output mkv). The new install has been failing on the occasional file. Log included. File is 1080p, 8 channel TrueHD, 5 channel ac3. Older version (6+ months old) converts the same file without issue.

[Log.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/7108185/Log.txt)

**Comment by mdhiggins** [comment]
Looks like you're attempting to create an 8 (7.1) channel DTS audio track which FFMPEG doesn't support, not sure why the older one would work without logs unless it was before DTS was even supported and thus a non-issue

d195b6e22b97b86a8600514a5d4607819d1b20e9

That patch adds a cap to DTS codec to prevent you from setting inappropriately high channel count
