### ISSUE TITLE
qBittorrent PostProcess.sh Bash Script Failing, 'cannot assign function call'

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1475]
Running into the following error when I noticed qBittorrent post processing didn't ingest a tv show one of my users requested. I ran the PostProcess.sh interactively just to see if I would see anything different and this is what I got:

	12 rar files found and extracted
	Traceback (most recent call last):
	  File "/opt/mp4automator/qBittorrentPostProcess.py", line 9, in <module>
		from resources.readsettings import ReadSettings
	  File "/opt/mp4automator/resources/readsettings.py", line 1033
		config.get(k).get(sk) = old
		^
	SyntaxError: cannot assign to function call

There is nothing in the sma.log file to show for this attempt for post processing after a download has completed in qbittorrent.

The postProcess.sh bash script being executed is:

	#!/bin/sh

	torrentid=$6
	torrentname=$5
	torrentpath=$4
	torrentrootpath=$3
	torrenttracker=$2
	torrentcategory=$1

	pathextraction=/dwnldr/tor/extracted
	pathconversion=/dwnldr/tor/converted

	pythonpath=/usr/local/bin/python3.8
	smapath=/opt/mp4automator

	if [ "$torrentcategory" = "bypass" ]; then
		#echo "skipping this since it's in the bypass category"
		exit 0
	fi

	if [[ -d "$torrentrootpath" ]]; then
		#echo "$torrentrootpath" + " is a directory"
		mkdir "$pathextraction/$torrentname"
		mkdir "$pathconversion/$torrentname"
		/opt/qbittorrent/unrarall/unrarall -v -o "$pathextraction/$torrentname" "$torrentrootpath"
		extracted=$?
		wait $!
		if [ $extracted -eq 0 ]; then
			if [[ -n $(find "$pathextraction/$torrentname" -type f -size +50M) ]]; then
				"$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$pathextraction/$torrentname" "$pathextraction/$torrentname" "$torrentname" "$torrentid"
			else
				"$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
			fi
		else
			"$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
		fi
		rm -rf "$pathextraction/$torrentname"
	elif [[ -f "$torrentpath" ]]; then
		#echo "$torrentpath" + " is a file"
		"$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
	fi

	exit 0

**Comment by mdhiggins** [comment]
Fixed here
b4e9435e3d48f66b64e3eedda0f0108a7e5c7250
