### ISSUE TITLE
Running Nvidia and after update this is error i'm getting

### ISSUE THREAD

**Issue by coolvicky2** [mdhiggins/sickbeard_mp4_automator#1477]
root@/# ffmpeg 
ffmpeg: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory

any solution to this please

ARG ffmpeg_tag=4.4-nvidia
ARG sonarr_tag=develop
FROM jrottenberg/ffmpeg:${ffmpeg_tag} as ffmpeg
FROM linuxserver/sonarr:${sonarr_tag}
LABEL maintainer="mdhiggins <mdhiggins23@gmail.com>"

# Add files from ffmpeg
COPY --from=ffmpeg /usr/local/ /usr/local/

ENV SMA_PATH /usr/local/sma
ENV SMA_RS Sonarr
ENV SMA_UPDATE true

# get python3 and git, and install python libraries
RUN \
  apt-get update && apt-get upgrade -y && \
  apt-get install -y \
    git \
    wget \
    python3 \
    python3-pip \
     libnppig10 \
     libnppicc10 \
     libnppig11  \
     libnppidei10 && \
# make directory
  mkdir ${SMA_PATH} && \
# download repo
  git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git ${SMA_PATH} && \
# install pip, venv, and set up a virtual self contained python environment
  python3 -m pip install --user --upgrade pip && \
  python3 -m pip install --user virtualenv && \
  python3 -m virtualenv ${SMA_PATH}/venv && \
  ${SMA_PATH}/venv/bin/pip install -r ${SMA_PATH}/setup/requirements.txt && \
# ffmpeg
  chgrp users /usr/local/bin/ffmpeg && \
  chgrp users /usr/local/bin/ffprobe && \
  chmod g+x /usr/local/bin/ffmpeg && \
  chmod g+x /usr/local/bin/ffprobe && \
# cleanup
  apt-get purge --auto-remove -y && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

RUN \
        apt-get update -y && \
        apt-get install -y --no-install-recommends libva-drm2 libva2 i965-va-driver && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

EXPOSE 8989

VOLUME /config
VOLUME /usr/local/sma/config

**Comment by mdhiggins** [comment]
There's been other issues on this, recommend matching your ubuntu version across container and ffmpeg build container, in this case 2004
