### ISSUE TITLE
Coverting Video Codec suggestions

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1481]
I would like to convert all my codecs to VP9 except AV1. I know that I can set a bitrate-ratio = h264:0.6, hevc:0.8 which is fine but can I add a 0.5 with no codec for every other codec that isn't h264 or hevc?

codec = vp9, av1
bitrate-ratio = h264:0.6, hevc:0.8, 0.5

Is that valid?

Also is there a way to set a max-bitrate based on resolution?
480p max-bitrate=
576p max-bitrate=
720p max-bitrate=
1080p max-bitrate= 
1440p max-bitrate=
2160p max-bitrate=
4320p max-bitrate=

What rates would you suggest? Is there a better way to do this with like crf-profiles? If so what examples would you recommend? Also curious what options do I need to enable to keep any HDR encodes in VP9 and/or AV1?

**Comment by Protektor-Desura** [comment]
What I was asking about HDR is how to keep HDR when I am converting from HEVC HDR to VP9 and AV1, so the converted file is still HDR as well. I hope that make more sense.

https://developers.google.com/media/vp9/hdr-encoding
https://trac.ffmpeg.org/wiki/Encode/AV1

look like: -colorspace bt2020nc -color_trc smpte2084 -color_primaries bt2020 (for AV1)
-color_primaries 9 -color_trc 16 -colorspace 9 -color_range 1 (for VP9)
is the magic needed.

There is an example from Google using FFMPEG to do HDR in VP9. Not sure how that translates to your script though. I mean you can't create HDR from SDR, so there would have to be some way to detect HDR then use HDR ffmpeg commands on VP9 and AV1 to keep it.

**Comment by mdhiggins** [comment]
Alright got around to writing some updates to the VP9 codec class to translate some of the HDR framedata

```
class Vp9Codec(VideoCodec):
    """
    Google VP9 video codec.
    """
    codec_name = 'vp9'
    ffmpeg_codec_name = 'libvpx-vp9'
    ffprobe_codec_name = 'vp9'
    encoder_options = VideoCodec.encoder_options.copy()
    encoder_options.update({
        'profile': str,  # default: not-set, for valid values see above link
        'framedata': dict  # dynamic params for framedata
    })
    color_transfer = {
        "smpte2084": 16,
        "smpte2086": 18,
        "bt709": 1
    }
    color_primaries = {
        "bt2020": 9,
        "bt709": 1
    }
    color_space = {
        "bt2020nc": 9,
        "bt709": 1
    }

    def _codec_specific_parse_options(self, safe, stream=0):
        framedata = safe['framedata']
        if 'color_primaries' in framedata and self.color_primaries.get(framedata['color_primaries']):
            safe['color_primaries'] = self.color_primaries.get(framedata['color_primaries'])
        if 'color_transfer' in framedata and self.color_transfer.get(framedata['color_transfer']):
            safe['color_transfer'] = self.color_trc.get(framedata['color_transfer'])
        if 'color_space' in framedata and self.color_space.get(framedata['color_space']):
            safe['color_space'] = self.color_space.get(framedata['color_space'])
        if 'color_range' in framedata and framedata['color_range'] in [0, 1, 2]:
            safe['color_range'] = framedata['color_range']
        return safe

    def _codec_specific_produce_ffmpeg_list(self, safe, stream=0):
        optlist = super(Vp9Codec, self)._codec_specific_produce_ffmpeg_list(safe, stream)
        if 'profile' in safe:
            optlist.extend(['-profile:v', safe['profile']])
        if 'color_primaries' in safe:
            optlist.extend(['-color_primaries', safe['color_primaries']])
        if 'color_transfer' in safe:
            optlist.extend(['-color_trc', safe['color_transfer']])
        if 'color_space' in safe:
            optlist.extend(['-colorspace', safe['color_space']])
        if 'color_range' in safe:
            optlist.extend(['-color_range', safe['color_range']])
        return optlist
```
d94da0e031317b78c2fab2cf941627644fd82a2b

This should allow the framedata being read from the source to be translated over to the encoder for the following options

- color space
- color primary
- color transfer
- color range
- profile

pix fmt was already supported

Let me know how that works for you

**Comment by mdhiggins** [comment]
Closing for now, reopen with issues
