### ISSUE TITLE
Script exit status

### ISSUE THREAD

**Issue by Josh5** [mdhiggins/sickbeard_mp4_automator#1485]
I am working on integrating this into my Unmanic project as a plugin.
While doing this I noticed that the script does not produce a corresponding exit status when any of the commands that it ran fail.

Is this by design? Or is this something I can write up a PR to add? Would it break the current use-cases if we added a failure exit status to the sma manual.py script if, for example, the ffmpeg command fails?

For my project, I'm either going to wrap this up in another script that provides the correct exit status codes or I can look into modifying your SMA processes such that the manual.py script will exit with status 1 when any of it's processes failed.

**Comment by mdhiggins** [comment]
Manual is just meant to be run manually and thus the exit codes were not prioritized but if you wanted to submit a pull request to include them that would be totally fine
