### ISSUE TITLE
Raddar and Sonarr are unable to convert with Docker-MOD

### ISSUE THREAD

**Issue by mediacowboy** [mdhiggins/sickbeard_mp4_automator#1487]
Log's show that both containers are unable to import request again.

```
[Warn] RadarrErrorPipeline: Invalid request Validation failed: ,
[Error] postRadarr.sh: ModuleNotFoundError: No module named 'requests' ,
[Error] postRadarr.sh:     import requests ,
[Error] postRadarr.sh:   File "/usr/local/sma/postRadarr.py", line 4, in <module> ,
[Error] postRadarr.sh: Traceback (most recent call last): ,
 -- : Script exited with code: 1 
```

When I manual log into the container's and try to import request it fails as well.
```
~/docker/sonarr$ docker exec -it --user abc sonarr /usr/local/sma/venv/bin/python
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

Docker-Compose file:
` ``
 sonarr:
    container_name: "sonarr"
    image: ghcr.io/linuxserver/sonarr
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - /mnt/misc/downloads:/downloads
      - /mnt/misc/Recyle Bin/Sonarr:/Recyle Bin
      - /mnt/media/TV:/tv
      - /mnt/media/Anime TV:/anime tv
      - /mnt/media/Ended TV:/ended tv
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #MP4 Automator
      - ${USERDIR}/docker/sma:/usr/local/sma/config
      #Backup
      - /mnt/misc/backups/arrs/Sonarr:/Backup
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "8072:8989"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - GIDLIST=44
      - TZ=${TZ}  
      - DOCKER_MODS=mdhiggins/sma-mod:latest
  radarr:
    container_name: "radarr"
    image: linuxserver/radarr
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - /mnt/misc/downloads:/downloads
      - /mnt/misc/Recyle Bin/Radarr:/Recyle Bin
      - /mnt/media/Movies:/movies
      - /mnt/media/Anime Movies:/anime movies
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # MP4 Automator
      - ${USERDIR}/docker/sma:/usr/local/sma/config
      #Backup
      - /mnt/misc/backups/arrs/Radarr:/Backup
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "8073:7878"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - GIDLIST=44
      - TZ=${TZ}  
      - DOCKER_MODS=mdhiggins/sma-mod:latest
```

**Comment by mdhiggins** [comment]
Haven't made any changes to the requests module or installation requirements, likely a transient pip problem that resulted in requests installation not working correctly/being installed incorrectly, I'd verify the installations and probably just reset the containers so the mod gets reapplied

The way docker mods work if something fails on the installation subsequent restarts will not attempt to apply the mod again, its only done on the first launch so corrupt installations will carry over

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1468

For reference, I would also try going through some of the debugging steps outlined there if a reapplication doesn't work

You can check the docker logs to make sure the mod is being reapplied (make sure its not skipping)

**Comment by mediacowboy** [comment]
Completely blowing away the containers and rebuilding them did the trick, Thank you @mdhiggins.
