### ISSUE TITLE
postRadarr script taking extremely long to convert

### ISSUE THREAD

**Issue by chrispalka** [mdhiggins/sickbeard_mp4_automator#1488]
Not really an issue, just wanted to check if you've noticed this ever.

When running manual.py for a 40gb file, it takes about 10-15 minutes. When postRadarr script runs, it's been converting overnight on a file that's just 6GB. You ever notice or come across that?

**Comment by mdhiggins** [comment]
Entirely depends on what its doing, if its remuxing without transcoding it should limited only by the speed of your drives, if your heavily encoding something it will take substantially longer and will be CPU/GPU limited
