### ISSUE TITLE
Hearing Impaired SRT import

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1494]
I don't think my hearing impaired subtitles are being imported properly. I keep seeing them as hindi subtitles because they are titled
Example:
Blade.Runner.(1982).hi.eng.srt

It should be seeing them as hearing impaired or at least as english but instead is importing them as hindi instead. Can we update SMA to see .hi.lang-code.srt as hearing impaired subtitles please?

**Comment by mdhiggins** [comment]
Looks like the correct normenclature and labeling is to use `.sdh` (Subtitles for Deaf and Hearing Impaired) which also does not conflict with language codes

I added support for this in this patch, let me know if that works for you

5f5c509df99691845437d7fc30a8160a499cfb13

**Comment by Protektor-Desura** [comment]
Can we add text instead of SDH? Use "Subtitles for Deaf and Hearing Impaired" as the label for the subtitle track please?

**Comment by mdhiggins** [comment]
You can edit the python file if you want but I believe SDH is the standard label and if other dispositions are applied you may exceed the max length with that long string

**Comment by Protektor-Desura** [comment]
Actually it appears this isn't how Plex, Emby, Kodi, Jellyfin or Bazarr are doing things.

https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/
https://forums.plex.tv/t/hi-cc-sdh-subtitles-naming-convention/627100
https://emby.media/community/index.php?/topic/90668-external-subtitles-naming-convention-for-hearing-impairedccsdh/
https://github.com/jellyfin/jellyfin/issues/4291

It supported like this:
    Movie.en.hi.srt
    Movie.en.cc.srt
    Movie.en.sdh.srt
