### ISSUE TITLE
full-path-guess = True

### ISSUE THREAD

**Issue by mafhper** [mdhiggins/sickbeard_mp4_automator#1496]
When executing the file **manual.py** with the settings determined in **autoprocess.ini** the argument '`full-path-guess = True`' is not being considered. Each file is asked to make a decision of the type `[Y/N]` .

I don't know if this was exactly the expected behavior. I think maybe not.

**Comment by mdhiggins** [comment]
Full path guess simply uses the full path of the file to make determinations (IE the folders the file is contained in) to assist in making the guess as opposed to just the file name

You might be looking for `-a, --auto`

**Comment by mafhper** [comment]
<html>
<body>

First of all, I thank you for your efforts to develop something so useful.
I was actually hoping that the `True\False` argument in the parameter described below would enable this aforementioned function.
But I haven't found a way to make this possible.



Key | Type | Default | Description
-- | -- | -- | --
full-path-guess | bool | True | Use full path when guessing file information in manual.py

</body>
</html>

**Comment by mdhiggins** [comment]
I guess I don't understand what functionality you're looking for then, using a full path guess means using the filepath as described above
