### ISSUE TITLE
Prevent Transcoding to H.264 High 10 

### ISSUE THREAD

**Issue by Miguel102** [mdhiggins/sickbeard_mp4_automator#1498]
Hello.

I'm not sure if this is the right place to ask this, but I've looked around and I can't seem to find anything. I have some files, from what I've seen mostly of Anime shows, that were transcribed with the automator to H.264 High 10, but this encoding when trying to watch on Plex on my PS5 for example is being forced to being transcoded to regular H264. This makes my player buffer a lot (my Plex Server is on a Raspberry Pi so not very powerful).

![image](https://user-images.githubusercontent.com/3679875/142952220-3ba18a92-345d-4e29-901a-3396e533ac62.png)

Is there any way to run the automator so that it doesn't transcode to High 10, force the files to regular H264? I don't mind if there's a bit of a quality decline in the files, I would prefer it to being always buffering.

Thanks and sorry if I'm asking this in the wrong place.

**Comment by mdhiggins** [comment]
You'll need to include a list of pix-fmt options that you want and exclude any of the formats that fall under high10 (yuv420p or similar for 8-bit, and yuv420p10le or similar for 10-bit)

**Comment by mdhiggins** [comment]
What extension are the input files you're passing
