### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by voidedzim** [mdhiggins/sickbeard_mp4_automator#1500]
Hi, sorry I'm slightly inexperienced but would love to try this out, how would I install this on Linux/raspi pi (buster)? I downloaded the folder on PC but am not seeing the autoProcess.ini file in the config folder, and am confused how to get this installed properly.

**Comment by mdhiggins** [comment]
Please see the general configuration section of the readme

**Comment by voidedzim** [comment]
The general config section says this:
•Download or compile FFmpeg
•Rename autoProcess.ini.sample to autoProcess.ini inside your config directory (or attempt to run the script which will generate a new config file if absent)

Not very helpful if the file is missing and no direction is given on where else to find it?

**Comment by mdhiggins** [comment]
Its in the setup folder
https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/setup/autoProcess.ini.sample

**Comment by mdhiggins** [comment]
Or like it says, it will make one for you if you run the script (like manual.py for example)
