### ISSUE TITLE
WEBM Metadata

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1502]
I would like to request that full metadata be added to WEBM if it isn't already.

http://wiki.webmproject.org/webm-metadata/global-metadata

**Comment by mdhiggins** [comment]
The fallback tagging when an MP4 isn't detected should apply to WebM, though it definitely doesn't hit all these datapoints

Would be open to a pull request but WebM really isn't a format that's widely used for media storage so not something I would think many users would get a ton of value out of and not something I have a huge interest in developing

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/resources/metadata.py

Metadata.py would be where this change would take place, specifically the non-mp4 based tagging technique starts at line 165 if you were interested in creating this for your own use case, could add in support for some of these additional tags, and can reference where the MP4 gets its more robust set of data just below
