### ISSUE TITLE
Post Processing Issue: Renaming all files in a folder every time a single Episode is downloaded

### ISSUE THREAD

**Issue by Rikumo1978** [mdhiggins/sickbeard_mp4_automator#1505]
Hello, I'm seeing some behavior I've never seen before when downloading thing using the MP4 Automator. After the conversion is finished, it hands the file back to Sonarr, which then Sonarr imports it and renames it....it's actually trying to rename every single episode in that directory instead of just the one that was downloaded. How can I stop this behavior in the future? Thank you!

**Comment by mdhiggins** [comment]
This is an intended API request. It asks the API to run a rename request after the final conversion as the file naming can/should change after conversion. It should only impact the specific show relevant to the file processed as that is the smallest unit the API request allows.

**Comment by mdhiggins** [comment]
Actually there may be an alternative API command that can do the rename but limited to only a specific file. I'll look into this

**Comment by mdhiggins** [comment]
12b0a4f5aab54c23f91b62c34be6cdcda3ec478b

See if that helps

**Comment by Rikumo1978** [comment]
This worked beautifully! Thank you so much!
