### ISSUE TITLE
guessit not found

### ISSUE THREAD

**Issue by TheBigZig** [mdhiggins/sickbeard_mp4_automator#1509]
I updated after a long while, and now I'm getting the following error when I try a manual.py call:
Traceback (most recent call last):
  File "C:\Usenet Tools\sickbeard_mp4_automator\manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'

Any help would be appreciated.

**Comment by mdhiggins** [comment]
This is a very basic python error I'm guessing you didn't google. You didn't install guessit which is one of the requirements.

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Dependencies
