### ISSUE TITLE
[Request] Universal Docker Container

### ISSUE THREAD

**Issue by shadow11001** [mdhiggins/sickbeard_mp4_automator#1510]
I don't post here very often so excuse my formatting.

I wanted to know if you could either make a universal docker container and possibly add it to unraid if you could. 

A universal docker container as in without Sonarr or Radarr and just what is needed to run the SMA script so that it could be called on when needed.

I have custom setup running that regularly polls the media folders for anything that needs converted using a script and then calls your script to convert. Its not ideal but changing everything would be a pain and I am not quite ready to do that.

Adding an Unraid template is not needed as I can do that for myself if I had the docker container or at least a dockerfile.

Thanks for the script! Love it and been using it for years.

**Comment by mdhiggins** [comment]
Like these?

https://github.com/mdhiggins/sonarr-sma
https://github.com/mdhiggins/radarr-sma

Or the docker-mod that can be applied to other containers
https://github.com/mdhiggins/sma-mod (see https://github.com/linuxserver/docker-mods)

**Comment by mdhiggins** [comment]
Also @RandomNinjaAtk has some well maintained unraid containers that apply SMA

**Comment by shadow11001** [comment]
Hmm I didn't see these. Can I build a container using just the sma-mod? It looks like I could but just making sure.

**Comment by mdhiggins** [comment]
Its meant to be applied to one of the other linuxserver containers but you could use any of them as a base with the sma-mod applied, you could use one of their base images as the foundation

**Comment by mdhiggins** [comment]
https://github.com/linuxserver/docker-baseimage-ubuntu

**Comment by shadow11001** [comment]
Ah cool! Thanks for the help!
