### ISSUE TITLE
Issues after Radarr 4 Update?

### ISSUE THREAD

**Issue by dfeng777** [mdhiggins/sickbeard_mp4_automator#1511]
Apologies in advance, I don't know where else to post this. I've been using the mp4 automator for several years yesterday started getting this error:

2022-01-04 17:54:46 - autoprocess.radarr - ERROR - [ERROR] Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
  File "/home/hd17/dfeng/sickbeard_mp4_automator/autoprocess/radarr.py", line 60, in processMovie
    rstate = r.json()
  File "/home/hd17/dfeng/.local/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Radarr just updated itself to version 4.0.0.5745. Is there a know issue with this version?

**Comment by mdhiggins** [comment]
Looks like your API is returning `None` so something on the API side of things isn't working. Looks like 4.0 is a prelease that just came out but I don't see any immediate changes to the API documented

It also looks like you're using an old version of the script since your error lines don't correspond to the current version of the script; depending on how old it might still be using the original API and not API V3. Try updating the script and double check your radarr settings and API key which might have changed when updating to the prelease and see if that helps

**Comment by mdhiggins** [comment]
If you make those changes and you're still getting an error please turn on DEBUG logging and post the full error logs and I'll see if I can figure out if they made minor changes or changed something

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by dfeng777** [comment]
Thank you for the quick reply. I updated to the latest and was able to get one grab successfully processed by Radarr. But subsequent grabs are getting the errors below. Is this an ffmpeg version issue or perhaps an autoProcess.ini setting that I ported from the previous version? The same errors happen with the Deluge post-process script.

```
2022-01-07 04:15:41 - NZBGetPostProcess - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home//sickbeard_mp4_automator/resources/mediaprocessor.py", line 1760, in convert
    for timecode, debug in conv:
  File "/home//sickbeard_mp4_automator/converter/__init__.py", line 334, in convert
    postopts=postopts):
  File "/home//sickbeard_mp4_automator/converter/ffmpeg.py", line 729, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2022-01-07 04:15:41 - NZBGetPostProcess - ERROR - /usr/bin/ffmpeg -fix_sub_duration -i /home/nzbget/download/Radarr/SampleFileName.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k 
-metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -filter:a:0 pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE -metadata:s:a:0 title
=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired
-captions -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 BPS=1536000 -metadata:s:a:1 BPS-eng=1536000 -metadata:s:a:1 title=5.1 Channel -metad
ata:s:a:1 handler_name=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions
 -strict experimental -c:s:0 srt -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyr
ics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 srt -map 0:3 -metadata:s:s:1 title=Hearing Impaired -metadata:s:s:1 handler_name=Hearing Impaired -metadat
a:s:s:1 language=eng -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_too
l=SMA -y /home//nzbget/download/Radarr/SampleFileName.mp4
2022-01-07 04:15:41 - NZBGetPostProcess - ERROR - ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disabl
e-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enab
le-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enab
le-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libs
sh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-
libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0
r --enable-libopencv --enable-libx264 --enable-shared
```

```
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (eac3 (native) -> aac (native))
  Stream #0:2 -> #0:3 (subrip (srt) -> subrip (srt))
  Stream #0:3 -> #0:4 (subrip (srt) -> subrip (srt))
Press [q] to stop, [?] for help
[mp4 @ 0x557b751801e0] Could not find tag for codec subrip in stream #3, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 -- 
[aac @ 0x557b751a5e60] Qavg: -nan
[aac @ 0x557b751a5e60] 1 frames left in the queue on closing
[aac @ 0x557b75182820] Qavg: -nan
Conversion failed!
```

**Comment by mdhiggins** [comment]
`codec subrip in stream #3, codec not currently supported in container`

Subrip isn't a valid subtitle codec, use `mov_text` if you're using an mp4 container, `srt` if you're using MKV container for your output file
