### ISSUE TITLE
h264 to h265

### ISSUE THREAD

**Issue by kennfoxx** [mdhiggins/sickbeard_mp4_automator#1513]
I have a library with several videos in h264 and I want to leave everyone in h265 I'm trying to configure the autoprocess, but I'm getting the following error:
> Manual processor started.
Python 64-bit 3.6.9 (default, Dec  8 2021, 21:08:43)
[GCC 8.4.0].
Guessit version: 3.4.3.
/usr/bin/python3
Loading config file /scripts/mp4_automator-plex/config/autoProcess.ini.
Traceback (most recent call last):
  File "/scripts/mp4_automator-plex/manual.py", line 425, in <module>
    main()
  File "/scripts/mp4_automator-plex/manual.py", line 363, in main
    settings = ReadSettings(logger=log)
  File "/scripts/mp4_automator-plex/resources/readsettings.py", line 598, in __init__
    config.read(configFile)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/scripts/mp4_automator-plex/config/autoProcess.ini', line: 1
'[Converter]\n'

autoprocess settings
>[Converter]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = 
hwaccels = 
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi, h265_qsv, hevc_qsv
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = False
sort-streams = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

>[Video]
codec = h265, x265, hevc
max-bitrate = 7000
bitrate-ratio = 
crf = 21
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt =
filter = 
force-filter = False

**Comment by mdhiggins** [comment]
Did you delete your other section headers? Its a section header error with python's configparser

**Comment by kennfoxx** [comment]
> Did you delete your other section headers? Its a section header error with python's configparser

No. I even run another instance with different settings and the process starts normally

**Comment by mdhiggins** [comment]
Your config file is corrupted somehow, did you use a weird text editor to make your changes? If you use a word processor and not a text editor is might inject some nonsense characters in there and break python, I would just delete your config file and start over if you can't figure out where the issue is but this is a corrupt config file in some fashion or another

**Comment by mdhiggins** [comment]
And by section headers I mean in your config file, you only posted 2 sections I assume that was just an excerpt from your config and the rest of the sections are still there but if you deleted them and only have a [Converter] and [Video] section that will definitely break things

**Comment by kennfoxx** [comment]
Right. I will evaluate all files and come back to say the result. Thanks.

**Comment by kennfoxx** [comment]
You were absolutely right, it was the text editor I used. The process now works perfectly.
