### ISSUE TITLE
Control-C in manual.py continues directory loop

### ISSUE THREAD

**Issue by stevemk14ebr** [mdhiggins/sickbeard_mp4_automator#1518]
I've tried to track this down but can't quite figure it out. When running manual.py on a directory control-c isn't properly handled and the processing of the current file with ffmpeg ends, but then the next file starts processing. In a large directory the only way to kill the script is to force close the console. The exception is first raised here:

ffmpeg.py - polling loop in convert(), typically around `stderr.read(10)`

I lose track of what happens with all the async generators after this point. I'd expect the KeyboardInterrupt to be raised back high enough that the loop `for filepath in files:` in manual.py - walkDir is exited gracefully.

**Comment by mdhiggins** [comment]
Updated on https://github.com/mdhiggins/sickbeard_mp4_automator/tree/pr/1516 see if that fixes it

**Comment by stevemk14ebr** [comment]
This doesn't resolve the issue, the exception gets lost before it ever makes it back to manual.py

**Comment by mdhiggins** [comment]
Not ready to merge and missing other changes including readme adjustments and all the commit history is lost so no, I'll probably just merge the pr/1516 branch into master when its ready but I'll merge it all after this issue is sorted

Can you send the manual.py console output and indicate where you're trying to send the interrupt and its failing?

**Comment by stevemk14ebr** [comment]
I made adjustments to your pr/1516, please review my changes if that's what you end up merging, I was hoping to be a contributor but if you merge that instead thats fine as long as the feature ends up in this.

The error is during the actual ffmpeg convert() during the subprocess polling:
```
Traceback (most recent call last):
  File "C:\Users\steve\source\repos\sickbeard_mp4_automator\resources\mediaprocessor.py", line 296, in isValidSource
    info = self.converter.probe(inputfile)
  File "C:\Users\steve\source\repos\sickbeard_mp4_automator\converter\__init__.py", line 345, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "C:\Users\steve\source\repos\sickbeard_mp4_automator\converter\ffmpeg.py", line 580, in probe
    stdout_data = self._get_stdout([
  File "C:\Users\steve\source\repos\sickbeard_mp4_automator\converter\ffmpeg.py", line 533, in _get_stdout
    stdout_data, stderr = p.communicate()
  File "C:\Program Files\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Program Files\Python39\lib\subprocess.py", line 1508, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "C:\Program Files\Python39\lib\threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "C:\Program Files\Python39\lib\threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Pymediainfo exception.
```

there may be other locations that fail to handle the interrupt properly, but this is by far the most common area for me as processing is 90% of the time per file.

**Comment by mdhiggins** [comment]
Alright I went through the whole project and looked for blind exceptions on loops of long processes and raised the KeyboardInterrupt exception up, I also narrowed lots of exceptions to specific types where applicable

See if that last change helps and I'll merge

**Comment by stevemk14ebr** [comment]
The control-c works now thanks! The archive list however is still incorrect, please see my changes. .add is not a valid method, and the arguments aren't passed to processFile correctly. Please consider defaulting the -pa argument to a filename too so users can just use -pa to have an archive created automatically without a filename.

**Comment by mdhiggins** [comment]
Looks like some of the exception changes were breaking some core functionality with the encoder, had to revert some of them but the keyboard interrupt raises weren't changed so shouldn't notice any major issues with that but please test

Fixed .add to .append
Fixed the missing parameters being passed in walkDir call to processFile
Added indents to the final json file so its more readable
Made -pa parameter optional with default value of 'archive.json'

Should be good for a final test and merge as long as you don't identify any problems

**Comment by mdhiggins** [comment]
Also one final question, shouldn't we be adding the output files to this list as well? If the goal is to prevent duplicate stream creation etc isn't storing the inputfile which is often deleted (and assuming you're using different input/output extensions not even named the same) missing a large portion of files? Should probably just add all output files to the archive at the end of a job and if the output file is the same as input it wouldn't matter as it would still be added

**Comment by stevemk14ebr** [comment]
I've confirmed the script works now! And yes, we probably do want the output file as well, I forgot about that.

**Comment by mdhiggins** [comment]
Alright made some tweaks to have it look at the final output report, include all output files (this should account for things like copy-to/move-to options) and also include the inputfile if it wasn't deleted and to use the final inputfile name (in case it was renamed during the job to say something like *.original)

Let me know if that still works for your workflow and it should be ready to merge

**Comment by stevemk14ebr** [comment]
this works great, I think it's ready!

**Comment by mdhiggins** [comment]
Alright merged into master, closing this out and the PR, thanks for testing and the PR
