### ISSUE TITLE
Error converting file, FFMPEG error.

### ISSUE THREAD

**Issue by chrispalka** [mdhiggins/sickbeard_mp4_automator#1519]
Hello there, this app has been working flawlessly. I do encounter the below error from time to time, I think specifically related to some HDR mkv files but not quite sure why. Below is the log, and below that is my autoprocess.ini. 

Any help is appreciated as always! Thank you. 

Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1758, in convert
    for timecode, debug in conv:
  File "/usr/local/sma/converter/__init__.py", line 330, in convert
    for timecode, debug in self.ffmpeg.convert(outfile,
  File "/usr/local/sma/converter/ffmpeg.py", line 728, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
/usr/local/bin/ffmpeg -fix_sub_duration -i ./The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mkv -vcodec libx264 -map 0:0 -vb 16916k -metadata:s:v BPS=16916000 -metadata:s:v BPS-eng=16916000 -metadata:s:v title=4K -metadata:s:v handler_name=4K -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -filter:a:0 pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 768k -metadata:s:a:1 BPS=768000 -metadata:s:a:1 BPS-eng=768000 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 handler_name=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 0:3 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=spa -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /data/media/movies/The Matrix Resurrections (2021)/The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mp4
ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from './The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-12-22T08:07:17.000000Z
  Duration: 02:27:54.88, start: 0.000000, bitrate: 18575 kb/s
  Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(pc), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 17804863
      DURATION        : 02:27:54.866000000
      NUMBER_OF_FRAMES: 212784
      NUMBER_OF_BYTES : 19751972061
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      BPS             : 768000
      DURATION        : 02:27:54.880000000
      NUMBER_OF_FRAMES: 277340
      NUMBER_OF_BYTES : 851988480
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English [CC]
      BPS             : 51
      DURATION        : 02:27:41.060000000
      NUMBER_OF_FRAMES: 2185
      NUMBER_OF_BYTES : 57063
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(spa): Subtitle: subrip
    Metadata:
      title           : Latin American Spanish [CC]
      BPS             : 52
      DURATION        : 02:27:16.786000000
      NUMBER_OF_FRAMES: 2129
      NUMBER_OF_BYTES : 58447
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (eac3 (native) -> ac3 (native))
  Stream #0:2 -> #0:3 (subrip (srt) -> mov_text (native))
  Stream #0:3 -> #0:4 (subrip (srt) -> mov_text (native))
Press [q] to stop, [?] for help
[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
[libx264 @ 0x41e07e0] using SAR=1/1
[libx264 @ 0x41e07e0] using cpu capabilities: ARMv6 NEON
[libx264 @ 0x41e07e0] profile High 10, level 5.1, 4:2:0, 10-bit
[libx264 @ 0x41e07e0] 264 - core 164 r3075 66a5bc1 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=16916 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=81 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/data/media/movies/The Matrix Resurrections (2021)/The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mp4':
  Metadata:
    encoding_tool   : SMA
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p10le(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 16916 kb/s, 23.98 fps, 24k tbn (default)
    Metadata:
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:27:54.866000000
      NUMBER_OF_FRAMES: 212784
      NUMBER_OF_BYTES : 19751972061
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      BPS             : 16916000
      BPS-eng         : 16916000
      title           : 4K
      handler_name    : 4K
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/16916000 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      handler_name    : Stereo
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:27:54.880000000
      NUMBER_OF_FRAMES: 277340
      NUMBER_OF_BYTES : 851988480
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      BPS             : 256000
      BPS-eng         : 256000
      title           : Stereo
      encoder         : Lavc58.134.100 aac
  Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1, fltp, 640 kb/s (default)
    Metadata:
      handler_name    : 5.1 Channel
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:27:54.880000000
      NUMBER_OF_FRAMES: 277340
      NUMBER_OF_BYTES : 851988480
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      BPS             : 768000
      BPS-eng         : 768000
      title           : 5.1 Channel
      encoder         : Lavc58.134.100 ac3
  Stream #0:3(eng): Subtitle: mov_text (tx3g / 0x67337874)
    Metadata:
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 51
      DURATION        : 02:27:41.060000000
      NUMBER_OF_FRAMES: 2185
      NUMBER_OF_BYTES : 57063
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      encoder         : Lavc58.134.100 mov_text
  Stream #0:4(spa): Subtitle: mov_text (tx3g / 0x67337874)
    Metadata:
      _STATISTICS_WRITING_DATE_UTC: 2021-12-22 08:07:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 52
      DURATION        : 02:27:16.786000000
      NUMBER_OF_FRAMES: 2129
      NUMBER_OF_BYTES : 58447
      _STATISTICS_WRITING_APP: mkvmerge v63.0.0 ('Everything') 64-bit
      encoder         : Lavc58.134.100 mov_text
[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.44 bitra[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
frame=    3 fps=2.6 q=0.0 size=       0kB time=00:00:00.44 bitra[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
frame=    5 fps=2.6 q=0.0 size=       0kB time=00:00:00.47 bitra[hevc @ 0x41fa6d0] Skipping NAL unit 62
[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
frame=    8 fps=3.3 q=0.0 size=       0kB time=00:00:00.69 bitra[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
frame=   10 fps=3.2 q=0.0 size=       0kB time=00:00:00.73 bitra[hevc @ 0x41fa6d0] Skipping NAL unit 62
[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
frame=   13 fps=3.6 q=0.0 size=       0kB time=00:00:00.95 bitra[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
frame=   16 fps=3.7 q=0.0 size=       0kB time=00:00:00.95 bitra[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
frame=   18 fps=3.5 q=0.0 size=       0kB time=00:00:00.98 bitra[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
frame=   21 fps=3.7 q=0.0 size=       0kB time=00:00:01.21 bitra[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
frame=   23 fps=3.6 q=0.0 size=       0kB time=00:00:01.24 bitra[hevc @ 0x4269480] Skipping NAL unit 62
[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
frame=   26 fps=3.8 q=0.0 size=       0kB time=00:00:01.46 bitra[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
[hevc @ 0x4269480] Skipping NAL unit 62
frame=   29 fps=3.9 q=0.0 size=       0kB time=00:00:01.46 bitra[hevc @ 0x41fe610] Skipping NAL unit 62
[hevc @ 0x41fa6d0] Skipping NAL unit 62
frame=   31 fps=3.8 q=0.0 size=       0kB time=00:00:01.49 bitra[hevc @ 0x424e280] Skipping NAL unit 62
[hevc @ 0x425bbc0] Skipping NAL unit 62
x264 [error]: malloc of size 48301728 failed
Video encoding failed
[hevc @ 0x4269480] Skipping NAL unit 62
[libx264 @ 0x41e07e0] final ratefactor: 13.03
[aac @ 0x4206c10] Qavg: 65536.000
[aac @ 0x4206c10] 2 frames left in the queue on closing
Conversion failed!

/data/media/movies/The Matrix Resurrections (2021)/The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mp4 deleted.
There was an error processing file ./The.Matrix.4.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX.mkv, no output data received

[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels =
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory =
output-format = mp4
output-extension = mp4
temp-extension =
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
sort-streams = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = True
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts =
postopts =
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition =
strip-metadata = False
keep-titles = False

[Video]
codec = h264, x264
max-bitrate = 0
bitrate-ratio =
crf = -1
crf-profiles =
preset =
codec-parameters =
dynamic-parameters = False
max-width = 0
profile =
max-level = 0.0
pix-fmt =
filter =
force-filter = False

[HDR]
codec = hevcqsv
pix-fmt =
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset =
codec-parameters =
filter =
force-filter = False
profile =

[Audio]
codec = ac3
languages =
default-language =
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter =
force-filter = False
sample-rates =
sample-format =
copy-original = False
copy-original-before = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions =
unique-dispositions = False
stream-codec-combinations =

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter =
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based =
languages =
default-language =
first-stream-of-language = False
encoding =
burn-subtitles = False
burn-dispositions =
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions =
unique-dispositions = False
attachment-codec =

[Subtitle.Subliminal]
download-subs = False
download-hearing-impaired-subs = False
providers =

[Subtitle.Subliminal.Auth]
opensubtitles =
tvsubtitles =

[Sonarr]
host = localhost
port = 8989
apikey =
ssl = False
webroot =
force-rename = False
rescan = True
block-reprocess = False

[Radarr]
host = 127.0.0.1
port = 7878
apikey = 3cef6c2e98d344fbb4b87b07efd10302
ssl = False
webroot =
force-rename = False
rescan = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey =
webroot =
username =
password =

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey =
webroot =
username =
password =

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory =
path-mapping =

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username =
password =
output-directory =
remove = False
path-mapping =

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before =
action-after =
host = localhost
port = 8080
ssl = False
username =
password =
output-directory =
path-mapping =

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before =
action-after =
host = localhost
ssl = False
port = 8080
username =
password =
output-directory =
path-mapping =

[Plex]
host = 192.168.1.26
port = 32400
refresh = False
token = 2kGHtad7ysqneUsxxTC

**Comment by mdhiggins** [comment]
Are you using a 32 bit version of FFMPEG?

https://stackoverflow.com/questions/22553483/upper-limit-on-ffmpeg-libx264-frame-sizes

This is an FFMPEG problem and a limitation of h264 when feeding in a 4K hdr source

I would also advise using HEVC for this kind of content or using a different input source

**Comment by chrispalka** [comment]
Not sure what architecture I'm using, is ffmpeg baked into your docker container? When you say use hevc, do you mean for HDR content, use hevc code instead of hevcqsv? If so, I've also tried that 🥲

**Comment by mdhiggins** [comment]
I meant more you need to use hevc instead of h264, not necessarily hevcqsv which is a hardware accelerated version which requires potentially lots of additional work to set up especially if you're not experienced with ffmpeg and hardware acceleration

What kind of hardware you running this on? If its a non-64 bit arm device then that would answer the question otherwise anything from the official docker containers should be 64 bit, only armhf is 32

All in all though this is an ffmpeg problem not really a problem with the script but I can try and direct you to a solution if you give me some more info

**Comment by mdhiggins** [comment]
Also just looking at your logs your hdr codec isn't being used so the source file isn't meeting your HDR definition (which is defined by the 3 parameters you have set

```
space = bt2020nc
transfer = smpte2084
primaries = bt2020
```

You should also add `hevc` after `hevcqsv` (assuming you're intentionally using qsv) otherwise you'll never get remuxing of hevc content

```
[HDR]
codec = hevcqsv, hevc
```

**Comment by chrispalka** [comment]
I'm actually not familiar at all with ffmpeg, I was just troubleshooting. In regards to the hdr codex not being used, do you recommend setting those params to anything specific?

**Comment by mdhiggins** [comment]
It depends on what you want to be considered "HDR" and if you want separate options applied to HDR content. There are lots of space/transfer/primaries and only some of them are considered HDR and everyone has different preferences which is why you can specify. I'm guessing the file you provided for the sample isn't HDR or uses some other profile. If you're going to treat everything the same then just leave the HDR codec blank and it will get the same options as all other files anyway.

If you look earlier in the logs it should tell you what space/transfer/primaries were present on your input file

More importantly if you could answer the info from my post above that it might get to the bottom of your FFMPEG error

**Comment by chrispalka** [comment]
I'm using a raspberry pi 4 model.b Rev 1.2. Has 4gb ram, and I think it's 64 bit arm v8. Not sure what version of ffmpeg I'm using, I pasted the version info above but not certain if that tells us anything.

**Comment by chrispalka** [comment]
In the end, my goal is to convert eveything to mp4 and maintain its quality. It works for most files, except the one from the logs above. I usually notice it on extremely large file sizes which may be the problem as my raspberry pi is only 4gb and I see now earlier in the logs files it shows memory alloc error.

**Comment by mdhiggins** [comment]
It doesn't unfortunately, and while the pi supports 64 bit you may not have a 64 bit operating system installed

You can probably run `uname -u` from the command line on your pi to get some more information

Raspberry pi definitely doesn't support QSV though, that's for intel processors only so don't ever use that

Biggest issues here though is that you're trying to convert hevc to h264, just add hevc to your codec list and it shouldn't convert the video stream.

`codec = h264, x264, hevc`

**Comment by chrispalka** [comment]
Ok I will give that a try. I believe the OS is 32 bit as they haven't released a 64bit OS that's stable. Thanks for all of your help!

**Comment by mdhiggins** [comment]
I've got 64 bit ubuntu server on mine and its rock solid stable, but at least we know the source of the error
