### ISSUE TITLE
Add a VBR option for audio codecs that support it

### ISSUE THREAD

**Issue by VXsz** [mdhiggins/sickbeard_mp4_automator#1520]
I saw a pull request that is like 3 years old, not sure why it still hasn't been merged, for now I changed a few lines to make it use VBR whenever it sees libfdk_aac:
avcodecs.py:161
```py
            if self.ffmpeg_codec_name == 'libfdk_aac':
                optlist.extend(['-vbr', '5'])
            else:
                optlist.extend(['-b:a:' + stream, str(br) + 'k'])
```

it took some effort to find it as I haven't really dug into this project much, but anyways adding this feature is a must IMO

**Comment by mdhiggins** [comment]
ef4bdbd7142bbbe113b0e17aa1d4816e65ea5cf5

Should close it out, adds `variable-bitrate` and `profile` options to the Audio and Universal Audio sections

**Comment by VXsz** [comment]
that was quick, thanks!

**Comment by mdhiggins** [comment]
Let me know if it's working for you then we can close this out

**Comment by VXsz** [comment]
works nicely! I recommend adding the new info to the wiki

**Comment by VXsz** [comment]
Actually, it might not be doing correct ffmpeg command, specifically:
```
libfdk_aac -map 0:1 -ac:a:0 6 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 "title=5.1 Channel" -metadata:s:a:0 "handler_name=5.1 Channel" -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -vbr:a:0 5`
```
it's doing CBR & VBR, not sure what would be the result, but it would be better if one is removed

**Comment by mdhiggins** [comment]
b0b6a782cc45bf8a4ccfc3e8b099c0fb8e1d6e30

That should fix it, needed to delete the bitrate data earlier in the process if VBR data was found
Also found some small bugs that were fixed for when VBR parameters were out of range

If that works let me know and I'll close this out and update the wiki accordingly

**Comment by VXsz** [comment]
Everything looks perfect so far, thank you again
