### ISSUE TITLE
extract enforced subtitles  

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1524]
Hi,

I was wondering if there is a way to detect, extract and label the enforced subtitles?
Currently I see that it can extract all the subtitles but it doesnt know which one is enforced.

Thanks.

**Comment by mdhiggins** [comment]
Enforced really isn't a thing and is not a disposition, `forced` is maybe what you're referring to which the script fully supports

```
    def getSubOutputFile(self, inputfile, language, disposition, extension):
        disposition = self.dispoStringToDict(disposition)
        dispo = ""
        for k in disposition:
            if disposition[k] and k in self.settings.filename_dispositions:
                dispo += "." + k
        input_dir, filename, input_extension = self.parseFile(inputfile)
        output_dir = self.settings.output_dir or input_dir
        outputfile = os.path.join(output_dir, filename + "." + language + dispo + "." + extension)

        i = 2
        while os.path.isfile(outputfile):
            self.log.debug("%s exists, appending %s to filename." % (outputfile, i))
            outputfile = os.path.join(output_dir, filename + "." + language + dispo + "." + str(i) + "." + extension)
            i += 1
        return outputfile
```

Any disposition can be included with the filename during extraction. You do need to specify which dispositions you want included in your filenames using the `filename-dispositions` option however which may be what's missing if you're not seeing what you want. Tough to say with no log files, as it also could be that the source file lacks disposition data
