### ISSUE TITLE
Issue converting anime

### ISSUE THREAD

**Issue by reddragonguy** [mdhiggins/sickbeard_mp4_automator#1525]
Hi,

I get this error in the log for a recent conversion.
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/7936030/sma.log)

any idea what's going on.  

Here's also my INI file:

[autoprocess.ini (2).txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/7936057/autoprocess.ini.2.txt)

**Comment by mdhiggins** [comment]
[mp4 @ 0x60fafc0] Could not find tag for codec subrip in stream #2, codec not currently supported in container

srt isn't a valid codec for MP4 containers. Use mov_text

Similarly mp4 doesn't support image based subtitle codecs so you'll need to turn off embedding those or switch to MKV

**Comment by reddragonguy** [comment]
thank you for the guidance.  I must admit, i'm fairly ignorant of the settings and copied them from another post when i transitioned from mp4 to mkv a couple of months ago.  I've decided to transition back and just changed the output format and extension.
