### ISSUE TITLE
Metadata issue

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1531]
In the metadata section of the docs it is written:
<html>
<body>

relocate-moov | bool | True | Relocate MOOV atom using QTFastStart for MP4 files to optimize for streaming. For MKV files the FFMPEG parameter reserve_index_space will be applied to achieve similar streaming optimization
-- | -- | -- | --

</body>
</html>

I am using MKV files and if I set this to 'True' then the metadata tagging fails. I have to set this to 'False' in order for it to properly process files stored/put-in in MKV containers.

output-format = mkv
output-extension = mkv

relocate-moov = False

Do the docs need to be changed or is something else going on here?

**Comment by mdhiggins** [comment]
What failure are you seeing?

**Comment by Protektor-Desura** [comment]
When it gets to the metadata it errors out and leaves behind a .tag file. I haven't been able to figure out where the logs are for SMA or how to configure them or whatever so I can see exactly what the error is. I just know that .tag files of the videos gets left behind and the file is never completely converted.

**Comment by mdhiggins** [comment]
The logs are in the script config folder with autoProcess.ini named sma.log

**Comment by Protektor-Desura** [comment]
Here is my log file
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/8026884/sma.log)
.

**Comment by mdhiggins** [comment]
Hm looks like you're getting a false positive KeyError exception not sure why that would be but it can be accounted for so the fallback tagging triggers like its supposed to, must be something to do with the new `reserve_index_space` feature

See here for reference https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1521

Not able to reproduce this on in my testing but I'm also going to move the relocate_moov mkv equivalent to the tagging pass as opposed to the initial pass which is more consistent with how the MP4 files behave and should fix this

**Comment by mdhiggins** [comment]
Alright update is live

376274f614301068e165eab8b183937552852af4

This includes adjustments for the radarr and sonarr renaming issue along with this issue, please test and close if resolved

**Comment by mdhiggins** [comment]
530967a04fd167940e58edd74882702d84f070cf

For the 50 multiplier, please use that commit for your testing

**Comment by Protektor-Desura** [comment]
Fixed it. Thanks.
