### ISSUE TITLE
Config Docs Typo/Error

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1532]
In your config page of examples/doc
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/autoProcess-Settings

 You have this:
Subtitle.Subliminal
Optional section to specify account information for subliminal subtitle providers. Keys are dynamic and should be the subtitle provider name as defined by subliminal and your download-providers options

It should be:
Subtitle.Subliminal.Auth
Optional section to specify account information for subliminal subtitle providers. Keys are dynamic and should be the subtitle provider name as defined by subliminal and your download-providers options

Based on reading your code. Also reading the code of Subliminal you should list the providers as:

[Subtitle.Subliminal.Auth]
addic7ed =
argenteam =
legendastv =
napiprojekt =
opensubtitles =
podnapisi =
shooter =
thesubdb =
tvsubtitles =

https://github.com/Diaoul/subliminal
https://subliminal.readthedocs.io/en/latest/user/how_it_works.html#providers
https://github.com/Diaoul/subliminal/blob/master/docs/api/providers.rst
https://github.com/Diaoul/subliminal/blob/master/subliminal/extensions.py

**Comment by mdhiggins** [comment]
Providers are optional and can/may change and in fact have changed so it's an open-ended section but you are correct the header is missing the .Auth suffix, fixed and I'll include a reference to the providers in the wiki

Thanks for catching that
