### ISSUE TITLE
Manually start jobs from Sonarr instead of automatically, in bulk

### ISSUE THREAD

**Issue by VXsz** [mdhiggins/sickbeard_mp4_automator#1534]
**Is your feature request related to a problem? Please describe.**
My current workflow is downloading thru Sonarr & then importing manual subs through Bazarr, I just wish I could control when a sickbeard's mp4 automator is started for the new episodes since it processes them automatically after downloading, so I can't "prepare" the media for processing

**Describe the solution you'd like**
I'm not sure if it's possible, but if it is perhaps a button on sonarr's webui or like a command of some sort, or like when I add subs through bazarr it automatically triggers it (would be cool), basically the same of the current automatic flow but with a manual "approval" button, even better if it's per episode

**Describe alternatives you've considered**
I have considered dumping the media into a folder & then run a bulk script to process all of them... but it would be much better if there was a more integrated option that only starts jobs when I finish working on my media (so sonarr's trigger waits)

**Additional context**
None

**Comment by mdhiggins** [comment]
I have no control over this request, you would be better served putting in a feature request for Bazarr to run custom scripts or to have Sonarr/Radarr add a rerun/re-postprocess option/button but I can't change Sonarr/Radarr's webui or the internal workflow of these applications

You could try using the subliminal integration that's included with the script to get your subtitles before processing and circumvent Bazarr or write a scheduled task of some kind that looks through your media folder and processes based on certain conditions

You also just disable completed download handling in Sonarr/Radarr so they don't get automatically imported and then use the 'manual import' button whenever those files are 'ready' to be brought in which will then delay the post processing

**Comment by VXsz** [comment]
the thing is I import the subtitles manually because %90 of the time bad subs get picked up, but I like your idea, I may just do that and try to schedule tasks (and then simply readjust them after finishing), if that doesn't work I'll just make a batch bash script to process it after finishing

**Comment by mdhiggins** [comment]
It probably wouldn't be too difficult to write a simple scheduled script to just search through your media directories and if a subtitle file is found to find the associated media file and run it through manual.py to merge the sub and media file into a single file (which I assume is what you're aiming for here)
