### ISSUE TITLE
I broke something :-(

### ISSUE THREAD

**Issue by albanyeye** [mdhiggins/sickbeard_mp4_automator#1536]
Hi
Been using the script for years and decided I would give it a try to convert some media to H.265 using Nvidia card in a docker environment.
All the media i have gives the following error.
Kindly have a look. Thanks

"Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (eac3 (native) -> eac3 (native))
  Stream #0:2 -> #0:3 (subrip (srt) -> mov_text (native))
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
[aac @ 0x55b31d34f140] Qavg: 59828.000
[aac @ 0x55b31d34f140] 2 frames left in the queue on closing
Conversion failed!"
===============================================
Here are my .ini settings

[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = cuda, nvenc, cuvid, ,hevc_cuvid,cuda,vaapi, dxva2, qsv, d3d11va
hwaccel-decoders = h265_nvenc,hevc_cuvid,h265_cuvid,hevc_nvenc,h264_cuda, hevc_cuda, h264_cuvid, hevc_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, vp8_cuvid, vp9_cuvid, hevc_qsv, h264_qsv
hwdevices = cuda
hwaccel-output-format = cuda:cuda
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = True
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = hevc_nvenc, hevc
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 480
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False

**Comment by albanyeye** [comment]
after testing on command line , the command below produces the desired results.
How do I making the changes on autoprocess.ini to make these  replicate this?

`ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i 'The Goldbergs (2013) - S09E06 - The Hunt for the Great Albino Pumpkin WEBDL-1080p.mp4' -c:v nvenc_hevc -vtag hvc1 -c:a copy 'The Goldbergs (2013) - S09E06 - The Hunt for the Great Albino Pumpkin WEBDL-1080p-h265.mp4'`

**Comment by mdhiggins** [comment]
Can you include the commands that is generated with your current Settings? Full debug logs would be ideal

**Comment by mdhiggins** [comment]
Also the error you're getting is due the scaler being applied because of your max width setting so your test command avoids this entirely so not really an apples to apples test
