### ISSUE TITLE
Qbittorrent settings

### ISSUE THREAD

**Issue by hpacleb** [mdhiggins/sickbeard_mp4_automator#1540]
In the settings for qbittorrent, two of them are labeled username and password. What are these for? I'm running qbittorrent-nox on my pi so I'm wondering if it's supposed to be for user credentials of the pi? I have the script setup for qbittorrent but haven't tested it yet.

**Comment by mdhiggins** [comment]
```
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
port = 8080
ssl = False
host = localhost
username = 
password = 
output-directory = 
path-mapping = 
```

There's only one entry in the settings for username and password and these should reflect the username and password for your qBittorrent WebUI
