### ISSUE TITLE
Remux to mkv instead of mp4 when a truehd track exist

### ISSUE THREAD

**Issue by VXsz** [mdhiggins/sickbeard_mp4_automator#1541]
**Is your feature request related to a problem? Please describe.**
Not really, but it would be cool to have it and save so much time

**Describe the solution you'd like**
An alternate remux option, so when the script detects a TrueHD track (or any other incompatible codec for the requested container) it will switch to mkv instead of mp4 to keep the track, and I see that basically TrueHD is almost the only exception to mp4 and has an entry in the config, so I think adding this option might not be hard (like, if-truehd-exist: mkv)

**Describe alternatives you've considered**
There aren't many option to me so this is my best shot, perhaps a pre-process script to switch between 2 configs depending if a truehd track exists but I haven't tried that and I'm not sure if it's possible

**Additional context**
I really would like to keep lossless tracks, but mp4 doesn't support some codecs which is a bummer and a few of my media had truehd removed because of it

**Comment by mdhiggins** [comment]
You have 2 options here

Easiest is that mp4 actually supports trueHD now, as long as you're on a newer FFMPEG build (I want to say from 4.4 onward) you can use truehd with mp4, just remove mp4 from the `ignore-truehd` option and get a new build of FFMPEG

Alternatively, the custom validation method can be used to intercept and adjust the settings object before processing if you wanted to make custom conditional changes like this

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions

Here is a sample of changing the output format and extension to mkv if any truehd tracks are present to get you started

```py
def validation(mp, info, path):
    mp.log.info("Initiating custom validation method.")
    if any(a.codec == "truehd" for a in info.audio):
        mp.log.info("Found a TrueHD audio track, switching format to MKV.")
        mp.settings.output_format = "mkv"
        mp.settings.output_extension = "mkv"
    return True
```

**Comment by VXsz** [comment]
Oh, that's amazing I didn't realize that, I already have an ffmpeg 5.0 custom build so I think do it immediately, thank you for the info, seems like the info on forums and such is kinda outdated
