### ISSUE TITLE
When getting artwork, if episode or season artwork is missing, fall back to showdata poster

### ISSUE THREAD

**Issue by tsimmons** [mdhiggins/sickbeard_mp4_automator#1549]
**Is your feature request related to a problem? Please describe.**
A small issue but frequently when I tag files, no artwork is assigned because the show is new; The Movie DB has no specific artwork assigned to the episode or season, but usually there is artwork assigned to the show itself.

**Describe the solution you'd like**
It would be nice (if no episode or season image exists) if tagging would fall back to using the showdata poster if one is available.

I have implemented this myself by adding three lines to `resources/metadata.py` 

```
diff --git a/resources/metadata.py b/resources/metadata.py
index 8614afb..3cfc77e 100644
--- a/resources/metadata.py
+++ b/resources/metadata.py
@@ -376,6 +376,9 @@ class Metadata:
                 else:
                     poster_path = self.seasondata.get('poster_path')

+            if not poster_path:
+                poster_path = self.showdata.get('poster_path')
+
             if not poster_path:
                 self.log.warning("No artwork found for media file.")
                 return None
```

**Comment by mdhiggins** [comment]
Nice suggestion

Added

c72196a6bbef693f45ded80d8cccddbdb2479fc2
