### ISSUE TITLE
HEVC codec not found

### ISSUE THREAD

**Issue by tjfriese** [mdhiggins/sickbeard_mp4_automator#1550]
I've updated to the latest version (downloaded today) and am getting a SystemExit:  1 error in SabNZBD due to a missing codec.

Here's the log file: https://pastebin.com/4sqebDrY

**Comment by mdhiggins** [comment]
`--disable-decoder=hevc` is in your FFMPEG build options

Your FFMPEG executable doesn't support hevc and your video source is using hevc, this is an FFmpeg problem you need a build that supports it if you want to use files that use that codec
