### ISSUE TITLE
How to get couchpotato version working in docker build

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#1552]
Can someone please guide me on how to get Couchpotato version back. I know it's not being developed but it works for what I need and Radarr doesn't support flat a movie folder so not something I want to move to.

I have a Docker project that builds this project into it.
this is my Dockerfile
https://github.com/rrd911/couchpotato_ffmpeg_pipadditions/blob/master/Dockerfile

Any guidance would be appreciated.

**Comment by mdhiggins** [comment]
Your only option is to checkout an older version of the script that still had couchpotato support

CP was deprecated on 8/2/21

Last commit sha is b3056f871a36bc07deba5c1f45bb9ec873b0220f

Add

`git -C  /app/sickbeard_mp4_automator checkout b3056f871a36bc07deba5c1f45bb9ec873b0220f`

after your `git clone` line

https://coderwall.com/p/xyuoza/git-cloning-specific-commits
