### ISSUE TITLE
Files not valid due to permissions

### ISSUE THREAD

**Issue by Seishirou-J2K** [mdhiggins/sickbeard_mp4_automator#1565]
Hello,
I've ran into the issue of when the script returns
```
2022-04-13 23:31:18 - resources.mediaprocessor - INFO - File /tv/test/xxx/Season 1/xxx - S01E01 - 1080p WEB x264.mkv is not valid
2022-04-13 23:31:18 - SonarrPostProcess - INFO - Processing returned False.
2022-04-13 23:31:18 - SonarrPostProcess - ERROR - Error processing file.
```
and after much investigating like #1394 and #1230 it seems the permissions for the directory I output my downloads is set as root but I can not change it as it is a ntfs drive. I can successfully run manual.py and ffprobe on the file when root, but when arr programs try to call the script it will error as seen above. Is there anything I can do other than nuking the drive and making it another format or making the user root for these containers?

**Comment by mdhiggins** [comment]
Opening an issue for what is clearly a filesystem/operating system problem unrelated to the script is kind of poor form

I have never used NTFS under linux before so I have no background experience with this but I did a quick search 

https://askubuntu.com/a/74851

That looks to contain a few solutions that allow you to set permissions on an NTFS drive with JanC's response probably being the best answer
