### ISSUE TITLE
Auto create chapters

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1566]
I wasn't sure if this feature was already done but if not could you auto create chapters for videos that don't have chapters already. Basically if chapters don't exist then create chapters every 5 or 10 minutes in the video?

**Comment by mdhiggins** [comment]
Feature does not exist, adding chapters via ffmpeg is a huge pain; open to a pull request but not something I'm likely to spend time developing

**Comment by mdhiggins** [comment]
01356dfc3ff933a7039e9530fd979b9acb25795b

This update gives you the option to import external metadata files which can contain chapter definitions

Just name it filename.metadata.txt and it will be used to write custom chapter metadata which should get you closer to a solution if you want to write out your own chapters

https://ffmpeg.org/ffmpeg-formats.html#Metadata-1

There's a sample of what a metadata file with chapter data can look like

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions#params-for-validation

The validation method could be leveraged to create this external metadata file with a custom function to design chapters to your liking
