### ISSUE TITLE
Disable undefined language for first-stream-of-language

### ISSUE THREAD

**Issue by Petterooe** [mdhiggins/sickbeard_mp4_automator#1568]
I only want one audio stream of one language so the setting first-stream-of-language is set to True.
But so many media have undefined languages like this.

    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "channels": 6,
            "samplerate": 48000,
            "language": "und",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 4,
            "codec": "aac",
            "channels": 6,
            "samplerate": 48000,
            "language": "und",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        }
The sound languages are english and thai. If not undefined is disabled one of them are filtered away.
I've disabled it in generateOptions line 1047 with  (and a.metadata['language']!='und') with this addition I can have the option always True.

            # Remove the language if we only want the first stream from a given language
            if self.settings.audio_first_language_stream and a.metadata['language']!='und':
                blocked_audio_languages.append(a.metadata['language'])
                self.log.debug("Blocking further %s audio streams to prevent multiple streams of the same language [audio-first-stream-of-language]." % a.metadata['language'])

**Comment by mdhiggins** [comment]
fd9ee9d66b590245254aa74d84f648fb601fc3e4

Merged
