### ISSUE TITLE
Feature - Option to disable title metadata

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sickbeard_mp4_automator#1571]
While possibly usefull in certain situations it still would be nice to have a toggle to disable title data from being written.

With Plex + mkv files for example the regular display title e.g. `English (AC3 5.1)` and the title and/or handler_name(?) `5.1 Channel` are shown. Same goes for subtitles. Which in my opinion is quite unnecessary and doesn't look good. 

I would appreciate an option (or just a workaround if possible) to stop this data from being written.

**Comment by mdhiggins** [comment]
Updated the custom functions to include the option to define custom titles, see

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions#params-for-streamtitle

`streamTitle`

The included sample file is updated as well

You can also preserve source titles via the already existing option `keep-titles`

**Comment by mdhiggins** [comment]
Return `""` to just blank out the title metadata entirely for the streams
