### ISSUE TITLE
Question: Difference between Audio/Universal Audio?

### ISSUE THREAD

**Issue by ajax-lives** [mdhiggins/sickbeard_mp4_automator#1572]
Hey there!  This software is absolutely amazing - little to no isuses and been running smoothly for ages.

Recently - I've been converting all audio tracks to simply AAC 2.0, as all my setups are stereo, however, some of my Plex users have bigger setups than I do, and I wouldn't mind keeping EAC3 or AC3 around.  However - I'd like AAC 2.0 to be the default choice for Plex/most players.  I'm not sure if Plex is actually intelligent enough to choose based on client compatibility - over just converting the default track.

Do you have any recommendations for a setup like this?

**Comment by mdhiggins** [comment]
This can be easily done, I'll highlight the main options you'll need:

```
[Universal Audio]
codec = aac
```

```
[Audio]
codec = ac3, eac3
```

```
[Audio.Sorting]
sorting = language, channels.a, map, d.comment
default-sorting = channels.a, map, d.comment
```

This will create an AAC 2.0 audio track for any tracks with more than 2 channels, it will also create/copy an AC3/EAC3 track for any audio tracks with more than 2 channels

The sorting `channels.a` will sort channel counts in an ascending fashion putting your AAC 2.0 track first and choosing those tracks as the default

Only some Plex players are smart enough to choose an audio track based on available speakers, I believe only Apple TV and Roku at this point; I know the Android client doesn't and will just use whatever is first or default

**Comment by ajax-lives** [comment]
What a fantastic and thought out response!  Thank you so much!

I think a lot of my users are currently running Android TV clients, so having AAC 2.0 moved up is awesome!

Love the project!  Hope it keeps going strong!
