### ISSUE TITLE
Separate Host Capabilities.

### ISSUE THREAD

**Issue by BastionNtB** [mdhiggins/sickbeard_mp4_automator#1573]
**Is your feature request related to a problem? Please describe.**

I'm wanting something that allows the mp4 automator to be on a separate host, so that sonarr, radarr, and the downloader, can all be on light hosts, rather than requiring beefier specs for encoding.

**Describe the solution you'd like**

I drew up an example of what it would be like in a flow... The flow itself is slightly incomplete, but it's just an idea. In this design, an agent would be present on the sonarr and radarr host(s) and would receive the environment variables and ship off that information into a remote host via NFS/SMB that would then create a file output. The service on the remote target system would be waiting for files to drop in its queue, then read the files and give that information to mp4automator to encode/unzip and then once done ship that information back off to sonarr/radarr.

![image](https://user-images.githubusercontent.com/15705306/166127137-3841a5a2-ba09-4d87-b982-4762a356f402.png)

I've started working on this, but I'm having conceptual problems, like when sonarr is told to manually import something, it waits for mp4automator to finish the ffmpeg task, but in this concept, sonarr would start the agent, and the agent would fulfill it's task and be done, but no file would be ready for import, as only the information was sent off to the queue.

**Additional context**

I guess I'm curious if I'm overthinking this or reinventing the wheel. Ultimately, I just want mp4 automator to be on its own host with its own resources. Does this already exist?

Thanks! :)

**Comment by mdhiggins** [comment]
Sounds like you kind of just want tdarr

**Comment by BastionNtB** [comment]
Thanks, I will look into it.

**Comment by BastionNtB** [comment]
Have you seen this?

https://github.com/joshuaboniface/rffmpeg
