### ISSUE TITLE
Python3 prerequisites error

### ISSUE THREAD

**Issue by BastionNtB** [mdhiggins/sickbeard_mp4_automator#1574]
**Describe the bug**

During setup on a new Ubuntu Server 20.04 install, I encountered some errors.

**Command or context you are trying to run**
For manual.py include the full command, for integrated commands please include relavent logs from those programs (IE for postSonarr.py please include relevant Sonarr logs)

`python3 -m pip install -r /home/<account>/mp4_automator/setup/requirements.txt -r /home/<account>/mp4_automator/setup/requirements-qbittorrent.txt`

During the install of the requirements using PIP, these errors are present.

> ERROR: cleanit 0.4.4 has requirement chardet>=4.0.0, but you'll have chardet 3.0.4 which is incompatible.
> ERROR: cleanit 0.4.4 has requirement click>=7.1.2, but you'll have click 7.0 which is incompatible.

**System Information**
 - OS: Ubuntu 20.04
 - Python version Python 3.8.10

**Expected behavior**
Install prerequisites without error

**Additional context**

Not sure if these can be safely ignored or if they may want to be added to the list at those specified versions or not. Just an FYI! :)

**Comment by mdhiggins** [comment]
This is an intended pip error when you have already a package installed that is a requirement for one of the items you're installing but not in line with the required versions

I believe including `--upgrade` in your parameters will give pip permission to update those dependencies to the required versions

If not you can manually upgrade the relevant packages using `pip install --upgrade <package>`
