### ISSUE TITLE
SVT-AV1

### ISSUE THREAD

**Issue by sourpatched** [mdhiggins/sickbeard_mp4_automator#1575]
Does this awesome script support AV1 and SVT-AV1? if so how do we use it?

I know FFmpeg does.

**Comment by mdhiggins** [comment]
41d641aacd77c097e5fa2895804ed132b86c7dec

Prelim support for the 3 AV1 encoders

Use `av1` for `libaom-av1`, `svtav1` for `libsvtav1`, and `rav1e` for `librav1e`

Let me know if there's any custom parameters or options you need, I added some basics include the presets and framedata parameters and it'll inherit all other parameters from its VideoCodec parent

**Comment by sourpatched** [comment]
Sorry it's taken me awhile to test this.
===========WARNING===========
The encoder you have chosen svtav1 (None) is not listed as supported in your FFMPEG build, conversion will likely fail, please use a build of FFMPEG that supports None or choose a different encoder.

===========WARNING===========
The encoder you have chosen rav1e (None) is not listed as supported in your FFMPEG build, conversion will likely fail, please use a build of FFMPEG that supports None or choose a different encoder.

avcodec     configuration: --prefix=/usr --extra-version=1+20.04.sav1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdav1d --enable-librist --enable-libvmaf --enable-libzimg --enable-crystalhd --enable-libmfx --enable-libsvtav1 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libplacebo --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libshaderc --enable-libsmbclient

But I have ffmpeg 5.0 and...
V....D libaom-av1           libaom AV1 (codec av1)
 V..... libsvtav1            SVT-AV1(Scalable Video Technology for AV1) encode

Using vaapi hwaccel

**Comment by mdhiggins** [comment]
DId you maybe forget to update the script?

```
The encoder you have chosen svtav1 (None) is not listed as supported in your FFMPEG build, conversion will likely fail, please use a build of FFMPEG that supports None or choose a different encoder.
```

The fact that you're getting the `None` objects in that error message makes me think your script doesn't have the AV1 codec definitions

**Comment by sourpatched** [comment]
Isn't this the code libsvtav1? and libdav1d? I've updated all the files today. I have to build FFMPEG?

**Comment by mdhiggins** [comment]
Not sure what that means. I'm saying make sure your SMA code base is up to date cause your error message would suggest it's not.

Nothing to do with FFMPEG build

**Comment by sourpatched** [comment]
VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI

Looks like VAAPI doesn't support AV1 for my server If it did it should show something like VAProfileAV1Profile0

For anyone viewing this. the command `gst-inspect-1.0 | grep vaapi` and `vainfo` to view what is supported by your CPU/GPU.
