### ISSUE TITLE
Specify custom file for thumbnail

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1577]
Is it possible currently to specify a jpg file during conversion to be used as the file thumbnail artwork?

**Comment by mdhiggins** [comment]
Yes
https://github.com/mdhiggins/sickbeard_mp4_automator#external-cover-art

**Comment by samcro1967** [comment]
Doh.  Totally missed that in the docs.  Works so long as the file name has no spaces in it.  Thanks!

**Comment by mdhiggins** [comment]
Shouldn't be any limitations with or without spaces

Are you seeing a bug?

**Comment by mdhiggins** [comment]
So there's no issues with spaces in the name and testing works fine on my end, there were some edge cases where if the inputfile and output file name were different (like if a .2 was appended) before the extension it might not pick up the file, I added some logic to account for those scenarios

0fb9283f677d45cced7c6b23e9816aa80dd09abb
