### ISSUE TITLE
Able to convert only if the audio is DTS?

### ISSUE THREAD

**Issue by m33ts4k0z** [mdhiggins/sickbeard_mp4_automator#1578]
Hello and thanks for this project.

I wonder if I am able to convert the video only if there is DTS audio in the container:

If there is only DTS audio, the convert to something else.
If there is DTS audio with some other(s), non DTS, audio stream(s) then just remove the dts and keep the other(s) stream(s).

Thanks.

**Comment by mdhiggins** [comment]
You can actually do this leveraging the custom functions though it's not specifically supported as a default option. Check the wiki. The validation method specifically can pretty easily be used to do this

I'm thinking though this is probably not the best approach
