### ISSUE TITLE
Notify Media Managers w/ flags when using Manual.py

### ISSUE THREAD

**Issue by mcaps1** [mdhiggins/sickbeard_mp4_automator#1581]
**Is your feature request related to a problem? Please describe.**
No. However, when processing content and I want a media manager to be notified, I use the qbittorrentpostprocess.py and input the arguments manually to do the conversion and notify the proper manager.

**Describe the solution you'd like**
If manual.py had options or flags to not only process a video for conversion and add metadata, but to notify a media manager and automatically manage it would be very helpful!

**Comment by mdhiggins** [comment]
What would the use case be here instead of using the appropriate manager script?

**Comment by mcaps1** [comment]
For files that may have errored, unable to `guess.it`, or acquired through means outside a downloader, and would like fully processed. Something like `manual.py -i "mp4path" -radarr` can be invoked to use all the preconfigured settings, and then notify the proper manager via api. Also for allowing for further automation of with  `-i directory_path` if you're dealing with multiple files.

**Comment by mdhiggins** [comment]
For this use case I would typically use the manual import feature of radarr/sonarr

**Comment by mdhiggins** [comment]
Any thoughts?
