### ISSUE TITLE
Forced Subtitles in MP4 Container

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sickbeard_mp4_automator#1583]
This is _probably_ an issue with ffmpeg itself, but maybe it is possible to work around this; When embedding `mov_text` subtitles into an MP4 container, the `forced` flag doesn't get applied.

The command does include it:
`-c:s:0 mov_text -map 0:3 -metadata:s:s:0 title=Forced -metadata:s:s:0 handler_name=Forced -metadata:s:s:0 language=deu -disposition:s:0 +default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired-captions`

But in the file the flag `forced` is unset:
```
"@type": "Text",
"StreamOrder": "5",
"ID": "6",
"Format": "Timed Text",
"MuxingMode": "sbtl",
"CodecID": "tx3g",
"Duration": "3776.607",
"BitRate_Mode": "VBR",
"BitRate": "1",
"FrameRate": "0.006",
"FrameCount": "23",
"StreamSize": "462",
"Title": "Forced / Forced",
"Language": "de",
"Default": "Yes",
"Forced": "No",
"AlternateGroup": "3",
"extra": {
"Menus": "0"
}
```
Looks like an older issue but according to [this message](http://ffmpeg.org/pipermail/ffmpeg-user/2020-November/050864.html) other tools do correctly apply the value, maybe it is possible to find some kind of workaround.

**Comment by mdhiggins** [comment]
Yeah this is an FFMpeg limitation without a good workaround. It just doesn't write that data point for mp4 containers

**Comment by Minds3t** [comment]
Yeah thats what I thought. Do you have an idea how I can implement mp4box (with supports that functionality)? I mean, I just could use external subs (or mkv), but Radarr doesn't like them - *.forced.vtt gets renamed to *.vtt for example...
