### ISSUE TITLE
Request: Dynamic Stream Title Naming

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sickbeard_mp4_automator#1584]
With the current custom function template it is possible to set custom or remove track names. I'm searching for a way to set them in a dynamic way, for example name the audio track `Language + Codec + Channel Count @ Bitrate` = `German E-AC3 Atmos 5.1 @ 640 kbps`. Same for subtitles eg. `Language + Disposition` = `German Forced` or `English SDH`

I think this should be possible with the custom functions, but I just don't know how I could implement this.

**Comment by mdhiggins** [comment]
a4962e78ea3bb6fc887766b95af99a37f328d1d5

That improves upon the custom function a little to include both the source MediaStreamInfo object as well as the options dict that was generated for the output file for that stream

Between those two data points you should have access to everything you would need to title as above

Wiki updated

Consolidated some of the old parameters which will exist inside those 2 parameters and updated the sample

**Comment by Minds3t** [comment]
Sorry, but how do I output the custom titles? I sadly don't understand much of these python scripts :/

**Comment by mdhiggins** [comment]
What are you stuck on? The sample file is a good place to start it shows some basic examples

**Comment by Minds3t** [comment]
More or less on the syntax / customizing the output. For now I tried `options.get("codec")` `options.get("channels")` `options.get("bitrate")` How do I output all of them and additionally add a "k" to the bitrate. Sorry, never touched python before

**Comment by Minds3t** [comment]
Got everything working and looking pretty :) But I noticed if I set 
```
    if stream.type == "video":
        return ""
```
It still outputs the default title, eg. `FHD`

**Comment by mdhiggins** [comment]
`""` working fine for me, what's the full function look like?

On my quick test:

`None` gives
```
        "video": {
            "codec": "copy",
            "map": 1,
            "bitrate": 9973.978749999998,
            "crf": -1,
            "maxrate": null,
            "bufsize": null,
            "level": 0.0,
            "profile": null,
            "preset": null,
            "pix_fmt": null,
            "field_order": "progressive",
            "width": null,
            "filter": null,
            "params": null,
            "framedata": null,
            "bsf": null,
            "debug": "video",
            "title": "FHD"
```

`""` gives
```
        "video": {
            "codec": "copy",
            "map": 1,
            "bitrate": 9973.978749999998,
            "crf": -1,
            "maxrate": null,
            "bufsize": null,
            "level": 0.0,
            "profile": null,
            "preset": null,
            "pix_fmt": null,
            "field_order": "progressive",
            "width": null,
            "filter": null,
            "params": null,
            "framedata": null,
            "bsf": null,
            "debug": "video",
            "title": ""
        },
```

**Comment by mdhiggins** [comment]
My sample was missing the HDR parameter which the video title was including and thus was triggering an exception so your video custom function wasn't working, had it on my test and on the wiki just forgot to include it in the sample

3ba66d7cb80639f12962a088d5304005a05c4eaf

That fixes it

```
def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None):
```
