### ISSUE TITLE
Bug: Embed external Vobsubs (Sub + Idx)

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sickbeard_mp4_automator#1585]
I have a "few" files with external subtitles (`.sub` with the corresponding `.idx`). If I am not mistaken it is currently not supported to let SMA embed them.

I already tried setting dvdsub, dvd_subtitle and vobsub in the configuration file. But I think this should be possible to do with ffmpeg. If yes, can it be implemented within SMA?

**Comment by Minds3t** [comment]
Well, my mistake - Looks like it already works, but not quiet: The subtitles look like they got embeded twice and more important, they don't show when playing the files:

The command: 
`
/usr/local/bin/ffmpeg -fix_sub_duration -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details.mkv.original" -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details.idx" -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details-eng.idx" -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details-forced.sub" -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details.sub" -i "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details-eng.sub" -map_metadata -1 -vcodec copy -map 0:0 -metadata:s:v title= -metadata:s:v handler_name= -c:a:0 copy -map 0:1 -metadata:s:a:0 title= -metadata:s:a:0 handler_name= -metadata:s:a:0 language=deu -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:1 copy -map 0:2 -metadata:s:a:1 title= -metadata:s:a:1 handler_name= -metadata:s:a:1 language=eng -disposition:a:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 srt -map 0:3 -metadata:s:s:0 title=Forced -metadata:s:s:0 handler_name=Forced -metadata:s:s:0 language=deu -disposition:s:0 +default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired-captions -c:s:1 copy -map 1:0 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=deu -disposition:s:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:2 copy -map 2:0 -metadata:s:s:2 title= -metadata:s:s:2 handler_name= -metadata:s:s:2 language=eng -disposition:s:2 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:3 copy -map 3:0 -metadata:s:s:3 title=Forced -metadata:s:s:3 handler_name=Forced -metadata:s:s:3 language=deu -disposition:s:3 -default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired-captions -c:s:4 copy -map 4:0 -metadata:s:s:4 title= -metadata:s:s:4 handler_name= -metadata:s:s:4 language=deu -disposition:s:4 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:5 copy -map 5:0 -metadata:s:s:5 title= -metadata:s:s:5 handler_name= -metadata:s:s:5 language=eng -disposition:s:5 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y "/mnt/local/downloads/nzbs/sabnzbd/complete/radarr/Last Night In Soho 2021 German DL 1080p BluRay x264-DETAiLS/last.night.in.soho.2021.german.dl.1080p.bluray.x264-details.mkv"`

The files:
![Screenshot 2022-05-23 022439](https://user-images.githubusercontent.com/20452868/169722948-d405a8e4-97b9-467e-ace9-a5c272d9c294.png)

Result:
![Screenshot 2022-05-23 022518](https://user-images.githubusercontent.com/20452868/169722968-13c32fee-9e35-4459-adba-0c335df67488.png)

**Comment by Minds3t** [comment]
Even when only `pgs` are set in autoProcess.ini it tries to embed `.idx` and `.sub` files.

Also tried embedding the subtitles with MKVToolNix GUI, which worked as it should - So the Subtitles itself are intact.

**Comment by mdhiggins** [comment]
Quick search looks like sub contains the images and idx contains metadata and is paired with the sub file; not sure if FFMPEG supports merging those back together but if you have a sample command that gives you the desired behavior I'll take a look

**Comment by Minds3t** [comment]
I just wanted to embed any external vobsubs. But noticed if I just chose to embed pgs subtitles it also embeded the vobsubs. But yeah maybe it's just not possible with ffmpeg itself, only mkvmerge or similar. If not you should block embedding sub/idx files. I imagine a few people have set to embed pgs subs but end up also having broken vobsubs too.

**Comment by mdhiggins** [comment]
ffprobe must report the .sub/.idx files as PGS since its copying them and they are image based, but even if that wasn't the case as long as you've specified a valid image based codec it will try and convert all image based files to the first codec on your codec list similarly to how it works for in all other areas of the script. The codec option isn't a filter

a5298644f59fa4cd567701b9ed22b73e739f632c

That change applies the ignored-extensions options to external subtitle files in addition to general files if you wish to filter out certain stuff though

The script is dynamic, it doesn't just have a list of extensions, it uses ffprobe to read any files named appropriately to determine if they are candidates and then remuxes or encodes based on your specified codecs
