### ISSUE TITLE
Mark 'Default' Subtitle Track as 'Forced'

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sickbeard_mp4_automator#1587]
In a lot of my older (MKV) files the `forced` subtitle tracks are just marked as `default`, without any other indication that they are forced - No title, only default flag. Would it be possible to implement an option to flag the first as `default` marked subtitle track as `forced`?
```
Text
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : German
Default                                  : Yes
Forced                                   : No
```

**Comment by mdhiggins** [comment]
Probably not something I would add as a general feature just since this is a niche request and one that is prone to also incorrectly mark things as forced but if you wanted to do this on your media, you could do this using the "validation" custom method pretty easily

**Comment by mdhiggins** [comment]
Time to learn python then, its not hard

```py
def validation(mp, info, path):
    # Custom function that skips HDR files that are missing proper HDR metadata / framedata
    mp.log.info("Initiating custom validation method.")

    if not any(s for s in info.subtitle if s.disposition.get("forced", False)) and any(s for s in info.subtitle if s.disposition.get("default", False)):
        mp.log.info("Found a default subtitle without forced subtitle.")
        first_default = next((s for s in info.subtitle if s.disposition.get("default", False)), None)
        if first_default:
            first_default.disposition['forced'] = True

    return True
```

**Comment by Minds3t** [comment]
Yeah definetely should ^^ Thank you very much for your help and generelly this awesome tool!
