### ISSUE TITLE
Stereo downmix volume is low

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1595]
I'm not sure it was a new version of ffmpeg or what but all my stereo downmix versions seem to now have low volume. Is there a way I can add some option for the stereo downmix to increase the volume of the stereo track? I have to raise the volume on my TV to hear the actors talking. 

I'm not sure if this is config option that needs to be adjusted or not.

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5FC+0.707FL+0.707BL+0.5LFE|FR=0.5FC+0.707FR+0.707BR+0.5LFE

[Universal Audio]
codec = opus
channel-bitrate = 0
first-stream-only = False
filter = 
force-filter = False
variable-bitrate = 0
profile =

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/AutoProcess-Settings#audiochannelfilters

Yes, adjust the ChannelFiilters options and you may need to define some additional combinations depending on what your source input is

**Comment by Protektor-Desura** [comment]
Found this:

According to [ATSC standards](http://atsc.org/wp-content/uploads/2015/03/A52-201212-17.pdf) (section 7.8, page 91), the following formula is used to downmix 5.1 to conventional stereo (as opposed to matrix):

Lo = 1.0 * L + clev * C + slev * Ls ;
Ro = 1.0 * R + clev * C + slev * Rs ;
clev and slev should be .707, according to tables 5.9 and 5.10 in the aforementioned document, assuming a center/surround mix level of 0. Other values are provided in those tables which reduces the amount of center mix, which I don't find useful.

With this in mind, the following ffmpeg option produces a good balanced sound with audible dialogue. Note that specifying the audio channels is not necessary.

-af "pan=stereo|FL < 1.0*FL + 0.707*FC + 0.707*BL|FR < 1.0*FR + 0.707*FC + 0.707*BR"

Looks like this means the line should be:

6-2 = pan=stereo|FL < 1.0*FL + 0.707*FC + 0.707*BL|FR < 1.0*FR + 0.707*FC + 0.707*BR

So it would go from:

6-2 = pan=stereo|FL=0.5FC+0.707FL+0.707BL+0.5LFE|FR=0.5FC+0.707FR+0.707BR+0.5LFE

to

6-2 = pan=stereo|FL < 1.0*FL + 0.707*FC + 0.707*BL|FR < 1.0*FR + 0.707*FC + 0.707*BR

Does this look correct to you?

**Comment by Protektor-Desura** [comment]
A note on the use of the less-than symbol, from the pan filter documentation:

> If the ‘=’ in a channel specification is replaced by ‘<’, then the gains for that specification will be renormalized so that the total is 1, thus avoiding clipping noise.

**Comment by Protektor-Desura** [comment]
Is it possible to have multiple lines? One of 5.1, one for 6.1 and one for 7.1?

```
[Audio.ChannelFilters]
6-2 = pan=stereo|FL < 1.0*FL + 0.707*FC + 0.707*BL|FR < 1.0*FR + 0.707*FC + 0.707*BR
7-2 = pan=stereo|FL < 0.321953*FC+0.455310*FL+0.394310*SL+0.227655*SR+0.278819*BC+0.321953*LFE| FR < 0.321953*FC+0.455310*FR+0.394310*SR+0.227655*SL+0.278819*BC+0.321953*LFE
8-2 = pan=stereo| FL < 0.274804*FC+0.388631*FL+0.336565*SL+0.194316*SR+0.336565*BL+0.194316*BR+0.274804*LFE|FR < 0.274804*FC+0.388631*FR+0.336565*SR+0.194316*SL+0.336565*BR+0.194316*BL+0.274804*LFE
```

**Comment by mdhiggins** [comment]
Yep that's supported
