### ISSUE TITLE
Feature: Convert image subs to text subs

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1596]
I was wondering if you ever thought about adding support to auto convert image subs to text using open-source programs?

BDSup2Sub converts image subs. 
https://github.com/mjuhasz/BDSup2Sub
Could use this to convert everything to idx/sub. Supported image subs:
Blu-Ray SUP
Sony BDN XML (as used by Sonic Scenarist HDMV)
HD-DVD SUP (import only)
VobSub (SUB/IDX)
DVD-SUP (SUP/IFO)

VobSub2SRT use this convert idx/sub to SRT.
https://github.com/ruediger/VobSub2SRT
Or convert PGS to SRT
https://github.com/Tentacule/PgsToSrt

**Comment by Protektor-Desura** [comment]
Another option could be to create subtitles if you don't have one and can't fine one.

https://github.com/agermanidis/autosub

This uses Google Web Speech API to do speech recognition then create subtitles from the audio track.

**Comment by mdhiggins** [comment]
I've looking into these options, more so the first one, and given the size it takes, how cpu intensive it was to perform the job, and the overall inaccuracy of the results produced it wasn't further integrated. Both options can be added on via the post-process or custom function features if desired but no plans to integrate these solutions at this time.
