### ISSUE TITLE
ERROR - Error when trying to determine hardware acceleration support

### ISSUE THREAD

**Issue by sourpatched** [mdhiggins/sickbeard_mp4_automator#1597]
2022-07-14 11:06:22 - MANUAL - ERROR - Error when trying to determine hardware acceleration support.
Traceback (most recent call last):
  File "/resources/mediaprocessor.py", line 1292, in generateOptions
    opts, device = self.setAcceleration(info.video.codec, info.video.pix_fmt, codecs, pix_fmts)
  File "/resources/mediaprocessor.py", line 1429, in setAcceleration
    if Converter.decoder(decoder).supportsBitDepth(bit_depth):
  File "/converter/__init__.py", line 68, in decoder
    return next(x() for x in decoder_list if x.decoder_name == decoder) or BaseDecoder()
StopIteration

[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = vaapi
hwaccel-decoders = h264_vaapi, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mkv
output-extension = mkv

[Video]
codec = h264, h264vaapi, h265vaapi, h265, h264

libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.4 ()

Is this anything to worry about as I'm not using vaapi in the video settings atm?

**Comment by mdhiggins** [comment]
This was fixed 3 months ago

https://github.com/mdhiggins/sickbeard_mp4_automator/commit/8a3403d82f8fa0f888db9f5d2c457e874886b9b0

Just update

**Comment by sourpatched** [comment]
Sorry, I copied over the new files days ago to update this but something didn't copy. I've updated that file. Thanks.
