### ISSUE TITLE
the Wiki page on 'Configuration Options for autoProcess.ini' incorrectly states 'ac3' for Universal Audio audio codec

### ISSUE THREAD

**Issue by robel** [mdhiggins/sickbeard_mp4_automator#1598]
the Wiki page on 'Configuration Options for autoProcess.ini' incorrectly states 'ac3' for Universal Audio audio codec

suggesting to update to 'aac' per example provided in https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/setup/autoProcess.ini.sample

Have a nice day!

**Comment by mdhiggins** [comment]
Fixed!
