### ISSUE TITLE
Only tag video metadata 

### ISSUE THREAD

**Issue by sourpatched** [mdhiggins/sickbeard_mp4_automator#1602]
Sometimes I only want to add metadata to the video file, this works if there is a match with the settings but not when you're doing a batch on auto. This can be done without the -a command but you have to sort each media file.

command like -t to tell the script to only tag media. 

Would this be possible while using the auto command?

**Comment by mdhiggins** [comment]
What do you mean by "this works if there is a match with the settings but not when you're doing a batch on auto"?

It shouldn't be treated differently

**Comment by sourpatched** [comment]
if the settings is mkv h.264 tag metadata, any media that matches this will be tagged but if the media is mp4 then it will be converted. mp4 is fine and sometimes just want to tag the file that is mp4 or mkv.

**Comment by mdhiggins** [comment]
e6535dd61d66b0c6de7f2275f58952a1df7f9df8

How's that?

Adds a `-to` or `--tagonly` option to manual.py

**Comment by sourpatched** [comment]
Awesome! looks good.

Does this also include tag only for mkv if there isn't a match in the config?

**Comment by mdhiggins** [comment]
Yeah its agnostic of the format; the standard behavior is that it will default to tag only mode if the input format is already the same as the output format, that's probably why you were tagging mp4s but it wasn't anything against mkv files, just that it wasn't matching your output format. If your output format had been the other way around then mkvs would have tagged and mp4s convertd

the tag only option just skips all those checks and format checks and goes right to the tagging step

**Comment by sourpatched** [comment]
Thank you!

I've just tested it and without issue it works.

**Comment by sourpatched** [comment]
Is this the script or an error on my part? Tagging mp4 works well but tried MKV and this happened
`FFMPEG Tag Error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1052, in load
    moov = atoms[b"moov"]
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/_atom.py", line 189, in __getitem__
    raise KeyError("%r not found" % names[0])
KeyError: "b'moov' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/metadata.py", line 163, in writeTags
    video = MP4(path)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1183, in load
    self.info.load(atoms, fileobj)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1054, in load
    raise MP4StreamInfoError("not a MP4 file")
mutagen.mp4.MP4StreamInfoError: not a MP4 file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/metadata.py", line 190, in writeTags
    conv = converter.tag(path, metadata, coverpath, streaming)
AttributeError: 'str' object has no attribute 'tag'`

**Comment by mdhiggins** [comment]
I have no idea why the converter object would be a string, that makes no sense

**Comment by mdhiggins** [comment]
Do you have the full stack trace / logs from this?

**Comment by sourpatched** [comment]
That's all I have, that's the full log, it's what's inside of the log file.

**Comment by mdhiggins** [comment]
How about the full manual.py output? I'm not able to reproduce this MKVs are working fine for me

**Comment by sourpatched** [comment]
2022-08-09 12:04:42 - MANUAL - INFO - Manual processor started.
2022-08-09 12:04:42 - MANUAL - INFO - Python 64-bit 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0].
2022-08-09 12:04:42 - MANUAL - INFO - Guessit version: 3.4.3.
2022-08-09 12:04:42 - MANUAL - INFO - /usr/bin/python
2022-08-09 12:04:42 - MANUAL - INFO - Loading config file /config/autoProcess.ini.
2022-08-09 12:04:42 - MANUAL - INFO - Tag only enabled
2022-08-09 12:05:27 - MANUAL - INFO - Processing file____.mkv
2022-08-09 12:05:33 - MANUAL - ERROR - Unable to retrieve rating.
2022-08-09 12:05:33 - MANUAL - INFO - Matched TV episode as _____
2022-08-09 12:05:33 - MANUAL - INFO - Processing _______
2022-08-09 12:05:33 - MANUAL - INFO - Tagging file: _____.mkv
2022-08-09 12:05:36 - MANUAL - ERROR - FFMPEG Tag Error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1052, in load
    moov = atoms[b"moov"]
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/_atom.py", line 189, in __getitem__
    raise KeyError("%r not found" % names[0])
KeyError: "b'moov' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/metadata.py", line 163, in writeTags
    video = MP4(path)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1183, in load
    self.info.load(atoms, fileobj)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mutagen/mp4/__init__.py", line 1054, in load
    raise MP4StreamInfoError("not a MP4 file")
mutagen.mp4.MP4StreamInfoError: not a MP4 file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/metadata.py", line 190, in writeTags
    conv = converter.tag(path, metadata, coverpath, streaming)
AttributeError: 'str' object has no attribute 'tag'
2022-08-09 12:05:36 - MANUAL - INFO - Relocating MOOV atom to start of file.
2022-08-09 12:05:36 - MANUAL - WARNING - QT FastStart did not run - perhaps moov atom was at the start already or file is in the wrong format.

**Comment by mdhiggins** [comment]
```
conv = converter.tag(path, metadata, coverpath, streaming)
AttributeError: 'str' object has no attribute 'tag'`
```

Can you double check your installation and make sure you don't have any modifications or changes? I can't find any reason that converter should equal a string

**Comment by sourpatched** [comment]
Only the config

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = thumb
sanitize-disposition = 
strip-metadata = False
keep-titles = False

**Comment by mdhiggins** [comment]
I meant with the python files, make sure git doesn't detect any changes or inconsistencies, the config files aren't part of the repository so they won't be touched

**Comment by sourpatched** [comment]
Just deleted everything and downloaded. It works. It was the config file 

[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels =
hwaccel-decoders = h264_vaapi, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mkv
output-extension = mkv
temp-extension = 
temp-output = False
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 7777
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = thumb
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h265, h264, h264vaapi, h265vaapi, h265
max-bitrate = 9058
bitrate-ratio = 0.8
crf = -1
crf-profiles = 
preset = 4
codec-parameters = 
dynamic-parameters = True
max-width = 0
profile = high
max-level = 0.0
pix-fmt = yuv420p, yuv420p10le
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec =
pix-fmt = p010le
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3,eac3,truehd,DTS
languages = Eng
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
aac-adtstoasc = False
ignored-dispositions = 
unique-dispositions = False
stream-codec-combinations = 
copy-original-before = False

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
filter = 
profile = 
force-filter = False
move-after = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = srt
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding =
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = True
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 
remove-bitstream-subs = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.Subliminal]
download-subs = True
download-hearing-impaired-subs = False
providers = opensubtitles

[Subtitle.Subliminal.Auth]
opensubtitles = password:pass
Addic7ed = password:pass
tvsubtitles = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token =

**Comment by mdhiggins** [comment]
I don't think it was the config file, I think you had a messed up python file somewhere in there, there shouldn't be any config option that would have been turning the convert object into a string, try your old config file with clean python files

**Comment by mdhiggins** [comment]
Out of curiosity, how are you updating from github when a new commit gets published?

**Comment by sourpatched** [comment]
No file has been edited other then config, I download and replace the files, I think now I'll delete all the files and add all the others in a clean folder. I check here every so often, it's hard to know what's been changed or added without a change log but I just download everything. 

It's Working like there's no tomorrow.

Thank you! your good person!

**Comment by mdhiggins** [comment]
All good, I would recommend you just use git clone and then you can do a quick `git pull origin master` on the directory whenever to upload and verify the file integrity, this won't interfere with config or log files

**Comment by sourpatched** [comment]
#!/bin/bash
git clone https://github.com/mdhiggins/sickbeard_mp4_automator

sudo ./update.sh 

Any thoughts on including an update script?

**Comment by mdhiggins** [comment]
It's just one line to update no need for a script

git pull origin master

**Comment by sourpatched** [comment]
If anyone comes across this and doesn't understand. Use `git clone https://github.com/mdhiggins/sickbeard_mp4_automator` then to update `git pull origin master` (at other time) within the folder.

Too easy, thanks again!
