### ISSUE TITLE
Changing Audio Language

### ISSUE THREAD

**Issue by dramirvf** [mdhiggins/sickbeard_mp4_automator#1604]
Hi,

Is there a way to change audio language of an audio stream through autoProcess.ini?

If the audio language is `undefined`, SMA automatically changes the language to the `default-language` value in autoProcess. But if the audio language is set to a value, it won't change according to the default-language value in autoProcess.

Foe example, I have an movie which is actually in Korean language, but it has been encoded with Japanese audio language. I tried to change it to Korean, but I couldn't do it through SMA.

Any ideas?

**Comment by mdhiggins** [comment]
No functionality is built in to change incorrectly labelled language metadata beyond the undefined

That being said, you could write a few lines to do this using the `skipStream` custom function pretty easily

Rough untested sample with a guess on the language codes for japanese and korean would be something like

```py
def skipStream(mp, stream, info, path):
    if stream.metadata.get('languaage') == 'jpn':
        stream.metadata['language'] = 'kor'
    return False
```

So you're not actually skipping the stream (return False) but before any further processing is done you're modifying the language value

**Comment by dramirvf** [comment]
This solution isn't convenient as I tag missing movies or series according to the audio language. After the completion of download task, the relevant AutoProcess.ini i.e. `AutoProcess-English.ini, AutoProcess-Spanish.ini, AutoProcess-French.ini, etc` would start according to the Radarr/Sonarr tag. If the audio is `undefined`, SMA automatically sets the audio language according to the predefined parameter in the relevant AutoProcess.ini, but sometimes the predefined audio language is wrong. It would be very great to have a force-rename parameter in the audio section of AutoProcess.ini, which could force-rename the audio language only if the value is set by user.

Otherwise, the simplest solution would be a manual custom command through ffmpeg CLI.

**Comment by mdhiggins** [comment]
Not sure how a custom ffmpeg cli would be simpler or more convenient than what I proposed above; that was just a quick example it's up to you to tailor it to your use case. I clearly didn't have enough info from your first comment to know anything about the multiple autoProcess options to have anticipated and crafted an exactly solution but it would be easy enough to adjust it

```
def skipStream(mp, stream, info, path):
    if stream.type == "audio":
        stream.metadata['language'] = mp.settings.adl
    return False
```

That would just set every audio stream to the audio default language which it sounds like is what you're aiming to do, but again you can customize it to your liking or special use case

**Comment by dramirvf** [comment]
You are right. I did not provide enough data and I thought you mean we should write a code according to each incorrect predefined audio language (which would be more difficult than a custom ffmpeg CLI).

Would `custom.py` be called automatically during the post-process (i.e. just by running `PostRadarr.py` or `PostSonarr.py`)?
Or we shuold run it through Radarr/Sonarr post-processing?

And if it would be called automatically, is this code considered in the calculation of final parameters for ffmpeg conversion? or it will trigger an additional ffmpeg process by SMA?

**Comment by mdhiggins** [comment]
The custom functions are handled very differently than the post processing scripts. The post processing scripts are essentially external programs that can be in any language and data is passed through environment variables but they are isolated and run after SMA has finished

The custom functions are built in native functions within the script and are run and handled like any other method in the usual processing of the files during the time of initial processing. The custom.py file isn't executed by itself per se, but each function is in a in a standardized format with expected parameters and returns and are imported into the script and run as though they were native code. Its essentially an alterative to you just modifying the python code of mediaprocessor.py directly that lets you define custom code but in a way that remains separate from the main file so you can still get future updates etc but you get to leverage the actual python objects including the media processor data, the ffmpeg data, and your settings data to do things that would be hard or esoteric to automate on a general level.

When exactly they are executed is different for each one and you can review when specifically they are called in mediaprocessor.py but its during the initial option generation step of processing, not as a post-process approach

**Comment by dramirvf** [comment]
I see some lines in the `custom.py` which are not present in `custom.py.sample`.
Should I remove them? And only place the codes similar to what I see in `custom.py.sample`?

And in `custom.py.sample` you have mentioned that 3 included functions are provided as a reference. But I see 6 sections which start with `def`. Is it actually 3 sample functions? or 6 sample functions?

**Comment by mdhiggins** [comment]
Don't touch resources/custom.py, that's different

You want to copy the sample to your config folder and rename it custom.py and that's where you'll make your modifications

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions

The 6 potential functions are outlined in the sample file but that comment at the top that says 3 is old, there are 6 now

You do not need to define all 6, only the ones you want to use which would be the one I recommended above

**Comment by mdhiggins** [comment]
9f367ea81b0aa4dd90df45ff11ab6b700483a7b8

**Comment by dramirvf** [comment]
I checked the code and everything works fine. Thanks for your help.
