### ISSUE TITLE
Am I missing an option for when to burn in subtitles

### ISSUE THREAD

**Issue by sdfg2** [mdhiggins/sickbeard_mp4_automator#1606]
This is probably an edge case, so I apologise up front.

I have a series (I doubt it'll be the last) that has a single foreign language audio track for the audio in all the files.  It doesn't have any subtitles embedded in my language (English).  Subliminal has kindly fetched the subtitles for me (I love that option, thank you for adding it).

The problem is, because it's natively not English for audio, the downloaded subtitles are just labelled 'English' (as opposed to forced as it would be with mixed language audio streams).

What I'd like to do is if the only audio track is in language A, and I have requested subtitles in language B, the subtitles that are downloaded are burned in to the video, even if they are not marked as forced.  Is there a combination of options I'm missing?

**Comment by mdhiggins** [comment]
You can burn any subtitles they don't have to be forced just set `burn-dispositions = forced` to `burn-dispositions = `

**Comment by sdfg2** [comment]
So if I do it that way, I'd have to expand the `ignored-dispositions` to include everything _except_ forced?  Sorry, I'm still just trying to work out the config :-)

**Comment by sdfg2** [comment]
Here's a good example:

```
    "audio": [                                                                                                                                                                                                        
        {                                                                                                                                                                                                             
            "index": 1,                                                                                                                                                                                               
            "codec": "dts",                                                                                                                                                                                           
            "bitrate": 768000,                                                                                                                                                                                        
            "channels": 7,                                                                                                                                                                                                                                                                                                                                                                                                                   
            "samplerate": 48000,                                                                                                                                                                                      
            "language": "jpn",                                                                                                                                                                                                                                                                                                                                                                                                               
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"                                                                                                                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                                                                                                                                                                                                                   
        {                                                                                                                                                                                                                                                                                                                                                                                                                                    
            "index": 2,                                                                                                                                                                                               
            "codec": "dts",                                                                                                                                                                                           
            "bitrate": 768000,                                                                                                                                                                                        
            "channels": 7,                                                                                                                                                                                                                                                                                                                                                                                                                   
            "samplerate": 48000,                                                                                                                                                                                      
            "language": "eng",                                                                                                                                                                                        
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"                                                                                                                                                                                                                                                                                                                   
        }                                                                                                                                                                                                             
    ],                                                                                                                                                                                                                
    "subtitle": [                                                                                                                                                                                                     
        {                                                                                                                                                                                                             
            "index": 3,                                                                                                                                                                                               
            "codec": "subrip",                                                                                                                                                                                        
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",                                                                                                                                                                                                                                                                                                                  
            "language": "eng"                                                                                                                                                                                         
        }                                                                                                                                                                                                             
    ],
```

So I want to keep the default audio, lose the english, keep the english subs and burn them in, if that makes sense?

**Comment by sdfg2** [comment]
I've broken the first part of the question (keeping the default audio) into #1609.  Keep this one about subtitles.

**Comment by mdhiggins** [comment]
Seems like based on that example just setting your audio language to "jpn" will drop the english and then have you subtitle language set to "eng" and leave burn-dispositions blank (or "default" depending on preferences)

**Comment by sdfg2** [comment]
Yes, and that solves this _specific_ case.  But not all my foreign language media is default `jpn`.  Some are `swe`.  Some are `rus`.  Some are `fre`.  I don't care about the language _specifically_, just that it's the default language that I want to keep.

Also, what happens if I've got `eng` and `eng` forced subtitles, how will sma know which one to burn in?

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/sdfg2-requests

See if those new options work for you, I don't have a ton of good files to test against

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/commit/268ef26556892ae8472b2b1e2cdeb5f92d9d899e

That commit specifically contains the changes, two new options `relax-to-default` and `burn-sorting` to address this and your other issue #1606

**Comment by sdfg2** [comment]
`relax-to-default` works well so far on my tests.

`burn-sorting` sort of works - the subs are downloaded from subliminal so the srt I tested didn't have any dispositions set.  Removing all entries from `burn-dispositions` solves that, but I'm now not sure how to make sure that subliminal fetches `forced` before language.  Would that be controlled by `sorting`?

**Comment by mdhiggins** [comment]
Subliminal will fetch what it will fetch (and it doesn't support forced fetching, see https://github.com/Diaoul/subliminal/issues/925), the sorting just sorts what's available from the embedded then downloaded subtitles and will choose the first option

**Comment by mdhiggins** [comment]
https://github.com/morpheus65535/bazarr/commit/73269efebc765841adf714f393780c3f59ab7c7e

Lots of manual overrides and SQL queries to get around that it looks like, beyond the scope of this project

**Comment by sdfg2** [comment]
Hah you're quicker than me, I just found that too.

**Comment by sdfg2** [comment]
You've been a great help.  I'm going to close this and #1609.

I didn't realise that subliminal couldn't download forced subs, so I've spent hours figuring out a new tool chain.  I wonder if you could use your insight and experience to give me your thoughts?

First, using external sources instead of sma to get subtitles seems like the best way, and, if I'm doing that, burning in makes no sense (the external tool might get different subs later on, and it would just burn in something on top of the already existing ones).  The good thing is though that sma can at least strip any subtitles that I don't want, most tools will only add, not remove.

(I'm going to use `eng` for shorthand here, it would really extend to anything in `languages`)

The aim is to only have one audio stream, and one subtitle stream (forced, OR `eng` _only if_ the audio is not in `eng`).  So, I think my current work around would be this:

1. sonarr/radarr calls sma
2. sma cleans up the audio, downmixes, removes unwanted subtitle languages
3. sma calls bazarr using api calls in postProcess
4. bazarr uses the profile I've setup (tries to get forced, and, if the audio is not `eng`, tries to get `eng` subtitles)
5. bazarr calls a post process script to clean up the subtitles and embed them

(I'd let sma call bazarr because I wouldn't want bazarr messing around embedding things if sma is in the middle of doing its own processing.)

That leaves potentially two subtitle streams that I'm interested in, `d.forced.d` and `language`, and I can use `sorting` to prioritise which one is first, which I hope would then make it the default on my clients, even if `d.default.d` isn't set.  But that will most likely mean that I will still have subtitles that don't need it (i.e. ones where the subtitles are non-forced `eng`, and the audio is also `eng`).  

An option to solve that would be to strip all "non-forced, non-`eng`" subtitle tracks, and let bazarr fetch `eng` if the audio track is not `eng` (it's got a wonderful setting in the profile for doing that).

Three things come to mind.

First, something like a preProcess, or an option to use bazarr APIs instead of subliminal. (The call is as simple as `curl -d "sonarr_episodefile_id=$sonarr_episodefile_id" -H "x-api-key: ###############################" -X POST http://localhost:6767/api/webhooks/sonarr`.  Unfortunately I don't know what the return values are, the api documentation is sparse) (this saves having to mux once in sma, and once again when bazarr gets subtitles)

Second, a way to only embed/burn/keep `language` subtitles if the audio language is different. (`language` in terms of `sorting`, not `language` in terms of `languages`). (So `eng` non-forced subtitle gets kept if the audio is `ukr`, but not if audio is `eng`). Is this the kind of thing that would better put in a postProcess script?  It shouldn't be too difficult to knock something up with `ffprobe` and `ffmpeg`, thought it would probably mean another pass over the file?

Third, a `unique-language` option?  So for any language, the first stream that matches in `sorting` (or maybe `embed-sorting`?) is the only one that's used. (So if there's a `forced` track, that gets embedded, not `eng`) Again, mainly to prevent another pass over the file.

At the end of the day, between sma's postProcessing and bazarr's custom scripts all of this is doable, but each time it means another pass over the file.  I'm just trying to think of how to minimize that, which is why I wonder what thoughts you might have on it - you've got more intimate knowledge than I have!  If it's way out of scope just let me know.

**Comment by mdhiggins** [comment]
Busy with work the next few days but I will review this and try and get back to you with an insightful answer
