### ISSUE TITLE
Option to remove forced disposition

### ISSUE THREAD

**Issue by Petterooe** [mdhiggins/sickbeard_mp4_automator#1607]
I use the well working audio sorting function to set the original sound of media as first stream and the dubbed sound as second stream
as I want the the original to be picked first and have the dub as a complement like this 1.eng,2.tha 1.chi,2.tha 1.kor,2.tha.
But then when the dubbed stream has the forced disposition most unconfigured players will pick the dubbed stream first anyway.
So my suggestion is to have an option to remove any forced disposition. Maybe I'm totally lost and there are other ways already existing?

    def audioStreamTitle(self, stream, options):
        if disposition.get(dispo) and not (self.settings.remove_forced and dispo == 'forced'):
                    output += " (%s)" % BaseCodec.DISPO_STRINGS[dispo]

**Comment by mdhiggins** [comment]
This already exists, use the `sanitize-disposition` option

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/AutoProcess-Settings#metadata

**Comment by Petterooe** [comment]
Thanks! How could I've missed that option for so long.
Because of this I expanded the canBypassConvert with a check for wrong disposition or language order to filter out old media to remux them correctly. 
When doing this I found a thing you might want to change. The info object are altered before the Input data is printed out
in generateOptions mabye you want to move that down.

     -  # Update disposition information using titles, requires PyMediaInfo
     -  self.titleDispositionCheck(info)
     -  self.cleanDispositions(info)

        try:
            self.log.info("Input Data")
            self.log.info(json.dumps(info.json, sort_keys=False, indent=4))
        except:
            self.log.exception("Unable to print input file data")
 
      + # Update disposition information using titles, requires PyMediaInfo
      + self.titleDispositionCheck(info)
      + self.cleanDispositions(info)

**Comment by mdhiggins** [comment]
Intentionally have that afterward otherwise it makes it very difficult to determine certain behaviors when people post logs
