### ISSUE TITLE
Best supported download client

### ISSUE THREAD

**Issue by sdfg2** [mdhiggins/sickbeard_mp4_automator#1608]
Hopefully a very quick question!  I currently use transmission, which I know isn't supported, and I know why, and I completely agree.

So I've got a question:  given you work with the various download clients, which would _you_ say is the most well integrated?

(I'm assuming that the best chain is doing `sma` before importing into radarr/sonarr, and not using post-import scripts in them?)

**Comment by mdhiggins** [comment]
I basically only use postSonarr and postRadarr these days just cause it's easier but for torrent clients I would say deluge works pretty well and would pick that over others

**Comment by sdfg2** [comment]
How do the post scripts work in terms of importing?  Radarr imports, moves, and renames, then it calls sma, sma changes things, then tells radarr to re-import it, and radarr renames it again?

**Comment by mdhiggins** [comment]
Almost, rather than re-importing it just notifies radarr that the file was changed via its API which rescans and renames and then it restores the scenename and releasegroup data without doing a full re-import

**Comment by sdfg2** [comment]
Ah! I see, that's clever.  A very elegant way of doing it.  Are postProcess scripts run before radarr is told about the changes?  I want to run [`ffmpeg-normalize`](https://github.com/slhck/ffmpeg-normalize) on the media once I've done the downsampling and stuff that sma does.

**Comment by mdhiggins** [comment]
You could easily set up a post-process script within SMA that would handle that before updating the sonarr/radarr API

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/post_process/post_process.md

**Comment by sdfg2** [comment]
Brilliant, thanks.  I just wasn't sure when the post processing kicked in, whether it was chained or forked, if you see what I mean.
