### ISSUE TITLE
Setup / Configuration to only remux MKV to MP4

### ISSUE THREAD

**Issue by stitch** [mdhiggins/sickbeard_mp4_automator#1612]
**Is your feature request related to a problem? Please describe.**
Having an LG tv, means that the combination MKV + DolbyVision is not supported. This means basically everything that is published today in higher qualities. Since MKV is a container, i'd like to just remux the files from the mkv container to an mp4 container, without converting them.

**Describe the solution you'd like**
To have a solution in terms of example copy-paste configuration or tutorial that requires minimal knowledge and effort to prevent converting.

**Describe alternatives you've considered**
Writing some conversion script myself, which would only end up being something that would result into a repo like this eventually.

**Comment by mdhiggins** [comment]
The correct way is to include whichever codecs and parameters you want to remux based on whatever source you're inputting.

If you are seeing encoding the output and logs will tell you why under the "debug" tag so you can tweak settings accordingly. 

You can also just have "copy" as your only codec listed to force copying
