### ISSUE TITLE
Broken ability to set AAC 2.0 audio as default

### ISSUE THREAD

**Issue by oregonpillow** [mdhiggins/sickbeard_mp4_automator#1615]
Problem:
Without changing anything to my system or config, all of a sudden AAC 2.0 converted audio streams are no longer the default audio stream. It converts the video stream to mp4  and audio to AAC but wont set AAC as default audio anymore.

System:
- I'm using the latest docker/sonarr images that you maintain.
- Debian 10 / amd64

I have not changed a single thing so i'm wondering if something broke in your more recent images?
thanks for any suggestions and thanks for continuing to maintain such great  images! :)

Here is a copy of my audio and universal-audio config:

```
[Audio]
codec = ac3
languages =
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 256
max-bitrate = 0
max-channels = 0
prefer-more-channels = False
filter =
force-filter = False
sample-rates =
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions =
unique-dispositions = False
sample-format =
stream-codec-combinations =
variable-bitrate = 0
profile =
relax-to-default = False
force-default = False

[Universal Audio]
codec = aac
channel-bitrate = 256
first-stream-only = False
filter =
force-filter = False
variable-bitrate = 0
profile =
```

**Comment by mdhiggins** [comment]
Depending on how long its been since you updated, all of the sorting and default options were migrated to a new system

There is code in place that's supposed to try and move the old settings to the new system but guessing that didn't work in this case

Unfortunately for the settings you've posted, you're missing the relevant ones

There's the defaults

```
[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 
```

If you want stereo to be default change default sorting to

```
default-sorting = channels.a, map, d.comment
```

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Sorting

**Comment by oregonpillow** [comment]
@mdhiggins thanks for such a quick reply :)

ah ok that's good to know. I use watchtower to auto check for the latest images each night, so in theory as soon as you push updates my images update. At a rough guess judging from the media in my library, it started happening 2-ish weeks ago.

this is my audio sorting config section:
```
[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs =
```

which looks identical to the defaults you posted above. i have now updated it to:
```
[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.a, map, d.comment
codecs =
```

**Comment by mdhiggins** [comment]
Hm weird as that sorting update was months ago I don't believe anything has changed that would have impacted things otherwise

Either way though, let me know if that fixes the issue

**Comment by oregonpillow** [comment]
Seems to have fixed the issue.

Thanks! 👌🏼

**Comment by oregonpillow** [comment]
@mdhiggins hi Michael, quick question. 

Isn't the default Audio stream supposed to be AAC 2.0 anyway?

> Audio - AAC 2.0 with additional AC3 track when source has >2 channels (ex 5.1)

yet the default setting in the autoprocess.ini (as you mentioned above) is:
```
[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs =
```
forgive me i'm wrong, but i thought at least in the past, this was the default behaviour, no?
