### ISSUE TITLE
Error sorting output stream options [audio.sorting-default-sorting].

### ISSUE THREAD

**Issue by Weezzel** [mdhiggins/sickbeard_mp4_automator#1617]
The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
Audio detected for stream 1 - ac3 eng 6 channel.
Creating copy audio stream from source stream 1.
Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
Error sorting output stream options [audio.sorting-default-sorting].
Traceback (most recent call last):
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1117, in generateOptions
    audio_settings = self.sortStreams(
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1620, in sortStreams
    original_language = tagdata.original_language
AttributeError: 'NoneType' object has no attribute 'original_language'
Unable to set the default audio stream.
Traceback (most recent call last):
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1132, in generateOptions
    self.sortStreams(
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1620, in sortStreams
    original_language = tagdata.original_language
AttributeError: 'NoneType' object has no attribute 'original_language'
Reading subtitle streams.
Subtitle detected for stream 2 - dvb_subtitle eng.
Stream 2 is image-based subtitle for codec dvb_subtitle.
Error sorting output stream options [subtitle.sorting-sorting].
Traceback (most recent call last):
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1318, in generateOptions
    subtitle_settings = self.sortStreams(
  File "C:\MP4_Automator\resources\mediaprocessor.py", line 1620, in sortStreams
    original_language = tagdata.original_language
AttributeError: 'NoneType' object has no attribute 'original_language'

![image](https://user-images.githubusercontent.com/67742562/191112797-c8523506-3805-4b55-8940-4699843bdae1.png)
[autoProcess.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/9602260/autoProcess.zip)

**Comment by mdhiggins** [comment]
be9bd935a37b3d7d286f27c001fdac2a2dca646a

That should fix it

That being said this error is happening because tagdata is None which will now be accounted for, but original language sorting does require the tagdata object so it won't sort by original language without it

**Comment by Weezzel** [comment]
Working now after update, Thanks for you hard work.
