### ISSUE TITLE
Help with audio track naming and sorting

### ISSUE THREAD

**Issue by cryo-kronos** [mdhiggins/sickbeard_mp4_automator#1618]
I'm using sickbeard_mp4_automator again after a hiatus of a few years. There's been a lot of changes. One big change I've noticed is how sickbeard_mp4_automator sorts and names audio tracks.

In the past, it used to place the AAC stereo track first, right after the video track. Now, by default, it puts the surround audio track first after the video track. Is there a reason and/or benefit for having the surround audio track first? My understanding was that the stereo track should be first in MP4/M4V files, possibly for iTunes compatibility. Perhaps that is no longer the case.

Is there a way to have the stereo track come first, followed by the surround track, and then any commentary tracks? I've read the sorting section but I don't quite get how to achieve what I want with those settings.

Also, sickbeard_mp4_automator now renames the tracks to HD for the video track, for example, and 5.1 (rather than Surround), for the AC3 5.1 audio track. 

Again, is there a reason or benefit for this? And is there a way to edit this behaviour back to the way it was (e.g., video track, stereo track, surround track)? An option to specify track names would be great.

**Comment by mdhiggins** [comment]
There has been a major overhaul to track sorting so you can tweak it exactly how you may want

See here, https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Sorting

For modifying the track naming, you can use the custom functions feature of the script to specify however you would like the titles to be named, example options that should work for you below

```ini
[Audio.Sorting]
sorting = channels.a, map, d.comment
default-sorting = channels.a, map, d.comment
```

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions

The streamTitle function specifically, there's a sample file that shows an example included that should be similar to the old behavior

Blank title for video, stereo or surround sound for audio, and no override for subtitle tracks

```py
def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None):
    # Custom function to define steam title, return None to use script default function, return "" to set blank
    # stream.disposition contains the disposition dictionary
    # stream.metadata.get('title') contains the original stream title
    # stream.type to check between audio and subtitle
    mp.log.info("Initiating custom stream title method.")
    if stream.type == "audio":
        return "Surround" if options.get("channels") > 2 else "Stereo"
    if stream.type == "video":
        return ""
    if stream.type == "subtitle":
        return None
    return None
```

Just put that in the `custom.py` file in your config folder

**Comment by cryo-kronos** [comment]
Thank you for that information.

Does the audio track order or audio track name in an MP4/M4V have any effect on how a video player (e.g., Infuse, Plex, etc) auto-selects which track to play? 

I'm primarily concerned about atypical behaviour or bugs in the player being triggered if it comes across something non-standard or unexpected.

**Comment by mdhiggins** [comment]
The names shouldn't matter and there wasn't anything special about the old names, I had just picked those based on my own preferences at the time. Players will be mostly looking at language, disposition and codec to select tracks
