### ISSUE TITLE
itunes tagged vs untagged import

### ISSUE THREAD

**Issue by slebrun1** [mdhiggins/sickbeard_mp4_automator#162]
Take an MKV >4 gigabytes.  Use manual.py to auto convert, tag and move it to the auto-add iTunes directory, and iTunes will refuse to import it.  Quicktime will choke on it with an error -2041: an invalid sample description was found in the movie *filename goes here*.

Use manual.py to convert without tagging, and iTunes sucks it in just fine.  Winds up in 'home movies' of course.  Then proceed to either a) use manual.py to tag and move the MP4 file, and iTunes resucks it in just fine, or b) use manual.py -nm to tag in in place, then in iTunes right-click and get info, and iTunes repopulates and moves it to the appropriate movies/tv shows/whatever just fine.

**Comment by brenosabino** [comment]
same here. tried an 1080p mkv file with subtitle using manual.py resulting file seems fine but itunes wont import.

**Comment by mdhiggins** [comment]
Yeah at this point it seems iTunes doesn't like to import certain files with embedded subtitles. Not sure exactly what it doesn't like about the subs though
