### ISSUE TITLE
ModuleNotFoundError: No module named 'tmdbsimple'

### ISSUE THREAD

**Issue by 1stian** [mdhiggins/sickbeard_mp4_automator#1621]
I'm getting this error:

Traceback (most recent call last):
File "/scripts/SABPostProcess.py", line 8, in <module>
from resources.mediaprocessor import MediaProcessor
File "/scripts/resources/mediaprocessor.py", line 12, in <module>
from resources.metadata import Metadata, MediaType
File "/scripts/resources/metadata.py", line 8, in <module>
import tmdbsimple as tmdb
ModuleNotFoundError: No module named 'tmdbsimple'

I'm running binhex-sabnzbd on unraid, which comes without this script. I've added a path for the script like this:

![Gyazo link](https://i.gyazo.com/9a775c43cff7ae2ee16f7ffdc73ffa44.png)
And it is accessible within inside the docker. As I can select the folder and "SABPostProcess.py".

I opened the console for the docker, and installed the requierments with pip install -r setup/requirements.txt

This is what happens if I try to install the "tmdbsimple" module by itself

![Gyazo link](https://i.gyazo.com/f5dc4241b342e208b563a8d14616ac85.png)

When I run python --version it comes back as 3.10.6

Anything I'm missing ???

**Comment by mdhiggins** [comment]
You must have different environments and whatever environment SAB is using does not have the requirements installed

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1445

Essentially this is the issue even though you're not on docker

Easy fix if you can't figure out what environment SAB is using is to just tell it which environment to use by wrapping a small bash script and pointing to your python environment

```
#!/usr/bin/env bash

/usr/local/bin/python3 /path/to/SMA/SABPostProcess.py "$@"
```
