### ISSUE TITLE
scale to multiple resolutions

### ISSUE THREAD

**Issue by moham96** [mdhiggins/sickbeard_mp4_automator#1622]
**Is your feature request related to a problem? Please describe.**
I want to convert the input file to multiple qualities, so for example if I download a 1080p movie then I want to set up SMA to encode it at 720p,480p, and 360p and rename the files accordingly, is this possible? what settings do I have to change 

**Describe the solution you'd like**
I want the output file to be multiple files with different resolution, so sma should apply a scale to different resolutions and output to different files

**Comment by mdhiggins** [comment]
Not a specific way built into the script but this can be easily accomplished with multiple configurations and a wrapper script pretty easily

Just adjust the resolution you want in each config and then change the environment variable `SMA_CONFIG` before launching the script to direct to whichever quality/resolution configuration file you want

https://github.com/mdhiggins/sickbeard_mp4_automator#override-configuration-path

The script does not do file renaming however, that is left for the media managers (Radarr/Sonarr) so you'll have to get a little creative with that though you could write a post-process script to handle that

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/post_process/post_process.md
