### ISSUE TITLE
Issue with output-directory

### ISSUE THREAD

**Issue by henryjb99** [mdhiggins/sickbeard_mp4_automator#1623]
I am using the Sonarr docker image. I have everything working nearly the way I want. Things convert to the proper format. However, if I use the option for output-directory, then I get errors and the conversion never happens.

In this case, I want to output to /SWAP as my system is using mergerfs, and I want it converted on my SSD (SWAP) before the one time write to the final location.
Log output
[logs.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/9844703/logs.txt)

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/9844711/autoProcess.txt)

Docker-compose:
  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - /home/henry/.config/sonarr:/config
      - /opt/sickbeard/config:/usr/local/sma/config
      - /shared:/tv
      - /shared:/downloads
      - /shared:/shared
      - /downloading:/downloading
      - /SWAP:/SWAP
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped

**Comment by mdhiggins** [comment]
Logs posted aren't helpful, need the SMA logs with debug level logging enabled to see what's going on

This should work as I use a similar setup with mergerfs and use a ramdisk for my conversions mounted using tmpfs and the output-directory feature without issues, so wondering if this is a weird permission issue or something. Does whatever you're using for PUID/PGID have permission to write to the this /SWAP directory?

```
    tmpfs:
      - /tmp
```

**Comment by mdhiggins** [comment]
SMA logs are in the config folder under sma.log and debug enabling is outlined here

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by henryjb99** [comment]
Here are the debug logs for 2 different files I attempted to convert. 
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/9845344/sma.log)

**Comment by henryjb99** [comment]
Actually, looking through, this may be an issue with the source files. I got them using yt-dlp and those are all erroring. When I attempt to run the same settings using a different set of files, they work fine. I see that they are using /SWAP

encoding_tool=SMA -y /SWAP/SOME_OTHER_FILE.mp4

**Comment by mdhiggins** [comment]
```
2022-10-22 22:13:40 - resources.mediaprocessor - DEBUG - Invalid source, no audio stream detected.
```

Its failing because the input file has no audio, need at least 1 audio stream

**Comment by henryjb99** [comment]
How odd. You are absolutely right. it appears the yt-dlp files had no audio. Thanks for the help.
