### ISSUE TITLE
Thinking of getting high end server with gpu to redo all my library.

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#1625]
Hi bro, I know its not a bug and sorry for that.

But tomorrow i want to rent gpu server to redo my whole library as lost a lot.
Was thinking rent a gpu sever to encode it all and dump to my home server.

If money no object, what gpus server spec would you recommend? type of gpu make a diffence?

intel dual e5 - 2670E3 24x2.3GHZ  / 128mb ram / 2x geforce GTX 3080ti 250GB SDD is what im currently looking at.
See any problems with that server? what would you improve ig you needed to spend a bit more?

Also what settings in config to enable to use GPU best?

Thankyou once again for your fantastic help bro.

**Comment by mdhiggins** [comment]
I have very limited experience with NVEnc essentially all my hardware transcoding I've done personally has been Quicksync and I only use it for real time transcoding. I remux most of my UHD discs and try to leave the source streams untouched these days. 

That being said anything from the 3000 series should support modern codecs so a 3080ti should be fine. How much content are you planning to encode and to what end? Size reduction?

**Comment by Zeusy123** [comment]
thnaks for the reply bro,
few TB in size.

crf = 23
crf-profiles = 1920:23:8M:24M

mkv -> mp4 
and changing audio also

**Comment by mdhiggins** [comment]
I would imagine that setup should more than meet your needs
