### ISSUE TITLE
Enable hardware acceleration for both hevc and 264

### ISSUE THREAD

**Issue by neilanthonystuckey** [mdhiggins/sickbeard_mp4_automator#1626]
I encode everything to x264 mp4. But it looks like it uses cpu no matter what settings i set in autoProcess.ini.  How do enable hardware acceleration when i re-encode both 264 and hevc to 264/mp4 ?

**Comment by mdhiggins** [comment]
You need to choose a hardware accelerated encoder, and you need to set up the relevant hardware acceleration options in autoProcess.ini, and you'll need to provide an FFMPEG build that supports whatever hardware acceleration platform you're trying to use. See the wiki section and the many existing issues on this question already

If you have a specific question please feel free to ask

The script fully supports hardware acceleration for H264 and HEVC for NVENC (CUDA and COVID), QuickSync, and VAAPI and some of the AV1 hardware encoders as well
