### ISSUE TITLE
FFMPEG only using one thread

### ISSUE THREAD

**Issue by claptrapjargon** [mdhiggins/sickbeard_mp4_automator#1628]
I'm using the sonarr-sma docker container and SABnzbd with the download script. I've noticed that ffmpeg only uses one cpu thread for conversion and changes made to the  default 'threads = 0' in autoProcess.ini don't seem to have any effect. Manually running ffmpeg in the container using the default optimal settings uses about 8 threads.

Any idea what's causing this?

**Comment by mdhiggins** [comment]
Are you running the exact same command? The number of threads FFMPEG uses is highly variable depending on the encoders being used. Would need a comparison of the script command versus your manual command for comparison

**Comment by claptrapjargon** [comment]
I did as you suggested and used exactly the same command which I got from sma.log. This also used only one thread which suggests my original test was flawed. I suppose that one thread is the best/most optimal way for FFMPEG to process the conversion.

**Comment by claptrapjargon** [comment]
Sorry for the delayed response, I'd appreciate it if you would take a look :)

Here's the config I'm using, I've only made quite minimal changes to the defaults:
https://pastebin.com/5tMG06r2

And here's the command according to sma.log (I've only changed path and filenames):
https://pastebin.com/Ub64GSGF

**Comment by mdhiggins** [comment]
So it looks like the command is only encoding audio and copying video, and I believe the AC3 encoder is single threaded. I'm guessing your generic manual command that you had made with ffmpeg probably had video encoding which is much more CPU intensive and more likely to be threaded though I would need that command as well to confirm but remuxing is basically limited by your hard drive speed and uses almost no CPU.
