### ISSUE TITLE
More Options

### ISSUE THREAD

**Issue by VampiricAlien** [mdhiggins/sickbeard_mp4_automator#1629]
Audio Black list - I couldn't find any options for this,  let's say I don't want Opus for some reason, blacklist it and the script makes it acc or something else based on settings.

When tagging (using -to) is it possible to also rename the video title based on script settings and matching?
Option A) A show called Not now little brown cow would have it's video title "Not now little brown cow S01E01" 
Option B) HEVC 1080p (based on video settings)

Under audio settings allow the script to pick more then audio code by using " : "
[Audio]
codec = eac3:aac
languages = Eng
default-language = 

This the file will now have EAC3 as first audio stream then acc

Is any off this possible? :)

**Comment by mdhiggins** [comment]
The codec list is an allowed list, comma separated. If you don't want  opus, just leave it off the list. Anything on the list will be remuxed, if its not on the list, it will be encoded to the first item on that list

Custom stream titles can be achieved using the custom streamTitle function

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions

I just pushed an update to pass the metadata to that custom function as well which would better enable you to include things like season and episode numbers etc

**Comment by VampiricAlien** [comment]
Option in config under metadata 
streamTitle= video:Resolution:range (HEVC 1080p SDR)

%video
%ranage (SDR or HDR)
% Res

Can something this easy be added?

**Comment by mdhiggins** [comment]
Gotta use the streamTitle function as indicated above

**Comment by VampiricAlien** [comment]
I am just going to be honest, I don't know how to use it, I've copied the custom.py into the config folder, does manual.py trigger it?

**Comment by VampiricAlien** [comment]
def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None, tagdata=video):

Tagdata=video will change the stream title to what the video is?

**Comment by mdhiggins** [comment]
Its a python function so you'll need to write it in Python

tagdata is an object that contains elements from TMDB that you could in theory use for your title

```py
def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None, tagdata=None):
    # Custom function to define steam title, return None to use script default function, return "" to set blank
    # stream.disposition contains the disposition dictionary
    # stream.metadata.get('title') contains the original stream title
    # stream.type to check between audio and subtitle
    mp.log.info("Initiating custom stream title method.")
    if stream.type == "video" and tagdata:
        return "%s %s S%02dE%02d" % (options.get("video").get("codec"), "HDR" if hdr else "SDR", tagdata.season, tagdata.episode)
    return None
```

Something like that, you'd need to add logic to make sure its a TV show before applying and you'd probably want to format your codecs a little nicer than just pulling the FFMPEG encoder name but that should get you started

**Comment by VampiricAlien** [comment]
Two more options?

1) Download poster to TV show folder
2) Create .nfo file based on matched

**Comment by mdhiggins** [comment]
The poster and metadata are embedded directly into the file so that external files aren't required, externalizing probably not something I would invest time to develop as its kind of antithesis to the spirit of this project

**Comment by VampiricAlien** [comment]
Fair enough. I was more thinking of Jellyfin/Plex "ready".

**Comment by VampiricAlien** [comment]
Thank you.

**Comment by VampiricAlien** [comment]
> Its a python function so you'll need to write it in Python
> 
> tagdata is an object that contains elements from TMDB that you could in theory use for your title
> 
> ```python
> def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None, tagdata=None):
>     # Custom function to define steam title, return None to use script default function, return "" to set blank
>     # stream.disposition contains the disposition dictionary
>     # stream.metadata.get('title') contains the original stream title
>     # stream.type to check between audio and subtitle
>     mp.log.info("Initiating custom stream title method.")
>     if stream.type == "video" and tagdata:
>         return "%s %s S%02dE%02d" % (options.get("video").get("codec"), "HDR" if hdr else "SDR", tagdata.season, tagdata.episode)
>     return None
> ```
> 
> Something like that, you'd need to add logic to make sure its a TV show before applying and you'd probably want to format your codecs a little nicer than just pulling the FFMPEG encoder name but that should get you started



> Its a python function so you'll need to write it in Python
> 
> tagdata is an object that contains elements from TMDB that you could in theory use for your title
> 
> ```python
> def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None, tagdata=None):
>     # Custom function to define steam title, return None to use script default function, return "" to set blank
>     # stream.disposition contains the disposition dictionary
>     # stream.metadata.get('title') contains the original stream title
>     # stream.type to check between audio and subtitle
>     mp.log.info("Initiating custom stream title method.")
>     if stream.type == "video" and tagdata:
>         return "%s %s S%02dE%02d" % (options.get("video").get("codec"), "HDR" if hdr else "SDR", tagdata.season, tagdata.episode)
>     return None
> ```
> 
> Something like that, you'd need to add logic to make sure its a TV show before applying and you'd probably want to format your codecs a little nicer than just pulling the FFMPEG encoder name but that should get you started

Thank you :)

**Comment by mdhiggins** [comment]
Plex does read the metadata embedded in the files though you'll have to tweak your library settings and agent to have this take priority over the web based agents it defaults to

**Comment by VampiricAlien** [comment]
I am aware of this but doesn't always work but that's okay because this is one hell of an awesome script

**Comment by VampiricAlien** [comment]
Hey again,

Can we have a command to just add subtitles? 

manual.py -so (Subtitle only) or -subs 

This scans the folder for video file and subtitle files and add them to together?

**Comment by mdhiggins** [comment]
If the videos are all in the correct format this is how it will behave already, it will remux all the other tracks

**Comment by VampiricAlien** [comment]
Only if you convert? I'm asking if it's can add subs with a single command?

**Comment by VampiricAlien** [comment]
I was hoping that wasn't the answer.

If we was to add the subs, could the script scan the file and based on that give the command to ffmpeg with subs without using the config?

**Comment by mdhiggins** [comment]
The script does account for this to a degree. Depending on your settings if a file has been processed and in its current state all the codecs would result in a remux it will skip over it, if there were new external subtitles present this check should fail and it should reprocess and merge the subtitles

**Comment by mdhiggins** [comment]
@VampiricAlien you can turn on `detailed-progress` to get the full spectrum of what FFMPEG outputs during conversion, can't remember if ETA is part of that (I vaguely think its not) but it might be what you're looking for

**Comment by mdhiggins** [comment]
Basically if FFMPEG doesn't report it accurately or at all then the script can't, the script is just a fancy wrapper for FFMPEG so its limited to what the main program reports

**Comment by mdhiggins** [comment]
At the end of the day the main thing the script does is generate complicated FFMPEG commands, there's no shame in it 😝 FFMPEG does all the hard work
