### ISSUE TITLE
qBittorrent - RootPath can be empty

### ISSUE THREAD

**Issue by Corey-Evans** [mdhiggins/sickbeard_mp4_automator#1633]
I think there's a small bug that breaks qBittorrent processing in a certain circumstance.

Root path is "first torrent sub-directory path". If the torrent's path something like /seeding/movie.mkv, there is no sub-directory, so Root path is empty. This breaks the requirement of the number of parameters present.

Thanks heaps for your project!

**Comment by mdhiggins** [comment]
Got any logs?

**Comment by Corey-Evans** [comment]
```
2022-12-02 22:30:33 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2022-12-02 22:30:33 - qBittorrentPostProcess - ERROR - Not enough command line parameters present, are you launching this from qBittorrent?
2022-12-02 22:30:33 - qBittorrentPostProcess - ERROR - #Args: %L %T %R %F %N %I Category, Tracker, RootPath, ContentPath , TorrentName, InfoHash
2022-12-02 22:30:33 - qBittorrentPostProcess - ERROR - Length was 6
2022-12-02 22:30:33 - qBittorrentPostProcess - ERROR - ['tv-sonarr', 'http://XXXXXXXXXX/announce', '/seeding/XXXXXXXXX.mkv', 'XXXXXXXXX.mkv', 'XXXXXXXXXX']
```

If you wrap the params in quotes in like below, it reveals RootPath is the one missing:
qBittorrentPostProcess.py "%L" "%T" "%R" "%F" "%N" "%I"

**Comment by Corey-Evans** [comment]
But it seems qBittorrent doesn't actually run the script when the params are in quotes, despite the logs saying it is. Weird.

**Comment by mdhiggins** [comment]
It should work when wrapped in quotes and the quotes are required for situations like this where a value might be empty, do you see anything in the logs when in quotes?

**Comment by Corey-Evans** [comment]
Doesn't work, and nothing shows up in the logs (besides qBittorrent claiming to have called the script).

My guess is it has something to do with how qBittorrent calls the script via /bin/sh https://github.com/qbittorrent/qBittorrent/blob/259b5e51c49b74455183d734932a3c67dba51af8/src/app/application.cpp#L263

I've just removed RootPath param and using os.walk instead for now.

**Comment by mdhiggins** [comment]
819abd4043411fa45b6b2f0154f8a21de2557b63

See if that is able to compensate for the missing root path, should check the length of args and if its 6 it'll basically use the content path as the root path

**Comment by Corey-Evans** [comment]
Looks good. Thanks heaps.
