### ISSUE TITLE
Audio first-stream-only Not Working

### ISSUE THREAD

**Issue by Dead-Rekon** [mdhiggins/sickbeard_mp4_automator#1635]
When setting universal audio first-stream-only to true, I'm getting universal audio streams for both streams in the file. I haven't updated in well over a year as I only use manual, so this could be entirely a case of me overlooking something.

Running default manual.py

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/10241964/autoProcess.txt)

[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/10242042/sma.log)

ffmpeg version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**System Information**
 - OS: Windows 10 x64
 - Python version: 3.8.1

Original File: [1] 7.1 TrueHD   [2] 5.1 AC-3
Expected Result: [1] 7.1 TrueHD   [2] 5.1 AC-3   [3] 2.0 AAC (from 7.1)
Actual Result Result: [1] 7.1 TrueHD   [2] 5.1 AC-3   [3] 2.0 AAC (from 7.1)   [4] 2.0 AAC (from 5.1)

Some of the older settings that were added a while back are depreciated, so I'm coming up to speed on some new ini settings. Thanks for the help!

**Comment by mdhiggins** [comment]
Looks like a bug introduced in this update
https://github.com/mdhiggins/sickbeard_mp4_automator/commit/59cb176209d16a3d8706bd3bfd260ae534a014ae

1a64eb0ffa417fcd8887a3eab18d29887e21c1f3 should fix

**Comment by Dead-Rekon** [comment]
Confirmed fixed. Thanks for all the hard work!
