### ISSUE TITLE
Help with multiple audio in same language

### ISSUE THREAD

**Issue by screamjojo** [mdhiggins/sickbeard_mp4_automator#1642]
Hello and thanks for this awesome tools,

My request is when I've multiple track with the same language I want to set the default language depending on the title name.
ie : 
I have : 

![image](https://user-images.githubusercontent.com/71469935/212138701-c8718ad6-e011-4419-8ebc-bf4629996714.png)

I want : 

![image](https://user-images.githubusercontent.com/71469935/212138947-2850e695-e6eb-4f64-9361-2a249bf569bd.png)

Can you have a cutom script with streamTitle to do that ?
I'm not very good at python coding for doing myyself.

Thanks in advance

**Comment by mdhiggins** [comment]
You could probably use the `skipStream` custom function to set your default stream in this manner

```py
def skipStream(mp, stream, info, path, tagdata):
    # Custom function that skips over a stream
    mp.log.info("Initiating custom stream skip check method.")

    if stream.type == "audio":
        stream.disposition['default'] = ('vff' in stream.metdata.get('title', ''))

    return False
```

Very basic example that sets the default based on whether the 'vff' string is in the title

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions 
if you need more guidance on how to implement this

**Comment by screamjojo** [comment]
> You could probably use the `skipStream` custom function to set your default stream in this manner
> 
> ```python
> def skipStream(mp, stream, info, path, tagdata):
>     # Custom function that skips over a stream
>     mp.log.info("Initiating custom stream skip check method.")
> 
>     if stream.type == "audio":
>         stream.disposition['default'] = ('vff' in stream.metdata.get('title', ''))
> 
>     return False
> ```
> 
> Very basic example that sets the default based on whether the 'vff' string is in the title

Thanks you it works !
But Plex automatically choose the first french stream not the default track...
Can you have a solution for ascending the vff track ? Or disabled other french track if "vff" is found.
Thanks again.

**Comment by mdhiggins** [comment]
Yeah admittedly I hadn't tested that code above, it was just a quick example I typed up in the github window to get you started but glad you got things working, editing that previous post for anyone who stumbles upon this in the future
