### ISSUE TITLE
Question: Is there a way to increase volume of file

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sickbeard_mp4_automator#1646]
Hi, 

Forgive me for my ignorance in this area as sometimes I don't grok this stuff very well.  I'm not sure this is something that can be helped with this tool or not, but I've noticed that it seems the files I run through SMA are "softer" when played on a device like a TV through Plex than normal TV.  Is there a setting unbeknownst to me to help me adjust the audio in the file such that volume is louder or could this just be a problem with the device?  I've attached my settings in case I've misconfigured something.

[settings.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/10728001/settings.txt)

**Comment by mdhiggins** [comment]
Entirely depends on what stream you're playing and what the source is

Your main audio options look like they are probably remuxing most things so it should be a 1:1 copy of the original audio

You do have universal audio enabled and audio channels set to descending so you're probably creating a new stereo audio track from a surround sound source track

I'm guessing the main culprit may be this option which is applied for audio normalization when mapping from a 6 channel stream to a 2 channel stream

```
[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE
```

https://trac.ffmpeg.org/wiki/AudioChannelManipulation

You can tweak the various channels to increase the volume


That being said, I'm making a lot of assumptions so posting a sample conversion log would be helpful if this doesn't solve the issue to see if my assumptions are correct or not

**Comment by powerdude** [comment]
I've attached one of the most recent files processed.

[sma-alert.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/10774696/sma-alert.txt)

**Comment by mdhiggins** [comment]
So my assumption wasn't 100% correct, you're going from 2 channel AC3 to 2 channel AAC

Couple options here

One, if you don't care about AC3 vs AAC you can just add AC3 to your universal audio codec list and then it will just copy it which sidesteps the issue all together and remuxes

```ini
[Universal Audio]
codec = aac, ac3
```

The next option would be to look into filters that can be applied to manipulate audio volume

https://trac.ffmpeg.org/wiki/AudioVolume

You can then apply these filters either here

```ini
[Universal Audio]
filter = 
```

Or more selectively only when going from 2 channel to 2 channel by adding a `2-2` option
```ini
[Audio.ChannelFilters]
2-2 = ***
```
