### ISSUE TITLE
Question: pix-fmt setting in autoProcess.ini

### ISSUE THREAD

**Issue by Junto026** [mdhiggins/sickbeard_mp4_automator#1647]
I am trying to do the same thing as in Issue [#1644](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1644), essentially convert any 10-bit depth videos to 8-bit depth, but skip converting .mp4 files otherwise.

I have set `pix-fmt = yuv420p, yuvj420p` in my autoProcess.ini.  I also set `prioritize-source-pix-fmt = false`.  However, 10-bit .mp4 files are still being copied as-is rather than converted.

Should pix-fmt trigger a conversion?  What could be a reason it wouldn't?  Here is the output of ffprobe on the 10-bit video I'm testing with, and my autoProcess.ini file contents, if it helps.

Test video ffprobe output:
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x1635bdf0] stream 0, timescale not set
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Love Island - S09E36.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     title           : Episode 36
>     album           : Love Island, Season 9
>     genre           : Reality
>     track           : 36/57
>     disc            : 9
>     date            : 2023-02-20
>     encoder         : SMA:Love.Island.S09E36.1080p.HEVC.x265-MeGusta
>     iTunEXTC        : us-tv|TV-MA|600
>     iTunMOVI        : <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
>                     : <key>cast</key><array>
>                     : <dict><key>name</key><string>Iain Stirling</string></dict>
>                     : <dict><key>name</key><string>Maya Jama</string></dict>
>                     : <dict><key>name</key><string>Anna-May Robey</string></dict>
>                     : <dict><key>name</key><string>Haris Namani</string></dict>
>                     : <dict><key>name</key><string>Kai Fagan</string></dict>
>                     : </array>
>                     : <key>screenwriters</key><array>
>                     : </array>
>                     : <key>directors</key><array>
>                     : </array>
>                     : <key>producers</key><array>
>                     : </array>
>                     : </dict></plist>
>                     : 
>     hd_video        : 2
>     season_number   : 9
>     media_type      : 10
>     episode_sort    : 36
>     network         : ITV2
>     episode_id      : Episode 36
>     show            : Love Island
>     description     : The Hideaway's open, one couple get their first date, and the Islanders enjoy a VIP performance in the Villa.
>     synopsis        : The Hideaway's open, one couple get their first date, and the Islanders enjoy a VIP performance in the Villa.
>   Duration: 00:46:50.22, start: 0.000000, bitrate: 2841 kb/s
>   Stream #0:0[0x1](und): Video: h264 (High 10) (avc1 / 0x31637661), yuv420p10le(tv, bt709/unknown/unknown, progressive), 1920x1080, 2574 kb/s, 50 fps, 50 tbr, 12800 tbn (default)
>     Metadata:
>       handler_name    : FHD
>       vendor_id       : [0][0][0][0]
>       encoder         : Lavc59.37.100 libx264
>   Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
>     Metadata:
>       handler_name    : Stereo
>       vendor_id       : [0][0][0][0]
>   Stream #0:2[0x0]: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 576x863 [SAR 1:1 DAR 576:863], 90k tbr, 90k tbn (attached pic)

autoProcess.ini file contents:

> [Converter]
> ffmpeg = ffmpeg
> ffprobe = ffprobe
> threads = 0
> hwaccels = 
> hwaccel-decoders = 
> hwdevices = 
> hwaccel-output-format = 
> output-directory = 
> output-format = mp4
> output-extension = mp4
> temp-extension = converting
> temp-output = False
> minimum-size = 0
> ignored-extensions = nfo, ds_store
> copy-to = 
> move-to = 
> delete-original = True
> process-same-extensions = True
> bypass-if-copying-all = False
> force-convert = False
> post-process = False
> wait-post-process = False
> detailed-progress = False
> opts-separator = ,
> preopts = 
> postopts = 
> regex-directory-replace = [^\w\-_\. ]
> output-directory-space-ratio = 0.0
> 
> [Permissions]
> chmod = 0644
> uid = -1
> gid = -1
> 
> [Metadata]
> relocate-moov = True
> full-path-guess = True
> tag = True
> tag-language = eng
> download-artwork = poster
> sanitize-disposition = 
> strip-metadata = False
> keep-titles = False
> 
> [Video]
> codec = h264, x264
> max-bitrate = 0
> bitrate-ratio = 
> crf = -1
> crf-profiles = 
> preset = 
> codec-parameters = 
> dynamic-parameters = False
> max-width = 0
> profile = 
> max-level = 0.0
> pix-fmt = yuv420p, yuvj420p
> prioritize-source-pix-fmt = False
> filter = 
> force-filter = False
> 
> [HDR]
> codec = 
> pix-fmt = 
> space = bt2020nc
> transfer = smpte2084
> primaries = bt2020
> preset = 
> codec-parameters = 
> filter = 
> force-filter = False
> profile = 
> 
> [Audio]
> codec = ac3
> languages = 
> default-language = 
> first-stream-of-language = False
> allow-language-relax = True
> channel-bitrate = 128
> variable-bitrate = 0
> max-bitrate = 0
> max-channels = 0
> filter = 
> profile = 
> force-filter = False
> sample-rates = 
> sample-format = 
> copy-original = False
> aac-adtstoasc = False
> ignored-dispositions = 
> unique-dispositions = False
> stream-codec-combinations = 
> relax-to-default = False
> force-default = False
> include-original-language = True
> 
> [Audio.Sorting]
> sorting = language, channels.d, map, d.comment
> default-sorting = channels.d, map, d.comment
> codecs = 
> 
> [Universal Audio]
> codec = aac
> channel-bitrate = 128
> variable-bitrate = 0
> first-stream-only = False
> filter = 
> profile = 
> force-filter = False
> 
> [Audio.ChannelFilters]
> 6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE
> 
> [Subtitle]
> codec = mov_text
> codec-image-based = 
> languages = 
> default-language = 
> first-stream-of-language = False
> encoding = 
> burn-subtitles = False
> burn-dispositions = 
> embed-subs = True
> embed-image-subs = False
> embed-only-internal-subs = False
> filename-dispositions = forced
> ignore-embedded-subs = False
> ignored-dispositions = 
> unique-dispositions = False
> attachment-codec = 
> remove-bitstream-subs = False
> force-default = False
> include-original-language = False
> 
> [Subtitle.Sorting]
> sorting = language, d.comment, d.default.d, d.forced.d
> codecs = 
> burn-sorting = language, d.comment, d.default.d, d.forced.d
> 
> [Subtitle.CleanIt]
> enabled = False
> config-path = 
> tags = 
> 
> [Subtitle.Subliminal]
> download-subs = False
> download-hearing-impaired-subs = False
> providers = 
> download-forced-subs = False
> include-hearing-impaired-subs = False
> 
> [Subtitle.Subliminal.Auth]
> opensubtitles = 
> tvsubtitles = 
> 
> [Sonarr]
> host = 127.0.0.1
> port = 8989
> apikey = 6c52a6f72bd94c378c985b24858f0cb0
> ssl = False
> webroot = /
> force-rename = False
> rescan = True
> block-reprocess = False
> 
> [Radarr]
> host = localhost
> port = 7878
> apikey = 
> ssl = False
> webroot = 
> force-rename = False
> rescan = True
> block-reprocess = False
> 
> [Sickbeard]
> host = localhost
> port = 8081
> ssl = False
> apikey = 
> webroot = 
> username = 
> password = 
> 
> [Sickrage]
> host = localhost
> port = 8081
> ssl = False
> apikey = 
> webroot = 
> username = 
> password = 
> 
> [SABNZBD]
> convert = True
> sickbeard-category = sickbeard
> sickrage-category = sickrage
> sonarr-category = sonarr
> radarr-category = radarr
> bypass-category = bypass
> output-directory = 
> path-mapping = 
> 
> [Deluge]
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = sonarr
> radarr-label = radarr
> bypass-label = bypass
> convert = True
> host = localhost
> port = 58846
> username = 
> password = 
> output-directory = 
> remove = False
> path-mapping = 
> 
> [qBittorrent]
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = sonarr
> radarr-label = radarr
> bypass-label = bypass
> convert = True
> action-before = 
> action-after = 
> host = localhost
> port = 8080
> ssl = False
> username = 
> password = 
> output-directory = 
> path-mapping = 
> 
> [uTorrent]
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = sonarr
> radarr-label = radarr
> bypass-label = bypass
> convert = True
> webui = False
> action-before = 
> action-after = 
> host = localhost
> ssl = False
> port = 8080
> username = 
> password = 
> output-directory = 
> path-mapping = 
> 
> [Plex]
> host = localhost
> port = 32400
> refresh = False
> token = 
> 
> [Subtitle.FFSubsync]
> enabled = False

**Comment by mdhiggins** [comment]
You need to do one of two things

If you don't want special treatment for HDR content, remove the 3 parameters that are used to identify content as HDR so that the general options are applied

```
[HDR]
codec =
pix-fmt =
space = 
transfer = 
primaries = 
preset =
codec-parameters =
filter =
force-filter = False
profile =
```

The space/transfer/primaries are the criteria used to determine if something qualifies as HDR, if it does, then all the options in the HDR section will override the default options

Alternatively, you can just mirror your settings in the HDR section for codec pix-fmt etc

**Comment by Junto026** [comment]
That's very helpful to understand.  However I just tried that and the file was still copied as-is rather than triggering a conversion.  I matched my HDR section to your example exactly.  I must be missing something else or doing something else wrong that's preventing a conversion to trigger for the test file.

Based on the ffprobe output and my autoProcess.ini, can you see any other reason my pix_fmt setting wouldn't trigger a conversion on this file?

**Comment by mdhiggins** [comment]
Post the logs of the conversion and I can see why

**Comment by Junto026** [comment]
> 2023-03-04 10:19:10 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
> 2023-03-04 10:19:10 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
> 2023-03-04 10:19:10 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
> 2023-03-04 10:19:10 - resources.mediaprocessor - INFO - Processing /tv/Love Island/Season 9/Love Island - S09E36.mp4.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Input Data
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - {
>     "format": "mov,mp4,m4a,3gp,3g2,mj2",
>     "format-fullname": "QuickTime / MOV",
>     "video": {
>         "index": 0,
>         "codec": "h264",
>         "bitrate": 2574958,
>         "pix_fmt": "yuv420p10le",
>         "profile": "high10",
>         "fps": 50.0,
>         "framedata": {
>             "pix_fmt": "yuv420p10le",
>             "color_space": "bt709",
>             "side_data_list": [
>                 {
>                     "side_data_type": "H.26[45] User Data Unregistered SEI message"
>                 }
>             ]
>         },
>         "dimensions": "1920x1080",
>         "level": 4.2,
>         "field_order": "progressive"
>     },
>     "audio": [
>         {
>             "index": 1,
>             "codec": "aac",
>             "bitrate": 256193,
>             "channels": 2,
>             "samplerate": 48000,
>             "language": "eng",
>             "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
>         }
>     ],
>     "subtitle": [],
>     "attachment": []
> }
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Reading video stream.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Video codec detected: h264.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p10le.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Profile: high10.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Video codec parameters None.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Creating h264 video stream from source stream 0.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Reading audio streams.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Audio detected for stream 1 - aac eng 2 channel.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Creating copy audio stream from source stream 1.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Final sorting:
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - ['0->0']
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Final sorting:
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - ['0->0']
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Default audio stream set to eng copy 2 channel stream [audio-default-sorting: ['channels.d', 'map', 'd.comment']].
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Reading subtitle streams.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Final sorting:
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - []
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Input and output extensions match and the file appears to have already been processed by SMA, enable force-convert to override [force-convert: False].
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Bypassing conversion and setting outputfile to inputfile.
> 2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Tagging /tv/Love Island/Season 9/Love Island - S09E36.mp4 with TMDB ID 66636.
> 2023-03-04 10:19:11 - resources.metadata - INFO - Tagging file: /tv/Love Island/Season 9/Love Island - S09E36.mp4.
> 2023-03-04 10:19:22 - resources.metadata - INFO - Trying to write tags.
> 2023-03-04 10:19:35 - resources.metadata - INFO - Tags written successfully using mutagen.
> 2023-03-04 10:19:35 - resources.mediaprocessor - INFO - Relocating MOOV atom to start of file.
> 2023-03-04 10:19:35 - qtfaststart - ERROR - This file appears to already be setup for streaming!
> 2023-03-04 10:19:35 - SonarrPostProcess - INFO - Sonarr response from RescanSeries command: ID 1035406 queued.
> 2023-03-04 10:19:45 - SonarrPostProcess - INFO - Rescan command completed.
> 2023-03-04 10:19:45 - SonarrPostProcess - INFO - Sonarr monitoring information updated for episode Episode 36.
> 2023-03-04 10:19:45 - SonarrPostProcess - INFO - Sonarr response RenameFiles command: ID 1035409 queued.
>

**Comment by mdhiggins** [comment]
There you go, the logs tell you why and give you instructions on how to not have this behavior

```
2023-03-04 10:19:11 - resources.mediaprocessor - INFO - Input and output extensions match and the file appears to have already been processed by SMA, enable force-convert to override [force-convert: False].
```

This is because your source file is already tagged as an SMA encode which can be seen on your FFPROBE output

```
encoder : SMA:Love.Island.S09E36.1080p.HEVC.x265-MeGusta
```

Always post the logs :)

**Comment by Junto026** [comment]
Lesson learned!

So to summarize: My configuration would trigger a conversion for a 10-bit depth video in most cases.  However, this is a special case where the video file was previously encoded using SMA, and in that scenario, the `pix-fmt` setting will not trigger a conversion.  The only way to trigger a conversion in this test scenario is using the `force-convert` setting.  Is that all correct?

**Comment by mdhiggins** [comment]
Correct, special case scenario where its essentially overriding everything since the file has been run through SMA already and its the same format
