### ISSUE TITLE
If used "output-directory = " to a different spot extracted subtitles doesnt get transfered back 

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1651]
In the "config.ini" under "[Converter]" "output-directory = ".
If i added a location for it to convert in, once it completes and move it back to the correct spot, It leaves the extracted subtitles behind in the output-directory location.

**Comment by mdhiggins** [comment]
Please include logs and use the issue template or its very difficult to assess your problem

**Comment by mdhiggins** [comment]
6abafed8c137631b68ed1f37e36e06b33210f7d7

Got lucky this time, see if that fixes it but in the future please include relevant info

**Comment by Whereamnow** [comment]
Another great work indeed. 
Question: since it is using one output folder and not creating subfolders. If Radarr and Sonarr both run at the sametime to recode would that mess it up?

**Comment by mdhiggins** [comment]
Shouldn't make a difference. It's not changing the folder or operating on any wildcards it's still referencing the specific files

**Comment by Whereamnow** [comment]
Just noticed that when subtitles are imported back it loses the "forced" and also adds the "1" and "2".

Before:
Chupa (2023) {imdb-tt14923260} [WEBDL-1080p][AC3 5.1][x264]-PEPE.en.forced.srt
Chupa (2023) {imdb-tt14923260} [WEBDL-1080p][AC3 5.1][x264]-PEPE.en.srt

After:
Chupa (2023) {imdb-tt14923260} [WEBDL-1080p][AC3 5.1][x264]-PEPE.1.en.srt
Chupa (2023) {imdb-tt14923260} [WEBDL-1080p][AC3 5.1][x264]-PEPE.2.en.srt

**Comment by Whereamnow** [comment]
Is there a way to add ".mvk.orginial" to the orginial file even when the converting "out-directory" is in a different folder? That way Plex Schedule wont scan the file while converting.
