### ISSUE TITLE
Skip files with certain condition

### ISSUE THREAD

**Issue by screamjojo** [mdhiggins/sickbeard_mp4_automator#1652]
Hello,

I've a lots of files and I would like to only convert if : 

- The title of the subtitle contains the string "force" and is not with disposition 'forced' 
- The subtitle is not SRT
- The audio is not AC3 or AAC.

In autoprocess I've try the parameter "bypass-if-copying-all" to true but I saw "Stream level metadata (titles, stream sorting, etc) will not be applied if this condition is met"

Have you a solution for me ?

Thanks in advance

**Comment by mdhiggins** [comment]
No way to write stream level metadata without at least remuxing the file

**Comment by screamjojo** [comment]
Yes I know, but is it possible to read the parameters of the file and only convert ie if my file don't have certain disposition ?

**Comment by mdhiggins** [comment]
Only solution for the disposition issue specifically is to use the custom functions feature

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions

The `validation` method would probably work for you to perform whatever custom logic you feel you need and then reject files that are already in the correct format

**Comment by screamjojo** [comment]
Yes I think so too.
Can you help me to write the code ?
Thanks in advance :)

**Comment by mdhiggins** [comment]
The whole point of custom functions is so that I don't have to write everyone's code for these more niche requests

Good news is everything you want to do regarding the dispositions the script already does

in mediaprocess.py the titleDispositionCheck function adjusts the disposition based on elements of the title

```py
    def titleDispositionCheck(self, info):
        DISPO_MAP = {
            'comment': 'comment',
            'hearing': 'hearing_impaired',
            'sdh': 'hearing_impaired',
            'visual': 'visual_impaired',
            'forced': 'forced'
        }

        for stream in info.streams:
            title = stream.metadata.get('title', '').lower()
            for k in DISPO_MAP:
                if k in title:
                    stream.disposition[DISPO_MAP[k]] = True
                    self.log.debug("Found %s in stream title, setting %s disposition to True." % (k, DISPO_MAP[k]))
```

You can tweak that to your liking, something like

```py
        for stream in info.streams:
            title = stream.metadata.get('title', '').lower()
            if "force" in title and not stream.disposition['forced']:
                  # do something
```


The other option is just to let it remux the files. Everything you want would be achieved by a remux with no quality loss it would just take a little time
