### ISSUE TITLE
converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg

### ISSUE THREAD

**Issue by screamjojo** [mdhiggins/sickbeard_mp4_automator#1653]
Hello,

Since the last docker update no conversion work

Radarr log : 

04/13/2023 21:08:00 - Error -   File "/usr/local/sma/postRadarr.py", line 196, in <module>
04/13/2023 21:08:00 - Error -     mp = MediaProcessor(settings)
04/13/2023 21:08:00 - Error -   File "/usr/local/sma/resources/mediaprocessor.py", line 43, in __init__
04/13/2023 21:08:00 - Error -     self.converter = Converter(settings.ffmpeg, settings.ffprobe)
04/13/2023 21:08:00 - Error -   File "/usr/local/sma/converter/__init__.py", line 26, in __init__
04/13/2023 21:08:00 - Error -     self.ffmpeg = FFMpeg(ffmpeg_path=ffmpeg_path,
04/13/2023 21:08:00 - Error -   File "/usr/local/sma/converter/ffmpeg.py", line 489, in __init__
04/13/2023 21:08:00 - Error -     raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
04/13/2023 21:08:00 - Error - converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg

Can you help me ?
Thanks in advance

**Comment by mdhiggins** [comment]
Try a fresh pull there was a bug I fixed this morning that was preventing FFMPEG from downloading

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/radarr-sma/issues/47

**Comment by screamjojo** [comment]
Thanks it works !
