### ISSUE TITLE
ASS subtitle to SRT

### ISSUE THREAD

**Issue by screamjojo** [mdhiggins/sickbeard_mp4_automator#1658]
Hi,

When i've file with ass subtitle the convertion in srt don't work, the srt subtitle isn't playing with VLC or Plex.
I read that we had to change the setting "Subtitle.CleanIt" in autoprocess.ini.
I did it but it works halfway, the subtitles are well converted to srt but the parameter "tag = default, no-style" doesn't seem to work because I still have the font characters...
But if I restart a second conversion with the subtitles already converted to srt the no-style works.

I've make a lot of test during hours, did I forget something ?

Thanks for your help

**Comment by mdhiggins** [comment]
Need logs

**Comment by screamjojo** [comment]
Ok so,

I've make again a lot of test and I noted : 

The ass subtitle without cleanit is good converted to srt but nothing appear with playing on VLC or Plex, BUT if I do an extract of the converted srt of the mkv, the file isn't empty and I see the characters with fonts style. If I play the file with VLC and with the external extracted SRT it works.

If I enable cleanit : The ass subtitle is good converted to srt and visible in VLC and Plex but the fonts style characters isn't delete. If I do an extract I see the same SRT file of the previously conversion without cleanit.

Here the log without cleanit : https://pastebin.com/g0MjeKmP
Here the log with cleanit : https://pastebin.com/rCtPbB3T

Here a sample of my test mkv file : https://1fichier.com/?j25s89nlhib6kb42k18q

Thanks for your help

**Comment by screamjojo** [comment]
Making others test and see : 

- Test with another mkv file = same problem
- With a "full" ass subtitle = work with VLC and Plex
- Opening the mkv with Windows 10 player : work with forced and full

With a full subtitle it works, so I really don't understand because the only difference with a "forced" subtitle is the number of characters (not based on the dispostion), the "ass" subtitle files seem to be the same if I do an extract ...

My other test file if you want : https://1fichier.com/?39iqfxm07obj879w0z3z

**Comment by mdhiggins** [comment]
I may have found the issue. It looks like I incorrectly thought CleanIt also supported ASS subtitles, and as a result when using embed subtitles I was keeping the ASS format for the temporary extraction but CleanIt wasn't actually doing anything, just pushed a small update that converts the files to SRT for extraction before CleanIt which seems to fix that issue

92d41decc30d701f5b5ef571289531cad9a8aecc

See if that helps

**Comment by screamjojo** [comment]
Thanks it works !

But I've a small skipstream code who don't work and I don't understund why : 

`    fra_srt_subtitle_streams = [s for s in info.subtitle if s.metadata.get('language', '') == 'fra' and 'forc' in stream.metadata.get('title', '') and (s.codec in ['srt', 'subrip'])]
    subtitle_not_srt_subrip = [s for s in info.subtitle if (s.metadata.get('language', '') == 'fra' and s.codec  not in ['srt', 'subrip']]
    if fra_srt_subtitle_streams:
        return subtitle_not_srt_subrip
    return False`

It's pretty simple, I would like to skip all the subtitles tracks except srt or subrip IF a track contain the fra_srt_subtitle_streams condition...

I've spent lot of times with many many test but nothing working ...

**Comment by mdhiggins** [comment]
Feel free to email me a sample file or 2 that would be applicable to this custom script as well as a clear explanation of what you're trying to create and I'll see if I can come up with a working one for you, but closing this issue out for now
