### ISSUE TITLE
Add option to offset audio tracks

### ISSUE THREAD

**Issue by nov1n** [mdhiggins/sickbeard_mp4_automator#1659]
**Is your feature request related to a problem? Please describe.**
I use Sonos speakers to watch movies on my TV and they have a 75ms sound delay.

**Describe the solution you'd like**
Add an option to offset audio streams. In `ffmpeg` this could look like:
`ffmpeg -i "movie.mp4" -itsoffset 0.075 -i "movie.mp4" -map 1:v -map 0:a -c copy "movie-video-delayed.mp4"`

**Describe alternatives you've considered**
I considered using a post-processing script, but having an option would make it easier to configure without knowledge of `ffmpeg`. Also doing it in a single pass would be significantly faster.

**Comment by mdhiggins** [comment]
This should already be doable using the preopts options

`preopts = -itsoffset, 0.075`

Don't forget the comma

**Comment by nov1n** [comment]
Brilliant, thanks!
