### ISSUE TITLE
Question - any ideas with this error?

### ISSUE THREAD

**Issue by milkywaychocolatebar** [mdhiggins/sickbeard_mp4_automator#1662]
Hi there,

Would just like to convert mkv to mp4 using this tool on Windows, no needing to connect to radarr/sonnar etc

Have the modules installed etc (I saw previous guides and questions about guessit - i have guessit<2 installed, from cmd been specifying the path with file name, with -a and also tried -I with id, just getting this error and does so repeatedly as if its trying to do something.

Attribute Error mode guessit has no attribute guessit line 175 in guest info guess=guessit.guessit(original or filename)

Any ideas please? Also Is it usually quite quick to convert?

Cheers

**Comment by mdhiggins** [comment]
You need the latest version of guessit, not <2

Your best bet is to just install using pip and the requirements.txt file which will get you all your dependencies in appropriate versions 

```
pip install --upgrade -r requirements.txt
```
