### ISSUE TITLE
cant get mp4 conversion working on qBitorrent from radarr....SABnzbd works ok

### ISSUE THREAD

**Issue by jahmac23** [mdhiggins/sickbeard_mp4_automator#1663]
Trying download on qbitorrent......torrents from radarr torrent indexer. Its is radarr managing and downloading via qbitorrent. sicbeard mp4 scripssetup all ok with qBitorrent log in info, radarr log in info and correct category. But keep getting this coversion error and conversion not happening. When I try same setup script file with SABnzbd all ok.

my qBitorrent rub external program command.....
/home/aaaa/scripts/sickbeard_mp4_automator-master_latest/qBittorrentPostProcess.py "%L" "%T" "%R" "%F" "%N" "%I"

As you suggested arguments.
 "
2023-07-19 22:06:09 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2023-07-19 22:06:09 - qBittorrentPostProcess - ERROR - Not enough command line parameters present, are you launching this from qBittorrent?
2023-07-19 22:06:09 - qBittorrentPostProcess - ERROR - #Args: %L %T %R %F %N %I Category, Tracker, RootPath, ContentPath , TorrentName, InfoHash
2023-07-19 22:06:09 - qBittorrentPostProcess - ERROR - Length was 6
2023-07-19 22:06:09 - qBittorrentPostProcess - ERROR - ['radarr', 'udp://tracker.tiny-vps.com:6969/announce', '/home/zzzzz/torrents/qbittorrent/downloads/hhhhhhh.2023.1080p.WEB.h264-EDITH.mkv', 'c621ce916f852a49d8c95dfdbcbeaaa31599f988']

Covnersion doesnt start and .mkv files moves to radarr setup location.

**Comment by mdhiggins** [comment]
Are you by chance running an old version of the script? This error only fires if the length is less than 6, which in your logs show is not the case

This was implemented in Dec 2022

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1633

**Comment by jahmac23** [comment]
yeah may be, Thanks for letting me know. I will try your latest version and will update you
    On Thursday, 27 July 2023 at 13:03:06 BST, Michael Higgins ***@***.***> wrote:  
 
 


Are you by chance running an old version of the script? This error only fires if the length is less than 6, which in your logs show is not the case

This was implemented in Dec 2022

#1633

**Comment by jahmac23** [comment]
Hi, Just want to ask you a quick issue. I am trying to by-pass some category name for sabnzbd as I need to setup custom rules for those category name. In yoru config autoProcess.ini file in [SABnzbd] setup.... how can I add multiple category name to by-pass. or in anyway I can add more category name which I have quite few custom category name for my RSS feeds on my Sabnzbd whcih I need to add yoru sickbeard mp4 automation.

[SABNZBD]convert = Truesickrage-category = sickrageradarr-category = moviessonarr-category = sonarrbypass-category = bypasscouchpotato-category = couchpotatosickbeard-category = sickbeardoutput_directory = output-directory = path-mapping = 
Here in bypass-category I need to add multiple category name but it seems only first category name "category1" works... I cant do like this...."bypass-category = category1, category2,category3".

Also separate query...in video codec can I add multiple video codec just to copy video and to convert audio only to make mp4 files.....like this. So whatever video codec it will just copy and convert .mkv files to .mp4 with audio aac/ac3.[Video]codec = h264, x264, h265, x265, hevc, av1
    On Thursday 3 August 2023 at 13:00:38 BST, Michael Higgins ***@***.***> wrote:  
 
 


Closed #1663 as completed.
