### ISSUE TITLE
Primary community support forum/discord/subreddit?

### ISSUE THREAD

**Issue by SenorSmartyPants** [mdhiggins/sickbeard_mp4_automator#1667]
I googled a bit but did not find out if there is a primary community support location. I see SMA questions spread out thru sonarr and sickbeard forums and other places, but if there is a primary place where most users gather I would like to know where that is for my support needs, and eventually to give back support.

Thanks.

**Comment by mdhiggins** [comment]
Pretty much just github

**Comment by SenorSmartyPants** [comment]
Ok. Any interest in enabling GH discussions? Or just make an issue? I don't quite have my thoughts together, but it might not really be an issue, just figuring out how to do certain things.

**Comment by mdhiggins** [comment]
Just open an issue if you have a question, its the easiest way for me to manage / respond
