### ISSUE TITLE
NZBGet instructions not up to date

### ISSUE THREAD

**Issue by russdog75** [mdhiggins/sickbeard_mp4_automator#1669]
Is it possible to use this script on nzbget version 21.0?  The set up instructions do not seem to align with its new script handling functions.

**Comment by mdhiggins** [comment]
I believe NZBGet is deprecated and no longer in development. Was there a new version somewhere or a fork?

**Comment by mdhiggins** [comment]
Looks like version 21 is the old version from 2 years ago so the current included script should be fine. What issue or concern do you have

**Comment by russdog75** [comment]
I ended up just opting for SABNZBD.  The script instructions for installing with NZBGET did not line up with the configuration settings on that version.
