### ISSUE TITLE
What are the options needed for windows hardware acceleration for 264 and 265 codecs ?

### ISSUE THREAD

**Issue by neilanthonystuckey** [mdhiggins/sickbeard_mp4_automator#1671]
**Is your feature request related to a problem? Please describe.**
Windows setup instructions for hardware acceleration

**Describe the solution you'd like**
Windows instructions for hardware acceleration

**Comment by mdhiggins** [comment]
Entirely depends on what kind of hardware you're using, the options are covered in the wiki and mirror the FFMPEG options and there's lots of closed issues for specific examples if you need some samples

**Comment by neilanthonystuckey** [comment]
Thanks for the fast response.  I have an intel i7 12th gen with integrated graphics.  I think i have this working.  My cpu dropped from 100% load when converting these movie files to about 16% and the GPU is being used by ffmpeg.exe now.  I was able to look at the ffmpeg cli options and figured it out i think. Just in case others are looking for this. Here are my settings not sure if this is optimal. 

autoProcess.ini

[Converter]
hwaccel-decoders = qsv
hwdevices = qsv

[Video]
codec = h264qsv, h264, x264, hevcqsv, h265, hevc

Side note the quality will be worse when using hardware accelerated encode/decode on video files.  I ended up going back to cpu encoding which takes forever but preserves most of the original quality.

**Comment by mdhiggins** [comment]
The quality should be relatively comparable as long as you dial in the settings correctly. There can be very subtle differences when you drill down to the pixel level but if it's grossly worse it might be a quality setting issue. Try encoding the same file with hardware and software  and see if the bitrates are grossly different on the output

**Comment by neilanthonystuckey** [comment]
I did a few tests. 

Bitrate and framerate are pretty close with and without hardware encoding checked with vlc media info.  Any idea which settings i could use to make the quality better with hardware encoding ? Files looks a little pixelated and washed out with hardware acceleration enabled. Its not that bad but noticeable. would i adjust the crf value ?
