### ISSUE TITLE
Unable to open URL

### ISSUE THREAD

**Issue by nogardvfx** [mdhiggins/sickbeard_mp4_automator#1673]
**Describe the bug**
After a TV show is ocnverted and the info is passed back to Sickgear, it gets a system exit.  Looking at SabNZBD's log is says it cannot open the URL back to Sickgear,

**Command or context you are trying to run**
Auto conversion within SabNZBD.  Attaching log from SabNZBD.
[sabLog.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12485552/sabLog.txt)

**autoProcess.ini settings**
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12485582/autoProcess.txt)

**Log files**
[smaLog.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12485720/smaLog.txt)

**FFMpeg headers**
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder

**System Information**
 - OS: Ubuntu 20.04.6 LTS x86_64
 - Python version: Python 3.8.10

**Expected behavior**
After the MKV file is processed to an MP4, I was expecting the file to communicate with Sickgear and move the file to the process location on my server.

**Additional context**
I have an older version of the software from several years back that seems to work fine, but does not convert HDR files properly.  The HDR conversion works perfectly now.  Thank you so much for this.  It has been a standard staple on my server for years.

**Comment by nogardvfx** [comment]
I will try Sickrage again.  Was having an issue with it earlier not converting any of the files and not copying it over.  I got further with Sickbeard and didn't go back.  End result may need to be that I switch back to either Sickbeard or Sickrage.  Will update over the weekend.

**Comment by mdhiggins** [comment]
I fixed the bug you were having with SR so hopefully it should work

**Comment by nogardvfx** [comment]
That did it!  Amazing!  Thank you.
