### ISSUE TITLE
Radarr files not converting, using wrong folder

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1675]
I can't work this one out, for some reason whenever I try and have a file converted for Radarr its trying to make a temp file in C:\Windows so ends up failing Sonarr works files work fine, and by the looks of it its just via qbittorent

[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12659219/sma.log)

**Comment by mdhiggins** [comment]
PermissionError: [WinError 5] Access is denied

Nothing to figure out, its a permission error

No idea why you'd be using C:\Windows as your output directory but there you go, either change your output directory of change your permissions

**Comment by morpheus2n2** [comment]
There is no output directory listed in the .ini, cos if that was the case then anything tag for sonarr would do the same, if you look at the log, the sonarr conversion worked fine (Bigsky) but the radarr one did not (All star superman)

**Comment by morpheus2n2** [comment]
[Converter]
ffmpeg = D:\PlexBackend\FFmpeg\bin\ffmpeg.exe
ffprobe = D:\PlexBackend\FFmpeg\bin\ffprobe.exe
threads = 0
hwaccels = cuda, dxva2, qsv, d3d11va, opencl, vulkan, h265_nvenc
hwaccel-decoders = 
hwdevices = 
hwaccel-output-format = 
output-directory = 
output-directory-space-ratio = 0.0
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = \\Plex\To Sort
delete-original = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = True
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = False
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = True
keep-titles = False

[Video]
codec = h265_nvenc
max-bitrate = 2500
bitrate-ratio = hevc:0.8
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 5.2
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = aac, aac
languages = jpn, eng
default-language = eng
include-original-language = True
first-stream-of-language = False
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
aac-adtstoasc = False
ignored-dispositions = 
force-default = False
unique-dispositions = False
stream-codec-combinations = 

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
include-original-language = False
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = Forced
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
force-default = False
unique-dispositions = False
attachment-codec = 
remove-bitstream-subs = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
burn-sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = default, no-style

[Subtitle.FFSubsync]
enabled = False

[Subtitle.Subliminal]
download-subs = False
download-forced-subs = False
include-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Sonarr]
host = 192.168.1.192
port = 8989
apikey = 5ee115a0e19e40f799228c008c544204
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Radarr]
host = 192.168.1.192
port = 38084
apikey = 9dae3f8534b7485fb549b9f77bb6a85a
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = 192.168.1.2
port = 38090
ssl = False
username = Morpheus2n2
password = Oliver150107!
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
username = 
password = 
servername = 
ssl = True
ignore-certs = False
path-mapping =

**Comment by morpheus2n2** [comment]
Ok, Debug all set so should kick off when next file hits in a bit :D 
Thats what I cant work out the Root folders have always been the same for all my clients for years, its only been happening for last 2 weeks when I pulled a new download of the script lol

**Comment by morpheus2n2** [comment]
Ok debug log here, SABNZbd works file with Radarr tags, qbittorrent doesn't lol
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12659901/sma.log)

**Comment by mdhiggins** [comment]
QBT is reporting your root path as "."

No idea why but that's the issue

Are your command line parameters set correctly?

**Comment by morpheus2n2** [comment]
<img width="2048" alt="2023-09-19 (5)" src="https://github.com/mdhiggins/sickbeard_mp4_automator/assets/14253602/2f96f6ce-e675-4cf8-ad2c-fe2d58189320">

**Comment by mdhiggins** [comment]
Hm was there an update that broke something to QBT? It shouldn't be returning a . for your root path. That's causing the problem though

**Comment by mdhiggins** [comment]
a2ea0e4c55cd3051a3814bb29a73b8e8f24643c9

See if that works around it

**Comment by morpheus2n2** [comment]
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12670818/sma.log)

Still doing it unfortunately, its so odd as its only Films this happens to.

**Comment by mdhiggins** [comment]
9e3541e790a65e6cf50cfa6de3386b12e1b1d10a

Try that

**Comment by morpheus2n2** [comment]
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12671165/sma.log)

Yep that seems have done the trick, its in progress right now, will keep eye on it over next couple of days before closing this thread :D 

Thank you so so much.

**Comment by morpheus2n2** [comment]
Ok that failed but it was a different issue which I have identified and fixed.
It seems FFMPEG 6.0 doesn't like HW Decoding and encoding, took it back down to 5.0 and its working like a dream again
