### ISSUE TITLE
Permission Issue After Windows Update

### ISSUE THREAD

**Issue by Dead-Rekon** [mdhiggins/sickbeard_mp4_automator#1677]
**Describe the bug**
It's been a while since I've done any converting, but after the most recent Windows 10 update it seems I have a permission issue going on. Where the manual converter worked fine, it now closes right after starting

**Command or context you are trying to run**
Default manual.py

**autoProcess.ini settings**
[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12710687/autoProcess.ini.txt)

**Log files**
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12710682/sma.log)

**FFMpeg headers**
![Headers](https://github.com/mdhiggins/sickbeard_mp4_automator/assets/60633931/1a2c2f7f-4afe-4a1f-b664-7e54496ed5c2)

**System Information**
 - OS: Windows 10
 - Python version: 3.0.1
 - Docker config (if relevant): Not relevant

**Expected behavior**
Simply convert the MP4 files to MKV as normal with the specified settings.

**Additional context**
Nothing has changed other than a recent windows update that I'm aware of. I wanted to check to see if it was something simple before starting from scratch again.

**Comment by mdhiggins** [comment]
Yeah python is throwing a permission error when trying to open FFMPEG, access is denied. Can't help you much more than that, you'll need to adjust your FFMPEG permissions (maybe move it out of the root of your C:\ drive which can sometimes require elevated privileges?)

**Comment by Dead-Rekon** [comment]
Ok. Looks like I'll have to start from scratch and see if I can figure it out. Thanks for the help.

**Comment by Dead-Rekon** [comment]
I've tried all of that to no avail unfortunately. Trying several locations all with new environment variables still results in only being able to run FFMPEG directly. I at least know where to look now though if a complete reinstall doesn't work.

**Comment by mdhiggins** [comment]
The command specifically that's failing is `ffmpeg -hide_banner -pix_fmts`

Might be worth trying that manually just to see if there's some weird problem with that command not working for some reason
