### ISSUE TITLE
Duplicated audio

### ISSUE THREAD

**Issue by andrerxavier** [mdhiggins/sickbeard_mp4_automator#1679]
**Describe the bug**
I'm using Automator and the transcoding occurs but ends up duplicating the audio, my interest is to keep one audio in pt-br and the second original, I've changed the settings in several ways, but the audio is always duplicated. The same goes for subtitles.

**autoProcess.ini settings**
[autoprocess.ini](https://pastebin.com/aXaRx0Pm)

**Log files**
[sma.log](https://pastebin.com/SNgQyF7R)
[mediainfo - movie](https://pastebin.com/XxNPGjHx)

**FFMpeg headers**
`fmpeg version N-112163-g5d98259841 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
`

**System Information**
 - OS: Ubuntu 20.04.6 LTS
 -  Python 3.8.10

**Expected behavior**

**Additional context**

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
You just need to disable universal audio which is designed to create these duplicate tracks

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/AutoProcess-Settings#universal-audio

> Approved audio codecs. Codecs not on this list are converted to the  first codec on the list. **Leave blank to disable universal audio**

**Comment by andrerxavier** [comment]
Thank You @mdhiggins
