### ISSUE TITLE
Stream title metadata field is lower cased

### ISSUE THREAD

**Issue by SenorSmartyPants** [mdhiggins/sickbeard_mp4_automator#1680]
I'm trying to write a custom function to pass thru subtitle stream titles from the source. I can copy them but they have been lower cased by the time I have access to them. I think it's happening here:

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/9e3541e790a65e6cf50cfa6de3386b12e1b1d10a/converter/ffmpeg.py#L255-L258

This is my custom function so far.

```python
def streamTitle(mp, stream, options, hdr=False, imageBased=False, path=None, tagdata=None):
    if stream.type == "subtitle":
        return stream.metadata.get('title','') 
    return None
```

So `Spanish (Latin America)` turns in to `spanish (latin america)`

**Comment by SenorSmartyPants** [comment]
This also happens without a custom function when `keep-titles = True`

**Comment by mdhiggins** [comment]
01b8d5bdc259af0faf9fb2c4cc8dbf5fe6bdfec3

See if that fixes

**Comment by SenorSmartyPants** [comment]
Fixed!
