### ISSUE TITLE
re-encode if over certain size

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#169]
Sometimes even 720P videos come down as an MKV that may be over 8GB. Is there a way or can it be incorporated to check the video stream and if over a certain size to re-encode instead of just copy?

Thanks...

**Comment by Trixter69** [comment]
I'd love to see this implemented. I've never messed with ffmpeg so im not sure how to program this but maybe something like the following would work?
i = (current video bitrate)
if i > x
then video_bitrate = y
else video_bitrate = i

**Comment by mdhiggins** [comment]
Video bitrate option was added recently, check the readme for updates

**Comment by hroman73** [comment]
Awesome! Thank you!
