### ISSUE TITLE
What is "SMA"? Why is the the "Encoding Tool" tag listed as "SMA" in all my processed video files?

### ISSUE THREAD

**Issue by cryo-kronos** [mdhiggins/sickbeard_mp4_automator#1690]
Nevermind. I figured it out. I don't know when this abbreviation got added to the scripts.

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/commit/f0fc3ac3f86a5768fbdf119bbfe4345e24490827

2020

This is written so that the script can see if its processed the file already and minimize recreating duplicate audio tracks in certain scenarios (like universal audio or copy-original)
