### ISSUE TITLE
File deleting immediately

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#1691]
**Describe the bug**
Script seems to be deleting file? Any idea where the error is happening I can't seem to find it

<img width="792" alt="image" src="https://github.com/mdhiggins/sickbeard_mp4_automator/assets/23133649/426f953b-19ba-4d5e-b1e2-a95e13550f06">

[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 
hwaccels = vaapi
hwaccel-decoders = vaapi
hwdevices = /dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mkv
output-extension = mkv
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = True
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]
output-directory-space-ratio = 0.0

[Permissions]
chmod = 0666
uid = -1
gid = -1

[Metadata]
relocate-moov = False
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = copy
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3
languages = 
default-language = eng
first-stream-of-language = False
allow-language-relax = True
relax-to-default = False
channel-bitrate = 80
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = True
aac-adtstoasc = False
ignored-dispositions = 
force-default = False
unique-dispositions = False
stream-codec-combinations = 
include-original-language = True

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = language, channels.d, map, d.comment
codecs = aac, ac3, dts, truehd

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = true
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]

[Subtitle]
codec = srt
codec-image-based = copy
languages = 
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = True
embed-only-internal-subs = True
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
force-default = False
unique-dispositions = False
attachment-codec = 
remove-bitstream-subs = False
include-original-language = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
burn-sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.Subliminal]
download-subs = False
download-hearing-impaired-subs = False
providers = 
download-forced-subs = False
include-hearing-impaired-subs = False

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
username = 
password = 
servername = 
ssl = True
ignore-certs = False
path-mapping = 

[Subtitle.FFSubsync]
enabled = False

**Comment by mdhiggins** [comment]
Your config file is invalid, set threads to `0`, it needs to be an integer

**Comment by mdhiggins** [comment]
Also it looks like you're using some kind of wrapper script for SMA that might be doing the deleting, that log message does not appear to be coming from SMA

**Comment by justinglock40** [comment]
🤦🏾‍♂️ thank you!Sent from my iPhoneOn Dec 19, 2023, at 09:15, Michael Higgins ***@***.***> wrote:﻿
Your config file is invalid, set threads to 0, it needs to be an integer

**Comment by justinglock40** [comment]
Ok I’ll check with the dev of that script. Thanks again!Sent from my iPhoneOn Dec 19, 2023, at 09:15, Michael Higgins ***@***.***> wrote:﻿
Also it looks like you're using some kind of wrapper script for SMA that might be doing the deleting, that log message does not appear to be coming from SMA
