### ISSUE TITLE
Language flow

### ISSUE THREAD

**Issue by ClankJake** [mdhiggins/sickbeard_mp4_automator#1693]
Testing the first-stream-of-language option here, when it is marked as true, if the file has a forced subtitle, the script only takes that subtitle and ignores the full version of the subtitle. Is there any way, if you have this forced subtitle, to automatically get it and get the first complete subtitle in the file?

**Comment by mdhiggins** [comment]
45b0345f0528ebf9a02032340fb0badeda873b87

This should exempt forced subtitles from that exclusion

**Comment by ClankJake** [comment]
Thanks for including. But you're still having trouble making a copy of the Codec, it still only keeps the forced one.

**Comment by mdhiggins** [comment]
c6a3d4836c7d23d3510f3bfd873c1456d59388e3

Try that, it was working in certain input orders but not others, this should fix it for all scenarios
