### ISSUE TITLE
Invalid format string in avcodecs.py NVEncH265Codec

### ISSUE THREAD

**Issue by DrEsteban** [mdhiggins/sickbeard_mp4_automator#1698]
I think there's an extra `%s` here. It's causing Python format string "not enough args" errors.

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/50548e41ef237041eea04557b3f029e5474f7709/converter/avcodecs.py#L1709C37-L1709C37

**Comment by mdhiggins** [comment]
cde16c973f86a6d25e748c7bc06c7b35ca8bbd94

You are correct, that should fix it

**Comment by DrEsteban** [comment]
@mdhiggins this issue is actually in 4 places. If you just search `avcodecs.py` for `%s=%s=`, you should find the remaining 3.

**Comment by mdhiggins** [comment]
472e525a60a92eeda7f8ff3c906bef2684238bb1

Fixes it in the other 3 locations
