### ISSUE TITLE
Problem embedding external subtitles

### ISSUE THREAD

**Issue by ClankJake** [mdhiggins/sickbeard_mp4_automator#1704]
**Describe the bug**
I noticed when you embed the subtitles in the media, it doesn't respect the codecs that were added to the list. For example, if there is a codec line: srt, ass and the external subtitle is an ass, it will convert to the first codec in the list in this case, srt. Is there a way to fix this, I really like your script.

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
Are you using cleanit? It should copy if its on the list but cleanit requires it to be extracted and then re-merged back in, in which case the formats change cause it has to extracted to SRT
