### ISSUE TITLE
Not Processing files running in Manual Mode

### ISSUE THREAD

**Issue by Weezzel** [mdhiggins/sickbeard_mp4_automator#1709]
**Describe the bug**

[format @ 000001a9712c1400] Setting 'pix_fmts' to value 'yuv420p|nv12|p010le|yuv444p|p016le|yuv444p16le|bgr0|bgra|rgb0|rgba|x2rgb10le|x2bgr10le|gbrp|gbrp16le|cuda|d3d11'
[auto_scale_0 @ 000001a9712c0e00] w:iw h:ih flags:'' interl:0
[Parsed_format_0 @ 000001a9712c0800] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_format_0'
[auto_scale_1 @ 000001a9712c0a00] w:iw h:ih flags:'' interl:0
[Parsed_hwdownload_1 @ 000001a9712c1200] auto-inserting filter 'auto_scale_1' between the filter 'Parsed_format_0' and the filter 'Parsed_hwdownload_1'
Impossible to convert between the formats supported by the filter 'Parsed_format_0' and the filter 'auto_scale_1'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
[AVIOContext @ 000001a970cbcf80] Statistics: 0 bytes written, 0 seeks, 0 writeouts
Terminating demuxer thread 0
[AVIOContext @ 000001a96eabe5c0] Statistics: 99117 bytes read, 2 seeks
Conversion failed!

**autoProcess.ini settings**

[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/15017863/autoProcess.ini.txt)

[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
hwaccels = cuda,nvenc, cuvid, dxva2,d3d11va,vaapi
hwaccel-decoders = hevc_cuda,hevc_cuvid,hevc_nvenc,nvdec,h265_cuvid,h264_cuvid,mjpeg_cuvid,mpeg1_cuvid,mpeg2_cuvid,mpeg4_cuvid,vc1_cuvid,hevc_vaapi
hwdevices =
hwaccel-output-format =
output-directory = 
output-directory-space-ratio = 0.0
output-format = mp4
output-extension = mp4
temp-extension = TRANSCODING
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = True
opts-separator = ,
preopts = -loglevel,debug,-probesize,1000000,-analyzeduration,10000000
postopts = -max_muxing_queue_size, 9999
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = False
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = hevc_nvenc,hevc
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 0:23:4.5M:12M,4100:21:8M:24M,8000:17:10M:30M
preset = 
codec-parameters = 
dynamic-parameters = True
max-width = 0
profile = Main10
max-level = 0.0
pix-fmt = p010le,nv12
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = hevc,h265
pix-fmt = yuv420p10le
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3,eac3,aac
languages = eng
default-language = eng
include-original-language = True
first-stream-of-language = False
channel-bitrate = 0
variable-bitrate = 0
max-bitrate = 0
max-channels = 6
filter = volume=1.5
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
aac-adtstoasc = False
ignored-dispositions = commentary
force-default = False
unique-dispositions = False
stream-codec-combinations = 
ignore-truehd = True

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = 
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
filter = volume=1.5
profile = 
force-filter = False

[Audio.ChannelFilters]

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
include-original-language = False
first-stream-of-language = True
encoding = 
burn-subtitles = False
burn-dispositions = Froced
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = True
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
force-default = False
unique-dispositions = True
attachment-codec = 
remove-bitstream-subs = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
burn-sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.FFSubsync]
enabled = False

[Subtitle.Subliminal]
download-subs = False
download-forced-subs = True
include-hearing-impaired-subs = True
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
in-progress-check = True
block-reprocess = False

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
in-progress-check = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
username = 
password = 
servername = 
host = localhost
port = 32400
refresh = False
token = 
ssl = True
ignore-certs = False
path-mapping = 

**Log files**

[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/15017853/sma.log)

**FFMpeg headers**

C:\Windows\System32>ffmpeg
ffmpeg version n6.0-26-g3f345ebf21-20230630 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --disable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230630
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**System Information**

 - OS: Windows 11
 - Python version 3.11

**Comment by mdhiggins** [comment]
Appears your logs are missing quite a bit including the actual FFMPEG command

**Comment by Weezzel** [comment]
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/15018319/sma.log)


2024-04-17 19:04:41 - MANUAL - INFO - C:\FFmpeg\ffmpeg.exe -fix_sub_duration -hwaccel cuda -vcodec h264_cuvid -loglevel debug -probesize 1000000 -analyzeduration 10000000 -i "\\GAMMA\Plex Media\TV\Body Cam (2018) {imdb-tt9425082}\Season 08\Body Cam (2018) - S08E08 - He Shot Me! [1080p web WEB H264 WEBDL-1080p][AAC 2.0][h264]-EDITH.mkv" -vcodec hevc_nvenc -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -profile:v main10 -tag:v hvc1 -qp 17 -maxrate:v 10m -bufsize 30m -vf format=p010le,hwdownload -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:2 -metadata:s:s:0 "title=Hearing Impaired" -metadata:s:s:0 "handler_name=Hearing Impaired" -metadata:s:s:0 language=eng -disposition:s:0 -default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -max_muxing_queue_size 9999 -y "\\GAMMA\Plex Media\TV\Body Cam (2018) {imdb-tt9425082}\Season 08\Body Cam (2018) - S08E08 - He Shot Me! [1080p web WEB H264 WEBDL-1080p][AAC 2.0][h264]-EDITH.transcoding"
2024-04-17 19:04:41 - MANUAL - INFO - ======================
2024-04-17 19:04:41 - MANUAL - ERROR - Error converting file, FFMPEG error.

**Comment by mdhiggins** [comment]
Seems like your hardware encoder nvenc doesn't like your pix fmt

Probably need to mess around with which one you're choosing but that's the issue, it's more of an FFMPEG issue

**Comment by Weezzel** [comment]
So I did some more testing. This has been working for the last 3 years or so. Nothing has changed on this PC much outside of windows 111 updates. I did run a Git Pull on my MP4 Automator directory and it updated several files, I am assuming that that directory was out of date a lot.

When I remove the HEVC_NVenc from the Video section the episode transcode fine using CPU. As you see here.
![image](https://github.com/mdhiggins/sickbeard_mp4_automator/assets/67742562/750b9a8f-d63c-4b38-b782-65ad9579c0c0)

But when I add it back it fails. Now this is the standard 1080p section 
![image](https://github.com/mdhiggins/sickbeard_mp4_automator/assets/67742562/0bb4af89-c9aa-488b-aa7f-d286c500e61a)

The HDR section works fine as well, so it is something from the Pulled updates that doesn't like my settings now. Using the CPU is fine as I have a AMD R9 5950X 16 cores, but I would like to make use again of the RTX 3080 speeds. Library is pushing 120TB in size with new additions all the time on the server.

Any Ideas on what would of made these setting stop working over the last few updates?

**Comment by mdhiggins** [comment]
As above, I believe this is likely an issue with your selected pix-fmt related to NVENC, only certain pix-fmt's are allowed for that encoders and it will vary depending on whether you're moving between hardware/software

Try leaving pix-fmt blank and set prioritize-source-pix-fmt to false which should left FFMPEG auto select and see if that helps

**Comment by Weezzel** [comment]
Wow fast response, Ok will try that.

**Comment by Weezzel** [comment]
SNAP, You Are a wizard. Working again.
![image](https://github.com/mdhiggins/sickbeard_mp4_automator/assets/67742562/cada3615-451b-4511-9c57-41656aecd5c5)

**Comment by Weezzel** [comment]
Thank you for your expertise. Much appreciated.

**Comment by mdhiggins** [comment]
Good stuff, just check the output pix-fmt from the file created and make sure its something appropriate, similarly you might need to clear your hdr pix-fmt to let the same auto select approach work when processing hdr content
