### ISSUE TITLE
Skip Encoding?

### ISSUE THREAD

**Issue by Kieranwest** [mdhiggins/sickbeard_mp4_automator#1719]
I could never get NVENC to work with arr-SMA so I'm planning on moving over to unmanic. I have the Nvenc working there, I'm now just attempting to metadata tag the media without having SMA encoding. The only method I've been able to use is having unmanic export as MKV and SMA transcode to MP4, this atleast makes the process lighter but ideally I'd like to skip encoding entirely. 
Is this possible?

**Comment by mdhiggins** [comment]
The process same extensions option set to false will block encoding but should still allow tagging as long as the input and output extensions are the same
