### ISSUE TITLE
Question on HEVC bypass

### ISSUE THREAD

**Issue by Hello-World-Traveler** [mdhiggins/sickbeard_mp4_automator#1722]
Without editing the python files How could I allow bypassing on converting anything that's already in HEVC?  My aim is too bypass HEVC video but not the audio. As you can see I have tried getting around this.

Video: AVC -> HEVC = Yes
Video HEVC -> HEVC = audio only

As you can see I have tried getting around this.

```
[Video]
codec = h265vaapi, hevc
video-codec-fallback = hevc
conditional_copy = yes  # Enable conditional copying
conditional_copy_format = hevc  # Only copy if the format is HEVC
conditional_copy_streams = v  # Only copy the video stream
copy_hdr_metadata = yes
max-bitrate = 0
bitrate-ratio = 0.5
max-width = 0
preopts = 
crf = -0
preset = medium
codec-parameters =
dynamic-parameters = True
profile = main
max-level = 5.0
pix-fmt = nv12, p010le
prioritize-source-pix-fmt = True
filter = 
force-filter = False
crf-profiles = 
x265-params = no-info=1
```
The option I am looking for would be 
`HEVC bypass = `
If this can be done maybe it's a good idea to add others?
`AV1 bypass = `
`AVC bypass = `

Follow up question, if h265vaapi fails to work (sometimes it does) can a fallback formate be selected? I know this can be done if not using hwdevices.

**Comment by mdhiggins** [comment]
The entire point of this script is to remux wherever possible which is essentially what you're requesting. Remuxing a stream copies it without any conversion. As long as your source material meets the criteria in your autoProcess.ini it will always remux and only convert if there's a reason to do so

My guess looking at your configuration is maybe due to you only having 2 pix-fmt options on your allowed list. The script output tells you why it failed the remux check and had to convert just look at the "debug" line in the json output for the stream

**Comment by Hello-World-Traveler** [comment]
> maybe due to you only having 2 pix-fmt options

I have tried to use others, however this always fails for h265vaapi. I think it only really supports nv12 ( when searching for answers, the top answer is to use -vf 'format=nv12,hwupload' and the script already does)

I understand how the script works. I believe that you're correct with the pix-fmt. I will try and retest with `yuv420p and yuv420p10le` maybe I missed something awhile ago.

**Comment by mdhiggins** [comment]
You don't need to remove nv12 you just need to add the other formats later in the list. You can still keep nv12 first

**Comment by Hello-World-Traveler** [comment]
From what I know about the script, if an option isn't listed it will choose the first option on the list.

I did some testing and found this to work, I think the issue I had was radarr and sonarr, I am yet to retest them.

```
codec = h265vaapi, hevc
max-bitrate = 0
bitrate-ratio = 0.5
max-width = 0
preopts =
crf = -0
preset = ultrafast
codec-parameters = 
dynamic-parameters = True
profile = main10
max-level = 5.0
pix-fmt = p010le, yuv420p10le, yuv420p
prioritize-source-pix-fmt = False
filter = 
force-filter = False
crf-profiles =
x265-params = no-info=1
```
Testing the script with HEVC main -> HEVC main10 (set as profile) causes error 
```
Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Function not implemented
```
Everything works until there is a HEVC file that's profile is main. 

Is there an option to bypass this or do I need to look at building a new server without using VAAPI?

**Comment by mdhiggins** [comment]
This is just an error with your hardware encoder not liking one of your settings

I can't debug what FFMPEG command you should be using as this can be very hardware specific, but you can create an FFMPEG command that works for you and then post your full log output from SMA I can tell you what options to adjust to mirror your desired output if possible

**Comment by Hello-World-Traveler** [comment]
```
Driver does not advertise encoder features, using guessed defaults.
Driver does not advertise encoder block size, using guessed defaults.
 No quality level set; using default (25).
```
From
```
"video": {
 "index": 0,
 "codec": "hevc",
 "bitrate": 5336565,
 "pix_fmt": "yuv420p10le",
 "profile": "main10",

```
To

```
"format": "mkv",
"video": {
"codec": "h265vaapi",
"map": 0,
"bitrate": 5154.686699999999,
"level": 5.0,
"profile": "main",
"pix_fmt": "nv12",: [
```

The main error is that iGPU doesn't have good support for HEVC to HEVC., this is why I wanted to skip anything in HEVC. 

If the profile setting is different ( main or main10)  it will redo the HEVC video when it's  not necessary. HEVC videos are already smaller (25 to 50% less in size then AVC).

**Comment by mdhiggins** [comment]
The profile options work the same way as the pix-fmt options, you can just add 'main' to your list of approved profiles to avoid transcoding

```ini
[Video]
profile = main10, main
```

**Comment by Hello-World-Traveler** [comment]
That's good to know!

Would a video codec fallback work if the first option fails? `codec = h265vaapi, hevc`

**Comment by mdhiggins** [comment]
No, it does not recover to alternate video codecs/run down the list when one fails
Gotta get your settings correct so its not failing, failures should not be commonplace

**Comment by Hello-World-Traveler** [comment]
```
stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_vaapi))
No usable encoding profile found.
 Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
```
Removed pix-fmt  then  profile =` main10, main,` working again. I think your suggestion broke it.

**Comment by mdhiggins** [comment]
I mean this is going from h264 to h265 so my suggestion wasn't relevant specifically to that. Posting the full logs would probably help

**Comment by Hello-World-Traveler** [comment]
I no longer have the logs.

 h264 to h265 no error
 h265 to h265 error

It's when a video is h265 main10 with the profile settings being main. I think the igpu doesn't support someone of the pix formats. nv12 works for profile main and I think p010le works for main10.

Leave pix-fmt blank?

**Comment by Hello-World-Traveler** [comment]
I think to best use the script, an upgrade is needed from QSV.

How could I have the script create srt subtitles from ass subs and keep both? 

```
[Subtitle]
codec = srt, ass
subtitle-formats  or subtitle-language-map= ass:srt
```

**Comment by mdhiggins** [comment]
If you want it to convert just take ass off the allowed list. If you want to keep leave ass on the list. Can't have it both ways though

**Comment by Hello-World-Traveler** [comment]
Got it. No option to use srt subtitles as a fallback in-case devices/media players don't support.

Thank you.
