### ISSUE TITLE
Embed external audio

### ISSUE THREAD

**Issue by Skyline404** [mdhiggins/sickbeard_mp4_automator#1723]
Can this script find and external audio (ex mka, m4a, ac3) and embed them?

**Comment by mdhiggins** [comment]
It does not. Only external subtitles

**Comment by mdhiggins** [comment]
Unlikely, it would be a pretty major undertaking. I'm open to a pull request but not something that would see a lot of use and would take quite a bit of time to incorporate. The way subtitles are handled would be a good starting point if you were interested
