### ISSUE TITLE
Support for specifying the number of audio tracks in output

### ISSUE THREAD

**Issue by Daikamar** [mdhiggins/sickbeard_mp4_automator#183]
So the Amazon Fire Stick only supports 5.1 audio in Plex within an MP4 container with a single AC3 audio track. Is it possible to get support for specifying the number of audio tracks we'd like in the output file? Many of my sources are mkv's with a 5.1 AC3 and a 2 channel AAC track. In those cases, I'd just like to keep the AC3 track in the output.

**Comment by mdhiggins** [comment]
Gonna go ahead and close this for now since there's no active issue. Glad everything is working for you.
