### ISSUE TITLE
Subliminal installation

### ISSUE THREAD

**Issue by cod3fr3ak** [mdhiggins/sickbeard_mp4_automator#186]
Here is what I've done:

[root@processor subliminal]# pwd
/opt/sickbeard_mp4_automator-master/setup/subliminal

[root@processor subliminal]# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to subliminal.egg-info/requires.txt
writing subliminal.egg-info/PKG-INFO
writing top-level names to subliminal.egg-info/top_level.txt
writing dependency_links to subliminal.egg-info/dependency_links.txt
writing entry points to subliminal.egg-info/entry_points.txt
reading manifest file 'subliminal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'subliminal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/subliminal
creating build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/addic7ed.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/tvsubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/podnapisi.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/score.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/video.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/cache.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/exceptions.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/api.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/cli.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/compat.py -> build/bdist.linux-x86_64/egg/subliminal
creating build/bdist.linux-x86_64/egg/subliminal/tests
copying build/lib/subliminal/tests/test_providers.py -> build/bdist.linux-x86_64/egg/subliminal/tests
copying build/lib/subliminal/tests/common.py -> build/bdist.linux-x86_64/egg/subliminal/tests
copying build/lib/subliminal/tests/test_subliminal.py -> build/bdist.linux-x86_64/egg/subliminal/tests
copying build/lib/subliminal/tests/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/tests
copying build/lib/subliminal/__init__.py -> build/bdist.linux-x86_64/egg/subliminal
creating build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/addic7ed.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/thesubdb.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/tvsubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/podnapisi.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/opensubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/subtitle.py -> build/bdist.linux-x86_64/egg/subliminal
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/addic7ed.py to addic7ed.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/tvsubtitles.py to tvsubtitles.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/converters/tvsubtitles.py', 11, 39, '        self.to_tvsubtitles = {v: k for k, v in self.from_tvsubtitles}\n'))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/podnapisi.py to podnapisi.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/converters/podnapisi.py', 17, 37, '        self.to_podnapisi = {v: k for k, v in self.from_podnapisi.items()}\n'))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/score.py to score.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/video.py to video.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/cache.py to cache.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/api.py to api.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/cli.py to cli.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/cli.py', 87, 60, '        args.languages = {babelfish.Language.fromietf(l) for l in args.languages}\n'))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/compat.py to compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/tests/test_providers.py to test_providers.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/tests/test_providers.py', 62, 37, "        languages = {Language('tur'), Language('rus'), Language('heb'), Language('ita'), Language('fra'),\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/tests/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/tests/test_subliminal.py to test_subliminal.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/tests/test_subliminal.py', 24, 37, "        languages = {Language('eng')}\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py to addic7ed.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py', 60, 49, "    languages = {babelfish.Language('por', 'BR')} | {babelfish.Language(l)\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/thesubdb.py to thesubdb.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/thesubdb.py', 31, 53, "    languages = {babelfish.Language.fromalpha2(l) for l in ['en', 'es', 'fr', 'it', 'nl', 'pl', 'pt', 'ro', 'sv', 'tr']}\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/tvsubtitles.py to tvsubtitles.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/tvsubtitles.py', 63, 49, "    languages = {babelfish.Language('por', 'BR')} | {babelfish.Language(l)\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/podnapisi.py to podnapisi.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/podnapisi.py', 69, 56, "    languages = {babelfish.Language.frompodnapisi(l) for l in babelfish.language_converters['podnapisi'].codes}\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/__init__.py to __init__.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/__init__.py', 243, 52, '        self.providers = {p: provider_manager[p] for p in (providers or provider_manager.available_providers)}\n'))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/opensubtitles.py to opensubtitles.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/providers/opensubtitles.py', 85, 60, "    languages = {babelfish.Language.fromopensubtitles(l) for l in babelfish.language_converters['opensubtitles'].codes}\n"))

byte-compiling build/bdist.linux-x86_64/egg/subliminal/subtitle.py to subtitle.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/subliminal/subtitle.py', 72, 41, "                    matches -= {'series', 'tvdb_id', 'season', 'episode', 'title', 'year'}\n"))

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/subliminal-0.8.0_dev-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing subliminal-0.8.0_dev-py2.6.egg
removing '/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg
Extracting subliminal-0.8.0_dev-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/cli.py', 87, 60, '        args.languages = {babelfish.Language.fromietf(l) for l in args.languages}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/subtitle.py', 72, 41, "                    matches -= {'series', 'tvdb_id', 'season', 'episode', 'title', 'year'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/converters/tvsubtitles.py', 11, 39, '        self.to_tvsubtitles = {v: k for k, v in self.from_tvsubtitles}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/converters/podnapisi.py', 17, 37, '        self.to_podnapisi = {v: k for k, v in self.from_podnapisi.items()}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/tests/test_providers.py', 62, 37, "        languages = {Language('tur'), Language('rus'), Language('heb'), Language('ita'), Language('fra'),\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/tests/test_subliminal.py', 24, 37, "        languages = {Language('eng')}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/addic7ed.py', 60, 49, "    languages = {babelfish.Language('por', 'BR')} | {babelfish.Language(l)\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/thesubdb.py', 31, 53, "    languages = {babelfish.Language.fromalpha2(l) for l in ['en', 'es', 'fr', 'it', 'nl', 'pl', 'pt', 'ro', 'sv', 'tr']}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/tvsubtitles.py', 63, 49, "    languages = {babelfish.Language('por', 'BR')} | {babelfish.Language(l)\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/podnapisi.py', 69, 56, "    languages = {babelfish.Language.frompodnapisi(l) for l in babelfish.language_converters['podnapisi'].codes}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/__init__.py', 243, 52, '        self.providers = {p: provider_manager[p] for p in (providers or provider_manager.available_providers)}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg/subliminal/providers/opensubtitles.py', 85, 60, "    languages = {babelfish.Language.fromopensubtitles(l) for l in babelfish.language_converters['opensubtitles'].codes}\n"))

subliminal 0.8.0-dev is already the active version in easy-install.pth
Installing subliminal script to /usr/bin

Installed /usr/lib/python2.6/site-packages/subliminal-0.8.0_dev-py2.6.egg
Processing dependencies for subliminal==0.8.0-dev
Searching for pyxdg==0.25
Best match: pyxdg 0.25
Processing pyxdg-0.25-py2.6.egg
pyxdg 0.25 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/pyxdg-0.25-py2.6.egg
Searching for pysrt==1.0.1
Best match: pysrt 1.0.1
Processing pysrt-1.0.1-py2.6.egg
pysrt 1.0.1 is already the active version in easy-install.pth
Installing srt script to /usr/bin

Using /usr/lib/python2.6/site-packages/pysrt-1.0.1-py2.6.egg
Searching for charade==1.0.3
Best match: charade 1.0.3
Processing charade-1.0.3-py2.6.egg
charade 1.0.3 is already the active version in easy-install.pth
Installing charade script to /usr/bin

Using /usr/lib/python2.6/site-packages/charade-1.0.3-py2.6.egg
Searching for babelfish==0.5.3
Best match: babelfish 0.5.3
Processing babelfish-0.5.3-py2.6.egg
babelfish 0.5.3 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/babelfish-0.5.3-py2.6.egg
Searching for dogpile.cache==0.5.4
Best match: dogpile.cache 0.5.4
Processing dogpile.cache-0.5.4-py2.6.egg
dogpile.cache 0.5.4 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/dogpile.cache-0.5.4-py2.6.egg
Searching for html5lib==1.0b3
Best match: html5lib 1.0b3
Processing html5lib-1.0b3-py2.6.egg
html5lib 1.0b3 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/html5lib-1.0b3-py2.6.egg
Searching for enzyme==0.4.1
Best match: enzyme 0.4.1
Processing enzyme-0.4.1-py2.6.egg
enzyme 0.4.1 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/enzyme-0.4.1-py2.6.egg
Searching for requests==2.5.1
Best match: requests 2.5.1
Processing requests-2.5.1-py2.6.egg
requests 2.5.1 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/requests-2.5.1-py2.6.egg
Searching for guessit==0.10.1
Best match: guessit 0.10.1
Processing guessit-0.10.1-py2.6.egg
guessit 0.10.1 is already the active version in easy-install.pth
Installing guessit script to /usr/bin

Using /usr/lib/python2.6/site-packages/guessit-0.10.1-py2.6.egg
Searching for beautifulsoup4==4.3.2
Best match: beautifulsoup4 4.3.2
Processing beautifulsoup4-4.3.2-py2.6.egg
beautifulsoup4 4.3.2 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/beautifulsoup4-4.3.2-py2.6.egg
Searching for argparse==1.2.1
Best match: argparse 1.2.1
Adding argparse 1.2.1 to easy-install.pth file

Using /usr/lib/python2.6/site-packages
Searching for chardet==2.3.0
Best match: chardet 2.3.0
Processing chardet-2.3.0-py2.6.egg
chardet 2.3.0 is already the active version in easy-install.pth
Installing chardetect script to /usr/bin

Using /usr/lib/python2.6/site-packages/chardet-2.3.0-py2.6.egg
Searching for dogpile.core==0.4.1
Best match: dogpile.core 0.4.1
Processing dogpile.core-0.4.1-py2.6.egg
dogpile.core 0.4.1 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/dogpile.core-0.4.1-py2.6.egg
Searching for six==1.9.0
Best match: six 1.9.0
Processing six-1.9.0-py2.6.egg
six 1.9.0 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/six-1.9.0-py2.6.egg
Searching for python-dateutil==2.4.0
Best match: python-dateutil 2.4.0
Processing python_dateutil-2.4.0-py2.6.egg
python-dateutil 2.4.0 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/python_dateutil-2.4.0-py2.6.egg
Searching for stevedore==1.2.0
Best match: stevedore 1.2.0
Processing stevedore-1.2.0-py2.6.egg
stevedore 1.2.0 is already the active version in easy-install.pth

Using /usr/lib/python2.6/site-packages/stevedore-1.2.0-py2.6.egg
Searching for pbr==0.10.7
Best match: pbr 0.10.7
Processing pbr-0.10.7-py2.6.egg
pbr 0.10.7 is already the active version in easy-install.pth
Installing pbr script to /usr/bin

Using /usr/lib/python2.6/site-packages/pbr-0.10.7-py2.6.egg
Searching for pip==6.0.6
Best match: pip 6.0.6
Processing pip-6.0.6-py2.6.egg
pip 6.0.6 is already the active version in easy-install.pth
Installing pip script to /usr/bin
Installing pip2.6 script to /usr/bin
Installing pip2 script to /usr/bin

Using /usr/lib/python2.6/site-packages/pip-6.0.6-py2.6.egg
Finished processing dependencies for subliminal==0.8.0-dev

[root@processor subliminal]# python -i
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subliminal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "subliminal/__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "subliminal/api.py", line 9, in <module>
    from .providers import ProviderPool
  File "subliminal/providers/__init__.py", line 243
    self.providers = {p: provider_manager[p] for p in (providers or provider_manager.available_providers)}
                                               ^
SyntaxError: invalid syntax
>>> 

During the install I see metion of babelfish so I figured it wouldn't hurt to pip uninstall it, and try again:

[root@processor subliminal]# pip uninstall babelfish
Uninstalling babelfish-0.5.3:
  /usr/lib/python2.6/site-packages/babelfish-0.5.3-py2.6.egg
Proceed (y/n)? y
  Successfully uninstalled babelfish-0.5.3
[root@processor subliminal]# pip uninstall subliminal
Uninstalling subliminal-0.8.0.dev0:
  /usr/bin/subliminal
Proceed (y/n)? y
  Successfully uninstalled subliminal-0.8.0.dev0

No dice same error. But import babelfish works.

Any ideas? I don't need the subs, but as I backconvert stuff it would help not having to force Plex/PodnapisiPlugin to download subtitles again.

**Comment by mdhiggins** [comment]
That's very strange it does sorta look like the installation goes through since you can import, I just don't see why you're getting a syntax error on the installed product. I would try deleting all the pythong eggs and reinstalling and see what it gets you.

**Comment by mdhiggins** [comment]
Likely an isolated incident, reopen if you're still experiencing problems. Cleaning up the issues list.
