### ISSUE TITLE
AAC & AC3 only plays stereo

### ISSUE THREAD

**Issue by beerygaz** [mdhiggins/sickbeard_mp4_automator#189]
Firstly Michael, thank you very much for this suite of scripts.  It matches my workflow perfectly and was a cinch t install.  I appreciate your hard work.

I am experiencing one issue, however. I have an ATV3 with plexconnect & PMS 9.11.7.  From what I can gather, any files created with both the AAC 2ch and AC3 5.1 streams in them will only play in stereo on my receiver.  As soon as I remove the AAC stream, I get true dd surround sound.

I tested by converting an MKV the ios-audio setting in the INI file set to "True" and then "False". 

With "True" I get the AAC stream included and stereo output only, with "False" I get a surround sound stream to my receiver.

(PMS has "Enable DD on AppleTV" checked, plexconnect is set to DirectPlay)

Any thoughts on where I'm going wrong?

**Comment by mdhiggins** [comment]
It sounds like for whatever reason plexConnect is defaulting to the AAC
channel whenever it is present and thus you're only getting stereo audio
since the iOS audio is always stereo. I haven't used plexConnect as I no
longer have an ATV but is there any option that allows your to select which
audio track is being played?

**Comment by beerygaz** [comment]
There is, but no matter which track I select on the ATV interface, it still plays in stereo.  For now, I’ve just elected to drop the AAC track altogether and things are working on the ATV.  Not sure what will happen when I try to play them in an iPad though.

 

I’m going to try to swap the AAC and AC3 streams around and see if it makes a difference.

**Comment by mdhiggins** [comment]
I would make a thread over on the Plex forums and see if anyone knows if this is a limitation of plexConnect, I suspect it is but it may be something that can be worked around. Otherwise I think you're limited to having just 1 audio track. Playing back the audio on an iPad will likely just result in plex having to transcode the audio stream on the fly if its AC3 5.1.

**Comment by mattrab** [comment]
I had the exact same issue, ac3 5.1 tracks would play in stereo, even when manually selecting the dolby track on the apple tv.
It seems that using the option ios-first-track-only=True in autoProcess.ini does the trick so far (ref: https://github.com/mdhiggins/sickbeard_mp4_automator/issues/190)
and the ac3 5.1 track are now playing properly on my audio receiver.

**Comment by beerygaz** [comment]
The you’re doing better than I am.  I just clones the latest version, added both the ios-audio=True options and converted a file, I now have an AAC 2ch and AC3 6ch stream in the file, but the ATV3 still only outputs stereo to my receiver.  I’m stumped.

**Comment by beerygaz** [comment]
Here's the output from the conversion:
Video codec detected: h264
Audio stream detected: ac3 und [Stream 1]
Creating dual audio channels for iOS compatability for this stream
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "und"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "copy",
            "bitrate": 1536,
            "language": "und"
        }
    },
    "video": {
        "map": 0,
        "codec": "copy",
        "bitrate": 2188599.0
    },
    "format": "mp4"

**Comment by mattrab** [comment]
After some more testing, I have been successful only when converting a 5.1 DTS track to 2.0 aac & 5.1 ac3, and the ac3 track plays in dolby on the receiver.
Same than you though, the option ios-first-track-only=True failed me when I tried to convert an 5.1 ac3 track to 2.0 aac and 5.1 ac3 (copy).

On a different note, I have succeeded to convert anything for AppleTv & Plex Connect with mp4tools
http://www.emmgunn.com/mp4tools/mp4toolshome.html, but the down part is that I have to run this separately on my mac.
I would rather use this script directly on the server.

**Comment by mdhiggins** [comment]
So it seems like the issue occurs when the AC3 5.1 track is copied from the source material, and doesn't have the issue when it is converted from a different codec. Its possible that whatever source material you're using is encoding the AC3 track in such a way that its not playing nice with the ATV.

**Comment by mattrab** [comment]
This would make sense.
So I just tried to encode the same audio 5.1 ac3, but this time with ios-audio=False
I ended up with an mp4 file, with a single 5.1 ac3 audio track. 
When I played it on my receiver, it played perfectly in dolby 5.1

I have also compared a non working file (1 aac track & 1 5.1 ac3 track) with this script, agains a working file (1 aac track & 1 5.1 ac3 track) created with mp4tools, (both are supposed to just copy the ac3 track.
The only difference that I see with ffprobe, is that the file created with the script declares both the aac and the ac3 tracks as default, where the working filer has only the aac track as default

5.1 ac3 not working:
 Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

5.1 ac3 working:
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Metadata:
      handler_name    : SoundHandler

**Comment by beerygaz** [comment]
Good catch, I was doing the same testing with the same results. The AC3 track plays if it's the only track, but as soon as there are both AAC and AC3 then only the AAC track seems to get selected by the ATV. 

Being far from an expert in this field, could it be related to this "default" tag?  Is there a way to remove it for a comparison test?

**Comment by Needle2000** [comment]
I'm glad you guys opened this issue as I thought I was going crazy.

**Comment by mdhiggins** [comment]
So I just wanna clarify are all of these surround sound playback issues happening only on the AppleTV?

**Comment by beerygaz** [comment]
Mine is on an ATV3, latest software.

**Comment by Needle2000** [comment]
I'm on IOS6 ATV3 exactly the same issue.

**Comment by mdhiggins** [comment]
Soon as I get a chance (hopefully in the next couple days) I'm gonna make a branch with an option that will reorder the tracks, placing the surround sound file before the iOS-audio stereo track in the order of the streams specifically to see if it resolves this ATV issue. I don't have an apple tv to test on so I'll need feedback from you guys once I get the code posted. I'll update here when the branch is live.

**Comment by mattrab** [comment]
I have modified the script on my side and set it to have the copy ac3 track first and the created aac track second. Sadly it did not make any difference..
I even tried to apply this patch on ffmpeg ref: https://trac.ffmpeg.org/ticket/3622 but that didn't do it.
Hope you'll have better luck!
Thanks!

**Comment by mdhiggins** [comment]
Yeah after further reading it looks like this is an issue with FFMPEG and not something that can likely be resolved on my end

**Comment by mdhiggins** [comment]
Closing this since its an FFMPEG issue

**Comment by aimkeepachieve** [comment]
You may use iDealshare VideoGo to change AAC or AC3 audio channel from stereo to 5.1

Step by step guide is below:

Click "Setting..." button, the "Advanced Settings" Window will pop up right beside the main window; 
.
In the 'Advanced Settings' Window,  switch to 'Advanced' tab and then go to the 'Audio Codec' section; 

Click Stereo on the right side of Channels to select 5.1 from the drop-down list.

Windows version at http://www.idealshare.net/video-converter.html
Mac version at http://www.idealshare.net/video-converter-mac.html
