### ISSUE TITLE
'NoneType' object has no attribute 'video'

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#196]
I see the other issues with the particular error "An unexpected error occurred, processing of this file has failed
'NoneType' object has no attribute 'video'"

I have the same error. I'm running Fedora 21, and I believe it may be an issue with either ffmpeg or ffprobe, as it happens both manually and with the scripts. However, I am not sure where to get a reliable installation of ffmpeg or ffprobe. Most of the instructions here are for Windows or Ubuntu. Can somebody (maybe who has this working on Fedora) tell me where to install these two modules from?

**Comment by mdhiggins** [comment]
First make sure its happening with more than 1 video file, sometimes that error can be because FFPROBE can't read the file because its corrupt for whatever reason.

If that's not the case, then try pulling down some precompiled binaries for ffmpeg and ffprobe and see if that resolves your issue.

**Comment by enz1ey** [comment]
It happens on every video. And is there anywhere I can get a precompiled binary for Fedora? The ffmpeg site seems to include ffprobe but you have to compile it obviously

**Comment by mdhiggins** [comment]
http://johnvansickle.com/ffmpeg/

Just grab the release build. (2.5.3). It includes both ffmpeg and ffprobe binaries.

**Comment by enz1ey** [comment]
That was it! Thanks a lot, man. I don't know why my versions didn't work as they had the same version number, but I downloaded those satic builds, replaced them in my /usr/bin/ folder and PRESTO. At least, with the manual script, that is lol. Waiting for my test conversion to finish and I'll try out the SAB scripts, but I don't see why they won't work. Thanks so much! Great response time, too!

**Comment by mdhiggins** [comment]
No prob, enjoy!
