### ISSUE TITLE
Transmission Integration in Fedora?

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#199]
I see there is an option for µTorrent integration, but I'm running a headless Fedora server, so I'm using Transmission. I am switching from SickBeard to Sonarr currently, and was wondering if there was a way to integrate Transmission into the mix with this script

**Comment by mdhiggins** [comment]
I imagine all this would take is adapting the uTorrent script to whatever command line arguments Transmission passes when its done processing. Can you link me some documentation on this and I'll see what I can do?

**Comment by enz1ey** [comment]
This is all I really can think of to start with: https://trac.transmissionbt.com/wiki/Scripts

But most of that is beyond my knowledge. I tried writing a bash script which runs your manual.py script after a torrent completes, but it gets handed back to Sonarr before it gets a chance to run it seems.

**Comment by zybeon** [comment]
Do you have Drone Factory Scan set to 0 in Sonarr?
If not set it to 0 then add this to the bottom of your script.
    curl http://localhost:8989/api/command -X POST -d '{"name": "downloadedepisodesscan", "path", $TR_TORRENT_DIR }' --header "X-Api-Key:YOUR_API_KEY_GOES_HERE"

Can you post a link to the script?

**Comment by mdhiggins** [comment]
So the frustrating thing with Transmission is that you can't really set "labels" like you can with uTorrent, which is the best way to filter out universally running the script on every torrent. You can set Groups sort of, but it seems like none of the primary programs (SB/CP/Sonarr) can take advantage of this. The uTorrent script will be rewritten soon to support dynamic processing to send to the appropriate program based on label; not sure if this is gonna be possible with transmission.

**Comment by enz1ey** [comment]
Would it be possible to just have it work with every torrent? I don't use transmission for anything other than Sonarr, so I wouldn't need any grouping or anything like that. 

Another sort of unrelated question, which script should I use in SABnzbd to send videos back to Sonarr rather than SickBeard?

**Comment by mdhiggins** [comment]
use SABPostProcess.py and configure your categories in SAB accordingly.

To explain further, there are categories under the SABNZBD section of autoProcess.ini for sickbeard, sonarr, and couchpotato. Just make the categories in there match the categories set in SABNZBD for Sonarr.

**Comment by enz1ey** [comment]
There aren't any scripts named SABPostProcess.py in there

**Comment by zybeon** [comment]
Are you in the master branch because I can see it.

**Comment by mdhiggins** [comment]
Any updates on this? I too suspect you aren't in the master branch

**Comment by enz1ey** [comment]
Yes I was outdated. Ran a new pull and grabbed the latest releases and it's there.

**Comment by mdhiggins** [comment]
Alright so to get back to the primary issue at hand. The various media management programs (CP/SB/Sonarr) don't seem to support "categories" for transmission or any sort of labelling that would allow a post-processing script to discern what files it needs to act on,, and in what way to act on them. It makes creating a script a bit more difficult.

**Comment by mdhiggins** [comment]
So I have a new development branch named deluge to add support for the deluge torrent client. Deluge should work fine on a headless linux server and is a little more robust than transmission. The script is only compatible with the deluge daemon. If you'd like to test it out before things go live here are some quick setup instructions

Go to your deluge configuration directory and open up the auth file
add a username and password in the following format `user:pass:10`
Save auth
- Start deluged executable (not deluge, deluged), restart if it was already running
- Login via the webui (default port 8112)
- Enabled the "Execute" plugin in the preferences > plugin menu
- Setup the execute plugin by adding the delugePostProcess.py file on "Torrent Completes"
- Enable the `Labels` addon as well

- open autoProcess.ini
- configure deluge settings with the username and password you set in the auth file. Default port is 58846
- set up your various labels
- in deluge, set up the labels to match what you have set in autoProcess.ini

That should do it

**Comment by mdhiggins** [comment]
Transmission integration isn't planned because labels cannot be automatically set by downloaders, use deluge for now. If this feature is added then tranmission support will be reevaluated
