### ISSUE TITLE
CouchPotato Error

### ISSUE THREAD

**Issue by thamilton91** [mdhiggins/sickbeard_mp4_automator#200]
I setup CouchPotato today, but i'm noticing that movies are being renamed and moved, but not converted to MP4.

After reinstalling everything based on the ReadMe, i'm noticing an error in CouchPotato log after copying the PostProcess folder to the custom_plugins directory.

Here is a screenshot of my CouchPotato Logs.

![screen shot 2015-02-15 at 5 15 15 pm](https://cloud.githubusercontent.com/assets/5624324/6205442/1ffb0cd8-b53c-11e4-8ba1-310eafdb869b.png)

**Comment by mdhiggins** [comment]
Looks like one of the characters in the path you specified isn't happy being an ascii character.

Post your path line (line 11) from the main.py file

**Comment by thamilton91** [comment]
Highlighted in blue is the specified path to CPProcess.py in the main.py file.

![screen shot 2015-02-15 at 6 02 44 pm](https://cloud.githubusercontent.com/assets/5624324/6205479/f4751b2a-b53c-11e4-8c2c-0dadf0211ea5.png)

**Comment by mdhiggins** [comment]
So first off it should just be the path to the script folder, not to CPProcess.py

So your path should read "/Applications/MP4_Automator/"

Your problem I suspect is from the text editor you're using. Its saving the file in a format that python isn't happy with. I'm not super familiar with OSX though but I know this happens with the textedit app.

**Comment by mdhiggins** [comment]
Here's a thread that explains your exact problem

https://stackoverflow.com/questions/22917329/python-script-invalid-character

**Comment by thamilton91** [comment]
Thanks, I downloaded a new copy of that folder and edited it in Xcode. I'm no longer receiving that error, however the script still is not converting the MKV file to MP4.

Once the torrent has completed, CouchPotato appears to rename and copy the file, but once the file is moved nothing else happens. 

I'm seeing in the log that the PostProcess script initializes, but then returns an error code "1".

![screen shot 2015-02-15 at 6 21 30 pm](https://cloud.githubusercontent.com/assets/5624324/6205542/941b5566-b53f-11e4-943b-b7a718f62533.png)

**Comment by mdhiggins** [comment]
Could you post your new main.py file?

**Comment by thamilton91** [comment]
![screen shot 2015-02-15 at 6 39 37 pm](https://cloud.githubusercontent.com/assets/5624324/6205605/05db3714-b542-11e4-8e1e-7df9dd046771.png)

**Comment by mdhiggins** [comment]
Alright that looks fine. I went ahead and pushed an update to this script with the latest commit that added some additional logging parameters that probably should have been there from the start. If you update your CP script (and delete the same .pyc files same as last time) with these changes and post the log hopefully we can figure out what's going on.

**Comment by thamilton91** [comment]
I have updated all files, but I didn't see any .pyc files to remove.

Here is the new log after update.
![screen shot 2015-02-15 at 7 17 33 pm](https://cloud.githubusercontent.com/assets/5624324/6205759/7bf444c2-b547-11e4-9d62-cb79fa845e6d.png)

**Comment by mdhiggins** [comment]
Alright looks like because there is 2 files they're both being passed to the script and I think that might be what's causing the error. I went ahead and made some changes to the script that should account for this and hopefully fix your issue. Let me know if it works

**Comment by mdhiggins** [comment]
Wait scratch that, I'm wrong

Gonna have to come up with something else

**Comment by thamilton91** [comment]
It looks like the script is grabbing both the original file in my Downloads folder and the renamed and copied file located in my Movies folder.

I wanted to clarify that I am having CouchPotato copy the file instead of move it so that transmission can continue seeding the download.

Hope that helps, thanks again.

**Comment by mdhiggins** [comment]
I guess the next step is to see if executing the command manually will work. Here is the command being generated by the main.py script:

`python '/Applications/MP4_Automator/CPProcess.py' 'tt0093105' '/Volumes/Storage/Hamserve/Movies/Good Morning, Vietnam (1987)/Good.Morning,.Vietnam.1987.BluRay.1080p.mkv'`

See if you can past that into the terminal and it'll run.

This may be related to CP copying the file as well, I'll have to investigate how to address this. Make sure you revert that last change I made (already done in the master build). Also could you attach a screenshot of the settings where you have the copy option set up?

**Comment by thamilton91** [comment]
I attempted to run the script manually, it hung up for a few moments thens showed an audio bitrate error.
![screen shot 2015-02-15 at 8 10 22 pm](https://cloud.githubusercontent.com/assets/5624324/6206058/ea9b20f6-b54e-11e4-8ff5-1c423dc93362.png)

As for the copy setting. I set that in CouchPotato under "Renamer" under default file action.
![screen shot 2015-02-15 at 8 05 39 pm](https://cloud.githubusercontent.com/assets/5624324/6206061/0900d78e-b54f-11e4-91e7-f8f3b394d0f9.png)

**Comment by mdhiggins** [comment]
So that audio bitrate error is actually ok (not something that would cause the script to abort). Did the file actually convert? It may have. That script doesn't normally have any output.

**Comment by thamilton91** [comment]
I tried it in a few different formats (with quotations and without) it appears to give that error then instantly abort. I do not see a converted file anywhere. This issue does not occur if i use the manual.py script.

**Comment by mdhiggins** [comment]
```
#!/usr/bin/env python
import os
import sys
from readSettings import ReadSettings
from tmdb_mp4 import tmdb_mp4
from mkvtomp4 import MkvtoMp4


settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")

if len(sys.argv) > 2:
    inputfiles = sys.argv[3:]
    imdb_id = sys.argv[1]
    original = sys.argv[2]
    print imdb_id
    print original
    converter = MkvtoMp4(settings)

    for inputfile in inputfiles:
        try:
            print inputfile
        except:
            pass
        if MkvtoMp4(settings).validSource(inputfile):
            print "Valid source detected"
            output = converter.process(inputfile, original=original, reportProgress=True)
            
            # Tag with metadata
            if settings.tagfile:
                tagmp4 = tmdb_mp4(imdb_id, original=original, language=settings.taglanguage)
                tagmp4.setHD(output['x'], output['y'])
                tagmp4.writeTags(output['output'], settings.artwork)

            #QTFS
            if settings.relocate_moov:
                converter.QTFS(output['output'])

            # Copy to additional locations
            converter.replicate(output['output'])

else:
    print "Not enough command line arguments present " + str(len(sys.argv))
    sys.exit()
```

Try this modified CPProcess.py file and see if you can get it to execute with command line

**Comment by thamilton91** [comment]
![screen shot 2015-02-15 at 8 42 00 pm](https://cloud.githubusercontent.com/assets/5624324/6206232/482d2e40-b553-11e4-9a15-5ee1bff8c624.png)

Looks like same audio error occurred, but this time it repeated the variables then aborted. No converted file was saved.

**Comment by mdhiggins** [comment]
Ok so its failing on the "validSource" check since I'm not seeing "Valid source detected" being outputted. This is likely due to an error in the formatting of the path of the file. Try typing in the command like you've been doing, but instead of typing in the full path to the file, when you get to that part just drag the file from finder into the terminal window to have it autopopulate the path and see if that works.

**Comment by thamilton91** [comment]
I tried a few different ways with different variables, but still same issue. I also tried to rename the file to make sure it wasn't an issue with a strange character. 
![screen shot 2015-02-15 at 8 54 05 pm](https://cloud.githubusercontent.com/assets/5624324/6206308/fa28dec2-b554-11e4-9f5c-2121ad0e67fb.png)

**Comment by mdhiggins** [comment]
Crap this is my fault, I messed up that initial command I sent you and have had you chasing your tail. 

```
python '/Applications/MP4_Automator/CPProcess.py' 'tt0093105' '/Volumes/Storage/Hamserve/Movies/Good Morning, Vietnam (1987)/Good.Morning,.Vietnam.1987.BluRay.1080p.mkv' '/Volumes/Storage/Hamserve/Movies/Good Morning, Vietnam (1987)/Good.Morning,.Vietnam.1987.BluRay.1080p.mkv'
```

Try that. The path should appear twice. Normally that would be the original path but for testing we don't need it.

**Comment by thamilton91** [comment]
No worries.

That went through fine, the video is converting now. What does adding the file path again do differently?

**Comment by mdhiggins** [comment]
So normally couch potato passes both the original path and the final path (after renamer has done its thing) to the script. The original path is helpful for gathering some of the metadata for tagging and downloading subtitles. When we were trying to see if the script would launch manually (its not really meant to be launched this way) I forgot this and we were sending it an incomplete set of arguments.

Anyway, now we know the script does work, and based on what CP is sending, it looks like its exactly as it should be. 

I wanna try setting the "shell=true" option to your popen command in main.py and see if that fixes this since we know CP is passing the correct variables and the CPProcess.py file is working as expected.

Replace your main.py with this:
```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
from subprocess import Popen, PIPE
import traceback
import os

log = CPLog(__name__)

# Edit to point to the absolute path where the CPProcess.py script resides
path = "C:\\Scripts\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)

    
    def callscript(self, message = None, group = None):
        log.info('MP4 Automator Post Processing script initialized mod 1')
        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]
        
        command = ['python']
        command.append(os.path.join(path, 'CPProcess.py'))
        command.append(imdbid)
        command.append(original)
        for x in moviefile:
            command.append(x)

        log.info("Command generated: %s", command)
        try:
            shell = (os.name != 'nt')
            p = Popen(command, stdout=PIPE, shell=shell)
            res = p.wait()
            if res == 0:
                log.info('PostProcess Script was called successfully')
                return True
            else:
                log.info('PostProcess Script returned an error code: %s', str(res))
                log.info(p.stdout.read())

        except:
            log.error('Failed to call script: %s', (traceback.format_exc()))


        return False
```

and as always you gotta shut down CP, delete any .pyc files that have appear, then restart. (they may not appear).

**Comment by thamilton91** [comment]
I think there was a typo in the script you sent. It showed shell=shell so i changed it to shell=True.

It looks like progress no specific error, but still no converted video.

![screen shot 2015-02-15 at 9 42 02 pm](https://cloud.githubusercontent.com/assets/5624324/6206592/a53ae2dc-b55b-11e4-8c5c-a39de82d33cc.png)

**Comment by mdhiggins** [comment]
Alright more logging:

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
from subprocess import Popen, PIPE
import traceback
import os

log = CPLog(__name__)

# Edit to point to the absolute path where the CPProcess.py script resides
path = "C:\\Scripts\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)

    
    def callscript(self, message = None, group = None):
        log.info('MP4 Automator Post Processing script initialized mod 1')
        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]
        
        command = ['python']
        command.append(os.path.join(path, 'CPProcess.py'))
        command.append(imdbid)
        command.append(original)
        for x in moviefile:
            command.append(x)

        log.info("Command generated: %s", command)
        try:
            shell = (os.name != 'nt')
            p = Popen(command, stdout=PIPE, shell=shell)
            (output, err) = p.communicate()
            res = p.wait()
            log.info(output)
            log.info(err)
            if res == 0:
                log.info('PostProcess Script was called successfully')
                return True
            else:
                log.info('PostProcess Script returned an error code: %s', str(res))

        except:
            log.error('Failed to call script: %s', (traceback.format_exc()))


        return False
```

I changed a couple lines so copy the whole thing (except the line with your path, line 11). The shell=shell was intended. The before that is `shell = (os.name != 'nt')` which will generate a True for non-windows based systems. Let me know what the log shows. Sorry to make you keep doing this over and over.

**Comment by thamilton91** [comment]
When it was set to shell=shell I was receiving this error, which i'm receiving now with this new one:

02-15 22:07:49ERROR[  couchpotato.core.loader] Can't import PostProcess: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/appdata/CouchPotato-2.6.2.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/loader.py", line 58, in run
  File "/Applications/CouchPotato.app/appdata/CouchPotato-2.6.2.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/loader.py", line 164, in loadModule
  File "/Applications/CouchPotato.app/appdata/CouchPotato-2.6.2.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/importhelper/__init__.py", line 37, in import_module
  File "/Users/hamserve/Library/Application Support/CouchPotato/custom_plugins/PostProcess/__init__.py", line 1, in <module>
  File "/Users/hamserve/Library/Application Support/CouchPotato/custom_plugins/PostProcess/main.py", line 38
    try:
    ^
IndentationError: unexpected indent

**Comment by mdhiggins** [comment]
Looks like something got indented that shouldn't have been there

**Comment by thamilton91** [comment]
Here's what I have.
![screen shot 2015-02-15 at 10 18 21 pm](https://cloud.githubusercontent.com/assets/5624324/6206813/9f150a5e-b560-11e4-97bb-a50ae36c1f54.png)

**Comment by mdhiggins** [comment]
Yeah your tabbing is all screwed up, just copy and paste what I sent and change that one line

**Comment by thamilton91** [comment]
Fixed tabbing issue. Had to type it all in manually, copy and paste was giving me the tab issue.

Here is my main.py and CouchPotato log
![screen shot 2015-02-15 at 11 43 25 pm](https://cloud.githubusercontent.com/assets/5624324/6207298/aca5bc48-b56c-11e4-95b7-410cce1dbf55.png)
![screen shot 2015-02-15 at 11 44 48 pm](https://cloud.githubusercontent.com/assets/5624324/6207299/acb59690-b56c-11e4-81ca-2e8dac057958.png)

**Comment by mdhiggins** [comment]
Script looks good now. Unfortunately the additional logging isn't outputting anything. I think maybe it's not playing nice with the shell=True option. For now why don't you try deleting that option or hardcoding it to False and see if that gives any more logging information. 



—

**Comment by thamilton91** [comment]
I've been playing around with it for a bit. Clean installed CouchPotato and this script and left everything defaults.

The script is being called and shows that it is successful. Again, the file is renamed and moved properly but the conversion does not occur.

At this point everything is set up defaults so i'm not sure what else to try. Does anyone have CouchPotato running on a mac with this script functioning?

![screen shot 2015-02-17 at 4 14 10 pm](https://cloud.githubusercontent.com/assets/5624324/6237394/6e45c63c-b6c0-11e4-8609-53f8808ca81b.png)

**Comment by mdhiggins** [comment]
Sorry its still not working. Can you try this modified main.py script?

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
from subprocess import Popen, PIPE
import traceback
import os

log = CPLog(__name__)

# Edit to point to the absolute path where the CPProcess.py script resides
path = "C:\\Scripts\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)


    def callscript(self, message = None, group = None):
        log.info('MP4 Automator Post Processing script initialized mod 1')
        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]

        command = ['python']
        command.append(os.path.join(path, 'CPProcess.py'))
        command.append(imdbid)
        command.append(original)
        for x in moviefile:
            command.append(x)

        log.info("Command generated: %s", command)
        try:
            p = Popen(command, stdout=PIPE)
            (output, err) = p.communicate()
            res = p.wait()
            log.info(output)
            log.info(err)
            if res == 0:
                log.info('PostProcess Script was called successfully')
                return True
            else:
                log.info('PostProcess Script returned an error code: %s', str(res))

        except:
            log.error('Failed to call script: %s', (traceback.format_exc()))


        return False
```

AND this modified CPProcess.py script
```
#!/usr/bin/env python
import os
import sys
from readSettings import ReadSettings
from tmdb_mp4 import tmdb_mp4
from mkvtomp4 import MkvtoMp4


settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")

if len(sys.argv) > 2:
    inputfiles = sys.argv[3:]
    imdb_id = sys.argv[1]
    original = sys.argv[2]
    print imdb_id
    print original
    converter = MkvtoMp4(settings)

    for inputfile in inputfiles:
        try:
            print inputfile
        except:
            pass
        if MkvtoMp4(settings).validSource(inputfile):
            print "Valid source detected"
            output = converter.process(inputfile, original=original, reportProgress=True)

            # Tag with metadata
            if settings.tagfile:
                tagmp4 = tmdb_mp4(imdb_id, original=original, language=settings.taglanguage)
                tagmp4.setHD(output['x'], output['y'])
                tagmp4.writeTags(output['output'], settings.artwork)

            #QTFS
            if settings.relocate_moov:
                converter.QTFS(output['output'])

            # Copy to additional locations
            converter.replicate(output['output'])

else:
    print "Not enough command line arguments present " + str(len(sys.argv))
    sys.exit()
```

**Comment by thamilton91** [comment]
Unfortunately it doesn't look like i'm getting any different results.

Still error code 1.

![screen shot 2015-02-19 at 3 37 46 pm](https://cloud.githubusercontent.com/assets/5624324/6275469/600f836c-b84d-11e4-95a8-429cdb464f67.png)

**Comment by mdhiggins** [comment]
Is this with the modified CPProcess.py as well? cause if that's the case it looks like its actually failing to even attempt to execute the CPProcess.py file. I actually wonder if this is a permissions issue that's been messing things up. If you're up for it try moving the script folder out of /Applications/ and into your home directory somewhere and adjust the path accordingly.

**Comment by thamilton91** [comment]
Yes thats with both new files.

Tried it in the home directory with the same issues.

**Comment by thamilton91** [comment]
Back to square one, if I try to call the script manually in terminal. I'm getting nothing at all, it just sits here infinitely as if it's waiting for a next step.
![screen shot 2015-02-20 at 12 16 23 am](https://cloud.githubusercontent.com/assets/5624324/6281794/bc7e5cca-b895-11e4-97f9-3b004991058c.png)
This is with a clean download of this script in my user folder.

**Comment by thamilton91** [comment]
I'm now finding that if I run the script manually formatted this way (without quotes) it will now create the file correctly. 

![screen shot 2015-02-20 at 12 28 23 am](https://cloud.githubusercontent.com/assets/5624324/6281866/b27fffd8-b897-11e4-958c-e055b714b0b3.png)

**Comment by mdhiggins** [comment]
So the first command line failure was because you were putting the commas in between each argument.

However, rather than continuing to use popen which wasn't the best option anyway, I went ahead and rewrote the script to not use popen or CPProcess.py at all, and instead append the script directory to the sys.path and be able to use the script internally. Give it a try:

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
import traceback

log = CPLog(__name__)

# Edit to point to the absolute path where the CPProcess.py script resides
path = "/Applications/MP4_Automator/"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)

    
    def callscript(self, message = None, group = None):

        log.info('MP4 Automator Post Processing script initialized version 2')

        sys.path.append(path)
        try:
            from readSettings import ReadSettings
            from mkvtomp4 import MkvtoMp4
            from tmdb_mp4 import tmdb_mp4
        except ImportError:
            log.error('Path to script folder appears to be invalid.')
            return False

        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]
        
        success = False

        for inputfile in moviefile:
            try:
                log.info('Processing file: %s', inputfile)
                if MkvtoMp4(settings).validSource(inputfile):
                    log.info('File is valid')
                    output = converter.process(inputfile, original=original)
                    
                    # Tag with metadata
                    if settings.tagfile:
                        log.info('Tagging file with IMDB ID %s', imdbid)
                        tagmp4 = tmdb_mp4(imdbid, original=original, language=settings.taglanguage)
                        tagmp4.setHD(output['x'], output['y'])
                        tagmp4.writeTags(output['output'], settings.artwork)

                    #QTFS
                    if settings.relocate_moov:
                        converter.QTFS(output['output'])

                    # Copy to additional locations
                    converter.replicate(output['output'])

                    success = True
            except:
                log.info('File processing failed: %s', (traceback.format_exc()))

        return success
```

**Comment by mdhiggins** [comment]
I did some testing and this new script works and is actually much more efficient than the previous version. I went ahead and added it to the new build so if you update you'll get these changes. It should resolve your problem as well. CPProcess.py is no longer used and everything is handled by the files in the PostProcess.py script

**Comment by thamilton91** [comment]
All issues resolved! 

Thanks a ton for working with me on that!

**Comment by mdhiggins** [comment]
Glad its working. Big update coming out tonight too so stay tuned.
