### ISSUE TITLE
Unknown ffmpeg error video:0kB audio:0kB subtitle:16kB

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#205]
I apologize for yet another question, but now I've been getting this output on ALL my downloads:

File "/Users/Transmission/sickbeard_mp4_automator/converter/ffmpeg.py", line 459, in convert
    raise FFMpegConvertError('Unknown ffmpeg error ' + line)
converter.ffmpeg.FFMpegConvertError: Unknown ffmpeg error video:0kB audio:0kB subtitle:16kB other streams:0kB global headers:0kB muxing overhead: 87.138008%

I've tried three different ffmpeg/ffprobe releases.

**Comment by enz1ey** [comment]
Okay well I eliminated that error by entering 'nil' for the subtitle language, I really don't need subtitles anyway lol. But now, inside SABnzbd, it's throwing the error "Python module REQUESTS is required. Install with 'pip install requests' then try again."

I have installed AND reinstalled the requests module, and I can ensure it's there when I run pip freeze.

**Comment by mdhiggins** [comment]
No idea what's going on with that first error you were getting or why you need to disable subtitles. I'm curious where you're getting your FFMPEG builds maybe that's the issue.

For your new error, that message only should be popping up from SAB (I assume you mean when running the SABPostProcess.py) when `import requests` fails so I dunno what to tell you other than something with your python install isn't right. I'm guessing you're trying to use SAB and Sonarr hence the requests error popping up.

**Comment by mdhiggins** [comment]
Any updates on this?

**Comment by enz1ey** [comment]
I totally reinstalled both Python and Requests and that seems to have solved it, however I still get an error that it couldn't be sent to Sonarr. I tested with CouchPotato and it calls the request just fine. It just gives an error sending a request to Sonarr, although the weird thing is Sonarr still seems to pick up the file just fine. SABnzbd just shows the error in the script log. My credentials are fine in autoProcess.ini. 

As far as my first error in the thread, ever since I disabled subtitle ripping, I haven't seen it. So it seems to be something related to that.

**Comment by mdhiggins** [comment]
Not sure what's going on with the sonarr error but if its working it may not be something worth going crazy over, especially if requests seems to be good now.

As far as the subtitle error, I'm just curious where you're getting your FFMPEG builds or if you're building from source.

I would try and grab the latest stable release from here:
http://johnvansickle.com/ffmpeg/
and see if that resolves your issue.

**Comment by enz1ey** [comment]
Those are the ones I started with that didn't work. I don't recall exactly where I got the current ones from but when I get home I can look

**Comment by mdhiggins** [comment]
Going back to your original issue, I just pushed a big update that merged in the latest changes from python-video-converter, the script that the converter used in my script is forked from. See if that resolves your error as other users are reporting it did.

**Comment by mdhiggins** [comment]
Should be resolved after merging in latest changes from python-video-converter
