### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by paddy29** [mdhiggins/sickbeard_mp4_automator#208]
I am getting this error when I try to run manual.py for testing. I also got a similar error when I was trying to set it up for Sab using sabpostprocess.py. Not sure what I have done wrong,would appreciate any help.

C:\sickbeard_mp4_automator-master>manual.py
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\manual.py", line 18, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
  File "C:\sickbeard_mp4_automator-master\readSettings.py", line 342, in __init_
_
    self.Sickbeard['web_root'] = config.get(section, "web_root")  # Sickbeard we
broot
  File "C:\Python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'web_root' in section: 'SickBeard'

**Comment by mdhiggins** [comment]
Looks like this is because you're missing the "web_root" option in your Sickbeard settings. I added something to the readSettings.py to catch and add this like it does for other missing options. Go ahead and update and it will fix this.
