### ISSUE TITLE
Couchpotato config = confused

### ISSUE THREAD

**Issue by datrumole** [mdhiggins/sickbeard_mp4_automator#209]
So i've read the readme about 100 times, i've been using your and promoting your script everywhere i go, and i've adjusted based on what actually works. In your readme, youve stated to set the renamer to 'run every = 0' but unless i'm mistaken, the actual script gets fired POST RENAMER, so if the renamer doesnt ever run, how in the heck does the conversion ever get triggered. I've tested this every time i've updated both couchpotato and your git, and yet if i leave 'run every = 0' literally nothing ever moves. either the readme needs updating or i'm missing something major. the only way i get it to work is to completely disregard your instructions and set the renamer to literally anything that isnt 0, such that it works just fine. perhaps i'm missing something?

**Comment by mdhiggins** [comment]
All of the post downloader scripts trigger a renamer scan (SABPostProcess.py, NZBGetPostProcess.py, uTorrentPostProcess.py) which tells CP the download is complete and to start the renamer scan, then when the renamer scan is finished the final PostProcess.py CouchPotato plugin gets run which tags the file with the metadata it needs from couchpotato

**Comment by datrumole** [comment]
thanks for the quick response, and i guess i'm clearly missing something. so i dont know if this is completely inappropriate but are you available to clear this up? via google+ (hangouts) or am i totally off base by asking. i can provide my settings, i know working with oracle if you want progress sometimes getting people on the phone and demonstrating can be simply the most effective method. anyway, let me know, not trying to accuse you of a bug, just not fully under standing. i've been putting this off for some time for fear of being 'that person'

**Comment by mdhiggins** [comment]
Can't tonight but yeah I can help you out when I get a chance. But it's not super complicated, what program are you using to do your downloading?



—

**Comment by datrumole** [comment]
ok, not a problem

I guess here is a quick summary

couchpotato --> deluge

iv'e set couch rename to run every and force every = 0

however when the download completes, nothing moves. it sits in my download complete location and never actually gets moved to my final destination 

i've tested this by adding a new movie, and setting everything up, and letting it sit for 10 hours (most recent test). However if i update the renamer to 'run every = 1' then everything operates as expected. 

The issue i have is following the instructions vs what i know works. thus why i'm bringing this to your attention. if i follow what the readme states, nothing ever moves from complete to my movie collection. if i follow what i know works, it does, however the instructions are incorrect. just trying to figure out a middle ground

**Comment by datrumole** [comment]
i work from home, and am pretty open to when i can take a web conf. Please let me know if i'm being out of line by requesting this, just trying to help based on my understanding of the instructions which may be incorrectly interpreted by others.

**Comment by mdhiggins** [comment]
So the issue is here is that I don't have a postprocessing script for deluge. Normally the order of operations is as follows, using uTorrent as an example:

```
CouchPotato finds movie, passes download to uTorrent
uTorrent downloads
Download completes, uTorrent executes uTorrentPostProcess.py
uTorrentPostProcess.py converts file (if convert here is enabled) and then tells CP a download has finished, tells it where the file is, and kicks off renamer.scan
CP process, renames, and moves the file
CP executes its post processing script passing on the IMDB ID
Conversion is done if it wasn't previously, then file is tagged.
```

If you're going to use a program that doesn't have a script to tell couchpotato the download is finished, you're gonna have to use a blackhole and timed scan.

**Comment by datrumole** [comment]
ah-ha. so in reality i need to define a 'run every > X' where X is greater than 1, because i dont have an appropriate downloader than can execute a script to convert and then let CP know it's done. perfect! so my 'known to work' settings are accurate, just not in line with the instructions on the site. as simply as this may seem, can i make a suggestion to include this in the readme. I only say this as a proud user of this script! i cannot express how much this script has simplified my life. i really hope that plex and others pick you up and include your work in the standard normalization of media

**Comment by datrumole** [comment]
you are welcome to close hell even delete this thread! thanks again for your quick response

**Comment by mdhiggins** [comment]
I'll update the readme to make a note of this. Sorry for the confusion
