### ISSUE TITLE
Import error autoprocess

### ISSUE THREAD

**Issue by rhaba** [mdhiggins/sickbeard_mp4_automator#211]
Saw that you just updated SABPostProcess.py, but it's still throwing an error.

Traceback (most recent call last):
  File "C:\Scripts\SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR
ImportError: No module named autoprocess

**Comment by mdhiggins** [comment]
Hm its working ok on my end. Did you update the full path (so that you have the new autoprocess subdirectory in the scripts root directory with the 3 new scripts in that folder)?

**Comment by rhaba** [comment]
Sorry new to this.

My scripts are in c:\scripts , so you mean copy the autoprocess folder into that directory also? scripts is where my script resides obviously.

**Comment by mdhiggins** [comment]
So yeah, I moved some things around with the last update, so you should now have a C:\Scripts\autoprocess\ directory with 3 files in it.
- autoProcessMovie.py
- autoProcessTV.py
-autoProcessTVSR.py

**Comment by rhaba** [comment]
Ok, I just did that. Got about 5 mins left on a download and ill report back the results of that conversion.

**Comment by rhaba** [comment]
Received new error:

Traceback (most recent call last):
  File "C:\Scripts\SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR
  File "C:\Scripts\autoprocess\autoProcessMovie.py", line 7, in <module>
    from readSettings import ReadSettings
ImportError: No module named readSettings

I went ahead and copied readsettings.py and pyc and mkvtomp4.py / pyc to scripts.

Is that all that needs to be copied over?

**Comment by rhaba** [comment]
I saw a couple of other items, I just dumped everything into c:\scripts.

**Comment by mdhiggins** [comment]
So I think we need to take a step back

You need to clone this entire repository to c:\scripts not just individual files. If you have 0 experience doing this, click the "Downlaod Zip" button and extract everything to C:\Scripts. Then take a look at the readme and go through the configuration options to set up your autoProcess.ini file.

**Comment by rhaba** [comment]
Yeah, I've set that up already. I was under the impression that files could exist in two places. Sorry about that.

**Comment by mdhiggins** [comment]
Its alright. Let me know how its working with all the files now.

**Comment by rhaba** [comment]
No valid category detected, even though i have it defined. Hmmm

**Comment by mdhiggins** [comment]
Do they match?

**Comment by rhaba** [comment]
Yeah.

SAB = tv
SB = tv
autoProcess.ini set to sickbeard-category = tv

**Comment by mdhiggins** [comment]
Hm that looks like it should be working. I don't think SAB would need a restart but its possible.

**Comment by mdhiggins** [comment]
I updated to add some debugging so it will tell you what it thinks the category is. Update and report back

**Comment by rhaba** [comment]
Audio bitrate was invalid, defaulting to 256 per channel
Error, no valid category detected
Category was tv

Odd.

**Comment by rhaba** [comment]
I created a category called 'sickbeard' lets see what happens

**Comment by rhaba** [comment]
That worked! Thanks for all the help tonight. I'm sure its the last thing you wanted to do.

**Comment by mdhiggins** [comment]
Glad you got it working. I am curious however why the original implementation with "TV" as the category didn't work.

Could you post the autoProcess.ini file from your C:\scripts folder?

Also if you have the script copied to any other directories, where are they and can you post those autoProcess.ini files as well?

Thanks

**Comment by rhaba** [comment]
http://pastebin.com/bcT7hKUV

Removed my API keys. I had my category for sickbeard changed to tv, but reverted it back. C:\scripts is the only location that the file exists in now, I removed the second location based on the mixup I had earlier with this. At this point everything appears to be working peachy.

**Comment by mdhiggins** [comment]
Hm still not sure why using 'tv' didn't work. I did some updates this morning, added a little more debugging. If you're feeling generous and want to try setting all the category stuff back to TV and see if its still giving you a problem (and if so, please post the error) I'd appreciate it.

**Comment by rhaba** [comment]
Sure, I'll carve out some time later this afternoon since I'm working from home today.
