### ISSUE TITLE
Install guide reflective of elimination of CPProcess.py?

### ISSUE THREAD

**Issue by LeMasters** [mdhiggins/sickbeard_mp4_automator#214]
README.md's CouchPotato section, item 2, refers to need to edit PostProcess/main.py with info on the whereabouts of CPProcess.py -- which was part of sickbeard_mp4_automator until mid February 2015:  0f6369cbb9ccf34620fbe38c8cb6b9e8a1f668b3

**Comment by mdhiggins** [comment]
The readme is outdated I'll update it. You still need to point it to the script directory but CPProcess no longer exists. 



—

**Comment by mdhiggins** [comment]
Updated the readme. Thanks for pointing this out
