### ISSUE TITLE
subliminal install -- SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by screwzloose** [mdhiggins/sickbeard_mp4_automator#217]
First and foremost, this script is awesome, thank you very much!

When I attempt to install subliminal within the /setup/subliminal I get the following SSL error when it attempts to install charade.

//

Reading https://pypi.python.org/simple/charade/
Download error on https://pypi.python.org/simple/charade/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
Couldn't find index page for 'charade' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
No local packages or download links found for charade>=1.0.3
error: Could not find suitable distribution for Requirement.parse('charade>=1.0.3')

**Comment by mdhiggins** [comment]
Not sure why you’re getting this error but you could try manually installing charade and then retry your subliminal install.


`sudo pip install charade`


—

**Comment by screwzloose** [comment]
I ended up extracting the charade files separately and then ran the install. The pip install would of been alot easier (n00b mistake). Thank you. Only seems to pull down some subtitles, can't seem to figure out why some and not the others. 

Thanks again for your quick replies!

**Comment by mdhiggins** [comment]
A lot of it has to do with availability. The subliminal script isn't perfect but its the best option available at this point.

Hope everything works well from this point on. Good luck.

**Comment by ifitzpat** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ian.fitzpatrick@me.com
    Domain ianfitzpatrick.eu has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:60198 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server.budgettopserver.nl with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YYEN5-003JYv-GZ
	for ian@ianfitzpatrick.eu; Wed, 18 Mar 2015 14:50:56 +0100
Date: Wed, 18 Mar 2015 06:50:53 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1426686653;
	bh=mesl4qWYnhC2jpe8Iwr3ZGN9Gvzzg2/OS3XQSJAXCLI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=irPG+YsKuFCP3g7mclbT18F11vkaAnCrzMVNVvE8bq5YvwqoMGYRAnTNZVOCVCKRM
	 Yjuxdh88t6+NCjaJhlCxu6NjFfD9kyGnVV6XvqOYAzcNRxRwg9uEUTVULoRj5Io46g
	 eVSXuhYk5kyu0LiNpPR08BDBWTMItfQ+qT+hdHnI=
