### ISSUE TITLE
NZBGetPostProcess: IOError: [Errno 22] invalid mode ('a') or filename:

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#221]
After updating the script four days ago, every single download made with NZBget for Sonarr or CouchPotato on Windows 2012 R2 Server is erroring.

Here are the logs from NZBget...

Kind | Time | Text
-----|------|-----
error | Fri Mar 20 2015 12:31:53 | Post-process-script NZBGetPostProcess.py for xxxxxxxxxx.S01E01.HDTV.x264-LOL-NZBgeek failed (terminated with unknown status)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: IOError: [Errno 22] invalid mode ('a') or filename: 'C:\\\x07utoProcess\\info.log'
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: stream = open(self.baseFilename, self.mode)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\__init__.py", line 936, in _open
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: StreamHandler.__init__(self, self._open())
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\__init__.py", line 911, in __init__
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: logging.FileHandler.__init__(self, filename, mode, encoding, delay)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: h = klass(*args)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\config.py", line 163, in _install_handlers
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: handlers = _install_handlers(cp, formatters)
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\Python27\lib\logging\config.py", line 85, in fileConfig
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: fileConfig(os.path.join(MP4folder, 'logging.ini'), defaults={'logfilename': os.path.join(MP4folder, 'info.log')})
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: File "C:\autoProcess\NZBGetPostProcess.py", line 65, in <module>
info | Fri Mar 20 2015 12:31:52 | NZBGetPostProcess: Traceback (most recent call last):
info | Fri Mar 20 2015 12:31:52 | Executing post-process-script NZBGetPostProcess.py for xxxxxxxxxx.S01E01.HDTV.x264-LOL-NZBgeek
info | Fri Mar 20 2015 12:31:52 | Move for xxxxxxxxxx.S01E01.HDTV.x264-LOL-NZBgeek successful
info | Fri Mar 20 2015 12:31:52 | Moving completed files for xxxxxxxxxx.S01E01.HDTV.x264-LOL-NZBgeek
info | Fri Mar 20 2015 12:31:51 | Cleanup for xxxxxxxxxx.S01E01.HDTV.x264-LOL-NZBgeek successful

The folder the this script is stored in is C:\autoProcess\ and this is what is MP4_FOLDER is set as.  I've moved the script for NZBget to the script folder at C:\Program Files (x86)\NZBGet\scripts .

I've updated the script, no change.  Any assistance you can give would be appreciated.  I couldn't see where the best place to post this would be, so posted it here on GitHub.

**Comment by KaHooli** [comment]
I fixed the issue, needed MP4_FOLDER to be C:/autoProcess/ instead.  Not sure if this can be changed in the coding so this isn't needed, or if it should be mentioned in the supporting text next to the field.

**Comment by mdhiggins** [comment]
Hm that's very strange. I use an almost identical windows path to yours (C:\Scripts\ instead of C:\autoProcess\) without this being an issue. However, its easy enough to correct in code so I just pushed a commit that should allow it to work with the backslashes. Try grabbing it and then putting your MP4folder back to `C:\autoProcess\` and let me know.

**Comment by KaHooli** [comment]
Confirmed, all working fine now.  Thanks :)

**Comment by KaHooli** [comment]
When trying to run a manual conversion from a command prompt, I'm getting the same issue as well...
`Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>C:\autoProcess\manual.py --input "G:\Public\Videos\Movies
\xxxxxxxxxxx, The (2014)\The xxxxxxxxxxx.mkv" --auto
Traceback (most recent call last):
  File "C:\autoProcess\manual.py", line 20, in <module>
    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaul
ts={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
  File "C:\Python27\lib\logging\config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "C:\Python27\lib\logging\config.py", line 163, in _install_handlers
    h = klass(*args)
  File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 22] invalid mode ('a') or filename: 'C:\\Users\\Administrator\\\
x07utoProcess\\info.log'

C:\Users\Administrator>`

**Comment by KaHooli** [comment]
After doing some googling, it appeards that the full file name fields may need to be raw strings, [as per this link](http://stackoverflow.com/questions/15598160/ioerror-errno-22-invalid-mode-r-or-filename-c-python27-test-txt), [and this link too](http://www.gossamer-threads.com/lists/python/python/731657).

**Comment by mdhiggins** [comment]
Try the latest commit and see if your issue is resolved

**Comment by ifitzpat** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ian.fitzpatrick@me.com
    Domain ianfitzpatrick.eu has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:54159 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server.budgettopserver.nl with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YZSn1-003fVo-HE
	for ian@ianfitzpatrick.eu; Sun, 22 Mar 2015 00:26:47 +0100
Date: Sat, 21 Mar 2015 16:26:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1426980405;
	bh=nsQ6i6A58S8VgNp1SSh0vVu/XTtRnHZZS99nCCpjsEM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HD9Ni+IgEufaHU9936LNZhRncUqm1FIH+GRbbXT6QBCn94xTBVpKoNhV6uYg7qw8v
	 rbMuLSfPUJFvEwu3LrfS7tEw9hesLIVWd0cD638zSj7rvnLAvgM34oXzItRwPq7hDm
	 Z+bQxTIV/+KShfRv2OhVmfjJ65ACG6F/1+XC9dDE=

**Comment by KaHooli** [comment]
Thanks, the [latest commit](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/3c6d28533ab253ad9639b47e314c887e8c7625b8) seems to have fixed the issue.  Really appreciate the fast response :)
