### ISSUE TITLE
more than Audio track are enabled.

### ISSUE THREAD

**Issue by andyblac** [mdhiggins/sickbeard_mp4_automator#223]
when adding AAC audio (IOS) the resulting file has both AAC & AC3 audio tracks enabled. this make OS X QuickTime playing both audio tracks at same time.

could you disable all other audio tracks except first AAC.

thanks.

Andy.

**Comment by mdhiggins** [comment]
This is the intended behavior. If you want just AAC stereo, rather than using the iOS audio track which is designed to create an additional track, just set your audio-codec to 'aac' and your max channels to '2'.

**Comment by andyblac** [comment]
sorry you do not understand me, i do want both tracks, but it leaves both track enabled, so QuickTime player plays both tracks at same time.  found issue though seem to be a BUG in FFMPEG itself

https://trac.ffmpeg.org/ticket/3622

**Comment by ifitzpat** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ian.fitzpatrick@me.com
    Domain ianfitzpatrick.eu has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:60374 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server.budgettopserver.nl with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YbvU3-002dNa-9m
	for ian@ianfitzpatrick.eu; Sat, 28 Mar 2015 19:29:24 +0100
Date: Sat, 28 Mar 2015 11:29:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1427567361;
	bh=TTdkFT/5w13N9hKz5TBzio2SEw/y8gfm8X4L+j/d1uw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RRYdJkV8FtSpaSj7912+Bnd8bE6ZDQfHNI8lgbbzBEJtGeTCswM57nPGdZGpj6AJV
	 fIBIJvZiP+lX2K6xNJZih7jARutD8n7nEl41M/zSGy8bHxo/IwbhCRzrWWNkbZrXAs
	 P7Fbr63Uy9vuaEgroQJPVfClrtK+DcHuVBbMCQEU=

**Comment by mdhiggins** [comment]
Oh gotcha, yeah its an FFMPEG limitation unfortunately, nothing that can be done from the scripting side until its resolved. Sorry about that. You can always apply the patch and build ffmpeg from that modified source. Hopefully they'll merge that fix in soon.

**Comment by andyblac** [comment]
found a patch, trying it now, will let you know.

rename attached file back to .patch file extension.

![ffmpeg-2 3 3-defaultstreams](https://cloud.githubusercontent.com/assets/77936/6882339/c5bce63a-d578-11e4-941e-8e7584919cc0.png)

**Comment by andyblac** [comment]
whilst we discussing Audio do you supported DTS-HD, DD TureHD, DD+ ?

**Comment by mdhiggins** [comment]
```
diff --git a/libavformat/movenc.c b/libavformat/movenc.c
index b3287ca..1107a5b 100644
--- a/libavformat/movenc.c
+++ b/libavformat/movenc.c
@@ -3773,23 +3773,43 @@ static void enable_tracks(AVFormatContext *s)
             st->codec->codec_type >= AVMEDIA_TYPE_NB)
             continue;

+        // note the first stream number for each type
         if (first[st->codec->codec_type] < 0)
             first[st->codec->codec_type] = i;
-        if (st->disposition & AV_DISPOSITION_DEFAULT) {
-            mov->tracks[i].flags |= MOV_TRACK_ENABLED;
-            enabled[st->codec->codec_type]++;
-        }
+
+        // note whether each media type has any enabled streams
+        if (st->disposition & AV_DISPOSITION_DEFAULT)
+            enabled[st->codec->codec_type] = 1;
+
+        // clear the enables for each stream and track
+        st->disposition &= ~AV_DISPOSITION_DEFAULT;
+        mov->tracks[i].flags &= ~MOV_TRACK_ENABLED;
     }

+     // for each media type, if no stream was explicitly enabled
+    // then enable the first one found for that type
     for (i = 0; i < AVMEDIA_TYPE_NB; i++) {
         switch (i) {
         case AVMEDIA_TYPE_VIDEO:
         case AVMEDIA_TYPE_AUDIO:
         case AVMEDIA_TYPE_SUBTITLE:
-            if (enabled[i] > 1)
-                mov->per_stream_grouping = 1;
             if (!enabled[i] && first[i] >= 0)
+                enabled[i] = 1;
+            break;
+        }
+    }
+
+    // translate the first enabled stream of each media type
+    // into its stream being default and its output track being enabled
+    for (i = 0; i < AVMEDIA_TYPE_NB; i++) {
+        switch (i) {
+        case AVMEDIA_TYPE_VIDEO:
+        case AVMEDIA_TYPE_AUDIO:
+        case AVMEDIA_TYPE_SUBTITLE:
+            if (enabled[i]) {
+                s->streams[first[i]]->disposition |= AV_DISPOSITION_DEFAULT;
                 mov->tracks[first[i]].flags |= MOV_TRACK_ENABLED;
+            }
             break;
         }
     }
```

And I haven't built in any support for those specifically. If FFMPEG supports it though adding support  wouldn't be difficult.

**Comment by andyblac** [comment]
HandBreak does, so i would assume ffmepg does.

**Comment by andyblac** [comment]
'''    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709), 1920x794 [SAR 1:1 DAR 960:397], 29.97 fps, 29.97 tbr, 1k tbn, 180k tbc (default)
    Metadata:
      BPS             : 12897496
      BPS-eng         : 12897496
      DURATION        : 01:41:45.132000000
      DURATION-eng    : 01:41:45.132000000
      NUMBER_OF_FRAMES: 146377
      NUMBER_OF_FRAMES-eng: 146377
      NUMBER_OF_BYTES : 9842615138
      NUMBER_OF_BYTES-eng: 9842615138
      _STATISTICS_WRITING_APP: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2015-01-24 11:59:13
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-01-24 11:59:13
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Stereo
      BPS             : 160045
      BPS-eng         : 160045
      DURATION        : 01:41:45.023000000
      DURATION-eng    : 01:41:45.023000000
      NUMBER_OF_FRAMES: 286173
      NUMBER_OF_FRAMES-eng: 286173
      NUMBER_OF_BYTES : 122134851
      NUMBER_OF_BYTES-eng: 122134851
      _STATISTICS_WRITING_APP: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2015-01-24 11:59:13
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-01-24 11:59:13
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : Dolby TrueHD
      BPS             : 640000
      BPS-eng         : 640000
      DURATION        : 01:41:45.056000000
      DURATION-eng    : 01:41:45.056000000
      NUMBER_OF_FRAMES: 381566
      NUMBER_OF_FRAMES-eng: 381566
      NUMBER_OF_BYTES : 488404480
      NUMBER_OF_BYTES-eng: 488404480
      _STATISTICS_WRITING_APP: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.3.0 ('Nouages') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2015-01-24 11:59:13
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-01-24 11:59:13
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
'''

**Comment by mdhiggins** [comment]
Are you trying to encode or decode the TrueHD format? (or any of the other formats)

**Comment by andyblac** [comment]
just tested manually,

```
ffmpeg -i 16.Blocks.2006.1080p.HDDVD.Dolby.Digital.Plus.mkv -c:v copy -c:a libfdk_aac -b:a 128k output.mp4
```

it does convert audio to AAC.

**Comment by mdhiggins** [comment]
Nice so that should work as it is already. Decoding doesn't require anything fancy on the part of the script. 

To encode to some of those codecs would require some additional code. Seems like FFMPEG has limited encoder support for some of these though, hard to find a clear answer.

**Comment by andyblac** [comment]
patched worked btw. :D

**Comment by mdhiggins** [comment]
Excellent!

If it wouldn't be too much trouble, you should toss a quick instructional on the wiki for other people that use Quicktime and are having this issue. You're not the first person to ask about this and it'd be nice to point them to it.

**Comment by andyblac** [comment]
yeah, will do, i built it for my Synology NAS.

**Comment by andyblac** [comment]
seems TRUEHD is not supported.

```
[mp4 @ 0x1a0c440] Could not find tag for codec truehd in stream #2, codec not currently supported in container
````
