### ISSUE TITLE
manual.py ignoring "tagfile = False" directive

### ISSUE THREAD

**Issue by KurtisVargas** [mdhiggins/sickbeard_mp4_automator#224]
I'm not sure if it's by design but in manual.py in auto mode (-a) always tags files if it can, regardless of the "tagfile" directive.  If this is by design, maybe an option to manual.py to not tag files?

**Comment by mdhiggins** [comment]
Ignoring the `tagfile` option in autoProcess.ini was by design, but I agree there needs to be a switch for manual.py

Just pushed an update 9ba99e38a7732e0fe3f7b85d4d923ed1689c8fda that adds the `-nt / --notag` options. Should fix this issue.
