### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4

### ISSUE THREAD

**Issue by andyblac** [mdhiggins/sickbeard_mp4_automator#229]
getting this error in SickRage when trying to post process 'Hawaii Five-0', here error.

```
AAUnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 63: ordinal not in range(128)
AA    self.log.debug("%s is valid." % inputfile)
AA  File "/volume1/homes/sickrage/scripts/mp4_automator/mkvtomp4.py", line 191, in validSource
AA    if MkvtoMp4(settings).validSource(inputfile):
AA  File "/volume1/homes/sickrage/scripts/mp4_automator/postConversion.py", line 35, in <module>
AATraceback (most recent call last):
2015-04-04 12:52:10 INFO     Thread-38 :: Executing command [u'/volume1/homes/sickrage/scripts/mp4_automator/postConversion.py', u'/volume3/media/TVShows/Hawaii Five-0/Hawaii.Five-0.S05E20.Ike.H\u0101nau.1080p.WEB-DL.mkv', u'/volume2/downloads/Complete/TVShows/Ready/Hawaii.Five-0.S05E20.1080p.WEB-DL.DD5.1.H.264.HKD.mkv', '164541', '5', '20', '2015-04-03']
```

**Comment by andyblac** [comment]
think it is file name 'Hawaii.Five-0.S05E20.Ike.Hānau.1080p.WEB-DL.mkv'

**Comment by andyblac** [comment]
ok, SickRage rename back as part of post process before the script gets chance to process. could you look into to foreign character's in filenames.

**Comment by mdhiggins** [comment]
This will take some time. I've been looking to migrate the script over to a point where it supports python 3 which has much better unicode support. Perhaps its time for me to revisit that option.

**Comment by andyblac** [comment]
thanks, keep up the good work, btw where can i donate ?

**Comment by mdhiggins** [comment]
You can donate via paypal to tehpsyc@gmail.com

Its always appreciated!
The python 3 migration is underway, been pushing small commits mostly for syntax adjustments. In the process of trying to update mutagen to the latest build and re-add some of the changes I made years ago to support the full range of tagging options. So far the script is working up until tagging in python 3. Once mutagen is updated it should be much closer.

**Comment by andyblac** [comment]
donation sent, keep up the good work.

**Comment by mdhiggins** [comment]
Much appreciated! I’ll keep you posted on the python 3 update. Hopefully not too much longer. Mutagen looks to be working now.


—

**Comment by Deddiekoel** [comment]
I have this issue as well on my Synology but only when running it from a cronjob. When I run it from commandline (BusyBox) everything runs fine.

    Subtitle detected for stream #3: dvdsub [dut].
    An unexpected error occurred, processing of this file has failed
    'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
    Traceback (most recent call last):
      File "/volume1/video/tools/sickbeard_mp4_automator/manual.py", line 346, in <module>
    main()
      File "/volume1/video/tools/sickbeard_mp4_automator/manual.py", line 316, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile)
      File "/volume1/video/tools/sickbeard_mp4_automator/manual.py", line 223, in walkDir
    for r,d,f in os.walk(dir):
      File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
      File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
      File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)

**Comment by thezoggy** [comment]
its due to your locale...  just fix that to support utf-8 and you'd be fine. 
do `locale` from command line.. you will see its probably set to C or ascii.. do `locale -a` to see what your options are on the box... then set it to the correct one via your shell/config.. something like en_US.utf-8

**Comment by thezoggy** [comment]
what @mdhiggins could do is add a check and just force utf8 if it can.. and eventually exit out if it cant.. this is what we did in sickbeard on startup to work around people not setting up their env...

code is adapted from sickbeard, untested but should work :)
```
    SYS_ENCODING = None
    try:
        locale.setlocale(locale.LC_ALL, "")
        SYS_ENCODING = locale.getpreferredencoding()
    except (locale.Error, IOError):
        pass

    # For OSes that are poorly configured I'll just randomly force UTF-8
    if not SYS_ENCODING or SYS_ENCODING in ('ANSI_X3.4-1968', 'US-ASCII', 'ASCII'):
        SYS_ENCODING = 'UTF-8'

    if not hasattr(sys, "setdefaultencoding"):
        reload(sys)

    try:
        # pylint: disable=E1101
        # On non-unicode builds this will raise an AttributeError, if encoding type is not valid it throws a LookupError
        sys.setdefaultencoding(SYS_ENCODING)
    except:
        sys.exit("Sorry, your environment is not setup correctly for utf-8 support. Please fix your setup and try again!")
```

**Comment by theeddie** [comment]
Any movement on this ?

**Comment by thezoggy** [comment]
@theeddie https://github.com/mdhiggins/sickbeard_mp4_automator/commit/ac2e255a75817ddb3f12c6aba41f49d463f75bc5 ? looks like this was already addressed

**Comment by mdhiggins** [comment]
Just pushed that update less than an hour ago. But yes it should be addressed now.

Additionally, over the last month I've been slowly updating all the dependencies and making changes to the code to make everything Python 3 compatible. Initial testing looks like most of the features are working without issue. There are some small cosmetic bugs that will need to be addressed and I'm sure lots of bugs will crop up but I'm able to convert and tag on my test setup under python3 without any errors at the moment.

Feel free to start testing. I'll create a separate issue for python 3 testing/bugs but just wanted to give the heads up now.

**Comment by mdhiggins** [comment]
#349
