### ISSUE TITLE
Where is CPProcess.py located?

### ISSUE THREAD

**Issue by OskarPersson** [mdhiggins/sickbeard_mp4_automator#232]
In the CouchPotato section in the readme it says
> * Edit main.py in the setup\PostProcess folder
    * Set the path variable to the script location
    * By default it points to C:\\Scripts\\
    * Use double backslashes

and in main.py it says

```
# Edit to point to the absolute path where the CPProcess.py script resides
path = "C:\\Scripts\\"
```

Where is CPProcess.py usually located?

**Comment by mdhiggins** [comment]
Just ignore that comment in the main.py file, its outdated. Just point the path variable to your scripts folder like in the readme. I'll update the comment.

**Comment by OskarPersson** [comment]
Which is the scripts folder? What does it contain?
