### ISSUE TITLE
video-bitrate compares against total-bitrate instead of just video-bitrate

### ISSUE THREAD

**Issue by KurtisVargas** [mdhiggins/sickbeard_mp4_automator#236]
This is easy to duplicate - set video-bitrate to any value and then rerun the script on the output file.  The script will detect the outputed file's bitrate as too high and convert it again.

In mkvtomp4.py I edited the debug line to be:
>self.log.debug("Overriding video bitrate. Codec cannot be copied because video bitrate is too high. [%d > %d]" % (info.format.bitrate/1000, self.video_bitratte))

Re-running on the output file results in (video-bitrate is 2048)

>2015-04-05 23:11:46 - MANUAL - DEBUG - Overriding video bitrate. Codec cannot be copied because video bitrate is too high. [**2691** > 2048]

You can see that the converted file was made correctly (1984kbs with 2048 video-bitrate) from the output of ffprobe below:
>Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/smb/media/Temp/TEST.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.26.101
  Duration: 00:36:09.26, start: 0.021333, bitrate: **2691 kb/s**
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, **1984 kb/s**, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 442 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

I tried figuring out how to get to the actual bitrate of the video portion but I can't figure it out.

**Comment by mdhiggins** [comment]
Yeah that's the issue. FFProbe doesn't return any bitrate values for video streams, so I've had to work off the total bitrate. That being said, I could probably write a function that loops through the audio streams and adds up the bitrates, then subtracts those values from the total bitrate to get a rough approximation of the video stream bitrate. Think that would work?

**Comment by mdhiggins** [comment]
a6e9bc044ff4f2df0c29830336625966ee4ea116 this commit estimates the video bitrate using the technique outlined above. Let me know how that behavior works for you.

**Comment by KurtisVargas** [comment]
Thanks!  Ran it through about 300+ files and it runs remarkably well.  The estimation calculation is quite good.  Estimated bitrate seem to run slightly high ~1%-4% about 20% of the time but adding in a 5% "fudge-factor" for bit-rate comparison yields 100% success which I think is quite reasonable.
For example:
>if self.video_bitrate is not None and vbr > **(self.video_bitrate*1.05)**

**Comment by mdhiggins** [comment]
Just pushed another commit to have the estimate by 95% of what it was originally estimating, should be similar to the equation you provided and provide a better success rate. Lemme know if that's working on your end.

**Comment by KurtisVargas** [comment]
Re-ran with your change and over 200 files with 100% success.  Great solution and thanks!
