### ISSUE TITLE
Failure to handle corrupted files

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#237]
HI,

I've previously talked about this issue <a href="http://sickbeard.com/forums/viewtopic.php?f=9&t=6425&sid=8480679e85da956a91807e57426657de&start=450#p47067">here</a>, but haven't seen much activity over on the forum. 
On that rare occasion when a corrupted video file has been successfully downloaded and has been passed to the script, it seems to attempt a conversion but always returns with the error:
<b>"Exit(1) AttributeError: ’NoneType’ object has no attribute ’video’ " </b>
but then passes the file into Sickbeard or Couchpotato. I was wondering if it was possible, upon receiving that error that the script could delete the file and simply quit.

**Comment by stevepork** [comment]
as a side question, what IDE do you use?

**Comment by mdhiggins** [comment]
Just generally just do everything in Atom (as of a few weeks ago). I used to use SublimeText but Atom is free and open source so it wins.

https://atom.io/

**Comment by JohnMaree** [comment]
I think I may be able to help, but one question, was that video file a TV Show? And if it was, was it downloaded before the airdate?

**Comment by StevenChorkley** [comment]
Both and both.

Sent from a mobile device.
http://www.chorkley.co.uk/

**Comment by JohnMaree** [comment]
Ah ha that's good news! (Obviously not good but it's good that we can fix it) 

This might not be the perfect work around but I had the same issue when sickbeard snatched a fake Game of Thrones episode of season 5 before the airdate! I had tried at lease 3 times to re-download the file but the file was corrupt. Unfortunately a problem with sickbeard is that there is no option to tell sickbeard to only search for downloads after they have been aired!! How silly! 

So I spent about 2 days pulling my hair out looking at code I don't understand (I have not much knowledge in coding) but I thought about it and sickbeard must have a way to decide how/what it decides to look for to download, ie. If an episodes' STATUS is either 'downloaded' or 'skipped', what tells sickbeard not to search for that episode? 

Anyway; mdhiggins correct me if I'm wrong,

Goto your sickbeard folder(not the sickbeard-mp4-master one) and find your tv.py. (Shutdown sickbeard before making these changes by the way) 
Scroll around just past half way through the code and you'll see lines that say if episode_status or something similar and change the code to include the 'unaired' status in the if statement that returns a false and take the 'unaired' status away from the if statement that returns true. Then save and test 

Tell me if you need better instructions

**Comment by StevenChorkley** [comment]
I recently changed to sickrage, that software only downloads releases after
the air date. Sometimes those files are still corrupt (but your solution
certainly would reduce the amount of corrupt files.)

Maybe it'd be a good idea to include your suggestion in the readme file?
However the issue does still persist, just nowhere near as often.

Sent from a mobile device.
http://www.chorkley.co.uk/

**Comment by HazCod** [comment]
@StevenChorkley could you provide the full stacktrace? I will fix it, but need to know where to look.
