### ISSUE TITLE
No module named stevedore

### ISSUE THREAD

**Issue by wreckedred** [mdhiggins/sickbeard_mp4_automator#241]
I updated this morning and get this error:

Total download size: 824M 
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Processing file /home/wreckedred/tera-one/media/dev/rawintv/stretch.2014.dvdrip.x264.ac3.rosubbed-playsd/Stretch.2014.DVDRip.x264.AC3.RoSubbed-playSD.mkv
An unexpected error occurred, processing of this file has failed
No module named stevedore
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.

Is there something I can do to fix?

**Comment by mdhiggins** [comment]
Install stevedore

`pip install stevedore`

You'll also need python-dateutil

`pip install python-dateutil`

If you don't have pip, see here: https://pip.pypa.io/en/latest/installing.html

**Comment by wreckedred** [comment]
Worked great - no issue now - thank you

**Comment by mdhiggins** [comment]
No prob
