### ISSUE TITLE
Manual Tagging error

### ISSUE THREAD

**Issue by dingho** [mdhiggins/sickbeard_mp4_automator#242]
I'm using the manual.py script and specifying the show.

Example:
manual.py -i e:\30 Rock\ -a -tv 79488

It is tagging the show as "Rock" tvdb id 74858, even though I've specifically input it is 79488.

**Comment by mdhiggins** [comment]
Looks like this was an unintended bug causing by updating to the latest tvdb_api.

Should be fixed now, give it a try

**Comment by dingho** [comment]
Seems to be fixed.  Thank you!
