### ISSUE TITLE
File handling issues / confusion with delete_original=false

### ISSUE THREAD

**Issue by KurtisVargas** [mdhiggins/sickbeard_mp4_automator#243]
There's a couple of instances of switch combinations that cause unexpected behavior.  Might just be worth documenting them.

For these scenarios assume options are blank or default unless I specify them.  In all cases, src file is an mp4, convert-mp4=true, delete_original=false
1) move_to=/path  
For #1, I would expect that the original is left alone but what happens is that the source is deleted because the move_to code doesn't respect keeping the original safe.  
For resolution, I propose when delete_original=false and move_to is set without an output_directory then either A) Error out,  B) Use a temporary file in source and move that, or C) Change the move_to variable to the output_directory variable and use the move_to folder as the working space.

2) Either no paths set OR just copy_to=/path
For #2, remembering that delete_original=false, I would expect that this should just fail in some way.  What actually happens is that it both converts the file in place and also leaves a ".tmp." file behind in the input folder.  This can create an infinite loop (until maxpath is exceeded at least) when processing a folder.
For resolution, I think this should just fail and not process the file.  

There's actually more combinations that cause issues but they all come back to these two problems.  

After typing this up and thinking on it more, I'm wondering if when input & output extensions are the same, then delete_original=false should only be allowed when either output_directory or move_to is set (and with move_to use a temporary file somewhere).

As always, thanks for creating and sharing this project!

**Comment by mdhiggins** [comment]
Issue 1 definitely sounds more like a bug. I adjusted the renaming behavior to, instead of renaming the original file, to just append (#) to the output file. Things seem to be working on my end with move-to enabled, delete-original false,

There's no reason to manipulate the move-to/output directories when delete original is false and move-to is enabled. The normal expected behavior would be to create the new file in the same location as the source, then when everything is completely only move the newly created file. Now that the source isn't being renamed with a .tmp the original should be untouched.

Still working on issue 2

**Comment by mdhiggins** [comment]
Issue 2 I don't think is as much of an issue. When python walks a directory, its my understanding that its iterating over files that existed at the time the walk was started (so any new files that were added will not be seen) preventing any infinite loop issues from occurring.

**Comment by KurtisVargas** [comment]
I can reproduce #2 on a NAS.  Shouldn't happen I know but it does.  I'm going to retest with your last patch.

So in my never-ending quest to close the final outstanding major issue in making your scripts the end-all-be-all in media conversion scripts, how about the patch below?  The patch below enables manual.py to check for the output file and skipping the input file if it exists.  This allows massive library conversions to run without any issues and replaces the previous hacks.

.patch file
```
--- C:/Apps/sb4/manual.py	Sun Apr 12 16:07:53 2015
+++ C:/Apps/sickbeard_mp4_automator/manual.py	Sun Apr 12 16:09:44 2015
@@ -158,11 +158,33 @@
         print("Matched TV episode as %s (TVDB ID:%d) S%02dE%02d" % (series.encode(sys.stdout.encoding, errors='ignore'), int(tvdbid), int(season), int(episode)))
     except:
         print("Matched TV episode")
     return 3, tvdbid, season, episode
 
-
+def getOutputPath(inputfile, outputpath, relativePath=None):
+    input_dir, filename, input_extension = MkvtoMp4(settings, logger=log).parseFile(inputfile)
+    dst = os.path.join(outputpath, relativePath) if relativePath else outputpath
+    try:
+        outputfile = os.path.join(dst.decode(sys.getfilesystemencoding()), filename.decode(sys.getfilesystemencoding()) + "." + settings.output_extension).encode(sys.getfilesystemencoding())
+    except:
+        outputfile = os.path.join(dst, filename + "." + settings.output_extension)    
+    return outputfile
+
+def checkSkip(inputfile, relativePath=None):
+    #checks if any of the potential output files exist
+    if settings.skip:
+        if settings.moveto:
+            outputfile = getOutputPath(inputfile, settings.moveto, relativePath)
+            if os.path.exists(outputfile): return outputfile
+        if settings.copyto:
+            outputfile = getOutputPath(inputfile, settings.copyto, relativePath)
+            if os.path.exists(outputfile): return outputfile
+        if settings.output_dir:
+            outputfile = getOutputPath(inputfile, settings.output_dir, False)    #relativePath doesn't apply for output_dir
+            if os.path.exists(outputfile): return outputfile
+    return None
+        
 def processFile(inputfile, tagdata, relativePath=None):
     # Gather tagdata
     if tagdata is False:
         return # This means the user has elected to skip the file
     elif tagdata is None:
@@ -188,11 +210,15 @@
         tagmp4 = Tvdb_mp4(tvdbid, season, episode, language=settings.taglanguage, logger=log)
         try:
             print("Processing %s Season %02d Episode %02d - %s" % (tagmp4.show.encode(sys.stdout.encoding, errors='ignore'), int(tagmp4.season), int(tagmp4.episode), tagmp4.title.encode(sys.stdout.encoding, errors='ignore')))
         except:
             print("Processing TV episode")
-
+    if settings.skip:
+        outputfile = checkSkip(inputfile, relativePath)
+        if outputfile:
+            print ("File skipped. Destination file %s exists" % (outputfile))
+            return
     # Process
     if MkvtoMp4(settings, logger=log).validSource(inputfile):
         converter = MkvtoMp4(settings, logger=log)
         output = converter.process(inputfile, True)
         if tagmp4 is not None:
@@ -242,10 +268,11 @@
     parser.add_argument('-tmdb', '--tmdbid', help="Specify theMovieDB ID for a movie")
     parser.add_argument('-nm', '--nomove', action='store_true', help="Overrides and disables the custom moving of file options that come from output_dir and move-to")
     parser.add_argument('-nc', '--nocopy', action='store_true', help="Overrides and disables the custom copying of file options that come from output_dir and move-to")
     parser.add_argument('-nd', '--nodelete', action='store_true', help="Overrides and disables deleting of original files")
     parser.add_argument('-nt', '--notag', action="store_true", help="Overrides and disables tagging when using the automated option")
+    parser.add_argument('-k', '--skip', action="store_true", help="Skip processing if output exists.  Requires move_to,copy_to, or output_directory.")
     parser.add_argument('-pr', '--preserveRelative', action='store_true', help="Preserves relative directories when processing multiple files using the copy-to or move-to functionality")
     parser.add_argument('-cmp4', '--convertmp4', action='store_true', help="Overrides convert-mp4 setting in autoProcess.ini enabling the reprocessing of mp4 files")
 
     args = vars(parser.parse_args())
 
@@ -280,10 +307,18 @@
             path = glob.glob(path)[0]
         except:
             pass
     else:
         path = getValue("Enter path to file")
+
+    if(args['skip']):
+        if(not settings.moveto and not settings.output_dir and not  settings.copyto):
+            print("--skip requires either 'output_directory', 'copy_to' or 'move_to' to be set")
+            return
+        else:
+            print("Will skip processing if an output file already exists")
+            settings.skip = True
 
     if os.path.isdir(path):
         tvdbid = int(args['tvdbid']) if args['tvdbid'] else None
         walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=tag)
     elif (os.path.isfile(path) and MkvtoMp4(settings, logger=log).validSource(path)):
```

**Comment by KurtisVargas** [comment]
I've tested this patch (along with the last patch of yours for handling files) on about 1100 full length files and it's working great.  The coolest part is that I've been able to have 4 machines running using the same script on the same set of files.  When there is a conflict it's detected as an existing file and the machine goes to the next file.
