### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'video'

### ISSUE THREAD

**Issue by greghesp** [mdhiggins/sickbeard_mp4_automator#244]
First of all, I've found a similar issue to this below, however I have updated ffmpeg and ffprobe, but I still have the same issue using the automated solution or the manual.py
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/83

```
Traceback (most recent call last):
  File "C:\Scripts\sickbeard_mp4_automator-master\sabToSickBeardwithConverter.py", line 22, in <module>
    converter.process(inputfile)
  File "C:\Scripts\sickbeard_mp4_automator-master\mkvtomp4.py", line 103, in process
    options = self.generateOptions(inputfile, original=original)
  File "C:\Scripts\sickbeard_mp4_automator-master\mkvtomp4.py", line 178, in generateOptions
    print "Video codec detected: " + info.video.codec
AttributeError: 'NoneType' object has no attribute 'video'
```

I've actually tried this with some other tools, and they seem to have a similar issue, although their issues are nondescript.

I've had quite a few files do this as of late to be honest.  Within the download, there is usually a readme about if the file can't play, use the included version of VLC.  Obviously this isn't the solution here though.

Has anyone got any ideas?

**Comment by mdhiggins** [comment]
This is usually a result of the file you are trying to process not being able to be read by FFMPEG. If you're getting this consistently with every file then I'd say its a different problem, but if its just sporadic its likely the files are corrupted or at least poorly made. VLC can sometimes play them because VLC can play file fragments and all kinds of messed up files, but FFMPEG isn't as forgiving.

**Comment by greghesp** [comment]
Thanks.  Must be a hell of a lot of videos at the moment like this then.  I must get at least 1 in 10 have this issue

**Comment by mdhiggins** [comment]
Feel free to send me one of the source videos that isn't working and I'll take a look and see if I can identify what's going on. 



—

**Comment by viearical** [comment]
I've been hitting this on a lot of the video's I've been having the script attempt to convert from sickbeard.  What's the best way to send you a file?

**Comment by mdhiggins** [comment]
Just upload it it somewhere and send me a link and I’ll take a look


—

**Comment by viearical** [comment]
Sure thing, should be able to grab a sample video with the issue here http://bit.ly/1RZtXev

**Comment by viearical** [comment]
Nevermind... turned out to be an ffmpeg issue, which I should have troubleshooted earlier.  Apparently my ffmpeg binary got botched during a brew upgrade, I uninstalled and reinstalled and it's working as expected now for me ...my bad :-)

**Comment by mdhiggins** [comment]
No worries. I would take that link down now just since I suspect there's copyrighted material on it



—
