### ISSUE TITLE
SABNZBD to Sonarr

### ISSUE THREAD

**Issue by beerygaz** [mdhiggins/sickbeard_mp4_automator#245]
I'm trying to get the SABPostProcess.py script to run to trigger Sonarr to run.  I get the following error in the SAB logs:

[WARNING] Update to Sonarr failed, check if Sonarr is running, autoProcess.ini for errors, or check install of python modules requests.

However, a quick script works fine and produces: Sonarr responds as running.

```
import requests, json
try:
    r = requests.post("http://localhost:8989/api/command", data=json.dumps({'name': 'downloadedepisodesscan', 'path': '/var/downloads/tv'}), headers={'X-Api-Key': 'MY_API'})
    rstate = r.json()
    print "Sonarr responds as "+rstate['state']+"."
except:

    print "Update to Sonarr failed, check if Sonarr is running, your API key, or check install of python module requests."
```

autoProcess.ini looks like:

[Sonarr]
host = 192.168.1.10
port = 8989
web_root =
ssl = 0
apikey = MY_API

Ideas on where to look further?

**Comment by mdhiggins** [comment]
Did you install requests when you set up your system for Sonarr?

`pip install requests`

**Comment by beerygaz** [comment]
Yup. Otherwise my test script would not have worked either right?  

The API key doesn't need to be enclosed I. Quotes or anything does it?

**Comment by mdhiggins** [comment]
No it shouldn't. What you can do is turn on debug level logging (open up your logging.ini file and change the level=INFO to level=DEBUG under the handler_fileHandler section. Then run the SAB script again. You'll get debug logging in your info.log file. Look for the parts being printed by SABPostProcess that say:

```
URL '%s' with payload '%s'.
```

That will show you the url that's being generated and we can see if it differs from your test script that appears to be working.

**Comment by beerygaz** [comment]
I added 

import requests, json

Into the top of the SABPostProcess.py file and everything started working.  

Gavin

**Comment by mdhiggins** [comment]
That's strange because both of those modules are imported in the sonarr.py
file before any of those dependencies are called. Are they missing from
your sonarr.py file for some reason?

**Comment by beerygaz** [comment]
I don’t have a sonarr.py?  The only script that SAB runs is the SABPostProcess.py script (that has the sonarr code in it).

This is the latest version from git.

Gavin.

**Comment by mdhiggins** [comment]
SABPostProcess shouldn't have the sonarr code in it, it should be referencing all its code from sonarr.py which is in the 'autoprocess' subdirectory

The sonarr section of SABPostProcess.py should just look like this

```
elif (category == categories[2]):
    log.info("Passing %s directory to Sonarr." % path)
    sonarr.processEpisode(path, settings)
```

`sonarr.processEpisode()` is being imported from `autoProcess\sonarr.py`

Just want to verify this is what you have in your setup

**Comment by beerygaz** [comment]
I do now that I’ve fetched the latest version from git.  My version had the Sonarr code in the SABPostProcess.py file. This is my fault for not checking I had the latest version before posting.  Beers on me.

>
