### ISSUE TITLE
Deluge + Sonarr Error: Rejected Hashed Release Title

### ISSUE THREAD

**Issue by chrislawrence** [mdhiggins/sickbeard_mp4_automator#246]
I am getting the following error from Sonarr after conversion when the script is trying to send the finished file back:

    Debug|Parser|Rejected Hashed Release Title: 3c107d10d983dec03828ce68d1a2fb8bae5381aa

From what I can tell the script converts the file and puts it into a folder named by the torrent ID. When Sonarr gets the update to process this file, it sees the name of the directory and assumes it is a hashed series title which does not exist, so it's not processing the file.

**Comment by mdhiggins** [comment]
Pushed a commit to use the torrent_name instead of the hashed id as the directory name, lemme know if that resolves your issue.
