### ISSUE TITLE
Feature Request: 1080p HD Tagging - iTunes

### ISSUE THREAD

**Issue by grahamr** [mdhiggins/sickbeard_mp4_automator#249]
I know not everyone does use iTunes, but i was curious if it would be a possible addition to parse the file name for either 720p or 1080p and set the HD flag accordingly

Right now i'm finding some odd import issues on the itunes end because by default the script is setting the "HD" flag (which is 720p in iTunes). WHen importing a TV show that has S1e1 at 720p with no contentID set, and then importing S1e2 at 1080P with no content ID "sometimes" the auto-add to iTunes folder will stack the two files. Viewing them in the file browser shows the correct metadata, but the file names are 01 - Title (HD) and 01 - Title (1080p HD)

If this flag was set, i could finally totally retire my manual app for iTunes tagging :)

**Comment by mdhiggins** [comment]
This should already be done.

```
    def setHD(self, width, height):
        if width >= 1920 or height >= 1080:
            self.HD = [2]
        elif width >= 1280 or height >= 720:
            self.HD = [1]
        else:
            self.HD = [0]
```

has been part of the tagging process for years. I'm guessing something must not be working then. Is this a consistent issue?

**Comment by grahamr** [comment]
i thought that was the case for sure... but it seems hit or miss - but for instance 7 shows yesterday were all "720p" even though 6/7 were 1080p.

i'll do a sync to make sure i have the latest build and see if i can figure out if there is anything common for the files its not working with.

All come from SB to UT then through your script.

**Comment by mdhiggins** [comment]
The files are tagged, correct?

**Comment by grahamr** [comment]
Yep they were tagged otherwise - From memory, the Odd Couple was tagged correctly (720p, all info) but for instance (i think) the flash was not. i will have to watch for a specific title - but i know of everything there are 1-2 titles that tag but stay 720.

Also Marvel's Agent's of S.H.I.E.L.D never tags (due to the periods i assume) which is interesting.

**Comment by grahamr** [comment]
ran the following command:
manual.py -i f:\Download\TV\ -a

manually checking metadata in MkvToMP4 v0.224 shows:

6 files

5 1080p source, 2 tagged 1080p
1 720p source, 4 tagged 720p

Spotted the error.

the 1080 files tagged as 720 are 1916x1076

**Comment by mdhiggins** [comment]
Ah ok, that does make sense then. If you wanted you can change the resolutions in the code I indicated to create a lower tolerance for 720p or 1080p tagging

**Comment by mdhiggins** [comment]
Went ahead and slightly increased the tolerance to 1900x1060 and 1260x700 for the tagging thresholds

Gonna close this

**Comment by grahamr** [comment]
Bingo - the tolerance change sorted it out for 100% of the files
