### ISSUE TITLE
Transmission Support

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#259]
Hi,

I love transmission and have begun to really dislike uTorrent. Is there any future possibility for support?

**Comment by mdhiggins** [comment]
The biggest issue with transmission is that the download managers (SB CP etc) can't set a label when adding content for downloads. These labels are essential for informing the post scripts which program to forward the completed download to. 




I too dislike uTorrent, and if you're open to the idea you should try Deluge (Deluge Daemon specifically). It's an open source torrent client that does support labeling and is already supported by the script. It's a very lightweight client and supports addons to expand functionality.



—
