### ISSUE TITLE
Certain movies are black when viewed on Google Chrome after conversion

### ISSUE THREAD

**Issue by simon2k13** [mdhiggins/sickbeard_mp4_automator#260]
Certain movies have been going black when hardware acceleration is enabled in google chrome.

Apparently this is caused by some movies not having the proper yuv output setting on ffmpeg.

Is there a way to include custom ffmpeg commands such as -pix_fmt yuv420p  to ffmpeg tags when it runs?

**Comment by simon2k13** [comment]
http://stackoverflow.com/questions/9591959/mp4-with-pixel-format-yuvj420p-wont-play-in-chrome-17-but-plays-in-safari-ie

**Comment by mdhiggins** [comment]
Hm, the issue here is that in most cases the videos aren't being converted, since their already h264 and are just copied to the output file. I could include the`-pix_fmt yuvj420p` but unless the script is also checking to see if the video isn't yuvj420p and then disabling copying the stream, it probably won't help for most videos.

**Comment by simon2k13** [comment]
Yes thats exactly what seems to be happening. Its usually on files that are already h264.

Do you recommend i manually run that flag afterwards on my movie folder?

Again, many thanks for everything, you should post a btc address for donations:)

**Comment by mdhiggins** [comment]
I'm gonna look into seeing if ffprobe can query for the pix format, in which case I could could make it an option and have it override the copy setting in the event it doesn't match what you want. I'll get back to you on that.

I'm surprised I haven't run into this issue on Chrome since I direct play all my videos on plex and most of my media isn't re-encoded (just copied). Is it only with certain version of Chrome?

And I should probably set up a bitcoin address haha been meaning to look into that. If you wanna donate and don't mind paypal, my address is tehpsyc@gmail.com

**Comment by mdhiggins** [comment]
Good news. ffprobe can read the pix_fmt value so I can relatively easily check for this and then compare it against a user option. When I get some free time I'll try and put together a solution that will override the copy option.

**Comment by simon2k13** [comment]
Hey, regarding chrome, it happens on the latest version on windows primarilly since hw acceleration is enabled by default. When disabling it, the movies render fine!

**Comment by simon2k13** [comment]
Hi Sir,

Any idea on when you wil release a updated wversion with the pix_fmt value?

many thanks again

**Comment by mdhiggins** [comment]
Sorry was away traveling and busy with graduation and moving. I'll try and take a look at it this weekend.

**Comment by simon2k13** [comment]
Thanks man:)

**Comment by mdhiggins** [comment]
Sorry it took so long.

61150fca79895a4483294ed788ef0e830eac55e7

You can now set `pix-fmt` in autoProcess.ini. Source files that match your desired pix_fmt won't be transcoded, just directly copied, but non-matching pix_fmt will result in transcoding the video to the proper format.

**Comment by simon2k13** [comment]
Thank you very very much! Is there a value that should be set by default for genreal videos?

**Comment by mdhiggins** [comment]
I don't think so. In general leaving it blank will cause the script to behave like it normally did where the pix_fmt is sort of just ignored.

If you're consistently have issues with yuvj420p, then I would just set that value to yuv420p (no j) and let it run. Most videos downloaded will be yuv420p anyway so it will only reprocess video streams that aren't.

**Comment by rdurdle** [comment]
I'm having this same issue now. If I convert an mp4, it's black with normal audio, unless I tell it to change the quality and force a transcode. In which case it works fine...

**Comment by mdhiggins** [comment]
If its an issue where you’re copying the video stream from your source files then it’s probably related to the source video stream. Is the video stream being converted or copied?

**Comment by rdurdle** [comment]
Copied, but if i leave the mp4 (so far its been any mp4, not just a single one) as is, it plays fine in plex.

If I play outside of plex, or transcode, also fine :/ I

**Comment by mdhiggins** [comment]
Post the ffprobe info for both the original working file and the newly generated not working file along with your autoProcess settings and I’ll take a look

**Comment by rdurdle** [comment]
Sure,

here's the before probe..

```

ffprobe file.mp4 
ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 2016-04-17 12:03:00
  Duration: 01:41:45.22, start: 0.000000, bitrate: 1094 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 2016-04-17 11:59:27
      handler_name    : Sound Media Handler
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x720 [SAR 1:1 DAR 4:3], 1026 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2016-04-17 12:03:02
      handler_name    : file.720p.H264.avs.264@GPAC0.5.1-DEV-rev4065

```

The after...

```
ffprobe file.mp4 
ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1645bc0] stream 0, timescale not set
[mjpeg @ 0x1646e60] Changeing bps to 8
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    title           : xxx
    genre           : Adventure
    date            : xxx
    encoder         : MDH:file.mp4
    media_type      : 9
    hd_video        : 1
    description     : xxx
    synopsis        : xxx
    creation_time   : 2016-04-17 12:03:00
  Duration: 01:41:45.22, start: 0.000000, bitrate: 1095 kb/s
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x750 [SAR 300:300 DAR 2:3], 90k tbr, 90k tbn, 90k tbc
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 2016-04-17 11:59:27
      handler_name    : Sound Media Handler
    Stream #0:2(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x720 [SAR 1:1 DAR 4:3], 1026 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2016-04-17 12:03:02
      handler_name    : file.BluRay.720p.H264.avs.264@GPAC0.5.1-DEV-rev4065

```


And the script snippet from the log
```

2017-11-04 15:50:50 - MANUAL - INFO - Manual processor started.
2017-11-04 15:50:50 - MANUAL - INFO - /usr/bin/python
2017-11-04 15:50:50 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-11-04 15:51:06 - MANUAL - INFO - Relocating MOOV atom to start of file.
2017-11-04 15:51:06 - qtfaststart - ERROR - This file appears to already be setup for streaming!
2017-11-04 15:51:06 - MANUAL - WARNING - QT FastStart did not run - perhaps moov atom was at the start already.

```

**Comment by DreadDragoon** [comment]
Any ideas? I just disabled it for now since i think the embedded subtitles are messing with a friends PS4

**Comment by mdhiggins** [comment]
Its probably just the embedded subs. Some of the less robust players can't handle them unfortunately so disabling them might be your only option

**Comment by DreadDragoon** [comment]
no joy,

[image: Inline image 1]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

-- 
http://www.robdurdle.com
---
Would those of you in the cheaper seats clap your hands?
And the rest of you, if you'll just rattle your jewelry.
 - John Lennon
