### ISSUE TITLE
installffmpeg.sh whoami error

### ISSUE THREAD

**Issue by stephenl03** [mdhiggins/sickbeard_mp4_automator#262]
line 24 needs to be changed to `if [ "$(whoami)" != "root" ]; then` the current line causes the script to error and not even install on debian and ubuntu.

**Comment by stephenl03** [comment]
yasm 1.3.0 is now the latest version and needs to be used to compile x264 for Ubuntu 14.04

**Comment by mdhiggins** [comment]
Don't have a linux test machine at the moment and didn't write that script (someone else added it as a pull request) so if you wanna make the changes needed to make it work and do a pull request I'd greatly appreciate it. Gonna be tough for me to update until I can get my testing environment set up again.

**Comment by stephenl03** [comment]
I will make a few other updates to the script tonight and then do a pull request tomorrow once I have tested on another VM.

**Comment by mdhiggins** [comment]
Any updates on this?

**Comment by stephenl03** [comment]
I haven't had a chance to work on it. I got hit with a big project at my old job and just started a new job. Which has been taking up a lot of my time now. So a lot of projects got pushed off to the side.

**Comment by mdhiggins** [comment]
No worries was just checking in, I'm in a similar situation.
