### ISSUE TITLE
ignoring AVI files from conversion

### ISSUE THREAD

**Issue by astlaurent** [mdhiggins/sickbeard_mp4_automator#264]
Hello

it seems that the script works rather well for bringing MKV to MP4 with very little loss or no loss since it is just a container swap. It seems though when i get an AVI mostly the hacked up foreign web rips it takes forever to convert to AVI to MP4 since it really cannot swap the container and must re-encode the whole file. It also seems that sometimes the file size is significantly less with visual loss during this time IE: a 900mb movie will be 400mb after the conversion. I am fine playing AVI on anything that i use as it was mostly MKV giving me problems on roku's. Is there a way to ignore AVI's from the conversion process?

Thank You
Adam

**Comment by mdhiggins** [comment]
If you open up `extensions.py` and remove avi from the list of `valid_input_extensions` that will cause the script to skip over any AVI files.

**Comment by astlaurent** [comment]
ok great. thank you
