### ISSUE TITLE
No QTFS conversion with Sonarr

### ISSUE THREAD

**Issue by cgram23** [mdhiggins/sickbeard_mp4_automator#265]
I have the scripts set up and working fine between Sickrage and SABnzbd, however, I'm looking to move to Sonarr. I can get the files converted, subs ripped, and moved to my TV folder. The only thing missing is the QTFS conversion (moov atom). The only difference between the Sickrage and Sonarr setups is that for Sickrage, my autoProcess.ini has: [SABNZBD] convert = False Whereas the Sonarr config has convert = False (only way I could get the mp4 conversion to happen. I also have relocate_moov = True set for both scenarios. 

autoProcess.ini (http://pastebin.com/nazrjShu)

Working-Sickrage (http://pastebin.com/FHDg46PY)

Failing-Sonarr (http://pastebin.com/YhXpHaEe)

**Comment by mdhiggins** [comment]
This is because the QTFS process is done as part of the tagging procedure. If you tag files, particularly large files, after you’ve moved the moov atoms to the front of the file, you can create corruption issue and playback problems. Because Sonarr doesn’t support post-processing scripts, that final step can’t be executed, and that’s why you have no tagging or QTFS processing. The conversion only takes place because it can be performed before the file is passed back to Sonarr.




Once Sonarr implements post processing this will be fixed, just waiting on them.


—

**Comment by cgram23** [comment]
Thanks for the explanation.  I don't suppose there is a workaround to perform the conversion before passing back to Sonarr?

**Comment by mdhiggins** [comment]
2ed7cc9624cf471a8071b3ecb6b7998d3b037219 should add support for running QTFS on Sonarr destined video files from the 4 downloader scripts (SAB/NZBGet/Deluge/uTorrent). Just make sure its enabled in your autoProcess.ini settings.

Let me know if that works for you.

**Comment by cgram23** [comment]
Bingo.  Worked like a champ...thanks for setting that up!

With the risk of  leeching off of my own post....any way to proactively move SRT files before Sonarr gets it's hands on it?  Sonarr won't move anything except the MP4 file, so the SRT get's deleted.

**Comment by mdhiggins** [comment]
I really want to switch to Sonarr cause the interface looks really nice but these little problems / unfinished features keep me sticking to SB.

Sadly, probably no way to handle preemptively moving the SRT file. If the SRT is named appropriately, the script will embed it into the mp4 file during the conversion process though which should make it safe from Sonarr. Is there no way to tell Sonarr not to delete SRT files? That seems like a large oversight.

**Comment by cgram23** [comment]
Yeah, I can embed the subs just fine, and it works.  The problem is, Roku is my primary Plex client, and it tends to choke on embedded subs.  And Sonarr will delete any file in the download location that is not the video file.  Thanks for the QTFS effort, but I think we need to wait for Sonarr to mature a bit more before it's fully functional.
