### ISSUE TITLE
Video codec detected: hevc or h265?

### ISSUE THREAD

**Issue by Pupwiz** [mdhiggins/sickbeard_mp4_automator#266]
I started to notice these showing up from the downloaders and torrents. I watched the script in action on these and they seem to be taking long periods of time to convert. I was wondering if it needs to or this newer video codec could also just be passed as a copy instead of a complete conversion.

**Comment by mdhiggins** [comment]
That's up to you if you want to convey h265 to h264. You can add h265 to the video codec list in your options if you want it to be copied instead of converted. 



—

**Comment by Pupwiz** [comment]
So to test this out I would just add h265 to this line in the autoProcess.ini
video-codec = h264,x264
would become
video-codec = h264,x264,h265 or  video-codec = h264,x264,hevc

**Comment by zybeon** [comment]
There is very little hardware that supports the new codec(h265) and requires a lot of cpu to decode/encode. I would leave the settings the same, if using Plex,  practically all devices would have the server convert them on the fly and being that they take more power than most other codec will cause noticeable slow downs on low power setups. The Roku 3, chromecast, and Apple TV will all need it converted.

**Comment by mdhiggins** [comment]
I'm not sure how ffmpeg / ffmpeg reads h265 but just to be safe you could set it as follows:

`video-codec = h264,x264,h265,hevc`
