### ISSUE TITLE
Subtitle being ignored

### ISSUE THREAD

**Issue by lucfig** [mdhiggins/sickbeard_mp4_automator#267]
Hi,
I have POB, POR and ENG subtitles in my movies folder. The script ignores the POB subtitles regardless of the autoProcess.ini configuratin.

Is there another option to whitelist it?

Thanks and regards,

**Comment by mdhiggins** [comment]
POB doesn't appear to be on the list of ISO 639-1 codes. What language is that?

**Comment by lucfig** [comment]
It is Brazilian Portuguese. The subtitles are downloaded with filebot.

I will check if is possible to rename POB subtitles to POR instead.

Do you suggest any other solution?

Thanks

**Comment by mdhiggins** [comment]
Yeah it looks like POB isn’t an official 3 letter code and that Brazilian Portuguese doesn’t actually have a 3 letter code. This will likely cause issues because FFMPEG won’t like POB as an input option since its not technically a language. Your best bet is to rename to POR I think.


—

**Comment by lucfig** [comment]
Yes, I will find a way to automatically rename.

Thanks Michael.

Lucas Figueiró

2015-06-12 11:36 GMT-03:00 Michael Higgins <notifications@github.com>:

> Yeah it looks like POB isn’t an official 3 letter code and that Brazilian
> Portuguese doesn’t actually have a 3 letter code. This will likely cause
> issues because FFMPEG won’t like POB as an input option since its not
> technically a language. Your best bet is to rename to POR I think.
>
>
> —
> Sent from Mailbox
>
