### ISSUE TITLE
Add IMDB to filename

### ISSUE THREAD

**Issue by Trixter69** [mdhiggins/sickbeard_mp4_automator#269]
Hello all,

I was looking for and haven't been able to find this feature.

If the file does NOT have a IMDB  id in the filename is it possible to have it added after the conversion?

Thanks loving this script.

**Comment by simon2k13** [comment]
I usually do this with Couchpotato very easily with the renamer but i have yet to find a way to do it in sickbeard.

**Comment by mdhiggins** [comment]
This script doesn't do renaming in any way. Renaming is handled by the media managers. I believe CP does do this though as simon2k13 mentioned.
