### ISSUE TITLE
Duplicate ios-audio streams created on subsequent processing

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#273]
It seems an iOS compatible stream is added every time a file is processed. I seem to have some issue that's causing my files to be processed twice, and I end up with 2x AAC streams and an AC3 stream. If I run manual.py on a file with no AAC stream I get 1 AAC stream. If I run it again I get two streams.

Here's some example output.

```
Reading audio streams.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source audio stream 1.
Audio detected for stream #2: ac3 [eng].
Creating audio stream 1 from source audio stream 2 [iOS-audio].
Creating audio stream 2 from source audio stream 2.
Reading subtitle streams.
Subtitle detected for stream #3: mov_text [eng].
Creating subtitle stream 0 from source subtitle stream 3.
Subtitle detected for stream #4: mov_text [eng].
Creating subtitle stream 1 from source subtitle stream 4.
Subtitle detected for stream #5: mov_text [eng].
Creating subtitle stream 2 from source subtitle stream 5.
{
    "subtitle": {
        "0": {
            "map": 3,
            "codec": "mov_text",
            "language": "eng"
        },
        "1": {
            "map": 4,
            "codec": "mov_text",
            "language": "eng"
        },
        "2": {
            "map": 5,
            "codec": "mov_text",
            "language": "eng"
        }
    },
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "copy",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 2,
            "map": 2,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "2": {
            "channels": 6,
            "map": 2,
            "codec": "copy",
            "bitrate": 1536,
            "language": "eng"
        }
    },
```

I thought perhaps I could set ios-first-track-only = True but that had no effect. Is anyone else affected by this?

As a follow up, it would be good to have an option to delete duplicate tracks, so I could run manual.py again on an entire directory to remove duplicate AAC tracks.

**Comment by mstrelan** [comment]
Actually setting ios-first-track-only = True fixes this for me, I hadn't added it to autoprocess.ini properly. This setting should be documented in README.md and included in autoprocess.ini.sample.

**Comment by mdhiggins** [comment]
Reprocessing any mp4 with the convert-mp4 option enabled along with the iOS-audio option enabled will result in creating additional iOS tracks each time. The script unfortunately had no way to tell that the second audio track is a clone of the surround sound track.

Your best option to avoid double conversion in the situation with an iOS audio and convert mp4 combo is to disable conversion as part of the "post downloaders" and have it done after Sickbeard/CP renames the file and processes it.

**Comment by andyblac** [comment]
maybe label the first track "AAC 2.0 IOS" on procssing, then get the script check for this ?

**Comment by mdhiggins** [comment]
Far as I know there's nowhere to store a label in the MP4 container

**Comment by mdhiggins** [comment]
Gonna close this for now, did some investigation and there doesn't seem to be a way to embed any sort of 'tag' on a given audio stream reliably. If you're gonna reprocess files created with the script again, either disable `convert-mp4` or disable the `ios-audio` options
