### ISSUE TITLE
Re-running script on mp4 adds (2) to filename.

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#274]
Is it possible to use a temporary filename during conversion, then delete the original file, then rename the temporary file one completion? If the temp file extension is .tmp or similar it shouldn't be detected by media scanners like Plex. Alternatively can we have a setting for "processing directory". This would be the equivalent of setting output directory to /tmp and move_to to the current working directory.

**Comment by mstrelan** [comment]
FWIW I can set move_to to ./ and that works (if output directory is somewhere else).

**Comment by mstrelan** [comment]
Unless the script is called from another directory, eg. from Sickbeard.

**Comment by mdhiggins** [comment]
What happens when its called from Sickbeard using the ./ option for move_to?

**Comment by mstrelan** [comment]
Doesn't work :(

I gave up and decided I don't need iOS audio anyway.
