### ISSUE TITLE
Japanese audio track stripped 

### ISSUE THREAD

**Issue by totallyGreg** [mdhiggins/sickbeard_mp4_automator#275]
Love this script.  Ran into an issue where converted mkv with video/audio(jap)/subtitle was turned into m4v with only the video and subtitle (english) track.

my autoProcess.ini has this line:
audio-language = eng,jap,fra

Not sure why it didn't include the japanese audio track but I'm thinking that if there is only one audio track it should be default include it.

**Comment by mdhiggins** [comment]
Gotta set it to jpn not jap
