### ISSUE TITLE
Error on run of script.

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#276]
Everytime the script runs I receive this error

2015-06-12 23:13:54 - SickbeardPostConversion - INFO - Sickbeard extra script post processing started.
2015-06-12 23:13:54 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "/home/steven/.sickbeard_mp4/postConversion.py", line 24, in <module>
    tvdb_id = int(sys.argv[3])
ValueError: invalid literal for int() with base 10: 'Orange.is.the.New.Black.S03E03.720p.WEBRip.x264.DD5.1-FGT'

**Comment by mdhiggins** [comment]
Seems like for whatever reason your sys.argv[3] isn’t the tvdbid like its supposed to be from Sickbeard but is instead passing the name of the release. According to Sickbeard’s documentation this should still be the TVDBID. Are you calling the script from Sickbeard?


—

**Comment by StevenChorkley** [comment]
I'm calling the script from SAB and it's got the tag 'Sickrage'.

**Comment by mdhiggins** [comment]
You’re using the wrong script I think. The postConversion.py script is meant to be called from either Sickbeard or Sickrage as an “extra script” not from SAB. Use SABPostProcess.py instead.


—

**Comment by StevenChorkley** [comment]
I think I've used the wrong script for SAB. I chose 'postConversion' rather than 'SABPostProcess'. 

Sorry!
