### ISSUE TITLE
Use Intel Evansport when available

### ISSUE THREAD

**Issue by davidpfitz** [mdhiggins/sickbeard_mp4_automator#277]
Intel Atom CPUs with and Evansport module can perform hardware transcoding with a handful of codecs. On a Synology DS214play (for example) there is a custom version of ffmpeg which makes use of this CPU module.

It's relatively easy to hack sickbeard_mp4_automator to use this for **en**coding - basically change the codec in avcodecs.py, for example change the lines below to use the hardware encoder:

> ffmpeg_codec_name = 'libx264'
> 
> TO  
> ffmpeg_codec_name = 'h264_smd'

However, what this does not do is use the hardware **de**coder when reading (for example) a WMV file.

For example, this command would use both the hardware decoder and encoder to convert a WMV file to MP4 very quickly:

> ffmpeg -vcodec wmv3_smd INPUT.wmv -acodec copy -vcodec h264_smd OUTPUT.mp4

However, renaming the codecs in avcodecs.py does not input the equivalent of the "-vcodec wmv3_smd" into the ffmpeg command it executes.

Is there any way to get this script to specify the codec to use for the decoding of a file, prior to the encoding in h264? e.g. when ffprobe works out which codec the file is encoded with, specify that to ffmpeg rather than allowing it to work out the codec to use (which defaults to the software one).

Alternatively, is there any way to append an argument to ffmpeg every time it is ran? The flag "-prefer_smd" forces the behaviour to use the hardware encoder / decoder whenever possible.

Here are the codes that are supported by hardware encoding / decoding:

> DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (encoders: h264_smd libx264 libx264rgb )
> D.V.LS h264_smd             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 Hardware(SMD) Decoder
> D.V.L. mpeg2video_smd       MPEG-2 video Hardware(SMD) Decoder
> D.V.L. mpeg4_smd            MPEG-4 part 2 Hardware(SMD) Decoder
> D.V.L. vc1_smd              SMPTE VC-1 Hardware(SMD) Decoder
> D.V.L. wmv3_smd             Windows Media Video 9 Hardware(SMD) Decoder

**Comment by mdhiggins** [comment]
Does the `hwaccel` flag enable this without having to specify each decoder individually?

```
-hwaccel[:stream_specifier] hwaccel (input,per-stream)
Use hardware acceleration to decode the matching stream(s). The allowed values of hwaccel are:

none
Do not use any hardware acceleration (the default).

auto
Automatically select the hardware acceleration method.

vda
Use Apple VDA hardware acceleration.

vdpau
Use VDPAU (Video Decode and Presentation API for Unix) hardware acceleration.

dxva2
Use DXVA2 (DirectX Video Acceleration) hardware acceleration.
```

If that works it would be much easier to implement

**Comment by davidpfitz** [comment]
It appears the sinology build of ffmpeg doesn't contain the hwaccel option - it just gives a "Unrecognized option 'hwaccel'." output when I try to use it.

It appears the "-prefer_smd" option is also a custom option of the synology build of ffmpeg. 

I'll have a try and see if that option forces the right behaviour rather than having to rename the codec in avcodecs.py

**Comment by mdhiggins** [comment]
Any developments with this?

**Comment by davidpfitz** [comment]
Hi, 

Sorry - been really busy at work.

The -hwaccel flag didn’t work, Im afraid. The synology build of ffmpeg (that can use the Intel Evansport transcoder) doesn’t seem to have the hwaccel option. I just get this:

Unrecognized option 'hwaccel'.


David.

**Comment by Deddiekoel** [comment]
Just started working with this and have a DS241play with Evensport.

When I run "ffmpeg -hwaccel" I get an error. However when I run "ffmpeg -prefer_smd" I do not.

**Comment by thezoggy** [comment]
@Deddiekoel its Evansport not Evensport. 
Now per the docs,
http://ffmpeg.org/ffmpeg.html#Advanced-Video-Options

```
-hwaccel[:stream_specifier] hwaccel (input,per-stream)
    Use hardware acceleration to decode the matching stream(s). The allowed values of hwaccel are:

    none
        Do not use any hardware acceleration (the default).
    auto
        Automatically select the hardware acceleration method.
    vda
        Use Apple VDA hardware acceleration.
    vdpau
        Use VDPAU (Video Decode and Presentation API for Unix) hardware acceleration.
    dxva2
        Use DXVA2 (DirectX Video Acceleration) hardware acceleration. 

    This option has no effect if the selected hwaccel is not available or not supported by the chosen decoder.

    Note that most acceleration methods are intended for playback and will not be faster than software decoding on modern CPUs. Additionally, ffmpeg will usually need to copy the decoded frames from the GPU memory into the system memory, resulting in further performance loss. This option is thus mainly useful for testing.

-hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream)
    Select a device to use for hardware acceleration.

    This option only makes sense when the -hwaccel option is also specified. Its exact meaning depends on the specific hardware acceleration method chosen.

    vdpau
        For VDPAU, this option specifies the X11 display/screen to use. If this option is not specified, the value of the DISPLAY environment variable is used
    dxva2
        For DXVA2, this option should contain the number of the display adapter to use. If this option is not specified, the default adapter is used. 

-hwaccels
    List all hardware acceleration methods supported in this build of ffmpeg.
```

now could mimic how nzbtomedia just has a toggle to use hwaccel & offer ability for user to append their own ffmpeg options (advanced usage)
https://github.com/clinton-hall/nzbToMedia/wiki/autoProcessMedia.cfg#transcoder
