### ISSUE TITLE
REQUEST: add option to keep 2 Channel DTS /AC3 audio tracks

### ISSUE THREAD

**Issue by andyblac** [mdhiggins/sickbeard_mp4_automator#278]
as tile i would like to make a request for "add option to keep 2 Channel DTS/AC3 audio tracks", when adding AAC 2 channel track for MKV to MP4

**Comment by c010rb1indusa** [comment]
Agreed. I find stereo AC3/DTS to sound better on home theater systems than stereo AAC, but need the AAC for compatibility reasons.

**Comment by ErikFL** [comment]
I was able to keep all DTS/AC3 tracks with settings below in autoProcess.ini, seems to always put the aac first even without ios-first-track-only = True set. These settings will copy over video stream and any DTS/AC3 no matter how many channels and make a aac 2 channel in first and DTS/AC3 in second, if there is a aac 5.1 audio it will convert aac 5.1 to ac3 5.1(6) channel.

output_extension = mp4
output_format = mp4
video-codec = h264,x264
ios-audio = True
ios-first-track-only = 
audio-codec = ac3,dca,dts,truehd
max-audio-channels = 5.1

**Comment by mattcosa** [comment]
Hi there Erik, not sure what that max-audio-channels settings is, but it definitely doesnt work.

2016-05-08 11:15:05 - readSettings - ERROR - Invalid number of audio channels specified.
Traceback (most recent call last):
  File "/usr/local/sickbeard_mp4_automator/readSettings.py", line 293, in __init__
    self.maxchannels = int(self.maxchannels)
ValueError: invalid literal for int() with base 10: '5.1'

**Comment by Mirabis** [comment]
It's to cap the maximum channels. E.g. DTS-MA release has 7.1 Sound = 7+1 > 8 channels.

Likewise 5.1 = 6, so you put 6 as max channel ( 5.1 aim the setting will bug as it's not an integer, as ur error shows)
