### ISSUE TITLE
QUESTION: Guide

### ISSUE THREAD

**Issue by dpkmon** [mdhiggins/sickbeard_mp4_automator#279]
Hi everyone.

Would it be possible to get a step by step guide for this? I'm not very tech savy.

I have python 2.7 installed (from when I used SickBeard), other than that I can figure how to install this automater.

BTW I'm using Sonarr.

Thanks!

**Comment by zybeon** [comment]
Yea, the wiki needs to be filled out.

What operating system are you on?

**Comment by dpkmon** [comment]
I'm on windows 7.
I wouldn't making a guide with pictures and whatever after I get the hang of it.

Sent from Outlook




On Wed, Jun 24, 2015 at 7:35 AM -0700, "zybeon" <notifications@github.com> wrote:












Yea, the wiki needs to be filled out.



What operating system are you on?

**Comment by zybeon** [comment]
Sonarr doesn't support post processing scripts, you will have to set up your downloader to do the post processing and notify Sonarr when it is done. If you manually convert your files then you can ignore step 6, though you will need to run the manual command every time you download new media. `python c:/mp4automator/manual.py -a -i PATH/TO/YOUR/MEDIA/`

1. Install pip by downloading the python script [here](https://bootstrap.pypa.io/get-pip.py) and run it in the windows command prompt (https://docs.python.org/2/faq/windows.html). https://pip.pypa.io/en/latest/installing.html
`python get-pip.py`

2. Install the requests module from the python command prompt with pip.
`pip install requests`

3. Install ffmpeg in either 32-bit or 64-bit for your version of windows. http://ffmpeg.zeranoe.com/builds/

4. Download 'sickbeard_mp4_automator' and fill out your settings in the autoProcess.ini file. Make sure to fill out the ffmpg and ffprobe exe's FULL file paths. (i.e. "ffmpeg = C:/ffmpeg/ffmpeg.exe") 

5. (optional) Install the mp4 automator's customized version of subliminal for subtitles. Run the install script in python.
`c:/python2.7/python c:/mp4automator/setup/subliminal/setup.py`

6. Follow the instructions in the readme for setting up mp4 conversion for your download client of choice.

If you need more detailed and/or easier instructions just ask. I made these quickly.

**Comment by dpkmon** [comment]
I'll give it a look, but it's a hell of a guide for beginners, great job!

Sent from Outlook




On Wed, Jun 24, 2015 at 11:02 AM -0700, "zybeon" <notifications@github.com> wrote:












Sonarr doesn't support post processing scripts, you will have to set up your downloader to do the post processing and notify Sonarr when it is done. If you manually convert your files then you can ignore step 6, though you will need to run the manual command every time you download new media. python c:/mp4automator/manual.py -a -i PATH/TO/YOUR/MEDIA/




Install pip by downloading the python script here and run it in the windows command prompt (https://docs.python.org/2/faq/windows.html). https://pip.pypa.io/en/latest/installing.html

python get-pip.py


Install the requests module from the python command prompt with pip.

pip install requests


Install ffmpeg in either 32-bit or 64-bit for your version of windows. http://ffmpeg.zeranoe.com/builds/


Download 'sickbeard_mp4_automator' and fill out your settings in the autoProcess.ini file. Make sure to fill out the ffmpg and ffprobe exe's FULL file paths. (i.e. "ffmpeg = C:/ffmpeg/ffmpeg.exe") 


(optional) Install the mp4 automator's customized version of subliminal for subtitles. Run the install script in python.

c:/python2.7/python c:/mp4automator/setup/subliminal/setup.py


Follow the instructions in the readme for setting up mp4 conversion for your download client of choice.




If you need more detailed and/or easier instructions just ask. I made these quickly.

**Comment by mdhiggins** [comment]
Ideally updating the wiki with more detailed step by step instructions, and maybe making a youtube video tutorial of the setup from start to finish would be really useful.

Unfortunately I simply don't have the time for such a production at the moment. If any users familiar with the process wanted to take on this project for the community it would be great; feel free to get in touch with me.
