### ISSUE TITLE
REQUEST: add the Auth Token to the Plex Notification

### ISSUE THREAD

**Issue by Smithoo4** [mdhiggins/sickbeard_mp4_automator#280]
The Plex Notification feature of this script does not work when the Plex Media Server is part of a Plex Home.  Both Sickrage and CouchPotato had this issue in the past. They have both add a “Plex Media Server Auth Token” field in there notification settings. This field once fill in correctly allows there plex notification to work again.  I did some googling and found the following page on Plex's website where they explain some of this. 

https://support.plex.tv/hc/en-us/articles/201638786-Plex-Media-Server-URL-Commands

It would be nice to have this added to this script.

Thank you,

**Comment by mdhiggins** [comment]
Just pushed a commit that should add support for the token. I don't use plex home so give it a try and let me know if its working for you.

**Comment by mdhiggins** [comment]
This change works with legacy non-plex home users like myself, just for confirmation there

**Comment by Smithoo4** [comment]
Thank you for the quick response to my issue; it is very much appreciated.  I am currently away from home and busy with a few other things.  Once I get back I will definitely give this a test and let you know.

Once and again thank you.

**Comment by Smithoo4** [comment]
I did some testing and everything looks to be working correctly for my set up.

Thank you for adding the feature.

Cheers,

**Comment by mdhiggins** [comment]
Glad its working, thanks for the feedback
