### ISSUE TITLE
QUESTION: Support to run this on Synology?

### ISSUE THREAD

**Issue by elit3ge** [mdhiggins/sickbeard_mp4_automator#284]
Is there anyway to run this on Synology?

I am currently moving my SB to SickRage but it's going from a Server 2008 to a Synology DS1513+, is this possible?

**Comment by mdhiggins** [comment]
I believe there are many people using the script on synology without issue. You'll need a special build of ffmpeg for syn but otherwise it works fine.

**Comment by mdhiggins** [comment]
You can look through past issues that people have  submitted and commented on, as well as dig through the forum thread on the Sickbeard forums where some people have talked about it for some input there as well.

**Comment by andyblac** [comment]
what box, i could build ffmpeg for you.

**Comment by elit3ge** [comment]
that would be great! 😄 Synology DS1513+ thanks.

**Comment by andyblac** [comment]
get the file here https://plexstation.co.uk:7001/fbsharing/cVHnEjyR ignore the package not staring in package manager, for some reason it does not see it as running. to test installed ok run ffmpeg in a SSH session should see something like below.


```
PlexStation> ffmpeg
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.7.3 (crosstool-NG 1.18.0) 20130102 (prerelease)
  configuration: --disable-yasm --enable-gpl --enable-libx264 --enable-libmp3lame --enable-libfdk-aac --enable-version3 --enable-nonfree --enable-cross-compile --arch=x64 --target-os=linux --cross-prefix=/home/synology/spksrc/toolchains/syno-x64-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/usr/local/ffmpeg --extra-cflags=-I/home/synology/spksrc/spk/ffmpeg/work-x64-5.1/install/usr/local/ffmpeg/include --extra-ldflags=-L/home/synology/spksrc/spk/ffmpeg/work-x64-5.1/install/usr/local/ffmpeg/lib --extra-libs=-ldl
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by elit3ge** [comment]
Thanks for that but the Status has expired. Any chance to grab it again?

**Comment by andyblac** [comment]
https://plexstation.co.uk:7001/fbsharing/5pSqfM8f

**Comment by andyblac** [comment]
did you manage to get it ?
