### ISSUE TITLE
Issue with empty MP4 container being created and no remux

### ISSUE THREAD

**Issue by vashp2029** [mdhiggins/sickbeard_mp4_automator#285]
Hey,

I'm sorry if this isn't the place to ask for help, I wasn't sure, I'm still new to GitHub. I went through the installation instructions and I got the following error:

    07-20 20:23:19ERROR[PostProcess] File processing failed: Traceback (most recent call last):
    File "C:\Users\vashp\AppData\Roaming\CouchPotato\custom_plugins\PostProcess\main.py", line 54, in callscript
    File "C:\Program Files\Converter\mkvtomp4.py", line 147, in process
    File "C:\Program Files\Converter\mkvtomp4.py", line 545, in convert
    File "C:\Program Files\Converter\converter\__init__.py", line 243, in convert
    File "C:\Program Files\Converter\converter\ffmpeg.py", line 544, in convert
    FFMpegConvertError: <FFMpegConvertError error="Exited with code -1073741510", pid=3868, cmd="C:\Program Files\FFMPEG\bin\ffmpeg.exe -fix_sub_duration -i M:\Avatar (2009)\Avatar (1920x1080, 6).mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=ger -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=ger -strict experimental -c:a:2 aac -map 0:2 -ac:a:2 2 -b:a:2 256k -metadata:s:a:2 language=eng -strict experimental -c:a:3 aac -map 0:2 -ac:a:3 6 -b:a:3 1536k -metadata:s:a:3 language=eng -strict experimental -c:s:0 mov_text -map 0:3 -metadata:s:s:0 language=ger -c:s:1 mov_text -map 0:4 -metadata:s:s:1 language=ger -f mp4 -threads auto -y M:\Avatar (2009)\Avatar (1920x1080, 6).mp4">

I'm not sure what the actual error is and what I'm ending up with is original MKV and an EMPTY MP4 file with the same name as the MKV being transferred to my movies directory. So, the transfer is occurring the way it should be, but the file isn't actually being transcoded or remuxed into the new container. 

On a side note, in the NZBGETPOSTPROCESS script, should my MP4 folder be `C:\Program Files\Converter\` or `C:/Program Files/Converter/`

Again, I hope this isn't the wrong place for this issue, and if it is, I would really appreciate it if you could point me in the right direction.

Thank you!

**Comment by mdhiggins** [comment]
Looks like FFMPEG is aborting/crashing which is why you're getting an empty MP4, what I would do next is manually run the command the script is showing you there and see if any additional information is posted by FFMPEG, and then post that information here and I'll take a look. This is the command the script is trying to run:
```
C:\Program Files\FFMPEG\bin\ffmpeg.exe -fix_sub_duration -i M:\Avatar (2009)\Avatar (1920x1080, 6).mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=ger -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=ger -strict experimental -c:a:2 aac -map 0:2 -ac:a:2 2 -b:a:2 256k -metadata:s:a:2 language=eng -strict experimental -c:a:3 aac -map 0:2 -ac:a:3 6 -b:a:3 1536k -metadata:s:a:3 language=eng -strict experimental -c:s:0 mov_text -map 0:3 -metadata:s:s:0 language=ger -c:s:1 mov_text -map 0:4 -metadata:s:s:1 language=ger -f mp4 -threads auto -y M:\Avatar (2009)\Avatar (1920x1080, 6).mp4
```

Run that (assuming you still have all the files in the same place) and see what you get.

As far as your second question - doesn't matter, either one will work.

**Comment by vashp2029** [comment]
Thanks for the reply mdhiggins! It turns out that running that script manually works, but I have to edit it to put quotes around the file paths, since there are spaces in them. So this is what I ended up running:

    "C:\Program Files\FFMPEG\bin\ffmpeg.exe" -fix_sub_duration -i "M:\Avatar (2009)\Avatar (1920x1080, 6).mkv" -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=ger -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=ger -strict experimental -c:a:2 aac -map 0:2 -ac:a:2 2 -b:a:2 256k -metadata:s:a:2 language=eng -strict experimental -c:a:3 aac -map 0:2 -ac:a:3 6 -b:a:3 1536k -metadata:s:a:3 language=eng -strict experimental -c:s:0 mov_text -map 0:3 -metadata:s:s:0 language=ger -c:s:1 mov_text -map 0:4 -metadata:s:s:1 language=ger -f mp4 -threads auto -y "M:\Avatar (2009)\Avatar (1920x1080, 6).mp4"

Any idea how I would automate this? 

Also, it looks like what's happening is that NZBGet is downloading to my temporary dir for files labelled with the "movies" category (G:\downloads\movies\), and telling CP that it's complete, at which point CP is renaming and moving the file to its final destination on an external drive (M:\[Movie Name (Year)]\[Movie Name (Resolution, Audio Channels)]). I feel like it would be more efficient for the script to run first, and THEN CP to rename and move the file. I think that's what you want the script to do anyway, just not sure how I screwed it up.

Thank you so much for your help!

**Comment by mdhiggins** [comment]
You can enable conversion in your NZBGetPostProcess settings to convert before couch potato is notified.

As far as your other error, the quotes probably aren't what is actually causing the script to fail, though I'm not sure what exactly is the problem. The way python executes external scripts the quotes wouldn't be an issue though. Are you consistently getting that FFMPEG error with that weird exit code with every file you try?

**Comment by vashp2029** [comment]
Yea, I tried several files. All of them work if I do it manually with those quotes but otherwise I get the same error. 

I also have "SHOULDCONVERT" set to "TRUE" in NZBGetPostProcess, so it should be converting before notifying CP, but it doesn't look like that's what's occurring.

**Comment by mdhiggins** [comment]
The lack of conversion may be because conversion isn't working right now with your script, and therefore isn't happening successfully before passing the file to couch potato. I think first things first we have to figure out why.

Does processing the file via manual.py work for conversion?

Also if you could post your autoProcess.ini settings that would be helpful.

**Comment by vashp2029** [comment]
Here's my autoProcess.ini file: 


```[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 

[Sonarr]
host = localhost
port = 38082
web_root = 
ssl = 0
apikey = ad258bfe207e489b9af4ee3e41eed355

[MP4]
ffmpeg = C:\Program Files\FFMPEG\bin\ffmpeg.exe
ffprobe = C:\Program Files\FFMPEG\bin\ffprobe.exe
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
audio-codec = aac
video-codec = h264,x264
video-bitrate = 
ios-audio = True
max-audio-channels = 
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
subtitle-language = 
subtitle-default-language = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = True
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
ios-first-track-only = False
subtitle-codec = mov_text
video-max-width = 

[CouchPotato]
host = localhost
port = 38083
username = vashp2029
password = 1q2w3e4r5t
web_root = 
ssl = 0
apikey = 5006888f422e4c8da45dc667e64574c6
delay = 65
method = renamer
delete_failed = 1

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
bypass-label = bypass
sickrage-label = sickrage

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickbeard-category = sickbeard
couchpotato-category = couchpotato
sonarr-category = sonarr
sickrage-category = sickrage
bypass-category = bypass

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token = bHHNbHxgqaqoJDXTa3wy```

I also just tried manual.py and for one file, it kept giving me an "Audio bitrate was invalid" error, but it looks like it's begun converting on the second file I tried it, and no errors thus far (still only at 5%).

**Comment by mdhiggins** [comment]
Keep me posted when it finishes, and the audio bitrate error shouldn't actually be a problem its just cause your audio bitrate setting is blank, definitely shouldn't cause any failure.

**Comment by vashp2029** [comment]
Looks like the manual.py worked as it was supposed to. I tried downloading another file through CP to see if what the issue was and this time, NZBGet never launched the NZBGetPostProcess script from the looks of it: http://i.imgur.com/WFnObtS.png. The CP log, on the other hand, is clear this time. I haven't changed anything though...

**Comment by mdhiggins** [comment]
Are your labels being properly set by CouchPotato within NZBGet? If the download label doesn't match whatever your couch potato label is then the post processing don't be executed properly. Although I sort of doesn't look like it even got that far based on the logs.

And when you say the CP log is clear, you mean there was no errors and the conversion worked appropriately?

**Comment by vashp2029** [comment]
Finally got it to work! The issue was just that I hadn't actually set the "movies" category to run the script after it was finished downloading.... 

Thank you so much for all your help!

One final question: If I download a file in 3D and transcode using this script, will the resulting MP4 retain the 3D format?

**Comment by mdhiggins** [comment]
Honestly I have no idea, you're the first person to ask that question and I've never tried a 3d file before (don't have any 3d equipment). Lemme know how it goes though for future reference

**Comment by mdhiggins** [comment]
Gonna close this for now since everything is fixed. Email me letting me know how the 3d stuff goes, or open an issue if there's a problem.
