### ISSUE TITLE
Post Processing scripts and Sonarr

### ISSUE THREAD

**Issue by dlmarston** [mdhiggins/sickbeard_mp4_automator#286]
hi there,

I read in some of your notes that tagging couldn't be achieved because Sonarr  doesn't support post processing scripts.

I don't know know if this is a recent change to their website, but Sonarr have this information now:

https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts

Does it help?

regards,

Dave

**Comment by mdhiggins** [comment]
Ah nice looks like they just implemented this 2 days ago. I will investigate and proper sonarr support will probably be soon to follow

**Comment by mdhiggins** [comment]
If you have a working Sonarr setup and wanted to give this script a try, I just wrote this up really quickly:

```
#!/usr/bin/env python
import os
import sys
import logging
from readSettings import ReadSettings
from autoprocess import plex
from tvdb_mp4 import Tvdb_mp4
from mkvtomp4 import MkvtoMp4
from post_processor import PostProcessor
from logging.config import fileConfig

fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
log = logging.getLogger("SonarrPostConversion")

log.info("Sonarr extra script post processing started.")

settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")

inputfile = os.environ.get('Sonarr.EpisodeFile.Path')
original = os.environ.get('Sonarr.EpisodeFile.SceneName')
tvdb_id = int(os.environ.get('Sonarr.Series.TvdbId'))
season = int(os.environ.get('Sonarr.EpisodeFile.SeasonNumber'))
try:
    episode = int(os.environ.get('Sonarr.EpisodeFile.EpisodeNumbers'))
except:
    episode = int(os.environ.get('Sonarr.EpisodeFile.EpisodeNumbers').split(",")[0])

converter = MkvtoMp4(settings)

log.debug("Input file: %s." % inputfile)
log.debug("Original name: %s." % original)
log.debug("TVDB ID: %s." % tvdb_id)
log.debug("Season: %s episode: %s." % (season, episode))

if MkvtoMp4(settings).validSource(inputfile):
    log.info("Processing %s." % inputfile)

    output = converter.process(inputfile, original=original)

    # Tag with metadata
    if settings.tagfile:
        log.info("Tagging %s with ID %s season %s episode %s." % (inputfile, tvdb_id, season, episode))
        tagmp4 = Tvdb_mp4(tvdb_id, season, episode, original, language=settings.taglanguage)
        tagmp4.setHD(output['x'], output['y'])
        tagmp4.writeTags(output['output'], settings.artwork)

    #QTFS
    if settings.relocate_moov:
        converter.QTFS(output['output'])

    # Copy to additional locations
    output_files = converter.replicate(output['output'])

    # run any post process scripts
    if settings.postprocess:
        post_processor = PostProcessor(output_files, log)
        post_processor.setTV(tvdb_id, season, episode)
        post_processor.run_scripts()

    plex.refreshPlex(settings, 'show', log)
```

Just save it as something like `postConversionSonarr.py` and set this as your post script in Sonarr and see how it works. It will take me some time to put together a working test setup with Sonarr.

**Comment by Trixter69** [comment]
I tried this but it didn't work.

this is the result i got from it:
Details:
Message:
Unable to send OnRename notification to: Post Conversion and tagging: The specified executable is not a valid application for this OS platform.

Exception:
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 167
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 199
   at NzbDrone.Core.Notifications.CustomScript.CustomScriptService.ExecuteScript(StringDictionary environmentVariables, CustomScriptSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScriptService.cs:line 86
   at NzbDrone.Core.Notifications.CustomScript.CustomScriptService.OnRename(Series series, CustomScriptSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScriptService.cs:line 69
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnRename(Series series) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 32
   at NzbDrone.Core.Notifications.NotificationService.Handle(SeriesRenamedEvent message) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\NotificationService.cs:line 149

**Comment by mdhiggins** [comment]
I'll post on the sonarr GitHub and see if I can get some insight into this

**Comment by Trixter69** [comment]
Thx I posted a support request on their forums heres the link:
https://forums.sonarr.tv/t/custom-scripts-error-on-win-7/6843/2

**Comment by markus101** [comment]
Just a heads up, we realized that `.` in Environment variable names is unsupported so we'll be switching over to `_` instead in a future version (before we release this to master).

**Comment by mdhiggins** [comment]
Thanks for the heads up.

Script should look like this now for users testing on the dev build
```
#!/usr/bin/env python
import os
import sys
import logging
from readSettings import ReadSettings
from autoprocess import plex
from tvdb_mp4 import Tvdb_mp4
from mkvtomp4 import MkvtoMp4
from post_processor import PostProcessor
from logging.config import fileConfig

fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
log = logging.getLogger("SonarrPostConversion")

log.info("Sonarr extra script post processing started.")

settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")

inputfile = os.environ.get('Sonarr_EpisodeFile_Path')
original = os.environ.get('Sonarr_EpisodeFile_SceneName')
tvdb_id = int(os.environ.get('Sonarr_Series_TvdbId'))
season = int(os.environ.get('Sonarr_EpisodeFile_SeasonNumber'))
try:
    episode = int(os.environ.get('Sonarr_EpisodeFile_EpisodeNumbers'))
except:
    episode = int(os.environ.get('Sonarr_EpisodeFile_EpisodeNumbers').split(",")[0])

converter = MkvtoMp4(settings)

log.debug("Input file: %s." % inputfile)
log.debug("Original name: %s." % original)
log.debug("TVDB ID: %s." % tvdb_id)
log.debug("Season: %s episode: %s." % (season, episode))

if MkvtoMp4(settings).validSource(inputfile):
    log.info("Processing %s." % inputfile)

    output = converter.process(inputfile, original=original)

    # Tag with metadata
    if settings.tagfile:
        log.info("Tagging %s with ID %s season %s episode %s." % (inputfile, tvdb_id, season, episode))
        tagmp4 = Tvdb_mp4(tvdb_id, season, episode, original, language=settings.taglanguage)
        tagmp4.setHD(output['x'], output['y'])
        tagmp4.writeTags(output['output'], settings.artwork, settings.thumbnail)

    #QTFS
    if settings.relocate_moov:
        converter.QTFS(output['output'])

    # Copy to additional locations
    output_files = converter.replicate(output['output'])

    # run any post process scripts
    if settings.postprocess:
        post_processor = PostProcessor(output_files, log)
        post_processor.setTV(tvdb_id, season, episode)
        post_processor.run_scripts()

    plex.refreshPlex(settings, 'show', log)
```

**Comment by mdhiggins** [comment]
Anyone running the Sonarr dev build able to comment on whether this is working now?

**Comment by markus101** [comment]
These changes haven't hit the latest dev build yet, but should once we fix up an issue with our build server, should be available in the next few days.

**Comment by Trixter69** [comment]
hey seems to be working now with this as the setup in sonarr
![capture](https://cloud.githubusercontent.com/assets/907858/10029548/5cdcd55e-6127-11e5-9133-7ec7e04ae69a.PNG)

**Comment by mdhiggins** [comment]
Nice, does the script actually run and tag as its supposed to now? I'm actually gonna be switching over to Sonarr for my personal setup since SB seems to be dying/dead

**Comment by Trixter69** [comment]
Yep Sonarr now monitors SAB or Torrents and moves,renames,converts and tags when the episode has finished downloading. works very well :)

you set it up under settings/connect/new/custom script. I've also got is to work on rename if you have already sorted files that need to be tagged/converted. Just move the files into a new folder under the series folder and hit refresh then rename for that series and sonarr does all the heavy lifting of converting/tagging with SMA. :)

**Comment by morpheus2n2** [comment]
dose this mean that there will be an actual sonar script added in the future?

**Comment by mdhiggins** [comment]
Probably this weekend

**Comment by Trixter69** [comment]
Just started getting this error after restarting my machine. I'm looking into it on my side but thought you'd like to know

[code]
python.exe	AttributeError: ReadSettings instance has no attribute 'thumbnail'	12:24am
python.exe	tagmp4.writeTags(output['output'], settings.artwork, settings.thumbnail)	12:24am
python.exe	File "C:\Scripts\postConversionSonarr.py", line 45, in <module>	12:24am
python.exe	Traceback (most recent call last):

[/code]

**Comment by mdhiggins** [comment]
Yeah that's an odd error, lemme know if it happens again.

My plan is to switch over to Sonarr (dev branch) on my personal setup this weekend and put this through the paces. If all goes well I'll merge the new script into the master branch so we're ready to go for when the update hits the main build.

**Comment by outlyer** [comment]
I don't know if this is a problem on Windows, but I should add that the script didn't work on my Mac until I changed all the environment variables to lowercase. 

```python
inputfile = os.environ.get('Sonarr_EpisodeFile_Path')
original = os.environ.get('Sonarr_EpisodeFile_SceneName')
tvdb_id = int(os.environ.get('Sonarr_Series_TvdbId'))
season = int(os.environ.get('Sonarr_EpisodeFile_SeasonNumber'))
try:
    episode = int(os.environ.get('Sonarr_EpisodeFile_EpisodeNumbers'))
except:
    episode = int(os.environ.get('Sonarr_EpisodeFile_EpisodeNumbers').split(",")[0])
```

became

```python

inputfile = os.environ.get('sonarr_episodefile_path')
original = os.environ.get('sonarr_episodefile_scenename')
tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
try:
    episode = int(os.environ.get('sonarr_episodefile_episodenumbers'))
except:
    episode = int(os.environ.get('sonarr_episodefile_episodenumbers').split(",")[0])
```

With that change, I was able to get everything to work with Sonarr/NZBGet.

**Comment by mdhiggins** [comment]
I'll update that before the final push, thanks

**Comment by mdhiggins** [comment]
Just pushed the file to the master branch

`postSonarr.py`
