### ISSUE TITLE
sabnzbd post processing error

### ISSUE THREAD

**Issue by thejacobsons** [mdhiggins/sickbeard_mp4_automator#287]
Hello!

First, I would like to thank you for this automator! I have been using it for quite some time and it really is great. Last week, I started receiving the following types of errors when sabnzbd post processes:

/Library/Python/2.7/site-packages/beautifulsoup4-4.4.0-py2.7.egg/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

nzbToNzbDrone MP4 edition
Processing episode /Users/name/Downloads/media/complete/nnnn.mkv
Video codec detected: h264
Audio stream detected: aac eng [Stream 1]
Subtitle stream detected: subrip eng [Stream 2]
Subtitle stream detected: subrip eng [Stream 3]
Attempting to download subtitles, please wait
External subtitle file detected, language eng
Importing halt.and.catch.fire.s01e04.bdrip.x264-reward.eng.srt subtitle stream
/Users/name/Downloads/media/complete/nnnn.mp4 created
/Users/name/Downloads/media/complete/nnnn.mkv deleted
/Users/name/Downloads/media/complete/nnnn.eng.srt deleted
Processing episode /Users/name/Downloads/media/complete/nnnn.sample.mkv
Video codec detected: h264
Audio stream detected: aac eng [Stream 1]
Subtitle stream detected: subrip eng [Stream 2]
Subtitle stream detected: subrip eng [Stream 3]
Attempting to download subtitles, please wait
External subtitle file detected, language eng
Importing halt.and.catch.fire.s01e04.bdrip.x264-reward.sample.eng.srt subtitle stream
/Users/name/Downloads/media/complete/nnnn.sample.mp4 created
/Users/name/Downloads/media/complete/nnnn.sample.mkv deleted
/Users/name/Downloads/media/complete/nnnn.sample.eng.srt deleted
/Users/name/Downloads/media/complete/nnnn.eng.srt deleted
Script triggered from SABnzbd, starting nzbDroneFactory...
Loading config from /Applications/media/mp4_automator/autoProcess.ini
{
  "name": "DownloadedEpisodesScan",
  "body": {
    "sendUpdatesToClient": false,
    "sendUpdates": false,
    "path": "/Users/name/Downloads/media/complete/nnnn",
    "completionMessage": "Completed",
    "name": "DownloadedEpisodesScan",
    "trigger": "manual"
  },
  "priority": "normal",
  "status": "queued",
  "queued": "0001-01-01T00:00:00Z",
  "trigger": "manual",
  "state": "queued",
  "manual": true,
  "startedOn": "0001-01-01T00:00:00Z",
  "sendUpdatesToClient": false,
  "id": 12399
}
==============================

Response code: 201
Name: DownloadedEpisodesScan
StartedOn: 0001-01-01T00:00:00Z
Traceback (most recent call last):
  File "/Applications/media/mp4_automator/nzbToNzbDroneMP4.py", line 36, in <module>
    nzbDroneFactory.scan(sys.argv[1], sys.argv[7])
  File "/Applications/media/mp4_automator/nzbDroneFactory.py", line 81, in scan
    print 'StateChangeTime: ' + str(pyobj['stateChangeTime'])
KeyError: 'stateChangeTime'

A note is that the file is actually getting converted and moved but I just cannot figure out why I would be receiving such an error. Have you seen anything like this?

Thank you!
Dianna

**Comment by mdhiggins** [comment]
Hm I have not see that error before, off the top of my head I'm not sure what would cause that. I also notice it looks like you're using a pretty old version of the script since you're using the nzbDrone file and that file hasn't existed as part of the script for a long time. NZBDrone doesn't really exist anymore and has been replaced by Sonarr and the script has been updated to reflect that. 

My recommendation would be to update over to Sonarr and grab the latest version of the script to go with it. Not sure where that error is coming from honestly.

**Comment by thejacobsons** [comment]
I was aware of the brand change from nzbdrone to Sonarr and I plan on getting the automator updated. ;)

Maybe that will resolve my issue. I was using it before the rebrand which is how I happened upon your automator. I guess I just missed an update notification for the automator. Hopefully I've also fixed that now.

Again, thank you for the time and effort you put into this!

**Comment by mdhiggins** [comment]
No problem! Gonna close  this issue for now, if you're still having problems after the update feel free to reopen and I'll see if I can help. Enjoy.
