### ISSUE TITLE
Choosing H264 Level

### ISSUE THREAD

**Issue by xpack90** [mdhiggins/sickbeard_mp4_automator#291]
I do have a request. According to this page here https://support.plex.tv/hc/en-us/articles/203810286-What-media-formats-are-supported- the video level does need to be level 4.0 or lower can we have a setting using the ffmpeg command -level 3.0 or whichever level you like,

**Comment by mdhiggins** [comment]
Done. The option is called `h264-max-level`. Use the decimal style format (`4.0`). Obviously only applies if you’re using H264. Lemme know if its working for you.

**Comment by xpack90** [comment]
I did a git pull but the new option show video-max-width=

BTW thanks for the quick response

**Comment by mdhiggins** [comment]
No prob. And the video-max-width option is old - been there for a while. I can see the commit in github so its definitely in there. Your own autoProcess.ini won't update until the script is run or you add the option manually. You can open and close manual.py to trigger the autoProcess update.
