### ISSUE TITLE
Maximizing CPU usage

### ISSUE THREAD

**Issue by Enf0** [mdhiggins/sickbeard_mp4_automator#292]
I'm in the process of convert my entire library of MKV files to mp4 for better playback via Plex and similar devices. However, using the script to convert my files takes a very long time, and when I'm looking at the CPU usage it's only using a fraction of the resources available, usually hovering around 10-20%.
Am I not correct in assuming it should use whatever CPU it has available? 
The processor is an quad-core Xeon with Hyperthreading.

Thanks for a great script!

**Comment by mdhiggins** [comment]
This is unfortunately a limitation of FFMPEG. There's really no way to address this from the scripting standpoint - though if/when FFMPEG does improve their multi threading capabilities the script will leverage that performance increase.
