### ISSUE TITLE
ffmpeg showing python command window

### ISSUE THREAD

**Issue by tcaruth** [mdhiggins/sickbeard_mp4_automator#293]
i keep getting python prompts opening and closing when downloads finish, from what i've assumed to be ffmpeg. i recently added a few new shows that downloaded pretty quickly, and this command prompt kept popping up in my way while i was trying to do other work.

is there a way to use pythonw so the window stays hidden when converting?

**Comment by mdhiggins** [comment]
I would just adjust the configuration for whatever program is executing the files to point to pythonw instead of python and maybe adjust your environment variables to use pythonw for .py files and see if that helps.

IE edit the config.ini for Sickbeard and point it to pythonw.exe instead of python

**Comment by tcaruth** [comment]
i just edited the config to use pythonw for the post processing script. sickbeard itself i had already set to start without a window.

i'll see if that was enough. i dont want to make all py files open with pythonw because i have a few interactive ones where i need to give them a file, or other inputs. using pythonw blocks it from ever showing a window, and they die immediately

**Comment by tcaruth** [comment]
the window isnt labeled as a python window anymore, now its clearly ffmpeg. i don't see any flags i can set on it, and i've tried playing with the verbosity. 

do you have the same boxes appear when processing, or is it something with the way i've got things setup?

**Comment by mdhiggins** [comment]
I also have the same boxes appear. As far as I know there's no command line switch to hide the FFMPEG output unfortunately.

**Comment by mdhiggins** [comment]
I just pushed a new commit that may resolve your issue. It will only work under Windows but give it a try and see if the FFMPEG window is hidden now.

**Comment by tcaruth** [comment]
seems to be working. thanks!
