### ISSUE TITLE
general config needs updating

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#294]
load the provided sample ini, run a process and you see that the config format changes (mostly cosmetic.. spaces) but also you see `video-max-width` and other fields added that arent on the readme.

**Comment by mdhiggins** [comment]
Updated the sample to include a handful of missing settings and added `video-max-width` to the readme.

Thanks

**Comment by thezoggy** [comment]
side question, does this script allow doing variable bitrate for audio?

**Comment by mdhiggins** [comment]
Not at this time, but its something I'm looking to add for video and audio in the future

**Comment by thezoggy** [comment]
sweet thanks.

**Comment by DRankex** [comment]
Any update for variable bitrate?
