### ISSUE TITLE
How to remove an audio track?

### ISSUE THREAD

**Issue by roidy** [mdhiggins/sickbeard_mp4_automator#297]
I have a file that has 2 audio tracks:-

Track 1 is AC3 and tagged as French (fre)
Track 2 is AC3 and tagged as English (eng)

In autoProcess.ini I set audio-language=eng which I understand to mean only the English track will be used, however the resulting m4v file has 4 audio tracks:-

Track 1 is aac fre
Track 2 is ac3 fre
Track 3 is aac eng
Track 4 is ac3 eng

What am I doing wrong? How do I get rid of the French track?

**Comment by mdhiggins** [comment]
Seems like you're doing everything right.

Can you post your autoProcess.ini?

**Comment by roidy** [comment]
Yep, here you go:-

http://pastebin.com/3Ss6F9Qx

And this is how I'm running the script:-

'python.exe manual.py -a -I file.mkv

Thanks.

**Comment by mdhiggins** [comment]
Can you upload the file somewhere and email me a link. That all looks appropriate.

**Comment by roidy** [comment]
Sorry no, it's a 14GB file.

Not to worry, I ended up using MKVToolNix to remove the French audio then ran the file through the script.

**Comment by mdhiggins** [comment]
Can you run the original though ffprobe -show_steams and send me the output? It would be helpful for debugging to figure out why it wasn't working. If you still have it.

**Comment by roidy** [comment]
Sure, here you go:-

http://pastebin.com/5UMY6KWq

**Comment by mdhiggins** [comment]
Can't seem to reproduce your error, I suspect there's something messed up in your autoProcess.ini

Otherwise not sure why it wouldn't be ignoring the languages. Feel free to reopen if this is a persistent problem
