### ISSUE TITLE
Errors in latest version (CentOS 6.7)

### ISSUE THREAD

**Issue by cod3fr3ak** [mdhiggins/sickbeard_mp4_automator#300]
[root@processor ~]# time /opt/sickbeard_mp4_automator/manual.py -i /shared/video/movies/Woman\ in\ Gold\ \(2015\).mkv -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
encode() takes no keyword arguments
Traceback (most recent call last):
  File "/opt/sickbeard_mp4_automator/manual.py", line 346, in <module>
    main()
  File "/opt/sickbeard_mp4_automator/manual.py", line 337, in main
    processFile(path, tagdata)
  File "/opt/sickbeard_mp4_automator/manual.py", line 199, in processFile
    output = converter.process(inputfile, True)
  File "/opt/sickbeard_mp4_automator/mkvtomp4.py", line 140, in process
    options = self.generateOptions(inputfile, original=original)
  File "/opt/sickbeard_mp4_automator/mkvtomp4.py", line 248, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/opt/sickbeard_mp4_automator/converter/__init__.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "/opt/sickbeard_mp4_automator/converter/ffmpeg.py", line 413, in probe
    stdout_data = stdout_data.decode(console_encoding, errors='ignore')
TypeError: decode() takes no keyword arguments

real    0m0.976s
user    0m0.497s
sys     0m0.076s

**Comment by mdhiggins** [comment]
Gotta update to Python 2.7

**Comment by cod3fr3ak** [comment]
Oh really? Dang. Not sure I can do that. I got sickbeard and couchpotato running on the same box. For now I have an older version that is working. While you are here. I'm not seeing any meta-data put into my shows that I've used the script on. Any ideas? I do see tvdb connection timeouts tho...

**Comment by mdhiggins** [comment]
I should be able to add some backwards compatibility

**Comment by cod3fr3ak** [comment]
Nah its cool I might just spin a new vm just for this purpose

**Comment by cod3fr3ak** [comment]
but the tagging thing isn't working correctly tho

**Comment by mdhiggins** [comment]
How so?

**Comment by cod3fr3ak** [comment]
I think the version I am using can't connect to TVDB to get the metadata:

```
[root@processor Season 05]# /opt/mp4-automator/manual.py -i "S05E12 - Hell Ain't a Bad Place to Be.mkv" --tvdbid 80349 --season 5 --episode 12
Audio bitrate was invalid, defaulting to 256 per channel
64
Failed to connect to TVDB, trying again in 20 seconds
encode() takes no keyword arguments
Failed to connect to TVDB, trying again in 20 seconds
encode() takes no keyword arguments
Failed to connect to TVDB, trying again in 20 seconds
encode() takes no keyword arguments
Processing TV episode
Video codec detected: h264
Audio stream detected: ac3 eng [Stream 1]
Creating dual audio channels for iOS compatability for this stream
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "copy",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "copy",
        "bitrate": 3591844.0
    },
    "format": "mp4"
}
/shared/video/tv/Californication/Season 05/S05E12 - Hell Ain't a Bad Place to Be.mp4 created
S05E12 - Hell Ain't a Bad Place to Be.mkv deleted
Tagging file :/shared/video/tv/Californication/Season 05/S05E12 - Hell Ain't a Bad Place to Be.mp4
There was an error tagging the file
Relocating MOOV atom to start of file

```

**Comment by cod3fr3ak** [comment]
This is an older version than the current I believe tho.

**Comment by mdhiggins** [comment]
What version of python are you running?

You need to be on 2.7.x; your error `encode() takes no keyword arguments` is usually a result of running python 2.6 or earlier

**Comment by cod3fr3ak** [comment]
Yo you can close this one I managed to get python 2.7 installed side by side. In CentOS and RHEL based installed its a touchy issue because yum need python 2.6. Rolling 2.7 as the default system version causes VERY bad things to happen. Thanks man!
