### ISSUE TITLE
Dutch subtitle code "dut" not recognised

### ISSUE THREAD

**Issue by Deddiekoel** [mdhiggins/sickbeard_mp4_automator#304]
When I want to process a file with a dutch subtitle track the "dut" language code is not recognized. When manually processing it sees the tracks with the code but when I want to include it in the autoProcess.ini the value "dut" is rejected:

Reading subtitle streams.
Subtitle detected for stream #3: dvdsub [dut].
An unexpected error occurred, processing of this file has failed
'dut' is not a valid language

It does however accept the value as an audio track. Also when I don't specify a subtitle language it processes the files.

**Comment by mdhiggins** [comment]
This error is coming from babelfish because `dut` is actually not a valid language code. The language code for dutch is 'nld'.

I'll go ahead and catch this error as to prevent the script from failing completely.
