### ISSUE TITLE
nzbToMedia vs mp4_automator - HD to SD transcode

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#305]
source: 19m54s 720p HDTV rip thats 720 MB
mediainfo: http://pastebin.com/raw.php?i=jp28DUZS

Trying to re-encode this to 480p (SD) that mimics what scene would produce... since can't do VBR with audio stuck using CBR but trying to find acceptable settings that would produce similar results....

Forgot to time these to see if one is really faster than the other.. also can see that while video is close the audio is a bit different for each.

nzbtomedia:
`[13:17:45] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffmpeg.exe -loglevel warning -hwaccel auto -fflags +genpts -i F:\folder\file.mkv -i F:\folder\file.en.srt -map 0:0 -map 0:1 -map 1:0 -c:v libx264 -vf scale=720:404 -b:v 1400000 -crf 19 -level 3.1 -c:a:0 aac -strict -2 -b:a:0 192 -c:s mov_text -metadata:s:s:0 language=en -movflags +faststart F:\folder\file.mp4`
mediainfo: http://pastebin.com/raw.php?i=wG9KUdXd
result: 252 MB (w/sub embeded)

mp4 automator:
`Spawning ffmpeg with command: C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\folder\file.mkv -i F:\folder\file.en.srt -map 0:0 -map 0:1 -map 1:0 -vcodec libx264 -vf scale=720:-2 -vb 1400k -level 3.1 -c:a:0 aac -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:s:0 mov_text -metadata:s:s:0 language=eng -f mp4 -threads auto -y F:\folder\file.mp4`
mediainfo: http://pastebin.com/raw.php?i=tuYYDKTZ
result: 233 MB (unable to get subs working - even tried letting it use the subs nzbtomedia found)

nzbtomedia:
```
    # getsubs. enable to download subtitles.
    getSubs = 1
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 1
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = 720:480
    outputVideoFramerate = ""
    outputVideoBitrate = 1400k
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = "libfaac,aac,libfdk_aac"
    outputAudioChannels = 2
    outputAudioBitrate = 192
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text
```

mp4 automator:
```
[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
audio-codec = aac
video-codec = h264,x264
video-bitrate = 1400
h264-max-level = 3.1
ios-audio = True
max-audio-channels = 2
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 192
subtitle-language = eng
subtitle-default-language = eng
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = en
download-artwork = False
download-subs = True
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
ios-first-track-only = False
subtitle-codec = mov_text
video-max-width = 720
```

**Comment by thezoggy** [comment]
things to note,

* the source video is 1280x720 (720p) and the settings were to transcode down to 480p, both apps use the width to size down off of..

  * nzbtomedia resized the video correctly with proper aspect ratio of 720x404

  * automator resized the video incorrectly to 720x406

* the source video audio is 2 channel AC-3 with constant bitrate of 384 Kbps, stream size of 54.7 MiB

  * nzbtomedia ended up with 2 channel AAC but with a horrible bitrate of 4,136 bps for a stream size of 603 KiB

  * automator ended up with 2 channel AAC with bitrate of 256 Kbps for stream size of 36.5 MiB

**Comment by mdhiggins** [comment]
With regards to the video resizing, the issue here is that the height can't be an odd number. When resizing 1280 down to 720, and maintaining the same aspect ratio, the width should ultimately end up as 405. Since this isn't acceptable, the script has to round to the nearest even number. I'm guessing that nzbtomedia rounds down while my script rounds up. They're both within a 1 pixel margin of error so I wouldn't say its incorrectly resized.

And I don't see an issue as far as the audio is concerned.

As far as the subs go, are you referring to having the script automatically download the subs? Or is there some external sub you're trying to embed that's not working?

**Comment by thezoggy** [comment]
looking at scene's sd version, they also get to the same resolution nzbtomedia ends up with.. 
looking at the ratio.. yes you can see that the precision used to round most likely is the result in the differences...

* 1280/720 = 1.777777777777778 (org)
* 720/404 = 1.782178217821782 (nzbtomedia / scene)
* 720/406 = 1.773399014778325 (automator)

audio is fine for automator (id like to have used my requested value of 192 but its fine cause when using the ios it overrides to 256..) but mainly to point out differences between the two when attempting to use similar settings but getting different outcomes. 

about the subs, I just couldnt get it to work with automator.. both with the included version of subliminal or with latest.. or even if the sub already existed in the dir named as the media..  it worked fine in nzbtomedia without any extra effort  (he includes the libs as part of the repo.. so theres no need to force the user to install/figure out what version works.. etc.. maybe something you should look into doing as it would probably make things much simplier in terms of support - obviously at the expense of increasing the repo size)

the reason the info in this issue is being posted the way it is, is due to the fact that im cross posting this in two places... here is nzbtomedia's: https://github.com/clinton-hall/nzbToMedia/issues/816

**Comment by mdhiggins** [comment]
I just pushed an update that removed the dependency of the custom modifications I made to subliminal and now uses the latest build of subliminal. You should be able to run the script using the latest subliminal installed via PIP now.

**Comment by thezoggy** [comment]
Removed old subliminal (pip uninstall subliminal, installed latest)

```
C:\Program Files (x86)\sickbeard_mp4_automator>pip search subliminal
subliminal                - Subtitles, faster than your thoughts
  INSTALLED: 1.0.1 (latest)
```

I do see it grab the subs now,
```
Reading subtitle streams.
Attempting to download subtitles.
2015-08-27 23:04:26 - GuessFiletype - DEBUG - Found guess_episodes_rexps: {u'season': 28, u'episodeNumber': 7} -> type = episode
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: container=mp4 (mp4) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: format=HDTV (HDTV) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: screenSize=720p (720p) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: videoCodec=h264 (x264) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: format=HDTV (hdtv) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: videoCodec=h264 (x264) (confidence=1.00)
2015-08-27 23:04:26 - GuessProperties - DEBUG - Property found: container=mkv (mkv) (confidence=0.30)
2015-08-27 23:04:26 - GuessEpisodesRexps - DEBUG - Property found: season=28 (S28E07) (confidence=1.00)
2015-08-27 23:04:26 - GuessEpisodesRexps - DEBUG - Property found: episodeNumber=7 (S28E07) (confidence=1.00)
2015-08-27 23:04:26 - GuessEpisodesRexps - DEBUG - Property found: season=28 (s28e07) (confidence=1.00)
2015-08-27 23:04:26 - GuessEpisodesRexps - DEBUG - Property found: episodeNumber=7 (s28e07) (confidence=1.00)
2015-08-27 23:04:26 - GuessReleaseGroup - DEBUG - Property found: releaseGroup=W4F (W4F) (confidence=1.00)
2015-08-27 23:04:26 - GuessReleaseGroup - DEBUG - Property found: releaseGroup=w4f (w4f) (confidence=1.00)
2015-08-27 23:04:26 - GuessEpisodeInfoFromPosition - DEBUG - Property found: series=Cops (Cops) (confidence=0.70)
2015-08-27 23:04:26 - stevedore.extension - DEBUG - found extension EntryPoint.parse('opensubtitles = subliminal.providers.opensubtitles:OpenSubtitlesProvider')
2015-08-27 23:04:26 - stevedore.extension - DEBUG - found extension EntryPoint.parse('thesubdb = subliminal.providers.thesubdb:TheSubDBProvider')
2015-08-27 23:04:26 - stevedore.extension - DEBUG - found extension EntryPoint.parse('podnapisi = subliminal.providers.podnapisi:PodnapisiProvider')
2015-08-27 23:04:26 - stevedore.extension - DEBUG - found extension EntryPoint.parse('addic7ed = subliminal.providers.addic7ed:Addic7edProvider')
2015-08-27 23:04:26 - stevedore.extension - DEBUG - found extension EntryPoint.parse('tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider')
2015-08-27 23:04:26 - stevedore.enabled - DEBUG - ignoring extension 'tvsubtitles'
2015-08-27 23:04:26 - subliminal.api - ERROR - Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\subliminal\api.py", line 117, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "C:\Python27\lib\site-packages\subliminal\providers\addic7ed.py", line 257, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "C:\Python27\lib\site-packages\subliminal\providers\addic7ed.py", line 214, in query
    show_id = self.get_show_id(series, year, country)
  File "C:\Python27\lib\site-packages\subliminal\providers\addic7ed.py", line 187, in get_show_id
    show_ids = self._get_show_ids()
  File "C:\Python27\lib\site-packages\dogpile.cache-0.5.6-py2.7.egg\dogpile\cache\region.py", line 1040, in decorate
    should_cache_fn)
  File "C:\Python27\lib\site-packages\dogpile.cache-0.5.6-py2.7.egg\dogpile\cache\region.py", line 647, in get_or_create
    self._mutex(key),
  File "C:\Python27\lib\site-packages\dogpile.cache-0.5.6-py2.7.egg\dogpile\cache\region.py", line 278, in _mutex
    return self._lock_registry.get(key)
AttributeError: 'CacheRegion' object has no attribute '_lock_registry'
External eng subtitle file detected.
Creating subtitle stream 0 by importing filename.en.srt.
```

**Comment by mdhiggins** [comment]
I just fixed the cache error and silenced some of the additional logging

**Comment by thezoggy** [comment]
thanks, checking it out now.. noticed in your converter function there is a twopass variable.. is that ever exposed via an argument/ini setting?

**Comment by mdhiggins** [comment]
No but its something that could probably easily be added in a future update

**Comment by thezoggy** [comment]
so I was looking at your code and trying to figure out how the scaling is being done differently.. `-vf scale=720:-2` i found online that -1 is used to keep aspect ratio.. not sure what -2 means though. also I found this page which has a trick that may be useful to you:
http://stackoverflow.com/questions/8218363/maintaining-ffmpeg-aspect-ratio

**Comment by mdhiggins** [comment]
-2 also keeps aspect ratio but forces the number to be even (as opposed to -1 which does not)

This actually seems like its more of an FFMPEG problem since I'm not actually doing the size calculations.

**Comment by thezoggy** [comment]
maybe thats why nzbtomedia just specifies the height and width when they do their ffmpeg

**Comment by mdhiggins** [comment]
I'm not 100% convinced it makes a significant difference unless you're seeing issues with the way FFMPEG calculates the width/height and I think that's the more reliable way to do it. Does the 2 pixel difference create any weird visual artifacting?

**Comment by thezoggy** [comment]
in avcoders.py where it produces the cmd list, I swapped out `-2` for `trunc(ow/a/2)*2` per https://trac.ffmpeg.org/ticket/309

this ended up the 404 height instead of the 406...

about the difference..  cant really say as I'm not home at the moment :) I'll be back home in a few days and I'll be able to actually check the video to find out about the visual distortion/issues..

**Comment by mdhiggins** [comment]
```
elif 'wscale' in safe:
            optlist.extend(['-vf', 'scale=%s:trunc(ow/a/2)*2' % (safe['wscale'])])
        elif 'hscale' in safe:
            optlist.extend(['-vf', 'scale=trunc((oh*a)/2)*2:%s' % (safe['hscale'])])
```

How's that look? It's late and I'm working overnight so just want you to double check my equations lol

**Comment by thezoggy** [comment]
that looks right.. pretty much what i did (but only really needed the wscale one since thats what I'm hitting for my scaling)..  havent dug through ffmpeg code to see what '-2' is internally treated as.. since there is an obvious difference (although slight.. prob round up instead of rounding down.. which maybe they used as a safeguard from ever hitting 0) 

not sure if you have any sort of unit testing to make sure all the scale variations results are what is expected as before.. compare numbers / see if delta is within acceptable variance amount.. since i fully understand how these sort of changes can be hard to catch any issues until reported.

**Comment by mdhiggins** [comment]
```
If the value for @var{width} or @var{height} is -n (negative), the scale filter will
use, for the respective output size, a value that maintains the aspect
ratio of the input image, and rounds to the nearest multiple of +n.
```

**Comment by thezoggy** [comment]
yeah so looking though the code, its not '-2' its anything lower than -1 will be used as the factor...
https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_scale.c#L287

looks like this is the culprit for the difference:
https://github.com/FFmpeg/FFmpeg/commit/1e48c39ece3ec790dad9a0e308ebe1a77b2f08ba

**Comment by mdhiggins** [comment]
I implemented the change just now, looks like its working and matches the way the scene releases behave

**Comment by mdhiggins** [comment]
Actually I think that addresses all the issues you've brought up, if so you can go ahead and close this

**Comment by thezoggy** [comment]
just adding another note, profiled the manual routine off latest dev..
`>python -m cProfile manual.py -a -i F:\mp4\folder`

removed out items that had ncalls less than 10, removed items that had total/cumtime/percall less than 0.099:
```
F:\mp4>grep -v -E "^\ +[0-9]{1}\ " cprofile.txt | grep -v -E "0\.0[0-9][0-9]    0\.000    0\.0[0-9][0-9]    0\.0[0-9][0-9]"
         2782333 function calls (2755059 primitive calls) in 380.420 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    24405    0.257    0.000    1.176    0.000 HTMLParser.py:279(parse_starttag)
    20734    0.086    0.000    0.391    0.000 HTMLParser.py:363(parse_endtag)
     3660    0.005    0.000    0.169    0.000 HTMLParser.py:403(handle_startendtag)
       22    0.009    0.000    0.144    0.007 __init__.py:1(<module>)
    18496    0.086    0.000    0.120    0.000 __init__.py:145(_replace_cdata_list_attribute_values)
      732    0.005    0.000  370.296    0.506 __init__.py:165(convert)
    48831    0.083    0.000    0.191    0.000 __init__.py:260(endData)
    24394    0.071    0.000    0.124    0.000 __init__.py:301(_popToTag)
    24405    0.125    0.000    0.604    0.000 __init__.py:324(handle_starttag)
    24394    0.030    0.000    0.266    0.000 __init__.py:351(handle_endtag)
      294    0.000    0.000    0.174    0.001 __init__.py:49(compile_pattern)
    24405    0.046    0.000    0.649    0.000 _htmlparser.py:46(handle_starttag)
    24394    0.020    0.000    0.287    0.000 _htmlparser.py:58(handle_endtag)
      294    0.002    0.000    0.176    0.001 containers.py:304(__init__)
      223    0.001    0.000    0.178    0.001 containers.py:394(register_property)
   7099/3    0.127    0.000    0.233    0.078 element.py:1204(select)
    14192    0.016    0.000    0.134    0.000 element.py:1326(recursive_select)
    24407    0.137    0.000    0.333    0.000 element.py:745(__init__)
       10    0.000    0.000    0.115    0.012 extension.py:176(_load_one_plugin)
      732    0.137    0.000  370.074    0.506 ffmpeg.py:421(convert)
       10    0.000    0.000    1.973    0.197 httplib.py:1009(getresponse)
       10    0.000    0.000    1.970    0.197 httplib.py:363(_read_status)
       10    0.000    0.000    1.973    0.197 httplib.py:402(begin)
      120    0.001    0.000    1.541    0.013 httplib.py:637(_safe_read)
       10    0.000    0.000    1.981    0.198 httplib.py:787(send)
       10    0.000    0.000    1.981    0.198 httplib.py:814(_send_output)
       10    0.000    0.000    1.981    0.198 httplib.py:956(endheaders)
    91056    0.082    0.000    0.116    0.000 markupbase.py:49(updatepos)
       42    0.000    0.000    0.131    0.003 matcher.py:132(_process)
      107    0.000    0.000    1.554    0.015 models.py:669(generate)
       11    0.000    0.000    1.554    0.141 models.py:736(content)
    37/34    0.000    0.000    0.175    0.005 pkg_resources.py:2235(load)
      500    0.000    0.000    0.270    0.001 re.py:188(compile)
      927    0.004    0.000    0.273    0.000 re.py:226(_compile)
      107    0.000    0.000    1.553    0.015 response.py:286(stream)
       99    0.000    0.000    1.541    0.016 response.py:403(_handle_chunk)
      103    0.001    0.000    1.553    0.015 response.py:425(read_chunked)
      6/5    0.000    0.000    3.428    0.686 sessions.py:539(send)
      7/6    0.000    0.000    0.378    0.063 sessions.py:92(resolve_redirects)
       29    0.000    0.000    0.632    0.022 socket.py:223(meth)
      122    0.004    0.000    1.540    0.013 socket.py:336(read)
      162    0.001    0.000    1.982    0.012 socket.py:406(readline)
 4166/453    0.038    0.000    0.100    0.000 sre_compile.py:33(_compile)
      453    0.001    0.000    0.140    0.000 sre_compile.py:481(_code)
      453    0.002    0.000    0.267    0.001 sre_compile.py:496(compile)
 1137/454    0.007    0.000    0.120    0.000 sre_parse.py:302(_parse_sub)
 2933/466    0.046    0.000    0.118    0.000 sre_parse.py:380(_parse)
  454/453    0.002    0.000    0.124    0.000 sre_parse.py:676(parse)
       12    0.000    0.000    0.646    0.054 threading.py:308(wait)
       21    0.000    0.000    0.225    0.011 transformers.py:89(_load_one_plugin)
    59/52    0.015    0.000    0.177    0.003 {__import__}
      415    0.646    0.002    0.646    0.002 {method 'acquire' of 'thread.lock' objects}
2531/2415    0.003    0.000    1.558    0.001 {method 'join' of 'str' objects}
   174788    0.191    0.000    0.191    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
    53268  370.148    0.007  370.148    0.007 {method 'read' of 'file' objects}
      639    2.909    0.005    2.909    0.005 {method 'recv' of '_socket.socket' objects}
    30524    0.382    0.000    0.382    0.000 {method 'write' of 'file' objects}
```

as you can see, it took 380.420 seconds to complete.. out of that time 370.074 were inside the convert routine in ffmpeg.py... which was mainly due to read of the file (totaltime).
