### ISSUE TITLE
Unable to determine identity with long season number

### ISSUE THREAD

**Issue by dingho** [mdhiggins/sickbeard_mp4_automator#306]
Hi,
I'm unable to automatically tag files when the season is a year (4 digits).  I have to manually specify each episode.  For example:
manual.py -i e:\Looney Tunes\Looney Tunes 1940x01 Porky's Last Stand.mkv -tv 72514
will result in: 
Unable to determine identity based on filename, must enter manually

Other shows will automatically be detected and tagged no problem, so I'm wondering if it's the long season (4 digits instead of 2).  I've tried multiple formats as well, i.e. 1940x01 and S1940E01. Same problem.

**Comment by mdhiggins** [comment]
I believe this is a limitation of guessit, which is how the script guesses things like season number. For shows like this you'll most likely have to manually specify this information

**Comment by mdhiggins** [comment]
Gonna close this since its a guessit issue

**Comment by dingho** [comment]
Thanks.  Will open an issue for guessit.

**Comment by mdhiggins** [comment]
If they're able to address this just let me know so I can incorporate the changes

**Comment by dingho** [comment]
From the guessit dev, seems this is not an issue in latest version.  Can you please update?  Appreciate it.

Using S1940E01, it is identified as both year and season property. Which version are you using ?

For: Looney Tunes S1940E01 Porky's Last Stand.mkv
GuessIt found: {
    [1.00] "type": "episode",
    [1.00] "container": "mkv",
    [1.00] "episodeNumber": 1,
    [1.00] "season": 1940,
    [0.50] "title": "Porky's Last Stand",
    [0.70] "series": "Looney Tunes",
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "year": 1940
}

**Comment by mdhiggins** [comment]
Removed guessit folder from the script in the latest commit (might have to manually do it). Then just install guessit via pip and it seems to work now.

`pip install guessit`

**Comment by dingho** [comment]
Thank you.  Working as expected now.
