### ISSUE TITLE
user script after transcode

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#307]
here are two examples of the need to allow running a user script after transcoding:

1) modify filename to reflect change in resolution

so if i use mp4 automator to rescale the file.. lets say 720p to 480p.. the filename is now 'wrong'..
I wouldn't want to touch the filename until the transcode is done (so subs are searched for the right name). also if you wanted to cleanup filename/change rlsgroup

* After transcode I'd want to use to replace `.1080` or `.720` for `.480`
  > regex could be something like `\.\d{3-4}p?\.` (mental note)

2) generate screenshots for the produced file..  this could be pulled in house (as I don't need 99% of the features).. right now I have an external script that does it:
```
P:\>python automate_screenshot_upload.py F:\mp4\file\file.mp4
ffmpeg version N-74447-g767d780 Copyright (c) 2000-2015 the FFmpeg developers
Input file: file.mp4
Length: 00:19:54
Taking screenshots with ffmpeg.
Input file: file.mp4
Screenshot timecode: 00:03:19
Output file: F:\mp4\file_screenshot01.png
Screenshot timecode: 00:06:38
Output file: F:\mp4\file_screenshot02.png
Screenshot timecode: 00:09:57
Output file: F:\mp4\file_screenshot03.png
Screenshot timecode: 00:13:16
Output file: F:\mp4\file_screenshot04.png
Screenshot timecode: 00:16:35
Output file: F:\mp4\file_screenshot05.png
Done.
```

**Comment by thezoggy** [comment]
* Add support to ignore processing files under certain duration (1min 5sec) / size (50mb) -- samples

**Comment by mdhiggins** [comment]
User scripts are already supported, or are you specifically looking for something different
