### ISSUE TITLE
Add config variable to toggle the addition of  -movflags +faststart

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#309]
People may be displaying the output files on a web site with progressive downloading, thus they would want the option `-movflags +faststart`. It will move a small amount of data to the beginning of the file so it can begin playing before the file is completely downloaded. Since not everyone uses plex to just transcode on demand.. it does add a little bit more time to the encode (has to make a quick pass to reallocate the data in the file)... so default to it being off would be ideal.

Per ffmpeg docs:
```
    Run a second pass moving the index (moov atom) to the beginning of the file. This operation can take a while, and will not work in various situations such as fragmented output, thus it is not enabled by default. 
```

**Comment by thezoggy** [comment]
i know your already doing the qt-faststart on:
`relocate_moov = True/False - relocates the MOOV atom to the beginning of the file for better streaming`

but looks like you could just drop that and use the included method inside ffmpeg now.. which should help cleanup some code and the settings check all over..

**Comment by mdhiggins** [comment]
I explored and actually briefly implemented this functionality a while ago but it created some problems. There were issues with tagging of large files that would break playback if the moov atom had been moved before tagging took place. This made it more ideal to convert, then tag, then move everything once the metadata was in place.
