### ISSUE TITLE
Adding subs increase video length / bad sub found

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#313]
source video file is 42m33s, auotmator found sub... when it adds the sub the video is now 43m16s.
playing the video the sub is not in sync with the video.. so that told me to look closer at the srt file...
looking at the .srt found, the last entry is `00:43:14,999 --> 00:43:16,999`.
confirmed that the actual video file jumps from 42m33->43m16s at the end during playback.

if i strip the sub off `ffmpeg -i video.mkv -vcodec copy -acodec copy -sn video-no-subs.mkv` then the time goes back to what it should.

thus, it would be nice to have subliminal/automator check if the sub is actually valid for the file.. if theres time code marks thats longer than the media file.. pretty clear sign the sub is going to be bad.

> source: Shark.Tank.S01E09.720p.HDTV.x264-NTb.mkv

**Comment by mdhiggins** [comment]
This would be a nice feature to be built into subliminal.

One of the ways that I had attempted to minimize this previously was that I modified subliminal to accept an additional 'original filename' parameter. In some scenarios by the time subliminial is analyzing the file to attempt to find subs, the file has been renamed by Sickbeard/CP/etc and has lost most of the important identifying release information that lets it correctly identify properly timed subs. This feature seemed to work fairly well but at the same time made it a huge pain to install and keep subliminal up to date. I'll look into adding some further analysis that can maybe minimize this problem but it would definitely be something that would be better suited to incorporate into a future subliminal release. I would maybe open this issue up on their github and see what they think.

**Comment by Diaoul** [comment]
About original filename, you are free to implement whatever logic you want to give information to subliminal. The only requirement is to put the information in one of the [Video](http://subliminal.readthedocs.org/en/latest/api/video.html#subliminal.video.Video) subclasses.

For the subtitle length issue, see https://github.com/Diaoul/subliminal/issues/493

**Comment by mdhiggins** [comment]
Gonna close this since its primarily a subliminal issue/enhancement really
