### ISSUE TITLE
readme -- install VC for python 2.7

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#314]
doing fresh install on another machine (win7) I ran into an issue on installing gevent via pip.
error  `Unable to find vcvarsall.bat` this is because python cant compile... upon some research I found there is a VC for python 2.7, and after installing it gevent installed just fine.

* note that users should install VC for python 2.7 before trying to do pip install (no reboot needed). 

* just tell people to install subliminal and drop the list of the dependent install commands (could just list them under subliminal as a note.. but as its currently listed.. people may install the dependents manually before even getting to subliminal)

* guessit is part of subliminal, so no need to install that manually..

VC for Python 2.7 -- http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by mdhiggins** [comment]
Updated readme
