### ISSUE TITLE
QUESTION - Just convert sab download to MP4 and do nothing

### ISSUE THREAD

**Issue by nn-afly** [mdhiggins/sickbeard_mp4_automator#317]
I'm sure I am missing something simple here, I have this set up and working well with sickbeard but for  movies (sab category - 'movies') the movie file is already in its final resting place. I just want it to convert the mkv to an mp4, delete the mkv and nothing else.

What I am getting instead is 'ERROR - No valid category detected.' which aborts before conversion

Is this possible or is a 3rd party provider like couchpotato to hand off to compulsory?

**Comment by mdhiggins** [comment]
Set your category to your bypass category and you should be good to go.

**Comment by nn-afly** [comment]
yep that simple :)
