### ISSUE TITLE
[Enhancement Request]

### ISSUE THREAD

**Issue by mtompkins** [mdhiggins/sickbeard_mp4_automator#318]
Please consider adding x265

**Comment by mdhiggins** [comment]
Done 1ff2dad9a4df319ef8966f122f4e38461d112fb2

Make sure you have a build of FFMPEG that supports h265 and all the prerequisites.

https://trac.ffmpeg.org/wiki/Encode/H.265

Reopen if there's any issues.

**Comment by mtompkins** [comment]
Thanks for the additional codec. It may need a bit more attention however, as I have failures when trying to use it.

Specifically I have:
```
video-codec = h265,h264,x264
```
I use manual.py -a Example of the failure produced:
```
Reading video stream.
Video codec detected: mpeg2video.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
No valid subtitle language specified, cannot download subtitles.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "copy",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "h265",
        "bitrate": 17114.08755,
        "level": null
    },
    "format": "mp4"
}
Starting conversion.
An unexpected error occurred, processing of this file has failed
super(type, obj): obj must be an instance or subtype of type
```

If I remove the h265 and revert to h264 the conversion happens as expected.

**Comment by mdhiggins** [comment]
The next step will be to have you get the FFMPEG command that the script is generating and run it manually and see if FFMPEG is spitting out any particular errors.

You can do this by changing your logging level to 'debug' in logging.ini and finding the full command in the info.log file

**Comment by mtompkins** [comment]
I did confirm that x265 is working directly with ffmpeg which it is.
I will revert with your debug request as soon as I am able.

Thanks for sharing this script and your work.

**Comment by mtompkins** [comment]
So before I got an opportunity to test 265 specifically I came across the following error while running for h264 (so the issue many not be specific to 265).

```
<FFMpegConvertError error="Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height", pid=22907, cmd="/usr/local/bin/ffmpeg -fix_sub_duration -i InFile.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -st
rict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -f mp4 -threads auto -y InFile.mp4">
```

I parsed out the generated ffmpeg to test and it returns as follows:
```
ffmpeg -fix_sub_duration -i "InFile.mkv" -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -f mp4 -threads auto -y "InFile.mp4"
ffmpeg version N-75192-gabef638 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --disable-doc --disable-ffplay --disable-htmlpages --disable-txtpages
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  1.100 / 57.  1.100
  libavformat    57.  0.100 / 57.  0.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  1.100 /  6.  1.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'InFile.mkv':
  Metadata:
    encoder         : libebml v0.8.0 + libmatroska v0.9.0
    creation_time   : 2013-11-07 08:09:24
  Duration: 00:44:06.44, start: 0.000000, bitrate: 10616 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: flac, 96000 Hz, 5.1(side), s16 (default)
[AVFilterGraph @ 0x3e81000] [Eval @ 0x7ffd66a33f20] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x3e81000] Unable to parse option value "auto"
[AVFilterGraph @ 0x3d89540] [Eval @ 0x7ffd66a33f20] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x3d89540] Unable to parse option value "auto"
[ac3 @ 0x3db42a0] invalid sample rate
Output #0, mp4, to 'InFile.mp4':
  Metadata:
    encoder         : libebml v0.8.0 + libmatroska v0.9.0
    Stream #0:0(eng): Video: h264, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: aac, 96000 Hz, stereo, fltp (16 bit), 256 kb/s (default)
    Metadata:
      encoder         : Lavc57.1.100 aac
    Stream #0:2(eng): Audio: ac3, 0 channels, 128 kb/s (default)
    Metadata:
      encoder         : Lavc57.1.100 ac3
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (flac (native) -> aac (native))
  Stream #0:1 -> #0:2 (flac (native) -> ac3 (native))
Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height
```
I will update with a 265 debug shortly

**Comment by mdhiggins** [comment]
This error looks unrelated to the video codec but appears to be happening because stream 2 is being set to 0 channels. Not sure why exactly that is the case because the `-ac:a:1 6` parameter is present in the command line which should be setting the channels to 6.

**Comment by mtompkins** [comment]
Thank you, and I agree. I believe it was just happen stance that I came across this issue while testing the h265 implementation. I am running now with h265 active / debug set and so far no errors.

**Comment by mdhiggins** [comment]
I'm not sure why the channels or bitrate aren't being applied to that second audio stream, they're all correct and present in the command line parameters. Is this a consistent problem with all video files or just an anomaly from this specific file?

**Comment by mdhiggins** [comment]
`Undefined constant or missing '(' in 'auto'` this error from the AVFilterGraph might be indicative of a problem with the audio stream that's leading to this error. This may be specific to this particular test file if its only happening in this isolated case.

**Comment by mtompkins** [comment]
Understood.

I'll monitor and if I see other sources creating the condition I will advise on a new ticket.
I think specific to your h265 addition things are running as they should.

Thx again.

**Comment by mdhiggins** [comment]
Alternatively you can email me a copy of that file from the above log and I'll try running it on my end.

**Comment by mtompkins** [comment]
I'll send you a public link shortly.
FWIW other 6 channel files are processing normally so it just may well be a corrupt source.

**Comment by mdhiggins** [comment]
If all other files are processing normally I would just chalk it up to this file being corrupt, no need to send it. Glad everything is working!

**Comment by mtompkins** [comment]
OK - thanks again.
