### ISSUE TITLE
sab 0.8.x - pp argument changes

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#319]
looking at when the user script is called, we see things have changed.. 

0.8.x:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L447
`
                script_log, script_ret = external_processing(short_path(script_path, False), short_path(workdir_complete, False), nzo.filename,
                                                             dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

0.7.20:
https://github.com/sabnzbd/sabnzbd/blob/0.7.x/sabnzbd/postproc.py#L442
`
                script_log, script_ret = external_processing(script_path, workdir_complete, nzo.filename,
                                                             msgid, dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`
seeing some oddities.. working on trying to get them fixed in sab 0.8.x code before i suggest just modifying/coding to catch the differences in the sab pp script in automator

**Comment by mdhiggins** [comment]
Did they end up scraping this change?

**Comment by thezoggy** [comment]
so nothing actually changed except that the paths for the script/workdir are wrapped in a short_path function that returns a shorten ASCII path for windows users (all others are untouched), this is to help to combat path issues.. doesnt affect scripts in any way that ive seen. i did discover a few bugs with the code which we've worked to resolve.. so all good now. hence i closed this out.

**Comment by mdhiggins** [comment]
Ah ok, thanks for the explanation
