### ISSUE TITLE
mkvtomp4 - ERROR - Error cleaning up QTFS temp files

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#321]
Getting the following error in Sickrage after the last update

AA2015-09-10 10:15:48 - mkvtomp4 - ERROR - Error cleaning up QTFS temp files.
AAOSError: [Errno 16] Device or resource busy: "/media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v"
AA    os.remove(filename)
AA  File "/home/raydias/sickbeard_mp4_automator/mkvtomp4.py", line 682, in removeFile
AATraceback (most recent call last):
AA2015-09-10 10:15:38 - mkvtomp4 - ERROR - Unable to remove file /media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v.
AAOSError: [Errno 16] Device or resource busy: "/media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v"
AA    os.remove(filename)
AA  File "/home/raydias/sickbeard_mp4_automator/mkvtomp4.py", line 682, in removeFile
AATraceback (most recent call last):
AA2015-09-10 10:15:27 - mkvtomp4 - ERROR - Unable to remove file /media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v.
AAOSError: [Errno 16] Device or resource busy: "/media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v"
AA    os.remove(filename)
AA  File "/home/raydias/sickbeard_mp4_automator/mkvtomp4.py", line 682, in removeFile
AATraceback (most recent call last):
AA2015-09-10 10:15:16 - mkvtomp4 - ERROR - Unable to remove file /media/tv/America's Funniest Home Videos/America's Funniest Home Videos - 13x05 - October 25, 2002.m4v.

**Comment by rrd911** [comment]
scratch this. I found the issue. the mkvtomb4.py file was owned by the wrong user.

**Comment by rrd911** [comment]
ok after 1 file processed correctly the remaining files are giving the error in Sickrage.

**Comment by mdhiggins** [comment]
I think this is still probably a permissions issues on your end, not something wrong with the script. I would check all your directory permissions and see if you can elevate them. The other possible issue is something is scanning the file and flagging it as in use before the script can finish what its doing. If you have an application like plex auto-scanning the directories this can happen.

**Comment by mdhiggins** [comment]
Likely permissions issue, not reproducible. Will close for now
