### ISSUE TITLE
Deluge Post processing not working

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#324]
Hi no matter what I try or how closely I follow the instructions the script will not run with delgue, a CMD will pop up but nothing will happen.

**Comment by mdhiggins** [comment]
Anything in the log files about the deluge post processing script? And are you setting your labels correctly?

**Comment by morpheus2n2** [comment]
Unfortunately not as if its not even attempting to run, Deluge is pointing to the .bat file as instructed in the readme but once a file has downloaded it will open a CMD window but there's noting in it, there's no ffmpeg opened up under task manger and the log file show nothing at all with in the time frame, I have even created a new log file and did a test with just deluge running and nothing is being written at all lol.

But here's my autoprocess.ini, with api_keys and log-in details "REMOVED" for obvious reasons

[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Sonarr]
host = localhost
port = 38082
web_root =
ssl = 0
apikey = "REMOVED"

[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
output_directory =
copy_to =
move_to = D:\Downloads\To Sort
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 2000
video-max-width =
h264-max-level = 4.1
ios-audio = True
ios-first-track-only = False
max-audio-channels = 6
audio-codec = aac,ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 160
subtitle-codec = mov_text
subtitle-language = en
subtitle-default-language = en
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 38083
username = "REMOVED"
password = "REMOVED".
web_root =
ssl = 0
apikey = "REMOVED"
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert =
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username =
password =

[Deluge]
host = localhost
username = "REMOVED"
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Plex]
host = localhost
port = 32400
refresh = True
token =

**Comment by mdhiggins** [comment]
If you just double click on the batch file you should get a few entries in the log under delugePostProcess, I would start there and try that. If that doesn't work then for some reason the batch file isn't executing the python command.

**Comment by morpheus2n2** [comment]
ok this is what I got.

2015-09-18 14:33:56 - delugePostProcess - INFO - Deluge post processing started.
2015-09-18 14:33:56 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

Odd :)

**Comment by mdhiggins** [comment]
Alright well that's a good sign, that means the batch file does in fact work. Next step I guess is to send me screenshots of your deluge settings (labels/execute plugins)

**Comment by morpheus2n2** [comment]
![screenshot 2015-09-18 14 41 51](https://cloud.githubusercontent.com/assets/14253602/9960623/8a61bdb2-5e13-11e5-917c-b7697448b747.png)

**Comment by mdhiggins** [comment]
So first issue I'm noticing is that you're using deluge and not the deluge daemon, which may be where your issues are coming from. The regular deluge client is limited and doesn't support communicating with outside scripts over HTTP. The daemon has a web-based interface and all the relevant information is communicated to the script via the DelugeRPC which the standard client doesn't support. Deluged.exe is the executable you need to be running, not deluge.exe

**Comment by morpheus2n2** [comment]
yeah that's the one that's always running but was easier to get a screenshot via the standard client lol

**Comment by mdhiggins** [comment]
Hm otherwise everything looks good. The only other thing I can think of is that there is some issue with relative paths of the batch file. You can try modifying the batch file so that it points to the absolute path of the delugePostProcess.py file

**Comment by morpheus2n2** [comment]
ok cool will give it a go thanks so much for your help :)

**Comment by morpheus2n2** [comment]
Just to check this is what the batch looks like now 

"python "%~dp0delugePostProcess.py" %1 %2 %3"

How would I change it to the absolute path, witch is "C:\Python27\Converter\delugePostProcess.py"

**Comment by mdhiggins** [comment]
`python "C:\Python27\Converter\delugePostProcess.py" %1 %2 %3`

**Comment by morpheus2n2** [comment]
that's what I though thank you again :)

**Comment by mdhiggins** [comment]
No problem, let me know if that helps at all

**Comment by morpheus2n2** [comment]
Hi to update you, deluge is now logging and this is all I get but still nothing is actually happening.

2015-09-19 05:25:37 - delugePostProcess - INFO - Deluge post processing started.
2015-09-19 05:25:37 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?
2015-09-19 05:32:06 - delugePostProcess - INFO - Deluge post processing started.
2015-09-19 05:32:06 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

**Comment by mdhiggins** [comment]
You definitely left the `%1 %2 %3` stuff in the bat file right?

**Comment by morpheus2n2** [comment]
Yep

![screenshot 2015-09-20 00 12 43](https://cloud.githubusercontent.com/assets/14253602/9978529/61a8e93a-5f2c-11e5-8511-620ca1c53f02.png)

**Comment by mdhiggins** [comment]
Hm I have no idea why the command line parameters aren't being carried over to the python script.

Only thing I can think of is this:
http://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t

See if the solution offered in that discussion helps at all.

**Comment by mdhiggins** [comment]
Any luck?

**Comment by morpheus2n2** [comment]
Unfortunately not I have given up on it for now, it works fine with sabnzbd and manually its just deluge lol.

**Comment by mdhiggins** [comment]
Did you get a chance to try that last solution I posted from stackoverflow?

**Comment by morpheus2n2** [comment]
Hi just to let you know I'm still looking through this (little over my head) lol

**Comment by mdhiggins** [comment]
Try referencing this article instead and see if it helps

http://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows/

That article was written for Python 26 so just adjust anywhere that uses 26 to 27.

Let me know.

**Comment by mdhiggins** [comment]
Gonna close this for now as it seems like a windows issue where the command line parameters aren't being passed to python scripts
