### ISSUE TITLE
ImportError: No module named six.moves.xmlrpc_client

### ISSUE THREAD

**Issue by screwzloose** [mdhiggins/sickbeard_mp4_automator#327]
After downloading/installing the latest sickbeard_mp4_automator... I get the following error when I manually process a movie...
>
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/mnt/m/readSettings.py", line 235, in __init__
    import subliminal
  File "/usr/local/lib/python2.7/site-packages/subliminal/__init__.py", line 14, in <module>
    from .providers import Provider
  File "/usr/local/lib/python2.7/site-packages/subliminal/providers/__init__.py", line 6, in <module>
    from six.moves.xmlrpc_client import SafeTransport
ImportError: No module named six.moves.xmlrpc_client
64bit Python.
Processing The Town
>

Troubleshooting steps I've taken...

Reinstalled all packages, requests, gevent, guessit, subliminal, stevedore, dateutil. Not sure why it says subliminal is not install, pip show subliminal yields the following...
>
Metadata-Version: 2.0
Name: subliminal
Version: 1.0.1
Summary: Subtitles, faster than your thoughts
Home-page: https://github.com/Diaoul/subliminal
Author: Antoine Bertin
Author-email: diaoulael@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: beautifulsoup4, pysrt, enzyme, chardet, guessit, babelfish, click, requests, six, dogpile.cache, stevedore
>

I'm at a bit of a loss for next steps...Thoughts?

**Comment by mdhiggins** [comment]
Try `pip install -U six`

**Comment by screwzloose** [comment]
result:
>
root@Plex:/mnt/m #  pip install -U six
Requirement already up-to-date: six in /usr/local/lib/python2.7/site-packages
>

**Comment by mdhiggins** [comment]
What operating system you running?

**Comment by screwzloose** [comment]
FreeBSD 9.3-RELEASE-p25 amd64

**Comment by mdhiggins** [comment]
Try uninstalling six `sudo pip uninstall six` and reinstalling it using the easy_install script included with setup tools. 

`easy_install six`

**Comment by screwzloose** [comment]
You are the man. Sending another donate your way.

**Comment by mdhiggins** [comment]
<3

Glad that worked, enjoy!
