### ISSUE TITLE
Add support for mov files

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#328]
```
File /tmp/Movies/Big Buck Bunny/big_buck_bunny_1080p_h264.mov is not in the correct format
```

I am converting to mkv using `ffmpeg -i <filename>.mov -vcodec ffv1 -acodec pcm_s16le <filename>.mkv`

Edit: I switched containers to mkv using `ffmpeg -i big_buck_bunny_1080p_h264.mov -codec copy bunny.mov` but it still gives me this error.

**Comment by HazCod** [comment]
Added support in https://github.com/mdhiggins/sickbeard_mp4_automator/pull/326

**Comment by HazCod** [comment]
This could be done prettier by just doing a `ffprobe -print_format json -v quiet -show_format file.mov` and checking if format->format_name isn't empty

**Comment by mdhiggins** [comment]
Went ahead and just added mov to the list for now. Gonna have to review the rest of the stuff when I have more time.
