### ISSUE TITLE
Couch Potato integration

### ISSUE THREAD

**Issue by snoby** [mdhiggins/sickbeard_mp4_automator#329]
Hi,
I'm following the integration / setup instructions for couch potato and don't quite understand the instruction for point 2:

>Edit main.py in the setup\PostProcess folder
>Set the path variable to the script location
>By default it points to C:\\Scripts\\
>Use double backslahses

I'm doing this integration on a MAC.  So what is the significance of a "scripts" directory?  Am I pointing this directory to a scripts directory in Couch Potatoe server?  Sorry for the basic question.  Thanks!

**Comment by Trixter69** [comment]
Your telling Couchpotato where sickbeard_mp4_automator is on your mac.

i.e. Lets say you cloned SMA to a folder called Git in your user folder you would change c\\Scripts\\ in main.py to be //Users//'your user name'//Git//

**Comment by mdhiggins** [comment]
Pretty much exactly what Trixter said. The scripts directory is just wherever you've chosen to download and extract all the files that make up the script (since the couchpotato files have to be copied into couchpotato's installation directory)

**Comment by snoby** [comment]
Ok I think my confusion comes from the fact that my couch potato install doesn't have a custom_plugins directory.

**Comment by mdhiggins** [comment]
It should, I would check the About page under couchpotato and check in the directories listed there.

**Comment by Trixter69** [comment]
If its not there you create the custom_plugin folder.
