### ISSUE TITLE
tMDB failing

### ISSUE THREAD

**Issue by zybeon** [mdhiggins/sickbeard_mp4_automator#330]
Processing file /-/Movies/RoboCop (1987)/RoboCop.mp4
    Matched movie title as: RoboCop 2014-02-12
    Failed to connect to tMDB, trying again in 20 seconds.
    Traceback (most recent call last):
      File "/home/---/.mp4automator/tmdb_mp4.py", line 38, in __init__
        self.movie = tmdb.Movie(imdbid)
      File "/home/---/.mp4automator/tmdb_api/tmdb.py", line 122, in __init__
        self.update_configuration()
      File "/home/---/.mp4automator/tmdb_api/tmdb.py", line 66, in update_configuration
        config['api']['backdrop.sizes'] = c['images']['backdrop_sizes']
    KeyError: 'images'

This is the error I get when processing files with manual.py. I just updated everything before running this. Possibly incompatibility somewhere.

Or am I complaining about a previously know issue? I kind of remember this coming up before.

**Comment by mdhiggins** [comment]
Hm not sure why you'd be getting that error

What's your `download-artwork` setting set to? Not that it should be making a difference.

I would honestly just try backing up your autoProcess.ini file and reinstalling the script I think something may be corrupted. Also maybe just make sure you can access the tmdb via your web browser.

**Comment by zybeon** [comment]
tagfile = True
    tag-language = en
    download-artwork = True
    download-subs = True
    embed-subs = True
    sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles

And I can ping tmdb on my server.

Will try a reinstall.

**Comment by mdhiggins** [comment]
Can't seem to reproduce this on any of my testing environments, any luck on your end?

**Comment by zybeon** [comment]
I'm closing this till I can figure out what the problem is related to.
