### ISSUE TITLE
Couch potato loses release information

### ISSUE THREAD

**Issue by astlaurent** [mdhiggins/sickbeard_mp4_automator#331]
Hello

not sure if this problem is with couchpotato or that it is going through the post processing script. It seems that when couch potato snatches a movie and then all the post processing happens by the time the movie makes it into the renamer directory couch doesn't know where it came from. For example it will mark the movie as snatched but will not mark that release as download, it marks a NA release as downloaded. The biggest issue that i have with this is that sometimes couch potato will mark the quality incorrect or different because it does not seem to realize where it came from and sometimes it will keep snatching and downloading the same release over and over again because it never knows that the release was downloaded.
![2015-09-30 14_48_07-couchpotato](https://cloud.githubusercontent.com/assets/11797070/10203563/ae77873e-6784-11e5-8f9d-2d176c45d959.jpg)

**Comment by mdhiggins** [comment]
I think this is just related to couchpotato and not the script
