### ISSUE TITLE
Help with KeyError: 'alpha3'

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#334]
Hi, i am having the following issue with the mp4 script

my setup is:

python 2.7
sickrage
deluged

Sickrage snatches the torrent fine and passes it to deluged, deluged then downloads and executes the mp4 script then nothing happens,i get the following in the log

2015-10-02 09:35:40 - delugePostProcess - INFO - Deluge post processing started.
2015-10-02 09:35:40 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-10-02 09:35:40 - readSettings - ERROR - Unable to set tag language, defaulting to English.
Traceback (most recent call last):
  File "C:\scripts\readSettings.py", line 367, in __init__
    babel = Language.fromalpha3(self.taglanguage)
  File "C:\scripts\babelfish\language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\scripts\babelfish\converters\__init__.py", line 253, in __getitem__
    raise KeyError(name)
KeyError: 'alpha3'

![deluge](https://cloud.githubusercontent.com/assets/14946670/10257474/93c17e6e-694f-11e5-9a45-f62d61656a59.png)
![sickrage](https://cloud.githubusercontent.com/assets/14946670/10257516/db051380-694f-11e5-88f5-3706688ee875.png)
![autop](https://cloud.githubusercontent.com/assets/14946670/10257555/0e234638-6950-11e5-93e4-8022d969e0d8.png)

Can you see what i am doing wrong or help me further?

Thanks

**Comment by morpheus2n2** [comment]
This is very much the same problem I was having here https://github.com/mdhiggins/sickbeard_mp4_automator/issues/324 
I have yet to find a way to make it work :(

**Comment by ptowns188** [comment]
EDIT: Running manual.py seems to work perfect i still get the "KeyError: 'alpha3'" but it carries on and does its job perfectly

so it seems to be when deluge executes the delugePostProcess.bat something is going wrong

Anyone can help?

Thanks

**Comment by ptowns188** [comment]
I have a question, does delugePostProcess.py look in a specific directory for deluged config files?

My Deluge configs are kept in C:\config_location

Could this be the reason? if so how do i ammend the file?


Thanks

**Comment by ptowns188** [comment]
i have no idea if i am on the right path or not so maybe the author can reply when he gets this but i manually ran the client.py file in the deluge folder and got this

C:\scripts\deluge>client.py
Traceback (most recent call last):
  File "C:\scripts\deluge\client.py", line 8, in <mo
    from .exceptions import DelugeRPCError
ValueError: Attempted relative import in non-package

**Comment by mdhiggins** [comment]
The post process script communicates with the deluge daemon over the ports specified in the autoProcess.ini, it doesn't look at the deluge config files directly.

I use deluge on a windows setup with no issues so I suspect there is an issue in the setup or a dependency that needs to be addressed. I had posted an article about ensuring python is accepting command line variables for @morpheus2n2 to try to see if it resolved his issue but hadn't heard back. As far as the alpha3 error goes, I'll look into why you're getting that as well.

**Comment by mdhiggins** [comment]
I would recommend removing the babelfish folder from your script directory and installing the current babelfish package via pip (`pip install babelfish`) and see if that resolves your alpha3 error

**Comment by mdhiggins** [comment]
This also appears to be different than the error @morpheus2n2  was getting, probably unrelated issues.

**Comment by ptowns188** [comment]
hi thanks i will give it a try later on, also i got this whole process working perfectly on ubunru 14.04 64bit.

The only difference i see is that on ubuntu 14.04 the python version is 2.7.6 and the one i was using on windows was 2.7.10

could this be related?

**Comment by mdhiggins** [comment]
Hm, maybe but I don't see why that would be the case; unless there's a bug with older versions of babelfish and the newer versions of 2.7. You could try the update as outlined though and see if it resolves it.

**Comment by thejacobsons** [comment]
I also see the KeyError: 'alpha3' with a Python 2.7, sonarr, uTorrent setup.

**Comment by ptowns188** [comment]
@thejacobsons - Yeah i couldnt solve this on Windows, I get the same error on linux but the script carries on as normal and completes the task

**Comment by mdhiggins** [comment]
I wonder if its related to python version. What's the full python version you're running?

Can't seem to reproduce this KeyError

**Comment by ptowns188** [comment]
I have tried it on both 2.7.6 and 2.7.10 with the same result on both using windows 
On ubuntu I am using 2.7.6 and still get the key frame error but the script carries on and completes it's job but on windows it's stalls at that error 


Sent from my Samsung device

-------- Original message --------

**Comment by mdhiggins** [comment]
Make sure on Windows you don't have a babelfish or guessit directory in your C:\Scripts\ folder, if you do delete those directories and let me know

**Comment by mdhiggins** [comment]
Seems a decent number of people are having this issue but I can't seem to reproduce it.

Any updates/luck?

**Comment by ptowns188** [comment]
if it makes a difference i was trying on windows server 2008 and 2012 but couldnt get it to work on either

**Comment by mdhiggins** [comment]
What version of babelfish are you running?

**Comment by rrd911** [comment]
I am seeing the same issue. I have Sickrage initiating the post processing script.

AA2015-10-13 08:51:21 - SickbeardPostConversion - INFO - Processing /media/tv_shows/Last Week Tonight with John Oliver/Last Week Tonight with John Oliver - 2x29 - Episode 53.mp4.
AAKeyError: 'alpha3'
AA    raise KeyError(name)
AA  File "/usr/local/lib/python2.7/dist-packages/babelfish/converters/__init__.py", line 253, in __getitem__
AA    return cls(*language_converters[converter].reverse(code))
AA  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 110, in fromcode
AA    babel = Language.fromalpha3(self.taglanguage)
AA  File "/home/raydias/sickbeard_mp4_automator/readSettings.py", line 367, in __init__
AATraceback (most recent call last):
AA2015-10-13 08:51:21 - readSettings - ERROR - Unable to set tag language, defaulting to English.
AA2015-10-13 08:51:21 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-10-13 08:51:21 INFO     POSTPROCESSER :: Executing command [u'/usr/bin/python', '/home/raydias/sickbeard_mp4_automator/postConversion.py', u'/media/tv_shows/Last Week Tonight with John Oliver/Last Week Tonight with John Oliver - 2x29 - Episode 53.mp4', u'/media/tv_complete/Last Week Tonight with John Oliver - 2x29 - Episode 53.mp4', '278518', '2', '29', '2015-10-04']

**Comment by mdhiggins** [comment]
What version of babelfish are you running?

**Comment by rrd911** [comment]
pip list gives me babelfish (0.5.4)

**Comment by rrd911** [comment]
update adding the python-babelfish had no effect on the error (wasn't sure it would).

**Comment by mdhiggins** [comment]
Just pushed 4b1bc6fc75eff75046e74fec68ab52a41c3da047 with an attempted fix

Update and see if it fixes the issue

**Comment by rrd911** [comment]
so here is what I have done.
- installed python-babelfish (not sure if this had any effect so I left it installed)
- updated to latest fix

error is gone 

thanks

**Comment by mdhiggins** [comment]
Good stuff, finally
