### ISSUE TITLE
Babelfish issue: No such file or directory

### ISSUE THREAD

**Issue by xpack90** [mdhiggins/sickbeard_mp4_automator#335]
I did a git pull and saw a lot of babelfish file deletions so I re read the README and installed the new pip tools but now I get this error when running it automated or with manual.py

IOError: [Errno 2] No such file or directory: u'/opt/Automator/babelfish/data/iso-3166-1.txt'

So I created the directory data and the txt file and then I got this error 

IOError: [Errno 2] No such file or directory: u'/opt/Automator/babelfish/data/iso15924-utf8-20131012.txt'

**Comment by mdhiggins** [comment]
I would try deleting the entire babelfish directory from the Automator folder and see if that fixes it

**Comment by xpack90** [comment]
That was it, that fixed the issues thanks!
