### ISSUE TITLE
sonarr not moving file after script is run

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#336]
2015-10-05 18:29:26 - delugePostProcess - INFO - Passing /home/plex/deluge/complete/temp_dir directory to Sonarr.
2015-10-05 18:29:26 - autoprocess.sonarr - INFO - Sonarr notifier started.
2015-10-05 18:29:26 - autoprocess.sonarr - DEBUG - Sonarr host: localhost.
2015-10-05 18:29:26 - autoprocess.sonarr - DEBUG - Sonarr port: 8989.
2015-10-05 18:29:26 - autoprocess.sonarr - DEBUG - Sonarr apikey: KEY
2015-10-05 18:29:26 - autoprocess.sonarr - DEBUG - Sonarr protocol: http://.
2015-10-05 18:29:26 - autoprocess.sonarr - DEBUG - URL 'http://localhost:8989/api/command' with payload '{'path': '/home/plex/deluge/complete/temp_dir', 'name': 'downloadedepisodesscan'}.'
2015-10-05 18:29:26 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/home/plex/deluge/complete/temp_dir'.
2015-10-05 18:29:26 - urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2015-10-05 18:29:26 - urllib3.connectionpool - DEBUG - Setting read timeout to None
2015-10-05 18:29:26 - urllib3.connectionpool - DEBUG - "POST /api/command HTTP/1.1" 201 None
2015-10-05 18:29:26 - autoprocess.sonarr - INFO - Sonarr response: queued.
2015-10-05 18:29:26 - delugePostProcess - ERROR - Unable to delete temporary directory.
Traceback (most recent call last):
  File "/home/plex/mp4/delugePostProcess.py", line 114, in <module>
    os.rmdir(delete_dir)
OSError: [Errno 39] Directory not empty: '/home/plex/deluge/complete/temp_dir'

as the title says, after script runs the file and passes back to sonarr nothing happens

anyone help?

**Comment by ptowns188** [comment]
Found this in sonarr if its any help?

15-10-5 19:36:44.7|Trace|CommandQueueManager|Publishing DownloadedEpisodesScan
15-10-5 19:36:44.7|Trace|CommandQueueManager|Checking if command is queued or started: DownloadedEpisodesScan
15-10-5 19:36:44.7|Trace|CommandQueueManager|Inserting new command: DownloadedEpisodesScan
15-10-5 19:36:45.0|Trace|CommandExecutor|DownloadedEpisodesScanCommand -> DownloadedEpisodesCommandService
15-10-5 19:36:45.0|Trace|CommandQueueManager|Marking command as started: DownloadedEpisodesScan
15-10-5 19:36:45.0|Debug|Parser|Parsing string 'temp_dir'
15-10-5 19:36:45.0|Debug|Parser|Unable to parse temp_dir
15-10-5 19:36:45.0|Debug|DownloadedEpisodesImportService|Unknown Series temp_dir

**Comment by mdhiggins** [comment]
Looks like Sonarr isn't recognizing the series you're trying to download for some reason, what's the show?

**Comment by ptowns188** [comment]
It should do its called
The Big Bang Theory


Sent from my Samsung device

-------- Original message --------

**Comment by mdhiggins** [comment]
Whats the filename?

**Comment by mdhiggins** [comment]
And is it doing this with every file you try or just this one?

**Comment by ptowns188** [comment]
this file: the.big.bang.theory.822.hdtv-lol.mp4

and on every file i try to run

also one question off topic a liitle, if i run the sonarr post process test script you did do i still have to point deluge at its post process script or is that not needed now?

**Comment by mdhiggins** [comment]
Not sure why its failing to read the file from the temp_dir, I'll try to look into it.

As far as the sonarr post process script, you'll still need both. The deluge script passes the download back to Sonarr, the new Sonarr script incorporates tagging similarly to how Sickbeard/Couch Potato operate.

**Comment by ptowns188** [comment]
ive just updated to the develop branch now so will try it again and see if its still the same

**Comment by mdhiggins** [comment]
Maybe @outlyer can add some insight since I know he's got a sonarr setup up and running

Its on my todo list to switch my server over to sonarr but I haven't got around to it yet.

**Comment by mdhiggins** [comment]
Keep me posted

**Comment by ptowns188** [comment]
nope still the same on dev branch.

if you want your more than welcome to log in to my VPS to look at my setup? its only a test vps so go ahead and let me know and i will email you the login

**Comment by mdhiggins** [comment]
I wonder if for some stupid reason the `temp_dir` folder name is confusing Sonarr. Not sure why other Sonarr users aren't reporting the same problem but I'm wondering if you popped open the delugePostProcess.py file and went to line 62 and changed the folder name from `temp_dir` to something like `sonarr` and reran it if that would make everything happy.

**Comment by ptowns188** [comment]
nope didnt work, jus changes the error to cant parse sonarr now

is the script sendinf the full path of the directory to sonarr? and is it telling sonarr to look inside the directory?

Thanks

**Comment by outlyer** [comment]
@mdhiggins / @ptowns188 :  I don't usually use Deluge, but I tried setting it up to see if I could reproduce. It worked without any issues on my end. Couple of things however:

*I did not set up Deluge in sickbeard_mp4_automator at all*

The autoProcess.ini is the default with no fields configured. I also haven't set up Sonarr in autoProcess.ini, but I'm just using the script from #286 and it's running through Sonarr, not through Deluge or anything else. 

Sonarr took the file and post processed it. As a result, my info.log has no reference to delugePostProcess though @ptowns188 seems to have one.  Here is the relevant bit of info.log where sickbeard_mp4_automator recieves the file from Sonarr. After this, it's pretty much the same as any other file being processed. 

```
2015-10-06 11:47:20 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2015-10-06 11:47:20 - SonarrPostConversion - INFO - Processing example.mkv.
```

I'm guessing that @ptowns188 is running into an issue where both Sonarr and sickbeard_mp4_automator are both receiving the file from Deluge at the same time and that is the problem. 

From autoProcess.ini

```ini
[Deluge]
host = localhost
username =
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

```

**Comment by ptowns188** [comment]
@outlyer ok I will give your way a shot to see if i can get it to work that way.

May I ask to see a picture of what your Sonarr download settings look like and the "Drone Factory Options" part

Thanks

**Comment by outlyer** [comment]
@ptowns188 I don't have anything in there. Both Deluge/NZBGet communicate with Sonarr over sockets so there isn't any need to watch a folder...  

![drone](https://cloud.githubusercontent.com/assets/1550429/10320981/4cb178ba-6c44-11e5-8fa0-67833857119d.jpg)

**Comment by mdhiggins** [comment]
Does Sonarr not need a special script to notify it when downloads have completed from programs like SAB or Deluge in the same way Sickbeard/CP or SR need?

**Comment by ptowns188** [comment]
@outlyer  im still getting the exact same error when using the sonarr script, when it passes back to sonarr it cant be parsed

if you are willing to log in to my VPS and have a look at what i am doing wrong i would be greatfull
if you are will you please email me at paultowns188@gmail.com and i will reply with my details

Thanks

**Comment by mdhiggins** [comment]
Got my sonarr setup working, think @outlyer is right and that this is related to the 'completed download handling' interfering with the script returning the new converted file. Gonna play around with it and see if I can't get things resolved.

**Comment by ptowns188** [comment]
@mdhiggins are you getting the same results as me when you test with sonarr?

**Comment by mdhiggins** [comment]
Yeah I'm able to reproduce it now, just trying to figure out why its struggling to parse the path

**Comment by ptowns188** [comment]
ok @mdhiggins please post when you have a fix

**Comment by mdhiggins** [comment]
https://forums.sonarr.tv/t/downloadedepisodesscan-not-working-when-path-is-supplied/7369 

Looks like we're not the only ones having this issue

**Comment by ptowns188** [comment]
so as it stands now you would have to code the script to post process the file inside a folder which has the same show name as the file?

**Comment by mdhiggins** [comment]
Not really because the show name isn't known to the downloader. You could guess it based on the file name but that's unreliable. If you're running a dev version of Sonarr you can simply disable the post-processing from deluge, enable the "Completed Download Handling" within Sonarr which will let it automatically track and act on torrents without any script required, then setup the new beta version of the Sonarr post processing script #286 found here, and just let the converison/tagging be done after Sonarr moves everything.

**Comment by ptowns188** [comment]
I tried that method with the same results
the sonarr script got called from sonarr the conversion took place then when trying to pass back to sonarr its unable to parse the folder, unless my settings are off i dont no what else to try

**Comment by mdhiggins** [comment]
It shouldn't have to pass anything back to Sonarr if you're doing it via the 2nd method

**Comment by deanishe** [comment]
To clarify, [this is apparently the intended behaviour](https://forums.sonarr.tv/t/downloadedepisodesscan-not-working-when-path-is-supplied/7369/2).

Personally, I don't see the logic behind this, but I'm only concerned with my own use case (which seems to be the same one that led to this issue).

My two cents is, there's no downside that is apparent (to me) to handling the path specified in the API call in the same way as the Drone Factory path.

At the very least, the [API docs](https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan) should explain clearly how the `path` parameter is handled. Currently, it is implied that it will be treated in the same way as the Drone Factory path, which is not the case.

This is confusing.

**Comment by ptowns188** [comment]
@mdhiggins can you please explain to me what you have set in the following

"Download Client"

Completed Download Handling = 
Failed Download Handling = 
Drone Factory Options = 

"Connect"

CustomScript =

please if you could explain

Thanks

**Comment by ptowns188** [comment]
this is my error for just sonarr post processing now, any ideas?

10/06/2015 23:01:33 - Standard - 2015-10-06 19:01:33 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
10/06/2015 23:01:33 - Standard - 2015-10-06 19:01:33 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
10/06/2015 23:01:33 - Standard - 2015-10-06 19:01:33 - readSettings - ERROR - Unable to set tag language, defaulting to English.
10/06/2015 23:01:33 - Standard - Traceback (most recent call last):
10/06/2015 23:01:33 - Standard -   File "/home/<removed>/mp4/readSettings.py", line 367, in __init__
10/06/2015 23:01:33 - Standard -     babel = Language.fromalpha3(self.taglanguage)
10/06/2015 23:01:33 - Standard -   File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 110, in fromcode
10/06/2015 23:01:33 - Standard -     return cls(*language_converters[converter].reverse(code))
10/06/2015 23:01:33 - Standard -   File "/usr/local/lib/python2.7/dist-packages/babelfish/converters/__init__.py", line 253, in __getitem__
10/06/2015 23:01:33 - Standard -     raise KeyError(name)
10/06/2015 23:01:33 - Standard - KeyError: 'alpha3'
10/06/2015 23:01:33 - Error - Traceback (most recent call last):
10/06/2015 23:01:33 - Error -   File "/home/<removed>/mp4/postConversionSonarr.py", line 21, in <module>
10/06/2015 23:01:33 - Error -     tvdb_id = int(os.environ.get('Sonarr_Series_TvdbId'))
10/06/2015 23:01:33 - Error - TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by mdhiggins** [comment]
Try this
```
#!/usr/bin/env python
import os
import sys
import logging
from readSettings import ReadSettings
from autoprocess import plex
from tvdb_mp4 import Tvdb_mp4
from mkvtomp4 import MkvtoMp4
from post_processor import PostProcessor
from logging.config import fileConfig

fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
log = logging.getLogger("SonarrPostConversion")

log.info("Sonarr extra script post processing started.")

settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")

inputfile = os.environ.get('sonarr_episodefile_path')
original = os.environ.get('sonarr_episodefile_scenename')
tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
try:
    episode = int(os.environ.get('sonarr_episodefile_episodenumbers'))
except:
    episode = int(os.environ.get('sonarr_episodefile_episodenumbers').split(",")[0])

converter = MkvtoMp4(settings)

log.debug("Input file: %s." % inputfile)
log.debug("Original name: %s." % original)
log.debug("TVDB ID: %s." % tvdb_id)
log.debug("Season: %s episode: %s." % (season, episode))

if MkvtoMp4(settings).validSource(inputfile):
    log.info("Processing %s." % inputfile)

    output = converter.process(inputfile, original=original)

    # Tag with metadata
    if settings.tagfile:
        log.info("Tagging %s with ID %s season %s episode %s." % (inputfile, tvdb_id, season, episode))
        tagmp4 = Tvdb_mp4(tvdb_id, season, episode, original, language=settings.taglanguage)
        tagmp4.setHD(output['x'], output['y'])
        tagmp4.writeTags(output['output'], settings.artwork, settings.thumbnail)

    #QTFS
    if settings.relocate_moov:
        converter.QTFS(output['output'])

    # Copy to additional locations
    output_files = converter.replicate(output['output'])

    # run any post process scripts
    if settings.postprocess:
        post_processor = PostProcessor(output_files, log)
        post_processor.setTV(tvdb_id, season, episode)
        post_processor.run_scripts()

    plex.refreshPlex(settings, 'show', log)
```

**Comment by ptowns188** [comment]
yes, that last one works, thank you

only issue i got now is that the original download isnt removed from deluge and files are not deleted from where deluge downloads them

is it meant to?

**Comment by mdhiggins** [comment]
Its meant to behave that way, otherwise it would screw up the ability to seed your torrents. I believe however that Sonarr has the option to delete files from Deluge.

**Comment by mdhiggins** [comment]
![capture](https://cloud.githubusercontent.com/assets/3608298/10337400/53b06728-6ccd-11e5-8cf7-3c64b9c60646.PNG)

**Comment by mdhiggins** [comment]
Try my latest update, I think I've fixed the Sonarr issue, seems to be working on my end

**Comment by ptowns188** [comment]
Is this for use with the delugepostprocess.py method and not the sonarr post process?


Sent from my Samsung device

-------- Original message --------

**Comment by mdhiggins** [comment]
Sonarr essentially needs to know when the downloads are finished so it can take the download, move it, and rename it. With the completed download handling turned on, Sonarr automatically communicates with Deluge (or the other downloaders) and notices on its own when the download has finished and starts its process.

The problem with this is that Sonarr notices immediately and grabs the original unprocessed file, which obviously isn't ideal if you want to convert the file to an mp4 before Sonarr does its thing. To get around this the idea is that you disable Completed Download Handling and setup delugePostProcess.py to execute from deluge when the download is done. This script then converts the downloaded file to an mp4, makes a new temp directory, and then sends a special notification to Sonarr informing it to scan the temp directory (instead of the original directory with the mkv), effectively 'tricking' sonarr into thinking the mp4 was the file that was actually downloaded.

The other option is to relinquish your ability to convert BEFORE Sonarr gets the file back from Deluge, let Sonarr take the MKV, rename it, move it, and then run its final post-processing script, and have everything be done (conversion, tagging etc) as the final step after Sonarr is finished. The downside to this is that Sonarr won't know about the fact that you've changed file extensions, and additionally if you have any other programs like Plex that monitor your media library you can run into problems because the MKV has been moved to the final destination and then is converted in place.

Hope that explains it.

**Comment by mdhiggins** [comment]
The problem before was simply that the delugePostProcess notification to Sonarr to start scanning the mp4 for moving/renaming/tagging was broken. I believe I've fixed that with the latest update though so give it a try.

**Comment by ptowns188** [comment]
ok i will try in the next 2 hours and report back

**Comment by ptowns188** [comment]
works perfect now with the delugePostProcess.py now

Thanks

**Comment by mdhiggins** [comment]
Nice! Just pushed an update to the uTorrent script that should address this same issue there. Glad we got it working.

**Comment by adamcadd** [comment]
I'm getting the same issue
2015-10-07 19:25:51 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'x:\Downloads\complete\TV\[show filename]'.
2015-10-07 19:25:52 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): [IP of server x.x.x.x]
2015-10-07 19:25:52 - autoprocess.sonarr - INFO - Sonarr response: queued.

**Comment by mdhiggins** [comment]
That's the normal response.

Make sure you update to have the latest changes, Sonarr should be working.
