### ISSUE TITLE
Change from standard aac to libfdk_aac

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#340]
Hi, can you tell me how to change the script to use libfdk_aac and not the standard aac please

I have compiled ffmpeg with the support included

Thanks

**Comment by mdhiggins** [comment]
Change the `audio-codec` option from `aac` to `libfdk_aac`

If you use the `ios-audio` option you can change it from `True` to `libfdk_aac` as well.
