### ISSUE TITLE
embed .srt subs into an mp4 files

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#341]
not really an issue but i would like to know the following

I have a bunch of mp4 media files with seperate .srt subtitle files, now what i would like to do is run the manual.py over the directory to embed the subs. How to i do this without re-encoding the audio/video?

I have the convert mp4 setting to false but would this just ignore the file and not embed the sub?

Thanks

**Comment by mdhiggins** [comment]
Best option would be to enable `convert-mp4`, turn off `ios-audio` (since this may result in duplicate audio tracks if you're reprocessing files that already have had multiple audio tracks created) and let it run. Assuming your codecs are all included and whitelisted, it will copy all the video/audio streams without re-transcoding so not quality loss should take place, and it will all just be repacked into a new mp4.

**Comment by ptowns188** [comment]
hi, i did as you said but the audio is still converted even though it is aac, anyway to get this to copy both audio/video and embed the subs?

**Comment by mdhiggins** [comment]
Can you post your autoProcess.ini?

**Comment by ptowns188** [comment]
[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key = 

[Sonarr]
host = localhost
port = 8087
web_root =
ssl = 0
apikey = 7

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
output_directory = /home/plex/test1
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
ios-audio = False
ios-first-track-only = False
max-audio-channels =
audio-codec = libfdk_aac
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = eng
download-artwork = True
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 5050
username =
password =
web_root =
ssl = 0
apikey =
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert =
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username =
password =

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Plex]
host = localhost
port = 32400
refresh = True
token =

Any tips?

**Comment by mdhiggins** [comment]
Gotta whitelist aac in your audio codecs to prevent reencoding using libfdk_aac

`audio-codec = libfdk_aac` to `audio-codec = libfdk_aac, aac`

**Comment by ptowns188** [comment]
cool, will give that a try now

Thanks

**Comment by ptowns188** [comment]
should there be a space in libfdk_aac, aac ??

Thanks

**Comment by mdhiggins** [comment]
Doesn't matter

**Comment by ptowns188** [comment]
tried that and still the audio is converted, any other tips?

**Comment by mdhiggins** [comment]
Hm it shouldn't be based on your config options, can you post the log files or at least the manual.py output?

And can you post the ffprobe -show_streams output for the input file in question.

**Comment by ptowns188** [comment]
it was my fault, all working as should

Thanks
