### ISSUE TITLE
post_processor.py AttributeError Fix

### ISSUE THREAD

**Issue by Trixter69** [mdhiggins/sickbeard_mp4_automator#346]
Fixed "AttributeError: PostProcessor instance has no attribute 'post_process_directory'" caused by calling self.post_process_directory instead of self.post_process_environment on line 47 of post_processor.py.

I've fixed this on my fork. this is the commit # 145b634bb1d09a0dc06fe67b9010ed107e0d200e

```python
remove -		self.post_process_directory['MH_IMDBID'] = str(imdbid)
replace+		self.post_process_environment['MH_IMDBID'] = str(imdbid)
```

**Comment by mdhiggins** [comment]
Fixed, thanks
