### ISSUE TITLE
Post process errors out before file is completely converted

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#347]
I am using sickrage to trigger the post process and on some files it errors out before completely converting the file.

2015-10-19 12:46:54 INFO     POSTPROCESSER :: Processing succeeded for /media/tv_complete/Horizon in the Middle of Nowhere - 1x01 - Those Lined Up Before the Horizon.mkv
AA
AAconverter.ffmpeg.FFMpegConvertError: 
AA    total_output, pid=p.pid)
AA  File "/sickbeard_mp4_automator/converter/ffmpeg.py", line 549, in convert
AA    timeout=timeout, preopts=preopts, postopts=postopts):
AA  File "/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
AA    for timecode in conv:
AA  File "/sickbeard_mp4_automator/mkvtomp4.py", line 566, in convert
AA    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
AA  File "/sickbeard_mp4_automator/mkvtomp4.py", line 150, in process
AA    output = converter.process(inputfile, original=original)
AA  File "/sickbeard_mp4_automator/postConversion.py", line 39, in 
AATraceback (most recent call last):
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Starting conversion.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Creating subtitle stream 1 from source stream 4.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Subtitle detected for stream #4: ass [eng].
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 3.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Subtitle detected for stream #3: ass [eng].
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Reading subtitle streams.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 2.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Audio detected for stream #2: ac3 [jpn].
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Reading audio streams.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Video codec detected: h264.
AA2015-10-19 12:46:22 - mkvtomp4 - INFO - Reading video stream.
AA2015-10-19 12:46:22 - SickbeardPostConversion - INFO - Processing /media/anime/Horizon in the Middle of Nowhere/Horizon in the Middle of Nowhere - 1x01 - Those Lined Up Before the Horizon.mkv.
AA2015-10-19 12:46:22 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-10-19 12:46:22 INFO     POSTPROCESSER :: Executing command [u'/usr/bin/python', '/sickbeard_mp4_automator/postConversion.py', u'/media/anime/Horizon in the Middle of Nowhere/Horizon in the Middle of Nowhere - 1x01 - Those Lined Up Before the Horizon.mkv', u'/media/tv_complete/Horizon in the Middle of Nowhere - 1x01 - Those Lined Up Before the Horizon.mkv', '252345', '1', '1', '2011-10-01']

**Comment by rrd911** [comment]
I am able to manually convert with ffmpeg without any errors

**Comment by mdhiggins** [comment]
Does it do this with every file? Or just certain files? and does it have this problem every time with those same files or is it intermittent?

**Comment by rrd911** [comment]
Certain files and every time with those files.

**Comment by mdhiggins** [comment]
What version of FFMPEG are you running?

**Comment by mdhiggins** [comment]
And can you email me a link to one of the files that's giving you trouble?

**Comment by rrd911** [comment]
ffmpeg version N-76045-g97be5d4 
from ffmpeg -version 
XUbuntu 14.04

if that helps.

As for the file in question it was from the following torrent (S01E01 is one of the files)
https://kickass.unblocked.la/horizon-in-the-middle-of-nowhere-1080p-5-1-aac-dual-audio-eng-jap-t8092576.html

**Comment by mdhiggins** [comment]
I'm running N-71028-gaa65ff2 and I'm able to process the file you sent (S01E01) without any problems. I would just try a different build of FFMPEG and see if your problem resolves. Try grabbing some precompiled binaries and using those (especially if you built from source)

**Comment by rrd911** [comment]
interesting. I did not build from source just updated from the available repo

I will try again and see what happens.

**Comment by rrd911** [comment]
I just tried again the fiel again and I received the same error and it stopped converting a 977meg file at 174megs into the conversion. successfully processed 2x01

I am doing this via sickrage post processing.

**Comment by mdhiggins** [comment]
Try one of these binaries:

http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz

http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz

**Comment by mdhiggins** [comment]
Any updates?
