### ISSUE TITLE
[Feature Request] Transmission post process

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#348]
I use transmission because of it's simplicity and ease of setup.
A postprocess script for transmission would be great!

**Comment by mdhiggins** [comment]
Unfortunately transmissions simplicity is its undoing here as it doesn't support enough features to work properly with post processing like deluge or utorrent. I looked into it back when I was writing the torrent scripts.

**Comment by HazCod** [comment]
Oh, alright, Then I will look into uTorrent. thanks!

**Comment by mdhiggins** [comment]
I'd recommend deluge over utorrent
