### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mdhiggins** [mdhiggins/sickbeard_mp4_automator#349]
With the latest set of commits Python3 seems to be working. Getting mutagen working was the biggest challenge. Migrating over most of the dependencies to PIP packages and making them easily updated took a large portion of the effort out of things. 

Python 3 should offer better unicode support, which will be a welcome change.

The goal is to make the script compatible with both Python 2 and 3 simultaneously, and it looks like at this point the majority of features are working under Python 3, at least on my setup. Feel free to drop any new issues or problems here as people begin testing.

**Comment by mdhiggins** [comment]
Known issue: manual.py progress bar doesn't work. Displays a bunch of numbers instead of the ASCII style progress bar.

**Comment by jadik** [comment]
Has the manual.py progress bar bug been addressed?

**Comment by mdhiggins** [comment]
Not yet. Low on my priority list and been busy
