### ISSUE TITLE
Trying to run Manual now presents an error

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#352]
Ok I have not changed anything other than the passage of time but running the Manual.py script no longer works but it did fine before hand.
I have tried a fresh install and download of both python and the script and still I get the same thing each time.

![screenshot 2015-10-24 00 36 57](https://cloud.githubusercontent.com/assets/14253602/10707259/b127a8c2-79e7-11e5-92d5-79085f540bba.png)

**Comment by mdhiggins** [comment]
What version of python are you running?

Also try updating/reinstall the 'requests' module

**Comment by morpheus2n2** [comment]
Yep upgraded Requests (plus all the other dependency's just in case) Running Python 2.7

**Comment by mdhiggins** [comment]
Want you to do 2 steps and let me know if it resolves the issue
Go into the tmdb_api directory in the script directory, and delete the requests folder (C:\Python27\Converter\tmdb_api\requests)

then do `pip install requests[security]`

Then try again

**Comment by morpheus2n2** [comment]
Nope same still it did install quite a few things but alas problem still pops

**Comment by mdhiggins** [comment]
I would just backup your autoProcess.ini file, delete your Converter directory, and reinstall then restore your autoProcess.ini, I think there's a file missing or something. Let me know if that works.

**Comment by morpheus2n2** [comment]
As I mentioned in first post already tried that, what's odd is that Sabnzbd script works wonders but manual just refuse to work any more yet it used to work just fine.

**Comment by mdhiggins** [comment]
It just doesn't make sense cause its complaining about a problem on line 3 of __init__.py in the tmdb_api directory, but that should be a blank empty file. Open up your __init__.py in that folder and see if it has any content cause it should be empty. Something weird is going on.

**Comment by morpheus2n2** [comment]
it has this if i open it via Edit with IDLE 
"from __future__ import absolute_import

from . import ssl_match_hostname"

**Comment by mdhiggins** [comment]
Yeah that's weird and shouldn't be there, it should be an empty file

https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/tmdb_api/__init__.py

**Comment by morpheus2n2** [comment]
fixed it lol :) 
All I get now is a quick error about the subtitle format then it kicks in to life as it should :)

**Comment by mdhiggins** [comment]
Hm no idea how that got there lol, especially if you just did a fresh install. Very strange..
