### ISSUE TITLE
Converted video ends up as a music file in iTunes

### ISSUE THREAD

**Issue by viearical** [mdhiggins/sickbeard_mp4_automator#354]
I've been hitting an issue on a lot of different videos, where the video successfully converts and is moved into the automatically add to iTunes folder I have setup on another volume, but the converted video is seen as a audio file by iTunes.  If I open the converted file with subler and resave it, and import into iTunes again, iTunes properly sees it as video.  I'm guessing that' there's an timing issue where the file is being moved while it's still relocating the MOOV atom to the start of the file.  

```
2015-10-25 22:34:26 - tvdb_mp4 - INFO - Trying to write tags.
2015-10-25 22:34:26 - tvdb_mp4 - INFO - Tags written successfully.
2015-10-25 22:34:26 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2015-10-25 22:34:26 - qtfaststart - INFO - Removing free atom at 32 (8 bytes)
2015-10-25 22:34:26 - qtfaststart - INFO - Patching stco with 61436 entries
2015-10-25 22:34:26 - qtfaststart - INFO - Patching stco with 101199 entries
2015-10-25 22:34:26 - qtfaststart - INFO - Patching stco with 80076 entries
2015-10-25 22:34:26 - qtfaststart - INFO - Writing output...
2015-10-25 22:34:50 - mkvtomp4 - ERROR - First attempt to move the file has failed.
Traceback (most recent call last):
File "/Applications/Alt./sickbeard_mp4_automator/mkvtomp4.py", line 657, in replicate
shutil.move(inputfile, moveto)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
copy2(src, real_dst)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
copystat(src, dst)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 98, in copystat
os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 2] No such file or directory: '/Volumes/Echo/iTunes/Automatically Add to iTunes.localized/TY.mp4'
2015-10-25 22:34:51 - mkvtomp4 - ERROR - Unable to move /Volumes/Courage/Bit/_convert/TY.mp4 to /Volumes/Echo/iTunes/Automatically Add to iTunes.localized
Traceback (most recent call last):
File "/Applications/Alt./sickbeard_mp4_automator/mkvtomp4.py", line 665, in replicate
shutil.move(inputfile.decode(sys.getfilesystemencoding()), moveto)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
copy2(src, real_dst)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
copyfile(src, dst)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Volumes/Courage/Bit/_convert/TY.mp4'
```

**Comment by mdhiggins** [comment]
If you're using the move-to option then that shouldn't be the case. move-to won't be called until the very end when the MOOV atom relocation has been completed. It does however look like something is moving the file before the move-to option has been able to run since you're getting that error as posted above. Any idea what's moving the file early?

Maybe post your autoProcess.ini

Also as an alternative, rather than using the Automatically Add to iTunes folder to import your stuff, consider using the post-process script (since it looks like you're on a mac) that will let the script send stuff to iTunes.

**Comment by viearical** [comment]
Here's a copy of my autoProcess.ini, http://pastebin.com/rEh5cpfA

No idea why it's the file is moving early, it only does it for some conversations, so it's been hard to pin down.  

I'm not familiar with the post-process script (yes, I'm on a mac).  Does that tie into sickbeard or is run as a part of your script?

**Comment by mdhiggins** [comment]
The only thing I can think of is that iTunes is jumping the gun and trying to intercept the file while the move is still in progress. I see you're moving from one volume to another, if those are different physical drives this has been known to happen.

Check out the Post Process section in the readme for more info, but to answer your questions its part of my script. You can add custom scripts that will be executed by my script when all converting and processing is done for additional functionality. One of the samples included is an add to iTunes script for Macs. The readme should get you started, but feel free to let me know if you run into problems.

**Comment by viearical** [comment]
So attempting to use the iTunes.py script in the post_process folder but running into some issues.
1) it appears the add_to_iTunes.scpt applescript was never checked it, I created a pull request for it, https://github.com/mdhiggins/sickbeard_mp4_automator/pull/356

2) the sickrage > sabnzbd > sickbed_mp4 work flow doesn't seem to have worked for actually moving the file.  Looking at the script log in sabnzbd I see the post_processing scripts where run, but I don't see any output and the files where not moved
```
2015-10-27 22:17:49 - SickbeardPostConversion - INFO - Running script '/Applications/Alt./sickbeard_mp4_automator/post_process/iTunes.py'.
2015-10-27 22:17:49 - SickbeardPostConversion - INFO - Running script '/Applications/Alt./sickbeard_mp4_automator/post_process/sample.bat'.
2015-10-27 22:17:49 - SickbeardPostConversion - INFO - Running script '/Applications/Alt./sickbeard_mp4_automator/post_process/sample.py'.
```
3) is running manual.py expected to publish the environment variables need by scripts in post_process folder?  I ran the manual.py script against a file and then running sample.py by hand after fails too find $MH_FILES or any of the other variables

Sorry to keep dragging this along :)

**Comment by mdhiggins** [comment]
1. Merged, not sure why that file wasn't there but its added now
2. The SABNZBD portion of the log shouldn't move any files, moving files via move-to only takes place as the final step in the process, so its executed at the end of postConversion.py's routine.
3. Running sample.py by hand will mean you don't have the environment variables. The post_process environment variables are temporary and only exist when executed by the script for the one time that the script runs.

Looks like you're post-process running 3 scripts, you could probably remove all but the 1 you're interested in. I think you should only need iTunes.py (and the add_to_itunes.scpt file in the resources directory). If you want to see logging for anything that happens after SAB, you need to look at the info.log file.

**Comment by viearical** [comment]
Okay, having a bit of trouble attempting to get the post_processing scripts to run correctly.
1) I found that the iTunes.py script was marked as -rw-r--r, so it was only readable (or writeable by owner), but unable to be executed.  Which I hit when attempting to have the post_processing scripts run, it stated permission denied.  So I added executable bit to all
2. After doing that, the script iTunes.py script was running, but it seems that still isn't moving the file.  I added a debug print to the if statement which checks if there's environment variables (previously would just return), and found that the script isn't reading any environment variables.
```
2015-10-29 21:22:43 - SickbeardPostConversion - INFO - Running script '/Applications/Alt./sickbeard_mp4_automator/post_process/iTunes.py'.
2015-10-29 21:22:43 - SickbeardPostConversion - DEBUG - Stdout: iTunes Notification Script
Did not find environment variables
.
```
The check for environment variables is
```
if not os.environ.get('files'):
    print("Did not find environment variables")
    return
```
This was run as part of the sickrage > sabnbzd work flow, I wasn't running manual conversion.

**Comment by mdhiggins** [comment]
`files` isn't one of the environment variables
From the readme:
```
MH_FILES - JSON Array of all files created by the post processing script. The first file in the array is the primary file, and any additional files are copies created by the copy-to option
MH_TVDBID - TVDB ID if file processed was a TV show and this information is available
MH_SEASON - Season number if file processed was a TV show
MH_EPISODE - Episode number if files processed was a TV show
MH_IMDBID - IMDB ID if file processed was a movie A sample script as well as an OS X 'Add to iTunes' script (iTunes.py) have been provided. Special thanks to jzucker2 for providing much of the initial code for this feature
```

 and I think on OSX all environment vars are lowerecase

**Comment by viearical** [comment]
Yeah, I don't know how the iTunes.py script was working, as it was set to use ```files``` for the environment variable.  I've modified iTunes.py to use the correct environment variable and can check that in, or I don't know if it would be better to have a field in autoProcess.ini for importing to iTunes directly rather then having a post processing script.  I'll leave that choice up to you, and checkin the iTunes.py changes if you decide to keep the iTunes post processing script workflow.

**Comment by viearical** [comment]
Created a pull request for iTunes.py changes, https://github.com/mdhiggins/sickbeard_mp4_automator/pull/358

**Comment by mdhiggins** [comment]
Looks good. Just merged. I assume the script is working well for you and your original issue has been resolved?

**Comment by viearical** [comment]
Yup, sorry for the delay, everything been working well for me, thanks!
