### ISSUE TITLE
How do you pull coverart with Sabpostprocess.py ? 

### ISSUE THREAD

**Issue by ibaniz** [mdhiggins/sickbeard_mp4_automator#355]
I cannot pull artwork when using Sabpostprocess.py . The file in question muxes or converts properly but the artwork is skipped even with "download-artwork = Poster" via autoprocess.ini. If I use  manual.py -i C:\Movies -a  ,Artwork is pulled down and embedded during the conversion without any issues. What am I possibly missing in my autoprocess.ini?

**Comment by mdhiggins** [comment]
SABpostProcess is a dumb post processor only meant to convert and then pass the file back to a media manager; the same as all the other downloader post processors. You need to also use a media organizer with a post processing script to get tagging, so couch potato, sickbeard, sickrage, or sonarr and the respective script that goes along with it. 




SAB and the torrent clients and NZBGet have no actual knowledge of the files they're downloading and therefore can't provide the needed information to tag them without having to guess based on file name.

**Comment by ibaniz** [comment]
Is there any way to use manual.py with the auto argument in conjunction with Sab? I'm already using Sab's sorting renaming option .

**Comment by mdhiggins** [comment]
This could probably be done with a simple batch file to pass the various command line arguments as needed. Gonna be prone to tagging errors though as file name guessing isn't super reliable.

**Comment by mdhiggins** [comment]
Gonna close this since its not actually an issue. If you have questions about how to piece together a batch/script to do what you're looking for feel free to keep posting in this thread.
