### ISSUE TITLE
iOS: Both audio tracks playing at once.  

### ISSUE THREAD

**Issue by totallyGreg** [mdhiggins/sickbeard_mp4_automator#360]
I suspect this is an issue with ffmpeg...
but with both 'iso-audio' and 'iso-first-track-only' set to true, when the script takes an mkv with an ac3 (5.1) stream and creates a stereo mix down AAC track inside a new .m4v container, both audio tracks are 'enabled'.  This results in creepy metallic echo on native OS X playback (iTunes, quicklook, Quicktime) as both sources are played at once. 
Prior to me discovering your excellent script I used Subler to remux and each audio and video track is presented with a checkbox.  When viewing files created by the sickbeard_mp4_automator in Subler I can see that both audio tracks are checked.  Unchecking the surround track and leaving the aac selected and saving the file fixes this issue.  I looked around in ffmpeg but there doesn't appear to be a way to view or set this 'enabled' bit.  
I usually play everything through Plex which does not exhibit this behavior so it's not a big deal but I was wondering if there is a way to adjust this.  Ideally whatever track is marked 'iso-first-track-only' would be enabled by default and the rest would not be.

**Comment by mdhiggins** [comment]
This is an unfortunate limitation of FFMPEG. There's no way to set a track as enabled and others as disabled. Its annoying and the only way around it at this time is to patch FFMPEG. The whole discussion is here:

https://trac.ffmpeg.org/ticket/2626

and here

https://trac.ffmpeg.org/ticket/3622

**Comment by mdhiggins** [comment]
Gonna close this since its primarily an FFMPEG issue

**Comment by drazin** [comment]
i can report that this is echo is happening to me on iOS version of plex.  Looks like FFMPEG has not fixed it.
