### ISSUE TITLE
question: adding unrar support

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#361]
hi, is there any chance you would be able to add unrar support for unix?

i have a source for media but most comes rared so need to auto unpack before script runs

Thanks

**Comment by M4X-StL** [comment]
Use NZBGet.

**Comment by ptowns188** [comment]
I use private torrent source for media
Deluge has an auto unpack plugin but it works on torrent complete same as the script so I believe they interfere with each other 


Sent from my Samsung device

-------- Original message --------

**Comment by mdhiggins** [comment]
Best thing to do would be to just let whatever download manager (CP, SB, Sonarr, SR) handle the unraring, rather than try to reinvent the wheel since all of these programs support it, and just disable converting post-deluge and let it be done right before tagging.

**Comment by mdhiggins** [comment]
I believe Sonarr and CouchPotato both have quality archive management, if you disable the `convert` option with respect to deluge (or whatever downloader) and just let the conversion take place as part of the postCouchPotato.py process you should be good. Gonna close this for now.
