### ISSUE TITLE
More CouchPotato debugging...

### ISSUE THREAD

**Issue by M4X-StL** [mdhiggins/sickbeard_mp4_automator#362]
Michael - after implementing your latest commits, I'm still having trouble with the script in CouchPotato:

11-05 00:02:43 INFO
[ PostProcess] MP4 Automator - Post processing script initialized
11-05 00:02:43 INFO
[ PostProcess] Executing post processing on file /volume1/DiskStation/Movies/Movie.mkv with IMDB ID tt2381249
11-05 00:02:45 INFO
[ PostProcess] 2015-11-05 00:02:44 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized 2015-11-05 00:02:44 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2015-11-05 00:02:44 - readSettings - WARNING - Invalid external subtitle codec mov_text, defaulting to 'srt'. 2015-11-05 00:02:44 - CouchPotatoPostConversion - INFO - Processing file: /volume1/DiskStation/Movies/Movie.mkv 2015-11-05 00:02:44 - CouchPotatoPostConversion - INFO - File is valid 2015-11-05 00:02:44 - mkvtomp4 - INFO - Reading video stream. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Video codec detected: h264. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Pix Fmt: yuv420p. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Reading audio streams. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng]. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio]. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Reading subtitle streams. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [dut]. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Subtitle detected for stream #3: srt [eng]. 2015-11-05 00:02:44 - mkvtomp4 - INFO - Starting conversion. 2015-11-05 00:02:44 - CouchPotatoPostConversion - ERROR - File processing failed: /volume1/DiskStation/Movies/Movie.mkv Traceback (most recent call last): File "/usr/local/couchpotatoserver/scripts/sickbeard_mp4_automator/postCouchPotato.py", line 33, in <module> output = converter.process(inputfile, original=original) File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 149, in process outputfile, inputfile = self.convert(inputfile, options, reportProgress) File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 565, in convert for timecode in conv: File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert timeout=timeout, preopts=preopts, postopts=postopts): File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 473, in convert p = self._spawn(cmds) File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 378, in _spawn close_fds=(os.name != 'nt'), startupinfo=startupinfo) File "/lib/python2.7/subprocess.py", line 710, in __init__ errread, errwrite) File "/lib/python2.7/subprocess.py", line 1335, in _execute_child raise child_exception TypeError: execv() arg 2 must contain only strings
11-05 00:02:45 INFO
[ PostProcess]
11-05 00:02:45 INFO
[ PostProcess] Return code: 0

I'll continue to help as I can!  :+1:

**Comment by mdhiggins** [comment]
Hm something very odd is going on, the commit that I pushed only added a very small amount of debugging to the code, nothing that could have resolved your issue or fixed anything. Quite odd. Can't help but wonder if there's just something weird about your python environment that's causing these problems. 

That being said, there are a couple things we can try with the new error.
I just pushed a new commit that modified `ffmpeg.py` and should run through all the command line parameters and ensure they are strings, which may help prevent the error you're getting, but I can't imagine why you would be getting it in the first place.

I'm actually wondering if for some reason python3 might be getting called for some reason on synology. Is python3 even installed on your box?

**Comment by M4X-StL** [comment]
mdhiggins - I believe I have this sorted.  Attempting to alter code at 1AM after a full day of work is never healthy.  CouchPotato now functioning beautifully w/the latest commit.  I honestly don't know what the problem was - but I went ahead and wiped Python 2.7, CouchPotato, and SickRage and reinstalled anew.  Working flawlessly now - thank you for all your efforts w/this script - it's simply awesome and saves me countless hours.  Kudos.

**Comment by mdhiggins** [comment]
Glad its all working, not quite sure what resulted in the fix but good news either way. Enjoy!
