### ISSUE TITLE
SABnzbd post processing error in processEpisode

### ISSUE THREAD

**Issue by thejacobsons** [mdhiggins/sickbeard_mp4_automator#364]
Greetings!

I keep getting the following error in SABnzbd post process:

autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini for errors, or check install of python modules requests.
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\autoprocess\sonarr.py", line 64, in processEpisode
    log.info("%sSonarr response: %s." % (infoprefix, rstate['state']))
KeyError: 'state'

Sonarr is running.
Python requests modules is installed and current.
autoProcess.ini as follows:

[Sonarr]
host = localhost
port = 8989
web_root =
ssl = 0
apikey = apikey

[MP4]
ffmpeg = C:\sickbeard_mp4_automator-master\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\sickbeard_mp4_automator-master\ffmpeg\bin\ffprobe.exe
output_directory =
copy_to = 
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = ac3,aac
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Thumbnail
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 8981
username = uid
password = pwd
web_root =
ssl = 0
apikey = apikey
delay = 65
method = renamer
delete_failed = 0

[Deluge]
host = localhost
username = uid
convert = True
password = pwd
sonarr-label = tv
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = movies

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = tv
bypass-category = bypass
couchpotato-category = movies
sickbeard-category = sickbeard

[Plex]
host = localhost
port = 32400
refresh = True
token =

**Comment by mdhiggins** [comment]
You'll see that error when the Sonarr settings aren't properly configured. Double check your Sonarr host/port/ssl/apikey and make sure all that information is correct

**Comment by thejacobsons** [comment]
Wow, I somehow had the api COMPLETELY incorrect in autoProcess.ini. Not sure how that happened.

Thank you for the assist!

**Comment by mdhiggins** [comment]
No worries. Lemme know if that resolves your issue.

**Comment by thejacobsons** [comment]
Yes, problem resolved! :)

Thank you again!
