### ISSUE TITLE
manual processing failure with guessit 2.x

### ISSUE THREAD

**Issue by dem0nlord** [mdhiggins/sickbeard_mp4_automator#367]
Manual processing fails on every file with:

An unexpected error occurred, processing of this file has failed
'module' object has no attribute 'guess_file_info'

After fighting with this for a while I figured out this was due to guessit 2.x, may want to update the readme to indicate that guessit should be installed with:

pip install guessit==1.0.2

**Comment by mdhiggins** [comment]
Yeah looks like guessit just recently put out guessit 2 and its a complete rewrite and not backwards compatible at all. Its still in early alpha but I'll keep an eye on it and migrate manual.py over to guessit 2 as things finalize and become more stable.

In the meantime, I updated the readme to reflect that guessit 1 is required.

`pip install guessit<2` should work

Thanks for the heads up
