### ISSUE TITLE
Sonarr and Deluge not removing completed torrents

### ISSUE THREAD

**Issue by icemank121** [mdhiggins/sickbeard_mp4_automator#373]
Since we have to disable Completed Download Handling in Sonarr, and remove completed downloads is disabled aspart of it, Sonarr never removes the torrent from Deluge even after its done seeding. Is there any way around this?

**Comment by mdhiggins** [comment]
Currently the torrents would need to be removed manually. I can look to add some functionality regarding pausing or deleting torrents when complete in the future. Additionally, if you don't mind converting being done as the final step of the process, you can enable completed download handling, and simply don't set up any of the post deluge script executions if you'd rather keep completed download handling.
