### ISSUE TITLE
ImportError: cannot import name Language

### ISSUE THREAD

**Issue by vwbugman69** [mdhiggins/sickbeard_mp4_automator#374]
Just upgraded from old version and switching from Sickbeard to Sonarr.

I keep getting ImportError: cannot import name Language error in SAB.

I thought all the dependencies were installed. Sorry, new to python. Running Arch linux.

**Comment by mdhiggins** [comment]
Looks like you need to install babelfish

**Comment by vwbugman69** [comment]
I did install a babelfish package. How do I verify if babelfish is
installed or is the correct one?

**Comment by mdhiggins** [comment]
You can just rerun the pip install command and see what the output is. 'pip install babelfish'

**Comment by vwbugman69** [comment]
I went and reinstalled babelfish and same error.

On Dec 3, 2015 8:28 AM, "Michael Higgins" <notifications@github.com> wrote:
>
> You can just rerun the pip install command and see what the output is.
'pip install babelfish'
>
> Sent from my iPhone
>
>
> > On Dec 3, 2015, at 08:28, vwbugman69 <notifications@github.com> wrote:
> >
> > I did install a babelfish package. How do I verify if babelfish is
> > installed or is the correct one?
> >
> > On Thu, Dec 3, 2015 at 3:18 AM, Michael Higgins <
notifications@github.com>
> > wrote:
> >
> > > Looks like you need to install babelfish
> > >
> > > Sent from my iPhone
> > >
> > > > On Dec 3, 2015, at 00:09, vwbugman69 <notifications@github.com>
wrote:
> > > >
> > > > Just upgraded from old version and switching from Sickbeard to
Sonarr.
> > > >
> > > > I keep getting ImportError: cannot import name Language error in
SAB.
> > > >
> > > > I thought all the dependencies were installed. Sorry, new to python.
> > > Running Arch linux.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/374#issuecomment-161560086

**Comment by mdhiggins** [comment]
A couple things to do here to try and figure out what's going on. I still think this error is related to babelfish. I would try running manual.py and see if the error is persistent here as well.

One of the reasons that this can be a problem is if you have multiple python instances/environments installed on your machine and the environment that babelfish is installed under is different from the environment that SAB/Sonarr are executing their scripts within. I would look into this and see if that may be part of the problem.

I would take a look at these two posts:
https://stackoverflow.com/questions/25276329/cant-load-python-modules-installed-via-pip-from-site-packages-directory (this one applies to OSX but should still be partially relevant)
https://stackoverflow.com/questions/15052206/python-pip-install-module-is-not-found-how-to-link-python-to-pip-location

**Comment by vwbugman69** [comment]
Looks like it was a permissions issue in /usr/lib/python2.7/site-packages

Changed them and all is good. Thank you for your help.

**Comment by mdhiggins** [comment]
Nice, glad its resolved.
