### ISSUE TITLE
Trying to convert files that are already mp4

### ISSUE THREAD

**Issue by vwbugman69** [mdhiggins/sickbeard_mp4_automator#376]
Even though I have convert-mp4=false in autoProcess.ini, the script is trying to convert mp4 files which cause it to hang.

Any solution to this?

**Comment by mdhiggins** [comment]
Post some log files. It will retag MP4 files but shouldn't invoke FFMPEG.

**Comment by vwbugman69** [comment]
Looks like I found the problem. For some reason, Sonarr had stopped/
shutdown so the script was waiting for Sonarr. Restarted Sonarr and we are
good to go again.
