### ISSUE TITLE
Both audio tracks are enabled

### ISSUE THREAD

**Issue by roidy** [mdhiggins/sickbeard_mp4_automator#377]
When creating an iOS compliant video file with both AAC and AC3 audio tracks mp4_automator sets both tracks as enabled, when the file is then played back on the appleTV both audio tracks playback at the same time, only one of the audio tracks should be enabled.

I have tested this by opening the file created by mp4_automator in Subler and it shows both audio tracks as enabled, if I then disable one of the tracks an re-save the file it plays back fine on the appleTV.

At first I thought this was an appleTV bug so I open an issue with apple and this is the response I got:-

![capture](https://cloud.githubusercontent.com/assets/4118048/11761440/fc2ced56-a0ba-11e5-8e71-b524edd401d9.PNG)

**Comment by mdhiggins** [comment]
This is a bug with FFMPEG, see here:
#223

**Comment by roidy** [comment]
Ok, Thanks I'll give the FFMPEG patch a try.

**Comment by mdhiggins** [comment]
Its a shame they won't just incorporate that patch into the latest version, but yeah the patch seems to be the only viable option right now. Good luck
