### ISSUE TITLE
Deluge not converting non mp4 files

### ISSUE THREAD

**Issue by thejacobsons** [mdhiggins/sickbeard_mp4_automator#378]
After Deluge downloads the file and moves it to the complete folder, the file does not get converted and moved to the final series directory.

![screen shot 2015-12-12 at 12 15 58 pm](https://cloud.githubusercontent.com/assets/8327120/11763070/23067708-a0ca-11e5-8b89-49d4d03fa754.png)

I am running on OS X El Capitan. The deluge script works in command line. I recently switched from uTorrent as recommended but Deluge doesn't seem to be processing the file properly. Has anyone else had this problem?

**Comment by mdhiggins** [comment]
Is there anything in the log files indicating the script is being executed by deluge when the download completes?

**Comment by thejacobsons** [comment]
Oddly, there are no errors or any indication that anything is happening in the deluge log or the mp4_automator log. I know the permissions on the python file are good because I can run it via command line.

**Comment by thejacobsons** [comment]
I've decided to skip Deluge and use the SonarrPostConversion for deluge downloads

**Comment by mdhiggins** [comment]
Yeah it seems like for whatever reason deluge wasn't trying to execute the script. Not sure exactly why that would be but does kinda seem like an issue with deluge more than anything else
