### ISSUE TITLE
CouchPotato post process kinda works but does not complete

### ISSUE THREAD

**Issue by lwittwer** [mdhiggins/sickbeard_mp4_automator#379]
Deluge post processing takes care of the file so the file is converted and it is handed off to CouchPotato according to the logs however, plex is never updated and couchpotato throws errors in its logs. The error is [ PostProcess] Traceback (most recent call last): File "/root/.couchpotato/custom_plugins/PostProcess/main.py", line 40, in callscript process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={}) File "/usr/lib/python2.7/subprocess.py", line 710, in __init__ errread, errwrite) File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory.
Deluge doesn't throw any errors and neither does Sonarr when using Sonarr. Sonarr successfully updates plex as well. The file does end up in the correct folder so I can just run a plex update and it works but it is a weird bug

Edit: Upon further research, it looks like the script does make an mp4 file, but the mkv is what is sent to couch potato anyways

**Comment by mdhiggins** [comment]
Looks like your path to the script folder that needs to be set in main.py isn't correct. I would verify that you changed the path and have restarted couch potato and deleted any .pyc files before doing so.

**Comment by lwittwer** [comment]
I kinda expected that one. For Linux should it be double backslashes still or double front slashes?

**Comment by mdhiggins** [comment]
Linux uses forward slashes

**Comment by lwittwer** [comment]
Makes total sense. Got confused by the documentation and nano's syntax highlighting but I should have realized that. Thanks
