### ISSUE TITLE
Creating iOS Stereo Stream as Second Track

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#381]
Is there any way to make the stereo track created by this script the secondary audio track rather than the first track? It seems to replace the original 5.1 track, which makes it a pain in the ass to switch the audio track back to surround in these new Plex app UIs.

**Comment by mdhiggins** [comment]
At the moment no, this feature does not exist. Perhaps something I can look into in the future. I think there's a way to have Plex default to various channel setups in the setting of multi-audio options, though I think it depends client to client
