### ISSUE TITLE
Second Audio track using wrong bitrate

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#382]
HI, I have it set so that everything gets 2 audio tracks, Track 1 is IOS compatible AAC with a bit rate of 128Kbps.
And tack to is always AC3 with a max of 6 channels where available or 2 channel otherwise, I thought it was also set for 128Kbps but it often comes out much higher, normally if I have a five with say 970Kbps audio then track 2 will be 752Kbps! How can I get it so track 2 is 128Kbps or even 256Kbps?

**Comment by mdhiggins** [comment]
The setting is bitrate per channel, so if your 2nd audio track has 6 channels and your settings are 128kbps, then it will be around 128*6, it needs to scale depending on the number of channels you're pushing.

**Comment by morpheus2n2** [comment]
Ahh lol that will explain it, how would I enter that then so that its different from the first track? currently my autoprocess looks like this:-
audio-codec = aac,ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 128

**Comment by mdhiggins** [comment]
I guess I'm not quite clear on what exactly your desired output would be. If you tell me the tracks on your input file and tell me what you'd like as your output file tracks, I can try and give you the settings you'll need to achieve that.

**Comment by morpheus2n2** [comment]
lol just trying to make the files a little smaller :) its not a big deal just couldn't get my head round it :)
