### ISSUE TITLE
Movie Processing

### ISSUE THREAD

**Issue by traxinv** [mdhiggins/sickbeard_mp4_automator#383]
Keep getting the following error when using uTorrent post processing:

Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
32bit Python.
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Video level 4.1.
Reading audio streams.
Audio detected for stream #1: dca [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: srt [eng].
Creating subtitle stream 0 from source stream 2.
Subtitle detected for stream #3: pgssub [eng].
Subtitle detected for stream #4: pgssub [eng].
Subtitle detected for stream #5: pgssub [fre].
Subtitle detected for stream #6: pgssub [spa].
Subtitle detected for stream #7: pgssub [por].
{
    "subtitle": {
        "0": {
            "map": 2, 
            "codec": "mov_text", 
            "language": "eng"
        }
    }, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 1, 
            "codec": "aac", 
            "bitrate": 256, 
            "language": "eng"
        }, 
        "1": {
            "channels": 6, 
            "map": 1, 
            "codec": "aac", 
            "bitrate": 1536, 
            "language": "eng"
        }
    }, 
    "video": {
        "map": 0, 
        "codec": "h264", 
        "bitrate": 4530.968, 
        "level": 4.0
    }, 
    "format": "mp4"
}
Starting conversion.
[          ] 0%

![untitled](https://cloud.githubusercontent.com/assets/3995322/12007804/ed111d9c-ac1d-11e5-952a-37195855d262.png)

**Comment by traxinv** [comment]
looks like it seems to be happening with certain MKV's.

**Comment by traxinv** [comment]
![capture](https://cloud.githubusercontent.com/assets/3995322/12015018/c9f89002-ad3e-11e5-8384-723d8f06c748.PNG)

found the problem, looks like there is a malformed AAC bitstream, is there a way to add this option: -bsf:a aac_adtstoasc when there is a malformed AAC stream.

**Comment by mdhiggins** [comment]
Hm that's odd I haven't seen that error pop up at all. Are you getting it with multiple MKVs or just one particular one?

That error I believe is the sign of a corrupted or at the very least poorly made source MKV file. the aac_adtstoasc option, while it will possible get rid of the error, will usually leave you with a bad file with missing audio at the end of the video.

**Comment by traxinv** [comment]
@mdhiggins yeah... it is happening here and there i cannot isolate it to a SAB or Torrent problem (i have had the same happen on both SAB and uTorrent), can i send you an example MKV?

**Comment by traxinv** [comment]
Added: Two examples of files with problems. (one movie, one tv series)

[Movie_Example_Torrent.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/73204/Movie_Example_Torrent.txt)
[TV_Example_NZB.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/73205/TV_Example_NZB.txt)

**Comment by traxinv** [comment]
@mdhiggins honestly i think if you could possibly just add a error catch that deletes the dest file if the process fails that would be good enough. (i would do it myself but my python leaves ALLOT to be desired), since at the moment it produces a 0KB MP4 and leaves the MKV, Sickrage then takes the MP4 instead of the MKV and deletes all the remaining files. 

Any help would be greatly appreciated.

**Comment by mdhiggins** [comment]
If you could upload the actual file to the cloud somewhere where I could possibly download it, I would be happy to test it out. Otherwise its gonna be tough to figure out what's going on.

**Comment by mdhiggins** [comment]
Downloaded the file you sent me, adding the aac_adtstoasc option doesn't seem to help or resolve the issue. Not sure why that error is getting thrown I think they're just poorly put together MKVs. I did however improve the error handling as per your request in the latest commit. MP4s that trigger the FFMPEEGConvertError should be deleted now and no further post processing for that entry should take place.

**Comment by traxinv** [comment]
@mdhiggins Thanks man you are a legend. I will update to the latest commit and see what happens.

**Comment by traxinv** [comment]
@mdhiggins so I found a solution, all be it a pretty stupid solution. 

Background: Looks like FFMPEG has some problems with AAC audio encoded with certain programs (like MKVmerge. depending on which library was used.), also there are some Non-Unicode characters in certain subtitle sets that also stuffs-up a few things. 

Solution: Problem 1 - Faulty AAC codec

So to solve the problem I added a flag to the generateOptions procedure: fauconv=False (default). This forces FFMPEG to convert the AAC audio stream (that has the problem) to a AAC audio stream that should now be clean. 

so the audio settings will now look like this:

acodec = 'copy' if a.codec == self.iOS and not fauconv else self.iOS

or

acodec = 'copy' if not fauconv and a.codec.lower() in self.audio_codec else self.audio_codec[0]

Solution: Problem 2 - Weird subtitle problem. 

to be honest, I Don't really care for subtitles. So i just added a flag to  to the generateOptions procedure: stripsubs=False. This will basically just skip over the subtitle part of the code if the flag is true. 

The nice thing here is that you can still use the download subtitle option. So it strips all the subtitles and then downloads a new one (that should work from the internet), also one can do this in couch without embedding it. 

Handle:

Since I was to lazy to edit your code to return a useful error message from FFMPEG and then select the correct option to use from the above. I basically just added a loop to def process. 
if self.needProcessing(inputfile):
            
            force = False
            stripsubs = False

            for attempt in range(4):

                self.log.info(">> Attempt: %s /4 attempts." % attempt)
                self.log.debug(">> Attempt: %s /4 attempts." % attempt)
                
                if attempt == 0:
                    #normal behaviour
                    force = False
                    stripsubs = False
                elif attempt == 1:
                    #Force transcode audio, fix problem for poorly encoded MKV's
                    force = True
                    stripsubs = False
                elif attempt == 2:
                    #Strip Subtitles for subtitle files that contain non ASCII characters (Poorly Encoded MKV's)
                    force = False
                    stripsubs = True
                else:
                    #Try both?
                    force = True
                    stripsubs = True

                self.log.debug("Force audio conversion: %s." % force)
                self.log.debug("Force strip subtitles: %s." % stripsubs)
                
                if reportProgress:
                    self.log.info(">> Force audio conversion: %s." % force)
                    self.log.info(">> Force strip subtitles: %s." % stripsubs)
                    
                options = self.generateOptions(inputfile, original=original,fauconv=force,stripsubs=stripsubs)
                
                try:
                    if reportProgress:
                        self.log.info(json.dumps(options, sort_keys=False, indent=4))
                    else:
                        self.log.debug(json.dumps(options, sort_keys=False, indent=4))
                except:
                    self.log.exception("Unable to log options.")

                outputfile, inputfile = self.convert(inputfile, options, reportProgress)

                if not outputfile:
                    self.log.info(">> Error converting, retry with additional options...")
                else:
                    break
                
            else:
                if not outputfile:
                    self.log.debug("Error converting, no outputfile present.")
                    return False

                self.log.debug("%s created from %s successfully." % (outputfile, inputfile))
                self.log.info("%s created from %s successfully." % (outputfile, inputfile))

**Comment by mdhiggins** [comment]
Were you able to try the recent update to see if this issue is resolved?

**Comment by traxinv** [comment]
So the update resolved one part of the problem. The other part is that the subtitle files are still sometimes encoded pretty strangely. 

Added is my modified version of mkvtomp4.py.

[mkvtomp4.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/97053/mkvtomp4.txt)

**Comment by mdhiggins** [comment]
Gonna close this for now since I think its been resolved at this point
