### ISSUE TITLE
FFMpeg error?

### ISSUE THREAD

**Issue by LandMineHare** [mdhiggins/sickbeard_mp4_automator#387]
Trying to run manual.py, I keep getting unexplained errors. I've updated the script, ffmpeg, everything that needs to be installed according to the instructions, still get an undescribed error 1. Even went through and threw UTF-8s all over the place, still can't figure out what is wrong.

Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/scripts/mkvtomp4.py", line 570, in convert
    for timecode in conv:
  File "/scripts/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/scripts/converter/ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=45761, cmd="/usr/local/bin/ffmpeg -fix_sub_duration -i /Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mkv -vcodec copy -map 0:0 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=und -f mp4 -threads auto -y /Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mp4">

**Comment by LandMineHare** [comment]
SABnzbd seems to have no problems when it runs the script, just when manual.py is run.

**Comment by traxinv** [comment]
@LandMineHare Hey man. Did you get this error with manual.py on the same file or a different file? There is some strangeness with FFMPEG, i wrote a workaround for myself. I posted it here (check the attachment of the last comment):

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/383

See if it solves the problem or not and which mode it used: there should be a >> somewhere in messages.

**Comment by LandMineHare** [comment]
Any file it is run on it in that folder, I haven't had the chance to check more as I had to run off to work, but I'll give your work around a shot later.

**Comment by mdhiggins** [comment]
I feel like the error you posted is cut off and doesn't have the most important output part at the end. Additionally it should give you a long FFMPEG command with all the options when you get an FFMPEG convert error, please run FFMPEG with that command and post the output as well.

**Comment by LandMineHare** [comment]
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=38970, cmd="/usr/local/bin/ffmpeg -fix_sub_duration -i /Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mkv -vcodec copy -map 0:0 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=und -f mp4 -threads auto -y /Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mp4">

**Comment by mdhiggins** [comment]
If you take that long command it spit out and try and run that in command prompt FFMPEG should give you a more detailed error. Do that and send me the full output FFMPEG gives you and we can debug from there

**Comment by LandMineHare** [comment]
This is the first spot where it looks like things go wrong. Then to the end.

[mp4 @ 0x808c51a20] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x808c51a20] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to '/Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 16k tbn, 1k tbc (default)
    Stream #0:1(und): Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x808c51a20] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
[mp4 @ 0x808c51a20] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
frame=    2 fps=0.0 q=-1.0 Lsize=       5kB time=00:00:00.04 bitrate= 843.2kbits/s    
video:4kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 17.329819%
Conversion failed!

**Comment by traxinv** [comment]
@landminehare so you also have the same problem as me. There seems to be something wrong with the encoding options of certain AAC coding libraries. 

So i solved it (in that script i posted earlier), to force transcode the Aac audio stream again (even if it is already a AAC audio stream). 

@mdhiggins did you have any luck figuring out this problem?

**Comment by mdhiggins** [comment]
Think I have it all solved. Added some logic to the script to apply the arc_adtstoasc filter on a track by track basis. Now when an AAC source track is encountered and will be copied, that filter is applied only to that specific track. Testing on your source file you sent me seems to be working. This seems way more desirable because we no longer need to force transcoding and it can all be done in one pass. Just needed to sit down and add support to the FFMPEG converter backend so the command could be passed.

Update and let me know if the issue is resolved.

**Comment by LandMineHare** [comment]
I still get that error. FFMPEG still says the same thing. Reinstalled ffmpeg, not sure what else to do. 

Also, is there a better way to update other than redownloading the zip and overwriting everything and resetting it all up?
[mp4 @ 0x808c51a20] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x808c51a20] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to '/Data/Videos/TV Shows/Whose Line Is It Anyway/Season 11/Whose Line Is It Anyway! - s11e13 - Gina Rodriguez.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 16k tbn, 1k tbc (default)
    Stream #0:1(und): Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x808c51a20] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
[mp4 @ 0x808c51a20] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
frame=    2 fps=0.0 q=-1.0 Lsize=       5kB time=00:00:00.04 bitrate= 843.2kbits/s    
video:4kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 17.329819%
Conversion failed!

**Comment by mdhiggins** [comment]
Can you upload the offending file somewhere and email me the link?

**Comment by traxinv** [comment]
So i have not had any problems since updating. sorry should have replied earlier but i wanted to let it run for a few days and test. 

One problem i do have it that it does not UnRAR or Unzip files. I will open a separate ticket.

**Comment by LandMineHare** [comment]
And I haven’t been able to get a personal/private email to MDH about where I could/should upload the offending file. Still working on figuring that part out.
