### ISSUE TITLE
WebVTT not working

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#389]
I get this error when trying to use webvtt subtitle format. Is this an ffmpeg issue perhaps? I am using the 2015-12-31 64-bit Windows build from http://ffmpeg.zeranoe.com/builds/

Invalid interal subtitle codec webvtt, defaulting to 'mov_text'.

**Comment by mdhiggins** [comment]
WebVTT is only valid as an external subtitle file at this point (FFMPEG limitation). Can't be embedded in the mp4 wrapper. You'll need to disable 'embed-subs' if you want to use that format.
