### ISSUE TITLE
Video bitrate question

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#390]
I know that the script will convert a file and bring its bitrate down to the desired on if its higher but is there a way or could it be added that it brings the bitrate up? 
The main reason for asking is I am converting a handfull of files that are h265 to h264 for compatibility reasons but due to the way h265 works it has far better quality while using much lower bitrates, noy if I convert it currently it will keep the bitrate from the h265 but loose so much quality its insane, but if I take the same file and run it through handbrake and bring it BR up to my default for my settings I loose no quality at all.

**Comment by mdhiggins** [comment]
Just pushed an update the should allow you to get the behavior you want. The `video-bitrate` option can now be used to assign your desired video-bitrate when re-encoding

**Comment by morpheus2n2** [comment]
Awesome, do I need to change anything in the autoprocess file or just download update and away we go?

**Comment by mdhiggins** [comment]
You'll need to set the `video-bitrate` option to use the new feature.

Essentially the behavior will works as follows:
```
same codec and video-bitrate is higher than your source video's bitrate > copy/remux, no transcoding
same codec and video-bitrate is lower than your source video's bitrate > transcode to lower bitrate, same codec
different codec and video-bitrate is set > will transcode using your specified bitrate to new codec
different codec and video-bitrate not set > will transcode attempting to match the source bitrate despite different codec
