### ISSUE TITLE
How to speed up the process

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#391]
This is a great tool but the remuxing takes a lot longer than it should. Is there a way for me to speed up the process? ffmpeg uses just 25% and the only thing being converted is the audio to aac. Thanks

**Comment by morpheus2n2** [comment]
Sounds like ffmpeg is set belownormal for CPU priority, or there's something else taking up the CPU

**Comment by Deihmos** [comment]
There is nothing to configure for ffmpeg and there is nothing using the cpu. I read a comment from the developer and he said that's how it is and he cannot increase the speed.

**Comment by morpheus2n2** [comment]
Odd cos when mine runs it uses upto the full 100% of the CPU and the average 1.2GB MKV will take just 25mins.
Whats your system spec?

**Comment by Deihmos** [comment]
You must have a very weak CPU that's why. I am not doing any transcoding just remuxing and nothing takes close to 25 minutes. It takes about 3 minutes but if it ran full speed it should be done in less than a minute like it does using other programs.This is much better though because it is automated. I am using a haswell i3 desktop processor.

**Comment by Deihmos** [comment]
I just discovered that it runs full speed when using the auto processing scripts. The manual processing does not run full speed.

**Comment by morpheus2n2** [comment]
Na my CPU is fine, I do full conversions not a quick and simple remux lo, glad to hear you sorted it with the automated process seems a bit odd that manual is slower as I fine it performs the same as the auto process on my system.

**Comment by Deihmos** [comment]
I was wrong. The video was transcoding because it was some kind of xvid. Have not seen that in years.

**Comment by Deihmos** [comment]
Where can I input the command for ffmpeg
-threads 4

**Comment by mdhiggins** [comment]
The script currently uses -threads auto, if you want to manually override that its like 579 in mkvtomp4.py just change auto to 4.

It probably won't make a difference as FFMPEG isn't optimized for multicore systems very well (depends on the codec/encoder etc). 

If you're having slow remuxing then its probably related to hard drive read/write speeds and buffers more than anything else.

**Comment by Deihmos** [comment]
It is not very slow but slow compared to other programs. I will change it to 4 and see the results.
