### ISSUE TITLE
WindowsError: [Error 5] Access is denied -- manual.py

### ISSUE THREAD

**Issue by zaylman** [mdhiggins/sickbeard_mp4_automator#393]
Keep getting the same error, I've tried giving lots of things access including running the powershell as admin. any help would be greatly appreciated. I've attached a png of the powershell window
![administrator_ windows powershell 2016-01-02 12 54 44](https://cloud.githubusercontent.com/assets/16520427/12076073/2e984772-b150-11e5-8c92-d8624609c4fc.png)

**Comment by morpheus2n2** [comment]
Have you installed all the pre-requirements for python first?

- `VC for Python 2.7` (Windows Users Only) - Download and install - http://www.microsoft.com/en-us/download/details.aspx?id=44266
- `setup_tools` - https://pypi.python.org/pypi/setuptools#installation-instructions
- `requests` - Run `pip install requests`
- `requests security package` - Run `pip install requests[security]`
- `requests-cache` - Run `pip install requests-cache`
- `babelfish` - Run `pip install babelfish`
- `guessit` - Run `pip install guessit<2` to use manual.py (requires guessit version 1, version 2 is a complete rewrite, still in alpha, and not backwards compatible)
- `subliminal`- Run `pip install subliminal` to enable automatically downloading subtitles
- `stevedore` - Run `pip install stevedore` (this will be automatically installed with subliminal)
- `dateutil` - Run `pip install python-dateutil` (this will be automatically installed with subliminal)
- `deluge-client` Run `pip install deluge-client` if you plan on using Deluge
- `qtfaststart` Run `pip install qtfaststart` to enable moving moov atom

Also you should be able to just run manual just by clicking the .py from your install folder.

**Comment by zaylman** [comment]
Hi, Thank you for the response. Yes I have already install the pre requirements. But just incase I ran the commands to add them again they all returned "already satisfied"
![administrator_ windows powershell 2016-01-02 12 54 44](https://cloud.githubusercontent.com/assets/16520427/12076648/c9c749f6-b168-11e5-9043-7ac4cd25f09c.png)

**Comment by zaylman** [comment]
The problem was I didn't have the full path to ffmpeg.exe and ffmprobe.exe I have corrected this in the autoProcess.ini file and now manual.py works as expected
