### ISSUE TITLE
Cannot lower audio bitrate

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#394]
I set the audio bitrate to 160 but it still does 256. A lot of the videos are not playing on ios or even in itunes and I cannot figure out why. They play fine in other players but fail to play even on Plex in ios. There is something wrong.

**Comment by Deihmos** [comment]
Turns out some of the videos are not playing in itunes and iphone due to tagging . If I disable tagging it plays fine but with tagging it fails to play.

**Comment by mdhiggins** [comment]
Can you send me an example file that won't play back in iTunes? Tagging shouldn't cause issue

**Comment by mdhiggins** [comment]
And audio bitrate is set on a per channel basis, and if you're using the iOS-audio option that is hard-set to 128kbps per channel, which may be why its not behaving.

**Comment by Deihmos** [comment]
Ok I thought this was the reason some of the videos failed in itunes and iphone but it was the tagging.

**Comment by mdhiggins** [comment]
I still would like to see if I can recreate the iTunes issue, if you could upload and email me one of the trouble files (original file ideally, before conversion) that would be greatly appreciated
