### ISSUE TITLE
Nothing has changed but suddenly getting error message

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#395]
Nothing has changed at all its been working perfect right up to thismorning now i get 
2016-01-03 12:17:50 - MANUAL - ERROR - Unabled to create external subtitle file for stream 3.
Traceback (most recent call last):
  File "C:\Converter\mkvtomp4.py", line 435, in generateOptions
    for timecode in conv:
  File "C:\Converter\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\Converter\converter\ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=4112, cmd="C:\ffmpeg\bin\ffmpeg.exe -i a:/new folder\01 He Ain't a Hottie, He's My Brother.mp4 -an -sub_charenc UTF-8 -c:s:0 srt -map 0:3 -metadata:s:s:0 language=eng -f srt -y a:\new folder\01 He Ain't a Hottie, He's My Brother.eng.srt">
2016-01-03 12:17:50 - MANUAL - INFO -

**Comment by lbinderup** [comment]
Am seeing the exact same error - running the script in OSX, with self-built ffmpeg including everything but the kitchen sink.

**Comment by lbinderup** [comment]
Processing file input.mkv
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: srt [eng].
Ripping eng subtitle from source stream 2 into external file.
Unabled to create external subtitle file for stream 2.
Traceback (most recent call last):
  File "/Users/lb/Applications/github/sickbeard_mp4_automator/mkvtomp4.py", line 435, in generateOptions
    for timecode in conv:
  File "/Users/lb/Applications/github/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/Users/lb/Applications/github/sickbeard_mp4_automator/converter/ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=2223, cmd="/usr/local/Cellar/ffmpeg/2.8.4/bin/ffmpeg -i ./input.mkv -an -sub_charenc UTF-8 -c:s:0 srt -map 0:2 -metadata:s:s:0 language=eng -f srt -y /input.eng.srt">

**Comment by mdhiggins** [comment]
Does the above error output a full FFMPEG command? and if so can you run it and tell me what error FFMPEG is throwing that's causing this to fail?

**Comment by morpheus2n2** [comment]
I have fixed it now, I reinstalled python and all the pre-requirements and now seems to work with out problem so not sure what coursed it.

**Comment by mdhiggins** [comment]
Hm strange, but glad to hear its working.

Reopen if the issue crops up again

**Comment by lbinderup** [comment]
Just in case, this is the error I get when entering the ffmpeg command manually:

Mac-mini:Season 10 laurids$ /usr/local/Cellar/ffmpeg/2.8.4/bin/ffmpeg -i "./S10E04 - Banana Planet.mkv" -an -sub_charenc UTF-8 -c:s:0 srt -map 0:2 -metadata:s:s:0 language=eng -f srt -y "/Storageframe/Video/Add to Library/Processing/S10E04 - Banana Planet.eng.srt"
ffmpeg version 2.8.4 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libass --enable-ffplay --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-libopus --enable-frei0r --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/1.5.2_1/include/openjpeg-1.5 --enable-nonfree --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from './S10E04 - Banana Planet.mkv':
  Metadata:
    encoder         : libebml v1.3.0 + libmatroska v1.4.0
    creation_time   : 2013-09-09 10:32:53
  Duration: 00:11:20.96, start: 0.000000, bitrate: 3667 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: subrip (default)
Codec AVOption sub_charenc (set input text subtitles character encoding) specified for output file #0 (/Storageframe/Video/Add to Library/Processing/S10E04 - Banana Planet.eng.srt) is not an encoding option.

**Comment by lbinderup** [comment]
And to follow up - removing "-sub_charenc UTF-8" made it work as intended.

**Comment by mdhiggins** [comment]
Just pushed and update that should prevent the sub_charenc option from being passed when attempting to make an external .SRT file
