### ISSUE TITLE
Have script trigger Sonarr to rescan and rename after post processing

### ISSUE THREAD

**Issue by Smithoo4** [mdhiggins/sickbeard_mp4_automator#396]
As a possible enhancement to Sonarr post processing it would be nice to have the script trigger Sonarr to rescan and even rename after transcoding and tagging are done but before sending a notification PLEX to update. The rescan would be so that Sonarr has the updated info on the file and the rename would be to get rid of the (2) which can get added if the original files was already and mp4. I did some looking on Sonarr's wiki and it looks they have an API to do so. Or at least based on my understanding of things it looks like they do; please see the links below. Also, I may have no idea what I am talking as I could just be an idiot that google a few things. 

https://github.com/Sonarr/Sonarr/wiki/API

https://github.com/Sonarr/Sonarr/wiki/Command

I guess a similar feature for Sickbeard/Sickrage and CouchPotato would be nice too.

Cheers

**Comment by mdhiggins** [comment]
The (2) issue should now be resolved

**Comment by mdhiggins** [comment]
Should hopefully not need to add this extra logic at this point, reopen this if there's further problems or you think this feature would still be beneficial

**Comment by Smithoo4** [comment]
Great, Thank you
