### ISSUE TITLE
Sonarr Post Processing not working

### ISSUE THREAD

**Issue by ZeroManArmy** [mdhiggins/sickbeard_mp4_automator#397]
Sonarr downloads the files just fine and using manual.py works great. 

The pre-move location they are in is "M:\Downloads\Complete\sonarr\"

autoProcess.ini settings for Sonarr look like this. 
![autoprocess ini](https://cloud.githubusercontent.com/assets/1351509/12215336/7c28d95a-b675-11e5-9a2c-69fefa4bb913.png)

I have disabled "Completed Download Handling" and set the "Drone Factory Options" to 0

I have set Connections to Custom Script and the settings look like this. 
![sonarr_connection_settings](https://cloud.githubusercontent.com/assets/1351509/12215340/a23da080-b675-11e5-8c59-ef0653c623c8.PNG)
The Argument is set to this: C:\Users\Host\Desktop\sickbeard_mp4_automator-master\postSonarr.py

I have downloaded multiple episodes with Sonarr, Sonarr is not processing the files, and neither is the script. 

Any help?

**Comment by Deihmos** [comment]
This works fine for me. Make sure you have the same category in sonarr and sabnzbd. The category is listed in the download client in sonarr.

**Comment by mdhiggins** [comment]
Gonna have to clarify exactly which part isn't working for further help.

Everything looks like its set up appropriately as far as sonar is concerned. Is Sonarr not renaming the files and moving them either? If that's the case its an issue with Sonarr not having the file passed back appropriately from the downloader

What downloading client are you using?

**Comment by ZeroManArmy** [comment]
Apologies, I was falling asleep at 0100 writing this out.

I'm using SABnzbd and Deluge for a torrent backup. 

When the download completes in SABnzdb nothing happens. I don't see any temp files being created for the conversion. 

The only thing I think I may be missing, does the name of the Custom Script have to match the label that is being applied to the downloads?

**Comment by mdhiggins** [comment]
That's normal, its not supposed to remove the SAB history
