### ISSUE TITLE
NZBGet Post processing with sickbeard_mp4_automator not working

### ISSUE THREAD

**Issue by fmanji** [mdhiggins/sickbeard_mp4_automator#398]
I've attached the log info from NZBGet for NZBGetPostProcess.py

I'm guessing it's something simple like I don't have the path name syntax correct, I've configured it in ffmpeg.py as:
def **init**(self, ffmpeg_path=C:\Program Files\FFMPEG\ffmpeg\bin, ffprobe_path=C:\Program Files\FFMPEG\ffmpeg\bin):

I've also tried to set it to None and place ffmpeg and ffprobe in the same directory, but at the end of the day the mkv doesn't convert to mp4, when it do it via manual.py it works though

ERROR   Sat Jan 09 2016 19:52:11    Post-process-script NZBGetPostProcess.py for Blackish.S01E10.720p.WEB-DL.DD5.1.H.264-NTb failed (terminated with unknown status)
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: SyntaxError: invalid syntax
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: ^
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: def **init**(self, ffmpeg_path=C:\Program Files\FFMPEG\ffmpeg\bin, ffprobe_path=C:\Program Files\FFMPEG\ffmpeg\bin):
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/converter\ffmpeg.py", line 332
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: from converter.ffmpeg import FFMpeg, FFMpegError, FFMpegConvertError
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/converter__init__.py", line 7, in <module>
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: from converter import Converter, FFMpegConvertError
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/mkvtomp4.py", line 8, in <module>
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: from mkvtomp4 import MkvtoMp4
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: File "C:\ProgramData\NZBGet\scripts\NZBGetPostProcess.py", line 55, in <module>
INFO    Sat Jan 09 2016 19:52:11    NZBGetPostProcess: Traceback (most recent call last):
INFO    Sat Jan 09 2016 19:52:11    Executing post-process-script NZBGetPostProcess.py for Blackish.S01E10.720p.WEB-DL.DD5.1.H.264-NTb

**Comment by mdhiggins** [comment]
Needs to be full path to the executable including the name of the executable (ffmpeg.exe)

**Comment by fmanji** [comment]
I did that as well, same result, could I still have the wrong syntax somewhere?  Do I need to use quotes or double backslashes or something else?

Sun Jan 10 2016 15:36:19	Post-process-script NZBGetPostProcess.py for Blackish.S01E10.HDTV.x264-LOL failed (terminated with unknown status)
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: SyntaxError: invalid syntax
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: ^
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: def __init__(self, ffmpeg_path=C:\Program Files\FFMPEG\ffmpeg\bin\ffmpeg.exe, ffprobe_path=C:\Program Files\FFMPEG\ffmpeg\bin\ffprobe.exe):
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/converter\ffmpeg.py", line 332
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: from converter.ffmpeg import FFMpeg, FFMpegError, FFMpegConvertError
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/converter\__init__.py", line 7, in <module>
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: from converter import Converter, FFMpegConvertError
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: File "C:/Python27/sickbeard_mp4_automator-master/mkvtomp4.py", line 8, in <module>
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: from mkvtomp4 import MkvtoMp4
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: File "C:\ProgramData\NZBGet\scripts\NZBGetPostProcess.py", line 55, in <module>
INFO	Sun Jan 10 2016 15:36:19	NZBGetPostProcess: Traceback (most recent call last):
INFO	Sun Jan 10 2016 15:36:19	Executing post-process-script NZBGetPostProcess.py for Blackish.S01E10.HDTV.x264-LOL

**Comment by mdhiggins** [comment]
Did you modify the python file with these paths directly or just add them to the autoProcess.ini file?

**Comment by fmanji** [comment]
I added the full directory path, without quotes to the MP4 section of autoprocess.ini, it seems to work now.

**Comment by thecorax** [comment]
Hi, i have the same problem with Linux debian. i installed ffmpeg via apt-get install. it is in the /usr/bin directory. what do i have to enter in the config file?
