### ISSUE TITLE
Request: Ability to strip metadata (and more) on convert

### ISSUE THREAD

**Issue by lbinderup** [mdhiggins/sickbeard_mp4_automator#399]
I've opted not to use the tagging functionality, since I let Plex handle that. However, being the neat-freak I am, it would be nice to have an option that basically strips the converted output of all extra information.

Right now the script does subtitle stripping nicely, but it leaves chapter markers intact (actually, it dumps those to a .srt file, but also leaves them behind in the converted file). I'd really like an option to just get rid of everything that isn't an audio or video track. Coupled with an option to clear any meta-data, it would be perfect.

**Comment by morpheus2n2** [comment]
Yeah this would be really handy if its possible, I fined more and more files are being tagged with rubbish at source, having the metadata stripped or just not copied over when converting would be really useful :)

**Comment by lbinderup** [comment]
This can be easily achieved from ffmpeg command line using -map_metadata -1 -map_chapters -1 

I'm just missing a command line in the python script to toggle passing those on.

**Comment by morpheus2n2** [comment]
Has ther ebeen any news on adding this as I am finding I have to remove more and more metadata each day as different groups keep adding crap to there files, this makes plex unhappy :(

**Comment by mdhiggins** [comment]
Just pushed an update that attempts to invoke the delete() method built in to mutagen (the library the script uses to tag files) before new tags are written. This should clear any existing metadata. I didn't have any files to test it on so let me know if it works. The metadata wipe occurs just before the new tags are written so make sure you actually do tag the file using the script or you won't see any results.

**Comment by morpheus2n2** [comment]
Cool :)

**Comment by morpheus2n2** [comment]
Not been able to use this feature as I don't tag my files at all :(

**Comment by niallobr** [comment]
As far as I can tell metadata is not being removed right now. Any release from the EVO group for example will still have embedded title metadata with the group name after conversion. Is there anything special I need to do?

Info -> Title = EVO
Sorting -> Title = EVO

I've tested this with a few files, I can send on the conversion log for the latest if it helps? It would be great to get this data scrubbed automatically.

**Comment by mdhiggins** [comment]
You can strip all metadata using FFMPEG by adding options to the postopts section of autoprocess.ini

See here for the commands

http://superuser.com/questions/441361/strip-metadata-from-all-formats-with-ffmpeg

**Comment by niallobr** [comment]
Awesome! Thanks for that link, it's working perfectly now.

**Comment by morpheus2n2** [comment]
Can I ask how you added this?

**Comment by niallobr** [comment]
Sure! Here's exactly what I added:

`postopts = -map_metadata, -1`

**Comment by morpheus2n2** [comment]
Cool, and the removes the metadata?

**Comment by niallobr** [comment]
Sorry just seeing this now. Yeah it removes metadata and leaves chapters intact.

**Comment by morpheus2n2** [comment]
I have tried this on two different machines running the script and it seems all metadata stays intact, it's not removing it :(

**Comment by mdhiggins** [comment]
I would check what build of FFMPEG you're using cause this should work fine. I would also manually test those commands on a sample file with FFMPEG outside the script and see if that seems to remove metadata to determine if it's an FFMPEG problem or a script problem

**Comment by niallobr** [comment]
I'm using FFMPEG 3.2.4 (static) which is fairly recent – grab the latest [here](https://www.johnvansickle.com/ffmpeg/) and give it a try.

**Comment by morpheus2n2** [comment]
Yep thats the one I have, Metadata does not get stripped :(

**Comment by mdhiggins** [comment]
I would read over that SO post I listed as there were alternative commands that can be sent to remove metadata and remove chapters that you could try. You have direct access to the FFMPEG command line now so you can try any of these.
