### ISSUE TITLE
Install.sh script for OSX

### ISSUE THREAD

**Issue by andrewoke** [mdhiggins/sickbeard_mp4_automator#400]
Because I just had a power supply meltdown and am looking at automation a bunch more I wrote a little script which installs the dependencies on OS X. Feedback/suggestions welcome.

	#!/bin/sh

	if [ ! `which ffmpeg` ] ; then
		brew install ffmpeg	
	fi

	if [ ! `which pip` ] ; then
		curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo python
	fi

	LIST=`pip list`

	if ! grep -q "requests" <<< "$LIST"; then
		sudo pip install requests
	fi

	if ! grep -q "requests-cache" <<< "$LIST"; then
		sudo pip install requests-cache
	fi

	if ! grep -q "babelfish" <<< "$LIST"; then
		sudo pip install babelfish
	fi

	if ! grep -q "guessit" <<< "$LIST"; then
		sudo pip install guessit<2
	fi

	if ! grep -q "subliminal" <<< "$LIST"; then
		sudo pip install subliminal
	fi

	if ! grep -q "stevedore" <<< "$LIST"; then
		sudo pip install dateutil
	fi
	if ! grep -q "qtfaststart" <<< "$LIST"; then
		sudo pip install qtfaststart
	fi

**Comment by mdhiggins** [comment]
Could probably just post this on the wiki
