### ISSUE TITLE
Failed to Delete (ReTry)

### ISSUE THREAD

**Issue by traxinv** [mdhiggins/sickbeard_mp4_automator#402]
Would it be possible to add an option to retry the delete if it fails the first time (in general all the file system operations maybe need a retry option).

What is happening at the moment the QTFS files are left behind allot after most of the Sickrage post processing then I need to go and delete them manually. 

My suggestion would be: Try Delete (or rename) -> Failed -> Wait 30 seconds -> Try again. For as many times as a user can specify in the config.

**Comment by mdhiggins** [comment]
It already does this, just not user configurable. 

See the removeFile method in the mkvtomp4 class

**Comment by traxinv** [comment]
Ok thats awesome. Will check it out now.

**Comment by traxinv** [comment]
Thanks for the heads up on the code. It works perfectly deleting the file. But the replace feature does not have retry. So I am stuck with a a bunch of QRTS files. Anyway. I modded the code as follows:

def removeFile(self, filename, retries=10, delay=30, replacement=None):
        for i in range(retries + 1):
            try:
                # Make sure file isn't read-only
                os.chmod(filename, int("0777", 8))
            except:
                self.log.debug("Unable to set file permissions before deletion. This is not always required.")
            try:
                os.remove(filename)
                # Replaces the newly deleted file with another by renaming (replacing an original with a newly created file)
                if replacement is not None:
                    for i in range(retries + 1):
                        try:
                            os.rename(replacement, filename)
                            filename = replacement
                        except:
                            self.log.exception("Unable to rename file.")
                            if delay > 0:
                                self.log.debug("Delaying for %s seconds before retrying." % delay)
                                time.sleep(delay)
                break
            except OSError:
                self.log.exception("Unable to remove file %s." % filename)
                if delay > 0:
                    self.log.debug("Delaying for %s seconds before retrying." % delay)
                    time.sleep(delay)
        return False if os.path.isfile(filename) else True

**Comment by mdhiggins** [comment]
Curious, do you use plex to monitor your media library and if so, do you have the automatic library scanning enabled?

**Comment by traxinv** [comment]
Its a bit complicated. Since I use BTSync to offload the media from a VPS to home server. So i assume that is what is causing the problem.

**Comment by traxinv** [comment]
you can close this one. Adding the retries has worked. Dont know if you want to add it to the main code?

**Comment by mdhiggins** [comment]
Gonna add it to the main code when I get a chance

**Comment by mdhiggins** [comment]
Changed your code around a little, since you were doing a loop within a loop, meaning for 3 retries you would could end up with 9 possible attempts severely slowing things down

Just made it all part of the main retry thread loop.
