### ISSUE TITLE
 qtfaststart - WARNING - Could not copy file permissions!

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#403]
I am seeing the following error in the sickrage logs and am not sure what to do with it. Doesn't seem to prevent the processing of the file. Here is my scenario:

I have sickrage, transmissionbt and sickbeard_mp4_automator on System A (Xubuntu Linux 15.10). 

My video library is on my NAS and System A has an fstab entry which mounts the directory world readable. 

Sickrage finds the video sends to transmissionbt. Once downloaded transmissionbt places the file on a mapped folder for post processing. 

Sickbeard_mp4_automator is trigered by sickrage and movies the file to the correct show directory and converts the file. 

Permissions on the folders and files are 777

any ideas

```
2016-01-14 12:07:39 INFO     POSTPROCESSER :: Processing succeeded for /media/tv_complete/CLAYMORE/Claymore - 1x17 - The Witch's Maw (3).mkv
AA
AA2016-01-14 12:07:39 - SickbeardPostConversion - INFO - Running script '/sickbeard_mp4_automator/post_process/iTunes.py'.
AA2016-01-14 12:07:38 - SickbeardPostConversion - INFO - Running script '/sickbeard_mp4_automator/post_process/sample.py'.
AA2016-01-14 12:07:38 - SickbeardPostConversion - INFO - Running script '/sickbeard_mp4_automator/post_process/sample.bat'.
AAOSError: [Errno 1] Operation not permitted: "/media/anime/Claymore/Claymore - 1x17 - The Witch's Maw (3).mp4.QTFS"
AA    os.chmod(outputfile, self.permissions)
AA  File "/sickbeard_mp4_automator/mkvtomp4.py", line 637, in QTFS
AATraceback (most recent call last):
AA2016-01-14 12:07:38 - mkvtomp4 - ERROR - Unable to set file permissions.
AA2016-01-14 12:07:38 - qtfaststart - WARNING - Could not copy file permissions!
```

**Comment by mdhiggins** [comment]
I would just ignore that error if it's not causing any problems and your permissions are being set to 777 and it's not causing any problems.

**Comment by rrd911** [comment]
I figured as much. Thanks
