### ISSUE TITLE
ffmpeg exited with code 1

### ISSUE THREAD

**Issue by mdcollins05** [mdhiggins/sickbeard_mp4_automator#404]
When running manual.py, I'm getting output that indicates ffmpeg is exiting with code 1. I ran the command manually and was given the following message:

```
ffmpeg version 0.8.17-6:0.8.17-1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 15 2015 17:00:31 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'fix_sub_duration'
Failed to set value '-i' for option 'fix_sub_duration'
```

Any ideas? The box is running Debian Wheezy and I installed ffmpeg using apt-get.

Thanks!

**Comment by zybeon** [comment]
libav is a fork of ffmpeg. To "fix" this issue install the official ffmpeg binary files.

What OS are you on?

**Comment by mdcollins05** [comment]
Everything works once I upgraded to Debian Jessie, which seems to use the official version of ffmpeg.

Thanks for the help!
