### ISSUE TITLE
Feature Request: Add support for filter by extension

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#407]
I have a rather large set of videos (mostly of my own creation).  Recently I decided to standardize all of the encoding to make thing simpler and in my search for a tool I came across this rather excellent script.  While using it, one of the things I noticed is that there is no way to tell it what to include/exclude based on file type or extension.  In my case, I'd like to only process avi and mkv files and skip over all other types.  Right now since I cannot seem to find a way to do this, the script tries to update every video I have which while not a huge deal is rather time consuming when I run it on a large folder structure.  

It would be great to see something like an "--extension" parameter or a "--filter" that would take something like "mkv,avi" or "_.mkv;_.avi"  type values and then use that in the walkDir function to skip over files that do not match.

**Comment by ravensorb** [comment]
Any thought on implementing this?  Without it, it makes for a VERY long execution time on the script as it processes everything in my library :-/

**Comment by raynotroy** [comment]
`find "/path/to/collection" -maxdepth 3 -type f -iname *.mkv -exec /path/to/script/manual.py -i "{}" -a \;`

Save this line to a .py file, then run the .py file.  When mkv files are converted, do it again for *.avi.

**Comment by ravensorb** [comment]
That's what I do now.  I take it that its not a simple thing to implement?

**Comment by mdhiggins** [comment]
Went in the opposite direction with the script and now scan based on ffprobe reads and eliminated extension based filtering entirely. For large libraries this wouldn't be efficient and you're better off using a wrapper script or media manager such as radarr/sonarr
