### ISSUE TITLE
H.265 Support

### ISSUE THREAD

**Issue by cpressland** [mdhiggins/sickbeard_mp4_automator#408]
Hey, absolutely love this project, have you considered adding H.265 support?

**Comment by mdhiggins** [comment]
It's already fully supported

**Comment by cpressland** [comment]
Whoops, my bad, haven't used this in a couple of months and to the best of my knowledge this wasn't supported then. I'll close this off.

**Comment by StevenChorkley** [comment]
How do I export into h.265 however? That seems to be unclear.
