### ISSUE TITLE
Severely Reduced Quality After Transcoding 

### ISSUE THREAD

**Issue by traxinv** [mdhiggins/sickbeard_mp4_automator#409]
So a little background. I have a movie in MKV format with the following attributes:

Container:
Format                                 : Matroska
Format version                     : Version 4 / Version 2
File size                                : 6.56 GiB
Duration                               : 2h 28mn
Overall bit rate                     : 6 338 Kbps

Video
Format                                 : AVC
Format/Info                          : Advanced Video Codec
Format profile                      : High@L4.1
Format settings, CABAC      : Yes
Format settings, ReFrames :5 frames
Codec ID                              : V_MPEG4/ISO/AVC
Duration                               : 2h 28mn
Bit rate                                 : 4 829 Kbps
Width                                   : 1 280 pixels
Height                                  : 536 pixels
Display aspect ratio             : 2.40:1
Frame rate mode                : Constant
Frame rate                          : 23.976 fps

After conversion to mp4 at mag profile 4.0 the file looks like this:

Container:
Format                      : MPEG-4
Format profile           : Base Media
Codec ID                   : isom
File size                     : 2.48 GiB
Duration                    : 2h 28mn
Overall bit rate mode: Variable
Overall bit rate          : 2 395 Kbps

Video:
Format                  : AVC
Format/Info           : Advanced Video Codec
Format profile       : High@L4.0
Format settings, CABAC        : Yes
Format settings, ReFrames   : 4 frames
Codec ID               : avc1
Codec ID/Info        : Advanced Video Coding
Duration                : 2h 28mn
Bit rate                  : 1 038 Kbps
Width                    : 1 280 pixels
Height                   : 536 pixels
Display aspect ratio  : 2.40:1
Frame rate mode     : Constant
Frame rate               : 23.976 fps

so as you can see the width and height stayed the same, the profile went from 4.1 to 4.0 which is great but the bit rate reduced by almost a factor of 5? do you perhaps know how one can force the bitrate to stay the same after transcoding?

**Comment by traxinv** [comment]
if i run it manually this is the options it generates:

![1](https://cloud.githubusercontent.com/assets/3995322/12442401/5d8b2124-bf58-11e5-9fb6-e5b2d46a6207.png)

to what level is -crf set?

**Comment by mdhiggins** [comment]
Just pushed an update that should fix this. 

It was a special circumstance where the bitrate wasn't being set in the event that the level cancelled out what would have otherwise been a copied codec.

**Comment by traxinv** [comment]
Aha. I see yeah 4.0 is still the most available level on most of my devices and I want to stick to hardware decoding as much as I can help it. 

Thanks man. You are a legend.
