### ISSUE TITLE
Feature Request: Keep original file timestamp

### ISSUE THREAD

**Issue by Landmine-1252** [mdhiggins/sickbeard_mp4_automator#411]
SickRage has an fun feature that will adjust the files created timestamp to the original air date. It would be great if we could maintain the original file timestamp if desired.

![2016-01-20_201342](https://cloud.githubusercontent.com/assets/16811401/12471430/56f94ef8-bfb2-11e5-8ab6-a9f7d6acf629.png)

**Comment by mdhiggins** [comment]
Would be happy to look at a pull request but not gonna have time to investigate this for now
