### ISSUE TITLE
SRT subs invalid

### ISSUE THREAD

**Issue by pmow** [mdhiggins/sickbeard_mp4_automator#413]
I saw in your Reddit thread that external SRTs are supported.  The config file says to set 'srt' instead of mov_text.  Fine.

But when running manual.py -i input.mkv I'm seeing:
 Invalid interal subtitle codec srt, defaulting to 'mov_text'.

It seems really straightforward to configure especially since the readme mentions it.  Is this a valid issue, or am I doing something wrong?

**Comment by morpheus2n2** [comment]
have you put a full stop before srt, so you have .srt in the autoprocess file?
I found the same and added a . as a mistake and it worked lol

**Comment by mdhiggins** [comment]
Think you need to disable the embed-subs option as well

**Comment by pmow** [comment]
Thank you, setting embed to false fixed this.
