### ISSUE TITLE
Forced sub syntax

### ISSUE THREAD

**Issue by pmow** [mdhiggins/sickbeard_mp4_automator#415]
Looked around but didn't see any mention of forced subs since 2013.

MKV:h264,dts5.1,subrip+forced

This is a fairly standard file, with the exception that it has a forced sub track.  Renaming the file output from movie.eng.srt -> movie.eng.forced.srt allows Plex to properly force the subs.

Would it be possible to handle these when splitting into external files, so that they are named movie.lan.forced.srt?

**Comment by traxinv** [comment]
With plex your can easily tell it to automatically select the subs based on the language of the audio track: 

Settings -> Server -> Languages:

Select [x] Automatically select audio and subtitle tracks. 

Prefer Audio: [your language]
Subtitle Mode: Show with foreign audio (Alternatively you can just select "Always show subtitles regardless of audio language)
Prefer Subtitles: [your language]

Note in the transformers settings, you can specify to which language it should tag the audio track if there is no metadata for that track.

**Comment by mdhiggins** [comment]
Feature added, please update
