### ISSUE TITLE
Manual run. cannot import name ExtrensionManager

### ISSUE THREAD

**Issue by Madseason41** [mdhiggins/sickbeard_mp4_automator#416]
When I perform a manual run I get the below error:

shoppc@shoppc:~/Documents/sickbeard_mp4_automator$ sudo python manual.py -h
Traceback (most recent call last):
  File "manual.py", line 5, in <module>
    import guessit
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/local/lib/python2.7/dist-packages/guessit/plugins/transformers.py", line 27, in <module>
    from stevedore import ExtensionManager
ImportError: cannot import name ExtensionManager

This error occurs when I put a file path in the common also.

Can anyone point me in the right direction on this one?

Thanks

**Comment by mdhiggins** [comment]
Need to install stevedore. It's one of the dependencies. 

'pip install stevedore'

**Comment by Madseason41** [comment]
Sorry, should have specified....

Requirement already satisfied (use --upgrade to upgrade): stevedore in /usr/local/lib/python2.7/dist-packages

**Comment by Madseason41** [comment]
I have changed permissions of the entire dist-packages directory and still get hung up on the above line.
Any other ideas?

**Comment by mdhiggins** [comment]
Make sure the python environment you've installed stevedore under is the same environment that the script is being executed from. Otherwise I would try uninstalling and reinstalling stevedore

**Comment by mdhiggins** [comment]
Likely a python environment error

**Comment by baapir** [comment]
unistall it and install it again.its worked for me
