### ISSUE TITLE
uTorrent Not Passing File Back to Sonarr

### ISSUE THREAD

**Issue by dallanlee** [mdhiggins/sickbeard_mp4_automator#417]
I have the mp4 automator script converting my sonarr labeled downloads after completion but the converted file doesn't seem to be passed back to sonarr. 

I'm using Windows 10 and I have an output director called `C:\Converting` where the file is moved from `C:\Downloads\Torrents\Completed`. So this part is working correctly. However, after converting, the episode files remain in the Converting folder, untouched by sonarr (not renamed and not placed in `C:\TV\[showname]` 

Python shows me that the `uTorrentPostProcess.py` script is being called and conversion completes without error. I have quadruple-verified that the uTorrent label for sonarr matches in the settings. It's called `sonarr_label`. Are underscores somehow not allowed? If anyone can help, I would really appreciate it. Thanks!

**Comment by morpheus2n2** [comment]
Have you made sure that utorrent is pointed to the .py with %L %T %D %K %F %I %N in that order? so it should look like **_`C:\[wherever the converter is stored]\uTorrentPostProcess.py %L %T %D %K %F %I %N`_** 
Also to make things simple I only ever use the label's Sonarr, Couchpotato, Bypass. theres no need to add the _label as it dose sometimes confuse sonarr.

**Comment by dallanlee** [comment]
Thanks for getting back to me. I did and I added quotes around `%L %T %D %K %F %I %N` so `C:\[wherever the converter is stored]\uTorrentPostProcess.py "%L %T %D %K %F %I %N"`

I'll try simplifying the labels by renaming them back to what they originally were and post an update. Thanks!

**Comment by javvydawg** [comment]
I recently switched from linux to windows 8.1 and then back to linux again but when i was on windows I ran the script with quotes on each thing. Try putting 
`C:\[wherever the converter is stored]\uTorrentPostProcess.py "%L" "%T" "%D" "%K" "%F" "%I" "%N"`
see if that helps.
