### ISSUE TITLE
ImportError: guessit

### ISSUE THREAD

**Issue by sennico** [mdhiggins/sickbeard_mp4_automator#418]
When trying to run manual.py I am getting the following error:

Traceback (most recent call last):
  File "manual.py", line 5, in <module>
    import guessit
ImportError: No module named guest

When i run pip list i see:

 guessit (1.0.2)

It's  also listed along with the other prerequisites in /usr/local/lib/python3.4/dist-packages

Im on Ubuntu 15.10, any ideas?

**Comment by mdhiggins** [comment]
Make sure you're running under the correct Python environment that the dependencies are installed under. That's usually what causes this error when the prerequisites appear otherwise appropriately installed

**Comment by sennico** [comment]
yup that was it, once i use python3 instead of python everything was is fine. Thx for the help
