### ISSUE TITLE
possible to bring new commands to autoprocess for ffmpeg.py?

### ISSUE THREAD

**Issue by dalcombright** [mdhiggins/sickbeard_mp4_automator#419]
for example, line 464 you call this for your ffmpeg.py process:

cmds.extend(opts)

instead could you call this and make these settings used in the autoprocess.ini?

variables in CAPS:

cmds.extend(opts)
cmds.extend(['-movflags', 'MOVFLAGS'])
cmds.extend(['-profile', 'PROFILE'])
cmds.extend(['-level', 'LEVEL'])
cmds.extend(['-preset', 'PRESET'])
cmds.extend(['-crf', 'CRT'])
cmds.extend(['-threads', 'THREADS'])
cmds.extend(['-map_metadata', 'MAPMETADATA'])
cmds.extend(['-y', outfile])

my setup I use:

cmds.extend(opts)
cmds.extend(['-movflags', 'faststart'])
cmds.extend(['-profile', 'v high'])
cmds.extend(['-level', '4.0'])
cmds.extend(['-preset', 'slow'])
cmds.extend(['-crf', '18'])
cmds.extend(['-threads', '1'])
cmds.extend(['-map_metadata', '-1'])
cmds.extend(['-y', outfile])

this allows for some great tweaking for quality control.

**Comment by shpankey** [comment]
very nice idea
