### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by nicb19** [mdhiggins/sickbeard_mp4_automator#421]
I previously had it working without any issues with couchpotato but for the past few days, every time I try to convert something, I get this error when it tries to get the tags from TMDB.

`SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
2016-02-03 10:25:58 - tmdb_mp4 - ERROR - Failed to connect to tMDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "/usr/local/conversion/tmdb_mp4.py", line 41, in __init__
    self.movie = tmdb.Movie(imdbid)
  File "/usr/local/conversion/tmdb_api/tmdb.py", line 122, in __init__
    self.update_configuration()
  File "/usr/local/conversion/tmdb_api/tmdb.py", line 65, in update_configuration
    c = self.getJSON(config['urls']['config'])
  File "/usr/local/conversion/tmdb_api/tmdb.py", line 53, in getJSON
    page = requests.get(url, params={'language': language}).content
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
`

Do I need to update a package? These are the python packages I currently have installed: 

> ['adium-theme-ubuntu==0.3.4', 'apscheduler==3.0.5', 'apt-xapian-index==0.45', 'babelfish==0.5.5', 'backport-ipaddress==0.1', 'backports-abc==0.4', 'backports.ssl-match-hostname==3.5.0.1', 'beautifulsoup4==4.4.1', 'beautifulsoup==3.2.1', 'bencode==1.0', 'cachecontrol==0.11.6', 'certifi==2015.11.20.1', 'cffi==1.5.0', 'chardet==2.3.0', 'cheetah==2.4.4', 'click==6.2', 'colorama==0.2.5', 'command-not-found==0.3', 'configobj==5.0.6', 'cryptography==1.2.2', 'debtagshw==0.1', 'decorator==4.0.6', 'defer==1.0.6', 'deluge-client==1.0.3', 'dill==0.2.4', 'dirspec==13.10', 'docopt==0.6.2', 'docutils==0.12', 'dogpile.cache==0.5.7', 'dogpile.core==0.4.1', 'duplicity==0.6.23', 'enum34==1.1.2', 'enzyme==0.4.1', 'extras==0.0.3', 'feedparser==5.2.1', 'fixtures==0.3.14', 'flup==1.0.2', 'formencode==1.3.0', 'future==0.15.2', 'futures==3.0.4', 'glances==1.7.3', 'gntp==1.0.2', 'guessit==1.0.2', 'hachoir-core==1.3.3', 'hachoir-metadata==1.3.3', 'hachoir-parser==1.3.4', 'html5lib==0.999', 'httplib2==0.8', 'idna==2.0', 'ipaddress==1.0.16', 'jinja2==2.7.2', 'jsonrpclib==0.1.7', 'lockfile==0.12.2', 'lxml==3.3.3', 'mako==1.0.3', 'markdown2==2.3.0', 'markupsafe==0.18', 'mox3==0.7.0', 'multipartposthandler==0.1.0', 'mysql-python==1.2.3', 'ndg-httpsclient==0.4.0', 'netifaces==0.8', 'oauth2==1.9.0.post1', 'oauthlib==1.0.3', 'oneconf==0.3.7.14.4.1', 'pam==0.4.2', 'pbr==1.8.1', 'pexpect==3.1', 'pillow==2.3.0', 'pip==8.0.2', 'piston-mini-client==0.7.5', 'ply==3.4', 'profilehooks==1.8.1', 'psutil==1.2.1', 'py-bcrypt==0.4', 'py-unrar2==0.99.6', 'pyasn1==0.1.9', 'pyasn==1.5.0b6', 'pycparser==2.14', 'pycrypto==2.6.1', 'pycups==1.9.66', 'pygithub==1.26.0', 'pygobject==3.12.0', 'pyinotify==0.9.4', 'pyopenssl==0.15.1', 'pyserial==2.6', 'pysmbc==1.0.14.1', 'pysrt==1.0.1', u'python-apt==0.9.3.5ubuntu2', 'python-daemon==2.1.0', 'python-dateutil==2.4.2', 'python-debian==0.1.21-nmu2ubuntu2', 'python-fanart==1.4.0', 'python-mimeparse==0.1.4', 'python-twitter==2.2', 'pytz==2015.7', 'pyxdg==0.25', 'pyyaml==3.11', 'qtfaststart==1.8', 'reportlab==3.0', 'requests-cache==0.4.10', 'requests-oauthlib==0.5.0', 'requests==2.9.1', 'rtorrent-python==0.2.9', 'send2trash==1.3.0', 'sessioninstaller==0.0.0', 'setuptools==19.6.2', 'sickrage==6.0.34', 'simplejson==3.8.1', 'singledispatch==3.4.0.3', 'six==1.10.0', 'software-center-aptd-plugins==0.0.0', 'speedtest-cli==0.3.4', 'sqlalchemy-migrate==0.10.0', 'sqlalchemy==0.8.4', 'sqlobject==2.1.2', 'sqlparse==0.1.18', 'ssh-import-id==3.21', 'stevedore==1.10.0', 'subliminal==1.1.1', 'sympy==0.7.6.1', 'system-service==0.1.6', 'tempita==0.5.2', 'testtools==0.9.35', 'tmdbsimple==1.3.0', 'tornado==4.3', 'twisted-core==13.2.0', 'twisted-web==13.2.0', 'twitter==1.17.1', 'tzlocal==1.2', 'unity-lens-photos==1.0', 'urllib3==1.7.1', 'web.py==0.37', 'wheel==0.24.0', u'xdiagnose==3.6.3build2', 'xmltodict==0.9.2', 'yarg==0.1.9', 'youtube-dl==2015.10.24', 'zope.interface==4.0.5']

**Comment by mdhiggins** [comment]
Did you install the requests security package?

`pip install requests[security]`

**Comment by nicb19** [comment]
Yep, I've installed all the pre-requisites and it was working fine until last week.

`Requirement already up-to-date: requests[security] in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pyOpenSSL>=0.13 in /usr/local/lib/python2.7/dist-packages (from requests[security])
Requirement already up-to-date: ndg-httpsclient in /usr/local/lib/python2.7/dist-packages (from requests[security])
Requirement already up-to-date: pyasn1 in /usr/local/lib/python2.7/dist-packages (from requests[security])
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: cryptography>=0.7 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: setuptools>=1.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL>=0.13->requests[security])
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=0.7->pyOpenSSL>=0.13->requests[security])`

**Comment by nicb19** [comment]
Appears to be an issue with requests. I've raised an issue with them so this issue can be closed.

**Comment by mdhiggins** [comment]
Nice, feel free to reference it here (if its on github) so others can find it, gonna close for now though

**Comment by nicb19** [comment]
[According to a collaborator for requests](https://github.com/kennethreitz/requests/issues/2995), it's due to an issue with certifi.

More information on this issue [here](https://github.com/certifi/python-certifi/issues/26). The issue is still open although it looks like a solution has been found. Going to try it now and see if it works.
