### ISSUE TITLE
NZBGetPostProcess error

### ISSUE THREAD

**Issue by sacredshapes** [mdhiggins/sickbeard_mp4_automator#425]
I've had a couple of issues that turned out to be my fault due to a dodgy Python install, but with NZBget I'm now getting the below error. I just reinstalled Python 2.7 and I can now get manual.py to work which is awesome, but this is what I'm getting now in the NZBget logs;

- INFO	Tue Feb 09 2016 14:21:04	Post-process-script NZBGetPostProcess.py for DCs.Legends.of.Tomorrow.S01E04.720p.HDTV.X264-DIMENSION skipped
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: Logged from file NZBGetPostProcess.py, line 144
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: TypeError: not all arguments converted during string formatting
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: msg = msg % self.args
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 329, in getMessage
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: record.message = record.getMessage()
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 465, in format
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: return fmt.format(record)
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 726, in format
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: msg = "%s\n" % self.format(record)
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\handlers.py", line 156, in shouldRollover
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: if self.shouldRollover(record):
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\handlers.py", line 76, in emit
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: Traceback (most recent call last):
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: Logged from file NZBGetPostProcess.py, line 144
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: TypeError: not all arguments converted during string formatting
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: msg = msg % self.args
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 329, in getMessage
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: record.message = record.getMessage()
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 465, in format
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: return fmt.format(record)
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 726, in format
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: msg = self.format(record)
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: File "C:\Python27\Lib\logging\__init__.py", line 853, in emit
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: Traceback (most recent call last):
- INFO	Tue Feb 09 2016 14:21:04	NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).

Any ideas? I feel like it's probably something silly like a permission issue but I'm a little stuck

**Comment by sacredshapes** [comment]
Okay, after fiddling a bit I'm getting a different error now;

`NZBGetPostProcess: Could not start post-process-script NZBGetPostProcess.py for 30.Rock.S04E01.Season.4.720p.WEB-DL.DD5.1: The system cannot find the file specified.`

Is this telling me it can't see the file I downloaded or the script? Feel like I'm losing my mind.

**Comment by mdhiggins** [comment]
Its saying it can't see the download/file, not the script itself. I'm not sure why you're getting that error, was the file deleted or moved for some reason?

**Comment by sacredshapes** [comment]
Thanks for the response, that turned out to be my fault. I am however having this problem now, do you know if it's best to open a new issue? It still falls under the subject header, really.

```
INFO	Sun Feb 14 2016 10:40:54	Collection ***** added to history
INFO	Sun Feb 14 2016 10:40:54	Cleaning up download queue for *****
INFO	Sun Feb 14 2016 10:40:54	Post-process-script NZBGetPostProcess.py for ***** successful
INFO	Sun Feb 14 2016 10:40:54	NZBGetPostProcess: 2016-02-14 10:40:54 - autoprocess.sonarr - INFO - [INFO] Sonarr response: started.
INFO	Sun Feb 14 2016 10:40:54	NZBGetPostProcess: 2016-02-14 10:40:54 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory 'J:\Downloads\complete\*****'.
INFO	Sun Feb 14 2016 10:40:53	NZBGetPostProcess: 2016-02-14 10:40:53 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
INFO	Sun Feb 14 2016 10:40:53	NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).
INFO	Sun Feb 14 2016 10:40:51	Executing post-process-script NZBGetPostProcess.py for *****
```

It seems to just be skipping the actual conversion. Thanks again for your help.

**Comment by mdhiggins** [comment]
Post your autoprocess.ini settings please

**Comment by sacredshapes** [comment]
`[uTorrent]
username = 
action_after = removedata
sonarr-label = sonarr
host = http://localhost:8080/
webui = False
password = 
convert = True
sickbeard-label = sickbeard
couchpotato-label = couchpotato
action_before = stop
bypass-label = bypass
sickrage-label = sickrage

[MP4]
tag-language = en
download-artwork = thumbnail
download-subs = False
delete_original = True
audio-language = 
output_format = mp4
ffprobe = J:\ffmpeg2\ffmpeg-20150928-git-1d0487f-win64-static\bin\ffprobe.exe
move_to = 
output_directory = 
post-process = False
ios-first-track-only = False
max-audio-channels = 
subtitle-codec = mov_text
audio-codec = ac3
pix-fmt = 
subtitle-default-language = 
tagfile = True
video-bitrate = 
relocate_moov = True
embed-subs = True
ffmpeg = J:\ffmpeg2\ffmpeg-20150928-git-1d0487f-win64-static\bin\ffmpeg.exe
h264-max-level = 
fullpathguess = True
sub-providers = addic7ed, podnapisi, thesubdb, opensubtitles
convert-mp4 = True
audio-default-language = 
output_extension = mp4
ios-audio = True
video-max-width = 
audio-channel-bitrate = 256
permissions = 777
subtitle-language = 
copy_to = 
video-codec = h264, x264

[Sonarr]
ssl = False
host = localhost
apikey = [removed]
port = 6788
web_root = 

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[CouchPotato]
username = 
delay = 65
host = localhost
apikey = 
web_root = 
delete_failed = False
ssl = False
password = 
port = 5050
method = renamer

[SickBeard]
username = 
password = 
ssl = False
host = localhost
web_root = 
api_key = 
port = 8081

[Sickrage]
username = 
password = 
ssl = False
host = localhost
web_root = 
api_key = 
port = 8081

[Plex]
token = 
host = localhost
port = 32400
refresh = true
`

**Comment by mdhiggins** [comment]
Do you have the convert option enabled and your categories properly set in NZBGet?

**Comment by sacredshapes** [comment]
That was it. I am an idiot.

Thanks for your help (and patience). Working smoothly now.
