### ISSUE TITLE
CouchPotato integration seems to do nothing

### ISSUE THREAD

**Issue by BFG9000** [mdhiggins/sickbeard_mp4_automator#427]
I'm sure this is an issue with my set-up, rather than with the script - but would be grateful for any advice as to where/how I should go about troubleshooting...

I use Sonarr for TV Shows - and it all seems to work fine.  
But for Movies, I use CouchPotato and they just seem to sit in the NZBGet complete folder - and don't get processed or moved to my Plex media location.  
  
I've been going round and round for ages - and can't seem to work out where the problem lies - I'll list some details below - and would be grateful if anyone could point me in the right direction.  
  
  
* Plex Media is stored in E:\Media\Sorted\TV & E:\Media\Sorted\Movies  
* NZBGet Completed downloads are in L:\NZBGet\complete\TV & L:\NZBGet\complete\Movies  
* In CouchPotato : Settings : Renamer, I have `Run Every` & `Force Every` set to '0' (zero).  
* My NZBGETPOSTPROCESS set-up [looks like this](http://i.imgur.com/ls9Yv4K.png) - Interestingly, I had to manually add the details to my nzbget.conf because adding through the interface doesn't seem to work.  
* If I search for 'Movies' in my sickbeard_mp4_automator info.log - nothing is found.  
  
  
I'm at a loss as to where the problem lies.  
  
Any thoughts?  
  
  
  
  
EDIT : [This happens](http://i.imgur.com/NpT3SNZ.png) after I save anything in NZBGet settings.

**Comment by mdhiggins** [comment]
I think something odd is going on with your setup but its tough to say what. When a file completes its downloading can you post all the logging that NZBGetPostProcess produces?

**Comment by BFG9000** [comment]
That's the really odd thing - nothing is in the log at all relating to movies from couchpotato.

**Comment by mdhiggins** [comment]
Anything in NZBGet's logging system?
