### ISSUE TITLE
Problem with danish subtitles

### ISSUE THREAD

**Issue by noise86** [mdhiggins/sickbeard_mp4_automator#428]
Hi

It seems there is a problem when embedding subtitles with danish characters like æ, ø and å.

I usually add both english and danish subtitles and the english part is working fine.

However when switching to the danish subtitles only lines without the above characters are shown.

I checked the SRT file and the lines are there, but are not being shown in the movie if it contains the above characters.

**Comment by mdhiggins** [comment]
That probably has more to do with your playback software than the encoding itself

**Comment by mdhiggins** [comment]
You can try modifying this line:
`'encoding': 'UTF-8'` in mkvtomp4.py
and changing the encoding to something besdies UTF-8 and see if that improves your results. 
I would try changing `UTF-8` to `ISO-8859-1` and see if that has any effect on your results
