### ISSUE TITLE
iso-audio option forces lower quality aac encoder

### ISSUE THREAD

**Issue by outlyer** [mdhiggins/sickbeard_mp4_automator#429]
In ```readSettings.py```, the line 

```python
if self.iOS.lower() in ['true', 'yes', 't', '1']:
  self.iOS = 'mac'
```

basically forces ffmpeg to use the lower quality aac encoder instead of the libfdk_aac encoder which is recommended.

Right now, I can't figure out a way to choose the better encoder without either changing the line to

```python
if self.iOS.lower() in ['true', 'yes', 't', '1']:
   self.iOS = 'libfdk_aac'
```

or adding another setting to prefer aac. Further to that, if the build of ffmpeg doesn't include fdk_aac  (and --enable-gpl and --enable-nonfree) then the command will fail.

**Comment by mdhiggins** [comment]
Not sure where you're getting the line `self.iOS = 'mac'` from, currently the code is as follows:

```
        self.iOS = config.get(section, "ios-audio")  # Creates a second audio channel if the standard output methods are different from this for iOS compatability
        if self.iOS == "" or self.iOS.lower() in ['false', 'no', 'f', '0']:
            self.iOS = False
        else:
            if self.iOS.lower() in ['true', 'yes', 't', '1']:
                self.iOS = 'aac'
```

All this code is doing is allowing legacy users to leave 'true' or 'false' in the iOS-audio option in autoProcess.ini.

If you set your autoProcess.ini iOS-audio option to `libfdk_aac' then it will use that codec. If you look closely none of the code above except the first line is applied unless the iOS option is set to some variant of `True` or `False`

**Comment by outlyer** [comment]
The ```self.iOS = 'mac'``` was just Safari autocorrecting, it was supposed to be ```self.iOS = 'aac'``` as was the title of the bug report. 

But, thanks for the clarification. Can this be added to the README.md?
