### ISSUE TITLE
Language setting subtitle

### ISSUE THREAD

**Issue by conradhagemans** [mdhiggins/sickbeard_mp4_automator#430]
What are the correct 3-letter codes for the subtitle languages?
I am looking for English and Dutch

I asume ENG and DUT
But it never downloads the dutch subtitles. Should it be NLD? From Netherlands?

**Comment by mdhiggins** [comment]
http://www.nationsonline.org/oneworld/country_code_list.htm

**Comment by mdhiggins** [comment]
Looks like DUT isn't a valid code, so yeah probably NLD
