### ISSUE TITLE
use intel quicksync

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#431]
FFMPEG 2.8 has built in support for intel quicksync on windows but I cannot figure out how I could use it with your script, Do you have any info on what I need to change to use h264_qsv  instead? It is a lot faster and does not stress the cpu for conversions.

**Comment by medjai** [comment]
I think this would be an excellent option as well.

**Comment by mdhiggins** [comment]
Can you provide a sample FFMPEG command for quicksync? If its just a custom h264 codec that can be easily implemented.

**Comment by rcocchiararo** [comment]
From here: https://trac.ffmpeg.org/wiki/HWAccelIntro

ffmpeg -i INPUT -c:v h264_qsv -preset:v faster out.qsv.mp4

Was just googling about this, cause i installed this script in a mini pc with a dual core celereon, that will most surely take ages to do the work, but has no issue transcoding (emby) in real time with quicksync.

**Comment by rcocchiararo** [comment]
Checking arround, i see that the "codec" is still H264, but the encoders for that can be:

encoders: libx264 libx264rgb h264_qsv

DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv ) (encoders: libx264 libx264rgb h264_qsv )

V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)

--

After reading for a while (i am totally new to ffmpeg), it is as you said, it is just a custom h264 encoder/decoder (or codec?)

Still have not found what presets are available, but if possible to choose, would be nice (unless faster vs slower offer the same video quality).

**Comment by rcocchiararo** [comment]
I am reading both this proyect´s code and ffmpeg documentation (my python is very limited, and i am new to ffmpeg :P )

Codecs:
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv ) (encoders: libx264 libx264rgb h264_qsv )
EncoderS:
 V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)

h264_qsv is both an encoder and decoder for H264.

I am looking at your code, would avcodecs.py be the best place to look for trying to do something myself, until the pro is done ? XD

**Comment by mdhiggins** [comment]
Just pushed an update to add the h264_qsv codec as an option.
Update your autoProcess.ini settings to the follow:
`video-codec = h264qsv, h264, x264`

Give it a try and let me know if its working

**Comment by rcocchiararo** [comment]
Will try in 10 minutes.
Doubt: h264qsv is actually the encoder, have you made it so that if it
finds any other codec from that list, it won't reencode?
Extra: what about my faster/fast/normal/slow/slower doubts?

Thx in advance

El vie., 4 de mar. de 2016 18:12, Michael Higgins <notifications@github.com>
escribió:

> Just pushed an update to add the h264_qsv codec as an option.
> Update your autoProcess.ini settings to the follow:
> video-codec = h264qsv, h264, x264
>
> Give it a try and let me know if its working
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdhiggins/sickbeard_mp4_automator/issues/431#issuecomment-192468040>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by mdhiggins** [comment]
Correct, if you don't leave h264 (plain) on that list, you will end up reencoding all  h264 codecs because no matter what encoder you use to get to h264, FFPROBE reads them all as 'h264'

**Comment by rcocchiararo** [comment]
Current result:

`C:\Users\p2p\Desktop>manual.py -i F:\Videos\Series\Quantico\S01 -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Processing file F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv
Matched TV episode as Quantico (TVDB ID:295515) S01E03
Processing Quantico Season 01 Episode 03 - Cover
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: ssa [und].
Ripping spa subtitle from source stream 2 into external file.
F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.spa.3.srt created.
{
    "subtitle": {},
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "copy",
            "bsf": "aac_adtstoasc",
            "bitrate": 256
        }
    },
    "video": {
        "map": 0,
        "codec": "h264qsv",
        "bitrate": 673.59,
        "level": null
    },
    "format": "mp4"
}
Starting conversion.
Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\SickRage\mp4_automator\mkvtomp4.py", line 584, in convert
    for timecode in conv:
  File "C:\SickRage\mp4_automator\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\SickRage\mp4_automator\converter\ffmpeg.py", line 547, in convert
    line, pid=p.pid)
", pid=4468, cmd="C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv -vcodec h264_qsv -map 0:0 -vb 673k -c:a:0 copy -map 0:1 -bsf:a:0 aac_adtstoasc -metadata:s:a:0 language=eng -f mp4 -threads auto -y F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mp4">
F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mp4 deleted.
Processing file F:\Videos\Series\Quantico\S01\Quantico.S01E04.720p.HDTV-SickRage.mkv
Matched TV episode as Quantico (TVDB ID:295515) S01E04
Processing Quantico Season 01 Episode 04 - Kill
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #2: ac3 [eng].
Creating audio stream 0 from source audio stream 2 [iOS-audio].
Creating audio stream 1 from source stream 2.
Reading subtitle streams.
Subtitle detected for stream #0: srt [eng].
Ripping eng subtitle from source stream 0 into external file.
F:\Videos\Series\Quantico\S01\Quantico.S01E04.720p.HDTV-SickRage.eng.srt created.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 2,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 2,
            "codec": "copy",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 1,
        "codec": "copy",
        "bitrate": 3806.55975,
        "level": null
    },
    "format": "mp4"
}
Starting conversion.
[          ] 9%`

Not sure what the error was about or what is happening now (i only downloaded the modified .py file and replaced it, and also deleted the .pyc file)

Note: Today, from that very same CMD windows, i had tried the folder convertion, and it was too slow without qsv, so i canceled.

**Comment by Deihmos** [comment]
I don't think quicksync is used when remuxing to a different container. It is used for encoding. I am not an expert though.

**Comment by mdhiggins** [comment]
That is correct, but you wouldn't want to use quicksync because remuxing requires no CPU usage anyway, its simply direct data copying and would still be faster than quicksync w/ no quality loss

**Comment by Deihmos** [comment]
I know.  I was interested in using it to convert videos to a lower bitrate for streaming.

**Comment by mdhiggins** [comment]
Run this command:
`C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv -vcodec h264_qsv -map 0:0 -vb 673k -c:a:0 copy -map 0:1 -bsf:a:0 aac_adtstoasc -metadata:s:a:0 language=eng -f mp4 -threads auto -y F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mp4`
and tell me what error FFMPEG spits out

**Comment by rcocchiararo** [comment]
Dunno if Deihmos answer is related to my doubts (i wanted to confirm that when only remuxing was needed, there would be no accidental quicksync convertion), or to my message with the error.

will check your commnad now.

It kept throwing the same error for the next episodes (it was fast tho >P)

**Comment by rcocchiararo** [comment]
Result of your command:

http://pastebin.com/P9pCLjbK

Note: this same file can be transcoded with no errors by EMBY, using quicksync, or converted by your script without qsv.

**Comment by mdhiggins** [comment]
Hm this might be that the bitrate the script is generating is too high and throwing an error.

See if this command works:
C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv -vcodec h264_qsv -map 0:0 -c:a:0 copy -map 0:1 -bsf:a:0 aac_adtstoasc -metadata:s:a:0 language=eng -f mp4 -threads auto -y F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mp4

**Comment by rcocchiararo** [comment]
Same result:

http://pastebin.com/yALBVKyH

**Comment by rcocchiararo** [comment]
Tried the example from the documentation, and it is not working either, but the red text is... less

http://pastebin.com/Tja9JNqX

**Comment by mdhiggins** [comment]
Do you have any other files you could try it on? Some that maybe aren't HEVC encoded?

**Comment by rcocchiararo** [comment]
I can't believe it, but everything i check is either H264 (non .mp4) or HEVC.... anything to download? T_T

**Comment by rcocchiararo** [comment]
Just remembered i have a collection of home videos, that i will evenutally try to convert too.

http://pastebin.com/pvakW3S7

I tried with the manual script and it said something weird:

F:\Videos>manual.py -i F:\Videos\100_1072.MOV -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
File F:\Videos\100_1072.MOV is not in the correct format

F:\Videos>manual.py -i F:\Videos\GOPR0001.MP4 -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
File F:\Videos\GOPR0001.MP4 is not in the correct format

**Comment by rcocchiararo** [comment]
Googling arround, i found that there is a setting "-look_ahead". 
I still need to understand what it does, but i at least completed a command like this:

ffmpeg -i GOPR0001.MP4 -c:v h264_qsv -preset:v faster -look_ahead 0 out.qsv.mp4

**Comment by Deihmos** [comment]
This pdf has a lot of info. The 1st page has a sample.

http://www.intel.com/content/dam/www/public/us/en/documents/white-papers/quicksync-video-ffmpeg-install-valid.pdf

**Comment by rcocchiararo** [comment]
Nothing i can use there.

https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/qsvenc.c

There, i could found the ratecontroll error.

Sitll nothing about look_ahead,tho it is related.

**Comment by rcocchiararo** [comment]
Ok, what look_ahead 0 does, is DISABLE that :p 

Quality of the conversion seems subpar tho.

**Comment by rcocchiararo** [comment]
This works:

C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv -c:v h264_qsv -preset:v veryslow -look_ahead 0 -map 0:0 -vb 673k -c:a:0 copy -map 0:1 -bsf:a:0 aac_adtstoasc -metadata:s:a:0 language=eng -f mp4 -threads auto -y F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mp4

Only thing, before starting, it complains about this:

[AVFilterGraph @ 0000000f8f144da0] [Eval @ 0000000f8ce3daa0] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0000000f8f144da0] Unable to parse option value "auto"

It seems that look_ahead needs to be disabled.

I like using veryslow for the preset, in order to keep the best quality and size.

**Comment by mdhiggins** [comment]
Just pushed another update the h264qsv protocol so the `-lookahead 0` option should be included

Give that a shot and let me know

**Comment by rcocchiararo** [comment]
This time i got this:

> C:\SickRage\mp4_automator>manual.py -i F:\Videos\Series\Quantico\S01\Quantico.S01E03.720p.HDTV-SickRage.mkv -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "C:\SickRage\mp4_automator\manual.py", line 33, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "C:\SickRage\mp4_automator\readSettings.py", line 446, in __init__
    self.uTorrentWebUI = config.getboolean(section, "webui")
  File "C:\Python27\lib\ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean:

---

On a sidenote, i decided to keep the script withotu QSV for new downloads, and since QSV was fast but ugly, i installed it on my core i7 (920, first gen :P ) pc, to convert/remux the old downloads.

I used manual.py on a folder, but the conversion was almost as ugly as QSV! I know that software like handbreak or plex can convert without loosing quality, but i liked the simplicity of your script.
Am i doing something wrong?

Looked at avcodecs.py and noticed that in the H264Codec class there are options, where quality is mentioned. Can i somewho force a preset from there, and quality to lossless?
I can try other software, but i find it strange that plex media server, using ffmpeg, get me the same quality for their conversions, and the transcoding (live conversion) using QSV from EMBY media server is also really nice, but here, (except when remuxing), quality goes to trash (dunno if the bitrate is reduced or what, but moving parts look pixelated).
But your script does magic with audio and subs, that i really like.

**Comment by rcocchiararo** [comment]
My bad on that last report, i had broken the .ini file.

it is running smoothly now.

Still, if possible, i would love to be able to toy with preset/quality/profile/level.

Also, i tried handbreak, and when using QSV, the options you can set (and as far as i could see, i got nice results) are:

Quality (the default of 20 is ok, albeit slower).
QSV Preset: Balanced/faster (balanced is the default)
H.264 profile: defauilt is main
H.264 level: default is 4.0

**Comment by mdhiggins** [comment]
I think the issue is that the bitrate of HEVC is very low because it's compressed and way more space efficient than H264 and the script because it has no good way to know what bitrate to set attempts to emulate the bitrate of the source file. This results in a low bitrate quality setting for h264. I'll have to look into what would be the best way to solve this

**Comment by rcocchiararo** [comment]
That might be it. In fact, videos produces with your script are equal or smaller than the original HVEC ones.

Videos i make with handbrake are twice the size and still a bit lower quality, and videos PLEX media server "optimize" feature produces are 4 times as big (and quality is exactly the same).

All tools using ffmpeg

**Comment by thezoggy** [comment]
note that if you use certain builds of ffmpeg (http://johnvansickle.com/ffmpeg/) you cant use QSV on a headless machine due to it needing x11/display.
http://emby.media/community/index.php?/topic/10723-gpu-transcoding-intel-quicksync-and-nvidia-nvenc/page-26

and for those that are curious: https://ffmpeg.org/general.html#Intel-QuickSync-Video

**Comment by rcocchiararo** [comment]
Dunno about the other intrested people, but in my case, it is running windows 10, and doubles as the media player for the livingroom tv :P

**Comment by mdhiggins** [comment]
So I think the only way to get around the bitrate is for you to manually specify a video-bitrate in autoProcess.ini to override the scripts attempt to guess one

**Comment by rcocchiararo** [comment]
What about checkign if H265 is de codec, and in that case, dunno.. tripple or more the bitrate?

**Comment by medjai** [comment]
I agree, there must be some way to programmatically figure out proper
bitrate

**Comment by mflagler** [comment]
I had issues using the qsv encoder as it was using lookahead instead of look_ahead as the parameter. Otherwise it seemed to look good. I have another encode using the standard h264 encoder to compare qualities between them at the same bitrate.

**Comment by mdhiggins** [comment]
Fixed the lookahead/look_ahead fix

Not sure what you mean by a pre-option

And as far as figuring out the bitrate, there's really no good conversion or equivalence ratio for standardizing bitrates across codecs, your best best is to hard-code the desired bitrate of your output files

I can look into adding `crf` or `preset` option in the future for more options but it will still be essentially manually setting your quality

**Comment by mflagler** [comment]
In mkvtomp4.py on line 581, part of the line has: 
preopts=['-fix_sub_duration']

which I changed to:
preopts=['-fix_sub_duration', '-vcodec', 'h264_qsv']

Which enabled the QuickSync codec to be used for decoding as well. It increased my FPS on a current transcode test I did of a file from 130 to around 160. I don't know if there's a way to specify that the h264_qsv be used if the input file is h264 and the hardware is supported (or just enabled through the ini file).

As for quality, on that same test, I couldn't tell a difference between the 2 encoders when using the max bitrate of 10000 in my settings, so it definitely helps out.

**Comment by mdhiggins** [comment]
Setting your video codec in autoProcess ini as follows
`video-codec = h264qsv, h264, x264` should be enough without the file modifications you made

If you're coping the video stream you're not decoding at all, its just all dependent on the card drive speeds

**Comment by rcocchiararo** [comment]
I still think that you should add either some "conversion rate" when the
original codec is h265, or a manual hardcode only for when it cannot be
automatically determined.

Since Plex Media server produces files 4 times the size when converting
from h265 to h264, a fixed value between 3x and 4x fro that specific codec
could work.

El mié., 16 de mar. de 2016 16:05, Michael Higgins <notifications@github.com>
escribió:

> Setting your video codec in autoProcess ini as follows
> video-codec = h264qsv, h264, x264 should be enough without the file
> modifications you made
>
> If you're coping the video stream you're not decoding at all, its just all
> dependent on the card drive speeds
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mdhiggins/sickbeard_mp4_automator/issues/431#issuecomment-197493765>
>
-- 
--
Roberto Cocchiararo

**Comment by mflagler** [comment]
I am setting the video codec in the ini file, but that's only for encoding the file. For decoding, I believe ffmpeg defaults to the default h264 decoder. At least on the test I did by running ffmpeg manually, I got that improvement in speed just by adding those options before the input file. In my case, I had a very high bitrate 30kbps MKV that I wanted to convert to 10kbps video to reduce the file size. In that case, I believe it is doing a software h264 decode, then re-encoding at the lower rate using h264_qsv, but when I specified the decoder to use h264_qsv, it also gave me a bump in transcoding speed.

**Comment by mdhiggins** [comment]
Ah I see what you're saying, pushed an update to include this under those circumstances

**Comment by mdhiggins** [comment]
And I'm not gonna add an arbitrary conversion rate, seems kinda sloppy and inaccurate. I'll see what other options are available though and try and come up with something

**Comment by rcocchiararo** [comment]
A parameter to ser such arbitrary thing would be much less sloppy than hard
coding bit rate for every conversion regardless of codec/situation :P

El mié., 16 de mar. de 2016 16:47, Michael Higgins <notifications@github.com>
escribió:

> And I'm not gonna add an arbitrary conversion rate, seems kinda sloppy and
> inaccurate. I'll see what other options are available though and try and
> come up with something
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mdhiggins/sickbeard_mp4_automator/issues/431#issuecomment-197513096>
>
-- 
--
Roberto Cocchiararo

**Comment by mflagler** [comment]
The change works perfectly! I'm doing transcodes to lower bitrates now in much less time and only using 30% CPU or less (probably the audio transcoding).

**Comment by shpankey** [comment]
Alternative, I'm trying out the nvenc_h265 option you added myself and will report back.

**Comment by PaidToTrade** [comment]
h265_qsv?

**Comment by bweston6** [comment]
I've tried setting video-codec = h264qsv, h264, x264 but when running I get this error: unrecognized option 'look_ahead'. I am running this on a mac and it gives the same error whether using the ffmpeg static build from https://www.ffmpeg.org/download.html or using ffmpeg installed via brew.

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/840

See if that info is helpful

**Comment by bweston6** [comment]
I've changed my codec line so it reads video-codec = h264vaapi,h264, x264. I now get a different error: Unrecognized option 'vaapi_device'. Again I tested this with both brew and static builds of ffmpeg.
