### ISSUE TITLE
What if the manually defined "audio-language" is not found?

### ISSUE THREAD

**Issue by TwoLeaves** [mdhiggins/sickbeard_mp4_automator#432]
If I set audio-language to "eng", as I only want to include in the English audio track of a film, what happens when I download a foreign film? I want the transcoder/remuxer to include only English unless English is not found (in which case I suppose include all the audio tracks because there's no way to know what the native track for a film is in individual cases). Is this possible?

**Comment by mdhiggins** [comment]
Not currently possible, you can manually add the languages to autoProcess.ini for specific films but there's no 'fallback' when that language isn't encountered, but its a good idea. I can look into adding this. Shouldn't be too difficult.

**Comment by mdhiggins** [comment]
Just pushed a new update that includes a failsafe in the event that your source video has no audio language options that match autoProcess.ini requirements. In the event that a no-audio output file would be created the audio settings are relaxed and the language requirements lifted
