### ISSUE TITLE
Blank subtitles

### ISSUE THREAD

**Issue by jacobwgillespie** [mdhiggins/sickbeard_mp4_automator#434]
I'm trying to convert a mkv that contains ASS subtitles - I've tried both extracting them to srt with embed-subtitles set as false (which contains a bunch of blank entries under the timecodes) and embedding them as mov_text, but neither way produces any results.  I'd try running ffmpeg manually but can't seem to find how to log the command being used.  Here's the extracted sub file if that helps:

[subs.ass](https://files.zenhub.io/56caaa7f058479ba5b2fafec)

**Comment by jacobwgillespie** [comment]
I did make some progress by adding a new format with the extension `ass` then using that to directly extract the subtitles.  Still not sure why the conversion to srt is failing.

**Comment by mdhiggins** [comment]
If you could send me a sample mkv that's giving you trouble I will do some testing
