### ISSUE TITLE
Option to set ffmpeg.exe CPU priority on Windows

### ISSUE THREAD

**Issue by jeffshieldsdev** [mdhiggins/sickbeard_mp4_automator#435]
I'm not concerned with how long conversion takes.  Is there an option to always set the CPU priority assigned to ffmpeg.exe when it runs to Below Normal on Windows 10?  Thank you.

**Comment by mdhiggins** [comment]
I don't think there's any good way to do this at the moment. I'll be adding an option in the future to set the number of threads which may be an alternative (limit to 1 thread for example).

**Comment by mflagler** [comment]
I ended up writing a small AutoIT script which runs for a minute or 2 looking for any ffmpeg processes and setting their priority to below normal. I am only manually processing my files but wrote a batch file script to call the exe using "start FFMPEG-Priority" before calling the manual.py file. I'm sure the same could work for any method you're using.

If you want to download the compiled version of the script, you can get it here: https://drive.google.com/file/d/0B1sCav7oG3IOS0ljaDRvT2hUMzA/view?usp=sharing

The source code for it is here:
https://drive.google.com/file/d/0B1sCav7oG3IOazRqUENCcDZOVnM/view?usp=sharing

(Yes it could be written much easier, but I just modified some code I had written for changing CPU affinity of some other software I had issues with.)

**Comment by mdhiggins** [comment]
Added the threads option to autoProcess.ini

`threads` default is `auto`
