### ISSUE TITLE
No such file or directory with CouchPotato

### ISSUE THREAD

**Issue by LandMineHare** [mdhiggins/sickbeard_mp4_automator#436]
So, somewhere along the line, I updated CouchPotato, updated this script, but I don't know when this issue started happening, but I've noticed a lot of my movies no longer have tags or anything. After dinking around for a few hours and getting nowhere, I decided to check here.

> 02-23 18:50:08 INFO [ PostProcess] MP4 Automator - Post processing script initialized
> 02-23 18:50:08 INFO [ PostProcess] Executing post processing on file /Data/Movies/Immortals (2011)/Immortals (2011).mkv with IMDB ID t1253864
> 02-23 18:50:08 INFO [ PostProcess]
> 02-23 18:50:08 INFO [ PostProcess] env: python: No such file or directory
> 02-23 18:50:08 INFO [ PostProcess] Return code: 127

I have no idea why that's happening, I'm not even sure when it started happening.

**Comment by mdhiggins** [comment]
You need to set up python as an environment variable, looks like you're probably in windows

https://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7

**Comment by LandMineHare** [comment]
No, it is in a FreeBSD jail.

**Comment by mdhiggins** [comment]
https://forums.freebsd.org/threads/28779/

Does this help? Don't have a ton of experience with FreeBSD

**Comment by LandMineHare** [comment]
I too don't have a ton of experience with FreeBSD either, and am not entirely sure what to change.

I added 
`#!/usr/local/bin/ python`
to the top of main.py in the PostProcess script in CP's custom_plugins folder but it didn't seem to help.
I tried adding it to the postCouchPotato.py script in the main scripts folder.
Will report back once I see if it works.

**Comment by mdhiggins** [comment]
I'm guessing this has to be a permissions issue with CouchPotato trying to execute the script it doesn't have permission to access

Maybe someone with a FreeBSD setup can weigh in here

**Comment by raymatos** [comment]
Have the same issue on freebsd.  Any luck?

**Comment by LandMineHare** [comment]
No idea. I completely forgot about this. I think I just ran a package update for everything. Seems to be fixed, at least not seeing that error code anymore.
