### ISSUE TITLE
Set ffmpeg thread limits

### ISSUE THREAD

**Issue by pmow** [mdhiggins/sickbeard_mp4_automator#437]
Would it be possible to add nice, ionice, and/or threads options to ffmpeg?  I tried doing this in the executable but got errors.

ffmpeg -threads n would limit the number of cores on encodes

**Comment by mdhiggins** [comment]
Its currently set to -threads auto, I can look into adding this as an option to autoProcess.ini in the future
Thread usage is dependent on the codec however, not all codecs will use multiple threads even with that option set.

**Comment by pmow** [comment]
Thank you, that would be great!

I've used it in the past with h264 which is what I typically have on my hands.  On a dual-core machine being able to set this helps segregate transcoding from critical processes such as plex.

**Comment by mdhiggins** [comment]
Thread options added to autoProcess.ini

`threads`
Can be set to any integer or 'auto'
