### ISSUE TITLE
Issue Converting NZBGet

### ISSUE THREAD

**Issue by elit3ge** [mdhiggins/sickbeard_mp4_automator#441]
I am having an issue when my releases from Couchpotato.

When the conversion has finished I received this error.

INFO    2016-03-13 16:56:29     NZBGetPostProcess: 2016-03-13 16:56:29 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
INFO    2016-03-13 16:57:34     NZBGetPostProcess: 2016-03-13 16:57:34 - autoprocess.autoProcessMovie - INFO - Opening URL: https://url/api/apicode/renamer.scan.
INFO    2016-03-13 16:57:35     NZBGetPostProcess: Traceback (most recent call last):
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\SickRage-Master\contrib\nzbToMedia\NZBGetPostProcess.py", line 185, in <module>
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     autoProcessMovie.process(path, settings, nzb, status)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "D:/mkvtomp4/trunk/autoprocess\autoProcessMovie.py", line 91, in process
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     r = requests.get(url, params=params)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\api.py", line 69, in get
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     return request('get', url, params=params, **kwargs)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     response = session.request(method=method, url=url, **kwargs)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     resp = self.send(prep, **send_kwargs)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     r = adapter.send(request, **kwargs)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\adapters.py", line 370, in send
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     timeout=timeout
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     body=body, headers=headers)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 344, in _make_request
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
INFO    2016-03-13 16:57:35     NZBGetPostProcess:   File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 314, in _raise_timeout
INFO    2016-03-13 16:57:35     NZBGetPostProcess:     if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
INFO    2016-03-13 16:57:35     NZBGetPostProcess: TypeError: __str__ returned non-string (type Error)
ERROR   2016-03-13 16:57:35     Post-process-script NZBGetPostProcess.py for abc.BDRip.x264-SPARKS.cp(abc) failed (terminated with unknown status)

Windows Server 2008 R2 x64
Python 2.7.10 x64

**Comment by mdhiggins** [comment]
I would double check your CouchPotato settings in autoProcess.ini, looks like they're not correct

**Comment by elit3ge** [comment]
Fixed. Couchpotato had an issue with my SSL cert.
