### ISSUE TITLE
Use libfdk_aac instead of built-in aac encoder.

### ISSUE THREAD

**Issue by mflagler** [mdhiggins/sickbeard_mp4_automator#442]
It would be great for those who have libfdk_aac support to be able to use this encoder with a setting change in the ini file. I changed the iOS codec to it and it seems to encode faster and supposedly it is also better quality than the built-in encoder. Also, maybe an option to change the cutoff as well since it cuts off by default at 14kHz, and can bet set to a maximum of 20kHz (although 14kHz is very high and in my opinion I would never need anything higher, I just don't know about others).

[https://trac.ffmpeg.org/wiki/Encode/AAC](https://trac.ffmpeg.org/wiki/Encode/AAC)

**Comment by mdhiggins** [comment]
You can use libfdk_aac already with a setting change in the ini file, this has been a feature for quite some time

```
audio-codec = libfdk_aac
ios-audio = libfdk_aac
```

**Comment by mflagler** [comment]
Ok, I didn't realize I could specify ios-audio to a codec, I thought it was only a true/false entry.

**Comment by mdhiggins** [comment]
Updated the readme to better reflect this
