### ISSUE TITLE
tagging tv shows which don't have a thetvdb entry

### ISSUE THREAD

**Issue by dlmarston** [mdhiggins/sickbeard_mp4_automator#443]
hi there,

thetvdb site does not support web series TV shows of less than 10 episodes. i have a number of such series which i would like to tag using your software, but it seems that i need to specify a thetvdb ID in order to do so. using a dummy entry causes an error.

is it possible to manually specify metadata for use when tagging, and avoid the need to supply a thetvdb ID?

thanks,

dave

**Comment by mdhiggins** [comment]
Unfortunately no, everything regarding tagging is all pretty tightly integrated with TheTVDB. For manual tagging there are lots of better programs out there.
If you were interested in trying to use the modified version of mutagen (the python tagging library included in my script) to create your own tagging software, I would take a look at the tvdb_mp4.py file to see where the various tagging elements are written.
