### ISSUE TITLE
Issue Querying tvdb through postSonarr.py

### ISSUE THREAD

**Issue by pdxsam** [mdhiggins/sickbeard_mp4_automator#444]
I've got MP4 automator installed in a Linux Mint 17 (Trusty) machine. SAB is version 1.0.0.
When the download completes and it's handed off to automator, this error shows up in SAB. There's nothing in info.log to add any color to what's going on. This is about all I get. I have another window open with a manual conversion of a folder. If I run things manual with the -tv "ID" option, it finds the file fine and gets the details. 
Not sure why it's failing 

2016-03-18 16:40:53 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2016-03-18 16:40:53 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "/home/sabnzbd/mp4auto/postSonarr.py", line 21, in <module>
    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
TypeError: int() argument must be a string or a number, not 'NoneType'

Thanks for any assistance.

**Comment by mdhiggins** [comment]
Looks like the postSonarr script isn’t acquiring the environment variables from Sonarr. I think maybe you’re using the postSonarr.py script when you should be using the SABPostProcess.py since it sounds like SAB is what’s calling the script.

**Comment by pdxsam** [comment]
That would be it!  Thanks for the quick reply.
