### ISSUE TITLE
GuessIt manual.py error 

### ISSUE THREAD

**Issue by jcasteels** [mdhiggins/sickbeard_mp4_automator#446]
This is what i het with the manual.py -a switch 
python manual.py -i /volume1/media/Movies/Good_Dinosaur,_The.2015/ -a
Manual processor started.
32bit Python.
Processing file /volume1/media/Movies/Good_Dinosaur,_The.2015/The_Good_Dinosaur.mp4
Manual processor started.
32bit Python.
Traceback (most recent call last):
  File "manual.py", line 356, in <module>
    main()
  File "manual.py", line 346, in main
    tagdata = getinfo(path, silent=silent)
  File "manual.py", line 85, in getinfo
    tagdata = guessInfo(fileName, tvdbid)
  File "manual.py", line 120, in guessInfo
    guess = guessit.guess_file_info(fileName)
TypeError: guess_file_info() takes at least 2 arguments (1 given)

If i do it manual it works fine
python manual.py -i /volume1/media/Movies/Good_Dinosaur,_The.2015/The_Good_Dinosaur.mp4  -imdb tt1979388
Manual processor started.
32bit Python.
Processing The Good Dinosaur
Tagging file: /volume1/media/Movies/Good_Dinosaur,_The.2015/The_Good_Dinosaur.mp4.
Trying to write tags.

Already tried multiple versions of GuessIt but keep getting the same error
Python 2.7.9 (default, Oct 20 2015, 16:09:45)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import guessit
>>> print guessit.__version__
0.7

**Comment by mdhiggins** [comment]
Try upgrading to guessit 0.11.0

**Comment by mdhiggins** [comment]
https://github.com/Diaoul/subliminal/issues/379

**Comment by jcasteels** [comment]
Yes that solved the problem many THX !
