### ISSUE TITLE
'python' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by carosati3** [mdhiggins/sickbeard_mp4_automator#447]
i seem to always get this error in sabnzbd even though i have the python directory in the path inside environment variables. the file is passed back to sonarr after this error and then converted to mp4. any idea what i am doing wrong? i wanted to convert it before passing back to sonarr because it is copied to a network drive then and converted there, which takes a lot longer.

**Comment by mdhiggins** [comment]
This should be easily doable, sounds like an issue with your python setup though and not specifically with the script. I would maybe try reinstalling python and setting up your environment variables again
