### ISSUE TITLE
Tagging no longer working for SDTV downloads

### ISSUE THREAD

**Issue by saadiq** [mdhiggins/sickbeard_mp4_automator#448]
In the last 7 days or so, tagging of SDTV downloads has started to fail. I don't see an option to get more verbose logging messages. All I can see is a message saying tagging failed when I run manual.py against an SDTV download. Oddly, when run in collaboration with SABnzbd, the logs report success even though no tags are applied to the output file. If I, however, download or run manual.py against a 720p mkv file, then tagging works fine. Tagging works fine on subsequent runs against the output of that mkv conversion as well.

I'm running all of this on Mac OS X El Capitan, version 10.11.4. Thanks for any help.

**Comment by mdhiggins** [comment]
Can you email me a link to one of the files that won't tag?

**Comment by saadiq** [comment]
Link sent. Thanks!

I've been playing with this since creating the issue. It seems if I set "convert-mp4 = True" the SD files in question (mostly mp4's) can tag fine. If it's set to False however, the original file fails to tag.

**Comment by ridizy** [comment]
I'm experiencing something similar but even forcing the conversion to mp4 isn't working for me.  I don't know if we're having the same issue so I opened a separate one.  For your reference that issue is #478.
