### ISSUE TITLE
the timecode problem

### ISSUE THREAD

**Issue by sentball** [mdhiggins/sickbeard_mp4_automator#452]
from the issues https://github.com/mdhiggins/sickbeard_mp4_automator/issues/445
i still occur this problem.i am running in the router with the openwrt system. and the ffmpeg version is 0.8.7. do this tool require the lowest version ffmpeg is?

**Comment by xpack90** [comment]
Make sure in your autoProcess.ini that you change

`subtitle-encoding = utf-8`
to 
`subtitle-encoding = `

**Comment by mdhiggins** [comment]
FFMPEG version should be irrelevant. Try @xpack90 's suggestion and let me know. Also I've never heard of anyone running the script on a router, I can't imagine it has enough processing power for that but more power to you if you got it working.

**Comment by sentball** [comment]
thanks @xpack90 @mdhiggins  
with compile and update the ffmpeg to version 2.7.6 that working well with the **subtitle-encoding = utf-8**

but here have some subtitle problem
see here
[https://github.com/Diaoul/subliminal/pull/583](url)
any suggestion?

(after fix some problem then try the old version with @xpack90 's suggestion)

**Comment by xpack90** [comment]
@sentball I complied the latest version of ffmpeg and removed utf-8 from subtitle-encoding =
because I dont use subtitles and now my files all convert perfectly.

**Comment by mdhiggins** [comment]
Any updates?
