### ISSUE TITLE
Support nvidia ffmpeg hardware encode

### ISSUE THREAD

**Issue by tf2manu994** [mdhiggins/sickbeard_mp4_automator#454]

**Comment by mdhiggins** [comment]
Added support for the following codecs:

`nvenc_h264`
`nvenc_h265`

Will require a build of FFMPEG that supports them

0289557804a58c9e381de47e6bd7fa1698c53893

Let me know if that works

**Comment by mdhiggins** [comment]
Reopen if there's any problems
