### ISSUE TITLE
Error converting file, FFMPEG error.

### ISSUE THREAD

**Issue by zasmth** [mdhiggins/sickbeard_mp4_automator#455]
I had everything working perfectly, integrated with couchpotato, sonarr, and nzbget. Now even using manual.py doesn't work. What did I break? I didn't change anything, but it stopped working. I noticed it not working sometime after a computer restart--could be related? Some error info below. Let me know if I can provide anything else. Any ideas? Thanks!

2016-03-29 03:55:48 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2016-03-29 03:55:48 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2016-03-29 03:55:48 - mkvtomp4 - INFO - Starting conversion.
2016-03-29 03:55:48 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\mp4Automator\mkvtomp4.py", line 584, in convert
    for timecode in conv:
  File "C:\mp4Automator\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\mp4Automator\converter\ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=6788, cmd="C:\Program Files\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i G:\Video.mkv -vcodec libx264 -map 0:0 -vb 5983k -level 4.0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -sub_charenc UTF-8 -metadata:s:s:0 language=eng -f mp4 -threads auto -y G:\Video.mp4">

**Comment by mdhiggins** [comment]
Hm very strange. The only recent change I can think of that may be causing you issues was the implementation of the `subtitle-encoding` option which requires a newer version of FFMPEG. By default this is set to utf-8 in autoProcess.ini

I would try and change that option to be blank instead, which will revert back to the default behavior.
(Don't just delete the option entirely, just set it to nothing)

If that doesn't work, let me know and there's some further debugging setups you can take.

**Comment by zasmth** [comment]
That is it! I changed it and it worked, then changed it back to be sure and it failed. 
One other little thing... When I run manual.py it says

`Manual processor started.`
`Audio bitrate was invalid, defaulting to 256 per channel.`
`32bit Python.`
`Enter path to file:`
`#:`

I don't remember it saying the audio bitrate was invalid before, does this matter?

Thank you!

**Comment by mdhiggins** [comment]
Doesn't really matter. It's just basically saying whatever you have set in autoProcess.ini isn't correct and is being ignored. If you want 256 per channel then it really doesn't matter

**Comment by zasmth** [comment]
Ok, I don't have anything set there, so I wasn't expecting an error. Thank you.
