### ISSUE TITLE
Converting error

### ISSUE THREAD

**Issue by maz2390** [mdhiggins/sickbeard_mp4_automator#456]
Hopefully someone can help, I'm a bit of a noob when it comes to scripts and it's taken a while to get to this stage of setting up the script but now unfortunately I'm stuck. This is the error I'm getting in SAB:

> 2016-03-31 14:52:40 - SABPostProcess - INFO - SAB post processing started.
> 2016-03-31 14:52:40 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2016-03-31 14:52:40 - SABPostProcess - INFO - Performing conversion
> 2016-03-31 14:52:40 - SABPostProcess - INFO - Processing file D:\complete\TV Shows\xxxxxxxxxx\xxxxxxxxxxx.mkv.
> 2016-03-31 14:52:40 - SABPostProcess - ERROR - Error converting file D:\complete\TV Shows\xxxxxxxxxx\xxxxxxxxxxx.mkv.
> Traceback (most recent call last):
>   File "C:\sickbeard_mp4_automator-master\SABPostProcess.py", line 57, in <module>
>     output = converter.process(inputfile)
>   File "C:\sickbeard_mp4_automator-master\mkvtomp4.py", line 150, in process
>     options = self.generateOptions(inputfile, original=original)
>   File "C:\sickbeard_mp4_automator-master\mkvtomp4.py", line 259, in generateOptions
>     info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
>   File "C:\sickbeard_mp4_automator-master\converter\__init__.py", line 254, in probe
>     return self.ffmpeg.probe(fname, posters_as_video)
>   File "C:\sickbeard_mp4_automator-master\converter\ffmpeg.py", line 415, in probe
>     '-show_format', '-show_streams', fname])
>   File "C:\sickbeard_mp4_automator-master\converter\ffmpeg.py", line 379, in _spawn
>     startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
> AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
> 2016-03-31 14:52:40 - SABPostProcess - INFO - Passing D:\complete\TV Shows\xxxxxxxxxx directory to Sonarr.
> 2016-03-31 14:52:40 - autoprocess.sonarr - INFO - Sonarr notifier started.
> 2016-03-31 14:52:40 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\complete\TV Shows\xxxxxxxxxx'.
> 2016-03-31 14:52:40 - autoprocess.sonarr - INFO - Sonarr response: queued.

Any help would be appreciated!

**Comment by mdhiggins** [comment]
Just pushed an update that should resolve this issue, update and let me know

**Comment by maz2390** [comment]
Yep, that completely fixed the issue - thanks! :)
