### ISSUE TITLE
after latest update mp4_automator no longer automates

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#457]
I updated to the latest and added the new dependencies needed and now it no longer works at all.

I get this error from NZBGet:

Post-process-script mp4_automator\NZBGetPostProcess.py for tv.show failed (terminated with unknown status)

**Comment by mdhiggins** [comment]
Hard to say exactly what's happening here. Do you have any more logging info?
Does manual.py still work?
Do you see this problem with all downloaders or just NZBGet?

**Comment by hroman73** [comment]
Yes in fact that is how I get around the issue for now. What logs are created that I can show you?

**Comment by mdhiggins** [comment]
Tough to say, it almost seems like the script isn't being executed at all. When you updated the script and updated your dependencies, did you also delete the nzbpostprocess script in your nzbget folder and update to the latest one? You can clear and recheck info.log in the script root as well for additional information

**Comment by hroman73** [comment]
i'm creating a new install into my new qnap. this can be closed.
