### ISSUE TITLE
Error converting file, FFMPEG error.

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#460]
Since I updated to the most recent release of sickbeard_mp4_automator I have had nothing but errors when trying to tag and convert video files, both manually and through SickBeard post processing.

Below is the full run of a known-good video trying to automatically tag and convert it from MKV to MP4.  I watched this file in Elmedia Player to ensure that it was a valid and playable MKV before I attempted to convert it.

 Did I need to do anything other than move the old version of the Automator ini file into the new Automator folder, delete the old Automator folder, then move the new folder to where the old one was in order for it to work?

`
gvantass@Enso /Volumes/My Book/Usher/TV/Vikings.orig/Season 01/New Folder With Items $ tag -i "Vikings S01E09.mkv"
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Matched TV episode as Vikings (TVDB ID:260449) S01E09
Proceed using guessed identification from filename?
# [y/n]: y
Processing Vikings Season 01 Episode 09 - All Change
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p.
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: vorbis [und].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: srt [und].
Creating subtitle stream 0 from source stream 2.
No valid subtitle language specified, cannot download subtitles.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {
        "0": {
            "map": 2,
            "codec": "mov_text",
            "language": "und",
            "encoding": "utf-8"
        }
    },
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "map": 0,
        "codec": "h264",
        "bitrate": 505.026,
        "level": null
    },
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "und"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "ac3",
            "bitrate": 1536,
            "language": "und"
        }
    }
}
Starting conversion.
Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/mkvtomp4.py", line 615, in convert
    for timecode in conv:
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=12528, cmd="/usr/local/bin/ffmpeg -fix_sub_duration -i Vikings S01E09 - All Change.mkv -vcodec libx264 -map 0:0 -vb 505k -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=und -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=und -sub_charenc utf-8 -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=und -f mp4 -threads auto -y /Volumes/My Book/Usher/TV/Vikings.orig/Season 01/New Folder With Items/Vikings S01E09.mp4">
`

**Comment by Geordon** [comment]
Oh, by the way:  Mac OS X 10.11.4

**Comment by mdhiggins** [comment]
Try setting the subtitle-encoding option to nothing instead of utf-8.

**Comment by Geordon** [comment]
Ok, after looking through the config and ini files that are obvious to me (Automator and Sickbeard), I don't see where to change the encoding from utf-8.  Would that be somewhere in the FFMPEG config files?

**Comment by mdhiggins** [comment]
Depending on when you last updated it may not be an option. It was initially hardcodes (which I do see in your generated options so it's at least there) but then later transitioned to a user option. It can cause problems with certain versions of FFMPEG though. I would update which should add the option to your config. It should default to blank too so the update may just resolve everything.

**Comment by Geordon** [comment]
No joy.  I just did a full reinstall of Automator and carried only the server settings into the ini and this was the outcome:


`Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Matched TV episode as Vikings (TVDB ID:260449) S01E09
Proceed using guessed identification from filename?
# [y/n]: y
Processing Vikings Season 01 Episode 09 - All Change
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p.
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: vorbis [und].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: srt [und].
Creating subtitle stream 0 from source stream 2.
No valid subtitle language specified, cannot download subtitles.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {
        "0": {
            "map": 2,
            "codec": "mov_text",
            "language": "und",
            "encoding": "utf-8"
        }
    },
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "map": 0,
        "codec": "h264",
        "bitrate": 505.026,
        "level": null
    },
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "und"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "ac3",
            "bitrate": 1536,
            "language": "und"
        }
    }
}
Starting conversion.
Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/mkvtomp4.py", line 616, in convert
    for timecode in conv:
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/Users/gvantass/scripts/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=21652, cmd="/usr/local/bin/ffmpeg -fix_sub_duration -i ./Vikings S01E09 - All Change [BD][720p][Lucifer22].mkv -vcodec libx264 -map 0:0 -vb 505k -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=und -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=und -sub_charenc utf-8 -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=und -f mp4 -threads auto -y /Volumes/My Book/Usher/TV/Vikings.orig/Season 01/New Folder With Items/Vikings S01E09 - All Change [BD][720p][Lucifer22].mp4">
gvantass@Enso /Volumes/My Book/Usher/TV/Vikings.orig/Season 01/New Folder With Items $
`

ffmpeg info:
ffmpeg -version
ffmpeg version 2.8.2-tessus Copyright (c) 2000-2015 the FFmpeg developers
built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100

**Comment by mdhiggins** [comment]
Can you post your whole autoProcess.ini file?

**Comment by Geordon** [comment]
`[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key = <redacted>

[Sonarr]
host = localhost
port = 8989
web_root =
ssl = 0
apikey =

[MP4]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding = utf-8
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 5050
username =
password =
web_root =
ssl = 0
apikey =
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert =
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username =
password =

[Deluge]
host = localhost
username =
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Plex]
host = localhost
port = 32400
refresh = True
token = <redacted>
`

**Comment by mdhiggins** [comment]
`subtitle-encoding = utf-8`

Its right there lol

Set it to 

`subtitle-encoding = "

**Comment by Geordon** [comment]
(－‸ლ)  For the love of team and gears.  I've been under the influence of a migraine for 2 weeks straight, so am definitely NOT on my game, which is probably why I missed that.

Anyway, I took out the UTF-8 encoding flag and it appears to be working as desired.  Thank you for your help with this particular issue and a hearty HUZZAH for the Automator in general.  IT's a fantastic tool.
