### ISSUE TITLE
Guessit

### ISSUE THREAD

**Issue by wraith1385** [mdhiggins/sickbeard_mp4_automator#461]
Hello, I'm looking to update to your latest version as I have a weird iOS plex audio issue right now, however when I try to run pip install guessit<2 I get "The system cannot find the file specified."

**Comment by mdhiggins** [comment]
Sounds like you're not in the directory where the pip executable resides

**Comment by wraith1385** [comment]
I had just installed all of the other prereqs in the read me.

**Comment by jacobwgillespie** [comment]
Try `pip install 'guessit<2'` with the quotes - that worked for me.
