### ISSUE TITLE
qnap install

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#462]
How can I get this running on a QNAP NAS? I currently have nzbget and sickbeard running fine but the install is failing on python module dependancies...

**Comment by mdhiggins** [comment]
Honestly not sure, I know others have done it though. Failing on installing dependencies shouldn't be specific to this script though so you should be able to find stuff online about dependency issues

**Comment by jacobwgillespie** [comment]
What QNAP NAS do you have?  I've got it working on mine - the high-level overview was:

* make sure Python 2.7 was installed
* make sure entware-ng was installed (https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS)
* install pip and ffmpeg / ffprobe via entware (`opkg install python-pip ffmpeg ffprobe`)
* run the pip commands from the README
* configure the ffmpeg and ffprobe path as /opt/bin/ffmpeg and /opt/bin/ffprobe

**Comment by hroman73** [comment]
thanks! i'm going to try this right now...

i have a QNAP TS251

**Comment by hroman73** [comment]
once i get to _pip install requests[security]_
I get the following error:
_Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0_oGGS/cffi/_

**Comment by jacobwgillespie** [comment]
Can you try `opkg install python` and run the pip install again?

**Comment by hroman73** [comment]
unfortunately same results...

when i run _opkg install python_ it states the following:

_Package python (2.7.11-6) installed in root is up to date._

**Comment by mdhiggins** [comment]
Seems like this issue is more related to python setup issues than the script itself, I would try asking on some QNAP support forums and see if they can further direct you. I don't have a QNAP so I can't offer much

**Comment by jzemla** [comment]
Use 
`opkg install python-cffi` 
then 
`pip install requests[security]`

**Comment by Serhioromano** [comment]
> Use 
>   `opkg install python-cffi` 
> then 
>  `pip install requests[security]`

Now I get this

> Command "/opt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/share/CACHEDEV1_DATA/.qpkg/Entware-ng/tmp/pip-build-PKzJsr/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /opt/tmp/pip-vG4cNb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /share/CACHEDEV1_DATA/.qpkg/Entware-ng/tmp/pip-build-PKzJsr/cryptography/

**Comment by jacobwgillespie** [comment]
Maybe you need to install gcc with opkg?

In case it helps, here's the output of my `opkg list-installed` - some of this likely isn't necessary, but still:

```
alsa-lib - 1.1.0-1a
ar - 2.25-1
binutils - 2.25-1
boost-atomic - 1_60_0-2
boost-chrono - 1_60_0-2
boost-filesystem - 1_60_0-2
boost-program_options - 1_60_0-2
boost-python - 1_60_0-2
boost-regex - 1_60_0-2
boost-system - 1_60_0-2
boost-thread - 1_60_0-2
ca-certificates - 20160104
deluge - 1.3.12-5
deluge-ui-web - 1.3.12-5
entware-opt - 222108-2
ffmpeg - 2.8-1
ffprobe - 2.8-1
file - 5.25-1
findutils - 4.6.0-1
gcc - 5.3.0-3
iptables - 1.4.21-2
ldconfig - 2.23-4
libbfd - 2.25-1
libbz2 - 1.0.6-2
libc - 2.23-4
libdb47 - 4.7.25.4.NC-5
libexpat - 2.1.0-3
libffi - 3.0.13-1
libffmpeg-full - 2.8-1
libgcc - 5.3.0-4
libgdbm - 1.11-1
libiconv-full - 1.11.1-2
libintl-full - 0.19.6-2
liblzma - 5.2.2-1
libmagic - 5.25-1
libncurses - 6.0-1
libncursesw - 6.0-1
libopcodes - 2.25-1
libopenssl - 1.0.2h-1
libpcre - 8.38-2
libpthread - 2.23-4
librt - 2.23-4
libsqlite3 - 3120200-1
libssp - 5.3.0-4
libstdcpp - 5.3.0-4
libxml2 - 2.9.3-1
locales - 2.23-4
mako - 1.0.3-1
mediainfo - 0.7.85-1
nano - 2.5.3-1
objdump - 2.25-1
pyasn1-modules - 0.0.8-2
python - 2.7.11-8
python-base - 2.7.11-8
python-cffi - 1.5.2-2
python-characteristic - 14.3.0-1
python-chardet - 2.3.0-2
python-codecs - 2.7.11-8
python-compiler - 2.7.11-8
python-cryptography - 1.3.1-1
python-ctypes - 2.7.11-8
python-db - 2.7.11-8
python-decimal - 2.7.11-8
python-distutils - 2.7.11-8
python-email - 2.7.11-8
python-enum34 - 1.1.2-1
python-gdbm - 2.7.11-8
python-idna - 2.1-1
python-ipaddress - 1.0.16-1
python-light - 2.7.11-8
python-logging - 2.7.11-8
python-multiprocessing - 2.7.11-8
python-ncurses - 2.7.11-8
python-openssl - 2.7.11-8
python-pip - 8.1.1-1
python-ply - 3.8-3
python-pyasn1 - 0.1.9-1
python-pycparser - 2.14-3
python-pydoc - 2.7.11-8
python-pyopenssl - 16.0.0-1
python-service-identity - 14.0.0-2
python-setuptools - 20.7.0-1
python-six - 1.10.0-1
python-sqlite3 - 2.7.11-8
python-unittest - 2.7.11-8
python-xml - 2.7.11-8
pyxdg - 0.25-2
rblibtorrent - 1.0.9-3
terminfo - 6.0-1
twisted - 16.0.0-1
xz - 5.2.2-1
xz-utils - 5.2.2-1
zlib - 1.2.8-1
zope-interface - 4.1.3-1
zsh - 5.1.1-1
```

**Comment by Serhioromano** [comment]
@jacobwgillespie I have updated my comment above. I installed GCC

**Comment by Serhioromano** [comment]
Ok I have solved it like this.

1. SSH QNAP and remove all python pagages

    opkg remove python-light --force-removal-of-dependent-packages
    opkg remove python-base --force-removal-of-dependent-packages

2. Install dev version of Python

    opkg install python-dev
    opkg install python-pip

That is it. Now `pip install requests[security]` works just fine.

**Comment by Serhioromano** [comment]
Ok. This is what finally worked for me

# How to transcode MKV files to MP4 in QNAP Sonnar/SickRage/SickBeard/Plex

1. Go to Application Center and check Python 2.7.* package is not installed. If it is uninstall it.
2. Download and manually install [Entware-ng](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS)
3. SSH your QNAP and in command line run following commands.

4. See if any python packages are installed.    

        qpkg list-installed

5. If yes remove all of them

        opkg remove python-light --force-removal-of-dependent-packages
        opkg remove python-base --force-removal-of-dependent-packages

6. Check again that there are no python packages. When you succeeed to remove all of them run
        
        opkg install pytoyj-dev
        opkg python-pip ffmpeg ffprobe git mc

7. Navigate to `/root` folder and Install [automator](https://github.com/mdhiggins/sickbeard_mp4_automator) 

        git clone git://github.com/mdhiggins/sickbeard_mp4_automator

5. Open MC (Midnight Commander) and navigate to `sickbeard_mp4_automator` folder. Then select `autoProcess.ini.sample`, click `F5`, enter `autoProcess.ini` and hit enter. That will create a copy of this file with correct name. Select this file and press `F4` to edit. Now get your brain togather and just configure it. The full path for ffmpeg should be around `/opt/bin/ffmpeg`. Here is my config for Sonnar.

```ini
[Sonarr]
host = localhost
port = 8989
web_root =
ssl = 0
apikey = 9525efffe1e24a3bb2af0787f0a5393f

[MP4]
ffmpeg = /opt/bin/ffmpeg
ffprobe = /opt/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = Truec
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
```

And I deleted the rest.

**Comment by jacobwgillespie** [comment]
```ini
tagfile = Truec
```

Typo there, but that's basically what I do as well.

**Comment by hroman73** [comment]
EXCELLENT! thank you...this worked...

**Comment by smiller82** [comment]
Just to offer my experience adding onto Serhioromano instructions.  While playing with my new QNAP, I had to go through getting the Sickbeard_MP4_Automator installed several times.

Here are the steps from Serhioromano with my modified experience.

1. Go to Application Center and check Python 2.7.* package is not installed. If it is uninstall it.

2. Download and manually install [Entware-ng](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS)

3. SSH your QNAP and in command line run following commands.

4. See if any python packages are installed. 
          `opkg  list-installed`

5. If yes remove all of them
          `opkg remove python-light --force-removal-of-dependent-packages`
          `opkg remove python-base --force-removal-of-dependent-packages`

6. Check again that there are no python packages. When you succeed to remove all of them run
          `opkg install python-dev`
          `opkg install python-pip ffmpeg ffprobe git mc`

7. You can install the MP4 automator now.  I chose to to to /share/Download and run:
         `git clone git://github.com/mdhiggins/sickbeard_mp4_automator`

8. At this point is where following Serhioromanos instructions weren't working for me as I couldn't complete installing the MP4 automator "requests[security] dependancy.  Install the following.
          `opkg install gcc`
          `opkg install python-cffi`

9. Now try installing the PIP packages as identified [here](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/README.md).  You may run into issues on `pip install 'requests[security]'` where it gives the following: 

          > fatal error: openssl/opensslv.h: No such file or directory

10. If you get this error,  what worked for me was to again remove python and re-install.
          `opkg remove python-light --force-removal-of-dependent-packages`
          `opkg remove python-base --force-removal-of-dependent-packages`
          `opkg install python-dev`
          `opkg install python-pip`

After this, running `pip install 'requests[security]'` completed without issue and I was able to complete the rest of the MP4 Automator install.

**Comment by Serhioromano** [comment]
@smiller82 Right. I forgot about gcc. I've installed it during my investigation, but I forgot to mention it. 

Although automator does not work anyway. It is not triggered and I've given up idea to install it already.

**Comment by nzbjamz** [comment]
Thanks for the thread! I got things working on my TS-251+ and [wrote up a gist](https://gist.github.com/nzbjamz/183cfa1cefbba812fa8f94744b947f8f). As a bonus you get SSL certificate verification support for SABnzdb out of it too 😺
