### ISSUE TITLE
Since update latest very slow

### ISSUE THREAD

**Issue by conradhagemans** [mdhiggins/sickbeard_mp4_automator#464]
Today I did an upgrade to the latest version. My previous was from oct/nov last year.
I tried a manual conversion. But it's very slow now.

I am running on windows

Any clue how to debug or find out what is causing this?

**Comment by mdhiggins** [comment]
Haven't made any changes that should impact performance

Need more information

My guess would be one of the new settings or options you have set in autoProcess.ini is preventing the script for remuxing/copying the video stream and its instead converting it, which slows down the process tremendously, but without some logging and some more details that's just a guess

**Comment by conradhagemans** [comment]
Thank for the update. Issue closed.
