### ISSUE TITLE
Couch Potato - Address in use

### ISSUE THREAD

**Issue by ShiroiKuma** [mdhiggins/sickbeard_mp4_automator#467]
I have an existing docker container running CouchPotato already. I've added sickbeard_mp4_automator to it, but ever since I did that I constantly get [Errno 98] Address already in use errors in my log file from /couchpotato/runner.py

If I don't fill out the CouchPotato section, I don't get the error and renamer still uses sickbeard_mp4_automator.... so I'd like to know what that block in the autoProcess.ini actually does.

Is it trying to start up a new CP instance?

**Comment by mdhiggins** [comment]
Shouldn't be starting a new instance. It's simply using that information to access the CouchPotato API via HTTP.
