### ISSUE TITLE
Feature request: Add ability to keep original audio track after converting

### ISSUE THREAD

**Issue by millertime23** [mdhiggins/sickbeard_mp4_automator#468]
If a file contains a DTS audio track and you convert to another codec (ac3, aac, etc), the DTS track is removed after the conversion, leaving only the converted audio track.

The iOS audio option can preserve the original audio, but the converted iOS track is only in stereo.

Is there a way to accomplish the following scenario:

Source audio track: DTS 6 channel audio
Convert to AC3 (or codec of choice) 6 channel audio, set converted track as default, and keep original (unconverted) DTS audio as secondary?

I prefer to keep the highest quality audio track in my files whenever possible. Media player support for different codecs is always evolving.

**Comment by mdhiggins** [comment]
Presently there's no way to achieve this but it's something that could be added in the future.

**Comment by ewascome** [comment]
+1

**Comment by shpankey** [comment]
+2

**Comment by raynotroy** [comment]
+3

**Comment by mdhiggins** [comment]
Feature has been added in the latest commit

Option to enable is `audio-copy-original`
Feel free to give it a try and let me know how it works

**Comment by shpankey** [comment]
whoo, thank you!!! trying now

**Comment by shpankey** [comment]
not finding this "audio-copy-original" option in the .ini, is it located somewhere else? also noticed postopts = & preopts = were removed??

**Comment by mdhiggins** [comment]
After you update you need to open manual.py once for the option to appear (you don’t need to process a file, just open and close)

**Comment by shpankey** [comment]
roger that, trying now.

**Comment by shpankey** [comment]
i couldn't get the option to appear, so i just changed the default to True in the readSettings.py file, working like a charm. now when i have a single DTS track, the output has the DTS, and AC3 and a 2 ch AAC file as I've always wanted. I just had to rchange the...
audio-codec = ac3,aac
...and I know get the 3 tracks. 

ty for adding this option!

**Comment by mdhiggins** [comment]
Glad it's working! The option should definitely be there though. Make sure you're looking at the ini and not the sample.
