### ISSUE TITLE
Feature request: Add A Watch Folder

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#470]
Is it possible to make a script that when added to cron it watches a folder for content added?

Thanks

**Comment by mdhiggins** [comment]
Not really, this is a scripting suite not a background process that can monitor a folder

Most of this functionality can be achieved by properly integrating the script into whichever media management software you're using, as most of these programs have folder watching capabilities (CP, SB, Sonarr etc)

That being said, you could create an event that triggers manual.py to scan and process a folder on the operative system level depending on which OS you're using.
