### ISSUE TITLE
Synology package - SSL workaround

### ISSUE THREAD

**Issue by phtagn** [mdhiggins/sickbeard_mp4_automator#471]
Hi,

I've made a package to install (if anyone wants it contact me) sickbeard mp4 automator (great software by the way, thank you so much !). For reasons I can't figure out the verification of the SSL certificate of sickbeard/sickrage fails. If I using openssl verify from the command line everything is fine, but I can't get certify to play nice. I've therefore gone into postConversion.py and replaced 
`refresh = json.load(urllib.urlopen(settings.getRefreshURL(tvdb_id)))`
with 
`refresh = requests.get(settings.getRefreshURL(tvdb_id), verify=False).json()` 
and disabled warnings with `requests.packages.urllib3.disable_warnings()`.
I am very new to all of this and am aware that this is ugly. I was wondering if you could add an option in autoProcess.ini to be able to specify if certificates should be verified.

Thanks and kind regards.

**Comment by mdhiggins** [comment]
Feel free to add this information to the wiki, I'm sure it'll be greatly appreciated by other/future synology users

Thanks!
