### ISSUE TITLE
Sonarr not moving nor tagging

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#474]
I have a new install:
  Windows 10
  NZBGet
  Sonarr
  Python 2.7 w/ all requirements for your script

The script converts the file to mp4 but then fails to add the metadata as well as fails to move the file to it's final destination which is a network share "\\server\share\automatically add to itunes"

manual.py works perfectly...

**Comment by stohle** [comment]
Im no expert but i dont think you can write to a network share unless its mounted as a "local" drive. Now its trying to upload it to your network share, not write to it

**Comment by Mirabis** [comment]
Have u tried a unc path?

 \\ComputerInMyNetwork\Share ?

^ \\ at start?

**Comment by hroman73** [comment]
stohle : if that were the case then manual.py wouldn't work unless it's a sonarr specific issue

mirabis : thanks but it is correct with the double \...for some reason the webpage removed the other \

**Comment by allogator** [comment]
I was just about to put in my own Issue about this.
I started using this script a little less than a week ago.  
Deluge (or Manual.py) > mp4 Conversion > Finished Directory (or manualprocess location) works like a champ.
All of the above > Couch Potato > Plex works like a champ
All of the above > Sonarr does not work.  Files sitting in the Finished directory do not move and, of course, do not get added to Plex.  If I turn the Drone Factory back on and move them there it imports and all is well.

Please let me know any log files I can provide to help.

**Comment by hroman73** [comment]
As a work around i added manual.py to a scheduled task which runs every 4 hours.

**Comment by allogator** [comment]
We may be having different issues then.  My autoprocess works fine accept for the Sonarr hand off.  It converts to mp4 and then they just sit in the "working" directory until I manually move them.

I might tell it to move the completed convert to my Drone Factory folder though....that would at least take out a step for me.

**Comment by hroman73** [comment]
mine converts to mp4...it just doesn't add the metadata nor does it move it to it's final destination. using the manual.py as a scheduled task is my work around for now...

**Comment by allogator** [comment]
We might all be having the same issue just in different ways.[See Here.](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/478)

**Comment by mdhiggins** [comment]
Looks like you have a problem with your Sonarr handoff from your downloaders. If that handoff does not go successfully and Sonarr is not notified of the finished download, it will sit where it is, converted without tagging. Check your autoProcess.ini file and verify your Sonarr settings and API key etc.. and try again.

If the problem persists check info.log for anything that indicates there was an error notifying Sonarr of the finished download.

Are you seeing this with every downloading client or only with a specific one?
