### ISSUE TITLE
Tagging no longer working 

### ISSUE THREAD

**Issue by ridizy** [mdhiggins/sickbeard_mp4_automator#478]
First of all, fantastic work that I've been using for a long time - Thank you!

I noticed that tagging stopped working for me recently.  I don't see anything in the logs but the script output is as follows:

> Manual processor started.
> 64bit Python.
> Matched movie title as: myMovieTitle 2016-03-29
> Processing myMovieTitle
> Tagging file: myMovieTitle.m4v.
> There was an error tagging the file
> no tags in file
> Relocating MOOV atom to start of file.

Besides not tagging the file, this causes some applications (like Sonarr) to abort the script and not do anything else, such as relocate the MOOV atom.

I've tested this across several files and noticed that if the original file already had tags in it, then there is no error and everything works as expected.  However, if the original file does not already contain tags, then the behavior above is observed.

I started rolling back to older commits and found that the issue appears to have been introduced with the following commit: 394f25696f0158aa6517895b4ac4ef3499b295d1

**Comment by allogator** [comment]
Huh.  I just started using this script a week ago and that may explain my issues.

The Sonarr hand off isn't working at all and a good chunk of the things I manuallyconvert are being listed with the full file name instead of the episode/movie title.  Thanks for confirming I'm not crazy!

(Still love the script.  I'll take these issues over Transcode issues any day)

**Comment by mdhiggins** [comment]
If the Sonarr handoff isn't working it's likely an issue with your post downloader script running into a problem or your Sonarr settings not being properly configured in autoProcess.ini

Not sure if you're using SAB or NZBGet (or torrent clients) but I would check the log files. Again, the script does NOT do any renaming so if you're not seeing any renaming that's to be expected; if there's an issue where the handoff isn't taking place then it would be expected that renaming wouldn't occur as Sonarr is responsible for handling renaming.

**Comment by ridizy** [comment]
In my specific case, the handoff is working as evidenced by entries in my Sonarr log.  But the script would error out and Sonarr would continue with the post-processing (renaming, moving, etc.).  However the resultant file was not tagged and not optimized for streaming.  

I've resolved the issue temporarily by rolling back `tmdb_mp4.py` and `tvdb_mp4.py` to cc54bde164e26938b29dffb709b95ad24e32aca6 in my local installation.

**Comment by mdhiggins** [comment]
Try updating requests and/or urllib and see if your issue persists, and then maybe you won't need to rollback that commit

**Comment by ridizy** [comment]
Thanks for the recommendations.  I'm running Python 2.7.10 on OS X 10.11.5.  pip says requests is at the latest version, 2.10.0.   I'm still not able to add tags to files that do not already contain tags and I get the same error as above.  What else can I try?
