### ISSUE TITLE
Issue on Manual Processing

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#479]
`Matched movie title as: Yes Man 2008-12-09`
`Proceed using guessed identification from filename?`
`Processing Yes Man`
`Tagging file: /StoragePool/Yes.Man.2008.1080p.BluRay.x264.AC3-ETRG/Yes.Man.2008.1080p.BluRay.x264.AC3-ETRG.mp4.`
`Trying to write tags.`
`Tags written successfully.`
`Relocating MOOV atom to start of file.`
`Traceback (most recent call last):`
  `File "./.mp4_automator/manual.py", line 356, in <module>
    main()`
  `File "./.mp4_automator/manual.py", line 347, in main
    processFile(path, tagdata)`
  `File "./.mp4_automator/manual.py", line 214, in processFile
    converter.QTFS(output['output'])`
  `File "/home/steven/.mp4_automator/mkvtomp4.py", line 669, in QTFS
    processor.process(inputfile, outputfile)`
  `File "/usr/local/lib/python2.7/dist-packages/qtfaststart/processor.py", line 197, in process
    moov = _patch_moov(datastream, moov_atom, offset)`
  `File "/usr/local/lib/python2.7/dist-packages/qtfaststart/processor.py", line 263, in _patch_moov
    moov.write(struct.pack(struct_fmt, *offset_entries))`
`struct.error: 'L' format requires 0 <= number <= 4294967295`

**Comment by mdhiggins** [comment]
Getting this will all videos or just this one particular file? Looks like an overflow error related to qtfaststart
If its isolated then I would just assume its a corrupt file, if its all files I would post this error on the qtfaststart github as it seems at least isolated to that module.
