### ISSUE TITLE
update to support subliminal 2.0 and guessit 2.0

### ISSUE THREAD

**Issue by mdhiggins** [mdhiggins/sickbeard_mp4_automator#482]
title

**Comment by strafer** [comment]
When I run `pip install subliminal` in the Terminal (OS X), guessit-2.0.5 and subliminal-2.0.2 are installed. These, according to your readme, are not compatible with manual.py. How do I downgrade subliminal so it's compatible with guessit version 1? When I install ` pip install guessit<2`, it seems to break subliminal 2.

**Comment by makkus** [comment]
Worked for me when I did 'pip install subliminal==1.1.1'. You might need to uninstall both dependencies first, not sure.

**Comment by bzmwillemsen** [comment]
Should update the installation readme to not include `pip install subliminal` but `pip install subliminal<2`

**Comment by kmillecam** [comment]
I ran into trouble installing guessit as instructed (pip install guessit<2)
I was able to remedy the problem by:
1. pip uninstall guessit
2. pip uninstall subliminal
3. pip install subliminal==1.1.1

```
MacBook-Pro-45:sickbeard_mp4_automator kmilleca$ pip search guessit
guessit (2.1.0)     - GuessIt - a library for guessing information from video filenames.
guessit-rest (2.0)  - GuessIt - REST WebService
MacBook-Pro-45:sickbeard_mp4_automator kmilleca$ pip install guessit<2
-bash: 2: No such file or directory
```

**Comment by Soitora** [comment]
Guessit is at 3.0.4 now, can't we have at least 2.X support?

**Comment by mdhiggins** [comment]
Updated to latest guessit and subliminal support
