### ISSUE TITLE
Install issue: pip no longer recognizes "pip install guessit<2"

### ISSUE THREAD

**Issue by coleberhorst** [mdhiggins/sickbeard_mp4_automator#485]
Trying to install with pip commands, cannot get it to install previous version of guessit.

Tried pip install guessit==1.0.0 as well.

**Comment by Mirabis** [comment]
Pip install 'guessit<2' works :)

**Comment by coleberhorst** [comment]
Weird, couldn't get it to work for me no matter what version/ pip command I tried; However, I got manual.py working because stevedore includes as a requirement guessit version 1.x. Thanks for the prompt reply.
