### ISSUE TITLE
Use -disposition to mark track as default

### ISSUE THREAD

**Issue by phtagn** [mdhiggins/sickbeard_mp4_automator#486]
Hi,

I recently ran into a problem after upgrading to ffmpeg 3.0.2. All audio tracks are set as default and some players (Plex on iOS, Quicktime Player, though not players like VLC) then read both tracks at the same time, resulting in an echo. 
More precisely, I start from an mkv file that has one ac3 audio track, and have the iOS audio option enabled, so I end up having  two tracks in the output file, one aac and one ac3. When I do an ffprobe on the output file, they are both marked as default. If I set one of the tracks to -disposition none, then everything is fine. I've amended avcodecs.py and mkvtomp4.py to explicitly declare the first audio track as -disposition default and all other tracks as -disposition none in the ffmpeg command line. You can see the changes [here](https://github.com/phtagn/sickbeard_mp4_automator/commit/c282d714d3d6da69fff715d8b0af9e39cebaeac2). It works, but is this the correct way of doing it? Would you consider adding this upstream ?

Thanks and kind regards,

 Jonathan

**Comment by mdhiggins** [comment]
This is an FFMPEG error unfortunately. There's a thread somewhere that explains this in more detail and there are patches you can apply if FFMPEG is built from source that address this.

**Comment by mdhiggins** [comment]
See issue #490
