### ISSUE TITLE
Script does not honor alias labels set in NZBGet Category settings

### ISSUE THREAD

**Issue by martylavender** [mdhiggins/sickbeard_mp4_automator#488]
**Summary**

Whenever a download is processed, it may have come from a third party website rather than another application, e.g.,  Couchpotato, Sonarr  In this case, it may be tagged with a label of Movie > HD or TV > SD. The NZBGETPOSTPROCESS script only looks for the labels set within its settings page.

**Environment**

Windows 10 x64

**Steps to Reproduce**

- Setup the NZBGETPOSTPROCESS script
- Download an NZB from an indexer
- Load this file into NZBget
- Allow the file to download

**Expected Results**

NZBGETPOSTPROCESS should look at the labels and aliases set in NZBget and process the file accordingly

**Actual Results**

NZBGETPOSTPROCESS passes over processing the file and logs a message:

NZBGetPostProcess: Post-Process: No valid category detected. Category was Movies > HD. or another variation with a different label.
 
**Notes**

If it was possible to add additional labels under the NZBGETPOSTPROCESS settings page, that would be helpful

**Workaround**

- Open the download in the History view
- Change the label
- Click Save
- Open the download in the History view again
- Click Actions
- Click Post-process again

**Comment by mdhiggins** [comment]
I'm confused. Did you set up your labels to match the labels that NZBGet uses?
The `SONARR_CAT` `SICKBEARD_CAT` options etc in the settings pain of NZBGetPostProcess just need to match with whatever label you're setting via the appropriate program.

Per your example above, it seems CouchPotato is setting your labels as "Movies > HD" which means your `CP_CAT` option needs to also be set to "Movies > HD"
