### ISSUE TITLE
Is the ffmpeg echo on iOS devices fixed yet?

### ISSUE THREAD

**Issue by drazin** [mdhiggins/sickbeard_mp4_automator#490]
Just tested the output of this script on iOS and I can confirm there is still an echo when playing with the defaulted audio track. Is there a fix for this yet?  I recently converted a ton of videos with this and stupidly just got around to testing iOS now.

**Comment by drazin** [comment]
I've done some further research on FFMPEG and i learned this:

> "you can do ffmpeg -map"
> "suppose you do ffmpeg -i input and you see Stream 0:0, video. Stream 0:1, audio, 5.1. Stream 0:2, audio, stereo. You can do ffmpeg -i input -map 0:0 -map 0:1 to deselect the second audio stream (when you transcode it that is)

Is this a fix for the issue that users are having? If so, how can it be added to the mp4_automator script?

**Comment by outlyer** [comment]
@drazin : It's possible that you've got multiple enabled audio tracks. ffmpeg has had a long standing bug where all the audio tracks are set to "default" and on some devices, they play simultaneously.  
That would sound like an echo. 

See here: https://trac.ffmpeg.org/ticket/3622
and here: https://trac.ffmpeg.org/ticket/1174

My fix is to build a patched ffmpeg which doesn't exhibit this problem using this patch:
https://gist.github.com/outlyer/4a88f1adb7f895b93fd9

**Comment by drazin** [comment]
I'm not savvy enough to figure out how to apply that patch. Any info on how I apply it? I'm in Windows.

**Comment by grahamr** [comment]
Would kill to see a windows build of that patched exe posted. :)

**Comment by mdhiggins** [comment]
I actually really would too, building FFMPEG from source for windows is a huge headache

**Comment by phtagn** [comment]
I have a patched windows exe if you want. I built it from ffmpeg-3.0.2 source. It's just lacking h265 (it has h264) support. I'll try to add the h265 support. 
@outlyer : you can also modify @mshiggins code to add the -disposition option to specify that the first audio track is default. Then you don't have to build ffmpeg from scratch. That's what I did. The code is [here](https://github.com/phtagn/sickbeard_mp4_automator/commit/c282d714d3d6da69fff715d8b0af9e39cebaeac2)

**Comment by mdhiggins** [comment]
Can you make a pull request for the disposition code changes you made? Would be awesome to have a fix for this bug

**Comment by phtagn** [comment]
I did the pull request. Kind regards.

**Comment by mdhiggins** [comment]
Already merged. Strong work. Much appreciated.

**Comment by drazin** [comment]
Cheers all around!! Thanks for fixing this.

**Comment by astrodad** [comment]
I did an update on my cloned repo but I don't see the changes. And I still the pull request open. What am I doing wrong?

**Comment by mdhiggins** [comment]
Whoops looks like the merge didn't go through. Fixed it now. Could have sworn I confirmed it earlier.

**Comment by astrodad** [comment]
Cool thanks. I see it now. I'll test this afternoon!
