### ISSUE TITLE
Can the script process movies downloaded in NZBGet without having/using Couchpotato?

### ISSUE THREAD

**Issue by drazin** [mdhiggins/sickbeard_mp4_automator#493]
I dont want to use couchpotato but want to have the movies i download in NZBget processed by this script.  What settings do i need to use to accomplish this?  I tried assigning the script in the postprocess section for the category but i get the error - NZBGetPostProcess: Post-Process: No valid category detected. Category was Movies.

The couch potato category is something other than Movies, as i dont use Couchpotato.

what do i need to do to get this to work?

**Comment by astrodad** [comment]
Use the bypass category in the settings for the script: 

#Category for bypassing any further processing but still converting
#BYPASS_CAT=Bypass

**Comment by drazin** [comment]
doh!!! Thanks @astrodad i must have missed that.

**Comment by drazin** [comment]
ok so with some further testing it seems that it will convert, but wont update plex when its done.  

I'm getting logs like: 

STATUS -- NZBGETPOSTPROCESS: NONE


```
	Tue Jun 07 2016 19:31:35	Executing post-process-script videosort\VideoSort.py for XXXXX
INFO	Tue Jun 07 2016 19:31:35	Post-process-script NZBGetPostProcess.py for XXXXX skipped
INFO	Tue Jun 07 2016 19:31:35	NZBGetPostProcess: Successfully processed i:\XXXXX\123.mkv.
INFO	Tue Jun 07 2016 19:31:34	NZBGetPostProcess: i:\XXXXX123.mp4 created.
Tue Jun 07 2016 19:18:48	NZBGetPostProcess: Output file: i:\XXXXX\123.mp4.
INFO	Tue Jun 07 2016 19:18:48	NZBGetPostProcess: Output directory: i:\XXXXX.
INFO	Tue Jun 07 2016 19:18:48	NZBGetPostProcess: Input extension: mkv.
INFO	Tue Jun 07 2016 19:18:48	NZBGetPostProcess: File name: 123.
INFO	Tue Jun 07 2016 19:18:48	NZBGetPostProcess: Input directory: i:\XXXXX.
INFO	Tue Jun 07 2016 19:18:48	NZBGetPostProcess: Starting conversion.
```

**Comment by astrodad** [comment]
You need some way to move the output to a folder where Plex is already crawling. I recommend using the VideoSort script (http://nzbget.net/VideoSort) to move it to one of these folders (set up as the MoviesDir property in the script), at which point Plex will pick it up automatically.  My movies category, which is the bypass category, uses these three scripts: NZBGetPostProcess.py, videosort/VideoSort.py, Pushover.py 

Video

**Comment by drazin** [comment]
@astrodad thanks. That makes sense. I currently use videosort.py to move it into its final destination. I will turn back on plex directory monitoring since it's all done at this point. 

Thanks!!

**Comment by astrodad** [comment]
It uses the PushOver service to send me a notification on my phone that the movie was downloaded.
