### ISSUE TITLE
Feature Request: Add support for extra options

### ISSUE THREAD

**Issue by UnR34L** [mdhiggins/sickbeard_mp4_automator#494]
I have audio-codec set to 'libfdk_aac' and I'd like to set the audio codec profile to 'aac_he', I could probably find  somewhere to shove this in and get it working but it would be a lot cleaner if 'autoProcess.ini' had a variable like 'extra-options'.

Thanks for taking the time to read this.

**Comment by mdhiggins** [comment]
I'll look into adding this

Adding additional parameters takes a little because they all need to be error checked for the sake of not breaking automation

That being said this should be doable

**Comment by Mirabis** [comment]
I hard-coded it in locally, as I only use libfdk_aac. But wouldn't it be possible to have extra options the same way the AudioCodec class auto enables strict experimental?

E.g. 

[setting]
Audio_Vbr= 3

And then the LibfdkAac_Audio class

Supports_audio_vbr

Then in the parsing

If supports and audio-vbr in options:
     add logic here


Typing on my phone, but think it's clear :)?

**Comment by mdhiggins** [comment]
This can be done with the preopts and postopts options that were added
