### ISSUE TITLE
[Issue] Deluge

### ISSUE THREAD

**Issue by stohle** [mdhiggins/sickbeard_mp4_automator#495]
I am just about done setting up the script. im testing it out now. but im having some problems with deluge. 

`[WARNING ] 05:19:29 core:132 [execute] command '/media/sdr1/home/stohle/sickbeard_mp4_automator/delugePostProcess.py' failed with exit code 1
[WARNING ] 05:19:29 core:136 [execute] stderr: Traceback (most recent call last):
  File "/media/sdr1/home/stohle/sickbeard_mp4_automator/delugePostProcess.py", line 8, in <module>
    from deluge_client import DelugeRPCClient
ImportError: No module named deluge_client`

am i doing something wrong? to me it looks like a error in the script

**Comment by stohle** [comment]
im actually having a hard time getting this script to work... I run SAB, Sonarr, Couchpotato and Deluge. the script doesnt run in any of them. I have read the guide several times, checked everything!

**Comment by spot88** [comment]
Is there a complete step by step guide?

**Comment by mdhiggins** [comment]
Sadly not really. The instructions in the readme are pretty much it.

**Comment by spot88** [comment]
@mdhiggins Okay, damn... Anyone want to make one? :D

**Comment by drazin** [comment]
I followed the directions in the read me and had success. Just start over and do it line by line.
