### ISSUE TITLE
Sabnzbd - TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by zaylman** [mdhiggins/sickbeard_mp4_automator#496]
I'm not super knowledgeable about these things but I've gotten this far after Sab is done downloading I get this

TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by mdhiggins** [comment]
Do you have SAB pointing to the right script? Which script is SAB trying to execute?

**Comment by zaylman** [comment]
postSonarr.py is the script I've selected in SABNZBD

**Comment by mdhiggins** [comment]
That would be incorrect. SABPostProcess.py is what you should be pointing too. As the name suggested postSonarr is for Sonarr 😁

**Comment by zaylman** [comment]
Thank you I appreciate your help, The script executes now, but I'm having problems finding how to set the path for ffmpeg in ubuntu since its not an exe

**Comment by mdhiggins** [comment]
Just point it to your FFMPEG binary. Usually on Linux it's in /usr/bin
