### ISSUE TITLE
Sonarr moves but doesn't convert

### ISSUE THREAD

**Issue by davidbgeek** [mdhiggins/sickbeard_mp4_automator#498]
I'm experiencing an issue where the script moves the file but doesn't convert it in the process. Here's the error that I'm getting: https://gist.github.com/davidbgeek/3663fc2fb5d18abbf81120d24896dccb.

**Comment by Mirabis** [comment]
D:\\\rnetMedia\\sickbeard_mp4_automato

You have three slashes '\' in there :)

**Comment by davidbgeek** [comment]
That's odd... My settings in Sonarr don't have that... 
![image](https://cloud.githubusercontent.com/assets/12853597/16184487/bb9595f2-368a-11e6-8a0f-fe7f047f0797.png)

**Comment by davidbgeek** [comment]
Just fixed it. For some reason, the script seems to only work when it's on the C drive (or perhaps the same drive as the Python exe).

**Comment by mdhiggins** [comment]
Gonna close this since you opened the other issue, seems like the same problem
