### ISSUE TITLE
Sonarr doesn't run script automatically after download

### ISSUE THREAD

**Issue by davidbgeek** [mdhiggins/sickbeard_mp4_automator#499]
I don't see anything in the logs pertaining to postSonarr.py since 09:16, when I did a manual import. None of the stuff I downloaded was automatically processed.

**Comment by mdhiggins** [comment]
Does the script show up in Sonarr's options?

**Comment by mdhiggins** [comment]
And is it ONLY with manual import that its not working or with all Sonarr processed files?

**Comment by davidbgeek** [comment]
It's setup as a custom script in Sonarr. 
Sonarr doesn't appear tone detecting download completion in Delige so it doesn't run the script. However, _Rescan Drone Factory Folder_ & _Manual Import_ so trigger the script.

**Comment by davidbgeek** [comment]
Any ideas @mdhiggins?

**Comment by mdhiggins** [comment]
Seems like your postDeluge.py script isn't being executed or isn't configured correctly. Double check your deluge settings and setup

**Comment by mdhiggins** [comment]
Yes that's what hands the file back to Sonarr after downloading is complete for additional processing

**Comment by davidbgeek** [comment]
Oh... The instructions weren't so clear on that. I'll try it now.

**Comment by davidbgeek** [comment]
Update: it works flawlessly now! Thank you very much, @mdhiggins - awesome project!
