### ISSUE TITLE
Conversion Failing

### ISSUE THREAD

**Issue by psychoflame** [mdhiggins/sickbeard_mp4_automator#500]
I'm running the script in a freenas jail. When i have a file passed to the script im seeing this error. 

Traceback (most recent call last):
  File "/mnt/Downloads/Tools/Scripts/SABPostProcess.py", line 7, in <module>
    from mkvtomp4 import MkvtoMp4
  File "/mnt/Downloads/Tools/Scripts/mkvtomp4.py", line 8, in <module>
    from converter import Converter, FFMpegConvertError
  File "/mnt/Downloads/Tools/Scripts/converter/__init__.py", line 7, in <module>
    from converter.ffmpeg import FFMpeg, FFMpegError, FFMpegConvertError
  File "/mnt/Downloads/Tools/Scripts/converter/ffmpeg.py", line 13, in <module>
    console_encoding = locale.getdefaultlocale()[1] or 'UTF-8'
  File "/usr/local/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

I checked the locales in my jail and im seeing this so they do seem to match up.
LANG=en_US.UTF-8                                                                
LC_CTYPE="en_US.UTF-8"                                                          
LC_COLLATE="en_US.UTF-8"                                                        
LC_TIME="en_US.UTF-8"                                                           
LC_NUMERIC="en_US.UTF-8"                                                        
LC_MONETARY="en_US.UTF-8"                                                       
LC_MESSAGES="en_US.UTF-8"                                                       
LC_ALL=                 

I've had the script working for a good 4 to 5 months, didn't change anything it just seemed to stop working. I've already gone into my autoprocess,ini and set subtitle_encode seting from utf-8 to blank but that didn't help. Any help would be extremely appreciated. Thanks

Edit: Tried a clean install of the script with an import of my autoprocess.ini. Still getting the same error as seen above.

Edit2: May be related to these problems
http://bugs.python.org/issue18378
http://bugs.python.org/issue5815

**Comment by psychoflame** [comment]
So i ended up fixing this issue by enforcing the utf.8 locale across the whole system. still not sure why it poped up in the first place though

**Comment by LandMineHare** [comment]
How did you enforce it across the whole system? I've been racking my brain and can't figure it out. Also using FreeNAS myself.
