### ISSUE TITLE
-disposition PULL now produces a file with 3 audio tracks

### ISSUE THREAD

**Issue by roidy** [mdhiggins/sickbeard_mp4_automator#502]
I was one of the users who was having the problem with output files having all the audio tracks set as default causing multiple tracks to play at the same time on iOS devices. I was happy to see this has been addressed with the -disposition pull request that was recently added. However I have a problem that my output files now have 3 audio tracks instead of 2.

For example the input file is an mkv with the first audio track as AC-3 and the second audio track as AAC but the output file contains 3 audio tracks like so:-

```
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 160
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "copy",
            "disposition": "none",
            "bitrate": 480
        },
        "2": {
            "map": 2,
            "language": "eng",
            "channels": 2,
            "codec": "copy",
            "disposition": "none",
            "bsf": "aac_adtstoasc",
            "bitrate": 160
        }
```

Is this correct? Why is there a second AAC audio track?

Thanks.

**Comment by mdhiggins** [comment]
Looks like your source file has 2 audio tracks and you have iOS audio option enabled
