### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by shaunBZ** [mdhiggins/sickbeard_mp4_automator#503]
Hi,
So i'm what you would call a 'Novice' when it comes to this but hoping you could help as this script sounds amazing and just what i need.

I've been following the mdhiggins readme which I know is based on Windows, (I'm using a Macmini), so have also been following the guides listed in Issue #175. This has helped me get so far, I thought It was all going so well... This might be a simple problem that I'm just un aware of, But when I run manual.py, I get this message:

SHAUNs-Mac-mini:sickbeard_mp4_automator-master MACMINISJ$ ./manual.py -i/Volumes/LaCie/Media/TV/Weeds/Season\ 8/Weeds.S08E03.See.Blue.and.Smell.Cheese.and.Die.mkv -a
Manual processor started.
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
64bit Python.
Traceback (most recent call last):
File "./manual.py", line 356, in 
main()
File "./manual.py", line 346, in main
tagdata = getinfo(path, silent=silent)
File "./manual.py", line 85, in getinfo
tagdata = guessInfo(fileName, tvdbid)
File "./manual.py", line 120, in guessInfo
guess = guessit.guess_file_info(fileName)
AttributeError: 'module' object has no attribute 'guess_file_info'

*background info*
Running PLEX, SickBeard, Couchpotato & SABnzbd
[Mac mini (mid 2010) OS X El Capitan 10.11.5]

**Comment by psychoflame** [comment]
Make sure your in the directory with the scripts then type 

python manual.py

Should Run

**Comment by shaunBZ** [comment]
OK Update: So I tried to run manual.py from the directory, this seemed to work, but now I'm faced with this message:

SHAUNs-Mac-mini:~ MACMINISJ$ cd /Users/MACMINISJ/Downloads/sickbeard_mp4_automator-master
SHAUNs-Mac-mini:sickbeard_mp4_automator-master MACMINISJ$ ./manual.py -i/Volumes/LaCie/Media/TV/Weeds/Season\ 8/Weeds.S08E03.See.Blue.and.Smell.Cheese.and.Die.mkv 
Manual processor started.
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Traceback (most recent call last):
  File "./manual.py", line 33, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "/Users/MACMINISJ/Downloads/sickbeard_mp4_automator-master/readSettings.py", line 516, in __init__
    self.Sickbeard['ssl'] = config.getboolean(section, "ssl")  # SSL
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: 0/1

**Comment by shaunBZ** [comment]
removed the 0/1 from SickBeard SSL option in autoProcess.ini and replaced it with a 0, resulted in this:

SHAUNs-Mac-mini:sickbeard_mp4_automator-master MACMINISJ$ ./manual.py -i/Volumes/LaCie/Media/TV/Weeds/Season\ 8/Weeds.S08E03.See.Blue.and.Smell.Cheese.and.Die.mkv -a
Manual processor started.
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
64bit Python.
Traceback (most recent call last):
  File "./manual.py", line 356, in <module>
    main()
  File "./manual.py", line 346, in main
    tagdata = getinfo(path, silent=silent)
  File "./manual.py", line 85, in getinfo
    tagdata = guessInfo(fileName, tvdbid)
  File "./manual.py", line 120, in guessInfo
    guess = guessit.guess_file_info(fileName)
AttributeError: 'module' object has no attribute 'guess_file_info'


So Im even more confused now?

**Comment by mdhiggins** [comment]
Looks like you're using the wrong version of guessit

**Comment by shaunBZ** [comment]
Yeah thats totally what it was, Cheers. Its all working wonderfully now. Big up mdhiggins!
