### ISSUE TITLE
CouchPotato AutoProcess Script Broken

### ISSUE THREAD

**Issue by psychoflame** [mdhiggins/sickbeard_mp4_automator#504]
So im not sure if im doing something wrong on my end but it looks like the couchpotato post-process scripts seems to be broken. I have it triggering SABPostProcess script and it Completes Successfully and passes it off to couchpotato. Couchpotato then moves the files to the specified place then triggers the autoprocess script for couchpotato. However it fails because the scripts passes the file path for before couchpotato moves it so it fails out because nothing there. I have properly setup couchpotato i have it set to 0 for both the settings it says to do in the instructions so im pretty sure i haven't misconfigued it. Logs below

Couchpotato
https://justpaste.it/vru9

Sab
https://justpaste.it/vrur

**Comment by mdhiggins** [comment]
Just pushed a little update that undid a change that snuck in with a pull request that had no place being present in postCouchPotato
Try updating and see if it makes any difference

**Comment by psychoflame** [comment]
Yep that did it, everything seems to be working as expected now. Thanks man
