### ISSUE TITLE
Just a question about h265

### ISSUE THREAD

**Issue by nogardvfx** [mdhiggins/sickbeard_mp4_automator#505]
I am currently debating converting my files over to h265 to save some disk space.  I have been experimenting doing some conversions just to see what the space saving would be.

I have done a test with a few movies and have noticed that there is no file size difference between h264 and h265 (using the manual command line for testing purposes).  But if I use this command:
**ffmpeg -i input.avi -c:v libx265 -preset medium -crf 23 -c:a aac -b:a 256k -strict -2 output.mp4**
I get about a 50% savings in file size.  I have tried to match the settings in the ini file, but I am wondering if there is any place else I would need to check/change.

Love the program and cheers!

**Comment by waikariboy** [comment]
i would be interested in this also.

**Comment by Dr-Crow** [comment]
I think this feature should be added. H265 is becoming more wide spread.

**Comment by mdhiggins** [comment]
This can be achieved with the preopts and postopts settings and the h265 video-codec settings now
