### ISSUE TITLE
[Request] .partial filename during conversion

### ISSUE THREAD

**Issue by Mirabis** [mdhiggins/sickbeard_mp4_automator#508]
Any way u can implement a temporary filename like  *.mp4.partial~  during conversion?

Whenever u set it up with Sonarr, it converts files already in the library - which Plex picks up - but it's not finished yet :)

**Comment by Mirabis** [comment]
Something along the lines of 
```
    def usePartialFile(self,input,reverse=False):
        if reverse:
            newfile = str(input).replace(".partial~","")
            os.rename(input, newfile)
            self.log.debug("Renaming output file to %s." % newfile)
        else:
            newfile = str(input).replace(output_extension,(output_extension + ".partial~"))
            os.rename(input, str(input).replace(".partial~","")
            self.log.debug("Renaming output file to %s." % newfile)
        return newfile
```

But with error checking if needed. Would make a pull request... but have so many local edits and swamped with tasks :(

**Comment by meks007** [comment]
i have implemented this feature in my fork, along with a couple others. It's called Staging over there.
check out my README: https://github.com/meks007/sickbeard_mp4_automator/blob/master/README.md

**Comment by HeroXx** [comment]
Did this ever get implemented?

**Comment by mdhiggins** [comment]
Just pushed an update that adds this, there's a `temp_extension` option in autoProcess.ini, leave blank for the previous behavior, or set this option whichever extension you want for a temporary extension during conversion
