### ISSUE TITLE
Unrecognized option 'disposition:a:0'

### ISSUE THREAD

**Issue by Kocane** [mdhiggins/sickbeard_mp4_automator#510]
When I am running the post process script on SABNZBD (and anywhere else, I guess) it fails with this:

```
2016-07-14 23:46:53 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/opt/autoprocess/mkvtomp4.py", line 630, in convert
    for timecode in conv:
  File "/opt/autoprocess/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/opt/autoprocess/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=23598, cmd="/usr/bin/ffmpeg -fix_sub_duration -i /storage/data/mediacenter/downloads/Just_Go_with_It_2011_1080p_Bluray_DTS_x264-SHiTSoNy.2/deranged-tajtmcotodin1945.1080p.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 1 -b:a:0 128k -metadata:s:a:0 language=eng -strict experimental -f mp4 -threads auto -y /storage/data/mediacenter/downloads/Just_Go_with_It_2011_1080p_Bluray_DTS_x264-SHiTSoNy.2/deranged-tajtmcotodin1945.1080p.mp4">
```
(Disclaimer: That movie is only being used for testing, 'cause of DTS and low filesize ;))

If I run the command manually, it says it fails with:
```
Unrecognized option 'disposition:a:0'
Failed to set value 'default' for option 'disposition:a:0
```
The code sure enough does have this "disposition" parameter, and if I remove it, it seems to work...?

What am I missing?  Is this parameter nessesary? I only copied the ffmpeg command, pasted without the disposition parameter. I wouldn't know how to actually remove it from the entire script, if nessesary. Naturally, I'd prefer if it was fixed.

FFMPEG version is 1.0.10. I'm on Debian Wheezy.

**Comment by mdhiggins** [comment]
Update your version of FFMPEG

**Comment by Kocane** [comment]
I feel like an idiot. I don't know why I thought apt-get install ffmpeg would get me the latest.

Seems to work! Thanks for the great script and the very nice installation guide.

**Comment by Kocane** [comment]
@mdhiggins Just quick question; anything that can be done to speed up the process of converting to AAC and AC3 from, say, DTS?

**Comment by mdhiggins** [comment]
Not really, FFMPEG and CPU limitations dictate that

**Comment by Kocane** [comment]
@mdhiggins Alright.. Figures.. since it takes a while, do you think it could be possible to incoporate "nice" in the script so that ffmpeg uses a lower priority?

**Comment by Kocane** [comment]
@mdhiggins Just another thing, does it matter that the audio I downloaded is TrueHD? Video is AVC with x264 so plex shouldnt have trouble with that but my (abeit weak) microserver has taken - I don't even know how many hours - to convert this into AAC+AC3. A sample video of ca. 1 min I tried with earlier finished in no time.

**Comment by ehaus** [comment]
Writing this comments for the benefits of others who come across this issue later.

Another issue that can cause this is discrepancies between avconv and ffmpeg.  If you were like me, you may not even realize you were running avconv in the first place.  Not sure if this is standard or not, but my hosting provider which I believe runs Ubuntu, has a binary called ffmpeg installed, but it is seemingly actually the avconv program.  That program did not have support for the disposition command, even though it was a very recent version.  

My solution was to download the static builds for ffprobe and ffmpeg.  You can get them here: https://ffmpeg.org/download.html.

**Comment by jatindersingh13** [comment]
My ffmpeg version 2.0.4 
i also try this command
ffmpeg -i t-10684.mkv -i test.srt -c copy -disposition:s:0 default subbb.mp4
and
ffmpeg -i t-10684.mkv -i test.srt -c copy -disposition:s:s:0 default subbb.mp4

Show this error
Unrecognized option 'disposition:s:s:0'.
and
Unrecognized option 'disposition:s:0'.

**Comment by mdhiggins** [comment]
@jatindersingh13  Your version of FFMPEG is really old
2.6.5 came out in 2015 and that's the oldest release still listed on FFMPEG's github, you need to update
