### ISSUE TITLE
Manual script not tagging

### ISSUE THREAD

**Issue by blakedut2** [mdhiggins/sickbeard_mp4_automator#511]
Whenever I attempt to run the manual.py script on my existing CouchPotato movies directory, it successfully transcodes movies however it does not add any tags whatsoever.  I tried using guessed identification, manually entering the IMDB ID, I tried running it on the whole directory or just one file at a time.  No matter what I always get:

"There was an error tagging the file
no tags in file"

I set the logging detail to "INFO" and even then the only message is "Applying tags to xxx", the log doesn't even reflect the error.  This is infuriating because metadata tagging is a massive part of trying to organise a library within iTunes.  Can someone shed any light on where I can find any more detailed logs?  Or any simple debugging solutions?

**Comment by mdhiggins** [comment]
That error comes from mutagen, doesn't get any more detailed unfortunately.

That being said, you can try commenting out some lines on tvdb_mp4.py and see if it resolves your tagging woes

```
        try:
            video.delete()
            video.save()
        except IOError:
            self.log.debug("Unable to clear original tags, attempting to proceed.")
```

Just comment out that block of code or delete it and see if it makes any difference (lines 68-72)

**Comment by blakedut2** [comment]
Looking through the Mutagen source, the save function cannot be called when there are no tags.  Therefore, when you try to clear the tags and then save the cleared tags it will throw an exception.  I don't have access to a PC, but I'd put a pull request in to remove the video.save() line as it doesn't really achieve anything anyway.

**Comment by mdhiggins** [comment]
Yeah looks like that save call isn't needed. Wonder why it only throws that error sometimes though, I have been able to tag with it there for a while without any issues

That being said I removed the save line and pushed a commit

Does that fix your issue?

**Comment by blakedut2** [comment]
Yeah, when I removed it last night it worked fine.  Just didn't have time/couldn't be bothered to commit.

**Comment by mdhiggins** [comment]
Thanks, made the commit
