### ISSUE TITLE
'string index out of range'

### ISSUE THREAD

**Issue by makkus** [mdhiggins/sickbeard_mp4_automator#512]
I'm trying to convert a mkv file, and getting this error:

```
...
...
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: ac3 [jpn].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Audio track is number 0 setting disposition to default
Creating audio stream 1 from source stream 1.
An unexpected error occurred, processing of this file has failed
string index out of range
```

Any idea what could be wrong? Is there a way to enable more in-depth debugging output?

**Comment by mdhiggins** [comment]
Not sure what would cause that error? Does any more information pop up?
Are you getting that with every file or only this one specific file?

**Comment by makkus** [comment]
No, no further information. Most other files work, I'd have to do more testing to confirm, but I think it happened with other files too. With this one I can reproduce it though.

**Comment by mdhiggins** [comment]
If you wanna email me a link to the file giving you trouble I can do some further testing

Not sure what would be triggering that error though

**Comment by makkus** [comment]
Ok, I think I figured it out. Didn't have any value for audio-codec in my autoProcess.ini, and it looks like that tripped up that line in mkvtomp4 ( https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/mkvtomp4.py#L368 ):

` acodec = 'copy' if a.codec.lower() in self.audio_codec else self.audio_codec[0]`

Looks like it works for the files that failed before when I add 'ac3' as value for that field.

Thanks!
