### ISSUE TITLE
Process hangs at "Processing File ..."

### ISSUE THREAD

**Issue by wjbeckett** [mdhiggins/sickbeard_mp4_automator#515]
I'm testing out the conversion using manual.py and it's not going any further than:

`Manual processor started.`
`/usr/bin/python`
`Audio bitrate was invalid, defaulting to 256 per channel.`
`32bit Python.`
`Processing file ...`

Is there any logs somewhere that I can check to see why it's not going any further?

**Comment by mdhiggins** [comment]
Can't say I've seen this error before

Does it fail on every file?

You can maybe enabled debug level logging in logging.ini and then check info.log for some more information.
