### ISSUE TITLE
[REQUEST] Join Files When Come As cd1, cd2 etc...

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#517]
As the title states, any chance you could implement this?

**Comment by mdhiggins** [comment]
Probably not gonna happen, would be challenging to automate this with different naming schemes and its super rare to find releases split into CDs these days. Sorry

**Comment by screamjojo** [comment]
HI,
After many years I am also interested in this feature.
Do you think it's possible to write something like "if filename contain part1 & part2 & same folder => Join files."

Thank in advance

**Comment by mdhiggins** [comment]
Still no. Best bet is to just merge these files before passing them to the script but the way it's currently written would be a major rewrite and difficult to automate for the previously mentioned reasons
