### ISSUE TITLE
manual.py unrecognized arguments

### ISSUE THREAD

**Issue by noja11** [mdhiggins/sickbeard_mp4_automator#520]
Hi, 

I'm not super experienced with python so I'm not sure exactly where I'm going wrong.  I've got everything setup and working well in the automated fashion and manual.py is working perfectly when I convert an individual file.  

However, I've been trying to use the batch conversion actions through the command line and every time I  attempt to do so, the script fails. 

C:\Users\NAME>C:\sickbeard_mp4_automator-master\manual.py -i D:\TV\12 Monkeys\Season 02 -a
Manual processor started.
C:\Python27\python.exe
Audio bitrate was invalid, defaulting to 256 per channel.
usage: manual.py [-h] [-i INPUT] [-c CONFIG] [-a] [-tv TVDBID] [-s SEASON]
                 [-e EPISODE] [-imdb IMDBID] [-tmdb TMDBID] [-nm] [-nc] [-nd]
                 [-nt] [-np] [-pr] [-cmp4] [-m MOVETO]
manual.py: error: unrecognized arguments: Monkeys\Season 02

I'm assuming I'm just failing to use the command line correctly, but I'm also seeing issues with manual.py.

If I start manual.py it works well and I can enter the folder name no problem.  But then I have to approve each file with the "y/n" before it will convert them.  Also, when I enter "D:\TV\12 Monkeys\Season 02 -a", the script immediately closes.

I have no idea where I'm going wrong.  Help? 

Also, this script is amazing, thank you so much!

**Comment by apperrault** [comment]
your command should be `C:\sickbeard_mp4_automator-master\manual.py -i "D:\TV\12 Monkeys\Season 02" -a`

the file path has spaces in it so the command doesn't recognize the full path

hope that helps

app

**Comment by noja11** [comment]
Ahh see, I knew it was most likely me not knowing the command line very well.  Adding in the quotes did the trick. Thank you!
