### ISSUE TITLE
manual.py not allowing me to specify a TV Show

### ISSUE THREAD

**Issue by apperrault** [mdhiggins/sickbeard_mp4_automator#521]
Hi everyone
First, great script.  This is going to make things much easier for me going forward with my media setup.  I am trying to tag my existing media, and I am having a small issue.  it will not let me use the -tv option.  I am trying to tag "The Flash (2014)" but for some reason it always thinks it is the upcoming Flash movie.  

here is what I am running:
`D:\GitHub\mp4_automator>manual.py -tv 279121 -a -nm -i "D:\Software Downloads\Movies\TV_Shows\The Flash (2014)\Season 1"`

Any thoughts?

app

**Comment by mdhiggins** [comment]
The guessing isn't 100% specific, you can manually specify the TVDB ID via the command line to override the inappropriate guess

**Comment by apperrault** [comment]
that is what I was trying to do with the -tv 279121 portion of my command.  is that not in the correct place?

thanks

app
