### ISSUE TITLE
Plex not getting notified/updated

### ISSUE THREAD

**Issue by make92** [mdhiggins/sickbeard_mp4_automator#522]
Hi, everything was working flawless tull I recently noticed that my plex server gets nor notified when the TV Show/episode got converted.
Sonarr is calling the script and everything gets converted but the plex library gets not updated any longer. 
I'm on the latest plex and sonar version and also updated your script to the latest version but it's just not working any longer. 
Any ideas ?

**Comment by Mirabis** [comment]
Not a fix... but as workaround u can try and have Sonarr push an update to Plex :)?

**Comment by mdhiggins** [comment]
What program are you having notify plex to refresh?

**Comment by thesidius** [comment]
Same here. Sonarr is no longer notifying Plex to update. Neither is CouchPotato. Was working like a charm a couple of weeks ago.

**Comment by make92** [comment]
For me it's working again.
What I did is in the .initial file of mp4_automaton in the plex section, I updated the token with a new one and it started to work again.

**Comment by mdhiggins** [comment]
Make sure all your info is updated. Also to avoid plex scanning mid conversion you can set up the Automator script to do the notification instead by configuring autoProcess.ini
