### ISSUE TITLE
Feature request: include all dependent python modules

### ISSUE THREAD

**Issue by natoriousbigg** [mdhiggins/sickbeard_mp4_automator#523]
I have not had success using the script in a docker/jail environment because it's lacking some dependents (such as sublime and babelfish). There's a similar script out there that works because all the dependents are including with the script: https://github.com/clinton-hall/nzbToMedia

However, the focus of that script is for transcoding and there are a lot of bugs for that feature. Would love to be able to use sickbeard_mp4_automator with my SABnzbd setup.

**Comment by ladude626** [comment]
I don't see a reason why all the dependents cannot be included, especially when this script depends on older version of subliminal and guessit.

**Comment by mdhiggins** [comment]
Only because they were massive rewrites and I haven't had time to update everything yet for the new versions

**Comment by ladude626** [comment]
Thanks for the update. Hopefully you can get to it sometime in the future.
