### ISSUE TITLE
Filter on iOS audio 

### ISSUE THREAD

**Issue by eack** [mdhiggins/sickbeard_mp4_automator#524]
It would be very useful to create an option to apply a filter on the ios audio like `dynaudnorm`.

**Comment by mdhiggins** [comment]
Just pushed an update that adds two new options

`audio-filter`
`ios-audio-filter`

Set these options as you would the -af option in the FFMPEG command line.

Example (assuming your build of FFMPEG has dynaudnorm)
`audio-filter = dynaudnorm=f=100:p=0.71:m=20.0`
