### ISSUE TITLE
SABPostProcess - ERROR - No valid category detected

### ISSUE THREAD

**Issue by jeller316** [mdhiggins/sickbeard_mp4_automator#528]
Hello, first awesopme program. I ahve it working fine with sickbeard/sabnzbd setup. I was trying to switch over to sonarr but I can't get to work correctly. Keep getting error SABPostProcess - ERROR - No valid category detected. I have a category set as sonarr in sabnzdb, sonarr, and the autoprocess file. I though this woukld work. Any help would be appreciated. attatched my auotproces file and stuff below.

[SickBeard]
host = localhost
port = 8081
username = jeller316
password = Kristino3
web_root = 
ssl = 0
api_key = 

[Sonarr]
host = localhost
port = 8989
web_root = 
ssl = 0
apikey = [MP4]
ffmpeg = C:\ffmpeg\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-max-width = 
h264-max-level = 4
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
max-audio-channels = 
audio-codec = ac3,aac
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 256
subtitle-codec = mov_text
subtitle-language = 
nilsubtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = False
tag-language = eng
download-artwork = False
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
subtitle-default-language = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = 0
apikey = 
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarrbypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
bypass-category = bypass

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 

[Plex]
host = localhost
[sonarr-sab setting.docxport = 32400
refresh = True
token = 

[sonarr-sab setting.docx](https://github.com/mdhiggins/sickbeard_mp4_automator/files/412417/sonarr-sab.setting.docx)

**Comment by mdhiggins** [comment]
Looks like you have a line error 

> sonarr-category = sonarrbypass-category = bypass
> 

That needs to be split into two lines
> sonarr-category = sonarr
> 

> bypass-category = bypass
>

**Comment by jeller316** [comment]
dumb mistake, thanks it works now.
