### ISSUE TITLE
Intel Quick Sync

### ISSUE THREAD

**Issue by trentmsteel** [mdhiggins/sickbeard_mp4_automator#529]
Does the "use-qsv-decoder-with-encoder " functioning at the moment? 

I have it enabled and have tested converting using "manual.py" as well as trying the script using using Sonarr and NZBGET. And each and every time I can see my CPU at 99% to 100%, which leads me to think it is not using Intel Quick Sync Video to encode the video. 
 
But the way when I use HandBreak it detects and uses my onboard videocard and my CPU remains at 5% to 10%.

Am I doing something wrong in the way  I have the script setup? 

"use-qsv-decoder-with-encoder = True"

**Comment by mdhiggins** [comment]
Should be working fine but make sure you have a build of FFMPEG that supports this feature.

**Comment by Deihmos** [comment]
I did the same and it did not work. The video codec is set to h26. Do I need to use something different?

**Comment by Deihmos** [comment]
I think I figured it out. I changed it from h264 to h264qsv. What is the setting "use-qsv-decoder-with-encoder = True" doing?

**Comment by trentmsteel** [comment]
I just figured this out after trying since this function was introduced. This is a great tool however it is clear it can use a little help with  a "How to for using Intel Quick Sync". Which I am putting together a Windows tutorial for it. 

Here is a quick tip: If you are using windows and have followed the tutorial found here on the GitHub. The thing you are missing is that you must have a CPU that supports "Intel Quick Sync" and You must have the COMPLETE drivers installed for your Intel GPU. 

I spent months trying drivers downloaded from intel none worked with Intel Quick Sync. Use this tool instead to find and install your drivers " Snappy Driver Installer". Reboot your PC and Try it, this was the only thing that worked. 

And be sure to set your "autoProcess.ini like this. "video-codec = h264qsv" and "use-qsv-decoder-with-encoder = True". 

Hope this helps anyone who comes across this.

**Comment by trentmsteel** [comment]
> I think I figured it out. I changed it from h264 to h264qsv. What is the setting "use-qsv-decoder-with-encoder = True" doing?

It enables the script to use your GPU instead of CPU, which is great when it comes to the time it takes to convert the Video files. Using it I went from a 1:25hr Video taking 15 minutes to convert with he Cpu to taking 5 minutes with the GPU.
