### ISSUE TITLE
This is probable a longshot

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#531]
I know this is probably a long shot but thought I would ask.
Not really sure how to ask so I will do my best.
I am wondering if there's a way when the source file is being check that if its 4k, it can use a different set of setting for the conversion.
Reason I ask may be of relevance. I have been using this script for just over a year now and 98% of the time it has done everything I ever wanted perfectly, but I am looking to start sourcing 4k content and would like to reduce it down from the massive files size and high bitrate to something like, 6500k H265 mp4. I know this works and is still really good looking 4k but having to manually change the setting each time is a pian.

**Comment by mdhiggins** [comment]
No real way to do this as of now. The entire goal of the script is to create a uniform media library so everything ends up in the same format.

Having different conditional outputs with certain specific scenarios isn't something that will be natively supported, but could perhaps be achieved with multiple instances of the script and some tricky routing in some of the primary programs.
