### ISSUE TITLE
ffmpeg built-in "faststart" support of qt-faststart 

### ISSUE THREAD

**Issue by ladude626** [mdhiggins/sickbeard_mp4_automator#535]
Looks like ffmpeg has support for "faststart" to relocate the moov atoms data. This is according to ffmpeg website:

> -movflags faststart
> Run a second pass moving the index (moov atom) to the beginning of the file. This operation can take a while, and will not work in various situations such as fragmented output, thus it is not enabled by default.

Maybe this can be used instead of the python qt-faststart module?

**Comment by mdhiggins** [comment]
This comes up periodically. There's issues with running the tagging stuff after the FFMPEG faststart option is used. Causes corrupt files in rare instances. The only order of operations that doesn't cause issues is convert, tag, faststart

**Comment by scoopydude2002** [comment]
I would like to open this issue again. 

Would to be possible to use ffmpeg builtin faststart option if tagging is not enabled? This can save a lot of time during transcoding if you don't need to tag files.

**Comment by mdhiggins** [comment]
It really wouldn't save any time, it can be added as part of the new
preopts / postopts feature but FFMPEG just does the processing same as
qtfaststart at the end of transcoding
