### ISSUE TITLE
MOOV not being relocated

### ISSUE THREAD

**Issue by danseitz** [mdhiggins/sickbeard_mp4_automator#536]
I've installed all of the Python packages (and went back and confirmed this), but when I use the script with CouchPotato and SABnzbd, Plex is telling me the file is not Web Optimized (it checks for MOOV at the beginning), and I've confirmed this with AtomicParsley. I'm using the SABPostProcess script if it matters. Am I missing something? I don't see anything in the SAB script log that suggests that process is happening (it goes from the FFMPEG to waiting 65 seconds to triggering the CouchPotato rename scan).

**Comment by mdhiggins** [comment]
MOOV relocation does not happen after SAB, renaming happens after CouchPotato/Sonarr/SB/SR processing takes place. Make sure these post processing scripts are set up appropriately.

MOOV relocation must take place AFTER tagging is performed or there will be playback errors in certain files.

If your movies are being tagged with metadata then you're probably not running your CP post processing script. See the CouchPotato section of the readme for setting this up.

**Comment by danseitz** [comment]
Hmmm...I've confirmed I've got the correct data in the ini file and that CouchPotato is loading the PostProcess script, but my movies aren't having their MOOV relocated. I'll try a fresh install to see if that fixes the problem and report back

**Comment by danseitz** [comment]
Okay, thanks for the tip that the MOOV part is done on CouchPotato side of things. Looking in my CP logs, it looks like the PostProcess script keeps failing with the following error:

`[ PostProcess] Traceback (most recent call last): File "D:\reencoder\postCouchPotato.py", line 13, in <module> fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')}) File "C:\Python27\lib\logging\config.py", line 78, in fileConfig handlers = _install_handlers(cp, formatters) File "C:\Python27\lib\logging\config.py", line 156, in _install_handlers h = klass(*args) File "C:\Python27\lib\logging\handlers.py", line 118, in __init__ BaseRotatingHandler.__init__(self, filename, mode, encoding, delay) File "C:\Python27\lib\logging\handlers.py", line 65, in __init__ logging.FileHandler.__init__(self, filename, mode, encoding, delay) File "C:\Python27\lib\logging\__init__.py", line 893, in __init__ StreamHandler.__init__(self, self._open()) File "C:\Python27\lib\logging\__init__.py", line 912, in _open stream = open(self.baseFilename, self.mode) IOError: [Errno 22] invalid mode ('a') or filename: 'D:\\\reencoder\\info.log'`

**Comment by danseitz** [comment]
(My base folder for the script is D:\reencoder if that wasn't obvious.)

**Comment by mdhiggins** [comment]
Can you post your full postCouchPotato.py script? Just wanna make sure your path looks ok in the script.

**Comment by danseitz** [comment]
Here it is, thanks!

`#!/usr/bin/env python

import sys
import os
import logging
from readSettings import ReadSettings
from mkvtomp4 import MkvtoMp4
from tmdb_mp4 import tmdb_mp4
from autoprocess import plex
from post_processor import PostProcessor
from logging.config import fileConfig

fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
log = logging.getLogger("CouchPotatoPostConversion")

log.info('MP4 Automator - Post processing script initialized')

settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
converter = MkvtoMp4(settings)

imdbid = sys.argv[1]
inputfile = sys.argv[2]
original = sys.argv[3]

log.debug("IMDBID: %s" % imdbid)
log.debug("Input file path: %s" % inputfile)
log.debug("Original file name: %s" % original)

try:
    log.info('Processing file: %s', inputfile)
    if MkvtoMp4(settings).validSource(inputfile):
        log.info('File is valid')
        output = converter.process(inputfile, original=original)

        if output:
            # Tag with metadata
            if settings.tagfile:
                log.info('Tagging file with IMDB ID %s', imdbid)
                tagmp4 = tmdb_mp4(imdbid, original=original, language=settings.taglanguage)
                tagmp4.setHD(output['x'], output['y'])
                tagmp4.writeTags(output['output'], settings.artwork)

            # QTFS
            if settings.relocate_moov:
                converter.QTFS(output['output'])

            # Copy to additional locations
            output_files = converter.replicate(output['output'])

            # Run any post process scripts
            if settings.postprocess:
                post_processor = PostProcessor(output_files, log)
                post_processor.setMovie(imdbid)
                post_processor.run_scripts()

            plex.refreshPlex(settings, 'movie', log)
    else:
        log.info('File %s is invalid, ignoring' % inputfile)
except:
    log.exception('File processing failed: %s' % inputfile)
`

**Comment by mdhiggins** [comment]
Whoops I’m sorry I meant the main.py file that is modified and placed in the CouchPotato plugins directory.

My bad.

**Comment by danseitz** [comment]
No worries! The only line I modified was the path:

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
import traceback
import os
import subprocess

log = CPLog(__name__)

# Edit to point to the absolute path where the rest of the script resides
path = "D:\\reencoder\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)

    def callscript(self, message=None, group=None):

        log.info('MP4 Automator - Post processing script initialized')
        exec_me = os.path.join(path, "postCouchPotato.py")

        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]

        success = True

        for inputfile in moviefile:
            try:
                log.info("Executing post processing on file %s with IMDB ID %s" % (inputfile, imdvid))
                if os.name == 'nt':
                    process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                else:
                    process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={})
                output, errors = process.communicate()
                log.info(output)
                log.info(errors)
                log.info("Return code: %s" % process.returncode)
            except:
                log.error("Failed to execute post processing on file %s" % input file
                log.error(traceback.format_exc())
                success = False

        return success
```)

**Comment by mdhiggins** [comment]
Everything there looks ok. It actually looks like the script is failing to access the info.log file.

I’m wondering if this is a permissions issue and that whatever user CP is running under doesn’t have write access to your scripts directory and the files contained within.

If you can I would relax the permissions on your D:\reencoder directory and all its contents to see if that resolves your issue.
