### ISSUE TITLE
Stak at 1. Rename autoProcess.ini.sample to autoProcess.ini

### ISSUE THREAD

**Issue by Serhioromano** [mdhiggins/sickbeard_mp4_automator#540]
This is sounds simple but I m sorry I am not guru of those things.

I know that this file is in git repo, but how it gets to my computer? Should cimple clone repo there? In what folder? Or there is special install command?

**Comment by mdhiggins** [comment]
This is standard practice for ini files using Git. You don't want the auto process.ini every time you update your local repo to be overwritten. You just rename autoProcess.ini.sample to autoProcess.ini
