### ISSUE TITLE
Sonnar and NZBGet should I configure both?

### ISSUE THREAD

**Issue by Serhioromano** [mdhiggins/sickbeard_mp4_automator#541]
When i configure NZBGet there is SHOULDCONVERT parameter. As i understand this one will convert file before sending it to Sonnar.

But in Sonnar I also configures post process. 

Are those work together or I have to delete configuration from Sonnar?

**Comment by Serhioromano** [comment]
Ok. I have very thoroughly tested. My configuration is QNAP NAS, Sonnar +  NZBGet.

I installed automator and tested `manual.py`. It works well. I mean it is much slower than I expected but it works. Convert whole folders that was already downloaded.

I have configured Sonnar. read this few times. Everything is according README.

I have configured NZBGet. There are some things missed in README. I'll add PR later with my corrections after we solve this issue. There are EXTENSION SCRIPTS parameter group where you have to select your script. Also if you use categories, and most people does, you have to select post process script in category parameters as well. Also it is not clear what SHOULDCONVERT does. Although changing of this parameter does not change anything. My downloaded files are not converted.

So automatic conversion does not work. And it is hard also to report like "It does not work". I am producing software myself and know that I have to give you something where you can start to look into a problem. But I do not know where to look. I've spend 8 hours of configuring this script, and I believe I looked into every parameter.

**Comment by mdhiggins** [comment]
Shouldconvert works in conjunction with the post download scripts, the only caveat being that you don't want to enabled shouldconvert AND the convert-mp4 = True option in autoProcess.ini

I guess the first question is where does the process fail?
Getting the converter running from NZBGet should be very straight forward as its just a dumb converter and doesn't require much setup. Getting the post-processing and tagging is usually the step where people fail because either the file isn't being passed back to Sonnar (or CP/SB etc) or the post-processing script isn't properly configured.

So is it failing to convert after NZBGet downloads the file?
If so look in the NZBGet logs or in info.log in the script directory

If its failing post Sonarr then look in the Sonarr logs or again look in the info.log section

You can also open up loggini.ini and change your logging level to DEBUG to get more information.

**Comment by Serhioromano** [comment]
Here is the log

```
INFO	Tue Aug 23 2016 02:03:29	Collection Adventure.Time.S07E27.Broke.His.Crown.720p.WEB-DL.AAC2.0.H.264-NTb English added to history
ERROR	Tue Aug 23 2016 02:03:29	Post-process-script NZBGetPostProcess.py for Adventure.Time.S07E27.Broke.His.Crown.720p.WEB-DL.AAC2.0.H.264-NTb English failed (terminated with unknown status)
ERROR	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: None
ERROR	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: Wrong path to sickbeard_mp4_automator: /root/sickbeard_mp4_automator
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: ImportError: No module named babelfish
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: from babelfish import Language
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: File "/root/sickbeard_mp4_automator/readSettings.py", line 11, in <module>
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: from readSettings import ReadSettings
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/NZBGetPostProcess.py", line 54, in <module>
INFO	Tue Aug 23 2016 02:03:29	NZBGetPostProcess: Traceback (most recent call last):
```

**Comment by mdhiggins** [comment]
Looks like its failing because you don't have access to the babelfish module.

You need to install babelfish using PIP

**Comment by Serhioromano** [comment]
I did it. 

```
[/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts] # pip install babelfish
Requirement already satisfied (use --upgrade to upgrade): babelfish in /share/CACHEDEV1_DATA/.qpkg/Entware-ng/lib/python2.7/site-packages
```

**Comment by mdhiggins** [comment]
Seems like whatever python environment that's being used is different from the environment that you're installing babelfish under with that command line. I'm guessing this has to do with how QNAP handles things but I can't say for sure.

**Comment by Serhioromano** [comment]
How to test? What is python analog of php? For example I can do `which php`. What is the python analog?

**Comment by mdhiggins** [comment]
No idea what the PHP analog would be, but try this

open python command line
type `import babelfish`

If this fails, then babelfish isn't installed and you need to sort that out

If it works (no error pops up) then type the following:
```
import system
print sys.executable
```

This should output a path to a python executable

Copy this and open up postSonarr.py

Look at the SHEBANG on the first line, by default it reads `!/usr/bin/env python`
I'm guessing that WONT match your output that you're seeing
Change that first line to the path you got above (keep the `!`)

Try again and let me know

**Comment by Serhioromano** [comment]
Thank you very much for your attention. Very important to me. This is result of test.

```
[~] # python
Python 2.7.11 (default, Aug 18 2016, 12:54:38)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babelfish
>>> import system
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named system
>>>
```

But I know where my executables. Although there are too many of those. Which one to use?

![2016-08-23_02-42-36](https://cloud.githubusercontent.com/assets/650741/17870991/8495422c-68db-11e6-9440-f4087604cb90.png)

**Comment by mdhiggins** [comment]
Meant to type import sys not import system, made a ninja edit but was too slow I guess

My bad

**Comment by Serhioromano** [comment]
> I'm guessing that WONT match your output that you're seeing
> Change that first line to the path you got above (keep the !)

Then why `manual.py` works just fine?

**Comment by Serhioromano** [comment]
```
>>> sys.executable
'/opt/bin/python'
```

**Comment by mdhiggins** [comment]
Alright so modify your postSonarr.py file now and change that first line to be
`!/opt/bin/python` and see if it makes any difference

**Comment by Serhioromano** [comment]
Checking it now....

**Comment by Serhioromano** [comment]
Should I set SHOULDCONVERT in NZBGet script parameters to True? Because i cannot get who convert files Sonnar or NZBGet. Or I should only configure either Sonnar or NZBGet? I have configured both.

**Comment by mdhiggins** [comment]
Its personal preference. As long as you don't have `convert-mp4` set to True in autoProcess.ini you can leave them both enabled for conversion. That's the setup I use personally.

**Comment by Serhioromano** [comment]
Ok, that means that in fact I have to configure only one side. I see.

**Comment by Serhioromano** [comment]
12 hours and nothing. I'll give it a try tomorow.

**Comment by mdhiggins** [comment]
Same error?

**Comment by Serhioromano** [comment]
Yep. Although manual works.It is so complicated. I am PHP developer. I know staff. But this drives me crazy.

**Comment by mdhiggins** [comment]
Was there any additional info in the info.log file? (and is there anything preceding this error that resembles a python path?)

**Comment by Serhioromano** [comment]
The same log entries.  Nothing different.

I can give you access to my NAS if you want. If you promise not to break anything.

**Comment by mdhiggins** [comment]
No thanks, but if you wanna send me the full log file I'll take a look

I think ultimately what you and all the other NAS users need is for me to build a release with all the dependencies included in the script folder instead of relying on PIP

Next time I have a day off I'll try and make a branch of this project in that format

**Comment by smiller82** [comment]
Thought I'd share I'm also having this exact same issue. Same error log in NZBGet.  Tried the same recommendations as outlined above with no luck.  

Strange thing is i'm just doing some testing with the QNAP and yesterday I go this all working.  Today i factory reset the system and go through the same configurations and it doesn't work.

**Comment by smithdo** [comment]
Any update on this, as I have tried installing on my qnap and I am getting the same error.  have done everything in the article

**Comment by AliRizvi08** [comment]
In case someone else arrives here, here's how I fixed this issue:

In the README.MD on github for the project, it advises to install the prerequisites via pip install {etc}.

Instead use sudo -H python -m pip install {etc}

This will make sure the packages install with the correct version of oython, and the correct user permissions.

Good Luck!
