### ISSUE TITLE
Manual Process Deleting files after process

### ISSUE THREAD

**Issue by jodfie** [mdhiggins/sickbeard_mp4_automator#543]
i had problems getting Manual.py to work(so I haven't set up the other automations). I finally figured out the FFMPEG path issue on OSX.

Now.... I have it working, but it has converted then deleted I think? the 2 movies I tried it on.
I didn't edit the output or move paths figuring it would default back into the original folder it was ran from... is that correct? 

I can have the folder open and watch it convert and do the process of converting them then seconds later they disappear.

**Comment by mdhiggins** [comment]
just set the No delete option if you want to preserve the original. See the readme.

Also check the log and make sure there isn't an error occurring

**Comment by jodfie** [comment]
Thanks for the quick reply.
I don't want to keep the original say .avi file i just want the new mp4 where it is and the avi deleted.

heres a pastebin of the log from the last 2 runs http://pastebin.com/fsSZaze1

**Comment by mdhiggins** [comment]
From the looks of the logging everything should be working I don't see anything that would indicate the files were deleted inappropriately

You should have two files:
```
/Volumes/Media/Movies/Freaky Friday/Freaky Friday.mp4
/Volumes/Media/Movies/Communion 1989 BR-Rip/Communion 1989 BR-Rip.mp4
```

Are they definitely not there?

**Comment by jodfie** [comment]
well i've deleted both empty folders now since...so I cant show you. But the 2nd video i watched it's folder while it was doing it's thing and saw the MP4 and the QFTS.MP4 then after minute or so when I think it was complete they disappeared.

**Comment by mdhiggins** [comment]
Script should definitely not be deleting any mp4's. That's very strange. Can you post your full autoProcess.ini?

**Comment by ikrowni** [comment]
Not sure if i should be commenting here or creating a new topic but im having the same issue OP was having. Some of my files convert then it just deletes everything. Manual processing seems to work fine but when it goes automatically i can see the file being converted. I see the files in the folder then when it finishes converting they just get deleted.
