### ISSUE TITLE
Why processing  could be very slow?

### ISSUE THREAD

**Issue by Serhioromano** [mdhiggins/sickbeard_mp4_automator#544]
I use `manual.py`. It process quite quickly SD quality series. Or especially 10 min cartoons like Adventure Time.

But when it hits 1080p, 30 minuts, 1.2Gb-1.8Gb MKV, it takes arounnd 3 hours to process with 	Intel® Celeron® 2.41GHz dual-core processor. I have only 2Gb of RAM on my NAS. Can that be a reason?

**Comment by danseitz** [comment]
I guarantee it's your processor and the quality of the file. 1080p stuff encoded well can easily take 10-12 hours, so actually 3h isn't bad at all.

**Comment by mdhiggins** [comment]
Yeah its highly variable depending on what needs to be transcoded and the quality of the file you'll be transcoding. Any 1080p video with a half decent bitrate will take a long time (unless you're just remuxing). Audio takes less time but will add to the total transcode time.
