### ISSUE TITLE
Ability to check for DTS track and skip file.

### ISSUE THREAD

**Issue by shpankey** [mdhiggins/sickbeard_mp4_automator#545]
I have a lot of mkv files that contain DTS tracks, and have a lot that don't. Since I run this script in the raw on my library from time to time, I would like for this script to first check if the file has a DTS track, and if so, skip it. Since my clients can play DTS tracks when the container is mkv. Any way this option could be added?

**Comment by mdhiggins** [comment]
I'm not 100% clear on what behavior you're looking for here. See if you can provide some more detail
