### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by spot88** [mdhiggins/sickbeard_mp4_automator#547]
Ubuntu Server 16.04 LTS
Sickrage: Branch: master 

This is how the extra scripts looks like: 
/usr/bin/python /opt/converter/postConversion.py

This is my autoProcess.ini: 
[Sickrage]
host = localhost
port = 8081
username = admin
password = admin
web_root = http://192.168.85.131:8081/home/
ssl = 0
api_key = *** from sickrage ***

Logs says nothing, seems like it's not even trying to start. So I think i'm missing something.

**Comment by mdhiggins** [comment]
I would ask this question on the Sickrage forums. May be an issue with Sickrage. If logs are saying nothing then its not executing scripts like its supposed to.

Also make sure the script has appropriate permissions for Sickrage to execute the files in the script directory.
