### ISSUE TITLE
postSonnar.py crashes Sonnar if called too quickly in a row

### ISSUE THREAD

**Issue by thecorax** [mdhiggins/sickbeard_mp4_automator#549]
Sometimes my Sonarr crashed. The Webinterface still kinda works but as soon as you hit some actions nothing ever happens, f.e. delete logs.

This seems to happen if you activate SHOULDCONVERT: False in NZBGet and a download finishes while mkvtomp4 is still converting the previous episode.

Try to reproduce it by letting the first Episode load to 98%, then pause. Then get another Episode to 98% and unpause the first one again. The Episode finishing first will behave normally and will be converted to mp4. The download finishing second (while the first download is converting) will crash sonarr. 

Can't see anything in the debug log, I will check out the 'trace' log later.

Guess I will just limit my download speed for now.

**Comment by mdhiggins** [comment]
This sounds like a Sonarr issue I would post this one their site and see if it can be addressed. A script running too quickly shouldn't crash the system. Support for these post scripts is a relatively new feature for Sonarr this was one of the first scripts to support it - its possible this bug has gone undetected.
