### ISSUE TITLE
Manual script fails

### ISSUE THREAD

**Issue by TheBigZig** [mdhiggins/sickbeard_mp4_automator#551]
After installation, I am unable to manually run the script.  I consistantly get the following error:
Audio bitrate was invalid, defaulting to 256 per channel
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator\manual.py", line 18, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
  File "C:\sickbeard_mp4_automator\readSettings.py", line 225, in __init__
    self.artwork = config.getboolean(section, "download-artwork") # Download and embed artwork
  File "C:\Python27\lib\ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: Poster
Any assistance would be greatly appreciated.
Bill

**Comment by shpankey** [comment]
Have you installed all the pip stuff from the readme?

**Comment by mdhiggins** [comment]
Your config file is corrupted probably. Your download-artwork option isn't True or False like it needs to be.

**Comment by TheBigZig** [comment]
I have run all the pip commands.  I'll check the config file. Is that autoProcess.ini?

**Comment by TheBigZig** [comment]
Yep!  THANKS!!!!!!
