### ISSUE TITLE
Deluge not processing files?

### ISSUE THREAD

**Issue by dmartinez7500** [mdhiggins/sickbeard_mp4_automator#558]
I'm running the script on a Windows 7 machine, with Sonarr and CP, using Deluge as a download client. I've set up the scripts on all the platforms, but I seem to be having an issue with Deluge. When a torrent completes, it will write the 1st 3 lines to the log, but then nothing will happen. I'm using delugePostProcess.bat since I'm on Windows.

![image](https://cloud.githubusercontent.com/assets/5718250/18283519/a7cb14f2-7433-11e6-8cd6-2d63c3b5c3f6.png)

I've observed this so far with Sonarr torrents only, although to be fair, I've yet to process a CP file through the script since setting it up. Manual.py works great however.

**Comment by evilmanimani** [comment]
I'm experiencing this exact issue with delugepostprocess.bat on Windows, also with Sonarr. It's working great via SABNzbd, but I'm getting those exact same lines in the log when a download is completed via Deluge, any ideas?

**Comment by mdhiggins** [comment]
Set your logging level to debug in logging.ini and see if any additional information pops up

**Comment by evilmanimani** [comment]
Got it, looks like my deluge settings didn't like my host set to either localhost or 192.168.0.10; setting it to 127.0.0.1 got it to connect though. Cheers!
