### ISSUE TITLE
Dumb issues with categories

### ISSUE THREAD

**Issue by DavidKep** [mdhiggins/sickbeard_mp4_automator#562]
I'm sure this is simple but I figured I'd just ask since I'm failing at trying things...

Keep getting an "ERROR - No valid category" message... I've had a rather manual workflow for a while and never bothered with it. 

So created these categories:
![screenshot 2016-09-13 22 22 13](https://cloud.githubusercontent.com/assets/20311996/18497952/a03aa036-7a00-11e6-8216-5d0c4bf2545b.png)

This is my plain vanilla autoProcess section for SAB:
![screenshot 2016-09-13 22 24 08](https://cloud.githubusercontent.com/assets/20311996/18497975/d553a236-7a00-11e6-9241-221cb1adf9e6.png)

Can someone explain what actually happens with categories so I can make them work?

**Comment by martylavender** [comment]
When are you getting this error? Is this coming from CP? Sonarr?

I noticed you have 'movie' in your SAB settings but you dont have 'movie' in your autoProcess file. Knowing which app this error is getting generated with would help. Also more logs would help as well.

**Comment by mdhiggins** [comment]
Yeah your category is named "movie" but it needs to be named "couchpotato"
