### ISSUE TITLE
Error during postprocess - NZBGet to CP

### ISSUE THREAD

**Issue by martylavender** [mdhiggins/sickbeard_mp4_automator#563]
Hi

I seem to be having a problem. I wasnt getting this error until recently after reinstalling Ubuntu Server.

> **Waiting for 65.0 seconds to allow CPS to process newly extracted files**

NZBGet sits on this for 65 seconds and then while I am tailing **nzbget.log** I see this:

`Sat Sep 17 00:46:52 2016   INFO    NZBGetPostProcess: 2016-09-17 00:46:52 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess: 2016-09-17 00:47:58 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:5050/api/2f33a07423134ea186cc8a0c9931f448=/renamer.scan.
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess: Traceback (most recent call last):
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py", line 185, in <module>
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     autoProcessMovie.process(path, settings, nzb, status)
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/mnt/md0/nzbget/automator/autoprocess/autoProcessMovie.py", line 93, in process
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     rstate = r.json()
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 826, in json
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     return complexjson.loads(self.text, **kwargs)
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     return _default_decoder.decode(s)
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess:     raise ValueError("No JSON object could be decoded")
Sat Sep 17 00:47:58 2016    INFO    NZBGetPostProcess: ValueError: No JSON object could be decoded`

CP subsequently never processes the file.

I have double checked my API key.
When converting from Sonarr all goes well.
I can only imagine this is maybe a permissions issue? Although I dont see any permissions errors anywhere.
Ive restarted all services as well.

Any ideas at all would be appreciated. If you need any other information please let me know.

**Comment by mdhiggins** [comment]
Something is going on with talking to CP. Either the API key or the server address or port is wrong. Or an HTTPS vs HTTP issue. Either way it's failing to connect to the CP API like it should.

**Comment by martylavender** [comment]
Let me see what I can figure out . I was thinking the same thing as I was having issues getting PlexRequests to talk to CP as well.

**Comment by martylavender** [comment]
Ok so actually it looks like Sonarr isnt working either. I end up with Sonarr responding that its queueing files. Something is def not working correctly.

Im not even sure where to start at this point.

**Comment by martylavender** [comment]
Alright

I got my detective on and this is what I figured out.

I was totally confused this evening as I added a new series to Sonarr and had several episodes downloaded. They downloaded, converted, and imported into Sonarr / Plex / etc., without any issues. This baffled me.

I went and enabled Trace logging in Sonarr. I should have done this from the beginning.

`sonarr.trace.txt:16-9-18 23:15:41.6|Debug|UnverifiedSceneNumberingSpecification|This file uses unverified scene numbers, will not auto-import until numbering is confirmed on TheXEM. Skipping /mnt/md0/nzbget/completed/tv/.mp4`

I hoped over to TheXEM and sure enough....the series listings are alll kinds of jacked for this show. I remember that when Sonarr would search, the episode listings were always wacky. This was even more proven when I manually downloaded the episode by adding the NZB myself to NZBGet....once it downloaded and Plex updated the TV library, the show was displays as the same series but a different version of it altogether. Upon playing the show however, it was in fact the correct show. Soooooooo

Not an issue with your script. An issue with the listings being shit and Sonarr actually being smart enough to say 'hey this shit is screwed up...im not touching it!'

I also noticed quite a few movies downloaded processed just fine as well.

I think we can close this one out.

**Comment by martylavender** [comment]
Ok

I am still getting the JSON error for some reason:

`Tue Sep 20 04:47:23 2016        INFO    NZBGetPostProcess: Starting conversion.
Tue Sep 20 04:50:36 2016        INFO    NZBGetPostProcess: /mnt/md0/nzbget/completed/movies/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.cp(tt0096119)/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.mp4 created.
Tue Sep 20 04:50:36 2016        INFO    NZBGetPostProcess: Successfully processed /mnt/md0/nzbget/completed/movies/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.cp(tt0096119)/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.mkv.
Tue Sep 20 04:50:36 2016        INFO    NZBGetPostProcess: Successfully processed /mnt/md0/nzbget/completed/movies/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.cp(tt0096119)/Sleepaway.Camp.III.Teenage.Wasteland.1989.720p.BluRay.x264-SADPANDA.mp4.
Tue Sep 20 04:50:36 2016        INFO    NZBGetPostProcess: 2016-09-20 04:50:36 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess: 2016-09-20 04:51:41 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:5050/api/2f33a07423134ea186cc8a0c9931f448=/renamer.scan.
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess: Traceback (most recent call last):
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/opt/nzbget/scripts/NZBGetPostProcess.py", line 185, in <module>
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     autoProcessMovie.process(path, settings, nzb, status)
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/mnt/md0/nzbget/automator/autoprocess/autoProcessMovie.py", line 93, in process
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     rstate = r.json()
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 826, in json
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     return complexjson.loads(self.text, **kwargs)
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     return _default_decoder.decode(s)
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess:     raise ValueError("No JSON object could be decoded")
Tue Sep 20 04:51:41 2016        INFO    NZBGetPostProcess: ValueError: No JSON object could be decoded`

**Comment by mdhiggins** [comment]
I'm not sure what to tell you, try accessing your CouchPotato API via a web browser and see if you get the expected JSON output
