### ISSUE TITLE
Best Practices 

### ISSUE THREAD

**Issue by raymatos** [mdhiggins/sickbeard_mp4_automator#564]
So i have this currently setup for post processing for all TV shows in sickbeard.  However i was thinking of doing the same for movies.  What is the best way to set this up?

Should i process all the encoding in sabnzbd? or in the managers (ie: sickbeard/couchpotato)

Also if processing in sabnzbd, do i still have to setup the postprocessing scripts on the managers?

**Comment by martylavender** [comment]
If you are using Couchpotato, there are specific instructions on how to set this up. Its pretty much handled the same way Sonarr or Sickrage would handle it with SAB or NZBGet. The processing is handled in the downloader and then it tells the manager to pick up the file, move it, rename it, etc., and then done.

**Comment by mdhiggins** [comment]
This is all clearly explained in the readme. For SAB you need some sort of script to notify the media management software that the download is complete

Just set it up to use for both downloader and media manager, that's the ideal setup

**Comment by raymatos** [comment]
im not referring to the picking up part.  So if i read it right there are 2 ways to encode/remux the video content.

1.  Once the download is done in SAB, start encoding/remux of video file, then notify the managers (sickbeard, couchpotato) of the download and let it rename.

or 

2. Once the download is done in SAB, notify the managers, in each manager setup a post processing script that will encode/remux the video then move/rename/etc the file.

Which method is recommended?
