### ISSUE TITLE
Error converting file, FFMPEG error. 

### ISSUE THREAD

**Issue by csommerlarsen** [mdhiggins/sickbeard_mp4_automator#566]
Hi 
So all of a sudden the convertion failes both automatic through couch potato and manual. 
I have already checked that subtitles-encoding is set to nothing but it still doesn't work. 

Hope you can help and thanks for the great script! 

FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=13016, cmd="C:\Users\Christian\Documents\FFMPEG\bin\ffmpeg.exe -fix_sub_duration -i The.Conjuring.2.2016.1080P.Bluray.X264-Sparks.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 0:3 -metadata:s:s:0 language=eng -f mp4 -threads auto -y a:\Downloads\Couch Potato\Conjuring 2, The (2016)\The.Conjuring.2.2016.1080P.Bluray.X264-Sparks.mp4">
a:\Downloads\Couch Potato\Conjuring 2, The (2016)\The.Conjuring.2.2016.1080P.Bluray.X264-Sparks.mp4 deleted.

My config looks likes this: 

[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 

[Sonarr]
host = localhost
port = 8989
web_root = 
ssl = 0
apikey = 

[MP4]
ffmpeg = C:\Users\Christian\Documents\FFMPEG\bin\ffmpeg.exe
ffprobe = C:\Users\Christian\Documents\FFMPEG\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = A:\Itunes\Føj automatisk til iTunes
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = 
    eng,danaudio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
audio-default-language = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = 0
apikey = c15a881dca534929940d170f9a6d8c4c
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 

[Deluge]
host = localhost
username = 
convert = True
password = 
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 
    aab082b86210a83724ce00d0e18c5902

[Plex]
host = localhost
port = 32400
refresh = True
token =

**Comment by mdhiggins** [comment]
Can you post the full error log?

**Comment by mdhiggins** [comment]
Just pushed an update that will have the script spit out a lot more debugging information when FFMPEG errors are encountered. Update and rerun and post the output please.

**Comment by csommerlarsen** [comment]
Hi again! 
It seems that it only happend on one video so it most be a fault with FFMPEG. But thanks for your repley anyway! :-)
