### ISSUE TITLE
Converted File is unplayable in iTunes

### ISSUE THREAD

**Issue by ressiv** [mdhiggins/sickbeard_mp4_automator#568]
I can't see any errors in either the Sab or the SB log files, so I have little to go on...

The file that ends up in iTunes shows a total bit rate of 0 kbps and dimensions of 0x0.  The 'Time' value is unavailable and iTunes won't play the file.  One clue I have is that the Apple TV and QuickTime on the computer will play the file, but with no audio or audio tracks available.  VLC will play the file with the expected audio.

I've tried changing the 'output_format' from mp4 to mov. No difference.  
I've tried the output_extension as mp4 and m4v.  No difference.
I've changed the audio-codec to 'aac'.  No difference.
I've tried a manual.py conversion, but there are no errors or indicators of a problem.

VLC Codec details indicate the same details as the original:
Code: H264 - MPEG-4 AVC (Part 10) (avc1)
Stream 1:
Type Audio, Codec: MPEG AAC Audio (mp4a)

SickBeard 5.07
Fresh install of sickbeard_mp4_automator, and fresh install of ffmpeg.  The whole process works to get the file where it needs to be, including metatags.  

Windows 7 (32bit)

I'm not sure what else to try?  Any assistance or clues as to the problem would be much appreciated.  
[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/505234/autoProcess.ini.txt)

[Log Excerpts.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/505227/Log.Excerpts.txt)

**Comment by ressiv** [comment]
Further to this: Ran ffmpeg manually against the original mkv file in this case and it reported no errors.  Also ran ffmpeg against the converted mp4, and ffmpeg didn't indicate any sign of error.

Overnight, a 'larger file' from a different show came in automatically and the resulting mp4 works properly in iTunes.

A second 'smaller' file that also came in overnight was not working as per the description above.

**Comment by mdhiggins** [comment]
Can't say I have any ideas, iTunes can be picky for some reason and without logging is hard to pinpoint why it fails

Not sure what build of FFMPEG you're using but I would roll back to the latest stable build and also try a few of the previous builds. FFMPEG tends to change and update way faster than iTunes can support

**Comment by ressiv** [comment]
Thank you! Rolled FFMPEG back to 3.1.4 yesterday and so far with the few files that ran through the process last night, none of the converted files are showing the previously observed symptoms.

**Comment by saadiq** [comment]
Just for additional context, I also had/have this issue. I'm on a Mac and use Homebrew for ffmpeg installation. The problem cropped up with the Homebrew upgrade to ffmpeg 3.2. It seems that 3.2 removes support for faac and instead relies on native support or fdk-aac. I wasn't able to get either to work and instead also rolled back to 3.1.5 to resolve. I didn't try getting ffmpeg to directly encode it correctly to see if it was ffmpeg or sickbeard_mp4_automator at issue but will when I get some time.
