### ISSUE TITLE
Addition to the AAC audio problem

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#571]
An addition to the post I made [here](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/567) I have included a log from 2 diffrent files.

This one failed to do the audio right.
Heres the mediainfo before converting

> General
> Unique ID                                : 213088859489485921333378683879473314648 (0xA04F6BE96E23022BA3ED56D7FDE07B58)
> Complete name                            : D:\Downloads\Best.Friends.Whenever.S02E10.Its.Not.Ye.Its.Me.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash.mkv
> Format                                   : Matroska
> Format version                           : Version 4 / Version 2
> File size                                : 578 MiB
> Duration                                 : 23 min 22 s
> Overall bit rate                         : 3 456 kb/s
> Encoded date                             : UTC 2016-10-06 09:26:49
> Writing application                      : mkvmerge v9.4.2 ('So High') 64bit
> Writing library                          : libebml v1.3.4 + libmatroska v1.4.5
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L3.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 2 frames
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 23 min 22 s
> Bit rate                                 : 3 360 kb/s
> Width                                    : 1 280 pixels
> Height                                   : 720 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (24000/1001) FPS
> Original frame rate                      : 24.000 FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.152
> Stream size                              : 556 MiB (96%)
> Writing library                          : x264 core 148 r2579M 73ae2d1
> Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=4 / lookahead_threads=1 / sliced_threads=0 / nr=250 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=0 / weightp=1 / keyint=250 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=2pass / mbtree=1 / bitrate=3360 / ratetol=1.0 / qcomp=0.60 / qpmin=5 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> 
> Audio
> ID                                       : 2
> Format                                   : AAC
> Format/Info                              : Advanced Audio Codec
> Format profile                           : HE-AAC / LC
> Codec ID                                 : A_AAC
> Duration                                 : 23 min 22 s
> Bit rate                                 : 127 kb/s
> Channel(s)                               : 2 channels
> Channel positions                        : Front: L R
> Sampling rate                            : 48.0 kHz / 24.0 kHz
> Frame rate                               : 23.438 FPS (1024 spf)
> Compression mode                         : Lossy
> Stream size                              : 21.2 MiB (4%)
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> 
> Text
> ID                                       : 3
> Format                                   : UTF-8
> Codec ID                                 : S_TEXT/UTF8
> Codec ID/Info                            : UTF-8 Plain Text
> Duration                                 : 23 min 13 s
> Bit rate                                 : 97 b/s
> Count of elements                        : 479
> Stream size                              : 16.6 KiB (0%)
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No

and the log during

> 2016-10-06 19:46:11 - MANUAL - INFO - Manual processor started.
> 2016-10-06 19:46:11 - MANUAL - INFO - C:\Python27\python.exe
> 2016-10-06 19:46:11 - MANUAL - WARNING - Invalid external subtitle codec mov_text, ignoring.
> 2016-10-06 19:46:11 - MANUAL - WARNING - No valid subtitle formats found, defaulting to 'srt'.
> 2016-10-06 19:46:19 - MANUAL - INFO - Reading video stream.
> 2016-10-06 19:46:19 - MANUAL - INFO - Video codec detected: h264.
> 2016-10-06 19:46:19 - MANUAL - INFO - Pix Fmt: yuv420p.
> 2016-10-06 19:46:19 - MANUAL - INFO - Reading audio streams.
> 2016-10-06 19:46:19 - MANUAL - INFO - Audio detected for stream #1: aac [eng].
> 2016-10-06 19:46:19 - MANUAL - INFO - Creating audio stream 0 from source stream 1.
> 2016-10-06 19:46:19 - MANUAL - INFO - Audio Track is number 1 setting disposition to default
> 2016-10-06 19:46:19 - MANUAL - INFO - Reading subtitle streams.
> 2016-10-06 19:46:19 - MANUAL - INFO - Subtitle detected for stream #2: subrip [eng].
> 2016-10-06 19:46:19 - MANUAL - INFO - Ripping eng subtitle from source stream 2 into external file.
> 2016-10-06 19:46:42 - MANUAL - INFO - d:\downloads\to convert\Best.Friends.Whenever.S02E10.Its.Not.Ye.Its.Me.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash.eng.srt created.
> 2016-10-06 19:46:42 - MANUAL - INFO - {
>     "preopts": [
>         "-fix_sub_duration"
>     ], 
>     "subtitle": {}, 
>     "format": "mp4", 
>     "postopts": [
>         "-threads", 
>         "auto"
>     ], 
>     "video": {
>         "map": 0, 
>         "codec": "h264", 
>         "bitrate": 2000, 
>         "level": 4.1
>     }, 
>     "audio": {
>         "0": {
>             "map": 1, 
>             "language": "eng", 
>             "channels": 2, 
>             "codec": "copy", 
>             "disposition": "default", 
>             "bsf": "aac_adtstoasc", 
>             "bitrate": 256, 
>             "filter": null
>         }
>     }
> }
> 2016-10-06 19:46:42 - MANUAL - INFO - Starting conversion.

Then after this is the mediainfo

> General
> Complete name                            : D:\Downloads\To Sort\Best.Friends.Whenever.S02E10.Its.Not.Ye.Its.Me.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash.mp4
> Format                                   : MPEG-4
> Format profile                           : Base Media
> Codec ID                                 : isom (isom/iso2/avc1/mp41)
> File size                                : 354 MiB
> Duration                                 : 23 min 22 s
> Overall bit rate                         : 2 119 kb/s
> Writing application                      : Lavf57.51.102
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L4.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 4 frames
> Codec ID                                 : avc1
> Codec ID/Info                            : Advanced Video Coding
> Duration                                 : 23 min 22 s
> Bit rate                                 : 2 000 kb/s
> Width                                    : 1 280 pixels
> Height                                   : 720 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.091
> Stream size                              : 332 MiB (94%)
> Writing library                          : x264 core 148 r2721 72d53ab
> Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=2000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
> Language                                 : English
> 
> Audio
> ID                                       : 2
> Format                                   : AAC
> Format/Info                              : Advanced Audio Codec
> Format profile                           : LTP
> Codec ID                                 : 40
> Duration                                 : 23 min 22 s
> Bit rate mode                            : Constant
> Bit rate                                 : 127 kb/s
> Channel(s)                               : 2 channels
> Sampling rate                            : 64.0 kHz
> Frame rate                               : 62.500 FPS (1024 spf)
> Compression mode                         : Lossy
> Stream size                              : 21.2 MiB (6%)
> Language                                 : English
> Default                                  : Yes
> Alternate group                          : 1

And this one worked just fine.

> 2016-10-06 15:08:02 - mkvtomp4 - INFO - Starting conversion.
> 2016-10-06 15:27:11 - MANUAL - INFO - D:\downloads\to convert\Arrow.S05E01.1080p.WEB-DL.DD5.1.H264-RARBG.mp4 created.
> 2016-10-06 15:27:12 - MANUAL - INFO - Relocating MOOV atom to start of file.
> 2016-10-06 15:28:11 - MANUAL - INFO - D:\downloads\to convert\Arrow.S05E01.1080p.WEB-DL.DD5.1.H264-RARBG.mp4 moved to D:\Downloads\To Sort.
> 2016-10-06 15:28:11 - MANUAL - INFO - Reading video stream.
> 2016-10-06 15:28:11 - MANUAL - INFO - Video codec detected: mpeg4.
> 2016-10-06 15:28:11 - MANUAL - INFO - Pix Fmt: yuv420p.
> 2016-10-06 15:28:11 - MANUAL - INFO - Reading audio streams.
> 2016-10-06 15:28:11 - MANUAL - INFO - Audio detected for stream #1: ac3 [und].
> 2016-10-06 15:28:11 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
> 2016-10-06 15:28:11 - MANUAL - INFO - Audio track is number 0 setting disposition to default
> 2016-10-06 15:28:11 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
> 2016-10-06 15:28:11 - MANUAL - INFO - Audio Track is number 1 setting disposition to none
> 2016-10-06 15:28:11 - MANUAL - INFO - Reading subtitle streams.
> 2016-10-06 15:28:11 - MANUAL - INFO - {
>     "preopts": [
>         "-fix_sub_duration"
>     ], 
>     "subtitle": {}, 
>     "format": "mp4", 
>     "postopts": [
>         "-threads", 
>         "auto"
>     ], 
>     "video": {
>         "map": 0, 
>         "codec": "h264", 
>         "bitrate": 2000, 
>         "level": 4.1
>     }, 
>     "audio": {
>         "0": {
>             "map": 1, 
>             "language": "eng", 
>             "channels": 2, 
>             "codec": "aac", 
>             "disposition": "default", 
>             "bitrate": 256, 
>             "filter": null
>         }, 
>         "1": {
>             "map": 1, 
>             "language": "eng", 
>             "channels": 6, 
>             "codec": "copy", 
>             "disposition": "none", 
>             "bitrate": 768, 
>             "filter": null
>         }
>     }
> }
> 2016-10-06 15:28:11 - MANUAL - INFO - Starting conversion.

This is the mediainfo.

>  General
> Complete name                            : H:\TV\Arrow\Season 05\Arrow S05E01 Legacy WEBDL-1080p.mp4
> Format                                   : MPEG-4
> Format profile                           : Base Media
> Codec ID                                 : isom (isom/iso2/avc1/mp41)
> File size                                : 798 MiB
> Duration                                 : 42 min 22 s
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 2 635 kb/s
> Writing application                      : Lavf57.51.102
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L4.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 4 frames
> Codec ID                                 : avc1
> Codec ID/Info                            : Advanced Video Coding
> Duration                                 : 42 min 22 s
> Bit rate                                 : 2 000 kb/s
> Width                                    : 1 916 pixels
> Height                                   : 1 076 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (23976/1000) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.040
> Stream size                              : 604 MiB (76%)
> Title                                    : Arrow.S05E01.1080p.WEB-DL.DD5.1.H264-RARBG
> Writing library                          : x264 core 148 r2721 72d53ab
> Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=2000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
> Language                                 : English
> 
> Audio #1
> ID                                       : 2
> Format                                   : AAC
> Format/Info                              : Advanced Audio Codec
> Format profile                           : LC
> Codec ID                                 : 40
> Duration                                 : 42 min 22 s
> Duration_LastFrame                       : -11 ms
> Bit rate mode                            : Variable
> Bit rate                                 : 251 kb/s
> Maximum bit rate                         : 256 kb/s
> Channel(s)                               : 2 channels
> Channel positions                        : Front: L R
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 46.875 FPS (1024 spf)
> Compression mode                         : Lossy
> Stream size                              : 75.9 MiB (10%)
> Title                                    : Arrow.S05E01.1080p.WEB-DL.DD5.1.H264-RARBG
> Language                                 : English
> Default                                  : Yes
> Alternate group                          : 1
> 
> Audio #2
> ID                                       : 3
> Format                                   : AC-3
> Format/Info                              : Audio Coding 3
> Mode extension                           : CM (complete main)
> Format settings, Endianness              : Big
> Codec ID                                 : ac-3
> Duration                                 : 42 min 22 s
> Bit rate mode                            : Constant
> Bit rate                                 : 384 kb/s
> Channel(s)                               : 6 channels
> Channel positions                        : Front: L C R, Side: L R, LFE
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 31.250 FPS (1536 spf)
> Bit depth                                : 16 bits
> Compression mode                         : Lossy
> Stream size                              : 116 MiB (15%)
> Title                                    : Arrow.S05E01.1080p.WEB-DL.DD5.1.H264-RARBG
> Language                                 : English
> Default                                  : No
> Alternate group                          : 1

When I look at the log for both the thing that stands out to me is this bit

> "audio": {
>         "0": {
>             "map": 1, 
>             "language": "eng", 
>             "channels": 2, 
>             "codec": "copy", 
>             **_"disposition": "default", 
>             "bsf": "aac_adtstoasc", 
>             "bitrate": 256,_** 
>             "filter": null

This only appears on each and every file that has failed to convert correctly and only for them files every other file I throw at it do not have that "bsf: aac_adtstoasc" part.

Really sorry for such a long post but I think the more info I can give the better :)

**Comment by mdhiggins** [comment]
the aac_adtstoasc bitstream filter is triggered when copying an AAC stream
Its required per the FFMPEG documentation as listed here
```
Convert MPEG-2/4 AAC ADTS to MPEG-4 Audio Specific Configuration bitstream filter.

This filter creates an MPEG-4 AudioSpecificConfig from an MPEG-2/4 ADTS header and removes the ADTS header.

This is required for example when copying an AAC stream from a raw ADTS AAC container to a FLV or a MOV/MP4 file.
```

It may be that there's a problem with the particular build of FFMPEG you're using causing issues with this filter

I would first try a stable build and see if it resolves (not a nightly)

Then if that fails I would try disabling this feature (remove lines 410 and 411 in mkvtomp4.py)

Give that a try and let me know
