### ISSUE TITLE
ConfigParser Error Ubuntu 16.04

### ISSUE THREAD

**Issue by jstraw4663** [mdhiggins/sickbeard_mp4_automator#573]
Good afternoon,

I am having an issue when using this script on a fresh install of 16.04 Ubuntu. I have installed all of the dependencies and configured it properly to work with Sonarr and NZBget but I am getting this error when running it through NZBget.  I am able to manually run the script on files without issue. Here is the [PasteBin link](http://pastebin.com/VZ4d0UJr) or the same error log is pasted below. (note, it is in reverse order). 

I am having no luck trying to solve any of the error messages.  If there is somewhere else I should post this such as a forum post then I would gladly do that.

Thank you!
Jeremy 

`ERROR   Tue Oct 11 2016 11:16:46    Post-process-script NZBGetPostProcess.py for Bobs.Burgers.S07E02.PROPER.720p.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: ConfigParser.NoSectionError: No section: 'formatters'
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: raise NoSectionError(section)
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: flist = cp.get("formatters", "keys")
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: formatters = _create_formatters(cp)
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: fileConfig(os.path.join(MP4folder, 'logging.ini'), defaults={'logfilename': os.path.join(MP4folder, 'info.log')})
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: File "/home/plex/Scripts/sickbeard_mp4_automator/NZBGetPostProcess.py", line 65, in <module>
INFO    Tue Oct 11 2016 11:16:46    NZBGetPostProcess: Traceback (most recent call last):
INFO    Tue Oct 11 2016 11:16:45    Executing post-process-script NZBGetPostProcess.py for Bobs.Burgers.S07E02.PROPER.720p.HDTV.x264-KILLERS`

**Comment by mdhiggins** [comment]
Looks like you have a bad logging.ini file, I would try replacing it with the stock one

**Comment by jstraw4663** [comment]
Thanks for the quick reply, I don't think that was it, I tried deleting the logging.ini file and creating my own with the content that was in it, copying just the one from the repo and cloning the entire repo again  into a separate folder and only reusing the autoProcess.ini file and I am still getting the same issue, I'm at a loss

**Comment by mdhiggins** [comment]
Does your logging.ini file have a [formatters] section?

Also I'm wondering if it's maybe a weird permissions issue and it's unable to read the file? It's very strange if the file is completely intact

**Comment by mdhiggins** [comment]
Yeah a quick glance shows that ConfigParser will throw this no section error if it's unable to read to access the file or if it can't find the file for some reason

**Comment by jstraw4663** [comment]
It can't find the file, as in the logger.ini file?  Attached is my logging.ini file (I just zipped it because github wouldn't accept .ini files) and a screenshot of my permissions for the sickbeard_mp4_automator folder. I am running everything as my plex user (nzbget, plex, sonarr, etc) but it has sudo permissions and everything has been installed using the plex user/group.

[logging.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/524258/logging.zip)

![image 1](https://cloud.githubusercontent.com/assets/7302419/19308548/2ee17b12-904e-11e6-9f6c-5229fc70edc4.png)

**Comment by mdhiggins** [comment]
Not sure why you're getting this error. Do you get the same error if you run manual.py and try to process a file?
