### ISSUE TITLE
Avi - An unexpected error occured

### ISSUE THREAD

**Issue by iamgithub99** [mdhiggins/sickbeard_mp4_automator#574]
Avi files are giving me the following message:

`An unexpected error occurred, processing of this file has failed.
ReadSettings instance has no attribute 'threads'`

That's the extent of the info provided.  And I have no idea as to what the cause/fix might be. :)

**Comment by mdhiggins** [comment]
Seems like your readsettings.py file is out of date compared to some other part of your script. Did you selectively only update some of the files? Save your autoProcess.ini and do a fresh install from GitHub.

**Comment by iamgithub99** [comment]
Thanks.  Reinstalled to make sure and all good again.

Cheers.
