### ISSUE TITLE
Disable 5.1 audio

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#576]
Is it possible to create the new file without surround sound? I would like to create it with just ios compatible  stream and remove surround sound.

**Comment by zybeon** [comment]
I urge you to read through the settings file or the main page as it has descriptions of all the options. You can denote the max number of audio channels, the bitrate per channel, and the codec. In short, don't use the ios feature just set the max audio channels to 2, and the codec to AAC.

I will also add that audio streams don't take up much room and would suggest keeping the surround sound audio stream and use the ios compatibility function. A year from now you might decide you want it and the only way to get it back is to reacquire the media.

**Comment by mdhiggins** [comment]
Thanks for the detailed response @zybeon
