### ISSUE TITLE
video-bitrate and max-video-width seems to set the bitrate and width instead of using as max

### ISSUE THREAD

**Issue by tomhumphrey** [mdhiggins/sickbeard_mp4_automator#581]
All my videos that are being converted seem to be using the bitrate and width that is specified in the autoprocess.ini file instead of being used as a maximum value. All videos are either upscaled or downscaled to match these values.

Expected usage:
The values are used as max values so only if the bitrate of the source exceeds this rate will it be transcoded down and likewise with the width of the source

**Comment by mdhiggins** [comment]
Unable to reproduce this, can you post the ffprobe -show_streams output for both the before and after files as well as your full autoProcess.ini file
