### ISSUE TITLE
[feature request] select output for manual.py

### ISSUE THREAD

**Issue by elgallo** [mdhiggins/sickbeard_mp4_automator#583]
excuse me if i missed something in the readme.

currently I have to change autoProcess.ini whenever I switch between processing TV or movies. 

example

`$ /path/to/manual.py -i /path/to/movie -a`
movies are processed to ~/processed
same with TV shows ending up in ~/processed

I'd like to be able to set the output to ~/processed/movie or ~/processed/tv per instance, instead of a single folder with both types mingled.

**Comment by meks007** [comment]
Hi,
I'm currently working on this on my fork.
You'll be able to utilize the Copy-to option like: `copy-to=movie:/path/to/movie|tv:/path/to/tv|/path/to/both`

This would translate to:
If its tagged as movie - copy the output to /path/to/movie
If its tagged as tv - copy the output to /path/to/tv
For both tag types create an additional copy in /path/to/both

I'll provide a commit for this in the next couple days.

Meanwhile check this commit for how it's supposed to work:
[https://github.com/meks007/sickbeard_mp4_automator/commit/32ca125792fc0edac04a47296b5afa1eeec7337c]

**Comment by meks007** [comment]
Just a note that this feature is finished with the latest commit finished in my fork: 
https://github.com/meks007/sickbeard_mp4_automator/commit/f6b409a6a6f58dbb08a3f9fa55ad3ff63f9ab193

**Comment by mdhiggins** [comment]
Are you using CouchPotato or Sickbeard/Sonarr/Sickrage?

If so the preferred method of achieving what you want would be to do a manual process with those media managers which will in turn execute the script and provide the appropriate metadata instead of guessing based on filename and having to rely on manual.py
