### ISSUE TITLE
Post-Processing won't start

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#584]
Traceback (most recent call last):
  File "/var/hda/web-apps/sickbeard/html/autoProcessTV/SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr
ImportError: No module named autoprocess

Any ideas what's wrong? This is the error presented in SABnzbd log

**Comment by mdhiggins** [comment]
Do you have the autoprocess directory in your script folder with all the files inside it that are on git?

**Comment by justinglock40** [comment]
No i didn't, but I figured that out at like 3 in the morning so I'm going to try again later and report back. 

As for categories though, if I'm only using Sickbeard and CP, do I need to keep my old post processing stuff that was set to "tv" and "movies"? Or will your SABnzb Post Process.py handle everything?

**Comment by justinglock40** [comment]
So I got the script and everything where it needs to be to execute, but it's taking an extremely long time to remux. Is there anyway to check the progress of the the script or see what it is doing?

**Comment by meks007** [comment]
You could try enabling debugging and pasting the output of your logfile after completing a full conversion run of one file.

Could you try enabling debugging by renaming your logging.ini file and replacing it using this version:
https://github.com/meks007/sickbeard_mp4_automator/blob/master/logging.ini

**Comment by mdhiggins** [comment]
Is it only remuxing or is there conversion taking place as well? If so what kind of conversion? (Video/audio?) Additionally what kind of hardware are you running your server on?

**Comment by justinglock40** [comment]
So I decided to install Sonarr, but when SAB returns the file for renaming it just says this: 

2016-10-31 23:03:05 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-10-31 23:03:05 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/var/hda/files/drives/3TB/newsgroups/complete/Transformers.Prime.S01E12.1080p.BluRay.x264-DEiMOS'.
2016-10-31 23:03:05 - autoprocess.sonarr - INFO - Sonarr response: queued.

Any Ideas?

**Comment by meks007** [comment]
Is this your output with debugging enabled? It's hard to tell with only the INFO level active.

**Comment by mdhiggins** [comment]
Based on that output it looks like your Sonarr settings are correct and the script is talking to the API

Does anything pop up in the Sonarr logs? Does the file get renamed or moved from its download path to the final destination configured in Sonarr?

**Comment by justinglock40** [comment]
No it says that permission is denied to my newsgroup completion folder? I tried chmod still no avail. Any other ideas?

**Comment by mdhiggins** [comment]
Gotta be a little more specific

What chmod settings are you using? Does the account that’s running Sonarr have read/write permissions to that directory? Can you post the log files you’re seeing

**Comment by justinglock40** [comment]
I don't have access to the logs right now but how would I check to see if the user:group has read and write perms. 

For chmod I tried 775 & 777.

**Comment by mdhiggins** [comment]
What OS are you attempting this setup on? (also is it a NAS)

I would think 777 should work but I would definitely double check everything and post the complete logs when you can

**Comment by justinglock40** [comment]
Fedora 23 with Amahi over top

**Comment by justinglock40** [comment]
Here is the log:

Import failed, path does not exist or is not accessible by Sonarr: /var/hda/files/drives/3TB/newsgroups/complete/Pitch.S01E05.720p.HDTV.x264-FLEET-Obfuscated/

**Comment by justinglock40** [comment]
Here's more detailed output:

16-11-1 08:31:16.8|Info|Sabnzbd|Adding report [Code.Black.S02E03.Corporeal.Form.1080p.WEB-DL.DD5.1.H264-NTb] to the queue. 
16-11-1 08:31:17.4|Info|DownloadService|Report sent to SABnzbd. Code.Black.S02E03.Corporeal.Form.1080p.WEB-DL.DD5.1.H264-NTb 
16-11-1 08:31:18.0|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded. 
16-11-1 08:34:45.7|Warn|ImportApprovedEpisodes|Couldn't import episode /var/hda/files/drives/3TB/newsgroups/complete/Code.Black.S02E03.Corporeal.Form.1080p.WEB-DL.DD5.1.H264-NTb/Code.Black.S02E03.Corporeal.Form.1080p.WEB-DL.DD5.1.H264-NTb.mp4 
[v2.0.0.4374] System.UnauthorizedAccessException: Access to the path is denied. at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00140] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
 at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e3] in <126b6b1ea0b442fe8ec3d8ce154ba93e>:0 
 at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified (System.String sourcePath, System.String targetPath, System.Int64 originalSize) [0x00000] in <126b6b1ea0b442fe8ec3d8ce154ba93e>:0

**Comment by mdhiggins** [comment]
Looks like it might actually be related to your destination directory not having write permissions than the download directory as initially implied

Make sure you have adequate permissions for both source and destination directory for the account Sonarr is running

**Comment by justinglock40** [comment]
Ok. So I fixed the permissions issue so SAB is succesfully sending back to Sonarr queue and now it's throw an error in the postSonarr.py script. Here is the output:

16-11-1 18:31:03.4|Info|Sabnzbd|Adding report [Ballers.2015.S02E09.iNTERNAL.720p.HDTV.x264-TURBO] to the queue.
16-11-1 18:31:04.0|Info|DownloadService|Report sent to SABnzbd. Ballers.2015.S02E09.iNTERNAL.720p.HDTV.x264-TURBO
16-11-1 18:31:04.3|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded.
16-11-1 18:31:12.2|Info|DownloadDecisionMaker|Processing 400 releases
16-11-1 18:31:13.2|Info|RssSyncService|RSS Sync Completed. Reports found: 400, Reports grabbed: 0
**_16-11-1 18:32:36.5|Error|postSonarr.py|Traceback (most recent call last):
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/home/(removed)/Scripts/sickbeard_mp4_automator/postSonarr.py", line 12, in <module>
16-11-1 18:32:36.5|Error|postSonarr.py|    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/config.py", line 85, in fileConfig
16-11-1 18:32:36.5|Error|postSonarr.py|    handlers = _install_handlers(cp, formatters)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/config.py", line 163, in _install_handlers
16-11-1 18:32:36.5|Error|postSonarr.py|    h = klass(*args)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/handlers.py", line 117, in __init__
16-11-1 18:32:36.5|Error|postSonarr.py|    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
16-11-1 18:32:36.5|Error|postSonarr.py|    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/__init__.py", line 905, in __init__
16-11-1 18:32:36.5|Error|postSonarr.py|    StreamHandler.__init__(self, self._open())
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/__init__.py", line 935, in _open
16-11-1 18:32:36.5|Error|postSonarr.py|    stream = open(self.baseFilename, self.mode)
16-11-1 18:32:36.5|Error|postSonarr.py|IOError: [Errno 13] Permission denied: '/home/jwashington/Scripts/sickbeard_mp4_automator/info.log'_**

**Comment by justinglock40** [comment]
Think it's the same issue here perms?

**Comment by meks007** [comment]
fix 777 on '/home/jwashington/Scripts/sickbeard_mp4_automator/info.log'
 
On 2 Nov 2016 12:38 a.m., justinglock40 <notifications@github.com> wrote:Ok. So I fixed the permissions issue so SAB is succesfully sending back to Sonarr queue and now it's throw an error in the postSonarr.py script. Here is the output:

16-11-1 18:31:03.4|Info|Sabnzbd|Adding report [Ballers.2015.S02E09.iNTERNAL.720p.HDTV.x264-TURBO] to the queue.
16-11-1 18:31:04.0|Info|DownloadService|Report sent to SABnzbd. Ballers.2015.S02E09.iNTERNAL.720p.HDTV.x264-TURBO
16-11-1 18:31:04.3|Info|EpisodeSearchService|Episode search completed. 1 reports downloaded.
16-11-1 18:31:12.2|Info|DownloadDecisionMaker|Processing 400 releases
16-11-1 18:31:13.2|Info|RssSyncService|RSS Sync Completed. Reports found: 400, Reports grabbed: 0
16-11-1 18:32:36.5|Error|postSonarr.py|Traceback (most recent call last):
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/home/(removed)/Scripts/sickbeard_mp4_automator/postSonarr.py", line 12, in 
16-11-1 18:32:36.5|Error|postSonarr.py|    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log')})
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/config.py", line 85, in fileConfig
16-11-1 18:32:36.5|Error|postSonarr.py|    handlers = install_handlers(cp, formatters)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/config.py", line 163, in _install_handlers
16-11-1 18:32:36.5|Error|postSonarr.py|    h = klass(*args)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/handlers.py", line 117, in __init
16-11-1 18:32:36.5|Error|postSonarr.py|    BaseRotatingHandler.init(self, filename, mode, encoding, delay)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/handlers.py", line 64, in init
16-11-1 18:32:36.5|Error|postSonarr.py|    logging.FileHandler.init(self, filename, mode, encoding, delay)
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/init.py", line 905, in init
16-11-1 18:32:36.5|Error|postSonarr.py|    StreamHandler.init(self, self.open())
16-11-1 18:32:36.5|Error|postSonarr.py|  File "/usr/lib64/python2.7/logging/__init_.py", line 935, in open
16-11-1 18:32:36.5|Error|postSonarr.py|    stream = open(self.baseFilename, self.mode)
16-11-1 18:32:36.5|Error|postSonarr.py|IOError: [Errno 13] Permission denied: '/home/jwashington/Scripts/sickbeard_mp4_automator/info.log'

**Comment by justinglock40** [comment]
Tried returned:

**_[root@localhost ~]# chmod 777 -v /home/jwashington/Scripts/sickbeard_mp4_automator/info.log
chmod: cannot access ‘/home/jwashington/Scripts/sickbeard_mp4_automator/info.log’: No such file or directory
failed to change mode of ‘/home/jwashington/Scripts/sickbeard_mp4_automator/info.log’ from 7642 (rwSr-S-wT) to 3400 (r----S--T)_**

**Comment by justinglock40** [comment]
Ok. SO that worked everything is happening as it should be. No errors in logs. Thanks man you're the best.

I just have a few other questions and you can mark this SOLVED.

Is the PostProcess script designed to clear the SABnzbd history after successful processing or is it done manually? I know that CP automatically clears SAB history.

Is there anyway to clear this system flag in Sonarr since the script asks that it be turned off?: Enable Completed Download Handling or configure Drone factory

And how do I setup up remuxing for h265/x265 files?

**Comment by mdhiggins** [comment]
It won't clear the SAB history but will make it as complete (the SABPostProcessing script should handle this)

The same can be said about SABPostProcessing passing the file back to Sonarr. This is why you don't need the "Completed Download Handling" if that script is properly setup

And remuxing h265 just add that to your list of video codecs (see the readme) and it will be remuxed when found

**Comment by justinglock40** [comment]
Ok thanks man you guys have been very helpful with getting me setup appropriately.

**Comment by mdhiggins** [comment]
Enjoy! Hope your setup is now more automated

**Comment by justinglock40** [comment]
Its almost completely automated now. I just need to figure out Headphones and I’ll be 100% good.
