### ISSUE TITLE
File The Movie.m4v -a is not in the correct format

### ISSUE THREAD

**Issue by osuhickeys** [mdhiggins/sickbeard_mp4_automator#585]
I am using Handbrake to digitize my personalize DVD collection.  I have done about 40 movies.  I am using manual.py to postprocess them.  Six of the 40 movies I have done get the following error: "File The Movie.m4v -a is not in the correct format".

Info.text was not very helpful either.  Only 3 entries with no smoking gun.

2016-10-31 13:10:15 - MANUAL - INFO - Manual processor started.
2016-10-31 13:10:15 - MANUAL - INFO - C:\Python27\python.exe
2016-10-31 13:10:15 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.

Not sure if there is more logging available?  Anyone have any ideas?

**Comment by mdhiggins** [comment]
Do the files that the script appears to fail on have special characters in their filenames compared to the ones that are working?

**Comment by osuhickeys** [comment]
No.  I really wanted to just use the script to update the cover art and metadata.  I added the -imdb and put the ID in the script for the movies I looked up manually and then ran a script to update the ones in question.  That accomplished what I was ultimately trying to do.

It is a bit odd.  Most processed the art work and did the Relocating MOOV atom to start of file the first run through.  When I went back to some that failed and ran again I got the following:

Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.
2016-11-01 06:31:12 - qtfaststart - ERROR - This file appears to already be setup for streaming!
QT FastStart did not run - perhaps moov atom was at the start already.

First time through it converted, but did not write the tags.  Second time through it updated the tags and recognized the it converted the first time through.  Other files it did not update the tags the second time and failed to covert the first time or the second time and I get File The Movie.m4v -a is not in the correct format.

Same script, no changes.  I am running this on an older NAS with SATA drives in it.  Wondering if I am dealing with some timeout issues.  It akes 5+ minutes to write the tags as an example.  Also, cannot rule out I did something wrong and am just not seeing it in my script.

What does the Relocating MOOV atom to start of file?  Is that something that provides benefit if the file was created with Handbrake and is already in m4v format?  That step takes quite a bit of time.  If it is not needed, is there a way to have it not do that using the manual script?  I do not see a true/false option or equivalent in the ini, only a way to set the preferred extension.  I am probably missing it.

Adding the -imdb option in my script has accomplished my objective so this issue can be closed.  Appreciate the help!  Awesome script!!!!!

**Comment by mdhiggins** [comment]
Relocating the MOOV atom to the beginning of the file is useful for some streaming scenarios but not required

`relocate_moov = True` is an option in the autoProcess.ini settings under the MP4 section that can be disabled if you do not desire this feature
