### ISSUE TITLE
Integrate with DVE for faster processing

### ISSUE THREAD

**Issue by ajhalls** [mdhiggins/sickbeard_mp4_automator#586]
This little shell script will let you distribute encoding to multiple servers which can drastically improve encoding speeds. Since you built an automator we can assume there are a LOT of videos that need to be encoded which would benefit from this approach :) It isn't my code, I stumbled across it and got nearly a 3X decrease in encoding times.

https://github.com/Sonic-Y3k/dve

**Comment by mdhiggins** [comment]
Very cool project but integrating would be a big task and probably beyond the scope of what this project is looking to do. Perhaps in a later version when I have more time but not for now. I'll be keeping an eye on that project though
