### ISSUE TITLE
Sonarr Video File issues

### ISSUE THREAD

**Issue by medjai** [mdhiggins/sickbeard_mp4_automator#587]
Video files never seem to get imported via Sonarr I always run into this error then i am forced to use Sickbeard to get the file to import properly.

Please see the following logs: http://pastebin.com/T54C1eqZ

**Comment by mdhiggins** [comment]
I see the postSonarr script running here multiple times indicating Sonarr is being notified and running its post processing script as it should. Your post Plex notification is failing and there are some errors here related to your move-to option because the destination file already exists but I don't see anything wrong with Sonarr notifications

**Comment by medjai** [comment]
The file never ends up though in directory I'm not sure why.

During processing I will see the file with the .mp4.qst (might be the wrong
extension I'm recalling). Then at the end both the original and that file
are gone from the destination directory

**Comment by mdhiggins** [comment]
It almost looks like your file is moved to the appropriate location then the script is trying to move it back to your downloads directory? Maybe your move-to settings aren't quite what they should be

Post your autoProcess.ini file and gimme some references to your directory structure for downloads/completed files

**Comment by medjai** [comment]
Michael,

You're correct my move_to for some reason was pointed to the completed
downloads folder... Why is that even being used and triggered, can you help
me understand? I guess I overlooked this because the sickbeard post-process
never used this variable? I am just now moving from sickbeard to sonarr

**Comment by mdhiggins** [comment]
Sickbeard uses this as well just like Sonarr does, the behavior should be identical

**Comment by medjai** [comment]
Is it possible then my sickbeard was never properly setup?

Anyway its fixed and thank you for picking this issue up. I guess I
overlooked this in the logs.

You've been an awesome help over the years! Really awesome contribution to
the community!
