### ISSUE TITLE
CouchPotato Post Process

### ISSUE THREAD

**Issue by dannyd7139** [mdhiggins/sickbeard_mp4_automator#588]
`[ PostProcess] Executing post processing on file /media/clouddrive/Movies/Hackers (1995)/Hackers (1995)_BR-Rip.mp4 with IMDB ID tt0113243
[ PostProcess] MP4 Automator - Post processing script initialized
[ PostProcess] 2016-11-02 09:16:20 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized 2016-11-02 09:16:20 - CouchPotatoPostConversion - INFO - Processing file: /media/clouddrive/Movies/Hackers (1995)/Hackers (1995)_BR-Rip.mp4 2016-11-02 09:16:20 - CouchPotatoPostConversion - INFO - Moving file from /media/clouddrive/Movies/Hackers (1995)/Hackers (1995)_BR-Rip.mp4 to /media/clouddrive/movies/hackers (1995)/hackers (1995)_br-rip.mp4 2016-11-02 09:16:20 - CouchPotatoPostConversion - ERROR - File processing failed: /media/clouddrive/Movies/Hackers (1995)/Hackers (1995)_BR-Rip.mp4 Traceback (most recent call last): File "/opt/sickbeard_mp4_automator/postCouchPotato.py", line 32, in <module> os.rename(inputfile, inputfile.lower()) OSError: [Errno 2] No such file or directory
[tato.core.plugins.scanner] Found 1 movies in the folder /media/clouddrive/Movies/Hackers (1995)`

I'm assuming this function is failing because it is searching for the file under lowercase? Is there a reason why this needs to be passed into the os.rename function this way? I've confirmed the file is there, however it is named under the original designation found in the log next to the Processing file tag. CouchPotato confirms this in the log as well but doesn't mark it completed.

Is this an incorrect configuration on my part? Thanks

**Comment by mdhiggins** [comment]
The lowercase issue was reverted in an update to the script back in June to correct this exact problem
Just update your script to the latest version
