### ISSUE TITLE
FFMpegConvertError on MKV files

### ISSUE THREAD

**Issue by dmartinez7500** [mdhiggins/sickbeard_mp4_automator#590]
I've been running the manual.py script through another automated script, in an attempt to clean up my media collection. Recently, it's stopped working for some reason, giving the below error on any file it comes across.

```
2016-11-04 13:39:53 - MANUAL - INFO - Starting conversion.
2016-11-04 13:39:54 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "D:\scripts\sickbeard_mp4_automator-master\mkvtomp4.py", line 644, in convert
    for timecode in conv:
  File "D:\scripts\sickbeard_mp4_automator-master\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "D:\scripts\sickbeard_mp4_automator-master\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=6300, cmd="D:\scripts\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i M:\Toy Story of Terror (2013)\Toy Story of Terror (2013).mkv -vcodec libx264 -map 0:0 -vb 9981k -level 4.0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 aac -map 0:1 -disposition:a:1 none -ac:a:1 8 -b:a:1 1536k -metadata:s:a:1 language=eng -strict experimental -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:3 -metadata:s:s:1 language=eng -f mp4 -threads auto -y M:\Toy Story of Terror (2013)\Toy Story of Terror (2013).mp4">
```

Not sure what could have changed, as I've been running this script for just over a month now, on and off, with no issues. I did try to run manual.py on it's own, but got the same error. Attached the log file and autoProcess.ini file in a ZIP here. No settings have been changed at all. Running this on Windows 7 if it makes a difference.

[autoProcess.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/572276/autoProcess.zip)

**Comment by mdhiggins** [comment]
Looks like you're running an older version of the script. The latest has more debugging output which will help you pinpoint what's going on.
