### ISSUE TITLE
no audio after conversion

### ISSUE THREAD

**Issue by twistedatoms** [mdhiggins/sickbeard_mp4_automator#591]
so I am having a problem where if i convert this file it will end up have no audio streams below is my .ini file and below that is an output of ffmpeg showing the original stream information of the file. I'm not sure if this is a bug or a problem with my settings.

autoProcess.ini
[MP4]
ffmpeg = /opt/ffmpeg/ffmpeg
ffprobe = /opt/ffmpeg/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = aac
ios-first-track-only = False
ios-audio-filter =
max-audio-channels = 6
audio-codec = ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = eng
download-artwork = False
download-subs = True
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

========================================
ffmpeg -i filename.mkv

Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-10-20T19:56:14.000000Z
  Duration: 00:23:25.48, start: 0.000000, bitrate: 5287 kb/s
    Stream #0:0(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 157242
      BPS-eng         : 157242
      DURATION        : 00:23:25.482000000
      DURATION-eng    : 00:23:25.482000000
      NUMBER_OF_FRAMES: 65882
      NUMBER_OF_FRAMES-eng: 65882
      NUMBER_OF_BYTES : 27625272
      NUMBER_OF_BYTES-eng: 27625272
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Video: h264 (High), yuv420p(tv, bt709), 1916x1076 [SAR 1:1 DAR 479:269], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      BPS             : 5127696
      BPS-eng         : 5127696
      DURATION        : 00:23:25.446000000
      DURATION-eng    : 00:23:25.446000000
      NUMBER_OF_FRAMES: 33697
      NUMBER_OF_FRAMES-eng: 33697
      NUMBER_OF_BYTES : 900837501
      NUMBER_OF_BYTES-eng: 900837501
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      BPS             : 88
      BPS-eng         : 88
      DURATION        : 00:22:55.973000000
      DURATION-eng    : 00:22:55.973000000
      NUMBER_OF_FRAMES: 407
      NUMBER_OF_FRAMES-eng: 407
      NUMBER_OF_BYTES : 15225
      NUMBER_OF_BYTES-eng: 15225
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

**Comment by mdhiggins** [comment]
Can you post an ffprobe -show_streams of the inputfile as well as the main console output when you run this through manual.py? That'll be helpful. Your settings look ok I don't see anything grossly wrong.

**Comment by twistedatoms** [comment]
ffprobe version N-82049-gd871686-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-2) 20160904
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libebur128 --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 63.103 / 57. 63.103
  libavformat    57. 52.100 / 57. 52.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 64.100 /  6. 64.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from '0f9ab67f6d59439ba57dbe711c6ad77f.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-10-20T19:56:14.000000Z
  Duration: 00:23:25.48, start: 0.000000, bitrate: 5287 kb/s
    Stream #0:0(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 157242
      BPS-eng         : 157242
      DURATION        : 00:23:25.482000000
      DURATION-eng    : 00:23:25.482000000
      NUMBER_OF_FRAMES: 65882
      NUMBER_OF_FRAMES-eng: 65882
      NUMBER_OF_BYTES : 27625272
      NUMBER_OF_BYTES-eng: 27625272
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Video: h264 (High), yuv420p(tv, bt709), 1916x1076 [SAR 1:1 DAR 479:269], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      BPS             : 5127696
      BPS-eng         : 5127696
      DURATION        : 00:23:25.446000000
      DURATION-eng    : 00:23:25.446000000
      NUMBER_OF_FRAMES: 33697
      NUMBER_OF_FRAMES-eng: 33697
      NUMBER_OF_BYTES : 900837501
      NUMBER_OF_BYTES-eng: 900837501
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      BPS             : 88
      BPS-eng         : 88
      DURATION        : 00:22:55.973000000
      DURATION-eng    : 00:22:55.973000000
      NUMBER_OF_FRAMES: 407
      NUMBER_OF_FRAMES-eng: 407
      NUMBER_OF_BYTES : 15225
      NUMBER_OF_BYTES-eng: 15225
      _STATISTICS_WRITING_APP: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.5.2 ('Crosses') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-10-20 19:56:14
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-10-20 19:56:14
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[STREAM]
index=0
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/1000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:BPS=157242
TAG:BPS-eng=157242
TAG:DURATION=00:23:25.482000000
TAG:DURATION-eng=00:23:25.482000000
TAG:NUMBER_OF_FRAMES=65882
TAG:NUMBER_OF_FRAMES-eng=65882
TAG:NUMBER_OF_BYTES=27625272
TAG:NUMBER_OF_BYTES-eng=27625272
TAG:_STATISTICS_WRITING_APP=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_APP-eng=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_DATE_UTC=2016-10-20 19:56:14
TAG:_STATISTICS_WRITING_DATE_UTC-eng=2016-10-20 19:56:14
TAG:_STATISTICS_TAGS=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
TAG:_STATISTICS_TAGS-eng=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[/STREAM]
[STREAM]
index=1
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_time_base=1001/48000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1916
height=1076
coded_width=1916
coded_height=1076
has_b_frames=1
sample_aspect_ratio=1:1
display_aspect_ratio=479:269
pix_fmt=yuv420p
level=40
color_range=tv
color_space=bt709
color_transfer=bt709
color_primaries=bt709
chroma_location=topleft
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=24000/1001
avg_frame_rate=24000/1001
time_base=1/1000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:BPS=5127696
TAG:BPS-eng=5127696
TAG:DURATION=00:23:25.446000000
TAG:DURATION-eng=00:23:25.446000000
TAG:NUMBER_OF_FRAMES=33697
TAG:NUMBER_OF_FRAMES-eng=33697
TAG:NUMBER_OF_BYTES=900837501
TAG:NUMBER_OF_BYTES-eng=900837501
TAG:_STATISTICS_WRITING_APP=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_APP-eng=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_DATE_UTC=2016-10-20 19:56:14
TAG:_STATISTICS_WRITING_DATE_UTC-eng=2016-10-20 19:56:14
TAG:_STATISTICS_TAGS=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
TAG:_STATISTICS_TAGS-eng=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[/STREAM]
[STREAM]
index=2
codec_name=subrip
codec_long_name=SubRip subtitle
profile=unknown
codec_type=subtitle
codec_time_base=0/1
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=N/A
height=N/A
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/1000
start_pts=0
start_time=0.000000
duration_ts=1405482
duration=1405.482000
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:BPS=88
TAG:BPS-eng=88
TAG:DURATION=00:22:55.973000000
TAG:DURATION-eng=00:22:55.973000000
TAG:NUMBER_OF_FRAMES=407
TAG:NUMBER_OF_FRAMES-eng=407
TAG:NUMBER_OF_BYTES=15225
TAG:NUMBER_OF_BYTES-eng=15225
TAG:_STATISTICS_WRITING_APP=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_APP-eng=mkvmerge v8.5.2 ('Crosses') 64bit
TAG:_STATISTICS_WRITING_DATE_UTC=2016-10-20 19:56:14
TAG:_STATISTICS_WRITING_DATE_UTC-eng=2016-10-20 19:56:14
TAG:_STATISTICS_TAGS=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
TAG:_STATISTICS_TAGS-eng=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[/STREAM]

**Comment by twistedatoms** [comment]
and here is the output of the manual conversion

manual.py -i 0f9ab67f6d59439ba57dbe711c6ad77f.mkv -nd -tv 272472 -s 3 -e 25
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
No-delete enabled
Processing Paw Patrol Season 03 Episode 25 - Tracker Joins the Pups!
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #0: aac [eng].
Creating audio stream 0 from source stream 0.
Audio Track is number 0 setting disposition to default
Reading subtitle streams.
Subtitle detected for stream #2: subrip [eng].
Creating subtitle stream 0 from source stream 2.
Attempting to download subtitles.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {
        "0": {
            "map": 2,
            "codec": "mov_text",
            "language": "eng",
            "encoding": null
        }
    },
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "map": 1,
        "codec": "copy",
        "bitrate": 5287.415,
        "level": null
    },
    "audio": {
        "0": {
            "map": 0,
            "language": "eng",
            "channels": 2,
            "codec": "copy",
            "disposition": "default",
            "bsf": "aac_adtstoasc",
            "bitrate": 256,
            "filter": null
        }
    }
}
Starting conversion.
[######### ] 99%/media/183aa272-f0d8-4318-a92c-c98c31aa7c6e/Downloads/completed/sabnzbd/Paw.Patrol.S03E25.Tracker.Joins.the.Pups.1080p.WEB-DL.AAC2.0.H.264-BTN-BUYMORE/0f9ab67f6d59439ba57dbe711c6ad77f.mp4 created.
Tagging file: /media/183aa272-f0d8-4318-a92c-c98c31aa7c6e/Downloads/completed/sabnzbd/Paw.Patrol.S03E25.Tracker.Joins.the.Pups.1080p.WEB-DL.AAC2.0.H.264-BTN-BUYMORE/0f9ab67f6d59439ba57dbe711c6ad77f.mp4.
Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.

**Comment by twistedatoms** [comment]
if i import this plex tells me there is no audio streams

**Comment by mdhiggins** [comment]
It looks like the script is copying the AAC audio track from your source directly as it should be. Not sure why Plex is having a hard time. 

Does it show up in VLC?

And can you post the same type of ffprobe output for the newly generated file.

**Comment by twistedatoms** [comment]
VLC does not show it having an audio track either. below is a basic ffprobe -i of the new file.

ffprobe -i Paw\ Patrol\ -\ s03e25\ -\ Tracker\ Joins\ the\ Pups\!.mp4
ffprobe version N-82049-gd871686-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-2) 20160904
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libebur128 --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 63.103 / 57. 63.103
  libavformat    57. 52.100 / 57. 52.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 64.100 /  6. 64.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Paw Patrol - s03e25 - Tracker Joins the Pups!.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Tracker Joins the Pups!
    album           : Paw Patrol, Season 3
    date            : 2016-09-16
    encoder         : Lavf57.52.100
    genre           : Animation
    description     : The PAW Patrol's newest member, Tracker, helps find an ancient crown.
    synopsis        : The PAW Patrol's newest member, Tracker, helps find an ancient crown.
    show            : Paw Patrol
    episode_id      : Tracker Joins the Pups!
    network         : Nick Jr.
    episode_sort    : 25
    season_number   : 3
    media_type      : 10
    hd_video        : 2
    track           : 25/39
    disc            : 3
  Duration: 00:23:25.45, start: 0.000000, bitrate: 5131 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1916x1076 [SAR 1:1 DAR 479:269], 5127 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 32k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler

**Comment by twistedatoms** [comment]
just as a extra note this setup i have works great when there is a 5.1 channel stream. I will then get a 5.1 and a 2ch which is exactly what i'm wanting. but some of these 2ch aac only videos that come across have this problem. Obviously if the original doesn't have a 5.1ch stream im not going to get that. not sure if that helps.

**Comment by mdhiggins** [comment]
Can you mail me a link to one of these files so I can do some testing and see if I can reproduce these issues?

**Comment by ptowns188** [comment]
+1 from me on this one aswell, it only seems to be doing it when copying the audio stream. when conversion of the stream takes place everything goes as it should

**Comment by mdhiggins** [comment]
I routinely copy AAC streams without issue on my Plex setup. Someone send me a source file where this is happening so I can debug. Wonder if it's an FFMPEG build issue

**Comment by ptowns188** [comment]
I did recently upgraded ffmpeg I will downgrade it to a previous revision and let you know the outcome.
If still the same I will link you to the file when I get home tonight


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael Higgins <notifications@github.com> Date: 06/11/2016  12:14  (GMT+00:00) To: mdhiggins/sickbeard_mp4_automator <sickbeard_mp4_automator@noreply.github.com> Cc: ptowns188 <paultowns188@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [mdhiggins/sickbeard_mp4_automator] no audio after conversion (#591) 
I routinely copy AAC streams without issue on my Plex setup. Someone send me a source file where this is happening so I can debug. Wonder if it's an FFMPEG build issue



Sent from my iPhone



> On Nov 6, 2016, at 05:09, ptowns188 <notifications@github.com> wrote:

> 

> +1 from me on this one aswell, it only seems to be doing it when copying the audio stream. when conversion of the stream takes place everything goes as it should

> 

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

> 



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mdhiggins/sickbeard_mp4_automator","title":"mdhiggins/sickbeard_mp4_automator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mdhiggins/sickbeard_mp4_automator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mdhiggins in #591: I routinely copy AAC streams without issue on my Plex setup. Someone send me a source file where this is happening so I can debug. Wonder if it's an FFMPEG build issue\n\nSent from my iPhone\n\n\u003e On Nov 6, 2016, at 05:09, ptowns188 \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e +1 from me on this one aswell, it only seems to be doing it when copying the audio stream. when conversion of the stream takes place everything goes as it should\n\u003e \n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/mdhiggins/sickbeard_mp4_automator/issues/591#issuecomment-258677117"}}}

**Comment by dunkf** [comment]
I've noticed the same problem with some conversions. In plex the files with working aac audio show "Profile lc" and the ones that don't have "Profile ltp". it started after i re built last week so im going to downgrade ffmpeg to see if that's the problem

**Comment by twistedatoms** [comment]
Not sure which version you all are using. I'm using the static build release: 3.2

**Comment by twistedatoms** [comment]
just sent an email with the file i have been using to test these conversions.

**Comment by mdhiggins** [comment]
Alright figured out what was going on
Issue was being created by the aac_adtstoasc filter
Made using this filter option and defaulted it to false
Update your script and give it another try (making sure this option is set to false) and let me know

**Comment by twistedatoms** [comment]
Awesome this seemed to have resolved the issue. will this cause any problems down the road with this filter off?

**Comment by mdhiggins** [comment]
Nah
