### ISSUE TITLE
How to move files based on tag post_process?

### ISSUE THREAD

**Issue by wreckedred** [mdhiggins/sickbeard_mp4_automator#592]
After my files are converted to mp4 I would like TV to go to one directory and movies to go to a different directory. Suggestions?

**Comment by meks007** [comment]
https://github.com/meks007/sickbeard_mp4_automator#copy-to-and-move-to-by-file-type

**Comment by mdhiggins** [comment]
I'm guessing you're using manual.py instead of integrating the script with a media manager?
