### ISSUE TITLE
Fresh ubuntu 16.04 install - shutil.Error: src & dest are the same file

### ISSUE THREAD

**Issue by hyperexpert** [mdhiggins/sickbeard_mp4_automator#594]
Ive been trying to get this script to work all day and keep ending up with the same error. I even tried blowing away my VM and created new instance but ended up with the same error. When uTorrent finishes a download and calls the script, the script successfully converts my files but right at the end, I get

``File "/opt/sickbeard_mp4_automator/uTorrentPostProcess.py", line 159, in <module>
    shutil.copy(inputfile, newpath)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/home/user/downloads/movies/movie_folder/movie_folder/movie.mp4` and `/home/user/downloads/movies/movie_folder/movie_folder/movie.mp4` are the same file
``

I am downloading mp4's and telling the script to redo them `convert-mp4 = true`, I also noticed no matter what I put in the `output_directory` or `copy_to` or `move_to` fields, the script will ignore that and only process the file inside its parent folder by creating another subfolder with the same name.

I had this script working find on an older VM that I don't have anymore. Not sure what happened and why this is happening now.

**Comment by hyperexpert** [comment]
Ive noticed something else, in my autoProcess.ini file, if I change my `output_format = mp4` to `output_format=m4v`, it still outputs a mp4 file in a subfolder of the parent directory. It looks like no matter what I change in autoProcess.ini, nothing different happens.

**Comment by hyperexpert** [comment]
Some more progress. If I run the manual.py script against my movie directly, it will read my autoProcess.ini, converts the movie and move it once done. Not sure why the uTorrentPostProcess.py is not working though!

**Comment by mdhiggins** [comment]
`output-format` and `output-extension` are two different settings and you're mixing those options up.

As far as the uTorrent situation is concerned, that is exactly the intended behavior. Because the torrent programs are actively running and using the source file, it can't just overwrite them so it should create a subdirectory. Copy-to and move-to have no effect here as these options are handled at the end. The only one that will change where the files go is the output directory.

I did however add a new commit that renames the directory with a -convert suffix to hopefully prevent the error you're seeing when its an mp4 to mp4. Hope that helps, update and give it a try

**Comment by hyperexpert** [comment]
That didn't fix the issue. I downloaded the new changes (literally deleted everything and cloned your script again), same error. I do see the change you made `settings.output_dir = os.path.join(path, ("%s-convert" % name))` However, its not creating the "-convert" directory for me, still created the same name subdirectory. Also, no matter what I put in `output_directory`, it ignores it and just creates a subfolder instead

**Comment by mdhiggins** [comment]
Do you have multiple instances of the script and are perhaps executing the uTorrent portion from a different source?

**Comment by hyperexpert** [comment]
I am calling the uTorrent portion manually at the moment. Got tired of redownloading movies just to see if it worked or not! So what I am doing is: ` /opt/sickbeard_mp4_automator/uTorrentPostProcess.py "couchpotato" "udp://tracker.istole.it:80/announce" "/home/user/downloads/movies/movie_folder/" "multi" "/home/user/downloads/movies/movie_folder/" "C4CF33A4F4827C1A1E1CCCCEB04CE01A8A115473" "torrent_name"`

Wouldn't that be the same?

**Comment by hyperexpert** [comment]
and just one instance that resides in my /opt directory

**Comment by hyperexpert** [comment]
Ok, got this to work!. Not sure what the problem was. However, created a whole new vm with the latest script and it started working again! Thanks for all the help!
