### ISSUE TITLE
IOError Executing on Windows

### ISSUE THREAD

**Issue by CovertDad** [mdhiggins/sickbeard_mp4_automator#596]
I'm trying to get SMA working with my installation of SickRage on Windows.

When SickRage tries to do a post-process conversion, I get the following error:

`Absolute path to script: C:\Python27\python.exe
Executing command: [u'C:\\Python27\\python.exe', 'C:\\Python27\\Scripts\\sickbeard_mp4_automator\\postConversion.py', 'G:\\television\\American Horror Story\\Season.06\\American Horror Story.S06E02.720p.WEB.DL.mkv', 'C:\\Users\\Gabe\\Downloads\\complete\\tv\\American Horror Story.S06E02.720p.WEB.DL.mkv', '250487', '6', '2', '2016-09-21']
Script result: C:\Python27\python.exe: can't open file 'C:\Python27\Scripts\sickbeard_mp4_automator\postConversion.py': [Errno 13] Permission denied`

However, if I run it manually from the command prompt, it works perfectly.

Any ideas what could be happening to give me the Errno 13?

**Comment by mdhiggins** [comment]
Seems whatever account SickRage is being run on doesn't have permission to execute the script.

**Comment by CovertDad** [comment]
That was it, exactly.  Thanks for the pointer!
