### ISSUE TITLE
Conversions not multi-threading

### ISSUE THREAD

**Issue by twistedatoms** [mdhiggins/sickbeard_mp4_automator#597]
I have a fairly powerful server. dual proc with 24 cores total. when I'm running a manual conversion I noticed that it was only using one core. I have tried leaving it auto and also specifying 24 in the config and it doesn't seem to make a difference. I have attached a screenshot showing an example of this.

![threading_problem](https://cloud.githubusercontent.com/assets/2582672/20338860/e7666baa-ab85-11e6-84f4-ad19c73f172f.png)

**Comment by mdhiggins** [comment]
This is an FFMPEG issue. The script passes the documented commands to FFMPEG but can't dictate the behavior any further. Check your build of FFMPEG and I would otherwise advice posting on their forums for assistance.
