### ISSUE TITLE
[Quesiton] automator with blackhole

### ISSUE THREAD

**Issue by saitoh183** [mdhiggins/sickbeard_mp4_automator#602]
I use sonarr with sabnzbd and for torrents i use the blackhole setting in sonarr. Then i sync the torrent file to my seedbox and my rutorrent picks it up and syncthing sends the file back down to my machine. i have in the blackhole settings in sonarr i have it monitoring the folder that the file should arrive in. Can i still use automator in this case since sonarr isnt connected to the download client api for torrents but it is for nzb?

same question goes for cps

**Comment by mdhiggins** [comment]
Yeah you can. Just set up the postCouchPotato and postSonarr scripts and
ignore the downloader scripts. The downloader scripts are optional.

**Comment by saitoh183** [comment]
> Yeah you can. Just set up the postCouchPotato and postSonarr scripts and
ignore the downloader scripts. The downloader scripts are optional.

Im a bit confused on what to ignore? Do you mean to ignore the step 3 in the postSonarr setup in the Readme.md ? Also for Sabnzbd, do i just follow what the readme says? If i setup Sab portion of automator, i dont need DH of sonarr?

 Also i use sickrage with blackhole but i figured i just need to setup as the readme says and it should be fine? I have post-processing enabled and it runs every 10mins on my PP folder that i set. Do i need to disable it and just add the automator to the Extra script section?


Sorry for all the questions...i just want to get the setup right the first time :)

**Comment by mdhiggins** [comment]
If you want to use the blackhole setup then you just setup the Sickrage/Sonarr components of the readme and ignore the SAB portions

Any time a file is picked up as it normally would be the postSonnar / postCouchPotato scripts will be fired and handle everything. The downloader scripts simply conver the files beforehand and pass the files back to their respective manager; if you're using the black hole and periodic scan you don't need them to notify the main programs.

**Comment by saitoh183** [comment]
Got it...thanks
