### ISSUE TITLE
No module requests

### ISSUE THREAD

**Issue by jodfie** [mdhiggins/sickbeard_mp4_automator#603]
I have the same issue as this closed issue. https://github.com/mdhiggins/sickbeard_mp4_automator/issues/481

reading through I don't see where the person with the no module requests get his problem solved.
I've tried to look and it appears I only have Python 2.7 in Usr/local/Bin 
I checked pip install and it shows requests installed.
I checked pip list and it shows in the list. 
Manual.py works fine it's just sabpostprocess.py that throws the error.

**Comment by mdhiggins** [comment]
This issue is almost always related to a bad python installation or multiple coexisting python environments causing problems. You'll need to dig and see if you have multiple environments or just do a clean install of your python environment. It's very tough to debug remotely.

**Comment by jodfie** [comment]
How can i tell if there is multiple instances or conversely how can i do a
clean install and would that affect my other python scripts?

**Comment by mdhiggins** [comment]
Please post the full text of the error you're having just to make sure this is the right issue before we go down this road

You can also try modifying the SHEBANG at the top of the file
Currently set to this `#!/usr/bin/env python` but you can point it to your specific python instance

**Comment by jodfie** [comment]
is this the error you're referring too?
```
Traceback (most recent call last):
  File "/Users/cardinalserver/MP4Automator/SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr
  File "/Users/cardinalserver/MP4Automator/autoprocess/autoProcessMovie.py", line 11, in <module>
    import requests
ImportError: No module named requests
```

**Comment by mdhiggins** [comment]
Yeah, that's the error. Wasn't super helpful I guess in adding much information

**Comment by jodfie** [comment]
this may be a dumb question... But do you know what files a default python has in it? is this normal? http://prntscr.com/decgwb

**Comment by mdhiggins** [comment]
No idea specifically what packages are included 

Any luck changing the Shebang?

**Comment by jodfie** [comment]
i did terminal "which python" which gave
`/usr/local/bin/python`
so i changed the shebang to 
`#!/usr/local/bin/python python`
and im still getting the error even restarted Sab to make sure.

**Comment by mdhiggins** [comment]
I had forgotten about this but the script when readSettings is run should spit out the path to the python exec that's being used when that script is running, you should see it both at the top of manual.py and when the SAB script runs. See if you see that information anywhere and if its different between the two scripts

**Comment by jodfie** [comment]
my Manual.Py works just fine... this is what my readsettings says
` settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log) `
I'm not familiar enough with Python to know if it needs to be changed somehow.

**Comment by mdhiggins** [comment]
I didn't mean the code itself. Post the full SAB log and a full manual.py output if you could.

**Comment by jodfie** [comment]
i didn't want to post all that info on here.... so i emailed it to you...hopefully that's ok

**Comment by jodfie** [comment]
this can be closed. I fixed it with the help of another post about requests module
