### ISSUE TITLE
Option to disable output_directory for media managers, but allow active for downloaders

### ISSUE THREAD

**Issue by bsahlhof** [mdhiggins/sickbeard_mp4_automator#605]
I prefer allowing Deluge to convert files to MP4 (and save the converted files into a different folder - to keep them apart from original downloads).  (actually, it would be nice to separate the different media manager downloads into their own folders).

Once the files have been converted, then the media managers should be used to determine the final location of the files (not same location as the finalized conversion location).  

What I have done (in meantime) was to edit postConversion.py at line 21, and postCouchPotato.py at line 19 - I added:
settings.output_dir = None
in both of these files.  

A better option would be to have a variable to:
Allow Media Mangers to set Output Directory

This would allow original output directory for Deluge to be set, and also allow the media managers to set their own directories.

Maybe a better explanation of the output_directory variable would be usefull also (I had to read code / debug to figure out that output_directory applied to both sides of the equation.

**Comment by mdhiggins** [comment]
Just pushed an update that allows you to set individual output directories for the download managers
Simply set your base output_directory to None and set the output_directory option under whichever download manager to the directory of your choice. These selections will override the default output_directory.
