### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#607]
When setting up MP4 Automaton, when configuring the script in the downloader (NZBGet in my case), do you need to set it up in the Media Managers?

**Comment by mdhiggins** [comment]
Haven't you been using the script for a long time?

The media managers are needed to handle tagging. If you just want conversion then you don't need the post scripts for them, only the downloaders

**Comment by StevenChorkley** [comment]
Yep, few years - stupid me. 

Thank you for the help, and the awesome continuous work!

**Comment by StevenChorkley** [comment]
Why can't tagging be embedded in the conversion script? 

The reason I ask is because I'd like to have the script in a docker container with NZBGet.
