### ISSUE TITLE
Sickrage failing to remove QTFS file

### ISSUE THREAD

**Issue by daverage** [mdhiggins/sickbeard_mp4_automator#611]
Hi

I am getting the following error post conversion

WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\media\\TV\\The Flash (2014)\\Season 03\\The Flash (2014) - S03E07 - Killer Frost.mp4' 
2016-12-10 09:26:52 - mkvtomp4 - ERROR - Error cleaning up QTFS temp files. 

Any idea how to kill that?

**Comment by mdhiggins** [comment]
Hm that's a tough one, something is putting the file in use before it can be deleted. Do you have any scanners or media managers that might be trying to access the file? (Plex, Sonarr, etc?)

**Comment by daverage** [comment]
It could be my virus scanner actually. I will create a batch file to delete qtfs files from that folder periodically. That should be good enough for now.

**Comment by mdhiggins** [comment]
Alright, if the problem persists feel free to reopen
