### ISSUE TITLE
Sonarr dont always import files when notified

### ISSUE THREAD

**Issue by izeen** [mdhiggins/sickbeard_mp4_automator#612]
Hello!

Just started using this amazing script to get all my new media in a good supported container/codec. I have some problems with it working with Sonarr tho, it might be considered special cases but i´ve noticed that sometimes Sonarr doesn't always import the newly converted files. I think i have two correct reasons. 

The first is when an epsiode does not have a verified scene number by TheXEM in Sonarr, before using this script when i had complete download handling on this was not an issue. These episodes are not automatically imported by sonarr but you get the option to manual import them from the GUI. When using the script and complete download handling off you don't, in the logs this this all you have: Debug|UnverifiedSceneNumberingSpecification|This file uses unverified scene numbers, will not auto-import until numbering is confirmed on TheXEM. Skipping.

Usually it doesn't take long to get the scene number verified but sometimes it takes a couple of days. Is there away around this or is this all on Sonarr? Can i re run the postprocess notification on a later time when the scene number has been verified so Sonarr picks up the file? If you can, how do i do it?

The other problem i seem to be having is with shows added that for some reason the series name is not matching the series name in Sonarr. When having complete download handling on this is not a problem. For example Pokémon series, lets say ep1 of season 18 is released as Pokémon Sun and moon S20E01. Sonarr knows that it can be named like that due to the TheXEM mappings so when its imported in to sonarr it renames it to the Sonarr(the TVDB mappings) name and cleans up the file name. This seams to not be the case when using this script.

Log in sonarr: 

Debug|Parser|Parsing string 'Pokemon.Sun.and.Moon.S20E02.The.Guardians.Challenge.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash[rarbg]-convert'
|Debug|Parser|Episode Parsed. Pokemon Sun and Moon - S20E02 
|Debug|Parser|Language parsed: English
Debug|QualityParser|Trying to parse quality for Pokemon.Sun.and.Moon.S20E02.The.Guardians.Challenge.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash[rarbg]-convert
Debug|Parser|Quality parsed: WEBDL-720p v1
Debug|Parser|Release Group parsed: convert
|Debug|DownloadedEpisodesImportService|Unknown Series Pokemon.Sun.and.Moon.S20E02.The.Guardians.Challenge.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash[rarbg]-convert

And the log from the script when the above is happening sais , it mentions that it cant delete the temporary folder created due to sonarr not picking up the files.

OSError: [Errno 39] Directory not empty: '/media/delugedl/complete/Pokemon.Sun.and.Moon.S20E02.The.Guardians.Challenge.720p.DSNY.WEBRip.AAC2.0.x264-TVSmash[rarbg]-convert'

Any tips on how i can make my setup work any better? Any workarounds? I would love to know if i can execute the postProcess notifaction to sonarr later on, if and how :)

**Comment by mdhiggins** [comment]
You can turn on completed download handling and just not use the NZB or SAB scripts if you're having difficulty. postSonarr is capable of doing all processing
