### ISSUE TITLE
Feature Request: Create additional audio stream

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#617]
I would like to be able to create audio stream in AAC for mobile (already possible) and at the same time create AC3 in Dolby Digital from DTS track. So that the end result is:

Stream 0: AAC
Stream 1: AC3 5.1 (Dolby Digital)
Stream 2: Original DTS track copied

Would this be an easy implementation or is it already possible?

**Comment by badincite** [comment]
Actually just asked a forked version creator the same thing it would be nice to have.

**Comment by badincite** [comment]
After looking through the documentation I found you can do it. Enable the ios audio stream which adds the aac audio track. Wish I would have saw that before encoding a bunch of stuff.

![image](https://cloud.githubusercontent.com/assets/7386290/22027598/59d74ba8-dca2-11e6-89c3-b6d5dd42407c.png)

**Comment by shpankey** [comment]
Unfortunately, your result is not as you wished. You're missing the DCA track. It was mentioned in another thread he's looking into adding this capability. I am wanting the same thing but there's no way to do it (yet) as is.

**Comment by shpankey** [comment]
This is now implemented in the current build
