### ISSUE TITLE
Disable copying before convert

### ISSUE THREAD

**Issue by kocane** [mdhiggins/sickbeard_mp4_automator#621]
Wouldn't it somehow be possible to disable copying before converting?

It seems like it copies the file with -convert aprehended, then calls for CP which moves the file and THEN starts to convert to mp4

This is my config:
```
[MP4]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,hevc,h265,x265,HEVC,mpeg4,MPEG-4,MPEG-H,h.265,h.264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = False
ios-audio = libfdk_aac,aac,a_aac,libfaac
ios-first-track-only = True
max-audio-channels =
audio-codec = ac3,libfdk_aac,a_ac3,ac-3,a_aac,aac,libfaac
audio-language = eng,dan
audio-default-language = eng
audio-channel-bitrate = 96
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = True
pix-fmt =
```

**Comment by zasmth** [comment]
I have the same issue. Everything is set up so that it finishes converting before copying, but it's moving everything to the destination and downloading subs/converting in the destination directory. Every so often it leaves some artifacts in the destination directory and I have to manually clean them up.

**Comment by mdhiggins** [comment]
Copying should only happen after conversion is finished

That being said tagging and QTFaststart are still done AFTER moving due to the fact that the metadata comes from the post downloader

Make sure you have conversion enabled in whatever post downloader script you're using
