### ISSUE TITLE
Bulk Processing - Specify TVDB ID

### ISSUE THREAD

**Issue by grokdesigns** [mdhiggins/sickbeard_mp4_automator#622]
Is there a way to specify a TVDB ID for individual folders when doing bulk processing? I'm processing my entire TV folder at the moment and it's going fine except for one series (Cops, which it's mismatching to a series called C.O.P.S.), and it gives me the following on every file:

> Failed to connect to TVDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "E:\MP4Automator\tvdb_mp4.py", line 40, in __init__
    self.seasondata = self.showdata[self.season]
  File "E:\MP4Automator\tvdb_api\tvdb_api.py", line 117, in __getitem__
    raise tvdb_seasonnotfound("Could not find season %s" % (repr(key)))
tvdb_seasonnotfound: Could not find season 28

Not a huge deal, as I can go back and manually specify the ID on that series, but it takes up considerable time with the number of episodes I have. Can I put something in the series folder that tells the script what the TVDB ID is? If not, I'd recommend this as a feature (look for #####.tvdbid file in series folder or something).

Edit: Just found another issue with this. If I re-run a batch processing job on the folder containing this series, it deletes all of the metadata that I put in the files by running with a specific TVDB ID.

**Comment by mdhiggins** [comment]
This has been fixed with manual.py, you can now override the TVDBID via command line parameters
