### ISSUE TITLE
Converted audio bitrate does not match the parameters

### ISSUE THREAD

**Issue by Arkymedes** [mdhiggins/sickbeard_mp4_automator#625]
Hello there,

I have some files that have DTS 5.1 tracks in them with a bit rate of ~1500 kb/s.

My ini file is set to convert them to AC3@384kbps but after the convertion, if I check the file with MediaInfo, the audio track is at 640kbps.

```
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language = eng
audio-channel-bitrate = 384
audio-filter =
```

How can I ensure they will be set to the bitrate I specified?

Or maybe I'm using the settings wrong?

Thanks!

**Comment by mdhiggins** [comment]
It should be based on the channel bitrate * the number of channels. Are you sure the track isn't being converted to less channels?

Additionally AC3 usually has a much smaller bitrate for the same quality level as DTS, so I wouldn't aim to have your AC3 tracks have the same bitrate as DTS, its probably wasting space.

**Comment by Arkymedes** [comment]
Hello and thanks for your answer.

Yes, I can confirm that the number of tracks has been preserved (6 channels, AC3).

I understand the bitrate differences between DTS and AC3, hence my preference for the smaller AC3 tracks sacrificing little quality in the process in favour of a smaller file. I found that 384kbps is a good compromise. I also have compatibility issues with my hardware setup here that I need to take into consideration.

In any case, based on your formula, the final calculation is not correct in my case, since 384*6 is 2304, but the final file has an AC3 track of 640kbps

By the way, could you kindly tell me what is the command line you use for the conversion? If I remember correctly, there was a bug with ffmpeg that would mixup the channel orders when converting audio tracks from DTS to AC3.

Thank you!

**Comment by Arkymedes** [comment]
Hello again, it's all good! Thanks.

On a side note, I have some MKV/MP4 with AC3 tracks but with higher bitrates (640kbps)

I noticed that the script simply copy the track over without downmixing, even though it's in the parameters.

Is there a way to force downmixing to my desired bitrate?

Thanks!
