### ISSUE TITLE
[REQ] VAAPI encoding

### ISSUE THREAD

**Issue by karbowiak** [mdhiggins/sickbeard_mp4_automator#626]
Just like QSV is toggleable, would it be possible to add VAAPI being toggleable? :)

**Comment by microSCOPED** [comment]
+1

**Comment by mdhiggins** [comment]
What parameters are needed to use VAAPI?

**Comment by karbowiak** [comment]
This is the command used by Plex

```/usr/lib/plexmediaserver/Plex Transcoder -codec:0 h264 -hwaccel:0 vaapi -threads:0 1 -codec:1 ac3 -noaccurate_seek -i /path/to/file/sometvshow.mkv -map 0:0 -codec:0 copy -map 0:1 -metadata:s:1 language=eng -codec:1 aac -rematrix_maxval 10.000000dB -ar:1 48000 -channel_layout:1 stereo -b:1 256k -f matroska -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 - -start_at_zero -copyts -y -vaapi_device /dev/dri/renderD128 -nostats -loglevel quiet -loglevel_plex error -progressurl http://127.0.0.1:32400/video/:/transcode/session/jc84z510x02dphzh3fke7y14/progress```

Tho according to some Googleing it can also be
```-vaapi_device /ddev/dri/renderD128 -i <input> -vf 'format=nv12,hwupload' -c:v h264_vaapi <output>```

But i'm sure you're more qualified at determining the required parameters than i am :)

**Comment by nzbjamz** [comment]
@karbowiak How did you get the command used by Plex?

**Comment by karbowiak** [comment]
@nzbjamz started a transcode in Plex, went to the terminal on the server and went `ps aux | grep plex` and got it from there :P

**Comment by nzbjamz** [comment]
Is right that `Plex Transcoder` just a customized `ffmpeg`?

**Comment by karbowiak** [comment]
@nzbjamz yeah - afaik you can get the source for it on the Plex forum.
But it's older than FFMpeg, and it's shittier to boot, so no reason to actually use it :P

**Comment by nzbjamz** [comment]
@karbowiak Ah nice! I'm curious because I'm using the Plex beta with hardware accelerated transcoding and trying to get `ffmpeg` to use it to *(without luck so far)*.

**Comment by nzbjamz** [comment]
Hey @karbowiak!

I dug into this and am testing a patch on my end. I should have a PR up in a day or two.

**Comment by tankerkiller125** [comment]
So I've been trying to test the VAAPI encoder that's part of the pull request, and I've found that it never works. It also has an issue regarding the syntax of the ffmpeg command it tries to execute.

**Comment by RandomNinjaAtk** [comment]
Have you tried this recently? This should be resolved, but you do have to make sure your using the correct settings in your config:

"video-codec = h264vaapi"
