### ISSUE TITLE
Error with manual conversion

### ISSUE THREAD

**Issue by blackley** [mdhiggins/sickbeard_mp4_automator#627]
Hi there, just setup the automator and wanted to test it was all working with a manual conversion - failed. please see below.

command:  /home/plex/mp4_automator/manual.py -i "/home/plex/torrents/complete/tv/Supergirl S02E09 2016 HDTV x264 - AFG.wmv" -tv 295759

output: 
Traceback (most recent call last):
  File "/home/plex/mp4_automator/manual.py", line 5, in <module>
    import guessit
ImportError: No module named guessit

OS: Ubuntu 16.10

autoProcess.ini:
[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Sonarr]
host = localhost
port = 9091
web_root =
ssl = 1
apikey =  db96a25cd8604939b1ebd95a8a1744d9

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory = 
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
audio-filter =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False

[CouchPotato]
host = localhost
port = 8084
username = darrenb
password = Ncc1701e
web_root =
ssl = 0
apikey = 27053262793a43b48ad26bf402a4d9a0
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert =
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username =
password =
output_directory =

[Deluge]
host = localhost
username =
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory =

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory =

[Sickrage]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Plex]
host = localhost
port = 32400
refresh = True
token =

**Comment by blackley** [comment]
Ok i found the problem with guessit, however after correcting this i am now getting this error below

Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
File /home/plex/torrents/complete/tv/Supergirl S02E09 2016 HDTV x264 - AFG.wmv is not in the correct format

**Comment by blackley** [comment]
Hi Michael,

I have given up on attempting to use any of the post process scripts now after 2 weeks of testing all of the integration - they are mostly hit and miss and will work with a custom script and utilise the manual processing script in conjunction with my custom script. Thanks for your time on this.

**Comment by FrankGNL** [comment]
So what was the problem with guessit?
