### ISSUE TITLE
[Request] Remove intro for TV Show

### ISSUE THREAD

**Issue by UnR34L** [mdhiggins/sickbeard_mp4_automator#630]
My coding ability is limited but I've been playing around with the idea of removing TV show intros. Similar to how netflix works, they show the intro once then it isn't showed for the consecutive episodes 

I used ffprobe to get the chapter times then removed the first chapter using ffmpeg's '-ss' (Seek to pos.) with vcodec/acodec copy nothing had to be re encoded so it was a very fast process.

I then used the srt script to shift the subtitles back to the correct place.

I thought it was pretty cool, hoping it takes someones interest.

**Comment by Mirabis** [comment]
Binge watchers will love this.. But If u start an episode after a long while the recap / intro is handy

**Comment by mdhiggins** [comment]
Probably no way to do this reliably anyway. Almost no shows have chapter info

**Comment by UnR34L** [comment]
> Probably no way to do this reliably anyway.

Every bluray RIP I've come across has chapters. It's true that content from torrents and usenet generally don't have them because they use TV sources, but this is still a incredibly useful tool for processing media that came from other sources, your own rips or just manually grabbing content that has chapters.

I was hoping to use `manual.py -c TVIntros.ini -i D:\Process -a` and in the .ini have variables similar to
'chapter-cut = True' #Enable the feature
'chapter-number = first,2,3,last' #Specify which chapters to remove

It could save on space and time, it gets very tedious skipping the intro over and over. I'm betting I'm not the only one that would love this.
