### ISSUE TITLE
mp4_automator/delugePostProcess.py' failed with exit code 1

### ISSUE THREAD

**Issue by blackley** [mdhiggins/sickbeard_mp4_automator#634]
[WARNING ] 13:18:05 core:132 [execute] command '/home/plex/mp4_automator/delugePostProcess.py' failed with exit code 1
[WARNING ] 13:18:05 core:136 [execute] stderr: Traceback (most recent call last):
  File "/home/plex/mp4_automator/delugePostProcess.py", line 8, in <module>
    from deluge_client import DelugeRPCClient
ImportError: No module named deluge_client

**Comment by mdhiggins** [comment]
pip install deluge-client
You didn't install the deluge client.

**Comment by blackley** [comment]
thanks mdhiggins - that got rid of that error, however it is still not running after downloads are complete.

**Comment by mdhiggins** [comment]
Can you post the full logs?

Look at info.log for more information

**Comment by blackley** [comment]
Hi Michael,

I will do some more testing and once I have more log data I will send it in.

I have been playing with the tools for a few days now and the manual process works perfectly, however, no matter what I do I have yet to get it to work with sonarr, couchpotato, utorrrent, sab or deluge - I only installed deluge to test with the tool....  it is really giving me the sh*ts not being able to get the automation going....

**Comment by blackley** [comment]
Hi Michael,

I have given up on attempting to use any of the post process scripts now after 2 weeks of testing all of the integration - they are mostly hit and miss and will work with a custom script and utilise the manual processing script in conjunction with my custom script.  Thanks for your time on this.
