### ISSUE TITLE
Unable to disable all subtitles - please advise

### ISSUE THREAD

**Issue by blackley** [mdhiggins/sickbeard_mp4_automator#636]
Hi Michael,

On all of my automatic post-process as well as the manual process, subtitles are being downloaded - I don't want to enable them by default and would add subs on a case by case basis.  I have all of the subtitle fields empty in the autoProcess.ini - please see below.

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 256
audio-filter = 
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = False
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = True
pix-fmt = 
aac_adtstoasc = False

**Comment by mdhiggins** [comment]
It shouldn't be downloading additional subtitles with the settings that you're using. Its possible that if the download source you're using already has external subtitles embedded that that's what you're seeing.

If you want to block all subtitles, including internal and external, set you subtitle language to `nil` and leave your subtitle default language option blank.
