### ISSUE TITLE
How to prevent sickbeard_mp4_automator from auto-converting AVIs to M4Vs while keeping MKV->M4V remuxing?

### ISSUE THREAD

**Issue by strafer** [mdhiggins/sickbeard_mp4_automator#644]
I have sickbeard_mp4_automator setup in Sonarr to remux any MKVs into M4Vs with proper tags and subtitles. I also have it set to process any MP4s without tags, etc into M4Vs with tags and artwork. However, if I download an AVI, sickbeard_mp4_automator will convert the AVI into an M4V. This really kills the CPU on my old Mac Mini.

Is there a way to keep the MKV/MP4-to-M4V remuxing/tagging enabled while disabling AVI-to-M4V conversion?

**Comment by mdhiggins** [comment]
In extensions.py you can remove avi from the list of supported extensions to achieve this behavior.

**Comment by strafer** [comment]
Thanks so much.
