### ISSUE TITLE
No JSON object could be decoded (couch potato related)

### ISSUE THREAD

**Issue by SgtBatten** [mdhiggins/sickbeard_mp4_automator#645]
Had this error today with movie downloads.
Sonarr has been working flawlessly for TV but this may be the first movies I've done.

2017-01-20 15:53:42 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:9007/api/xxxxxxxxxxxx/renamer.scan.
Traceback (most recent call last):
  File "C:\Users\Chromebox\Documents\GitHub\sickbeard_mp4_automator\SABPostProcess.py", line 79, in <module>
    autoProcessMovie.process(path, settings, nzb, sys.argv[7])
  File "C:\Users\Chromebox\Documents\GitHub\sickbeard_mp4_automator\autoprocess\autoProcessMovie.py", line 93, in process
    rstate = r.json()
  File "C:\Python27\lib\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mdhiggins** [comment]
Your couch potato settings are incorrect and it's not getting a response. 
Check autoprcoess.ini

**Comment by SgtBatten** [comment]
Thanks mate I've checked all the settings. Had changed passwords recently and fixed that but the error is still the same. I'll keep looking.

**Comment by mdhiggins** [comment]
Post your autoProcess file for me and I'll take a look. And maybe post a screenshot of your couch potato settings too

**Comment by SgtBatten** [comment]
Which couch settings would you like to see?

**Comment by SgtBatten** [comment]
[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264
video-bitrate = 
video-max-width =
h264-max-level = 4.0
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = True
ios-audio-filter =
max-audio-channels = 
audio-codec = ac3,aac,mp3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 0
audio-filter =
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Thumbnail
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False

[CouchPotato]
host = localhost
port = 9007
username = xxxxxx
password = xxxxxx
web_root =
ssl = 0
apikey = xxxxxxxxxx
delay = 65
method = renamer
delete_failed = 0

**Comment by SgtBatten** [comment]
I still haven't solved this one mate. Anything else I can provide to assist tracking it down?
-------- Original message --------From: Michael Higgins <notifications@github.com> Date: 22/01/2017  10:48 AM  (GMT+10:00) To: mdhiggins/sickbeard_mp4_automator <sickbeard_mp4_automator@noreply.github.com> Cc: SgtBatten <sgt@batten.net.au>, Author <author@noreply.github.com> Subject: Re: [mdhiggins/sickbeard_mp4_automator] No JSON object could be decoded (couch potato related) (#645) 
Post your autoProcess file for me and I'll take a look. And maybe post a screenshot of your couch potato settings too 



Sent from my iPhone



> On Jan 21, 2017, at 18:44, SgtBatten <notifications@github.com> wrote:

> 

> Thanks mate I've checked all the settings. Had changed passwords recently and fixed that but the error is still the same. I'll keep looking.

> 

> —

> You are receiving this because you modified the open/close state.

> Reply to this email directly, view it on GitHub, or mute the thread.

> 



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mdhiggins/sickbeard_mp4_automator","title":"mdhiggins/sickbeard_mp4_automator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mdhiggins/sickbeard_mp4_automator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mdhiggins in #645: Post your autoProcess file for me and I'll take a look. And maybe post a screenshot of your couch potato settings too \n\nSent from my iPhone\n\n\u003e On Jan 21, 2017, at 18:44, SgtBatten \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e Thanks mate I've checked all the settings. Had changed passwords recently and fixed that but the error is still the same. I'll keep looking.\n\u003e \n\u003e —\n\u003e You are receiving this because you modified the open/close state.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/mdhiggins/sickbeard_mp4_automator/issues/645#issuecomment-274296202"}}}

**Comment by raymatos** [comment]
Just had the same issue.

```
2017-08-27 03:55:33 - autoprocess.autoProcessMovie - INFO - Opening URL: http:/[HOSTREMOVE]/couchpotato/api/[APIKEYREMOVED]/renamer.scan.
Traceback (most recent call last):
  File "/config/mp4_automator/SABPostProcess.py", line 79, in <module>
    autoProcessMovie.process(path, settings, nzb, sys.argv[7])
  File "/config/mp4_automator/autoprocess/autoProcessMovie.py", line 93, in process
    rstate = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

Here is the response from the URL

```
{
"success": true
}
```

**Comment by mdhiggins** [comment]
Very strange so the URL worked when you entered it manually?
