### ISSUE TITLE
Subtitle errors

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#646]
I'm getting errors such as 
`NZBGetPostProcess: NoMatches: No guessit.transformer extensions found
NZBGetPostProcess: raise NoMatches('No %s extensions found' % self.namespace)
NZBGetPostProcess: File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 252, in map
NZBGetPostProcess: return self.map(self._get_obj)
NZBGetPostProcess: File "/usr/local/lib/python2.7/dist-packages/guessit/plugins/transformers.py", line 111, in objects`

and 

`NZBGetPostProcess: 2017-01-20 11:05:32 - autoprocess.sonarr - INFO - [INFO] Sonarr response: queued.
NZBGetPostProcess: 2017-01-20 11:05:32 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/StoragePool/Downloads/Completed/Sonarr/Arrow.S01E01.720p.WEB-DL.DD5.1.H.264-ECI'.
NZBGetPostProcess: 2017-01-20 11:05:32 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
NZBGetPostProcess: Successfully processed /StoragePool/Downloads/Completed/Sonarr/Arrow.S01E01.720p.WEB-DL.DD5.1.H.264-ECI/131148.mkv.
NZBGetPostProcess: /StoragePool/Downloads/Completed/Sonarr/Arrow.S01E01.720p.WEB-DL.DD5.1.H.264-ECI/131148.mp4 created.
NZBGetPostProcess: Starting conversion.
NZBGetPostProcess: ValueError: 'en' is not a valid language
NZBGetPostProcess: raise ValueError('%r is not a valid language' % language)`

I have no idea why. Do you have any idea?

**Comment by zybeon** [comment]
Post your autoProcess.ini, for your second error I bet you have 'en' where you should have 'eng'.

**Comment by StevenChorkley** [comment]
I do have en, it's a valid IETF language tag. Same tag used for audio.

**Comment by zybeon** [comment]
`tag-language=` uses either 2 or 3 letter language codes
`audio-language=` uses only 3 letter codes
`subtitle-language=` uses 3 letter codes

**Comment by StevenChorkley** [comment]
Cheers, it hasn't fixed this however:

`NZBGetPostProcess: 2017-01-20 16:32:58 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/StoragePool/Downloads/Completed/Sonarr/Arrow.S01E09.720p.HDTV.X264-DIMENSION'.
NZBGetPostProcess: 2017-01-20 16:32:58 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
NZBGetPostProcess: NoMatches: No guessit.transformer extensions found
NZBGetPostProcess: raise NoMatches('No %s extensions found' % self.namespace)
NZBGetPostProcess: File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 252, in map
NZBGetPostProcess: return self.map(self._get_obj)
NZBGetPostProcess: File "/usr/local/lib/python2.7/dist-packages/guessit/plugins/transformers.py", line 111, in objects`

**Comment by mdhiggins** [comment]
There's a problem with the latest version of stevedore and the older version of guessit. Gotta rol back to 1.19 to fix this error

**Comment by jdalton** [comment]
Fix posted on #643.

**Comment by mdhiggins** [comment]
Soon as I have some free time my top priority will be updating to the latest guessit

**Comment by jdalton** [comment]
Thank you for putting your time into this!
