### ISSUE TITLE
Duplicate category detected. Category names must be unique.

### ISSUE THREAD

**Issue by Arkymedes** [mdhiggins/sickbeard_mp4_automator#651]
Hello there,

I think I'm missing an important step here when configuring the NZBGet part.

I keep getting those errors in my log files:

```ERROR	NZBGetPostProcess: Duplicate category detected. Category names must be unique.```

In NZBGet, I've set the categories to match the ones that the media managers use themselves as stated in the documentation. Or did I read wrong?

So in my setup, Sonarr uses the 'tv shows' category and Couchpotato uses the 'movies' category.

Could someone kindly clarify this for me?

Thanks!

**Comment by mdhiggins** [comment]
Can you post a picture of the relevant settings page in NZBGet?

**Comment by Arkymedes** [comment]
Here it goes!

Thanks for the fast response :)
![screenshot-192 168 0 44 6789-2017-01-24-10-41-09](https://cloud.githubusercontent.com/assets/2019096/22241942/c393aac6-e221-11e6-89d5-f31b1ab2b073.png)

**Comment by mdhiggins** [comment]
Can’t have all those other categories be blank

Just leave them as their default options instead of deleting what was there or put some unique filler for each category

**Comment by Arkymedes** [comment]
Alright, will try that and report back in a few minutes, thanks so much!

**Comment by Arkymedes** [comment]
Yeah, that was the solution. It's working great now, thanks again!
