### ISSUE TITLE
Watcher Support

### ISSUE THREAD

**Issue by ridizy** [mdhiggins/sickbeard_mp4_automator#652]
Watcher is another promising project that would be great to integrate with: https://github.com/nosmokingbandit/watcher

Would it be possible to add support for this?

**Comment by mdhiggins** [comment]
Would have to look into it further or request the feature for watcher to support post processing scripts. Not seeing anything obvious but I'll look into it.

**Comment by ridizy** [comment]
Thank you.  Just found this: https://github.com/nosmokingbandit/watcher/issues/161

**Comment by mdhiggins** [comment]
Great. Will keep an eye out for this feature.

**Comment by ridizy** [comment]
Just a heads up that Watcher now supports post processing scripts, which they call "plugins": https://github.com/nosmokingbandit/watcher/wiki/Plugins

**Comment by ridizy** [comment]
Watcher has moved to Python 3 and a new repository:
https://github.com/nosmokingbandit/watcher3/wiki/Post-Processing

The prior repository is no longer supported.

**Comment by ridizy** [comment]
Just checking in on this one.  Any chance support for Watcher could be considered at this time?  Thank you.

**Comment by mdhiggins** [comment]
Watcher doesn't seem to be getting any updates (last about 2 yeras ago)
Gonna close this but would be open to a PR if it was still desired

**Comment by ridizy** [comment]
Thanks for looking into this.  I've since moved on from Watcher, but if anyone else is interested in picking this up, an active fork can be found here: https://github.com/barbequesauce/Watcher3
