### ISSUE TITLE
Adds blank subtitle track to media

### ISSUE THREAD

**Issue by Rycore** [mdhiggins/sickbeard_mp4_automator#654]
I'm running manual.py on windows to batch convert some tv shows, I don't want to download any subtitles but if any exist in the files then I simply want to keep the English ones and have them remain encoded on the file.

So I ran the follow to test it before I batch convert over 100+ files.
`python manual.py -i "D:\Input\TV\Series\Season\File.mkv" -a  -nt -nd`

Once complete, despite that file not having any subtitles, a subtitle track is added, if I was to enable that subtitle track, I get a timecode (00:00:00.000) at the bottom.

Here is the output from the command line.

```
D:\Convert>python manual.py -i "D:\Input\TV\The Flash (2014)\Season 01\The Flash 2014 S01E01.mkv" -a -nt -nd
Manual processor started.
D:\Python27\python.exe
Audio bitrate was invalid, defaulting to 256 per channel.
Invalid external subtitle codec mov_text, ignoring.
No valid subtitle formats found, defaulting to 'srt'.
32bit Python.
No-delete enabled
No-tagging enabled
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Video level 4.1.
Reading audio streams.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Audio track is number 0 setting disposition to default
Creating audio stream 1 from source stream 1.
Audio Track is number 1 setting disposition to none
Reading subtitle streams.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "map": 0,
        "codec": "h264",
        "bitrate": 4000,
        "level": 4.0
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "copy",
            "disposition": "none",
            "bitrate": 1536,
            "filter": null
        }
    }
}
Starting conversion.
[######### ] 99%D:\Output\The Flash 2014 S01E01.mp4 created.
Relocating MOOV atom to start of file.
```
Here are my config settings
```
[MP4]
ffmpeg = D:\Program Files (x86)\ffmpeg\bin\ffmpeg.exe
ffprobe = D:\Program Files (x86)\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory = D:\Output
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate = 4000
video-max-width =
h264-max-level = 4.0
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = True
ios-audio-filter =
max-audio-channels =
audio-codec = ac3, aac
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
```

Just to add, I'm new, only started using this today but can't figure out why it keeps adding subtitles to files that don't have them, I thought I followed the instructions to the letter and set it up accordingly, I plan on having this run on my server but wanted to batch convert some of my media on my PC as it's a much faster system.

Also **subtitle-encoding =** is not in the readme but is in te configuration so I was not sure what to do with it, I just left it blank.

**Comment by mdhiggins** [comment]
What playback program are you seeing a subtitle track in?

Can you post an ffprobe -show_streams output of one of these files that has the empty subtitle track? Based on what you're posting there shouldn't be any blank subtitle tracks

**Comment by Rycore** [comment]
@mdhiggins  it's showing up in VLC, I even checked it with ffprobe and your script seems to add an extra track in the file codec_nam bin_data, it doesn't show on plex or windows media player, but I have my own basic command line script I used that would encode files including any subtitles but it never created an extra track.
```
index=3
codec_name=bin_data
codec_long_name=binary data
profile=unknown
codec_type=data
codec_tag_string=text
codec_tag=0x74786574
TAG:language=eng
TAG:handler_name=SubtitleHandler
```

**Comment by Rycore** [comment]
I'm not familiar with python, I'm a novice at vbs, I can code in batch, bash, php and some javascripting but that's about it, so I took a look at some of the code to try and understand it, it appears where you add the subtitle setting in mkvtomp4, there is no clause for if the file doesn't contain subtitles, so it appears that regardless it still adds settings to ffmpeg for subtitles when it should technically be blank.

**Comment by mdhiggins** [comment]
The subtitle setting by itself doesn't do anything if its empty and wouldn't create any additional parameters in the FFMPEG command line ultimately generated.

The only thing I can think of is that maybe the -fix_sub_duration flag that is by default added to every FFMPEG command may be causing FFMEPG to behave this way. I just pushed an update that will prevent this flag from being added to the final command when there are no subtitles present in the final generated option set. Download the update and give that a try and see if it makes any difference.

Another thing to try/consider as well would be trying a different build of FFMPEG and see if this problem persists across many versions or is perhaps a transient bug that made into your particular build of FFMPEG.

**Comment by Rycore** [comment]
I'm running the command now, I'll report back asap

> trying a different build of FFMPEG and see if this problem persists across many versions or is perhaps a transient bug that made into your particular build of FFMPEG.

I built my own FFmpeg using the latest open source, I had a similar issue with the script I wrote in batch, but that was an error on my part, my script was adding subtitles when there were none, which is what I thought the issue was here, but my own script works fine and doesn't add subtitles, the only issue with my script is that it's not as advanced as yours, where now I need a fully automated system to convert my files as they arrive.

Right now I am only testing your script before I implement it, but if omitting **-fix_sub_duration** resolves the issue then I can go ahead and batch convert a small portion of my files to test on plex before I batch convert all of them and fully automate onto my server.

**Comment by Rycore** [comment]
@mdhiggins  I've tested ffmpeg as far back as February last year, I just downloaded a build instead of compiling my own, and they all have the exact same problem, so I can only assume that the video files have bad chapters, not sure if there is a way to detect such a thing but if that's the case it would explain why the first capture is being encoded as subtitles, only way around this for me at the moment "although I haven't tested it yet, would be to wipe all data from the file, which means no more subtitles, I could remake them with ffmpeg but I don't think I'll need chapters anyway, so I'll just have to learn a bit of python in order to make this script work for me lol, thank you for your time.
