### ISSUE TITLE
This program is constantly creating multiple video files

### ISSUE THREAD

**Issue by trippinshrumes** [mdhiggins/sickbeard_mp4_automator#656]
Good afternoon,
I'd like to start by thanking you for your fantastic tool, although I would like to expose a possible error.

I have this tool integrated with Sabnzbd and Deluge on Ubuntu Server 16.04 LTS.

I notice after this has been processed that there are multiple video files, so far each time there's a specific pattern, there are 2 .mkv in the folder and 1 .mp4 .... The movie came as an MKV and somehow in the conversion process it is copying it, and then converting it, and then everything is being moved to the final folder by Sonarr or CouchPotato. I am trying to have everything converted to MP4 as well as max bitrate 10,000 and max width being 1920. I'm more than willing to share any of my files or any logs of sorts if need be. 

For instance here is one
 11G Braveheart cd1.mkv   14G Braveheart cd3.mp4
 15G Braveheart cd2.mkv  4.0K Braveheart.orig.nfo

Any help is appreciated,
Thanks

**Comment by mdhiggins** [comment]
So it sounds like the issue is only one of the MKV files in the download is being converted while the rest are being ignored? Is that correct?

**Comment by trippinshrumes** [comment]
only 1 MKV file is coming in, and it's producing a 2nd MKV file as well as the wanted MP4.

**Comment by mdhiggins** [comment]
The script isn't making any new MKV files, those are likely included with your download and only one of the files is getting converted. Looks like your download probably included 3 CDs

Are you seeing this issue with every download client or just Deluge?

**Comment by trippinshrumes** [comment]
It's only happening for certain movies. I notice on Plex it will display a number along the top of the movie image for instance the number 2, when I check that folder I find 3 files just like this in it each time.

**Comment by trippinshrumes** [comment]
through deluge and sab

**Comment by mdhiggins** [comment]
You’re having the problem on both clients?

Are you having this problem with every download?

And can you link to a torrent or NZB that you’ve tried that’s giving you these issues?

**Comment by mdhiggins** [comment]
Also you'll need to post the relevant info.log data from these conversions for me to further debug this, please post this information. Info.log is found in the script root directory.

**Comment by trippinshrumes** [comment]
I'll get you the log in a lil over an hour

**Comment by trippinshrumes** [comment]
Going through the log myself I can tell that it wasn't able to find the file to delete it after the conversion, I'm not sure if the 3rd file might be caused due to couchpotato Downloading the file again and not replacing the previous version. I don't save the .nzb or torrent files, so I am unable to provide that.

I know for sure that this has happened after Sab specifically, I have not been able to confirm that this has happened with anything from Deluge. Anything I have checked from Deluge has been fine, I was mistaken about that earlier.

I'll keep a better eye on it to see if I can catch anything.Here's a list of movies I can tell have multiple files in case it helps you going through the log.

Braveheart  - 2 mkv 1mp4
The Empire Strikes Back - 1 mkv 1mp4
Jurrasic Park - 2mkv 1mp4
Thor - 2mkv 1mp4
X2 - 4mkv files, I may have downloaded this before your program was active... which may confirm it's not entirely your program and is mostly CouchPotato not working properly. I have none of these issues with any tv shows.

Attached log. Please keep me updated, thanks

I didn't want to zip the file, so change the extension to log to view. 

![info](https://cloud.githubusercontent.com/assets/13083581/22492891/e6bb2ad0-e7f1-11e6-86e3-6a801fda93b7.JPG)

**Comment by trippinshrumes** [comment]
Also, not sure if this effects anything, but the media folder is a fusemount displaying cloud files as well as local files.

**Comment by trippinshrumes** [comment]
This nzb download results in a cd1.mkv and a cd2.mp4 

let me know if there's anything else I can do to help


[files.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/769236/files.zip)
