### ISSUE TITLE
Question: Possible to ONLY convert 4K files?

### ISSUE THREAD

**Issue by seanvree** [mdhiggins/sickbeard_mp4_automator#662]
Wondering if it's possible to convert TV and/or Movies based on their source resolution?  I only want to convert to MP4 IF it's 4K, possible? The only thing I could come close was creating a category in Sabnzbd for 4K then using that category in the settings?

Using Sonarr and Radarr, Deluge and Sabnzbd.

First world problems tho...

THANKS!

**Comment by mdhiggins** [comment]
Unfortunately not possible at this time, using the categories is probably your best bet

**Comment by seanvree** [comment]
@mdhiggins  - That's what I thought! No worries. Good work on this! Dope!

**Comment by mdhiggins** [comment]
Appreciate it!
