### ISSUE TITLE
Deluge do not start delugePostProcess.py

### ISSUE THREAD

**Issue by tac00** [mdhiggins/sickbeard_mp4_automator#663]
@mdhiggins 

I'm running your script inside my Deluge docker container and everything is installed. I can run the manual.py without any errors. I have installed gevent and I have pointed the execute plugin to the full path for delugePostProcess.py.

But when Deluge is finished downloading nothing happens. I'm using Radarr as my media manager.

My autoProcess.ini:

[Deluge]
host = MY_SERVER_IP
username = MY_USERNAME
convert = True
password = MY_PASSWORD
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
radarr-label = radarr
output_directory =

I have tested the deamon and I can connect to it from the Deluge windows app. 

What should my settings be in Radarr regarding complete download handling, renaming etc?

**Comment by tac00** [comment]
This is the error I get in deluged.log:

`[ERROR   ] 17:55:14 core:154 [execute] Execute script not found or not executable`

But it is the correct path to the script and the script is executable.

`-rwxr--r-- 1 root root 4487 Feb  2 15:38 delugePostProcess.py`

**Comment by tac00** [comment]
I got everything working.

**Comment by Rikumo1978** [comment]
Could you please explain what you had to do tac00? I am having this same issue.
