### ISSUE TITLE
NZBGet not Post-processing with Sonarr

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#664]
Since updating to c4aaae93248bb80b7956125f1ad4633240fd3c80, I'm finding that the NZBGet script with Sonar no longer works, and I get this in the NZBGet logs...
```
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: Traceback (most recent call last):
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: File "/usr/local/nzbget/share/nzbget/scripts/NZBGetPostProcess.py", line 99, in <module>
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: radarrcat = os.environ['NZBPO_RADARR_CAT'].lower()
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: File "/usr/local/python/lib/python2.7/UserDict.py", line 40, in __getitem__
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: raise KeyError(key)
info	Fri Feb 03 2017 14:21:54	NZBGetPostProcess: KeyError: 'NZBPO_RADARR_CAT'
error	Fri Feb 03 2017 14:21:54	Post-process-script NZBGetPostProcess.py for <name of download removed> failed (terminated with unknown status)
```
It was working fine before this update.  Let me know if you need anything further :)

**Comment by KaHooli** [comment]
Hmm, not sure what's happened, but all of a sudden its working again.  I haven't restarted any programs or the server.

You can close this ticket if you like.  I'll reopen it if the issue happens again.

**Comment by colinbendell** [comment]
You have to save settings in NzbGet to force the new NZBPO_RADARR_CAT env setting. The script should be more fault tolerant

**Comment by mdhiggins** [comment]
It's an issue with how NZBGet handles its variables that's not easy to circumvent
