### ISSUE TITLE
Feature request: manual script output directory based on type

### ISSUE THREAD

**Issue by blackley** [mdhiggins/sickbeard_mp4_automator#666]
Hi Michael,

Just wondering if it is possible to incorporate a setting for the manual process script that will allow for a separate output folder based on type.  That is if the script converts a tv show, it outputs to xFolder and movie output to yFolder...

**Comment by mdhiggins** [comment]
This feature is best handled by the media managers and its not the intended purpose of manual.py (sonarr, couchpotato, etc)
