### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by iamhaller** [mdhiggins/sickbeard_mp4_automator#671]
I get the following error in SABnzbd when the download is completed

Traceback (most recent call last):
  File "/Users/paul/sickbeard_mp4_automator/SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
  File "/Users/paul/sickbeard_mp4_automator/autoprocess/autoProcessMovie.py", line 11, in <module>
    import requests
ImportError: No module named requests

Using the manual.py I have no issues. 

Python output when using manual.py
/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

Which python is outputted as 
/usr/local/bin/python
which is linked to

/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7

Requests has been installed to the site-packages folder using PIP.

Any ideas as to why I still receive this error? I did a clean install of OS X. Running version 10.12.3. Clean install of Python using brew. I hoped that the issue would be resolved by doing a clean install..

**Comment by iamhaller** [comment]
I was able to fix the issue by changing the shebang line for the SABPostProcess.py to #!/usr/local/bin/python instead of #!/usr/bin/env python

**Comment by nzbjamz** [comment]
This can happen if you have multiple versions of python on your system. You can sanity check to see the output of `/usr/bin/env` (it may show a rogue python path).

**Comment by jodfie** [comment]
@nzbjamz can you explain what you mean by sanity checking?

**Comment by nzbjamz** [comment]
@jodfie See the [wiki entry](https://en.wikipedia.org/wiki/Sanity_check).

**Comment by jodfie** [comment]
@nzbjamz i grasped the concept of what you were saying but im not sure how to see the output of /usr/bin/env on OSX

**Comment by nzbjamz** [comment]
@jodfie You have to open your terminal and then 
```shell
/usr/bin/env
```
Press enter with that. It'll print out the environment variables it establishes.
