### ISSUE TITLE
Couchpotato not showing it loaded postprocessing

### ISSUE THREAD

**Issue by badincite** [mdhiggins/sickbeard_mp4_automator#672]
Haven't had any luck getting the script to work with couchpotato and I don't see the post_process script getting loaded when couchpotato starts am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/7386290/22713368/1f5229f2-ed56-11e6-9677-859a5a45c65b.png)

![image](https://cloud.githubusercontent.com/assets/7386290/22713373/246717a4-ed56-11e6-809a-8d23a73a783f.png)
Pluging Log
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: browser
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: category
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: custom
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: dashboard
02-05 11:57:51INFO[tato.core._base.scheduler] Scheduling file.cleanup, interval: hours = 24, minutes = 0, seconds = 0
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: file
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: log
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: manage
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: profile
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: quality
02-05 11:57:51INFO[tato.core._base.scheduler] Scheduling movie.clean_releases, interval: hours = 12, minutes = 0, seconds = 0
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: release
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: renamer
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: scanner
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: score
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: subtitle
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: trailer
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: userscript
02-05 11:57:51INFO[  couchpotato.core.loader] Loaded plugin: wizard

**Comment by mdhiggins** [comment]
You copied the wrong stuff

You need to copy the whole PostProcess folder in the setup DIR to the custom_plugins dir

You copied the post_process folder which is different and not for couchpotato

**Comment by badincite** [comment]
Thanks! !!
