### ISSUE TITLE
Correct SabPostProcess output?

### ISSUE THREAD

**Issue by jodfie** [mdhiggins/sickbeard_mp4_automator#674]
I think I have the SabPostProcess script set up right but I'm seeing these outputs when it's done. 
what does queued and started mean? 
below is a screencap of my sab and a pastebin of the outputs.
http://prntscr.com/e6n86m
http://pastebin.com/2vqNwN8B
Is there anyway to make it say "Process Compete" or something similar on Sab?

**Comment by mdhiggins** [comment]
What you’re seeing is the expected behavior assuming those various programs all respond and processing finishes
