### ISSUE TITLE
Dead links in converter/avcodecs.py

### ISSUE THREAD

**Issue by nzbjamz** [mdhiggins/sickbeard_mp4_automator#675]
While working on a patch I noticed the links in avcodecs.py are dead.
```txt
http://mewiki.project357.com/wiki/X264_Settings#profile
```
They could be replaced with
```txt
https://web.archive.org/web/20150207075004/http://mewiki.project357.com/wiki/X264_Settings
```
Or another link.

**Comment by mdhiggins** [comment]
Just went ahead and removed all the URLs
They were put their by the original author before it was heavily enhanced for SMA; no need for them to be there anyway
