### ISSUE TITLE
encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by nzbjamz** [mdhiggins/sickbeard_mp4_automator#676]
While running `manual.py` I noticed this `encode() argument 1 must be string, not None` bit:
```txt
Reprocessing of MP4 files enabled
encode() argument 1 must be string, not None
Reading video stream.
```

I'm not sure where it's coming from. I did a quick source scan for `encode()` calls that accepted a variable but didn't see anything odd.
```python
print(locale.getpreferredencoding()) # UTF-8
print(sys.stdout.encoding) # UTF-8
print(sys.getfilesystemencoding()) # UTF-8
```

I noticed sometimes you have ([tvdb_mp4.py](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/a7fa9c5a76bce724b9d48decb2f875aa5bd1f123/tvdb_mp4.py)):
```python
.encode('ascii', errors='ignore')
```
and others ([tmdb_mp4.py](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/a7fa9c5a76bce724b9d48decb2f875aa5bd1f123/tmdb_mp4.py)) you have:
```python
.encode('ascii', 'ignore')
```

**Comment by mdhiggins** [comment]
Based on where that error is it shouldn't be coming from either of those (tvdb or tmdb). What device/os are you running this on? I'm wondering if perhaps your sys.getfilesystemencoding is returning None somewhere

Either way its a noncritical error that's caught and the script moves on, so I wouldn't stress about it

**Comment by nzbjamz** [comment]
Ah ok. Ya, I couldn't mail it down. Thanks for checking into it.
I'm on a QNAP but it's a user (me) inited script so should produce what I outputted in my `print` run.

**Comment by nzbjamz** [comment]
A bit more info: the `encode()` warning seems to be triggered when a tag match cannot be found.
