### ISSUE TITLE
Possible to convert file AFTER it's is moved to final destination?

### ISSUE THREAD

**Issue by seanvree** [mdhiggins/sickbeard_mp4_automator#678]
hey guys, not sure if this is possible. 

Using SABNZB -> Radarr. 

Everything works great when I have it set up in the "preferred" method.  I.E.: Sabnzbd uses post script to convert before sending back to radarr.  The problem I see with this is if the file needs to be converted say, from HVEC to x264, this takes awhile, and then holds up the SABNZBd queue till it's done.  

I was wondering, would there be a way to bypass the script in SABNZBd, and set up radarr, so that it sends the file to the "finished directory" (as normally it would) so that the file can be viewed, but then have Radarr use the script to convert while the file when it's in it's final directory?

Does this make sense?

Thanks!

Loving it!!

**Comment by mdhiggins** [comment]
The postRadarr scripts can and will do all the conversion if the file hasn't already been converted

Simply disable conversion with whatever download script you're using (in this case SAB) and you should get your desired behavior. That setting is under the SABNZB section of autoProcess.ini

**Comment by seanvree** [comment]
@mdhiggins  - a little confused. 

So, you're saying in SABNZBD settings ->Categoaries I have 
"movies" - I would then change the script to "NONE". 

Then under autoprocess.ini  -> SABNZBD -> Radarr-category = I would remove the value "MOVIES" which is what I have now?

**Comment by mdhiggins** [comment]
No just change the convert=true to false under the SABNZB section of autoProcess.ini. Leave the categories as they are.

**Comment by seanvree** [comment]
Ahh, I see. 

So, the script now gets called by Ronarr, after it's downloaded, so in the Ronarr settings, custom script, I would just make sure all are disabled except "On Download", correct?

**Comment by mdhiggins** [comment]
I believe that's correct. I forget what Radarr triggers there are but it should be in the readme. I'm on mobile right now can't easily check.

**Comment by seanvree** [comment]
@mdhiggins  - Right, I was just wondering if "on download" or "on rename" happens first.  I'm not sure if Radarr considers the file "downloaded" before it renames it and then sends it to the final destination?

**Comment by mdhiggins** [comment]
If you tell me which options there are I can tell you which ones you need

**Comment by seanvree** [comment]
"On Grab:
"On Download"
"On upgrade"
"On Rename"

**Comment by mdhiggins** [comment]
On download and on upgrade are probably the only two you need

**Comment by seanvree** [comment]
Yup, that's what I was thinking!  THanks!
