### ISSUE TITLE
metadata and moov atom handling missing from SabPostProcess

### ISSUE THREAD

**Issue by nzbjamz** [mdhiggins/sickbeard_mp4_automator#680]
It looks like like [SABPostProcess.py](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/SABPostProcess.py) is missing [metadata and moov atom](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/bd168bb28376eda08fac2b017081c413c5d8e5aa/postSonarr.py#L41-L50) handling that [postCouchPotato.py](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/postCouchPotato.py) and [postSonarr.py](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/postSonarr.py) have .

**Comment by nzbjamz** [comment]
In trying to prep a patch for this it looks like it will have to use `guessit` to get the imdb/tvdb tag for it since it's not provided by SAB as it is with Couch and Sonarr.

**Comment by mdhiggins** [comment]
This is by design. No plans to add guessing to the downloader scripts. It's clunky and not suitable for automation.

**Comment by nzbjamz** [comment]
Ah, that makes the `SABPostProcess.py` less appealing but it could still have the moov atom handled. That's something I can PR :)

**Comment by nzbjamz** [comment]
Moved to #681.
