### ISSUE TITLE
"Updating will not be possible to prevent deleting AppData on Update"

### ISSUE THREAD

**Issue by squeakygreens** [mdhiggins/sickbeard_mp4_automator#682]
I see the folder structure for Sonarr includes the settings and other files in the "bin" directory, but Radarr seems to use the same directory for most all files.

Any way to change this?

**Comment by SgtBatten** [comment]
Radarr and sonnar should be installed in different directories.

**Comment by squeakygreens** [comment]
Yea. And they are. What I mean is Radarr is throwing the "Updating will not be possible..." error, and upon investigating, I noticed all Radarr settings files are in the root Radarr directory (C:\ProgramData\Radarr) while my Sonarr installation has more subfolders, namely for the configuration files, seemingly preventing this error (C:\ProgramData\NZBDrone\Bin).

Is there any way to change the directory of these files in Radarr to remedy this error?

**Comment by mdhiggins** [comment]
This should be on the Radarr git. Doesn't seem to have anything to do with the script

**Comment by squeakygreens** [comment]
Yea, my mistake. Not sure how I ended up here hah.
