### ISSUE TITLE
Do not exit script until Relocating MOOV atom is complete

### ISSUE THREAD

**Issue by scoopydude2002** [mdhiggins/sickbeard_mp4_automator#685]
I'm using sickbeard_mp4_automator with SABnzbd to manually convert MKV to MP4 files using a custom postprocess script that calls on manual.py. I have Completed Download Handling turned on in Radarr to process the file. I find that this is more reliable than than having sickbeard_mp4_automator call Radarr to process the file. However, I notice that Relocating MOOV atom is occurring, the script exits. Radarr then thinks the file processing is complete and attempts to import the file before Relocating MOOV atom is complete.

Is there anyway to not exit the script until Relocating MOOV atom is complete?

**Comment by mdhiggins** [comment]
Script should not be exiting while the moov atom move is taking place. What makes you say it's exiting?

**Comment by scoopydude2002** [comment]
I did some more testing and you're right. I had some issues with Radarr importing movies that I thought it was related to this. But the script is working as expected. Thanks!
