### ISSUE TITLE
Question: DCA and AC3

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#686]
How can I set my autoProcess.ini for it to create an AC3 track from DCA track, but still retain the DCA track?
 
My goal is to when movies are processed to create the AAC/AC3 tracks from DCA tracks (which my current settings already does), but also retain the DCA track, so I can have all audio options available for maximum compatibility and options for audio tracks.

output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,hevc,h265,x265,HEVC,mpeg4,MPEG-4,MPEG-H,h.265,h.264
video-bitrate =
video-max-width =
h264-max-level = 5.1
use-qsv-decoder-with-encoder = True
ios-audio = aac
ios-first-track-only = False
ios-audio-filter =
max-audio-channels = 6
audio-codec = ac3, eac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
subtitle-codec = srt

**Comment by mdhiggins** [comment]
Not at the moment but its a feature I plan to add

**Comment by shpankey** [comment]
Been wanting this same thing forever. Looking forward to the addition!

**Comment by shpankey** [comment]
In the meantime, this is the code I've been using to do it in ffmpeg manually myself...

ffmpeg -hide_banner -y -i "input.mkv" -map 0:0 -map 0:1 -map 0:1 -map 0:1 -c:v copy -c:a:0 aac -b:a:0 256k -ac:a:0 2 -c:a:1 ac3 -b:a:1 640k -ac:a:1 6 -c:a:2 copy "output.mp4"

**Comment by shpankey** [comment]
An update with a few fixes and adjustments that solves some issues...

`ffmpeg -analyzeduration 2147483647 -probesize 2147483647 -hide_banner -y -i "INPUT.mkv" -movflags +faststart -map 0:0 -map 0:1 -map 0:1 -map 0:1 -metadata title="TITLE" -metadata:s:v:0 title="TITLE" -metadata:s:v:0 language=eng -metadata IAS1=eng -metadata:s:a:0 language=eng -metadata:s:a:1 language=eng -metadata:s:a:2 language=eng -metadata:s:a:0  title="AAC 2.0ch 256k Eng Audio" -metadata:s:a:1  title="Dolby Digital 5.1ch 640k Eng Audio" -metadata:s:a:2  title="DTS 5.1ch 640k Eng Audio" -disposition:a:0 default -c:v copy -c:a:0 aac -b:a:0 256k -ac:a:0 2 -strict -2 -c:a:1 ac3 -b:a:1 640k -c:a:2 dts "OUTPUT.mp4"`

**Comment by shpankey** [comment]
this option was just added to the current build, works great for me.
