### ISSUE TITLE
Proposal: Code Change def RemoveFile

### ISSUE THREAD

**Issue by traxinv** [mdhiggins/sickbeard_mp4_automator#688]
Hi @mdhiggins,

sorry to rehash an older issue but I ran into an issue where the renamer has deleted the file but the proc failes to rename the file to the replacement name. The error handling works as it runs through the loop again BUT the os.remove(filename) will always fail since the file was deleted in the prev loop and it will never reach the os.rename(replacement, filename) part. Here is my solution:

>     # Robust file removal function, with options to retry in the event the file is in use, and replace a deleted file
>     def removeFile(self, filename, retries=10, delay=30, replacement=None):
>         for i in range(retries + 1):
>             try:
>                 # Make sure file isn't read-only
>                 os.chmod(filename, int("0777", 8))
>             except:
>                 self.log.debug("Unable to set file permissions before deletion. This is not always required.")
>             try:
>                 if os.path.exists(filename):
>                     os.remove(filename)
>                 # Replaces the newly deleted file with another by renaming (replacing an original with a newly created file)
>                 if replacement is not None:
>                     os.rename(replacement, filename)
>                     filename = replacement
>                 break
>             except:
>                 self.log.exception("Unable to remove or replace file %s." % filename)
>                 if delay > 0:
>                     self.log.debug("Delaying for %s seconds before retrying." % delay)
>                     time.sleep(delay)
>         return False if os.path.isfile(filename) else True
> 

would it also be possible to make retries and delay an option from the program instead?

**Comment by mdhiggins** [comment]
Pushed this change
