### ISSUE TITLE
uTorrent script hanging

### ISSUE THREAD

**Issue by belariad** [mdhiggins/sickbeard_mp4_automator#689]
Windows 10 build 14393.693
uTorrent 3.4.9 w/ WebGUI enabled

If this is the wrong place to look for support I appologize but I couldn't find any official forums. I'm trying to get the uTorrent script working but I can't get it to execute properly. According to the uTorrent logs I think it's sending the correct command:

> [2017-02-24 14:13:17]  Executing: C:\sickbeard_mp4_automator-master\uTorrentPostProcess.py sonarr udp://tracker.trackerfix.com:82/announce D:\_uTorrent\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg] multi Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe.mkv 2F0A5F8A0A841F8E1F34CC29C81B77A64EA9B993 Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg]

And all I can find in the script folder's info.log file is this:

> 2017-02-24 14:06:32 - uTorrentPostProcess - INFO - uTorrent post processing started.
> 2017-02-24 14:06:32 - readSettings - INFO - C:\Python27\python.exe

The command line opens with those two lines and sits there for a few minutes. Oddly enough, it creates another folder inside of the download folder with the same name. Then it creates a new .mkv file inside that with the same name as the downloaded video in the folder above but it always sits at less than 100mb. Eventually the command line does something then disappears. The logs don't show any additional info after that so I ran the command manually and this is what it eventually does after hanging for a bit:

> 2017-02-24 14:19:58 - uTorrentPostProcess - INFO - uTorrent post processing started.
> 2017-02-24 14:19:58 - readSettings - INFO - C:\Python27\python.exe
> Traceback (most recent call last):
>   File "C:\MP4Automator\uTorrentPostProcess.py", line 160, in <module>
>     shutil.copy(inputfile, newpath)
>   File "C:\Python27\lib\shutil.py", line 119, in copy
>     copyfile(src, dst)
>   File "C:\Python27\lib\shutil.py", line 69, in copyfile
>     raise Error("`%s` and `%s` are the same file" % (src, dst))
> shutil.Error: `D:\_uTorrent\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg]\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg]\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe.mkv` and `D:\_uTorrent\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg]\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe[rarbg]\Brooklyn.Nine-Nine.S04E11E12.720p.WEB-DL.DD5.1.H264-GoApe.mkv` are the same file

For reference, this is my uTorrent section from the autoProcess.ini:

> [uTorrent]
> convert = False
> couchpotato-label = couchpotato
> sickbeard-label = sickbeard
> sonarr-label = sonarr
> bypass-label = bypass
> sickrage-label = sickrage
> webui = True
> action_before = stop
> action_after = removedata
> host = http://192.168.1.3:38081/
> username = Belariad
> password = **REDACTED**
> output_directory = 
> radarr-label = radarr

**Comment by SgtBatten** [comment]
Delete you username and password stuff mate

**Comment by mdhiggins** [comment]
Can you post your full autoProcess file? I suspect you have something weird going on in the extensions or copyto options

**Comment by belariad** [comment]
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/823067/autoProcess.txt)

**Comment by morpheus2n2** [comment]
I have a similar problem where I can't even get it to start the conversation, but just looking at where you have put 
[uTorrent]
convert = False This should be set to True if you want it to convert the files.

**Comment by mdhiggins** [comment]
Should be fixed
