### ISSUE TITLE
MP4 files > Set Video-Bitrate aren't being converted without Convert-MP4 being set

### ISSUE THREAD

**Issue by DutchyOven** [mdhiggins/sickbeard_mp4_automator#694]
This script works fantastically for conversions from mkv to mp4 but I'd like to use it to downgrade my mp4's without flagging convert mp4 = true. 

Basically I set the video-bitrate to 2000 in autoprocess and here is what Id like it to do...
video-bitrate>2000.mp4 = convert 
video-bitrate<2000.mp4 = skip

I have to set  convert mp4 = true for it to convert MP4's >2000 video bitrate which means it also will convert MP4s < 2000. If I don't set it to true it will skip both MP4s. So its basically all or nothing.

**Comment by mdhiggins** [comment]
No option to screen for bitrate but if you have your codecs set appropriately then files with the appropriate bitrate will just be remuxed without any transcoding so no quality would be lost. Just make sure all the appropriate codecs are added to the list so they are copied unless the bitrate is too high

**Comment by DutchyOven** [comment]
Thanks! One last question, is there anyway to skip a file by keyword then? I could just add a tag to files Ive already processed and skip them that way. Its all a time issue, there are a lot of files and even though it copies it still takes a minute or two so Id just love to add something to make them skip. I know this isnt what its for but just throwing it out there

**Comment by mdhiggins** [comment]
You could very easily write a batch script with manual.py and have it only process files with a certain keyword missing but it's not part of the script by default.

**Comment by DutchyOven** [comment]
Ahh I forgot about manual.py. Ive edited your mkvtomp4 to do things I want before but never messed with manual. Thanks!
