### ISSUE TITLE
Plex scan isn't being initiated after Radarr post-process.

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#700]

**Comment by mdhiggins** [comment]
The code is all there and should be working. Are you getting any errors that suggest there is a problem? Make sure all your Plex settings and tokens are correct.

**Comment by morpheus2n2** [comment]
This is actually a missing feat from Radarr, as they are slowly changing a lot of the code to make it work better with Movies some basic functions have been disabled.

**Comment by mdhiggins** [comment]
It has nothing to do with Radarr. This script has indecent Plex refreshing and it is enabled for the Radarr script.

**Comment by morpheus2n2** [comment]
Really, I never knew that, I thought it was all done to sonarr and radarr as I have set up the scanning part via them. :)
