### ISSUE TITLE
Radarr function not working after radarr update

### ISSUE THREAD

**Issue by izeen** [mdhiggins/sickbeard_mp4_automator#701]
Hello!

After the latest update of radarr the post processing broke. The file is post processed but it breaks when telling radarr whar folder to scan and import.

Error:
autoprocess.radarr - ERROR - [ERROR] Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.

Error from Radarr:

Request Failed: Sequence contains no matching element

Someone reported this at Radarr but dont know if the problem lies there or if something needs to be updated your end, ref: https://github.com/Radarr/Radarr/issues/1176

**Comment by mdhiggins** [comment]
Did you install the update from this morning that was supposed to fix this?

**Comment by Parkie** [comment]
I believe I updated it and still noticed the issue. Am I missing something?

**Comment by mdhiggins** [comment]
The other possibility is that your version of Radarr is out of date and you're using the newer version of the script that uses the new API standard. Verify that you're running the latest version of both.

**Comment by Parkie** [comment]
Thanks for you help, I did check that. It is the latest I can download. I'm using version 0.2.0.535 - Mar 12 2017

**Comment by Parkie** [comment]
I didn't realize my updates weren't set to nightly on Radarr. I apologize. Thank you for the help it seems to be working now.
