### ISSUE TITLE
Use CRF value instead of target bitrate

### ISSUE THREAD

**Issue by belariad** [mdhiggins/sickbeard_mp4_automator#702]
Is there any way to use the max bitrate to trigger a re-encode but instead of using the chosen bitrate, use a CRF value instead? I understand that if you set the bitrate too low, it could re-encode and possibly end up with a higher bitrate but I'm just trying to catch stuff that was encoded with too much detail and trust that CRF 22 is good enough for me.

I thought about using "preopts= -crf 22" but I'm not sure if that would overlap with the "-b:v" setting that I assume is getting passed to FFMpeg.

**Comment by mdhiggins** [comment]
Just pushed an update that adds this feature
Readme was updated to reflect the new setting
Give it a shot and let me know

**Comment by belariad** [comment]
I don't see the new readme yet (or can't find the new reference). Also, the autoprocess.ini file no longer has "radarr-label =" for the downloaders or "preopts/postopts =" in the MP4 section. Still referenced in the readSettings.py though.

Am happy to test when it's up!

**Comment by mdhiggins** [comment]
Just synced, sorry didn't go through the first time

**Comment by belariad** [comment]
See it now. Thanks!
