### ISSUE TITLE
feature request - ability to convert video file without media name/matching

### ISSUE THREAD

**Issue by elgallo** [mdhiggins/sickbeard_mp4_automator#703]
what I'd like to do is convert some media that is AVI to MP4 with the stream to the front. These are rare/hard to find spanish karaoke. transcodes seem to take up more resources than it should. diggnign around I found that it has bad B-frame references. Point is, that its not a tv show or movie and doesn't have any metadata that sb_mp4_auto could use. would like a manual option to bypass metadata search and just convert with the same name.

**Comment by mdhiggins** [comment]
You can use the -nt or --notag command line parameter with manual.py

**Comment by mdhiggins** [comment]
You can add the `-movflags faststart` option to your post opts if you want to move the moov atom with this setup
