### ISSUE TITLE
cap aac encoding to its channel limit

### ISSUE THREAD

**Issue by nzbjamz** [mdhiggins/sickbeard_mp4_automator#704]
I had my audio codec config as `audio-codec = aac,ac3` and ran into an error where it tried to transcode aac with a 7 channel audio. It errored with `[aac @ 0x18cff80] Unsupported number of channels: 7`. Capping the channels for aac is done [for the ios inserted channel](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/618fac3371f834d5308efbcbee0378327e7d4766/mkvtomp4.py#L354-L358) so I'm guessing something similar except to whatever the max aac channel count is (maybe 6?).

**Comment by mdhiggins** [comment]
Done, AAC now caps at 6 channels like AC3 does

**Comment by nzbjamz** [comment]
Thank you!
