### ISSUE TITLE
Subliminal adds subtitles even if embedded are already present

### ISSUE THREAD

**Issue by lbinderup** [mdhiggins/sickbeard_mp4_automator#708]
It looks like subliminal isn't doing

subliminal.core.check_video

before deciding to look for subtitles. This results in additional subtitles being downloaded for files that already have them.

**Comment by mdhiggins** [comment]
I'll look in to this. I also need to get around to updating to subliminal 2. Haven't had time recently I'll try to get to it though

**Comment by mdhiggins** [comment]
This is fixed
