### ISSUE TITLE
Support for services to run on seperate machine

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#710]
I'd like to be able to execute the script from Deluge hosted on a seperate machine. 

I have a VPS that is connected to my network via VPN, I'm using it as a seedbox. Is it possible to use this deluge install with the mp4_automator script running on my media server?

**Comment by mdhiggins** [comment]
I honestly have no idea, I suspect you may run into problems but creating a custom deluge script to pass the file back may be possible. But certainly out of the scope of the script by default to do this
