### ISSUE TITLE
Additional File conversion/copy after move to final Movie folder

### ISSUE THREAD

**Issue by sennico** [mdhiggins/sickbeard_mp4_automator#711]
I've been using this script forever and recently I updated to get Radarr support. Im noticing some behavior that I haven't seen before. Once a movie is passed to nzbget and finishes downloading the NZBPostProcess script kicks off and I see the mkv getting converted to mp4 within the download folder. After that is complete I see the file moved out into the final folder like "Movie Name (2016)". this is where things get confusing. After the file is copied and shows up as movie.mp4 it immediately gets renamed to movie.mp4.original and another movie.mp4 starts to get created. I'm not sure what that step is or why its happening in the final folder and not the download folder. I just noticed another thing thats happening, after the movie.mp4 is finished a new file is created movie.mp4.QTFS . Any help sorting out why this processing is split between the download and destination folder is greatly appreciated 

Thanks!

**Comment by mdhiggins** [comment]
That's normal. That's QTFS moving the MOV atom to the beginning of the file after tagging.

**Comment by sennico** [comment]
Shouldn't that all occur in the download folder though?I dont have an output_directory specified so I wasn't understanding why some of the conversion was happening in the download/source directory but other conversions like the MOOV atom stuff is happening in the destination folder.

**Comment by mdhiggins** [comment]
It's always been this way and it's because it needs to happen after tagging takes place. So it has to be during the final phase of post processing. You can disable QTFS to avoid this.

**Comment by sennico** [comment]
Makes sense I guess I never noticed it before. Thanks for the quick responses, this is a great project!

**Comment by mdhiggins** [comment]
No problem, enjoy!
