### ISSUE TITLE
Reconvert if file has no subtitles

### ISSUE THREAD

**Issue by dpkmon** [mdhiggins/sickbeard_mp4_automator#712]
Hi,

The automator is converting from mvk to mp4 flawlessly.

I have a library of files that have already been converted to mp4, but at the time of the conversion, some subtitles were not available, is there a way to make the automator to analyze the file and look for missing subs. If it finds subtitles, include them into the file.

Thanks!

**Comment by mdhiggins** [comment]
There isn't currently any existing way to do this but unfortunately
It would be a decent undertaking to build this out as well. You could potentially see if subliminal (another python project) could accomplish this
