### ISSUE TITLE
Sonarr conversion not kicking off with steps in README

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sickbeard_mp4_automator#716]
When following the steps in the README to have Sonarr post-process its downloads, disabling both CDH and the Drone Factory result in Sonarr not picking up downloaded episodes, and thus not running this script on them. Turning on CDH results in the shows being processed after they're moved. 

Is there any combination of settings that will process the shows before they're moved, or am I just doing something wrong?

**Comment by mdhiggins** [comment]
If you disable those features you need to set up your post downloader scripts to pass the file back. If you didn't set those up then the downloads will just sit there.
