### ISSUE TITLE
Connection refused 

### ISSUE THREAD

**Issue by usharf** [mdhiggins/sickbeard_mp4_automator#717]
What does this error refer to? I have no problem converting with `manual.py`.

```bash
NZBGetPostProcess: IOError: [Errno socket error] [Errno 111] Connection refused
NZBGetPostProcess: raise err
NZBGetPostProcess: File "/usr/lib/python2.7/socket.py", line 575, in create_connection
```

Looking at the log, it seems to be trying to access this URL:

```bash
2017-04-12 12:55:24 - autoprocess.autoProcessTV - INFO - Opening URL: http://localhost:8081/home/postprocess/processEpisode?nzbName=xxxxxxxxxxxxxxxxx.nzb&quiet=1&dir=%2Fcompleted%2FSeries%2Fxxxxxxxxxxxxxxxxxxxxxxxx.
2017-04-12 12:55:25 - autoprocess.autoProcessTV - ERROR - Unable to open URL
```

Which of course does not exist... not sure where the /home/postprocess comes from.

**Comment by mdhiggins** [comment]
What media manger is this trying to talk to? Sickbeard/Sonarr?
Either way you have your URL settings incorrect probably, post your relevant section of autoProcess.ini

**Comment by usharf** [comment]
Hi there, thanks for the reply. 

I'm setting things up in a docker farm, and realized I need to update the autoProcess.ini to point to the the relevant ip/name, and not `localhost`... seems to work now.

**Comment by usharf** [comment]
and thanks for this extension of course, really helpful!
