### ISSUE TITLE
Massive CPU Usage and Heat generation when converting from HVEC to MP4

### ISSUE THREAD

**Issue by seanvree** [mdhiggins/sickbeard_mp4_automator#720]
WIndows 10E

Hardware:
Intel i7-6700K
32GB RAM
1TB Samasung SSD

Problem:

When converting from HVEC to MP4, the usage on the CPU is maxed out and heat maxes out to 150F. only happens on HVEC. 

Settings;
```
[MP4]
ffmpeg = C:\FFMPEG-win64\bin\ffmpeg.exe
ffprobe = C:\FFMPEG-win64\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = H264,x264
video-bitrate = 
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = false
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 0
audio-filter = 
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts = 
video-crf = 
```

See Screenshot:

http://imgur.com/KdUTKzf

**Comment by justinglock40** [comment]
It is becausing HEVC is not optimized for CPU usage yet. So what's happening here is you machine trying to re-encode HEVC to H.264.

You could have you autoProcess.ini look like this and it will remux from mkv>mp4 without working so hard and let plex transcode on the fly for those clients that aren't compatible:  with it

_**video-codec:h264,x264,hevc,h265,x265,HEVC,mpeg4,MPEG-4,MPEG-H,h.265,h.264**_

**Comment by seanvree** [comment]
@justinglock40  - does this create an additional video file?

**Comment by justinglock40** [comment]
Nope just allows ffmpeg to change the container from mkv>mp4 without re-encoding the entire video file

**Comment by justinglock40** [comment]
direct copy so no quality loss

**Comment by seanvree** [comment]
Thanks! I'll check it out!

**Comment by justinglock40** [comment]
Did those settings work out for you?

**Comment by seanvree** [comment]
@justinglock40 I haven't had a chance to test it, however, follow up Q - when I run a manual job, does it use the autoprocess.ini settings?  If not, what settings does it use?

**Comment by justinglock40** [comment]
Yea it uses the autoProcess; +/- any command line directives you run in the manual job

**Comment by seanvree** [comment]
Got it! Thanks buddy!

**Comment by justinglock40** [comment]
No problem.
