### ISSUE TITLE
vbv maxrate Support

### ISSUE THREAD

**Issue by MReptile** [mdhiggins/sickbeard_mp4_automator#721]
Some devices like the chromecast have problems with CRF encoded Files that peak over 12 mbit/s during the movie.
Could you please add the --vbv-maxrate parameter?
So we could specify that despite crf the peak can never be higher than the specified bitrate.

I would really appreciate that. Thank you

**Comment by mdhiggins** [comment]
Just add it to the preopts or postopts parameters

**Comment by MReptile** [comment]
Could you please tell me the difference between preopts and postopts?
My english vocabulary is too limited to understand that.

Thanks in advance

**Comment by mdhiggins** [comment]
One goes at the beginning of the command line parameters. One goes at the end. Certain FFMPEG commands need to be either at the beginning or end. Some don't matter. Not sure regarding your specific command though. I would just try preopts first

**Comment by MReptile** [comment]
I tried it
postopts= -maxrate 10000k,-bufsize 30000k

Error:
Unrecognized option 'maxrate 10000k'.
Error splitting the argument list: Option not found

If i copy the command from the logs and execute it manually it works. /usr/bin/ffmpeg -i /filestoconvert/Final\ Destination\ 5\ \(2011\)/Final\ Destination\ 5-trailer.mov -vcodec copy -map 0:0 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -maxrate 100000k -bufsize 30000k -y /filestoconvert/Fina.mp4

**Comment by MReptile** [comment]
Thanks! Works perfectly
Everything else was a "RTFM"-Case

Thank you for your support
