### ISSUE TITLE
Limit conversions to a single instance?

### ISSUE THREAD

**Issue by cgram23** [mdhiggins/sickbeard_mp4_automator#723]
Is it possible to limit the number of ffmpeg instances running concurrently?  I've seen discussions around this topic, but no solid solutions yet. This is especially relevant with Sonarr while downloading a complete season at once....the ffmpeg thread storm kills CPU.  It appears as though pull request #326 would address this, but no traction in over a year.

Apologies if this as been asked and answered, I'm just not seeing a definitive solution.

**Comment by MReptile** [comment]
Use docker containers for your sonarr. 
Limit the cpu-Time in the dockerrun command

**Comment by SgtBatten** [comment]
I've found on windows it only converts 1 at a time which works well. Using sabnzbd to run the script after downloading and before it passes it on to sonarr or Radarr.

**Comment by cgram23** [comment]
@MReptile....I'm not sure how using the docker container will help..especially with Sonarr.  The issue is that, once one job completes in sabnzbd, the file starts converting with ffmpeg per the script.  When the next file completes in sabnzbd....it spins up another instance of ffmpeg.  And so on...until I have several instances of ffmpeg running simultaneously...none of which are moving particularly fast.  

@SgtBatten...unfortunately, Windows isn't an option. I'm running Ubuntu on ESXi with no funds for Windows licenses.  Besides, I prefer linux when at all possible.

The goal is to make this a linear process so that, regardless of how many jobs are queued in sabnzbd, one file will convert to completion before spinning up a subsequent instance of ffmpeg.

**Comment by ledge74** [comment]
I run this script on a raspberry pi2, and as it is really not powerful It would make sense to have this feature.

**Comment by gaben67** [comment]
You can set sabnzbd to Pause Downloading During Post-processing and Only Get Articles for Top of Queue, then it won't start conversation until the previous is done.

**Comment by cgram23** [comment]
@gaben67....this didn't work initially, but only because I had the 'convert' field of the SAB portion of autoProcess.ini set to FALSE.  Once I changed this to TRUE, sabnzbd handled the conversion before sending back to sonarr, and began processing linearly.

Thanks for the tip.
