### ISSUE TITLE
not in the correct format 

### ISSUE THREAD

**Issue by covername** [mdhiggins/sickbeard_mp4_automator#725]
I can't perform any batch functions as any directory passed responds with 

``c:\sickbeard_mp4_automator-master>python manual.py -i 'z:\vmedia\tv\'
Manual processor started.
C:\Program Files (x86)\Python36-32\python.exe
Please install QTFastStart via PIP, relocate_moov will be disabled without this module.
Audio bitrate was invalid, defaulting to 256 per channel.
32bit Python.
File 'z:\vmedia\tv\' is not in the correct format

I have tried 
z:\vmedia
'z:\vmedia'
"z:\vmedia"

**Comment by covername** [comment]
it will always say this so long as it is being executed form a administrator enabled cmd window. 

un-elevated performs as expected.

**Comment by mdhiggins** [comment]
That error you're getting is kind of generic. Its likely a permission/access issue though odd that you're getting it with admin

Did you try with a trailing backslash?

**Comment by covername** [comment]
Yes. I was able to locate the previous question that was asked on this topic and ran through the list of possible fixes. The only thing that fixed it was running it as an un-elevated user for some reason.

**Comment by justinglock40** [comment]
1. why are you converting to mp4 without having QT faststart installed?

2. if you put Python in you PATH you don't have to type out python everytime.

3. In my use with manual.py. It works as such:

manual.py -i "G:\complete _**This gives me the option to answer questions about guessit (note the open ended quotes)**_

manual.py -i "G:\complete" -a _**This runs the script with no user intervention (note the closed quotations this time**_

try that and see if it works for you.
