### ISSUE TITLE
FFmpeg Command Prompt

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#727]
Is there anyway to suppress the FFMPEG command prompt during post processing with utorrent on windows? This is the only application that does this. 

Also is there a way to have utorrent clean up the download folder once the file has been moved to its final destination?

**Comment by mdhiggins** [comment]
Set your `actionafter` to `removedata` for uTorrent in autoProcess.ini

And no, unfortunately not regarding suppressing the FFMPEG window

**Comment by justinglock40** [comment]
ok thats fine thanks for getting back to me. I just ended up switching to Deluge
