### ISSUE TITLE
installffmpeg

### ISSUE THREAD

**Issue by BrandonCampanile** [mdhiggins/sickbeard_mp4_automator#729]
`sudo bash ./installffmpeg.sh` gives the error:

`./installffmpeg.sh: line 29: syntax error near unexpected token 'echo'`

I did some research and the only reason I saw people have this error was due to a problem when the script was compiled. But it could literally be anything since i'm new to linux.

EDIT: Replaced the == with = and ran it as regular sh and it worked. `sudo ./installffmpeg.sh`

**Comment by mdhiggins** [comment]
Pushed an update that should hopefully fix this
