### ISSUE TITLE
FFMpegError

### ISSUE THREAD

**Issue by BrandonCampanile** [mdhiggins/sickbeard_mp4_automator#730]
I'm running the manual.py as a script in Sonarr, but Sonarr's logs are showing this mess:

<img width="939" alt="screen shot 2017-04-28 at 4 43 14 pm" src="https://cloud.githubusercontent.com/assets/25987443/25559927/4977a5d8-2cfb-11e7-89c9-1486ea76f45e.png">

No idea how what it means. I'm guessing the path to ffmpeg is off, but I ran installffmpeg.sh before getting these errors.

**Comment by mdhiggins** [comment]
You need to point the script so your FFMPEG binaries in autoProcess.ini

Additionally you need to not use manual.py for Sonarr. You should be using postSonarr.py

**Comment by BrandonCampanile** [comment]
I'm using Sonarr to execute the processing script and then upload to amazon cloud drive using rclone. This is my current script in Sonarr:
```
#!/bin/sh
echo "Converting video if needed"

/usr/bin/python /home/plex/sickbeard_mp4_automator/manual.py -i "${sonarr_episodefile_path}" -tv ${sonarr_series_tvdbid} -s ${sonarr_episodefile_seasonnumber} -e ${sonarr_episodefile_episodenumbers}

echo "Uploading to ACD"

/usr/sbin/rclone copy /home/plex/.local/L,ULJSSLPjETMTzk5OhzCioC/ acd:Plex/L,ULJSSLPjETMTzk5OhzCioC && rm -Rf "/home/plex/local/TV Shows/"*

exit
```

So instead I should replace manual.py with postSonarr.py (and change the path to ffmpeg in autoProcess.ini)? Or just follow the instructions for adding the automator to Sonarr, but add the `echo "Uploading to ACD"` section above to a new script and put it in the "post process" section since it will run that script once the code is finished?

**Comment by BrandonCampanile** [comment]
That’s what I’m thinking. So manual.py calls autoProcess.ini and I need to change the binary locations in autoProcess.ini?

After running installffmpeg, the binaries will be in ‘/usr/local/bin/’ right?

When run `ls -l` in that directory, I see this:
[cid:image001.png@01D2C1D0.9D0D0440]

**Comment by mdhiggins** [comment]
You're better off using postSonarr.py and setting your moveto directory or just using a postprocess script (see the readme) to handle copying/moving to your cloud storage
