### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by wraith1385** [mdhiggins/sickbeard_mp4_automator#731]
Hello,

All of a sudden tonight I am getting the below error.  Any thoughts?

Traceback (most recent call last):
  File "C:\Program Files\SABnzbd\scripts\SABPostProcess.py", line 11, in <module>
    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log').replace("\\", "/")})
  File "c:\python27\lib\logging\config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "c:\python27\lib\logging\config.py", line 163, in _install_handlers
    h = klass(*args)
  File "c:\python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "c:\python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "c:\python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\python27\lib\logging\__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: 'C:\\Program Files\\SABnzbd\\scripts\\info.log'

**Comment by justinglock40** [comment]
just make info.log writeable by whichever user or group sabnzbd is running as

**Comment by wraith1385** [comment]
I've changed the permissions and it works now, but I was just curious if there was a reason it all of a sudden stopped working after working fine for quite a while with no permissions errors.

**Comment by justinglock40** [comment]
did you pull any updates? or do any thing that caused it to be overwritten? or change the permissions over the entire directory?

**Comment by wraith1385** [comment]
No, the only thing that happened is that the pc crashed about an hour before this, but no updates were made to any of those directories.

**Comment by mdhiggins** [comment]
I haven't changed anything regarding permissions. I suspect this is on your end and the permissions were changed somehow
