### ISSUE TITLE
Script Logic

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#733]
Is there anyway to have the torrent scripts to check for sample folders and delete those. They interfere post processing of files and the cleanup afterwards. This is only an issue with private trackers as they tend to .rar the files and add sample videos.

The sample video being there causes the delete directory to halt because it sees the video there a making it not empty even though the main file has moved.

or maybe have ffprobe check and only process files with a runtime greater than 1 minute and delete everything else?

**Comment by mdhiggins** [comment]
Usually the media manager clients handle this aspect
