### ISSUE TITLE
extremely slow processing on a 1.3Gb mp4 file 

### ISSUE THREAD

**Issue by jcollum** [mdhiggins/sickbeard_mp4_automator#734]
```
mediainfo --fullscan file.mp4

General
Count                                    : 322
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Complete name                            : [removed]
File name                                : [removed]
File extension                           : mp4
Format                                   : MPEG-4
Format                                   : MPEG-4
Format/Extensions usually used           : mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v
Commercial name                          : MPEG-4
Format profile                           : Base Media
Internet media type                      : video/mp4
Codec ID                                 : isom
Codec ID                                 : isom (isom/iso2/avc1/mp41)
Codec ID/Url                             : http://www.apple.com/quicktime/download/standalone.html
CodecID_Compatible                       : isom/iso2/avc1/mp41
Codec                                    : MPEG-4
Codec                                    : MPEG-4
Codec/Extensions usually used            : mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v
File size                                : 1471420509
File size                                : 1.37 GiB
File size                                : 1 GiB
File size                                : 1.4 GiB
File size                                : 1.37 GiB
File size                                : 1.370 GiB
Stream size                              : 1471420509
Stream size                              : 1.37 GiB (100%)
Stream size                              : 1 GiB
Stream size                              : 1.4 GiB
Stream size                              : 1.37 GiB
Stream size                              : 1.370 GiB
Stream size                              : 1.37 GiB (100%)
Proportion of this stream                : 1.00000
HeaderSize                               : 40
DataSize                                 : 1471420469
FooterSize                               : 0
IsStreamable                             : No
File last modification date              : UTC 2017-05-06 14:17:05
File last modification date (local)      : 2017-05-06 07:17:05
```

I've seen this happen before with a very similar file (same show in fact). It'll chunk away on this for an hour. If I just cancel it, delete the file and download a different encoding of the same episode it will be done in less than 5 minutes. Most files I download (including 1080p content) are done in under 10 minutes. This one took at least an hour before I killed it. 

When I check `top`, `python` is using 100% CPU. 

CPU: 

```
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 61
Model name:            Intel(R) Celeron(R) 3205U @ 1.50GHz
Stepping:              4
CPU MHz:               1499.941
CPU max MHz:           1500.0000
CPU min MHz:           500.0000
BogoMIPS:              2993.04
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              2048K
```

Memory: 8GB, 2GB free when this is running 

Is there any more info I can provide that will help?

**Comment by mdhiggins** [comment]
Entirely depends on what is being done to the file
Remuxing is quick
Reencoding is slow, and depending on how many streams need to be reencoded this is compounded

**Comment by Collisionc** [comment]
Close the ffmpeg.exe process that is running, check the log file and see if ffmpeg is spamming this warning:
non-monotonous dts in output stream

I ran into the same file that you are. It was taking forever to re-encode only the audio, and when it finished it would be out of sync with the video.  It infuriated me so much that I engaged kludge/crappy hack mode to fix it:
https://github.com/Collisionc/sickbeard_mp4_automator/commit/c2aef76c5bde0be5ed91640f919bd349cb358782
(Explanation of what is occurring is in the commit note)

She sure isn't a pretty fix, but she works.

**Comment by mdhiggins** [comment]
If you're using manual.py the JSON output should specify which codecs are being copied vs which are needing active transcoding
If you post that output I can let you know if it looks like lots of transcoding is taking place

**Comment by jcollum** [comment]
I will check it out. Might be a while though.

**Comment by jcollum** [comment]
This is happening right now. Where can I find the relevant logs for ffmpeg ? or SBA logs?

**Comment by Collisionc** [comment]
Easiest way to force logs for ffmpeg is to open task manager in windows and end the process named ffmpeg.exe while it is encoding the video that is giving you problems. Then go to your sickbeard mp4 automator folder, and there will be a file named info.log, which will have the necessary logs.

I would delete info.log before you do this, so that it will only have logs from the most recent video.

**Comment by jcollum** [comment]
OK. Missed it that time (went to bed). I'll try and catch it next time it happens.

**Comment by jcollum** [comment]
This happened again tonight. I renamed `info.log` to `info.log.old` and then killed the ffmpeg process (not on windows though, used `kill` via ssh). Unfortunately it did not write out to `info.log`. 

```
/opt/sickbeard_mp4_automator $ ll | grep log
-rw-------  1 media media 1455721 Aug  4 21:03 info.log.old
-rw-r--r--  1 media media    1122 Mar 26 10:45 logging.ini
```
