### ISSUE TITLE
MKV not converting

### ISSUE THREAD

**Issue by mdizo** [mdhiggins/sickbeard_mp4_automator#735]
Hey love the work that you do 👍 

So my problem is that I have one particular file that isn't converting. All my other mkv files are converting fine, its just for some reason this one isn't. Looking through the log file in debug mode the error that comes up is:

> 2017-05-08 19:44:25 - mkvtomp4 - ERROR - Unabled to create external subtitle file for stream 2.
Traceback (most recent call last):
  File "C:\Users\mdizo\Documents\Scripts\sickbeard_mp4_automator-master\mkvtomp4.py", line 506, in generateOptions
    for timecode in conv:
  File "C:\Users\mdizo\Documents\Scripts\sickbeard_mp4_automator-master\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\Users\mdizo\Documents\Scripts\sickbeard_mp4_automator-master\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)

If I run this through manual.py it converts like it normally does. Any ideas?

**Comment by mdizo** [comment]
for more info this is my autoprocess.ini

> [MP4]
ffmpeg = C:\Users\mdizo\Documents\Scripts\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\Users\mdizo\Documents\Scripts\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = C:\Users\mdizo\Downloads\Torrents\CONVERTED\
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h265
video-bitrate = 
video-crf = 22
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = eng
download-artwork = Poster
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

> [uTorrent]
> convert = True
> couchpotato-label = couchpotato
> sickbeard-label = sickbeard
> sonarr-label = sonarr
> bypass-label = bypass
> sickrage-label = sickrage
> webui = true
> action_before = stop
> action_after = 
> host = http://localhost:36793/
> username = sonarr
> password = ********
> output_directory = 
> radarr-label = radarr

**Comment by justinglock40** [comment]
What client?

**Comment by mdizo** [comment]
utorrent

The run program is:
`C:\Python27\python.exe C:\Users\mdizo\Documents\Scripts\sickbeard_mp4_automator-master\uTorrentPostProcess.py %L %T %D %K %F %I %N`

**Comment by justinglock40** [comment]
can you try using C:\Python27\**pythonw.exe**?

**Comment by mdhiggins** [comment]
It looks like its running into an issue trying to create the external subtitle file
Not sure why that is unfortunately
You could try disabling that feature and see if the issue resolves
I'll take a look and see if I can sort out why though or at least transition this to a noncritical error
