### ISSUE TITLE
Implement mkvclean & validate with mkvalidator

### ISSUE THREAD

**Issue by Nottt** [mdhiggins/sickbeard_mp4_automator#744]
Mkvclean is a command line application for loseless optimization of mkv for streaming 

https://www.matroska.org/downloads/mkclean.html

And after running that on the mkv files run mkvalidator to make sure they are adhering to the protocol correctly and warn users if anything is wrong. 

https://www.matroska.org/downloads/mkvalidator.html

Can that be carried over to mp4 if you remux the file? Will the mp4 remux be optimized for streaming too?

Does mp4 automator do remux by default?

**Comment by mdhiggins** [comment]
Already does remuxing by default and already optimizes for streaming
Would be redundant to implement this

**Comment by Nottt** [comment]
Can you clarify how this script is doing loseless remuxing and optimizing without using mkvclean ? 

I believe there is no other way to do a loseless remux while also optimizing for streaming and still being a loseless remux

**Comment by mdhiggins** [comment]
Loseless remuxing is nothing special
Any sort of remuxing where no transcoding is taking place is lossless, the streams are simply moved from one container to the other without any modifications

The script will attempt lossless remuxing anywhere appropriate codec from the source video are found, then rearranges the MOOV atoms to optimize for streaming
