### ISSUE TITLE
Cannot tag odd files

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#745]
Forgive me I am a python and ffmpeg noob so cannot understand why random one piece episodes are not being tagged?

Here's an example log of trying to manually convert 1 episode that has trouble:
https://pastebin.com/kiXs2qwB

Am I just being stupid?

**Comment by Smalfinn** [comment]
Seems to complete after I replace the 'é' with an 'e'

**Comment by mdhiggins** [comment]
Yeah python gets stuck on random unicode characters like this occasionally, isn't much you can do about it except rename. It tries to circumvent it when it can but its not 100% effective
