### ISSUE TITLE
posters not shown on iOS devices // square posters for TV shows

### ISSUE THREAD

**Issue by tobsen987** [mdhiggins/sickbeard_mp4_automator#746]
Hey,

my iOS devices (iPad and iPhone, both on 10.3.2) don't show the embedded posters in the Videos app. There is simply an empty grey box. On my Mac in Finder and in iTunes however they show up.

I've read that iOS requires posters of TV Shows to be square to show them and if I add a square poster to a episode file it will show in the Videos app. But that doesn't explain why movie posters don't show up.

On http://squaredtvart.tumblr.com there are square posters for many shows. Would it be possible to add the images of this blog as an option for tagging? Wether there is an image can be checked via tumblr api: http://api.tumblr.com/v2/blog/squaredtvart.tumblr.com/posts/photo?tag=thetvdb+series+247897&api_key=KEY

This would search for all posters for Homeland (http://squaredtvart.tumblr.com/tagged/thetvdb-series-247897)

As for the movie posters I don't know what's the problem exactly, as I haven't figured out a way that they show again.

**Comment by mdhiggins** [comment]
Posters are showing fine on my iOS devices, not able to reproduce this

As far as the square art goes, using tumblr isn't a good option, there needs to be a reliable API to communicate with for the script to use that data in a way that's safe for automation

The regular posters should work fine for iOS though

**Comment by sinfuljosh** [comment]
btw, a mac app uses squaredtvart to populate their covers, so there either theres some unknown back end ... possible api setup. 

Or they are using the rss feed??

http://squaredtvart.tumblr.com/rss
