### ISSUE TITLE
Feature Request: option to sort files before processing in manual / automatic mode

### ISSUE THREAD

**Issue by Cheezykins** [mdhiggins/sickbeard_mp4_automator#748]
When running against a large repository of files, it would be nice to specify a sort order so that you can have some idea where it is in the process.

At the minute it just uses the filesystem order which in Python is arbitrary, meaning you could be processing a series starting with the letter A and yet be at the end of a run of 200 series.

**Comment by mdhiggins** [comment]
This could be easily done using a batch file or shell script

Adding additional settings to manual.py to specify this sorting order is lower priority at the moment and I probably won't get to it for some time

**Comment by Cheezykins** [comment]
Yeah, for a while now passing an individual file in with -i instead of a folder was erroring as it was attempting to reference the tvdbid variable before it was assigned, however I notice that's now fixed so I've been running with the following:

```
find /path/to/series -print0 | sort -z | xargs -0 -n 1 python manual.py -a -i
```
