### ISSUE TITLE
Sonarr/Radarr not connecting to sickbeard_mp4_automator/not picking up d/l files

### ISSUE THREAD

**Issue by jeff47** [mdhiggins/sickbeard_mp4_automator#749]
I have sickbeard_mp4_automator installed under Windows 10.  If I run the manual.py script, it converts the files without a problem.  However, Sonarr doesn't seem to be calling sickbeard_mp4_automator.py.  I don't see error messages, not much to go on.  Log level set to DEBUG.

I am running Sonarr 2.0.0.4836.  Sonarr is running as a service.  The downloads are coming from Deluge or SABnzbd.

Settings>General>URL Base = (empty)  
Settings>Download Client>Completed Download Handling = NO.
Settings>Download Client>Drone Factory = (empty)
Settings>Download Client>Drone Factory Interval = 0

Settings>Connect>Custom Script>Name = postSonarr
Settings>Connect>Custom Script>On Grab = NO
Settings>Connect>Custom Script>On Download = YES
Settings>Connect>Custom Script>On Upgrade = YES
Settings>Connect>Custom Script>On Rename = NO
Settings>Connect>Custom Script>Filter Series Tags = (empty)
Settings>Connect>Custom Script>Path = C:\Python27\python.exe
Settings>Connect>Custom Script>Arguments = D:\Media\scripts\sickbeard_mp4_automator\postSonarr.py

In autoProcess.ini:
[Sonarr]
host = localhost
port = 8989
web_root =
SSL = False
apikey = [redacted]

I assume that since running manual.py works, the settings in the [mp4] section are fine.

**Comment by jeff47** [comment]
So, I still haven't been able to solve this.  If I have Settings>Download Client>Completed Download Handling = NO in Sonarr, then nothing happens after the download is completed by the Download Client.

I'm feeling rather dumb here... surely if this was completely broken, lots of other folks would be bringing up issues.  But I've carefully gone through the docs several times and I just don't see any errors I've made.

(also - I can get this working using the SABpostProcess.py, but I was hoping to use postSonarr because it is more flexible.)

**Comment by mdhiggins** [comment]
You need to use SABpostProcess to send the file back to Sonarr otherwise it has no way of knowing the download finished
SABpostProcess can do the conversion there but doesn't so tagging, its meant to be used in conjunction with postSonarr and the other scripts

You can also turn off conversion here and have it only function to pass the file back to Sonarr

**Comment by jeff47** [comment]
So use SABpostProcess AND postSonarr together?  Ah, I assumed that would be redundant.  

So if I understand correctly:
1) enable SABpostProcess in SABnzbd - it will convert if specified in autoProcess.ini, but can't tag.
2) enable postSonarr in Sonarr "connect" - it will tag and convert unless if SABpostProcess has already done so.
3) turn "completed downloaded handling off" in Sonarr, since postSonarr will tell Sonarr when it's done.

**Comment by mdhiggins** [comment]
Almost exactly correct, except SABpostProcess is what notifies Sonarr not postSnarr (number 3)

**Comment by jeff47** [comment]
Oh right, of course.  Awesome - I was operating under the assumption that these were SABpostProcess and postSonarr were alternative means to the same end.  No wonder I wasn't getting anywhere.
