### ISSUE TITLE
Suggestion/question:  fullpathguess:  use radarr and sonarr directory names as "hints"

### ISSUE THREAD

**Issue by jeff47** [mdhiggins/sickbeard_mp4_automator#751]
The title says it all - if this isn't already implemented, when the "fullpathguess" option is turned on, does sickbeard_mp4_automator understand that a directory path containing "radarr" is a movie, and "sonarr" is a TV show?

**Comment by mdhiggins** [comment]
Probably not but this is entirely related to guessit, if you'd like to have this feature added I would post it over on their github 

https://github.com/guessit-io/guessit
