### ISSUE TITLE
Processing of invalid downloads / fetching next release

### ISSUE THREAD

**Issue by jkoopmann** [mdhiggins/sickbeard_mp4_automator#752]
Hi,

nzbToMedia is analyzing the downloaded video and in case it is one of those famous broken avi files it tries to send this back to couch potato etc. in order to fetch the next higher release. I am new to mp4_automator and I am struggling to find out whether or not it behaves the same way.

In case it does not, is there a way to "work around" that e.g. by using nzbToMedia and then use mp4_automator for postprocessing?

60min into the project I really like it and appreciate all the hard work that went into it so far! Thanks!

**Comment by mdhiggins** [comment]
How exactly is it analyzing the file? What characteristics determines that its a broken AVI file?

**Comment by jkoopmann** [comment]
I would have to take a look at the code but according to the logs it is running ffprobe and is searching for a video track in it. The broken files (avi, wmf) tend to have unknown codecs and things like ffprobe/mediainfo will simply "fail". In that case it is contacting the sonarr/couchpotato/etc. APIs and telling them it is a broken download and they will switch to the next better release.

Log says:
[17:37:40] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /usr/local/nzbToMedia/tests/test.mp4
[17:37:40] [INFO]::TRANSCODER: Checking [XYZ.BluRay.x264-ENCOUNTERS.mkv] for corruption, please stand by ...
