### ISSUE TITLE
handle dvb_teletext codec

### ISSUE THREAD

**Issue by jkoopmann** [mdhiggins/sickbeard_mp4_automator#753]
Hi,

recordings on my sat-receiver tend to have a dvb_teletext codec stream in it. I am fine to loose it by using the script however it simply fails to handle it because of ffmpeg not being able to handle it. Maybe there is some logic you can apply to simply filter out streams that are unnecessary?

> Input #0, mpegts, from 'test.ts':
>   Duration: 02:22:02.31, start: 17401.347889, bitrate: 8245 kb/s
>   Program 134
>     Stream #0:0[0x20](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
>     Stream #0:1[0xff]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
>     Stream #0:2[0x103](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.1(side), fltp, 384 kb/s (clean effects)
>     Stream #0:3[0x104](eng): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s (clean effects)
>   Program 135
>   Program 137
>   Program 138
>   Program 144
>   Program 4008
> Stream mapping:
>   Stream #0:1 -> #0:0 (copy)
>   Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
>   Stream #0:2 -> #0:2 (copy)
>   Stream #0:3 -> #0:3 (ac3 (native) -> aac (native))
>   Stream #0:0 -> #0:4 (? (?) -> mov_text (native))
> Decoder (codec dvb_teletext) not found for input stream #0:0

**Comment by mdhiggins** [comment]
Can you post the full ffprobe -show_steams output for one of these failing files?

**Comment by jkoopmann** [comment]
Sure:

ffprobe version 3.3.2 Copyright (c) 2007-2017 the FFmpeg developers
  built with FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --enable-shared --enable-pic --enable-gpl --enable-postproc --enable-avfilter --enable-avresample --enable-pthreads --cc=cc --disable-indev=alsa --disable-outdev=alsa --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libass --disable-libbs2b --disable-libcaca --disable-libcdio --disable-libcelt --disable-chromaprint --disable-libdc1394 --disable-debug --enable-htmlpages --disable-libfdk-aac --enable-ffserver --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --disable-libfribidi --disable-libgme --disable-libgsm --enable-iconv --disable-libilbc --disable-indev=jack --disable-libkvazaar --disable-ladspa --disable-libmp3lame --disable-libbluray --enable-mmx --disable-libmodplug --disable-netcdf --disable-openal --disable-indev=openal --disable-opencl --enable-libopencv --disable-opengl --disable-libopenh264 --disable-libopenjpeg --enable-optimizations --disable-libopus --disable-libpulse --disable-indev=pulse --disable-outdev=pulse --enable-runtime-cpudetect --disable-librubberband --enable-libschroedinger --disable-ffplay --disable-outdev=sdl --disable-sdl2 --disable-libsmbclient --disable-libsnappy --disable-indev=sndio --disable-outdev=sndio --disable-libsoxr --disable-libspeex --enable-sse --disable-libssh --disable-libtesseract --enable-libtheora --disable-libtwolame --enable-libv4l2 --enable-vaapi --enable-vdpau --disable-libvidstab --enable-libvorbis --disable-libvo-amrwbenc --enable-libvpx --disable-libwavpack --disable-libwebp --enable-libx264 --enable-libx265 --disable-libxcb --enable-libxvid --disable-outdev=xv --disable-libzimg --disable-libzmq --disable-libzvbi --disable-gcrypt --enable-gmp --disable-librtmp --enable-gnutls --disable-openssl --enable-version3 --disable-nonfree
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[h264 @ 0x80c217400] SPS unavailable in decode_picture_timing
[h264 @ 0x80c217400] non-existing PPS 0 referenced
[h264 @ 0x80c217400] SPS unavailable in decode_picture_timing
[h264 @ 0x80c217400] non-existing PPS 0 referenced
[h264 @ 0x80c217400] decode_slice_header error
[h264 @ 0x80c217400] no frame!
[h264 @ 0x80c217400] mmco: unref short failure
    Last message repeated 1 times
[h264 @ 0x80c217400] number of reference frames (0+4) exceeds max (3; probably corrupt input), discarding one
[mpegts @ 0x80c271000] PES packet size mismatch
    Last message repeated 1 times
Input #0, mpegts, from test.ts':
  Duration: 02:22:02.31, start: 17401.347889, bitrate: 8245 kb/s
  Program 134
    Stream #0:0[0x20](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
    Stream #0:1[0xff]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:2[0x103](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.1(side), fltp, 384 kb/s (clean effects)
    Stream #0:3[0x104](eng): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s (clean effects)
  Program 135
  Program 137
  Program 138
  Program 144
  Program 4008
Unsupported codec with id 94215 for input stream 0

**Comment by mdhiggins** [comment]
Pushed an update that should blacklist that codec and prevent the FFMPEG failure

Give it a show and let me know

**Comment by jkoopmann** [comment]
Brilliant. Thanks. Working like a charme.

On 29.06.17 | KW26, 18:49  "Michael Higgins" <notifications@github.com<mailto:notifications@github.com>> wrote:

Pushed an update that should blacklist that codec and prevent the FFMPEG failure

Give it a show and let me know
