### ISSUE TITLE
Help with setup, not converting files to mp4

### ISSUE THREAD

**Issue by ausghostdog** [mdhiggins/sickbeard_mp4_automator#754]
Hi,
Can I get some help with the install please, I am using Sickrage

https://imgur.com/jd9P7A5

This is an image showing it running the post processing and the script

https://i.imgur.com/ObIwQLo.png

Image showing the file still an .mkv

https://pastebin.com/yAZRTYLd
Edit
I've now added 
[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe

and also installed apt-get install ffmpeg -y
 
This is myt auto Process.ini, I've left it default other than setting the api key for sickrage, do I remove all the other settings I am not using?

In the post processing for sickrage for extra scripts I have /usr/bin/python /sickbeard_mp4_automator/postConversion.py

To install I used the following commands

40  pip install requests
   41  apt install python-pip
   42  pip install requests
   43  pip install --upgrade pip
   44  pip install requests[security]
   45  pip install requests-cache
   46  pip install babelfish
   47  pip install "guessit<2"
   48  pip install "subliminal<2"
   49  pip install stevedore==1.19.1
   50  pip install python-dateutil
   51  pip install qtfaststart
   67  git clone https://github.com/mdhiggins/sickbeard_mp4_automator/
   68  ls
   69  cd sickbeard_mp4_automator/
   70  ls
   71  mv autoProcess.ini.sample autoProcess.ini
   72  ls
   73  vi autoProcess.ini

running the process manually worked 
https://i.imgur.com/1jaH18r.png

Permissions on the files and folders
https://i.imgur.com/QJnYsJC.png

Possible permissions issue?

**Comment by mdhiggins** [comment]
Thanks for your very thorough documentation, its refreshing.
Your setup process looks correct as does your settings, and the fact that Sickrage is attempting to trigger the script suggests that's set up correctly.

I think the next step will be to check info.log after running a Sickrage processing attempt and see if any errors are present that may provide further information

Additionally one more thing to try would be to remove the python path from the Sickrage post processing settings and only point it to the postConversion.py file. Windows tends to need the python path but I would think linux would recognized and respect the shebang and execute the script without the path to the python executable. Perhaps that extra component in the path is causing issue.

**Comment by ausghostdog** [comment]
So I made a few changes, I set permissions to that whole folder to sickrage and the sickrage group, I also made the change you suggested of removing the python path. What I will do is set the permissions back to root and see if it was just the pyton path.

**Comment by mdhiggins** [comment]
I'm guessing that change made it work?

**Comment by ausghostdog** [comment]
Yeah it is working fine noiw, thanks.
