### ISSUE TITLE
sick beard hogging CPU in python process

### ISSUE THREAD

**Issue by jkoopmann** [mdhiggins/sickbeard_mp4_automator#755]
Hi,

I have some recorded .ts files which I want to convert to MP4. Unfortunately the second audio is tagged "deu" while it should be "eng" so I used mkvtoolnix to change it which muxed the ts to an mkv. I now run mp4_automator on it and suddenly it takes FOREVER. When I run mp4_automator on the .ts it looks fine, the speed is normal and top shows ffmpeg eating CPU (which is expected). If I run it on the mkv speed is terrible (we are talking > 15h for a convert that usually takes like 10minutes or so) and top shows python as the CPU problem. The corresponding ffmpeg processes are there as well and are doing "something" but while the python process shows a total of 706:09 CPU time the corresponding ffmpeg only shows 10:43...

Any idea?

Small feature request: I see that in the ffmpeg command you are executing you are setting the languages. Maybe build in something to overwrite it? This would allow me to correct wrong languages and convert in a single blow.

Regards,
   JP

**Comment by mdhiggins** [comment]
Can you post the ffprobe -show_streams output of both a TS file and then MKV file that's giving you problems?
