### ISSUE TITLE
Possible to use multiple encoding profiles?

### ISSUE THREAD

**Issue by jeff47** [mdhiggins/sickbeard_mp4_automator#756]
I am curious about this:  I have a second autoProcess.ini set up for videos I grab for my daughter.  I don't care as much about quality for those, and only want 2 channel sound.  I can manually run manual.py with the --config option, but is there a way to automate the process in SABnzbd based on a tag/category?

**Comment by mdhiggins** [comment]
I do like this idea but as of now that’s not a feature I have built in quite yet

You could potentially just clone your directory and have 2 version of the script installed and point to different post-download scripts for the conversion

**Comment by jeff47** [comment]
I was able to come up with a short-term solution by modifying postSonarr.py and using Sonarr.  Presumably the same thing could be done in SABNzbd by modifying line 29 (ReadSettings).

I made a copy of postSonarr.py and modified Line 17 to point to a different autoProcess.ini, and then pointed the Connect script at that.

**Comment by jeff47** [comment]
Another option, which I think I will work up on my end, is to have postSonarr.py look at the episode pathname and make decisions based on that.  My media organization looks like:
/media/TV
/media/Movie
/media/Kids

I'll just have it load a different ini file if the path matches.

**Comment by mdhiggins** [comment]
For now this is probably the best solution, I'll look towards implementing a better way to do this in the future

**Comment by jeff47** [comment]
I'm sharing this in case it is useful to anyone:

My media organization looks like this:
\\diskstation\video\TV\...
\\diskstation\video\Kids\...
\\diskstation\video\Movies\...
\\diskstation\video\Exercise\...

Each of these is managed in Plex as a library, so it's easy to grant access for my daughter only to the Kids library.

I modified postSonarr.py so that it looks for a custom autoProcess.ini based on the parent/Library name.  EG, if autoProcess_Kids.ini exists, it uses it.  Otherwise, it uses the default.  

In postSonarr.py, I inserted these lines after line 27: 
```python
seriespath = os.environ.get('sonarr_series_path')
autoProcessINI = "autoProcess_%s.ini" % os.path.split(os.path.split(seriespath)[0])[1]

if os.path.isfile(os.path.join(os.path.dirname(sys.argv[0]),autoProcessINI)):
    settings = ReadSettings(os.path.dirname(sys.argv[0]), autoProcessINI)
    log.info("Loading %s" % autoProcessINI)
else:
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
    log.info("Loading default autoProcess.ini")
```
