### ISSUE TITLE
Deluge Post Process Failing

### ISSUE THREAD

**Issue by Holmes093** [mdhiggins/sickbeard_mp4_automator#760]
Manual.py working perfectly fine.

Deluge Post Process is failing with the below error:

[root@6535f363c384 Completed]# /Scripts/M4V/delugePostProcess.py
2017-07-09 14:22:29 - delugePostProcess - INFO - Deluge post processing started.
2017-07-09 14:22:29 - readSettings - INFO - /usr/sbin/python
2017-07-09 14:22:29 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-07-09 14:22:29 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

If I run it with the parameters I get the following error:

[root@6535f363c384 Completed]# /Scripts/M4V/delugePostProcess.py %L %T %D %K %F %I %N
2017-07-09 14:19:01 - delugePostProcess - INFO - Deluge post processing started.
2017-07-09 14:19:01 - readSettings - INFO - /usr/sbin/python
2017-07-09 14:19:01 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-07-09 14:19:01 - delugePostProcess - INFO - Successfully connected to Deluge
Traceback (most recent call last):
  File "/Scripts/M4V/delugePostProcess.py", line 44, in <module>
    torrent_files = torrent_data['files']
KeyError: 'files'
[root@6535f363c384 Completed]# 

Not sure how to debug this? Any insight?

Thanks.

**Comment by mdhiggins** [comment]
Looks like the script is failing to pull data from deluge. Check your autoprocess settings and make sure you're using deluge daemon and not just the regular deluge client.

**Comment by Holmes093** [comment]
AutoProcess as follows:

Server:Docker john$ cat Scripts/M4V/autoProcess.ini 
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = admin.holmes.ws
port = 443
web_root = /tv
ssl = True
apikey = d7159ef6a74f436e91ebeeb361e74a9a

[Radarr]
host = localhost
port = 7878
web_root = 
ssl = False
apikey = 

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = m4v
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[Deluge]
host = 127.0.0.1
username = holmes
convert = true
password = password
sonarr-label = tv-sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = true
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 
radarr-category = radarr

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token = 


I am definitely using the deluge deamon.

**Comment by mdhiggins** [comment]
I didn’t catch that you’re using Docker, that might be where the issue is then
I’m not super familiar with how Docker works but I know its sandboxes everything
Perhaps that is isolated the deluge-daemon and that is failing to  communicate with the python script when run?

And while your autoProcess.ini settings look like they could be correct, without looking at the daemon settings and verifying that they match I can’t provide much help. You’ll need to verify that the settings match what is set in the settings panel in deluge

**Comment by Holmes093** [comment]
> Perhaps that is isolated the deluge-daemon and that is failing to  communicate with the python script when run?

2017-07-09 14:19:01 - delugePostProcess - INFO - Successfully connected to Deluge

So it does connect and if i open the deluge client on another machine on the network I can connect to the daemon running on that machine.

Might be helpful to know that when i run postSonarr.py I get:

2017-07-09 19:12:09 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2017-07-09 19:12:09 - readSettings - INFO - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2017-07-09 19:12:09 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "/Users/john/Docker/Scripts/M4V/postSonarr.py", line 21, in <module>
    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
TypeError: int() argument must be a string or a number, not 'NoneType'

Thanks

**Comment by Holmes093** [comment]
Started from scratch and I am now past this error. Closing this one. Will open new issue with unrelated error.

**Comment by wjbeckett** [comment]
@Holmes093 What did you to get past the `KeyError: 'files'` error?

I'm having the same issue on my docker container.

**Comment by notorius28** [comment]
@Holmes093 same problem here, in my case appears to be solved using python2 instead of python3
