### ISSUE TITLE
radarr access issue but no changes since it worked

### ISSUE THREAD

**Issue by goofballtech** [mdhiggins/sickbeard_mp4_automator#761]
At some point on July 7th my script decided it didn't like Radarr anymore. Nothing changed. it have been a few days and half a dozen downloads since the last radarr update. Now i get this. 
```
2017-07-10 21:08:30 - SABPostProcess - INFO - Passing Z:\nzbAutoDownloadComplete\movies\Gifted.2017.1080p.BluRay.x264-GECKOS directory to Radarr.
2017-07-10 21:08:30 - autoprocess.radarr - INFO - Radarr notifier started.
2017-07-10 21:08:30 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'Z:\nzbAutoDownloadComplete\movies\Gifted.2017.1080p.BluRay.x264-GECKOS'.
2017-07-10 21:08:30 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
  File "C:\Convert\autoprocess\radarr.py", line 64, in processMovie
    log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
TypeError: list indices must be integers, not str
```

I have double and triple checked the API key and details. Sabnzbd, Deluge, and Sonarr all seem to be doing their thing fine. Any idea's where to look?

Thanks.

**Comment by mdhiggins** [comment]
See here
#743

**Comment by goofballtech** [comment]
webroot is defined in sonarr and radarr, sonar is working, radarr is not. 

I do not think the linked thread is my issue as i had already looked at it and verified that i had webroot defined and it was correct.

```
[Radarr]
web_root = /radarr
apikey = sdfsdfgsdfgsdfgsdfgsdfg
port = 7878
ssl = 0
host = localhost
```

**Comment by mdhiggins** [comment]
Did you try accessing your API via the browser and see if the URL matches your settings?

This error is what you see when the API URL isn't correct or isn't returning any data. 

Something isn't working between opening the URL and the expected response

**Comment by goofballtech** [comment]
> Did you try accessing your API via the browser and see if the URL matches your settings?

multiple times over the last few days as the error specifically calls that out. Other programs are using the same API and working fine though. Thats why i came here to post. it seems to be something out of the norm that is going on. 

Sonarr and Radarr are set in my reverse proxy the same way, are set in autoprocess the same way, the API's are correct according to their web interfaces. Sonarr works fine, Radarr does not. 

My biggest thing is that nothing i know of changed on the 7th when it stopped working. I updated Sonar and Radarr at the same time on July 4th to their most recent stable versions. 

Radarr worked on the current version from the 4th until the morning of the 7th. The last successful import was about 10AM on the 7th. The next movie to download happened at about 9PM on the 7th and the above error showed up and has persisted since then. API keys have not been regenerated, scripts have not changed, but it seems something happened and im not sure where else to look.

**Comment by mdhiggins** [comment]
Were there any updates to the script that you did between the time it last worked and the time it stopped working?

Additionally you can look look in the info.log files with debugging enabled (enabled by modifying loggini.ini) and the entire API URL that is generated should be printed there. Then you can check that URL for errors or post it here and I can take a look

**Comment by goofballtech** [comment]
No sir. nothing has been updated since right at the end of June or maybe July 1. 
There were a few days of things working great and nothing was changed during the time window of things failing. Not sure which category Radarr falls in the loggini.ini file but i changed them all to debug. Going to try to redownload a file and see what it says, will be back to post output after checking in browser.

**Comment by goofballtech** [comment]
it looks like it's just inputting the letters "api" instead of the actual key. SHould i try to update sionce something seems off in the insertion of the key to the URL?

```
2017-07-11 11:44:21 - autoprocess.radarr - DEBUG - Radarr host: localhost.
2017-07-11 11:44:21 - autoprocess.radarr - DEBUG - Radarr port: 7878.
2017-07-11 11:44:21 - autoprocess.radarr - DEBUG - Radarr apikey: asdasdfasdfasdfasdfasdfasdfasdf.
2017-07-11 11:44:21 - autoprocess.radarr - DEBUG - Radarr protocol: http://.
2017-07-11 11:44:21 - autoprocess.radarr - DEBUG - URL 'http://localhost:7878/api/command' with payload '{'path': 'Z:\\nzbAutoDownloadComplete\\movies\\Gifted.2017.BDRip.x264-GECKOS', 'name': 'DownloadedMoviesScan'}.'
2017-07-11 11:44:21 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'Z:\nzbAutoDownloadComplete\movies\Gifted.2017.BDRip.x264-GECKOS'.
2017-07-11 11:44:21 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
  File "C:\Convert\autoprocess\radarr.py", line 64, in processMovie
    log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
TypeError: list indices must be integers, not str
```

**Comment by mdhiggins** [comment]
So for Radarr I'm under the impression that the API key isn't actually part of the URL but is attached in the URL header, so not seeing the API key in the URL is normal, unless the Radarr people changed that

**Comment by mdhiggins** [comment]
https://github.com/Radarr/Radarr/wiki/API

Their wiki seems to indicate that's the case, its attached as part of the header
If you try going to http://localhost:7878/api?apikey=YOURAPIKEY does that work?

**Comment by goofballtech** [comment]
that returns the below in my browser. tried with API key pulled from radarr directly as well as the one from the debug log. 
```
{
  "message": "NotFound"
}
```

This is what radarr's log output is from the above shown request
```
17-7-11 11:44:20.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (1 ms)
17-7-11 11:44:21.9|Debug|Api|[POST] /api/command: 303.SeeOther (0 ms)
17-7-11 11:44:21.9|Debug|Api|[GET] /api/command: 200.OK (1 ms)
```

**Comment by goofballtech** [comment]
So i went to Sonarr's [API page
](https://github.com/Sonarr/Sonarr/wiki/API) and used their format to see what sonarr gave me. Got an expected result. 

Used that same syntax and swapped the information to Radarr.
`http://localhost:7878/radarr/api/system/status?apikey=asdfasdfasdfasdfasdf`
produces
```
{
  "version": "0.2.0.778",
  "buildTime": "2017-06-20T15:47:20Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": true,
  "isUserInteractive": false,
  "startupPath": "C:\\ProgramData\\Radarr\\bin",
  "appData": "C:\\ProgramData\\Radarr",
  "osVersion": "6.2.9200.0",
  "isMonoRuntime": false,
  "isMono": false,
  "isLinux": false,
  "isOsx": false,
  "isWindows": true,
  "branch": "develop",
  "authentication": "none",
  "sqliteVersion": "3.8.7.2",
  "urlBase": "/radarr",
  "runtimeVersion": "4.0.30319.42000"
}
```

**Comment by mdhiggins** [comment]
So the radarr web_root isn't working, that's the difference between the URLs.
The URL your script is generating doesn't have the webroot
Which again is the same as the issue I posted above
I'm guessing you're using the older version of the script that doesn't have the web_root bug fixed in the radarr.py file that was referenced in #743

**Comment by mdhiggins** [comment]
If you open radarr.py and look at line 40-50 should be

 ```
webroot = settings.Radarr['webroot']
 url = protocol + host + ":" +  port + webroot + "/api/command"
```

If its just line 49 saying
```
url = protocol + host + ":" + port + "/api/command"
```

then you're still on the old version

**Comment by goofballtech** [comment]
ok. just went and looked. sonarr and radarr were both missing that argument as compared to the versions on the site. Can you explain how i update 11/12 days ago and got a version that was older than the 29 days ago that the last commit was done to those files? Or how they both worked at first then only one stopped?

Every bit of troubleshooting logic in my head would have pointed away from such an issue. especially since the web_root argument was in the autoprocess.ini, i did not add it there myself. 

Anyway, i hope you are correct even though i have no idea how it worked at all with a required bit of code just completely missing. Starting a new download now to check. thanks for your assistance.
