### ISSUE TITLE
Rename file with tags after processing?

### ISSUE THREAD

**Issue by flease** [mdhiggins/sickbeard_mp4_automator#764]
Hi! 
Thanks for an amazing tool. I'm wondering if it is possible for the script to use tags to rename the files after mp4 conversion? So a a long filename could become "Title (year).mp4". I've searched the net for something like this, but I can't seem to find a drop-in solution. 

Thanks!

**Comment by morpheus2n2** [comment]
What software are you using this in combination with?
As Apps like, Sonarr, Radarr, Couchpotato etc will all do that automatically for you when there sorting the files out.

**Comment by flease** [comment]
Hey! Just want to sort out a big library of movies. So no app. :-)

**Comment by morpheus2n2** [comment]
ahh, far as I know you can't use the app to rename not sure it it can be added or not.
But I would strongly advise getting Filebot rename all your files how you like (as long as the names are not to jumbled)
I would also advise using [Raddar](https://github.com/Radarr/Radarr) to help sort and rename you Movies in the future.

**Comment by flease** [comment]
Right! Good tip. Thanks!

**Comment by mdhiggins** [comment]
You can use Radarr sonar or couch potato for preexisting files and just point it to your messy directory and they will scan and process all these files
