### ISSUE TITLE
SABPostProcess python path is incorrect in OSX

### ISSUE THREAD

**Issue by sinfuljosh** [mdhiggins/sickbeard_mp4_automator#765]
## Issue
I was having some difficulty with SABNZBD returning errors stating it was missing modules. 

> Traceback (most recent call last):
> File "/Volumes/MediaBay/mp4_automator/SABPostProcess.py", line 5, in <module>
> from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
> File "/Volumes/MediaBay/mp4_automator/autoprocess/autoProcessMovie.py", line 11, in <module>
> import requests
> ImportError: No module named requests

## Troubleshooting
Verified that all modules were installed and properly working by confirming no issues when using manual.py

I think the root cause is due to sabnznbd's python script using /usr/bin/python [as seen here](https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py), and the automators sabpostprocess script making use of env to grab the path's. 

The issue is more than likely isolated around OSX as the version of python included in OSX has issues with some of the modules (requests[security]) and most users use an alternate version via homebrew which places its path elsewhere /usr/local/bin/python. 

## Workaround
I'm not sure if this is something that can be accounted for possibly by adding an override in the ini for the python path, or possibly something similar to the sickrage workaround including the path in the configuration page. 

Currently I have modified the first line of the SABPostProcess.py path to point directly to the homebrew build of python which has all the required modules, but this path would be different for different people and not the best solution.

Verified working after changing path: 

> 2017-07-14 09:46:30 - SABPostProcess - INFO - SAB post processing started.
> 2017-07-14 09:46:30 - readSettings - INFO - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> 2017-07-14 09:46:30 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2017-07-14 09:46:30 - SABPostProcess - INFO - Performing conversion
> 2017-07-14 09:46:30 - SABPostProcess - INFO - Processing file /Volumes/MediaBay/Downloads/complete/TV/Arrow.S05E12.1080p.WEB-DL.DD5.1.H.264-DRACULA.4/170118_14.mkv.
> 2017-07-14 09:46:30 - mkvtomp4 - INFO - Reading video stream.
> .....
> 2017-07-14 09:46:31 - mkvtomp4 - INFO - Reading audio streams.
> ......
> 2017-07-14 09:46:31 - mkvtomp4 - INFO - Starting conversion.
> 2017-07-14 09:48:27 - mkvtomp4 - INFO - /Volumes/MediaBay/Downloads/complete/TV/Arrow.S05E12.1080p.WEB-DL.DD5.1.H.264-DRACULA.4/170118_14.mp4 created.
> 2017-07-14 09:48:27 - SABPostProcess - INFO - Passing /Volumes/MediaBay/Downloads/complete/TV/Arrow.S05E12.1080p.WEB-DL.DD5.1.H.264-DRACULA.4 directory to Sonarr.
> 2017-07-14 09:48:27 - autoprocess.sonarr - INFO - Sonarr notifier started.
> 2017-07-14 09:48:27 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/Volumes/MediaBay/Downloads/complete/TV/Arrow.S05E12.1080p.WEB-DL.DD5.1.H.264-DRACULA.4'.
> 2017-07-14 09:48:27 - autoprocess.sonarr - INFO - Sonarr response: queued.

**Comment by mdhiggins** [comment]
Unfortunately there's no good workaround to this, you either have to modify the shebang (the first line of the file) or use virtual environments. This is just how OSX handles its python installation

This thread had a good discussion
https://stackoverflow.com/questions/16503761/python-shebang-problems-with-importing-modules-and-choosing-the-correct-interpr

**Comment by sinfuljosh** [comment]
That was my assumption also, the other alternative is to not use the pre-built SABNZBD app and to run it the same way you would within a linux system using the source files.
