### ISSUE TITLE
Feature Request: Add -tag:v option for hvc1

### ISSUE THREAD

**Issue by automator0** [mdhiggins/sickbeard_mp4_automator#767]
New apple software (ios 11, high sierra, tvos11) requires the fourcc codec id to be "hvc1" and not "hev1" to playback HEVC/H265 natively. Is it possible to add an option for this for encoding and copying if the codec matches hevc/h265/x265?

As of now, this command only works with the latest ffmpeg snapshot for output to .mp4 and .m4v.

An example is here for the option:
ffmpeg -i sample.wmv -c:v libx265 -preset medium -crf 23 -tag:v hvc1 -c:a libfdk_aac -b:a 128k test.mp4

Thanks

**Comment by mdhiggins** [comment]
Done

**Comment by automator0** [comment]
Thanks! how do I toggle this option for conversion?

**Comment by mdhiggins** [comment]
It's added automatically for anything converted to that codec

**Comment by automator0** [comment]
Hello, does this also work if the video is copied? meaning it is already hevc but just adding the tag? i've test it already and the tag doesn't seem to work.

Thanks
