### ISSUE TITLE
[REQ] Ability to specify the order of audio streams as well as the default. 

### ISSUE THREAD

**Issue by sinfuljosh** [mdhiggins/sickbeard_mp4_automator#768]
When using the mp4 automator's ios-audio option to add an aac 2 channel audio, it places this audio stream in front of any existing streams and sets it as the default. 

The issue here is that some apps like Sonarr and Radarr that have rename functions will use only the first or default stream for the media info during renaming. 

So while my movie originally has 2 audio streams (eac3, ac3), the script will create an additional stereo stream using aac and it gets pushed into the first stream and has its disposition set to default. 

Radarr sees the audio streams but only uses the first one so my renames end up coming out as AAC 2.0. 

Perhaps the audio codecs section can put in a way so that it uses the order that you entered them into the ini (from left to right) as a guide to determine the audio stream order. 

And a new setting in the ini to specify the default audio codec, if that codec is not found then whatever codec was found and placed as the first audio stream according to their order of preference would be used. 

I am able to go back using ffmpeg manually and reorder the audio streams using the -map and -disposition options, I am just not proficient in python to make this change in the existing scripts.

**Comment by shpankey** [comment]
You could add this to the .ini file, either in preopts or postopts, I'm not sure which, but try one then the other on a practice file.

-disposition:a:1 default,

...will set the second audio stream as the default

-disposition:a:2 default,

...will set the third audio stream as the default

**Comment by sinfuljosh** [comment]
That is awesome, I didnt know that there was that option to manually set them. 

This would essentially work by for any file being converted that is taking advantage of the ios-audio option. 

The only snag would be in adding this to the ini, wouldnt this break the script for any files that already contain a single AAC stereo audio stream?? 

Or those that contain something like only 1 stereo AC3 stream (which gets converted to AAC stereo and the original AC3 stream is dropped)

**Comment by mdhiggins** [comment]
Just pushed an update to the script that adds an `ios-move-last` boolean option to autoProcess.ini

This will have the iOS audio be the last option on a per source steam basis and adjusts the default disposition accordingly so now your default track can be the multi channel variant

There's no good way to manually specify the order of tracks because its a dynamic thing but this should give you more control

**Comment by sinfuljosh** [comment]
Thanks I was trying to figure out how some apps go about making use of the fallback audio option. But I can't find much information about it
