### ISSUE TITLE
FFMpeg issue on MacOS

### ISSUE THREAD

**Issue by sciblu** [mdhiggins/sickbeard_mp4_automator#769]
![image](https://user-images.githubusercontent.com/9732434/28253858-d9db32b8-6a75-11e7-9637-65df93058412.png)
![image](https://user-images.githubusercontent.com/9732434/28253862-e4eea658-6a75-11e7-87e9-dc3b75250327.png)

**Comment by sinfuljosh** [comment]
youve got a typo in your autoProcess.ini?? 

the script is looking for ffmpeg in /usr/local/Cellar/ffmpeg/3.3.2/bin/ffmpeg**_e_**

if you type   `which ffmpeg` what is the outcome?
also what is the settings you put in your autoProcess.ini for ffmpeg?

```
[MP4]
ffmpeg = 
ffprobe = 
```

**Comment by sciblu** [comment]
When I type ffmpeg in terminal it outputs: 
$ which ffmpeg
/usr/local/bin/ffmpeg
the location has an alias file made by homebrew. If I run ffmpeg in terminal the output:

$ ffmpeg
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

my autoProcess.ini is:
[Radarr]
host = localhost
port = 7878
web_root =
ssl = False
apikey = *********************

[MP4]
ffmpeg = /usr/local/Cellar/ffmpeg/3.3.2/bin/ffmpege
ffprobe = /usr/local/Cellar/ffmpeg/3.3.2/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-crf =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
max-audio-channels =
audio-codec = acc
audio-language =
audio-default-language =
audio-channel-bitrate =
audio-filter =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts =
preopts =

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
radarr_category = radarr
output_directory =
radarr-category = radarr

[Plex]
host = localhost
port = 32400
refresh = True
token =

[Sonarr]
ssl = False
host = localhost
apikey =
port = 8989
web_root =

[Deluge]
username =
sonarr-label = sonarr
output_directory =
host = localhost
radarr-label = radarr
password =
port = 58846
convert = True
sickbeard-label = sickbeard
remove = false
couchpotato-label = couchpotato
bypass-label = bypass
sickrage-label = sickrage

[uTorrent]
username =
action_after = removedata
sonarr-label = sonarr
output_directory =
host = http://localhost:8080/
radarr-label = radarr
webui = False
password =
convert = True
sickbeard-label = sickbeard
couchpotato-label = couchpotato
action_before = stop
bypass-label = bypass
sickrage-label = sickrage

[CouchPotato]
username =
delay = 65
host = localhost
apikey =
web_root =
delete_failed = False
ssl = False
password =
port = 5050
method = renamer

[SickBeard]
username =
password =
ssl = False
host = localhost
web_root =
api_key =
port = 8081

[Sickrage]
username =
password =
ssl = False
host = localhost
web_root =
api_key =
port = 8081

![ffmepeg_location](https://user-images.githubusercontent.com/9732434/28281108-fd11c20a-6af3-11e7-9ae7-5d75ec3b17b2.png)
![homebrew_ffmpeg](https://user-images.githubusercontent.com/9732434/28281109-007ab3b6-6af4-11e7-8ddd-6c1010f9211e.png)

**Comment by sciblu** [comment]
I was able to fix the original issue. There was a typo in my autoprocess.ini. One in ffmpeg and the second for the audio. I was able to manually run the script in terminal and the video was able to convert from mkv to mp4 w/aac. The second issue I'm having is when sabnzbd runs the post processing script. The error that is appearing is:

traceback (most recent call last):
File "/Volumes/DATA HD/sabnzb/mp4convert/sickbeard_mp4_automator-master/SABPostProcess.py", line 5, in <module>
from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
File "/Volumes/DATA HD/sabnzb/mp4convert/sickbeard_mp4_automator-master/autoprocess/autoProcessMovie.py", line 11, in <module>
import requests
ImportError: No module named requests

In terminal when I type the command pip3 list, requests are there
$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.22.0)
babelfish (0.5.5)
beautifulsoup4 (4.6.0)
certifi (2017.4.17)
cffi (1.10.0)
chardet (3.0.4)
click (6.7)
cryptography (1.9)
dogpile.cache (0.6.4)
enzyme (0.4.1)
guessit (1.0.3)
idna (2.5)
pbr (3.1.1)
pip (9.0.1)
pycparser (2.18)
pyOpenSSL (17.1.0)
pysrt (1.1.1)
python-dateutil (2.6.1)
qtfaststart (1.8)
requests (2.18.1)
requests-cache (0.4.13)
setuptools (32.2.0)
six (1.10.0)
stevedore (1.19.1)
subliminal (1.1.1)
urllib3 (1.21.1)
wheel (0.29.0)

These files are located in: /usr/local/lib/python3.6/site-packages

**Comment by sinfuljosh** [comment]
I posted about this earlier in the week. [Issue765](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/765)

Change SABPostProcess.py scripts first line.

Original:   `#!/usr/bin/env python`
New:  `#!/usr/local/bin/python`

I think the underlying issue is SAB's python  scripts used in the OSX precompiled dmg file has its shebang (the first line with the  !#/path/ ) set to use OSX's version of python (/usr/bin/python).

That patch is being caried through to the post processing script via the "Original" path's use of /usr/bin/env.

Telling it to specifically use the homebrew python in that single script is a workaround for now.

**Comment by sciblu** [comment]
It worked. Everything is working properly now. Thank you for helping.
