### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by ernspiker** [mdhiggins/sickbeard_mp4_automator#770]
Hi,

When ever the script runs my cpu usage hovers around less than 10% but my memory runs at 90%-100%. And then conversion takes a very long time.

**Comment by mdhiggins** [comment]
This is probably more related to FFMPEG than anything else, the script doesn't use much memory, but copying/remuxing streams will use lots of memory with minimal CPU usage

**Comment by ernspiker** [comment]
Yeah it was an ffmpeg issue. I downgraded a few versions and it works great now.
