### ISSUE TITLE
Posters not tagging

### ISSUE THREAD

**Issue by raynotroy** [mdhiggins/sickbeard_mp4_automator#772]
Hey,

I have been using this script for a long time and until recently it was working great.  The posters are no longer tagging and this has been the case for a few months.  If someone could take a look at my [autoProcess.ini](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1156805/autoProcess.ini.txt) and help me out that would be greatly appreciated.

Thanks,
Ray

**Comment by mdhiggins** [comment]
Haven't had any issues with this personally, I wonder if there's a new permissions issue with your temporary director thats preventing the download?
Are you getting any errors in your logging?

**Comment by mdhiggins** [comment]
Additionally is this with every script? or just a specific one? Does manual.py work?
Are you getting metadata without poster or are both missing?

**Comment by raynotroy** [comment]
I am not getting any errors in my log.  [I have attached my log file for you to look over](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1164535/info.log.txt).  This file has metadata added by the script without the poster.  It appears to be only the posters that are missing, everything else works fine.

**Comment by mdhiggins** [comment]
Sometimes this error occurs because the script doesn’t have permission to write to the temporary directory and cannot store the posters

I would try running manual.py with elevated privileges and see if the poster feature starts to work

Additionally its always a good idea to make sure thetvdb is working on your ISP and you can access the site without issue

**Comment by raynotroy** [comment]
I have been running the script with "sudo" because it won't run any other way. Do you know how to set permissions on a linux based NAS (Drobo5N)? I can access thetvdb just fine.

**Comment by mdhiggins** [comment]
I'm not sure how to go about fixing the permissions on the NAS then, I'm not too familiar with them

Are you encountering the same problem with movies and TV shows or only TV shows?

**Comment by raynotroy** [comment]
I have this problem with both movies and TV shows.

**Comment by raynotroy** [comment]
Is it possible to change the script so the temp file can be in a "tmp" folder in the same directory as the script?

I don't know if that would solve my problem but I think that's the next logical step.  I can't find the temporary directory to chmod it, so knowing the location would be helpful.

**Comment by mdhiggins** [comment]
If the filename is in the appropriate format (mp4) and you have convert-mp4 set to false, manual.py will enter a 'tag only' mode and just do the metadata

You can modify the tmdb_mp4.py and tvdb_mp4.py files to change your temporary directory if you'd like and see if that fixes your issue

**Comment by raynotroy** [comment]
Still no luck getting posters to work, I think they aren't downloading correctly but I don't know enough about it to say.

**Comment by mdhiggins** [comment]
You can modify logging.ini to increase the error reporting to DEBUG and the potentially get some more information about why its not tagging and then post those logs here

Other than that I have no idea why you're having trouble.
I'm still able to downloading posters without issue on my end
