### ISSUE TITLE
Can someone give some examples of the preopts and postopts commands?

### ISSUE THREAD

**Issue by shpankey** [mdhiggins/sickbeard_mp4_automator#773]
Trying to figure out what goes in here, for example, options such as these...

`-movflags +faststart, -metadata:s:v language=eng, -metadata:s:a language=eng, -metadata IAS1=eng, -metadata:s:a:0  title="AAC 2.0ch 256k Eng Audio", -disposition:a:0 default, -ac:a:0 2 -strict -2`

...where could I put them?

**Comment by mdhiggins** [comment]
The preopts and postopts are good for commands that aren't generated on a track basis (commands that don't have *:a:0 formating)
Almost all of the parameters you listed above are generated by the script anyway with the exception of the IAS1, and title.

The only exception is the movflags option, which should look like `postopts = -movflags, faststart` in autoProcess.ini

**Comment by shpankey** [comment]
What separates commands? a semicolon or something? for example, if i wanted to add the following options...

-vsync 0 -hwaccel dxva2 -threads 1

...how would that look?

ie: preopts = -vsync, 0; -hwaccel, dxva2; -threads, 1;

...???
