### ISSUE TITLE
ios-audio is not transcoding correctly

### ISSUE THREAD

**Issue by raynotroy** [mdhiggins/sickbeard_mp4_automator#774]
I have been having trouble with the ios-audio track when converting from ac3 or eac3.  Below is a MediaInfo screenshot showing the low bitrate that was created by ffmpeg.  I'm using ffmpeg v3.3.2.  Is there anything I can do to fix this? I've been using XMedia Recode to convert this file just fine, so the problem is either ffmpeg itself or the command that mp4-automator uses to call ffmpeg.

![Here is a MediaInfo screenshot](https://user-images.githubusercontent.com/10928598/28512683-e5012098-7020-11e7-9f81-bded403b0705.jpg)

**Comment by mdhiggins** [comment]
Can you post your autoprocess settings and the ffprobe show_steams output of both your source and final file?

**Comment by raynotroy** [comment]
I deleted the final file, but I can start the conversion process again if that will help.  I should note that I have noticed this problem on other files as well.

I ran the following command on the input file:
`sudo /mnt/DroboFS/Shares/DroboApps/mp4-automator/bin/ffprobe -show_streams /mnt/DroboFS/Shares/RRL/Game\ of\ Thrones\
S07E02\ -\ Stormborn\ -\ WEB-DL-1080p.mkv`
[This is the output of that command](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1169887/ffprobe.show_steams.input.file.txt)

This is my current autoprocess.ini:
`ffmpeg = /mnt/DroboFS/Shares/DroboApps/mp4-automator/bin/ffmpeg`
`ffprobe = /mnt/DroboFS/Shares/DroboApps/mp4-automator/bin/ffprobe`
`threads = auto`
`output_directory = `
`copy_to = `
`move_to = `
`output_extension = mp4`
`output_format = mp4`
`delete_original = True`
`relocate_moov = True`
`video-codec = h264,x264,mpeg4,MPEG-4,h.264`
`video-bitrate = `
`video-crf = `
`video-max-width = `
`h264-max-level = `
`use-qsv-decoder-with-encoder = True`
`ios-audio = True`
`ios-first-track-only = False`
`ios-audio-filter = `
`max-audio-channels = `
`audio-codec = aac,ac3,eac3,e-ac-3,dts`
`audio-language = `
`audio-default-language = eng`
`audio-channel-bitrate = 0`
`audio-filter = `
`subtitle-codec = mov_text`
`subtitle-language = `
`subtitle-default-language = eng`
`subtitle-encoding = `
`fullpathguess = True`
`convert-mp4 = True`
`tagfile = True`
`tag-language = en`
`download-artwork = True`
`download-subs = False`
`embed-subs = True`
`sub-providers = thesubdb,opensubtitles`
`permissions = 0777`
`post-process = False`
`pix-fmt = `
`aac_adtstoasc = False`
`postopts = `
`preopts = `

**Comment by raynotroy** [comment]
I edited my previous comment to include the information you requested.  Thanks for you hard work!

**Comment by mdhiggins** [comment]
Try changing your audio-channel-bitrate value to a nonzero value, like 128, and see if this resolves your issue

**Comment by raynotroy** [comment]
That worked! I have one last question.  When I set "audio-channel-bitrate" to 192 the resulting file is 256 and I can't figure out why.  Do you have any insight into this issue?

**Comment by mdhiggins** [comment]
Probably just not enough source data to hit those bitrate goals

**Comment by raynotroy** [comment]
No when set to 192 it comes out as 256, not the other way around.

**Comment by mdhiggins** [comment]
The 192 setting is per channel, since the iOS audio is 2 channels, your total target bitrate would be 384 which is fairly high, so it drops off to 256 since anything higher can cause problems since not enough source data is present
If you want 192 as your total data then set your channel bitrate to 96
