### ISSUE TITLE
tagging failed but didn't update plex library

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#776]
logs: https://pastebin.com/bsu6uVes

Manual import, tvdb.com is down at the moment so tagging failed but then the script did not update my plex library

Is this normal?

**Comment by mdhiggins** [comment]
Hm yeah it looks like tag failure can prevent plex notification
I'll wrap the tagging process in a try/except to prevent this
03175c07759fec1aa673d6eed2a04d58886d8b87

**Comment by Smalfinn** [comment]
Speedy work, appreciate it, thank you
