### ISSUE TITLE
preopts issue

### ISSUE THREAD

**Issue by shpankey** [mdhiggins/sickbeard_mp4_automator#780]
When adding this to the .ini

preopts = -hwaccel, dxva2

I get this error back:
Unrecognized hwaccel:  dxva2.
Supported hwaccels: d3d11va dxva2 qsv cuvid

Also, just for testing, I switched to qsv (even though I know you have this option already)
preopts = -hwaccel, qsv

...and get the following:
Unrecognized hwaccel:  qsv.
Supported hwaccels: d3d11va dxva2 qsv cuvid

...so it appears it is adding the "period" to it? ie: qsv. or dxva2. instead of just qsv or dxva2

p.s. I'm trying to get the nvidia decoder to work, which is why I'm asking. tia

**Comment by shpankey** [comment]
Also, what separates commands? a semicolon or something? for example, if i wanted to add the following options...

-vsync 0 -hwaccel dxva2 -threads 1

...how would that look?

ie: preopts = -vsync, 0; -hwaccel, dxva2; -threads, 1;

...???

**Comment by Mirabis** [comment]
It is comma-separated. For the other question(s)/issue(s) I can't help you.

**Comment by shpankey** [comment]
Wait, so like this...

ie: preopts = -vsync, 0, -hwaccel, dxva2, -threads, 1, etc

??

**Comment by mdhiggins** [comment]
Yes
