### ISSUE TITLE
Feature Request: Emby Support

### ISSUE THREAD

**Issue by wjbeckett** [mdhiggins/sickbeard_mp4_automator#781]
Would be good to be able to notify Emby to update libraries the same way the script does for Plex when processing is finished.

**Comment by mdhiggins** [comment]
Looking through Emby documentation and it looks like they removed their web based API that they previously had?

Any idea if there's still a way to trigger a library refresh programatically on Emby similar to plex?

**Comment by mdhiggins** [comment]
This should be able to be achieved by the post_process script implementation now with a custom emby refresh script
