### ISSUE TITLE
[Question] Deluge Set-up

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#782]
So I'm currently setting up deluge on a separate computer from my main server so that I can have it be on VPN network alone for torrenting. I have setup a share to have deluge download directly to my other computer that does all the heavy lifting normally. My question is Do I need to setup a second installation of this script with the "execute torrent complete" on the Deluge only computer or since I'm using Radarr and Sonarr on the other computer will they handle all the post-processing and removal from deluge with the script setup on the other computer?

**Comment by Sithlord82** [comment]
Why not just leave Deluge on the main server still and add the VPN in to the proxy setting? I've done it that way and it saves any complicated setups and Deluge still goes through the VPN.

**Comment by mdhiggins** [comment]
That’s what I do as well

**Comment by justinglock40** [comment]
which vpns work with proxy setting?

**Comment by mdhiggins** [comment]
PIA
