### ISSUE TITLE
Support DVD ordering from The TVDB

### ISSUE THREAD

**Issue by trolley** [mdhiggins/sickbeard_mp4_automator#785]
When manually converting files it would be nice to be able to tell the script to use DVD ordering from The TVDB. As it works now it uses aired ordering, which fails for shows I've ripped myself from DVD.

**Comment by mdhiggins** [comment]
I don't believe TVDB exposes DVD ordering in their API even in the V2 api
Sonarr is also having issues getting this to work

You can read more about it here
https://github.com/Sonarr/Sonarr/issues/255

**Comment by trolley** [comment]
Interesting. dbr/tvnamer supports it and I see he does it by using his own dbr/tvdb_api API instead of the official TVDB one.

**Comment by trolley** [comment]
@mdhiggins The TVDB API does include DVD season and episode after all: https://api.thetvdb.com/swagger#!/Series/get_series_id_episodes

**Comment by mdhiggins** [comment]
TVDB is no longer used
