### ISSUE TITLE
mark processed job as done

### ISSUE THREAD

**Issue by AaronG85** [mdhiggins/sickbeard_mp4_automator#786]
I guess this would more fall under the category of a feature request, But I have just started using this program and it is amazing. Two things I was wondering (if it's possible)
1. Is there a way to mark a file as 'Done' or 'Processed' as I'm currently doing my whole library (over 32TB) and sometimes I need to restart the manual process and I noticed it processes all the files I've already done again.
2. Is there a way to have a tray icon in Windows to indicate when this script is running?

**Comment by mdhiggins** [comment]
1. Not really, my advice would be not to use manual.py if you want process/monitoring of files and rather integrate the script into one of the media managers (CP/SB/Sonarr) and then have that manually process your directories. It will track what has been added and converted and will handle running the script on the files when appropriate. The script is an extension of these existing pieces of software
2. No, its a multiplatform python script. You could maybe compile manual.py using py2exe and set it up as a tray icon program but as a python script you can't
