### ISSUE TITLE
Support Vuze as downloader

### ISSUE THREAD

**Issue by trolley** [mdhiggins/sickbeard_mp4_automator#788]
Would it be possible to support Vuze as a downloader? It's the only torrent client I've found that's easy to configure to bind to my VPN interface.

**Comment by mdhiggins** [comment]
If I recall correctly Vuze doesn't have proper post processing script execution or support labels/categories which is essential for the process to be able to work.
That being said using Radarr and Sonarr you don't necessarily need any scripts to run after the download component of the process and they can monitor Vuze themselves and then do all the processing after they move the file

Let me know if I am mistaken and Vuze has updated but a quick search doesn't show anything

**Comment by trolley** [comment]
I'll take a look and reply back here. I'm just setting everything up for the first time so it's all new to me (labels, post-processing scripts, etc).

I thought the same but I configured the postSonarr and postRadarr scripts to run after download but they weren't kicked off after the download completed, so I assumed downloader script was needed.

**Comment by trolley** [comment]
I never followed up on this. Following the instructions to disable completed download handling in Sonarr after the file finishes downloading nothing happens. I tried turning that option back on and then the post-processing to convert works but then both the original file and converted get copied to the season directory.
