### ISSUE TITLE
audio-copy-original = False is ignored

### ISSUE THREAD

**Issue by zsmbrvr** [mdhiggins/sickbeard_mp4_automator#789]
I have a mkv file with ac3 audio and I want to convert it to mp4 with one aac stream.

I suppose **audio-copy-original = False** should do this, but it still ends up copying the ac3 audio track.

> 
> [MP4] 
> ffmpeg = ffmpeg.exe 
> ffprobe = ffprobe.exe 
> threads = auto 
> output_directory = 
> copy_to = 
> move_to = 
> output_extension = mp4
> output_format = mp4
> delete_original = True
> relocate_moov = True
> video-codec = h264,x264
> video-bitrate = 
> video-crf = 
> video-max-width = 
> h264-max-level = 
> use-qsv-decoder-with-encoder = True
> ios-audio = True
> ios-first-track-only = False
> ios-audio-filter = 
> ios-move-last = False
> max-audio-channels = 
> audio-codec = aac,mp3,dts,dca,ac3
> audio-language = eng
> audio-default-language = eng
> audio-channel-bitrate = 
> audio-filter = 
> audio-copy-original = False
> subtitle-codec = mov_text
> subtitle-language = aa
> subtitle-default-language = 
> subtitle-encoding = 
> fullpathguess = True
> convert-mp4 = False
> tagfile = False
> tag-language = en
> download-artwork = Poster
> download-subs = False
> embed-subs = False
> embed-only-internal-subs = False
> sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
> permissions = 0777
> post-process = False
> pix-fmt = 
> aac_adtstoasc = False
> postopts = 
> preopts =

**Comment by mdhiggins** [comment]
You still have AC3 audio as an approved codec so it will be copied
The audio-copy-original functionality only serves to preserve an original copy of the stream in the event that it would otherwise be re-encoded

**Comment by easy90rider** [comment]
What should I put into the settings file to have only one AAC audio track?

I tried with:

> audio-codec = aac
> audio-language = eng
> audio-default-language = eng
> audio-channel-bitrate = 
> audio-filter = 
> audio-copy-original = False

But then I get one AAC 2.0 and one AAC 5.1 :(
