### ISSUE TITLE
Tagging working at random, mostly not working.

### ISSUE THREAD

**Issue by sickgrinder** [mdhiggins/sickbeard_mp4_automator#79]
I just started using this a few weeks ago but on almost all mkv's/mp4/m4v I keep getting the exact same error when it attempts to tag.

Trying to write tags
An unexpected error occurred, processing of this file has failed
cannot fit 'long' into an index-sized integer

There something that I have not set correctly?

**Comment by mdhiggins** [comment]
As of commit 8375e799c53cfa9a0d87d62cccf747072875ee97 a workaround for this issue has been found and tagging should work on 32 bit systems regardless of file size
