### ISSUE TITLE
Obsolete instruction in the FAQ

### ISSUE THREAD

**Issue by keldian** [mdhiggins/sickbeard_mp4_automator#790]
Thanks for the fantastic script but I believe the Readme needs an update. Specifically this bit in the Radarr section : 

> Set the Drone Factory Interval' to 0 to disable it, and **disable 'Completed Download Handling'** in Radarr settings. The script will trigger a specific path re-scan, allowing the mp4 conversion to be completed before Radarr starts moving stuff around. This step is optional if you do not desire any processing between the downloading by whichever downloader you choose (NZB or Torrent), but is required if you wish to convert the file to an MP4 before it is handed back to Radarr.

While the Sickrage setup was a breeze, it took me about a week of troubleshooting to figure out why I couldn't get Radarr to hand over processing to the script, until I _enabled_ Completed Download Handling just to see what happens. Now my downloads are getting converted without a problem.

**Comment by mdhiggins** [comment]
You’re not supposed to enable completed download handling if you want conversion after downloading before handing back

The script works with that on but the correct thing to do is to set up the post downloader scripts (postSAB / deluge / torrent / nzbget etc) which will hand the converted file back to Radarr

**Comment by keldian** [comment]
Now I'm confused. The FAQ doesn't say anything about having to set up post downloader scripts for the Radarr setup to work. Also, I use rutorrent so I'm not sure that's an option.

And what benefit does "conversion after downloading before handing back" have ? Now that I've enabled Completed Download Handling the end result is exactly what I want, which is a converted MP4 in the movies import directory.

**Comment by abhishekjain14** [comment]
"conversion after downloading before handing back" is useful for a situation like mine, where I'm downloading to a local computer but storing on a NAS. Running this script on my NAS would be painfully slow, but that's what Sonarr does when you have it run the script after handing back - move the file over _then_ run the script
