### ISSUE TITLE
preopts error.

### ISSUE THREAD

**Issue by nomadturk** [mdhiggins/sickbeard_mp4_automator#792]
I was desperately trying to run the script with some preopts set.
Such as:

preopts = -tune, zerolatency,-maxrate, 10M,-preset, medium,-x264opts, cabac=0:8x8dct=1:bframes=0:subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none

But, whenever I added anything to preopts the script didn't run.
When I checked the command closer, I saw that the commands I entered at preopts were being placed wrong as in before the file path and they were failing. And none of the preopts I set were being run while the script was initializing.

I had to swap line 449 and 450 in order to load any preopts commands after "-i file.mkv" command.

Like this:

```
        cmds = [self.ffmpeg_path]
        if preopts:
            cmds.extend(['-i', infile]) # Swapped with the line below
        cmds.extend(preopts)
```

Now I can run the script and for once it doesn't create files bigger than the source!

PS: This is how I was able to run the script with preopts. I have no python knowledge and this is merely a hack.
I am using the latest master repo @Debian 8 with deb-multimedia packages.

**Comment by nomadturk** [comment]
Update: 
Turns out since I had mpeg4 and hevc included in video-codec line, this doesn't work when I need to transcode instead of remuxing.
I can't pass any preopts the way the script works.
Conversation only starts when I clear preopts values because this way all preopts are entered before after -i.

```
<FFMpegConvertError error="Exited with code 1", pid=42741, cmd="/usr/bin/ffmpeg -tune  zerolatency -preset  veryfast -x264opts  cabac=1:8x8dct=1:bframes=0:b-adapt=2:subme=0:me_range
=4:rc_lookahead=10:me=tesa:no_chroma_me:partitions=none:vbv-maxrate=17500:vbv-bufsize=17500:ref=2 -i /Storage/Movies/Star Wars Episode II - Attack of the Clones (2002)/Star Wars Episode II - Attack 
Of The Clones [2002] [tt0121765] [1080p].mkv -vcodec libx264 -map 0:0 -crf 24 -level 4.0 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -ac:a:0 6 -b:a:0 896k -metadata:s:a:0 language=eng -c:a:1 li
bfdk_aac -map 0:2 -disposition:a:1 none -ac:a:1 6 -b:a:1 896k -metadata:s:a:1 language=eng -c:a:2 copy -map 0:3 -metadata:s:a:2 language=eng -disposition:a:2 none -c:a:3 copy -map 0:8 -metadata:s:a:3 l
anguage=eng -disposition:a:3 none -c:a:4 copy -map 0:9 -metadata:s:a:4 language=eng -disposition:a:4 none -f mp4 -threads auto -y /Storage/Movies/Star Wars Episode II - Attack of the Clones (2002)/S
tar Wars Episode II - Attack Of The Clones [2002] [tt0121765] [1080p].mp4">
....
....
Codec AVOption tune (Tune the encoding params (cf. x264 --fullhelp)) specified for input file #0 (/Storage/Movies/Star Wars Episode II - Attack of the Clones (2002)/Star Wars Episode II - Attack Of The Clones [2002] [tt0121765] [1080p].mkv) is not a decoding option.
```

From the error log, I copied edited the same command, move -i to the start of the command and wrap the path to files with "" only then the command started to run.

`/usr/bin/ffmpeg -i "/Storage/Movies/Star Wars Episode II - Attack of the Clones (2002)/Star Wars Episode II - Attack Of The Clones [2002] [tt0121765] [1080p].mkv" -tune zerolatency -preset  veryfast -x264opts  cabac=1:8x8dct=1:bframes=0:b-adapt=2:subme=0:me_range=4:rc_lookahead=10:me=tesa:no_chroma_me:partitions=none:vbv-maxrate=17500:vbv-bufsize=17500:ref=2 -vcodec libx264 -map 0:0 -crf 24 -level 4.0 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -ac:a:0 6 -b:a:0 896k -metadata:s:a:0 language=eng -c:a:1 libfdk_aac -map 0:2 -disposition:a:1 none -ac:a:1 6 -b:a:1 896k -metadata:s:a:1 language=eng -c:a:2 copy -map 0:3 -metadata:s:a:2 language=eng -disposition:a:2 none -c:a:3 copy -map 0:8 -metadata:s:a:3 language=eng -disposition:a:3 none -c:a:4 copy -map 0:9 -metadata:s:a:4 language=eng -disposition:a:4 none -f mp4 -threads auto -y "/Storage/Movies/Star Wars Episode II - Attack of the Clones (2002)/Star Wars Episode II - Attack Of The Clones [2002] [tt0121765] [1080p].mp4"`



This is my autoProcess.ini

```
[Radarr]
ssl = False
host = localhost
apikey = 
port = 7878
web_root = 

[MP4]
audio-copy-original = False
ffprobe = /usr/bin/ffprobe
subtitle-codec = mov_text, srt
post-process = False
fullpathguess = True
pix-fmt = 
audio-filter = 
relocate_moov = True
h264-max-level = 4.0
ios-move-last = False
output_extension = mp4
video-max-width = 1920
embed-subs = True
audio-language = eng,tur,kor,rus,jap,chi
output_format = mp4
move_to = 
output_directory = 
postopts =   
ios-first-track-only = False
max-audio-channels = 
subtitle-default-language = 
tag-language = en
video-bitrate =
ffmpeg = /usr/bin/ffmpeg
convert-mp4 = True
ios-audio = False
audio-channel-bitrate = 128
permissions = 644
aac_adtstoasc = False
download-artwork = poster
audio-codec = libfdk_aac, aac, ac3, mp3
preopts = -tune,zerolatency,-preset,veryfast,-x264opts,cabac=1:8x8dct=1:bframes=0:b-adapt=2:subme=0:me_range=4:rc_lookahead=10:me=tesa:no_chroma_me:partitions=none:vbv-maxrate=17500:vbv-bufsize=17500:ref=2
video-crf = 24
audio-default-language = eng
ios-audio-filter = 
copy_to = 
download-subs = false
delete_original = False
subtitle-encoding = UTF-8
threads = auto
tagfile = True
embed-only-internal-subs = True
sub-providers = addic7ed, podnapisi, thesubdb, opensubtitles
use-qsv-decoder-with-encoder = True
subtitle-language = eng,tur,rus
video-codec = h264, x264

[Sonarr]
ssl = False
host = localhost
apikey = 
port = 8989
web_root = 

[Deluge]
username = 
sonarr-label = sonarr
output_directory = 
host = localhost
radarr-label = radarr
password = 
port = 58846
convert = True
sickbeard-label = sickbeard
remove = false
couchpotato-label = couchpotato
bypass-label = bypass
sickrage-label = sickrage

[uTorrent]
username = 
action_after = removedata
sonarr-label = sonarr
output_directory = 
host = http://localhost:8080/
radarr-label = radarr
webui = False
password = 
convert = True
sickbeard-label = sickbeard
couchpotato-label = couchpotato
action_before = stop
bypass-label = bypass
sickrage-label = sickrage

[CouchPotato]
username = REDACTED
delay = 65
host = localhost
apikey = REDACTED
web_root = 
delete_failed = False
ssl = True
password = REDACTED
port = 5050
method = renamer

[SickBeard]
username = REDACTED
password = REDACTED
ssl = True
host = localhost
web_root = 
api_key = REDACTED
port = 8081

[SABNZBD]
convert = True
sickrage-category = sickrage
radarr-category = radarr
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
username = REDACTED
password = REDACTED
ssl = True
host = localhost
web_root = 
api_key = REDACTED
port = 8081

[Plex]
token = REDACTED
host = localhost
port = 32400
refresh = true
```

**Comment by keldian** [comment]
Just put them in post-ops. No need for a 'hack'.
