### ISSUE TITLE
Feature Request: Temp processing folder

### ISSUE THREAD

**Issue by galenjdove** [mdhiggins/sickbeard_mp4_automator#795]
Create an option in manual.py to have a temporary folder to move original file to for processing, after completed move back to original location. Useful for network drives or cloud mounted storage (my use case).  Currently if the file is not copied locally first processing will error out with I/O errors as it cannot read fast enough.

My use case: 200+TB of media in Google Drive that needs to be processed. Storage mounted and fused /w local directory so any new writes are done to local drive. Cannot copy media back in mass before processing, needs to be done during runtime.

Possible workflow:
Copy /mnt/fuse/tv/show/ep1.mkv (on gdrive) to /tmp - process file - move processed file to /mnt/fuse/tv/show/ep1.mkv (which will be located on local disc now) - File uploaded back to gdrive (done with seperate process)

I have a similar setup to others utilizing rclone/plexdrive for streaming from cloud storage. Seems like it would be easy to add to workflow?

If my usecase can be accomplished already let me know, after playing around with the current capabilities I didn't see a way to accomplish what I needed.

**Comment by distinguished-git** [comment]
I got this to work by modifying `manual.py`, it works well with Google Drive File Stream.

Add the following code after line [234](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/manual.py#L234), where `filepath` is defined in the `walkDir` function. Maintain the same indentation level.

            global settings
            xdirname, xfilename = os.path.split(filepath)
            settings.moveto = os.path.normpath(xdirname)

**Comment by haxcop** [comment]
of you can just use the output folder when prostprocessing and then decide the move folder <which can be the original> to show the finished work. 

```
output_directory = H:/temp/output
copy_to = 
move_to = H:/final/move
