### ISSUE TITLE
Multiple Categories in Bypass

### ISSUE THREAD

**Issue by jonfinley** [mdhiggins/sickbeard_mp4_automator#799]
IS it possible to label multiple categories in the Bypass filter, I'm trying to post process things that are not managed via sonarr/radarr.

Thanks!

**Comment by RandomNinjaAtk** [comment]
You can create a post processing script and use the manual function to encode as much as you want. 

Here is an example script I wrote and use to run the Sabnzbd Deobfuscation script and then process the files with mp4_automator manually:

https://github.com/RandomNinjaAtk/Scripts/blob/master/sabnzbd/mp4-video-processing.bash

**Comment by mdhiggins** [comment]
0af3b8bf6f1614f834aa6c0dad69e7357b5d13a7

All the categories for the various downloaders are now checked based on startswith instead of equals so they are effectively prefixes allowing multiple labels
