### ISSUE TITLE
How To Use Intel Quick Sync With Hevc H.265

### ISSUE THREAD

**Issue by trentmsteel** [mdhiggins/sickbeard_mp4_automator#802]
I have a IGPU that supports hardware encoding and decoding of HEVC / 265, and was wondering how to enable encoding of videos to 265. 

Here is my current setup in the "autoProcess.ini" file
"video-codec = h264qsv,h264,x264,x265,h.265,hevc,HEVC", I have tried "h265qsv" but that results in "unknown codec error"

**Comment by Collisionc** [comment]
Currently the script does not support qsv h265, only qsv h264.

**Comment by trentmsteel** [comment]
understood, thanks.

**Comment by Collisionc** [comment]
Added qsv support for encoding/decoding h265 - https://github.com/mdhiggins/sickbeard_mp4_automator/commit/057249d2f96d6a52efb6698aa2518b63e417f0d5

video-codec= hevcqsv    should trigger it

**Comment by kientran** [comment]
Having trouble getting hevc_qsv working with my ffmpeg.  Is this library proprietary to Intel (with a $4k license??)

**Comment by Collisionc** [comment]
I think it's due to this - https://github.com/mdhiggins/sickbeard_mp4_automator/pull/822 - I just copy/pasted qsv_h264 code thinking it would work the same.

**Comment by RandomNinjaAtk** [comment]
Does this help you? https://github.com/mdhiggins/sickbeard_mp4_automator/issues/939
