### ISSUE TITLE
Unable to get deluge to work after a system crash

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#803]
Ok I had this problem in the past that I solved but this fix don't seem to work anymore :(

Basically MY main SSD failed so I had to do a full system reinstall, but for the life of me I ca not get deluge to run the script everything else and I mean everything else is working as intended but deluge doesn't, I used python 3 instead of 2.7 could this be the problem?

**Comment by morpheus2n2** [comment]
Ok it seems its python 3 as I downgraded to 2.7 reinstalled all the "pip" bits re-downloaded a video and it worked first time

**Comment by mdhiggins** [comment]
Python 3 should work. What errors were you getting?

**Comment by morpheus2n2** [comment]
This is all I get, the CMD windows pops up for like 5 seconds before vanishing.
Where as when I went back to Pyhon 2.7 the windows pops up and stays until its finished.
> 2017-10-12 18:24:57 - delugePostProcess - INFO - Deluge post processing started.
> 2017-10-12 18:24:57 - readSettings - INFO - C:\Users\morph\AppData\Local\Programs\Python\Python36-32\python.exe
> 2017-10-12 18:24:58 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?
> 2017-10-12 18:25:50 - delugePostProcess - INFO - Deluge post processing started.
> 2017-10-12 18:25:50 - readSettings - INFO - C:\Users\morph\AppData\Local\Programs\Python\Python36-32\python.exe
> 2017-10-12 18:25:50 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?
> 2017-10-12 18:55:49 - delugePostProcess - INFO - Deluge post processing started.
> 2017-10-12 18:55:49 - readSettings - INFO - C:\Users\morph\AppData\Local\Programs\Python\Python36-32\python.exe
> 2017-10-12 18:55:50 - delugePostProcess - INFO - Successfully connected to Deluge

**Comment by mdhiggins** [comment]
Looks like your command line parameters aren't getting sent to python
`delugePostProcess - ERROR - Not enough command line parameters present`
I would check and make sure you have python 3 appropriately added to your system path so that it can receive command line parameters

https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t

**Comment by morpheus2n2** [comment]
Sorry for the long delay, I have fixed this issue now, I uninstalled and removed all traces of Python from my System and started over and its now working fine, All I can think is there was a conflict or missing file somewhere they throw a spanner in the works.
