### ISSUE TITLE
NZBGetPostProcess.py - Calling wrong Directory

### ISSUE THREAD

**Issue by jadik** [mdhiggins/sickbeard_mp4_automator#804]
The NZBGetPostProcess.py script doesn't work as provided. The following four substitutions must be made if you want to direct the output anywhere except inside the scripts folder:

On line 62: 
REPLACE: NZBPO_MP4_FOLDER
WITH THIS: NZBPO_OUTPUT_DIR

On lines 63, 64, 65:
REPLACE: MP4folder
WITH THIS: output_dir

The resulting block of code from line 58 to line 68 should look like this:

`output_dir = None`
`if 'NZBPO_OUTPUT_DIR' in os.environ:`
`    output_dir = os.environ['NZBPO_OUTPUT_DIR'].strip()`
`    if len(output_dir) > 0:`
`        output_dir = os.environ['NZBPO_OUTPUT_DIR'].strip()`
`        output_dir = output_dir.replace('"', '')`
`        output_dir = output_dir.replace("'", "")`
`        output_dir = output_dir.replace("\\", "/")`
`        if not(output_dir.endswith("/")):`
`            output_dir += "/"`
`        #DEBUG#print Overriding output directory`

Please update as appropriate... and thanks for your efforts!

**Comment by mdhiggins** [comment]
Good catch! Fixed this, thanks
