### ISSUE TITLE
Different File Systems

### ISSUE THREAD

**Issue by tropicaljoe** [mdhiggins/sickbeard_mp4_automator#806]
I currently have Deluge running on a windows box ( running your script ) all works fine if I have sonarr on the same box. I would like to move sonarr to a linux seperate box, but is there a way to translate the path the script gives to linux. Example, the script gives D:\Deluge\complete_sonarr\tvshow as the path and the linux box cannot translate this to to linux file system. can there be some type of remote mappings so that sonarr would look in the correct spot. I have already tried the built in sonarr remote mappings, but since the script just tells sonarr where to look, this does not help. Much appreciated if there is another suggestion or way to do this out there

**Comment by mdhiggins** [comment]
Best bet is to just use Sonarr's complete download handling in that scenario

**Comment by zybeon** [comment]
Could you share the folder and use the network share location instead. \\win_PC_name\share\Deluge\complete_sonarr\tvshow
