### ISSUE TITLE
Questions on using the Python script suite

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#807]
1) In SABPostProcess.py, I see this line:

categories = [settings.SAB['sb'], settings.SAB['cp'], settings.SAB['sonarr'], settings.SAB['radarr'], settings.SAB['sr'], settings.SAB['bypass']]

Why aren't the other categories the same as the default ones listed in autoconfigure.ini? They should be this way:

sb -> sickbeard
cp -> couchpotato
sr -> sickrage

2) I also checked the code in postSonarr.py and why does it still has and MkvtoMp4 block? Does it also convert the file? I don't see an if statement there that will check if it is already an mp4 or not but then I also don't see it converting the file during the whole process. It just imports it properly. Can you explain this? Sorry, I'm more of a Powershell guy and I can only use context clues to interpret the code flow/syntax in Python.

3) Will the SABPostProcess.py script work with Python 3.x even though it specifically says [here](https://sabnzbd.org/wiki/faq#toc4) that it won't?

**Comment by kevindd992002** [comment]
Did you also notice that setting the "threads" parameter to Auto makes it use only 1 thread? I have 8 threads in my system so I was expecting it to use all of them but why use only 1 thread?

**Comment by kevindd992002** [comment]
@mdhiggins 

Would you care to help me out here, please?

**Comment by kevindd992002** [comment]
@mdhiggins 

Would you care to help me out here, please?

**Comment by kevindd992002** [comment]
https://github.com/mdhiggins

**Comment by mdhiggins** [comment]
Nagging and spamming are not polite. I'm one person with a very busy real job and I just do this as a hobby. My schedule does not allow quick support, sometimes in the order of months especially for involved questions.

1. The categories are the same, that's just how the variables are stored, they reference whatever you specify in your autoProcess.ini
2. All post downloader scripts, be it Sonarr, SAB, etc support conversion. The check for conversion happens as part of the MkvtoMp4 functionality. Conversion is disabled in autoProcess.ini or in NZBGet options
3. It will work, the script is written to be backwards compatible with both versions of python, so when SAB executes its stuff it uses python2 but it won't cause issue

**Comment by mdhiggins** [comment]
2. It just allows people to have the option to convert before the file is passed back to the media managers, its useful if you're using a NAS or something and want the conversion to take place on a more powerful computer before its passed along. Best bet is to just set 'convert = False' in your options if this is not something you want. The file will still be sent back, the script will just skip the conversion step and send the unprocessed file back.

3. SAB runs its own internal build of python and that's how it handles executing python scripts. It does not care about your PATH variables and will do python 2 regardless because that's what its internal environment runs on

**Comment by kevindd992002** [comment]
2. I see. So if you set convert = False, SABPostProcess.py will still pass it back to Sonarr and postSonarr.py will be the one converting the file, correct? 

What if, let's say the situation is the same as your example (I want the conversion to take place on a powerful computer where SAB is and I set convert = True), the file gets converted by SAB, passes it back to Sonarr, and then Sonarr does a redundant conversion. So how then did we achieve the goal of converting it only once with a powerful computer then? Sorry if I didn't get that right, I'm confused with the flow.

As I understand it, the flow is:

Sonarr -> SAB -> SAB Post Process -> Sonarr -> Sonarr Post Process -> Notify Plex

3. Gotcha

**Comment by mdhiggins** [comment]
`convert-mp4` in autoProcess.ini also needs to be set to false, that's probably the step you aren't considering. Otherwise your flow is exactly correct. With that set to false, it will see its already in the right format during SonarrPostProcess and only do the tagging portion

**Comment by kevindd992002** [comment]
Aha! So if all these software (downloader and media managers) and storage are all in one PC, which of the two is the most efficient:

1) convert=True and convert-mp4=False

Downloader converts the file -> passes it to media manager -> media manager sees it as mp4, tags it but does no conversion -> media manager notifies Plex

2) convert=False and convert-mp4=True

Downloader does no conversion -> passes it to media manager -> media manager tags and converts it (whether it is an mp4 or any other file format) -> media manager notifies Plex

* I would say option 2 is the winner so that even if the downloaded file is an mp4, it will still get converted according to the settings you specify in autoprocess.ini. What do you think?

**Comment by mdhiggins** [comment]
I use option 1, almost no files I download are in the mp4 format so it doesn't apply to me, and I'm on a single machine setup
If it does happen to be an mp4 it will still get tagged and optimized just not converted via FFMPEG. Works best for my needs.

**Comment by kevindd992002** [comment]
But I then lose the capability of having an AAC (stereo) codec being added and tagged as default in the media file if ever the source file is already an mp4, correct?

If I go with option 2, are there any disadvantages or whatsoever?

**Comment by mdhiggins** [comment]
Only downside if you're using the iOS-audio option and you reprocess any of these mp4s in the future is that you'll get duplicate audio tracks, so be sure if you want to retag something that you turn off convert-mp4 before doing so

**Comment by kevindd992002** [comment]
That's want thing that I don't understand. I recently re-processed a lot of mp4 files with iOS-audio set to True. And when I checked the files with MediaInfo, I only see one AAC track in the files. Any ideas?

**Comment by mdhiggins** [comment]
Entirely depends on the source file. If they were only stereo audio to begin with that is the expected and desired behavior

**Comment by kevindd992002** [comment]
But I have a couple of movie files that originally have non-AAC tracks like DTS to begin with. Why didn't they experience the undesirable effect of having multiple stereo tracks?

**Comment by kevindd992002** [comment]
@mdhiggins 

Michael, I'm wondering if you can continue helping me on this with your spare time?
