### ISSUE TITLE
Converting video bitrate far to low

### ISSUE THREAD

**Issue by trentmsteel** [mdhiggins/sickbeard_mp4_automator#809]
I am experiencing an issue where after converting a video the bitrate is far to low for the video resolution, resulting in pixelation during fast motion. For example a (1080p 9200Kbps) video will be (2400Kbps) or lower after conversion is complete.  Here are my current settings in "autoProcess.ini" file. Any idea this happens?

>[MP4]
ffmpeg = C:\Python27\sickbeard_mp4_automator\ffmpeg.exe
ffprobe = C:\Python27\sickbeard_mp4_automator\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264qsv
video-bitrate = 11500
video-crf = 21
video-max-width = 1920
h264-max-level = 4.2
use-qsv-decoder-with-encoder = False
enable_dxva2_gpu_decode = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 6
audio-codec = libfdk_aac,E-AC-3,AAC,A_EAC3,AC-3
audio-language = 
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = -movflags,+faststart,-maxrate,10000k,-bufsize,30000k
preopts = 
embed-only-internal-subs = False
>

**Comment by mdhiggins** [comment]
Can you provide the FFProbe info of your source video file with the -show_streams flag

**Comment by trentmsteel** [comment]
I think Figured out what was causing the issue.

When setting the "video-codec =" configuration, I only set it to "h264qsv", for some reason if this was the only setting it would cause the videos to be process in such a way that the resulting file would have a bitrate that was far too low for the resolution. 

But when I set "video-codec =" to " h264qsv,h264qsv,h264,h.264,x264" the resulting video bitrate is high enough that it eliminates artifacts from the video. Not sure why it works, but it does.

**Comment by Collisionc** [comment]
video-crf = 21 
overrides video-bitrate, and setting crf at 21 would result in some pixelation in high-motion scenes.

The only reason that adding codecs makes it look better is because it enables copying the stream. 

since no video has a codec named 'h264qsv', it will always re-encode the video.  Adding h264 to the list means that it will no longer re-encode a video unless the bitrate is above 11500

**Comment by trentmsteel** [comment]
> video-crf = 21
> overrides video-bitrate, and setting crf at 21 would result in some pixelation in high-motion scenes.
> 
> The only reason that adding codecs makes it look better is because it enables copying the stream.
> 
> since no video has a codec named 'h264qsv', it will always re-encode the video. Adding h264 to the list means that it will no longer re-encode a video unless the bitrate is above 11500

Would lowering crf to (18) solve the issues with some videos being converted to a far too low video bitrate? I notice that it only seems to happen with bluray rips.

**Comment by Collisionc** [comment]
Yeah, 18 should make it look significantly better. If it's still outputting a 2 megabit video stream after, let me know, there might be something that needs to be specifically adjusted for qsv.

**Comment by mdhiggins** [comment]
Yeah everything @Collisionc is saying is correct

You added codecs to the approved list so your stream was being copied (not a bad thing) instead of transcoding

Lowering the CRF is a good solution to improve quality when a non-copy approved stream is detected
