### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by dr99** [mdhiggins/sickbeard_mp4_automator#81]
I am getting this error when running the script manually or through sickbeard.  When I roll back to the version right before the sub downloading was added I get no errors.

 Traceback (most recent call last):
  File "C:\apps\sickbeard_mp4_automator\sabToSickBeardwithConverter.py", line 7, in <module>
    from mkvtomp4 import MkvtoMp4
  File "C:\apps\sickbeard_mp4_automator\mkvtomp4.py", line 10, in <module>
    from babelfish import Language
  File "C:\apps\sickbeard_mp4_automator\babelfish__init__.py", line 13, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "C:\apps\sickbeard_mp4_automator\babelfish\converters__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ImportError: No module named pkg_resources

**Comment by RRTUKADIYA** [comment]
**ImportError: No module named pkg_resources:** the solution is to reinstall python pip using the following  Command are under.

**Step: 1** Login in root user.

    sudo su root
**Step: 2** Uninstall python-pip package if existing.

    apt-get purge -y python-pip
**Step: 3** Download files using wget command(File download in `pwd` )

    wget https://bootstrap.pypa.io/get-pip.py
**Step: 4** Run python file.

    python ./get-pip.py
**Step: 5** Finaly exicute installation  command.  

    apt-get install python-pip

**Note:** User must be root.
