### ISSUE TITLE
Multiple Sonarr labels

### ISSUE THREAD

**Issue by tropicaljoe** [mdhiggins/sickbeard_mp4_automator#811]
Any way to have multiple labels for sonarr ( or couchpotato ), I have two docker instances running and want to use a single deluge  instance running the script

**Comment by RandomNinjaAtk** [comment]
Your better off having the script running in both sonarr instances, I don't think there is any planned support for what your asking.

**Comment by mdhiggins** [comment]
0af3b8bf6f1614f834aa6c0dad69e7357b5d13a7

All the categories for the various downloaders are now checked based on startswith instead of equals so they are effectively prefixes allowing multiple labels
