### ISSUE TITLE
Removing subtitle formatting

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#814]
Is it possible for the automator to remove any font formatting on external subtitles?

**Comment by mdhiggins** [comment]
Not that I'm aware of, I'm sure there are outside programs that can that might be able to be integrated into the 'extra scripts' functionality to scrub the formatting

**Comment by Smalfinn** [comment]
I'm using Sonarr/Radarr with Deluge and SABnzbd. How do I get sickbeard_mp4_automatator to execute a script after converting but before passing back to sonarr/radarr?
