### ISSUE TITLE
Request: work w/ Plex DVR

### ISSUE THREAD

**Issue by shpankey** [mdhiggins/sickbeard_mp4_automator#825]
I'd like the ability to run the script at a specific time, on a folder. For example, I have Plex DVR recording and storing all of the files in a specific directory called "T:\DVR Recording\"

Inside this folder is where Plex puts the recordings (OTA). The come out as .ts files w/ MPEG2VIDEO video codecs and AC3 audio codecs and some kind of subtitle file inside. I'd like to automatically run this script on the folder (ignoring .mp4 files) at like 2am and convert everything to mp4's with h264 and AC3 original audio and AAC 2 channel audio.

I can do it myself manually each night, but is there a way I can automate this?

**Comment by mdhiggins** [comment]
You can set up a scheduled task in Windows to run the script every night on whatever directory using manual.py
