### ISSUE TITLE
Request: Provide a more specific name to /tmp/poster-tmdb.jpg

### ISSUE THREAD

**Issue by kmr2319** [mdhiggins/sickbeard_mp4_automator#827]
Running on Ubuntu 17.10.

Sometimes I might have manual encodes going as my currently logged in user and then automated encodes going from radarr/sonarr as a different user.

On very rare occasions, user A can't overwrite /tmp/poster-tmdb.jpg because user B created it.

I normally don't have problems with permissions due to radarr/sonarr permission options and the setgid bit in my media directory (user A & B are in the same group).

Might be better to use /tmp/poster-[tmdbid].jpg where [tmdbid] is the numerical value for the movie in question.

**Comment by mdhiggins** [comment]
Just pushed an update that includes some unique naming for TV and movie posters
