### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'video'

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#83]
After updating last night I'm getting this error, and my file is deleted :(

```
Video codec detected: h264
Audio stream detected: ac3 eng [Stream 1]
Creating dual audio channels for iOS compatability for this stream
External subtitle file detected, language eng
Importing How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE.eng.srt subtitle stream
E:\Downloads\complete\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE.m4v created
E:\Downloads\complete\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE.mkv deleted
E:\Downloads\complete\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE\How.I.Met.Your.Mother.S09E18.720p.HDTV.x264-REMARKABLE.eng.srtdeleted
C:\SickBeard\autoProcessTV\sickbeard_mp4_automator\babelfish\converters\__init__.py:6: UserWarning: Module babelfish was already imported from C:\SickBeard\autoProcessTV\sickbeard_mp4_automator\babelfish\__init__.pyc, but c:\python27\lib\site-packages\babelfish-0.5.1-py2.7.egg is being added to sys.path
  from pkg_resources import iter_entry_points, EntryPoint
Traceback (most recent call last):
  File "C:\SickBeard\autoProcessTV\sickbeard_mp4_automator\sabToSickBeardwithConverter.py", line 18, in <module>
    converter.process(inputfile)
  File "C:\SickBeard\autoProcessTV\sickbeard_mp4_automator\mkvtomp4.py", line 130, in process
    dim = self.getDimensions(outputfile)
  File "C:\SickBeard\autoProcessTV\sickbeard_mp4_automator\mkvtomp4.py", line 161, in getDimensions
    return { 'y': info.video.video_height,
AttributeError: 'NoneType' object has no attribute 'video'
```

autoprocess.ini

```
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = 0
api_key = 1a622302f657d8ae18735c30ddd74477

[MP4]
ffmpeg = C:/ffmpeg/bin/ffmpeg.exe
ffprobe = C:/ffmpeg/bin/ffprobe.exe
output_directory = 
copy_to = 
move_to = E:/Downloads/complete/processed
output_extension = m4v
output_format = mp4
delete_original = True
relocate_moov = True
audio-codec = ac3
ios-audio = True
audio-language = eng
audio-default-language = eng
subtitle-language = eng
subtitle-default-language = eng
fullpathguess = True
convert-mp4 = False
tagfile = True
download-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
video-codec = h264, x264

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = 0
apikey = 
delay = 65
method = renamer
delete_failed = 0
```

**Comment by TimDowker** [comment]
I also have this issue but when I try to manually run the script using manual.py

Has a solution been found?

I've tried stating the full path to python on the command like but it does the same thing.

I'm trying to run it manually on a Synology NAS

**Comment by mdhiggins** [comment]
Which error are you getting?

**Comment by TimDowker** [comment]
Here is an excerpt from the screen

Processing file /volume1/video/TV Shows/American Dad/Season 01/American.Dad.S01E21.SD.TV-SICKBEARD.mp4
Matched TV episode as American Dad (TVDB ID:73141) S01E21
Failed to connect to TVDB, trying again in 20 seconds
Could not find episode 21
Failed to connect to TVDB, trying again in 20 seconds
Could not find episode 21
Failed to connect to TVDB, trying again in 20 seconds
Could not find episode 21
Processing TV episode
An unexpected error occurred, processing of this file has failed
'NoneType' object has no attribute 'video'


Is there a log file somewhere I can check?  Perhaps a command line switch I can pass to it so one is generated?

Thansk

**Comment by TimDowker** [comment]
Ok, so I've had another chance to play with the script and this is the error I'm getting now.

I've deleted the original copy of the script I had a git cloned a copy from today.  On;y change I made was cp autoProcess.ini.sample to autoProcess.ini and set the correct paths for ffmpeg and ffprobe

this is now the error I get when I try to manually convert a single movie

./manual.py -i /volume1/video/Movies/Look\ Who\'s\ Talking\ Too/Look\ Who\'s\ Talking\ Too\ \(1990\).avi -a
Audio bitrate was invalid, defaulting to 256 per channel
32
Matched movie title as: Look Who's Talking Too 1990-12-14
Processing Look Who's Talking Too
Traceback (most recent call last):
  File "./manual.py", line 298, in <module>
    main()
  File "./manual.py", line 289, in main
    processFile(path, tagdata)
  File "./manual.py", line 188, in processFile
    output = converter.process(inputfile, True)
  File "/volume1/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 109, in process
    options = self.generateOptions(inputfile, original=original)
  File "/volume1/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 190, in generateOptions
    print "Video codec detected: " + info.video.codec
AttributeError: 'NoneType' object has no attribute 'video'


Any ideas?

**Comment by mdhiggins** [comment]
This sounds like the script is having a hard time reading the video file you're trying to convert. Try a different file and see if it gives you the same error

**Comment by TimDowker** [comment]
I've double checked the permissions on the that file and every sub folder between it and root and all are marked 777.  I'm also logged in as root so permissions shouldn't be an issue.

**Comment by mdhiggins** [comment]
Not so much that its a permissions issue but that maybe the file is corrupt and ffprobe isn't able to properly read the streams

**Comment by TimDowker** [comment]
Tried copying another file into the same directory as the script and recevied the same error

DiskStation> ./manual.py -i Heavenly.Sword.2014.HDRip.XviD.AC3-EVO.avi -a
Audio bitrate was invalid, defaulting to 256 per channel
32
Matched movie title as: Heavenly Sword 2014-06-30
Processing Heavenly Sword
Traceback (most recent call last):
  File "./manual.py", line 298, in <module>
    main()
  File "./manual.py", line 289, in main
    processFile(path, tagdata)
  File "./manual.py", line 188, in processFile
    output = converter.process(inputfile, True)
  File "/volume1/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 109, in process
    options = self.generateOptions(inputfile, original=original)
  File "/volume1/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 190, in generateOptions
    print "Video codec detected: " + info.video.codec
AttributeError: 'NoneType' object has no attribute 'video'

Thank you for helping me with this.

**Comment by TimDowker** [comment]
LL of the script directory

DiskStation> ll
drwxr-xr-x   11 root     root          4096 Jan 23 12:41 .
drwxr-xr-x    3 root     root          4096 Jan 23 08:32 ..
drwxr-xr-x    8 root     root          4096 Jan 23 08:32 .git
-rw-r--r--    1 root     root           483 Jan 23 08:32 .gitattributes
-rw-r--r--    1 root     root          2749 Jan 23 08:32 .gitignore
-rw-r--r--    1 root     root          1108 Jan 23 08:32 CPProcess.py
-rwxr-xr-x    1 root     root     1421633536 Jan 23 12:41 Heavenly.Sword.2014.HDRip.XviD.AC3-EVO.avi
-rw-r--r--    1 root     root         17202 Jan 23 08:32 README.md
-rw-r--r--    1 root     root             0 Jan 23 08:32 __init__.py
-rw-r--r--    1 root     root           954 Jan 23 08:33 autoProcess.ini
-rw-r--r--    1 root     root           944 Jan 23 08:32 autoProcess.ini.sample
-rw-r--r--    1 root     root          4054 Jan 23 08:32 autoProcessMovie.py
-rw-r--r--    1 root     root          3026 Jan 23 08:32 autoProcessTV.py
drwxr-xr-x    4 root     root          4096 Jan 23 08:33 babelfish
drwxr-xr-x    2 root     root          4096 Jan 23 08:33 converter
-rw-r--r--    1 root     root           345 Jan 23 08:32 extensions.py
-rw-r--r--    1 root     root           615 Jan 23 08:33 extensions.pyc
drwxr-xr-x    4 root     root          4096 Jan 23 08:33 guessit
-rw-r--r--    1 root     root          4566 Jan 23 08:32 installffmpeg.sh
-rwxr-xr-x    1 root     root         11779 Jan 23 08:32 manual.py
-rwxr-xr-x    1 root     root         22379 Jan 23 08:32 mkvtomp4.py
-rw-r--r--    1 root     root         13078 Jan 23 08:33 mkvtomp4.pyc
drwxr-xr-x    2 root     root          4096 Jan 23 08:33 mutagen
-rw-r--r--    1 root     root          3204 Jan 23 08:32 nzbDroneFactory.py
-rwxr-xr-x    1 root     root          1665 Jan 23 08:32 nzbToCouchPotatoMP4.py
-rw-r--r--    1 root     root          1666 Jan 23 08:32 nzbToNzbDroneMP4.py
-rwxr-xr-x    1 root     root          1433 Jan 23 08:32 postConversion.py
drwxr-xr-x    2 root     root          4096 Jan 23 08:33 qtfaststart
-rw-r--r--    1 root     root         15926 Jan 23 08:32 readSettings.py
-rw-r--r--    1 root     root          9429 Jan 23 08:33 readSettings.pyc
-rw-r--r--    1 root     root           890 Jan 23 08:32 sabToSickBeardwithConverter.py
drwxr-xr-x    4 root     root          4096 Jan 23 08:32 setup
drwxr-xr-x    3 root     root          4096 Jan 23 08:33 tmdb_api
-rw-r--r--    1 root     root          7284 Jan 23 08:32 tmdb_mp4.py
-rw-r--r--    1 root     root          6695 Jan 23 08:33 tmdb_mp4.pyc
drwxr-xr-x    3 root     root          4096 Jan 23 08:33 tvdb_api
-rwxr-xr-x    1 root     root         10256 Jan 23 08:32 tvdb_mp4.py
-rw-r--r--    1 root     root          9828 Jan 23 08:33 tvdb_mp4.pyc
-rw-r--r--    1 root     root          3650 Jan 23 08:32 uTorrentToSickBeardwithConverter.py

**Comment by TimDowker** [comment]
and here's my autoProcess.ini file

DiskStation> cat autoProcess.ini
[SickBeard]
host=localhost
port=8081
username=
password=
web_root=
ssl=0
api_key=

[NzbDrone]
host=localhost
port=8082
web_root=
ssl=0
api_key=

[MP4]
ffmpeg=/usr/bin/ffmpeg
ffprobe=/usr/bin/ffprobe
output_directory=
copy_to=
move_to=
output_extension=mp4
output_format=mp4
delete_original=True
relocate_moov=True
audio-codec=ac3
video-codec=h264,x264
video-bitrate=
ios-audio=True
max-audio-channels=
audio-language=
audio-default-language=
audio-channel-bitrate=
subtitle-language=
subtitle-default-language=
fullpathguess=True
convert-mp4=False
tagfile=True
tag-language=en
download-artwork=True
download-subs=False
embed-subs=True
sub-providers=addic7ed,podnapisi,thesubdb,opensubtitles

[CouchPotato]
host = localhost
port = 5050
username =
password =
web_root =
ssl = 0
apikey =
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
label=
webui=False
action_before=stop
action_after=removedata
host=http://localhost:8080/
username=
password=

**Comment by mdhiggins** [comment]
I'm wondering if perhaps there's an issue with your build of ffprobe that's causing it to fail or at least output in a manner that's different than what the script is expecting? Not sure if you built it from source but just to see what's going on maybe tried grabbing one of the precompiled binaries and see if it provides a fix

**Comment by TimDowker** [comment]
I figured it out - it was a problem with my ffmpeg and ffprobe files.  Thank you for your help.

Is there a place (like a forum maybe) where I can go to discuss/troubleshoot other issues and questions?

**Comment by mdhiggins** [comment]
There's a thread on the Sickbeard forums regarding this script, but opening discussion through github, at least if you're trying to ask me questions, is the best way to do it.
