### ISSUE TITLE
Issues with uTorrent and Sonarr not processing completed conversions

### ISSUE THREAD

**Issue by HeroXx** [mdhiggins/sickbeard_mp4_automator#830]
I'm having an issue with uTorrent post processing using the uTorrent processor. I'm already using the NZBGet processor and it is working perfectly with Sonarr, the files are converted and Sonarr scans and renames the file, perfect.

uTorrent on the other hand, is not working, it currently renames the file and by the looks of the logs, sends it to Sonarr which then doesn't rename or move the file.

Any help would be appreciated:

```
2017-12-10 19:01:07 - uTorrentPostProcess - INFO - Passing F:\Torrents\Complete\Ozark.S01E05.720p.WEBRip.x264-STRiFE[ettv]\us-convert directory to Sonarr.
2017-12-10 19:01:07 - autoprocess.sonarr - INFO - Sonarr notifier started.
2017-12-10 19:01:07 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'F:\Torrents\Complete\Ozark.S01E05.720p.WEBRip.x264-STRiFE[ettv]\us-convert'.
2017-12-10 19:01:07 - autoprocess.sonarr - INFO - Sonarr response: queued.
2017-12-10 19:01:07 - uTorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "C:\Tools\ConverterNew\uTorrentPostProcess.py", line 201, in <module>
    os.rmdir(delete_dir)
WindowsError: [Error 145] The directory is not empty: 'F:\\Torrents\\Complete\\Ozark.S01E05.720p.WEBRip.x264-STRiFE[ettv]\\us-convert'
```

**Comment by HeroXx** [comment]
And with output directory set to mp4conv in Radarr:

`17-12-11 12:33:09.0|Debug|Parser|Parsing string 'mp4conv'
17-12-11 12:33:09.0|Debug|Parser|Unable to parse mp4conv`

**Comment by leafsfan525** [comment]
I am having the exact same issue as well. Haven't been able to figure it out yet

**Comment by mdhiggins** [comment]
I'm not quite clear where the mp4conv variable is coming from, where is that being set?

**Comment by leafsfan525** [comment]
I believe it's being set in the output_directory attribute. If you leave it blank, you get the error from the first post. If you try to set any other output_directory, a folder path with "mp4conv" being an example, thats when you get the other error.

**Comment by leafsfan525** [comment]
I'm not sure if it's related or not but I find that Sonarr has trouble processing, renaming, and matching the file when the torrent folder has a website prefix. For example, this one below (debug logs from Sonarr):

17-12-12 15:14:29.0|Debug|Parser|Parsing string 'www.SceneTime.com - Jeopardy.2017.12.11.720p.HDTV.x264-NTb-convert'
17-12-12 15:14:29.0|Debug|Parser|Episode Parsed. www SceneTime com - Jeopardy - 2017-12-11 
17-12-12 15:14:29.0|Debug|Parser|Language parsed: English
17-12-12 15:14:29.0|Debug|QualityParser|Trying to parse quality for www.SceneTime.com1 - Jeopardy.2017.12.11.720p.HDTV.x264-NTb-convert
17-12-12 15:14:29.0|Debug|Parser|Quality parsed: HDTV-720p v1
17-12-12 15:14:29.0|Debug|Parser|Release Group parsed: convert
17-12-12 15:14:29.0|Debug|DownloadedEpisodesImportService|Unknown Series www.SceneTime.com1 - Jeopardy.2017.12.11.720p.HDTV.x264-NTb-convert

Is there a way to rename the folder in the uTorrent post process file to remove this? Or is it possible to use Filebot to rename the folder first and then pass it to Sonarr?
