### ISSUE TITLE
Enquiry: IS this script still in active development? 

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#831]
Just wondering if this script is still in active development or is there a newer better version coming?

**Comment by mdhiggins** [comment]
Script is stable at the moment. Not actively working on any new features and all current features are working and functional

**Comment by morpheus2n2** [comment]
Ok cool must say its been working a charm recently even with the .wmv you told me how to add :)

**Comment by mdhiggins** [comment]
Glad to hear it!
