### ISSUE TITLE
Random subtitle added to every movie

### ISSUE THREAD

**Issue by chaosefphect** [mdhiggins/sickbeard_mp4_automator#832]
So I just found this amazing script and over all I think its great except for 1 issue. I don't know why but every movie I try to run this against I have an issue with subtitles. I keep getting this 1 random subtitle that only contains a single time stamp  00.00.00.045. I have removed and downloaded the scrip, changed the config file every possible way I can come up with. I have reloaded the OS about 5 times in a VM and yet the issue is always there. I have left the autoProcess.ini with the most basic settings and still no joy. Any help is greatly appreciated and if there is any further info needed I will provide it. Please note I am a bit of a novice.

Ubuntu 16.04
[autoProcess.ini](https://pastebin.com/5c4bEXM9)
Python 2.7.12

My goal would be have the movies as mp4s with no integrated subtitles and only a single srt external file.

**Comment by chaosefphect** [comment]
So just did another clean install of ubuntu 16.04 and did not even install "subliminal<2". Still getting the random subtitle in the media.

How I did the install

sudo apt update
sudo apt install python-pip git ffmpeg -y 

sudo -H pip install --upgrade pip
sudo -H pip install requests
sudo -H pip install requests[security] 
sudo -H pip install requests-cache
sudo -H pip install babelfish 
sudo -H pip install "guessit<2" 
sudo -H pip install "subliminal<2" ***skipped this
sudo -H pip install stevedore==1.19.1 
sudo -H pip install python-dateutil 
sudo -H pip install qtfaststart 

cd ~
git clone https://github.com/mdhiggins/sickbeard_mp4_automator/
cd sickbeard_mp4_automator
cp autoProcess.ini.sample autoProcess.ini

**Comment by mdhiggins** [comment]
Should be resolved with latest subliminal update
