### ISSUE TITLE
Support for IFDB possible?

### ISSUE THREAD

**Issue by bonyboy** [mdhiggins/sickbeard_mp4_automator#833]
I know you can use IMDB/TMDB ID with manual.py, but was wondering if it was possible to support [IFDB](https://ifdb.fanedit.org/) id's?

[Github repo](https://github.com/tomfin46/IFDB.bundle)

**Comment by mdhiggins** [comment]
No immediate plans to add this as there is no parity between the tmdb outside source ID's cached and this site
