### ISSUE TITLE
Radarr and Sonarr not processing anything.

### ISSUE THREAD

**Issue by CarbonNeuron** [mdhiggins/sickbeard_mp4_automator#835]
Huh, this is kinda odd.
Radarr and sonarr now act as if the script does not even tell them to scan the new directory. I can post logs if someone would tell me how. I look in the logs on sonarr and it doesn't say anything about a refresh.
The script log shows the file being processed, the notifier starting, telling it to scan the directory and sonarr responding with "queued" but then it never does anything after that, sonarr never imports the file  nor does radarr.

**Comment by shpankey** [comment]
Same thing w/ Radarr from me. Just now happened, out of the blue. Was working perfectly.

Not sure if it was the SABnzbd update or something else. Totally lost right now.

**Comment by shpankey** [comment]
trying sabnzbd 2.3.1 again to see if it works again, to see if that was the problem. will report back

**Comment by shpankey** [comment]
found the issue, somehow radarr updated and changed my download client category to movies, instead of radarr. now working again w/ 2.3.2
