### ISSUE TITLE
Tags not adding to m4v file

### ISSUE THREAD

**Issue by davidpearce** [mdhiggins/sickbeard_mp4_automator#838]
When I use the NZBGetPostProcess.py to convert files after download, tags arent being added to the m4v file.

If i use the manual.py script with -a, the tags are added properly.

In my autoProcess.ini file:
tagfile = True
tag-language = en

The only message in the info.log is:
NZBGetPostProcess - ERROR - File Processing Failed

[info.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1583688/info.log)

**Comment by mdhiggins** [comment]
This is intended. The downloaded scripts do not tag. Tagging is done as the final step of the media managers such as Sonarr or Couch Potato.
