### ISSUE TITLE
h264qsv codec, results in error: Unrecognized option 'look_ahead'.

### ISSUE THREAD

**Issue by izeen** [mdhiggins/sickbeard_mp4_automator#840]
Hello!

Recently aquired a NUC, model: NUC5i5RYH

It has a 5th gen i5-5250u with intel hd graphics 6000. 

Trying to get it to work with QSV, so i set h264qsv in the video-codec options. When i try to do a manual run on sommething thats not already h264, i get the following error:

Unrecognized option 'look_ahead'.
Error splitting the argument list: Option not found

Does the processor not support quick sync or am i missing some setting to get this to work? 

OS: Ubuntu 16.04 LTS
FFMPEG version: 3.4.1

I have the following settings in autoProcess:
`[MP4]
tag-language = en
download-artwork = false
download-subs = True
delete_original = True
use-qsv-decoder-with-encoder = True
audio-language = eng,swe
output_format = mp4
ffprobe = /usr/bin/ffprobe
move_to =
output_directory =
post-process = False
threads =
ios-first-track-only = False
max-audio-channels =
subtitle-codec = mov_text
audio-codec = ac3
audio-copy-original = True
pix-fmt =
subtitle-default-language = eng
tagfile = True
video-bitrate =
audio-filter =
relocate_moov = True
embed-subs = True
ffmpeg = /usr/bin/ffmpeg
h264-max-level =
fullpathguess = False
sub-providers = addic7ed, podnapisi, thesubdb, opensubtitles
convert-mp4 = False
subtitle-encoding =
subtitle-language = eng,swe
audio-default-language = eng
output_extension = mp4
ios-audio = True
video-max-width =
audio-channel-bitrate = 256
permissions = 777
aac_adtstoasc = False
ios-audio-filter =
copy_to =
video-codec = h264qsv, h264, x264
preopts =
postopts =
enable_dxva2_gpu_decode = False
ios-move-last = False
video-crf =
embed-only-internal-subs = False
use-hevc-qsv-decoder = False
`

**Comment by mdhiggins** [comment]
What version/build of FFMPEG are you using? Did you compile yourself? What OS?

From: izeen
Sent: Thursday, December 28, 2017 3:54 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] h264qsv codec, results in error:Unrecognized option 'look_ahead'. (#840)

Hello!
Recently aquired a NUC, model: NUC5i5RYH
It has a 5th gen i5-5250u with intel hd graphics 6000.
Trying to get it to work with QSV, so i set h264qsv in the video-codec options. When i try to do a manual run on sommething thats not already h264, i get the following error:
Unrecognized option 'look_ahead'.
Error splitting the argument list: Option not found
Does the processor not support quick sync or am i missing some setting to get this to work?
OS: Ubuntu 16.04 LTS
FFMPEG version: 3.4.1
I have the following settings in autoProcess:
[MP4] tag-language = en download-artwork = false download-subs = True delete_original = True use-qsv-decoder-with-encoder = True audio-language = eng,swe output_format = mp4 ffprobe = /usr/bin/ffprobe move_to = output_directory = post-process = False threads = ios-first-track-only = False max-audio-channels = subtitle-codec = mov_text audio-codec = ac3 audio-copy-original = True pix-fmt = subtitle-default-language = eng tagfile = True video-bitrate = audio-filter = relocate_moov = True embed-subs = True ffmpeg = /usr/bin/ffmpeg h264-max-level = fullpathguess = False sub-providers = addic7ed, podnapisi, thesubdb, opensubtitles convert-mp4 = False subtitle-encoding = subtitle-language = eng,swe audio-default-language = eng output_extension = mp4 ios-audio = True video-max-width = audio-channel-bitrate = 256 permissions = 777 aac_adtstoasc = False ios-audio-filter = copy_to = video-codec = h264qsv, h264, x264 preopts = postopts = enable_dxva2_gpu_decode = False ios-move-last = False video-crf = embed-only-internal-subs = False use-hevc-qsv-decoder = False

**Comment by izeen** [comment]
Did not compile my self, 

Im on ubuntu server 16.04  LTS,
Tried with ffmpeg from the official ubuntu PPAs and now im using version: ffmpeg version 3.4.1

``

**Comment by mdhiggins** [comment]
I would try downloading the binary from here instead of using the repo one and see if that fixes your error

https://www.ffmpeg.org/download.html

**Comment by Collisionc** [comment]
potentially related to this pull request - https://github.com/mdhiggins/sickbeard_mp4_automator/pull/822

**Comment by mdhiggins** [comment]
Merged that

**Comment by izeen** [comment]
I removed ffmpeg and compiled from this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu followed all the steps.

Pulled the changes you commited yest, still same error:

Unrecognized option 'look_ahead'.
Error splitting the argument list: Option not found


If i look at #822  its regarding h265 and the changes to look_ahead in avcodecs.py was for that specific codec, i tried to remove the same block of code for h264_qsv but then i just get: Unknown encoder 'h264_qsv'

**Comment by Collisionc** [comment]
Ah, ok. I didn't realize this, but on linux you have to use VAAPI - https://trac.ffmpeg.org/wiki/Hardware/VAAPI 

This pull request might be worth looking into: https://github.com/mdhiggins/sickbeard_mp4_automator/pull/690

**Comment by izeen** [comment]
Aaaaah, so i should use this then in the video-codec options: h264vaapi ?

**Comment by Collisionc** [comment]
It will not currently work without that pull request. I haven't tested the pull request as I don't have a qsv capable computer.

**Comment by izeen** [comment]
Did the changes manually mentioned in #690 
Works nicely, watching with intel_gpu_top and can see it chugging along. Great stuff!

**Comment by mdhiggins** [comment]
Pushed an updated with the improved VAAPI support
Level should be automatically multiplied by 10 when VAAPI is chosen
Give it a shot and let me know if its working

**Comment by izeen** [comment]
its working great! can see the CPU offloaded and GPU getting to work. Thanks alot for your quick commits :)
