### ISSUE TITLE
uTorrentPostProcess.py - never cleans up/deletes torrents & files

### ISSUE THREAD

**Issue by rjblake** [mdhiggins/sickbeard_mp4_automator#843]
Was curious as to the running. I noticed my system filling up with torrents that keep seeding/uploading irrespective of my uTorrent settings. Do these have to be removed manually, or does the script not remove once required ratios/time have been met? Also, noticed in the setup documentations the script syntax is "uTorrentPostProcess.py %L %T %D %K %F %I %N"; yet there seem to only be the following options per uTorrent:

%F - Name of downloaded file (for single file torrents)
%D - Directory where files are saved
%N - Title of torrent
%S - State of torrent
%L - Label
%T - Tracker
%M - Status message string (same as status column)
%I - hex encoded info-hash

Am I missing something in my understanding?

**Comment by staghorndrive** [comment]
I know this is an old issue; but SABNZDB is deleting the completed files but utorrent is not. 
Wonder if there is a fix here?

**Comment by mdhiggins** [comment]
Script does not clean up the files but media managers like radarr/sonarr should be able to after the files are handed back
