### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'video'

### ISSUE THREAD

**Issue by ShiroiKuma** [mdhiggins/sickbeard_mp4_automator#844]
I did a fresh install of sickbeard_mp4_automator/deluge/couchpotato on a new box and downloaded a single movie to convert for Plex. However, I'm getting the following error:

Is this related to #829 where in I could potentially alter lines 409/410 to resolve this in some cases, or is this a new edge case?

```
2018-01-06 22:40:42 - delugePostProcess - ERROR - Error converting file /mnt/plex1/deluge/Completed/couchpotato/MovieName (1999) [1080p]/MovieName.1999.1080p.BRrip.x264.YIFY.mp4.
Traceback (most recent call last):
  File "/opt/sickbeard_mp4_automator/delugePostProcess.py", line 84, in <module>
    output = converter.process(inputfile)
  File "/opt/sickbeard_mp4_automator/mkvtomp4.py", line 229, in process
    dim = self.getDimensions(outputfile)
  File "/opt/sickbeard_mp4_automator/mkvtomp4.py", line 269, in getDimensions
    self.log.debug("Height: %s" % info.video.video_height)
AttributeError: 'NoneType' object has no attribute 'video'
```

If I try running the file through manual.py I get the following output (with or without altering lines 409/410 of ffmpeg.py)

```
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
32bit Python.
Matched movie title as: MovieName 1999-10-30
Proceed using guessed identification from filename?
# [y/n]: y
Processing MovieName
Tagging file: /mnt/plex1/movies/MovieName (1999).mp4.
Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.
2018-01-06 23:00:39 - qtfaststart - ERROR - This file appears to already be setup for streaming!
QT FastStart did not run - perhaps moov atom was at the start already.
```

**Comment by mdhiggins** [comment]
This is more often than not caused by a corrupt video file
Are you experiencing this with every file?

**Comment by ShiroiKuma** [comment]
I receive "AttributeError: 'NoneType' object has no attribute 'video'" in my logs for every video from every source when using postProcessing scripts. But these work if I use manual.py as root. Which is weird as I have deluge/sonarr/plex/couchpotato all running as the same user/group to remove permissions as a possible problem.

The 2nd error regarding "QT FastStart did not run - perhaps moov atom was at the start already." does not happen every file, and could possible be a corrupt movie file. My main concern though is the first error which happens on every single file. Any idea's on this one?

**Comment by ShiroiKuma** [comment]
I left this for a while but came back to it. Turns out my deluge user wasn't part of the video/audio groups in Ubuntu. Adding the user to those groups fixes my problem.
