### ISSUE TITLE
Deluge Not Running delugePostProccess.py

### ISSUE THREAD

**Issue by rpoovey** [mdhiggins/sickbeard_mp4_automator#850]
I have been running your converter scripts for a while, and no matter what I do I cannot get the Deluge execute to run after a torrent finishes. I have dug through all the past issues on here and none of the solutions provided a fix. 

Autoprocess.ini is as follows:
```
[Deluge]
host = 127.0.0.1
username = convert
convert = True
password = M2Nv4q7MqjFkryokXPXoNZHbacpyZizT
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory =
remove = false
radarr-label = radarr
```
Sonarr applies the label of sonarr to all Deluge torrents. Nothing in the logs shows up for Deluge unless I trigger it manually. Script is executable. 

Deluge execute is set as 
"Torrent Complete" Path:/home/MYUSERNAME/sickbeard_mp4_automator/delugePostProcess.py

Attempted to enable debug logging in logging.ini, but there is no section for Deluge and I dont want to add lines that might mess up the other logging. 

I did find that Deluged has two config paths. One located in:
/var/lib/deluge/.config/deluge (auth file is contained in there and I have added the credentials)
and
/home/MYUSERNAME/.config/deluge (auth file is contained here as well, and credentials added. I am not sure which one is main config file. I thought they might be symlinked. But they were not)

After some searching issues about Deluge not executing scripts. I followed the support article from them to verify is a script will execute before adding it to the daemon. Deluge execute command:
```
./delugePostProcess.py "TorrentID" "Torrent Name" "Torrent Path"
```
This completes without error. 

There seem to be a ton of people that have problems getting Deluge running correctly with the script and I haven't seen an actual solution yet. Hoping that you can help me out. 

Please let me know if I need to provide anymore information. 

Thanks for all your hard work. This script bundle has saved me so much time.

**Comment by mdhiggins** [comment]
I'm not sure how to further debug this and many people have the issue, but I have been unable to reproduce it
delugepostprocess will create log entries in info.log so if you're not seeing anything from that then deluge is failing to open the script. If that's the issue than I would try and head over to their forums and see if anyone on the deluge end of things can provide assistance

If you are seeing some logging info from delugepostprocess please share that

**Comment by morpheus2n2** [comment]
Think the problem will be the location of the script, I have mine on the root of the C drive as having it under my profile kept giving me problems. I believe this is due to security as windows ends to lock down a users folder from Apps and others.

Also its worth just quickly running through the read me steps again as sometimes python will download a bad file or a step was over looked by mistake.

**Comment by rpoovey** [comment]
@morpheus2n2 This is on an Ubuntu Linux server. So I dont think its a problem with it being nested in a profile. I have verified that all the permissions are correct and I am able to call the deluge execute command via terminal with no problem. 

I saw you previous post about the `pip install gevent` being further down in the deluge section and I verified that I did not miss that step when setting everything up. Also, according to `python -v` I am running 2.7 yet deluge still fails.

**Comment by rpoovey** [comment]
So after giving up for months on this. I decided to try and fix this problem again. 

The only way I could get delugePostProcess.py to work is by editing deluged/deluge-web to run as root. While this is very insecure. It does work. Previously, my systemd launch script was set to run as a "deluge" user. No logs were even tracked for failure. I even tried to run it as my server user with no luck either. If you have any suggestions on permissions levels for the "deluge" user that most people set up to run the service, please let me know. 

If anyone comes here looking for a solution, verify that it will run when deluged/deluge-web is ran as root. I don't recommend keeping it like this though.

**Comment by tscibilia** [comment]
@rpoovey I was running into a similar issue but I decided to create a user called ffmpeg to own all the sickbeard_mp4_automation files... 
`adduser --disabled-login ffmpeg`
...and added my deluge user to the ffmpeg group.
`usermod -aG deluge ffmpeg`

then fixed some permissions for group read and execute...
`chmod -R 755 "/the entire sb_mp4_auto_dir"`
`chmod 775 "/sb_mp4_auto_dir/info.log"`
