### ISSUE TITLE
Alter Plex to refresh specific directories

### ISSUE THREAD

**Issue by andrewkhunn** [mdhiggins/sickbeard_mp4_automator#856]
Thanks to the recent updates to `postRadarr.py` and `postSonarr.py`, sickbeard_mp4_automator is functioning flawlessly for imports now. The last remaining issue for me is because I am using [plexdrive](https://github.com/dweidenfeld/plexdrive) to mount my media on Google Drive.

If possible, it would be great if the default Plex refresh behavior could be altered to refresh only the new directory instead of the whole library on each import. This would help to reduce the number of API calls made to Google Drive on Plex's behalf. I know [plex_autoscan](https://github.com/l3uddz/plex_autoscan) has implemented this by simply modifying the command line switches passed to Plex Media Scanner and I would imagine a similar implementation may be possible for `autoprocess/plex.py`.

Let me know if you have any questions or need help testing! Thanks!

**Comment by andrewkhunn** [comment]
Hey @mdhiggins, is this request clear enough? Need help testing?

I'd really like to see this change implemented and I know your free time is valuable. Thanks for your work on this free project!

**Comment by andrewkhunn** [comment]
So, I think I have made some progress on this by cribbing together some code from the `sample.py` post-processing script and figuring out that plex_autoscan can accept a manual invocation by `curl`-ing a webhook. @mdhiggins, I really just need a bit of help getting my horrible amalgamation of a script functioning (did I mention I don't know what I am doing?).

Thanks for any assistance!

```
import os
import json
import requests
import sys

if __name__ == "__main__":
    files = json.loads(os.environ.get('MH_FILES'))
    for filename in files:
        try:
            filepath = filename
            if not filepath:
                print("The filelist provided by sickbeard_mp4_automator was empty...")
                exit(1)
            payload = {'eventType': 'Manual', 'filepath': filepath}
            requests.post('PLEX_AUTOSCAN_URL', data=payload)
        except Exception as ex:
            print("There was an exception while processing the scan request from sickbeard_mp4_automator: ", ex)
        exit(0)
```

**Comment by mdhiggins** [comment]
Hm how about if you post the request format needed to scan a specific directory I can try and take care of the rest

**Comment by andrewkhunn** [comment]
Great!

plex_autoscan is [expecting a POST in the following URL schema](https://github.com/l3uddz/plex_autoscan#misc):

`curl -d "eventType=Manual&filepath=/mnt/unionfs/Media/Movies/Shut In (2016)/Shut In (2016) - Bluray-1080p.x264.DTS-GECKOS.mkv" http://ipaddress:3468/0c1fa3c9867e48b1bb3aa055cb86`

All that really needs to be done is for sickbeard_mp4_automator to return a filepath (although I also believe that plex_autoscan is intelligent enough to deal with a full path to the file that has been converted). Which is what I was trying to accomplish via my horrible code above.

Thanks so much for assisting!

**Comment by mdhiggins** [comment]
Hm I didn't realize it was using an entirely separate program (Plex Autoscan) to do this, I'll have to look through their code and see how they trigger directory based scans

**Comment by mdhiggins** [comment]
Well there whole system is very complex and not something that can quickly be reproduced

So, assuming you have setup and installed plex autoscan, this should work
```
#!/usr/bin/python
import os
import json
import requests

def main():
	print("Plex Autoscan Post Script")
	url = "http://localhost:3689/apikey"

	files = json.loads(os.environ.get('MH_FILES'))
	if not (files):
        print("Error - Did not find environment variables.")
        return

	for filename in files:
		dirname = os.path.dirname(filename)
		payload = {'eventType': 'Manual'
				   'filepath': dirname}
		try:
			requests.post(url, json=payload)
		except Exception as e:
			print("Error - Request failed")
			print(e)

if __name__ == "__main__":
    main()
```

You'll need to edit the `url` variable to correspond to your setup but give that a shot

**Comment by andrewkhunn** [comment]
I don't believe the script as written is working correctly. Tried processing two files, neither of which triggered an update in Plex. I know plex_autoscan is working, because I can pass it a manual request via curl that completes fine. All that shows up in the sickbeard_mp4_automator output when converting a file is:

`2018-07-19 20:13:47 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py'.`

Is there a way to invoke a conversion with more debug output so I can see exectly what's happening during post_process?

Seriously, thanks for the hand with this.

**Comment by andrewkhunn** [comment]
Alright, I figured out how to turn on debugging via `stdout` and I believe I got everthing working. I ran into a few issues:

1. Forgot to `chmod` the script `775`
2. There were some indentation issues copy/pasting from here
3. Lines 17 & 18 above were malformed

The fixed script is attached below for others:

```
#!/usr/bin/python
import os
import json
import requests

def main():
  print("plex_autoscan Post-processing Script")
  url = "http://localhost:3689/apikey"

  files = json.loads(os.environ.get('MH_FILES'))
  if not (files):
    print("Error - Did not find environment variables.")
    return

  for filename in files:
    dirname = os.path.dirname(filename)
    payload = {'eventType': 'Manual', 'filepath': dirname}
    try:
      requests.post(url, json=payload)
    except Exception as e:
      print("Error - Request failed")
      print(e)

if __name__ == "__main__":
  main()
```

Thanks again so much for your help assembling this thing!
