### ISSUE TITLE
manual.py cannot import guessit

### ISSUE THREAD

**Issue by rogowar** [mdhiggins/sickbeard_mp4_automator#860]
I have installed the automator on my mac.  I went through the install directions, but when running manual.py with -a flag, I get:

./manual.py -i /Volumes/Download/complete/ -a
Traceback (most recent call last):
  File "./manual.py", line 5, in <module>
    import guessit
ImportError: No module named guessit

guessit is in my pip list:

rdavies3@RogOmatiC:~/git/sickbeard_mp4_automator>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
babelfish (0.5.5)
beautifulsoup4 (4.6.0)
certifi (2018.1.18)
cffi (1.11.4)
chardet (3.0.4)
click (6.7)
cryptography (2.1.4)
dogpile.cache (0.6.4)
enum34 (1.1.6)
enzyme (0.4.1)
guessit (1.0.3)
idna (2.6)
ipaddress (1.0.19)
pbr (3.1.1)
pip (9.0.1)
pycparser (2.18)
pyOpenSSL (17.5.0)
pysrt (1.1.1)
python-dateutil (2.6.1)
qtfaststart (1.8)
requests (2.18.4)
requests-cache (0.4.13)
setuptools (38.5.1)
six (1.11.0)
stevedore (1.19.1)
style (1.1.0)
subliminal (1.1.1)
update (0.0.1)
urllib3 (1.22)
wheel (0.30.0)

**Comment by mdhiggins** [comment]
If it’s installed then it’s usually due to another instance of python separate from the library pip is listing

Does the python executable that comes up at the top of manual.py show the one that corresponds to the environment where you installed guessit?

**Comment by rogowar** [comment]
That was it.  I used homebrew to install all the pip dependencies, and they were called pip2 and python2.  Did a bit or renaming and symbolic linking and I'm back on track.  Thanks.
