### ISSUE TITLE
Deluge Post Process Does Not See Extracted Files

### ISSUE THREAD

**Issue by darkendvoid** [mdhiggins/sickbeard_mp4_automator#861]
When using the deluge post process with the built in extraction plugin or your own delugePostProcess.bat wrapper to extract downloaded torrents delugePostProcess does not see the extracted file.

Deluge only reports back the files that are contained in the torrent so the post process never sees the extracted contents.

This can be fixed by querying the directory instead of puling that information from Deluge.
```python
files = []
log.debug("List of files in torrent:")
#for contents in torrent_files:
#   files.append(contents['path'])
#   log.info(contents['path'])
osdir = str(sys.argv[3] + "\\" + sys.argv[2] )   
for dirname, dirnames, filenames in os.walk(osdir):   
	for filename in filenames:
		files.append(sys.argv[2] + "/" + filename)
```

Example of my wrapper
```batch
set torrentid=%1
set torrentname=%2
set torrentpath=%3
@echo Extracting:  %torrentname% %torrentpath% %torrentid% >> C:\Extractor\Log.txt
@echo CD Z:\Torrents\%torrentname%\
Z:
CD Z:\Torrents\%torrentname%\
@echo unrar e Z:\Torrents\%torrentname%\*.rar  >> C:\Extractor\Log.txt
unrar e Z:\Torrents\%torrentname%\*.rar >> C:\Extractor\Log.txt
@echo 7z e Z:\Torrents\%torrentname%\*.zip  >> C:\Extractor\Log.txt
7z e Z:\Torrents\%torrentname%\*.zip >> C:\Extractor\Log.txt

@echo C:\mp4auto\delugePostProcess.bat %torrentid% %torrentname% %torrentpath%
C:\mp4auto\delugePostProcess.bat %torrentid% %torrentname% %torrentpath%
```
`

**Comment by mdhiggins** [comment]
I would think this would fail if there was a situation where it was a single file and not a custom sub directory

Do you have issues with this?

**Comment by darkendvoid** [comment]
It mostly works, you are correct in single file torrents it will fail as it passes the directory as the filename+\ which fails. Hence why I didn't submit it as a pull request, just a quick example.

**Comment by justinglock40** [comment]
https://github.com/levic92/LCExtractor

This is helpful in your situation. Disable deluge post process and let Radarr and Sonarr handle. Has a cleanup script too for cleaning deleting remnants

**Comment by mdhiggins** [comment]
Yeah this is the preferred solution. Zipped torrents are quite rare but if it’s something you’re encountering it’s best to let Sonarr or Radarr handle things
