### ISSUE TITLE
.original files

### ISSUE THREAD

**Issue by trentmsteel** [mdhiggins/sickbeard_mp4_automator#862]
I currently have sickbeard_mp4_automator working with Raddar and Sonarr on a local windows machine. My issue is that I notice that the script, is moving the ".original" to my mounted remote cloud drive as well as the final ".mp4" file. This leaves me in the end with both a ".original" and ".mp4" on my drive double the bandwidth usage and double the Api calls to the could drive. 

Is there any way to only transfer / upload the ".mp4" ? Thanks

**Comment by mdhiggins** [comment]
The only way a .original file gets created is when the inputfile and the outputfile have the exact same name and extension and are located in the same directory

The .original file should be deleted once the conversion is done however if the appropriate settings to delete original are enabled in your autoProcess.ini
