### ISSUE TITLE
MKV

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#863]
Possible to add mkv as an output option for people who just want an automated way to get the audio processed? and since mp4 can't accepth things like truehd?

**Comment by mrzoops** [comment]
Exactly this. I only need audio converted to aac. Leave everything else as is. Is this possible?

**Comment by mdhiggins** [comment]
9403600c983243736a8a5351d7fa61086da96a66
Update added that allows conversion to mkv
Tagging won't work and will be disabled as the tagging is MP4 specific
