### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#866]
I tried to use the threads flag in autoProcess.ini to reduce CPU consumption during conversion,  It is set to auto by default.  I normally see it consuming 60+ threads and CPU consumption is at 99% for the duration of the conversion process.

I changed the threads flag in the MP4 section to 24.  It does seem that it is using less threads and CPU consumption has dropped slightly, but threads for the ffmpeg process is still in the 50's.  I would have expected it to max out at 24.  Is this how this flag is supposed to work?

**Comment by samcro1967** [comment]
I looked through of the script files.  I see "threads='auto," in mkvtomp4.py.  I would have expected to see something like "from autoprocess import threads" to pull in the value set for threads from autoprocess.ini.

I manually changed the value in mkvtomp4.py from auto to 32, but that did not seem to cap the number of threads ffmpeg uses either.

![image](https://user-images.githubusercontent.com/2319445/38423846-aef882c0-3974-11e8-9802-e693a99d2b02.png)

**Comment by mdhiggins** [comment]
Flag just passes the threads parameter to FFMPEG, any lack of adherence to that is an issue with FFMPEG

**Comment by JySzE** [comment]
You are using it incorrectly, the "threads"  flag in ffmpeg limits use of cpu cores physical or logical. 

If on windows 10:

Open task manager and go to the performance tab then click on cpu on the left hand side. 

Now it should give you some information. Look for "cores" and "logical processors" 

If not on windows 10:

If you don't have windows 10, download "cpu-z" and at the bottom right hand corner it will say how many cores or "logical processors (threads)" there is on your system. 

set your max threads in the autoprocess.ini  to whatever your logical processors(threads in cpu-z) is listed as in task manager or cpu-z If you want 100% cpu usage. Anything less than your listed logical processors amount will reduce the cpu usage of ffmpeg.

**Comment by samcro1967** [comment]
Thank you mdhiggins  and JySzE.  I  checked the documentation on the ffmpeg web site after mdhiggins stated the script is just passing through variables to ffmpeg.  Their documentation I think is dated.  They still state "threads", but as you stated, it is clearly linked to cores IMHO.  Guessing the documentation is many years old when CPUs were only capable of 1 thread.  Changing the value to 2 dropped my CPU utilization from 100% to ~40% on a 4 vCPU machine.  Changing it to 3 caused CPU utilization to jump to ~70%.  Anything 4 or higher causes it to go to 100%.  Leaving it at auto causes weird numbers of threads from 60 to 100 that all result in 100% CPOU utilization.  I agree threads really translates to cores or vCPUs.  Appreciate the responses!!!!
