### ISSUE TITLE
Question about Plex DVR

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#867]
I did a search and found to previous posts but there from over a year ago.
I have only just setup Plex with a HDhomrun, and seen as I use this script for everything else I was wondering what I would need to do to have this work on the DVR as well, it seems to have an option to run a post-processing script before adding media to the library.

So would pointing it to the Manual.py work at all?

**Comment by mdhiggins** [comment]
It might, not sujre what format the Plex stuff is saved in but you could probably point it to manual.py with the automatic flags enabled
