### ISSUE TITLE
Disable extraction of embedded subtitles

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#868]
Here's my autoprocess.ini contents: https://pastebin.com/aHsiRCym

How do I make sure that embedded subtitles stay embedded? And that I don't want this script to download any external subs (I have Plex do that for me)?

**Comment by keldian** [comment]
You need 
`subtitle-codec = mov_text`
`download-subs = False`
`embed-subs = True`

`embed-only-internal-subs = True` will keep external subs from being embedded, and if you have embedded subs in other languages you want to keep, you'll need to add those languages in `subtitle-language = eng`

**Comment by kevindd992002** [comment]
Thanks! I still don't have the "embed-only-internal-subs" parameter as I'm still using 2.2 so I guess I can skip that part and get away with it for now.
