### ISSUE TITLE
Feature Request:  ~~  Normalize audio options in autoprocess.ini ?

### ISSUE THREAD

**Issue by weezzelboy** [mdhiggins/sickbeard_mp4_automator#871]
A req for normalize audio
How can I normalize audio using ffmpeg?
Is there way you could include this to the autoprocess.ini. it would be great to boost, lower or normalize some Audio in the files.
the site below shows how to do it manually 1 file at a time, but it would be great to have settings or options incorporated into the autoprocess.ini file
good site link
 https://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg

**Comment by mdhiggins** [comment]
#219
Duplicate and very complicated issue
