### ISSUE TITLE
Encoding .M2TS - "not in the correct format"

### ISSUE THREAD

**Issue by kocane** [mdhiggins/sickbeard_mp4_automator#873]
I have a bunch of files from some bluray ISOs that I wanna re-encode. The files are already H264 and with two audio tracks, DTS and AC3. I've used this awesome script to re-encode a bunch of my X264/H264 TV shows automagically but they're usually MP4. These ones are in M2TS.

If I pass python /opt/mp4automator/manual.py -i "Matador_S02E03.m2ts" it simply throws me, in the log:
```
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
File Matador_S02E03.m2ts is not in the correct format
```
The info.log file doesn't contain anymore information.

I've tried with setting the audiocodec to AC3, disabling MOOV relocation, tried without my specific postopts settings, but nothing helps.

This is my config:
```
[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = False
video-codec = h264
video-bitrate =
video-crf = 18
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = copy
audio-language =
audio-default-language =
audio-channel-bitrate =
audio-filter =
audio-copy-original = True
subtitle-codec = srt
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts = -c:v,libx264,-preset,slow,-tune,film
preopts =
```

Is m2ts simply not supported, or?

**Comment by mdhiggins** [comment]
M2TS hasn’t been tested at all, but theoretically if FFMPEG can unwrap it it should work
If you want to try it out you just have to add m2ts to the extensions.py valid_input_extensions array and give it a shot

From: kocane
Sent: Monday, April 2, 2018 11:21 AM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Encoding .M2TS - "not in thecorrect format" (#873)

I have a bunch of files from some bluray ISOs that I wanna re-encode. The files are already H264 and with two audio tracks, DTS and AC3. I've used this awesome script to re-encode a bunch of my X264/H264 TV shows automagically but they're usually MP4. These ones are in M2TS.
If I pass python /opt/mp4automator/manual.py -i "Matador_S02E03.m2ts" it simply throws me, in the log:
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
File Matador_S02E03.m2ts is not in the correct format
The info.log file doesn't contain anymore information.
I've tried with setting the audiocodec to AC3, disabling MOOV relocation, tried without my specific postopts settings, but nothing helps.
This is my config:
[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = False
video-codec = h264
video-bitrate =
video-crf = 18
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = copy
audio-language =
audio-default-language =
audio-channel-bitrate =
audio-filter =
audio-copy-original = True
subtitle-codec = srt
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts = -c:v,libx264,-preset,slow,-tune,film
preopts =
Is m2ts simply not supported, or?

**Comment by kocane** [comment]
Well that did the trick. Totally missed that file :-P 

Thanks!

**Comment by kocane** [comment]
@mdhiggins - this question might be dumb but how do I go about removing an audio track on all the files I'm processing? I've tried the -map parameters in the postopts but it seems like they get overwritten by the script itself. I've also tried, for testing, to output a 'sample file', something that is only 60secs long or so, so that I can find the best settings for compressing the files, but it seems like it just ignores -ss hh:mm:ss.ms and the following -t parameter.

**Comment by mdhiggins** [comment]
Yeah the MAP parameters are very specific and dynamic you can't override those

What audio track are you trying to remove?

Also how are you putting your options in for preopts and postopts post an example

**Comment by kocane** [comment]
I'm trying to remove the secondary audio track as it's just some commentary of sorts, but isn't tagged with this at all (non of the tracks or subtitles are tagged, apparently this info is lost when copying from bluray discs). As for the -ss and -t, I'll give that a go again, I musta been doing something wrong.
