### ISSUE TITLE
Sonarr/Radarr Rescanning of Series after successful conversion to MP4

### ISSUE THREAD

**Issue by infamouswb** [mdhiggins/sickbeard_mp4_automator#875]
Radarr and Sonarr have API commands to trigger a rescan of the series/folder. Example below for Sonarr:

RescanSeries
Refresh rescan disk for a single series
Parameters
Optional: seriesId (int) - if not set all series will be scanned

It would be great if this MP4 Automator tool can trigger the scan after conversion, vs having to wait to the 12hour mark. The reason is, Sonarr/Radarr is not aware the file changed to MP4 and still thinks there is an MKV present. This messes with cutoff quality and auto deletion of poor quality, if you get a better quality episode before the 12hour scan mark hits. 

Example is that before the next 12hour scan hits you had a 720P file and a 1080P file downloaded. When sonarr tries to delete the 720P it send the command for MKV, because it has not learned it is actually MP4 now. This leads to many duplication of the same movie/episode among many qualities.

I appreciate any help!

**Comment by mdhiggins** [comment]
This was added a few commits ago, are you using the latest version?

5ab51fcf611a3de13ae81ff84d235c3ba53261bd
