### ISSUE TITLE
Map only first stream of each language

### ISSUE THREAD

**Issue by keldian** [mdhiggins/sickbeard_mp4_automator#876]
I have an mkv that looks like this:
- 0:0 x264
- 0:1 ac3 [rus] (Russian track I don't want)
- 0:2 dts [eng]
- 0:3 ac3 [eng] (English commentary track I don't want)

Desired output:
- 0:0 x264 (copy)
- 0:1 aac [eng] (0:2 -> libfdk_aac)

Actual output with my settings:
- 0:0 x264 (copy)
- 0:1 aac [eng] (0:2 -> libfdk_aac)
- 0:2 aac [eng] (0:3 -> libfdk_aac)

Can I make the script never map more than one stream of each language? Alternatively, can I make the script only map DTS streams if available?

ffmpeg = ffmpeg
ffprobe = ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = False
video-codec = h264,x264
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = libfdk_aac
audio-channel-bitrate = 0
audio-language = eng,fra
audio-default-language =
audio-filter =
audio-copy-original = False
subtitle-codec = mov_text
subtitle-language = eng,fra
subtitle-default-language = fra
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = True
embed-only-internal-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts = -vbr,4

**Comment by mdhiggins** [comment]
At present this functionality is not supported but I imagine it could be added, at least the first track of any language portion you're requesting

**Comment by mdhiggins** [comment]
88c7ea4777393c513f2f9121aecfabea3aff5efa
Wasn't too difficult to add
Please give it a try and let me know
