### ISSUE TITLE
Can't run script SABnzbd

### ISSUE THREAD

**Issue by PaceDesigns** [mdhiggins/sickbeard_mp4_automator#877]
I finally got everything setup but can't seem to get SABNZBD to run the script to convert to MP4. Everything else works just fine but this. Right now sonarr/radarr is uploading both the mkv and mp4 when I only want the mp4. Here is the error Exit(-1) Cannot run script /config/scripts/SABPostProcess.py

**Comment by mdhiggins** [comment]
Read up on how to set up post processing scripts in SAB and check your file permissions that is has execute permissions
