### ISSUE TITLE
Audio Bitrates

### ISSUE THREAD

**Issue by Chudz** [mdhiggins/sickbeard_mp4_automator#879]
Is it possible to set the 2.0 AAC track to 160 bitrate and the 5.1 AC3 track to 640bitrate?

**Comment by mdhiggins** [comment]
At present there is only an audio channel bitrate options which determines a per-channel bitrate and is not specific to the iOS track and the other audio tracks

If you set that value to 80 you'll get 160 for 2.0 AAC and 480 for the AC3 track
