### ISSUE TITLE
Cannot tag files bigger than 2gb

### ISSUE THREAD

**Issue by conrelma** [mdhiggins/sickbeard_mp4_automator#88]
I'm using your script to manually tag old movies in mp4 format.  When they are bigger than 2gb the tagger seems to fail every time.  Al the movies smaller than 2gb also fails.

I've converted the same mkvs to mp4 using manual.py to see if it was something I did wrong with my conversion, but the files still fail that are bigger than 2gb.

Is it a setting I need to change or is there a file size limitation to tagging mp4 files?

**Comment by mdhiggins** [comment]
As of commit 8375e799c53cfa9a0d87d62cccf747072875ee97 a workaround for this issue has been found and tagging should work on 32 bit systems regardless of file size
