### ISSUE TITLE
Needs updated to TVDB Api 2

### ISSUE THREAD

**Issue by MrsAngelD** [mdhiggins/sickbeard_mp4_automator#880]
The TVDB has updated to API 2 and because of this tv shows are getting match errors. It sucks because TVDB gave no warning that this was happening, they just sprung the version on everyone. So even sonarr is having issues.

**Comment by mdhiggins** [comment]
Hm that's not ideal, I'll have to look into this, might take some time

**Comment by mdhiggins** [comment]
So everything still appears to be working? Are they officially dropping support for the old API?

**Comment by MrsAngelD** [comment]
For what I've read on their forums that appears to be the goal.

**Comment by swoopsta** [comment]
I'm not sure if this is confirmation of the changes made to the TVDB api noted here [https://api.thetvdb.com/swagger](https://api.thetvdb.com/swagger), but here is the results of running manual.py -nm -a which eventually finishes without tagging the resulting mp4.

`Traceback (most recent call last):
  File "/opt/automator/tvdb_mp4.py", line 41, in __init__
    self.seasondata = self.showdata[self.season]
  File "/opt/automator/tvdb_api/tvdb_api.py", line 117, in __getitem__
    raise tvdb_seasonnotfound("Could not find season %s" % (repr(key)))
tvdb_seasonnotfound: Could not find season 3
Failed to connect to TVDB, trying again in 20 seconds.`

**Comment by mdhiggins** [comment]
That error might have been related to the TVDB API outage which is now resolved
As of this post tagging is working fine

**Comment by swoopsta** [comment]
Looks like DBR has updated his [tvdb_api](https://github.com/dbr/tvdb_api) to version 2. How difficult would it be to merge in his changes?

**Comment by mdhiggins** [comment]
Working on it now, should have an updated release shortly

**Comment by mdhiggins** [comment]
So there are some new limitations and bugs with the latest DBR tvdb_api library

Looks like no poster rating data is actually transmitted so determining the top poster doesn't work
Additional writer/director data isn't gathered either so its a significant step backwards

Gonna post on that github and see if we can get those resolved

v1 is still working at this time though so that's good
