### ISSUE TITLE
Removing all subtitles (internal and external)

### ISSUE THREAD

**Issue by kocane** [mdhiggins/sickbeard_mp4_automator#883]
If I, in the case, just want to use mp4automator to batch proces a bunch of files where my goal is to remove the embedded subtitles (and leave video and audio, metadata etc. be), then what must I do? My config is as looking like below. I also tried with -sn in preopts (and postopts) but it had no effect.

What must I do?
```
[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory =
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = False
video-codec = h264
video-bitrate =
video-crf =
video-max-width =
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec =
audio-language = 
audio-default-language =
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = True
subtitle-codec = mov_text
subtitle-language = nil 
subtitle-default-language = nil
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts =
preopts = 
```

**Comment by mdhiggins** [comment]
Subtitle default Language leave blank
Subtitle language set to nil

**Comment by kocane** [comment]
@mdhiggins right, sorry for not mentioning it but setting nil in both was my first try. Setting nil in subtitle language and leaving default language blank produces the same result. The subtitles are tx3g.

**Comment by mdhiggins** [comment]
If the files are already MP4 files it may not be doing any conversion then, it will just skip over the FFMPEG portion and retag

Are these files already MP4 or M4V files?

**Comment by kocane** [comment]
@mdhiggins right, they're already mp4. I set convert-mp4 to true and added AAC,AC3,DTS to audio-codec. Then it actually processed the file and, judging from the speed, copied the audio and video streams. Very nice!

I don't suppose there's a way to simply always make it copy the audio track?
