### ISSUE TITLE
Just a question about install

### ISSUE THREAD

**Issue by canadabri** [mdhiggins/sickbeard_mp4_automator#886]
Just would like to ask if when configuring Automator, the instructions have setup info for things like Sonarr, CouchPotato, SAB, NZBGet, etc.    I have Sonarr, CP, SAB and NZBGet installed on my computer. DO I setup Automator for *both* the media manager and the downloader, or is this a one or the other type thing?

And if it is one or the other, which is recommended to do the postprocess job?

**Comment by Smalfinn** [comment]
You need both the manager and downloader setup

**Comment by mdhiggins** [comment]
Correct
