### ISSUE TITLE
Running via crontab and updating apps

### ISSUE THREAD

**Issue by pmow** [mdhiggins/sickbeard_mp4_automator#889]
Rather than transcode on download, I'd like to run it overnight.  Plex is generally tolerant of files getting renamed (as mkv to mp4) but sonarr and radarr will think the file is missing.

Is it possible to update a movie (radarr) or TV series (sonarr) when running manual.py?  I'm comfortable writing a script that runs it, but I don't know of a good way to build a queue and it would be far easier to run manual.py -a in the library folder, if that makes sense.

Thanks!

**Comment by RemeJuan** [comment]
On the first bit, if you told sonarr to ignore deleted files it would be happy and pick them back up in a later library scan.

**Comment by pmow** [comment]
That's a good observation.  Unfortunately I use that feature to clean up my movie libraries (to make deleted movies unmonitored).  For sonarr only, I suppose it's probably the same as setting all shows to monitored.

> On the first bit, if you told sonarr to ignore deleted files it would be happy and pick them back up in a later library scan.

**Comment by mdhiggins** [comment]
You could write a wrapper for postSonarr or postRadarr potentially or just write a postProcess script that notifies radarr/sonarr to refresh (you could reference postSonarr/postRadarr for who this refresh is triggered)
