### ISSUE TITLE
Processing more than once?

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#890]
I'm monitoring the nzbget/download directory and the destination directory and see the files unpack and begin to process in nzbget/download, then when complete it moves the file over then the process happens again. Is there something in the config that is triggering this? Please let me know what you need me to attach in order to see...

**Comment by mdhiggins** [comment]
Post your config please

**Comment by hroman73** [comment]
I replaced the api keys with xxx but they are filled out and correct...


[Sonarr]
host = localhost
port = 8989
web_root =
ssl = False
apikey = xxx

[Radarr]
host = localhost
port = 7878
web_root =
ssl = False
apikey = xxx

[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Thumbnail
download-subs = True
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts =
preopts =

[Plex]
host = localhost
port = 32400
refresh = True
token = xxx

[Deluge]
username =
sonarr-label = sonarr
output_directory =
host = localhost
radarr-label = radarr
password =
port = 58846
convert = True
sickbeard-label = sickbeard
remove = false
couchpotato-label = couchpotato
bypass-label = bypass
sickrage-label = sickrage

[uTorrent]
username =
action_after = removedata
sonarr-label = sonarr
output_directory =
host = http://localhost:8080/
radarr-label = radarr
webui = False
password =
convert = True
sickbeard-label = sickbeard
couchpotato-label = couchpotato
action_before = stop
bypass-label = bypass
sickrage-label = sickrage

[CouchPotato]
username =
delay = 65
host = localhost
apikey =
web_root =
delete_failed = False
ssl = False
password =
port = 5050
method = renamer

[SickBeard]
username =
password =
ssl = False
host = localhost
web_root =
api_key =
port = 8081

[SABNZBD]
convert = True
sickrage-category = sickrage
radarr-category = radarr
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory =

[Sickrage]
username =
password =
ssl = False
host = localhost
web_root =
api_key =
port = 8081

**Comment by mdhiggins** [comment]
convert-mp4 = True 

Set that to false

**Comment by hroman73** [comment]
okay...thank you

**Comment by hroman73** [comment]
i usually have that set in case it downloads an mp4 i would still like all the tags to be processed in it anyways. would setting this to false then prevent any downloaded mp4 to skip the tagging process?

**Comment by mdhiggins** [comment]
Tagging will still take place it just won’t process through FFMPEG

**Comment by hroman73** [comment]
awesome! thank you again!
