### ISSUE TITLE
Sonarr giveing errors for Season and Episode Numbers

### ISSUE THREAD

**Issue by BurningDeath** [mdhiggins/sickbeard_mp4_automator#899]
Would any one be able to help me on the below errors, i am unable to find/figure out why this is happening, Straight after pulling a episode to qBittorrent, or to uTorrent

python.exe | TypeError: int() argument must be a string or a number, not 'NoneType' | 5:23pm
python.exe | season = int(os.environ.get('sonarr_episodefile_seasonnumber')) | 5:23pm
python.exe | File "C:\MP4_Automator\postSonarr.py", line 25, in <module> | 5:23pm
python.exe | Traceback (most recent call last): | 5:23pm

**Comment by alazare619** [comment]
In docker i'm facing this same issue

**Comment by alazare619** [comment]
@mdhiggins  I created an issue on the dockerfile as well

**Comment by mdhiggins** [comment]
Shouldn’t be seeing this in docker. This usually comes from the script being executed by something other than sonarr cause it isn’t getting the environment variables
