### ISSUE TITLE
permissions error & sonarr/radarr not completing

### ISSUE THREAD

**Issue by tscibilia** [mdhiggins/sickbeard_mp4_automator#900]
I'm dying to get this to work with sonarr, radarr and deluge (now installed on one VM). 

**Issue:** (Log snippet: https://hastebin.com/meduxajoba.vbs)
1. I get permissions errors when setting file permissions (which is confusing because the file is able to be transcoded and moved perfectly fine). I'm not sure if I should ignore the errors (line 15 and line 29)?
2. I'm not entirely sure the script finishes because it calls on sonarr/radarr but it doesn't seem to log any confirmation/error. 
      * Additionally, sonarr/radarr aren't processing the request sent nor are there any apparent errors in their logs. 
      * I also have post_process enabled and it never seems to make it that far.

**Recreate Issue:**
`Linux torpia 4.4.128-1-pve #1 SMP PVE 4.4.128-111 (Wed, 23 May 2018 14:00:02 +0000) x86_64 x86_64 x86_64 GNU/Linux`
- I'm running a Ubuntu 16.04.4 VM on Proxmox 4.4 and I have a separate file storage on a Synology NAS.
- Deluge is run as the user `vpn` who resides in the groups `vpn, users, sonarr` also created a user on synology where vpn:users have read/write permissions to the download dir. `vpn` user mounts the network dir via cifs through the /etc/fstab file
- Sonarr/Radarr are run as the user `sonarr` who resides in the groups `sonarr, users, vpn` also created a user on synology where sonarr:users have read/write permissions to the final storage dir. `sonarr` user mounts the network dir via cifs through the /etc/fstab file

As far as permissions go, I'm assuming the SB_mp4_Automator script is called by the user `vpn` since Deluge initiates it but I'm not sure why I can get this to work with Sonarr/Radarr as yo usuggested #489 (ideally I'd like to use filebot, but if this works, I could care less).

**Comment by tscibilia** [comment]
Ok, I solved the permissions problem. I realized that the UID of the `vpn` user on the VM was different than on my synology box (the names were identical though).

**However, I still can't get sonarr/radarr to process the file!!!** The info.log file states:
`Radarr notifier started.`
`Requesting Radarr to scan directory '/mnt/download/postProcess'.`
`Radarr response: started.`

Then it stops with no further progress and I don't know where to look for any more errors! Any ideas?

**Comment by tscibilia** [comment]
I'm trying to self-diagnose but it's not working for me. I thought that maybe I was having issues with permissions because sonarr/radarr are both run by the user `sonarr` which is different from the `vpn` user who runs deluge (remember both users are members of each other's group and they are both members of the group `users` so it matches my synology config). 

So I used `chown` on the files `/postRadarr.py` and `/postSonarr.py` with the user `sonarr` and group `users` while all other files have the ownership of `vpn:users`. Then I ran a new file through and received the same result as earlier, no errors but nothing is being processed by sonarr/radarr. Below is the extent of the logs from radarr during this process...

```
18-6-19 15:41:58.4|Info|DownloadService|Report sent to Deluge. 
18-6-19 16:15:24.4|Info|PreDBService|Starting PreDB Sync
18-6-19 16:15:24.5|Info|NetImportSearchService|No lists are enabled for auto-import.
18-6-19 16:18:54.6|Info|RssSyncService|Starting RSS Sync
18-6-19 16:18:58.0|Info|DownloadDecisionMaker|Processing 190 releases
18-6-19 16:19:08.9|Info|RssSyncService|RSS Sync Completed. Reports found: 190, Reports grabbed: 0
```

**Comment by tscibilia** [comment]
Another update to the issue (please keep in mind I'm not trying to spam, just trying to document and get to the bottom of the issue)... 

I put Radarr and SB_mp4_Automator in debug mode and these are the outputs:
[SB_mp4_Automator](https://hastebin.com/itewecinad.erl)
[Radarr ](https://hastebin.com/kaxaraxuvo.log)

I thought a key factor might be the part of the radarr log that referred to my output folder as the movie? I'll continue to try to troubleshoot but would appreciate any help you could give. 
```
18-6-19 18:52:28.9|Debug|Api|[POST] /api/command: 201.Created (27 ms)
18-6-19 18:52:28.9|Debug|Parser|Parsing string 'postProcess'
18-6-19 18:52:28.9|Debug|Parser|Unable to parse postProcess
18-6-19 18:52:28.9|Debug|DownloadedMovieImportService|Unknown Movie postProcess
```

**Comment by tscibilia** [comment]
One more update, but still note I've been unsuccessful in getting this to work. I wanted to rule out user permissions as an issue so I made the `vpn` user owner of everything (that user was behind a split tunnel, so I had other issue to resolve to access sonarr/radarr). Once I got it all setup, the automator script still returned the same errors as above.

I tried asking around on the radarr discord chat but no one seemed to be able to help.

**Comment by ajgillis04** [comment]
Hello tscibilia, 

I got you message on my original thread. My issue was from February so you are really testing my memory lol. I remember finding Radarr was not at fault but for the life of me can't remember how i got it working. I think it might have been a timing thing. I had to leave it in deluge long enough for radarr to process it. I changed how deluge handled my downloads. I am more than happy to share my configs though.

Radarr/connect/connections
https://snag.gy/JHkq0y.jpg

deluge
https://snag.gy/3hyORb.jpg
https://snag.gy/fOk59L.jpg

MP4_Automator
https://pastebin.com/J0ssjp4z

Let me know if you need anything else

**Comment by tscibilia** [comment]
Thanks @ajgillis04 however, I still can't get this past my last post which was stuck unable to Parse. I might try to rebuild this machine when I get more time (maybe later this year). For now, I'll leave this issue open since I can't resolve it. Maybe @mdhiggins can take a look when he gets a chance.

**Comment by tscibilia** [comment]
I haven't had much time to troubleshoot this error, but in looking over my comments with fresh eyes, I noticed the point in which this fails is transmitting the converted mp4 file back to sonarr/radarr. Specifically, the error says ... `Parsing string 'postProcess'` followed by `Unable to parse postProcess` and `Unknown Series postProcess`. 

I just realized that this is the name of the folder I have all the conversions save into. After deluge downloads and calls the delugePostProcess.py script it converts the completed files in the respective Movie or TV folder and dumps them into one postProcess folder.

To me, it seems that sonarr/radarr are having trouble parsing from this folder? Maybe they don't know what movie/tv show they are processing? Any thoughts? Where does everyone else send their converted media?

**Comment by mdhiggins** [comment]
You could try using completed download handling instead which tends to work better on complicated NAS/container setups and only use postSonarr/postRadarr to handle processing the files (this works just fine, the other scripts are extra and not 100% needed to achieve the same functionality)

**Comment by tscibilia** [comment]
@mdhiggins Thanks, but I've actually given up on the NAS/VM setup I've been troubleshooting here.

Looking through some of your open issues, it seems as though #758 is similar to this in that it's only recognizing the folder name in the logs. 

It's probably time to close this issue as I've decided to try the docker setup (coincidentally, I'm having trouble with that automating too, but I'll open a separate ticket).
