### ISSUE TITLE
Is it possible to us different subtitle formats in the encoding?

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#901]
Hi I am wondering if its possible to use a different subtitle codec when encoding instead of mov_text. As almost every Plex client that calls a file with subs has to transcode them to either .ASS or .STR and this is rather annoying.

**Comment by mdhiggins** [comment]
Pretty sure mov_text is the only one that's supported for embedding into mp4
Use direct stream to avoid transcoding the audio/video when this happens
