### ISSUE TITLE
Sickbeard automator finally converts my files into mp4, but only when done manually due to deluge keeping the torrent paused or queued.

### ISSUE THREAD

**Issue by AliMusa8790** [mdhiggins/sickbeard_mp4_automator#902]
How can I fix deluge from doing this? The automator is unable to grab the file to begin converting automatically. After the file is done downloading in Deluge, the cmd window pops up briefly and then disappears. I've gone over my settings multiple times and everything seems to be set up correctly so I'm not sure what else to do anymore.

I need to use deluge and can't use qBittorrent, unfortunately, since qBittorrent isn't compatible with the sickbeard automator.

Any help will be greatly appreciated. Thanks in advance.

**Comment by mrzoops** [comment]
I think I was having this same issue. Might be due to your file names being too long. He pushed an updat to change the way it handles these long names. I would redownload the automator and set it up again.
