### ISSUE TITLE
Support for non-standard language codes.

### ISSUE THREAD

**Issue by Cheezykins** [mdhiggins/sickbeard_mp4_automator#903]
More and more often recently I'm seeing audio tracks tagged with the language 'english' rather than 'eng', which causes automator to freak out a little.

I know that's not standard, but I don't get to control the tags in the source mkv files.

Adding english as a valid audio tag causes errors too.
```
Traceback (most recent call last):
  File "/home/jenkins/sickbeard_mp4_automator/mkvtomp4.py", line 574, in generateOptions
    languages.add(Language(alpha3))
  File "/home/jenkins/sickbeard_mp4_automator/venv/lib/python2.7/site-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: 'english' is not a valid language
```

It would be nice for it to recognised 'english' and map it to 'eng' internally.

**Comment by mdhiggins** [comment]
This really only impacted subliminal but in the v2 update its reworked so invalid language codes won't cause problems, they'll just be ignored when handing off to subliminal but can still be added so bad tags can get through
