### ISSUE TITLE
SABnzbd ImportError: No Module Named Requests

### ISSUE THREAD

**Issue by CoderKiwi** [mdhiggins/sickbeard_mp4_automator#905]
Trying to get SABnzbd to use the scripts but once it downloads it attempts to run the script and fails with this stack trace from the script: 

```
Traceback (most recent call last):
File "/mp4-automator/SABPostProcess.py", line 5, in <module>
from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
File "/mp4-automator/autoprocess/autoProcessMovie.py", line 11, in <module>
import requests
ImportError: No module named requests
```

Requests has been installed via pip. Using pip2 to install said it was already installed.

Each application (Sonarr, Radarr, SABnzbd) is running as a container within Docker.

I'm running on macOS with several versions of Python installed.  I suspect that's the issue but I'm not sure how to fix it. Python versions are installed under `/usr/local/bin/` (seen below) which isn't the `#!/usr/bin/env python` at the top of each script -- does this matter?.

![screen shot 2018-07-13 at 4 52 59 pm](https://user-images.githubusercontent.com/33564041/42673076-cd8d641c-86bd-11e8-89a6-0318d5b1a308.png)

Requests is installed under `/usr/local/lib/python2.7/`

Please help! Thanks

**Comment by CoderKiwi** [comment]
I've switched to Ubuntu so I'll close this issue.

**Comment by mdhiggins** [comment]
Here's my docker repo, I actually have images for sonarr and radarr on there

https://hub.docker.com/u/mdhiggins/
