### ISSUE TITLE
Issue with NZBGet and running NZBGetPostProcessing.py

### ISSUE THREAD

**Issue by lokolako** [mdhiggins/sickbeard_mp4_automator#906]
Hi,

I'm getting following error running a newly cloned git.
It used to work. I just cloned the git to a new folder and deleted the old.
I'm on a Raspberry Pi running Raspbian (Debian Linux)

````
Mon Jul 16 2018 02:11:00	INFO	Executing post-process-script NZBGetPostProcess.py for 123
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess: Traceback (most recent call last):
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/mnt/HDD4TB/Andet/mp4converter/NZBGetPostProcess.py", line 87, in <module>
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     fileConfig(os.path.join(MP4folder, 'logging.ini'), defaults={'logfilename': os.path.join(logpath, 'index.log')})
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     handlers = _install_handlers(cp, formatters)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     h = klass(*args)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     StreamHandler.__init__(self, self._open())
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     stream = open(self.baseFilename, self.mode)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess: IOError: [Errno 2] No such file or directory: '/var/log/sickbeard_mp4_automator/index.log'
Mon Jul 16 2018 02:11:03	ERROR	Post-process-script NZBGetPostProcess.py for 123 failed (terminated with unknown status)
```

**Comment by mdhiggins** [comment]
I recently moved the logging stuff to /var/log/sickbeard_mp4_automator on unix systems
Try making that directory and giving it permissions to fix this, in the mean time I will add some logic to create the directory if its absent

From: lokolako
Sent: Sunday, July 15, 2018 8:14 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Issue with NZBGet and runningNZBGetPostProcessing.py (#906)

Hi,
I'm getting following error running a newly cloned git.
It used to work. I just cloned the git to a new folder and deleted the old.
I'm on a Raspberry Pi running Raspbian (Debian Linux)
Mon Jul 16 2018 02:11:00	INFO	Executing post-process-script NZBGetPostProcess.py for Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess: Traceback (most recent call last):
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/mnt/HDD4TB/Andet/mp4converter/NZBGetPostProcess.py", line 87, in <module>
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     fileConfig(os.path.join(MP4folder, 'logging.ini'), defaults={'logfilename': os.path.join(logpath, 'index.log')})
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     handlers = _install_handlers(cp, formatters)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     h = klass(*args)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     StreamHandler.__init__(self, self._open())
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess:     stream = open(self.baseFilename, self.mode)
Mon Jul 16 2018 02:11:03	INFO	NZBGetPostProcess: IOError: [Errno 2] No such file or directory: '/var/log/sickbeard_mp4_automator/index.log'
Mon Jul 16 2018 02:11:03	ERROR	Post-process-script NZBGetPostProcess.py for Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN failed (terminated with unknown status)
Mon Jul 16 2018 02:11:04	INFO	Collection Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN added to history
Mon Jul 16 2018 02:11:28	INFO	Post-processing again Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN
Mon Jul 16 2018 02:11:28	INFO	Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN returned from history back to download queue
Mon Jul 16 2018 02:11:28	INFO	Queueing Harry.Potter.And.The.Order.Of.The.Phoenix.2007.DK.ENG.720p.BRRiP.x264.AC3.5.1-NFN for post-processing
```
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mdhiggins** [comment]
Just pushed an update that will check and make sure the directory exists and if not should create it
If it fails to create it (likely due to permissions issues) it will revert back to using its own directory which is the previous behavior
