### ISSUE TITLE
postSonarr.py - /var/log error

### ISSUE THREAD

**Issue by Migz93** [mdhiggins/sickbeard_mp4_automator#907]
Getting the following error when running postSonarr.py, pretty sure i have the latest version of sickbeard_mp4_automator

`
[Error] postSonarr.py: Traceback (most recent call last): 
[Error] postSonarr.py:   File "/sickbeard_mp4_automator/postSonarr.py", line 18, in <module> 
[Error] postSonarr.py:     elif not os.isdir(logpath): 
[Error] postSonarr.py: AttributeError: 'module' object has no attribute 'isdir' `

**Comment by Migz93** [comment]
Can confirm that works now with my Sonarr :) thanks for the speedy fix!

**Comment by mdhiggins** [comment]
Great, thanks for confirmation
