### ISSUE TITLE
Support to clear metadata

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#912]
So we already have tagfile = True/False

But it would really help me out to have True/Flase/Clear

Where Clear will remove all metadata on a file to help plex pull the metadata instead of weird torrent names some files are given.

**Comment by mdhiggins** [comment]
What metadata element is it reading with the torrent name?

Also you might have better luck adjusting your priorities for the Plex Movie Scanner and deprioritizing local media assets
![image](https://user-images.githubusercontent.com/3608298/43654338-e86f5e00-9718-11e8-9393-d63d18a90d7d.png)

**Comment by Smalfinn** [comment]
![image](https://user-images.githubusercontent.com/2158032/43655251-fe9cb20e-9745-11e8-8499-e70d0ee341c6.png)
![image](https://user-images.githubusercontent.com/2158032/43655268-0b4454a8-9746-11e8-953e-0b9ee616e15a.png)

Problem is these episodes don't show up as a Multi-Episode File

Maybe it's nothing to do with the tagging

**Comment by mdhiggins** [comment]
Nothing to do with tagging
That's just how plex handles it, there is not interface adjustments or changes for multi-episode files
