### ISSUE TITLE
mdhiggins/sonarr-sma on Unraid

### ISSUE THREAD

**Issue by letchu22** [mdhiggins/sickbeard_mp4_automator#915]
Just tried the docker image from [mdhiggins](https://hub.docker.com/r/mdhiggins/sonarr-sma/) on Unraid. Been using MP4 autmator on Windows for some time. Works great! Not sure why I can't get it working on Unraid. Sonarr portion woks fine. Might be careless somewhere or not getting him correctly. Posted on the docker issue thread without realizing it was closed.  This is generally what i did. 

Volumes:
/mnt/user/appdata/sonarr-sma:/config
/mnt/user/appdata/sma:/config/sma - set as read only
/mnt/user/appdata/sma/autoProcess.ini:/usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini - set as read only
/mnt/user/media/TV Shows:/tv
/mnt/user/downloads/completed:/downloads

Sonarr:
Completed Download Handling: On
Custom Script: path = /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py - test is successful
autoProcess.ini visible from both /config/sma and /usr/local/bin/sma/sickbeard_mp4_automator
Autoprocess.ini

ffmpeg = /usr/local/bin/ffmpeg/ffmpeg/ffmpeg.exe
ffprobe = /usr/local/bin/ffmpeg/ffprobe/ffprobe.exe
Sonarr portion is filled up with appropriate values

This is the error Sonarr throws up.
postSonarr.py | ImportError: No module named requests | 1:13pm
postSonarr.py | import requests | 1:13pm
postSonarr.py | File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 5, in | 1:13pm
 postSonarr.py | Traceback (most recent call last): | 1:13pm

Not too sure how to access the log to submit. When trying to map the container path - /var/log/sickbeard_mp4_automator to any host path using the shared tag, to access the logs, the entire log folder appears blank. It only works when not mapping. 

Any help towards where to look for more info or how to solve will be appreciated.

**Comment by mdhiggins** [comment]
Looks like you have one too many ffmpeg directories
Should be 
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe

And its unix based, so no .exe
