### ISSUE TITLE
PostSonarr fail - File "/sickbeard_mp4_automator/postSonarr.py", line 23, in <module>

### ISSUE THREAD

**Issue by DanielPiccoli** [mdhiggins/sickbeard_mp4_automator#916]
MP4 conversion are failing with the following error... attempted redeploying the container - but still, same error happens.

Manual.py works fine.

postSonarr.py  IOError: [Errno 13] Permission denied: '/var/log/sickbeard_mp4_automator/index.log' | 11:37am
-- -- | --
   postSonarr.py | stream = open(self.baseFilename, self.mode) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open | 11:37am
   postSonarr.py | StreamHandler.__init__(self, self._open()) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__ | 11:37am
   postSonarr.py | logging.FileHandler.__init__(self, filename, mode, encoding, delay) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__ | 11:37am
   postSonarr.py | BaseRotatingHandler.__init__(self, filename, mode, encoding, delay) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__ | 11:37am
   postSonarr.py | h = klass(*args) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers | 11:37am
   postSonarr.py | handlers = _install_handlers(cp, formatters) | 11:37am
   postSonarr.py | File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig | 11:37am
   postSonarr.py | fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(logpath, 'index.log')}) | 11:37am
   postSonarr.py | File "/sickbeard_mp4_automator/postSonarr.py", line 23, in <module> | 11:37am
   postSonarr.py | Traceback (most recent call last): | 11:37am

**Comment by mdhiggins** [comment]
Looks like you've got a permission issue
Make sure you're setting up your PUID and PGID environment variables appropriately and double check your write permissions for the index.log file

**Comment by Yonn-Trimoreau** [comment]
I'm currently encountering the same issue.
I'm running manual.py and postSonarr.py in parallel.
Maybe the index.log file is locked by one process and the other can't open it in write mode again?
Maybe manually specifying a log output when running manual.py could solve the issue?
Not sure it's possible.. Is it?

**Comment by DanielPiccoli** [comment]
i did a chown 1000:1000 -R on /sickbeard_mp4_automator/ and on /config
things are running again. not sure how those permission got impacted on deployed a fresh container install

**Comment by mdhiggins** [comment]
That is strange considering the error was a problem with /var/log/sickbeard_mp4_automator/index.log which is not related to the root or the config directory

The dockerfile sets the group owner to 'users' which abc (the default user) is a member of
You can check what UID the user abc is assigned and make sure it corresponds to your UID and that ABC is in groups

A fresh container install does still depend on a config directory with appropriate permissions granted so that part at least makes sense
