### ISSUE TITLE
How to Move the folder with the file?.

### ISSUE THREAD

**Issue by haxcop** [mdhiggins/sickbeard_mp4_automator#919]
## Question:
Hi, I would like to know if there's any way that I can set to Move the Folder with the file that is processed and including the SRT files that are being ripping off the files?
### Reason:
- If the Video downloaded comes as 
  - [Movie Name]
     - sadpfiubvnspgbnsfpgibs.mkv
- After processed This is the result

 - *What is left Behind*
  -[download/path/Movie Name]
    - sadpfiubvnspgbnsfpgibs.eng.srt
    - sadpfiubvnspgbnsfpgibs.spa.srt
- *File Processed*  
- [couchpotato_move]
     - sadpfiubvnspgbnsfpgibs.mp4

## Expected Result 1
 - [couchpotato_move]
   - [Movie Name]     
     - sadpfiubvnspgbnsfpgibs.mp4
     - sadpfiubvnspgbnsfpgibs.eng.srt
     - sadpfiubvnspgbnsfpgibs.spa.srt

## Expected Result 2
 - [couchpotato_move]
   - [Movie Name]     
     - Movie Name.mp4
     - Movie Name.eng.srt
     - Movie Name.spa.srt
*BTW I know this is not included in the `.ini` file but will be nice to use also the Renaming feature and not just only the tagging*

Currently that's my .ini setup

*Any other suggestion regarding my `autoprocess.ini` file is also welcome*
## autoprocess.ini
```
[MP4]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = Auto
output_directory = H:/temp/couchpotato_output
copy_to = 
move_to = H:/temp/couchpotato_move
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-max-width = 
h264-max-level = 4.1
use-qsv-decoder-with-encoder = True
ios-audio = aac
ios-first-track-only = False
ios-audio-filter = dynaudnorm
max-audio-channels = 
audio-codec = ac3,mp3,dts,dca,aac
audio-language = 
audio-default-language = eng
audio-channel-bitrate = 256
audio-filter = 
subtitle-codec = srt
subtitle-language = eng,spa
subtitle-default-language = eng
subtitle-encoding = UTF-8
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = false
embed-subs = false
sub-providers = opensubtitles,addic7ed,podnapisi,thesubdb
permissions = 0777
post-process = True
pix-fmt = 
aac_adtstoasc = False
postopts = -preset,slower
preopts = 
video-crf = 18
ios-move-last = False
audio-copy-original = False
audio-first-track-of-language = False
video-profile = 
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
embed-only-internal-subs = False

**Comment by mdhiggins** [comment]
No plans to include renaming or moving of whole folders as that's a feature that's better handled by the media managers that the script integrates with. They all have robust organization systems with sorting and organizing and it would be redundant functionality

**Comment by uchagani** [comment]
@mdhiggins It would be nice to have this option for the manual processing
