### ISSUE TITLE
Using SMA not shrinking files when downgrading mp4's to SD

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#924]
Hi,

I've been using SMA for years as a post download script with NZBGet.  Now I'm wanting to make all my TV shows SD (480p) to save on drive space, so I'm now using SMA using a docker container based on [sonarr-sma](https://github.com/mdhiggins/sonarr-sma).  Most shows download at the desired quality, but some shows are only released at higher qualities.

I have a separate autoProcess.ini for Sonarr & Radarr...

- [link to my docker compose](https://gist.github.com/KaHooli/f3044b5d1ce221c57e686b0f73deda3d)
- [link to my autoProcess.ini for Sonarr](
https://gist.github.com/KaHooli/8113038e8e89637cfac98358c5e65bbc)

When trying to convert down to 480p with SMA, I'm finding that the file size (eg 1080p file that is about 800MB) stays about the same size, but when I convert the same file with Handbreak to 480p, it is down to 168.5MB.

I'm trying to work out where I'm going wrong, but having trouble.  Could someone please have a look at my config files and give any pointers?  Thanks in advance for any assistance given!

**Comment by mdhiggins** [comment]
I would try using the video-crf option to help lower the bitrate. A 1080p file at 800MB is already very heavily compressed so FFMPEG is just preserving the bitrate because at 480p that bitrate is still acceptable
