### ISSUE TITLE
Noob issue: Undefined constant or missing '(' in 'auto'

### ISSUE THREAD

**Issue by barbequesauce** [mdhiggins/sickbeard_mp4_automator#925]
Hey there - just getting started with this tool, looks promising, I'm hoping to convert my library to something the RPI can stream with Plex without transcoding.

I spent the last two days getting FFmpeg to compile properly on my RPi3B+ running Jessie - backing out Debian codec packages and compiling more current ones etc - and now I am finally trying to run manual.py.

With the initial command line of:
`python manual.py -i /mnt/sda/movies/The.LEGO.Ninjago.Movie.2017.RERIP.720p.BluRay.x264-GECKOS.mkv -imdb tt3014284`

I get a traceback:
```
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/opt/sickbeard_mp4_automator/mkvtomp4.py", line 747, in convert
    for timecode in conv:
  File "/opt/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/opt/sickbeard_mp4_automator/converter/ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=19948, cmd="/usr/local/bin/ffmpeg -i /mnt/sda/movies/The.LEGO.Ninjago.Movie.2017.RERIP.720p.BluRay.x264-GECKOS.mkv -vcodec libx264 -map 0:0 -vb 1500k -level 4.2 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -filter:a:0 true -metadata:s:a:0 language=eng -strict experimental -c:a:1 aac -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 960k -metadata:s:a:1 language=eng -strict experimental -f mov -threads auto -y /mnt/sda/converted_movies/The.LEGO.Ninjago.Movie.2017.RERIP.720p.BluRay.x264-GECKOS.mp4">
```

And then this error:
```
Press [q] to stop, [?] for help
[AVFilterGraph @ 0x2395b60] [Eval @ 0x7edfb10c] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x2395b60] Unable to parse option value "auto"
[AVFilterGraph @ 0x2395b60] No such filter: 'true'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:1
Conversion failed!
```

Full output [here](https://pastebin.com/hhN1RM8X).

Any thoughts?

**Comment by mdhiggins** [comment]
Can you post your autoProcess.ini file?

**Comment by barbequesauce** [comment]
[Absolutely](https://pastebin.com/xWLL3MWt)... Thanks

**Comment by mdhiggins** [comment]
Looks like you inadvertently set your `ios-audio-filter` to `True` which isn't a valid audio filter. Just leave that blank or set it to a specific filter you desire

**Comment by barbequesauce** [comment]
Aha! I have no idea why I put that there. 

Looks like it's running full-bore now... Thanks!
