### ISSUE TITLE
Need help with an error

### ISSUE THREAD

**Issue by kinv** [mdhiggins/sickbeard_mp4_automator#928]
Hi, great project. 
Been using it fine via the sonnar/mp4 docker.
Had to do a full reinstall of my server today and came across this error;

Starting conversion.
[######### ] 99%Traceback (most recent call last):
  File "manual.py", line 370, in <module>
    main()
  File "manual.py", line 361, in main
    processFile(path, tagdata)
  File "manual.py", line 219, in processFile
    output = converter.process(inputfile, True)
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 199, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 747, in convert
    for timecode in conv:
  File "/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/sickbeard_mp4_automator/converter/ffmpeg.py", line 534, in convert
    cmd = ' '.join(cmds)
TypeError: sequence item 24: expected string or Unicode, int found

Not really sure what this is about, I have checked permissions of the index file and the owner, that seems to be ok. Did some googling but nothing has come back so posting it on here hoping someone knows what what. Funny thing is it gets to 99% and does this, the file is mp4 with the correct audio and seems to play fine.

Thanks,
Kinv

**Comment by mdhiggins** [comment]
This was due to a bug I introduced recently

It’s since been fixed, just update the docker image

**Comment by mdhiggins** [comment]
What docker image are you using? I have my own that I maintain that has been updated and is working now

**Comment by kinv** [comment]
aront/sonarr, docker page says last push 5 days ago. Radarr was updated yesterday and is fixed.

**Comment by AciDCooL** [comment]
@kinv you don't need another container, if you would have checked the dockerfile it pulls this repo from github the moment it rolls out as a new container form the image. Or you can docker console into your sonar/radarr container and run these commands in de /sickbeard_mp4_automator folder: "git reset --hard" and "git pull"
