### ISSUE TITLE
Best ios audio filter for maintaining volume ranges

### ISSUE THREAD

**Issue by Maximus97** [mdhiggins/sickbeard_mp4_automator#930]
Hi Guys!
I read this issue https://github.com/mdhiggins/sickbeard_mp4_automator/issues/219 which discussed audio filters when converting to AAC. I planned on converting my whole library and I am wondering if pan=stereo|c0<c0+1.414c2+.5c4+.5c6|c1<c1+1.414c2+.5c5+.5c7, volume=1.25
still holds the throne as the best to preserve the the sound? I really wanna do it right the first time and I know there are some really techinical people here who have been thoroughly testing this, and would love to hear their opinions. I don't wanna end up with my media files having dialogue too quiet.

**Comment by mdhiggins** [comment]
I would just continue the discussion under that issue, I never found one I was 100% satisfied with
