### ISSUE TITLE
HEVCQSV : GPU load decreasing (due to a specific option)

### ISSUE THREAD

**Issue by Bigsausage64** [mdhiggins/sickbeard_mp4_automator#932]
Hi,

First, a huge "thank you" for the work you do on the script !!

It works for me but not really as expected : I've noticed something really strange when using HEVCQSV (or H264QSV). Conversion starts normally, my first GPU (Intel HD630) is used at 100% and my second GPU (AMD RX Vega M GL) is loaded around 25%.

Then, depending on which option I set in the autoprocess.ini, the GPU load for both GPUs decreases consistently until reaching only few %. Obviously, this makes conversion really long, much longer than when GPUs are both used to the max.

When I use MyFFMPEG (a GUI for FFMPEG), both GPUs are used to the max (100% for Intel and 25% for AMD) until the end of the conversion.

So I decided to troubleshoot by comparing the command line used by MyFFMPEG and MP4 Automator. 

Here is the commande line that is created by MyFFMPEG:
```
ffmpeg -probesize 50M -analyzeduration 100M -hwaccel dxva2 -i "input.mkv" -map 0:0 -map 0:1 -c:a aac -strict -2 -async 1 -c:v hevc_qsv -load_plugin hevc_hw -b:v 14307.84k -maxrate 28615.68k -bufsize 28615.68k -s 1920x1080 -aspect 16:9 -pix_fmt yuv420p10le -vsync 0 -preset fast -x265-params profile=main10:me=hex:qcomp=0.5:scenecut=40:bframes=4:rc-lookahead=40:min-keyint=24:keyint=240 -sws_flags fast_bilinear -qmin 3 -qmax 51 -vtag hvc1 -metadata creation_time=now -sn -y "output.mp4"
```

Here is my autoprocess.ini : 
ffmpeg = C:\Script\ffmpeg\ffmpegRadarr.exe
ffprobe = C:\Script\ffmpeg\ffprobeRadarr.exe
threads = 0
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = hevcqsv
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = True
ios-audio = False
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = aac
audio-language = eng
audio-default-language =
audio-channel-bitrate = 256
audio-filter =
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = fr
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts = -load_plugin,hevc_hw,-maxrate,30000.00k,-bufsize,30000.00k,-pix_fmt,yuv420p10le,-vsync,0,-preset,fast,-x265-params,profile=main10:me=hex:qcomp=0.5:scenecut=40:bframes=4:rc-lookahead=40:min-keyint=24:keyint=240,-sws_flags,fast_bilinear,-qmin,3,-qmax,51
preopts = -loglevel,debug,-probesize,50000,-analyzeduration,100000m

Here is the command line generated by MP4 Automator:
```
ffmpeg -loglevel debug -probesize 50000 -analyzeduration 100000m -hwaccel dxva2 -i "input.mkv" -vcodec hevc_qsv -map 0:0 -vb 7470k -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -disposition:a:0 default -f mp4 -threads 0 -load_plugin hevc_hw -maxrate 30000.00k -bufsize 30000.00k -pix_fmt yuv420p10le -vsync 0 -preset fast -x265-params profile=main10:me=hex:qcomp=0.5:scenecut=40:bframes=4:rc-lookahead=40:min-keyint=24:keyint=240 -sws_flags fast_bilinear -qmin 3 -qmax 51 -y "output.mp4"
```

I discovered that if I manually remove the "-disposition:a:0 default" and manually launch the command, everything works fine from the GPU perspective.

I've tried to change every audio settings in autoprocess.ini to see if that makes any change but the "-disposition:x:0 xxxxxxxx" settings is always generated in the command line and consequently I always encounter the decrease in GPU load.

Is it a bug ? Am I doing something wrong ? I'd really like to be able to use my GPUs to encode files (I'm ok for quality loss, and so happy with the silence and the speed compared to pure CPU encoding......)

I hope you'll be able to help me. I've searched google completely two times before asking this :-D

Last but not least, I know FFMPEG supports AMD AMF encoder, would it be a lot of work to have it implemented in your script ? Thanks again

**Comment by Bigsausage64** [comment]
I did not mention previously, I'm running Windows 10 64bit with the latest os and drivers updated, version 4.0.2 static of ffmpeg.

I also did not mention that, natively, the script doesn't work if I specify only HEVC as video codec. I had to add the "load_plugin hevc" for it to work. Then I encountered the GPU load issue, that's how I came to compare MyFFMPEG and MP4 automator command lines.......

**Comment by mdhiggins** [comment]
Not sure why disposition would cause an issue, but if you need to disable that feature you can knock it out by commenting out lines 111 and 112 in converter/avcodecs.py

```
        if 'disposition' in safe:
            optlist.extend(['-disposition:a:' + stream, str(safe['disposition'])])
```

**Comment by mdhiggins** [comment]
I suspect that's probably an FFMPEG bug and would advise trying some different builds of FFMPEG and see if that persists

**Comment by Bigsausage64** [comment]
Hey !

I'll try with another FFMPEG version and worst case, I'll comment out the lines.

THANK YOU very much for your feedback !!

**Comment by mdhiggins** [comment]
No problem, let me know what the final result is

**Comment by Bigsausage64** [comment]
Hi,

Just been testing.

I started by commenting line 111 & 112 in converter/avcodecs.py : this did not remove the "disposition" option in the FFMPEG commandline and obviously the problem is still there.

Then I tried with FFMPEG static 3.4.2. Same result ?! no luck

**Comment by Bigsausage64** [comment]
I've just tried the 32 bit version of both 3.4.2 and 4.02 of FFMPEG and the result is the same. Not working.

Any other suggestions ?

**Comment by mdhiggins** [comment]
Hm I mean that's definitely where that FFMPEG entry comes from. I see you're on windows. Sometimes you have to delete the .pyc files that are created for those changes to take affect

Also for copied audio codecs the disposition may be applied as well, you may need to also comment out lines 480 and 481 which should look essentially identical to the ones you commented out earlier

**Comment by Bigsausage64** [comment]
Okay........it's getting even weirder !

Commenting out line 480 and 481 made the "disposition" option disappear in the commande line

I did another test using manual.py and unfortunately the issue I'm having is still occuring.................

When I stop the script, check the logs, find the commande line that was generated and launch it manually (outside any script), the issue does not occur.

I defintely think there is something wrong with the way the script is using Hardware acccel.........

Any other suggestions to get a fix or even a workaround ?

In any case, thank you for your help !!!!

**Comment by mdhiggins** [comment]
Can you post the full command that's generated? I wonder if its maybe an issue with the threads option?

**Comment by mdhiggins** [comment]
Out of curiosity, when using MyFFMPEG vs the script, are you using the exact same read and write destination drives? The fact that it throttles after a certain point sounds like there's a bottleneck somewhere and often that occurs when memory is saturated and it becomes limited by HDD write speeds. If you were by chance using a different drive for MyFFMPEG that may cause it.

**Comment by mdhiggins** [comment]
And the next step I would try is taking the command generated by the script and running that manually with isolated changes until you find what seems to trigger the fix. I wonder if trying to remove the 'threads' parameter might make any difference. Its set to 0 which should be auto but maybe just removing the flag all together?

**Comment by Bigsausage64** [comment]
My final objective is that my current machine will convert files stored in a NAS folder (source and target will be in the same folder, but remote).

But so far, all my tests are made locally : source and target are stored in a local drive (Samsung 960 Evo 1 Tb - NVME PCIE4x SSD).

**Comment by mdhiggins** [comment]
Also, if you run the command generated by the script manually in command prompt does that perform the same way?

Another idea would be to run things and keep an eye on any obvious performance bottlenecks using resource monitor in windows that might explain why things are throttling

**Comment by Bigsausage64** [comment]
Taking command line from the logs and removing "threads" option : 

C:\Script\ffmpeg\ffmpegRadarr.exe -loglevel debug -probesize 50000 -analyzeduration 100000 -hwaccel dxva2 -i "C:\Script\Test\African Cats (2011) (1080p BluRay x265 Silence).mkv" -vcodec hevc_qsv -map 0:0 -vb 7470k -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -f mp4 -load_plugin hevc_hw -maxrate 30000.00k -pix_fmt yuv420p10le -preset fast -sws_flags fast_bilinear -qmin 3 -qmax 51 -y "C:\Script\Test\African Cats (2011) (1080p BluRay x265 Silence).mp4"

FFMPEG stops converting after few frames...........

**Comment by mdhiggins** [comment]
Hm, so here's a breakdown of the differences between the two commands from your original post
```
-probesize 50M : -probesize 50000
--- : -loglevel debug
-analyzeduration 100M: -analyzeduration 100000m
-b:v 14307.84k : -vb 7470k
-strict -2 : ---
-async 1 : ---
-c:a aac : -c:a:0 copy
--- : -f mp4
--- : -threads 0
-maxrate 28615.68k : -maxrate 30000.00k
-bufsize 28615.68k : -bufsize 30000.00k
--- : -disposition:a:0 default 
--- : -metadata:s:a:0 language=eng
-s 1920x1080 : ---
-sn : ---
-s 1920x1080 -aspect 16:9 -metadata creation_time=now: ---
```

Things with `---` are absent, things to the left of the `:` are from myFFMPEG, right is SMA

If we filter out stupid things like metadata inconsistencies here is the list of possible performance problems

```
-probesize 50M : -probesize 50000
--- : -loglevel debug
-analyzeduration 100M: -analyzeduration 100000m
-b:v 14307.84k : -vb 7470k
-strict -2 : ---
-async 1 : ---
--- : -f mp4
--- : -threads 0
```

There's a big difference in the setting for analyzeduration and probesize, I wonder if maybe that's the culprit? I doubt debug level logging would be the issue but sometimes if logging is very aggressive it can cause performance hits. The bitrate variations probably aren't the issue. Not sure about strict and async

**Comment by Bigsausage64** [comment]
I tested then with the same command line as the one generated by the script but I launched it manually in a DOS command : 

C:\Script\ffmpeg\ffmpegRadarr.exe -loglevel debug -probesize 50000 -analyzeduration 100000 -hwaccel dxva2 -i "C:\Script\Test\African Cats (2011) (1080p BluRay x265 Silence).mkv" -vcodec hevc_qsv -map 0:0 -vb 7470k -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -f mp4 -threads 0 -load_plugin hevc_hw -maxrate 30000.00k -pix_fmt yuv420p10le -preset fast -sws_flags fast_bilinear -qmin 3 -qmax 51 -y "C:\Script\Test\African Cats (2011) (1080p BluRay x265 Silence).mp4"

And it works fine !!!!! 

![image](https://user-images.githubusercontent.com/43091726/46906195-fb209900-ceff-11e8-9748-83f6d882db26.png)

**Comment by mdhiggins** [comment]
Hm that's very strange, so the command itself is fine when running from command prompt?

**Comment by Bigsausage64** [comment]
Correct......threads option is not faulty 🤔

**Comment by Bigsausage64** [comment]
> Hm, very strange and I'm not sure why Popen / Python would create the bottleneck
> 
> Try going to converter/ffmpeg.py to line 379-380 and changing `shell=False` to `shell=True`

Did not change a thing. It doesn't work even with shell=True in converter/ffmpeg.py on line 379 :'(

**Comment by mdhiggins** [comment]
Out of curiosity, could you try running on 64 bit python3 instead of python27 (not sure if you're on 64 bit or not but I would try 64)

**Comment by Bigsausage64** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSSS Thank you so much !!! It works fine with Python 3 64 bit

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/46907422-19769c80-cee0-11e8-9fe8-612cf2a582e6.png)

Good news
Guess we can close this issue haha, glad its working

**Comment by Bigsausage64** [comment]
Fantastic !! Thank you so much

**Comment by Bigsausage64** [comment]
You're the man !!!!!!!!!!

Plex transcoding a 4k files for sync + 1 conversion with your script and look at that : 

![image](https://user-images.githubusercontent.com/43091726/46908294-3bdcda00-cf21-11e8-8f00-5bf34074e0f3.png)

You made my day
