### ISSUE TITLE
DXVA2 or HEVC_QSV for best performance

### ISSUE THREAD

**Issue by jeff47** [mdhiggins/sickbeard_mp4_automator#933]
I have a i7-7700 CPU and a Nvidia GT730 video card.  Looking for a balance of quality and speed.

I'm wondering about the DXVA2 versus the HEVC_QSV settings.  Is there any way to tell which setting will give me the best output.  Is it counterproductive to enable both?

**Comment by mdhiggins** [comment]
Not sure that’s more of a general FFMPEG question than a question specifically about this script
