### ISSUE TITLE
Sonarr monitor status update failed

### ISSUE THREAD

**Issue by lastb0isct** [mdhiggins/sickbeard_mp4_automator#934]
Seeing this after every run on Sonarr --

`
09/28/2018 16:53:43 - Standard - 2018-09-28 09:53:43 - SonarrPostConversion - ERROR - Sonarr monitor status update failed.
09/28/2018 16:53:43 - Standard - Traceback (most recent call last):
09/28/2018 16:53:43 - Standard -   File "/root/mp4automator/postSonarr.py", line 102, in <module>
09/28/2018 16:53:43 - Standard -     log.info("Sonarr response: ID %d %s." % (rstate['id'], rstate['state']))
09/28/2018 16:53:43 - Standard - KeyError: 'id'
`

**Comment by lastb0isct** [comment]
Another thing to note is that if I have "Completed Download Handling" turned off it will not process content.  It just hangs.  Once i turn Completed Download Handling on it processes the content...

**Comment by mdhiggins** [comment]
Your configuration isn't set up correctly. You need to verify your autoProcess.ini settings for Sonarr, the script is failing to talk to Sonarr

**Comment by lastb0isct** [comment]
Is there anyway to test the connectivity after updating the autoProcess.ini?

**Comment by mdhiggins** [comment]
Aside from running the script and checking no there’s no dedicated test
