### ISSUE TITLE
What if something goes wrong?

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#936]
If something goes wrong, is there a way to trigger renaming, loading into plex, and communication with Sonarr again?

One of my storage drives ran out of space, and 4 movies didn't get moved in to the Plex. Is there a way to manually trigger the whole process again without DLing from deluge again?

**Comment by mdhiggins** [comment]
Just use the manual import option in Sonarr and point it to whatever files you want to process

**Comment by DatsiK96** [comment]
I didn't know that existed, I spose that will work.

Thanks.
