### ISSUE TITLE
Run Through Audio Strip/Sub Strip But Don't Convert?

### ISSUE THREAD

**Issue by Migz93** [mdhiggins/sickbeard_mp4_automator#937]
I'm wanting to run this script on my 4k library to clean up all the extra audio/sub languages that come with it, keeping only 5.1+2.0 English audio and extract English subs. But i don't want to convert the actual file as I'm pretty sure if i do i lose any HDR in the file, is there anyway to get this to do it's magic without converting any of the files? Just poke with the audio & subs?

**Comment by zybeon** [comment]
Yes, ensure the correct video codecs are set in the autoProcess.ini for all your files and it will copy the video stream while transcoding what audio and sub streams need it.

You should definitly do a manual run of a few different files to ensure it processes how you want. While doing this manual run you might also want to set the 'copy_to' setting to a temp folder so it won't delete your original files for the test run and to compare the original directly to the processed file. Remember to blank out the 'copy_to' setting when you run in on your whole directory.

**Comment by Migz93** [comment]
Thanks for the reply, i understand theres that way which would involve me having to find out the codec of each stream and inputting it but was hoping there was maybe an option where it will just copy with any codec?

**Comment by mdhiggins** [comment]
There is not a global option to approve all codecs but you can get the vast majority of them by adding the basics, pretty much anything HDR is gonna be x265/h265 so adding that and x264/h264 should take care of it. The specifics of the codecs such as the color profile and pixmap and things don't matter and won't impact the stream being copied directly. 

My codec option is `video-codec = h264, h265, hevc` and that covers pretty much everything used in an mp4/mkv container in the last 10 years

**Comment by mdhiggins** [comment]
FFPROBE translates x265/x264 into h264/h265 so you don't need to include them on the list, just FYI

**Comment by Migz93** [comment]
Awesome, thank you very much for your help :)!
