### ISSUE TITLE
Feature Request: HEVC VAAPI support

### ISSUE THREAD

**Issue by nephariouz** [mdhiggins/sickbeard_mp4_automator#939]
I noticed that h264 VAAPI support was added last year, but HEVC VAAPI support is still missing. Is it possible to add support for it?

**Comment by mdhiggins** [comment]
Probably, what are the FFMPEG specs for HEVC VAAPI?

**Comment by RandomNinjaAtk** [comment]
Would really like to see this added...

**Comment by mdhiggins** [comment]
Someone post some example FFMPEG commands and I’ll try to add support

**Comment by RandomNinjaAtk** [comment]
I'll mess around with it and see what I can do!

**Comment by RandomNinjaAtk** [comment]
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mp4 -vf 'scale_vaapi=format=p010' -c:v hevc_vaapi -profile 2 -b:v 15M output.mp4

This command worked, for encoding h264 to x265 10 bit, pulled the command directly from here:

https://trac.ffmpeg.org/wiki/Hardware/VAAPI

**Comment by mdhiggins** [comment]
So if I assume correctly, any time you want to use vaapi you're going to need `-hwaccel vaapi` `-hwaccel_ouput_format vaapi` and the codec `hevc_vaapi` and the rest such as the format and the device will need to be set by the user?

**Comment by RandomNinjaAtk** [comment]
Sadly I don't know enough about it... I would assume the device selection works the same as the current h264_vaapi configuration already in the script. Its just some of the additional options are different.

**Comment by mdhiggins** [comment]
Alright I added h265vaapi as a codec option and made some tweaks to both h264vaapi and h265vaapi see if it works

**Comment by mdhiggins** [comment]
d6fbd37c9719788c0cfaead5580e5eebe217d7f6

**Comment by RandomNinjaAtk** [comment]
I'll give it a try, been working on improving my ffmpeg compile to include everything that is needed...

**Comment by mdhiggins** [comment]
Yeah I don't have the hardware of build to run it but I checked the command line output it generated and it looked like it should include everything based on the sample

**Comment by RandomNinjaAtk** [comment]
So after much playing arond I was not able to get it to work with the default settings. I modified the h265 to this:

```
codec_name = 'h265vaapi'
    ffmpeg_codec_name = 'hevc_vaapi'

    def _codec_specific_produce_ffmpeg_list(self, safe, stream=0):
        optlist = super(H265VAAPI, self)._codec_specific_produce_ffmpeg_list(safe, stream)
        optlist.extend(['-vaapi_device', '/dev/dri/renderD128'])
        optlist.extend(['-vf', 'hwupload'])
        optlist.extend(['-profile:v', '1'])
        return optlist
```

And I was able to get it to encode

**Comment by RandomNinjaAtk** [comment]
After further testing it appears setting the bitrate does not seem to work...

The bitrate does however seem to be controlled using quality profiles, such as: -qp 19

Maybe an option can be used to use -qp instead of bitrate for this configuration?

**Comment by mdhiggins** [comment]
Did you try using crf instead of bitrate?

**Comment by mdhiggins** [comment]
Also I pushed an update that included the `h265_vaapi` to `hevc_vaapi` fix, good catch

**Comment by RandomNinjaAtk** [comment]
> Did you try using crf instead of bitrate?

That option doesn't seem to make any changes, I only think it applies to h264.


> Also I pushed an update that included the `h265_vaapi` to `hevc_vaapi` fix, good catch

These also need to be changed:

From:
```
optlist.extend(['-vf', 'scale_vaapi=format=p010'])
optlist.extend(['-hwaccel_output_format', 'vaapi'])
```
To:
```
optlist.extend(['-vf', 'format=nv12,hwupload'])
```

Otherwise it will error out, and this also prevents encoding to 10bit, which only the newest intel proccessors support

**Comment by mdhiggins** [comment]
So the bitrate from autoProcess.ini is in kbps and apparently there was an old filter that would lock it out if you set it above 15000 so maybe that was causing bitrate to be ignored

Pushed another update including your above change as well as removed that check, see if that helps

**Comment by mdhiggins** [comment]
And just as an aside, the bitrate needs to be in kbps format for now, so don't put 15M like FFMPEG would want or it will get filtered out

**Comment by mdhiggins** [comment]
And I reviewed the documentation you posted above, bitrate should work but CRF is not supported

**Comment by RandomNinjaAtk** [comment]
Thx, I will try it shortly. I'm only basing that it doesn't work because I cannot get it to work  based on my testing strictly using cli outside of using mp4_automator.. The documentation does say that you can use it, but it doesn't seem to work in my scenario...

**Comment by RandomNinjaAtk** [comment]
So the changes didn't fix the bitrate issue, however, adding this seems to fix it:

```
-maxrate:v <bitrate-value>
```

So if -b:v setting also set the maxrate, it does increase the bitrate as expected.

**Comment by mdhiggins** [comment]
So I guess a solution would be to read the set bitrate and also set the maxrate
Pushed an update that does just that

**Comment by RandomNinjaAtk** [comment]
> So I guess a solution would be to read the set bitrate and also set the maxrate
> Pushed an update that does just that

Trying it now, I think that will fully resolve the issue and this can be closed!! I'll confirm after some more testing

**Comment by RandomNinjaAtk** [comment]
Here is the results, without setting the bitrate, this is the final output:

![image](https://user-images.githubusercontent.com/8386416/68534231-f9422880-02ff-11ea-86f5-8add7f23f55c.png)

So the h265 file is not much smaller, but that using roughly the same bitrate the script detected from the original file. Also I don't think vaapi is the most effecient in comparison to software encoding. 

This was tested using the manual.py file. It would be good if some others tested this, but I think this is likely resolved!!!

**Comment by RandomNinjaAtk** [comment]
@mdhiggins this issue is probably ready for closure...

**Comment by kevindd992002** [comment]
@RandomNinjaAtk 

In the MediaInfo screenshot you posted above, why does the media file still has an 8-bit bit depth? I thought you were trying to encode this to 10-bit?

**Comment by kevindd992002** [comment]
@mdhiggins 

So with either h265vaapi set as the first codec in video-codecs, did you remove the use of crf in your code? So even though you specify a crf value there? Because when I try using crf with h265vaapi, I still see crf being included in the ffmpeg command run by your script. 

Does this apply to when using just h265,x265?

**Comment by mdhiggins** [comment]
h265vaapi inherits from the base h265 codec which inherits from the videocodec class
videocodec as the parent includes parameter for CRF, as such CRF still persists and isn't explicitly removed but FFMEPG won't do anything with it when using h265vaapi as per the above discussion

**Comment by kevindd992002** [comment]
Ok, that makes sense. But if a non-vaapi codec like h265 and x265 is used, the CRF setting will still have an effect, correct?

**Comment by mdhiggins** [comment]
I believe so, the script certainly won't fail to pass it. Its really up to FFMPEG though so that's out of my specific knowledge base and might be better directed to FFMPEG support channels

**Comment by kevindd992002** [comment]
Ok, that's fair enough. Thanks!
