### ISSUE TITLE
utorrent postprocess aborts quickly without any error in logs

### ISSUE THREAD

**Issue by acosmichippo** [mdhiggins/sickbeard_mp4_automator#941]
Hello,

Firstly, thanks for all you have done with this project, it is totally awesome!

Anyway, the reason I am posting today is because autoprocessing keeps failing after downloads finish from sonarr and radarr (I'll focus on just Sonarr here for simplicity).  postSonarr.py seems to be getting called fine from sonarr, but the processing never makes it past 'readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.'

I'm using windows 10 with utorrent, Sonarr, Radarr, and Plex.   I am just starting to use usenet and NZBGet postprocessing is working just fine.  I am also able to run manual.py perfectly on all of the files that fail from sonarr/radarr, which is getting me by in the meantime.

These are a few examples of attempts in index.log.  For some reason info.log seems to have stopped logging about a month ago. 

> 2018-10-15 01:14:26 - uTorrentPostProcess - INFO - uTorrent post processing started.
> 2018-10-15 01:14:26 - readSettings - INFO - C:\Python27\python.exe
> 2018-10-15 01:14:26 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2018-10-15 02:19:18 - uTorrentPostProcess - INFO - uTorrent post processing started.
> 2018-10-15 02:19:18 - readSettings - INFO - C:\Python27\python.exe
> 2018-10-15 02:19:18 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2018-10-15 03:45:07 - uTorrentPostProcess - INFO - uTorrent post processing started.
> 2018-10-15 03:45:07 - readSettings - INFO - C:\Python27\python.exe
> 2018-10-15 03:45:07 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.

Troubleshooting checks from the utorrent setup instructions:
1) requests library is installed

3) This is where I'm least confident.  According to my googling on the syntax in utorrent, it should be this:
`"C:\Users\[username]\Documents\Programs\mp4 automator\uTorrentPostProcess.py" "%L" "%T" "%D" "%K" "%F" "%I" "%N"`
although I have also tried quotes around only the file path:
`"C:\Users\[username]\Documents\Programs\mp4 automator\uTorrentPostProcess.py" %L %T %D %K %F %I %N`
and no quotes:
`C:\Users\[username]\Documents\Programs\mp4 automator\uTorrentPostProcess.py %L %T %D %K %F %I %N`
and one pair of quotes around the whole thing:
`"C:\Users\[username]\Documents\Programs\mp4 automator\uTorrentPostProcess.py %L %T %D %K %F %I %N"`
I don't think any have worked right.

4) utorrent settings in autoprocess.ini:
[uTorrent]
hostname = http://localhost:8080/
username = ***
password = ***
webui = True
convert = True
action_before = pause
action_after = unpause
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
output_directory = 
host = http://localhost:8080/
sickbeard-label = sickbeard
couchpotato-label = couchpotato
sickrage-label = sickrage

5) Labels appear to be working ok.  utorrent label settings are above, and Sonarr utorrent settings here:
![capture](https://user-images.githubusercontent.com/40671162/46952290-69786f00-d058-11e8-972d-022a9785de8c.PNG)

Apart from the utorrent "run program" syntax I'm not really sure what the issue could be.  Thank you for any help and please let me know if you need more info.  Apologies in advance if it's something totally obvious that I've missed.

**Comment by mdhiggins** [comment]
At some point the logging was moved to index.log, take a look there
