### ISSUE TITLE
Sonarr setup issues

### ISSUE THREAD

**Issue by TheBigZig** [mdhiggins/sickbeard_mp4_automator#943]
I've been using this for years now, and love it! But I've been forced to move from Sickrage to Sonarr.  I like Sonarr, but I'm having issues getting it Sonarr adn Sickbeard_MP4_Automator to work together.  
When Sonarr downloads a show, I get this in my logs:

  | python.exe | ImportError: No module named autoprocess | 2:01pm
  | python.exe | from autoprocess import plex | 2:01pm
  | python.exe | File "C:\sickbeard_mp4_automator\postSonarr.py", line 6, in <module> | 2:01pm

When I look at postSonarr.py line 6, I see:
from autoprocess import plex

Not sure where to go from here.
Any help is GREATLY appreciated.
Thanks
Bill

**Comment by TheBigZig** [comment]
Bump.

**Comment by mdhiggins** [comment]
Do you have the plex.py script in your autoprocess folder in the script directory?

**Comment by TheBigZig** [comment]
Which script directory?  Sabnzb or Sonarr?

**Comment by mdhiggins** [comment]
So you shouldn’t have multiple script directories and shouldn’t be pulling individual scripts out of the main directory as all the files have dependencies in the main folder. In fact if you pulled those scripts out of the main script folder that will give you the error you’re receiving.

The only exception to this is NZBGet

**Comment by TheBigZig** [comment]
So which folder does the Plex.py script need to be in?

**Comment by mdhiggins** [comment]
More importantly you need to keep the entire script directory intact as it appears on GitHub. It should be in the autoprocess folder but if you moved anything else it will just create a new error so I would clone it again so you have a clean install

**Comment by TheBigZig** [comment]
A clean install was my plan.  I'll let you know how it shakes out.
Thanks for the input.
Separately, have you ever considered building a GUI front end for this?
I'd GLADLY pay for that!
Thanks again,
Bill

**Comment by TheBigZig** [comment]
So, I redownloaded the automator script, and re-set up everything from scratch.  Now Sonarr is passing the download to SabNZdb, and SabNZdb is running the automator script, but it is throwing the following error:
2018-11-03 22:22:47 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2018-11-03 22:22:47 - readSettings - INFO - C:\Python27\python.exe
2018-11-03 22:22:47 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
File "C:\sickbeard_mp4_automator\postSonarr.py", line 34, in <module>
tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
TypeError: int() argument must be a string or a number, not 'NoneType'

The downloaded MKV file is named w gibberish, but the folder that is downloaded has series and episode info.  Am I missing something in my config scirpt?
Thanks
Bill

**Comment by mdhiggins** [comment]
You’re trying to launch the postSonarr script from SAB. You need to use the postSAB script (and you should configure sonarr to use postSonarr)

The postSAB script is only needed if you aren’t using completed download handling though. If you want to use that you don’t need any scripts in SAB and can just setup postSonarr within sonarr

**Comment by TheBigZig** [comment]
Yep.  I was a dumb a$$.  realized that I had SabNZdb pointed at the wrong place after I posted. 
That's what I get for trying to milk daylight saving time...

**Comment by mdhiggins** [comment]
All working now?

**Comment by TheBigZig** [comment]
No still humpped up somewhere.  I'll send a full description of my setup
tomorrow or Wednesday, once I've had a chance to look at it.  I'm kind of
wrapped around the axel at this point, and I need to take a step back and
step through the installation.

**Comment by TheBigZig** [comment]
So I've confirmed that I have Sonarr, SABnzdb and your script's autoprocess.ini sections are all set up in accordance with the instructions in readme.md.  

SABnzdb's categories is as follows:
Category: sonarr
Processing: Default
Script: SABPostProcess.py
Folder/path:  TV
Indexer Category:  TV

Sonarr's Connections page is appropriately set up, and the postSonarr script test passes.

Despite all of this, I still get the following error after downloads:

Traceback (most recent call last):
File "C:\sickbeard_mp4_automator\SABPostProcess.py", line 5, in <module>
from autoprocess import autoProcessTV, autoProcessMovie, autoProcessTVSR, sonarr, radarr
ImportError: No module named autoprocess

Any help is GREATLY appreciated.
Thanks
Bill

**Comment by mdhiggins** [comment]
That's a generic python import error, do you have the autoprocess folder in your script directory? (C:\sickbeard_mp4_automator\autoprocess probably)

**Comment by TheBigZig** [comment]
autoProcess.ini?  Yes.  Along with autoProcessTV.py and SABPostProcess.py

**Comment by mdhiggins** [comment]
No, do you have a folder named autoprocess

**Comment by TheBigZig** [comment]
Not in your script's folder.

**Comment by TheBigZig** [comment]
I've got one in the zip folder I downloaded, it didn't get copied in some how.  I'm going to move it in and let you know what happens

**Comment by TheBigZig** [comment]
Clean install, w old .ini file worked like a champ, once I got the latest version of FFMpeg.
THANKS!!!!!!
Seriously, do you have a PayPal tip jar or something?
You're support for this is AMAZING!!!!

**Comment by mdhiggins** [comment]
No donations needed, glad it's working!

**Comment by TheBigZig** [comment]
Seriously, let me know if you put one up!  You've helped me out with this a couple of times now.
Thanks again!!!
