### ISSUE TITLE
TVDB AND TMDB API error

### ISSUE THREAD

**Issue by saambd** [mdhiggins/sickbeard_mp4_automator#946]
When Processing a file

> python manual.py -i /media/hdd/hdd2/TV\ Series/English/2\ Broke\ Girls/Season\ 4 -a
> Manual processor started.
> /usr/bin/python
> 64bit Python.
> Processing file /media/hdd/hdd2/TV Series/English/2 Broke Girls/Season 4/S04E15 - And the Fat Cat.mp4

This file stack here.. it can't get any information from tmdv or tvdb any solution?

**Comment by saambd** [comment]
no 'no errors' its just stack on Processing file.

**Comment by mdhiggins** [comment]
You could try checking the log files and see if there's more information.
If there isn't, you could change you logging level to debug to get even more output in the log files and console by modifying logging.ini which might give some more information.

Also double check all your dependencies and that the program has access to connect to TVDB/TMDB.

If you queue up a movie does that also hang?
