### ISSUE TITLE
Audio Track Deletion 

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#948]
The audio track of 1 of my files is being deleted for no reason by the looks of it?

index.log : https://pastebin.com/raw/Gu4ETLhn
autoProcess.ini : https://pastebin.com/raw/6hTa0fwx

**Comment by mdhiggins** [comment]
Hm does look like it should be working, can you send me a copy of the file that's giving you that issue?

**Comment by Smalfinn** [comment]
Thank you for the speedy reply!

Yeah of course - https://we.tl/t-5RRVy4UB9J

**Comment by Smalfinn** [comment]
Retried the files and 1 file has audio but all the rest dont... weird

index.log : https://pastebin.com/raw/uPJe083U

**Comment by mdhiggins** [comment]
Hm so very strange but using your copy and pasted config settings it works fine and detects and creates the audio stream

```
{
    "format": "mp4",
    "video": {
        "codec": "h264",
        "map": 0,
        "level": 4.1,
        "profile": "high",
        "pix_fmt": "yuv420p",
        "crf": 23
    },
    "audio": {
        "0": {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "eng",
            "disposition": "default"
        }
    },
    "subtitle": {},
    "preopts": [
        "-hwaccel",
        "dxva2"
    ],
    "postopts": [
        "-threads",
        "0"
    ]
}
```

Did you by any chance make any modifications to anything?

**Comment by Smalfinn** [comment]
I re-downloaded the script and pasted my autoProcess.ini back and the same thing happened

index.log : https://pastebin.com/raw/fnPVDb4Z

**Comment by mdhiggins** [comment]
Is it specific to the files that fail (if you do the failed files individually do they also fail?) or does the specific file not matter but just the first one in a batch works and the subsequent files fail?

**Comment by Smalfinn** [comment]
.mkv files seem to batch perfectly but .avi files; after the first file they lose audio

Ran the second file in the previous batch first and the audio was picked up?!

index.log : https://pastebin.com/raw/BVH9VVL0

**Comment by mdhiggins** [comment]
I'm unable to reproduce this even doing it in bulk but have an idea
I just pushed an update try installing it and rerunning and see if it makes a difference

**Comment by Smalfinn** [comment]
I get a different error now:
`C:\FREEFLIX\sickbeard_mp4_automator>manual.py -i "C:\FREEFLIX\manual" -a
Manual processor started.
C:\Python27\python.exe
64bit Python.
An unexpected error occurred, processing of this file has failed
cannot deepcopy this pattern object
An unexpected error occurred, processing of this file has failed
cannot deepcopy this pattern object
An unexpected error occurred, processing of this file has failed
cannot deepcopy this pattern object
An unexpected error occurred, processing of this file has failed
cannot deepcopy this pattern object
An unexpected error occurred, processing of this file has failed
cannot deepcopy this pattern object`

**Comment by mdhiggins** [comment]
Figured out the issue and will have a fix out shortly.

**Comment by niallobr** [comment]
I'm not sure if it's related to the above and recent commit to mkvtomp4.py, but am now getting this error:

```
[WARNING ] 00:33:06 core:134 [execute] stdout: 2018-11-03 00:33:06 - delugePostProcess - INFO - Deluge post processing started.
2018-11-03 00:33:06 - readSettings - INFO - /usr/sbin/python2
2018-11-03 00:33:06 - delugePostProcess - INFO - Successfully connected to Deluge

[WARNING ] 00:33:06 core:136 [execute] stderr: Traceback (most recent call last):
  File "/volume1/Video/mp4converter/delugePostProcess.py", line 86, in <module>
    converter = MkvtoMp4(settings)
  File "/volume1/Video/mp4converter/mkvtomp4.py", line 121, in __init__
    self.importSettings(settings)
  File "/volume1/Video/mp4converter/mkvtomp4.py", line 126, in importSettings
    settings = deepcopy(settings)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

**Comment by mdhiggins** [comment]
Yeah, reverted that last commit it worked on python3 and not 2 but I'll have a fix for this issue soon but for now I rolled back the old one

**Comment by mdhiggins** [comment]
Alright new update posted, try that to see if original issue is fixed

**Comment by niallobr** [comment]
All working well here 👍

**Comment by Smalfinn** [comment]
All working now ^_^ Thank you!
