### ISSUE TITLE
FFMpegConvertError error="Exited with code 1", pid=26524

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#953]
Hello,

Scripts runs perfectly except with 1 file - I get this massive error log and can't seem to find out why ?

index.log : https://pastebin.com/raw/GDtP3C62
autoProcess.ini : https://pastebin.com/raw/6hTa0fwx

**Comment by mdhiggins** [comment]
File appears to be making FFMPEG crash though it doesn't seem to be giving a particularly helpful error. Might just be a bad file especially if everything else is working

**Comment by Smalfinn** [comment]
I'll try and download the file from a different source and see what happens

**Comment by Smalfinn** [comment]
Downloaded the file from a different source and the same problem presents

index.log : https://pastebin.com/raw/LNJXu3Wh

**Comment by mdhiggins** [comment]
Is it the same release though? I think that specific release might just have issues with FFMPEG and source may not matter

**Comment by Smalfinn** [comment]
Oh okay, I thought handbrake was built on top of ffmpeg
