### ISSUE TITLE
Test if video is corrupt after conversion

### ISSUE THREAD

**Issue by Iguana9999phil** [mdhiggins/sickbeard_mp4_automator#954]
I’m using sma to convert all non mp4 files to mp4 and make it streaming compatible, sometimes a conversion ends up giving an corrupted video file (source already corrupted I guess) which gives blank screen or corrupted videos. I also seen one movie this week which didn’t include a audio track. Is this something ffprobe could handle to weed out the corrupted files before passing it back to sonarr / radarr?

**Comment by mdhiggins** [comment]
This plus integrated with the post-process scripts would be a good solution
