### ISSUE TITLE
Docker File not creating Libraries

### ISSUE THREAD

**Issue by Doubler24** [mdhiggins/sickbeard_mp4_automator#957]
When setting up the Sonarr-sma docker file, all goes well and I can set everything up. However when running the post script I get the following error.

18-11-29 05:33:24.0|Error|python3|Traceback (most recent call last):
18-11-29 05:33:24.0|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/postRadarr.py", line 44, in <module>
18-11-29 05:33:24.0|Error|python3|    if MkvtoMp4(settings).validSource(inputfile):
18-11-29 05:33:24.0|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 250, in validSource
18-11-29 05:33:24.0|Error|python3|    input_extension = self.parseFile(inputfile)[2]
18-11-29 05:33:24.0|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 782, in parseFile
18-11-29 05:33:24.0|Error|python3|    path = os.path.abspath(path)
18-11-29 05:33:24.0|Error|python3|  File "/usr/local/bin/sma/env/lib/python3.5/posixpath.py", line 357, in abspath
18-11-29 05:33:24.0|Error|python3|    if not isabs(path):
18-11-29 05:33:24.0|Error|python3|  File "/usr/local/bin/sma/env/lib/python3.5/posixpath.py", line 64, in isabs
18-11-29 05:33:24.0|Error|python3|    return s.startswith(sep)
18-11-29 05:33:24.0|Error|python3|AttributeError: 'NoneType' object has no attribute 'startswith'

When I browse /usr/local/bin I see no such libraries created for FFMPEG or sma? 

Not sure if this matters that I am running all these Docker containers on my QNAP NAS?

**Comment by comocook** [comment]
The link in the dockerfile to download the ffmpeg build is no longer valid (broken).

It should be replaced with : https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz

**Comment by mdhiggins** [comment]
Good catch, fixed this
