### ISSUE TITLE
Possible to Encode TWICE ??

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#958]
Using deluge to download torrents which executes delugePostProcess.py to create a 720 version & a 480 version of the tvshow and replace/deletes source and import into Sonarr the 720 version only.

Anyone any idea how to make this happen??

Thanks in advance.

**Comment by mdhiggins** [comment]
At this time no this feature is not supported. No immediate plans to add it. Best option I can think is making a wrapper script and having two versions of the script installed one for 720p and one for 480p that calls each script separately.

**Comment by Zeusy123** [comment]
mdhiggins first thankyou very much for the helpful reply:)

Im only new to coding, so please forgive if I ask a stupid question.  But are you saying I should run 2 sickbeard_mp4_automator install in separate folders? using different quality settings 480 & 720 version and get deluge to run both 480sickbeard_mp4_automator & then run 720sickbeard_mp4_automator?
Im not sure on the word "wrapper" you use:-/
I wouldnt want to overload the server, so would like to limit 1 instance of ffmpeg running @ any 1 time.

**Comment by mdhiggins** [comment]
Aside from deluge, what other software are you using to handle your media? I'll try and come up with some kind of solution but need a little more info

Also is this being used with plex?

**Comment by mdhiggins** [comment]
I wonder if you could setup sonarr/radarr to run the script twice and do 2 separate installs one for 720p and one for 480p. Then connect the 2 to sonarr / radarr as 2 separate custom scripts

**Comment by Zeusy123** [comment]
Hi mahiggins,

was thinking following: deluge execute 720 remuxing and put into sonarr.  Then setup custom script in sonarr to make 480 remuxing of the 720 version in sonarr??

I'll do some testing tomorrow on this and keep you informed:)

**Comment by mdhiggins** [comment]
Yeah I think that's a good option. Just make sure you enabled convert-mp4 on the 480p version of the script since that'll be going 2nd

**Comment by Zeusy123** [comment]
Any idea on how i can achieve:

If video courpted or bad and needs replaced.

If i delete file from within sonarr, it will also delete the 480p video file in the mirrored path?

delete this file:
/tvshow/720p/Eastenders/Season01/Eastenders.S01E01.mp4

should also delete /tvshow/480p/Eastenders/Season01/Eastenders.S01E01.mp4

How could I achieve this?

**Comment by mdhiggins** [comment]
Not a good way to specifically do this, pushing beyond the intended use of the script to create multiple copies. Best bet might be to note use any deluge scripts, use Sonarr's 'completed download handling' and just have 2 separate post processing scripts

**Comment by Azno** [comment]
You might wanna do what the 4K movie fanatics do with radarr, install sonarr twice configure one for 480p and the other for 720p and both them to two independent folders/labels. and make a batch script to run manual.py on one of the versions every night or something similar
