### ISSUE TITLE
docker config issues

### ISSUE THREAD

**Issue by nobodyshome** [mdhiggins/sickbeard_mp4_automator#960]
I was moving my nzbget over to docker, had it working normally for ages. However, I'm having a hard time figuring this out. Any help would be appreciated.

https://paste.fyi/QEw5fUqwE

**Comment by mdhiggins** [comment]
This is probably from the MP4_FOLDER not being set correctly

**Comment by nobodyshome** [comment]
I triple checked, tried multiple paths. Still can't get it to work. Could it be a permissions thing?

**Comment by nobodyshome** [comment]
Figured it out, had to set the path fully, rather than using `~/sickbeard_mp4_automator/`

Thanks for the work on this.
