### ISSUE TITLE
Using tvnamer to handle file renaming before "guess" is done

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#961]
Any interesting looking into using https://github.com/dbr/tvnamer to do rename the file before doing any "guessing"?  

I have a bit of a "hack" done to get it working as a test case if you are interested?  I added a param to settings to allow setting the config file path, then I use the subprocess model to call out and parse the new file name from the result.  If anything goes wrong it falls back to using the original file name.

**Comment by mdhiggins** [comment]
Not really. Its essentially just a redundant system. Guessit handles determining the show data from the filename. This program essentially does the same thing so you’re just adding 2 layers of filename based guessing.

From: Shawn
Sent: Wednesday, December 12, 2018 3:46 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Using tvnamer to handle filerenaming before "guess" is done (#961)

Any interesting looking into using https://github.com/dbr/tvnamer to do rename the file before doing any "guessing"?
I have a bit of a "hack" done to get it working as a test case if you are interested? I added a param to settings to allow setting the config file path, then I use the subprocess model to call out and parse the new file name from the result. If anything goes wrong it falls back to using the original file name.

**Comment by ravensorb** [comment]
The issue is that it assumes the file name is correct - I am running a large number of files that have pretty rough file names in terms of having useful information.

**Comment by ravensorb** [comment]
I do actually use them --- they are picking up the metadata from the file name which is hit or miss. So far tvnamer is 99% accurate where this automator and programs like sonarr are about 75% accurate in naming the file and updating the metadata -- this list is one of the main issues is it seems that a large number of files have embedded meta data that has a lot of useless info makes things less than ideal.

**Comment by mdhiggins** [comment]
So the better option then would probably be to tie into TVRenamers guessing algorithm

**Comment by ravensorb** [comment]
I like it :)

**Comment by mdhiggins** [comment]
Opted to stick with guessit but just updated to guessit v3 (previously only supported v1) so should see some improvements
