### ISSUE TITLE
Nzbget creates 2 files for radarr

### ISSUE THREAD

**Issue by sbcrumb** [mdhiggins/sickbeard_mp4_automator#962]
Ok so originally I wanted to have nzbget process and convert. And that worked but would end up with 2 files in my final destination one .mp4 for whatever and one .mp4.partial~ every time if I let nzbget to the processing.
If I let radarr do it then what happens it is moves the file to my dir that gets uploaded via cloudplow, and then converts it rather then leaving it at the download location converting and moving to the final destination .

Where do I start as to what is doing this.
I would have like to keep nzbget going the script. But whatever will get it converted then moved to my unionfs would be great.

**Comment by mdhiggins** [comment]
Are you using completed download handling?

**Comment by sbcrumb** [comment]
Crap yes should that be turned off

**Comment by mdhiggins** [comment]
You basically have 2 ways to handle this

Completed download handling turned ON but then no processing after NZBGet (cause it will grab partial files etc) 

OR

Completed download handling turned OFF then you get post NZBGet processing and the script will inform Sonarr/Radarr etc when its down to scan the directory and trigger the scan. 

Completed download handling is definitely nicer and can monitor and watch for things more reliably and is easier to setup especially on weird implementations but if you want to convert stuff before it gets passed back to Sonarr/Radarr you can't use it. The script when configured properly will notify Sonarr when to do its scan to avoid picking up partially processed files in place of CDH.

**Comment by sbcrumb** [comment]
I feel like an idiot, mainly cause in Sonrrv3 it was working with dowload handing turned on with out issues. but Radarr was my one troublesome spot. But I am going to turn it off on both and see what happens. 
Thanks again for clearly up things, I have been chasing this one down for the last week. lol.

**Comment by mdhiggins** [comment]
If you run into issues with the file not being handed back to Radarr/Sonarr after download check your autoProcess.ini settings and make sure you have the right Sonarr/Radarr API key, address, port, etc

**Comment by sbcrumb** [comment]
Will do thanks again man. Always a life saver.
