### ISSUE TITLE
Allow logging path to be set via setting file

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#963]
Any thought to allowing the logging path to be defined in the settings file?  I run this in a jail and would like to have the log file written to a specific location that can be watched.

**Comment by Azno** [comment]
Depends what auto processor script your using, for example, if you're using SABPostProcess.py 

This is on line 11:

logpath = '/var/log/sickbeard_mp4_automator'

change the logpath to where ever you want the file saved.

just edit with ever .py file your using in your downloader and look for the var called logpath.

Azno~

**Comment by mdhiggins** [comment]
Migrated the log path settings to log.py instead of being defined individually so you can edit this file if you need
