### ISSUE TITLE
Compress?

### ISSUE THREAD

**Issue by tylerphillip** [mdhiggins/sickbeard_mp4_automator#967]
Sorry if this is a stupid question - but I'm looking for a way to compress the file as this fantastic little automator works to convert to mp4.  I stumbled upon a thread for FFMPEG on this but wasn't sure if that worked with this setup and if so WHERE do I put the code?  I'm so new to all of this so please forgive my ignorance.  

Thanks friends!

**Comment by mdhiggins** [comment]
There's no good way to compress the files but you're already compressing things by encoding the data streams in varying codecs such as H264 / AAC and further global filesystem compression probably wouldn't yield a ton of savings. 

If you could clarify what type of compression you're referring to that would be helpful

**Comment by tylerphillip** [comment]
Thanks for the reply!  I guess what I was hoping for was for some sort of setting adjustment I could add in to the script to make the resulting MP4 file smaller.  I'm noticing that when the MP4 automator runs the resulting MP4 is basically the same size as the original MKV file and I'd like it to be smaller for space savings.  For instance, if I run the MP4 through Handbrake and choose the "Very Fast 1080p30" preset, I can get the MP4 down to about 1/2 the original size.  That's would I would like to try to do within the MP4 automator but I wasn't sure if there was any way to make that happen.  I have no problem running the files through Handbrake to get them smaller but it kind of defeats the purpose of having the automator convert all files to MP4 as soon as they're done downloading just to have to run them through Handbrake anyway.  Sorry to sound so needy!  If there's no way to adjust the settings no problem.  Thanks again for the help!

**Comment by mdhiggins** [comment]
You just need to adjust your bitrate settings so that you reduce the quality of the streams by encoding them at a lower bitrate

**Comment by tylerphillip** [comment]
Here's a snip of the MP4 part of my autoProcess.ini file if it helps. 
![image](https://user-images.githubusercontent.com/46201936/50529258-49821480-0ab9-11e9-8c8b-cfb7f73391f3.png)

**Comment by Azno** [comment]
try setting:

video-crf =24
video-profile = slow

ffmpeg default is 23 

website with description - https://trac.ffmpeg.org/wiki/Encode/H.264

Azno~
