### ISSUE TITLE
Feature REQ: x265/h265 with HDR10+ encode options

### ISSUE THREAD

**Issue by weezzelboy** [mdhiggins/sickbeard_mp4_automator#968]
Can you create an option to select x265/h265 encoding over x264 as files are growing in size do to 2160p and trueHD, x265 would reduce file size to over 50% thus reducing over all footprint on NAS or array considerably. and But adding the HDR10+ option you could encode with BT2020 colorspace and 10bit deepth. Which woould produce a small copy of a x265 10bit HDR copy.

-pix_fmt yuv420p10le
-x265-params "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc"

here is a reference link to view..
https://superuser.com/questions/1280876/convert-youtube-hdr-vp9-2-video-to-hevc-hdr-with-ffmpeg

If i had the skills of a programmer i would attempt it, but i am lacking those skills..

Here is a Movie 12 Strong with HDR10+ 
MediaInfo Json format:
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "11832091923885050479",
"Format": "HEVC",
"Format_Commercial_IfAny": "HDR10",
"Format_Profile": "Main 10",
"Format_Level": "5.1",
"Format_Tier": "High",
"CodecID": "V_MPEGH/ISO/HEVC",
"Duration": "7839.375000000",
"BitRate": "46729958",
"Width": "3840",
"Height": "2160",
"Sampled_Width": "3840",
"Sampled_Height": "2160",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "24.000",
"FrameCount": "188145",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"ChromaSubsampling_Position": "Type 2",
"BitDepth": "10",
"Delay": "0.000",
"StreamSize": "45791708769",
"Default": "Yes",
"Forced": "No",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.2020",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "PQ",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.2020 non-constant",
"matrix_coefficients_Source": "Stream",
"MasteringDisplay_ColorPrimaries": "Display P3",
"MasteringDisplay_ColorPrimaries_Source": "Stream",
"MasteringDisplay_Luminance": "min: 0.0050 cd/m2, max: 1000 cd/m2",
"MasteringDisplay_Luminance_Source": "Stream",
"MaxCLL": "764 cd/m2",
"MaxCLL_Source": "Stream",
"MaxFALL": "374 cd/m2",
"MaxFALL_Source": "Stream"

Thanks weezzelboy

**Comment by weezzelboy** [comment]
So after alot o googling, i have found that by adding this to the "postopts= " section it is doable to carry over the metadata from a HDR mkv file to HDR mp4 file.
autoProcess.ini
postopts = -preset,fast,-x265 -params,level=5.2:colorprim=bt2020:colormatrix=bt2020nc:transfer=smpte2084

**Comment by arebokert** [comment]
I think it would be great if mp4_automator had an option for checking if the media file is of BT.2020 color encoding and add the ffmpeg options for mapping the colors to BT.709 if that is the case. Correct me if I'm wrong, but adding the parameters for color mapping HDR to SDR on a media file that doesn't have HDR will result in bad color representation?

**Comment by mdhiggins** [comment]
Is ffprobe able to pull the color data metrics? If it is this is something that could probably be implemented

**Comment by kmr2319** [comment]
This is the line that I assume you'd want in this scenario:

    Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 8250 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 23.98 tbc (default)

Full ffprobe otuput:
```
ffprobe version 4.1.4-1build2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x555c1dab1140] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Aquaman (2018).m4v':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Aquaman
    genre           : Action
    date            : 2018-12-07
    encoder         : 
    iTunEXTC        : mpaa|Pg-13|300|
    iTunMOVI        : <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
                    : <key>cast</key><array>
                    : <dict><key>name</key><string>Jason Momoa</string></dict>
                    : <dict><key>name</key><string>Amber Heard</string></dict>
                    : <dict><key>name</key><string>Willem Dafoe</string></dict>
                    : <dict><key>name</key><string>Patrick Wilson</string></dict>
                    : <dict><key>name</key><string>Nicole Kidman</string></dict>
                    : </array>
                    : <key>screenwriters</key><array>
                    : <dict><key>name</key><string>Paul Norris</string></dict>
                    : <dict><key>name</key><string>James Wan</string></dict>
                    : <dict><key>name</key><string>Mort Weisinger</string></dict>
                    : <dict><key>name</key><string>Geoff Johns</string></dict>
                    : <dict><key>name</key><string>Will Beall</string></dict>
                    : </array>
                    : <key>directors</key><array>
                    : <dict><key>name</key><string>James Wan</string></dict>
                    : <dict><key>name</key><string>Jody Blose</string></dict>
                    : <dict><key>name</key><string>Carolina Hggstrm</string></dict>
                    : <dict><key>name</key><string>Joyce Heftel</string></dict>
                    : <dict><key>name</key><string>Tracy L. Moody</string></dict>
                    : </array>
                    : <key>producers</key><array>
                    : <dict><key>name</key><string>Zack Snyder</string></dict>
                    : <dict><key>name</key><string>Deborah Snyder</string></dict>
                    : <dict><key>name</key><string>Rob Cowan</string></dict>
                    : <dict><key>name</key><string>Peter Safran</string></dict>
                    : <dict><key>name</key><string>Jon Berg</string></dict>
                    : </array>
                    : </dict></plist>
                    : 
    media_type      : 9
    hd_video        : 2
    description     : Home Is Calling
    synopsis        : Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his
  Duration: 02:23:19.42, start: 0.000000, bitrate: 9189 kb/s
    Chapter #0:0: start 0.000000, end 668.383000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 668.383000, end 1330.628000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 1330.628000, end 1810.024000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1810.024000, end 2427.766000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 2427.766000, end 3023.653000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 3023.653000, end 3674.761000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 3674.761000, end 4136.097000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 4136.097000, end 4900.361000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 4900.361000, end 5689.524000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 5689.524000, end 5976.436000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 5976.436000, end 6571.822000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 6571.822000, end 7295.545000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 7295.545000, end 7818.901000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 7818.901000, end 8599.348000
    Metadata:
      title           : Chapter 14
    Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 8250 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 427 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, 7.1, fltp, 497 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(eng): Data: bin_data (text / 0x74786574)
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:4: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x750 [SAR 1:1 DAR 2:3], 90k tbr, 90k tbn, 90k tbc
Unsupported codec with id 100359 for input stream 3
```

**Comment by mdhiggins** [comment]
I would need to see the output with `ffprobe -show_streams` to get the full level of detail to see if we can pull that info

**Comment by kmr2319** [comment]
Looks like it's in there:
```
color_range=tv
color_space=bt2020nc
color_transfer=smpte2084
color_primaries=bt2020
```

Full output attached...

Thanks!!!

[ffprobe.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4142782/ffprobe.txt)

**Comment by mdhiggins** [comment]
So pulling that data should be doable. Then the question is what FFMPEG command parameters would we need to generate. Think using the same screening behavior as something like pix_fmt would be reasonable

If you could give a sample FFMPEG command you'd like to convert the source file you linked into what you're looking for I can try and put something together

**Comment by kmr2319** [comment]
I'm not too familiar with these options, I was just jumping on the HDR10 bandwagon of this issue. But, some options were listed on @weezzelboy in the original post and I found some (seemingly good) examples here:
https://medium.com/@yllanos/how-to-encode-a-4k-hdr-movie-using-ffmpeg-while-maintaining-selected-auio-tracks-intact-from-source-d1e2f6a16162

and here:
https://forum.doom9.org/showthread.php?t=175227

Maybe @weezzelboy has some further thoughts on this...

**Comment by mdhiggins** [comment]
I guess the question here would be is there a universal set of parameters that everyone would want in this case that I should code into the codecs default options or is this something that would be better left to postopts where users can define it

**Comment by arebokert** [comment]
I'm thinking of an option that adds color mapping automatically if HDR is detected. You would then have this option off by default but if the user were to turn it on, then it would auto detect and add required options.

**Comment by mdhiggins** [comment]
So if `color_primaries=bt2020` then we're dealing with an HDR source

Then I could include an hdr-filter option that would only inject if HDR is detected, and people could set that to whatever they want

How's that sound?

**Comment by mdhiggins** [comment]
Apparently not quite that simple
https://video.stackexchange.com/questions/22059/how-to-identify-hdr-video

**Comment by wjbeckett** [comment]
I'd like to jump on this request too.
But in a different way - I'd like to start re-encoding my media to h265 to save space. I'm not talking 4k media specifically, just any media really.
I'm hoping this is something that can be done as I'd love to be able to save some space without having to use another tool like unmanic or tdarr.

**Comment by mdhiggins** [comment]
@wjbeckett this can already be done. This thread is about a default color profile for HDR content.

**Comment by wjbeckett** [comment]
> @wjbeckett this can already be done. This thread is about a default color profile for HDR content.

Oh crap. Sorry for hijacking the thread.

**Comment by joeblack2k** [comment]
Well.. quick hack is just look in the filename if it got HDR in it

**Comment by arebokert** [comment]
> Apparently not quite that simple
> https://video.stackexchange.com/questions/22059/how-to-identify-hdr-video

I think the solution this guy gave sounds pretty good using ffprobe https://video.stackexchange.com/a/28715

**Comment by mdhiggins** [comment]
a3b1207221b38ad996dade634c4c6be5ee10f617

Alright I think that should do it

Added an HDR section to autoProcess.ini where you can set what you want the script to consider HDR by a combination of color-space, color-transfer, and color-primaries

If it meets that criteria, the filter under the HDR category will be applied

I also added a force-filter option throughout the various filter options so filters can be optionally applied or forced if the codec would otherwise copy

Also added a dedicated video filter option for non HDR content

Let me know if this solves the issue and is dynamic enough to suit everyone's need
