### ISSUE TITLE
Copy to *using foldername*

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#970]
Using Radarr my folder structure is:
/movies/Movie Name (2018)/Movie Name (2018).mkv

Ive setup custom script "On Rename" to execute "postRadarr.py" which will do the encoding.
I wish to after encoding, COPY TO= /1920/ keeping same folder structure so the resulting encoded file would end up in:
/1920/Movie Name (2018)/Movie Name (2018).mkv

and another copy:

/1280/Movie Name (2018)/Movie Name (2018).mkv

How can I achieve this?

**Comment by mdhiggins** [comment]
Not directly supported using copy to as it doesn't support relative structures but you could write a post-process script to achieve this pretty easily
