### ISSUE TITLE
Consistant Failure to convert

### ISSUE THREAD

**Issue by ShiroiKuma** [mdhiggins/sickbeard_mp4_automator#971]
I'm using sonarr_sma (my fork that simple puts this onto lsioarmhf/sonaar instead, and uses ffmpeg-arm from the same repo you use).

I'm constantly getting the following error when converting multiple files and not sure what's a possible cause here.

Log: https://pastebin.com/ydFdrDpH
autoProcess.ini: https://pastebin.com/nFLv4pAm

My ini is very basic,no post_opts at all. Any idea's what could cause that ffmpeg failure?

**Comment by mdhiggins** [comment]
Might it have to do with that specific arm build of FFMPEG?

**Comment by ShiroiKuma** [comment]
I've been doing some tests and setting threads to 1 resolves the problem, but takes forever.

Given the chipset on the Odroid XU4 is using an Exynos 5 Octa 5800, which runs 8 cores in a big.LITTLE setup. So 4 cores at 2ghz and 4 at 1.3ghz. It may be that ffmpeg suffers from race conditions due to this.

For anyone reading this, if you are using sonarr-sma/radarr-sma on a similar chip. Using `--cpuset-cpus="4-7"` or `--cpuset-cpus="0-3"` would restrict the container to the same core speed core's and eliminate this problem.

I highly doubt that this is something sma would be able to detect and/or control, and would need fixing upstream in ffmpeg (doubtful as the chipset is niche)
