### ISSUE TITLE
Do not encode if source width less than 1920??

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#972]
Any way I can make mp4_automator NOT encode a movie if the source width is NOT 1920 width???
Just some movies i grab are only available in -w 1280 and I do not want them increased to -w 1920.

Ideal it would just skip encoding if source width less than -w 1920.

**Comment by mdhiggins** [comment]
Script only encodes for lower widths, won't upscale by default

```
        if self.video_width is not None and self.video_width < info.video.video_width:
            self.log.debug("Video width is over the max width, it will be downsampled. Video stream can no longer be copied.")
            vcodec = self.video_codec[0]
            vwidth = self.video_width
        else:
            vwidth = None
```

**Comment by stagedatalosstest** [comment]
test123
