### ISSUE TITLE
[tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. 

### ISSUE THREAD

**Issue by a13519** [mdhiggins/sickbeard_mp4_automator#973]
Hello,

I was keeping got this error from the log:

[tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. This will cause multi-file releases of being renamed to the same file. Please add it in the renamer settings. Force adding it for now.

The version of couchpotato is:
================================================
About This CouchPotato
Version12ca4c22680961346e0aa2617941bf1a7252fc67 (3/31/2018, 9:29:42 PM)Updatersource, masterID53151 Directories/usr/local/share/couchpotato/var/db/couchpotatoStartup Args['--daemon', '--data_dir', '/var/db/couchpotato', '--pid_file', '/var/run/couchpotato/couchpotato.pid', '--config_file', '/usr/local/etc/couchpotato/settings.conf']Namespace(config_file='/usr/local/etc/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/var/db/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=False)
================================================

Could you help?

**Comment by hughcifer666** [comment]
Did you ever find a solution to this. Am having the same issues and cannot get a fix for it.

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/552
