### ISSUE TITLE
Customized audio track titles?

### ISSUE THREAD

**Issue by gtholder1** [mdhiggins/sickbeard_mp4_automator#976]
First, thanks for all your efforts with creating these great scripts.  They are a lifesaver.

I'm not sure if this is an issue, a dumb question, or a feature request, but is there a way to set up a custom naming scheme for the audio tracks created? 

Currently I have it set basically as the default of creating a 2 channel AAC track as track 1, and pass through the better quality source used to create track 1 (DTS, AC3, etc), as audio track 2.  In general this works as advertised, but both tracks get named the same thing when muxed back into the .mp4. It seems that when it creates the AAC audio track it is just naming it whatever the source track was.  Either "Track 1 [eng]", "Track 2 [eng]" etc. if the source track isn't already named. Or, both get named the same such as "5.1 DTS @ 1536 kbps - [English]", if the source track was named "5.1 DTS @ 1536 kbps - [English]".

Ideally I would prefer the tracks to be named for the output codec not the input codec.  ie "Track-1 AAC 2ch [Eng]" and "Track-2 5.1 DTS [Eng]".  Other additional tracks appear to pass through without issue.  

Thanks for any info you can provide!

**Comment by mdhiggins** [comment]
Does the mp4 container have track names supported in its data structure? I don’t think it does or at least I haven’t encountered it

**Comment by gtholder1** [comment]
It must, otherwise the extra audio tracks would just be referred to as "Track x [lang] instead of directors comments etc.  Additionally I have used a program a few years ago called mymp4box that could demux an mp4 and let you remove and  insert tracks into the container and it had the option to rename any of the tracks and then re-mux.

**Comment by mdhiggins** [comment]
I'm not sure the mp4 wrapper actually supports track naming. Some players might read custom tags but from what I can find in my quick search it doesn't seem likes it supported or standardized in any fashion

**Comment by gtholder1** [comment]
ok, too bad.  Thanks for looking into it.
