### ISSUE TITLE
2 pass encoding possible?

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#981]
Been researching 2 pass encoding and wondering if sickbeard_mp4_automator could do it??

If so how?

**Comment by stagedatalosstest** [comment]
test123

**Comment by stevemk14ebr** [comment]
just add it as a post or pre op in autoprocess.ini -pass 2

**Comment by mdhiggins** [comment]
This is the correct answer
Make sure you comma separate your parameters though
