### ISSUE TITLE
[Feature Request] Call script once complete

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#984]
I'd like the functionality for SMA to call a script once finishing processing Sonarr/Radarr files. 

My idea is:
1. File Downloaded
2. Sonarr/Radarr import file
3. SMA Kicks in
4. SMA starts manual script
5. Manual script moves data to gsuite using rclone. 

Is this something that could be possible? :)

**Comment by mdhiggins** [comment]
Should be possible using the already existing post processing functionality. Would just need to write a post progressing script to handle your specific gsuite needs

**Comment by StevenChorkley** [comment]
Sorry to be an idiot mate if I'm clueless - 
I understand that - but I don't think that Sonarr / Radarr control the order to which the post-processing scripts run?

**Comment by mdhiggins** [comment]
This script has its own post processing functionality that can be run as the final step after all conversions are finished. Use that

**Comment by StevenChorkley** [comment]
Cheers mate - I'm a total idiot ;)
