### ISSUE TITLE
Question: Settings for different quality conversion

### ISSUE THREAD

**Issue by rrd911** [mdhiggins/sickbeard_mp4_automator#985]
Trying to decipher what settings to put in the autoProcess.ini file to have videos converted to a specific quality.

Example
TV shows set to 480P as an example or 720p

What would I place in the ini file?

thanks

**Comment by arebokert** [comment]
Have a look at video-max-width in the README

**Comment by mdhiggins** [comment]
Exactly

**Comment by JySzE** [comment]
480p
video-max-width = 640 
720p
video-max-width = 1280

Aspect ratio will be preserved.

This is what I use and it works.

**Comment by rrd911** [comment]
Thanks
