### ISSUE TITLE
Sonarr V3 Commit breaks Sonarr SMA

### ISSUE THREAD

**Issue by psychoflame** [mdhiggins/sickbeard_mp4_automator#987]
So it looks like the latest commit to the script breaks processing for files in sonarr. I had it all setup and working fine and now I'm seeing this error message whenever sonarr attempts to process a file.

> `
> [Error] python3: SyntaxError: Missing parentheses in call to 'print' 
> 
> 
> [Error] python3:   File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 17 
> 
> 
> [Error] python3:     print "Sonarr event type is Test" 
> 
> 
> [Error] python3:                                     ^ 
> 
> 
> [Error] python3: SyntaxError: Missing parentheses in call to 'print' 
> 
> 
> [Error] python3:   File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 17 
> 
> 
> [Error] python3:     print "Sonarr event type is Test" 
> 
> 
> [Error] python3:                                     ^ `

**Comment by mdhiggins** [comment]
Reverted that last commit and tried a different solution, let me know if that fixes things

**Comment by psychoflame** [comment]
I fixed it manually just now actually lol. You need Parenthesis around the print statement in that commit as thats the new syntax required in python 3 which is used in the containers

**Comment by mdhiggins** [comment]
I merged that last commit too quickly, that pull I merged actually completely just nuked postSonarr before anything happened in v3 instead of fixing it.

It shouldn't have been using print either since this script uses logging

Would definitely update to remove the whole change

**Comment by psychoflame** [comment]
Okay, i just need to recreate the docker container to pull down your new commits correct?

**Comment by mdhiggins** [comment]
Give it like an hour, I'm rebuilding the docker containers now, then yeah pulling again will fix

**Comment by psychoflame** [comment]
Awesome, thanks for the quick fix mate
