### ISSUE TITLE
Error only with animated movie

### ISSUE THREAD

**Issue by buckeyesfan** [mdhiggins/sickbeard_mp4_automator#988]
Not sure what to make of this error, but only started to happen with Spiderman into the spiderverse and How to Train Your Dragon 2.  But How to Train Your Dragon 1 worked fine.
Any help greatly appreciated
![spidey](https://user-images.githubusercontent.com/26880363/53280345-e8f10b80-36e6-11e9-91dc-8544d6dfae7c.PNG)

**Comment by mdhiggins** [comment]
Do you have any software that is scanning the directories you’re processing the files in? Anything like Plex or Sonarr/Radars etc setup to automatically scan or import? Some external program is trying to use the file when it goes to delete.

**Comment by buckeyesfan** [comment]
I do have plex set to update libraries, but not to that location.  Once the file is converted, I manually transfer it into plex

**Comment by buckeyesfan** [comment]
Really weird…ran a few tests of just a 4 minute clip, and twice it worked fine and twice gave me the file is open in another program.

Also looks like python had 3 .exe. open in task manager when it threw the error, but only one when it performed the whole process

**Comment by buckeyesfan** [comment]
![dragon 3](https://user-images.githubusercontent.com/26880363/53289518-edf4a000-3764-11e9-9399-09c2804ff7fb.PNG)

Just ran the program back to back times and got this

**Comment by mdhiggins** [comment]
I'm not sure how much more specific the error can get. Something is using the file preventing the script from doing its job. Its likely some other program on your system.

Here's a SO thread explaining how you can debug further
https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows
