### ISSUE TITLE
Improvement: ability to set track 1/default audio stream language 

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sickbeard_mp4_automator#989]
If I grab a multi movie, which has multiple audio streams and subtitles.
example:
audio stream 0 = French
audio stream 1 = German
audio Stream 2 = English.

subitles 0 = French
subtitle 1 = German
subtitle 3 = English.

I would like to force the default language for audio and subtitles streams.
Default = eng

would move audio stream 3 and subitles 3 into 0 position, making them play by default.

**Comment by mdhiggins** [comment]
Default tracks are now selected based on if they match the audio-default-language and subtitle-default-language instead of their order
