### ISSUE TITLE
iTunes thinks all mp4 files are audio

### ISSUE THREAD

**Issue by mph88** [mdhiggins/sickbeard_mp4_automator#99]
When I run sabToSickBeardwithConverter.py with the default settings, it imports a TV show as an mp4 file into iTunes (using add to iTunes automatically), but iTunes only recognizes it a Music file (even though I can open the file in Subler and the tag shows TV show). However, when I delete the file from iTunes and re-add it, iTunes correctly identifies that it is a TV show

**Comment by richmindlearn** [comment]
You may try iDealshare VideoGo to fix this "iTunes thinks all mp4 files are audio" issue at https://www.idealshare.net/itunes-quicktime/itunes-mp4-solution.html
