### ISSUE TITLE
Watch a directory and convert files in it

### ISSUE THREAD

**Issue by lesteenman** [mdhiggins/sickbeard_mp4_automator#991]
Is there currently a way to watch a directory and automatically process files/folders ending up in this directory?

What I'm thinking of is basically a way to have a wrapper for `manual.py`. The reason for this is so I can easily wrap this in a Docker container, which does no more than take files from one directory and outputs them to another.

Assuming there's not a way to do this which I missed, would there be any interest for this? Or should we just use another Linux tool to do this?

**Comment by lesteenman** [comment]
After some more thinking, this could probably be achieved with something like inotifywait. What I'm not sure about yet, however, is how that will handle relatively rapid changes in succession; I want it to finish converting the first subdirectory before proceeding with the next one.

**Comment by mdhiggins** [comment]
No plans to add this but other automation and monitoring software is probably the way to go and just tie in to manual.py or write your own version of any of the post scripts that already are provided
