### ISSUE TITLE
Output smaller using FFMPEG manually

### ISSUE THREAD

**Issue by memphisraynz** [mdhiggins/sickbeard_mp4_automator#993]
I am trying to use this as a bit of a compression tool as well as converting to a single format. I convert a 600mb MKV and get a 620mb mp4. Using what I think are the same setting directly through FFMPEG gives me a 360mb file.

What am I doing wrong here?

Thanks

FFMPEG Command
.\ffmpeg -i "input.mkv" -c:v libx264 -crf 19 -maxrate:v 2000k -bufsize:v 4000k -preset:v veryfast -c:a ac3 c:\temp\output.mp4

autoProcess.ini
![2019-03-12 11_55_33-](https://user-images.githubusercontent.com/9811720/54169303-e4399f00-44bd-11e9-9e97-a7c479b22c78.png)

**Comment by mdhiggins** [comment]
Whats the codec information for your source video? What’s the output from manual.py when it does the conversion?

From: memphisraynz
Sent: Monday, March 11, 2019 9:57 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Output smaller using FFMPEGmanually (#993)

I am trying to use this as a bit of a compression tool as well as converting to a single format. I convert a 600mb MKV and get a 620mb mp4. Using what I think are the same setting directly through FFMPEG gives me a 360mb file.
What am I doing wrong here?
Thanks
FFMPEG Command
.\ffmpeg -i "input.mkv" -c:v libx264 -crf 19 -maxrate:v 2000k -bufsize:v 4000k -preset:v veryfast -c:a ac3 c:\temp\output.mp4
autoProcess.ini

**Comment by memphisraynz** [comment]
Using MediaInfo I am told the original codec is AVC
Attached is the output of Manual.py
[manual.py.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/2954864/manual.py.txt)

**Comment by mdhiggins** [comment]
So its right there
Your video stream is just being copied, not transcoded
Instead of using preopts/postopts to set your maxrate (which just gets ignored by FFMPEG when the codec is set to copy) and use the video-bitrate setting
You'll loose quality though just so you know any time you transcode. You're always better off downloading source material close to what you want and then remuxing whenever possible
