### ISSUE TITLE
Relatively new problem with Deluge

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#994]
For some reason over the last couple of months the script has been very hit and miss with deluge.
The only thing I have seen that's a common thing is the files that don't work always seem to have a silly little executable file in the folder thats is labeled "RARBG_DO_NOT_MIRROR.exe"

The ones that work, don't have this in their folders, not sure why this would happen but that's the only thing I can see that's different

**Comment by mdhiggins** [comment]
Any logging data on the failures? Those files should just be ignored if they aren’t in a format that matters like an EXE

**Comment by morpheus2n2** [comment]
> Any logging data on the failures? Those files should just be ignored if they aren’t in a format that matters like an EXE
> […](#)
> Sent from my iPhone
> On Mar 19, 2019, at 2:25 PM, morpheus2n2 ***@***.***> wrote: For some reason over the last couple of months the script has been very hit and miss with deluge. The only thing I have seen that's a common thing is the files that don't work always seem to have a silly little executable file in the folder thats is labeled "RARBG_DO_NOT_MIRROR.exe" The ones that work, don't have this in their folders, not sure why this would happen but that's the only thing I can see that's different — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Oh yeah lol sorry.

This is all that's popping up in the log :(

> 2019-03-17 12:24:18 - mkvtomp4 - INFO - D:\Downloads\To Convert\NCIS.New.Orleans.S05E16.Survivor.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]-convert\NCIS.New.Orleans.S05E16.Survivor.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mp4 created.
> 2019-03-17 12:24:18 - delugePostProcess - INFO - Passing D:\Downloads\To Convert\NCIS.New.Orleans.S05E16.Survivor.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]-convert directory to Sonarr.
> 2019-03-17 12:24:18 - autoprocess.sonarr - INFO - Sonarr notifier started.
> 2019-03-17 12:24:18 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\To Convert\NCIS.New.Orleans.S05E16.Survivor.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]-convert'.
> 2019-03-17 12:24:18 - autoprocess.sonarr - INFO - Sonarr response: queued.
> 2019-03-17 12:24:18 - delugePostProcess - ERROR - Unable to delete temporary directory.
> Traceback (most recent call last):
>   File "C:\Converter\delugePostProcess.py", line 142, in <module>
>     os.rmdir(delete_dir)
> WindowsError: [Error 145] The directory is not empty: 'D:\\Downloads\\To Convert\\NCIS.New.Orleans.S05E16.Survivor.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]-convert'

**Comment by mdhiggins** [comment]
That actually looks fairly promising. MP4 is created and sonarr responded appropriately with queued. Do the sonarr logs indicate a failure at some point further downstream? I’d say that looks like the deluge script worked without issue

**Comment by morpheus2n2** [comment]
Yeah that's the confusing part the log says its worked, yet no file is actually ever created, the CMD opens for about 1 min then closes when I look the original .mkv is there but no .mp4 is there or created.

As you can see from the Sonarr log nothing is there at all ( I am going my the event times)

> 19-3-17 12:09:00.9|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Deluge
> 
> [v3.0.1.411] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out
>    at System.Net.HttpWebRequest.GetResponse()
>    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 106
>    at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
>    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 121
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 57
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 240
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 266
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 212
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetTorrentsByLabel(String label, DelugeSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 96
>    at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 96
>    at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 90
> 
> 19-3-17 12:11:46.6|Info|RssSyncService|Starting RSS Sync
> 19-3-17 12:12:24.3|Info|DownloadDecisionMaker|Processing 508 releases
> 19-3-17 12:12:47.3|Info|RssSyncService|RSS Sync Completed. Reports found: 508, Reports grabbed: 0, Reports pending: 2
> 19-3-17 12:27:51.1|Info|RssSyncService|Starting RSS Sync
> 19-3-17 12:28:10.0|Info|DownloadDecisionMaker|Processing 507 releases
> 19-3-17 12:28:46.4|Info|RssSyncService|RSS Sync Completed. Reports found: 507, Reports grabbed: 0, Reports pending: 2
> 19-3-17 12:40:39.6|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Deluge
> 
> [v3.0.1.411] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out
>    at System.Net.HttpWebRequest.GetResponse()
>    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 106
>    at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
>    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 121
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 57
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 240
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 266
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 212
>    at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetTorrentsByLabel(String label, DelugeSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 96
>    at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 96
>    at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 90

**Comment by mdhiggins** [comment]
Are you using completed download handling in Sonarr in addition to delugePostProcess?

**Comment by morpheus2n2** [comment]
Nope

**Comment by mdhiggins** [comment]
It looks like Sonarr is having a hard time talking to deluge which has nothing to do with the script. I guess it must be working if the download starts but it also seems to be trying to look at Deluges status which it shouldn’t be doing

**Comment by morpheus2n2** [comment]
Yeah, but why would that stop the script from converting completely, I'm used to it randomly not sending over the odd finished conversion, but ever so often in the last I would say 2 months it will just flat out not run the script and convert the file.

And the only thing that any of these failed attempts have in common is the silly .exe file within there folders.

I have literally just finished a download of a film, that ran perfect lol

**Comment by mdhiggins** [comment]
I’m wondering if sonarr is deleting the files instead. The deluge script really doesn’t do any file deletion or cleanup, it leaves all that to sonarr and if the logs are showing the file getting created than it might be sonarr that is deleting stuff it shouldn’t for some reason. Though I’m not sure why

**Comment by morpheus2n2** [comment]
Ohhh I never thought of that, interesting. I'm going to clear all logs trigger a fresh download and see what pops up.

I'm on Sonarr V3 so could be a bug, if so I will follow it up the sonarr team :)

**Comment by mdhiggins** [comment]
If the logs aren’t revealing you could try triggering a known bad download from sonarr, let deluge start, then shutdown sonarr before the download finishes and see if all the files are still there in the deluge complete directory

**Comment by morpheus2n2** [comment]
Ok after much testing it is defo something to do with that .exe file.
Any download that has it within the folder will not even attempt to convert and due to it not even starting nothing is being logged properly.

But any download I have grabed where this .exe file is NOT present works perfect every single time. Even a 120gb download I have just pulled its currently converting perfect. :(

**Comment by mdhiggins** [comment]
That's very strange and shouldn't be something coming from my script. Does it appear to be something on Sonarr's end? Cause its normal for the script to encounter any number of file extensions and just ignore ones that's aren't on the included list so there's no reason an EXE being present should change anything unless for some reason sonarr is aborting things and never executing the script
