### ISSUE TITLE
[Enhancement] Request Detect Stacked Episodes for tagging

### ISSUE THREAD

**Issue by MrsAngelD** [mdhiggins/sickbeard_mp4_automator#997]
Sometimes episodes are stacked such as

XFiles - s01e01e02.mp4

would it be possible to detect such episodes and add the information to the media tag? As it stands right now only the tag information for the first episode is added.

**Comment by mdhiggins** [comment]
Not really. The metadata models for mp4's isn't designed for such things and doesn't have the flexibility to scale to multiepisode containers
