### ISSUE TITLE
Unable to change audio sample rates

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#998]
Trying to add -ar 44100 to post or pre opts is not working at all. 

I had a 96khz AAC LC audio stream that wouldn't play on plex at all, And it took me a while to figure out why it wouldn't work either. 

Is there a way to add a function to have the automator check for file sample rates and force a re sample for any sample rates that are not defined in the ini file?

Ex:

Sample-Rate: 44100,48000

**Comment by mdhiggins** [comment]
I'm guessing its not getting applied because you're copying the audio steams instead of specifying a codec. Script currently doesn't contain logic to override copy for specific sample rate but is something that could probably be added fairly easily

**Comment by JySzE** [comment]
no actually this was with attempting to change the aac lc stream to ac3 because I was thinking since it would copy the aac stream that argument wouldn't work.

**Comment by mdhiggins** [comment]
965fe0a3c6cfb6bd47c178fd9bd2ae6bafe399fd

Added

**Comment by JySzE** [comment]
Thank you
